weight_tickets table migration
transcom/mymove pull request #10055
Opened 2023-02-09 18:56 UTC by ruizajtruss

## [Jira ticket](https://dp3.atlassian.net/browse/MB-15158) for this change

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Setup to Run Your Code

<details>
<summary>💻 You will need to use three separate terminals to test this locally.</summary>

##### Terminal 1

Start the Storybook locally.

```sh
make storybook
```

##### Terminal 2

Start the UI locally.

```sh
make client_run
```

##### Terminal 3

Start the Go server locally.

```sh
make server_run
```

</details>

### Additional steps

1. Access the
2. Login as a
3.

## Verification Steps for Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Request review from a member of a different team.
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Frontend

- [ ] User facing changes have been reviewed by design.
- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/main/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
- [ ] There are no new console errors in the browser devtools
- [ ] There are no new console errors in the test output
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide#logging)
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide/#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#zero-downtime-migrations)
- [ ] Have been communicated to #g-database
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#secure-migrations)

## Screenshots

2023-02-16 15:40 UTC, mmayo-truss commented on migrations/app/migrations_manifest.txt
> +20230209174949_add_adjusted_net_weight_and_net_weight_remarks_to_weight_tickets_table.up.sql
Does it matter the order here, since the following line is already merged into main and applied to the stg migrations? I would assume this should be renamed to be added to the end.

2023-02-16 16:11 UTC, mmayo-truss commented on pkg/handlers/ghcapi/weight_ticket_test.go
> +			NetWeightRemarks:  "adjusted weight",
I think you can add both of these to the "Validate outgoing payload" section in lines 92-96

2023-02-16 16:22 UTC, mmayo-truss commented on pkg/handlers/internalapi/weight_ticket_test.go
> +			AdjustedNetWeight:        handlers.FmtInt64(3999),
I think these can get added to the validation check at the bottom of this test as well.

2023-02-16 16:36 UTC, mmayo-truss commented on pkg/services/weight_ticket/rules.go
> +			} else if newWeightTicket.NetWeightRemarks == nil || *newWeightTicket.NetWeightRemarks == "" {
Suggestion: I think this should be an `if` on its own, not `else if`. In the current condition if a weight ticket has a negative AdjustedNetWeight and no NetWeightRemarks, the only validation error that would get added is the "Adjusted net weight must be greater than zero" error.

2023-02-16 16:41 UTC, mmayo-truss commented on pkg/services/weight_ticket/rules.go
> +		if newWeightTicket.AdjustedNetWeight != nil {
Question: Should we also check if the new and the old adjusted weights match? Or will this only be filled if we are updating the adjusted net weight and will be nil when we are updating other fields?

2023-02-16 17:07 UTC, mmayo-truss commented on pkg/testdatagen/make_weight_ticket.go
> +	adjustedNetWeight := fullWeight - emptyWeight
Suggestion: I don't think you want to calculate the adjustedNetWeight here. This field is only if we want to have a number different from this calculation.

2023-02-16 17:12 UTC, mmayo-truss commented on pkg/testdatagen/make_weight_ticket.go
> +			AdjustedNetWeight:        &adjustedNetWeight,
Suggestion: I would leave these fields out here since they are optional and these fields will override the current calculation for the ppm shipment weight where we are subtracting full and empty weight for each weight ticket. 

If someone wants to create a weight ticket with an adjustedNetWeight and NetWeightRemarks, then they can pass those fields in the assertions.

OR, you could create a MakeWeightTicketWithAdjustedNetWeight function if that would be easier.

2023-02-16 17:21 UTC, mmayo-truss commented
Praise: I edited the adjusted net weight and the net weight remarks in the db for a weight ticket and was able to see the data on the front end! Noice!
![image](https://user-images.githubusercontent.com/110134470/219440454-a76a4793-f689-4495-a138-5e25dec5d8ad.png)

2023-02-16 17:23 UTC, mmayo-truss requested changes
This is looking good! I left a couple of questions and suggestions to look at.

2023-02-16 20:19 UTC, ruizajtruss commented on pkg/handlers/internalapi/weight_ticket_test.go
> +			AdjustedNetWeight:        handlers.FmtInt64(3999),
Nice catch, thanks - added! 🎉

2023-02-16 20:21 UTC, ruizajtruss commented on pkg/services/weight_ticket/rules.go
> +func verifyAdjustedNetWeightandNetWeightRemarksAreValid() weightTicketValidator {
Mine didn't catch that, good eye - fixed!

2023-02-16 20:31 UTC, ruizajtruss commented on pkg/services/weight_ticket/rules.go
> +			} else if newWeightTicket.NetWeightRemarks == nil || *newWeightTicket.NetWeightRemarks == "" {
That makes sense - change is made!

2023-02-16 20:39 UTC, ruizajtruss commented on pkg/services/weight_ticket/rules.go
> +		if newWeightTicket.AdjustedNetWeight != nil {
Don't think we have to check, this is only for updating the adjusted net weight

2023-02-16 20:56 UTC, ruizajtruss commented on pkg/testdatagen/make_weight_ticket.go
> +	adjustedNetWeight := fullWeight - emptyWeight
Yup! Meant to undo this and forgot 🤦

2023-02-16 21:51 UTC, mmayo-truss approved these changes
Great work @ruizajtruss ! 🏅 🚀

2023-02-17 17:04 UTC, kctruss approved these changes
🙌 Great job on this @ruizajtruss !!

2023-02-17 17:28 UTC, merged