MB-15167 - Add weight displays to review shipment weights
transcom/mymove pull request #10149
Opened 2023-02-24 22:41 UTC by michaelvaldes-truss

## [Jira ticket](https://dp3.atlassian.net/browse/MB-15167) for this change

## Summary

This PR should add weight displays to the review shipment weights page.

## Setup to Run Your Code

<details>
<summary>💻 You will need to use three separate terminals to test this locally.</summary>

##### Terminal 1

Start the Storybook locally.

```sh
make storybook
```

##### Terminal 2

Start the UI locally.

```sh
make client_run
```

##### Terminal 3

Start the Go server locally.

```sh
make server_run
```

</details>

### Additional steps

1. Access the office app as a services counselor
2. Navigate to a move
3. Navigate to the weights page by appending 'review-shipment-weights' to the url after the move code
4. Ensure that for moves with a risk of excess weight (e.g. move code RISKEX), there is a corresponding tag in the total estimated weight display.

## Verification Steps for Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Request review from a member of a different team.
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Frontend

- [ ] User facing changes have been reviewed by design.
- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/main/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
- [ ] There are no new console errors in the browser devtools
- [ ] There are no new console errors in the test output
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

## Screenshots
<img width="2526" alt="image" src="https://user-images.githubusercontent.com/97245917/221309961-93a4e843-1c65-4170-a2bb-399f628006e2.png">

2023-02-25 07:56 UTC, ruizajtruss commented on src/pages/Office/ServicesCounselingMoveInfo/ServicesCounselingMoveInfo.test.jsx
> +      },
**Praise:** Appreciate the re-ordering here!

2023-02-25 07:58 UTC, ruizajtruss requested changes
LGTM! 🚀  Just one question surrounding useCalculatedEstimatedWeight

2023-02-25 07:58 UTC, ruizajtruss commented on src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
> +  const estimatedWeightTotal = useCalculatedEstimatedWeight(mtoShipments);
**Question:** I wonder the same for the calculation here

2023-02-25 07:58 UTC, ruizajtruss commented on src/pages/Office/MoveDetails/MoveDetails.jsx
> +  const estimatedWeight = useCalculatedEstimatedWeight(mtoShipments);
**Question:** I'm curious if we should keep this calculation function within the useEffect on line 174 to ensure it runs on first render and every following update to the values in the dependency array

2023-02-25 07:58 UTC, ruizajtruss commented on src/hooks/custom.js
> +    return null;
**Praise:** Love the new approach here, saves us time incase none of the weights have the status we're looking for

2023-02-27 22:16 UTC, michaelvaldes-truss commented on src/pages/Office/MoveDetails/MoveDetails.jsx
> +  const estimatedWeight = useCalculatedEstimatedWeight(mtoShipments);
Good point -- I changed it back to useEffect in all the places where we were doing that previously.

2023-02-27 22:33 UTC, ruizajtruss approved these changes
Looks great! 🥳

2023-02-28 16:20 UTC, AnnaGingle commented
[_*I am unable to review this PR because of my OCONUS OOO but the platform team is working on that._ 

**The page is off to a great start but I see a couple of issues:**

- weightDisplay grid should fill the 960px container
- the 4 weightDisplay components should have a width of 222px
- Estimated weight (total) weightDisplay is larger than the others. The content should have a carriage return see [Figma](https://www.figma.com/file/5AhuEkaH3bJVrtffU3wp22/Milmove-Office-App?node-id=8643%3A100689&t=4DjUrz8HtrGNEN71-4)](https://github.com/transcom/mymove/pull/10149)

2023-03-03 21:24 UTC, ruizajtruss commented on src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
> +                  {externalVendorShipmentCount} shipment{externalVendorShipmentCount > 1 && 's'} not moved by GHC prime.{' '}
**Praise:** Clever touch!

2023-03-03 21:38 UTC, ruizajtruss approved these changes
LGTM 🚀

2023-03-03 21:49 UTC, AnnaGingle commented
The external vendor text should show in the estimated weight (total) weightDisplay if a move has a PPM because it is not moved by the GHC prime

2023-03-03 21:51 UTC, AnnaGingle requested changes
The external vendor text should show in the estimated weight (total) weightDisplay if a move has a PPM because it is not moved by the GHC prime
Figma link https://www.figma.com/file/5AhuEkaH3bJVrtffU3wp22/Milmove-Office-App?node-id=5689%3A80776&t=59vrz5pcygurBmyD-4

2023-03-03 22:19 UTC, AnnaGingle approved these changes
Great job!!!

2023-03-03 23:03 UTC, dinabeigelman approved these changes
pushing the approve button for @AnnaGingle

2023-03-03 23:05 UTC, merged