[MB-15057] Include actual delivery date in payload
transcom/mymove pull request #10189
Opened 2023-03-02 22:12 UTC by ruizajtruss

## [Jira ticket](https://dp3.atlassian.net/browse/MB-15057) for this change

## Summary

Service counselors need to be able to see the `actual delivery date` for mto shipments. The column was not previously included in the payload, but now it is 🥳 

## Setup to Run Your Code

<details>
<summary>💻 You will need to use three separate terminals to test this locally.</summary>

##### Terminal 1

Start the Storybook locally.

```sh
make storybook
```

##### Terminal 2

Start the UI locally.

```sh
make client_run
```

##### Terminal 3

Start the Go server locally.

```sh
make server_run
```

</details>

### Additional steps

1. Login as a services counselor
2. Select a move (`I selected Taylor III, Edgar - move code: #K7HWM9`)
3. Type in a date value into the `actual_delivery_date` column in the `mto_shipments` table for your selected move (If you selected the move mentioned above, you can find it under `id: "3d248abd-0565-4ec8-b54f-0cd48322946d"`)
4. Navigate to the network tab and select `mto_shipments`
5. The new field should be present 🎉 

## Verification Steps for Author

These are to be checked by the author.
- [x] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide#logging)
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide/#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#zero-downtime-migrations)
- [ ] Have been communicated to #g-database
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#secure-migrations)

## Screenshots
Before: 
![image](https://user-images.githubusercontent.com/111928238/222570576-ab644bf5-1abc-43a2-9630-011e67223079.png)

After 🎉 :
<img width="1252" alt="image (4)" src="https://user-images.githubusercontent.com/111928238/222570667-f7dd2f31-463d-4a18-a1c3-6b3c00e84d42.png">

2023-03-03 21:54 UTC, rogeruiz commented
hi @ruizajtruss, could you rebase your work on top of `main` or merge `main`
into your branch so it includes the new Go version 1.20.1 from #10185 rather
than the current version on this branch 1.19.3. Thanks. This will help me in
reviewing this and testing it locally.

2023-03-03 22:05 UTC, rogeruiz commented
I'm doing the merge locally too to see if any tests break. So if this passes
locally, you won't need to actually do the merge and I'll give my review. 🥳

2023-03-03 22:06 UTC, ruizajtruss commented
> I'm doing the merge locally too to see if any tests break. So if this passes locally, you won't need to actually do the merge and I'll give my review. 🥳

I just merged 😆

2023-03-03 22:16 UTC, rogeruiz requested changes
❌ This PR needs changes ...

Great work on this @ruizajtruss. I'm requesting changes to add a description from the comment in the database here to make it easier for folks reading the API documentation to understand what this property is for.

[➡️ Source for the comment on the database column.](https://github.com/transcom/mymove/blob/main/migrations/app/schema/20220901162926_add_scheduled_actual_delivery_dates.up.sql)

2023-03-03 22:16 UTC, rogeruiz commented on swagger-def/definitions/MTOShipment.yaml
> +    type: string
```suggestion
  actualDeliveryDate:
    x-nullable: true
    description: The actual date that the shipment was delivered to the destination address by the Prime
    format: date
    type: string
```

2023-03-03 22:18 UTC, rogeruiz commented
Just updating here that tests passed locally. So besides the small addition of a
description this is getting closer to getting merged in. 🎉

2023-03-03 22:44 UTC, ruizajtruss commented on swagger-def/definitions/MTOShipment.yaml
> +    type: string
Added! 🎉

2023-03-06 16:00 UTC, rogeruiz approved these changes
lgtm 🌈

2023-03-06 18:07 UTC, merged