[MB-15375] migration for removing net weight column from ppm shipments table
transcom/mymove pull request #10206
Opened 2023-03-06 20:19 UTC by ruizajtruss

## [Jira ticket](https://dp3.atlassian.net/browse/MB-15375) for this change

## Summary

Turns out the net weight column is an unused artifact from the days of yore and was causing a bit of confusion so its best we delete it.

## Setup to Run Your Code

<details>
<summary>💻 You will need to use three separate terminals to test this locally.</summary>

##### Terminal 1

Start the Storybook locally.

```sh
make storybook
```

##### Terminal 2

Start the UI locally.

```sh
make client_run
```

##### Terminal 3

Start the Go server locally.

```sh
make server_run
```

</details>

### Additional steps

1. Run make `db_dev_migrate`
2. Check the `ppm_shipments` table with your favorite db software and you should see the the column no longer exists on the table

## Verification Steps for Author

These are to be checked by the author.

- [x] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide#logging)
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide/#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#zero-downtime-migrations)
- [ ] Have been communicated to #g-database
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#secure-migrations)

2023-03-07 21:41 UTC, afoon commented
@mmayo-truss When a SC updates the `netWeight` on ppmShipment to reduce excess weight, what is value saved as?

2023-03-07 23:29 UTC, michaelvaldes-truss commented
> @mmayo-truss When a SC updates the `netWeight` on ppmShipment to reduce excess weight, what is value saved as?

@afoon @mmayo-truss  Is it saved as the `adjustedNetWeight` of the weight ticket(s)?

2023-03-08 16:13 UTC, afoon commented
> > @mmayo-truss When a SC updates the `netWeight` on ppmShipment to reduce excess weight, what is value saved as?
> 
> @afoon @mmayo-truss Is it saved as the `adjustedNetWeight` of the weight ticket(s)?

Yes that makes sense. Thank you for answering that.

2023-03-08 17:04 UTC, ruizajtruss commented
> > > @mmayo-truss When a SC updates the `netWeight` on ppmShipment to reduce excess weight, what is value saved as?
> > 
> > 
> > @afoon @mmayo-truss Is it saved as the `adjustedNetWeight` of the weight ticket(s)?
> 
> Yes that makes sense. Thank you for answering that.

Yep when the weight is adjusted to avoid excess weight warnings by an SC the value should be expected to be saved in the adjustedNetWeight column, that was the motivation behind removing this unused netWeight column because it makes things a bit confusing

2023-03-08 23:08 UTC, mmayo-truss commented on pkg/services/paperwork/form_creator_test.go
> -			NetWeight:           &netWeight,
Observation: I think this might have been on an old table that was archived. personally_procured_moves is a different table than the ppm_shipments table which you removed the net_weight field from.

2023-03-08 23:10 UTC, mmayo-truss commented
> > > > @mmayo-truss When a SC updates the `netWeight` on ppmShipment to reduce excess weight, what is value saved as?
> > > 
> > > 
> > > @afoon @mmayo-truss Is it saved as the `adjustedNetWeight` of the weight ticket(s)?
> > 
> > 
> > Yes that makes sense. Thank you for answering that.
> 
> Yep when the weight is adjusted to avoid excess weight warnings by an SC the value should be expected to be saved in the `adjustedNetWeight` column - this was the motivation behind removing the unused `netWeight` column because it makes things a bit confusing

just jumping in here to confirm exactly what @ruizajtruss and @michaelvaldes-truss said.

2023-03-08 23:14 UTC, ruizajtruss commented on pkg/services/paperwork/form_creator_test.go
> -			NetWeight:           &netWeight,
Yes it is, undoing now 🎉

2023-03-08 23:22 UTC, mmayo-truss requested changes
I am seeing references to ppm_shipments netweight on the front end, that I think you might want to look into. 

I am having trouble logging in locally, but I can see the ppm net weight referenced in the Prime UI: here is a screen shot and [here is a code point](https://github.com/transcom/mymove/blob/b42f5f1bb874d994c2de0df2f7c6a96eb9353c12/src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdatePPMForm.jsx#L97-L106)
![image](https://user-images.githubusercontent.com/110134470/223874505-fdfa9234-5ab0-4305-931e-5c2ed7c63c9c.png)

Net weight is also [part of the PPMShipmentShape](https://github.com/transcom/mymove/blob/6bda1bc9766abe26cc1a1b51276d56a314f16a1e/src/types/shipment.js#L37) and it could be removed there. 

There are a few more references to the net weight in the front end as well that I can help you look at if you'd like.

2023-03-09 22:25 UTC, ruizajtruss commented
> I am seeing references to ppm_shipments netweight on the front end, that I think you might want to look into.
> 
> I am having trouble logging in locally, but I can see the ppm net weight referenced in the Prime UI: here is a screen shot and [here is a code point](https://github.com/transcom/mymove/blob/b42f5f1bb874d994c2de0df2f7c6a96eb9353c12/src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdatePPMForm.jsx#L97-L106) ![image](https://user-images.githubusercontent.com/110134470/223874505-fdfa9234-5ab0-4305-931e-5c2ed7c63c9c.png)
> 
> Net weight is also [part of the PPMShipmentShape](https://github.com/transcom/mymove/blob/6bda1bc9766abe26cc1a1b51276d56a314f16a1e/src/types/shipment.js#L37) and it could be removed there.
> 
> There are a few more references to the net weight in the front end as well that I can help you look at if you'd like.

Recieved the go ahead to remove this from the PrimeUI 🎉

2023-03-10 00:28 UTC, rogeruiz approved these changes
lgtm 🌈

All these changes look straight forward. Thanks for the due diligence on this @ruizajtruss 

![bird delete this GIF by Skab](https://media0.giphy.com/media/xULW8N9O5WD32L5052/giphy.gif)

2023-03-10 15:20 UTC, AnnaGingle approved these changes

2023-03-10 15:30 UTC, mmayo-truss approved these changes
Changes look great @ruizajtruss Great work! Thanks for taking this on.

2023-03-10 16:35 UTC, merged