feat (make): add targets for deploying/reverting delpoys to non-ATO envs
transcom/mymove pull request #10234
Opened 2023-03-09 21:03 UTC by felipe-lee

## Summary

This came up as a nice-to-have improvement while testing out deployment failures. [First pass](https://github.com/transcom/mymove/pull/10183/commits/8abb9ececf9db10c28b0c912230b907baa886a1b) at this had used `:` as a separator. I switched it to `#` because I was testing a group regex, which didn't end up working, but at that point I didn't see a reason to switch back. Lmk if you think I should switch back to it though. The original version also was only for the `exp` env, but this version should work for the three non-ATO envs we can deploy to.

2023-03-09 22:06 UTC, rogeruiz requested changes
❌ This PR needs changes ...

Good work on updating this to support multiple environments, @felipe-lee. I have some suggestions for making this more ergonomic for everyone on the project.

2023-03-09 22:06 UTC, rogeruiz commented on Makefile
> +	sed -E -i '' "s#(&dp3-env) placeholder_env#\1 $(DEPLOY_ENV)#" .circleci/config.yml
```suggestion
	sed -E -i '' "s#(&dp3-env) placeholder_env#\1 $(DEPLOY_ENV)#" .circleci/config.yml
	@git diff .circleci/config.yml
	@echo "Please make sure to commit the changes in .circleci/config.yml in order to have CircleCI deploy $(GIT_BRANCH) to the Non-ATO $(DEPLOY_ENV) environment."
```

2023-03-09 22:06 UTC, rogeruiz commented on Makefile
> +	sed -E -i '' "s#(&dp3-env) placeholder_env#\1 $(DEPLOY_ENV)#" .circleci/config.yml
Let's add some more helpful output when these `sed` commands run so folks who don't read `sed` can understand what just happened and what their responsibilities are for deploying.

2023-03-09 22:08 UTC, rogeruiz commented
Once this is merged in, let's update the Confluence page which has folks manually doing these steps in their editors.

[=> Confluence page](https://dp3.atlassian.net/wiki/spaces/MT/pages/1470922798/How+to+deploy+to+Non-ATO+environments+Experimental+or+Demo+or+Loadtest+using+CircleCI#How-to-do-it) 🔒

2023-03-10 20:52 UTC, felipe-lee commented on Makefile
> +	sed -E -i '' "s#(&dp3-env) placeholder_env#\1 $(DEPLOY_ENV)#" .circleci/config.yml
@rogeruiz, I agree with most of the changes requested, but I feel like the git diff bit shouldn't be part of it. Everyone on the project uses git differently and some may not be aware of how to even get out of the pager. We could make it not use the pager though, and just output it to stdout like this:

```shell
@git --no-pager diff .circleci/config.yml
```

What do you think?

2023-03-11 00:59 UTC, rogeruiz commented on Makefile
> +	sed -E -i '' "s#(&dp3-env) placeholder_env#\1 $(DEPLOY_ENV)#" .circleci/config.yml
Great idea, let's have the `--no-pager`. I think this is a good balance. My original intention was to show the person using this what changed rather than just a bunch of `sed` commands.

2023-03-14 15:21 UTC, rogeruiz approved these changes
lgtm 🌈

2023-03-14 15:21 UTC, merged

2023-03-15 23:53 UTC, felipe-lee commented
> Once this is merged in, let's update the Confluence page which has folks manually doing these steps in their editors.
> 
> [=> Confluence page](https://dp3.atlassian.net/wiki/spaces/MT/pages/1470922798/How+to+deploy+to+Non-ATO+environments+Experimental+or+Demo+or+Loadtest+using+CircleCI#How-to-do-it) 🔒

@rogeruiz I made updates to [=> Confluence page](https://dp3.atlassian.net/wiki/spaces/MT/pages/1470922798/How+to+deploy+to+Non-ATO+environments+Experimental+or+Demo+or+Loadtest+using+CircleCI#How-to-do-it) 🔒. Lmk what you think, or feel free to make updates if you think something should be worded differently.