[MB-15173] Incorporate weights moved/weights moved by customer shipment list components to display shipment level weights
transcom/mymove pull request #10258
Opened 2023-03-14 22:02 UTC by afoon

## [Jira ticket](https://dp3.atlassian.net/browse/MB-15173) for this change

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Setup to Run Your Code

<details>
<summary>💻 You will need to use three separate terminals to test this locally.</summary>

##### Terminal 1

Start the UI locally.

```sh
make client_run
```

##### Terminal 2

Start the Go server locally.

```sh
make server_run
```

</details>

### Additional steps

1. Access the Office app as service counselor.
2. Navigate to `counseling/moves/XSWT05/review-shipment-weights/`
3. Shipment tables should be visible

## Screenshots
<img width="1490" alt="Screenshot 2023-03-14 at 3 53 38 PM" src="https://user-images.githubusercontent.com/28371460/225151287-712c1df8-f5a0-4e98-88ff-a6311f28b5eb.png">

2023-03-15 15:21 UTC, AnnaGingle requested changes
The shipment rows are highlighted blue on hover. This didn't happen in storybook. This gives the user the impression the shipment row is a button.

2023-03-16 17:27 UTC, AnnaGingle approved these changes
LGTM!

2023-03-16 19:12 UTC, michaelvaldes-truss approved these changes
Looks great! 🚀

2023-03-16 19:17 UTC, michaelvaldes-truss commented on src/components/Office/PPM/ReviewShipmentWeightsTable/ReviewShipmentWeightsTable.module.scss
> +      background-color: white;
**suggestion:** I think the linter is complaining about an extra space at the end of this line -- you might wanna just reformat the whole file in your editor though

2023-03-16 19:17 UTC, michaelvaldes-truss commented on src/components/Office/PPM/ReviewShipmentWeightsTable/ReviewShipmentWeightsTable.module.scss
> +
**suggestion (non-blocking):** you can remove the extra new line here

2023-03-16 20:35 UTC, merged