Clean up console errors.
transcom/mymove pull request #10542
Opened 2023-04-25 18:52 UTC by scottmries

## [Jira ticket](tbd) for this change

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Setup to Run Your Code

<details>
<summary>💻 You will need to use three separate terminals to test this locally.</summary>

##### Terminal 1

Start the Storybook locally.

```sh
make storybook
```

##### Terminal 2

Start the UI locally.

```sh
make client_run
```

##### Terminal 3

Start the Go server locally.

```sh
make server_run
```

</details>

### Additional steps

1. Access the
2. Login as a
3.

## Verification Steps for Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Request review from a member of a different team.
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Frontend

- [ ] User facing changes have been reviewed by design.
- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/main/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
- [ ] There are no new console errors in the browser devtools
- [ ] There are no new console errors in the test output
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide#logging)
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide/#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#zero-downtime-migrations)
- [ ] Have been communicated to #g-database
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#secure-migrations)

## Screenshots

2023-04-27 20:23 UTC, rileyorr commented
@scottmries the designs LGTM! However, the UI I saw on `SITEXT` and `PENDNG` were flipped. I wanted to call that out because I wanted to verify that what I'm seeing is correct for each move scenario. 

I've added screenshots of what I noticed with the move code included: 

**PENDNG**
<img width="1790" alt="Screenshot 2023-04-27 at 4 19 52 PM" src="https://user-images.githubusercontent.com/46329147/234982016-b240dbd0-a216-41bf-a501-b72472f9b9e3.png">

**SITEXT**
<img width="1790" alt="Screenshot 2023-04-27 at 4 20 24 PM" src="https://user-images.githubusercontent.com/46329147/234982021-15e780d0-c1e2-4ca3-909d-b5ff585a43fe.png">

2023-04-27 20:27 UTC, scottmries commented
@rileyorr Ah, good eye! I updated the comment.

2023-04-27 21:00 UTC, michaelvaldes-truss requested changes
Looks great! I added a few small comments, but the feature works overall 👍

2023-04-27 21:33 UTC, afoon approved these changes
Looks good. Just some questions and non-blocking questions

2023-04-27 21:33 UTC, afoon commented on src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.jsx
> +    const sitDaysUsed = moment(pastSITItem.sitDepartureDate).utc().diff(pastSITItem.sitEntryDate, 'days');
**question**: Why is `.utc()` needed here? I'm asking cause it was removed in the pass PR cause it was affecting the date math.

2023-04-27 21:33 UTC, afoon commented on src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.jsx
> +  const sitEndDateElement = <p>{formatDate(sitEndDate, utcDateFormat, 'DD MMM YYYY')}</p>;
The inclusion the `<p>` on the new date elements is affecting the styles.

2023-04-27 21:33 UTC, afoon commented on src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.jsx
> +  }
**quibble**: Could this work as one ternary?
```suggestion
const currentLocation = sitStatus?.location === LOCATION_TYPES.DESTINATION ? 'destination SIT' : 'origin SIT';
```

2023-04-28 13:05 UTC, rileyorr approved these changes
@scottmries thank you for confirming the scenarios and updating the comment! Everything LGTM

2023-04-28 16:27 UTC, scottmries commented on src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.jsx
> +  const sitEndDateElement = <p>{formatDate(sitEndDate, utcDateFormat, 'DD MMM YYYY')}</p>;
I removed it.

2023-04-28 16:27 UTC, scottmries commented on src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.jsx
> +    const sitDaysUsed = moment(pastSITItem.sitDepartureDate).utc().diff(pastSITItem.sitEntryDate, 'days');
I removed it.

2023-04-28 16:29 UTC, scottmries commented on src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.jsx
> +  }
Good point. I refactored.

2023-04-28 18:10 UTC, merged