[MB-15068] show fadd details received from ghc prime
transcom/mymove pull request #10540
Opened 2023-04-25 16:46 UTC by ruizajtruss

## [Jira ticket](https://dp3.atlassian.net/browse/MB-15068) for this change

## Summary

I verified that the data is properly handled both on the backend and frontend. The issue lied at the point in the go code where Domestic destination add'l SIT & Domestic destination SIT delivery are [being automatically generated](https://github.com/transcom/mymove/blob/f85a3203d6b3361da2d208036f7f23425aafa553/pkg/services/mto_service_item/mto_service_item_creator.go#L345). Once I identified that, I hardcoded some customer contact information and it displayed properly for the TOO! :fiesta_parrot: So that looks like it's good to go, I would appreciate some input on whether or not I should leave that hardcoded customer contact info in my PR since [this other ticket](https://dp3.atlassian.net/browse/MB-15533) handles setting up inputs for the Prime to submit their own information for these currently auto-generated fields, otherwise the PR is just going to be some front end refactoring I did to clean up the JSX that displays this information.

## Setup to Run Your Code

<details>
<summary>💻 You will need to use three separate terminals to test this locally.</summary>

##### Terminal 1

Start the Storybook locally.

```sh
make storybook
```

##### Terminal 2

Start the UI locally.

```sh
make client_run
```

##### Terminal 3

Start the Go server locally.

```sh
make server_run
```

</details>

### Additional steps

1. Access the `S1TT3R` move as a Prime user and submit a 
2. Login as a TOO and access the same move
3. Navigate to the move task order tab and you should see the information being displayed at the bottom of the page

## Verification Steps for Author

These are to be checked by the author.

- [x] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Frontend

- [ ] User facing changes have been reviewed by design.
- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/main/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
- [ ] There are no new console errors in the browser devtools
- [ ] There are no new console errors in the test output
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide#logging)
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide/#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#zero-downtime-migrations)
- [ ] Have been communicated to #g-database
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#secure-migrations)

## Screenshots

2023-04-25 21:11 UTC, AnnaGingle commented
Hey @ruizajtruss I find the A/C calls out the field like this

![Domestic destination SIT delivery](https://user-images.githubusercontent.com/48488699/234404847-bcb70ef2-4714-4dd2-a62d-fdfe2ff2931a.png)
 I don't see a review is requested anymore but I would have asked for changes.

2023-04-25 21:21 UTC, ruizajtruss commented
> Hey @ruizajtruss I find the A/C calls out the field like this
> 
> ![Domestic destination SIT delivery](https://user-images.githubusercontent.com/48488699/234404847-bcb70ef2-4714-4dd2-a62d-fdfe2ff2931a.png) I don't see a review is requested anymore but I would have asked for changes.

Yes, moved back to draft for some changes but I appreciate your comment. That screenshot looks different from what was listed in my ticket; so thank you for the clarification!

2023-04-27 19:08 UTC, AnnaGingle approved these changes
LGTM

2023-04-27 20:17 UTC, afoon submitted a review, later dismissed
Looking good so far. Just a few changes to make sure the AC is met.

2023-04-27 20:17 UTC, afoon commented on src/components/Office/ServiceItemDetails/ServiceItemDetails.jsx
> +                'Available delivery date 1':
**todo:** The AC for the ticket has the text as:
```suggestion
                'First available delivery date 1':
```

2023-04-27 21:16 UTC, ruizajtruss commented on src/components/Office/ServiceItemDetails/ServiceItemDetails.jsx
> +                'Customer contact 1':
@afoon I believe the ticket may have been out of date as @AnnaGingle shared a screenshot which motivated these label changes https://github.com/transcom/mymove/pull/10540#issuecomment-1522422967

2023-04-27 21:17 UTC, michaelvaldes-truss requested changes

2023-04-27 21:17 UTC, michaelvaldes-truss commented on pkg/services/mto_service_item/mto_service_item_creator.go
> +	var extraServiceItem models.MTOServiceItem
suggestion: is it possible to skip this if/else condition entirely and just copy the CustomerContacts like we copy most of the other fields? 

```suggestion
		extraServiceItem := models.MTOServiceItem{
		MTOShipmentID:   firstSIT.MTOShipmentID,
		MoveTaskOrderID: firstSIT.MoveTaskOrderID,
		ReServiceID:     reService.ID,
		ReService:       reService,
		SITEntryDate:    firstSIT.SITEntryDate,
		SITPostalCode:   firstSIT.SITPostalCode,
		Reason:          firstSIT.Reason,
		Status:          models.MTOServiceItemStatusSubmitted,
		CustomerContacts: firstSIT.CustomerContacts,
	}
```

2023-04-27 21:54 UTC, ruizajtruss commented on pkg/services/mto_service_item/mto_service_item_creator.go
> +	var extraServiceItem models.MTOServiceItem
@michaelvaldes-truss My motivation behind the if/else block is two fold. 

- I initially tried out your suggested change as it seemed like the most straight forward approach but when you try to submit a DDFSIT as a Prime user you are met with a 500 error. From what I understand, this is because it is adding unexpected fields when the only fields `CustomerContacts` is expecting is ` Type`, `FirstAvailableDeliveryDate`, and `TimeMilitary`. That's the story behind this block of code:
```
 CustomerContacts: []models.MTOServiceItemCustomerContact{
      {
	     Type:                       models.CustomerContactTypeFirst,
	     FirstAvailableDeliveryDate: firstSIT.CustomerContacts[0].FirstAvailableDeliveryDate,
	     TimeMilitary:               firstSIT.CustomerContacts[0].TimeMilitary,
      },
      {
	     Type:                       models.CustomerContactTypeSecond,
	     FirstAvailableDeliveryDate: firstSIT.CustomerContacts[1].FirstAvailableDeliveryDate,
	     TimeMilitary:               firstSIT.CustomerContacts[1].TimeMilitary,
      },
 },
```

- That resolved our 500 error but if you tried running the command `make db_dev_fresh` you would be met with the below error. so I included the if/else statement to account for that.
```
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0
```


Open to suggestions if you have a better approach

2023-04-27 23:32 UTC, michaelvaldes-truss commented on pkg/services/mto_service_item/mto_service_item_creator.go
> +	var extraServiceItem models.MTOServiceItem
I gotcha! Here's what I suspect is happening:

If you just set the customer contacts directly as in
`CustomerContacts: firstSIT.CustomerContacts,`
the extra service item shares the same exact customer contacts as the original service item, including their db ids. 
When the `mto_service_item_creator` creates each extra service item, it probably tries to explicitly create a new customer contact and runs into a duplicate table id problem.

The way you wrote it actually creates a new customer contact struct without an ID, and so the `mto_service_item_creator` has no problem creating a new customer contact with a new ID and the same Type, FADD, and Time.

If this is the case, then we probably want to ask the following question: should these service items 
a) explicitly share the same customer contact in the database, or 
b) should they have different customer contacts with the same data (at least upon creation)?

If the answer is a) then we should update the `mto_service_item_creator` to not break when saving a customer contact that already exists.
If the answer is b) then we might want to create a helper function like `copyCustomerContact` that does pretty much exactly what you have now, so that we can call it and not have to reference specific indices of the customerContacts array.

2023-04-28 23:06 UTC, ruizajtruss commented on pkg/services/mto_service_item/mto_service_item_creator.go
> +	var extraServiceItem models.MTOServiceItem
After conferring with @donaldthai during our 1:1, came to the conclusion the answer is b so I created a helper function to copy the contacts over without relying on indices to keep things flexible 🎉

2023-05-01 21:03 UTC, michaelvaldes-truss approved these changes
lgtm! that helper function is _clean_ 🤌

2023-05-01 21:08 UTC, michaelvaldes-truss commented on pkg/services/mto_service_item/mto_service_item_creator.go
> +	//If we have contacts copy them over, otherwise we will return an empty slice
**nitpick:** In the case of `customerContacts` being empty, I think that this might actually return nil instead of an empty slice.

2023-05-01 23:04 UTC, merged