[MB-14975] Change calculation for total # days remaining
transcom/mymove pull request #10581
Opened 2023-05-01 18:54 UTC by afoon

## [Jira ticket](https://dp3.atlassian.net/browse/MB-14975)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

- [ ] Calculates the # “Total days remaining” from Today’s calendar date and the Expiration Date. 
- [ ] If the total days remaining calculates to be <0 days, then reflect “Expired” 
- [ ] If the total days remaining calculates to be =0 days, then reflect “0 days remaining” (eg: If today’s date = Feb 28 and the Expiration Date = Feb 28)
- [ ] Calculated values and Updated labels are reflected on both the SIT Dashboard and the Edit Module

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/run-storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/about/application-setup/milmove-local-client/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/about/development/testing)

### How to test

1. Access the Office app
2. Login as a TOO
3. Navigate to `moves/SITEXT/mto`
4. Click edit and change the end date to today's date and save the changes.
    - [ ] Remaining days should be 0
5.  Click edit and change total approved days to `59` days and save the changes.
   - [ ] Remaining days should be `Expired`

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/about/supported-browsers) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

## Screenshots

2023-05-01 21:59 UTC, afoon commented
There was an issue where the wrong end dat was showing up. I subtracted `1` day to account for the difference where needed.

2023-05-01 22:20 UTC, afoon commented
There is one bug with the history. If there is a re-render or a data fetch that happens on the page, the total approved days calculations will be incorrect since the total numbers are calculate from the `approvedDays` which is a difference in days from the last `approvedDays` value.. I'm not sure how likely that situation will happen. But wanted to note it.

https://user-images.githubusercontent.com/28371460/235541483-940d4064-d89c-403d-8b43-5f3834f5ba37.mov

2023-05-02 17:45 UTC, AnnaGingle approved these changes
The total days remaining is working great! Thanks

2023-05-03 16:16 UTC, ruizajtruss requested changes

2023-05-03 16:16 UTC, ruizajtruss commented on src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.test.jsx
> -          sitStatus={{ ...SITStatusDestination, totalDaysRemaining: -1 }}
Note: I think this was supposed to stay as `-1` so that the `Expired` text pops up

2023-05-03 16:16 UTC, ruizajtruss commented on src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.jsx
> +  };
Question: Since we have this exact function both in this file and in `ShipmentSITDisplay.jsx` starting on line 111; might it be better if we just break this function out as util?

2023-05-03 16:17 UTC, ruizajtruss commented on src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.test.jsx
> -          sitStatus={{ ...SITStatusDestination, totalDaysRemaining: -1 }}
Resolving this since I think you already fixed it 🎉

2023-05-03 16:24 UTC, ruizajtruss requested changes
Looks good so far and I noticed you already fixed some of the issues that arose from the merge conflicts 🎉  Just a couple of small comments

2023-05-03 16:24 UTC, ruizajtruss commented on src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.test.jsx
> +import { debug } from 'jest-preview';
Might want to remove this

2023-05-03 16:24 UTC, ruizajtruss commented on src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.test.jsx
> +    debug();
Might want to remove this too

2023-05-03 17:55 UTC, ruizajtruss approved these changes
LGTM! 🎉

2023-05-03 20:35 UTC, merged