[ MB-16029 ] Allow editing SIT for any status SIT
transcom/mymove pull request #10640
Opened 2023-05-11 16:56 UTC by rogeruiz

## [Jira ticket](https://dp3.atlassian.net/browse/MB-16029)

## Summary

This patch fixes `sitStatus` values returned by the server so that TOOs can edit
both active and inactive SIT service items. This is currently a **Draft** and is
considered a work-in-progress for now.

<!--
## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/run-storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/about/application-setup/milmove-local-client/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/about/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/about/supported-browsers) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/about/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2023-05-12 20:44 UTC, michaelvaldes-truss requested changes
There are a few things that might need to be updated, but otherwise this is a slick solution to a tricky problem 👍

2023-05-12 20:44 UTC, michaelvaldes-truss commented on pkg/services/mto_shipment/shipment_sit_status.go
> +				currentSIT = &shipment.MTOServiceItems[i]
Ah, so we're treating future sit as if it's current sit, nice!

2023-05-12 20:44 UTC, michaelvaldes-truss commented on pkg/testdatagen/scenario/shared.go
> +	factory.BuildMTOServiceItem(db, []factory.Customization{
Nice fix to the test data -- all three sit service items must initially be created together.

2023-05-12 20:44 UTC, michaelvaldes-truss commented on src/components/Office/ReviewSITExtensionModal/ReviewSITExtensionModal.jsx
> +    sitEndDate: formatDateForDatePicker(moment(sitStartDate).add(sitStatus.totalDaysRemaining - 1, 'days')),
**suggestion:** This fixes the end date calculation for future sit, but it might break it for current sit; current sit should still be `today + totalDaysRemaining -1`

2023-05-12 20:44 UTC, michaelvaldes-truss commented on src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.jsx
> +    ? moment(sitStartDate)
**suggestion:** This fixes the end date calculation for future sit, but it might break it for current sit; current sit should still be today + totalDaysRemaining -1

2023-05-12 20:44 UTC, michaelvaldes-truss commented on src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.jsx
> +    sitEndDate: formatDateForDatePicker(moment(sitStartDate).add(sitStatus.totalDaysRemaining - 1, 'days')),
**suggestion:** same as before, this fixes the end date calculation for future sit, but it might break it for current sit; current sit end date should still be today + totalDaysRemaining -1

2023-05-12 20:44 UTC, michaelvaldes-truss commented on Makefile
> +	dlv debug -l 127.0.0.1:38697 --headless cmd/milmove/*.go -- serve 2>&1 | tee -a log/dev.log
**question:** was this update intentional?

2023-05-15 13:57 UTC, rogeruiz commented
Thanks for the feedback @michaelvaldes-truss. I'll address the concerns in some commits today.

2023-05-15 13:59 UTC, rogeruiz commented on Makefile
> +	dlv debug -l 127.0.0.1:38697 --headless cmd/milmove/*.go -- serve 2>&1 | tee -a log/dev.log
Yes, this is old code that doesn't work anymore. So I'm updating this target in case folks want to run `dlv debug` rather than attaching to the running `make server_run` process. We could also remove the whole `make server_run_debug` target.

2023-05-15 21:04 UTC, rogeruiz commented on src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.jsx
> +    ? moment(sitStartDate)
Strange this seems to be working okay? I have a SitStatus with 30 days in SIT with total SIT days used both to be 30 and the total days remaining is still 60. This lines up with what the function is trying to do. I'm not sure if we have another bug here or not.

2023-06-01 21:56 UTC, donaldthai reviewed
Looking pretty good so far! I left some comments/suggestions. I also was running into the issue that @michaelvaldes-truss brought up about current SIT end date is off.

2023-06-01 21:56 UTC, donaldthai commented on src/components/Office/ReviewSITExtensionModal/ReviewSITExtensionModal.jsx
> +    sitEndDate: formatDateForDatePicker(calculateSitStartDate.add(sitStatus.totalDaysRemaining - 1, 'days')),
issue: So @michaelvaldes-truss mentioned this earlier but I'm also running into an issue where the `calculatedSitStartDate` is using an earlier date when I think it could be using "today's date" for a shipment that is currently in SIT.

suggestion: In the case of a current SIT, we could potentially add another another case for the `calculateSitStartDate` to consider current SIT.

Screenshot:
<img width="1534" alt="image" src="https://github.com/transcom/mymove/assets/1522549/e97d34ae-0cec-4d1f-ae38-72c8c758e970">

2023-06-02 15:38 UTC, rogeruiz commented on src/components/Office/ReviewSITExtensionModal/ReviewSITExtensionModal.jsx
> +  }
I agree. I was using Moment as it's already being used in multiple places here. I wanted to avoid the work of the refactor to get this bug finished.

2023-06-02 15:49 UTC, donaldthai commented on src/components/Office/ReviewSITExtensionModal/ReviewSITExtensionModal.jsx
> +  }
Yeah, no worries! I was just noting it here for informational reference.

2023-06-23 15:51 UTC, rogeruiz commented
Closing this as the work has been transferred over to #10916.

2023-06-23 15:51 UTC, closed without merging