[MB-15876] Prime API endpoint to create a SIT address change request
transcom/mymove pull request #10649
Opened 2023-05-12 08:04 UTC by ruizajtruss

## [Jira ticket](tbd)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/run-storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/about/application-setup/milmove-local-client/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/about/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/about/supported-browsers) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/about/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2023-05-23 18:39 UTC, michaelvaldes-truss requested changes
This is looking great so far! There are a _lot_ of changes and everything is really well organized and tested! I just left a few suggestions which are mostly superficial.

2023-05-23 18:39 UTC, michaelvaldes-truss commented on pkg/models/mto_service_items.go
> +func FetchServiceItem(db *pop.Connection, serviceItemID uuid.UUID) (MTOServiceItem, error) {
**suggestion:** it seems like all the places where this function is used and would be useful, we're using it for a sitAddressUpdate. Would it make more sense to just make the `MTOServiceItem` subfield of the `SITAddressUpdate` in the function `FetchSITAddressUpdate` and fetch the service item that way, instead of making separate calls?

2023-05-23 18:39 UTC, michaelvaldes-truss commented on pkg/services/sit_address_update.go
> +// ApprovedSITAddressUpdateCreator Interface for the service object that creates a approved SIT Address Update with a distance < 50 miles
```suggestion
// ApprovedSITAddressUpdateCreator Interface for the service object that creates an approved SIT Address Update
```
This function can be used to create an update with a distance > 50 miles if the TOO creates it.

2023-05-23 18:39 UTC, michaelvaldes-truss commented on pkg/services/sit_address_update/rules.go
> +			verrs.Add("MTOServiceItem", "A SIT address update already exists for this service item")
**nitpick:**
```suggestion
			verrs.Add("MTOServiceItem", "A pending SIT address update already exists for this service item")
```

2023-05-23 18:39 UTC, michaelvaldes-truss commented on pkg/services/sit_address_update/rules.go
> +		var existingSITAddressUpdate models.SITAddressUpdate
**suggestion:** can we move this check to a separate function since it's not technically checking the presence of required fields?

2023-05-23 19:26 UTC, mlm55 commented on pkg/handlers/primeapi/payloads/model_to_payload.go
> +		NewAddressID:      strfmt.UUID(sitAddressUpdate.NewAddressID.String()),
Suggestion: it might be more meaningful to return the actual address rather than the id

2023-05-23 19:31 UTC, mlm55 commented on pkg/services/sit_address_update/sit_address_update_request_approver.go
> +type sitAddressUpdateRequestApprover struct {
suggestion: would it be worth matching the naming scheme of the `approvedSITAddressUpdateCreator`? if so, we could change `approvedSITAddressUpdateCreator` to `approvedSITAddressUpdateRequestCreator` too if that's easier

2023-05-24 07:17 UTC, ruizajtruss commented on pkg/models/mto_service_items.go
> +func FetchServiceItem(db *pop.Connection, serviceItemID uuid.UUID) (MTOServiceItem, error) {
I feel that by keeping them separate, it makes things easier in terms of debugging and overall maintenance/flexibility. It may be the case now that we are using it mostly for `SITAddressUpdate` but they could still come in handy down the line for other uses. 

There's also a couple places where each function is being used individually where we are only interested in that specific piece of data and not everything else. Take for example `CreateSITAddressUpdateRequest` where we only fetch the service item and aren't fetching a sit address update. 

There's a similar case in a couple of tests where we're checking specific items and don't need to pull much else. For example `TestApproveSITAddressUpdateRequest` where we only fetch the address update to check its values.

2023-05-24 07:36 UTC, ruizajtruss commented on pkg/handlers/primeapi/payloads/model_to_payload.go
> +		NewAddressID:      strfmt.UUID(sitAddressUpdate.NewAddressID.String()),
I figured since the client already knows the address since they submitted it, returning the newly created resources seemed like it made most sense which is why I went with just returning the ID and the status. 

Granted, as I type this I realize that my logic fails me considering the remarks are returned 🤣 

Totally open to returning the actual address though if that better suits the Prime's needs! 🎉  Don't think returning the whole service item is needed however.

2023-05-24 17:16 UTC, michaelvaldes-truss requested changes
One last suggestion!

2023-05-24 17:16 UTC, michaelvaldes-truss commented on pkg/services/sit_address_update/sit_address_update_request_creator.go
> +		sitAddressUpdateRequest.Distance, err = f.planner.TransitDistance(txnAppCtx, &sitAddressUpdateRequest.OldAddress, &sitAddressUpdateRequest.NewAddress)
**suggestion:** the distance should actually be calculated between the new address and the `mto_service_item.SITDestinationInitialAddress`
We might need to update any service and test that has the wrong calculation, like the `approved_sit_address_update_creator`
```suggestion
		sitAddressUpdateRequest.Distance, err = f.planner.TransitDistance(txnAppCtx, serviceItem.SITDestinationOriginalAddress, &sitAddressUpdateRequest.NewAddress)
```

2023-05-24 17:39 UTC, ruizajtruss commented on pkg/services/sit_address_update/sit_address_update_request_creator.go
> +		sitAddressUpdateRequest.Distance, err = f.planner.TransitDistance(txnAppCtx, &sitAddressUpdateRequest.OldAddress, &sitAddressUpdateRequest.NewAddress)
Right before this portion of the code, the old address is set to the current final address since that's the most up to date address:
`sitAddressUpdateRequest.OldAddressID = *serviceItem.SITDestinationFinalAddressID
sitAddressUpdateRequest.OldAddress = *serviceItem.SITDestinationFinalAddress`

Isn't the calculation supposed to be based off the most recent final address? If I understand correctly, the final address matches the initial address unless it's been updated at some point.

If this isn't the case we might want to look at this [PR as well again](https://github.com/transcom/mymove/pull/10698) on [this line](https://github.com/transcom/mymove/blob/c85087590bc217f14e7d4141740964c595d45abb/pkg/services/sit_address_update/approved_sit_address_update_creator.go#L59)

2023-05-24 17:47 UTC, michaelvaldes-truss commented on pkg/services/sit_address_update/sit_address_update_request_creator.go
> +		sitAddressUpdateRequest.Distance, err = f.planner.TransitDistance(txnAppCtx, &sitAddressUpdateRequest.OldAddress, &sitAddressUpdateRequest.NewAddress)
Yep -- the OldAddress is being set properly, but the distance calculation should always be made between the new address and the _initial_ address, which can be different from the old address if a previous address update has already been submitted. 
The [tech spec](https://dp3.atlassian.net/wiki/spaces/MT/pages/2090336310/Technical+Spec+SIT+Service+Items) mentions this, but it's kind of subtle 😅 
The other service created in that PR, the `approved_sit_address_update_creator`, should be updated as well.

2023-05-24 17:51 UTC, ruizajtruss commented on pkg/services/sit_address_update/sit_address_update_request_creator.go
> +		sitAddressUpdateRequest.Distance, err = f.planner.TransitDistance(txnAppCtx, &sitAddressUpdateRequest.OldAddress, &sitAddressUpdateRequest.NewAddress)
Thanks for the link, I see what you're talking about! I'll make the changes 🎉

2023-05-24 18:34 UTC, michaelvaldes-truss approved these changes
lgtm! Great stuff, this PR is a _lot_

2023-05-26 12:58 UTC, merged