[MB-15883] [FE] Create/reuse modal to edit the SIT address for the SIT service item
transcom/mymove pull request #10648
Opened 2023-05-11 21:41 UTC by afoon

## [Jira ticket](tbd)

## Summary

This PR implements the frontend for [MB-15797 - TOO can create/set SIT address change](https://dp3.atlassian.net/browse/MB-15797)

>**Note**
>This **DOES NOT** implement the functionality with the server, i.e save save changes. The focus here is creating the component to the design spec.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers
- [ ] Clicking on “Edit” link in the “Approved service item” section will display a modal to Edit SIT delivery address
- [ ] Matches the [designs](https://www.figma.com/file/5AhuEkaH3bJVrtffU3wp22/Milmove-Office-App?type=design&node-id=11287-118005&t=o7cKNmt0kH2rxxWY-0) , particularly: 
  - [ ] HHG blue label is displayed at top left corner
  - [ ] Title of modal is Edit service item
   - [ ] SIT delivery address in a white section
   - [ ] Initial SIT delivery address
   - [ ] Address Form
       - [ ] Distance warning
       - [ ] Address 1
       - [ ] Address 2 (optional)
       - [ ] City
       - [ ] State
       - [ ] ZIP
  - [ ] Office remarks
  - [ ] Save button
  - [ ] Cancel button
  - [ ] Grayed out if address and office remarks are empty
  - [ ] Closes the modal when cancel, x, or background is clicked
 - [ ] Has unit test

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/run-storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/about/application-setup/milmove-local-client/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/about/development/testing)

### How to test

1. Access the Office App
2. Login as a TOO
3. Navigate to `{insert-move-here}`
>**Note**
> WIP

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/about/supported-browsers) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

## Screenshots

>**Note**
> WIP

2023-05-24 03:48 UTC, afoon commented on src/components/Office/ServiceItemUpdateModal/ServiceItemUpdateModal.jsx
> +    officeRemarks: Yup.string().required('Required'),
Usually this is nullable but the backend requires the remarks to complete the request. If  we want TOOs to be able to leave this blank, a change will need to be made there.

2023-05-24 15:31 UTC, AnnaGingle requested changes
- Address formatted incorrectly
- Office Remarks field should be 136px in height
- Missing border & additional padding around Final SIT delivery content

![Anna's private board - 10648](https://github.com/transcom/mymove/assets/48488699/043ebc6c-80ff-4c61-98e7-7aca023d8370)

2023-05-24 15:33 UTC, rogeruiz commented
thanks @AnnaGingle I'll take a look at this feedback and have a new version for you to review shortly.

2023-05-24 19:01 UTC, AnnaGingle approved these changes
Great work!

2023-05-24 19:57 UTC, afoon commented on src/utils/shipmentDisplay.jsx
> +    </address>
@rogeruiz This style change is affecting a few other places that also use formatAddress. It's breaking some test and happo renderings. @AnnaGingle can you confirm the changes in spacing seen in the Happo renderings are fine? I've added an example of on the visual changes.
<img width="865" alt="Screenshot 2023-05-24 at 3 56 55 PM" src="https://github.com/transcom/mymove/assets/28371460/4b253254-cc0d-4862-8149-5e32e480190b">

2023-05-24 20:14 UTC, rogeruiz submitted a review, later dismissed
lgtm 🌈

2023-05-24 20:20 UTC, rogeruiz commented on src/utils/shipmentDisplay.jsx
> +    </address>
@AnnaGingle I'm going to update this PR to make this not a breaking visual change across the other components that @afoon mentioned here.

2023-05-25 14:21 UTC, rogeruiz commented on src/utils/shipmentDisplay.jsx
> +    </address>
This was fixed in https://github.com/transcom/mymove/pull/10648/commits/68021b0905ada00fa620b1aca45d7f823037ab82

2023-05-25 17:02 UTC, rogeruiz approved these changes
lgtm 🌈

2023-05-26 15:30 UTC, donaldthai commented
@Mergifyio update

2023-05-26 18:44 UTC, merged