MB-15874: show edit/review requests link, yellow alert and yellow tag for SIT address change request
transcom/mymove pull request #10688
Opened 2023-05-17 21:50 UTC by StuTruss

## [Jira ticket](https://dp3.atlassian.net/browse/MB-15874)

## Summary

This PR implements the designs shown [here](https://www.figma.com/file/5AhuEkaH3bJVrtffU3wp22/Milmove-Office-App?node-id=10509-115679&t=he6qPm8lP6yYnK7c-4)

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers
- [ ] Link In Approved service item section: 
  - [ ] "Edit" link if there are no SIT address changes
  - [ ] "Review request" link if there are SIT address change requests
 - [ ] Yellow notification on MTO page: "Service item update requested. Review request below."
 - [ ] Yellow status label on MTO page Approved Service Item section: "UPDATE REQUESTED"
 - [ ] Has unit test

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/run-storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/about/application-setup/milmove-local-client/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/about/development/testing)

### How to test

1. Access `http://officelocal:3000/testharness/list` and scroll down to button that says `HHGMoveInSITWithAddressChangeRequestOver50Miles` then click it. 
2. Copy value of `locator` field
3. Access the Office App
4. Login as a TOO
5. Navigate to move with value of `locator` field you copied earlier
6. Click `Move task order` tab

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/about/supported-browsers) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

## Screenshots
Yellow notification saying "Service Item update requested. Review request below"
<img width="1726" alt="Screenshot 2023-05-17 at 2 48 57 PM" src="https://github.com/transcom/mymove/assets/111077497/dda24ba2-65ce-4c16-aef0-f8e2495d97ca">

Yellow status label saying "UPDATE REQUESTED"
<img width="963" alt="Screenshot 2023-05-17 at 2 49 12 PM" src="https://github.com/transcom/mymove/assets/111077497/7ca1114f-0962-46f9-831c-de20370709b3">

2023-05-18 18:55 UTC, afoon requested changes
LGTM. The unit test for `MoveTaskOrder.jsx` needs to be updated to test for the new alert and new variable that can affect notification count. `ServiceItemTable.jsx` needs a unit test for the new Edit button.

2023-05-18 19:35 UTC, michaelvaldes-truss requested changes
Left a few suggestions, but this is looking really great so far!
One more thing to note: pending @AnnaGingle 's judgement, we might also need to increment the "move task order" tab tag at the top, similar to how we're incrementing the shipment tag on the left in this PR.

2023-05-18 19:35 UTC, michaelvaldes-truss commented on src/shared/constants.js
> +export const SIT_ADDRESS_UPDATE_STATUS = {
**suggestion:** constants/sitUpdates.js might also be a good place to store information about which service items can have address updates in the first place (DDDSIT, which is defined in src/content/serviceItems.js)

2023-05-18 19:35 UTC, michaelvaldes-truss commented on src/components/Office/ServiceItemsTable/ServiceItemsTable.jsx
> +                    {sitAddressUpdates && hasSITAddressUpdate(sitAddressUpdates) ? 'Review Request' : 'Edit'}
**suggestion:** as @afoon pointed out on slack, we only want this button to appear for DDDSIT service items

2023-05-18 20:50 UTC, AnnaGingle requested changes
- Only the Domestic destination SIT delivery service item should have an Edit/Review button
- MTO top nav should have a Yellow tag like the MTO sidenav
- I need this test move to have risk of excess weight so I can confirm the alerts play nice.
- (not apart of this work but documenting because i don't see it in other jira stories). The move should have a 'Approvals requested' status. Right now it shows move approve. TOOs work on a first in first out basis. They would never think to click on this move otherwise.

2023-05-19 00:21 UTC, StuTruss commented
@AnnaGingle this is currently how the two alerts look on the page when they are both shown together.
<img width="1725" alt="Screenshot 2023-05-18 at 5 20 20 PM" src="https://github.com/transcom/mymove/assets/111077497/a9c8d7ee-a9e0-4184-83ca-d5783d4db893">

2023-05-19 18:12 UTC, AnnaGingle commented
> @AnnaGingle this is currently how the two alerts look on the page when they are both shown together. <img alt="Screenshot 2023-05-18 at 5 20 20 PM" width="1725" src="https://user-images.githubusercontent.com/111077497/239406443-a9c8d7ee-a9e0-4184-83ca-d5783d4db893.png">
The new alert should match the excess weight alert. Not sure why they are different sizes.

2023-05-19 18:42 UTC, afoon commented on src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
> +            <Alert type="warning" headingLevel="h4" className={styles.alertWithButton}>
```suggestion
            <Alert type="warning"  className={styles.alertWithButton}>
```
removing the heading level should fix the sizing.

2023-05-19 19:12 UTC, afoon approved these changes
Outside of the design changes requested, this LGTM.

2023-05-19 20:46 UTC, StuTruss commented
@AnnaGingle Made the alert slim and added a close btn to it
<img width="1728" alt="Screenshot 2023-05-19 at 1 29 35 PM" src="https://github.com/transcom/mymove/assets/111077497/73d2ddda-3b6c-48e6-9f12-c0d7ab7efede">

2023-05-19 20:54 UTC, michaelvaldes-truss approved these changes
Lgtm! Thanks for all your work on this, there was a lot of minutia to handle 🥇

2023-05-19 21:06 UTC, AnnaGingle requested changes
- The top nav MTO tag is not working as expected ([link to video](https://ustcdp3.slack.com/archives/CTNTFJSBA/p1684529911844029?thread_ts=1684527876.902239&cid=CTNTFJSBA))
- The service item tag should be ABOVE the service item title ([link to picture & designs](https://ustcdp3.sla
![Screenshot 2023-05-19 at 3 59 46 PM](https://github.com/transcom/mymove/assets/48488699/00b2cab7-1d8b-4e6f-b419-6031cf5acceb)
ck.com/archives/CTNTFJSBA/p1684530170684859?thr

Uploading Screen Recording 2023-05-19 at 3.56.43 PM.mov…

ead_ts=1684527876.902239&cid=CTNTFJSBA))

2023-05-22 16:37 UTC, AnnaGingle approved these changes
Great work! Approved!

2023-05-22 18:16 UTC, merged