MB-15796: TOO can view review request service item update modal
transcom/mymove pull request #10728
Opened 2023-05-22 21:01 UTC by StuTruss

## [Jira ticket](https://dp3.atlassian.net/browse/MB-15796)

## Summary

This PR uses the customizable modal @afoon create [here](https://github.com/transcom/mymove/pull/10648) to create a preliminary modal that shows the `HHG` tag as well as the title `Review request: service item update` because of @afoon changes, the service item details portion is already included even though that was not a part of the AC of the original ticket.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers
- [ ] HHG Label is displayed in top left corner: 
- [x] Title of modal is `Review request: service item update`
- [ ] Has unit tests

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/run-storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/about/application-setup/milmove-local-client/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/about/development/testing)

### How to test

1. Access `http://officelocal:3000/testharness/list` and scroll down to button that says `HHGMoveInSITWithAddressChangeRequestOver50Miles` then click it. 
2. Copy value of `locator` field
3. Access the Office App
4. Login as a TOO
5. Navigate to move with value of `locator` field you copied earlier
6. Click `Move task order` tab
7. Scroll down to `Review Request` button in approved service items portion and click it

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/about/supported-browsers) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

## Screenshots
Review Request Modal
<img width="865" alt="Screenshot 2023-05-22 at 1 42 36 PM" src="https://github.com/transcom/mymove/assets/111077497/769e8e24-c304-469e-88b2-6cde017a4871">

2023-05-22 21:45 UTC, AnnaGingle commented
The review modal looks good but I am not able to check the edit modal because the functionality isn't in place yet.

2023-05-22 21:55 UTC, afoon requested changes
This is missing the form element where the TOO can approve or reject the Request depicted in the designs. `ServiceItemUpdateModal` accepts the form as a child.
<img width="653" alt="Screenshot 2023-05-22 at 5 48 34 PM" src="https://github.com/transcom/mymove/assets/28371460/936d0b10-7ba4-42aa-b86c-502a34afc403">

2023-05-22 21:58 UTC, StuTruss commented
@afoon @AnnaGingle maybe I'm misunderstanding the ticket? Because in the implementation notes it says that this ticket should not include the SIT Address Information nor anything about the edit modal.

2023-05-22 22:09 UTC, afoon commented
@StuTruss The A/C is confusing me as well. I'm not sure why this story has less A/Cs than the Edit Address Form which also includes the form and functionality.

2023-05-23 13:56 UTC, AnnaGingle requested changes
The alert & number tags should not be visible when there is not an active request from the Prime


https://github.com/transcom/mymove/assets/48488699/c6037b68-86ff-4314-a785-afaa7b83d550

2023-05-24 07:54 UTC, afoon requested changes
I'm going to hold off on reviewing `MoveTaskOrder.jsx` and `ServiceItemsTable.jsx` until the most recent changes from the base branch are pulled into this PR. Some new patterns were introduced that will affect your work.

But I did want to flag reverting the label changes in ServiceItemDetails. I added more context below.

2023-05-24 07:54 UTC, afoon commented on src/components/Office/ServiceItemDetails/ServiceItemDetails.jsx
> +                  'Available delivery date 2':
Same revert here.
 ```suggestion
                  'First available delivery date 2':
```

2023-05-24 15:41 UTC, AnnaGingle requested changes
- Office Remarks field should be 136px in height
- Missing border & additional padding around Final SIT delivery content
- Missing UPDATE REQUESTED tag
![Anna's private board - 10728](https://github.com/transcom/mymove/assets/48488699/eeb5a69a-7cef-4b88-94e8-3e88060cadad)

2023-05-24 22:22 UTC, afoon commented
I changed the base branch to make it easier to see what changes were made just on this PR. When the Edit Address Modal PR is merge into main, Github will automatically base it back to main again.

Additionally, if ReviewRequestServiceItem work is complete before Edit Modal is ready to merge, we can merge the ReviewRequestModal changes into Edit Address Modal branch. Then changes for both PRs will be merged into main at the same time.

cc: @rogeruiz @StuTruss @donaldthai

2023-05-25 13:30 UTC, AnnaGingle submitted a review, later dismissed
Change 'Final SIT delivery' label to 'Final SIT delivery address'
Designs: 
![Edit SIT destination address change - onClick](https://github.com/transcom/mymove/assets/48488699/b5318e35-1714-43b2-b0d7-51167bf88eff)

2023-05-25 13:42 UTC, AnnaGingle approved these changes
Great work team!

2023-05-25 20:02 UTC, rogeruiz approved these changes
lgtm 🌈

Good work on this @StuTruss.

2023-05-26 17:07 UTC, rogeruiz commented
I've gotten confused by the two PRs, so I'm going to merge this into @afoon's PR so I'm working from a single branch.

2023-05-26 17:07 UTC, merged