[ MB-16199 ] Ensure service items have an origin and final destination address
transcom/mymove pull request #10806
Opened 2023-06-01 23:59 UTC by rogeruiz

- Refactoring NewMTOServiceItemUpdater;
- Making the function signatures more legible;

## [Click here for the Jira ticket](https://dp3.atlassian.net/browse/MB-16199)

## Summary

The goal of this patch is to have `DDDSIT` service items create a destination
origin address. This will allow for the address change calculations introduced
in #10649 and will help unblock other user stories as well.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/run-storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/about/application-setup/milmove-local-client/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/about/development/testing)

### How to test

_More information on how to properly test this manually coming soon..._

2023-06-06 21:25 UTC, rogeruiz commented
Currently, this does not include any changes around adding the SIT Final Destination Address in the Create MTO Service Item request. We will need to add this if tomorrow's meeting determines we should.

2023-06-07 17:29 UTC, ronaktruss commented on pkg/services/mto_service_item/mto_service_item_updater.go
> +		}
So far I have just read the code and most of it looks good at a high level. You may run into an issue where the serviceItem.SITDestinationFinalAddress is always nil. The serviceItem is being fetched and defined by the `findServiceItem` function in this file which doesn't eagerPreload the address information.

2023-06-07 17:30 UTC, rogeruiz commented on pkg/services/mto_service_item/mto_service_item_updater.go
> +		}
ah thank you! I'll refactor this.

2023-06-08 20:01 UTC, michaelvaldes-truss requested changes
This looks great so far, and it works on my machine 🎉 

**One additional suggestion:** can we update the scenarios that create approved DDDSIT service items in pkg/testdatagen/testharness/make_move.go to include the required Original Address?

2023-06-08 20:46 UTC, donaldthai requested changes
Looking good so far. Added some comments!

2023-06-08 20:46 UTC, donaldthai commented on pkg/services/mto_service_item/mto_service_item_updater.go
> +		"MTOServiceItems.SITDestinationFinalAddress",
Issue: Trying to approve/reject the SIT service item and I'm getting an error from this eager preload string. We typically just need the property name to load it in the struct.

Suggestion: I think we could just remove the `MTOServiceItems.` part to resolve the issue.

2023-06-08 21:10 UTC, rogeruiz commented on pkg/services/mto_service_item/mto_service_item_updater.go
> +		"MTOServiceItems.SITDestinationFinalAddress",
```suggestion
		"SITDestinationFinalAddress",
```

2023-06-09 15:01 UTC, rogeruiz commented
Okay, I've refactored based on the feedback I received here. Thanks folks.

2023-06-09 19:03 UTC, donaldthai commented
@Mergifyio update

2023-06-09 21:20 UTC, ronaktruss commented
Functionally this looks good to me. I tested the scenario where the prime provides a final destination address and when they don't. I didn't test the scenario where there isn't a shipment destination (I think there's another ticket to populate this).

2023-06-09 21:42 UTC, donaldthai commented
@Mergifyio update

2023-06-12 17:59 UTC, michaelvaldes-truss approved these changes
Lgtm -- approving a destination SIT ensures that the Original Address field is populated appropriately.
I don't want to delay this PR any longer since it's currently blocking acceptance testing, but can we update the scenarios that create approved DDDSIT service items in pkg/testdatagen/testharness/make_move.go to include the required Original Address?
This would ensure that our testharness scenarios are functional for SIT address update testing.

2023-06-12 21:53 UTC, merged

2023-06-12 21:53 UTC, rogeruiz commented
I'll update our test scenarios after this gets merged in on a separate PR.

2023-06-12 22:09 UTC, rogeruiz commented
https://github.com/transcom/mymove/pull/10880