MB-9411 Switch SFTP Connection to use private key refactor
transcom/mymove pull request #10898
Opened 2023-06-14 23:09 UTC by YanZ777

## [Jira ticket](https://dp3.atlassian.net/browse/MB-9411)

## Summary

The ticket is for actually swapping over to use a private key connection for GEX sftp. I wanted to do a small refactor first, so that I only need to update the key in one place. 

refactor: Reuse the cli package to reduce the number of places environment variables are being read. Adjust tests so that they aren't testing to check if every single environment variable is available.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/run-storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/about/application-setup/milmove-local-client/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/about/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/about/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

2023-08-08 17:41 UTC, duncan-truss commented
@YanZ777 This is the part called by the process_edis command that will also need to be converted to use key based auth:

https://github.com/transcom/mymove/blob/f408e7229eced6d70c8b93e52c85ea48478055fe/pkg/cli/gex_sftp.go#L111-L117

2023-08-08 17:43 UTC, YanZ777 commented
> @YanZ777 This is the part called by the process_edis command that will also need to be converted to use key based auth:
> 
> https://github.com/transcom/mymove/blob/f408e7229eced6d70c8b93e52c85ea48478055fe/cmd/milmove-tasks/process_edis.go#L225
> 
> https://github.com/transcom/mymove/blob/f408e7229eced6d70c8b93e52c85ea48478055fe/pkg/cli/gex_sftp.go#L111-L117

Yes, this PR is a refactor. I'm opening another PR that actually swaps it over to key based auth.

2023-08-10 20:04 UTC, ahobson reviewed
Nice work!

2023-08-10 20:04 UTC, ahobson commented on cmd/milmove-tasks/connect_to_gex_via_sftp.go
> +	awssession "github.com/aws/aws-sdk-go/aws/session"
We just merged in the changes to use the [v2 aws sdk](https://github.com/transcom/mymove/pull/11019) and I think you'll need to make some updates here. I can help if you need it

2023-08-10 20:04 UTC, ahobson commented on pkg/cli/cli_test.go
> +}
I think this functionality is provided by testify already https://pkg.go.dev/github.com/stretchr/testify/require ?

2023-08-10 20:50 UTC, YanZ777 commented on Dockerfile.local_ssh_test
> +# Sample sftp / ssh server to test key based authentication
I'd be ok with adding more documentation instead of a Dockerfile. I'll take this Dockerfile out of this PR then if that's the case and open a separate PR for documentation.

2023-08-11 03:10 UTC, YanZ777 commented on Dockerfile.local_ssh_test
> +# Sample sftp / ssh server to test key based authentication
Ok for the life of me, I could not figure out how to configure public key access from a file. I can do it from a string using the PUBLIC_KEY option and I can manually add it, but the PUBLIC_KEY_FILE option wasn't working for me for whatever reason. 😞 

I want folks to be able to configure whatever public key they wanted, so I'd prefer not to hardset one using the PUBLIC_KEY option.
I'll add steps in the documentation so that folks can configure the public key whichever way they wish with whatever public key they generate.

2023-08-11 12:56 UTC, ahobson commented on Dockerfile.local_ssh_test
> +# Sample sftp / ssh server to test key based authentication
This process worked for me:

```
mkdir -p ssh
ssh-keygen -f ssh/testgex
docker run --rm \
  --name sshd \
  -v ./ssh:/myssh \
  -e PUBLIC_KEY_FILE=/myssh/testgex.pub \
  -e USER_NAME=testu \
  -p 2222:2222 \
  linuxserver/openssh-server
```

Then, in another window
```
sftp -i ssh/testgex  -P 2222 testu@localhost
```

2023-08-11 13:06 UTC, ahobson commented on cmd/milmove-tasks/connect_to_gex_via_sftp.go
> +	dbConnection, err := cli.InitDatabase(v, logger)
It seems like maybe the only reason you establish a database connection is to create an AppContext so that later on you can use the logger. Would it make sense to change `cli.InitGEXSFTP` so it takes a `*zap.Logger` as an argument instead of an AppContext?

2023-08-11 13:06 UTC, ahobson commented on pkg/services/invoice/syncada_sftp_sender.go
> +		appCtx.Logger().Fatal("couldn't initialize SSH client", zap.Error(err))
This is a bit of a style question and so there's not necessarily a straightforward answer, but ...

To me, if the function returns an `error`, I would think it is the caller's responsibility to handler the error and panic/quit/retry whatever. Or, if the function is going to itself exit (by calling `Fatal`), then I wouldn't expect it to return an `error`.

I think using `Fatal` should be restricted to command line interfaces, not services that could be called multiple callers, including ones that don't want to immediately die on error.

2023-08-11 14:41 UTC, duncan-truss commented on pkg/services/invoice/syncada_sftp_sender.go
> +		appCtx.Logger().Fatal("couldn't initialize SSH client", zap.Error(err))
It may not change the suggestion but I do believe this is only run from our hourly scheduled task, even though this part of the code is in our pkg/services.  I think you can trigger a submission to GEX through our support API (but not the retrieving from SFTP parts) but that hits different files in this package FWIW.

2023-08-11 18:15 UTC, YanZ777 commented on Dockerfile.local_ssh_test
> +# Sample sftp / ssh server to test key based authentication
That's weird. I tried that as well and it doesn't work for me.
Based off the code that they have in their [init-openssh-server-config](https://github.com/linuxserver/docker-openssh-server/blob/193deedbc2c1f1eb67457c113dd58ea89c7d2e7c/root/etc/s6-overlay/s6-rc.d/init-openssh-server-config/run#L93) folder, I would expect to see a message that says "Public key from file added", but I don't get that at all. Also, when I check the /config/.ssh/authorized_keys, the public key isn't added there either.

2023-08-11 18:25 UTC, ahobson commented on Dockerfile.local_ssh_test
> +# Sample sftp / ssh server to test key based authentication
Are you sure you are mounting the volumes? Is your docker set up to allow mounting volumes from where you are?

<img width="260" alt="image" src="https://github.com/transcom/mymove/assets/21983/e921ac4f-ad35-4e1b-822e-88856a8b33d9">

I see ...
```
sshd is listening on port 2222
User/password ssh access is disabled.
Public key from file added
```

2023-08-11 22:10 UTC, YanZ777 commented on cmd/milmove-tasks/connect_to_gex_via_sftp.go
> +	dbConnection, err := cli.InitDatabase(v, logger)
I think the changes were a little bit bigger than I wanted to put in to this PR, so I split those changes off into #11202

2023-08-11 22:16 UTC, YanZ777 commented on pkg/services/invoice/syncada_sftp_sender.go
> +		appCtx.Logger().Fatal("couldn't initialize SSH client", zap.Error(err))
I agree with you here. I've switched it over to use `appCtx.Logger().Error` instead. I also saw some instances of `appCtx.Logger().Fatal` inside of `pkg/handlers/supportapi/payment_request.go`, so I changed those as well.

2023-08-14 12:40 UTC, ahobson requested changes

2023-08-14 12:40 UTC, ahobson commented on pkg/handlers/supportapi/payment_request.go
> +					appCtx.Logger().Error("couldn't initialize SSH client", zap.Error(err))
Don't you need to return the error here and in the other similar situations below?

2023-08-14 12:40 UTC, ahobson commented on pkg/services/invoice/syncada_sftp_sender.go
> +		appCtx.Logger().Error("couldn't initialize SSH client", zap.Error(err))
I believe you also need to return the error here and in similar situations below

2023-08-14 18:56 UTC, ahobson approved these changes
Wonderful!

2023-08-14 19:02 UTC, merged