[MB-16348] backend adding date of contact for service items
transcom/mymove pull request #10917
Opened 2023-06-16 21:03 UTC by ruizajtruss

## [Jira ticket](https://dp3.atlassian.net/browse/MB-16348)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/run-storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/about/application-setup/milmove-local-client/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/about/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/about/supported-browsers) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/about/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2023-06-21 16:08 UTC, mmayo-truss commented on swagger-def/definitions/MTOServiceItemCustomerContact.yaml
> +    description: Date of attempted delivery by the prime.
This is confusing to me. I thought that this was the date that they contacted the customer. This implies that it was an attempt to move the customer's items.

2023-06-21 16:11 UTC, mmayo-truss commented on swagger-def/definitions/MTOServiceItemCustomerContact.yaml
> +    description: Time of attempted delivery by the prime.
Similarly, if the TimeMilitary field corresponds to the dateOfContact this should be the time that the prime contacted the customer.

2023-06-21 16:13 UTC, mmayo-truss commented on swagger-def/prime.yaml
> +            * If provided, `timeMilitary1` & `dateOfContact1` is required.
With three fields required together, I think that it would be clearer to have a bullet that says something like: `timeMilitary1, dateOfContact1, and firstAvailableDeliveryDate1 are required together` and then another one for the 2 fields.

2023-06-21 16:22 UTC, ruizajtruss commented on swagger-def/definitions/MTOServiceItemCustomerContact.yaml
> +    description: Date of attempted delivery by the prime.
I believe they are essentially one in the same from what I was told - but I'm going through now to update the language and make it more consistent by changing `delivery` to `contact` along with a few others I just noticed I missed

2023-06-21 20:33 UTC, mlm55 reviewed
I was able to make the request via postman, but I wasn't able to get the prime simulator to work (it doesn't look like it was sending the firstAvailableDeliveryDates in the payload). Other than that, the code looks good. 

I agree with @mmayo-truss's suggestion about having a bullet indicating that timeMilitary1, dateOfContact1, and firstAvailableDeliveryDate1 are required together, but i do appreciate the helpful error message when `firstAvailableDeliveryDate1` was absent!

2023-06-21 21:37 UTC, ruizajtruss commented
> I was able to make the request via postman, but I wasn't able to get the prime simulator to work (it doesn't look like it was sending the firstAvailableDeliveryDates in the payload). Other than that, the code looks good.
> 
> I agree with @mmayo-truss's suggestion about having a bullet indicating that timeMilitary1, dateOfContact1, and firstAvailableDeliveryDate1 are required together, but i do appreciate the helpful error message when `firstAvailableDeliveryDate1` was absent!

The prime ui issue might be local - I just double checked and appears to still be working. Made the update to the language though! 🎉

2023-06-21 22:43 UTC, donaldthai requested changes

2023-06-21 22:43 UTC, donaldthai commented on migrations/app/schema/20230614231637_add_date_of_contact_column_to_mto_service_item_customer_contacts_table.up.sql
Suggestion: Let's test this on `exp` to double check this works. There's a possibility that If the new column is not nullable then I think the migration will fail due to existing data not having the column filled in. 

I think we may need to modify a few other columns too based on the new understanding of the customer contacts.

**We should verify this with product.** From how I understand these columns should be:
1. `date_of_contact` is optional since it's possible the prime has not yet contacted the customer
2. `time_military` is optional since this is associated to the new `date_of_contact` column
3.  `time_military` comments could be updated to say that the column is associated to the `date_of_contact` column

2023-06-21 23:36 UTC, ruizajtruss commented on migrations/app/schema/20230614231637_add_date_of_contact_column_to_mto_service_item_customer_contacts_table.up.sql
Done! 🎉

2023-06-22 14:53 UTC, donaldthai commented on migrations/app/schema/20230614231637_add_date_of_contact_column_to_mto_service_item_customer_contacts_table.up.sql
@ruizajtruss let's also test on `exp`! We usually test on there for any new migrations.

2023-06-23 21:41 UTC, donaldthai approved these changes
The DB looks good to me! Exp migration passed and tested locally this works!

Note: Make sure to revert the exp commit

2023-06-23 22:02 UTC, ruizajtruss commented
Verified in experimental:
![image](https://github.com/transcom/mymove/assets/111928238/d9d28e61-d094-4dc1-a262-b5c3dc43db3e)

2023-06-26 17:39 UTC, mmayo-truss commented on swagger-def/prime.yaml
> +            description: Time of delivery corresponding to `dateOfContact1`, in military format.
@ruizajtruss Should this be `dateOfContact2`?

2023-06-26 18:19 UTC, mmayo-truss commented on swagger-def/prime.yaml
> +            * Time of attempted contact corresponding to `firstAvailableDeliveryDate2`, in military format.
```suggestion
            * Time of attempted contact corresponding to `dateOfContact2`, in military format.
```

2023-06-26 18:19 UTC, mmayo-truss commented on swagger-def/prime.yaml
> +            description: Date of attempted contact by the prime corresponding to 'timeMilitary1'.
```suggestion
            description: Date of attempted contact by the prime corresponding to `timeMilitary1`.
```

2023-06-26 18:20 UTC, mmayo-truss commented on swagger-def/prime.yaml
> +            description: Date of attempted contact by the prime corresponding to 'timeMilitary2'.
```suggestion
            description: Date of attempted contact by the prime corresponding to `timeMilitary2`.
```

2023-06-26 18:30 UTC, mmayo-truss approved these changes
@ruizajtruss Thank you for making the changes to the wording. I think it is more clear now. 

I suggested some minor changes to the prime api documentation, for clarity and consistency. But they are not blocking.

I appreciate your effort in coordinating across teams in this PR. Good work!

2023-06-26 21:04 UTC, merged