update FE to account for new dateOfContact field
transcom/mymove pull request #10932
Opened 2023-06-20 21:27 UTC by StuTruss

## [Jira ticket](https://dp3.atlassian.net/browse/MB-16348)

## Summary

The purpose of this PR is to show the new date of contact field in the service items details section alongside the `timeMilitary` field. Also updates how we render `First available dates` and `customer contact attempts` to account for the case where there may be more than 2 of each. 

Check out [this slack thread if you would like extra context](https://ustcdp3.slack.com/archives/CTNTFJSBA/p1686772959097629)

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/run-storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/about/application-setup/milmove-local-client/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/about/development/testing)

### How to test

1. Run `make server_test`
2. All tests should pass
3. Create a new customer `HHG` move and move it along the system to make it available to the prime
4. Login into to the Prime UI and access your newly created move
5. Click the `Add Service Item` button
6. Scroll down to the form and select `Destination SIT` from the `Service item type` dropdown
7. The `date of attempted contact` field should be present - select a date, complete the form, and submit
8. It should now be reflected in the `mto_service_item_customer_contacts` table if you check your DB
9. You can also access the move as a `TOO` and check the move task order tab to check the service items section 

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/about/supported-browsers) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/about/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots
Service Item Section
<img width="963" alt="Screenshot 2023-06-20 at 2 22 00 PM" src="https://github.com/transcom/mymove/assets/111077497/82dd514b-8ec4-4735-a5be-d12eb21b99c7">

2023-06-21 16:07 UTC, ruizajtruss approved these changes
Code is clean and straightforward, LGTM 🚀  Thanks for working on this!

2023-06-21 16:14 UTC, afoon commented on src/components/Office/ServiceItemDetails/ServiceItemDetails.jsx
> +      ]);
**suggestion**: Can we add some comments or JSdoc to explain what is going on here? I can see this being confusing for engineers not familiar with lodash.

2023-06-26 19:47 UTC, AnnaGingle commented
First available delivery date 1 & Customer contact attempt 1 go together 
First available delivery date 1 & Customer contact attempt 1 are required but additional iterations are not (2,3,4)
![SIT service items](https://github.com/transcom/mymove/assets/48488699/23f4db08-028b-4b15-a2f0-2644b935ee18)

2023-06-26 19:47 UTC, AnnaGingle requested changes
First available delivery date 1 & Customer contact attempt 1 go together
First available delivery date 1 & Customer contact attempt 1 are required but additional iterations are not (2,3,4)
![SIT service items](https://github.com/transcom/mymove/assets/48488699/c7a0cf26-7a4e-4105-b9e4-7a99893a991a)

2023-06-27 17:04 UTC, StuTruss commented
@ruizajtruss @donaldthai could we get some clarity on what is expected here? It was my understanding that we wanted to change the FE to account for multiple `First available delivery date` as well as having `first available delivery date` & `customer contact` go together.

2023-06-27 17:05 UTC, StuTruss commented
> @ruizajtruss @donaldthai could we get some clarity on what is expected here? It was my understanding that we wanted to change the FE to account for multiple `First available delivery date` as well as having `first available delivery date` & `customer contact` go together.

for context this was the image i received as far as what was the intended outcome of this PR 
![image](https://github.com/transcom/mymove/assets/111077497/92fc80c0-ce3a-49ee-b02e-641da36203ea)

2023-06-27 17:08 UTC, AnnaGingle commented
@StuTruss There was an issue with updating our design system components. I can confirm this is [the expected design](https://www.figma.com/file/5AhuEkaH3bJVrtffU3wp22/Milmove-Office-App?type=design&node-id=13645-139219&mode=design&t=DqO0W3z7WbX0F8b5-4). Sorry for the confusion.
![SIT service items](https://github.com/transcom/mymove/assets/48488699/ee83d9e4-5c46-47cb-ab3e-75a49880527f)

2023-06-27 17:13 UTC, AnnaGingle commented
This is what I am seeing in the PR
![Screenshot 2023-06-27 at 12 12 30 PM](https://github.com/transcom/mymove/assets/48488699/ef92bb75-8439-41b1-8db2-d12de3d958c0)

2023-06-27 17:37 UTC, StuTruss commented
thanks for the clarification! @AnnaGingle

2023-06-27 18:11 UTC, StuTruss commented
> This is what I am seeing in the PR ![Screenshot 2023-06-27 at 12 12 30 PM](https://user-images.githubusercontent.com/48488699/249231193-ef92bb75-8439-41b1-8db2-d12de3d958c0.png)

@AnnaGingle is this how it should look if there is no available date or customer contact? 
<img width="960" alt="Screenshot 2023-06-27 at 11 11 21 AM" src="https://github.com/transcom/mymove/assets/111077497/f0682680-4543-4411-948c-26fd29d8ae5b">

2023-06-27 19:44 UTC, AnnaGingle commented
@StuTruss The empty states look right. We use the - dash.
![Screenshot 2023-06-27 at 2 43 01 PM](https://github.com/transcom/mymove/assets/48488699/b0d5a9fd-caf6-470e-86d4-72ef81000a1b)


Also, is there a testharness move with this info for me to check? I redeployed the PR & still am not seeing these fields.

2023-06-28 14:34 UTC, AnnaGingle commented
I may have spoken too soon. Im checking the Happo report & the new time format isn't tracking here.
![Screenshot 2023-06-28 at 9 33 11 AM](https://github.com/transcom/mymove/assets/48488699/a3c78475-d69c-485a-9fa3-081ef00641e3)
![Screenshot 2023-06-28 at 9 34 08 AM](https://github.com/transcom/mymove/assets/48488699/c051c9da-0978-431d-ae26-6aaa2c1358a5)

2023-06-28 15:43 UTC, AnnaGingle approved these changes
Approved! Thanks for your patience. I will follow up on the time format for the modal.

2023-06-29 00:05 UTC, merged