[MB-16267] Show destination address change request alerts to TOO
transcom/mymove pull request #11023
Opened 2023-07-07 21:56 UTC by SirenaBorracha

## [Jira ticket](https://dp3.atlassian.net/browse/MB-16267)

## Summary

This PR adds notifications to the Office app that alert the TOO that the Prime has submitted a destination change request for an approved shipment. 

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/run-storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/about/application-setup/milmove-local-client/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/about/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/about/supported-browsers) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/about/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2023-07-13 20:54 UTC, PDickeyTruss commented on src/components/LeftNav/LeftNav.stories.jsx
> +    <LeftNav sections={['requested-shipments', 'orders', 'allowances', 'customer-info']}>
I think we will want to revert this change, it is causing the happo diff error ☺️

2023-07-13 20:55 UTC, PDickeyTruss commented on src/components/Office/ShipmentDetails/ShipmentDetails.jsx
> +        shipment={shipment} // when combined with Patrick's work this shipment will have the new data which we will check against to determine whether or not to show the alert
Probably can remove this comment now

2023-07-14 16:10 UTC, PDickeyTruss commented on src/components/LeftNav/LeftNav.stories.jsx
> +    <LeftNav sections={['requested-shipments', 'orders', 'allowances', 'customer-info']}>
Fixed

2023-07-14 16:10 UTC, PDickeyTruss commented on src/components/Office/ShipmentDetails/ShipmentDetails.jsx
> +        shipment={shipment} // when combined with Patrick's work this shipment will have the new data which we will check against to determine whether or not to show the alert
Fixed

2023-07-14 20:20 UTC, AnnaGingle commented
Noting for others. When at /testharness/list you will want to create a new move using the new button titled 'HHGMoveWithAddressChangeRequest'.

2023-07-14 20:33 UTC, AnnaGingle requested changes
Great work! Everything is ask expected except some color styles need fixing. 
- The Shipment card's 'Review required' text is Error / #d63e04 when it should be #B50909 / Error text.
- The Shipment card's 'Destination address' vertical accent line should be Error / #d63e04. It is currently #B50909 / Error text.

2023-07-17 15:51 UTC, PDickeyTruss commented
Interesting, we did not add any new UI here (or new colors), just made use of the existing field error functionality/styling. I took a look around this morning and the new red Destination address border and text color match what we use throughout the app for the same kind of field errors. We could of course make this one-off error text/border a different color than we use elsewhere but I suspect we would prefer consistency?

<img width="1384" alt="Screenshot 2023-07-17 at 7 49 42 AM" src="https://github.com/transcom/mymove/assets/62263329/7dc49fa6-8cfa-4fde-a564-4f99ab174d0c">
<img width="1384" alt="Screenshot 2023-07-17 at 7 48 20 AM" src="https://github.com/transcom/mymove/assets/62263329/97cdd5ff-b142-4a68-8a1b-b40163b2b827">

2023-07-18 14:55 UTC, AnnaGingle approved these changes
LGTM!

2023-07-18 16:13 UTC, mandaem approved these changes
LGTM, including the tests :) Showing up correctly for move it should, and not for move it shouldn't.

2023-07-18 16:47 UTC, brandonlenz commented on src/pages/Office/MoveDetails/MoveDetails.jsx
> +  }, [mtoShipments, shipmentWithDestinationAddressChangeRequest, setShipmentsWithDeliveryAddressUpdateRequestedCount]);
There are several useEffect blocks in this PR with similar dependency arrays, so this won't be something I recommend delving into on this PR, but it's helpful to socialize on project using React:

It isn't always obvious until you get bit by weird rendering issues, but using arrays and objects in the dependency array effectively causes the useEffect block to run on _every_ render. React does not deep-compare JS objects, so two identical objects with different memory addresses are considered not-equal for dependency arrays.

I _do_ think it's possible to make this one work with non object dependencies, but it would require a little testing. Something like this:

```suggestion
  }, [shipmentWithDestinationAddressChangeRequest?.length, setShipmentsWithDeliveryAddressUpdateRequestedCount]);
```

`mtoShipments` isn't used inside the useEffect block. mtoShipments changing does (potentially) impact whether the number of `shipmentWithDestinationAddressChangeRequest`'s changes, so with the suggested change, it should still trigger when desired.

Does that make sense? Anything I'm overlooking?

2023-07-18 16:48 UTC, brandonlenz commented on src/components/Office/DefinitionLists/ShipmentInfoList.jsx
> +        {deliveryAddressUpdate?.status === 'REQUESTED'
non-blocking

2023-07-18 16:48 UTC, brandonlenz commented on src/pages/Office/MoveDetails/MoveDetails.jsx
> +  }, [mtoShipments, shipmentWithDestinationAddressChangeRequest, setShipmentsWithDeliveryAddressUpdateRequestedCount]);
non-blocking, but very curious!

2023-07-18 17:12 UTC, PDickeyTruss commented on src/components/Office/DefinitionLists/ShipmentInfoList.jsx
> +        {deliveryAddressUpdate?.status === 'REQUESTED'
Great spot! I for sure agree these status strings should be constants.  Ari and I had discussed making these consts and I think we just ended up overlooking it. Thank you for noticing and calling out, it is now fixed ☺️

2023-07-18 17:39 UTC, merged