create a new endpoint for review address update
transcom/mymove pull request #11020
Opened 2023-07-07 18:26 UTC by dymonmoore

## [Jira ticket](tbd)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/run-storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/about/application-setup/milmove-local-client/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/about/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/about/supported-browsers) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/about/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2023-07-18 15:17 UTC, duncan-truss commented on pkg/services/shipment_address_update/shipment_address_update_requester.go
> +	}
We could likely combine these two queries into a single statement:

```go
appCtx.DB().Eager("Shipment").Where("shipment_id = ?", shipmentID).First(&addressUpdate)
...
// assign to a local var if desired or you can use it directly
shipment := addressUpdate.Shipment
```

2023-07-18 15:19 UTC, duncan-truss commented on pkg/services/shipment_address_update/shipment_address_update_requester.go
> +	if tooApprovalStatus == "APPROVED" {
Let's try to use the constants for these, `models.ShipmentAddressUpdateStatusApproved`, so we get the type safety instead of the string.  It's easier to see everywhere it's used in the codebase that way too.

2023-07-18 19:12 UTC, duncan-truss requested changes
There is one additional AC that is needed here, we will need to use the move router to attempt to transition the status back to APPROVED if the address change was the last thing keeping it in the APPROVALS REQUESTED status.

![Screenshot 2023-07-18 at 3 06 14 PM](https://github.com/transcom/mymove/assets/52669884/1c47718d-54a9-4941-b76a-83258a5b8e35)

We will need to add logic to the move_router.go that checks that no shipment address changes are in the requested status before a move can transition back into the APPROVED state.

https://github.com/transcom/mymove/blob/5aa7e4e2474bd992ee239c2b91c97a6fa287ccab/pkg/services/move/move_router.go#L469

2023-07-18 22:28 UTC, mboren commented
I did a diff of the spectral output for ghc.yaml on this branch vs main and I found these two new warnings:
```
warning  operation-tag-defined        Operation tags must be defined in global tags.                          paths./shipments/{shipmentID}/review-shipment-address-update.patch.tags[0]
warning  endpoint-description-length  The endpoint description should be at least 128 characters.             paths./shipments/{shipmentID}/review-shipment-address-update.patch.description
```

2023-07-18 22:42 UTC, mboren commented
a lot of other endpoints in ghc.yaml use `tags : - shipment`
But it isn't defined in the list of tags at the top of the file.
Those endpoints must have been written before we started checking the errors.
We can either add `shipment` as a tag at the top of the file, or we can use the tag `mtoShipment` for this endpoint.
Not sure which is preferable.

2023-07-19 15:18 UTC, duncan-truss approved these changes
Confirmed by sending a request through the office app console.  I noticed the NewAddress and OriginalAddress objects were empty in the response (guessing that would require eager loading them in our query).  I assume we are re-fetching the shipment though in the office app and so that may not matter

2023-07-19 17:08 UTC, mboren commented on pkg/services/shipment_address_update/shipment_address_update_requester.go
> +	err := appCtx.DB().EagerPreload("Shipment", "Shipment.MoveTaskOrder").Where("shipment_id = ?", shipmentID).First(&addressUpdate)
I think you need to preload `OriginalAddress` and `NewAddress` here to get the addresses filled in in the response

2023-07-19 17:47 UTC, dymonmoore commented on pkg/services/shipment_address_update/shipment_address_update_requester.go
> +	err := appCtx.DB().EagerPreload("Shipment", "Shipment.MoveTaskOrder").Where("shipment_id = ?", shipmentID).First(&addressUpdate)
Will do, thanks!

2023-07-19 21:26 UTC, merged