[MB-16355] adding origin and destination fsc
transcom/mymove pull request #11087
Opened 2023-07-19 19:12 UTC by ruizajtruss

## [Jira ticket](https://dp3.atlassian.net/browse/MB-16355)

## Summary

This PR adds new labels and values to display calculations for DDSFSC, DOSFSC, and FRA in the TIO document viewer

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/run-storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/about/application-setup/milmove-local-client/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/about/development/testing)

### How to test

1. Access the `PARAMS` move as the prime
2. Request payment for `DOSFSC`
3. Access the same move as a `TIO`
4. Scroll to the bottom and click the `review service items` button for the DOSFSC surcharge
5. Hit the `show calculations` button and you should see the expected calculations displayed

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/about/supported-browsers) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/about/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2023-07-21 17:05 UTC, afoon commented
The calculations for `FRA` on `DOSFSC` are showing a NaN
<img width="410" alt="Screenshot 2023-07-21 at 1 04 43 PM" src="https://github.com/transcom/mymove/assets/28371460/f23a54b9-7f2a-43f8-acfb-21bc1c7156d6">

2023-07-21 17:11 UTC, ruizajtruss commented
> The calculations for `FRA` on `DOSFSC` are showing a NaN <img alt="Screenshot 2023-07-21 at 1 04 43 PM" width="410" src="https://user-images.githubusercontent.com/28371460/255237697-f23a54b9-7f2a-43f8-acfb-21bc1c7156d6.png">

That's expected for now, will be resolved once I pull in the DOSFSC pricer after its merged

2023-07-24 22:05 UTC, donaldthai requested changes
Looks good so far! Left one suggestion to change.

2023-07-24 22:05 UTC, donaldthai commented on src/components/Office/ServiceItemCalculations/helpers.js
> +
suggestion (blocking): The `FSCPriceDifferenceInCents` value is in cents so we'll have to format from cents to dollars for this one.

2023-07-25 03:59 UTC, ruizajtruss commented on src/components/Office/ServiceItemCalculations/helpers.js
> +
Thanks for catching that, fixed! 🎉

2023-07-25 17:37 UTC, donaldthai approved these changes
LGTM! Dropped a question about the devseed but it's non-blocking.

2023-07-25 17:37 UTC, donaldthai commented on pkg/testdatagen/scenario/shared.go
> +		if serviceItem.ReService.Code != models.ReServiceCodeDOSFSC {
Question: For this check, is this something we would want to remove after the SIT FSC origin pricer is done?

2023-07-25 18:02 UTC, ruizajtruss commented on pkg/testdatagen/scenario/shared.go
> +		if serviceItem.ReService.Code != models.ReServiceCodeDOSFSC {
Yes!

2023-07-25 18:21 UTC, ruizajtruss commented on pkg/testdatagen/scenario/shared.go
> +		if serviceItem.ReService.Code != models.ReServiceCodeDOSFSC {
I added a TODO

2023-07-26 20:22 UTC, donaldthai commented on src/components/Office/ServiceItemCalculations/helpers.js
> +        )}`;
Suggestion (non-blocking): I do have a non-blocking refactor if you're up for it. Idea here is to optimize for readability. Note there are some duplication but that's something that I think it's okay for readability.
```suggestion
  let label, value, detail;
  switch (itemCode) {
    case SERVICE_ITEM_CODES.DOSFSC:
      label = SERVICE_ITEM_CALCULATION_LABELS.MileageIntoSIT;
      distanceZip = SERVICE_ITEM_PARAM_KEYS.DistanceZipSITOrigin;
      value = getParamValue(distanceZip, params);
      detail =
`${SERVICE_ITEM_CALCULATION_LABELS[SERVICE_ITEM_PARAM_KEYS.ZipPickupAddress]} ${getParamValue(
          SERVICE_ITEM_PARAM_KEYS.ZipSITOriginHHGOriginalAddress,
          params,
        )} to ${SERVICE_ITEM_CALCULATION_LABELS[SERVICE_ITEM_PARAM_KEYS.ZipDestAddress]} ${getParamValue(
          SERVICE_ITEM_PARAM_KEYS.ZipSITOriginHHGActualAddress,
          params,
        )}`;
      
      break;
    case SERVICE_ITEM_CODES.DDSFSC:
      label = SERVICE_ITEM_CALCULATION_LABELS.MileageOutOfSIT;
      distanceZip = SERVICE_ITEM_PARAM_KEYS.DistanceZipSITDest;
      value = getParamValue(distanceZip, params);
      detail = `${SERVICE_ITEM_CALCULATION_LABELS[SERVICE_ITEM_PARAM_KEYS.ZipPickupAddress]} ${getParamValue(
    params,	          SERVICE_ITEM_PARAM_KEYS.ZipSITDestHHGOriginalAddress,
  )} to ${SERVICE_ITEM_CALCULATION_LABELS[SERVICE_ITEM_PARAM_KEYS.ZipDestAddress]} ${getParamValue(	          params,
    SERVICE_ITEM_PARAM_KEYS.ZipSITOriginHHGActualAddress,	        )} to ${SERVICE_ITEM_CALCULATION_LABELS[SERVICE_ITEM_PARAM_KEYS.ZipDestAddress]} ${getParamValue(
    params,	          SERVICE_ITEM_PARAM_KEYS.ZipSITDestHHGFinalAddress,
  )}`;	          params,
        )}`;
        
      break;
    default:
      label = SERVICE_ITEM_CALCULATION_LABELS.Mileage;
      distanceZip = SERVICE_ITEM_PARAM_KEYS.DistanceZipSITOrigin;
      value = getParamValue(distanceZip, params);
      detail =
`${SERVICE_ITEM_CALCULATION_LABELS[SERVICE_ITEM_PARAM_KEYS.ZipPickupAddress]} ${getParamValue(
          SERVICE_ITEM_PARAM_KEYS.ZipSITOriginHHGOriginalAddress,
          params,
        )} to ${SERVICE_ITEM_CALCULATION_LABELS[SERVICE_ITEM_PARAM_KEYS.ZipDestAddress]} ${getParamValue(
          SERVICE_ITEM_PARAM_KEYS.ZipSITOriginHHGActualAddress,
          params,
        )}`;
  }
```

2023-07-26 20:47 UTC, dinabeigelman approved these changes
LGTM! 🎉

2023-07-26 20:48 UTC, ruizajtruss commented on src/components/Office/ServiceItemCalculations/helpers.js
> +        )}`;
The funny part is I did do that earlier but then changed my mind last minute because I was worried it'd be too bulky to read through 🤣 I'll do it again and push it up!

2023-07-26 21:11 UTC, mlm55 commented on pkg/testdatagen/scenario/shared.go
> +		if serviceItem.ReService.Code != models.ReServiceCodeDOSFSC {
[This PR](https://github.com/transcom/mymove/pull/11110/files#diff-e24b52a37c80dbc5e9d03237bb69a26607a061212b3ecf3e17636d9cae57448c) might take care of the conditional? but for clarity, we would just want to take away the condition - we'd still want the `paymentServiceItems = append(paymentServiceItems, paymentItem)` line

2023-07-26 21:22 UTC, ruizajtruss commented on src/components/Office/ServiceItemCalculations/helpers.js
> +        )}`;
My approach was just a tiny bit different but same idea, unfortunately prettier does not like me writing multiple let variables on a single line 🎉

2023-07-26 21:38 UTC, merged