MB-16477: Update Initial SIT delivery address shown in edit service item modal
transcom/mymove pull request #11102
Opened 2023-07-24 20:35 UTC by StuTruss

## [Jira ticket](https://dp3.atlassian.net/browse/MB-16477)

## Summary

This PR updates the edit service item modal to instead show the `sitDestinationOriginalAddress` in the `Initial SIT delivery address` column 

## Verification Steps for the Author

These are to be checked by the author.

- [x] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/run-storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/about/application-setup/milmove-local-client/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/about/development/testing)

### How to test

1. Run `make_server_test` to verify all tests pass

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/about/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

2023-07-25 18:28 UTC, mlm55 approved these changes

2023-07-26 19:40 UTC, AnnaGingle requested changes
This isn't working as expected. the initial SIT delivery address should always be the address in place at the time the TOO approves the MTO. It is showing as the address the Prime entered when requesting SIT. 
- I set up a move with 2 HHG shipments using duty locations for destination addresses.
- I approved the MTO as the TOO
- As the Prime I requested SIT for both HHGs. I included an address for SIT for only 1 of the HHGs
- I go in as the TOO. I click edit on the Domestic Destination SIT delivery service item. The HHG which had an SIT address added by the Prime shows the address the Prime entered, not the Initial SIT delivery address (the address in place at the time the TOO approves the MTO).

[Check it out](https://office-milmove-pr-11102.mymove.sandbox.truss.coffee/moves/H97GJX/mto) in the deploy with mode code H97GJX.

2023-07-26 19:43 UTC, AnnaGingle commented
https://github.com/transcom/mymove/assets/48488699/69b7f27b-7f4d-49ff-986b-c2f0fe65cc05

2023-07-31 16:36 UTC, AnnaGingle approved these changes
LGTM!

2023-07-31 22:06 UTC, merged