[DRAFT][MB-16270] TOO destination address change review request modal
transcom/mymove pull request #11111
Opened 2023-07-25 20:42 UTC by SirenaBorracha

## [Jira ticket](https://dp3.atlassian.net/browse/MB-16270)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/run-storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/about/application-setup/milmove-local-client/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/about/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/about/supported-browsers) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/about/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2023-07-28 20:34 UTC, mandaem approved these changes
LGTM, functions as expected. I just eyeballed the design but from that, looked good.

2023-08-01 20:01 UTC, brandonlenz commented
Typing this out in part as an update for reviewers/designer, but also as notes for me to come back to later:

Few weird things going on (not as a result of this PR, but on the project generally) that are making style updates tricky here.

The base Modal parent component is using `base-darker` for `p` and `ul` elements, which is overriding attempts to setup the correct style in the more specific component styles of this PR's `AddressUpdatePreview`

We noticed styles in storybook were not matching the compiled app. Now that I look back, I think the storybook example was just the `AddressUpdatePreview` not wrapped with a `Modal`, so that would explain the difference there.

Going to dig into this a little more, because I don't think throwing in more `!important`s is the solution we should go with if we can avoid it.

2023-08-02 14:06 UTC, brandonlenz commented
The Modal styles are not behaving as I expect. Defining them from a component closer in the dom tree (like the alert itself) _does not_ override the parent modal's styles. However, in https://github.com/transcom/mymove/pull/11111/commits/4e0204df48caa14f469726a0047d2178dbced565 I was able to create a new span, and assign module styles to it which _did_ override the parent modal's style.

2023-08-02 14:20 UTC, brandonlenz commented on src/components/Hint/Hint.stories.jsx
> +  <Hint darkText>
Unrelated to this PR other than this being a simple example of a component using `base-darkest` color that I was looking for and noticed was broken.

Weirdly, `base-darkest` here is `171717`, while `base-darkest` in our modal is `1b1b1b`

2023-08-02 14:25 UTC, brandonlenz commented on src/components/Hint/Hint.stories.jsx
> +  <Hint darkText>
Ah, the `@include u-color('base-darkest)` and just setting `color: $base-darkest` result in different values, the latter being correct.

2023-08-02 15:01 UTC, brandonlenz commented on src/components/Office/ShipmentAddressUpdateReviewRequestModal/ShipmentAddressUpdateReviewRequestModal.jsx
> +                  </div>
Semantically, I don't think this is the right HTML for radio buttons. I _think_ we need this to be a Fieldset with a legend, rather than labels

2023-08-02 15:01 UTC, brandonlenz commented on src/components/Office/ShipmentAddressUpdateReviewRequestModal/ShipmentAddressUpdateReviewRequestModal.jsx
> +                  </div>
e.g. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio

2023-08-02 15:28 UTC, brandonlenz commented on src/components/Hint/Hint.stories.jsx
> +  <Hint darkText>
Note that this will cause a happo delete + add diff. (the darkerText prop isn't a thing, so I updated this example to use darkText which is a thing)

2023-08-02 19:46 UTC, AnnaGingle requested changes
This is really coming together! We just have 1 small thing to fix. The h4 leader `Review request` should be #171717 basedarkest

2023-08-02 20:27 UTC, brandonlenz commented
Hmmm @AnnaGingle I'm seeing the h4 as `#171717`, governed by [this styling](https://github.com/transcom/mymove/blob/f7812cb42ffebbed948713f8e2389e1a6e5dac32/src/components/Office/ShipmentAddressUpdateReviewRequestModal/ShipmentAddressUpdateReviewRequestModal.module.scss#L20):

<img width="573" alt="image" src="https://github.com/transcom/mymove/assets/15805554/9698e740-68f3-4c93-a628-01f939f6faf0">

2023-08-02 20:28 UTC, AnnaGingle commented
Ah, okay. I will go ahead & approve!
On Wed, Aug 2, 2023 at 3:27 PM Brandon Lenz ***@***.***>
wrote:

> Hmmm @AnnaGingle <https://github.com/AnnaGingle> I'm seeing the h4 as
> #171717, governed by this styling
> <https://github.com/transcom/mymove/blob/f7812cb42ffebbed948713f8e2389e1a6e5dac32/src/components/Office/ShipmentAddressUpdateReviewRequestModal/ShipmentAddressUpdateReviewRequestModal.module.scss#L20>
> :
> [image: image]
> <https://user-images.githubusercontent.com/15805554/257933577-9698e740-68f3-4c93-a628-01f939f6faf0.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/transcom/mymove/pull/11111#issuecomment-1662924303>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALR6B622J4VFOYPHQO4O3VTXTKZ3XANCNFSM6AAAAAA2XTQVBE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-08-03 13:46 UTC, AnnaGingle approved these changes

2023-08-03 17:11 UTC, merged