B-17616-TOO-Can-Edit-SIT-Entry-Date
transcom/mymove pull request #11488
Opened 2023-10-12 21:40 UTC by danieljordan-caci

## [API & UI - TOO can Edit First Day of SIT Date](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A844136&RoomContext=TeamRoom%3A808731&concept=TeamRoom)
## [MB-16666: TOO needs to be able to edit first day of SIT](https://www13.v1host.com/USTRANSCOM38/Epic.mvc/Summary?oidToken=Epic%3A834520)

## Summary

This is the only story for the feature where a TOO can edit the first day of SIT. 
This story involved:
- adding a PATCH endpoint to the GHC API to update a SIT entry date for a single service item (`/service-item/{serviceItemID}/entry-date-update`)
- activating a non-implemented GET endpoint in the GHC API to retrieve a service item from the database (`/move-task-orders/{moveTaskOrderID}/service-items/{mtoServiceItemID}`)
- adding a custom UI component in the frontend for displaying a modal and submitting the new SIT entry date
- updating the database with new value and then updating Redux state for the selected service item
- tests for both frontend and backend covering added code

Some things to note:
The displayed "SIT (STORAGE IN TRANSIT)" box at the top of the Move Task Order component does contain some SIT data that is displaying values from another area of state called `currentSit` and has not been updated due to it being out of scope of this story. This could be an enhancement for the future, but when the service item is updated successfully, the state does change for that specific service item in Redux.

### Setup to Run the Code

- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/about/application-setup/milmove-local-client/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/about/development/testing)

### How to test

1. Log into MilMove Office as a TOO
2. Find a Move that contains SIT service items
3. In the Move Task Order page, scroll down to see the list of service items
4. You should see an "Edit" button next to origin/destination 1st Day SIT service items
5. Click on the edit button and change the SIT entry date, enter office remarks, and click Save button
6. You should see a success banner at the top of the page and scroll down to see the SIT entry date has changed for the respective service item

### Frontend

- [ ] There are no new console errors in the test output.
There is an existing console error that was present prior to developing this story when updating any service item (like when updating the address) that is due to some undefined values in a shipment object somewhere. This was not addressed in this story due to it being out of scope.

### Backend

- [x] All tests created for new implementation are passing

## Screenshots

2023-10-20 17:30 UTC, cameroncaci requested changes
Backend review:

2023-10-20 17:30 UTC, cameroncaci commented on pkg/handlers/ghcapi/mto_service_items_test.go
> +		serviceItemID := uuid.Must(uuid.FromString("f7b4b9e2-04e8-4c34-827a-df917e69caf4"))
serviceItemID already declared at start on function

2023-10-20 17:30 UTC, cameroncaci commented on pkg/handlers/ghcapi/mto_service_items_test.go
> +	serviceItemID := uuid.Must(uuid.FromString("f7b4b9e2-04e8-4c34-827a-df917e69caf4"))
serviceItemID already declared at start on function

2023-10-20 17:30 UTC, cameroncaci commented on pkg/handlers/ghcapi/mto_service_items_test.go
> +		expectedUUID := uuid.Must(uuid.FromString("f7b4b9e2-04e8-4c34-827a-df917e69caf4"))
Wouldn't expectedUUID be `serviceItemID`? Just with a comment explaining that's the expected ID?

2023-10-20 17:30 UTC, cameroncaci commented on pkg/services/sit_entry_date_update/sit_entry_date_updater.go
> +type sitEntryDateUpdater struct {
Could you explain the purpose of the struct & the interface implementation of sitEntryDateUpdater?
Interface location for convenience: `pkg/services/sit_entry_date_update.go`

Are there properties added to this struct at a later date that would make it not just be an interface?

2023-10-20 17:30 UTC, cameroncaci commented on pkg/services/sit_entry_date_update/sit_entry_date_updater.go
> +	}
Curiosity question: What if sit entry date is nil? I see it's a pointer so it can be nil

2023-10-20 17:30 UTC, cameroncaci commented on pkg/services/sit_entry_date_update/sit_entry_date_updater_test.go
> +		notFoundUUID := "00000000-0000-0000-0000-000000000001"
Could you make this an auto generated UUID instead of a string?

2023-10-20 18:18 UTC, danieljordan-caci commented on pkg/services/sit_entry_date_update/sit_entry_date_updater_test.go
> +		notFoundUUID := "00000000-0000-0000-0000-000000000001"
For testing purposes - would there be a difference? The test is checking to see if it is not found and both methods achieve the same result.

2023-10-20 18:26 UTC, danieljordan-caci commented on pkg/handlers/ghcapi/mto_service_items_test.go
> +		serviceItemID := uuid.Must(uuid.FromString("f7b4b9e2-04e8-4c34-827a-df917e69caf4"))
Corrected.

2023-10-20 18:28 UTC, danieljordan-caci commented on pkg/handlers/ghcapi/mto_service_items_test.go
> +	serviceItemID := uuid.Must(uuid.FromString("f7b4b9e2-04e8-4c34-827a-df917e69caf4"))
Not sure what you mean by this - this is testing a different handler?

2023-10-20 18:30 UTC, danieljordan-caci commented on pkg/handlers/ghcapi/mto_service_items_test.go
> +		expectedUUID := uuid.Must(uuid.FromString("f7b4b9e2-04e8-4c34-827a-df917e69caf4"))
That is correct. I have changed the code to reflect `expectedUUID := serviceItemID` instead of just hardcoding it.

2023-10-20 18:34 UTC, danieljordan-caci commented on pkg/services/sit_entry_date_update/sit_entry_date_updater.go
> +type sitEntryDateUpdater struct {
I was mimicking what Truss had previously done in these service items.
See `pkg/services/ppmshipment/ppm_shipment_fetcher.go` or `pkg/services/mto_shipment/shipment_router.go` and other examples spread around the `/services` folder.

2023-10-20 18:36 UTC, danieljordan-caci commented on pkg/services/sit_entry_date_update/sit_entry_date_updater.go
> +	}
This is a validation so I'm assuming if it was nil then it would continue with the transaction. Could potentially check to see if it is nil and return an invalid input error since it doesn't contain the data we want to change?

2023-10-20 18:46 UTC, danieljordan-caci commented on pkg/services/sit_entry_date_update/sit_entry_date_updater.go
> +	}
Added in nil check

2023-10-23 13:07 UTC, cameroncaci commented on pkg/services/sit_entry_date_update/sit_entry_date_updater_test.go
> +		notFoundUUID := "00000000-0000-0000-0000-000000000001"
They do both achieve the same result, but it just keeps everything more consistent with our use of UUID v4 generation via the function call. That way it can also be easier down the line to find all v4 generations in case we ever needed to make modification - or in case some other test also decided to generate with `00000000-0000-0000-0000-000000000001`

2023-10-23 16:06 UTC, deandreJones approved these changes

2023-10-23 16:13 UTC, merged