B 17650 reject unchanged sit request
transcom/mymove pull request #11509
Opened 2023-10-24 20:25 UTC by TevinAdams

AGILITY TICKET B-17650

Summary:
This pull request  introduces new functionality. That functionality is that a patch request for a DOFSIT, DDDSIT or DOASIT service item should be rejected if there was nothing changed from the previous serviceItem.

How to know if the service item you are testing with is a DOFSIT, DDDSIT or DOASIT item?

Database: In the database mto_service_items table the service item will have a re_service_id listed below.
Service Item Numbers:
DOFSIT - 998beda7-e390-4a83-b15e-578a24326937
DDDSIT - 5c80f3b5-548e-4077-9b8e-8d0390e73668
DOASIT - 05eb6ff1-5cf6-4918-b887-8260dda6b9fe

MY TEST CASE:
This endpoint was tested with swagger.

Endpoint:  PATCH updateMTOServiceItem

For simplicity the etag was bypassed by commenting out its validation in file mto_service_item_updater.go lines 249-252. This was commented out because it would have taken much more time to understand the correct value to pass in here as i believe it is a generated hash that uses a third party library and a timestamp (Not completely sure).

Put the DOFSIT, DDDSIT or DOASIT service item ID in the mtoServiceItemID field

Make sure in the body of the request the "modelType" attribute is set to "UpdateMTOServiceItemSIT".

Here is an example body that was used for testing. This should be rejected because no change is being made to the service item
{
      "modelType": "UpdateMTOServiceItemSIT",
}

***NOTE This should be merged after B-17642 because there were additional fields the prime is able to update in that story. Once that one goes through the commented out code can be uncommented so that those fields are also tracked.

2023-10-24 21:14 UTC, TevinAdams commented
Closing to resolve tests

2023-10-24 21:48 UTC, TevinAdams commented
Tests resolved

2023-10-25 18:34 UTC, cameroncaci requested changes

2023-10-25 18:34 UTC, cameroncaci commented on pkg/services/mto_service_item/mto_service_item_validators.go
> +		// }
Ready to approve once uncommented

2023-10-25 20:31 UTC, TevinAdams commented on pkg/services/mto_service_item/mto_service_item_validators.go
> +		// }
@cameroncaci  this is ready for review.

2023-10-26 12:43 UTC, cameroncaci commented on pkg/services/mto_service_item/mto_service_item_validators.go
> +			"- To re-submit a SIT sevice item the new SIT service item must be different than the previous one.")
If you're just checking for differences here, why not just do if updateServiceItem != oldServiceItem since they're the same model? Then for nil checks base it off an array of the fields allowed?

I haven't dived incredibly deep into the service item model usage but I'm wondering if there are required fields, why would they be pointers?

2023-10-26 12:43 UTC, cameroncaci commented on pkg/services/mto_service_item/mto_service_item_validators.go
> +func (v *updateMTOServiceItemData) checkForSITItemChanges(_ appcontext.AppContext, serviceItemData *updateMTOServiceItemData) error {
If app context is thrown away here with `_` could we just remove the argument?

2023-10-26 12:44 UTC, cameroncaci commented on pkg/services/mto_service_item/mto_service_item_validators.go
>  func (v *updateMTOServiceItemData) checkLinkedIDs(_ appcontext.AppContext) error {
I see truss did the same here with app context and `_`. Could you fix this on their behalf?

2023-10-26 12:44 UTC, cameroncaci commented on pkg/services/mto_service_item/mto_service_item_validators.go
>  func (v *updateMTOServiceItemData) checkLinkedIDs(_ appcontext.AppContext) error {
Function beneath this one is doing it too

2023-10-26 12:47 UTC, cameroncaci requested changes
Identified possible areas for improvement and discussion

2023-10-26 15:17 UTC, TevinAdams commented on pkg/services/mto_service_item/mto_service_item_validators.go
> +			"- To re-submit a SIT sevice item the new SIT service item must be different than the previous one.")
The updatedServiceItem is basically a MTOServiceItem Model that was created with nil values. The params from the request gets applied to the model created. If no value was passed in then the model keeps that nil value. Thats why in these implementations we have to check for nil because the model object created starts off with all the values as nil then applies the changes from the request. Im a little confused at what you mean by base the nil checks off an array of fields allowed. Right now all fields in this method are allowed to be edited on DDDSIT, DOFSIT, and DOASIT to be edited through the request. If the item is not one of those then it does not run through the check.

2023-10-26 15:36 UTC, TevinAdams commented on pkg/services/mto_service_item/mto_service_item_validators.go
> +func (v *updateMTOServiceItemData) checkForSITItemChanges(_ appcontext.AppContext, serviceItemData *updateMTOServiceItemData) error {
Yes. Havent dived into Appcontext just yet but I think its similar to a state management tool like redux just for go. But in these cases it is not being called, I removed it, tests still pass, and functionality stayed the same for my implementation so I think it is safe to remove.

2023-10-26 18:54 UTC, cameroncaci commented on pkg/services/mto_service_item/mto_service_item_validators.go
> +			"- To re-submit a SIT sevice item the new SIT service item must be different than the previous one.")
Right I see, I was just wondering **_if_** there were required fields why they would be allowed to be nil. And as for base the nil checks off of an array of fields allowed, I mean we create an array to track which fields should not be nil in this new struct and compare the two.

Are your nil checks not checking for **required** fields but checking for nil before comparing old and new? If so you can disregard my comments about required fields and instead move back to `updateServiceItem != oldServiceItem`

2023-10-27 11:55 UTC, cameroncaci commented on pkg/services/mto_service_item/mto_service_item_validators.go
> +			"- To re-submit a SIT sevice item the new SIT service item must be different than the previous one.")
Okay, what about using `updateServiceItem != oldServiceItem` instead of manually comparing the fields?

2023-10-27 15:43 UTC, JamesHawks224 reviewed
Looks good.  No changes.

2023-10-27 16:23 UTC, TevinAdams commented on pkg/services/mto_service_item/mto_service_item_validators.go
> +			"- To re-submit a SIT sevice item the new SIT service item must be different than the previous one.")
@cameroncaci  I believe this approach will not be as reliable. I say that because there are fields in the old object that are set that cannot be set through the update method that is applied to the model. In addition to that there is a better way than doing updateServiceItem != oldServiceItem which is using the golang reflect package that compare structs. But this will not work in this case for the same reason but in addition to that, after looking into whats the best approach to compare golang structs it is highly suggested to create your own comparison method as using a custom comparison method performs much better than the pkg. The pkg will compare every single field vs a custom method will only compare what is needed. I posted some sources below. I do believe the custom method in this case is the best approach to take and mainly because the old service struct coming in will have values for fields that the model that it is compared to will not have a value for because there is no option for the prime to update those fields. So by using newStruct != oldStruct will render undesired results.

https://www.sobyte.net/post/2021-12/struct-compare/
https://stackoverflow.com/questions/24534072/how-to-compare-if-two-structs-slices-or-maps-are-equal

2023-10-27 19:35 UTC, deandreJones commented on pkg/services/mto_service_item/mto_service_item_validators.go
> +			"- To re-submit a SIT sevice item the new SIT service item must be different than the previous one.")
so im a little confused as to why the original struct wouldnt have all the values as the new one? -

how are those structs getting populated

2023-10-27 19:39 UTC, deandreJones commented on pkg/services/mto_service_item/mto_service_item_validators.go
> +			"- To re-submit a SIT sevice item the new SIT service item must be different than the previous one.")
on another note, if writing a custom validator, why not make it dymamic so that it could be used to compare any struct rather than just  updateMTOServiceItemData

2023-10-27 20:03 UTC, TevinAdams commented on pkg/services/mto_service_item/mto_service_item_validators.go
> +			"- To re-submit a SIT sevice item the new SIT service item must be different than the previous one.")
@deandreJones looking at pkg/handlers/primeapi/payloads/payload_to_model.go at line 556 a new MTO struct is created. The params that are passed in gets applied to that new struct, but not every field is getting changed on the struct. Only the ones that are wanting to be updated from the request. If you put a breakpoint or console model.reason right after the model is created the value should be <nil>.  Only fields that are allowed to be updated through this request is applied to this struct. Later in the process pkg/services/mto_service_item/mto_service_item_validators.go, method: setNewMTOServiceItem. newMTOServiceItem is created from the oldServiceItem and that model mentioned above applies fields to the new one.

2023-10-27 20:11 UTC, danieljordan-caci commented on pkg/services/mto_service_item/mto_service_item_validators.go
> +			"- To re-submit a SIT sevice item the new SIT service item must be different than the previous one.")
I agree that it might be easier to just compare structs. I know Go can be a little sassy - have you tried comparing the structs entirely and seeing what you get in the debugger? The structs should be the same.

Just doing a:
```
if updatedServiceItem = oldServiceItem
```
can be pretty tricky. I just tried and got a warning saying that the structs can't be compared despite them both being `models.MTOServiceItem`.

I just tried to use the `reflect.DeepEqual(updatedServiceItem, oldServiceItem)` as well and was getting false despite putting the same values in the API call.

I do think that Tevin is currently doing it in an appropriate way since the `payload_to_model.go` method is being used and that the structs will likely not be equal and it may be easier to just do individual checks like it is currently coded. At least for now.

2023-10-27 20:13 UTC, danieljordan-caci approved these changes
Looks good to me!

2023-10-27 20:21 UTC, TevinAdams commented on pkg/services/mto_service_item/mto_service_item_validators.go
> +			"- To re-submit a SIT sevice item the new SIT service item must be different than the previous one.")
@deandreJones So the calling method of checkForSITItemChanges is validate. This validate method runs for all serviceItems being updated from the prime. Within that method there are many validations specific to a serviceitem updates from the prime such as checkNonPrimeFields and some others. The way I approached it is to stick to the coding pattern that has already been established. The validate method has all the different checks specific to the prime making updates to a service item. I am not really making a new validator. Instead I am basically adding onto the primeUpdateMTOServiceItemValidator that already exist to validate these requests by adding an additonal check. Creating a new validator I think would go against what the application is already doing for this case. The validators are very specific.

2023-10-27 20:29 UTC, TevinAdams commented on pkg/services/mto_service_item/mto_service_item_validators.go
> +			"- To re-submit a SIT sevice item the new SIT service item must be different than the previous one.")
@d

> I agree that it might be easier to just compare structs. I know Go can be a little sassy - have you tried comparing the structs entirely and seeing what you get in the debugger? The structs should be the same.
> 
> Just doing a:
> 
> ```
> if updatedServiceItem = oldServiceItem
> ```
> 
> can be pretty tricky. I just tried and got a warning saying that the structs can't be compared despite them both being `models.MTOServiceItem`.
> 
> I just tried to use the `reflect.DeepEqual(updatedServiceItem, oldServiceItem)` as well and was getting false despite putting the same values in the API call.
> 
> I do think that Tevin is currently doing it in an appropriate way since the `payload_to_model.go` method is being used and that the structs will likely not be equal and it may be easier to just do individual checks like it is currently coded. At least for now.

Before starting my approach I did look up the best way to do this. Many languages you can compare structs using equality operators and different packages. But out of all I researched it seemed making our own would be best for performance reason but also the reflect pkg has been said to be used wrong in some cases and not as reliable. So if the structs are not so complex it is best to create our own. I can imagine as go evolves more pkgs for stuff like this will be introduced and will be a better approach.

2023-10-31 15:17 UTC, traskowskycaci reviewed
I am testing with Swagger and am using
```
{
"modelType": "UpdateMTOServiceItemSIT",
"sitRequestedDelivery": "2019-08-31",
"timeMilitary2": "1400Z",
"updateReason": "Test reason 67",
"requestApprovalsRequestedStatus": true,
"sitDepartureDate": "2019-08-31",
"sitPostalCode" : "90211"
}
```
in the body. This is data that has **not** changed and the response is:
```
{
  "detail": "ID: 6eba127d-cbc8-4bf7-b276-b174a71a91cd is in a conflicting state - this SIT service item cannot be updated because the status is not in an editable state.",
  "instance": "0e279c4d-e8b4-4f4e-80b8-b903abbd9525",
  "title": "Conflict Error"
}
```
Which I expect because the status was not REJECTED at that point. Manually changing to status to REJECTED and using the same body successfully updates the SIT, but wouldn't we expect it to be rejected since nothing changed?

Of note, when I shorten the body to just
```
{
"modelType": "UpdateMTOServiceItemSIT"
}
```

I do get the response of 
```
{
  "detail": "ID: 6eba127d-cbc8-4bf7-b276-b174a71a91cd is in a conflicting state - To re-submit a SIT sevice item the new SIT service item must be different than the previous one.",
  "instance": "7ae9d162-644e-44cd-8ff6-3bc7cfc0e04b",
  "title": "Conflict Error"
}
```

2023-10-31 17:28 UTC, TevinAdams commented
> {
> "modelType": "UpdateMTOServiceItemSIT",
> "sitRequestedDelivery": "2019-08-31",
> "timeMilitary2": "1400Z",
> "updateReason": "Test reason 67",
> "requestApprovalsRequestedStatus": true,
> "sitDepartureDate": "2019-08-31",
> "sitPostalCode" : "90211"
> }

Thanks for the find. This was caused by not comparing the dates using their UTC values. I have made a change to fix that. As for the messages that print out, that is based on which checks are implemented first. Right now the status check happens after the change check.

2023-10-31 17:42 UTC, deandreJones commented
branch is out of date with master and has conflicts

2023-10-31 17:58 UTC, TevinAdams commented
> branch is out of date with master and has conflicts

Just updated branch

2023-11-01 14:10 UTC, traskowskycaci approved these changes
Retested after the date change. Looks good.

2023-11-01 21:14 UTC, deandreJones approved these changes

2023-11-01 21:15 UTC, merged

2023-11-06 16:37 UTC, JamesHawks224 reviewed
looks good.  no changes.