initial commit
transcom/mymove pull request #11521
Opened 2023-10-27 20:49 UTC by danieljordan-caci

## [DB - Add Partial Delivery Weight Column to MTO Shipments Table](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A842079&RoomContext=TeamRoom%3A808731&concept=TeamRoom)

## Summary

Added a column of integers to the `mto_shipments` table in the database that will be used in future stories to handle partial deliveries out of SIT. The goal of this column is to store the multiple deliveries into an array, calculate those numbers, and subtract them from the `actual_weight` value. It is likely that there will be multiple deliveries so an array of integers was the most practical solution.

2023-10-27 21:05 UTC, TevinAdams commented on migrations/app/schema/20231027204028_add_partial_delivery_column_to_shipments_table.up.sql
Do we know if the weight also comes in as decimal values? I am thinking it may be best to have the array store floats to account for decimal spaces with weight. Also if the array will store multiple partial weights I am starting to think it may be best to store it as JSON so we can store a json array or weight objects that have the weight of course but also other information to make it easier to define but associate that weight value with its request.

2023-10-27 21:09 UTC, danieljordan-caci commented on migrations/app/schema/20231027204028_add_partial_delivery_column_to_shipments_table.up.sql
I understand where you're going with that and it isn't a bad idea - but I don't think it's completely necessary? Maybe? All we need to do is track the weight that is delivered out of SIT and an array of integers should track that. But I'm down to reach out and ask - when we initially discussed this, we decided on the same process as we are storing the partial payments out of SIT - which is also an array of integers.

2023-10-27 21:10 UTC, danieljordan-caci commented on migrations/app/schema/20231027204028_add_partial_delivery_column_to_shipments_table.up.sql
And currently all of their weight columns are integers - not floats.

2023-10-30 15:07 UTC, traskowskycaci commented on migrations/app/schema/20231027204028_add_partial_delivery_column_to_shipments_table.up.sql
Agree that the weight columns, both estimated and actual, come in as integers rather than floats so it makes sense to keep this as an array of ints. I am curious on the JSON thought - what benefits would that give us for calculating partial deliveries in the future? Do we need to have a unique ID or something tracking each partial delivery weight?

2023-10-30 16:04 UTC, TevinAdams commented on migrations/app/schema/20231027204028_add_partial_delivery_column_to_shipments_table.up.sql
Yeah then disregard my float Idea. But back to the JSON array I think the least we could store in the object is the partial weight and its request ID so when we pull partial weights at anytime we also have information that is needed to associate that number. Or if we just store it as a json array we can always add onto the object if we discover we need more than just the partial weight. Just looking for thoughts on that. I am not sure how difficult it will be if we need to pull these partial weights but do not have information on which request these partial weights belong to. In addition to that we will also need to add a partial weight column on the payment request table but that will be handled in a different story. I think by having the partial weight stored in the payment request table and then having a json array with abject such as: [{ partialWeightAmt: value, paymentRequestId: value }, ...] would be beneficial.

2023-10-31 13:22 UTC, danieljordan-caci commented on migrations/app/schema/20231027204028_add_partial_delivery_column_to_shipments_table.up.sql
I'm not against this! I would say that if we do it this way, then we should also update the partial payment column we added to also be JSON.

2023-10-31 13:27 UTC, danieljordan-caci commented on migrations/app/schema/20231027204028_add_partial_delivery_column_to_shipments_table.up.sql
Never a bad thing to store more information. We should maybe figure out what kind of information we would need to store in the JSON, etc. May be worth chatting about as a team.

2023-10-31 14:24 UTC, deandreJones commented on migrations/app/schema/20231027204028_add_partial_delivery_column_to_shipments_table.up.sql
so are we updating this to json, can it be simple for what we need for this feature, and maybe updated later if more data is needed

2023-10-31 14:31 UTC, danieljordan-caci commented on migrations/app/schema/20231027204028_add_partial_delivery_column_to_shipments_table.up.sql
Don't see why not! I was going to get everyone's opinion on it, but sounds like there's plenty of agreement.

2023-10-31 14:39 UTC, danieljordan-caci commented on migrations/app/schema/20231027204028_add_partial_delivery_column_to_shipments_table.up.sql
> so are we updating this to json, can it be simple for what we need for this feature, and maybe updated later if more data is needed

Oh wait - were you leaning towards keeping it as an array of integers and then moving to JSON later on if it's needed?

2023-10-31 14:56 UTC, TevinAdams commented on migrations/app/schema/20231027204028_add_partial_delivery_column_to_shipments_table.up.sql
> so are we updating this to json, can it be simple for what we need for this feature, and maybe updated later if more data is needed

That's what I was thinking with the JSON Array we could always add onto the object of what's needed. But off the top of my head I think the request ID and the partial payment amount is good. I think by making it a JSON Array it allows us to expand on it if we need more information.

2023-10-31 15:06 UTC, danieljordan-caci commented on migrations/app/schema/20231027204028_add_partial_delivery_column_to_shipments_table.up.sql
Cool. Then should I also update the partial payments column we added to also be JSON?

2023-11-01 21:18 UTC, deandreJones requested changes
i beleive this is the branch to add the new talbes and FKs for partial payments and deliveries

2023-11-02 13:18 UTC, danieljordan-caci commented
> i beleive this is the branch to add the new talbes and FKs for partial payments and deliveries

Correct. I will close and reopen with new code when complete. Prob get this done today.

2023-11-02 13:18 UTC, closed without merging