B-17690
transcom/mymove pull request #11542
Opened 2023-11-07 20:04 UTC by loganwc

## [Agility ticket](https://www13.v1host.com/USTRANSCOM38/TeamRoom.mvc/Show/848240)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

would like the Allowances screen to reflect the pro-gear amount entered by the service member,

So that I do not need to manually edit the allowances in order to see the information.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access milmovelocal
2. Create a PPM with Pro Gear
3. Access officelocal
4. Login as a TOO/SC
5. Open the PPM created with Pro Gear, under allowances should list 2000 for pro gear and 500 for spouse pro gear

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

2023-11-08 20:26 UTC, paulstonebraker approved these changes

2023-11-08 22:42 UTC, cameroncaci requested changes
Tested successfully in local. Proposing code changes:

2023-11-08 22:42 UTC, cameroncaci commented on pkg/handlers/internalapi/orders.go
> +
Could you switch this over to reusing a single `err` var and then immediately handling the error after each function call? This way if one of the functions error out we can immediately handle instead of proceeding with additional functions

2023-11-08 22:42 UTC, cameroncaci commented on pkg/models/entitlements.go
> +}
OPTIONAL REVIEW (If other proposal is rejected):

Could you write a test for this function? Additionally, this could be refactored to be:
```
func GetProGearEntitlement(rank ServiceMemberRank, isDependent bool) (int, error) {
	selfEntitlement, err := getEntitlement(rank)
	if err != nil {
		return 0, fmt.Errorf("rank %s not found in entitlement map", rank)
	}

	if isDependent {
		return selfEntitlement.ProGearWeightSpouse, nil
	}

	return selfEntitlement.ProGearWeight, nil
}
```

2023-11-08 22:42 UTC, cameroncaci commented on pkg/models/entitlements.go
> +}
I'm not sure if this code is necessary. func `GetEntitlement` already calls `getEntitlement` as well as it uses type `WeightAllotment{}` which holds both total weight _and_ progear weight. We could just change the return from an `int` to a `WeightAllotment` object. This may require additional refactoring of the existing funcs calling `GetEntitlement()`

2023-11-08 22:43 UTC, cameroncaci commented on pkg/models/entitlements.go
> +}
Please see https://github.com/transcom/mymove/pull/11542#discussion_r1387277866 before actioning this comment

2023-11-08 22:57 UTC, cameroncaci requested changes
Additional comment

2023-11-08 22:57 UTC, cameroncaci commented on pkg/handlers/internalapi/orders.go
> +			proGearSpouse, proGearSpouseErr := models.GetProGearEntitlement(*serviceMember.Rank, true)
Somewhat similar to the other comment of using the `WeightAllotment{}` object, is the second parameter to `GetProGearEntitlement`, `isDependent` a boolean to check for the spouse's pro gear? If so, I would recommend splitting this up into its own function entirely called something like `GetSpousalProGearEntitlement`. Since they're exported funcs they could be reusable - if we don't refactor `GetEntitlement` to just gather everything and return as one single object which could be the smallest code solution.

2023-11-13 17:20 UTC, cameroncaci commented on pkg/models/entitlements.go
> +}
`WeightAllotment` already exists to serve the purpose of `TotalEntitlements`

2023-11-13 18:06 UTC, loganwc commented on pkg/models/entitlements.go
> +}
I tried but I got error's that it didn't exist even though I was looking at it

2023-11-13 18:19 UTC, cameroncaci commented on pkg/models/entitlements.go
> +}
Interesting, could you try again and send me the specific error? I know Mac sometimes does not play nice with VSCode and can give false errors. A restart of VSCode typically resolves that

2023-11-14 14:33 UTC, loganwc commented on pkg/models/entitlements.go
> +}
![Screenshot 2023-11-14 at 8 30 02 AM](https://github.com/transcom/mymove/assets/148146808/3debcde4-247d-4f5b-8e3d-cdfcd89da6e8)

But the Entitlement struct has the weightAllotment field, now I could just return the entire WeightAllotment from the entitlements but then I would be adding redundant checks all over the code where the allotment is used. I felt it was cleaner to just have a single conditional in the entitlements class and return a modified struct with only the values that'll be used.

2023-11-14 14:34 UTC, cameroncaci commented on pkg/models/entitlements.go
> +}
`WeightAllotment` with a capital W

2023-11-14 14:38 UTC, loganwc commented on pkg/models/entitlements.go
> +}
![Screenshot 2023-11-14 at 8 38 06 AM](https://github.com/transcom/mymove/assets/148146808/dea05efa-ce73-4f24-acd3-0407700467aa)

2023-11-14 14:40 UTC, cameroncaci commented on pkg/models/entitlements.go
> +}
I don't see any squiggly errors from that section

2023-11-14 14:41 UTC, cameroncaci commented on pkg/models/entitlements.go
> +}
Your `weightAllotment` field is private by the way, you may be trying to call it somewhere it can't be called. Try making it public (Exportable) with a capital W

2023-11-14 14:41 UTC, loganwc commented on pkg/models/entitlements.go
> +}
That's where the struct is defined. If I try big W in the implementation it throws the same error 
![Screenshot 2023-11-14 at 8 41 42 AM](https://github.com/transcom/mymove/assets/148146808/3de0e63d-f901-45ac-9478-8535d33ab28e)

2023-11-14 14:44 UTC, loganwc commented on pkg/models/entitlements.go
> +}
I can't change it in the models.Entitlement because then there's multiple fields/methods with the same name

2023-11-14 14:47 UTC, cameroncaci commented on pkg/models/entitlements.go
> +}
Could you send me that snippet where you're using `WeightAllotment: weight` at? Without the error modal up so I can get a peek at how its being used

2023-11-14 15:00 UTC, loganwc commented on pkg/models/entitlements.go
> +}
handlers/internalapi/orders.go line 165-168

2023-11-14 15:08 UTC, cameroncaci commented on pkg/models/entitlements.go
> +}
Could you push your code (Add `--no-verify` to your commit to force it through)

2023-11-14 15:18 UTC, loganwc commented on pkg/models/entitlements.go
> +}
Pushed. I added a comment below the added code.

2023-11-14 15:24 UTC, cameroncaci commented on pkg/models/entitlements.go
> +}
Ah, I see. Here's how to fix it:
Update Entitlement struct to have an exported, and unmatched var name of `WeightAllotted` (Or whatever you deem fit) to `*WeightAllotment`. They can't both be the same name for this part.
```
// Entitlement is an object representing entitlements for orders
type Entitlement struct {
	ID                    uuid.UUID `db:"id"`
	DependentsAuthorized  *bool     `db:"dependents_authorized"`
	TotalDependents       *int      `db:"total_dependents"`
	NonTemporaryStorage   *bool     `db:"non_temporary_storage"`
	PrivatelyOwnedVehicle *bool     `db:"privately_owned_vehicle"`
	//DBAuthorizedWeight is AuthorizedWeight when not null
	DBAuthorizedWeight                           *int             `db:"authorized_weight"`
	WeightAllotted                              *WeightAllotment `db:"-"`
	StorageInTransit                             *int             `db:"storage_in_transit"`
	RequiredMedicalEquipmentWeight               int              `db:"required_medical_equipment_weight"`
	OrganizationalClothingAndIndividualEquipment bool             `db:"organizational_clothing_and_individual_equipment"`
	ProGearWeight                                int              `db:"pro_gear_weight"`
	ProGearWeightSpouse                          int              `db:"pro_gear_weight_spouse"`
	CreatedAt                                    time.Time        `db:"created_at"`
	UpdatedAt                                    time.Time        `db:"updated_at"`
}
```

Afterwards, here's what your `entitlment :=` will look like:
```
entitlement := models.Entitlement{
DependentsAuthorized: payload.HasDependents,
DBAuthorizedWeight:   models.IntPointer(weightAllotment.TotalWeight),
StorageInTransit:     models.IntPointer(sitDaysAllowance),
ProGearWeight:        weightAllotment.ProGearWeight,
ProGearWeightSpouse:  weightAllotment.ProGearWeightSpouse,
WeightAllotted:      weightAllotment,
}
```

Then you need to update the function call in this line:
`weightAllotment, weightAllotmentErr := models.GetEntitlement(*serviceMember.Rank, *payload.HasDependents)`

To return type `WeightAllotment`
`func GetEntitlement(rank ServiceMemberRank, hasDependents bool) (WeightAllotment, error) {`

2023-11-14 15:27 UTC, cameroncaci commented on pkg/models/entitlements.go
> +}
Also for this section here:
```
DBAuthorizedWeight:   models.IntPointer(weightAllotment.TotalWeight),
StorageInTransit:     models.IntPointer(sitDaysAllowance),
ProGearWeight:        weightAllotment.ProGearWeight,
ProGearWeightSpouse:  weightAllotment.ProGearWeightSpouse,
```

You would need to refactor out DBAuthorizedWeight, ProGearWeight, and ProGearWeightSpouse, because the new value of `WeightAllotted` will already hold all of those values. You'll just need to update anywhere entitlement.DBAuthorizedWeight is called and replace it with entitlement.WeightAllotted.TotalWeight for example

2023-11-14 15:35 UTC, cameroncaci commented on pkg/models/entitlements.go
> +}
Or you can look to see if alternatively `WeightAllotment` could be dropped entirely in favor of "flat" values like how
```
	ProGearWeight                                int              `db:"pro_gear_weight"`
	ProGearWeightSpouse                          int              `db:"pro_gear_weight_spouse"`
``` 
are flat inside of the `Entitlement` struct, this way it also attached to the database for Go Pop which is a lot better.

It's unfortunate this refactor is necessary and it isn't because of your work. It's just the backend structure for this was not setup properly for how we inherited it.

2023-11-14 15:35 UTC, cameroncaci commented on pkg/models/entitlements.go
> +}
Or you can look to see if alternatively `WeightAllotment` could be dropped entirely in favor of "flat" values like how
```
	ProGearWeight                                int              `db:"pro_gear_weight"`
	ProGearWeightSpouse                          int              `db:"pro_gear_weight_spouse"`
``` 
are flat inside of the `Entitlement` struct, this way it also attached to the database for Go Pop which is a lot better.

It's unfortunate this refactor is necessary and it isn't because of your work. It's just the backend structure for this was not setup properly for how we inherited it.

2023-11-14 15:35 UTC, cameroncaci commented on pkg/models/entitlements.go
> +}
Do both of these approaches make sense @loganwc ?

2023-11-14 15:37 UTC, cameroncaci commented on pkg/models/entitlements.go
> +}
The best configuration would be if 
```
type Entitlement struct {
	ID                    uuid.UUID `db:"id"`
	DependentsAuthorized  *bool     `db:"dependents_authorized"`
	TotalDependents       *int      `db:"total_dependents"`
	NonTemporaryStorage   *bool     `db:"non_temporary_storage"`
	PrivatelyOwnedVehicle *bool     `db:"privately_owned_vehicle"`
	//DBAuthorizedWeight is AuthorizedWeight when not null
	DBAuthorizedWeight                           *int             `db:"authorized_weight"`
	weightAllotment                              *WeightAllotment `db:"-"`
	StorageInTransit                             *int             `db:"storage_in_transit"`
	RequiredMedicalEquipmentWeight               int              `db:"required_medical_equipment_weight"`
	OrganizationalClothingAndIndividualEquipment bool             `db:"organizational_clothing_and_individual_equipment"`
	ProGearWeight                                int              `db:"pro_gear_weight"`
	ProGearWeightSpouse                          int              `db:"pro_gear_weight_spouse"`
	CreatedAt                                    time.Time        `db:"created_at"`
	UpdatedAt                                    time.Time        `db:"updated_at"`
}
```

Turned into
```
type Entitlement struct {
	ID                    uuid.UUID `db:"id"`
	DependentsAuthorized  *bool     `db:"dependents_authorized"`
	TotalDependents       *int      `db:"total_dependents"`
	NonTemporaryStorage   *bool     `db:"non_temporary_storage"`
	PrivatelyOwnedVehicle *bool     `db:"privately_owned_vehicle"`
	//DBAuthorizedWeight is AuthorizedWeight when not null
	DBAuthorizedWeight                           *int             `db:"authorized_weight"`
	StorageInTransit                             *int             `db:"storage_in_transit"`
	RequiredMedicalEquipmentWeight               int              `db:"required_medical_equipment_weight"`
	OrganizationalClothingAndIndividualEquipment bool             `db:"organizational_clothing_and_individual_equipment"`
	ProGearWeight                                int              `db:"pro_gear_weight"`
	ProGearWeightSpouse                          int              `db:"pro_gear_weight_spouse"`

	TotalWeightSelf               int `db:"ColumnNameHere`
	TotalWeightSelfPlusDependents int `db:"ColumnNameHere`


	CreatedAt                                    time.Time        `db:"created_at"`
	UpdatedAt                                    time.Time        `db:"updated_at"`
}
```

2023-11-14 15:38 UTC, cameroncaci commented on pkg/models/entitlements.go
> +}
Could you check to see if TotalWeightSelf and TotalWeightSelfPlusDependents are indeed from the database and not calculated within the code based on rank? @loganwc

2023-11-14 20:19 UTC, paulstonebraker approved these changes

2023-11-15 14:13 UTC, cameroncaci submitted a review, later dismissed
<img width="776" alt="image" src="https://github.com/transcom/mymove/assets/136814362/f567c20e-4531-419c-adb9-175eded0cd9d">
One last change and G2G: There is a duplicate function

2023-11-15 14:13 UTC, cameroncaci commented
Additionally make sure to update the comment on line 232 in that snippet provided

2023-11-16 14:07 UTC, cameroncaci approved these changes

2023-11-16 14:33 UTC, merged