B 17615 weight ticket designator for payment request uploads
transcom/mymove pull request #11547
Opened 2023-11-09 20:40 UTC by danieljordan-caci

## [B-17615](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A844121&RoomContext=TeamRoom%3A808731&concept=TeamRoom)

## Summary

Added capability of the Prime to add a parameter of `isWeightTicket` to a POST request to `/createUpload` endpoint. 

This required adding a migration file to add a column, `isWeightTicket` to the `proof_of_service_docs` table.

Updated the Go Struct for `ProofOfServiceDocs` model to include the `isWeightTicket` boolean value.

At this time it is an optional parameter, but if it is not provided then it is changed to `false` when put into the database.
*NOTE* This story did not have criteria to update the Prime simulator, so when using the Prime Sim you will be unable to test this or add a `isWeightTicket` value to the upload.

In order to see this change in the frontend, I also had to update the `model_to_payload.go` file for the GHC API and allow including the parameter in a `GET` request for payment requests.

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Log into MilMove as the Prime
2. Using Postman, send a POST request to `/createUpload` on an existing payment request
```
{
   "paymentRequestID": "uuid",
   "file": "fileUrl",
   "isWeightTicket": true
}
```
3. Perform a `GET` request to `/getMoveTaskOrders/{moveID}` to see the payment requests
4. Confirm you can see the `isWeightTicket` parameter for the upload you added to the payment request

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

2023-11-16 17:29 UTC, cameroncaci commented
Since this was drafted for a while it won't appear at the top. Pinging everyone for awareness: @deandreJones @TevinAdams @traskowskycaci

2023-11-16 17:29 UTC, cameroncaci requested changes

2023-11-16 17:29 UTC, cameroncaci commented on migrations/app/schema/20231109142950_add-weight-ticket-boolean-to-uploads-table.up.sql
> +ADD COLUMN is_weight_ticket boolean DEFAULT false;
Almost forgot, this needs a not null attribute

2023-11-16 18:18 UTC, danieljordan-caci commented on migrations/app/schema/20231109142950_add-weight-ticket-boolean-to-uploads-table.up.sql
> +ADD COLUMN is_weight_ticket boolean DEFAULT false;
Corrected

2023-11-16 20:21 UTC, traskowskycaci approved these changes
Tested with swagger and postman, looks good!

2023-11-20 20:19 UTC, cameroncaci commented on pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
> +}
Question,
Why is the error handlign here only set to `PROCESSING` and not returning an actual error in the func?

2023-11-20 20:20 UTC, danieljordan-caci commented on pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
> +}
No idea, this was an implementation in the other function I copied this from. Code from Truss days.

2023-11-20 20:20 UTC, cameroncaci commented on pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
> +	// checking if isWeightTicket is NULL to avoid panic
Where did this panic by the way? With our column value set to NOT NULL now I'm not sure if we need this anymore

2023-11-20 20:22 UTC, cameroncaci commented on pkg/factory/proof_of_service_doc_factory.go
> +		IsWeightTicket:   &isWeightTicket,
Is this still needed to be a pointer if `NOT NULL`?

2023-11-20 20:22 UTC, cameroncaci commented on pkg/models/proof_of_service_doc.go
> +	IsWeightTicket   *bool     `db:"is_weight_ticket"`
Just another quick pointer check if the DB column has `NOT NULL`

2023-11-20 20:40 UTC, danieljordan-caci commented on pkg/models/proof_of_service_doc.go
> +	IsWeightTicket   *bool     `db:"is_weight_ticket"`
FIXED YOU CRAZY KID

2023-11-20 20:40 UTC, danieljordan-caci commented on pkg/factory/proof_of_service_doc_factory.go
> +		IsWeightTicket:   &isWeightTicket,
This has been signed, sealed, and delivered

2023-11-20 20:40 UTC, danieljordan-caci commented on pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
> +	// checking if isWeightTicket is NULL to avoid panic
I panicked and fixed this for you

2023-11-20 20:42 UTC, cameroncaci approved these changes

2023-11-20 20:42 UTC, cameroncaci commented
Tested successfully locally!

2023-11-20 20:46 UTC, deandreJones commented
conflicts

2023-11-20 20:54 UTC, danieljordan-caci commented
> conflicts

Resolved

2023-11-20 21:09 UTC, merged