B 17664 remove vendor panel on ppm shipments
transcom/mymove pull request #11557
Opened 2023-11-14 15:34 UTC by antgmann

## B-17664 remove vendor panel on ppm shipments

## Summary

_"As a TOO when creating a MTO for a Partial PPM

I should not see an option of selecting a type of “Vendor” (either GHC Prime Contractor or External vendor)

So that as the TOO I can enter the Origin info and complete the PPM without this unnecessary step "_

Previously this panel only appeared on the page if the user is a TOO AND the shipment type is NOT HHG.

Since this task requires removing the panel for TOO when editing a PPM only, I have added a clause that will not show this panel for PPM moves.

This means that the new case for the panel showing will be: The user is a TOO AND the shipment type is NOT HGG AND the shipment type is NOT PPM. If all 3 conditions are not met, the panel will not show.

Now, the panel will only show for NTS or NTSR shipment options when viewing as a TOO. A quick adjustment to my local tests confirm this.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### How to test

1. Access milmove's office client
2. Login as a TOO role
3. Look for existing shipments.
4. Select one, and then select "Edit Shipment"
5. See if the Vendor panel is present, test the form by submitting it.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

## Screenshots
<img width="682" alt="Screenshot 2023-11-14 at 10 27 56 AM" src="https://github.com/transcom/mymove/assets/148906585/385309ee-637d-4837-8935-741c2b5e18f6">
<img width="1364" alt="Screenshot 2023-11-14 at 10 28 24 AM" src="https://github.com/transcom/mymove/assets/148906585/42f39e96-456e-4ae7-87e4-c50dc553083b">

2023-11-15 13:37 UTC, cameroncaci requested changes

2023-11-15 13:37 UTC, cameroncaci commented on src/components/Office/ShipmentForm/ShipmentForm.test.jsx
> -      expect(screen.queryByRole('heading', { level: 2, name: 'Vendor' })).not.toBeInTheDocument();
Test missing, functionality is good though

2023-11-15 13:39 UTC, antgmann commented on src/components/Office/ShipmentForm/ShipmentForm.test.jsx
> -      expect(screen.queryByRole('heading', { level: 2, name: 'Vendor' })).not.toBeInTheDocument();
I missed the .not., I thought it was expecting the vendor section. Will be remedied shortly.

2023-11-15 14:17 UTC, cameroncaci approved these changes

2023-11-16 13:51 UTC, MInthavongsay approved these changes

2023-11-16 13:54 UTC, merged