B 17588 enable prime to add partial weight
transcom/mymove pull request #11556
Opened 2023-11-13 22:02 UTC by TevinAdams

Ticket: B-17588

This PR will allow the prime to enter in a requested weight that is >= 1 on a payment request. The weight will be stored on the pull request. If the prime does not enter a weight then the value will be stored as 0. 

Currently the payment requests are not displaying a requested weight. Will need to display this value on the payment request if it is >= 1. If not, then display the full shipment weight which I believe is the prime_actual_weight on the mto_shipment table.

To test:
Submit a payment request with the requestedWeightAmount. Look in the database at the payment_request table and the value will be stored. This will be the number to display on the payment requests if it is not 0.

2023-11-15 13:17 UTC, cameroncaci commented
I thought if no weight was provided then the weight should be the entire shipment weight instead of 0? Is weight for payment handled differently than I'm thinking?

2023-11-16 21:09 UTC, TevinAdams commented
> I thought if no weight was provided then the weight should be the entire shipment weight instead of 0? Is weight for payment handled differently than I'm thinking?

Correct. Changes were made to meet this requirment.

2023-11-17 19:02 UTC, traskowskycaci reviewed
Which service item types will this work for? I have tried a few, including DOPSIT and DOFSIT and got the responses of: 
{
  "detail": "the parameter Service Item Parameter Name is either invalid or cannot be passed while creating a payment request for a DOPSIT service item",
  "instance": "8c78492c-5bd1-47ac-ab53-6b9180eb0d7b",
  "title": "Validation Error",
  "invalidFields": {}
}

{
  "detail": "the parameter Service Item Parameter Name is either invalid or cannot be passed while creating a payment request for a DOFSIT service item",
  "instance": "8d34eb7b-7a65-484b-b962-29004972f51f",
  "title": "Validation Error",
  "invalidFields": {}
}  

Also tried DOASIT:
{
  "detail": "the parameter Service Item Parameter Name is either invalid or cannot be passed while creating a payment request for a DOASIT service item",
  "instance": "6a2a48f6-514e-4040-b6fa-57395626a70d",
  "title": "Validation Error",
  "invalidFields": {}
}

I am logged in as a prime user and am using the prime swagger UI. User error on my part?

2023-11-17 20:42 UTC, TevinAdams commented
> Which service item types will this work for? I have tried a few, including DOPSIT and DOFSIT and got the responses of: { "detail": "the parameter Service Item Parameter Name is either invalid or cannot be passed while creating a payment request for a DOPSIT service item", "instance": "8c78492c-5bd1-47ac-ab53-6b9180eb0d7b", "title": "Validation Error", "invalidFields": {} }
> 
> { "detail": "the parameter Service Item Parameter Name is either invalid or cannot be passed while creating a payment request for a DOFSIT service item", "instance": "8d34eb7b-7a65-484b-b962-29004972f51f", "title": "Validation Error", "invalidFields": {} }
> 
> Also tried DOASIT: { "detail": "the parameter Service Item Parameter Name is either invalid or cannot be passed while creating a payment request for a DOASIT service item", "instance": "6a2a48f6-514e-4040-b6fa-57395626a70d", "title": "Validation Error", "invalidFields": {} }
> 
> I am logged in as a prime user and am using the prime swagger UI. User error on my part?

Did you put the shipmentid in the body?

2023-11-17 21:01 UTC, danieljordan-caci commented
> Which service item types will this work for? I have tried a few, including DOPSIT and DOFSIT and got the responses of: { "detail": "the parameter Service Item Parameter Name is either invalid or cannot be passed while creating a payment request for a DOPSIT service item", "instance": "8c78492c-5bd1-47ac-ab53-6b9180eb0d7b", "title": "Validation Error", "invalidFields": {} }
> 
> { "detail": "the parameter Service Item Parameter Name is either invalid or cannot be passed while creating a payment request for a DOFSIT service item", "instance": "8d34eb7b-7a65-484b-b962-29004972f51f", "title": "Validation Error", "invalidFields": {} }
> 
> Also tried DOASIT: { "detail": "the parameter Service Item Parameter Name is either invalid or cannot be passed while creating a payment request for a DOASIT service item", "instance": "6a2a48f6-514e-4040-b6fa-57395626a70d", "title": "Validation Error", "invalidFields": {} }
> 
> I am logged in as a prime user and am using the prime swagger UI. User error on my part?

This looks like you were passing in invalid parameter keys for service items (`Service Item Parameter Name`) is not a valid parameter key - the appropriate keys can be found in the `service_item_param_keys` table.

2023-11-17 22:16 UTC, traskowskycaci commented
> > Which service item types will this work for? I have tried a few, including DOPSIT and DOFSIT and got the responses of: { "detail": "the parameter Service Item Parameter Name is either invalid or cannot be passed while creating a payment request for a DOPSIT service item", "instance": "8c78492c-5bd1-47ac-ab53-6b9180eb0d7b", "title": "Validation Error", "invalidFields": {} }
> > { "detail": "the parameter Service Item Parameter Name is either invalid or cannot be passed while creating a payment request for a DOFSIT service item", "instance": "8d34eb7b-7a65-484b-b962-29004972f51f", "title": "Validation Error", "invalidFields": {} }
> > Also tried DOASIT: { "detail": "the parameter Service Item Parameter Name is either invalid or cannot be passed while creating a payment request for a DOASIT service item", "instance": "6a2a48f6-514e-4040-b6fa-57395626a70d", "title": "Validation Error", "invalidFields": {} }
> > I am logged in as a prime user and am using the prime swagger UI. User error on my part?
> 
> This looks like you were passing in invalid parameter keys for service items (`Service Item Parameter Name`) is not a valid parameter key - the appropriate keys can be found in the `service_item_param_keys` table.

that was indeed one of the issues. had some other issues with the mto shipment i was trying to use missing an address, so created a new move with a new shipment and new service item and that did the trick.

2023-11-17 22:21 UTC, traskowskycaci approved these changes
Hopped on a call with Tevin and he walked me through the process of creating a valid, testable move with associated MTO shipments, service items, and payment requests. Tested adding partial weight as the prime via swagger and it works great. Approving with the caveat that Tevin has more work to do on this to update the prime simulator.

2023-11-20 17:22 UTC, danieljordan-caci requested changes

2023-11-20 17:23 UTC, danieljordan-caci commented on migrations/app/schema/20231106173413_add_weight_column_to_payment_request.up.sql
> +COMMENT ON COLUMN payment_requests.requested_weight_amount IS 'The desired weight amount for the payment request.';
I just realized I wrote these comments but it didn't complete the review. Guess there was an additional step when submitting.

2023-11-20 18:37 UTC, danieljordan-caci commented
Getting this error due to `NULL` values in the db in the `requested_weight_amount` column.
```
"unable to fetch records: sql: Scan error on column index 10, name \"requested_weight_amount\": converting NULL to int is unsupported"
```

Also instead of having an input for the shipment ID in the UI, can you just send the shipment ID that is showing on the page when submitted? Attaching screenshot.
![Screenshot 2023-11-20 at 12 35 53 PM](https://github.com/transcom/mymove/assets/136510600/d42b89dd-9c2c-404d-9f96-2c7fea3c041a)

2023-11-21 15:55 UTC, cameroncaci commented
Marking back to draft as we await new changes per meetings with Daniel and Tevin

2023-11-21 17:21 UTC, TevinAdams commented
> Getting this error due to `NULL` values in the db in the `requested_weight_amount` column.
> 
> ```
> "unable to fetch records: sql: Scan error on column index 10, name \"requested_weight_amount\": converting NULL to int is unsupported"
> ```
> 
> Also instead of having an input for the shipment ID in the UI, can you just send the shipment ID that is showing on the page when submitted? Attaching screenshot. ![Screenshot 2023-11-20 at 12 35 53 PM](https://user-images.githubusercontent.com/136510600/284359951-d42b89dd-9c2c-404d-9f96-2c7fea3c041a.png)

You could but this is no longer needed.

2023-11-21 19:27 UTC, traskowskycaci approved these changes
Looks good. I see the billable weight (cwt) that matches my request.

![image](https://github.com/transcom/mymove/assets/147537467/c7662ce9-a662-4ab2-b201-2710ac022547)

2023-11-21 21:50 UTC, danieljordan-caci requested changes

2023-11-21 21:50 UTC, danieljordan-caci commented on pkg/handlers/primeapi/allowed_payment_service_item_params.go
> +		models.ReServiceCodeDOFSIT: {
Shouldn't this also include `DDFSIT`?

Here's the list I have:
```DOFSIT (Domestic origin 1st day SIT)
DOASIT (Domestic origin add'l SIT)
DOPSIT (Domestic origin SIT pickup)
DOSHUT (Domestic origin shuttle service)
DDFSIT (Domestic destination 1st day SIT)
DDASIT (Domestic destination add'l SIT)
DDDSIT (Domestic destination SIT delivery)
DDSHUT (Domestic destination shuttle service)

2023-11-21 21:56 UTC, danieljordan-caci commented on pkg/handlers/primeapi/allowed_payment_service_item_params.go
> +		models.ReServiceCodeDOFSIT: {
![image](https://github.com/transcom/mymove/assets/136510600/8aee0700-e05e-42c5-bfd4-868de737315e)
On this screenshot I am seeing 1st day SIT items: CWT, Days (Always = 1)

2023-11-21 23:35 UTC, TevinAdams commented on pkg/handlers/primeapi/allowed_payment_service_item_params.go
> +		models.ReServiceCodeDOFSIT: {
I went by the list in the screenshot. DDFSIT = Domestic Destination First Day SIT isn't on the screenshot but I can add it. I had to cross reference the names in the screenshot with the codes in the DB so I might have miss taken one for another.

2023-11-22 13:53 UTC, danieljordan-caci commented on pkg/handlers/primeapi/allowed_payment_service_item_params.go
> +		models.ReServiceCodeDOFSIT: {
It is - you can see it addresses both origin and destination: "Domestic SIT 1st Day & Warehouse"

2023-11-22 14:31 UTC, TevinAdams commented on pkg/handlers/primeapi/allowed_payment_service_item_params.go
> +		models.ReServiceCodeDOFSIT: {
I'll add it.

2023-11-22 14:36 UTC, TevinAdams commented on pkg/handlers/primeapi/allowed_payment_service_item_params.go
> +		models.ReServiceCodeDOFSIT: {
Added

2023-11-22 19:23 UTC, danieljordan-caci approved these changes
LGTM

2023-11-22 19:51 UTC, merged