B 17827 move history logs
transcom/mymove pull request #11585
Opened 2023-11-22 14:44 UTC by paulstonebraker

## [B-17827](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3a862104)

## Summary

MilMove office users need to be able to refer to the Move History component for visibility into events. One request was more information regarding SIT address changes, [found here in this screenshot](https://www13.v1host.com/USTRANSCOM38/attachment.img/855240/move%20history%20.png).

Because of the nature of SIT address changes, and needing to keep track of the previous address(es), all SIT address changes are INSERTS into the address table. As a result, the entries in the audit_history table do not contain relevant information to the SIT or the MTO, they simply contain the insert into the address table.

The approach I chose to use was to add a trigger to the sit_address_updates table, and retrieve the needed information in move_history_fetcher.sql file. I updated the appropriate front end event related constants, and created MoveHistory event templates for each event.

Origin SIT address changes were addressed by @danieljordan-caci in [this commit](https://github.com/transcom/mymove/commit/6be15e28c9e1f4febe6cc181d87ab171edbb1d39).

Please note the value displayed for the initial SIT delivery address is NOT necessarily the most recent change to the origin SIT address. The important information to the office user reviewing the information is the updated SIT delivery in relation to the initial SIT that was submitted.

More information on the technical implementation decisions initially made when creating the History and Audit Log can be found [here](https://dp3.atlassian.net/wiki/spaces/MT/pages/1634992192/PO9+Technical+Implementation).

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### How to test

(if you have a move accessible in an approvals requested stage, jump to step 6)
1. Access the application as a customer; create a new HHG move and submit it
2. Access the application as an office user; login as a services counselor and select the move you created. Fill out required information and Submit move details
3. Sign out and login in a TOO role; access the move and add service items to the shipment
4. Sign out and login in a PRIME role; access the move and add service item. Fill out the required information for a Destination SIT and create the service item
5. Sign out and login in a TOO role; access the move and approve the destination SIT requested service items on the Move task order tab
6. Sign out and login in a PRIME role; access the move and click Update Service Items. Fill out the Request Destination SIT Address Change form and save
7. Sign out and login in a TOO role; access the move and navigate to the move history. Note the entry for the destination SIT delivery address change by the PRIME
![image](https://github.com/transcom/mymove/assets/147535220/6fe61a17-2907-4a3e-acae-1f04c548fedf)
8. Navigate to Move task order tab and review the request for the Domestic destination SIT delivery address change. Enter remarks and reject the change.
9. Navigate back to Move history tab and note the entry for the rejection of the prime's request for destination SIT delivery address change by the TOO
![image](https://github.com/transcom/mymove/assets/147535220/da6fd9ab-9146-4331-af6b-ab08b57c87ce)
10. Navigate back to Move task order tab and edit the destination SIT delivery address.
11. Navigate back to Move history and note the entry for the updated destination SIT delivery address by the TOO
![image](https://github.com/transcom/mymove/assets/147535220/4dd4478a-8533-4545-a4c3-df7214eb8a8b)
12. Sign out and login in a PRIME role; access the move and click Update Service Items. Fill out the Request Destination SIT Address Change form and save
13. Sign out and login in a TOO role; navigate to the Move task order tab and accept the request to update destination SIT delivery address.
14. Navigate to move history tab and note the entry approving the requested destination SIT delivery change
![image](https://github.com/transcom/mymove/assets/147535220/c20f06a7-c7df-449d-8dfa-2be6a5450012)

2023-11-27 20:58 UTC, joeydoyecaci commented
I tried updating a service item as a prime user and It causes my session to crash. Attached console output. ![image](https://github.com/transcom/mymove/assets/150186792/239c9eef-b8d4-4dac-84d5-53bcfc460b91)

2023-11-27 21:05 UTC, danieljordan-caci commented
The `audit_history` table only cares about these three actions:
- `UPDATE`
- `INSERT`
- `DELETE``

Anytime those actions are performed, a row is added to the table and stores an `event_name` to the table (which is the name of an API call associated with the action). Looking at your AC:
- TOO editing SIT destination delivery address or -SIT origin pickup- address
   - This can have the event name of `updateMTOShipment` if not providing a final address
   - If it's a final address specifically for delivery, then they need to request it first
- TOO approving a Prime request to change SIT destination delivery address
   - This has the event name of `approveSITAddressUpdate`
- TOO rejecting a Prime request to change SIT destination delivery address
   - This has the event name of `rejectSITAddressUpdate`
- Prime has submitted a request to change SIT destination delivery address
   - This has the event name of `createSITAddressUpdateRequest`
   
When considering the Audit Log, each event name can have it's own component that renders. Have you looked into this? Did you run into any issues? You could render different components (AKA different text formatting, displays, etc) based on what the value in the `changed_data` column reads.

2023-11-27 21:27 UTC, danieljordan-caci commented
I know that's a little vague, but you can find some direction in `src/constants/MoveHistory/EventTemplates/index.js`:
```
export { default as acknowledgeExcessWeightRisk } from './AcknowledgeExcessWeightRisk/acknowledgeExcessWeightRisk';
export { default as approveShipment } from './ApproveShipment/approveShipment';
export { default as approveShipmentDiversion } from './ApproveShipmentDiversion/approveShipmentDiversion';
export { default as createBasicServiceItem } from './UpdateMoveTaskOrderStatus/createBasicServiceItem';
export { default as createMTOServiceItem } from './CreateMTOServiceItem/createMTOServiceItem';
export { default as createMTOServiceItemCustomerContacts } from './CreateMTOServiceItem/createMTOServiceItemCustomerContacts';
export { default as createMTOServiceItemDimensions } from './CreateMTOServiceItem/createMTOServiceItemDimensions';
export { default as createMTOShipment } from './CreateMTOShipment/createMTOShipment';
export { default as createAddresses } from './UpdateAddress/createAddress';
export { default as createMTOShipmentAgent } from './UpdateMTOShipment/createMTOShipmentAgent';
export { default as createOrders } from './CreateOrders/createOrders';
export { default as createEntitlements } from './CreateOrders/createEntitlements';
export { default as createMoves } from './CreateOrders/createMoves';
export { default as createPaymentRequest } from './CreatePaymentRequest/createPaymentRequest';
export { default as createPaymentRequestReweighUpdate } from './UpdateReweigh/createPaymentRequest';
export { default as createPaymentRequestShipmentUpdate } from './UpdateMTOShipment/createPaymentRequestShipmentUpdate';
export { default as createReweighRequestWeightUpdate } from './UpdateMTOShipment/createReweighRequestWeightUpdate';
export { default as createStandardServiceItem } from './ApproveShipment/createStandardServiceItem';
export { default as deleteShipment } from './DeleteShipment/deleteShipment';
export { default as proofOfServiceDocUpload } from './CreateUpload/proofOfServiceDocUpload';
export { default as requestShipmentCancellation } from './RequestShipmentCancellation/requestShipmentCancellation';
export { default as requestShipmentDiversion } from './RequestShipmentDiversion/requestShipmentDiversion';
export { default as requestShipmentReweigh } from './RequestShipmentReweigh/requestShipmentReweigh';
export { default as setFinancialReviewFlag } from './SetFinancialReviewFlag/setFinancialReviewFlag';
export { default as submitMoveForApproval } from './SubmitMoveForApproval/submitMoveForApproval';
export { default as updateAllowance } from './UpdateAllowances/updateAllowance';
export { default as updateBillableWeight } from './UpdateBillableWeight/updateBillableWeight';
export { default as updateBillableWeightAsTIO } from './UpdateBillableWeight/updateBillableWeightAsTIO';
export { default as updateBillableWeightRemarksAsTIO } from './UpdateBillableWeight/updateBillableWeightRemarksAsTIO';
export { default as updateMoveTaskOrderStatus } from './UpdateMoveTaskOrderStatus/updateMoveTaskOrderStatus';
export { default as updateMTOServiceItem } from './UpdateMTOServiceItem/updateMTOServiceItem';
export { default as updateMTOShipment } from './UpdateMTOShipment/updateMTOShipment';
export { default as updateMTOShipmentAgent } from './UpdateMTOShipment/updateMTOShipmentAgent';
export { default as updateMTOShipmentDeprecatePaymentRequest } from './UpdateMTOShipment/updateMTOShipmentDeprecatePaymentRequest';
export { default as reweighPaymentRequest } from './UpdateReweigh/updatePaymentRequest';
export { default as updateOrder } from './UpdateOrders/updateOrder';
export { default as updatePaymentRequest } from './UpdatePaymentRequest/updatePaymentRequest';
export { default as updatePaymentRequestJobRunner } from './UpdatePaymentRequest/updatePaymentRequestJobRunner';
export { default as updatePaymentRequestStatus } from './UpdatePaymentRequestStatus/updatePaymentRequestStatus';
export { default as updateReweighWeight } from './UpdateReweigh/updateReweighWeight';
export { default as updateServiceItemStatus } from './UpdateServiceItemStatus/updateServiceItemStatus';
export { default as updateMTOReviewedBillableWeightsAt } from './UpdateMTOReviewedBillableWeightAt/updateMTOReviewedBillableWeightsAt';
export { default as uploadAmendedOrders } from './UploadAmendedOrders/uploadAmendedOrders';
export { default as updateMTOShipmentStatus } from './UpdateMTOShipmentStatus/updateMTOShipmentStatus';
export { default as updateMTOServiceItemMoveStatus } from './CreateMTOServiceItem/createMTOServiceItemUpdateMoveStatus';
export { default as updateMoveEstimatedExcessWeight } from './UpdateMTOShipment/updateMTOShipmentPrimeEstimatedExcessWeight';
export { default as updateMTOStatusServiceCounselingCompleted } from './UpdateMTOStatusServiceCounselingCompleted/updateMTOStatusServiceCounselingCompleted';
export { default as updateAllowanceByCounselor } from './UpdateAllowances/updateAllowanceByCounselor';
export { default as updateServiceMemberByCounselor } from './UpdateServiceMember/updateServiceMemberByCounselor';
export { default as updateServiceMemberByTOO } from './UpdateServiceMember/updateServiceMemberByTOO';
export { default as createServiceMember } from './CreateServiceMember/createServiceMember';
export { default as patchServiceMember } from './PatchServiceMember/patchServiceMember';
export { default as updateAddress } from './UpdateAddress/updateAddress';
export { default as createUpload } from './CreateUpload/createUpload';
export { default as deleteUpload } from './DeleteUpload/deleteUpload';
export { default as updateServiceMemberBackupContacts } from './UpdateServiceMemberBackupContact/updateServiceMemberBackupContact';
export { default as createServiceMemberBackupContacts } from './CreateServiceMemberBackupContact/createServiceMemberBackupContact';
export { default as updateCustomer } from './UpdateCustomer/updateCustomer';
export { default as updateServiceItemSitEntryDate } from './UpdateSITEntryDate/updateSitEntryDate';
export { default as createDestinationSITUpdateRequest } from './CreateSITRequest/CreateSITAddressUpdateRequest';
export { default as approveSITAddressUpdate } from './UpdateSITAddress/ApproveSITAddressUpdate';
export { default as rejectSITAddressUpdate } from './UpdateSITAddress/RejectSITAddressUpdate';
export { default as createSITAddressUpdate } from './UpdateSITAddress/CreateSITAddressUpdate';
```

Each one of these represents an `event_name` in the `audit_history` table. So if that event was used in the move's history, then the specific component listed in the path renders.

So for `updateMTOShipment` event, it renders just a bland component:
```
export default {
  action: a.UPDATE,
  eventName: o.updateMTOShipment,
  tableName: t.mto_shipments,
  getEventNameDisplay: () => 'Updated shipment',
  getDetails: (historyRecord) => <LabeledDetails historyRecord={formatChangedValues(historyRecord)} />,
};
```

You could check what gets returned in the `historyRecord` and the `changedValues` object and render specific components based off of that, but honestly if we are talking about SIT destination delivery updates from the TOO - that'd be an easy check:
- Check if `destination_address_id` is in `changedValues`
- If so, render this component that displays the address (similar to what the `updateAddress.jsx` component is doing in `src/constants/MoveHistory/EventTemplates/UpdateAddress`

I'm not saying this is what you need to do, but this is what is currently being done for other move history logs and events. Let me know if ya got questions.

2023-11-27 21:29 UTC, danieljordan-caci commented
> I tried updating a service item as a prime user and It causes my session to crash. Attached console output. ![image](https://private-user-images.githubusercontent.com/150186792/286013606-239c9eef-b8d4-4dac-84d5-53bcfc460b91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMTk4NTYsIm5iZiI6MTcwMTExOTU1NiwicGF0aCI6Ii8xNTAxODY3OTIvMjg2MDEzNjA2LTIzOWM5ZWVmLWI4ZDQtNGRhYy04NGQ1LTUzYmNmYzQ2MGI5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyN1QyMTEyMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYjQ3OTg2YzkwZWU5OTdiNGExOGJjOWM0OTBmOGJkOTJhOTFjZjgyNzZmYjkwNzA0NWEyNTA2YzMzYjY2NjI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AhLGQ-MVpheUCplSBj7k-whSnBoCgSsibgeIz4Hm3Zw)

Seems like the `final_destination_address_id` column is empty for a service item in that shipment when it shouldn't be maybe?

2023-11-27 22:29 UTC, paulstonebraker commented
@danieljordan-caci thanks for all the info! I will give it a more thorough read, but upon a once over, I think I employed most of what you described in my approach. I think the biggest obstacle was that address changes for destination SITs are all inserts into the address table, not updates. So the old_data column returned from the DB is blank, and the changed_data column doesn't have anything relevant to the SIT/Move. A destination SIT address update made by a TOO looks like this in our audit logs currently

![image](https://github.com/transcom/mymove/assets/147535220/31027d56-568c-4001-8038-9018320a7e17)

and 'sit_destination_final_address_id' (the column updated on the mto_service_items table) is an ignored column on our trigger

2023-11-27 22:40 UTC, danieljordan-caci commented
> @danieljordan-caci thanks for all the info! I will give it a more thorough read, but upon a once over, I think I employed most of what you described in my approach. I think the biggest obstacle was that address changes for destination SITs are all inserts into the address table, not updates. So the old_data column returned from the DB is blank, and the changed_data column doesn't have anything relevant to the SIT/Move. The old_data and changed_data columns for a destination SIT address update made by a TOO look like this in our audit logs currently
> 
> ![image](https://private-user-images.githubusercontent.com/147535220/286034303-31027d56-568c-4001-8038-9018320a7e17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMjQ3OTAsIm5iZiI6MTcwMTEyNDQ5MCwicGF0aCI6Ii8xNDc1MzUyMjAvMjg2MDM0MzAzLTMxMDI3ZDU2LTU2OGMtNDAwMS04MDM4LTkwMTgzMjBhN2UxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyN1QyMjM0NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02N2MwMjQ4NmM5YWY1MWEzNzIzOTMyZmUwMTA0MTkxNDE3NjM4Mzk4MmI0NjJlYTRkZjU1Nzk5ZDU4NTUwMjkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sS5isV_GmHM569y911oeigea3TEFS6q2wiGrHyseU-w)
> 
> and sit_destination_final_address_id of mto_service_items table is an ignored column on our trigger, so that doesn't populate this particular action in our logs either

So when you're signed in as the TOO and update either the pickup/delivery address, what is the `event_name` that populates in the `audit_history` table?

2023-11-27 22:43 UTC, paulstonebraker commented
> > @danieljordan-caci thanks for all the info! I will give it a more thorough read, but upon a once over, I think I employed most of what you described in my approach. I think the biggest obstacle was that address changes for destination SITs are all inserts into the address table, not updates. So the old_data column returned from the DB is blank, and the changed_data column doesn't have anything relevant to the SIT/Move. The old_data and changed_data columns for a destination SIT address update made by a TOO look like this in our audit logs currently
> > ![image](https://private-user-images.githubusercontent.com/147535220/286034303-31027d56-568c-4001-8038-9018320a7e17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMjQ3OTAsIm5iZiI6MTcwMTEyNDQ5MCwicGF0aCI6Ii8xNDc1MzUyMjAvMjg2MDM0MzAzLTMxMDI3ZDU2LTU2OGMtNDAwMS04MDM4LTkwMTgzMjBhN2UxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyN1QyMjM0NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02N2MwMjQ4NmM5YWY1MWEzNzIzOTMyZmUwMTA0MTkxNDE3NjM4Mzk4MmI0NjJlYTRkZjU1Nzk5ZDU4NTUwMjkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sS5isV_GmHM569y911oeigea3TEFS6q2wiGrHyseU-w)
> > and sit_destination_final_address_id of mto_service_items table is an ignored column on our trigger, so that doesn't populate this particular action in our logs either
> 
> So when you're signed in as the TOO and update either the pickup/delivery address (are you just updating the shipment address?), what is the `event_name` that populates in the `audit_history` table?

This is just for the destination SIT address changes. The event name for a TOO changing the destination SIT address is ```createSITAddressUpdate```

2023-11-28 00:09 UTC, joeydoyecaci commented
> > I tried updating a service item as a prime user and It causes my session to crash. Attached console output. ![image](https://private-user-images.githubusercontent.com/150186792/286013606-239c9eef-b8d4-4dac-84d5-53bcfc460b91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMTk4NTYsIm5iZiI6MTcwMTExOTU1NiwicGF0aCI6Ii8xNTAxODY3OTIvMjg2MDEzNjA2LTIzOWM5ZWVmLWI4ZDQtNGRhYy04NGQ1LTUzYmNmYzQ2MGI5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyN1QyMTEyMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYjQ3OTg2YzkwZWU5OTdiNGExOGJjOWM0OTBmOGJkOTJhOTFjZjgyNzZmYjkwNzA0NWEyNTA2YzMzYjY2NjI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AhLGQ-MVpheUCplSBj7k-whSnBoCgSsibgeIz4Hm3Zw)
> 
> Seems like the `final_destination_address_id` column is empty for a service item in that shipment when it shouldn't be maybe?

That's what I'm seeing at this point. I've been able to get past this issue when using own profile rather than the pre-existing ones in dev.

2023-11-28 14:20 UTC, danieljordan-caci commented
> > > I tried updating a service item as a prime user and It causes my session to crash. Attached console output. ![image](https://private-user-images.githubusercontent.com/150186792/286013606-239c9eef-b8d4-4dac-84d5-53bcfc460b91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMTk4NTYsIm5iZiI6MTcwMTExOTU1NiwicGF0aCI6Ii8xNTAxODY3OTIvMjg2MDEzNjA2LTIzOWM5ZWVmLWI4ZDQtNGRhYy04NGQ1LTUzYmNmYzQ2MGI5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyN1QyMTEyMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYjQ3OTg2YzkwZWU5OTdiNGExOGJjOWM0OTBmOGJkOTJhOTFjZjgyNzZmYjkwNzA0NWEyNTA2YzMzYjY2NjI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AhLGQ-MVpheUCplSBj7k-whSnBoCgSsibgeIz4Hm3Zw)
> > 
> > 
> > Seems like the `final_destination_address_id` column is empty for a service item in that shipment when it shouldn't be maybe?
> 
> That's what I'm seeing at this point. I've been able to get past this issue when using own profile rather than the pre-existing ones in dev.

Yeah some of that test data needs to be addressed and adjusted to include some fields to avoid silly errors like this. Oh well.

2023-11-28 14:45 UTC, danieljordan-caci requested changes
Lotta good stuff here! Got some changes I would appreciate but feel free to let me know if you have any thoughts on any of the changes!

2023-11-28 14:45 UTC, danieljordan-caci commented on src/constants/MoveHistory/EventTemplates/CreateSITRequest/CreateSITAddressUpdateRequest.jsx
> +    return <div>Updated service item</div>;
Personally, I'd like for this to be more specific to what the event was. For example, this will display when the Prime requests a delivery address change for a SIT item. So do you think a more appropriate value to display in this `div` would be: `SIT Address Change Request` or something similar?

2023-11-28 14:45 UTC, danieljordan-caci commented on src/constants/MoveHistory/EventTemplates/UpdateSITAddress/ApproveSITAddressUpdate.jsx
> +    return <div>Updated service item</div>;
Same for this event - Instead of `Updated service item`, maybe `Approved SIT Address Update` or whatever?

2023-11-28 14:45 UTC, danieljordan-caci commented on src/constants/MoveHistory/EventTemplates/UpdateSITAddress/CreateSITAddressUpdate.jsx
> +    return <div>Updated service item</div>;
Maybe `Updated SIT Address`?

2023-11-28 14:45 UTC, danieljordan-caci commented on src/constants/MoveHistory/EventTemplates/UpdateSITAddress/RejectSITAddressUpdate.jsx
> +    return <div>Updated service item</div>;
`Rejected SIT Address Update`?

2023-11-28 14:45 UTC, danieljordan-caci commented on src/utils/formatSITData.js
> +const formatStatus = (changedValues, eventName) => {
I value comments a lot - could you maybe put a comment above each function briefly describing what it's doing so it's easier to diagnose at a quick glance?

2023-11-28 14:48 UTC, paulstonebraker commented on src/utils/formatSITData.js
> +const formatStatus = (changedValues, eventName) => {
Thats a great idea, will do. Thanks!

2023-11-28 16:18 UTC, joeydoyecaci commented on src/constants/MoveHistory/EventTemplates/UpdateSITAddress/ApproveSITAddressUpdate.jsx
> +
Minor nitpick, I've noticed the same code pattern occurring between the Approve,Create,Reject components. Because we know the component behavior won't change regardless of it being representative of an Approval or a Rejection, I think you only need one component to accomplish the goals of this component. If you were to consolidate to one for SITAddressUpdate, then inject your constants into the component, along with the message it would return.

2023-11-28 19:53 UTC, paulstonebraker commented on src/utils/formatSITData.js
> +  if (context[0].sit_destination_address_final) {
good call!

2023-11-28 20:18 UTC, paulstonebraker commented on src/constants/MoveHistory/EventTemplates/UpdateSITAddress/ApproveSITAddressUpdate.jsx
> +
I looked into this but this adheres to the current design pattern for our Move history and event templates, I believe.

2023-11-28 21:01 UTC, joeydoyecaci commented on src/constants/MoveHistory/EventTemplates/UpdateSITAddress/ApproveSITAddressUpdate.jsx
> +
Ok, no problem. It's just something I've noticed.

2023-11-28 21:05 UTC, paulstonebraker commented on src/constants/MoveHistory/EventTemplates/CreateSITRequest/CreateSITAddressUpdateRequest.jsx
> +    return <div>Updated service item</div>;
While I initially thought this (and the below) semantic name changes would be good, after looking at them in the UI, it is not in style with a lot the other Move history event names. Currently, move events are pretty general; for example, requestShipmentDiversion reads: "Update move" rather that "Move Diversion Request", with "Requested diversion for ___" in the details column.

In my opinion, we should keep this PR as is: event columns are more general and less specific, with details in the details column. If we feel strongly otherwise or would like to make things more specific in the events column going forward, I'd be happy to change it.

2023-11-29 15:10 UTC, paulstonebraker commented
@danieljordan-caci Updated with comments

@joeydoyecaci Updated with changes per your comments

Please give them a once over when convenient

2023-11-29 20:52 UTC, loganwc approved these changes

2023-11-29 21:03 UTC, joeydoyecaci approved these changes

2023-11-30 14:28 UTC, danieljordan-caci approved these changes
If you're good with it, I'm good with it! LGTM.

2023-11-30 14:58 UTC, merged