B 17814 Removing references to Fort Benning and removing incorrect link between Fort Walker and Fort Benning.
transcom/mymove pull request #11587
Opened 2023-11-22 15:15 UTC by traskowskycaci

Removing references to Fort Benning and removing incorrect link between Fort Walker and Fort Benning

## [Agility ticket](https://www13.v1host.com/USTRANSCOM38/TeamRoom.mvc/Show/808731)

## Summary

Fort Benning was renamed to Fort Moore. Fort A.P. Hill was renamed to Fort Walker. There was an incorrect link in the database between Fort Benning and Fort Walker, which is incorrect. The zip codes of 31905 and 31995 should be associated with Fort Moore, GA, instead of Fort Walker, GA.

This also contains a rename of Blackstone, VA in the duty locations table to Fort Barfoot/Blackstone, VA so that when users type in Fort Barfoot, they can see Fort Barfoot in the search results.

## Verification Steps for the Author

- [x] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [x] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the milmove application
2. Login as a customer starting a new move.
3. Type in Fort Barfoot and you should see Fort Barfoot/Blackstone, VA
4. Type in Ft Benning and no Fort Benning values should display.
5. Type in Ft Walker and it should display Fort Walker, VA 22427.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2023-11-22 17:12 UTC, deandreJones commented on migrations/app/schema/20231116162824_update_addresses_table_with_new_base_names.up.sql
> +
how sure are we that the Ids for the cities are the same across each environment?

2023-11-22 17:19 UTC, traskowskycaci commented on migrations/app/schema/20231116162824_update_addresses_table_with_new_base_names.up.sql
> +
That is a great question. I can change it to be based off a combination of street_address_1, street_address_2, and postal code, and city. Should I change all these to not use the id?

2023-11-22 17:22 UTC, danieljordan-caci commented on migrations/app/schema/20231116162824_update_addresses_table_with_new_base_names.up.sql
> +
We are following previous implementations done by Truss - I have very minimal doubts that we will run into issues with this since I've tested this in multiple environments and got the same results (dev, exp, stg).

2023-11-22 17:34 UTC, danieljordan-caci approved these changes

2023-11-22 20:54 UTC, deandreJones commented on migrations/app/schema/20231116162824_update_addresses_table_with_new_base_names.up.sql
> +
right- i think with the app being fresh and newish this is probably ok..
but as things evolve, its just not a good idea to assume that ids will always be the same across environments, especially when DB scripts can be applied to specific environments and could mess up the ordering

2023-11-22 20:55 UTC, deandreJones commented on migrations/app/schema/20231116162824_update_addresses_table_with_new_base_names.up.sql
> +
i lean toward adding a sub select statement or join to ensure you always grab right row for update

2023-11-24 17:58 UTC, traskowskycaci commented on migrations/app/schema/20231116162824_update_addresses_table_with_new_base_names.up.sql
> +
Changed the updates to be based on zip code and city names. This actually caught a few more lines that needed to be updated. I matched zip codes up to the 'Duty Locations Final' spreadsheet.

2023-11-27 14:29 UTC, deandreJones commented on migrations/app/schema/20231116162824_update_addresses_table_with_new_base_names.up.sql
> +UPDATE addresses SET city = 'Fort Cavazos' WHERE city in ('Fort Hood', 'FORT HOOD') and postal_code = '76544';
instead of filitering off the lower and upper case - use the "UPPER()" function
`UPDATE addresses SET city = 'Fort Cavazos' WHERE UPPER(city) =  'FORT HOOD' and postal_code = '76544';`

2023-11-27 14:49 UTC, cameroncaci requested changes
Accidentally forgot to include these comments in the previous change requests

2023-11-27 14:49 UTC, cameroncaci commented on pkg/handlers/internalapi/moves_test.go
> +				City:           "Fort Eisenhower",
Another occurrence of Augusta city name change

2023-11-27 14:49 UTC, cameroncaci commented on pkg/handlers/internalapi/service_members_test.go
>  				State:          "GA",
Another occurrence of Augusta city name change

2023-11-27 14:49 UTC, cameroncaci commented on pkg/services/payment_request/payment_request_recalculator_test.go
> +				City:           "Fort Eisenhower",
Another occurrence of Augusta city name change

2023-11-27 14:49 UTC, cameroncaci commented on pkg/services/payment_request/payment_request_creator_test.go
> +				City:           "Fort Eisenhower",
Another occurrence of Augusta city name change

2023-11-27 14:49 UTC, cameroncaci commented on pkg/services/order/order_fetcher_test.go
> +					City:           "Fort Eisenhower",
Another occurrence of Augusta city name change

2023-11-27 14:49 UTC, cameroncaci commented on pkg/testdatagen/make_duty_location.go
> +			City:       "Fort Eisenhower",
Another occurrence of Augusta city name change

2023-11-27 14:50 UTC, traskowskycaci commented on pkg/factory/duty_location_factory.go
> +				City:       "Fort Eisenhower",
I am going off of the 'Duty Locations Final' spreadsheet from the story initially and see the city is named Fort Eisenhower there. 
![image](https://github.com/transcom/mymove/assets/147537467/9241d475-629f-4abe-b969-55a5438359b3)

2023-11-27 14:52 UTC, traskowskycaci commented on pkg/factory/duty_location_factory.go
> +				City:       "Fort Eisenhower",
These are the zips I see for Augusta. ![image](https://github.com/transcom/mymove/assets/147537467/58f59a60-c58b-4a53-8a8f-bf6e07b90194)

2023-11-27 14:54 UTC, cameroncaci commented on pkg/factory/duty_location_factory.go
> +				City:       "Fort Eisenhower",
Tracking, thank you for clarifying. Could you update the comment to reflect the new changes?

2023-11-27 14:59 UTC, traskowskycaci commented on pkg/factory/duty_location_factory.go
> +				City:       "Fort Eisenhower",
Done, thanks for the catch!

2023-11-27 15:02 UTC, traskowskycaci commented on migrations/app/schema/20231116162824_update_addresses_table_with_new_base_names.up.sql
> +UPDATE addresses SET city = 'Fort Cavazos' WHERE city in ('Fort Hood', 'FORT HOOD') and postal_code = '76544';
Done, looks cleaner that way. Thanks!

2023-11-27 21:21 UTC, merged