B 17781 billing sit fsc
transcom/mymove pull request #11604
Opened 2023-11-28 15:47 UTC by WeatherfordAaron

## [Agility ticket](tbd)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test (after make server_run and make client_run)
1. Navigate to the mymove folder via Terminal and run the following command:
```npx playwright test --ui```
2. Run the test in txo > sitUpdates.spec.js > During ZIP update test

The test simulates the following actions that would be taken:
1. Create Move (HHG)
2. Counselor Approves move
3. TOO Approves move
4. Prime Updates Shipment
5. Prime Adds (Destination) SIT Service Item
6. TOO Accepts
7. Prime updates Service Item to change zip to >50 miles
8. TOO Approves zip update
9. Prime submits payment request (Select only SIT Delivery destination, SIT Fuel Charge)
10. TIO Views requests (ZIP should match the one that it was changed to)

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2023-11-28 17:44 UTC, taeJungCaci commented
I think you accidentally committed when server was doing it's build. May want to revert [created test](https://github.com/transcom/mymove/pull/11604/commits/13ba05e9823756fb63a8e5c21f46fa1d500ab2aa) commit as it deleted a lot of files.

2023-11-28 18:39 UTC, WeatherfordAaron reviewed
Note: This was something that automatically happened. I corrected it by rebasing the branch and then re-applying only the files that were edited

2023-11-28 18:40 UTC, WeatherfordAaron reviewed
This commit should represent the final completed changes for the test

2023-11-28 18:58 UTC, brooklyn-welsh commented
To fix the import statements that CircleCI and VSCode is complaining about, try running steps 2 and 3 from here https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#importing-dependencies 
 
 I don't think steps 4 and 5 are necessary, just doing 2 and 3 fixed it for me.

2023-11-28 22:56 UTC, taeJungCaci commented on pkg/services/sit_address_update/sit_address_update_request_approver.go
> +		relatedDestinationSITFuelCharge, err := models.FetchRelatedDestinationSITFuelCharge(txnAppCtx.DB(), serviceItem.ID)
Test cases are failing because this returns error when there are no related destination FSC if fetched. Need to catch that case so runs rest of the code instead of returning an error.

2023-11-29 13:56 UTC, WeatherfordAaron commented on pkg/services/sit_address_update/sit_address_update_request_approver.go
> +		relatedDestinationSITFuelCharge, err := models.FetchRelatedDestinationSITFuelCharge(txnAppCtx.DB(), serviceItem.ID)
ah ok. ty
How did you find that issue? I didn't see that error anywhere.

2023-11-29 17:57 UTC, taeJungCaci commented on pkg/services/sit_address_update/sit_address_update_request_approver.go
> +
I think adding a check before doing the fetching and updating for `relatedDestinationSITFuelCharge` should resolve the test cases that are failing. My suggestion should be add a variable like shown below or something similar.


```suggestion
		relatedDestinationSITFuelCharge, err := models.FetchRelatedDestinationSITFuelCharge(txnAppCtx.DB(), serviceItem.ID)
		relatedDestinationFSCAvailable := true
		if err != nil {
			if errors.Is(err, sql.ErrNoRows) {
				relatedDestinationFSCAvailable = false
				txnAppCtx.Logger().Error("When attempting to update the SIT Destination Fuel Service Charge, no associated FSC was found.")
			} else {
				return err
			}
		}
		if relatedDestinationFSCAvailable {
			serviceItemFSC, err := models.FetchServiceItem(txnAppCtx.DB(), relatedDestinationSITFuelCharge.ID)
			if err != nil {
				return err
			}

			_, err = f.updateServiceItemFinalAddress(txnAppCtx, serviceItemFSC, sitAddressUpdateRequest)
			if err != nil {
				return err
			}
		}

```

2023-11-29 20:10 UTC, WeatherfordAaron commented on pkg/services/sit_address_update/sit_address_update_request_approver.go
> +
Are you seeing a specific place where it says that's the issue? .. because the errors I'm seeing, I'm not sure this would cause that error.. also, I made a variation of the changes and still cannot get the # of server errors to reduce.

2023-11-29 21:57 UTC, taeJungCaci approved these changes
LGTM!

2023-11-29 23:19 UTC, brooklyn-welsh commented on playwright/tests/office/txo/sitUpdates.spec.js
> -// @ts-check
I'll echo Tae's sentiment here, that we definitely want to add this line back in (enables TypeScript error checking for the file).

But other than that the PR looks good to me, will approve after its added back.

2023-11-29 23:27 UTC, WeatherfordAaron commented on playwright/tests/office/txo/sitUpdates.spec.js
> -// @ts-check
ah so i did a bad thing ok

2023-11-29 23:27 UTC, JamesHawks224 requested changes
Test was successful.  Only saw 1 minor change.  Otherwise, code looks good.

2023-11-29 23:27 UTC, JamesHawks224 commented on pkg/models/mto_service_items.go
> +            WHERE res.code IN (?) AND mto_shipment_id IN (
"WHERE res.code IN (?) AND mto_shipment_id"
"mto_shipment_id" is missing a table alias e.g. "res.mto_shipment_id".

2023-11-29 23:41 UTC, WeatherfordAaron commented on playwright/tests/office/txo/sitUpdates.spec.js
> -// @ts-check
3:10  warning  'check' is defined but never used  @typescript-eslint/no-unused-vars

2023-11-29 23:41 UTC, WeatherfordAaron commented on pkg/models/mto_service_items.go
> +            WHERE res.code IN (?) AND mto_shipment_id IN (
ok I made that change and re-commited and pushed. Once the CircleCI re-test has completed, I should be good to go.

2023-11-30 00:43 UTC, WeatherfordAaron commented on playwright/tests/office/txo/sitUpdates.spec.js
> -// @ts-check
nm fixed

2023-11-30 14:55 UTC, taeJungCaci commented on pkg/models/mto_service_items.go
> +            WHERE res.code IN (?) AND mto_shipment_id IN (
Should the alias be msi instead of res? I don't think `mto_shipment_id` is in the table `re_services res` but it is in `mto_services_items`. I don't know if it automatically grabs from the `mto_service_items` table if you don't specify alias.

2023-11-30 14:55 UTC, taeJungCaci commented on pkg/models/mto_service_items.go
> +                SELECT res.mto_shipment_id FROM mto_service_items WHERE id = ?)`, ReServiceCodeDDSFSC, mtoServiceItemID).First(&serviceItem)
I don't think putting `res` alias in here works and should be left without it.

2023-11-30 15:00 UTC, brooklyn-welsh commented on pkg/models/mto_service_items.go
> +                SELECT res.mto_shipment_id FROM mto_service_items WHERE id = ?)`, ReServiceCodeDDSFSC, mtoServiceItemID).First(&serviceItem)
Agree, I think it's `msi` and not `res`. I was going to suggest that this could be simplified to 
`SELECT msi.id
            FROM mto_service_items msi
            INNER JOIN re_services res ON msi.re_service_id = res.id
            WHERE res.code = ? AND msi.mto_shipment_id = ?`
            
If I'm not mistaken?

2023-11-30 15:01 UTC, taeJungCaci commented on pkg/models/mto_service_items.go
> +            WHERE res.code IN (?) AND res.mto_shipment_id IN (
Related https://github.com/transcom/mymove/pull/11604#discussion_r1410740498

2023-11-30 15:06 UTC, brooklyn-welsh commented on pkg/models/mto_service_items.go
> +            WHERE res.code IN (?) AND res.mto_shipment_id IN (
(Pasted from [#11604 (comment)](https://github.com/transcom/mymove/pull/11604#discussion_r1410740498))

Agree, I think it's msi and not res. I was going to suggest that this could be simplified to
SELECT msi.id FROM mto_service_items msi INNER JOIN re_services res ON msi.re_service_id = res.id WHERE res.code = ? AND msi.mto_shipment_id = ?

If I'm not mistaken?

2023-11-30 15:26 UTC, WeatherfordAaron commented on pkg/models/mto_service_items.go
> +            WHERE res.code IN (?) AND mto_shipment_id IN (
You guys are right. I made the change and checked in the DB this time to verify that I was entering the correct sql syntax.

2023-11-30 17:02 UTC, JamesHawks224 commented on pkg/models/mto_service_items.go
> +            WHERE res.code IN (?) AND res.mto_shipment_id IN (
re: mto_shipment_id table alias
When I wrote my comment, the point of the comment was that a table alias needed to be added to the field and I gave an example (i.e. tbl alias.field). It was not meant to be the actual change.  I probably should've actually researched it and gave the actual change.  My apologies for the confusion.

I took the sql and got it to execute in DBeaver.  Correct, its msi.mto_shipment_id.

2023-11-30 17:13 UTC, JamesHawks224 commented on pkg/models/mto_service_items.go
> +            WHERE res.code IN (?) AND res.mto_shipment_id IN (
re: removing the sub-select

According to what I'm seeing, I believe the sub-select should be kept.

What I'm seeing... 
The sub-select is getting the mto_shipment_id for that service item id.
The outer query is getting a list of service item ids for the selected shipment id.
Based on the query, I presume there can be multiple service items for a given shipment id.

2023-11-30 17:14 UTC, JamesHawks224 approved these changes

2023-11-30 17:29 UTC, brooklyn-welsh approved these changes
Now that the SQL is fixed, everything looks good to me. Approving.

2023-11-30 17:31 UTC, KonstanceH approved these changes
All added tests and Intended functionality is working for me

2023-11-30 17:34 UTC, merged