B 18331 add ppm closeout office to move details
transcom/mymove pull request #11650
Opened 2023-12-13 20:07 UTC by pambecker

[B-18331] populate data in Closeout office field under Move Details

Summary
The QAE and TOO users should be able to see the Closeout office under the Move Details section.

Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

How to test

1. Login as a QAE role
2. Access a PPM move
3. Verify that the Closeout Office field appears under the Destination ZIP field and that it's populated with data if the Closeout Office exists.  This should be available for both Approved Shipments and Requested Shipments.
4.  Login as a TOO role and repeat the steps above.

Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

2023-12-14 04:55 UTC, paulstonebraker approved these changes

2023-12-14 14:30 UTC, danieljordan-caci requested changes
Could you also update `RequestedShipments.test.jsx` to reflect these changes?

2023-12-15 18:10 UTC, paulstonebraker approved these changes

2023-12-15 20:27 UTC, r-mettler approved these changes

2023-12-15 21:02 UTC, merged