B 18259
transcom/mymove pull request #11668
Opened 2023-12-19 15:47 UTC by deandreJones

[## [Agility ticket](tbd)](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A873093&RoomContext=TeamRoom%3A808731&concept=TeamRoom)

## Summary

NFPR - Partial Delivery Out of Destination SIT Automated Testing

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test
Run playwright tests for prime simulator flows
Prime simulator user :
is able submit payment request on SIT without destination SIT Out Date

2023-12-19 19:34 UTC, danieljordan-caci requested changes
Tests pass on my end, just need to add tests for functions in `pkg/factory/`:
`mto_service_item_factory.go`
`mto_shipment_factory.go`

2023-12-20 15:47 UTC, danieljordan-caci commented on pkg/factory/mto_service_item_factory.go
> +func BuildDestSITServiceItemsNoSITDepartureDate(db *pop.Connection, move models.Move, shipment models.MTOShipment, entryDate *time.Time) models.MTOServiceItems {
...no tests...? :(

2023-12-20 19:21 UTC, deandreJones commented on pkg/factory/mto_service_item_factory.go
> +func BuildDestSITServiceItemsNoSITDepartureDate(db *pop.Connection, move models.Move, shipment models.MTOShipment, entryDate *time.Time) models.MTOServiceItems {
thanks for keeping me accountable... i really hate writing tests

2023-12-20 19:27 UTC, danieljordan-caci commented on pkg/factory/mto_service_item_factory.go
> +func BuildDestSITServiceItemsNoSITDepartureDate(db *pop.Connection, move models.Move, shipment models.MTOShipment, entryDate *time.Time) models.MTOServiceItems {
Absolutely the same for me. But I refuse to let `server_test_coverage` get the best of me and that means making sure y'all write tests so it doesn't bite me in the butt later on haha

2023-12-20 19:37 UTC, danieljordan-caci approved these changes
Thank you for adding tests :) LGTM!

2023-12-20 21:54 UTC, traskowskycaci approved these changes

2023-12-20 21:56 UTC, merged