B 18107 shipment diversion
transcom/mymove pull request #11673
Opened 2023-12-21 16:52 UTC by cameroncaci

## [B-18107](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A871300&RoomContext=TeamRoom%3A808731&concept=TeamRoom)

## Summary

### Breaking API Change
`POST createMTOShipment` 

This POST endpoint now requires the parameter `divertedFromShipmentId` to be present if the `diversion` parameter is present and set to `true`

### Service logic

I refactored the mto_shipment service for createMtoShipment to allow validators to be passed in on creation, of which v1 now has the `protectV1Diversion` rule and v2 has the `checkDiversionValid` rule.
## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?
- [ ] Are you correctly using the prime/v1/ or prime/v2/ endpoint during postman testing?

Example payload

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Boot up postman
2. Import the new Prime API V2 .yaml file
3. Navigate to the new POST endpoint
  a. <img width="251" alt="image" src="https://github.com/transcom/mymove/assets/136814362/f49d4543-6d9c-496e-b109-e18943e43d73"> 
4. Make sure to update your environment variable to have `prime/v2/`, `{{baseUrl}}` is set by default to `prime/v1/`
5. Use the example payload
6. Modify payload accordingly for testing
 
Example payload

```
{
  "moveTaskOrderID": "59476e8f-5efe-407a-8da8-22d04d185a7d",
  "requestedPickupDate": "2023-12-19",
  "primeEstimatedWeight": 4500,
  "customerRemarks": "handle with care",
  "agents": [
    {
      "firstName": "string",
      "lastName": "string",
      "email": "I2Zo35dd%6hSYW2Xfi6wFD+G6CDGh44CfcWK2.ypLOWMlMTTNOKw@RmRi2KKDbC4to.yvLbJPMGTJChrkTbdshELMiTYErLIELVrjknRYzMlbBVNnUGdRYmMXELYp",
      "phone": "",
      "agentType": "RELEASING_AGENT"
    }
  ],
  "pickupAddress": {
    "streetAddress1": "123 Main Ave",
    "streetAddress2": "Apartment 9000",
    "streetAddress3": "Montmârtre",
    "city": "Anytown",
    "state": "AL",
    "postalCode": "90210",
    "country": "USA"
  },
  "shipmentType": "HHG",
  "diversion": true,
  "divertedFromShipmentId": "8b646662-a95a-41c6-a0f0-b3ab157a1935",
  "pointOfContact": "string",
  "counselorRemarks": "counselor approved",
  "ppmShipment": {
    "expectedDepartureDate": "2023-12-19",
    "pickupPostalCode": "90210",
    "secondaryPickupPostalCode": "90210",
    "destinationPostalCode": "90210",
    "secondaryDestinationPostalCode": "90210",
    "sitExpected": true,
    "sitLocation": "ORIGIN",
    "sitEstimatedWeight": 2000,
    "sitEstimatedEntryDate": "2023-12-19",
    "sitEstimatedDepartureDate": "2023-12-19",
    "estimatedWeight": 4200,
    "hasProGear": true,
    "proGearWeight": 0,
    "spouseProGearWeight": 0
  }
}
```

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

2023-12-22 01:13 UTC, cameroncaci commented
Finally! Test coverage is satisfied!

2023-12-27 14:42 UTC, danieljordan-caci requested changes

2023-12-27 14:42 UTC, danieljordan-caci commented on pkg/services/mto_shipment/rules.go
> +				return apperror.NewInvalidInputError(newer.ID, nil, verrs, "The diverted shipment must have a DivertedFromShipmentID if it is a diversion")
Can you fix this error output to be a little more specific? From what I can see, this is checking that the **parent shipment** is a diversion and if it is a diversion but DOESN'T have a `divertedFromShipmentId` value, it's returning this error.

Should this error say something like... `"The parent shipment must have a DivertedFromShipmentID if it is a diversion"` instead? If I'm totally wrong here, let me know - also if you do change it, please address the comment as well.

2023-12-27 15:25 UTC, cameroncaci commented on pkg/services/mto_shipment/rules.go
> +				return apperror.NewInvalidInputError(newer.ID, nil, verrs, "The diverted shipment must have a DivertedFromShipmentID if it is a diversion")
As the parent diversion is actually created via an update rather than hitting this endpoint, I can replace this error with `The new shipment must have a DivertedFromShipmentID referencing the parent`

2023-12-27 15:31 UTC, cameroncaci commented on pkg/services/mto_shipment/rules.go
> +				return apperror.NewInvalidInputError(newer.ID, nil, verrs, "The diverted shipment must have a DivertedFromShipmentID if it is a diversion")
As I am finding in the next story for this feature, this check is actually flawed. A "parent" shipment created by the prime will be marked as a diversion but with no DivertedFromShipmentID. I am removing this error check

2023-12-27 16:02 UTC, danieljordan-caci approved these changes
L
G
T
M
!

2023-12-27 16:03 UTC, TevinAdams approved these changes
Tests pass, CI build pass, Functionality worked and reviewed code. Everything looks good.

2023-12-28 14:40 UTC, merged