B 18112 update source of duty location and pay grade information in profile to show values from orders table
transcom/mymove pull request #11684
Opened 2023-12-26 17:39 UTC by traskowskycaci

## [Agility ticket](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3a871311)

## Summary

This PR is to ensure the orders table information for pay grade and current/origin duty location are shown on the profile and edit profile page, rather than the service member rank and duty location table information.

The edit profile page at this point is still updating the service member rank and duty location before updating the orders table. I believe that link will be broken with future work to move the entry point that customers will provide their pay grade and duty location to the orders portion of the move process.

## Verification Steps for the Author

These are to be checked by the author.

- [x] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [x] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### How to test

1. Access the milmove app as a customer.
2. Create a move and enter in a pay grade and duty location.
3. Put in orders.
4. Navigate to the profile page and ensure that you see pay grade and duty location information that matches the orders table columns of "grade" and "origin_duty_location_id". As a further test, you can edit the service_members rank column to be some other value than the orders grade value and refresh the page to make sure that you are still seeing the orders table value.

2023-12-28 15:08 UTC, loganwc commented
Do we not still want the text Pay grade? E1-9 and O1-10 are pay grades not ranks

2023-12-28 15:17 UTC, danieljordan-caci requested changes

2023-12-28 15:17 UTC, danieljordan-caci commented on src/pages/MyMove/Profile/EditServiceInfo.test.jsx
> +    const rankInput = await screen.findByLabelText('Pay grade');
Let's also make sure we change the variable names to avoid inconsistency

2023-12-28 15:17 UTC, danieljordan-caci commented on src/pages/MyMove/Profile/Profile.jsx
> +              payGrade={ORDERS_RANK_OPTIONS[payGrade] || ''}
Can you also address changing the name of that constant being used in `orders.js`? There's a variable called `ORDERS_RANK_OPTIONS` that should be renamed to something like `ORDERS_PAY_GRADE_OPTIONS` or whatever you feel is good.

2023-12-28 15:17 UTC, danieljordan-caci commented on src/scenes/Review/EditProfile.jsx
> +      rank: currentOrders.grade,
same thing here, replacing `rank` with `pay_grade`

2023-12-28 15:17 UTC, danieljordan-caci commented on src/components/Customer/ServiceInfoForm/ServiceInfoForm.jsx
> +                  <DropdownInput label="Pay grade" name="rank" id="rank" required options={rankOptions} />
Make sure we are also changing the `name` & `id` properties as well. Need to address the variable `rankOptions` being used here in `options`

2023-12-28 15:17 UTC, danieljordan-caci commented on src/components/Customer/ServiceInfoForm/ServiceInfoForm.test.jsx
> +    const rankInput = await screen.findByLabelText('Pay grade');
should be `payGradeInput` instead of `rankInput`

2023-12-28 15:19 UTC, danieljordan-caci commented
> Do we not still want the text Pay grade? E1-9 and O1-10 are pay grades not ranks

Yeah the focus of this story is to remove where the info is coming from. End goal is to get rid of rank entirely and instead use pay grade.

2023-12-28 16:37 UTC, danieljordan-caci commented
Approved Happo checks

2023-12-28 17:15 UTC, traskowskycaci commented
> Do we not still want the text Pay grade? E1-9 and O1-10 are pay grades not ranks


Which file are you talking about? We do want rank to become pay grade as rank is an outdated term.

2023-12-28 21:38 UTC, traskowskycaci commented
Marking this as a draft for now as I have some more work to do here. To be continued!

2024-01-05 16:11 UTC, danieljordan-caci requested changes

2024-01-05 16:11 UTC, danieljordan-caci commented on src/components/CustomerHeader/index.jsx
>              <span data-testid="deptRank" className={styles.details}>
Can you change this to `deptPayGrade`?

2024-01-05 16:11 UTC, danieljordan-caci commented on src/pages/MyMove/Profile/EditServiceInfo.jsx
> +        navigate(customerRoutes.PROFILE_PATH);
Do you need two `navigate(customerRoutes.PROFILE_PATH)` in this function?

2024-01-05 16:11 UTC, danieljordan-caci commented on src/pages/MyMove/Profile/EditServiceInfo.jsx
> +        // TODO - error handling - below is rudimentary error handling to approximate existing UX
I'd also get rid of this `TODO`

2024-01-05 16:11 UTC, danieljordan-caci commented on src/pages/Office/MoveAllowances/MoveAllowances.jsx
> +const rankDropdownOptions = dropdownInputOptions(ORDERS_PAY_GRADE_OPTIONS);
Can you change this variable name to `payGradeDropdownOptions`?

2024-01-05 16:11 UTC, danieljordan-caci commented on src/pages/Office/ServicesCounselingMoveAllowances/ServicesCounselingMoveAllowances.jsx
> +const rankDropdownOptions = dropdownInputOptions(ORDERS_PAY_GRADE_OPTIONS);
Same thing here with the variable name change

2024-01-05 19:51 UTC, traskowskycaci commented on src/pages/MyMove/Profile/EditServiceInfo.jsx
> +        navigate(customerRoutes.PROFILE_PATH);
Fixed most of your peer review feedback other than this - I would like to take care of this in my current story, 18111. It's possible, after talking with Wendy, that I will move the pay grade and current duty location off of the profile page entirely. So, I'd like to keep this navigate line/not modify tests until I have that laying flat.

2024-01-05 20:26 UTC, danieljordan-caci commented
It looks like some values have disappeared in the Happo checks - might need to take a look at storybook components of the most recently updated push of code.

2024-01-05 20:27 UTC, danieljordan-caci commented on src/pages/MyMove/Profile/EditServiceInfo.jsx
> +        navigate(customerRoutes.PROFILE_PATH);
Makes sense!

2024-01-05 21:11 UTC, traskowskycaci commented
> It looks like some values have disappeared in the Happo checks - might need to take a look at storybook components of the most recently updated push of code.

I believe this is due to now showing the order tables info on the profile page rather than the service member info. At certain points in the process, the orders table won't be updated yet. For example, creating a new move and before adding orders, this is what I see:
<img width="952" alt="image" src="https://github.com/transcom/mymove/assets/147537467/9766d76b-72ef-499d-801c-27a9bfe31a6f">
and then reviewing at that point:
<img width="887" alt="image" src="https://github.com/transcom/mymove/assets/147537467/62297a18-935d-4cf2-937a-e2bb878ceb60">

However, when I go ahead and put in orders:
<img width="919" alt="image" src="https://github.com/transcom/mymove/assets/147537467/22814e16-3b64-4459-9a82-24b0734f2d4f">
I can now see values.
<img width="938" alt="image" src="https://github.com/transcom/mymove/assets/147537467/b05abf16-8356-47bc-ab28-5bb3d44d87fc">

Thoughts? I can for sure fix it, but it also serves as a visual way for the testers to see that the info is now coming from the orders table. And, this info may be moving around/not even in the profile page in my next story.

2024-01-05 21:31 UTC, danieljordan-caci commented
> > It looks like some values have disappeared in the Happo checks - might need to take a look at storybook components of the most recently updated push of code.
> 
> I believe this is due to now showing the order tables info on the profile page rather than the service member info. At certain points in the process, the orders table won't be updated yet. For example, creating a new move and before adding orders, this is what I see: <img alt="image" width="952" src="https://private-user-images.githubusercontent.com/147537467/294611343-9766d76b-72ef-499d-801c-27a9bfe31a6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0ODk0MjgsIm5iZiI6MTcwNDQ4OTEyOCwicGF0aCI6Ii8xNDc1Mzc0NjcvMjk0NjExMzQzLTk3NjZkNzZiLTcyZWYtNDk5ZC04MDFjLTI3YTliZmUzMWE2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNVQyMTEyMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZjdjYmIzZGRlN2YzNTcxMzc2OTM4NDcyZTk3ODEwZjQzNTQ2OGRiNzUyNGQ5MTEyZGY4ZWEzMTMwMThkMDBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4hUFGHXWYKf5mRm1mO9lGcPnsujqDUneyyWkXV_ST-s"> and then reviewing at that point: <img alt="image" width="887" src="https://private-user-images.githubusercontent.com/147537467/294611382-62297a18-935d-4cf2-937a-e2bb878ceb60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0ODk0MjgsIm5iZiI6MTcwNDQ4OTEyOCwicGF0aCI6Ii8xNDc1Mzc0NjcvMjk0NjExMzgyLTYyMjk3YTE4LTkzNWQtNGNmMi05MzdhLWUyYmI4NzhjZWI2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNVQyMTEyMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDI2MWNhYmMwODgzODA5NzczMzU0ZDY1YzUzZWM2YjRlYTE3YzE3Yzg5OGIzNjhiMjZjNDNmNTJjZjU2NTZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Obe57RsI_bvbTbkPJu6AFzP2Nzrn6LWojoJxkMO_pZ8">
> 
> However, when I go ahead and put in orders: <img alt="image" width="919" src="https://private-user-images.githubusercontent.com/147537467/294611489-22814e16-3b64-4459-9a82-24b0734f2d4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0ODk0MjgsIm5iZiI6MTcwNDQ4OTEyOCwicGF0aCI6Ii8xNDc1Mzc0NjcvMjk0NjExNDg5LTIyODE0ZTE2LTNiNjQtNDQ1OS05YTgyLTI0YjA3MzRmMmQ0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNVQyMTEyMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMTFiZGVhOWE5YjcwNGVkMDJlYWQxMDQxZmE3NzY1MjI5MDdjY2JkZTgxNGMxMjc4MmRhNjEwMjAwN2E3NjBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GmF64chaCIBzp-EQSCxqJxLddcS1r-72O5hT_C4dhxs"> I can now see values. <img alt="image" width="938" src="https://private-user-images.githubusercontent.com/147537467/294611534-b05abf16-8356-47bc-ab28-5bb3d44d87fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0ODk0MjgsIm5iZiI6MTcwNDQ4OTEyOCwicGF0aCI6Ii8xNDc1Mzc0NjcvMjk0NjExNTM0LWIwNWFiZjE2LTgzNTYtNDdiYy1hYjI4LTViYjNkNDRkODdmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNVQyMTEyMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDM1YTJhZWIxYzE2MTNiNWQ5YzFkNGQ5NjgxODZmMGYwZmQ0N2NhYjdmNTg2MmRjODliZTU1YjhjYTBiNzZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1p-w1in-Yf-MCCwQSdeq138ccRXoAKs2DLeVqEmiI1w">
> 
> Thoughts? I can for sure fix it, but it also serves as a visual way for the testers to see that the info is now coming from the orders table. And, this info may be moving around/not even in the profile page in my next story.

Ahhh gotcha. Makes sense. You should be able to update the test values in the storybook component and that should fix the happo checks. Looks like you're down to one, `src/components/Customer/Review/ProfileTable/ProfileTable.stories.jsx`

2024-01-05 22:00 UTC, danieljordan-caci commented
LGTM LGTM LGTM!!!!

2024-01-05 22:01 UTC, danieljordan-caci approved these changes

2024-01-08 16:18 UTC, cameroncaci commented
@danieljordan-caci Checking in on this PR, I see you requested the data references to `rank` to be changed to `pay grade`. I don't know if this is the best approach as our backend is entirely structured around the "rank" parameter. It was to my knowledge we would continue referencing the data as "rank" until even the backend is updated to reflect "pay grade", while just visually displaying it as pay grade for the customer. This creates a discrepancy where frontend is talking about pay grade and the backend is talking about rank, while in the database it's rank. Additionally, even endpoints for GHC/Prime use "rank".

2024-01-08 16:24 UTC, traskowskycaci commented
> @danieljordan-caci Checking in on this PR, I see you requested the data references to `rank` to be changed to `pay grade`. I don't know if this is the best approach as our backend is entirely structured around the "rank" parameter. It was to my knowledge we would continue referencing the data as "rank" until even the backend is updated to reflect "pay grade", while just visually displaying it as pay grade for the customer. This creates a discrepancy where frontend is talking about pay grade and the backend is talking about rank, while in the database it's rank. Additionally, even endpoints for GHC/Prime use "rank".

I do remember that conversation. With this story and with 18111, it is more of transitioning from the service member value of rank to the order value of grade, and relying on that grade value in the backend. I tried to leave instances of service member rank as rank and anything related to orders as grade. What are your thoughts? Would you mind taking a look at 18111 and seeing what you think? My understanding of 18111 is to no longer even fill out the service member rank value during the customer flow and instead fill out the order grade value, so everything involving service member rank would need to reflect that change.

2024-01-09 16:08 UTC, cameroncaci commented on src/scenes/Review/EditProfile.jsx
> +        // this.props.updateServiceMember(response);
leftover comment

2024-01-09 16:08 UTC, cameroncaci commented on src/scenes/Review/EditProfile.jsx
> +        // TODO - error handling - below is rudimentary error handling to approximate existing UX
leftover todo

2024-01-09 16:16 UTC, traskowskycaci commented on src/scenes/Review/EditProfile.jsx
> +        // TODO - error handling - below is rudimentary error handling to approximate existing UX
Removed this one

2024-01-09 16:16 UTC, traskowskycaci commented on src/scenes/Review/EditProfile.jsx
> +        // this.props.updateServiceMember(response);
Removed this as well

2024-01-09 16:21 UTC, cameroncaci approved these changes

2024-01-09 16:30 UTC, merged