added the visible field for SIT Departure Date on the SIT dashboard a…
transcom/mymove pull request #11681
Opened 2023-12-22 17:40 UTC by WeatherfordAaron

## [Agility ticket](tbd)
B-18355

## Summary

Is there anything you would like reviewers to give additional scrutiny?
Make sure the SIT departure date populates when there is a SIT departure date on the current SIT and shows "-" whenever there is no SIT departure date on the current SIT.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

Prerequisite: Make sure there has been a SIT Departure date added to the current SIT by Prime and TOO approved the added SIT Departure Date.
1. Access the office side
2. Login as a TOO
3. Navigate to the MTO tab of the move
4. As long as there is an approved SIT Departure Date on the current SIT, the SIT Departure Date section should be populated with the correct date.. otherwise, there should be a "-".

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots
![Screenshot 2023-12-22 at 11 39 29 AM](https://github.com/transcom/mymove/assets/147739091/1382325c-36ef-4a3a-9926-92dac0698ffa)

2023-12-26 19:00 UTC, taeJungCaci commented on pkg/services/sit_status/shipment_sit_status.go
> +	return result, nil
Just curious on what would be the case to get in this statment? 

`if result < min || result > max {
		return result, errors.New("Clamp input is out of scope")
	}`

2023-12-26 19:01 UTC, WeatherfordAaron commented on pkg/services/sit_status/shipment_sit_status.go
> +	return result, nil
It had to go in so the testing would show it as being covered

2023-12-26 19:12 UTC, taeJungCaci commented on src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.jsx
> +  const totalSITDaysUsed = clamp(sitStatus.totalSITDaysUsed || 0, 0, shipment.sitDaysAllowance);
What would be the reason for the double clamping here? One in FE and one in BE

2023-12-26 19:22 UTC, taeJungCaci commented
Tested the UI and it looks like they have a set '-' that they use. 
<img width="715" alt="image" src="https://github.com/transcom/mymove/assets/146856854/444a1c40-b5cb-43c2-b774-21a2638d08c1">

2023-12-26 20:01 UTC, taeJungCaci commented
Also noticed that the Date formats are different. 
<img width="671" alt="image" src="https://github.com/transcom/mymove/assets/146856854/487be3ea-6ba2-4d11-90bc-2f12e372d750">

2023-12-26 20:02 UTC, WeatherfordAaron commented on src/components/Office/ShipmentSITDisplay/ShipmentSITDisplay.jsx
> +  const totalSITDaysUsed = clamp(sitStatus.totalSITDaysUsed || 0, 0, shipment.sitDaysAllowance);
Honestly I think this one can go.. I did this one and it found it's way into the code and I was getting errors because there was no clamp method. Let me get rid of this one. Good catch

2023-12-26 21:31 UTC, WeatherfordAaron commented
> Also noticed that the Date formats are different. <img alt="image" width="671" src="https://private-user-images.githubusercontent.com/146856854/292914797-487be3ea-6ba2-4d11-90bc-2f12e372d750.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2MjYzOTAsIm5iZiI6MTcwMzYyNjA5MCwicGF0aCI6Ii8xNDY4NTY4NTQvMjkyOTE0Nzk3LTQ4N2JlM2VhLTZiYTItNGQxMS05MGJjLTJmMTJlMzcyZDc1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNlQyMTI4MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYTg5MzM5NTE1OWZhNzNjMTc3MDFkNDU3Mjc5NThiYWE3ZjU1ZGU1OGRkMjY2NTY3NTRjYjA5ZDI3NjUyN2JhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kvRbv5E32XHq_G_HJxH7ZkmbY6OKux5IWs2QVIajMOU">

I don't know how to respond to that since they are already using different formats and only one of those was something I messed with in my branch. I had it use the swagger date format (if I remember correctly). I'll check this again though.

2023-12-26 21:31 UTC, WeatherfordAaron commented
> Tested the UI and it looks like they have an existing '-' that they use. <img alt="image" width="715" src="https://private-user-images.githubusercontent.com/146856854/292911314-444a1c40-b5cb-43c2-b774-21a2638d08c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2MjYzOTAsIm5iZiI6MTcwMzYyNjA5MCwicGF0aCI6Ii8xNDY4NTY4NTQvMjkyOTExMzE0LTQ0NGExYzQwLWI1Y2ItNDNjMi1iNzc0LTIxYTI2MzhkMDhjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNlQyMTI4MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MTU3NDE3ZWYwNmNmZWRlNTdlNzIxOTc2NDZmNzA3MTgwMzY1Y2IyNzhiMmMyOTRhZDc4NjZiYzNmZDY0NWViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-BS0Pbb4rkcMzGElBbjOTTehwvZgacOxaSDFhNp-o0Q">

I'll look into this one

2023-12-26 22:48 UTC, taeJungCaci requested changes

2023-12-26 22:48 UTC, taeJungCaci commented on src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.jsx
> +  const sitDepartureDate = sitStatus.currentSIT?.sitDepartureDate || DEFAULT_EMPTY_VALUE;
formatDate also needed here and in the file [ReviewSITExtensionModal.jsx](https://github.com/transcom/mymove/pull/11681/files#diff-42790323a73b153a4cbc146897a0756684ca99620d764126658311cd79c580ec)

2023-12-26 23:33 UTC, WeatherfordAaron commented on src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.jsx
> +  const sitDepartureDate = sitStatus.currentSIT?.sitDepartureDate || DEFAULT_EMPTY_VALUE;
got it

2023-12-28 14:48 UTC, taeJungCaci commented on src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.jsx
> +  const sitDepartureDate = sitStatus.currentSIT?.sitDepartureDate || DEFAULT_EMPTY_VALUE;
If you think changing the date format for your added Departure Date is out of scope for this PR, then sure - I won't see this as a issue. Don't forget to revert the change for the format in ShipmentSITDisplay file as well if not already done.

2023-12-28 14:50 UTC, WeatherfordAaron commented on src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.jsx
> +  const sitDepartureDate = sitStatus.currentSIT?.sitDepartureDate || DEFAULT_EMPTY_VALUE;
The date format for the one I added is fine to change. I think I misinterpreted what your ask was.

2023-12-28 14:54 UTC, taeJungCaci commented on src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.jsx
> +  const sitDepartureDate = sitStatus.currentSIT?.sitDepartureDate || DEFAULT_EMPTY_VALUE;
Oh, yeah I was saying you need to also change the formats in the Edit modal and extension modal because they are going to be showing different formats than the one from ShipmentSITDisplay.

2023-12-28 15:57 UTC, taeJungCaci approved these changes

2023-12-28 16:11 UTC, KonstanceH approved these changes

2023-12-28 16:14 UTC, merged

2023-12-28 17:14 UTC, JamesHawks224 reviewed
Looks good, no changes.