B 18416 update shipment destination address
transcom/mymove pull request #11713
Opened 2024-01-03 19:58 UTC by cameroncaci

## [B-18416](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A882407&RoomContext=TeamRoom%3A808731&concept=TeamRoom)

## Summary

Updates swagger def and associated pkg files to accomodate for new description for createNonSITAddressUpdateRequest. Endpoint and its logic remains the same, but with a more current and readable description.

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access swagger-ui locally to verify documentation changes.

2024-01-09 20:55 UTC, danieljordan-caci requested changes

2024-01-09 20:55 UTC, danieljordan-caci commented on swagger-def/prime.yaml
Could you throw somewhere in here:

which service items will be updated if the request is approved
mention that the TOO can reject the request

2024-01-09 20:55 UTC, danieljordan-caci commented on swagger-def/prime.yaml
> +    description: UpdateShipmentDestinationAddress contains the fields required for the prime to request an update for the destination address on an MTO Shipment or its SIT service items.
Same thing here in the description - just specify that its destination SIT and not Origin

2024-01-09 21:02 UTC, cameroncaci commented on swagger-def/prime.yaml
@TevinAdams could you assist here? I know you just recently expanded on the `createNonSITAddressUpdateRequest` endpoint. Would you know off the top of your head the answer to this?

2024-01-09 22:14 UTC, TevinAdams commented on swagger-def/prime.yaml
I would have to dive into that. When the request is approved by the TOO that hits a whole different endpoint. Not this one. I believe it calls the reviewShipmentAddress endpoint.

2024-01-09 22:24 UTC, traskowskycaci commented on swagger-def/prime.yaml
@cameroncaci  which service items will be updated if the request is approved ->
DDDSIT, DDFSIT, DDSFSC, DDASIT

2024-01-09 22:26 UTC, traskowskycaci commented on swagger-def/prime.yaml
> @cameroncaci which service items will be updated if the request is approved -> DDDSIT, DDFSIT, DDSFSC, DDASIT

For destination SIT items, specifically. Not sure if other service items would also be part of that or not?

2024-01-10 13:28 UTC, cameroncaci commented on swagger-def/prime.yaml
Okay, I see what you're saying. I'll put in the DDFSIT documentation of the service items explicitly updated. I was initially confused because it sounded pretty broad of a request. I feel like this should've been included in the prior stories for `createNonSITAddressUpdateRequest` when that functionality was added as it was previously not a feature

2024-01-10 13:57 UTC, cameroncaci commented
```
https://transcom.github.io/mymove-docs/api/prime/v1#tag/mtoServiceItem/operation/createMTOServiceItem

When a DDFSIT is requested, the API will auto-create the following group of service items:

DDFSIT - Domestic destination 1st day SIT
DDASIT - Domestic destination Additional day SIT
DDDSIT - Domestic destination SIT delivery
DDSFSC - Domestic destination SIT fuel surcharge
```

I updated the documentation to reflect that these are the service items for destination SIT and receive destination address updates based on the UpdateShipmentDestinationAddress endpoint

2024-01-10 22:33 UTC, traskowskycaci reviewed
I think it's worth clarifying that the UpdateShipmentDestinationAddress endpoint does not actually update the service item's destination final address ID. 

That part is done with a different endpoint which is when the TOO actually approves the shipment address change: 
![image](https://github.com/transcom/mymove/assets/147537467/9cbaad70-6839-4b64-815a-ab3d392f2f4f)

2024-01-11 16:49 UTC, TevinAdams approved these changes

2024-01-11 16:58 UTC, traskowskycaci approved these changes
This was a bit of a doozy to test so I bugged @cameroncaci throughout. After following all the steps and doing a reweigh on the diversion, then creating a payment request on the parent shipment unpacking service item, I do see the reweigh weight used in calculations here: 
![image](https://github.com/transcom/mymove/assets/147537467/591c9fd4-7621-4d0c-920b-834ad40c00c7)

For other devs doing testing - use weights > 500 lbs for both the actual weights and the reweighs. Below that number, it seems like the "5 cwt" (500 lbs) is the lowest we can see on the calculations.

2024-01-11 17:02 UTC, traskowskycaci commented
> > I think it's worth clarifying that the UpdateShipmentDestinationAddress endpoint does not actually update the service item's destination final address ID.
> > That part is done with a different endpoint which is when the TOO actually approves the shipment address change: ![image](https://private-user-images.githubusercontent.com/147537467/295732218-9cbaad70-6839-4b64-815a-ab3d392f2f4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5OTI3MDcsIm5iZiI6MTcwNDk5MjQwNywicGF0aCI6Ii8xNDc1Mzc0NjcvMjk1NzMyMjE4LTljYmFhZDcwLTY4MzktNGI2NC04MTVhLWFiM2QzOTJmMmY0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMVQxNzAwMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NmJkYzJjY2VjNWViNzQ0NDViZDY3NjNkODVkZjhkN2U5YzczMWNlOWRjNzMxMDZlOGQxM2Y3ZjcyZWZlNmVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UHrGZlgMRAxeYBWOADeGibFTay2PH7RlXbbMVkAnXz4)
> 
> What do you mean by that? Want to make sure I detail it as much as possible.

So the createNonSITAddressUpdate endpoint changes the shipment destination address. But the endpoint that actually changes the service item's destination address is that reveiew-shipment-address-update endpoint that is hit when the TOO approves. Just want to make sure we don't lose track of that, because I had to sit and think through it yesterday even being recently familiar with this stuff.

2024-01-11 17:04 UTC, cameroncaci commented
> > > I think it's worth clarifying that the UpdateShipmentDestinationAddress endpoint does not actually update the service item's destination final address ID.
> > > That part is done with a different endpoint which is when the TOO actually approves the shipment address change: ![image](https://private-user-images.githubusercontent.com/147537467/295732218-9cbaad70-6839-4b64-815a-ab3d392f2f4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5OTI3MDcsIm5iZiI6MTcwNDk5MjQwNywicGF0aCI6Ii8xNDc1Mzc0NjcvMjk1NzMyMjE4LTljYmFhZDcwLTY4MzktNGI2NC04MTVhLWFiM2QzOTJmMmY0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMVQxNzAwMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NmJkYzJjY2VjNWViNzQ0NDViZDY3NjNkODVkZjhkN2U5YzczMWNlOWRjNzMxMDZlOGQxM2Y3ZjcyZWZlNmVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UHrGZlgMRAxeYBWOADeGibFTay2PH7RlXbbMVkAnXz4)
> > 
> > 
> > What do you mean by that? Want to make sure I detail it as much as possible.
> 
> So the createNonSITAddressUpdate endpoint changes the shipment destination address. But the endpoint that actually changes the service item's destination address is that reveiew-shipment-address-update endpoint that is hit when the TOO approves. Just want to make sure we don't lose track of that, because I had to sit and think through it yesterday even being recently familiar with this stuff.

@traskowskycaci 
But when it gets auto approved (Should it meet the criteria), then this endpoint does it too right?

2024-01-11 17:05 UTC, traskowskycaci commented
> > > > I think it's worth clarifying that the UpdateShipmentDestinationAddress endpoint does not actually update the service item's destination final address ID.
> > > > That part is done with a different endpoint which is when the TOO actually approves the shipment address change: ![image](https://private-user-images.githubusercontent.com/147537467/295732218-9cbaad70-6839-4b64-815a-ab3d392f2f4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5OTI3MDcsIm5iZiI6MTcwNDk5MjQwNywicGF0aCI6Ii8xNDc1Mzc0NjcvMjk1NzMyMjE4LTljYmFhZDcwLTY4MzktNGI2NC04MTVhLWFiM2QzOTJmMmY0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMVQxNzAwMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NmJkYzJjY2VjNWViNzQ0NDViZDY3NjNkODVkZjhkN2U5YzczMWNlOWRjNzMxMDZlOGQxM2Y3ZjcyZWZlNmVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UHrGZlgMRAxeYBWOADeGibFTay2PH7RlXbbMVkAnXz4)
> > > 
> > > 
> > > What do you mean by that? Want to make sure I detail it as much as possible.
> > 
> > 
> > So the createNonSITAddressUpdate endpoint changes the shipment destination address. But the endpoint that actually changes the service item's destination address is that reveiew-shipment-address-update endpoint that is hit when the TOO approves. Just want to make sure we don't lose track of that, because I had to sit and think through it yesterday even being recently familiar with this stuff.
> 
> @traskowskycaci But when it gets auto approved (Should it meet the criteria), then this endpoint does it too right?

That would be a better question for @TevinAdams as he most recently looked at that - thoughts Tevin? I didn't think that the createNonSITAddress endpoint did any service item manipulation at all but I could be wrong. What happens when TOO approval is not needed as far as service item destination address changing?

2024-01-11 18:56 UTC, traskowskycaci commented
> > > > > > I think it's worth clarifying that the UpdateShipmentDestinationAddress endpoint does not actually update the service item's destination final address ID.
> > > > > > That part is done with a different endpoint which is when the TOO actually approves the shipment address change: ![image](https://private-user-images.githubusercontent.com/147537467/295732218-9cbaad70-6839-4b64-815a-ab3d392f2f4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5OTI3MDcsIm5iZiI6MTcwNDk5MjQwNywicGF0aCI6Ii8xNDc1Mzc0NjcvMjk1NzMyMjE4LTljYmFhZDcwLTY4MzktNGI2NC04MTVhLWFiM2QzOTJmMmY0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMVQxNzAwMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NmJkYzJjY2VjNWViNzQ0NDViZDY3NjNkODVkZjhkN2U5YzczMWNlOWRjNzMxMDZlOGQxM2Y3ZjcyZWZlNmVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UHrGZlgMRAxeYBWOADeGibFTay2PH7RlXbbMVkAnXz4)
> > > > > 
> > > > > 
> > > > > What do you mean by that? Want to make sure I detail it as much as possible.
> > > > 
> > > > 
> > > > So the createNonSITAddressUpdate endpoint changes the shipment destination address. But the endpoint that actually changes the service item's destination address is that reveiew-shipment-address-update endpoint that is hit when the TOO approves. Just want to make sure we don't lose track of that, because I had to sit and think through it yesterday even being recently familiar with this stuff.
> > > 
> > > 
> > > @traskowskycaci But when it gets auto approved (Should it meet the criteria), then this endpoint does it too right?
> > 
> > 
> > That would be a better question for @TevinAdams as he most recently looked at that - thoughts Tevin? I didn't think that the createNonSITAddress endpoint did any service item manipulation at all but I could be wrong. What happens when TOO approval is not needed as far as service item destination address changing?
> 
> Looking at the code, when the TOO Approves the request then it calls that review-shipment-address-update endpoint. If not then it goes through with updating the shipment Address Id. It does not do any service Item manipulation. I thought that part was being handled in another story or MR? If not we need to create a story for that. Should be the same update code that we have been putting in the other endpoints.

Sounds like we have missed a situation for updating service items with that createNonSITAddressUpdateRequest when TOO approval is not needed. Would everyone agree? @TevinAdams @danieljordan-caci @cameroncaci 

I don't believe 18033 covered that explicitly so I think it would be a new BL item.

2024-01-11 19:08 UTC, TevinAdams commented
> > > > > > > I think it's worth clarifying that the UpdateShipmentDestinationAddress endpoint does not actually update the service item's destination final address ID.
> > > > > > > That part is done with a different endpoint which is when the TOO actually approves the shipment address change: ![image](https://private-user-images.githubusercontent.com/147537467/295732218-9cbaad70-6839-4b64-815a-ab3d392f2f4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5OTI3MDcsIm5iZiI6MTcwNDk5MjQwNywicGF0aCI6Ii8xNDc1Mzc0NjcvMjk1NzMyMjE4LTljYmFhZDcwLTY4MzktNGI2NC04MTVhLWFiM2QzOTJmMmY0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMVQxNzAwMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NmJkYzJjY2VjNWViNzQ0NDViZDY3NjNkODVkZjhkN2U5YzczMWNlOWRjNzMxMDZlOGQxM2Y3ZjcyZWZlNmVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UHrGZlgMRAxeYBWOADeGibFTay2PH7RlXbbMVkAnXz4)
> > > > > > 
> > > > > > 
> > > > > > What do you mean by that? Want to make sure I detail it as much as possible.
> > > > > 
> > > > > 
> > > > > So the createNonSITAddressUpdate endpoint changes the shipment destination address. But the endpoint that actually changes the service item's destination address is that reveiew-shipment-address-update endpoint that is hit when the TOO approves. Just want to make sure we don't lose track of that, because I had to sit and think through it yesterday even being recently familiar with this stuff.
> > > > 
> > > > 
> > > > @traskowskycaci But when it gets auto approved (Should it meet the criteria), then this endpoint does it too right?
> > > 
> > > 
> > > That would be a better question for @TevinAdams as he most recently looked at that - thoughts Tevin? I didn't think that the createNonSITAddress endpoint did any service item manipulation at all but I could be wrong. What happens when TOO approval is not needed as far as service item destination address changing?
> > 
> > 
> > Looking at the code, when the TOO Approves the request then it calls that review-shipment-address-update endpoint. If not then it goes through with updating the shipment Address Id. It does not do any service Item manipulation. I thought that part was being handled in another story or MR? If not we need to create a story for that. Should be the same update code that we have been putting in the other endpoints.
> 
> Sounds like we have missed a situation for updating service items with that createNonSITAddressUpdateRequest when TOO approval is not needed. Would everyone agree? @TevinAdams @danieljordan-caci @cameroncaci
> 
> I don't believe 18033 covered that explicitly so I think it would be a new BL item.

18033 was for the mileage change logic and checks. I brought it up earlier in a huddle that we would need to make sure the service Items were getting updated in this endpoint but I thought someone said they already covered that. If that is not true, then yeah we just need a story to cover the service Items updating on that endpoint.

2024-01-11 19:50 UTC, cameroncaci commented
I thought the whole point of the `createNonSITAddressUpdateRequest` was to update the SIT final destination on MTO shipment destination being updated? This should occur automatically if no TOO approval is required and manually if TOO approval is required and they do in fact approve it. Am I not tracking correctly? I thought `createNonSITAddressUpdateRequest` would update the SIT final destination address on its own? So that SIT final dest address is tied to the shipment level, not service item level

@TevinAdams @traskowskycaci @danieljordan-caci

2024-01-11 19:56 UTC, traskowskycaci commented
> I thought the whole point of the `createNonSITAddressUpdateRequest` was to update the SIT final destination on MTO shipment destination being updated? This should occur automatically if no TOO approval is required and manually if TOO approval is required and they do in fact approve it. Am I not tracking correctly? I thought `createNonSITAddressUpdateRequest` would update the SIT final destination address on its own? So that SIT final dest address is tied to the shipment level, not service item level

Yes, you are spot on. There are two flows here.
1. Shipment address changes use createNonSITAddressUpdate -> createNonSITAddressUpdate checks if TOO approval is necessary -> TOO approval IS necessary -> TOO approves and a different endpoint, reveiew-shipment-address-update, updates the service items

2. Shipment address changes use createNonSITAddressUpdate -> createNonSITAddressUpdate checks if TOO approval is necessary -> TOO approval IS NOT necessary -> createNonSITAddressUpdate should update service items

Based on Tevin's findings, it sounds like createNonSITAddressUpdate is not doing that last step. I have not run through the flow and verified that.
@cameroncaci @TevinAdams @danieljordan-caci

2024-01-12 20:50 UTC, cameroncaci commented
# Heads up
Removed all mention of sit destintion service items being updated from this endpoint. this is to be reintroduced under B-18467.

2024-01-16 14:39 UTC, merged