B-18312-multi-move-dashboard(MERGE-AFTER-B18310)(INTEGRATION)
transcom/mymove pull request #11837
Opened 2024-01-24 14:51 UTC by TevinAdams

## [Agility ticket](https://www13.v1host.com/USTRANSCOM38/Default.aspx?menu=StoryBoardPage)

## Summary

This PR introduces the Multi Move dashboard. When the service member logs in they are routed to the multi move dashboard. Had to comment out playwright tests in  playwright/tests/my/mymove 
 and playwright/tests/my/milmove/ppms because they depend on the Home page.

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Ensure that the multiMove feature flag is switched on
2. Log into MilMove as a service member
3. You should have been routed to the Multi Move Dashboard

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

## Screenshots
![image](https://github.com/transcom/mymove/assets/136514590/43a01f55-d5df-4f79-92cd-373f1e368c7c)

2024-01-25 13:43 UTC, traskowskycaci approved these changes
Looks good!

2024-01-25 14:08 UTC, cameroncaci commented on src/utils/featureFlags.js
>    },
Shouldn't multi move be enabled in development?

2024-01-25 14:08 UTC, cameroncaci submitted a review, later dismissed
Feature flag questions

2024-01-25 14:19 UTC, cameroncaci commented on src/utils/featureFlags.js
>    },
Loadtest has its own environment actually. See this [section](https://transcom.github.io/mymove-docs/docs/backend/guides/how-to/add-an-experimental-feature-flag#circleci-deployment-flags) for all current environment flags. Not all are currently fully utilized though by the looks of it, but they do exist

2024-01-25 14:19 UTC, danieljordan-caci commented on src/utils/featureFlags.js
>    },
So how will we test this in `loadtest`?

2024-01-25 14:30 UTC, cameroncaci commented on src/utils/featureFlags.js
>    },
We should just be able to add in this:
```
export function detectEnvironment(nodeEnv, host) {
  if (nodeEnv !== 'production') {
    return nodeEnv;
  }

  switch (host) {
    
    URL Cases for loadtest...

    default:
      return 'development';
  }
}

....


  loadtest: {
    ...defaultFlags,
   multiMove: true,
  },
```

2024-01-25 14:31 UTC, cameroncaci commented on src/utils/featureFlags.js
>    },
So we add the URL flag, and then the environment case for loadtest -> multiMove true

2024-01-25 14:32 UTC, cameroncaci commented on src/utils/featureFlags.js
>    },
Technically speaking, it is already set to true for loadtest because loadtest inherits development flags @danieljordan-caci . This would be for if we want to explicitly declare loadtest to use its own feature flags

2024-01-25 14:33 UTC, danieljordan-caci commented on src/utils/featureFlags.js
>    },
Gotcha - well... in that case, we don't need to be explicit..... yet

2024-01-25 14:40 UTC, cameroncaci commented on src/utils/featureFlags.js
>    },
> This should definitely be added.
> 
> Should this be added to your previous feature flag BL item as a fix?

Hey now, don't scope creep on me haha. My BL item was created _before_ the decision that multi move would be going to the loadtest environment. But yes as we transition into loadtest for testing we should eventually begin an initiative to configure environment variables and feature flags accordingly

2024-01-25 14:41 UTC, danieljordan-caci commented on src/utils/featureFlags.js
>    },
Hey I'm not scope creeping! Just suggesting that it's relevant to that BL item now that we are using `loadtest`! Put the pitch fork down, @cameroncaci!

2024-01-25 14:55 UTC, TevinAdams commented on src/utils/featureFlags.js
>    },
@cameroncaci  I left it disabled so that way we do not have to comment out playwright tests. If we work locally and enable it when working and testing we could continue working without commenting out tests. I thought it was a better alternative to commenting out playwright tests. Right now those playwright tests have to be commented out because the workflows are not complete yet.

2024-01-25 14:57 UTC, TevinAdams commented on src/utils/featureFlags.js
>    },
@cameroncaci might need to discuss that at DSU to figure out what we want to do with MultiMove.

2024-01-25 15:47 UTC, cameroncaci commented
I think something went wrong with the merge. See files changed, this shouldn't be the case if the base is set to `integrationTesting`

2024-01-25 17:19 UTC, TevinAdams commented
> I think something went wrong with the merge. See files changed, this shouldn't be the case if the base is set to `integrationTesting`

The correct files are changed.

2024-01-25 19:01 UTC, cameroncaci commented
How come so many tests got commented? Also, could we go for test skips instead of comment, that way they're tracked via coverage?

https://devhints.io/jest

2024-01-25 19:02 UTC, cameroncaci commented
If these tests previously expected the redirect to go to their orders page, we should update the tests to navigate to the correct order URL instead of removing the test entirely. That's lot of test coverage that would get lost for pages that will still exist within the app

2024-01-25 19:38 UTC, cameroncaci commented on src/utils/featureFlags.js
>    },
> @cameroncaci I left it disabled so that way we do not have to comment out playwright tests. If we work locally and enable it when working and testing we could continue working without commenting out tests. I thought it was a better alternative to commenting out playwright tests. Right now those playwright tests have to be commented out because the workflows are not complete yet.

@TevinAdams Just now seeing this reply. If those playwright tests are just expecting to be automatically redirected, we should instead just add a new oneliner to those tests to navigate to the correct orders page for it

2024-01-25 20:35 UTC, TevinAdams commented
> If these tests previously expected the redirect to go to their orders page, we should update the tests to navigate to the correct order URL instead of removing the test entirely. That's lot of test coverage that would get lost for pages that will still exist within the app

These tests has to do with the Home page changing to the multi-move dashboard. We haven't built in or finalized the workflows that the original home page had into the multiMove page or workflow yet. It was brought up to comment or skip these tests because when we rebuild the workflows and finalize them we will be able to adjust the tests to rfelect the correct workflow.

2024-01-25 20:45 UTC, danieljordan-caci requested changes

2024-01-25 20:45 UTC, danieljordan-caci commented on src/scenes/MyMove/index.jsx
> +                {multiMoveWorkflow && <Route path={generalRoutes.HOME_PATH} end element={<Home />} />}
Shouldn't this allow for navigation to the move page?

I think we need to add a route to `routes.js`, something like:
```
export const customerRoutes = {
  MOVE_HOME_PAGE: '/move',
```

And then in this block, we can change this to:
`{multiMoveWorkflow && <Route path={customerRoutes.MOVE_HOME_PAGE} end element={<Home />} />}`

That way, once the user is routed to the dashboard, they'll have the ability to navigate to the move page. I just put up my PR for navigating that functionality if you want to take a look.

https://github.com/transcom/mymove/pull/11859

2024-01-25 20:45 UTC, danieljordan-caci commented on src/scenes/MyMove/index.jsx
> +                {multiMoveWorkflow && <Route path={generalRoutes.HOME_PATH} end element={<Home />} />}
Cause looking at this now - with `multiMoveWorkflow` set to `true`, there is no way for a user to navigate to their move since the `HOME_PATH` is the same for `MultiMovesLandingPage` and `Home`.

2024-01-25 20:54 UTC, TevinAdams commented on src/scenes/MyMove/index.jsx
> +                {multiMoveWorkflow && <Route path={generalRoutes.HOME_PATH} end element={<Home />} />}
The story was to route to the multiMove dashboard on log in. There is no way for the user to navigate to a move because at the creation of this story and the route that functionality did not exist. For that to happen there has to be code that references the path to navigate to it when some event is fired off. The code above will route the user to the Home page if multi move is enabled which isnt what we want.  When a user signs in the go to localhost:3000/ . That is considered the home path. The home path is now referencing the multimove landing page so that when the user signs in they are routed to the multi move page and not the Home page.

2024-01-25 20:55 UTC, cameroncaci commented on src/scenes/MyMove/index.jsx
> +                {multiMoveWorkflow && <Route path={generalRoutes.HOME_PATH} end element={<Home />} />}
We need to update `/move` to now be `/move/${MOVE_UUID}` right? And then populate with the correct move? So this is new functionality. Should we look at creating a spike? I believe this would be a breaking development change if it isn't included in this story.

2024-01-25 21:00 UTC, danieljordan-caci commented on src/scenes/MyMove/index.jsx
> +                {multiMoveWorkflow && <Route path={generalRoutes.HOME_PATH} end element={<Home />} />}
Right, this does route the user to the dashboard, but they will be unable to navigate anywhere else because the move and dashboard share the same route. Shouldn't that be addressed in this?

All I was suggesting is differentiate the dashboard from the current move home page so we can navigate between the two.

@cameroncaci I think that's a good idea to bring that up. Essentially the user will only have one move going at a time, so I think just changing the path of the move home page would be fine, but if we do your method, we'd be able to use `useParams()` which can be handy when calling APIs.

2024-01-25 21:02 UTC, danieljordan-caci commented on src/scenes/MyMove/index.jsx
> +                {multiMoveWorkflow && <Route path={generalRoutes.HOME_PATH} end element={<Home />} />}
With my suggested changes and added in functionality of the PR I listed, I'm able to be routed to the dashboard on login and navigate to my current move by clicking the `Go to Move` button. Just tried it out.

2024-01-25 21:25 UTC, TevinAdams commented on src/scenes/MyMove/index.jsx
> +                {multiMoveWorkflow && <Route path={generalRoutes.HOME_PATH} end element={<Home />} />}
If we create a MOVE_HOME_PAGE with path "/move" then map that path to the <Home /> element. We have to adjust the components that called HOME_PATH with path "/" to call MOVE_HOME_PAGE. On the Multi move page any buttons to reference the move has to use that MOVE_HOME_PAGE to work. Then all of the tests will have to be adjusted.

2024-01-25 21:33 UTC, danieljordan-caci commented on src/scenes/MyMove/index.jsx
> +                {multiMoveWorkflow && <Route path={generalRoutes.HOME_PATH} end element={<Home />} />}
That's correct - update that variable and then find that wherever it is in the code and change it accordingly.

2024-01-26 14:23 UTC, TevinAdams commented
> If these tests previously expected the redirect to go to their orders page, we should update the tests to navigate to the correct order URL instead of removing the test entirely. That's lot of test coverage that would get lost for pages that will still exist within the app

I adjusted all the tests to route to the multimove page. They cannot go any further than that until the workflows for uploading orders, navigating to the about page etc has been built into multi move landing page.

2024-01-29 19:00 UTC, danieljordan-caci approved these changes
Looks good to me!

I will have to make some adjustments to B-18313 to change to what you have done, but it should all work great!

2024-01-29 21:25 UTC, merged