B 18317 multi move get all moves endpoint (Integration)
transcom/mymove pull request #11866
Opened 2024-01-26 12:45 UTC by TevinAdams

## [Agility ticket](https://www13.v1host.com/USTRANSCOM38/Default.aspx?menu=StoryBoardPage)

## Summary

This story introduces a new endpoint on the internal API to retrieve all moves for a service member. The moves are returned in a json object with structure {currentMove: [{}], previousMoves: [{}]}

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Create a service member and go through the process of requesting a move.
2. Approve the move as a counselor and approve the move as a TOO
3. Add shipments to the move as a prime user
4. Through Postman or swagger send a request to the /all_moves{serviceMemberId} endpoint of the internalAPI
5. You should get a response with an JSON object {currentMove: [{}], previousMoves: [{}]}. currentMove will have one move in it representing the move with the latest CreatedAt DateTime. PreviousMoves will have all other moves.
6. To test previous moves make sure the service member has more than one move

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

## Screenshots

![image](https://github.com/transcom/mymove/assets/136514590/f99d53d3-1891-499f-bef7-e4a474e471e3)![image](https://github.com/transcom/mymove/assets/136514590/6f185b20-3b60-462f-9e5c-4c18c20ea054)

2024-01-26 19:31 UTC, danieljordan-caci commented
I am getting this error when testing:
```
{
  "message": "FETCH_FORBIDDEN"
}
```

Seems that the error is happening on this part of `FetchServiceMemberForUser`
```
	var serviceMember ServiceMember
	err := db.Q().Eager("User",
		"BackupMailingAddress",
		"BackupContacts",
		"DutyLocation.Address",
		"DutyLocation.TransportationOffice",
		"DutyLocation.TransportationOffice.PhoneLines",
		"Orders.NewDutyLocation.TransportationOffice",
		"Orders.OriginDutyLocation",
		"Orders.UploadedOrders.UserUploads.Upload",
		"Orders.Moves",
		"ResidentialAddress").Find(&serviceMember, id)

	if err != nil {
		if errors.Cause(err).Error() == RecordNotFoundErrorString {
			return ServiceMember{}, ErrFetchNotFound
		}
		// Otherwise, it's an unexpected err so we return that.
		return ServiceMember{}, err
	}
```

![Screenshot 2024-01-26 at 1 30 31 PM](https://github.com/transcom/mymove/assets/136510600/60c16896-c8b0-4afe-89a9-d16bd3a181ab)

2024-01-26 19:39 UTC, danieljordan-caci commented
Can you only call this endpoint when logged in & can you only query your own `id`?

2024-01-26 19:42 UTC, TevinAdams commented
> Can you only call this endpoint when logged in & can you only query your own `id`?

Yeah. You have to be logged in. So a service member can only see get their move information.

2024-01-26 19:43 UTC, TevinAdams commented
> I am getting this error when testing:
> 
> ```
> {
>   "message": "FETCH_FORBIDDEN"
> }
> ```
> 
> Seems that the error is happening on this part of `FetchServiceMemberForUser`
> 
> ```
> 	var serviceMember ServiceMember
> 	err := db.Q().Eager("User",
> 		"BackupMailingAddress",
> 		"BackupContacts",
> 		"DutyLocation.Address",
> 		"DutyLocation.TransportationOffice",
> 		"DutyLocation.TransportationOffice.PhoneLines",
> 		"Orders.NewDutyLocation.TransportationOffice",
> 		"Orders.OriginDutyLocation",
> 		"Orders.UploadedOrders.UserUploads.Upload",
> 		"Orders.Moves",
> 		"ResidentialAddress").Find(&serviceMember, id)
> 
> 	if err != nil {
> 		if errors.Cause(err).Error() == RecordNotFoundErrorString {
> 			return ServiceMember{}, ErrFetchNotFound
> 		}
> 		// Otherwise, it's an unexpected err so we return that.
> 		return ServiceMember{}, err
> 	}
> ```
> 
> ![Screenshot 2024-01-26 at 1 30 31 PM](https://private-user-images.githubusercontent.com/136510600/300091981-60c16896-c8b0-4afe-89a9-d16bd3a181ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyOTgxMjYsIm5iZiI6MTcwNjI5NzgyNiwicGF0aCI6Ii8xMzY1MTA2MDAvMzAwMDkxOTgxLTYwYzE2ODk2LWM4YjAtNGFmZS04OWE5LWQxNmJkM2ExODFhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNlQxOTM3MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02N2QxOWZkOTBhYjM3NDkxNjM4YTkwYzgyNDViMDA4ZDVjNTBlY2VjZjc5ZTdjZjhkYmUwNWJkMjRhNmExZTA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XwFi9PdC7gMy7qa6BVkkRv-Xc-xpDor8Gfa0Rpwprt0)

We will have to huddle because I never got this. Need to see what you are doing.

2024-01-26 19:59 UTC, danieljordan-caci commented
So when there is no moves associated with a user, I'm getting back:
```
{
  "currentMove": null,
  "previousMoves": null
}
```

What I'd like to get to avoid React errors and fit what I coded in previous BL items:
```
{
  "currentMove": [],
  "previousMoves": []
}
```

Could you add some checks to see if the `id` is `nil` or the list is `nil`, to return an empty array? I've already kinda toyed with it and this is getting me the result I want in `payloadMovesList`:
```
	// Convert currentMoves moves to internalmessages.MoveTaskOrder
	var convertedCurrentMovesList []*internalmessages.InternalMove
	if currentMoveList == nil || currentMoveList[0].ID == uuid.Nil {
		convertedCurrentMovesList = []*internalmessages.InternalMove{}
	} else {
		moves := movesList
		for _, move := range moves {

			eTag := etag.GenerateEtag(move.UpdatedAt)
			shipments := move.MTOShipments
			var payloadShipments *internalmessages.MTOShipments = payloads.MTOShipments(storer, &shipments)

			currentMove := &internalmessages.InternalMove{
				CreatedAt:    *handlers.FmtDateTime(move.CreatedAt),
				ETag:         eTag,
				ID:           *handlers.FmtUUID(move.ID),
				MtoShipments: *payloadShipments,
				MoveCode:     move.Locator,
				Orders:       move.Orders,
			}

			convertedCurrentMovesList = append(convertedCurrentMovesList, currentMove)
		}
	}

	// Convert previousMoves moves to internalmessages.MoveTaskOrder
	var convertedPreviousMovesList []*internalmessages.InternalMove
	if previousMovesList == nil {
		convertedPreviousMovesList = []*internalmessages.InternalMove{}
	} else {
		for _, move := range previousMovesList {

			if currentMoveList[0].ID != move.ID {
				eTag := etag.GenerateEtag(move.UpdatedAt)
				shipments := move.MTOShipments
				var payloadShipments *internalmessages.MTOShipments = payloads.MTOShipments(storer, &shipments)

				currentMove := &internalmessages.InternalMove{
					CreatedAt:    *handlers.FmtDateTime(move.CreatedAt),
					ETag:         eTag,
					ID:           *handlers.FmtUUID(move.ID),
					MtoShipments: *payloadShipments,
				}

				convertedPreviousMovesList = append(convertedPreviousMovesList, currentMove)
			}
		}
	}
```

2024-01-26 20:05 UTC, TevinAdams commented
> So when there is no moves associated with a user, I'm getting back:
> 
> ```
> {
>   "currentMove": null,
>   "previousMoves": null
> }
> ```
> 
> What I'd like to get to avoid React errors and fit what I coded in previous BL items:
> 
> ```
> {
>   "currentMove": [],
>   "previousMoves": []
> }
> ```
> 
> Could you add some checks to see if the `id` is `nil` or the list is `nil`, to return an empty array? I've already kinda toyed with it and this is getting me the result I want in `payloadMovesList`:
> 
> ```
> 	// Convert currentMoves moves to internalmessages.MoveTaskOrder
> 	var convertedCurrentMovesList []*internalmessages.InternalMove
> 	if currentMoveList == nil || currentMoveList[0].ID == uuid.Nil {
> 		convertedCurrentMovesList = []*internalmessages.InternalMove{}
> 	} else {
> 		moves := movesList
> 		for _, move := range moves {
> 
> 			eTag := etag.GenerateEtag(move.UpdatedAt)
> 			shipments := move.MTOShipments
> 			var payloadShipments *internalmessages.MTOShipments = payloads.MTOShipments(storer, &shipments)
> 
> 			currentMove := &internalmessages.InternalMove{
> 				CreatedAt:    *handlers.FmtDateTime(move.CreatedAt),
> 				ETag:         eTag,
> 				ID:           *handlers.FmtUUID(move.ID),
> 				MtoShipments: *payloadShipments,
> 				MoveCode:     move.Locator,
> 				Orders:       move.Orders,
> 			}
> 
> 			convertedCurrentMovesList = append(convertedCurrentMovesList, currentMove)
> 		}
> 	}
> 
> 	// Convert previousMoves moves to internalmessages.MoveTaskOrder
> 	var convertedPreviousMovesList []*internalmessages.InternalMove
> 	if previousMovesList == nil {
> 		convertedPreviousMovesList = []*internalmessages.InternalMove{}
> 	} else {
> 		for _, move := range previousMovesList {
> 
> 			if currentMoveList[0].ID != move.ID {
> 				eTag := etag.GenerateEtag(move.UpdatedAt)
> 				shipments := move.MTOShipments
> 				var payloadShipments *internalmessages.MTOShipments = payloads.MTOShipments(storer, &shipments)
> 
> 				currentMove := &internalmessages.InternalMove{
> 					CreatedAt:    *handlers.FmtDateTime(move.CreatedAt),
> 					ETag:         eTag,
> 					ID:           *handlers.FmtUUID(move.ID),
> 					MtoShipments: *payloadShipments,
> 				}
> 
> 				convertedPreviousMovesList = append(convertedPreviousMovesList, currentMove)
> 			}
> 		}
> 	}
> ```

Yeah I can return you empty arrays in that case.

2024-01-26 22:07 UTC, TevinAdams commented
> > So when there is no moves associated with a user, I'm getting back:
> > ```
> > {
> >   "currentMove": null,
> >   "previousMoves": null
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > What I'd like to get to avoid React errors and fit what I coded in previous BL items:
> > ```
> > {
> >   "currentMove": [],
> >   "previousMoves": []
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Could you add some checks to see if the `id` is `nil` or the list is `nil`, to return an empty array? I've already kinda toyed with it and this is getting me the result I want in `payloadMovesList`:
> > ```
> > 	// Convert currentMoves moves to internalmessages.MoveTaskOrder
> > 	var convertedCurrentMovesList []*internalmessages.InternalMove
> > 	if currentMoveList == nil || currentMoveList[0].ID == uuid.Nil {
> > 		convertedCurrentMovesList = []*internalmessages.InternalMove{}
> > 	} else {
> > 		moves := movesList
> > 		for _, move := range moves {
> > 
> > 			eTag := etag.GenerateEtag(move.UpdatedAt)
> > 			shipments := move.MTOShipments
> > 			var payloadShipments *internalmessages.MTOShipments = payloads.MTOShipments(storer, &shipments)
> > 
> > 			currentMove := &internalmessages.InternalMove{
> > 				CreatedAt:    *handlers.FmtDateTime(move.CreatedAt),
> > 				ETag:         eTag,
> > 				ID:           *handlers.FmtUUID(move.ID),
> > 				MtoShipments: *payloadShipments,
> > 				MoveCode:     move.Locator,
> > 				Orders:       move.Orders,
> > 			}
> > 
> > 			convertedCurrentMovesList = append(convertedCurrentMovesList, currentMove)
> > 		}
> > 	}
> > 
> > 	// Convert previousMoves moves to internalmessages.MoveTaskOrder
> > 	var convertedPreviousMovesList []*internalmessages.InternalMove
> > 	if previousMovesList == nil {
> > 		convertedPreviousMovesList = []*internalmessages.InternalMove{}
> > 	} else {
> > 		for _, move := range previousMovesList {
> > 
> > 			if currentMoveList[0].ID != move.ID {
> > 				eTag := etag.GenerateEtag(move.UpdatedAt)
> > 				shipments := move.MTOShipments
> > 				var payloadShipments *internalmessages.MTOShipments = payloads.MTOShipments(storer, &shipments)
> > 
> > 				currentMove := &internalmessages.InternalMove{
> > 					CreatedAt:    *handlers.FmtDateTime(move.CreatedAt),
> > 					ETag:         eTag,
> > 					ID:           *handlers.FmtUUID(move.ID),
> > 					MtoShipments: *payloadShipments,
> > 				}
> > 
> > 				convertedPreviousMovesList = append(convertedPreviousMovesList, currentMove)
> > 			}
> > 		}
> > 	}
> > ```
> 
> Yeah I can return you empty arrays in that case.

@danieljordan-caci  Done

2024-01-26 22:08 UTC, TevinAdams commented
> > So when there is no moves associated with a user, I'm getting back:
> > ```
> > {
> >   "currentMove": null,
> >   "previousMoves": null
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > What I'd like to get to avoid React errors and fit what I coded in previous BL items:
> > ```
> > {
> >   "currentMove": [],
> >   "previousMoves": []
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Could you add some checks to see if the `id` is `nil` or the list is `nil`, to return an empty array? I've already kinda toyed with it and this is getting me the result I want in `payloadMovesList`:
> > ```
> > 	// Convert currentMoves moves to internalmessages.MoveTaskOrder
> > 	var convertedCurrentMovesList []*internalmessages.InternalMove
> > 	if currentMoveList == nil || currentMoveList[0].ID == uuid.Nil {
> > 		convertedCurrentMovesList = []*internalmessages.InternalMove{}
> > 	} else {
> > 		moves := movesList
> > 		for _, move := range moves {
> > 
> > 			eTag := etag.GenerateEtag(move.UpdatedAt)
> > 			shipments := move.MTOShipments
> > 			var payloadShipments *internalmessages.MTOShipments = payloads.MTOShipments(storer, &shipments)
> > 
> > 			currentMove := &internalmessages.InternalMove{
> > 				CreatedAt:    *handlers.FmtDateTime(move.CreatedAt),
> > 				ETag:         eTag,
> > 				ID:           *handlers.FmtUUID(move.ID),
> > 				MtoShipments: *payloadShipments,
> > 				MoveCode:     move.Locator,
> > 				Orders:       move.Orders,
> > 			}
> > 
> > 			convertedCurrentMovesList = append(convertedCurrentMovesList, currentMove)
> > 		}
> > 	}
> > 
> > 	// Convert previousMoves moves to internalmessages.MoveTaskOrder
> > 	var convertedPreviousMovesList []*internalmessages.InternalMove
> > 	if previousMovesList == nil {
> > 		convertedPreviousMovesList = []*internalmessages.InternalMove{}
> > 	} else {
> > 		for _, move := range previousMovesList {
> > 
> > 			if currentMoveList[0].ID != move.ID {
> > 				eTag := etag.GenerateEtag(move.UpdatedAt)
> > 				shipments := move.MTOShipments
> > 				var payloadShipments *internalmessages.MTOShipments = payloads.MTOShipments(storer, &shipments)
> > 
> > 				currentMove := &internalmessages.InternalMove{
> > 					CreatedAt:    *handlers.FmtDateTime(move.CreatedAt),
> > 					ETag:         eTag,
> > 					ID:           *handlers.FmtUUID(move.ID),
> > 					MtoShipments: *payloadShipments,
> > 				}
> > 
> > 				convertedPreviousMovesList = append(convertedPreviousMovesList, currentMove)
> > 			}
> > 		}
> > 	}
> > ```
> 
> Yeah I can return you empty arrays in that case.

@danieljordan-caci  Done

2024-01-29 16:32 UTC, danieljordan-caci requested changes
Tested locally and passes. Returns an empty array

2024-01-29 16:32 UTC, danieljordan-caci commented on pkg/handlers/internalapi/moves.go
> +		convertedCurrentMovesList = []*internalmessages.InternalMove{}
The default model struct is not empty or `nil` so when a user does not have a current move, `currentMoveList` is not empty, it just has empty data for that object. So now I'm getting returned errors due to nil pointers.

That's why in my earlier comment, I was checking if the length was 0 or if `currentMoveList[0].ID == nil` in this check, which would then return the empty array.

For `previousMovesList` this length check is okay, but you'll need to check if at least one primary value is `nil` in the first object of this array.

2024-01-29 16:33 UTC, danieljordan-caci commented on pkg/handlers/internalapi/moves.go
> +		convertedCurrentMovesList = []*internalmessages.InternalMove{}
I was retesting this and discovered this - almost there!

2024-01-29 16:51 UTC, danieljordan-caci commented on pkg/handlers/internalapi/moves.go
> +			// var payloadOrders *internalmessages.Order = payloads
You gonna delete this comment?

2024-01-29 18:12 UTC, TevinAdams commented on pkg/handlers/internalapi/moves.go
> +		convertedCurrentMovesList = []*internalmessages.InternalMove{}
Edit I just made should handle this.

2024-01-29 18:12 UTC, TevinAdams commented on pkg/handlers/internalapi/moves.go
> +			// var payloadOrders *internalmessages.Order = payloads
Removed.

2024-01-29 18:54 UTC, danieljordan-caci approved these changes
Looks good! Tested on multiple users and got appropriate results. Good job!

2024-01-30 15:07 UTC, TevinAdams commented
> @TevinAdams Heads up, incorrect agility ticket link

Fixed that. Forgot about the share link in agility.

2024-01-30 15:47 UTC, cameroncaci requested changes

2024-01-30 15:47 UTC, cameroncaci commented on pkg/models/move.go
> +		"Orders.ServiceMember.DutyLocation.TransportationOffice.Address",
Can you switch this to pull the current duty location from the order? Eg `Orders.OriginDutyLocation.Address`

2024-01-30 15:47 UTC, cameroncaci commented on pkg/handlers/internalapi/moves_test.go
> +		// // Then: expect a 200 status code
Double comments

2024-01-30 15:47 UTC, cameroncaci commented on pkg/handlers/internalapi/moves.go
> +	}
Can you make this a shared function?

2024-01-30 15:47 UTC, cameroncaci commented on pkg/handlers/internalapi/moves.go
> +	} else {
This if statement isn't necessary, `convertedPreviousMovesList` is already of type `[]*internalmessages.InternalMove{}`. Additionally, the `for _, move := range previousMovesList {` won't run if it's length is 0

2024-01-30 15:47 UTC, cameroncaci commented on pkg/handlers/internalapi/moves.go
> +func payloadMovesList(storer storage.FileStorer, previousMovesList models.Moves, currentMoveList models.Moves, movesList models.Moves) (*internalmessages.MovesList, error) {
This function appears to never return an error

2024-01-30 15:47 UTC, cameroncaci commented on pkg/models/move.go
> +		"Orders.UploadedOrders.ServiceMember.DutyLocation.TransportationOffice.Address",
Again here, we'll want to pull the `OriginDutyLocation` from the uploaded orders, since we're getting rid of service member duty location

2024-01-30 15:47 UTC, cameroncaci commented on pkg/handlers/internalapi/moves.go
> +				convertedPreviousMovesList = append(convertedPreviousMovesList, currentMove)
No tests present specifically testing the result of `currentMove` or `convertedPreviousMovesList`

2024-01-30 16:16 UTC, TevinAdams commented on pkg/handlers/internalapi/moves.go
> +				convertedPreviousMovesList = append(convertedPreviousMovesList, currentMove)
There aren't any tests created for any of the payload conversions in this file(payloadForMoveModel, payloadForPPMModel). However they are all tested through the method that invokes them. In those tests these methods are implemented, and covered which keep test coverage up and if anything in these methods fail then the test will fail.

2024-01-30 16:18 UTC, TevinAdams commented on pkg/handlers/internalapi/moves.go
> +func payloadMovesList(storer storage.FileStorer, previousMovesList models.Moves, currentMoveList models.Moves, movesList models.Moves) (*internalmessages.MovesList, error) {
Fixed

2024-01-30 16:18 UTC, TevinAdams commented on pkg/handlers/internalapi/moves_test.go
> +		// // Then: expect a 200 status code
Removed

2024-01-30 17:00 UTC, cameroncaci commented on pkg/handlers/internalapi/moves.go
> +	}
For example, you create a nil var `convertedCurrentMovesList` and `convertedPreviousMovesList` that get appended to from this loop. Since this is within the internalapi and may be used again, I was suggesting move this loop to a function that will return these two vars so that they can be assigned with `:=` instead of appending

2024-01-30 17:51 UTC, cameroncaci commented on pkg/handlers/internalapi/moves.go
> +	} else {
If it's a pointer isn't it still `nil` and not `empty`? I see that you add on `{}` but it should still be nil right?

2024-01-30 18:13 UTC, TevinAdams commented on pkg/handlers/internalapi/moves.go
> +	} else {
`var convertedCurrentMovesList []*internalmessages.InternalMove` results in nil. `[]*internalmessages.InternalMove{}` results in []. This is whats needed to be returned.

2024-01-30 18:21 UTC, cameroncaci commented on pkg/handlers/internalapi/moves.go
> +	} else {
I see. If that's the case shouldn't we update 
```
	movePayload := &internalmessages.MovesList{
		CurrentMove:   convertedCurrentMovesList,
		PreviousMoves: convertedPreviousMovesList,
	}
```

To have a pointer so it can be nil and not empty? I may be remembering wrong off the top of my head, but does an empty object still count as a length? I don't think we would want to return a length if there aren't any previous moves

2024-01-30 18:22 UTC, danieljordan-caci commented on pkg/handlers/internalapi/moves.go
> +	} else {
It does if it has a struct that is not an empty array

2024-01-30 19:39 UTC, TevinAdams commented on pkg/models/move.go
> +		"Orders.ServiceMember.DutyLocation.TransportationOffice.Address",
Made this adjustment

2024-01-30 19:44 UTC, TevinAdams commented on pkg/models/move.go
> +		"Orders.UploadedOrders.ServiceMember.DutyLocation.TransportationOffice.Address",
This adjustment has been made.

2024-01-30 20:12 UTC, TevinAdams commented on pkg/gen/ghcapi/embedded_spec.go
> +          "x-omitempty": false,
Need to undo

2024-01-30 20:12 UTC, TevinAdams commented on pkg/gen/ghcapi/embedded_spec.go
> +          "x-omitempty": false,
need to undo

2024-01-30 20:12 UTC, TevinAdams commented on pkg/gen/ghcapi/embedded_spec.go
> -        },
need to undo

2024-01-30 22:32 UTC, traskowskycaci approved these changes

2024-01-30 22:37 UTC, TevinAdams commented on pkg/handlers/internalapi/moves.go
> +	} else {
The if statement has been removed and the code has been refactored. Right now, if there aren't any previous moves we are returning an empty array as needed. In this case the length is 0 with no objects within the array.

2024-01-30 22:38 UTC, TevinAdams commented on pkg/handlers/internalapi/moves.go
> +	}
Moved a lot of the implementation to its own method allowing the functionality to be shared

2024-01-31 12:59 UTC, cameroncaci approved these changes

2024-01-31 14:41 UTC, merged