E 04823 tickets b 18472 and b 18457 int
transcom/mymove pull request #11893
Opened 2024-01-30 15:42 UTC by traskowskycaci

## [Feature E-04823](https://www13.v1host.com/USTRANSCOM38/Epic.mvc/Summary?oidToken=Epic%3A866910)
- [Frontend: B-18472](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A887939)
- [Backend: B-18457](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A886626)
## Summary
These two tickets introduce new business logic and refactoring with how service member duty location, grade, and weight allotments function within MilMove. At a high level, grade and duty location has moved from the service member to the order. Additionally, grades now reflect a "true" value that is calculated by weight allotment and assigned to a `DBWeightAuthorized`. `DBWeightAuthorized` is directly tied to the maximum billable weight of a move. When a service member grade is updated, it immediately updated the maximum billable weight, whether it be increasing or decreasing the maximum amount.
## Verification Steps for Reviewers
- [ ] Do grade updates on the order accurately update the correct weight for the move? Entitlements can be found here: `pkg/models/entitlements.go`
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?
- [ ] Has the branch been pulled in and checked out?
### Setup to Run the Code
- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)
### How to test
Frontend:
1. Create a new customer profile and ensure you see the correct weight allowances based on your grade and dependents value. You can see this when adding shipments, as a TOO or services counselor, and throughout the flow.
2. When adding your grade and dependents to the orders, go back and edit them and make sure the weight allowance changes to reflect that.
3. Ensure that Current duty location and Grade are no longer seen in the Service Info or Profile section, and are instead associated with the orders on the review page after adding orders and before submitting the move.

Backend:
1. Login as a TIO
4. Select a move
5. Navigate to move details -> allowances
6. Make note of the "Weight allowance"
7. Update the grade to something that will change the weight allowance (See `pkg/models/entitlements.go`)
8. Review
9. Login as a Counselor
10. Select a move
11. Navigate to move details -> allowances
12. Make note of the "Weight allowance"
13. Update the grade to something that will change the weight allowance (See `pkg/models/entitlements.go`)
14. Review
15. Additionally, you can set the `HasDependents` value on the order to true or false, then update the grade again to review how dependents affect the weight allowance.
## Screenshots

2024-02-01 19:43 UTC, cameroncaci commented
@traskowskycaci 
Load testing is G2G!

2024-02-01 19:44 UTC, traskowskycaci commented
> @traskowskycaci Load testing is G2G!

Woooo!

2024-02-02 14:11 UTC, danieljordan-caci commented on pkg/models/service_member_grade.go
> +	ServiceMemberGradeE1 internalmessages.OrderPayGrade = "E_1"
Is there a reason these variable names are `ServiceMemberGrade` and not `ServiceMemberPayGrade`?

2024-02-02 14:12 UTC, danieljordan-caci commented on pkg/models/service_member_grade.go
> +	ServiceMemberGradeE1 internalmessages.OrderPayGrade = "E_1"
As a service member myself, a pay grade is rarely, if ever, just called `grade`

If it's a huge change, don't worry about it - just my two cents!

2024-02-02 20:04 UTC, paulstonebraker approved these changes
Tested per testing instructions, and did code review 😵‍💫 nicely done

2024-02-05 14:32 UTC, danieljordan-caci commented on pkg/handlers/primeapiv2/payloads/model_to_payload.go
> +		Rank:                           &grade, // Convert prime API "Rank" into our internal tracking of "Grade"
Does this need to be `Grade` instead of `Rank`?

2024-02-05 14:34 UTC, danieljordan-caci commented on pkg/handlers/primeapiv2/payloads/model_to_payload.go
> +		Rank:                           &grade, // Convert prime API "Rank" into our internal tracking of "Grade"
OOHHH, I think I see what's happening here. The prime provides `Rank` - are we tracking this? Is there a plan to make that change?

2024-02-05 14:38 UTC, danieljordan-caci commented on pkg/models/entitlements.go
> +	return WeightAllotment{}, fmt.Errorf("no entitlement found for rank %s", grade)
Should this read `no entitlement found for pay grade %s`?

2024-02-05 14:57 UTC, cameroncaci commented on pkg/models/entitlements.go
> +	return WeightAllotment{}, fmt.Errorf("no entitlement found for rank %s", grade)
Yes, yes it should. Thanks for the catch

2024-02-05 14:58 UTC, cameroncaci commented on pkg/handlers/primeapiv2/payloads/model_to_payload.go
> +		Rank:                           &grade, // Convert prime API "Rank" into our internal tracking of "Grade"
> OOHHH, I think I see what's happening here. The prime provides `Rank` - are we tracking this? Is there a plan to make that change from `Rank` to `Grade` eventually?

Precisely, that's what is happening. And as for a plan, there is currently no "official" plan. It's an unofficial "When we ever deprecate endpoint X and make a new V2 or higher endpoint, then rename Rank to be Grade."

This is to avoid breaking a bunch of different endpoints for a change so small.

2024-02-05 14:59 UTC, cameroncaci commented on pkg/models/service_member_grade.go
> +	ServiceMemberGradeE1 internalmessages.OrderPayGrade = "E_1"
Appreciate the service member insight! It should be an easy refactor, I'll give it a try. If it's not easy, then I'll let ya know

2024-02-05 15:03 UTC, danieljordan-caci commented on pkg/models/service_member_grade.go
> +	ServiceMemberGradeE1 internalmessages.OrderPayGrade = "E_1"
Not a hill I wanna die on btw. Just something I've always thought when reading `grade` - makes me think of `A+` or `D-` instead of a pay grade haha

2024-02-05 15:03 UTC, danieljordan-caci requested changes
Couple changes - once those are corrected, I'll give it to ya!

2024-02-05 15:07 UTC, deandreJones commented on pkg/factory/order_factory_test.go
> +		suite.Equal(originDutyLocationTOName, order.OriginDutyLocation.TransportationOffice.Name)
suite.Equal(originDutyLocation.Name, order.OriginDutyLocation.Name)
suite.Equal(originDutyLocationTOName, order.OriginDutyLocation.TransportationOffice.Name)

are these entries duplicated on purpose?

2024-02-05 15:35 UTC, danieljordan-caci commented on pkg/factory/order_factory_test.go
> +		suite.Equal(originDutyLocationTOName, order.OriginDutyLocation.TransportationOffice.Name)
Can't get nothin' past eagle eye Dre!

2024-02-05 16:17 UTC, cameroncaci commented on pkg/factory/order_factory_test.go
> +		suite.Equal(originDutyLocationTOName, order.OriginDutyLocation.TransportationOffice.Name)
Resolved!

2024-02-05 16:17 UTC, cameroncaci commented on pkg/models/entitlements.go
> +	return WeightAllotment{}, fmt.Errorf("no entitlement found for rank %s", grade)
Resolved!

2024-02-05 16:17 UTC, cameroncaci commented on pkg/models/service_member_grade.go
> +	ServiceMemberGradeE1 internalmessages.OrderPayGrade = "E_1"
Refactored and resolved!

2024-02-05 16:18 UTC, danieljordan-caci commented on pkg/models/service_member_grade.go
> +	ServiceMemberGradeE1 internalmessages.OrderPayGrade = "E_1"
My man!

2024-02-05 16:19 UTC, danieljordan-caci approved these changes
WOOHOO!

LGTM!

2024-02-05 16:46 UTC, merged