B-18326 Update the Estimated Weight - B-18327 Remove Fields - B-18322 Update Requested pickup date
transcom/mymove pull request #11941
Opened 2024-02-06 21:57 UTC by WeatherfordAaron

[Previous PR into integration testing](https://github.com/transcom/mymove/pull/11803)

2024-02-06 22:26 UTC, KonstanceH reviewed
- [ ] There are a couple floating ';' on the page
Other than that everything looks good to me

2024-02-08 15:58 UTC, taeJungCaci commented
Changes in this PR doesn't seem to match the PR to Integration.

For example:

 `columnHeaders={[headerPlannedMoveDate, headerActualMoveDate, headerActualArrivalDate]}`

is in the PR to Integration for not on this one.

2024-02-08 22:34 UTC, JamesHawks224 commented
test issue:
";" artifact showing on screen

![image](https://github.com/transcom/mymove/assets/146897935/5e7225b8-e26f-4f57-bb67-36a57913701e)

2024-02-08 22:38 UTC, JamesHawks224 commented
test issue:

test step 4 failed.
Observe that none of the follow fields show up:
...
-Requested Pickup Date
-Scheduled Pickup Date
-Actual Pickup Date

These fields show up on the MTO page
![image](https://github.com/transcom/mymove/assets/146897935/ff52a93a-d9ad-42c1-afda-1ecd6d3e2c85)

2024-02-08 22:42 UTC, JamesHawks224 commented
testing issue:

Step 4.
The following dates were enetered during shipment setup.
orders date:  1/3/2024
rpt by date:  4/2/2024
planned move date:  1/16/2024

No values show up in the MTO
![image](https://github.com/transcom/mymove/assets/146897935/6a0f88c7-cc70-4d7c-8dc0-ea15c7384c53)

2024-02-09 14:48 UTC, taeJungCaci requested changes
https://github.com/transcom/mymove/pull/11941#issuecomment-1934431587

2024-02-15 17:52 UTC, WeatherfordAaron commented
> Changes in this PR doesn't seem to match the PR to Integration.
> 
> For example:
> 
> `columnHeaders={[headerPlannedMoveDate, headerActualMoveDate, headerActualArrivalDate]}`
> 
> is in the PR to Integration but not on this one.

I checked the old branch against this branch and am not seeing a diff. Can you check one more time?

2024-02-22 17:31 UTC, JamesHawks224 commented
Verification rpt attached.
There were differences.
[B18326.verify_rpt.txt](https://github.com/transcom/mymove/files/14377372/B18326.verify_rpt.txt)

2024-02-27 17:43 UTC, taeJungCaci commented
> > Changes in this PR doesn't seem to match the PR to Integration.
> > For example:
> > `columnHeaders={[headerPlannedMoveDate, headerActualMoveDate, headerActualArrivalDate]}`
> > is in the PR to Integration but not on this one.
> 
> I checked the old branch against this branch and am not seeing a diff. Can you check one more time?

This was discussed through a DM in slack. Adding this comment as a reference.

2024-02-27 18:11 UTC, JamesHawks224 commented
Per dev, main pr is correct and complete.

2024-02-29 21:35 UTC, KonstanceH approved these changes

2024-02-29 21:47 UTC, taeJungCaci commented on src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
> +      displayedDeliveryAddress = destinationAddress || destinationDutyLocationAddress;
Looks like you have duplicated changes. These lines are already in line 166~168

2024-02-29 22:28 UTC, WeatherfordAaron commented
> Changes in this PR doesn't seem to match the PR to Integration.
> 
> For example:
> 
> `columnHeaders={[headerPlannedMoveDate, headerActualMoveDate, headerActualArrivalDate]}`
> 
> is in the PR to Integration but not on this one.

The current state of the ask from the PO is not to have the 3 fields but rather to only have 2. The names are correct at this time AFAIK.

2024-02-29 22:29 UTC, WeatherfordAaron commented on src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
> +      displayedDeliveryAddress = destinationAddress || destinationDutyLocationAddress;
Pushing that fix now. Thank you buddy

2024-02-29 22:32 UTC, taeJungCaci commented on src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
> +      displayedDeliveryAddress = destinationAddress || destinationDutyLocationAddress;
No problem! But if those 3 lines of code are all there is in this PR, isn't that mean the changes are already in main and this PR is actually not needed?

2024-02-29 22:34 UTC, taeJungCaci commented on src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
> +      displayedDeliveryAddress = destinationAddress || destinationDutyLocationAddress;
because I see 0 files changed now in this PR

2024-02-29 22:45 UTC, WeatherfordAaron commented on src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
> +      displayedDeliveryAddress = destinationAddress || destinationDutyLocationAddress;
Correct

2024-03-01 18:47 UTC, closed without merging