B 18645 move grade to orders from allowances int
transcom/mymove pull request #12011
Opened 2024-02-15 18:05 UTC by traskowskycaci

## [Agility ticket](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3a904659)

## Summary

As part of previous work on the customer view, we moved the Grade and Current Duty Location fields to be associated with the Orders for all customer facing pages.

For the TOO/Services Counselor view, the pay grade is currently displayed under the Allowances section and edited by clicking the "Edit Allowances" button.

This work will be moving the pay grade to be under the Orders section rather than the Allowances section, as well as editing the pay grade by using the "View and edit orders" button.

Changes to be made for TOO/Services Counselor screens:

- Update the pay grade to be shown under the Orders section.

- Remove the pay grade from the Allowances section.

- Update the "View and edit orders" button to allow editing of the pay grade.

- Remove the editing of the pay grade from the "Edit Allowances" section.

### How to test

TOO
1. Access the office app as a TOO
2. Make sure pay grade is under the Orders section
3. Make sure you can edit the pay grade
4. When you edit the pay grade, check that the Allowances -> Weight allowance was updated

Services counselor
1. Access the office app as a TOO
2. Make sure pay grade is under the Orders section
3. Make sure you can edit the pay grade
4. When you edit the pay grade, check that the Allowances -> Weight allowance was updated

## Screenshots
Previous view:
<img width="1078" alt="image" src="https://github.com/transcom/mymove/assets/147537467/bfb111e0-4330-491e-be6a-e6c1ad5fe9f7">

Current view:
<img width="961" alt="image" src="https://github.com/transcom/mymove/assets/147537467/c55be2c7-fc08-4162-904f-e9fecaf79cb5">

2024-02-16 16:42 UTC, danieljordan-caci requested changes

2024-02-16 16:42 UTC, danieljordan-caci commented on playwright/tests/office/qaecsr/csrFlows.spec.js
> +      await expect(page.locator('select[name="payGrade"]')).toBeDisabled();
There a reason there are two of these?

2024-02-16 16:42 UTC, danieljordan-caci commented on src/components/Office/DefinitionLists/AllowancesList.test.jsx
If you're going to remove the grade from this test, I'd also update the description to not include `grade`

2024-02-16 16:42 UTC, danieljordan-caci commented on src/pages/Office/Orders/Orders.jsx
> +    const { originDutyLocation, newDutyLocation, payGrade, ...fields } = values;
Looks like you're taking `payGrade` out of the values object, but not using it anywhere

2024-02-16 19:32 UTC, traskowskycaci commented on playwright/tests/office/qaecsr/csrFlows.spec.js
> +      await expect(page.locator('select[name="payGrade"]')).toBeDisabled();
Not a good one! Removed.

2024-02-16 19:32 UTC, traskowskycaci commented on src/components/Office/DefinitionLists/AllowancesList.test.jsx
Fixed this

2024-02-16 19:32 UTC, traskowskycaci commented on src/pages/Office/Orders/Orders.jsx
> +    const { originDutyLocation, newDutyLocation, payGrade, ...fields } = values;
Fixed this

2024-02-20 14:52 UTC, danieljordan-caci approved these changes
Tested locally and passes test cases.
L
G
T
M
!!!

2024-02-20 16:23 UTC, cameroncaci requested changes
Tested functionality successfully, included 2 code reviews

2024-02-20 16:23 UTC, cameroncaci commented on pkg/services/order/order_updater.go
> +
This code will call a pointer to a value that may not exist - `models.GetWeightAllotment` expects the value to not be nil. This code should all be wrapped inside the `!= nil statement`

2024-02-20 16:23 UTC, cameroncaci commented on pkg/services/order/order_updater.go
> +	order.Entitlement.DBAuthorizedWeight = &weight
Here again, just placing this code inside the nil check. If not, it will attempt to reference nonexistent code.

2024-02-20 18:10 UTC, traskowskycaci commented on pkg/services/order/order_updater.go
> +	order.Entitlement.DBAuthorizedWeight = &weight
Good catch! Fixed.

2024-02-20 18:10 UTC, traskowskycaci commented on pkg/services/order/order_updater.go
> +
Good catch! Fixed.

2024-02-20 18:57 UTC, merged