B 18914 int
transcom/mymove pull request #12074
Opened 2024-02-26 22:34 UTC by deandreJones

## [18914](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A908087)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

2024-02-26 22:36 UTC, danieljordan-caci approved these changes

2024-02-27 12:59 UTC, cameroncaci requested changes

2024-02-27 12:59 UTC, cameroncaci commented on src/utils/featureFlags.js
> +  const flagKey = 'counselor_move_create';
key naming should match local environment variable fallback (Without the `FEATURE_FLAG_` of course, just `counselor_move_creation`. See review on feature flag repo as well

2024-02-27 14:12 UTC, deandreJones commented on src/utils/featureFlags.js
> +  const flagKey = 'counselor_move_create';
updated to counselor_move_create in env files and envrc

2024-02-29 21:42 UTC, traskowskycaci approved these changes

2024-03-01 14:28 UTC, cameroncaci approved these changes
Resolved comments, all keys matching! G2G

Util to retrieve FF also G2G

2024-03-01 17:55 UTC, merged