Main b 18824 requested office users get single user endpoint
transcom/mymove pull request #12122
Opened 2024-03-01 15:09 UTC by danieljordan-caci

[INTEGRATION PR](https://github.com/transcom/mymove/pull/12121)

## [Agility ticket](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3a907137)

## Summary

***please ignore my brainfart*** the branch has the incorrect BL item, it should be `B-18824` and not `B-18885`

When it comes to having office users requesting their account, the admins will eventually need to review that user in the Admin console within MilMove. This will require an endpoint that can be called to retrieve that information so the UI can display it. I took notes off of what was being done for viewing admin users and pretty much copied that functionality over to `requested_office_users`.

I have merged the branch of [B-18822](https://github.com/transcom/mymove/pull/12113) into this in order to copy over the creation of the endpoint done in that branch.

The return value of querying the db should look like this:
```
{
  "id": "c56a4180-65aa-42ec-a945-5fd21dec0538",
  "userId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "firstName": "string",
  "middleInitials": "string",
  "lastName": "string",
  "email": "dkj-9pUmr@uLdkqVEkf9MsW9h8yoezuK-Eg5HEirPkavMgiFw8tvPyuVMaKQy3uys3ig3IrQM5WOyg9x2yvOsc3K1M2kv.rBrA5hihPdWu3.kYiMtccDklvvtbpSBUutDabBbbDQwVkCdVbTDmiKssUrhyvBpMGdnTAgvrsTONFhcPznXnAPeydXIKvZmBFqBYobvctock",
  "telephone": "468-681-8762",
  "transportationOfficeId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "active": true,
  "roles": [
    {
      "id": "c56a4180-65aa-42ec-a945-5fd21dec0538",
      "roleType": "customer",
      "roleName": "Transportation Ordering Officer",
      "createdAt": "2024-03-01T14:36:30.952Z",
      "updatedAt": "2024-03-01T14:36:30.952Z"
    }
  ],
  "edipi": "string",
  "otherUniqueId": "string",
  "rejectionReason": "string",
  "status": "APPROVED",
  "createdAt": "2024-03-01T14:36:30.952Z",
  "updatedAt": "2024-03-01T14:36:30.952Z"
}
```

This PR does the following:
- adds `GET requested-office-users/{officeUserId}` endpoint that returns a single row in the `office_users` table
- updates `swagger-def` to include the endpoint and handle the return values
- updated and added relevant tests

### How to test

1. Fire up `client` & `server`
2. Access MM as an admin
3. It isn't necessary, but make sure you have some users in the `office_users` table, they don't NEED to have a `REQUESTED` status, this query should still return a user
4. Head on over to `http://adminlocal:3000/swagger-ui/admin.html#/`
5. Copy an office user's `id` from the `office_users` table
6. Find the `requested-office-users/{officeUserId}` endpoint and plug in that `id`
7. Execute that sucker and you should get a return value back

## Screenshots
![Screenshot 2024-03-01 at 8 36 41 AM](https://github.com/transcom/mymove/assets/136510600/ecd6a649-e5bc-4304-a2b0-91e565696220)

2024-03-20 16:11 UTC, traskowskycaci requested changes
Slight difference noticed, capital O was changed to lowercase o in integration but is still capital in main

![image](https://github.com/transcom/mymove/assets/147537467/a85d9fbe-86c5-47a4-b0d5-d6f38c3f13b5)

![image](https://github.com/transcom/mymove/assets/147537467/f6ea69f7-e078-4ef6-baa7-317b3112bba1)

2024-03-20 16:14 UTC, danieljordan-caci commented
> Slight difference noticed, capital O was changed to lowercase o in integration but is still capital in main
> 
> ![image](https://private-user-images.githubusercontent.com/147537467/314576486-a85d9fbe-86c5-47a4-b0d5-d6f38c3f13b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5NTE0MDEsIm5iZiI6MTcxMDk1MTEwMSwicGF0aCI6Ii8xNDc1Mzc0NjcvMzE0NTc2NDg2LWE4NWQ5ZmJlLTg2YzUtNDdhNC1iMGQ1LWQ2ZjM4YzNmMTNiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMFQxNjExNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZjM4ZmM0NzNkOTExZjU1YTk3NzhjNzRhZjY1Mjc2MTAwMDZmMzM0NmJjYTExZjM2YjJiMTA3NTgzMzllZTZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YU5AMsF36u_XwVeo3H4aOfyGQUDgeLZWio-OCUCuT28)
> 
> ![image](https://private-user-images.githubusercontent.com/147537467/314576677-f6ea69f7-e078-4ef6-baa7-317b3112bba1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5NTE0MDEsIm5iZiI6MTcxMDk1MTEwMSwicGF0aCI6Ii8xNDc1Mzc0NjcvMzE0NTc2Njc3LWY2ZWE2OWY3LWUwNzgtNGVmNi1iYWE3LTMxN2IzMTEyYmJhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMFQxNjExNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYTNmODM3NzZiMDE1NTc0YzhjNzY4OTU0MDVhY2Y4ZDljNjE1YmEzODZiOTM3ZjY4MzFhNjJjNWJkNGUzMjM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zb5TTlEISbl2mfYryehgpDhutD2TZr7XDUAH8kDC7mc)

ugh that's annoying. This will likely have some slight variations from integration because I'm going to need to add that tag to the top of the swagger file and that is something I did NOT do in the integration branch for this PR

2024-03-20 16:22 UTC, traskowskycaci approved these changes

2024-03-20 16:23 UTC, danieljordan-caci commented
Reviewers, you will see a discrepancy in the file changes here due to updating swagger global tags and descriptions to please the spectral checks. The other commits should match up with the integration branch PR.

2024-03-21 14:28 UTC, TevinAdams approved these changes

2024-04-03 19:34 UTC, cameroncaci approved these changes

2024-04-03 19:34 UTC, merged