B 18885 sit delivery miles calculation int
transcom/mymove pull request #12171
Opened 2024-03-06 14:37 UTC by traskowskycaci

## [Agility ticket](tbd)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-03-07 18:22 UTC, traskowskycaci commented
> Showed Danny both origin and destination SIT delivery calculation examples and he is good with them all, with the exception of maybe needing to use zip5 rather than zip3 for some zip calculations. Getting further clarification on that.

Dre found the fix for this - we were using a mocked DTOD service rather than using the actual DTOD service. Turned that flag off so we should be getting accurate calculations for zips that use DTOD rather than Rand McNally.

2024-03-12 16:04 UTC, cameroncaci requested changes

2024-03-12 16:04 UTC, cameroncaci commented on pkg/services/mto_shipment/mto_shipment_address_updater.go
> +			}
This transaction is inside of the loop instead of being at the root level of the loop, meaning if part of the loop fails the other half that already executed will persist to the db

2024-03-12 16:04 UTC, cameroncaci commented on pkg/services/mto_shipment/mto_shipment_updater.go
> +			}
This transaction is inside of the loop instead of being at the root level of the loop, meaning if part of the loop fails the other half that already executed will persist to the db

2024-03-12 16:04 UTC, cameroncaci commented on pkg/services/shipment_address_update/shipment_address_update_requester.go
> +		}
Err check here can be removed and replaced with just
```
		if len(shipment.MTOServiceItems) > 0 {
// Comment explaining why it is returned early here if len of service items is > 0
			return mtoshipment.UpdateDestinationSITServiceItemsSITDeliveryMiles(f.planner, appCtx, &shipment, &addressUpdate.NewAddress, true)
		}
```

2024-03-12 17:34 UTC, traskowskycaci commented on .envrc
> +export DTOD_USE_MOCK=false
I can set it back to true and use a local .envrc variable, but I wanted it to be on in integration so that it can be accurately tested.

2024-03-12 18:20 UTC, cameroncaci commented on .envrc
> +export DTOD_USE_MOCK=false
Is this for playwright or server tests?

2024-03-12 18:20 UTC, cameroncaci commented on .envrc
> +export DTOD_USE_MOCK=false
Or e2e?

2024-03-12 18:24 UTC, deandreJones commented on .envrc
> +export DTOD_USE_MOCK=false
this is actually for calculations in general and whether the app should call dtod or use the made up miles
i think the hosted envrionments should actually call dtod

2024-03-12 19:56 UTC, traskowskycaci commented on pkg/services/mto_shipment/mto_shipment_address_updater.go
> +	}
Fixed

2024-03-12 19:56 UTC, traskowskycaci commented on pkg/services/mto_shipment/mto_shipment_address_updater.go
> +			}
Fixed

2024-03-12 19:56 UTC, traskowskycaci commented on pkg/services/mto_shipment/mto_shipment_address_updater.go
> +	}
Fixed

2024-03-12 19:56 UTC, traskowskycaci commented on pkg/services/shipment_address_update/shipment_address_update_requester.go
> +		}
Fixed

2024-03-12 19:57 UTC, traskowskycaci commented
Updated the document I made that is attached to the story, which should make testing this fairly straight forward.

2024-03-13 14:55 UTC, danieljordan-caci approved these changes
This looks pretty good, nothing is jumping out at me. LGTM!

2024-03-13 16:10 UTC, TevinAdams approved these changes
Worked through the test cases and didn't run into any issues.

2024-03-13 16:10 UTC, deandreJones approved these changes

2024-03-13 16:28 UTC, traskowskycaci commented on .envrc
> +export DTOD_USE_MOCK=false
Is this good to go up to integration as false?

2024-03-13 16:28 UTC, traskowskycaci commented on .envrc
> +export DTOD_USE_MOCK=false
@deandreJones

2024-03-13 16:31 UTC, deandreJones commented on .envrc
> +export DTOD_USE_MOCK=false
yes

2024-03-13 16:43 UTC, traskowskycaci commented
@cameroncaci need your approval of the requested changes then I'm good to go!

2024-03-13 16:48 UTC, cameroncaci requested changes

2024-03-13 16:48 UTC, cameroncaci commented on pkg/services/mto_shipment/mto_shipment_address_updater.go
> +			updatedMtoServiceItems = append(updatedMtoServiceItems, serviceItem)
Err not handled

2024-03-13 16:48 UTC, cameroncaci commented on pkg/services/mto_service_item/mto_service_item_updater.go
> +			}
Err not handled

2024-03-13 16:48 UTC, cameroncaci commented on pkg/services/mto_service_item/mto_service_item_updater.go
> +				}
Err not handled

2024-03-13 16:48 UTC, cameroncaci commented on pkg/services/mto_shipment/mto_shipment_updater.go
> +			}
Err not handled

2024-03-13 17:01 UTC, traskowskycaci commented on pkg/services/mto_shipment/mto_shipment_address_updater.go
> +			updatedMtoServiceItems = append(updatedMtoServiceItems, serviceItem)
Fixed

2024-03-13 17:01 UTC, traskowskycaci commented on pkg/services/mto_shipment/mto_shipment_updater.go
> +			}
Fixed

2024-03-13 17:13 UTC, cameroncaci approved these changes
Stamp!

2024-03-13 19:39 UTC, merged