B:18520 Update Nav Links To Return To Move Page (Integration)
transcom/mymove pull request #12197
Opened 2024-03-08 17:41 UTC by TevinAdams

## [Agility ticket](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-18520)

## Summary

Went through the milmove multimove workflows and updated the page navigations to route to customerRoutes.MOVE_HOME_PAGE (The Move) where needed. Let me know if I missed any workflows or navigations.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the milmove app as a service member
2. Go through the workflow of creating a user then a move. Go through the workflow of creating shipments.
3. Go through all workflows to catch where anywhere in the workflows navigations it should route back to the move.
4. Go through the edit workflows and backing out of the edit workflows.
5. Go through the workflows saving changes.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-03-12 13:28 UTC, traskowskycaci reviewed
After I submit the move as the customer, which page should I see next? Currently I am routed to the dashboard rather than the move page itself.

2024-03-12 13:40 UTC, traskowskycaci requested changes
Seeing the Oops, something went wrong page when I:
- Go through customer flow
- Whenever I can (either before or after submitting move) go to the Edit Profile page.
- Click the Edit next to Contact Info
![image](https://github.com/transcom/mymove/assets/147537467/741967e8-a86a-4cce-a5c8-f78b7bf4bb69)
- Click the save button at the bottom of the page. I didn't change any values before saving
- Click Return to move, which tries to route me to http://milmovelocal:3000/move/:moveId. This is where I see the something went wrong page. Seemed related to orders.
![image](https://github.com/transcom/mymove/assets/147537467/59244fe5-c1ea-43f6-a38d-62e3ba4a1c7b)
CCing @danieljordan-caci to see if this popped up in any of the previous PRs on orders

2024-03-12 14:10 UTC, TevinAdams commented
> After I submit the move as the customer, which page should I see next? Currently I am routed to the dashboard rather than the move page itself.

This is fixed. Missed the Agreement nav link.

2024-03-12 14:36 UTC, danieljordan-caci submitted a review, later dismissed

2024-03-12 14:36 UTC, danieljordan-caci commented on src/constants/routes.js
> +  PROFILE_PATH: '/service-member/profile/:moveId',
I would avoid using the `:moveId` here. I would say we should either just navigate the user `HOME_PATH` path when hitting save or use `state` to store the `moveId` when navigating around the profile screen. Similar to how the `needsToVerifyProfile` value is passed around.

2024-03-12 14:37 UTC, danieljordan-caci commented
> Seeing the Oops, something went wrong page when I:
> 
> * Go through customer flow
> * Whenever I can (either before or after submitting move) go to the Edit Profile page.
> * Click the Edit next to Contact Info
>   ![image](https://private-user-images.githubusercontent.com/147537467/312096785-741967e8-a86a-4cce-a5c8-f78b7bf4bb69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNTQ1MTcsIm5iZiI6MTcxMDI1NDIxNywicGF0aCI6Ii8xNDc1Mzc0NjcvMzEyMDk2Nzg1LTc0MTk2N2U4LWE4NmEtNGNjZS1hNWM4LWY3OGI3YmY0YmI2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQxNDM2NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMTg1MTAxODAzMTJhZTExOWMxN2Y0OGZlYWZiZmIzNmUwODgwMmUyMTU0NjE1NjM3NmEzMjM0Y2RhN2M3MmVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.u_uPUIg9stlKc3qGhU1ECuY3UWaXgcL3Jv6927lreCc)
> * Click the save button at the bottom of the page. I didn't change any values before saving
> * Click Return to move, which tries to route me to http://milmovelocal:3000/move/:moveId. This is where I see the something went wrong page. Seemed related to orders.
>   ![image](https://private-user-images.githubusercontent.com/147537467/312097469-59244fe5-c1ea-43f6-a38d-62e3ba4a1c7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNTQ1MTcsIm5iZiI6MTcxMDI1NDIxNywicGF0aCI6Ii8xNDc1Mzc0NjcvMzEyMDk3NDY5LTU5MjQ0ZmU1LWMxZWEtNDNmNi1hMzhkLTYyZTNiYTRhMWM3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQxNDM2NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNjIxZWI0NzliY2NiYWU2OGI1OGU4N2Q3N2Y4YWM0YTFjZTY1Yzc5ZjU1NGY2NjVkOWE0Mjc5ZDM0MmIyZDZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.n5a_QaTnGnGxuPNnOjXTWrGs7H1DqEVUF8betkIHMZc)
>   CCing @danieljordan-caci to see if this popped up in any of the previous PRs on orders

It's an issue with how he's using the params. I added a comment.

2024-03-12 16:24 UTC, cameroncaci submitted a review, later dismissed
On new customer -> set up profile -> reach multi move dashboard -> click profile icon -> click return to move -> error page

Additionally, after reaching this error page navigating back to profile appears to not work. Should be resolved by resolving the former

![image](https://github.com/transcom/mymove/assets/136814362/7513c63d-860e-41a7-a1ef-f66f749528e5)

![image](https://github.com/transcom/mymove/assets/136814362/4f627916-cd56-45a4-8176-ce594560a7ce)


![image](https://github.com/transcom/mymove/assets/136814362/29b9a2e4-1ada-4fe4-b0bf-d1a8aabf198b)

2024-03-12 19:43 UTC, TevinAdams commented
> Seeing the Oops, something went wrong page when I:
> 
> * Go through customer flow
> * Whenever I can (either before or after submitting move) go to the Edit Profile page.
> * Click the Edit next to Contact Info
>   ![image](https://private-user-images.githubusercontent.com/147537467/312096785-741967e8-a86a-4cce-a5c8-f78b7bf4bb69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNzI4NjYsIm5iZiI6MTcxMDI3MjU2NiwicGF0aCI6Ii8xNDc1Mzc0NjcvMzEyMDk2Nzg1LTc0MTk2N2U4LWE4NmEtNGNjZS1hNWM4LWY3OGI3YmY0YmI2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQxOTQyNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MmVlNzA2NDQzN2YxNDAxZDViN2JmYWIzNDQyNTQzODk1YzZhNDkwMzcyMGY3MWU3YTE4MjIwZDI5NjhiYmQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wDWh2Z1sO1c48N_lV_bBo0-dHYCGl2aIAj1WBP7dYbA)
> * Click the save button at the bottom of the page. I didn't change any values before saving
> * Click Return to move, which tries to route me to http://milmovelocal:3000/move/:moveId. This is where I see the something went wrong page. Seemed related to orders.
>   ![image](https://private-user-images.githubusercontent.com/147537467/312097469-59244fe5-c1ea-43f6-a38d-62e3ba4a1c7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNzI4NjYsIm5iZiI6MTcxMDI3MjU2NiwicGF0aCI6Ii8xNDc1Mzc0NjcvMzEyMDk3NDY5LTU5MjQ0ZmU1LWMxZWEtNDNmNi1hMzhkLTYyZTNiYTRhMWM3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQxOTQyNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTdiOTUyNmQxNDY1YjFlN2YwNTQ3MmFmNDgxNDUzNjRhNmE0NmQ2Y2E3YmJjOWZmMjY1MmYwNTEzOTdhMDkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tm3fcsksiybNiMBvvdk8MKaklnFFgRURc7pRcXpb5Z0)
>   CCing @danieljordan-caci to see if this popped up in any of the previous PRs on orders

This is fixed.

2024-03-12 20:03 UTC, TevinAdams commented
> After I submit the move as the customer, which page should I see next? Currently I am routed to the dashboard rather than the move page itself.

This has been changed to send you back to the move.

2024-03-12 20:04 UTC, TevinAdams commented on src/constants/routes.js
> +  PROFILE_PATH: '/service-member/profile/:moveId',
This change no longer exist. Found a better way to do this.

2024-03-13 14:40 UTC, traskowskycaci reviewed
Overall flowed nicely! I saw all the previous issues fixed, looking good.

I did see the Oops something went wrong page again when I:
- submitted the move
- Clicked Review your request
- Clicked the edit on the Edit next to the Profile on this page:
![image](https://github.com/transcom/mymove/assets/147537467/c9069ed5-ae33-4b96-9ddb-ae3b531c3dfe)

2024-03-13 14:40 UTC, traskowskycaci commented
> Overall flowed nicely! I saw all the previous issues fixed, looking good.
> 
> I did see the Oops something went wrong page again when I:
> 
> * submitted the move
> * Clicked Review your request
> * Clicked the edit on the Edit next the Profile on this page:
>   ![image](https://private-user-images.githubusercontent.com/147537467/312500167-c9069ed5-ae33-4b96-9ddb-ae3b531c3dfe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNDExMDIsIm5iZiI6MTcxMDM0MDgwMiwicGF0aCI6Ii8xNDc1Mzc0NjcvMzEyNTAwMTY3LWM5MDY5ZWQ1LWFlMzMtNGI5Ni05ZGRiLWFlM2I1MzFjM2RmZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QxNDQwMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjYwMWY5NDE1ODllZGEwNWU4MzdmMzhkNGIyZGI5OGVjYmIwNGQ2ZjkzZmRkZGQ4OTg3MDljZTAxMmI2YmEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pb5Ilq7Lr7W6rL8UoiVqxybSXafCCXdl4pAfaj16RiE)

The page I see that on is: http://milmovelocal:3000/service-member/profile

2024-03-13 14:48 UTC, danieljordan-caci commented
> > Overall flowed nicely! I saw all the previous issues fixed, looking good.
> > I did see the Oops something went wrong page again when I:
> > 
> > * submitted the move
> > * Clicked Review your request
> > * Clicked the edit on the Edit next to the Profile on this page:
> >   ![image](https://private-user-images.githubusercontent.com/147537467/312500167-c9069ed5-ae33-4b96-9ddb-ae3b531c3dfe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNDExMDIsIm5iZiI6MTcxMDM0MDgwMiwicGF0aCI6Ii8xNDc1Mzc0NjcvMzEyNTAwMTY3LWM5MDY5ZWQ1LWFlMzMtNGI5Ni05ZGRiLWFlM2I1MzFjM2RmZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QxNDQwMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjYwMWY5NDE1ODllZGEwNWU4MzdmMzhkNGIyZGI5OGVjYmIwNGQ2ZjkzZmRkZGQ4OTg3MDljZTAxMmI2YmEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pb5Ilq7Lr7W6rL8UoiVqxybSXafCCXdl4pAfaj16RiE)
> 
> The page I see that on is: http://milmovelocal:3000/service-member/profile

Do you see any errors in console?

2024-03-13 16:12 UTC, TevinAdams commented
> > > Overall flowed nicely! I saw all the previous issues fixed, looking good.
> > > I did see the Oops something went wrong page again when I:
> > > 
> > > * submitted the move
> > > * Clicked Review your request
> > > * Clicked the edit on the Edit next to the Profile on this page:
> > >   ![image](https://private-user-images.githubusercontent.com/147537467/312500167-c9069ed5-ae33-4b96-9ddb-ae3b531c3dfe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNDExMDIsIm5iZiI6MTcxMDM0MDgwMiwicGF0aCI6Ii8xNDc1Mzc0NjcvMzEyNTAwMTY3LWM5MDY5ZWQ1LWFlMzMtNGI5Ni05ZGRiLWFlM2I1MzFjM2RmZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QxNDQwMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjYwMWY5NDE1ODllZGEwNWU4MzdmMzhkNGIyZGI5OGVjYmIwNGQ2ZjkzZmRkZGQ4OTg3MDljZTAxMmI2YmEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pb5Ilq7Lr7W6rL8UoiVqxybSXafCCXdl4pAfaj16RiE)
> > 
> > 
> > The page I see that on is: http://milmovelocal:3000/service-member/profile
> 
> Do you see any errors in console?

This has been fixed. Needed to add moveId to state for when needing to navigate to the Profile page.

2024-03-13 16:15 UTC, TevinAdams commented
Actively fixing this for creating a move

2024-03-13 16:21 UTC, danieljordan-caci commented on config/env/stg.app.env
> +FEATURE_FLAG_MULTI_MOVE=true
We don't want this to be turned on in staging, right? @deandreJones

2024-03-13 16:25 UTC, danieljordan-caci commented on src/pages/MyMove/Home/MoveHome.jsx
> +  state = { ...state, moveId };
I don't think you need this here, do you? You can just use `state` as is and keep it `const`, right?
`const { state } = useLocation();`

And then use it like you do on line 321

2024-03-13 16:38 UTC, danieljordan-caci commented on src/pages/MyMove/Home/MoveHome.jsx
> +  state = { ...state, moveId };
Plus, `moveId` is already declared above in `useParams()`

2024-03-13 17:35 UTC, TevinAdams commented on src/pages/MyMove/Home/MoveHome.jsx
> +  state = { ...state, moveId };
Yeah beacuse I am setting moveId in state to allow navigation back to this page using that move id.

2024-03-13 17:38 UTC, danieljordan-caci requested changes

2024-03-13 17:38 UTC, danieljordan-caci commented on src/pages/MyMove/Profile/Profile.jsx
> +  const { moveId } = state;
Getting the Oops page when navigating to the user's profile from outside a move or link (just clicking the profile icon in the nav bar).

You'll need to add conditional logic to handle null values if `moveId` is not in `state`

2024-03-13 17:40 UTC, danieljordan-caci commented on src/pages/MyMove/Home/MoveHome.jsx
> +  state = { ...state, moveId };
Gotcha

2024-03-13 17:41 UTC, danieljordan-caci commented on src/pages/MyMove/Profile/Profile.jsx
> +  const { moveId } = state;
And you'll need to do that for every page you can access from outside of the `MoveHome` component

2024-03-13 23:15 UTC, TevinAdams commented on src/pages/MyMove/Profile/Profile.jsx
> +  const { moveId } = state;
Honestly I just did the work to store the moveId in state. So much easier and less of a headache. This most likely had to give access in a clean and proper way to the moveId.

2024-03-14 00:44 UTC, TevinAdams commented on src/pages/MyMove/Profile/Profile.jsx
> +  const { moveId } = state;
Code pushed up and this is fixed.

2024-03-14 13:09 UTC, TevinAdams commented on src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.jsx
> +// import { SET_MOVE_ID } from 'store/general/actions';
Done.

2024-03-14 15:27 UTC, danieljordan-caci commented
When clicking the `Edit` button to edit the Okta profile, it takes me to the profile edit page and not the okta edit page.

https://github.com/transcom/mymove/assets/136510600/ac6c2cb3-e7ff-4646-9f95-66122d71480e

2024-03-14 15:43 UTC, danieljordan-caci commented
> When clicking the `Edit` button to edit the Okta profile, it takes me to the profile edit page and not the okta edit page.
> 
>  Screen.Recording.2024-03-14.at.10.26.10.AM.mov

Once this is fixed, I'll stamp ya

2024-03-14 15:56 UTC, TevinAdams commented
> When clicking the `Edit` button to edit the Okta profile, it takes me to the profile edit page and not the okta edit page.
> 
>  Screen.Recording.2024-03-14.at.10.26.10.AM.mov

Changed this back to ` editURL={customerRoutes.EDIT_OKTA_PROFILE_PATH}`. Over looked it routing to the Contact Info Path. @danieljordan-caci  Fixed.

2024-03-14 16:00 UTC, deandreJones commented on config/env/stg.app.env
> +FEATURE_FLAG_MULTI_MOVE=true
off by default and utilize FF repo to control

2024-03-14 16:24 UTC, deandreJones commented on src/pages/MyMove/Profile/Profile.jsx
> +    isMultiMoveEnabled().then((enabled) => {
https://github.com/transcom/mymove/blob/214ae2d7387493d4b73c633312a37fd4d414ebc0/src/utils/featureFlags.js#L137

need to merge in integration, and make adjustments to how FF check it made

2024-03-14 19:33 UTC, TevinAdams commented on src/pages/MyMove/Profile/Profile.jsx
> +    isMultiMoveEnabled().then((enabled) => {
Replaced `isMultiMoveEnabled().then()` with `isBooleanFlagEnabled('multi_move').then()`

2024-03-14 19:51 UTC, TevinAdams commented on src/pages/MyMove/Profile/Profile.jsx
> +    isMultiMoveEnabled().then((enabled) => {
@deandreJones  Done

2024-03-14 20:12 UTC, traskowskycaci commented
> This has been fixed. Needed to add moveId to state for when needing to navigate to the Profile page.

Looks good! 

I did notice that from the 
"Review your request" button 
-> "Review your details" page 
-> clicking that edit next to the profile 
-> going to the Profile page, I can only "Return to Move" from the button at the top of the page 
-> end back at the move page

Alternatively, If I click the  "Review your request" button 
-> "Review your details" page 
-> clicking that edit next to the Orders 
-> scrolling to the bottom of the page, I click cancel 
-> end back at the "Review your details page"

Just a difference in routes I noticed. Honestly could go either way on it. Anyone have thoughts?

2024-03-14 20:15 UTC, danieljordan-caci commented
> > This has been fixed. Needed to add moveId to state for when needing to navigate to the Profile page.
> 
> Looks good!
> 
> I did notice that from the "Review your request" button -> "Review your details" page -> clicking that edit next to the profile -> going to the Profile page, I can only "Return to Move" from the button at the top of the page -> end back at the move page
> 
> Alternatively, If I click the "Review your request" button -> "Review your details" page -> clicking that edit next to the Orders -> scrolling to the bottom of the page, I click cancel -> end back at the "Review your details page"
> 
> Just a difference in routes I noticed. Honestly could go either way on it. Anyone have thoughts?

I say that's working as intended. Don't mind it.

2024-03-14 20:17 UTC, traskowskycaci commented
> I say that's working as intended. Don't mind it.

Won't argue with that. Looks good @TevinAdams!

2024-03-14 20:18 UTC, traskowskycaci approved these changes

2024-03-14 20:32 UTC, danieljordan-caci approved these changes

2024-03-14 20:33 UTC, merged