B 18913 int
transcom/mymove pull request #12222
Opened 2024-03-12 21:06 UTC by deandreJones

## [B-18913](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A908086)

## Summary

Given I am a Service Counselor
When i conduct a search for a move or customer
and i dont see the member i am looking for
then i willl see a button to create a new member in milmove

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the Office app
2. Login as a Counselor
3. Click Search tab
4. Complete a search
5. Observer add Customer Button at bottom of page

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

## Screenshots

<img width="1304" alt="image" src="https://github.com/transcom/mymove/assets/136509766/ee1ded6e-10e7-42ad-867b-add5574e4c04">

2024-03-13 14:30 UTC, traskowskycaci approved these changes
Looks good!

2024-03-13 20:53 UTC, danieljordan-caci requested changes

2024-03-13 20:53 UTC, danieljordan-caci commented on src/pages/Office/CustomerOnboarding/CustomerName.jsx
> +export default CustomerName;
Tests plz

2024-03-13 20:53 UTC, danieljordan-caci commented on src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
> +        )}
Can you add a unit test for this lil' guy?

2024-03-14 14:55 UTC, deandreJones commented on src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
> +        )}
added

2024-03-14 14:56 UTC, deandreJones commented on src/pages/Office/CustomerOnboarding/CustomerName.jsx
> +export default CustomerName;
added

2024-03-14 14:58 UTC, danieljordan-caci commented on src/constants/routes.js
> +  CUSTOMER_NAME_PATH: '/Onboarding/customerName',
Can you change this to `onboarding` instead of `Onboarding`?

2024-03-14 15:13 UTC, deandreJones commented on src/constants/routes.js
> +  CUSTOMER_NAME_PATH: '/Onboarding/customerName',
just for you

2024-03-14 16:00 UTC, danieljordan-caci approved these changes
LGTM! Thanks for the tests.

2024-03-14 16:18 UTC, merged