INT B 18889 remove prime ability to update destination address for approved shipment outside correct endpoint
transcom/mymove pull request #12240
Opened 2024-03-14 20:38 UTC by danieljordan-caci

## [Agility ticket](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-18889)

## Summary

When a shipment is in an `APPROVED` status, we do not want the Prime to have the freedom to update the destination address of a shipment without the TOO approving the change first. 

Right now there are two endpoints where the destination address can be updated without the respective logic checks that are in the `updateShipmentDestinationAddress` endpoint. This PR does the following:
- when calling the `updateMTOShipment` and `updateMTOShipmentAddress` endpoints, implemented logic to check the shipment status and if the shipment's destination address is provided in the `payload`
- handled error return to inform the user to use the `updateMTOShipmentDestinationAddress` endpoint instead when trying to update the destination address
- updated tests to reflect changes in logic

### How to test

1. Access MM as prime
2. Find a move with an approved shipment
3. Try to edit the destination address for the shipment by clicking the `Edit` and submitting the form
4. You should get back an error

## Screenshots
![Screenshot 2024-03-14 at 2 42 46 PM](https://github.com/transcom/mymove/assets/136510600/e9ecd425-d542-40fb-b2a0-d7cdcbce87e7)

2024-03-18 20:16 UTC, traskowskycaci approved these changes

2024-03-20 12:35 UTC, cameroncaci requested changes
Updating these here will help us when debugging or help the Prime when using our API

2024-03-20 12:35 UTC, cameroncaci commented on pkg/handlers/primeapi/mto_shipment.go
> +			}
Could we update this error response? As it checks for more than if the shipment is just approved

2024-03-20 12:35 UTC, cameroncaci commented on pkg/handlers/primeapi/mto_shipment_address.go
> +					"This shipment is approved, please use the updateShipmentDestinationAddress endpoint to update the destination address of an approved shipment", h.GetTraceIDFromRequest(params.HTTPRequest), nil)
Same right here

2024-03-20 12:36 UTC, cameroncaci commented
![image](https://github.com/transcom/mymove/assets/136814362/a5a15c6b-d1cd-4f3a-9b98-ffd92eb36d76)

`Update Shipment Destination Address` should be functional on an approved shipment right?

2024-03-20 13:01 UTC, danieljordan-caci commented
> ![image](https://private-user-images.githubusercontent.com/136814362/314500534-a5a15c6b-d1cd-4f3a-9b98-ffd92eb36d76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5Mzk5ODksIm5iZiI6MTcxMDkzOTY4OSwicGF0aCI6Ii8xMzY4MTQzNjIvMzE0NTAwNTM0LWE1YTE1YzZiLWQxY2QtNGYzYS05Yjk4LWZmZDkyZWIzNmQ3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMFQxMzAxMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNTc2NWQxY2FhY2Y2N2YxYzM0MTdkMDQyMWFkNTJjNTlkMTE1Njc5YmY1NzJjMWFmNjBmZTY2MGYxN2EwNmJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hlbiv-oWysq7os7nbBp7vkEPJN1G9zk4PX_-ubat7og)
> 
> Should `Udate Shipment Destination Address`be functional on an approved shipment?

Yessir

2024-03-20 13:03 UTC, danieljordan-caci commented on pkg/handlers/primeapi/mto_shipment.go
> +			}
I would say this error response is appropriate. 
It's checking if the shipment status is approved, which `This shipment is approved` covers
And also checking is the dest address is in the payload, which `please use the updateShipmentDestinationAddress endpoint to update the destination address` covers

I'm open to other suggestions though.

2024-03-20 13:41 UTC, cameroncaci commented on pkg/handlers/primeapi/mto_shipment.go
> +			}
Thought about it and yeah that works. No other code changes necessary, lgtm!

2024-03-20 14:22 UTC, merged