B:18828 - Create Okta Account AdminAPI Endpoint
transcom/mymove pull request #12278
Opened 2024-03-19 20:51 UTC by TevinAdams

## [Agility ticket](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-18828)

## Summary

This PR introduces a new endpoint(/create-okta-account) in the adminAPI  that allows the admin user to create an Okta account with information provided through the endpoint.

[Okta API Specifications](https://developer.okta.com/docs/reference/api/roles/) explains more about the okta api specifications

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Login as an admin user
2. open up postman or admin api swagger page
3. In swagger try out the create-okta-account endpoint under OKTA section
4. Here is a test Body to use: 

{
  "firstName": "Micheal",
  "lastName": "Jordan",
  "login": "user1010@userdomain.com",
  "email": "user1010@userdomain.com",
  "mobilePhone": "855-949-0339",
  "cacEdipi": "1244567890",
  "gsaId": "123456780",
  "groupId": []
}

5. Once you send the request expect a response like below: 
![image](https://github.com/transcom/mymove/assets/136514590/f6f6e48b-5cb2-477c-83c1-d57920fd4d7f)### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots
![image](https://github.com/transcom/mymove/assets/136514590/ed5a1a71-933c-48de-8cbb-d0a819ae72ec)![image](https://github.com/transcom/mymove/assets/136514590/9b583c82-612e-4287-86f4-b6d2f5b30c9b)

2024-03-20 15:49 UTC, traskowskycaci approved these changes
Tested and works as expected. Nice!

2024-03-20 17:53 UTC, danieljordan-caci requested changes

2024-03-20 17:53 UTC, danieljordan-caci commented on pkg/handlers/adminapi/create_okta_account.go
> +// CreateOktaAccount Handler creats okta accounts
Typo here in `creats`

2024-03-20 17:53 UTC, danieljordan-caci commented on pkg/handlers/adminapi/create_okta_account.go
> +				return userop.NewCreateOktaAccountOK().WithPayload(params.CreateOktaAccountPayload), err
Can you instead return the response from Okta? We will need their okta ID that is returned on a successful call.

2024-03-20 17:53 UTC, danieljordan-caci commented on pkg/handlers/authentication/okta/provider.go
> +}
Can you also throw in `?activate=true` into this function? We want to make sure that the users are activated upon creation and not staged. Could potentially make this a variable like I did in 18916

2024-03-20 17:53 UTC, danieljordan-caci commented on swagger-def/admin.yaml
> +        x-nullable: false
You can leave out these `x-nullable`s if they are false

2024-03-20 17:53 UTC, danieljordan-caci commented on swagger-def/admin.yaml
> +
white space here

2024-03-20 21:43 UTC, TevinAdams commented on pkg/handlers/adminapi/create_okta_account.go
> +				return userop.NewCreateOktaAccountOK().WithPayload(params.CreateOktaAccountPayload), err
Done

2024-03-20 21:44 UTC, TevinAdams commented on pkg/handlers/adminapi/create_okta_account.go
> +// CreateOktaAccount Handler creats okta accounts
@danieljordan-caci  Done

2024-03-20 21:44 UTC, TevinAdams commented on pkg/handlers/authentication/okta/provider.go
> +}
@danieljordan-caci  Done

2024-03-20 21:44 UTC, TevinAdams commented on swagger-def/admin.yaml
> +        x-nullable: false
@danieljordan-caci  Done

2024-03-20 21:44 UTC, TevinAdams commented on swagger-def/admin.yaml
> +
@danieljordan-caci  Done

2024-03-20 21:46 UTC, danieljordan-caci commented
Conflicts

2024-03-21 19:42 UTC, danieljordan-caci commented
Getting this when testing:
```
{
  "title": "Validation Error",
  "instance": "1ffab2e4-36e4-4dff-9513-a00d383d474d",
  "detail": "gsaId in body is required"
}
```

gsaId will not always be needed - can you make this nullable to where it doesn't have to be in the JSON body?

2024-03-21 19:43 UTC, danieljordan-caci commented
> Getting this when testing:
> 
> ```
> {
>   "title": "Validation Error",
>   "instance": "1ffab2e4-36e4-4dff-9513-a00d383d474d",
>   "detail": "gsaId in body is required"
> }
> ```
> 
> gsaId will not always be needed - can you make this nullable to where it doesn't have to be in the JSON body?

Probably the same for `cacEdipi` as well

2024-03-21 20:53 UTC, TevinAdams commented
> > Getting this when testing:
> > ```
> > {
> >   "title": "Validation Error",
> >   "instance": "1ffab2e4-36e4-4dff-9513-a00d383d474d",
> >   "detail": "gsaId in body is required"
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > gsaId will not always be needed - can you make this nullable to where it doesn't have to be in the JSON body?
> 
> Probably the same for `cacEdipi` as well

Yeah thats because those are required fields. I will remove them from being required.

2024-03-21 21:37 UTC, danieljordan-caci requested changes

2024-03-21 21:37 UTC, danieljordan-caci commented on pkg/handlers/adminapi/create_okta_account.go
> +			apiKey := v.GetString(cli.OktaAPIKeyFlag)
Couple of changes that I think need to happen. The use case of this endpoint is for when admin users hit that "approve" button. We need to call this endpoint in the update function that is called when the user does that.

You also should take out the `groupId` parameter because it isn't needed. This endpoint is in the Admin API so we know the use case will be to add office users. We can pass that group ID in from environment variables that Dre added [in this PR.](https://github.com/transcom/mymove/pull/12178)

So I think we should call this function when the params in the `UpdateRequestedOfficeUserHandler` contain `status: APPROVED`.

I'd make sure that you do an early return if either this or the update function fails

2024-03-21 21:38 UTC, danieljordan-caci commented on pkg/handlers/adminapi/create_okta_account.go
> +			apiKey := v.GetString(cli.OktaAPIKeyFlag)
I guess what I'm trying to avoid is having to call these separately. But instead call this endpoint when the admin approves the requested office user, which updates their status.

It's important to handle failures/errors of each case to avoid having an office account but no Okta account (if the Okta call failed but update passed), and vice versa.

2024-03-21 22:10 UTC, TevinAdams commented on pkg/handlers/adminapi/create_okta_account.go
> +			apiKey := v.GetString(cli.OktaAPIKeyFlag)
@danieljordan-caci  Let me get clarification on what exactly we are wanting for this story so I can the story accordingly.

1. We still want the endpoint, but want it called through the UpdateRequestedOfficeUserHandler
2. We want to call this functionality within the UpdateRequestedOfficeUserHandler, IF the params has a status == APPROVED
3. No longer care about the groupId as a parameter in this endpoint, instead grab it from the environment variables

Let me know if all of the above is what we are wanting out if this story and i will update the story accordingly.

2024-03-21 22:44 UTC, danieljordan-caci commented on pkg/handlers/adminapi/create_okta_account.go
> +			apiKey := v.GetString(cli.OktaAPIKeyFlag)
Looks good. Just make sure that we cover use cases of either the update failing or Okta returning an error, we need to make sure that we return an error and not let either of those processes go through.

2024-03-25 22:05 UTC, TevinAdams commented on pkg/handlers/adminapi/create_okta_account.go
> +			apiKey := v.GetString(cli.OktaAPIKeyFlag)
@danieljordan-caci The following changes have been made:
1. There is no longer a createOktaAccount endpoint
2. CreateOktaAccount logic has been moved to the UpdateRequestedOfficeUserHandler
3. CreateOktaAccount Logic only executes if params Status == "APPROVED"
4. GroupID is grabbed from environment variables
5. Update executes in all cases except when CreateOktaAccount logic is executed and fails.

2024-03-26 13:57 UTC, danieljordan-caci requested changes

2024-03-26 13:57 UTC, danieljordan-caci commented on pkg/handlers/adminapi/requested_office_users.go
> +				}
Couldn't you just run an `if` check just for the Okta call and proceed with everything else? Seems like the `runUpdateRequestedOfficeUser` check isn't necessary since it's always true and you're returning a 500 if the okta response isn't 200, so the `oktaAccountCreated` variable is a little redundant.

For example:
```
if (params.Body.Status == "APPROVED") {
   oktaAccountCreationResponse, err := CreateAccountOkta(appCtx, params)
   ...if oktaAccountCreationResponse.StatusCode != http.StatusOK -> end the call there and return an error
} 
// the rest of this will run if the above was successful OR the status == "REJECTED"
requestedOfficeUser, verrs, err := h.RequestedOfficeUserUpdater.UpdateRequestedOfficeUser(appCtx, requestedOfficeUserID, params.Body)
				if err != nil {
					return handlers.ResponseForError(appCtx.Logger(), err), err
				}
				if verrs != nil {
					appCtx.Logger().Error(err.Error())
					return requested_office_users.NewUpdateRequestedOfficeUserUnprocessableEntity(), verrs
				}

				if requestedOfficeUser.UserID != nil && body.Roles != nil {
					_, err = h.UserRoleAssociator.UpdateUserRoles(appCtx, *requestedOfficeUser.UserID, updatedRoles)
					if err != nil {
						appCtx.Logger().Error("Error updating user roles", zap.Error(err))
						return requested_office_users.NewUpdateRequestedOfficeUserInternalServerError(), err
					}
				}
....everything else
```
Thoughts?

2024-03-27 13:34 UTC, TevinAdams commented on pkg/handlers/adminapi/requested_office_users.go
> +				}
@danieljordan-caci  Yes I can. I was just trying to make it easy to follow by breaking it down but I am all for doing this. Its possible me trying to make it easier to follow might have made it more confusing.

2024-03-27 15:08 UTC, TevinAdams commented on pkg/handlers/adminapi/requested_office_users.go
> +				}
@danieljordan-caci  Done

2024-03-27 15:52 UTC, danieljordan-caci commented on pkg/handlers/adminapi/requested_office_users.go
> +func CreateAccountOkta(appCtx appcontext.AppContext, params requested_office_users.UpdateRequestedOfficeUserParams) (*http.Response, error) {
Could you rename this to specify that it is creating an office okta account?

2024-03-27 17:12 UTC, TevinAdams commented on pkg/handlers/adminapi/requested_office_users.go
> +func CreateAccountOkta(appCtx appcontext.AppContext, params requested_office_users.UpdateRequestedOfficeUserParams) (*http.Response, error) {
@danieljordan-caci CreateOfficeOktaAccount is now the new name

2024-03-27 18:35 UTC, danieljordan-caci approved these changes
LGTM! Nice work.

2024-03-27 19:09 UTC, merged