MAIN B-18825 Admin API Approve/Reject/Update requested office user (MERGE AFTER MAIN B-18916)
transcom/mymove pull request #12288
Opened 2024-03-20 17:09 UTC by danieljordan-caci

## [Agility ticket](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-18825)
[INTEGRATION BRANCH PR](https://github.com/transcom/mymove/pull/12230)

This PR requires the code from [MAIN B-18824](url[)](https://github.com/transcom/mymove/pull/12122) in order to avoid conflicts, so ensure that that PR merges prior to this one.

There will be a slight discrepancy in the code due to accommodating swagger/spectral errors in the B-18824 and will be keeping those changes and not using the changes done in this branch's integration PR. Other than that, the commits should be the same.

## Summary

With the incoming missile of office users requesting accounts, we need the functionality to have an endpoint that will allow a MilMove admin to update them, which will be used in the UI for:
- approving the user
- rejecting the user
- updating the user prior to approving/rejecting

This PR does the following:
- adds `PATCH` endpoint for `/requested-office-users/{officeUserId}`
- implements logic that takes in values that can be updated
- I did pull in @cameroncaci's commit containing his implementation of fetching roles in [this PR](https://github.com/transcom/mymove/pull/12199)
- added & updated tests
- updated swagger with relevant data

When calling the API, you can provide data similar to this and it should update. 
```
{
  "firstName": "Daniel",
  "middleInitials": "Bodacious",
  "lastName": "Jordan",
  "telephone": "222-456-7890",
  "roles": [
    {
      "name": "Transportation Invoicing Officer",
      "roleType": "transportation_invoicing_officer"
    },
    {
      "name": "Transportation Ordering Officer",
      "roleType": "transportation_ordering_officer"
    },
    {
      "name": "Contracting Officer",
      "roleType": "contracting_officer"
    },
    {
      "name": "Services Counselor",
      "roleType": "services_counselor"
    },
    {
      "name": "Prime Simulator",
      "roleType": "prime_simulator"
    }
  ],
  "transportationOfficeId": "bb80626f-a953-4832-8c9b-33ca116f9ec7",
  "edipi": "8675309000",
  "otherUniqueId": "thisIsAUniqu3Id",
  "status": "APPROVED"
}
```

### How to test

1. Fire up your `client` & `server` and log in as a MM Admin
2. Using postman or swagger UI
3. Send a `PATCH` request to `/requested-office-users/{officeUserId}`
4. Provide relevant data that can be updated and confirm it updates and persists in the db

## Screenshots
<img width="809" alt="Screenshot 2024-03-13 at 3 02 26 PM" src="https://github.com/transcom/mymove/assets/136510600/08607fc5-7a56-4760-abe5-7855568c723e">

2024-03-20 17:27 UTC, danieljordan-caci commented
> 1653 changes files on int vs 2454 here. Was other work merged into this branch that wasn't in the int branch?

Yeah these files include the changes from the dependent PR, that's why the numbers are inflated.

2024-04-05 16:31 UTC, traskowskycaci commented on swagger/admin.yaml
> +  - name: Requested office users
Can't find `Requested office users` in the integration PR and also checked integration and don't see it there

2024-04-05 16:32 UTC, danieljordan-caci commented on swagger/admin.yaml
> +  - name: Requested office users
Should be in the commit labeled `fixing spectral warnings`

2024-04-05 16:35 UTC, traskowskycaci commented on swagger/admin.yaml
> +  - name: Requested office users
You're right, I do see in that commit for the int PR. But then if I compare the files changed, I don't see it there anymore. Also don't see it here: https://github.com/transcom/mymove/blob/integrationTesting/swagger/admin.yaml

2024-04-05 16:37 UTC, danieljordan-caci commented on swagger/admin.yaml
> +  - name: Requested office users
What the

2024-04-05 16:37 UTC, traskowskycaci commented on swagger/admin.yaml
> +  - name: Requested office users
Did it maybe get overwritten by a subsequent PR in int that isn't in main yet?

2024-04-05 16:42 UTC, danieljordan-caci commented on swagger/admin.yaml
> +  - name: Requested office users
Possible. Not sure what to do in this situation @deandreJones

2024-04-08 13:15 UTC, cameroncaci commented on swagger/admin.yaml
> +  - name: Requested office users
That would be because it was directly committed on the `swagger` version rather than `swagger-def`, meaning it got overwrote by the next server run. See this commit where the code was introduced: https://github.com/transcom/mymove/pull/12230/commits/e793199f76119f7242a50a09c10924efd992da6b

2024-04-08 13:33 UTC, cameroncaci requested changes

2024-04-08 13:33 UTC, cameroncaci commented on swagger/admin.yaml
> +  - name: Requested office users
@danieljordan-caci https://github.com/transcom/mymove/commit/8e20a63d3df787213319af4f2a705d9364e3de1f

2024-04-08 13:34 UTC, cameroncaci commented on swagger/admin.yaml
> +  - name: Requested office users
This main PR is technically good to go, the commit that removed the tag was present on integrationTesting before it got merged in

2024-04-08 13:35 UTC, cameroncaci approved these changes

2024-04-08 13:35 UTC, danieljordan-caci commented on swagger/admin.yaml
> +  - name: Requested office users
Okay, this is my fault. @cameroncaci has found me guilty of self sabotage.

2024-04-08 14:05 UTC, traskowskycaci approved these changes

2024-04-08 14:29 UTC, merged