B 18795 int
transcom/mymove pull request #12313
Opened 2024-03-25 13:02 UTC by deandreJones

## [B-18795](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A906809)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

2024-03-25 13:05 UTC, cameroncaci requested changes

2024-03-25 13:05 UTC, cameroncaci commented on migrations/app/schema/20240322144246_updateAddressesCounty.up.sql
> +		adr.postal_code = usprc.uspr_zip_id);
I get the feeling we're gonna want to increase the timeout or else CircleCI will exit it early. Here's a quick example of one I've done in the past:
```
-- Set temp timeout due to large record modification
-- Time is 5 minutes in milliseconds
SET statement_timeout = 300000;
SET lock_timeout = 300000;
SET idle_in_transaction_session_timeout = 300000;
```

2024-03-25 13:08 UTC, deandreJones commented on migrations/app/schema/20240322144246_updateAddressesCounty.up.sql
> +		adr.postal_code = usprc.uspr_zip_id);
there is already a 60m timeout in the circle config- while running migrations
think we need more?

2024-03-25 13:09 UTC, traskowskycaci approved these changes
Migration ran successfully for me locally, county column has values. Nice!

2024-03-25 14:09 UTC, cameroncaci commented on migrations/app/schema/20240322144246_updateAddressesCounty.up.sql
> +		adr.postal_code = usprc.uspr_zip_id);
Oh, I didn't know that we changed it to have a blanket 60m timeout. Remember back to when we were conducting some TGET migrations? Those were failing. If that 60m timeout is newer than those migrations (4 months ago) then this should be fine as is

2024-03-25 14:23 UTC, deandreJones commented on migrations/app/schema/20240322144246_updateAddressesCounty.up.sql
> +		adr.postal_code = usprc.uspr_zip_id);
been there for 5 years... so not that new

Ill add the above to add additional safety net

2024-03-25 14:45 UTC, cameroncaci commented on migrations/app/schema/20240322144246_updateAddressesCounty.up.sql
> +		adr.postal_code = usprc.uspr_zip_id);
Hm, it's likely not operating properly then. We've seen on a few occasions the migrations were timing out

2024-03-25 14:45 UTC, cameroncaci approved these changes

2024-03-25 15:03 UTC, cameroncaci commented
Hm, getting some null values such as for 90210.
![image](https://github.com/transcom/mymove/assets/136814362/2f9eb795-d7ca-4eea-b4ed-ac5ca22872c5)

![image](https://github.com/transcom/mymove/assets/136814362/2d7d120f-9922-4c43-b9b7-76de342031d1)

2024-03-26 13:30 UTC, deandreJones commented
> Hm, getting some null values such as for 90210. ![image](https://private-user-images.githubusercontent.com/136814362/316548520-2f9eb795-d7ca-4eea-b4ed-ac5ca22872c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NjAwODAsIm5iZiI6MTcxMTQ1OTc4MCwicGF0aCI6Ii8xMzY4MTQzNjIvMzE2NTQ4NTIwLTJmOWViNzk1LWQ3Y2EtNGVlYS1iNGVkLWFjNWNhMjI4NzJjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQxMzI5NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZTVmYmM4ZjkzOTAxZjBkZDNjMzEwMDY1NjkxNjYxZTFhODQxZmQ1MmY0NzkyOWFkMjQ3NjUzOGIxYWQyNDMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5eNsT_RHWASAkEcr7F4lt4250GeJVS_RMZ5kJAmJP_8)
> 
> ![image](https://private-user-images.githubusercontent.com/136814362/316548190-2d7d120f-9922-4c43-b9b7-76de342031d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NjAwODAsIm5iZiI6MTcxMTQ1OTc4MCwicGF0aCI6Ii8xMzY4MTQzNjIvMzE2NTQ4MTkwLTJkN2QxMjBmLTk5MjItNGM0My1iOWI3LTc2ZGUzNDIwMzFkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQxMzI5NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MzA0ZmQ2MzJlMWE2ZWI4ZjFlMzNlNDkzMmUxOGJkODI5ZTJjNTk1ZGQ5MWVjODU5NDk5NjNmNjk0YmEyYzQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MN66R7-b2ztcIf2xM42PCuiaG7rxFi8kHNt0KB2Stwg)

refactored query, which got rid of the nulls.. that should have matched for me

2024-03-26 14:09 UTC, cameroncaci commented
> > Hm, getting some null values such as for 90210. ![image](https://private-user-images.githubusercontent.com/136814362/316548520-2f9eb795-d7ca-4eea-b4ed-ac5ca22872c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NjAwODAsIm5iZiI6MTcxMTQ1OTc4MCwicGF0aCI6Ii8xMzY4MTQzNjIvMzE2NTQ4NTIwLTJmOWViNzk1LWQ3Y2EtNGVlYS1iNGVkLWFjNWNhMjI4NzJjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQxMzI5NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZTVmYmM4ZjkzOTAxZjBkZDNjMzEwMDY1NjkxNjYxZTFhODQxZmQ1MmY0NzkyOWFkMjQ3NjUzOGIxYWQyNDMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5eNsT_RHWASAkEcr7F4lt4250GeJVS_RMZ5kJAmJP_8)
> > ![image](https://private-user-images.githubusercontent.com/136814362/316548190-2d7d120f-9922-4c43-b9b7-76de342031d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NjAwODAsIm5iZiI6MTcxMTQ1OTc4MCwicGF0aCI6Ii8xMzY4MTQzNjIvMzE2NTQ4MTkwLTJkN2QxMjBmLTk5MjItNGM0My1iOWI3LTc2ZGUzNDIwMzFkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQxMzI5NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MzA0ZmQ2MzJlMWE2ZWI4ZjFlMzNlNDkzMmUxOGJkODI5ZTJjNTk1ZGQ5MWVjODU5NDk5NjNmNjk0YmEyYzQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MN66R7-b2ztcIf2xM42PCuiaG7rxFi8kHNt0KB2Stwg)
> 
> refactored query, which got rid of the nulls.. that should have matched for me


Hm, still getting some nulls
![image](https://github.com/transcom/mymove/assets/136814362/8e3387dc-3179-417c-b125-2dc0083fb03c)

![image](https://github.com/transcom/mymove/assets/136814362/f9e3c515-c187-42c4-b8b2-b32d3e91a62b)

2024-03-26 14:24 UTC, cameroncaci commented
@deandreJones 
I bet it's because of the manual SQL inserts under db dev populate not using the factories, inserting _after_ the migrations

2024-03-26 14:26 UTC, deandreJones commented
> @deandreJones I bet it's because of the manual SQL inserts under db dev populate not using the factories, inserting _after_ the migrations. Hence probably why the makefile has a "TODO: deprecate" under that db dev populate

that makes sense, cuz when i run the script after the db is populated all is good

2024-03-26 14:29 UTC, cameroncaci commented
I wonder where these inserts are coming from.. I see c/o Some Person showing up here: `scripts/pricing-acceptance`

2024-03-26 14:29 UTC, cameroncaci approved these changes
Works like a charm, the county null issue is separate

2024-03-26 14:35 UTC, merged