B-19036-INT
transcom/mymove pull request #12342
Opened 2024-03-26 19:51 UTC by paulstonebraker

## [Agility ticket](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-19036)

## Summary

This gives Services Counselors the ability to create moves. To bridge the gap betwen SCs creating a profile, and then creating a move for that profile, we will need to refactor:
- SC search component to display users as well as moves
- Refactor the CreateMoveCustomerInfo and ServicesCounselingAddOrders components to not use the BASE_COUNSELING_MOVE_PATH
- MoveDetails to include the ability to upload orders files

Because of this, I left some component testing lean.

### How to test

1. Login as a services counselor and click Search
2. Search for an existing customer
3. Click "Create New Move" and get directed to the Customer info screen
4. Update customer info and take note of updates and save.
5. Find yourself at the new Add Orders page. Fill out orders information, take note of it and click next
6. Find yourself at the move details view of the new move. Scroll down and confirm the orders information and customer information you entered is correct

2024-03-26 21:26 UTC, danieljordan-caci requested changes
Some other things I noticed.

In `SearchResultsTable.jsx`, it'd be nice to change the `<button>` implementation to :
```
import { Button } from '@trussworks/react-uswds';

...
    : createHeader(
        'Create Move',
        (row) => {
          return (
            <Button
              onClick={() =>
                useNavigate(generatePath(servicesCounselingRoutes.BASE_MOVE_VIEW_PATH, { moveCode: row.locator }))
              }
              className={styles.createNewMove}
              data-testid="searchCreateMoveButton"
            >
              Create New Move
            </Button>
          );
        },
        { isFilterable: false },
      ),
```
This is much more user friendly & has the hover effect. I don't have any problems with it rendering. You could also remove the majority of the styling since its already used in that `Button` component (unless you're married to the transparent background then you can just throw in `secondary` to the props).

Also in `ServicesCounselingMoveDetails.jsx`, there's this line:
```
 <Grid col={6} className={scMoveDetailsStyles.testdiv}>
```
Could we potentially rename that class name from something other than `testdiv`? It isn't even being used in the `.scss` file. You also do not need the `col={6}` passed in.

In addition to that, the button placement is pretty weird and doesn't line up with the rest of the page. Adding a little flex can fix that. 

- adding some margin to the existing class container:
```
  .submitMoveDetailsContainer {
    display: flex;
    justify-content: flex-end;
    margin-right: 2em;
```
- adding flex to our future renamed `testdiv` class:
```
.testdiv {
  display: flex;
  justify-content: flex-end;
}
```
![Screenshot 2024-03-26 at 4 09 36 PM](https://github.com/transcom/mymove/assets/136510600/d9fed4de-8800-49ba-950c-d6b2c2205049)

Sorry for blowing you up. This PR is pretty huge, handling both the UI and backend changes! Good work, just some changes that I think will be better for user experience and developer readability/continuity.

2024-03-26 21:26 UTC, danieljordan-caci commented on swagger-def/ghc.yaml
> +      operationId: createOrder
Same thing here, change `createOrder` to `createOrders` to keep up with how other endpoints are wording it

2024-03-26 21:26 UTC, danieljordan-caci commented on swagger-def/ghc.yaml
> +          description: user is not authorized
Could you add in a 422 to handle unprocessable entities? This will allow you to send back custom errors from your backend.
```
        '422':
          $ref: '#/responses/UnprocessableEntity'
```

2024-03-26 21:26 UTC, danieljordan-caci commented on src/pages/Office/CreateMoveCustomerInfo/CreateMoveCustomerInfo.jsx
> +  };
Can you handle potential `null` values here? Should keep some errors from happening in case these are ever empty.
`customer.first_name` || ''`

2024-03-26 21:26 UTC, danieljordan-caci commented on src/components/Office/AddOrdersForm/AddOrdersForm.test.jsx
> +    });
Request to add one test to this to ensure the validations are passing. Something like:
```
  it('shows an error message if trying to submit an invalid form', async () => {
    const { getByRole, findAllByRole, getByLabelText } = render(<BackupAddressForm {...testProps} />);
    await userEvent.click(getByLabelText('Address 1'));
    await userEvent.click(getByLabelText(/Address 2/));
    await userEvent.click(getByLabelText('City'));
    await userEvent.click(getByLabelText('ZIP'));
    await userEvent.click(getByLabelText('State'));

    const submitBtn = getByRole('button', { name: 'Next' });
    await userEvent.click(submitBtn);

    const alerts = await findAllByRole('alert');
    expect(alerts.length).toBe(4);

    alerts.forEach((alert) => {
      expect(alert).toHaveTextContent('Required');
    });

    expect(testProps.onSubmit).not.toHaveBeenCalled();
  });
```
(stolen from `BackupAddressForm.test.jsx`

2024-03-26 21:26 UTC, danieljordan-caci commented on pkg/handlers/ghcapi/orders.go
> +			}
Instead of using `handlers.ResponseForError`, you could use `UnprocessableEntity` in swagger. You can still do these checks, but send back specific errors.
`No origin duty location found` or `No service member found with that id`, etc.

Some stolen snippet:
```
err = apperror.NewBadDataError("At least one office user role is required")
appCtx.Logger().Error(err.Error())
return officeuserop.NewCreateRequestedOfficeUserUnprocessableEntity(), err
```

2024-03-26 21:26 UTC, danieljordan-caci commented on pkg/handlers/ghcapi/orders.go
> +			}
This is entirely optional, btw. Not requiring this for my approval - I just think its best to be specific when returning errors to the prime & office apps.

2024-03-26 21:26 UTC, danieljordan-caci commented on src/pages/Office/ServicesCounselingAddOrders/ServicesCounselingAddOrders.test.jsx
> +  });
Please add a test here to handle when `Back` is clicked & when `Next` is clicked

2024-03-26 21:26 UTC, danieljordan-caci commented on src/pages/Office/ServicesCounselingAddOrders/ServicesCounselingAddOrders.jsx
> +  };
Can you change this to `navigate(-1)` instead? That way they can go back to the customer edit screen and reverse the flow instead of `/`

2024-03-26 22:03 UTC, paulstonebraker commented on pkg/handlers/ghcapi/orders.go
> +// CounselingUpdateOrderHandler create an order via POST /counseling/orders/{orderId}
Darn, almost got away with it

2024-03-26 22:03 UTC, paulstonebraker commented on pkg/handlers/ghcapi/orders.go
> +			}
I like this, will do

2024-03-26 22:18 UTC, paulstonebraker commented on swagger-def/ghc.yaml
> +      operationId: createOrder
Yeah I had trouble with this one, not sure which is more semantic. I think createOrders makes more sense and I've never heard to orders referred to as and order. But for some reason, in ghc.yaml the definition is `order`

2024-03-26 22:25 UTC, paulstonebraker commented on src/pages/Office/CreateMoveCustomerInfo/CreateMoveCustomerInfo.jsx
> +  };
I think values would only come back as undefined if they're empty, and wouldn't cause errors. But happy to make this change as well

2024-03-27 12:53 UTC, paulstonebraker commented on src/pages/Office/ServicesCounselingAddOrders/ServicesCounselingAddOrders.jsx
> +};
Nice, doing my css for me, ty

2024-03-27 13:35 UTC, danieljordan-caci commented on src/pages/Office/CreateMoveCustomerInfo/CreateMoveCustomerInfo.jsx
> +  };
I think it's better to cover these bases here, especially when pre-populating forms with values. This will significantly decrease the risk of seeing that pesky "Something Went Wrong" page.

2024-03-27 13:36 UTC, danieljordan-caci commented on swagger-def/ghc.yaml
> +      operationId: createOrder
I'll resolve this since its entirely subjective and has nothing to do with the implementation. Just rattlin' your brain a bit.

2024-03-27 13:37 UTC, danieljordan-caci commented on src/pages/Office/ServicesCounselingAddOrders/ServicesCounselingAddOrders.jsx
> +};
Well ideally you would have a stylesheet set up instead of doing inline styling haha

2024-03-27 18:47 UTC, loganwc approved these changes

2024-03-27 18:50 UTC, danieljordan-caci commented on pkg/handlers/ghcapi/orders.go
> +				err = apperror.NewBadDataError("Service member cannot be verified")
Might wanna change this to `Duty location not found` or something similar

2024-03-27 18:55 UTC, paulstonebraker commented on pkg/handlers/ghcapi/orders.go
> +				err = apperror.NewBadDataError("Service member cannot be verified")
Copying and pasting too fast smh

2024-03-28 16:47 UTC, paulstonebraker commented on src/components/Office/AddOrdersForm/AddOrdersForm.test.jsx
> +    });
Added, will update test alert amount if DutyLocationInput component gets updated to display alert

2024-03-28 17:33 UTC, danieljordan-caci approved these changes
Appreciate all of the changes. Beautiful work! Tested locally & looks WAY better.

 LGTM!!

2024-03-28 17:41 UTC, merged