INT-B-19148 Fix
transcom/mymove pull request #12349
Opened 2024-03-27 16:32 UTC by loganwc

## [Agility ticket](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A922834)

## Summary

Resolved an issue where approving ppm documents still sent an email.

### How to test

1. Run the backend with `EMAIL_BACKEND=ses AWS_REGION=us-gov-west-1  aws-vault exec transcom-gov-dev -- make server_run`
2. Create a new customer and create a BLUEBARK move
3. Approve the move as a SC
4. Approve items as TOO
5. Make changes as Prime
6. Approve/reject as TIO

Make sure no emails were sent

2024-03-27 17:15 UTC, paulstonebraker approved these changes

2024-03-27 18:14 UTC, danieljordan-caci requested changes

2024-03-27 18:14 UTC, danieljordan-caci commented on pkg/handlers/ghcapi/ppm_document.go
> +			move, _ := models.FetchMoveByMoveIDWithOrders(appCtx.DB(), ppmShipment.Shipment.MoveTaskOrderID)
I know it is tempting, but please do not disregard the error check here. If this query fails then you will not have the info that you need later on down in this handler function.

2024-03-28 18:35 UTC, danieljordan-caci approved these changes

2024-03-28 19:38 UTC, merged