B:18830 - Add Office Account Request Form
transcom/mymove pull request #12425
Opened 2024-04-05 23:26 UTC by TevinAdams

## [B-18830](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-18830)
## MERGE AFTER [B-19465](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-19465)

## Summary

This MR introduces functionality that will allow a user to request an office account by filling out a form.

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the Office Sign In Page
2. Select the Request Account tab in the top right corner of the navigation bar
3. Fill out the required information on the form then select Request Account Button
4. Check database table office_users. You should see the record with a REQUESTED status. You can also check the network tab for a 200.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

## Screenshots

2024-04-08 13:09 UTC, danieljordan-caci commented
You have a TON of commits that need to be looked at. A lot of these should already be in `integrationTesting` - do you happen to have some `main` commits in here?

2024-04-08 14:04 UTC, danieljordan-caci commented on src/utils/validation.js
> +    'Please select a role to request.',
Can you change `Please select a role to request` to something like `You must select at least one role`?

2024-04-08 14:13 UTC, TevinAdams commented
> Looking at the blurb you have on the page - have you had this reviewed by Danny? Might want to make sure he's cool with what's written. Ask me how I know haha
> 
> ```
> To request an office acount, please fill out the form below with all required fields. \
> Once submitted, a MilMove admin will review your account. 
> If approved, you will be notified and allowed to log in.
> 
> NOTE: When filling out your EDIPI or unique identifier, you MUST provide one or the other. 
> If using CAC, fill out the EDIPI field. If using PIV or ECA certs, please fill out the unique identifier.
> ```

@danieljordan-caci  All texts came from the attachment in the story from the text labels to the blurb up top.

2024-04-08 14:15 UTC, danieljordan-caci commented
> > Looking at the blurb you have on the page - have you had this reviewed by Danny? Might want to make sure he's cool with what's written. Ask me how I know haha
> > ```
> > To request an office acount, please fill out the form below with all required fields. \
> > Once submitted, a MilMove admin will review your account. 
> > If approved, you will be notified and allowed to log in.
> > 
> > NOTE: When filling out your EDIPI or unique identifier, you MUST provide one or the other. 
> > If using CAC, fill out the EDIPI field. If using PIV or ECA certs, please fill out the unique identifier.
> > ```
> 
> @danieljordan-caci All texts came from the attachment in the story from the text labels to the blurb up top.

Yeah I was the one that created that mockup but I have found that Danny doesn't like the word EDIPI so just saying to double check with him on it since we are actually pushing the code and not just doing a mockup.

2024-04-08 14:24 UTC, TevinAdams commented on src/components/form/OfficeAccountRequestFields/index.jsx
> +            label="DoD ID number | EDIPI"
@danieljordan-caci  That is what the attachment in the agility ticket had.

2024-04-08 14:26 UTC, TevinAdams commented
> > > Looking at the blurb you have on the page - have you had this reviewed by Danny? Might want to make sure he's cool with what's written. Ask me how I know haha
> > > ```
> > > To request an office acount, please fill out the form below with all required fields. \
> > > Once submitted, a MilMove admin will review your account. 
> > > If approved, you will be notified and allowed to log in.
> > > 
> > > NOTE: When filling out your EDIPI or unique identifier, you MUST provide one or the other. 
> > > If using CAC, fill out the EDIPI field. If using PIV or ECA certs, please fill out the unique identifier.
> > > ```
> > 
> > 
> > @danieljordan-caci All texts came from the attachment in the story from the text labels to the blurb up top.
> 
> Yeah I was the one that created that mockup but I have found that Danny doesn't like the word EDIPI so just saying to double check with him on it since we are actually pushing the code and not just doing a mockup.

@danieljordan-caci Okay cool Ill change it then. I didn tknow you made it but thats an easy change.

2024-04-08 14:27 UTC, TevinAdams commented on src/components/form/OfficeAccountRequestFields/index.jsx
> +            label="DoD ID number | EDIPI"
@danieljordan-caci  Yup I can make that change.

2024-04-08 14:37 UTC, TevinAdams commented on src/components/Office/RequestAccountForm/RequestAccountForm.jsx
> +              </p>
@danieljordan-caci  Done

2024-04-08 14:37 UTC, TevinAdams commented on src/components/MilMoveHeader/LoggedOutUserInfo.jsx
> +      {app === 'office' && (
@danieljordan-caci  Done

2024-04-08 14:37 UTC, TevinAdams commented on src/utils/validation.js
> +    .nullable(),
@danieljordan-caci  Done

2024-04-08 14:38 UTC, TevinAdams commented on src/utils/validation.js
> +    .nullable(),
@danieljordan-caci  should otherUniqueId be required if there is no DODID# filled out?

2024-04-08 14:40 UTC, danieljordan-caci commented on src/utils/validation.js
> +    .nullable(),
Can look at it that way, yeah, but also need to also consider it the other way. If `otherUniqueID` is not provided then `DODID#` is required

2024-04-08 14:41 UTC, TevinAdams commented on src/components/form/OfficeAccountRequestFields/index.jsx
> +          />
@danieljordan-caci  Done

2024-04-08 14:42 UTC, TevinAdams commented on src/components/form/OfficeAccountRequestFields/index.jsx
> +            inputMode="numeric"
@danieljordan-caci  Done

2024-04-08 14:43 UTC, TevinAdams commented on src/utils/validation.js
> +    'Please select a role to request.',
@danieljordan-caci  Done

2024-04-08 15:42 UTC, TevinAdams commented on src/components/form/OfficeAccountRequestFields/index.jsx
> +export const OfficeAccountRequestFields = ({ render }) => {
@danieljordan-caci  Done

2024-04-08 15:44 UTC, TevinAdams commented on src/components/MilMoveHeader/LoggedOutUserInfo.jsx
> +                data-testid="requestaccount"
@danieljordan-caci  Done

2024-04-08 15:45 UTC, TevinAdams commented on src/utils/validation.js
> +    .nullable(),
@danieljordan-caci  cool got it. I made the change have not merged any changes into the int branch yet.

2024-04-08 18:25 UTC, TevinAdams commented on src/pages/Office/RequestAccount/RequestAccount.jsx
> +      })
@danieljordan-caci added flash message

2024-04-08 19:03 UTC, TevinAdams commented
> Looking at the blurb you have on the page - have you had this reviewed by Danny? Might want to make sure he's cool with what's written. Ask me how I know haha
> 
> ```
> To request an office acount, please fill out the form below with all required fields. \
> Once submitted, a MilMove admin will review your account. 
> If approved, you will be notified and allowed to log in.
> 
> NOTE: When filling out your EDIPI or unique identifier, you MUST provide one or the other. 
> If using CAC, fill out the EDIPI field. If using PIV or ECA certs, please fill out the unique identifier.
> ```

Changed it to the blurb you suggested. No longer using the edipi term.

2024-04-08 19:03 UTC, TevinAdams commented
> You have a TON of commits that need to be looked at. A lot of these should already be in `integrationTesting` - do you happen to have some `main` commits in here?

This branch does have the branch for the open transportation office endpoint merged into it.

2024-04-08 19:29 UTC, danieljordan-caci commented
> > You have a TON of commits that need to be looked at. A lot of these should already be in `integrationTesting` - do you happen to have some `main` commits in here?
> 
> This branch does have the branch for the open transportation office endpoint merged into it.

It seems like a lot more than that. Any input on this @cameroncaci or @deandreJones?

2024-04-08 19:39 UTC, TevinAdams commented
> > > You have a TON of commits that need to be looked at. A lot of these should already be in `integrationTesting` - do you happen to have some `main` commits in here?
> > 
> > 
> > This branch does have the branch for the open transportation office endpoint merged into it.
> 
> It seems like a lot more than that. Any input on this @cameroncaci or @deandreJones?

I also had to merge in Cameron's branch with the new endpoint to submit the form.

2024-04-08 20:22 UTC, danieljordan-caci commented
> > > > You have a TON of commits that need to be looked at. A lot of these should already be in `integrationTesting` - do you happen to have some `main` commits in here?
> > > 
> > > 
> > > This branch does have the branch for the open transportation office endpoint merged into it.
> > 
> > 
> > It seems like a lot more than that. Any input on this @cameroncaci or @deandreJones?
> 
> I also had to merge in Cameron's branch with the new endpoint to submit the form.

Yeah but all of that should already be in `integrationTesting` already so it shouldn't be appearing here

2024-04-08 20:49 UTC, traskowskycaci commented
> Yeah but all of that should already be in `integrationTesting` already so it shouldn't be appearing here

Pulling in the latest int might make this easier to review, right? Should bring down the # of commits

2024-04-08 22:36 UTC, TevinAdams commented
> > > > > You have a TON of commits that need to be looked at. A lot of these should already be in `integrationTesting` - do you happen to have some `main` commits in here?
> > > > 
> > > > 
> > > > This branch does have the branch for the open transportation office endpoint merged into it.
> > > 
> > > 
> > > It seems like a lot more than that. Any input on this @cameroncaci or @deandreJones?
> > 
> > 
> > I also had to merge in Cameron's branch with the new endpoint to submit the form.
> 
> Yeah but all of that should already be in `integrationTesting` already so it shouldn't be appearing here

I did merge it into my branch before it was in integration.

2024-04-09 12:55 UTC, cameroncaci requested changes
@TevinAdams 
Just make a fresh branch off integrationTesting -> cherry-pick your commits explicitly meant for 18830 into that new branch -> push and new PR. The git history here is pretty polluted, doing this would be the easiest way to start fresh. No need for any branch mergres since this one's upstream is already in integrationTesting

2024-04-09 21:39 UTC, closed without merging