changes for SC upload orders
transcom/mymove pull request #12442
Opened 2024-04-09 16:49 UTC by paulstonebraker

## [Agility ticket](tbd)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-04-09 17:20 UTC, landan-parker-0 commented
It works for me.
When I click 'done' before the upload is complete, it unmounts the previewer upload while it's processing, and does not proceed with the upload.
I think the done button should be disabled until the upload is completed.

2024-04-09 19:01 UTC, paulstonebraker commented
> It works for me. When I click 'done' before the upload is complete, it unmounts the previewer upload while it's processing, and does not proceed with the upload. I think the done button should be disabled until the upload is completed.

Good find, and I agree. Awaiting confirmation from PO but after discussion with coach clayton lets proceed as if this is not in the scope of this work and will be addressed as part of file deletion.

2024-04-09 19:32 UTC, pambecker approved these changes

2024-04-09 19:48 UTC, landan-parker-0 approved these changes
Works correctly according to criteria

2024-04-10 15:42 UTC, danieljordan-caci requested changes
Just a couple little things, but this is great work.

I did find a break in the code when reviewing this and I tagged @joeydoyecaci in his PR where he made those changes. Just make sure we get those changes back into `integrationTesting` before merging the `main` PR for that BL item. Thanks!

2024-04-10 15:42 UTC, danieljordan-caci commented on pkg/handlers/ghcapi/uploads.go
> +			rollbackErr := fmt.Errorf("error creating upload")
We don't want to use `fmt.Errorf` really at all. Using `appCtx` to log errors is preferred.

Can you instead do:
```
appCtx.Logger().Error("error creating upload")
```

2024-04-10 15:42 UTC, danieljordan-caci commented on swagger-def/ghc.yaml
> +          required: false
You can just remove this `required: false` line if ya wanna

2024-04-10 19:01 UTC, pambecker approved these changes

2024-04-10 19:02 UTC, danieljordan-caci approved these changes
Send it! LGTM!

2024-04-10 19:03 UTC, merged