B:18830 - Add Office Account Request Form
transcom/mymove pull request #12456
Opened 2024-04-09 21:32 UTC by TevinAdams

## [B-18830](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-18830)
## MERGE AFTER [B-19465](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-19465) - Currently in Integration

## Summary

This MR introduces functionality that will allow a user to request an office account by filling out a form.

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the Office Sign In Page
2. Select the Request Account tab in the top right corner of the navigation bar
3. Fill out the required information on the form then select Request Account Button
4. Check database table office_users. You should see the record with a REQUESTED status. You can also check the network tab for a 200.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

## Screenshots

2024-04-09 21:37 UTC, danieljordan-caci commented
Still a ton of commits in this that aren't yours

2024-04-09 21:54 UTC, TevinAdams commented
> Still a ton of commits in this that aren't yours

@danieljordan-caci  Yes that is because I have 2 different branches merged into mine. That commit history comes with it.

2024-04-10 13:32 UTC, danieljordan-caci commented
> > Still a ton of commits in this that aren't yours
> 
> @danieljordan-caci Yes that is because I have 2 different branches merged into mine. That commit history comes with it. My B-19465 and Camerons B-18823 I needed those main branches to develop in main because that code is not in main. By merging those branches into mine it comes with their commit history. Merging my main into my int branch brings all of that over. Main -> Does Not have 18823 and 19465. Int has both of those. But we develop off of main. My 18830 branch needs work from 18823 and 19465. Those branches were merged into my branch so I can complete the work on main. Only thing is the commit history comes with it. Created an Int branch off integration. Merge 18830 main branch into int branch. That git history comes with it. That is why this PR has all those commits. Only other way around that is to wait for the dependant stories to get to main then cherry pick my commits.

I think in situations (when there are multiple `main` branch dependencies that aren't in `main` yet) like this it might be best to base your INT branch off of `integrationTesting` and then cherry-pick the commits from your `main` branch into that and open the PR.

The commit history just seems very polluted and it's atypical to see it like this. I understand why they are there, but it just seems a little off.

2024-04-10 14:03 UTC, danieljordan-caci commented
> > > > Still a ton of commits in this that aren't yours
> > > 
> > > 
> > > @danieljordan-caci Yes that is because I have 2 different branches merged into mine. That commit history comes with it. My B-19465 and Camerons B-18823 I needed those main branches to develop in main because that code is not in main. By merging those branches into mine it comes with their commit history. Merging my main into my int branch brings all of that over. Main -> Does Not have 18823 and 19465. Int has both of those. But we develop off of main. My 18830 branch needs work from 18823 and 19465. Those branches were merged into my branch so I can complete the work on main. Only thing is the commit history comes with it. Created an Int branch off integration. Merge 18830 main branch into int branch. That git history comes with it. That is why this PR has all those commits. Only other way around that is to wait for the dependant stories to get to main then cherry pick my commits.
> > 
> > 
> > I think in situations (when there are multiple `main` branch dependencies that aren't in `main` yet) like this it might be best to base your INT branch off of `integrationTesting` and then cherry-pick the commits from your `main` branch into that and open the PR.
> > The commit history just seems very polluted and it's atypical to see it like this. I understand why they are there, but it just seems a little off.
> 
> @danieljordan-caci That would cut down the commits on the int branch but that main branch will still have those commits from the other branches.

It would not because those specific commits that are related to `main` are already in `main` so they would not show up.

The reason why we are seeing all of these commits is because they are commits from `main` and not `integrationTesting`

2024-04-10 14:04 UTC, danieljordan-caci commented on src/pages/Office/RequestAccount/RequestAccount.jsx
> +  const { setMessage } = props;
Instead of destructuring like you're doing on line 16, you can do it like this:

```
export const RequestAccount = ({ setMessage }) => {
  const navigate = useNavigate();
  const [serverError, setServerError] = useState(null);
```

`props` is already implied with functional components so you can just call it right in there

2024-04-10 14:05 UTC, danieljordan-caci commented on src/pages/Office/RequestAccount/RequestAccount.jsx
> +  const { setMessage } = props;
Also can you rename that to `setFlashMessage` instead of `setMessage`? More descriptive and follows what is currently done throughout the rest of the app.

2024-04-10 14:06 UTC, danieljordan-caci commented
> > > > > > Still a ton of commits in this that aren't yours
> > > > > 
> > > > > 
> > > > > @danieljordan-caci Yes that is because I have 2 different branches merged into mine. That commit history comes with it. My B-19465 and Camerons B-18823 I needed those main branches to develop in main because that code is not in main. By merging those branches into mine it comes with their commit history. Merging my main into my int branch brings all of that over. Main -> Does Not have 18823 and 19465. Int has both of those. But we develop off of main. My 18830 branch needs work from 18823 and 19465. Those branches were merged into my branch so I can complete the work on main. Only thing is the commit history comes with it. Created an Int branch off integration. Merge 18830 main branch into int branch. That git history comes with it. That is why this PR has all those commits. Only other way around that is to wait for the dependant stories to get to main then cherry pick my commits.
> > > > 
> > > > 
> > > > I think in situations (when there are multiple `main` branch dependencies that aren't in `main` yet) like this it might be best to base your INT branch off of `integrationTesting` and then cherry-pick the commits from your `main` branch into that and open the PR.
> > > > The commit history just seems very polluted and it's atypical to see it like this. I understand why they are there, but it just seems a little off.
> > > 
> > > 
> > > @danieljordan-caci That would cut down the commits on the int branch but that main branch will still have those commits from the other branches.
> > 
> > 
> > It would not because those specific commits that are related to `main` are already in `main` so they would not show up.
> > The reason why we are seeing all of these commits is because they are commits from `main` and not `integrationTesting`
> 
> No these commits are not in Main. 18823 and 19465 is not in Main. That is why In had to merge the main working branches for those stories into mine.

Commits based off of `main`* my bad

2024-04-10 14:12 UTC, danieljordan-caci commented on src/components/form/OfficeAccountRequestFields/OfficeAccountRequestFields.jsx
> +          <TextField label="Telephone" name={telephoneFieldName} id="officeAccountRequestTelephone" />
Instead of `TextField`, can you use `MaskedTextField`?

```
          <MaskedTextField
            label="Telephone"
            id="officeAccountRequestTelephone"
            name="telephone"
            type="tel"
            minimum="12"
            mask="000{-}000{-}0000"
          />
```

This helps the user out by facilitating the dashes when entering the phone number

2024-04-10 14:15 UTC, danieljordan-caci commented
Okay, I believe I have all of my suggestions in.

I'm going to defer to @deandreJones on how to handle the merge because with the number of commits listed from you merging other branches into yours and then merging your `main` branch into this one, it just seems a little off.

We can either wait for those dependent PRs to be merged into `main` and then handle this or I'll follow Dre's direction on if it's safe to approve or not.

2024-04-10 15:49 UTC, TevinAdams commented on src/components/form/OfficeAccountRequestFields/OfficeAccountRequestFields.jsx
> +          <TextField label="Telephone" name={telephoneFieldName} id="officeAccountRequestTelephone" />
@danieljordan-caci  This change has been made for the telephone field.

2024-04-10 15:50 UTC, TevinAdams commented on src/pages/Office/RequestAccount/RequestAccount.jsx
> +  const { setMessage } = props;
@danieljordan-caci  This name change has been made.

2024-04-10 15:51 UTC, TevinAdams commented on src/components/form/fields/DropdownInput.jsx
> +        {showDropdownPlaceholderText && <option value="">{dropDownPlaceHolderText}</option>}
@danieljordan-caci This is actually not needed. Earlier in the story I was trying something but then took a different approach. These changes have been removed.

2024-04-10 16:03 UTC, TevinAdams commented
> Okay, I believe I have all of my suggestions in.
> 
> I'm going to defer to @deandreJones on how to handle the merge because with the number of commits listed from you merging other branches into yours and then merging your `main` branch into this one, it just seems a little off.
> 
> We can either wait for those dependent PRs to be merged into `main` and then handle this or I'll follow Dre's direction on if it's safe to approve or not.

@danieljordan-caci The cleanest and low risk way from a commit history and best practices stand point is probably to wait until the dependents are in Main. Only thing is I would have to do what I did yesterday with 18828 which is create another branch, cherry pick my changes into it but there will be no need to merge in the dependent branches because those changes will be in main. Commit history will only have my commits then. In this case our branching strategy is to merge the main branch of needed work into our working main to complete the story then merge our main into our int. This brings all the commit history with it. We may need to discuss cherry-picking further and make adjustments in cases like this but I do not think cherry-picking should be a normal thing from a best practices point of view. We may need to discuss further on cases like this. Overall the cleanest way is to wait for the dependent stories to finish though.

2024-04-10 20:18 UTC, traskowskycaci requested changes
One file requiring a merge conflict resolution at the time I write this

Compared the commit history from Cameron's main 18823 branch: https://github.com/transcom/mymove/compare/main...B-18823-GHC-Create-Requested-Office-User and your 19465 branch: https://github.com/transcom/mymove/pull/12439/commits and see matching commits in this branch.

I noticed the Request Account button is touching the bottom of the page. Could you add some spacing around it?

![image](https://github.com/transcom/mymove/assets/147537467/b8fe5bec-0496-48dd-b291-32f41337eee8)

2024-04-11 03:26 UTC, TevinAdams commented
> One file requiring a merge conflict resolution at the time I write this
> 
> Compared the commit history from Cameron's main 18823 branch: [main...B-18823-GHC-Create-Requested-Office-User](https://github.com/transcom/mymove/compare/main...B-18823-GHC-Create-Requested-Office-User) and your 19465 branch: https://github.com/transcom/mymove/pull/12439/commits and see matching commits in this branch.
> 
> I noticed the Request Account button is touching the bottom of the page. Could you add some spacing around it?
> 
> ![image](https://private-user-images.githubusercontent.com/147537467/321390788-b8fe5bec-0496-48dd-b291-32f41337eee8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MDYyMjUsIm5iZiI6MTcxMjgwNTkyNSwicGF0aCI6Ii8xNDc1Mzc0NjcvMzIxMzkwNzg4LWI4ZmU1YmVjLTA0OTYtNDhkZC1iMjkxLTMyZjQxMzM3ZWVlOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQwMzI1MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYjZiOThlM2RhNjk1MmM5MTgxNDczNzQ2NjRkMTM3YmNjMzgxMzIyNDg1MTQ1ZDM2NTc5ZjI1MjZjM2M3ZTdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oA_Tg8WEHEO7Ijn17vuIiH1Ips_CR0X5kfb-jupRmvI)

@traskowskycaci Done
![image](https://github.com/transcom/mymove/assets/136514590/9327cd52-384f-45bb-b4d5-2d93d608a583)

2024-04-11 14:30 UTC, deandreJones commented
> > Okay, I believe I have all of my suggestions in.
> > I'm going to defer to @deandreJones on how to handle the merge because with the number of commits listed from you merging other branches into yours and then merging your `main` branch into this one, it just seems a little off.
> > We can either wait for those dependent PRs to be merged into `main` and then handle this or I'll follow Dre's direction on if it's safe to approve or not.
> 
> @danieljordan-caci The cleanest and low risk way from a commit history and best practices stand point is probably to wait until the dependents are in Main. Only thing is I would have to do what I did yesterday with 18828 which is create another branch, cherry pick my changes into it but there will be no need to merge in the dependent branches because those changes will be in main. Commit history will only have my commits then. In this case our branching strategy is to merge the main branch of needed work into our working main to complete the story then merge our main into our int. This brings all the commit history with it. We may need to discuss cherry-picking further and make adjustments in cases like this but I do not think cherry-picking should be a normal thing from a best practices point of view. We may need to discuss further on cases like this. Overall the cleanest way is to wait for the dependent stories to finish though.

IF there are dependencies necessary for this BL- then those need to be move along first- so please wait to merge this- until the depencies have been resovled(merged)

2024-04-11 14:34 UTC, danieljordan-caci approved these changes
Thanks for making all of the changes. 

Approving this so you'll be able to merge once those dependencies are good to go in `main` since you're merging your `main` branch into this one.

2024-04-11 15:16 UTC, traskowskycaci approved these changes

2024-04-11 15:27 UTC, traskowskycaci approved these changes
Looks good!

2024-04-11 17:44 UTC, merged