B-19175-INT
transcom/mymove pull request #12526
Opened 2024-04-17 19:43 UTC by paulstonebraker

…ustomer search; wrap customer search in FF

## [Agility ticket](tbd)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-04-17 19:49 UTC, paulstonebraker commented on src/constants/routes.js
> +  QUEUE_SEARCH_PATH: 'Search',
@joeydoyecaci @loganwc can I remove these since they're in generalRoutes?

2024-04-17 20:17 UTC, paulstonebraker commented on src/components/CustomerSearchForm/CustomerSearchForm.jsx
> +
add Yup validation here

2024-04-17 20:34 UTC, paulstonebraker commented on src/constants/routes.js
> +  QUEUE_SEARCH_PATH: 'Search',
Can potentially remove QUEUE_SEARCH_PATH, BASE_QUEUE_SEARCH_PATH, BASE_ORDERS_ADD_PATH, ORDERS_ADD_PATH

2024-04-17 20:35 UTC, paulstonebraker commented on src/pages/Office/index.jsx
> +                          <ServicesCounselingAddOrders />
can potentially remove the counterpart to this added in old add orders workflow?

2024-04-17 20:48 UTC, loganwc commented on pkg/handlers/ghcapi/customer_test.go
> +// func (suite *HandlerSuite) TestSearchCustomersHandler() {
👀

2024-04-17 20:48 UTC, loganwc commented on src/constants/routes.js
> +  QUEUE_SEARCH_PATH: 'Search',
Yeah if it doesn't break when you remove them then I think it's fine because Joey consilidated and updated some of the routes

2024-04-17 20:50 UTC, paulstonebraker commented on pkg/handlers/ghcapi/customer_test.go
> +// func (suite *HandlerSuite) TestSearchCustomersHandler() {
> 👀

my solution to flaky tests

2024-04-19 14:22 UTC, loganwc approved these changes

2024-04-19 16:18 UTC, danieljordan-caci requested changes
Another big fat PR for Paul. Just a few things - nothing major. Great work on this.

2024-04-19 16:18 UTC, danieljordan-caci commented on pkg/services/office_user/customer/customer_searcher.go
> +	if params.DodID == nil && params.CustomerName == nil {
Shouldn't this be `||` instead of `&&`?

2024-04-19 16:18 UTC, danieljordan-caci commented on pkg/services/office_user/customer/customer_searcher.go
> +	if params.DodID == nil && params.CustomerName == nil {
I'm basing this off of your `verrs` message `DOD ID or customer name must be provided`

2024-04-19 16:18 UTC, danieljordan-caci commented on src/components/CustomerSearchForm/CustomerSearchForm.jsx
> +  searchType: Yup.string().required('searchtype error'),
Would the user know what `searchtype error` is? If not, we should make this more descriptive. Also should be camelCase if you're rolling forward with this error.

2024-04-19 16:18 UTC, danieljordan-caci commented on src/components/CustomerSearchForm/CustomerSearchForm.jsx
> +    searchText: Yup.string().trim().length(10, 'DOD ID must be exactly 10 characters'),
Can you clarify `numbers` or `digits` instead of `characters`?

2024-04-19 16:18 UTC, danieljordan-caci commented on src/components/CustomerSearchForm/CustomerSearchForm.jsx
> +      // eslint-disable-next-line consistent-return
Is this block of comments necessary?

2024-04-19 16:18 UTC, danieljordan-caci commented on src/components/CustomerSearchForm/CustomerSearchForm.test.jsx
> +          expect.anything(),
Not sure if I like `expect.anything()` - what happens when they submit the form? Are they navigated somewhere? I'd test for that instead.

2024-04-19 16:41 UTC, loganwc commented on pkg/services/office_user/customer/customer_searcher.go
> +	if params.DodID == nil && params.CustomerName == nil {
I think it should be && because if one isn't nil it should do search

2024-04-19 16:41 UTC, loganwc commented on pkg/services/office_user/customer/customer_searcher.go
> +	if params.DodID == nil && params.CustomerName == nil {
Basically you need one OR the other but you need to check both ala the ||

2024-04-19 16:44 UTC, danieljordan-caci commented on pkg/services/office_user/customer/customer_searcher.go
> +	if params.DodID == nil && params.CustomerName == nil {
Gotcha. So maybe a better error would be `You must provide either DOD ID or customer name` or something like that

2024-04-19 20:59 UTC, paulstonebraker commented on pkg/services/office_user/customer/customer_searcher.go
> +	if params.DodID == nil && params.CustomerName == nil {
I think `DOD ID or customer name must be provided` is fine

2024-04-19 20:59 UTC, paulstonebraker commented on src/components/CustomerSearchForm/CustomerSearchForm.jsx
> +  searchType: Yup.string().required('searchtype error'),
good call, updated

2024-04-19 20:59 UTC, paulstonebraker commented on src/components/CustomerSearchForm/CustomerSearchForm.jsx
> +    searchText: Yup.string().trim().length(10, 'DOD ID must be exactly 10 characters'),
Updated

2024-04-19 21:02 UTC, paulstonebraker commented on src/components/CustomerSearchForm/CustomerSearchForm.test.jsx
> +          expect.anything(),
I believe `expect.anything()` in this case applies to the rest of the data and allows us to use `toHaveBeenCalledWith` rather than `toHaveBeenCalled` so we can check for the presence of `searchText` and `searchType` but I made a small update to the test as well

2024-04-19 21:02 UTC, paulstonebraker commented on src/components/CustomerSearchForm/CustomerSearchForm.jsx
> +      // eslint-disable-next-line consistent-return
Removed except for eslint-disabled

2024-04-22 14:09 UTC, loganwc requested changes

2024-04-22 14:09 UTC, loganwc commented on src/components/CustomerSearchForm/CustomerSearchForm.test.jsx
> +      const onSubmit = searchCustomers;
you don't need this variable anymore, it's unused in this test. You're only referencing searchCustomers

2024-04-22 17:47 UTC, paulstonebraker commented
@pambecker brought to my attention that column sorting doesn't work, so putting this on pause until then

2024-04-22 22:32 UTC, paulstonebraker commented on src/components/CustomerSearchForm/CustomerSearchForm.jsx
> +      // eslint-disable-next-line consistent-return
I lied, the comments were necessary

https://dp3.atlassian.net/wiki/spaces/MT/pages/1921122376/Guide+to+Static+Analysis+Annotations+for+Disabled+Linters

2024-04-23 20:02 UTC, pambecker approved these changes

2024-04-24 14:12 UTC, danieljordan-caci commented on src/components/CustomerSearchForm/CustomerSearchForm.test.jsx
> +          expect.anything(),
Understood. Resolved!

2024-04-24 14:13 UTC, danieljordan-caci approved these changes
LGTM! Good work on this.

2024-04-24 14:33 UTC, loganwc approved these changes

2024-04-24 14:34 UTC, merged