B 19500 update 858 generator
transcom/mymove pull request #12536
Opened 2024-04-18 18:40 UTC by pambecker

**Fix issue when MilMove sends EDI 858s to Syncada via the GEX they are still sending test invoices with Prod invoices.**

Agility ticket 
https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A936878

_Verification Steps for Reviewers:_
These are to be checked by a reviewer.
- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

_How to test:_
1. Setup a payment request, grab the id to setup and call the endpoints
2. In Postman you can call (Login as a Prime on the UI to run the endpoints in Postman)
   /payment-requests/{paymentRequestID}/edi
3. OR in cmd line, you can call
   go run ./cmd/generate-payment-request-edi/ --payment-request-number {paymentRequestNumber}

2024-04-18 20:38 UTC, danieljordan-caci requested changes

2024-04-18 20:38 UTC, danieljordan-caci commented on pkg/handlers/supportapi/payment_request.go
> +			if flag == "production" || flag == "prod" || flag == "prd" {
I know this might be annoying, but can you change the variable name of this from `flag` to `envFlag` to be more descriptive and follow what's being done in `generate-payment-request-edi/main.go`?

2024-04-18 20:38 UTC, danieljordan-caci commented on pkg/handlers/supportapi/payment_request_test.go
> +		if flag == "production" || flag == "prod" || flag == "prd" {
`envFlag` plz

2024-04-18 20:38 UTC, danieljordan-caci commented on pkg/services/payment_request/payment_request_reviewed_processor.go
> +		if flag == "production" || flag == "prod" || flag == "prd" {
`envFlag` plz

2024-04-18 21:38 UTC, paulstonebraker approved these changes

2024-04-19 13:29 UTC, danieljordan-caci approved these changes
Thanks for making those changes! LGTM!

2024-04-19 13:30 UTC, deandreJones approved these changes

2024-04-19 13:30 UTC, merged