B 20034 int
transcom/mymove pull request #12595
Opened 2024-05-03 20:15 UTC by CoryKleinjanCACI

## [Agility ticket](tbd)

## Summary

This PR updates [B-19507](https://github.com/transcom/mymove/pull/12530) so that the application_parameters table can hold a wider array of parameters.

The tests here are to validate that 19507 still functions as expected.

### How to test

Couple of setup things you need to do first:
- `make db_dev_migrate` (this will create the `application_parameters` table
- You'll need to fill in a row with a value in `parameter_name`, 'parameter_value' and `id`, `updated_at` and `created_at` will auto populate
- In your `.envrc`, set `export FEATURE_FLAG_VALIDATION_CODE_REQUIRED=true`
- Now fire up your `client` and `server`

**For the happiest path**
1. Access MM as a customer
2. Login as a brand new customer
3. You should now see the validation code screen
4. Input the code you slapped in the `application_parameters` table
5. It should now let you progress through the profile set up

**For the saddest path**
1. Access MM as a customer
2. Login as a brand new customer
3. You should now see the validation code screen
4. Input anything other than the code you put in the database
5. You should see an error screen and not be able to progress
6. You can have as many attempts as you want when inputting the code (this was a requirement from Kipp)

## Screenshots
![Screenshot 2024-04-12 at 11 07 01 AM](https://github.com/transcom/mymove/assets/136510600/e8e522af-ecba-490e-b1d3-f3de93b81b2d)

Mobile
![Screenshot 2024-04-12 at 11 21 56 AM](https://github.com/transcom/mymove/assets/136510600/c7adffae-d824-4311-ae8d-bdcb430d3074)

![Screenshot 2024-04-12 at 11 12 31 AM](https://github.com/transcom/mymove/assets/136510600/c72a663b-caf1-4fa2-848e-432da5809dd3)

Mobile
![Screenshot 2024-04-12 at 11 21 38 AM](https://github.com/transcom/mymove/assets/136510600/bad88699-4e8f-4f20-a0fb-e8f4532d5639)

2024-05-06 14:35 UTC, danieljordan-caci requested changes
Little stuff with the comments - other than that, good work!

2024-05-06 14:35 UTC, danieljordan-caci commented on pkg/handlers/internalapi/application_parameters.go
>  			// receive the code
`receive the value`

2024-05-06 14:35 UTC, danieljordan-caci commented on pkg/handlers/internalapi/application_parameters.go
>  			// fetch the code, if not found it will be an empty string
`fetch the value`

2024-05-06 14:35 UTC, danieljordan-caci commented on pkg/models/application_parameters.go
> +// ApplicationParameters is a model representing application parameters and holds validation codes stored in the database
This comment could be cleaned up, too.
`a model representing application parameters and holds values related to their parameter names` or something like that

Just getting rid of the word `code` since we are generalizing the table now

2024-05-06 14:35 UTC, danieljordan-caci commented on pkg/models/application_parameters_test.go
>  	// if the code is not found, it should return an empty string
`if the value is not found`...

2024-05-06 14:55 UTC, danieljordan-caci commented
Okay, so I talked with @deandreJones and let's make a few changes to this to avoid any issues in production.

Instead of renaming the column, keep the `validation_code` column and add the new columns instead.

Then we can do a follow up story and remove the `validation_code` column once we know everything is working correctly.

2024-05-06 14:57 UTC, danieljordan-caci commented on migrations/app/schema/20240502183613_add_support_for_standalone_payment_cap.up.sql
> +COMMENT ON COLUMN application_parameters.parameter_value IS 'The value of the parameter';
So just to give reference to what I commented. Change this to:

```
ALTER TABLE application_parameters
ADD COLUMN IF NOT EXISTS parameter_name TEXT NOT NULL;
ADD COLUMN IF NOT EXISTS parameter_value TEXT NOT NULL;

COMMENT ON COLUMN application_parameters.parameter_name IS 'The name of the parameter';
COMMENT ON COLUMN application_parameters.parameter_value IS 'The value of the parameter';
```

2024-05-06 17:57 UTC, CoryKleinjanCACI commented on migrations/app/schema/20240502183613_add_support_for_standalone_payment_cap.up.sql
> +COMMENT ON COLUMN application_parameters.parameter_value IS 'The value of the parameter';
Agreed that makes sense. I updated it.

2024-05-08 13:37 UTC, danieljordan-caci commented on pkg/models/application_parameters.go
> +	ParameterValue string    `json:"parameter_value" db:"parameter_value"`
You need to return `ValidationCode` to this struct please

2024-05-08 18:16 UTC, danieljordan-caci approved these changes
Looks good on my end! Stamped!

2024-05-08 19:56 UTC, r-mettler approved these changes

2024-05-08 20:47 UTC, merged

2024-05-09 14:07 UTC, deandreJones reviewed
look good