Int b 19814 add origin/dest sit auth end date to db
transcom/mymove pull request #12593
Opened 2024-05-03 19:08 UTC by MichaelEngelbertCACI

## [Agility ticket](tbd)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-05-03 19:19 UTC, danieljordan-caci requested changes
Couple of things we like to have when adding columns/tables via migration files.

- Throwing in `IF NOT EXISTS` before the column name. This helps us avoid some unnecessary errors when running the migration.
ex. `ADD COLUMN  IF NOT EXISTS origin_sit_auth_end_date`

- Also make sure you're adding comments to the added columns - more info means more understanding.
ex. 
```
COMMENT ON COLUMN mto_shipments.origin_sit_auth_end_date IS 'This is a comment for this column.';
```

You can find some good examples in the existing migration files.

Some things specific to this implementation:
- Could you change the column names to use `auth` instead of `aut`? It is short for `authorized` so we want that to reflect accurately in the shorthand (also it says in the title of the BL item). Also keep in mind you'll need to rename the title of the migration file as well.

- In regards to adding comments for the columns. Are you familiar with SIT and what it is? What the authorized end date is? What the difference between origin and destination SIT is? Doing this small PRs like this is a great time to learn what they are so your comments can accurately reflect what the column is for.

- The PR description should not remain a boilerplate. Please fill in all relevant information, how to test as reviewers, plenty of PRs for you to compare to in order to keep it similar to how we've been doing it.


As always... Holler if you have questions. I invited you to a Teams meeting next Monday to go over all of these things, but please use your time between now and then to work on changing these things and improving your understanding on WHAT these changes mean and how it impacts the application. Kudos to getting your first PR up!

2024-05-03 19:21 UTC, danieljordan-caci commented
In addition to what I just put, make sure you're:
- assigning yourself to this PR in the `Assignees` section
- when requesting to merge code into `integrationTesting`, we want to add the label `INTEGRATION` to the PR
- always add the label of the team for your PRs, you can search for `Mountain Movers` and it's pink

2024-05-07 19:07 UTC, traskowskycaci approved these changes
I noticed aut rather than auth in the migration title, do you mind fixing that?

I do see the columns locally.

Make sure to get the summary of your PR update and also merge in the latest integration before pushing up.

2024-05-13 12:41 UTC, cameroncaci reviewed
Migration worked like a charm. @traskowskycaci @danieljordan-caci thoughts on if we remove the abbreviations and replace it with the long form of `origin_sit_authorized_end_date` and `destination_sit_authorized_end_date`? This would update "auth" and "dest" with their full wordage

2024-05-13 13:24 UTC, danieljordan-caci commented
> Migration worked like a charm. @traskowskycaci @danieljordan-caci thoughts on if we remove the abbreviations and replace it with the long form of `origin_sit_authorized_end_date` and `destination_sit_authorized_end_date`? This would update "auth" and "dest" with their full wordage

I don't feel it is necessary, personally - not against it though. I know that's not helpful, but that's how I feel haha

2024-05-13 13:40 UTC, traskowskycaci commented
> Migration worked like a charm. @traskowskycaci @danieljordan-caci thoughts on if we remove the abbreviations and replace it with the long form of `origin_sit_authorized_end_date` and `destination_sit_authorized_end_date`? This would update "auth" and "dest" with their full wordage

Either way works for me!

2024-05-13 16:44 UTC, danieljordan-caci approved these changes
I see the description is updated! Nice. Just one more little thing and this should be good to go.

2024-05-13 16:44 UTC, danieljordan-caci commented on migrations/app/schema/20240503181242_add_origin_dest_sit_aut_end_date_to_mto_shipments_table.up.sql
> +COMMENT ON COLUMN mto_shipments.dest_sit_auth_end_date IS 'receive the initial SIT authorized end date from the destination and subsequent updates';
Please change the title of this migration from to use `auth` and not `aut`

2024-05-14 14:00 UTC, merged