B-19178 MTO shipment risk of excess banner persistence solution
transcom/mymove pull request #12608
Opened 2024-05-06 22:54 UTC by landan-parker-0

## [Agility ticket](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-19178)

## Summary

Is there anything you would like reviewers to give additional scrutiny?
Continuation of:
https://github.com/transcom/mymove/pull/12499
## Screenshots

2024-05-15 18:54 UTC, pambecker commented on src/pages/Office/CustomerOnboarding/CreateCustomerForm.test.jsx
> +  it('submits the form and tests for unsupported state validation', async () => {
I noticed this file had more changes than your INT PR.  seems this test is duplicated in this file.  maybe a bad merge fix

2024-05-15 20:22 UTC, pambecker reviewed
Please delete the extra branches not being used for this backlog.

2024-05-15 20:22 UTC, pambecker commented on src/pages/Office/CustomerOnboarding/CreateCustomerForm.test.jsx
> -    await userEvent.type(getByTestId('cac-user-no'), fakePayload.cac_user);
did you mean to delete this line?

2024-05-15 20:22 UTC, pambecker commented on src/pages/Office/CustomerOnboarding/CreateCustomerForm.test.jsx
> -    await userEvent.type(getByTestId('create-okta-account-yes'), fakePayload.create_okta_account);
Maria updated this line (188) and line 190 in a recent merge to main, be sure you aren't breaking any logic.  I think we need to keep these lines.

2024-05-16 19:36 UTC, pambecker approved these changes
this matches the INT PR.  Please delete the extra 19178 int branch as mentioned before.

2024-05-20 17:23 UTC, loganwc approved these changes

2024-05-23 14:22 UTC, paulstonebraker requested changes

2024-05-23 14:22 UTC, paulstonebraker commented on pkg/services/move/move_weights.go
> +	if shouldSaveMoveRecord {
Were there any logic changes or was this refactored for some reason? I don't see any changes

2024-05-23 14:22 UTC, paulstonebraker commented on src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
> +  }, [estimatedWeightTotal, order?.entitlement?.authorizedWeight]);
I thought this was accurate (the excess weight flag directs your to look review the max billable weight), but the way it was originally is accurate. We should be checking against entitlement.totalWeight.

`A move is considered having excess weight if the total move weight exceeds the customer's weight allowance. A move is considered having risk of excess weight if the estimated weight total is within 90% of the customer’s weight allowance.`

2024-05-23 14:22 UTC, paulstonebraker commented on src/pages/Office/MoveDetails/MoveDetails.jsx
> +  }, [estimatedWeightTotal, order?.entitlement?.authorizedWeight]);
Same comment as I left in MoveTaskOrder.jsx. I think we need to clear up with PO how we want to handle this

2024-05-23 14:22 UTC, paulstonebraker commented on src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
> -  const nonPPMShipments = mtoShipments?.filter((shipment) => shipment.shipmentType !== 'PPM');
not going to die on this hill but I think this is easier to read

2024-05-28 18:39 UTC, closed without merging