B 19181 int create pptas api
transcom/mymove pull request #12629
Opened 2024-05-08 19:16 UTC by joeydoyecaci

Linked BLI: [B-19181](https://www13.v1host.com/USTRANSCOM38/TeamRoom.mvc/Show/848240)

##How to test:

#Testing Prerequisites

1. Postman is required to test. 
2. PPTAS is acessed through TLS similar to acessing Prime API. In setup of Postman, you must add the mTLS certificates to postman. See [Setup Postman to make mTLS calls](https://transcom.github.io/mymove-docs/docs/tools/postman/setup-postman-to-make-mutual-tls-api-calls). This will cover your authentication to the API.
3. Easiest way to get the API definition into postman is to import it as a Postman collection with OpenAI Spec 2.0 using the generated pptas.yaml file under /swagger.
4. Setup an environment in postman for making Prime API calls, then set an env variable for the base url and api (Optional, but otherwise you will have to manually add base url to the request). ![EnvSetup](https://github.com/transcom/mymove/assets/150186792/b4665dc5-ecfa-4cfd-819a-40ebff057179)
5. Setup a collection variable for the path routing from base url to api path (`prime/pptas`). Set apiPath under collection variables as shown here: 
![CollectionVariableSettings](https://github.com/transcom/mymove/assets/150186792/d676e83e-1942-41f7-bdda-b2d2f21372d6)
 6. Click on listMoves to edit the request to the following: `{{baseUrl}}/{{apiPath}}/moves?since=<dateTime>`
![RouteSetup](https://github.com/transcom/mymove/assets/150186792/cbff0f3d-73a2-44d2-bb04-a74e6bbc72ab)
7, Both client and server must be running.

#How To Test

1. Go to [PPTAS Swagger](http://primelocal:3000/swagger-ui/pptas.html) and verify that the page loads and there is a single endpoint here.
2. Go under that endpoint and try calling it using the example date (or any date).
3. The page should show the JSON results under a 200 result.
4. Within postman run the request using the one you setup in the pre requisites earlier. This should return a 200 result the reuslts in the response body.

2024-05-13 17:36 UTC, danieljordan-caci requested changes

2024-05-13 17:36 UTC, danieljordan-caci commented on pkg/cli/hosts.go
> +	// HTTPPPTASServerNameFlag is the HTTP GHC Prime Server Name Flag
Fix your comment here please.
`HTTPPPTASServerNameFlag is the HTTP PPPTAS Server Name Flag` or whatever you see fit

2024-05-13 17:36 UTC, danieljordan-caci commented on pkg/cli/services.go
> +	ServePPTASFlag string = "serve-api-pptas"
Same here for this comment. If PPTAS is going to be used outside of the GHC, then this comment is not correct.

2024-05-13 17:36 UTC, danieljordan-caci commented on pkg/handlers/routing/routing_init.go
>  			})
Did you mean to replace `prime/v3`? If not then you need to fix this. Can just revert this back to what it was and copy what is there underneath it.

2024-05-13 17:36 UTC, danieljordan-caci commented on swagger-def/pptas.yaml
> +  $ref: 'paths/pptas-paths/pptasEndpointPaths.yaml'
I understand what you're trying to do here, but let's have this `yaml` file be in the same format as the other ones. Or at least having the paths listed in this same file instead of having to go to `pptasEndpointPaths.yaml`

To me it's a little out of ordinary (and again... I understand what you're trying to do by compartmentalizing to avoid the giant wall of text), but for any dev that's going to work on the PPTAS swagger files, this will be atypical for them and they will likely spend extra time learning how this is structured - which we can avoid by just going with what we are used to and how the other swagger yamls are structured.

2024-05-15 13:19 UTC, joeydoyecaci commented on swagger-def/pptas.yaml
> +  $ref: 'paths/pptas-paths/pptasEndpointPaths.yaml'
I've needed to think it over a bit. I could see merging the endpoints back into the pptas.yaml file, as that may never be reused by other APIs. But I'd rather keep the endpoint dependencies separate, as some of these dependencies are also used within the other APIS (such as error handling or move models, etc.). Sure that is a change from the current pattern still, but that is a new precedent I'd like to set with PPTAS, that shouldn't be that far a departure. Would you consider this a good compromise?

2024-05-15 13:32 UTC, danieljordan-caci commented on swagger-def/pptas.yaml
> +  $ref: 'paths/pptas-paths/pptasEndpointPaths.yaml'
At the end of the day it's just my opinion - so really you can do whatever you want! Just my thoughts on it, is all.

2024-05-15 21:38 UTC, joeydoyecaci commented on pkg/cli/hosts.go
> +	// HTTPPPTASServerNameFlag is the HTTP GHC Prime Server Name Flag
Comment has been fixed.

2024-05-15 21:38 UTC, joeydoyecaci commented on pkg/cli/services.go
> +	ServePPTASFlag string = "serve-api-pptas"
Comment has been fixed.

2024-05-15 21:39 UTC, joeydoyecaci commented on pkg/handlers/routing/routing_init.go
>  			})
I've added back the /prime/v3 route.

2024-05-15 21:40 UTC, joeydoyecaci commented on swagger-def/pptas.yaml
> +  $ref: 'paths/pptas-paths/pptasEndpointPaths.yaml'
Fair enough, and I greatly appreciate the input here!

2024-05-16 19:24 UTC, pambecker approved these changes

2024-05-16 20:42 UTC, danieljordan-caci approved these changes

2024-05-17 21:55 UTC, merged