B-19722-INT USCG Customer must enter EMPLID
transcom/mymove pull request #12637
Opened 2024-05-09 17:30 UTC by paulstonebraker

## [Agility ticket](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-19722)

## Summary

USCG customers must enter EMPLID on account creation. This value is editable when a move is in draft state.

### How to test

1. Create a new customer
2. Select Coast Guard as branch and enter EMPLID
3. Go back and forth between pages and try to break (change branches, enter letters, etc)
4. If not broken advance through profile and orders creation until you have a move in draft. Access your profile screen and edit your EMPLID and try to break
5. If not broken, create a new customer and confirm that EMPLID must be unique

2024-05-09 17:43 UTC, paulstonebraker commented on src/pages/MyMove/Profile/DodInfo.jsx
> +          errorMessage = 'This EMPLID is already in use';
@danieljordan-caci any thoughts on handling the error this way

2024-05-09 18:24 UTC, danieljordan-caci commented on src/pages/MyMove/Profile/DodInfo.jsx
> +          errorMessage = 'This EMPLID is already in use';
I don't hate it, but part of me doesn't like the specific message based off of a generalized server error response. I haven't had a chance to pull this and test it, but initial gut response is... It works, yeah, but can the return error be more specific to the error you display to the user?

2024-05-09 18:40 UTC, paulstonebraker commented on src/pages/MyMove/Profile/DodInfo.jsx
> +          errorMessage = 'This EMPLID is already in use';
Should've provided more details. So this error gets returned in lines 182-184 of service_members.go, I followed the error handling to errors.go `ResponseForVErrors` and `ResponseForError` where it returns that message on line 176 `case *pq.Error`

I did a quick search of the internal app and didn't see much in the way of handling an error more specifically. So... I couldn't find any code to copy, which is why I tagged you 🤣

2024-05-10 17:08 UTC, danieljordan-caci requested changes
Please make sure you're also updating the storybooks.

2024-05-10 17:08 UTC, danieljordan-caci commented on src/components/Customer/Review/ServiceInfoDisplay/ServiceInfoDisplay.jsx
> +  });
Then you wouldn't need to use any hooks in the `ServiceInfoDisplay` component.

2024-05-10 17:08 UTC, danieljordan-caci commented on src/pages/MyMove/Profile/DodInfo.jsx
> +  });
Same thing here - adding an empty array so React knows to only run this once.

2024-05-13 19:56 UTC, paulstonebraker commented on src/components/Customer/Review/ServiceInfoDisplay/ServiceInfoDisplay.jsx
> +  });
Nicely done, thanks. WIll update using the latter shortly

2024-05-13 20:29 UTC, paulstonebraker commented
Converting to draft while I make storybook changes

2024-05-14 15:44 UTC, paulstonebraker commented on src/components/Customer/Review/ServiceInfoDisplay/ServiceInfoDisplay.jsx
> +  });
Implemented all this except for the `Loading` component as we don't seem to use that elsewhere with the feature flags

2024-05-15 19:10 UTC, danieljordan-caci commented
Conflicts

2024-05-15 20:59 UTC, danieljordan-caci requested changes
Thanks for making those changes and updating storybook. 

LGTM.

2024-05-15 20:59 UTC, danieljordan-caci approved these changes

2024-05-16 15:46 UTC, pambecker approved these changes
good to go once you create a PR for the milmove-feature-flags side of things

2024-05-16 15:59 UTC, merged