Int b 20043
transcom/mymove pull request #12736
Opened 2024-05-21 17:08 UTC by loganwc

## [Agility ticket](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A950357&RoomContext=TeamRoom%3A848240&concept=TeamRoom)

## Summary

Blocking SAFETY moves from office users without SAFETY privileges

## How to test
1. Create a safety move
2. Login as an office user with safety privileges
3. Copy the safety move url
4. Login as an office user without safety privileges
5. Try to navigate to safety move with url
6. Do not see the page

2024-05-31 11:59 UTC, pambecker requested changes

2024-05-31 11:59 UTC, pambecker commented on pkg/handlers/ghcapi/move.go
> +			if move.Orders.OrdersType == "SAFETY" && !privileges.HasPrivilege(models.PrivilegeTypeSafety) {
OrdersType is blank for me here

2024-05-31 17:50 UTC, pambecker approved these changes

2024-05-31 17:58 UTC, pambecker approved these changes
Code works as expected.  Good to go once the tests pass

2024-06-06 18:43 UTC, paulstonebraker commented
Is PO okay with the "oops something went wrong screen"? I thought they had requested the "404 can't find the page youre looking for" screen instead

2024-06-06 19:25 UTC, loganwc commented
> Is PO okay with the "oops something went wrong screen"? I thought they had requested the "404 can't find the page youre looking for" screen instead

that's the screen you get if you 404, try to navigate to fake locator and it'll just show the oops something went wrong screen

2024-06-06 19:27 UTC, paulstonebraker commented
> > Is PO okay with the "oops something went wrong screen"? I thought they had requested the "404 can't find the page youre looking for" screen instead
> 
> that's the screen you get if you 404, try to navigate to fake locator and it'll just show the oops something went wrong screen

Yeah I don't have a horse in the race, just thought I remembered them requesting the 404 page.

2024-06-06 19:27 UTC, paulstonebraker approved these changes

2024-06-06 19:31 UTC, pambecker approved these changes

2024-06-07 04:42 UTC, merged