B 18544 int ff sc create safety move
transcom/mymove pull request #12744
Opened 2024-05-21 20:03 UTC by pambecker

## 18544

## Service Counselor can create a Safety Move

This story also has a FF and should go with code checkin for milmove-feature-flag branch

### Setup to Run the Code

You will need to work with the FF FEATURE_FLAG_SAFETY_MOVE.
You will need to have a Service Counselor with safety privileges and one without privileges.

### How to test

1.  Login as a Service Counselor that has Safety Move privileges, make sure the FEATURE_FLAG_SAFETY_MOVE is on.
2. Access the Service Counselor's Customer Search tab, search for a user name that doesn't exist, and click Add Customer.
3. Verify that you see a new question as if this is a Safety Move.
4. Click the Yes radio button and verify that the DoDID is disabled and Okta and CAC questions at the bottom of the page are no longer visible.
5. Fill out the required information and click Save.
6. This should route you to the create order/move page.  Verify that Safety Move is selected and you can save successfully.
7. Run through 2-6 again, but pick No to the Safety Move question and verify that you can type in DoDID and that you see and have to fill out the Okta and CAC questions.
8. Verify that you see a choice of Safety Moves in the Orders type dropdown on the next page.
9. Login with a SC that does not have Safety Move privileges, run through the create new customer again and verify that you do not see the Safety Move question or the Safety Move choice in the Orders type dropdown.
10. Turn the FF off and login with the first user in #1 above and verify that you do not see the Safety Move question on create new user or in the Orders type dropdown.

2024-05-22 13:30 UTC, loganwc requested changes

2024-05-22 14:42 UTC, pambecker commented on src/utils/featureFlags.js
> +export function isSafetyMoveEnabled() {
> You no longer need to add a function like this, the existing function checks for all feature flags

yep, good catch, that was early on, it's not being called anywhere, I will remove it from this file.

2024-05-22 20:57 UTC, pambecker commented on src/utils/featureFlags.js
> +export function isSafetyMoveEnabled() {
Found the issue with the looping, it was occurring only for a user that did not have privileges.  fix is in.  Good catch!

2024-05-23 14:21 UTC, loganwc approved these changes
Great work!

2024-05-23 17:29 UTC, paulstonebraker approved these changes

2024-05-23 18:53 UTC, loganwc approved these changes

2024-05-23 18:53 UTC, merged