Int b 19300
transcom/mymove pull request #12758
Opened 2024-05-22 21:08 UTC by brooklyn-welsh

## [Agility ticket](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-19300)

## Summary

This branch contains 2 big changes:

1. The "Haul Price" item in the "Incentives" section of the final PPM Closeout Review screen will now update to read either "Linehaul Price" or "Shorthaul Price" depending on whether or not the move happens within the same Zip3.
2. This branch also fixed a bug in the pricing where items were always using the *linehaul* pricer for things like gross incentive, domestic area price, etc., even if a shipment would be classified as a shorthaul.

### How to test

1. Create a move that goes to any two zip codes with the same first 3 digits. Where you would normally check "use my new duty location", you can instead put in an address with the same Zip3 (e.g. 90210 -> 90245).
2. Go through the normal process to get to PPM closeout (sign, approve as SC, upload PPM documents).
3. As an SC, access the move through the closeout queue, go to the last "Confirm" screen and verify that you see "shorthaul price" as shown here:
![Screenshot 2024-05-22 at 4 58 23 PM](https://github.com/transcom/mymove/assets/146959895/40af5acf-502e-4c09-afc5-d7f21f8f2eec)

4. If you want to test that linehaul price will show up, find the `actual_pickup_postal_code` and `actual_destination_postal_code` columns for your move in the `ppm_shipments` table. Edit the destination code to "30183".
![Screenshot 2024-05-22 at 5 02 47 PM](https://github.com/transcom/mymove/assets/146959895/9c32142b-8a29-4a4e-bf9c-7bd408e6d1ab)

5. Refresh and continue back to the "Confirm" screen, you should now see that "Linehaul Price" shows up instead, and you should notice a substantial difference in price.

![Screenshot 2024-05-22 at 5 04 21 PM](https://github.com/transcom/mymove/assets/146959895/7aa08c0d-bfb8-4d9d-96ae-0aca5a1c3bd4)

2024-05-23 13:52 UTC, danieljordan-caci requested changes

2024-05-23 18:12 UTC, brooklyn-welsh commented on src/components/Office/PPM/PPMHeaderSummary/HeaderSection.jsx
> +  };
Yep, sorry meant to open this as a draft and not mark as ready at the time. This particular section of code was refactored, but I've written a test file that tests the rest of the code at `HeaderSection.test.jsx`

2024-05-24 13:09 UTC, WeatherfordAaron approved these changes
lgtm 👽

2024-05-24 13:29 UTC, danieljordan-caci commented on .github/workflows/analyze-bundle.yml
Are these changes cool to go to `integrationTesting` @deandreJones?

2024-05-24 14:30 UTC, deandreJones commented on .github/workflows/analyze-bundle.yml
yes- generally - dependabot library updates go straight to main
so someone is bound to get it in there PR if they do it right (pulling in main)

2024-05-24 14:31 UTC, danieljordan-caci approved these changes

2024-05-24 15:31 UTC, merged