B 19897 and b 19898 csr UI and backend int
transcom/mymove pull request #12786
Opened 2024-05-24 19:26 UTC by cameroncaci

##  [B-19898](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A947557) and [B-19897](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A947556)

## Summary

Introduces a standalone “Customer Service Representative” (CSR) role that splits from the existing QAE/CSR. This role is to function just like the previous QAE/CSR role with the exception of no longer having permission to create, update, delete, or mark violations on QAE reports found on the move page.

The frontend ticket [B-19898](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A947557) and backend ticket [B-19897](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A947556) were combined into a single PR so that they are tracked via the same build number and can be tested alongside one another for the PO.

**NOTE** The CSR was intentionally not added to the multi-role user because the CSR role has limited permissions. Multi role has all encompassing, meaning the multi-role user cannot successfully replicate the CSR user experience.

### How to test
**Identify a move**
This can be skipped if you already have a desired move ready
Open officelocal
Log in as a multi-role
Identify a “Move approved” status queue item and copy its locator #

**Create a QAE report**
If you are signed in as multi-role, please sign out at this point
Sign back in as a dedicated QAE (Currently QAE/CSR)
Navigate to the identified move by searching for its locator#
Navigate to the “Quality assurance” tab and you should see the ability to create reports
Create a QAE report
![image](https://github.com/transcom/mymove/assets/136814362/af5bfd99-f741-4d4d-bb18-da6584290a50)
![image](https://github.com/transcom/mymove/assets/136814362/69c2286f-2ebf-4fb8-ba72-d48be722d958)

**Review report as a CSR**
Sign out of the QAE role if you’re still signed in
Open officelocal
Select local sign in
Create a dedicated CSR user
![image](https://github.com/transcom/mymove/assets/136814362/e824d86f-e100-4b30-9f0b-a39902f056ac)

Navigate to the move you made a report on
You should see the ability to view the report, but not create anything
Verify you can successfully view and download the report
![image](https://github.com/transcom/mymove/assets/136814362/714c974e-dc02-415a-a9ed-64000d565b00)

**Request CSR account**
Open officelocal, sign out if you are currently signed in
Select "request account'
Fill out the form and select to request a CSR account
It should submit successfully
Log into adminlocal
Approve the requested CSR account
Attempt to sign into officelocal with said account

2024-05-28 13:48 UTC, danieljordan-caci requested changes
Nice tests, all good stuff. Just have a couple questions & changes! Feel free to bite back.

2024-05-28 13:48 UTC, danieljordan-caci commented on pkg/handlers/authentication/devlocal.go
> +	// QaeCsrOfficeUserType is the Customer Service Representative type of user for an Office user
Copy/paste typo here in your comment. I'm assuming `QaeCsrOfficeUserType` is supposed to be `CustomerServiceRepresentativeOfficeUserType` here

2024-05-28 13:48 UTC, danieljordan-caci commented on pkg/handlers/authentication/devlocal.go
> +		}
What're the chances you can change this to anything other than `Truss`? Why are we even still using that name in the app haha

2024-05-28 13:48 UTC, danieljordan-caci commented on pkg/testdatagen/scenario/shared.go
> +	/* A user with tio role */
Typo in your comment here

2024-05-28 13:48 UTC, danieljordan-caci commented on pkg/testdatagen/scenario/shared.go
> +	csrUUID := uuid.Must(uuid.FromString("72432922-BF2E-45DE-8837-1A458F5D1011"))
How come you're hard coding a uuid here? Would generating a uuid be better?

2024-05-28 13:48 UTC, danieljordan-caci commented on pkg/handlers/authentication/devlocal.go
> +
Would it be possible for you to abbreviate to CSR? Just kind of... Stands out when selecting a user. Everything else is abbreviated.

![Screenshot 2024-05-28 at 8 41 06 AM](https://github.com/transcom/mymove/assets/136510600/91b02282-0a4c-4c09-ab84-7bbf680854b6)

2024-05-28 13:48 UTC, danieljordan-caci commented on src/components/form/OfficeAccountRequestFields/OfficeAccountRequestFields.jsx
> +          />
A little picky, but can you arrange this to be above `Headquarters` and below `Quality Assurance & Customer Support`?
![Screenshot 2024-05-28 at 8 45 27 AM](https://github.com/transcom/mymove/assets/136510600/560d9d67-e066-4067-b1a0-c7a6b549a4f1)

2024-05-28 19:49 UTC, traskowskycaci reviewed
Running into an issue when trying to approve the office user I requested. Logged in as admin:

![image](https://github.com/transcom/mymove/assets/147537467/3bec65b3-7f94-497b-9df2-87792ad8541d)

Hit approve here:
![image](https://github.com/transcom/mymove/assets/147537467/170acb44-86cc-4789-99a2-93d696a9b0dc)

See this:
![image](https://github.com/transcom/mymove/assets/147537467/527a8d30-ebdd-4c8c-a8cd-38f63133c1a6)

Console:
![image](https://github.com/transcom/mymove/assets/147537467/3435e07c-33a2-48c0-9563-1e4668dda772)

Server log:
`2024-05-28T19:47:32.194Z        ERROR   adminapi/requested_office_users.go:284  Error creating okta account     {"git_branch": "B-19888-estimate-price-INT", "git_commit": "b652963472f6d8065fd86867e6d33477c9b17b40", "host": "adminlocal:3000", "milmove_trace_id": "c68719c4-c5f9-4c8f-840c-db401d43a9f9", "session_id": "pICtTk07HQaedbpd8ALCXJuGtHED_sF5YHAk7VKXft8"}
github.com/transcom/mymove/pkg/handlers/adminapi.(*UpdateRequestedOfficeUserHandler).Handle.UpdateRequestedOfficeUserHandler.Handle.func1
        /Users/m.traskowsky_cn/Documents/github/mymove/pkg/handlers/adminapi/requested_office_users.go:284
github.com/transcom/mymove/pkg/handlers.(*Config).AuditableAppContextFromRequestWithErrors.func1
        /Users/m.traskowsky_cn/Documents/github/mymove/pkg/handlers/config.go:145
github.com/transcom/mymove/pkg/appcontext.(*appContext).NewTransaction.func1
        /Users/m.traskowsky_cn/Documents/github/mymove/pkg/appcontext/context.go:67
[POP] 2024/05/28 19:47:32 sql - END Transaction --- (conn=tx-4272483568443215767, tx=4272483568443215767)`

2024-05-28 20:48 UTC, danieljordan-caci commented
> Running into an issue when trying to approve the office user I requested. Logged in as admin:
> 
> ![image](https://private-user-images.githubusercontent.com/147537467/334554925-3bec65b3-7f94-497b-9df2-87792ad8541d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5Mjk0MzEsIm5iZiI6MTcxNjkyOTEzMSwicGF0aCI6Ii8xNDc1Mzc0NjcvMzM0NTU0OTI1LTNiZWM2NWIzLTdmOTQtNDk3Yi05ZGYyLTg3NzkyYWQ4NTQxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOFQyMDQ1MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZDViOTM3NjQwNGIzMmIwOGZhY2IzZTllNWJhYjQ4MWE0YzM4NGEyMzRiYTgzZmVkZjg3NWEzMDA5NTQ4MGI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.q5hmmOksZpyQvhR_zrs8XeDJ9jpPINU32oPWrJq3ex4)
> 
> Hit approve here: ![image](https://private-user-images.githubusercontent.com/147537467/334555094-170acb44-86cc-4789-99a2-93d696a9b0dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5Mjk0MzEsIm5iZiI6MTcxNjkyOTEzMSwicGF0aCI6Ii8xNDc1Mzc0NjcvMzM0NTU1MDk0LTE3MGFjYjQ0LTg2Y2MtNDc4OS05OWEyLTkzZDY5NmE5YjBkYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOFQyMDQ1MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZjViZTc0YmZjMzllNzhlZjk5ODg3ZTJlZTg1ZGQ2NzhiNDVkYzg4OTRiYTIwZTRlM2Y4OTU3MzFkMWExNDkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7YrCt9YtbRemM0CsTAmQsdzU8uT9P2nfPc4sV8NYkKk)
> 
> See this: ![image](https://private-user-images.githubusercontent.com/147537467/334555395-527a8d30-ebdd-4c8c-a8cd-38f63133c1a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5Mjk0MzEsIm5iZiI6MTcxNjkyOTEzMSwicGF0aCI6Ii8xNDc1Mzc0NjcvMzM0NTU1Mzk1LTUyN2E4ZDMwLWViZGQtNGM4Yy1hOGNkLTM4ZjYzMTMzYzFhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOFQyMDQ1MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjNmNjA0YWY1ODNhOTA2MmE0ZjJlMmZkODIyOTg1YTRjYWZlNTUzMDhlZDI3OTlhNWY1NGI1NDc3ZjY4MWNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TUNrBBoPdOmxmqCecBiXR0MacCrSWO19mUZUtIvaDK8)
> 
> Console: ![image](https://private-user-images.githubusercontent.com/147537467/334555681-3435e07c-33a2-48c0-9563-1e4668dda772.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5Mjk0MzEsIm5iZiI6MTcxNjkyOTEzMSwicGF0aCI6Ii8xNDc1Mzc0NjcvMzM0NTU1NjgxLTM0MzVlMDdjLTMzYTItNDhjMC05NTYzLTFlNDY2OGRkYTc3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOFQyMDQ1MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZGRiMjM3Mzc3MjMwYTU0NGE2NzJiZmU0NmMzZWVlMDM1Nzc5NGQ1ZDE2MjEwNDcwZWVkZmFjMmE4ZTBjNTUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.okTLZKVUZWGHJS3RP42cA7LwZlB9Kqpts2kyRPWJLyE)
> 
> Server log: `2024-05-28T19:47:32.194Z ERROR adminapi/requested_office_users.go:284 Error creating okta account {"git_branch": "B-19888-estimate-price-INT", "git_commit": "b652963472f6d8065fd86867e6d33477c9b17b40", "host": "adminlocal:3000", "milmove_trace_id": "c68719c4-c5f9-4c8f-840c-db401d43a9f9", "session_id": "pICtTk07HQaedbpd8ALCXJuGtHED_sF5YHAk7VKXft8"} github.com/transcom/mymove/pkg/handlers/adminapi.(*UpdateRequestedOfficeUserHandler).Handle.UpdateRequestedOfficeUserHandler.Handle.func1 /Users/m.traskowsky_cn/Documents/github/mymove/pkg/handlers/adminapi/requested_office_users.go:284 github.com/transcom/mymove/pkg/handlers.(*Config).AuditableAppContextFromRequestWithErrors.func1 /Users/m.traskowsky_cn/Documents/github/mymove/pkg/handlers/config.go:145 github.com/transcom/mymove/pkg/appcontext.(*appContext).NewTransaction.func1 /Users/m.traskowsky_cn/Documents/github/mymove/pkg/appcontext/context.go:67 [POP] 2024/05/28 19:47:32 sql - END Transaction --- (conn=tx-4272483568443215767, tx=4272483568443215767)`

This error is likely due to the DODID number you're providing already existing in Okta. Quick search in the admin console:
![Screenshot 2024-05-28 at 3 47 42 PM](https://github.com/transcom/mymove/assets/136510600/4535b758-2b20-4ce3-ba91-b2d1b98d72a5)

So the error is likely cause you're trying to create another Okta user with a duplicate DODID but error handling sucks in the admin app, so we don't know why.

2024-05-28 20:52 UTC, traskowskycaci commented
> So the error is likely cause you're trying to create another Okta user with a duplicate DODID but error handling sucks in the admin app, so we don't know why.

Thank you! Retesting now.

2024-05-28 21:15 UTC, traskowskycaci commented on pkg/handlers/authentication/devlocal.go
> +
I wish the capitalization for this list made more sense. Probably out of scope for this story but just something this made me notice!

2024-05-28 21:15 UTC, traskowskycaci approved these changes
Works as described for me! I agree with Daniel's feedback as well.

2024-05-29 16:02 UTC, cameroncaci commented on pkg/handlers/authentication/devlocal.go
> +	// QaeCsrOfficeUserType is the Customer Service Representative type of user for an Office user
resolved

2024-05-29 16:03 UTC, cameroncaci commented on pkg/handlers/authentication/devlocal.go
> +		}
resolved

2024-05-29 16:34 UTC, danieljordan-caci commented on pkg/testdatagen/scenario/shared.go
> +	/* A user with tio role */
You see this one @cameroncaci ?

2024-05-29 16:39 UTC, cameroncaci commented on pkg/testdatagen/scenario/shared.go
> +	/* A user with tio role */
fixed typo

2024-05-29 16:41 UTC, cameroncaci commented on pkg/testdatagen/scenario/shared.go
> +	csrUUID := uuid.Must(uuid.FromString("72432922-BF2E-45DE-8837-1A458F5D1011"))
See `/migrations/app/schema/20240522124339_add_csr_to_roles.up.sql` where the CSR role is created with this UUID. Hard referencing the UUID allows for e2e testing (Or in this case, ensuring that our testdatagen correctly identifies the CSR role primary key)

2024-05-29 16:43 UTC, danieljordan-caci commented on pkg/testdatagen/scenario/shared.go
> +	csrUUID := uuid.Must(uuid.FromString("72432922-BF2E-45DE-8837-1A458F5D1011"))
Thank ya sir

2024-05-29 16:48 UTC, danieljordan-caci approved these changes
LGTM! Thanks for the changes.

2024-05-29 16:57 UTC, cameroncaci commented
flaky test failing

2024-05-29 16:57 UTC, merged