B 19827 int
transcom/mymove pull request #12896
Opened 2024-05-31 17:57 UTC by deandreJones

## [B-19827](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A946538)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the admin app-
2. go to office users
3. see task invoicing officer instead of transportation invoicing officer
4. create a TIO - see that you are able to login successfully

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

![image](https://github.com/transcom/mymove/assets/136509766/d934a753-787e-422b-8dff-572e6d35aed5)
![image](https://github.com/transcom/mymove/assets/136509766/e90d598c-693f-4c67-9614-48a0b661d3cd)
![image](https://github.com/transcom/mymove/assets/136509766/e9438bcc-8876-4a33-bbeb-ba9a86caad1e)

2024-05-31 21:33 UTC, TevinAdams approved these changes
Rename looks good. Went through admin and office and did not see any reference to Transportation Invoicing Officer. Was able to create a Task Invoicing Officer, Request the Task Invoicing role, and accept Office request with Task invoicing role. Was able to log in as a TIO and perform functions as usual.

2024-06-03 15:53 UTC, cameroncaci requested changes
"Transportation invoicing" is still present on the following lines:
`src/pages/Admin/RequestedOfficeUsers/RequestedOfficeUserEdit.jsx:51`
`src/pages/Admin/OfficeUsers/OfficeUserEdit.jsx:50`
`src/pages/Admin/OfficeUsers/OfficeUserCreate.jsx:33`

2024-06-03 15:57 UTC, deandreJones commented
> "Transportation invoicing" is still present on the following lines: `src/pages/Admin/RequestedOfficeUsers/RequestedOfficeUserEdit.jsx:51` `src/pages/Admin/OfficeUsers/OfficeUserEdit.jsx:50` `src/pages/Admin/OfficeUsers/OfficeUserCreate.jsx:33`

hmm.. must hav been from a new Pr

2024-06-03 18:27 UTC, deandreJones commented
> > "Transportation invoicing" is still present on the following lines: `src/pages/Admin/RequestedOfficeUsers/RequestedOfficeUserEdit.jsx:51` `src/pages/Admin/OfficeUsers/OfficeUserEdit.jsx:50` `src/pages/Admin/OfficeUsers/OfficeUserCreate.jsx:33`
> 
> hmm.. must hav been from a new Pr

ok - should be resolved now
@cameroncaci

2024-06-03 21:39 UTC, traskowskycaci approved these changes

2024-06-03 21:39 UTC, traskowskycaci commented on .circleci/config.yml
Do we want/need to update the cached yarn.lock file?

2024-06-04 12:48 UTC, cameroncaci approved these changes
Looks good, AC is met!

2024-06-04 13:15 UTC, deandreJones commented on .circleci/config.yml
actually no- I was trying something when the circle build was failing something that didnt exist on my local- turned out it was integration and not main.. 
but upping the version doesn't hurt anything- but gets us a fresh cache file-- with the issues we ran into last week - not a bad idea to get fresh cache

2024-06-04 13:16 UTC, merged