B 19825 rename qaecsr to qae int
transcom/mymove pull request #12920
Opened 2024-06-03 19:44 UTC by cameroncaci

## [B-19825](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A946536&RoomContext=TeamRoom%3A808731&concept=TeamRoom)

## Summary

Renames code-based and ui-base mentioned of QAE/CSR to just QAE (Acronym spelled out respectively). I left a few QAE/CSR combinations because they were respective of both QAE and CSR both being part of the commented code, or move search.

## Screenshots
![image](https://github.com/transcom/mymove/assets/136814362/0fb9cc6b-b15d-4e8b-92ee-5c89cb81a2d4)
![image](https://github.com/transcom/mymove/assets/136814362/ab6172d2-6a79-4629-9bd5-c1120a865471)
![image](https://github.com/transcom/mymove/assets/136814362/7d38aa52-ee7b-41ff-9baf-7597eeed5426)

2024-06-03 21:54 UTC, traskowskycaci requested changes
One failing test
![image](https://github.com/transcom/mymove/assets/147537467/e7f834cd-82ff-461d-8fbc-c21962506e46)

2024-06-04 13:18 UTC, cameroncaci commented
> One failing test ![image](https://private-user-images.githubusercontent.com/147537467/336241152-e7f834cd-82ff-461d-8fbc-c21962506e46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1MDU4MDAsIm5iZiI6MTcxNzUwNTUwMCwicGF0aCI6Ii8xNDc1Mzc0NjcvMzM2MjQxMTUyLWU3ZjgzNGNkLTgyZmYtNDYxZC04ZmJjLWMyMTk2MjUwNmU0Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNFQxMjUxNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NTJkNjUwMTZhYTI4MjBjZDFlYzBlMWI0MzkwZTk1NWZjMmYxOTY2ZDQzODFiZjNmY2YzMGYwMGFiNDY2NmY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.B3gltfVeUqjoPpHHDTS6TusfOo5RiRuWYifJCBl-Vo0)

Resolved. Appears to have occurred during merge conflict resolution with int. Issue not preset on the main branch.

2024-06-04 16:17 UTC, traskowskycaci commented on pkg/handlers/authentication/auth_test.go
> +	qaeCsrOfficeUser := factory.BuildOfficeUserWithRoles(suite.DB(), nil, []roles.RoleType{roles.RoleTypeQae})
Can we either rename to just `qaeOfficeUser` or pass in `roles.RoleTypeCustomerServiceRepresentative` as well as the `roles.RoleTypeQae`?

2024-06-04 16:35 UTC, traskowskycaci requested changes
Alright left a bunch of comments, apologies if that's confusing.

I searched for qaeCsr in your branch and of the references I found, I think most of them we can either rename as you changed the role type to just QAE, or alternatively, we can also include the new CSR role to make the qaeCsr combination accurate.

Most things I called out were where I saw a mismatch of the name or comment saying QAE CSR but it was now just QAE

2024-06-04 16:35 UTC, traskowskycaci commented on pkg/handlers/authentication/auth_test.go
> +	qaeCsrOfficeUser := factory.BuildOfficeUserWithRoles(suite.DB(), nil, []roles.RoleType{roles.RoleTypeQae})
Can we either rename to just qaeOfficeUser or pass in roles.RoleTypeCustomerServiceRepresentative as well as the roles.RoleTypeQae?

2024-06-04 16:35 UTC, traskowskycaci commented on pkg/handlers/authentication/permissions.go
>  var QAECSR = RolePermissions{
Can QAECSR be renamed to QAE?

2024-06-04 16:35 UTC, traskowskycaci commented on pkg/testdatagen/scenario/e2ebasic.go
>  func userWithQAECSRRole(appCtx appcontext.AppContext, userID uuid.UUID, email string) {
Rename userWithQAECSRRole to userWithQAERole

2024-06-04 16:35 UTC, traskowskycaci commented on pkg/testdatagen/scenario/e2ebasic.go
>  	qaecsrRole := roles.Role{}
qaecsrRole can be qaeRole

2024-06-04 16:35 UTC, traskowskycaci commented on pkg/testdatagen/scenario/e2ebasic.go
>  		log.Panic(fmt.Errorf("failed to find RoleTypeQAECSR in the DB: %w", err))
failed to find RoleTypeQAECSR -> failed to find RoleTypeQAE

2024-06-04 16:35 UTC, traskowskycaci commented on pkg/testdatagen/scenario/e2ebasic.go
Most qaeCrs names/variables in this entire file can become just qae since RoleTypeQAECSR became RoleTypeQae

2024-06-04 16:35 UTC, traskowskycaci commented on pkg/testdatagen/scenario/shared.go
Most qaeCrs names/variables in this entire file can become just qae since RoleTypeQAECSR became RoleTypeQae

2024-06-04 16:35 UTC, traskowskycaci commented on pkg/testdatagen/scenario/subscenarios.go
Most qaeCsr names/variables in this entire file can become just qae since RoleTypeQAECSR became RoleTypeQae

2024-06-04 16:35 UTC, traskowskycaci commented on playwright/tests/utils/office/officeTest.js
>    async signInAsNewQAECSRUser() {
signInAsNewQAECSRUser should be signInAsNewQAEUser since it's just the QAEOfficeUserType, then the tests that currently call the signInAsNewQAECSRUser should be updated to just QAE

2024-06-05 12:35 UTC, cameroncaci commented on pkg/handlers/authentication/auth_test.go
> +	qaeCsrOfficeUser := factory.BuildOfficeUserWithRoles(suite.DB(), nil, []roles.RoleType{roles.RoleTypeQae})
This isn't like this on main.. Something went wrong with this merge real bad

2024-06-05 12:35 UTC, cameroncaci commented
Restarting branch due to too many discrepancies with the main version

2024-06-05 12:35 UTC, closed without merging