B 19825 rename qaecsr to qae int
transcom/mymove pull request #12950
Opened 2024-06-05 12:51 UTC by cameroncaci

## [B-19825](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A946536&RoomContext=TeamRoom%3A808731&concept=TeamRoom)

## Preivous INT PR
This is a new PR due to the last integration branch having too many discrepancies with the main version of the branch, despite it being brought over via a merge instead of cherry-picking. Old pr https://github.com/transcom/mymove/pull/12920

## Summary

Renames code-based and ui-base mentioned of QAE/CSR to just QAE (Acronym spelled out respectively). I left a few QAE/CSR combinations because they were respective of both QAE and CSR both being part of the commented code, or move search.

## Screenshots
![image](https://github.com/transcom/mymove/assets/136814362/0fb9cc6b-b15d-4e8b-92ee-5c89cb81a2d4)
![image](https://github.com/transcom/mymove/assets/136814362/ab6172d2-6a79-4629-9bd5-c1120a865471)
![image](https://github.com/transcom/mymove/assets/136814362/7d38aa52-ee7b-41ff-9baf-7597eeed5426)

2024-06-06 14:58 UTC, TevinAdams commented
@cameroncaci  I still see qaecsr in the same name. For example "qaeCsrSearchForAndNavigateToMove()" inplaywright/tests/office/qaecsr/csrFlows.spec.js and "qaeCSRRoutes" insrc/constants/routes.js.  "QAECSRMoveSearch" insrc/pages/Office/QAECSRMoveSearch/QAECSRMoveSearch.test.jsx. I see that there are still QAECSR combination in names, texts and such. I know it may be more work changing those but should we go ahead and do that to minimize any confusion?

2024-06-06 16:03 UTC, traskowskycaci requested changes
Functionality looks good!

Left a comment on one file asking if you think we should break up qaeCsrSearchForAndNavigateToMove() into two functions - I kinda think so but let me know if you disagree.

The other instances of qaeCsr I see from searching, like qaeCSRRoutes, I'm fine with since I saw a comment from you saying QAEs and CSRs share routing but not permissions. Looks mostly good!

2024-06-06 16:31 UTC, cameroncaci commented on playwright/tests/utils/office/officeTest.js
I split this func in half with the latest commit, it makes sense to go ahead and separate this one. Resolved

2024-06-06 16:36 UTC, cameroncaci commented
> @cameroncaci I still see qaecsr in the same name. For example "qaeCsrSearchForAndNavigateToMove()" inplaywright/tests/office/qaecsr/csrFlows.spec.js and "qaeCSRRoutes" insrc/constants/routes.js. "QAECSRMoveSearch" insrc/pages/Office/QAECSRMoveSearch/QAECSRMoveSearch.test.jsx. I see that there are still QAECSR combination in names, texts and such. I know it may be more work changing those but should we go ahead and do that to minimize any confusion?

Split the playwright funcs in half, requesting re-review

2024-06-06 16:59 UTC, cameroncaci commented
Flaky tests failing

2024-06-06 17:42 UTC, traskowskycaci approved these changes
Looks SO nice! :rocket:

2024-06-10 14:08 UTC, danieljordan-caci approved these changes
Couldn't find anything that jumped out of me. Ran through flows of creating a QAE user as well as CSR and all seems to be working fine. LGTM!

2024-06-10 14:09 UTC, deandreJones approved these changes

2024-06-10 14:46 UTC, merged