B 19894 too queue moves int
transcom/mymove pull request #13005
Opened 2024-06-10 18:38 UTC by traskowskycaci

## [Agility ticket](tbd)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-06-11 21:19 UTC, traskowskycaci commented
Flaky test failures, functionality can still be reviewed

2024-06-11 21:49 UTC, traskowskycaci commented
Will be looking into the failing integration_tests_my tomorrow, looks fun
![image](https://github.com/transcom/mymove/assets/147537467/fd69259b-31cb-4c77-a3fd-e7922ef68330)

2024-06-12 14:09 UTC, danieljordan-caci requested changes
Nit picky. Sorryyyyyy

2024-06-12 14:28 UTC, loganwc approved these changes
looks good, approved but I also like Daniels suggested changes 🙌

2024-06-12 14:35 UTC, cameroncaci requested changes
Functions great, have some remarks for review below
![image](https://github.com/transcom/mymove/assets/136814362/ffdee01e-72dc-4fb4-8e3a-0b82d14b62e5)

2024-06-12 14:35 UTC, cameroncaci commented on pkg/handlers/ghcapi/queues.go
> +			}
Can you adjust this comment to remove specifically calling out a role, as this applies to GetMovesQueue handler as a whole rather than role-specific logic. Could this also be documented as default behavior per `swagger-def` docs on the endpoint?

2024-06-12 14:35 UTC, cameroncaci commented on swagger-def/ghc.yaml
> -              - APPROVED
Why remove this enum?

2024-06-12 14:44 UTC, traskowskycaci commented on swagger-def/ghc.yaml
> -              - APPROVED
I found it unnecessary since we are filtering in queues.go, but I could be persuaded to put it back in. What do you think?

2024-06-12 14:46 UTC, traskowskycaci commented on pkg/handlers/ghcapi/queues.go
> +			}
I can definitely remove the TOO reference in the comment here.

Just a note that there are comments throughout the rest of the file that call out roles specifically, should I remove those?
![image](https://github.com/transcom/mymove/assets/147537467/346f380e-4081-4228-961e-9e27cfc40259)
![image](https://github.com/transcom/mymove/assets/147537467/318fffd3-3bcb-4794-9e85-1a779f47a885)
![image](https://github.com/transcom/mymove/assets/147537467/e02c3c57-4ff2-4df3-9373-5782ec20c559)

2024-06-12 14:46 UTC, traskowskycaci commented on src/constants/queues.js
>  ];
Fix will be coming in from main! 
![image](https://github.com/transcom/mymove/assets/147537467/9bedae3c-f1a8-4e2f-8419-b94fa50197a8)

2024-06-12 14:54 UTC, traskowskycaci commented on src/constants/queues.js
>  ];
Fix is in for this!

2024-06-12 15:08 UTC, danieljordan-caci commented on swagger-def/ghc.yaml
> -              - APPROVED
I think I'm in agreement with Maria - if this enum isn't being used in the backend, then why keep it in swagger?

2024-06-12 15:09 UTC, danieljordan-caci approved these changes
Ran through and tried to break it - seems all in working order. LGTM!

2024-06-12 15:56 UTC, cameroncaci commented on swagger-def/ghc.yaml
> -              - APPROVED
This is to enforce best API practices -> Currently this would allow any status to get passed in as a string. By introducing an enum here, we enforce that the options of status that can be passed in through the API **_MUST_** be a status that we expect. Aka, it'd be pointless to allow them to request a status that doesn't exist, additionally this allows API documentation to list which statuses will actually work. Good for documentation and good for validation.

It's sort of like the equivalent of separation of duties. UI validates a form, API validates a payload.

2024-06-12 15:57 UTC, cameroncaci commented on pkg/handlers/ghcapi/queues.go
> +			}
I like the idea of keeping in that "This handler is primarily utilized by the TOO or HQ users", but since the handler isn't limited to them if you wouldn't mind, I think it'd be good to remove "For specific role" from the comments

2024-06-12 15:59 UTC, cameroncaci commented on swagger-def/ghc.yaml
> -              - APPROVED
Swagger will automatically handle the validation if the string passed in is not of the expected enum
![image](https://github.com/transcom/mymove/assets/136814362/933b4946-3fa2-4e4a-ab9d-0235730abf4b)

2024-06-12 16:16 UTC, cameroncaci commented on pkg/handlers/ghcapi/queues.go
> +			}
Maria clarified this endpoint has explicit logic to fail for any office user that is not the TOO. Rescinding remarks here

2024-06-12 16:49 UTC, traskowskycaci commented on swagger-def/ghc.yaml
> -              - APPROVED
Added that back in @cameroncaci 
![image](https://github.com/transcom/mymove/assets/147537467/84cbe168-c193-4671-a66c-4400435e89a0)

2024-06-12 16:55 UTC, deandreJones approved these changes

2024-06-12 17:01 UTC, cameroncaci approved these changes

2024-06-12 17:20 UTC, merged