B 19890 expand tac lookup int
transcom/mymove pull request #13003
Opened 2024-06-10 12:42 UTC by cameroncaci

## [B-19890](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A947549)

## Summary

Introduces TGET service objects which are now in use inside of the EDI 858 generator as well as a dedicated GHC (Office) endpoint to fetch LOAs

### How to test

1. Open officelocal and log in
2. Navigate to GHC swagger UI/linesOfAccounting/requestLineOfAccounting at http://officelocal:3000/swagger-ui/ghc.html#/linesOfAccounting/requestLineOfAccounting
3. Perform testing scenarios

<details>
<summary>Test a 200</summary>

Payload
```
{
  "serviceMemberAffiliation": "ARMY",
  "ordersIssueDate": "2014-01-01",
  "tacCode": "E12A"
}
```
Response
```
{
  "createdAt": "2023-08-03T19:17:10.050Z",
  "id": "06254fc3-b763-484c-b555-42855d1ad5cd",
  "loaAlltSnID": "123A",
  "loaBafID": "1234",
  "loaBdgtAcntClsNm": "000000",
  "loaBgFyTx": 2006,
  "loaBgnDt": "2005-10-01",
  "loaDocID": "HHG12345678900",
  "loaDptID": "1 ",
  "loaDscTx": "PERSONAL PROPERTY - PARANORMAL ACTIVITY DIVISION (OTHER)",
  "loaEndDt": "2015-10-01",
  "loaEndFyTx": 2016,
  "loaHsGdsCd": "HT",
  "loaInstlAcntgActID": "12345",
  "loaObjClsID": "22NL",
  "loaOpAgncyID": "1A",
  "loaPgmElmntID": "00000000",
  "loaStatCd": "U",
  "loaSysId": "10003",
  "loaTrnsnID": "B1",
  "loaTrsySfxTx": "0000",
  "orgGrpDfasCd": "ZZ",
  "updatedAt": "2023-08-03T19:17:38.776Z"
}
```
</details>

<details>
<summary>Test a 400</summary>

Payload
```
{
  "serviceMemberAffiliation": "ARMY",
  "ordersIssueDate": "2023",
  "tacCode": "F8J1"
}
```
Response
```
response
{
  "title": "Bad Request",
  "instance": "5e12a0b3-12e3-40b8-84c9-e216d45bb1ee",
  "detail": "parsing body body from \"\" failed, because parsing time \"2023\" as \"2006-01-02\": cannot parse \"\" as \"-\""
}
```
</details>

<details>
<summary>Test a 401</summary>

> [!IMPORTANT]
> Sign out of officelocal, then refresh swagger-ui, then try using the endpoint
response

Payload
```
{
  "serviceMemberAffiliation": "ARMY",
  "ordersIssueDate": "2023",
  "tacCode": "F8J1"
}
```
Response
```
response
{
Unauthorized
}
```
</details>

<details>
<summary>Test a 403</summary>

> [!IMPORTANT]
> Sign out of officelocal, do not refresh swagger-ui, then try using the endpoint
Response

Payload
```
{
  "serviceMemberAffiliation": "ARMY",
  "ordersIssueDate": "2023",
  "tacCode": "F8J1"
}
```
Response
```
response
{
Forbidden - CSRF token not found in request
}
```
</details>

<details>
<summary>Test a 404</summary>

Payload
```
{
  "serviceMemberAffiliation": "ARMY",
  "ordersIssueDate": "2023-01-01",
  "tacCode": "F8J1"
}
```
Response
```
response
{
404
}
```
</details>

<details>
<summary>Test a 422</summary>

Payload
```
{
  "serviceMemberAffiliation": "LEGGY",
  "ordersIssueDate": "2023-01-01",
  "tacCode": "F8J1"
}
```
Response
```
response
{
{
  "title": "Validation Error",
  "instance": "8e1125e8-a0b4-40e3-a017-dc6c9bdad72f",
  "detail": "serviceMemberAffiliation in body should be one of [ARMY NAVY MARINES AIR_FORCE COAST_GUARD SPACE_FORCE OTHER]"
}
}
```
</details>

2024-06-10 12:58 UTC, cameroncaci commented
flaky tests

2024-06-10 14:58 UTC, danieljordan-caci requested changes
Few questions, few changes - take a gander.

2024-06-10 14:58 UTC, danieljordan-caci commented on pkg/handlers/ghcapi/lines_of_accounting.go
> +			}
Can you also log the error like you're doing in the `nil` check above?

`appCtx.Logger().Error(err.Error())`

2024-06-10 14:58 UTC, danieljordan-caci commented on pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
> +		// loaDscTx := factory.MakeRandomString(100)
any reason why this is commented out?

2024-06-10 14:58 UTC, danieljordan-caci commented on pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
> +		//
can you clean up these comments plz?

2024-06-10 14:58 UTC, danieljordan-caci commented on pkg/services/line_of_accounting/line_of_accounting_fetcher.go
> +	}
Any particular reason you're returning an empty slice instead of `nil` here?

2024-06-10 14:58 UTC, danieljordan-caci commented on pkg/services/transportation_accounting_code/transportation_accounting_code_fetcher.go
> +			All(&tacs)
You can simplify this since the only difference is adding one query:
```
	query := appCtx.DB().Q().
		EagerPreload("LineOfAccounting").
		Join("lines_of_accounting loa", "loa.loa_sys_id = transportation_accounting_codes.loa_sys_id").
		Where("transportation_accounting_codes.tac = ?", tacCode).
		Where("? BETWEEN transportation_accounting_codes.trnsprtn_acnt_bgn_dt AND transportation_accounting_codes.trnsprtn_acnt_end_dt", ordersIssueDate).
		Where("? BETWEEN loa.loa_bgn_dt AND loa.loa_end_dt", ordersIssueDate).
		Where("transportation_accounting_codes.tac_fn_bl_mod_cd != 'P'")

	if serviceMemberAffiliation != models.AffiliationCOASTGUARD {
		query = query.Where("loa.loa_hs_gds_cd != ?", models.LineOfAccountingHouseholdGoodsCodeNTS)
	}

	err = query.All(&tacs)
```

2024-06-10 14:58 UTC, danieljordan-caci commented on pkg/services/transportation_accounting_code/transportation_accounting_code_fetcher.go
> +	}
Same thing here - would returning `nil` be better since we have an error?

2024-06-10 14:58 UTC, danieljordan-caci commented on swagger-def/ghc.yaml
> +      summary: "Fetch line of accounting"
Should this be `lines` instead of `line`? Looking at the endpoint `/lines-of-account` is the only reason I ask.

2024-06-10 14:58 UTC, danieljordan-caci commented on swagger-def/ghc.yaml
> +          $ref: '#/responses/ServerError'
Are you using all of these responses? In the handler I can only see:
`400` (bad request)
`404`
`500`
`200`

2024-06-11 16:15 UTC, cameroncaci commented on swagger-def/ghc.yaml
> +          $ref: '#/responses/ServerError'
`401`, `403`, and `500` are all managed by the server and swagger itself. Eg, CSRF or permissions based issues. `422` is a validation error triggered as part of the ServiceMemberAffiliation swagger rank validation

Triggered via payload
```
{
  "serviceMemberAffiliation": "LEGGY",
  "ordersIssueDate": "2023-01-01",
  "tacCode": "F8J1"
}
```

2024-06-11 16:16 UTC, cameroncaci commented on swagger-def/ghc.yaml
> +      summary: "Fetch line of accounting"
API pathing should be plural

2024-06-11 16:18 UTC, danieljordan-caci commented on swagger-def/ghc.yaml
> +          $ref: '#/responses/ServerError'
Gotcha. Makes sense. I'll resolve the convo. Thanks for explaining!

2024-06-11 16:19 UTC, cameroncaci commented on pkg/services/line_of_accounting/line_of_accounting_fetcher.go
> +	}
To return empty rather than nil, as the func is allowed to return slices of 0 and is not a pointer

2024-06-11 16:19 UTC, TevinAdams commented
Question for 19890, when testing for a 200 with payload similar to whats below. The tacCode has to match a tacCode has to match a records tac in the Transportation_accounting_codes table right? Then the ordersIssueDate has to match a issue_date of a record in orders and the affiliation type? The tac finds the loa by the loa_id on the tac? If all of that is correct then it returns the loa? Am I understanding that correctly? Whenever I test i keep getting Unable to find any lines of accounting based on the provided parameters. Maybe I am doing something wrong.
{
  "serviceMemberAffiliation": "ARMY", // Match Orders affiliation?
  "ordersIssueDate": "2014-01-01", // Match orders issue Date?
  "tacCode": "E12A" // Matches a TAC which has a loa_id that links it to a loa?
}

2024-06-11 16:19 UTC, cameroncaci commented on pkg/services/transportation_accounting_code/transportation_accounting_code_fetcher.go
> +	}
This is to return empty rather than nil, as the func is allowed to return slices of 0 and is not a pointer

2024-06-11 16:24 UTC, cameroncaci commented on pkg/services/transportation_accounting_code/transportation_accounting_code_fetcher.go
> +			All(&tacs)
Simplified on main branch, bringing it over now

2024-06-11 16:29 UTC, cameroncaci commented on pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
> +		//
Cleaned up on main, bringing over now

2024-06-11 16:29 UTC, cameroncaci commented on pkg/services/invoice/ghc_payment_request_invoice_generator_test.go
> +		// loaDscTx := factory.MakeRandomString(100)
Removed comment on main, pulling over now

2024-06-11 16:30 UTC, cameroncaci commented on pkg/handlers/ghcapi/lines_of_accounting.go
> +			}
Adjusted on main, bringing over now

2024-06-11 16:44 UTC, cameroncaci commented
> Question for 19890, when testing for a 200 with payload similar to whats below. The tacCode has to match a tacCode has to match a records tac in the Transportation_accounting_codes table right? Then the ordersIssueDate has to match a issue_date of a record in orders and the affiliation type? The tac finds the loa by the loa_id on the tac? If all of that is correct then it returns the loa? Am I understanding that correctly? Whenever I test i keep getting Unable to find any lines of accounting based on the provided parameters. Maybe I am doing something wrong.
> 
> ```
> {
>   "serviceMemberAffiliation": "ARMY", // Match Orders affiliation?
>   "ordersIssueDate": "2014-01-01", // Match orders issue Date?
>   "tacCode": "E12A" // Matches a TAC which has a loa_id that links it to a loa?
> }
> ```

Hm, maybe the seed data is generated randomly and is why that isn't quite working? It's what satisfied the condition on my end.

Here is a simple summary on the conditions:
- TAC has a LoaSysID value present that can be looked up inside the line of accounting table. The LOA table should have a row with a LoaSysID value matching that of the TAC
- The service member affiliation doesn't actually matter too much for this testing, just that coast guard members don't have the HHG NTS code "HS" filtered out
- The "ordersIssueDate" is only utilized in the following:
  - The ordersIssueDate must fall BETWEEN the TAC begin date and TAC end date
  - The ordersIssueDate must ALSO fall BETWEEN the LOA begin date and LOA end date
  - This ensures that the TAC and LOA is "valid" for the provided ordersIssueDate. The TAC and LOA begin/end dates are the date ranges in which they are "valid"

2024-06-11 16:49 UTC, cameroncaci commented
Flaky test failures

2024-06-11 19:02 UTC, danieljordan-caci approved these changes
Went through your test cases and all seems to be working as intended. LGTM!

2024-06-12 14:35 UTC, TevinAdams approved these changes

2024-06-12 14:40 UTC, traskowskycaci reviewed
Looks so, so good. I love the way this is done!

Couple overall questions for ya.

1. On the UI, I believe they want to see the full LOA string concatenated together. Should that be the responsibility of the UI to build that up? Do we want to store that anywhere/include it in the response?

2. I believe you're handling these already, but just double checking - are we explicitly checking for every aspect of the criteria for invalid LOA here? We need to store two booleans in the DB to send to Advana, one for an invalid TAC for a LOA, and one for an invalid HHG program code for a LOA. We do still have 19891 to do some of that work as well, just wondering if we want to include those bools in the endpoint as well?

`Criteria for invalid LOA:`
- No HHG Program Code
- No match to orders date and LOA eff date range (HHG)
- No match to orders date and current date (NTS)
- Missing any element per attachment in feature (DFAS elements)
- No LOA record found (LOA system ID key), or nothing returned based on existing logic (check logic for application of LOA to an EDI 858 for payment request transmission)

2024-06-12 15:49 UTC, cameroncaci commented
> Looks so, so good. I love the way this is done!
> 
> Couple overall questions for ya.
> 
> 1. On the UI, I believe they want to see the full LOA string concatenated together. Should that be the responsibility of the UI to build that up? Do we want to store that anywhere/include it in the response?
> 2. I believe you're handling these already, but just double checking - are we explicitly checking for every aspect of the criteria for invalid LOA here? We need to store two booleans in the DB to send to Advana, one for an invalid TAC for a LOA, and one for an invalid HHG program code for a LOA. We do still have 19891 to do some of that work as well, just wondering if we want to include those bools in the endpoint as well?
> 
> `Criteria for invalid LOA:`
> 
> * No HHG Program Code
> * No match to orders date and LOA eff date range (HHG)
> * No match to orders date and current date (NTS)
> * Missing any element per attachment in feature (DFAS elements)
> * No LOA record found (LOA system ID key), or nothing returned based on existing logic (check logic for application of LOA to an EDI 858 for payment request transmission)

1. This should be the responsibility of the UI in my opinion, I feel like the API should handle the model payloads and the UI how it should display
2. I left all that for 19891, I don't know if we want the UI to display whether or not it is "valid", just whether or not it is found. Soft warning if not found, display the concatenated long line of accounting if it is found. Thoughts?

2024-06-12 15:52 UTC, traskowskycaci commented
> 1. This should be the responsibility of the UI in my opinion, I feel like the API should handle the model payloads and the UI how it should display
> 2. I left all that for 19891, I don't know if we want the UI to display whether or not it is "valid", just whether or not it is found. Soft warning if not found, display the concatenated long line of accounting if it is found. Thoughts?

Both sound good to me. I do think they want to see if it's invalid and that's where the soft warning would come in. Good with leaving that for 19891!

2024-06-12 15:52 UTC, traskowskycaci approved these changes

2024-06-12 15:58 UTC, merged