B-19726-INT At EMPLID to SC Customer create
transcom/mymove pull request #13035
Opened 2024-06-12 13:19 UTC by paulstonebraker

## [Agility ticket](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-19726)

## Summary

Part of the effort to have USCG EMPLID accessible. Office users now must enter an EMPLID for USCG customers. This requirement is disabled for safety moves.

### How to test

1. Access the office app as a SC with safety move privileges
2. Create a new customer
3. Select Coast Guard as the branch and confirm the EMPLID appears
4. try different combinations of safety move/coast guard and confirm the only time the emplid is required is when its NOT a safety move and branch IS coast guard
5. try and break it

2024-06-13 19:31 UTC, danieljordan-caci requested changes
I know you didn't want me, BUT I'M HERE. Some changes, plz.

2024-06-13 19:31 UTC, danieljordan-caci commented on src/pages/Office/CustomerOnboarding/CreateCustomerForm.jsx
> +    emplid: isEmplidRequired ? Yup.string().required('Required') : Yup.string().notRequired(),
Right now I can enter letters and do not get an error message. Since EMPLID is similar to DODID and cannot contain letters, may you please update this to keep those pesky things out of there?

2024-06-13 19:31 UTC, danieljordan-caci commented on src/pages/Office/CustomerOnboarding/CreateCustomerForm.jsx
> +    emplid: isEmplidRequired ? Yup.string().required('Required') : Yup.string().notRequired(),
![Screenshot 2024-06-13 at 2 24 03 PM](https://github.com/transcom/mymove/assets/136510600/9d3ee634-1e36-4029-9635-3467a08fe606)

2024-06-13 19:31 UTC, danieljordan-caci commented on src/pages/Office/CustomerOnboarding/CreateCustomerForm.jsx
> +    emplid: isEmplidRequired ? Yup.string().required('Required') : Yup.string().notRequired(),
Also, while I'm thinking about this... Is this a required field or can it be optional like DODID?

2024-06-13 19:31 UTC, danieljordan-caci commented on src/pages/Office/CustomerOnboarding/CreateCustomerForm.jsx
>                    // clear out DoDID and OKTA fields
update comment plz since you're updating functionality

2024-06-13 19:31 UTC, danieljordan-caci commented on src/pages/Office/CustomerOnboarding/CreateCustomerForm.jsx
> +                if (e.target.value === 'COAST_GUARD') {
Instead of hard slapping the string in here, can you use a constants file? I just discovered `departmentIndicators.js` that would be handy.

```
if (e.target.value === departmentIndicators.COAST_GUARD) {
```

2024-06-13 19:31 UTC, danieljordan-caci commented on src/pages/Office/CustomerOnboarding/CreateCustomerForm.jsx
> +                    )}
Can you add a test in `CreateCustomerForm.test.jsx` that tests this being shown?

2024-06-14 15:51 UTC, pambecker commented on pkg/handlers/ghcapi/customer.go
> +					return smErr
Good catch, but while your fixing it, I think the 'err' on line 242 should be 'smErr' too

2024-06-14 15:51 UTC, pambecker commented on src/pages/Office/CustomerOnboarding/CreateCustomerForm.jsx
> +                        required
I don't think you want to put the required here, it's going to make it always required at this point (don't want that for Safety move), probably need to do something similar to okta and cac above on line 168

![image](https://github.com/transcom/mymove/assets/150711493/5c2928a5-3989-43f5-800f-015e17d0821e)

2024-06-14 16:01 UTC, pambecker commented on src/pages/Office/CustomerOnboarding/CreateCustomerForm.jsx
> +    emplid: isEmplidRequired ? Yup.string().required('Required') : Yup.string().notRequired(),
Good catch Daniel, we are working on asking the PO now.  And then based on that outcome, just want to leave a note here, that if the EMPLID does become optional for the SC, we should also add the 'Optional' indicator to the screen.

2024-06-18 19:35 UTC, paulstonebraker commented
Moving to draft to implement optional for EMPLID after discussion with PO

2024-07-03 20:53 UTC, paulstonebraker commented on src/pages/Office/CustomerOnboarding/CreateCustomerForm.jsx
> +    emplid: isEmplidRequired ? Yup.string().required('Required') : Yup.string().notRequired(),
Error message updated and yes, after you inquired @danieljordan-caci we checked with PO and determined it should be optional

2024-07-03 20:53 UTC, paulstonebraker commented on src/pages/Office/CustomerOnboarding/CreateCustomerForm.jsx
>                    // clear out DoDID and OKTA fields
Updated

2024-07-03 20:53 UTC, paulstonebraker commented on src/pages/Office/CustomerOnboarding/CreateCustomerForm.jsx
> +                if (e.target.value === 'COAST_GUARD') {
Updated thanks

2024-07-03 20:53 UTC, paulstonebraker commented on src/pages/Office/CustomerOnboarding/CreateCustomerForm.jsx
> +                    )}
Updated

2024-07-03 20:53 UTC, paulstonebraker commented on pkg/handlers/ghcapi/customer.go
> +					return smErr
Updated

2024-07-03 20:54 UTC, paulstonebraker commented on src/pages/Office/CustomerOnboarding/CreateCustomerForm.jsx
> +                        required
Updated thanks

2024-07-05 16:27 UTC, pambecker commented on src/pages/Office/CustomerOnboarding/CreateCustomerForm.jsx
> -  const [isSafetyMoveFF, setSafetyMoveFF] = useState(false);
We can't take this code out, this checks for the Safety move FF to only show the Safety Move question if the flag is on.

2024-07-05 17:52 UTC, paulstonebraker commented on src/pages/Office/CustomerOnboarding/CreateCustomerForm.jsx
> -  const [isSafetyMoveFF, setSafetyMoveFF] = useState(false);
Still can't figure out why I removed this but its back, thank you!

2024-07-06 01:51 UTC, pambecker approved these changes

2024-07-08 13:47 UTC, joeydoyecaci commented
If I enter a EMPID while safety move is 'No', then select yes, it trips the 'required' validator.
![image](https://github.com/transcom/mymove/assets/150186792/ae06162b-bff8-42e9-835e-5590cccbb7ae)

2024-07-08 14:28 UTC, loganwc submitted a review, later dismissed

2024-07-09 13:00 UTC, paulstonebraker commented
> If I enter a EMPID while safety move is 'No', then select yes, it trips the 'required' validator. ![image](https://private-user-images.githubusercontent.com/150186792/346587327-ae06162b-bff8-42e9-835e-5590cccbb7ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1Mjk5NjcsIm5iZiI6MTcyMDUyOTY2NywicGF0aCI6Ii8xNTAxODY3OTIvMzQ2NTg3MzI3LWFlMDYxNjJiLWJmZjgtNDJlOS04MzVlLTU1OTBjY2NiYjdhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQxMjU0MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMGIyMDI0ZGY0ZWRjYmIyYTFhMWU3YWE1YWNmOTI0ZjZjMDU3MDU3YmE0ZTlhY2Q1NDlhNDhiMDEzOGRlNjBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.o9VGc-yzMgP657TMbVUerr1c_VpeLPS3EA-wxkA4qNk)

Can you double check this? I'm unable to recreate on my local. Latest should have epmlid as optional unless I'm missing something

2024-07-09 13:24 UTC, joeydoyecaci commented
> > If I enter a EMPID while safety move is 'No', then select yes, it trips the 'required' validator. ![image](https://private-user-images.githubusercontent.com/150186792/346587327-ae06162b-bff8-42e9-835e-5590cccbb7ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1Mjk5NjcsIm5iZiI6MTcyMDUyOTY2NywicGF0aCI6Ii8xNTAxODY3OTIvMzQ2NTg3MzI3LWFlMDYxNjJiLWJmZjgtNDJlOS04MzVlLTU1OTBjY2NiYjdhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQxMjU0MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMGIyMDI0ZGY0ZWRjYmIyYTFhMWU3YWE1YWNmOTI0ZjZjMDU3MDU3YmE0ZTlhY2Q1NDlhNDhiMDEzOGRlNjBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.o9VGc-yzMgP657TMbVUerr1c_VpeLPS3EA-wxkA4qNk)
> 
> Can you double check this? I'm unable to recreate on my local. Latest should have epmlid as optional unless I'm missing something
> 
> ![image](https://private-user-images.githubusercontent.com/147535220/346965694-9f9b581d-6a98-496b-b853-b878cf0e2b0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MzAzMjEsIm5iZiI6MTcyMDUzMDAyMSwicGF0aCI6Ii8xNDc1MzUyMjAvMzQ2OTY1Njk0LTlmOWI1ODFkLTZhOTgtNDk2Yi1iODUzLWI4NzhjZjBlMmIwYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQxMzAwMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOTdlZGE3NTYyZjcwYTNjNjE5NDJiZmUyNDIwMWIxYmNiNjc5ODFjMTRhYmRhNGFjZGU2NTI3Njc2NTcyZjgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TAPEA0K6B8Fj4EA2m-ilrJZU-QtuLhKHkoXok2hh7-4)

Ok I just tried it again, and the issue is no longer present for me. Thanks!

2024-07-09 17:08 UTC, joeydoyecaci approved these changes

2024-07-09 17:15 UTC, loganwc approved these changes

2024-07-09 17:55 UTC, merged