B 19941 int
transcom/mymove pull request #13033
Opened 2024-06-12 12:50 UTC by antgmann

## [B-19941](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-19941)

## Summary

This story makes it such that an office user can no longer request a diversion in the application prior to the actual pickup date for a shipment. Additionally, it displays the diversion reason in the shipment information on the MTO office page.

Is there anything you would like reviewers to give additional scrutiny?
Please ensure all client tests are passing. 

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### How to test

1. Access the application as a TOO and find an HHG Shipment to use to test, or get one ready to test by logging in as a Service Counselor and completing counseling first. I have been using move code BILWEI.
2. With the move code you've just found, log in as a Prime Sim user. 
3. Go to that move code as a prime sim, edit the shipment, and change the actual pickup date to a day in the future.
4. Log back in as a TOO, and go to view the same move. On the Move Task Order tab, scroll down to the addresses card and click "Request Diversion".
5. Verify that even after entering a diversion reason, the button to request a diversion is inactive and does not submit. Note that there's no message explaining why it will not submit, that is per PO recommendation. This is AC #1. 
6. Log back in as a Prime Sim user and change back the actual pickup date to some time in the past, or the same day as testing. 
7. Log back in as a TOO, and request a diversion with a reason, and note that it will be submittable this time. Submit the diversion.
8. As a TOO on this MTO page, verify that a diversion has been requested and that the diversion reason is located in the important shipment dates card.
9. Log back in as a Prime Sim and accept the diversion.
10. Log back in as a TOO and notice that on the MTO page, the diversion requested reason has turned into the diversion approved reason. This is AC #2.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

## Screenshots
<img width="1266" alt="image" src="https://github.com/transcom/mymove/assets/148906585/a34a94da-38ae-4134-87fb-4025e736737b">
<img width="1266" alt="image" src="https://github.com/transcom/mymove/assets/148906585/6cc5fcaa-ec71-4385-ae11-32b7ab722467">
<img width="678" alt="image" src="https://github.com/transcom/mymove/assets/148906585/e3e30d1f-8911-45f4-9e3d-1aaa1f2bea19">

2024-06-12 16:50 UTC, ajlusk requested changes
A couple changes that need made and a couple questions out of curiosity.

2024-06-12 16:50 UTC, ajlusk commented on src/components/Office/RequestShipmentDiversionModal/RequestShipmentDiversionModal.jsx
> +  if (formatDate(today) > formatDate(shipmentInfo.actualPickupDate)) {
You're comparing strings here rather than date objects. The strings are dates formatted as M/D/YYYY so it works most of the time but will break around new years and probably around September switching to October.

Also, my understanding of the AC is that it should be a greater than or equal to rather that just greater than

![Screenshot 2024-06-12 at 12 30 25 PM](https://github.com/transcom/mymove/assets/158500142/18cec37b-1e34-4aec-b315-5e6d3e1e9857)

2024-06-12 16:50 UTC, ajlusk commented on src/components/Office/RequestShipmentDiversionModal/RequestShipmentDiversionModal.test.jsx
> +      actualPickupDate: 6 / 11 / 3024,
This get's parsed as a number, right? 6 divided by 11 divided by 3024. Placeholder that you forgot to go back to maybe?

2024-06-12 16:50 UTC, ajlusk commented on src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
> +    setSelectedShipment(mtoShipments[mtoShipments.findIndex((shipment) => shipment.id === mtoShipment.id)]);
Interesting, was this having issues when there was more than one shipment?

2024-06-12 16:50 UTC, ajlusk commented on src/components/Office/RequestShipmentDiversionModal/RequestShipmentDiversionModal.test.jsx
> -    expect(wrapper.find('button[data-testid="modalSubmitButton"]').prop('disabled')).toBe(false);
Was this removed due to being redundant given the submit simulation below?

2024-06-12 16:54 UTC, antgmann commented
> A couple changes that need made and a couple questions out of curiosity.

A couple of these issues are pretty glaring. Let me work through them one by one and get back to you. I just finished resolving the playwright issues locally, so it should go pretty quickly.

2024-06-12 18:06 UTC, antgmann commented on src/components/Office/RequestShipmentDiversionModal/RequestShipmentDiversionModal.test.jsx
> -    expect(wrapper.find('button[data-testid="modalSubmitButton"]').prop('disabled')).toBe(false);
It was mistakenly removed and has since been restored

2024-06-12 18:11 UTC, antgmann commented on src/components/Office/RequestShipmentDiversionModal/RequestShipmentDiversionModal.jsx
> +  if (formatDate(today) > formatDate(shipmentInfo.actualPickupDate)) {
Dates are now compared as date objects which should fix this issue. Additionally, greater than or equal to is now the current operation

2024-06-12 18:11 UTC, antgmann commented on src/components/Office/RequestShipmentDiversionModal/RequestShipmentDiversionModal.test.jsx
> +      actualPickupDate: 6 / 11 / 3024,
Yeah. Replaced with conversion to date object, should be resolved now.

2024-06-12 18:34 UTC, antgmann commented
> A couple changes that need made and a couple questions out of curiosity.

Everything *should* be addressed now. I apologize for the issues, I believe I may have lost a commit somewhere when I stashed at the end of the day. Thank you for reviewing and catching them.

2024-06-12 21:59 UTC, ajlusk approved these changes
Updates look good. Tests pass. I'm able to submit the diversion when I'm supposed to be able to and am not able when I'm not supposed to. The diversion reason text displays when appropriate and with the correct label depending on the status.

2024-06-20 17:46 UTC, MInthavongsay approved these changes
Tests all passed.

2024-06-20 18:27 UTC, merged