B-19891 TAC LOA Invalid DB INT
transcom/mymove pull request #13070
Opened 2024-06-14 16:56 UTC by traskowskycaci

## [Agility ticket](tbd)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-06-14 20:10 UTC, danieljordan-caci approved these changes
Tested and looks good!

![Screenshot 2024-06-14 at 3 10 04 PM](https://github.com/transcom/mymove/assets/136510600/7b38383e-7800-49b9-816b-8e062b5f1380)
![Screenshot 2024-06-14 at 3 10 11 PM](https://github.com/transcom/mymove/assets/136510600/6404d59a-bef5-4ae1-b660-506eeb12cb91)

2024-06-17 12:47 UTC, cameroncaci requested changes

2024-06-17 12:47 UTC, cameroncaci commented on migrations/app/schema/20240613192433_move_valid_loa_for_tac_col_to_lines_of_accounting_table.up.sql
> +COMMENT ON COLUMN lines_of_accounting.valid_loa_for_tac IS 'Result of LOA lookup for a TAC.';
Could we adjust this comment to point more towards the service object? Something like "Result of LOA service object validation that occurs whenever new LOAs are fetched by the client"

2024-06-17 12:47 UTC, cameroncaci commented on pkg/services/line_of_accounting/line_of_accounting_fetcher.go
> +		}
Out of convenience for us later down the line, can we add in the DFAS element? Like so

```		// if any LOA DFAS elements are missing, invalid
		var missingLoaFields []string
		if loa.LoaSysID == nil {
			missingLoaFields = append(missingLoaFields, "loa.LoaSysID")
		}
		if loa.LoaDptID == nil { // Department Indicator (A1)
			missingLoaFields = append(missingLoaFields, "loa.LoaDptID")
		}
		if loa.LoaTnsfrDptNm == nil { // Transfer from Department (A2)
			missingLoaFields = append(missingLoaFields, "loa.LoaTnsfrDptNm")
		}
		if loa.LoaBafID == nil { // Basic Symbol Number (A4)
			missingLoaFields = append(missingLoaFields, "loa.LoaBafID")
		}
		if loa.LoaTrsySfxTx == nil { // Subhead/Limit (A5)
			missingLoaFields = append(missingLoaFields, "loa.LoaTrsySfxTx")
		}
		if loa.LoaMajClmNm == nil { // Fund Code/MC (A6)
			missingLoaFields = append(missingLoaFields, "loa.LoaMajClmNm")
		}
		if loa.LoaOpAgncyID == nil { // Operating Agency Code/Fund Admin (B1)
			missingLoaFields = append(missingLoaFields, "loa.LoaOpAgncyID")
		}
		if loa.LoaAlltSnID == nil { // Allotment Serial Number (B2)
			missingLoaFields = append(missingLoaFields, "loa.LoaAlltSnID")
		}
		if loa.LoaPgmElmntID == nil { // Program Element (C1)
			missingLoaFields = append(missingLoaFields, "loa.LoaPgmElmntID")
		}
		if loa.LoaTskBdgtSblnTx == nil { // Project Task or Budget Sub line (C2)
			missingLoaFields = append(missingLoaFields, "loa.LoaTskBdgtSblnTx")
		}
		if loa.LoaDfAgncyAlctnRcpntID == nil { // Defense Agency Allocation Recipient (D1)
			missingLoaFields = append(missingLoaFields, "loa.LoaDfAgncyAlctnRcpntID")
		}
		if loa.LoaJbOrdNm == nil { // Job Order/Work Order Code (D4)
			missingLoaFields = append(missingLoaFields, "loa.LoaJbOrdNm")
		}
		if loa.LoaSbaltmtRcpntID == nil { // Sub-allotment Recipient (D6)
			missingLoaFields = append(missingLoaFields, "loa.LoaSbaltmtRcpntID")
		}
		if loa.LoaWkCntrRcpntNm == nil { // Work Center Recipient (D7)
			missingLoaFields = append(missingLoaFields, "loa.LoaWkCntrRcpntNm")
		}
		if loa.LoaMajRmbsmtSrcID == nil { // Major Reimbursement Source Code (E1)
			missingLoaFields = append(missingLoaFields, "loa.LoaMajRmbsmtSrcID")
		}
		if loa.LoaDtlRmbsmtSrcID == nil { // Detail Reimbursement Source Code (E2)
			missingLoaFields = append(missingLoaFields, "loa.LoaDtlRmbsmtSrcID")
		}
		if loa.LoaCustNm == nil { // Customer Indicator/MPC (E3)
			missingLoaFields = append(missingLoaFields, "loa.LoaCustNm")
		}
		if loa.LoaObjClsID == nil { // Object Class (F1)
			missingLoaFields = append(missingLoaFields, "loa.LoaObjClsID")
		}
		if loa.LoaSrvSrcID == nil { // Government or Public Sector Identifier (F3)
			missingLoaFields = append(missingLoaFields, "loa.LoaSrvSrcID")
		}
		if loa.LoaSpclIntrID == nil { // Special Interest Code or Special Program Cost Code (G2)
			missingLoaFields = append(missingLoaFields, "loa.LoaSpclIntrID")
		}
		if loa.LoaBdgtAcntClsNm == nil { // Abbreviated Department of Defense (DoD) Budget and Accounting (I1)
			missingLoaFields = append(missingLoaFields, "loa.LoaBdgtAcntClsNm")
		}
		if loa.LoaDocID == nil { // (SDN) Document or Record Reference Number (J1)
			missingLoaFields = append(missingLoaFields, "loa.LoaDocID")
		}
		if loa.LoaClsRefID == nil { // (ACRN) Accounting Classification Reference Code (K6)
			missingLoaFields = append(missingLoaFields, "loa.LoaClsRefID")
		}
		if loa.LoaInstlAcntgActID == nil { // Accounting Installation Number (L1)
			missingLoaFields = append(missingLoaFields, "loa.LoaInstlAcntgActID")
		}
		if loa.LoaLclInstlID == nil { // Local Installation Data (M1)
			missingLoaFields = append(missingLoaFields, "loa.LoaLclInstlID")
		}
		if loa.LoaFmsTrnsactnID == nil { // Transaction Type (N1)
			missingLoaFields = append(missingLoaFields, "loa.LoaFmsTrnsactnID")
		}
		if loa.LoaDscTx == nil { // Foreign Military Sales (FMS) Line Item Number (P5)
			missingLoaFields = append(missingLoaFields, "loa.LoaDscTx")
		}
		if loa.LoaUic == nil { // Activity Address Code/UIC (B3)
			missingLoaFields = append(missingLoaFields, "loa.LoaUic")
		}
```

2024-06-17 12:47 UTC, cameroncaci commented on pkg/services/line_of_accounting/line_of_accounting_fetcher.go
> +	for currLoaIndex, loa := range linesOfAccounting {
DFAS element "A3" is missing. It wasn't present in the crosswalk Dan sent, but A3 is part of the long LOA. See: https://www13.v1host.com/USTRANSCOM38/Default.aspx?Page=Widgets%2fDetails%2fAttachmentDetails&AssetWindow=true&AssetContext=Attachment%3a950468

A3 is the `loaEndFyTx`, and if you're wondering where the "BgFyTx" is, A3 holds the concatenation of both. See snippet below

![image](https://github.com/transcom/mymove/assets/136814362/eba3f3fc-353a-4bd7-b7f2-9fa940547674)

2024-06-17 13:25 UTC, traskowskycaci commented on pkg/services/line_of_accounting/line_of_accounting_fetcher.go
> +	for currLoaIndex, loa := range linesOfAccounting {
Good catch - thank you! Will get that fix in.

2024-06-17 13:57 UTC, traskowskycaci commented on migrations/app/schema/20240613192433_move_valid_loa_for_tac_col_to_lines_of_accounting_table.up.sql
> +COMMENT ON COLUMN lines_of_accounting.valid_loa_for_tac IS 'Result of LOA lookup for a TAC.';
Fixed in commit [9c7a423](https://github.com/transcom/mymove/pull/13070/commits/9c7a4237eb75faa03cf4651cb5d8e7405a43f506)

2024-06-17 13:57 UTC, traskowskycaci commented on pkg/services/line_of_accounting/line_of_accounting_fetcher.go
> +		}
Fixed in commit [f682e7e](https://github.com/transcom/mymove/pull/13070/commits/f682e7e65c2662348872f5b524924d5085276078)

2024-06-17 13:57 UTC, traskowskycaci commented on pkg/services/line_of_accounting/line_of_accounting_fetcher.go
> +	for currLoaIndex, loa := range linesOfAccounting {
Fixed in commit [9d4b13d](https://github.com/transcom/mymove/pull/13070/commits/9d4b13d524a3e9091c8284b0f22ddb269f391bdb) @cameroncaci

2024-06-17 14:21 UTC, cameroncaci requested changes

2024-06-17 14:21 UTC, cameroncaci commented on pkg/services/line_of_accounting/line_of_accounting_fetcher.go
> +			if loa.LoaBgFyTx == nil {
Sorry, one last thing! Could you set this to be "A3 is a concatenation of both LoaBgFyTx and LoaEndFyTx", just so we don't get confused later down the line cause technically they are separate fields

2024-06-17 14:49 UTC, traskowskycaci commented on pkg/services/line_of_accounting/line_of_accounting_fetcher.go
> +			if loa.LoaBgFyTx == nil {
Fixed in commit [update comments and tests](https://github.com/transcom/mymove/pull/13070/commits/a4a37eb13cd419e1f6ec3e73b8c43c0f920dfe34)

2024-06-17 14:49 UTC, cameroncaci commented on pkg/services/line_of_accounting/line_of_accounting_fetcher.go
> +			if loa.LoaBgFyTx == nil {
Fixed in https://github.com/transcom/mymove/pull/13070/commits/a4a37eb13cd419e1f6ec3e73b8c43c0f920dfe34

2024-06-17 14:50 UTC, cameroncaci approved these changes
Good job! Love it 🚀

2024-06-17 16:07 UTC, merged