B 19686 int customer can add third address
transcom/mymove pull request #13078
Opened 2024-06-17 16:33 UTC by joeydoyecaci

## [B-19686](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-19686)

## Summary

Due to the feature flag each set of steps will need to be run both with FEATURE_FLAG_THIRD_ADDRESS_AVAILABLE both off and on.

With the feature flag on.
1. Log into any milmove customer under milmovelocal to view a PPM shipment (can be existing or new, but need to be able to see edit for mto and PPM).
2. Go under edit for a PPM shipment
3. Click through until you see origin/destination address.
4. Click "Yes I have a second address". Fill out the required fields for the secondary address.
5. The option to add a third address should show. Clicking yes on this should show the third address entry block.
6. Enter a third address, fill in the required fields. Click save.
7. Leave the shipment edit screen, doesn't need to be saved, but we want to review the shipment data.
8. The third pickup and destination address should show here if one was added.
9. edit the shipment and click no for third destination address and save. move to the next screen.
10. Backtrack to the previous screen and click yes again, the third destination address should have been removed.
11. Go back to shipment summary to verify the field has been removed. There should be no empty entry for third address.

Repeat these steps for HHG, and NTS shipments. they should all work functionally equivalent with the same rules. If there is no third address, then there should be no blank fields of thrid address for either destination or pickup.

with the feature flag off

1. Log into any milmove customer under milmovelocal to view a PPM shipment (can be existing or new, but need to be able to see edit for mto and PPM).
2. Go under edit for a PPM shipment
3. Click through until you see origin/destination address.
4. Click "Yes I have a second address". Fill out the required fields for the secondary address.
5. There should be no option to add a third pickup or destination address
6. Leave the edit screen and view the shipment under review shipment. there should be no third address visible

Repeat these steps for HHG, and NTS shipments. they should all work functionally equivalent with the same rules

2024-06-17 19:31 UTC, pambecker commented
Joey, you will also need to update these 3 files for FF work.
![image](https://github.com/transcom/mymove/assets/150711493/ba2bca5c-a6fa-4e82-b207-d4f03b532ebe)

2024-06-17 19:49 UTC, pambecker commented
Can this extra directory be deleted?
![image](https://github.com/transcom/mymove/assets/150711493/09e885e2-4254-4dc6-90f5-7146c118f67e)

2024-06-17 19:50 UTC, pambecker commented on migrations/app/migrations_manifest.txt
> +20240516230021_19686_add_third_address_shipments.up.sql
Could you remove the BL # in the file name?  the standard naming is usually the date/timestamp and a brief description of the action being performed.

2024-06-17 20:28 UTC, pambecker commented on src/components/Customer/PPM/Booking/DateAndLocationForm/DateAndLocationForm.jsx
> +  const [isTertiaryAddressEnabled, setYourFFHere] = useState(false);
Could you rename the setter to be more specific and match the naming of the getter?

2024-06-17 20:28 UTC, pambecker commented on src/components/Customer/Review/ShipmentCard/DeliveryDisplay.jsx
> +  const [isTertiaryAddressEnabled, setYourFFHere] = useState(false);
Same here, could you rename the setter to be more specific and match the naming of the getter?

2024-06-17 20:28 UTC, pambecker commented on src/components/Customer/Review/ShipmentCard/PPMShipmentCard/PPMShipmentCard.jsx
> +  const [isTertiaryAddressEnabled, setYourFFHere] = useState(false);
Same here, setter should be renamed to match the getter.

2024-06-18 00:56 UTC, joeydoyecaci commented on migrations/app/migrations_manifest.txt
> +20240516230021_19686_add_third_address_shipments.up.sql
Good to know for naming of migrations. Done!

2024-06-18 00:58 UTC, joeydoyecaci commented on src/components/Customer/PPM/Booking/DateAndLocationForm/DateAndLocationForm.jsx
> +  const [isTertiaryAddressEnabled, setYourFFHere] = useState(false);
It has been set to setIsTertiaryAddressEnabled.

2024-06-18 00:58 UTC, joeydoyecaci commented on src/components/Customer/Review/ShipmentCard/DeliveryDisplay.jsx
> +  const [isTertiaryAddressEnabled, setYourFFHere] = useState(false);
It has been set to setIsTertiaryAddressEnabled.

2024-06-18 01:00 UTC, joeydoyecaci commented on src/components/Customer/Review/ShipmentCard/PPMShipmentCard/PPMShipmentCard.jsx
> +  const [isTertiaryAddressEnabled, setYourFFHere] = useState(false);
It has been set to setIsTertiaryAddressEnabled.

2024-06-18 12:23 UTC, paulstonebraker commented
for mto_shipment_creator.go /fetcher/updater and ppm creator/fetcher/updater, can you add tests for checking the tertiary address? Maybe just in ones where we are checking the secondary address

2024-06-18 13:14 UTC, pambecker commented on src/components/Customer/PPM/Booking/DateAndLocationForm/DateAndLocationForm.jsx
> +  const [isTertiaryAddressEnabled, setIsTertiaryAddressEnabled] = useState(false);
Sorry to hit on this again, but the 'Is' should be removed on the setter.  should be just 'setTertiaryAddressEnabled'.  otherwise you're basically saying 'setGet....'

2024-06-18 13:51 UTC, joeydoyecaci commented on src/components/Customer/PPM/Booking/DateAndLocationForm/DateAndLocationForm.jsx
> +  const [isTertiaryAddressEnabled, setIsTertiaryAddressEnabled] = useState(false);
I don't agree with this. the 'Is' in the name implies it's role as a flag, I don't see how that naming implies 'setGet'.

2024-06-18 13:54 UTC, loganwc commented on src/components/Customer/PPM/Booking/DateAndLocationForm/DateAndLocationForm.jsx
> +  const [isTertiaryAddressEnabled, setIsTertiaryAddressEnabled] = useState(false);
Joey is correct, that's the naming convention that react state variables follow

2024-06-18 14:11 UTC, pambecker commented on src/components/Customer/PPM/Booking/DateAndLocationForm/DateAndLocationForm.jsx
> +  const [isTertiaryAddressEnabled, setIsTertiaryAddressEnabled] = useState(false);
ok, just something I have to wrap my mind around I guess, different than Java and what I'm used to.  thanks

2024-06-21 16:47 UTC, loganwc requested changes

2024-06-21 16:47 UTC, loganwc commented on pkg/services/mto_shipment/mto_shipment_updater.go
> +	// If HasSecondaryDeliveryAddress is false, we want to remove the address
Could you update this comment please

2024-06-21 16:47 UTC, loganwc commented on pkg/services/mto_shipment/mto_shipment_updater_test.go
> +		fmt.Println("secondaryPickupAddress", tertiaryPickupAddress)
remove this println

2024-06-21 16:47 UTC, loganwc commented on pkg/services/mto_shipment/mto_shipment_updater_test.go
> +		fmt.Println("secondaryDeliveryAddress", tertiaryDeliveryAddress)
same thing here

2024-06-21 16:47 UTC, loganwc commented on src/components/Customer/PPM/Booking/DateAndLocationForm/DateAndLocationForm.jsx
> +                      {isTertiaryAddressEnabled && values.hasSecondaryPickupAddress === 'true' && (
can you add some tests for this input field? I think this should be testing the component correctly

```javascript
it('displays tertiary pickup Address input when hasTertiaryPickupAddress is true', async () => {
  await act(async () => {
    render(<DateAndLocationForm {...defaultProps} />);
    const hasTertiaryPickupAddress = await screen.getAllByLabelText('Yes')[2];

    await userEvent.click(hasTertiaryPickupAddress);
    const postalCodes = screen.getAllByLabelText('ZIP');
    const address1 = screen.getAllByLabelText('Address 1', { exact: false });
    const address2 = screen.getAllByLabelText('Address 2', { exact: false });
    const state = screen.getAllByLabelText('State');
    const city = screen.getAllByLabelText('City');
    await waitFor(() => {
      expect(address1[1]).toBeInstanceOf(HTMLInputElement);
      expect(address2[1]).toBeInstanceOf(HTMLInputElement);
      expect(city[1]).toBeInstanceOf(HTMLInputElement);
      expect(state[1]).toBeInstanceOf(HTMLSelectElement);
      expect(postalCodes[1]).toBeInstanceOf(HTMLInputElement);
    });
  });
});
```

2024-06-21 16:47 UTC, loganwc commented on src/components/Customer/PPM/Booking/DateAndLocationForm/DateAndLocationForm.jsx
> +                          <FormGroup>
same thing here 

```javascript
it('displays tertiary destination Address input when hasTertiaryDestinationAddress is true', async () => {
  await act(async () => {
    render(<DateAndLocationForm {...defaultProps} />);
    const hasTertiaryDestinationAddress = await screen.getAllByLabelText('Yes')[2];

    await userEvent.click(hasTertiaryDestinationAddress);
    const postalCodes = screen.getAllByLabelText('ZIP');
    const address1 = screen.getAllByLabelText('Address 1', { exact: false });
    const address2 = screen.getAllByLabelText('Address 2', { exact: false });
    const address3 = screen.getAllByLabelText('Address 3', { exact: false });
    const state = screen.getAllByLabelText('State');
    const city = screen.getAllByLabelText('City');

    await waitFor(() => {
      expect(address1[1]).toBeInstanceOf(HTMLInputElement);
      expect(address2[1]).toBeInstanceOf(HTMLInputElement);
      expect(address3[1]).toBeInstanceOf(HTMLInputElement);
      expect(state[1]).toBeInstanceOf(HTMLSelectElement);
      expect(city[1]).toBeInstanceOf(HTMLInputElement);
      expect(postalCodes[1]).toBeInstanceOf(HTMLInputElement);
    });
  });
});
```

2024-06-21 16:53 UTC, loganwc commented on src/components/Customer/PPM/Booking/DateAndLocationForm/DateAndLocationForm.jsx
> +                          <FormGroup>
Aside from that those small changes the functionality works exactly how I'd expect 👍

2024-06-25 16:43 UTC, pambecker commented on swagger-def/ghc.yaml
> +      tertiaryDeliveryAddress:
I didn't think we want all this here yet for this story.  We just want to touch what affects the customer, isn't this for the office user?  Same for support.yaml

2024-06-25 16:43 UTC, pambecker commented on src/components/Office/PaymentRequestCard/PaymentRequestCard.test.jsx
> +const dateRegex = /\d{2} [A-Za-z]{3} \d{4}/; // Regex match for DD MMM YYYY
Are these your changes in this file?  Don't seem related to the story.

2024-06-25 16:43 UTC, pambecker commented on pkg/handlers/primeapi/mto_service_item.go
> +				"TertiaryPickupAddress",
Should we be making all these changes in this backlog item?  for the primeapi, primeapiv2, primeapiv3.  seems out of scope.  Does it break without these changes?

2024-06-25 16:44 UTC, joeydoyecaci commented on src/components/Office/PaymentRequestCard/PaymentRequestCard.test.jsx
> +const dateRegex = /\d{2} [A-Za-z]{3} \d{4}/; // Regex match for DD MMM YYYY
This was to stop a flaky test that was randomly preventing me from committing.

2024-06-25 16:51 UTC, joeydoyecaci commented on swagger-def/ghc.yaml
> +      tertiaryDeliveryAddress:
I took a different approach, I believe it would be easier to add wherever there was a second address. This helped with an issue earlier on where despite the correct endpoint being called, the fields were not being populated.

2024-06-25 16:53 UTC, joeydoyecaci commented on pkg/handlers/primeapi/mto_service_item.go
> +				"TertiaryPickupAddress",
I took a different approach, I believe it would be easier to add wherever there was a second address, as the presence in of itself should not present a risk. Not my preferred approach but it did help with an issue earlier on where despite the correct endpoint being called, the fields were not being populated.

2024-06-25 16:53 UTC, joeydoyecaci commented on swagger-def/ghc.yaml
> +      tertiaryDeliveryAddress:
I took a different approach, I believe it would be easier to add wherever there was a second address, as the presence in of itself should not present a risk. Not my preferred approach but it did help with an issue earlier on where despite the correct endpoint being called, the fields were not being populated.

2024-06-27 11:50 UTC, pambecker approved these changes

2024-07-01 19:39 UTC, loganwc approved these changes

2024-07-02 16:31 UTC, merged