B-19763 Linehaul FSC Payment When Destination SIT - TOO Work
transcom/mymove pull request #13107
Opened 2024-06-20 18:28 UTC by WeatherfordAaron

PRs that went into INT
```12788 13019 13076```

2024-06-20 19:50 UTC, JamesHawks224 approved these changes
lgtm

2024-06-20 20:48 UTC, taeJungCaci requested changes

2024-06-20 20:48 UTC, taeJungCaci commented on pkg/services/ppm_closeout/ppm_closeout.go
> +		if *ppmShipment.HasReceivedAdvance && ppmShipment.AdvanceAmountReceived != nil {
Looks like you have changes in here that are from other stories and not have made into Main yet.

This is in: https://github.com/transcom/mymove/pull/12980/files

2024-06-20 20:48 UTC, taeJungCaci commented on pkg/services/ppm_closeout/ppm_closeout.go
> +	if weightTicket.Status == nil && ppmShipment.Status != models.PPMShipmentStatusNeedsCloseout && ppmShipment.Status != models.PPMShipmentStatusCloseoutComplete {
Same with these - they are in mine.

https://github.com/transcom/mymove/pull/12971/files#diff-b0aac5ae26809031cf0f10cff861b8160e488c175e779830b67de31634dc2700

2024-06-20 20:48 UTC, taeJungCaci commented on pkg/services/ppmshipment/aoa_packet_creator_test.go
> +	})
Maybe same with these. I don't see these in your INT PR. Please check the other files because it looks like you may have merged in all of INT changes here related your files.

2024-06-21 00:29 UTC, WeatherfordAaron commented on pkg/services/ppmshipment/aoa_packet_creator_test.go
> +	})
Sorry, it got confusing because I had so many commits. I did it again but went in one by one and added only the commits that are from those PRs that aren't merge-commits. Check one more time.. I think it's good this time.

2024-06-21 16:08 UTC, taeJungCaci requested changes

2024-06-21 16:08 UTC, taeJungCaci commented on pkg/payment_request/service_param_value_lookups/distance_zip_lookup.go
> +	destinationZip := destResult.PostalCode
Not sure where these changes came from - I don't see those changes in your INT PRs.

2024-06-21 16:49 UTC, closed without merging