B 20493 int
transcom/mymove pull request #13265
Opened 2024-07-18 14:20 UTC by deandreJones

## [B-20493](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A980573)

## Summary

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the Office app
2. Click Request Account 
3. For this test- we want to be able to select all available transportation offiices- even those that don't office ppm_closeout- , JPPSO Southeast (CNNQ) is one example, where before this change- it was not able to be selected, after this change it is able to be selected

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

## Screenshots

![image](https://github.com/user-attachments/assets/da24b8e6-56d6-48f2-9dcd-bc59c66198de)

2024-07-18 14:42 UTC, danieljordan-caci requested changes
Need you to clarify some things with Dan before signing off or doing additional work.

2024-07-18 14:42 UTC, danieljordan-caci commented on pkg/services/transportation_office/transportation_office_fetcher.go
>  select office.*
So I know this works, but I have some reservations.

This is also used for customers when searching for transpo offices in `/pkg/handlers/internalapi/transportation_offices.go:54`:
```
transportationOffices, err := h.TransportationOfficesFetcher.GetTransportationOffices(appCtx, params.Search)
			if err != nil {
				appCtx.Logger().Error("Error searching for Transportation Offices: ", zap.Error(err))
				return transportationofficeop.NewGetTransportationOfficesInternalServerError(), err
			}
```

and...

This is also used for customers when searching for transpo offices in `/pkg/handlers/ghcapi/transportation_offices.go:23`:
```
transportationOffices, err := h.TransportationOfficesFetcher.GetTransportationOffices(appCtx, params.Search)
			if err != nil {
				appCtx.Logger().Error("Error searching for Transportation Offices: ", zap.Error(err))
				return transportationofficeop.NewGetTransportationOfficesInternalServerError(), err
			}
```

So I think that if that is fine for customers and office users inside of the app to see all transpo offices, then we can leave this.

If not, then we should probably create a new service object that only this open handler uses. Should prob ask Dan.

2024-07-18 16:26 UTC, deandreJones commented on pkg/services/transportation_office/transportation_office_fetcher.go
>  select office.*
good call

2024-07-18 19:49 UTC, deandreJones commented on pkg/services/transportation_office/transportation_office_fetcher.go
>  select office.*
after some research- this endpoint can't be used, will have to create anew one or- use the admin api

![image](https://github.com/user-attachments/assets/d20bd745-2a42-4a77-8913-ed82b178353b)

2024-07-18 20:03 UTC, danieljordan-caci commented on pkg/services/transportation_office/transportation_office_fetcher.go
>  select office.*
Can just create a new service object that the handler calls. Just copy over what's in `pkg/services/transportation_office/transportation_office_fetcher.go`:

```
func (o transportationOfficesFetcher) GetTransportationOfficesForRequestedOfficeUsers(appCtx appcontext.AppContext, search string) (*models.TransportationOffices, error) {
	officeList, err := FindTransportationOfficeForRequestedOfficeUsers(appCtx, search)

	if err != nil {
		switch err {
		case sql.ErrNoRows:
			return &officeList, apperror.NewNotFoundError(uuid.Nil, "Search string: "+search)
		default:
			return &officeList, err
		}
	}

	return &officeList, nil
}

func FindTransportationOfficeForRequestedOfficeUsers(appCtx appcontext.AppContext, search string) (models.TransportationOffices, error) {
	var officeList []models.TransportationOffice

	// The % operator filters out strings that are below this similarity threshold
	err := appCtx.DB().Q().RawQuery("SET pg_trgm.similarity_threshold = 0.03").Exec()
	if err != nil {
		return officeList, err
	}

	sqlQuery := `
	with names as (select office.id as transportation_office_id, office.name, similarity(office.name, $1) as sim
        from transportation_offices as office
        where name % $1
		order by sim desc
        limit 5)
select office.*
        from names n inner join transportation_offices office on n.transportation_office_id = office.id
        group by office.id
        order by max(n.sim) desc, office.name
        limit 5`
	query := appCtx.DB().Q().RawQuery(sqlQuery, search)
	if err := query.All(&officeList); err != nil {
		if errors.Cause(err).Error() != models.RecordNotFoundErrorString {
			return officeList, err
		}
	}
	for i := range officeList {
		err := appCtx.DB().Load(&officeList[i], "Address")
		if err != nil {
			return officeList, err
		}
	}
	return officeList, nil
}
```

Bing bang boom.

2024-07-19 13:18 UTC, deandreJones commented on pkg/services/transportation_office/transportation_office_fetcher.go
>  select office.*
I don't like copied code- I prefer to make the code more flexible for multiple use

2024-07-19 13:54 UTC, danieljordan-caci commented
You just not putting labels on your PRs now, boss? :)

2024-07-19 14:52 UTC, traskowskycaci approved these changes
Query results look good!

May need a `make mocks_generate` on your branch

2024-07-19 14:54 UTC, deandreJones commented
> You just not putting labels on your PRs now, boss? :)

I never claimed to be perfect...

2024-07-19 14:54 UTC, deandreJones commented
> Query results look good!
> 
> May need a `make mocks_generate` on your branch

already did

2024-07-19 16:25 UTC, danieljordan-caci commented on pkg/services/transportation_office/transportation_office_fetcher.go
>  select office.*
Fine by me! Your solution looks good!

2024-07-19 16:26 UTC, danieljordan-caci approved these changes
Nailed it!

2024-07-19 19:51 UTC, merged