B 20497 int
transcom/mymove pull request #13269
Opened 2024-07-18 16:24 UTC by deandreJones

## [B-20497](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A980660)

## Summary

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the Office App
2. Request an account
3. Access Admin app.
4. Approve the requested account from above
5. go to office users on left nav
6. validate that the office use you approved is marked as Active (true)
7. logout- then access the Office App
8. login as that new user

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

## Screenshots
![image](https://github.com/user-attachments/assets/50c29f10-92da-4c5b-b68f-2aa91300e5f6)

![image](https://github.com/user-attachments/assets/8fc5ccac-ceb8-49f7-b26b-29e8de73dbbb)

![Screenshot 2024-07-18 at 11 22 30 AM](https://github.com/user-attachments/assets/a335c81c-0944-476c-9bd6-e6b88fe9ac69)

![image](https://github.com/user-attachments/assets/9cfbf61e-e781-4ca2-9df4-a3145a7ae2fc)

![image](https://github.com/user-attachments/assets/9b3bd96f-62ef-4229-a840-2760401298e8)

![image](https://github.com/user-attachments/assets/984fb054-4af5-4e88-b0f2-308dacc72baa)

![image](https://github.com/user-attachments/assets/e9b9a522-d5b4-4f01-be2a-d93feb1f6124)

2024-07-18 18:25 UTC, danieljordan-caci commented on pkg/services/requested_office_users/requested_office_user_updater.go
> +		}
Do you need `if officeUser.Status != nil` here? Seems redundant since we are already checking for it on line 70.

2024-07-18 18:26 UTC, danieljordan-caci requested changes
Can you update `requested_office_user_updater_test.go` as well to reflect this change?

2024-07-18 19:45 UTC, deandreJones commented on pkg/services/requested_office_users/requested_office_user_updater.go
> +		}
removed

2024-07-18 19:46 UTC, deandreJones commented
> Can you update `requested_office_user_updater_test.go` as well to reflect this change?

fine...

2024-07-19 13:44 UTC, danieljordan-caci approved these changes
Thanks for the fixes. Tested locally and works just fiiiiiine.

Looks like you have flaky tests failing, so I'll go ahead and check ya off.

2024-07-19 14:52 UTC, TevinAdams approved these changes
Tested and reviewed.

2024-07-19 14:56 UTC, merged