B 20165 tio fix page width int
transcom/mymove pull request #13266
Opened 2024-07-18 15:09 UTC by KonstanceH

## [B-20165](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A959449)

## Summary

This PR fixes the width of the review weights page for the TIO.
When reviewing weights the TIO shouldn't have to scroll horizontally to see the full page.

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### How to test

1. Login as a TIO
2. Click any move in TIO move queue
3. Click "Review Weights"
4. Should see entire page without having to scroll.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

## Screenshots
<img width="1247" alt="Screenshot 2024-07-15 at 8 46 15 AM" src="https://github.com/user-attachments/assets/28becfcb-2031-406f-b389-b429fa6dc1e5">

2024-07-18 20:04 UTC, taeJungCaci requested changes

2024-07-18 20:04 UTC, taeJungCaci commented on src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.jsx
> +      <div>
Instead of deleting the whole style, I would suggest adding a new class or modifying the existing class to match how it is shown in 'Review service items' page. I think deleting the whole sidebar class from the div is removing other styles you would want to keep.

I've found 2 things you might need to add/modify:
 - Width need to be 400px. I believe `.container` from `DocumentViewerSidebar.module.scss` is changing it to 500px. I would see if you can override the width.
 - Also add `box-shadow: -4px 0px 8px 0px rgba(0, 0, 0, 0.1);` to the class you would add.
 
Check out PaymentRequestReview.jsx and see if it helps.

2024-07-18 20:40 UTC, KonstanceH commented on src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.jsx
> +      <div>
> Instead of deleting the whole style, I would suggest adding a new class or modifying the existing class to match how it is shown in 'Review service items' page. I think deleting the whole sidebar class from the div is removing other styles you would want to keep.
> 
> I've found 2 things you might need to add/modify:
> 
> * Width need to be 400px. I believe `.container` from `DocumentViewerSidebar.module.scss` is changing it to 500px. I would see if you can override the width.
> * Also add `box-shadow: -4px 0px 8px 0px rgba(0, 0, 0, 0.1);` to the class you would add.
> 
> Check out PaymentRequestReview.jsx and see if it helps.

The fix analysis for this said to either remove it or just change the width to 400px so I went with just removing it. Your point is fair though so I'm going to go ahead and just change the width.

2024-07-18 20:42 UTC, taeJungCaci commented on src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.jsx
> +      <div>
Oh I didn't even see that analysis lol. Yeah, but I think it is talking about removing that width of 500

2024-07-18 20:46 UTC, KonstanceH commented on src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.jsx
> +      <div>
> Oh I didn't even see that analysis lol. Yeah, but I think it is talking about removing that width of 500

ahhh okay I misinterpreted it

2024-07-18 21:03 UTC, taeJungCaci commented on src/pages/Office/DocumentViewerSidebar/DocumentViewerSidebar.module.scss
> +  width: 400px;
Just to let you know this will also change the width for PPM Closeout document review page and where ever else this class is being used at. I think @brooklyn-welsh added that 500px so might want to check with him if it is okay to change back to 400. If not, you might have to add your own to override it.

2024-07-22 17:16 UTC, KonstanceH commented on src/pages/Office/DocumentViewerSidebar/DocumentViewerSidebar.module.scss
> +  width: 400px;
> Just to let you know this will also change the width for PPM Closeout document review page and where ever else this class is being used at. I think @brooklyn-welsh added that 500px so might want to check with him if it is okay to change back to 400. If not, you might have to add your own to override for review weights. Or possible change this back to 400px and add a separate one for PPM closeout review documents view.

Yea after thinking about, I went with your original suggestion to just make a new class. That way I don't have to look for where it would break everywhere else lol

2024-07-23 15:10 UTC, WeatherfordAaron approved these changes
lgtm 👽

2024-07-23 15:14 UTC, taeJungCaci approved these changes
LGTM

2024-07-24 15:14 UTC, merged