B 20686 int
transcom/mymove pull request #13294
Opened 2024-07-22 17:48 UTC by CoryKleinjanCACI

## [Agility ticket](tbd)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-07-22 18:29 UTC, danieljordan-caci commented on src/components/Office/PaymentRequestCard/PaymentRequestCard.jsx
> +  };
Randomly looking at this PR - just a suggestion (feel free to say no).

I think this could be refactored to be a little cleaner as well as a little more performance friendly. I did just pull your branch to make sure it returned the same:

```
  const nonWeightRelatedServiceItemsOnly = () => {
    return paymentRequest.serviceItems.every((serviceItem) =>
      Object.prototype.hasOwnProperty.call(nonWeightReliantServiceItems, serviceItem.mtoServiceItemCode),
    );
  };
```

You can use the `every` method to make the code more declarative and potentially a little more efficient because it will stop processing as soon as it finds something that doesn't satisfy the condition. 

`forEach` works just fine too, but it does look at each item in the array.

Just a suggestion! No pressure - what you currently have works just fine!

2024-07-22 19:04 UTC, CoryKleinjanCACI commented on src/components/Office/PaymentRequestCard/PaymentRequestCard.jsx
> +  };
I think thats a good suggestion. I wasn't super pleased with it, but wasn't aware of the 'every' function. Thanks.

2024-07-22 19:39 UTC, danieljordan-caci requested changes
Able to go through your test case successfully with one little hiccup.
![Screenshot 2024-07-22 at 2 37 28 PM](https://github.com/user-attachments/assets/df760844-f88d-4919-bf4b-9c56947d9c11)

When doing the prime simulator step, you can't ONLY update the estimated weight or you get an error (or at least I did). I just updated it manually in the db, so no biggie.
![Screenshot 2024-07-22 at 2 42 20 PM](https://github.com/user-attachments/assets/632fec73-1957-4a7d-a7a1-1ceeb16dd976)


LGTM, but I would like to see at least one test to test the added functionality.

I had a similar issue but appears to be a limitation of the Prime Simulator. You can use the Prime API to [update](http://primelocal:3000/swagger-ui/prime.html#/mtoShipment/updateMTOShipment) just the shipment dates which is what is needed in order to be able to create a Payment Request. I used this as the body to the swagger call.

{
  "scheduledPickupDate": "2024-07-24",
  "actualPickupDate": "2024-07-24",
  "firstAvailableDeliveryDate": "2024-07-24",
  "scheduledDeliveryDate": "2024-07-24",
  "actualDeliveryDate": "2024-07-24"
}

Then I was allowed to create a Payment Request with just the Move Management Fee. So using the API it is possible to submit a Payment Request without entering weights. The Prime Sim Update Shipment page assumes a weight must be entered and always attempts to pass in Actual Weight which defaults to 0 and isn't allowed.

Out of scope for this ticket though but maybe at some point the Prime Sim needs to be updated to allow you to update the shipment without having to enter the weights?

2024-07-22 19:56 UTC, danieljordan-caci approved these changes
'preciate the test!

2024-07-24 16:35 UTC, r-mettler approved these changes

2024-07-25 13:33 UTC, merged