MAIN - B-20454 - created db and model for boat shipment
transcom/mymove pull request #13296
Opened 2024-07-22 18:46 UTC by taeJungCaci

## [Agility ticket](tbd)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-07-26 21:32 UTC, JamesHawks224 commented on migrations/app/schema/20240716161148_create_boat_shipment_table.up.sql
> +CREATE INDEX boat_shipments_deleted_at_idx ON boat_shipments (deleted_at);
Obviously, there are benefits to indexing.  But, there are also costs to putting indexes on columns.  The data for the column is bigger since it has an index, therefore more storage is consumed.  And, there's a processing speed impact since the index has to be maintained when rows are updated, inserted or deleted.  Will these fields actually be used enough to justify the costs?

2024-07-26 21:33 UTC, JamesHawks224 requested changes
See code comments.

2024-07-26 22:36 UTC, taeJungCaci commented on migrations/app/schema/20240716161148_create_boat_shipment_table.up.sql
> +CREATE INDEX boat_shipments_deleted_at_idx ON boat_shipments (deleted_at);
Sure that's a good point. I didn't really think about the overall cost of putting indexes on those and you probably know more about them. It would be okay to have index on shipment_id and not the other three correct?

Also this is a PR into Main so I can add a sql to remove those index in the api story if that's okay. Unless you think I should create another INT PR just for that.

2024-07-29 14:29 UTC, JamesHawks224 commented on migrations/app/schema/20240716161148_create_boat_shipment_table.up.sql
> +CREATE INDEX boat_shipments_deleted_at_idx ON boat_shipments (deleted_at);
Talked with Tae.
re: Indexes.  If there's a use case for using them in queries, it makes sense to keep the index.  But, if there's not (e.g. created index), then remove it.

re: updating int indexes
Whichever is most convenient for you, as long as it gets in relatively soon.

2024-07-29 15:08 UTC, taeJungCaci commented
> See code comments.

As discussed, I will add the change to remove some of the indexes that may not be needed in the PR for B-20602 as they are under same feature.

2024-07-29 18:38 UTC, JamesHawks224 approved these changes

2024-07-29 21:28 UTC, r-mettler approved these changes
same as INT

2024-07-29 21:29 UTC, merged