B-20291:Customer review page errors int
transcom/mymove pull request #13313
Opened 2024-07-23 18:57 UTC by TevinAdams

## [Agility ticket](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-20291)

## Summary
Dan requested that if there is no Transportation Office office then show "To change these fields, contact your local PPPO office".

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the MilMove as customer and create a move using a duty location that does not have a Transportation Office OR use a move that already has this circumstance
2. Login to OFFICE as a TOO and approve the move
3. Go back to the MilMove customer and select Review your Request
4. If there move has no Transportation office it will should say "To change these fields, contact your local PPPO office". If it does then it should show the original message with Transportation office name and number.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-07-23 19:30 UTC, danieljordan-caci requested changes
Could you add a test for this please?

2024-07-23 21:17 UTC, TevinAdams commented
> Could you add a test for this please?

@danieljordan-caci  Test added.

2024-07-23 21:22 UTC, traskowskycaci commented
Should Dan's requested text change get added to the AC for the story?

2024-07-23 21:23 UTC, TevinAdams commented
> Should Dan's requested text change get added to the AC for the story?

Yeah let me add them there.

2024-07-24 13:34 UTC, danieljordan-caci approved these changes
Just a nitpicky suggestion. Up to you to change it - think it would be a lot cleaner code though.

Going to approve! Tested locally and works fine!

![Screenshot 2024-07-24 at 8 33 38 AM](https://github.com/user-attachments/assets/4d6fc3cc-6e25-4be6-88b4-8f0297ec278e)

![Screenshot 2024-07-24 at 8 33 49 AM](https://github.com/user-attachments/assets/11edf059-1358-43d1-aca6-3c5cae71e245)

2024-07-24 13:34 UTC, danieljordan-caci commented on src/components/Customer/Review/Summary/Summary.jsx
> +        )}
I think this could be refactored to be a little more concise
```
{moveIsApproved && (
  <div className="approved-edit-warning">
    *To change these fields, contact your local PPPO office
    {currentDutyLocation ? ` at ${currentDutyLocation.name}` : ''}{officePhone ? ` at ${officePhone}` : ''}.
  </div>
)}
```

This way you don't need the two `if` statements in the render.

2024-07-24 14:32 UTC, traskowskycaci requested changes
Mind attaching some screenshots showing this is 508 compliant? Otherwise, looks good and I'll approve!

2024-07-24 14:37 UTC, TevinAdams commented
> Mind attaching some screenshots showing this is 508 compliant? Otherwise, looks good and I'll approve!

@traskowskycaci  Screenshots added. Nothing with the styling changed. Dan only requested different text to show up based on if there is a transpo office or not.

2024-07-24 15:49 UTC, danieljordan-caci commented on src/components/Customer/Review/Summary/Summary.jsx
>              {officePhone ? ` at ${officePhone}` : ''}.
You can see the extra space in the first screenshot you added

2024-07-24 15:59 UTC, danieljordan-caci requested changes
Not seeing any changes.

2024-07-24 16:04 UTC, TevinAdams commented
> Not seeing any changes.

Sorry did that before seeing your comment about extra space.

2024-07-24 16:11 UTC, TevinAdams commented on src/components/Customer/Review/Summary/Summary.jsx
>              {officePhone ? ` at ${officePhone}` : ''}.
@danieljordan-caci  Extra space removed 
![image](https://github.com/user-attachments/assets/68c348d3-db53-42f9-945e-3530d7364435)

2024-07-24 16:12 UTC, traskowskycaci approved these changes

2024-07-24 16:14 UTC, danieljordan-caci approved these changes

2024-07-25 15:00 UTC, merged