B 20620 mobile home db model int
transcom/mymove pull request #13325
Opened 2024-07-24 22:08 UTC by KonstanceH

## [Agility ticket](tbd)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-07-26 19:51 UTC, JamesHawks224 commented on migrations/app/schema/20240723184614_create_mobile_home.up.sql
> +	mh_length int NOT NULL,
Why is year and length prefixed with "mh_".  The other fields are not.  If there's not a compelling reason, they should be made consistent with the other fields.

2024-07-26 19:59 UTC, JamesHawks224 commented on migrations/app/schema/20240723184614_create_mobile_home.up.sql
> +COMMENT on COLUMN mobile_home.shipment_id IS 'MTO shipment ID associated with this PPM shipment.';
comment is referring to "PPM Shipment", needs to be updated.

2024-07-26 20:34 UTC, JamesHawks224 commented on swagger-def/definitions/MobileHome.yaml
> +    type: string
Should these fields be here?  They aren't in the table.

2024-07-26 20:38 UTC, JamesHawks224 requested changes
Code reviewed.  Comments made.

2024-07-26 21:46 UTC, brooklyn-welsh requested changes

2024-07-26 21:46 UTC, brooklyn-welsh commented on swagger-def/definitions/MobileHome.yaml
> +  orginAddress:
Small typo "orgin" -> "origin"

2024-07-26 21:46 UTC, brooklyn-welsh commented on swagger/ghc.yaml
> +      - Mobile_Home
I'd probably go ahead and all caps this just to stay consistent.

2024-07-26 21:46 UTC, brooklyn-welsh commented on swagger/ghc.yaml
> +      Mobile_Home: Mobile Home
Same, "Mobile_Home" -> "MOBILE_HOME"

2024-07-26 21:46 UTC, brooklyn-welsh commented on swagger-def/definitions/MTOShipmentType.yaml
> +  - Mobile_Home
All caps for consistency: "Mobile_Home" -> "MOBILE_HOME"

2024-07-26 21:46 UTC, brooklyn-welsh commented on swagger-def/definitions/MTOShipmentType.yaml
> +  Mobile_Home: Mobile Home
All caps for consistency: "Mobile_Home" -> "MOBILE_HOME"

2024-07-26 21:46 UTC, brooklyn-welsh commented on src/pages/MyMove/Multi-Moves/MultiMovesMoveContainer/MultiMovesMoveContainer.jsx
> +      return 'Mobilehome';
Minor formatting fix: "Mobilehome" -> "Mobile Home"

2024-07-26 21:46 UTC, brooklyn-welsh commented on migrations/app/schema/20200205160112_add_enum_values_to_shipment_type_within_mto_shipments.up.sql
>      'BOAT_HAUL_AWAY',
So, I think in regards to migration files, they don't want us editing already existing ones, or we risk breaking something. Also, any environment other than dev (so prod I think, not sure about others) will *not* run these, since they run migration files only once, at least per the docs in the "danger" box on this page: https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#understanding-migrations.

So all of these changes to mto_shipment_type would need to be in a new migration file, where you alter the type similar to this one. In fact you could probably just copy this script line for line and it would work, it just needs to be in a new migration file so that the updates work in production. Since these are all working on the same table you should just need a single migration file. 

Probably best to keep it separate from the create mobile home script since they're technically two distinct operations.

2024-07-26 21:46 UTC, brooklyn-welsh commented on migrations/app/schema/20220203001924_add_ppm_to_mto_shipments_shipment_type_enum_values.up.sql
> +	'MOBILEHOME',
See other comment regarding migrations.

2024-07-26 21:46 UTC, brooklyn-welsh commented on migrations/app/schema/20230605163737_delete_hhg_shorthaul_domestic_hhg_longhaul_domestic_from_mto_shipments_shipment_type.up.sql
> +	'MOBILEHOME',
See other comment regarding migrations.

2024-07-26 21:46 UTC, brooklyn-welsh commented on swagger-def/definitions/MobileHome.yaml
> +  dimensions:
Since we already have fields for length, width, and height, is there any reason we need a string field for dimensions?

2024-07-26 21:46 UTC, brooklyn-welsh commented on migrations/app/schema/20240723184614_create_mobile_home.up.sql
> +CREATE TABLE IF NOT EXISTS mobile_home (
I think we'll need created_at, updated_at, and deleted_at fields for this too, I know deleted_at is one that's used for soft deleting things, and I think updated_at is used for the E-Tag system they use for dealing with multiple people editing the same resource. Also recording these things might be a contractual obligation for records but I'm not sure.

2024-07-26 21:46 UTC, brooklyn-welsh commented on swagger-def/ghc.yaml
> +        type: string
I think you could replace this block with "$ref: 'definitions/MobileHome.yaml".

2024-07-26 21:46 UTC, brooklyn-welsh commented on swagger/ghc.yaml
> +        type: string
Could replace with "$ref: '/definitions/MobileHome.yaml"

2024-07-29 16:01 UTC, taeJungCaci commented on migrations/app/schema/20230605163737_delete_hhg_shorthaul_domestic_hhg_longhaul_domestic_from_mto_shipments_shipment_type.up.sql
> +	'MOBILEHOME',
This might have been suggested already, but also might be a good idea so have it as `MOBILE_HOME` to be consistent with others.

2024-07-31 13:59 UTC, taeJungCaci reviewed
I haven't had the time to fully review this PR, but one of the things @brooklyn-welsh suggested was adding index to sql. This is what I had added on mine for Boat shipment:

CREATE INDEX boat_shipments_shipment_id_idx ON boat_shipments (shipment_id);
CREATE INDEX boat_shipments_deleted_at_idx ON boat_shipments (deleted_at);

Here is my PR for ref - I deleted other indexes not needed in my other PR:
https://github.com/transcom/mymove/pull/13296

2024-07-31 16:08 UTC, KonstanceH commented on migrations/app/schema/20240723184614_create_mobile_home.up.sql
> +	mh_length int NOT NULL,
I just changed it to mh_year/mh_length because year/length seemed to be sql keywords

2024-07-31 16:11 UTC, KonstanceH commented on swagger-def/definitions/MobileHome.yaml
> +  dimensions:
I just added it because it was in the agilty story details, but I agree it feels redundant so I'll remove it.

2024-07-31 16:17 UTC, KonstanceH commented on swagger-def/definitions/MobileHome.yaml
> +    type: string
No I think these fields are tied to the mtoshipment and not unique to the mobile home shipment so I'll remove these.

2024-07-31 16:54 UTC, taeJungCaci commented
> I haven't had the time to fully review this PR, but one of the things @brooklyn-welsh suggested was adding index to sql. This is what I had added on mine for Boat shipment:
> 
> CREATE INDEX boat_shipments_shipment_id_idx ON boat_shipments (shipment_id); CREATE INDEX boat_shipments_deleted_at_idx ON boat_shipments (deleted_at);
> 
> Here is my PR for ref - I deleted other indexes not needed in my other PR: #13296

Also, just to share my approach, I am using only inches for my length, width, and height to make it easier and named the variables - `lengthInInches`, `widthInInches`, and `heightInInches`. Thought it would be more descriptive. If you had something easier or better, I may be able to take your approach.

2024-07-31 17:05 UTC, KonstanceH commented
> > I haven't had the time to fully review this PR, but one of the things @brooklyn-welsh suggested was adding index to sql. This is what I had added on mine for Boat shipment:
> > CREATE INDEX boat_shipments_shipment_id_idx ON boat_shipments (shipment_id); CREATE INDEX boat_shipments_deleted_at_idx ON boat_shipments (deleted_at);
> > Here is my PR for ref - I deleted other indexes not needed in my other PR: #13296
> 
> Also, just to share my approach, I am using only inches for my length, width, and height to make it easier and named the variables - `lengthInInches`, `widthInInches`, and `heightInInches`. Also in `*int` Thought it would be more descriptive. If you had something easier or better, I may be able to take your approach.

yea that's definitely more descriptive so I'll add them in.

2024-07-31 17:06 UTC, KonstanceH commented
> I haven't had the time to fully review this PR, but one of the things @brooklyn-welsh suggested was adding index to sql. This is what I had added on mine for Boat shipment:
> 
> CREATE INDEX boat_shipments_shipment_id_idx ON boat_shipments (shipment_id); CREATE INDEX boat_shipments_deleted_at_idx ON boat_shipments (deleted_at);
> 
> Here is my PR for ref - I deleted other indexes not needed in my other PR: #13296

ah okay I'll add this in too

2024-07-31 19:06 UTC, brooklyn-welsh approved these changes
LGTM!

2024-07-31 19:55 UTC, taeJungCaci commented on migrations/app/schema/20240723184614_create_mobile_home.up.sql
> +    REFERENCES mto_shipments(id),
I think it would be good to add `ON DELETE CASCADE,` here so when the mtoShipment gets deleted, this will also get deleted.

```
CONSTRAINT mobile_home_mto_shipment_id_fkey
REFERENCES mto_shipments(id),
ON DELETE CASCADE,
```

2024-07-31 19:55 UTC, taeJungCaci commented on migrations/app/schema/20240723184614_create_mobile_home.up.sql
> +CREATE INDEX mobile_homes_created_at_idx ON mobile_homes (created_at);
This one you could probably take out. Jim was recommending to remove the ones that may not be useful and could eat up space.

`CREATE INDEX mobile_homes_created_at_idx ON mobile_homes (created_at);`

2024-07-31 19:55 UTC, taeJungCaci commented on pkg/models/mto_shipments.go
> +	MTOShipmentTypeMobilehome MTOShipmentType = "MOBILE_HOME"
Should this be `MTOShipmentTypeMobileHome` instead? I think you had Mobile_Home everywhere else. Might be better to change this now than later down the road where there might be 100+ files.

2024-08-01 14:16 UTC, KonstanceH commented on migrations/app/schema/20240723184614_create_mobile_home.up.sql
> +	mh_length int NOT NULL,
These have been updated to year and length_in_inches

2024-08-01 15:03 UTC, taeJungCaci commented on swagger-def/definitions/MobileHome.yaml
> +      - x-omitempty: false
I believe these are not available for mobile home and are only for PPMs

2024-08-01 15:17 UTC, KonstanceH commented on swagger-def/definitions/MobileHome.yaml
> +      - x-omitempty: false
yea you're right I could've sworn I had already removed them, but I just pushed this change up

2024-08-01 15:18 UTC, taeJungCaci approved these changes
LGTM!

2024-08-01 18:15 UTC, JamesHawks224 approved these changes

2024-08-01 18:46 UTC, merged