INT B-19819 unique DODID when creating a customer
transcom/mymove pull request #13323
Opened 2024-07-24 19:47 UTC by danieljordan-caci

## [Agility ticket](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-19819)

## Summary

When a service counselor is creating a customer, we want to make sure that the DODID that they're providing doesn't already exist. This added functionality needs to be wrapped up in a feature flag because that sounds like an inconvenience that would leave testing and developing an absolute nightmare.

You can find the merged feature flag in each environment [here.](https://github.com/transcom/milmove-feature-flags/pull/179)

This PR does the following:
- added feature flag to `envrc` and set to `false`
- added feature flag value to be read by `viper`
- updated `customer.go` handler to check for existing DODID only if the feature flag is on
- added a test and updated existing test structure
- updated UI styling to server error banner to share the same width as the form

### How to test

1. In your `envrc` change `FEATURE_FLAG_DODID_UNIQUE` to `true`
2. Fire up your `client` and `server`
3. Log in as a service counselor
4. Navigate to the `Customer Search` tab
5. Click the `Customer name` radio button
6. Type in literally anything and click `Search`
7. The `Add Customer` button should pop out at ya
8. Click it
9. Fill out the form and use an existing DODID value in the `DoD ID number` text input
10. Try to submit the form
11. You should see an error at the top of the page that says the DODID is already taken

## Screenshots
![Screenshot 2024-07-24 at 2 42 10 PM](https://github.com/user-attachments/assets/bb956eb3-2222-419b-810b-f098da5cec28)

2024-07-25 14:30 UTC, traskowskycaci approved these changes
![image](https://github.com/user-attachments/assets/d8894379-58d3-4281-99bf-a490ea842784)

Looks good!

2024-07-25 19:43 UTC, cameroncaci requested changes

2024-07-25 19:43 UTC, cameroncaci commented on pkg/handlers/ghcapi/customer.go
> +			dodidUniqueFeatureFlag := v.GetBool(cli.FeatureFlagDODIDUnique)
This won't work in the live environments - this should be replaced with `FeatureFlagFetcher` within the handler receiver. Hard checking for env vars will only ever pass locally and won't work with Flipt

[Docs](https://transcom.github.io/mymove-docs/docs/tools/feature-flags/how-to-use-feature-flags#backend-boolean-feature-flag-usage)

2024-07-25 19:44 UTC, cameroncaci commented on pkg/handlers/ghcapi/customer.go
> +			dodidUniqueFeatureFlag := v.GetBool(cli.FeatureFlagDODIDUnique)
You can use `make feature_flag_docker` to test Flipt locally once you add the FF to `docker-compose.feature_flag.yml`

2024-07-25 19:50 UTC, cameroncaci requested changes

2024-07-25 19:50 UTC, cameroncaci commented on .envrc
> +export FEATURE_FLAG_DODID_UNIQUE=false
Could you add this FF to the `config/env` app envs? To serve as a fallback for if the Flipt server goes down

2024-07-25 20:01 UTC, danieljordan-caci commented on pkg/handlers/ghcapi/customer.go
> +			dodidUniqueFeatureFlag := v.GetBool(cli.FeatureFlagDODIDUnique)
Are you sure? This is how I fetch the API key when making Okta calls.

2024-07-25 20:01 UTC, danieljordan-caci commented on pkg/handlers/ghcapi/customer.go
> +			dodidUniqueFeatureFlag := v.GetBool(cli.FeatureFlagDODIDUnique)
I might need your help to code this because I'm not finding any examples to help and the docs aren't super thorough on how to get the flag value from the backend.

2024-07-25 20:09 UTC, cameroncaci commented on pkg/handlers/ghcapi/customer.go
> +			dodidUniqueFeatureFlag := v.GetBool(cli.FeatureFlagDODIDUnique)
That pulls the API key from the AWS param store

2024-07-25 20:10 UTC, danieljordan-caci commented on pkg/handlers/ghcapi/customer.go
> +			dodidUniqueFeatureFlag := v.GetBool(cli.FeatureFlagDODIDUnique)
Aight I'll follow those docs and make ya proud

2024-07-25 20:42 UTC, danieljordan-caci commented on pkg/handlers/ghcapi/customer.go
> +			dodidUniqueFeatureFlag := v.GetBool(cli.FeatureFlagDODIDUnique)
Take a look when you get a chance

2024-07-25 20:42 UTC, danieljordan-caci commented on .envrc
> +export FEATURE_FLAG_DODID_UNIQUE=false
Added. Can't believe I forgot that!

2024-07-26 12:43 UTC, cameroncaci approved these changes

2024-07-26 13:13 UTC, merged