INT B-20591 prime can update destination address for NTSR shipment
transcom/mymove pull request #13347
Opened 2024-07-29 16:19 UTC by danieljordan-caci

## [Agility ticket](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-20591)

## Summary

The gov is wanting NTSR shipments to go through the same process as HHG shipments when the Prime requests a change to the delivery/destination address with the end goal being the TOO needs to approve the change if the business rules change.

This PR does the following:
- some random white space deletions cause it was driving me nuts
- added on to existing query when looking for shipments that are requesting an addy change - for NTSR shipments we need the storage address since technically that's the "pickup" address
- adjusted logic checks to either look at pickup or storage address, depending on `shipmentType`
- updated UI to conditionally show `Review required` instead of the address for NTSR shipments that have a pending destination address change
- added a way for the office user to click the `See delivery location to proceed.` link and be scrolled to where they need their attention
- disabled destination fields when the NTSR shipment has a pending destination address request
- let the TOO open up the destination address request modal for NTSR shipments
- minor CSS changes
- updated/added relevant tests to both backend and UI

### How to test

1. Fire up yer `client` & `server`
2. Find any shipment as a TOO (my fav is `SITEXT`) and add on a NTSR shipment
3. Fill out all of the necessary information
4. Make sure you approve the shipment (this makes it available to the Prime)
5. Go into the Prime Simulator, find the shipment inside the move, and click the `Update Shipment Destination Address` button
6. Fill out the form with an address that's hecka far away from the current ZIP, save it
7. Go into the same move as the TOO and you should see the shipment have a `Review required` where the NTSR's destination address should be
8. Go through the flow and either approve/reject the shipment (approving changes the address)
9. Now go through steps again and change the ZIP to be somewhere or the same ZIP - you shouldn't need approval from the TOO now since the business rules don't change

## Screenshots
![Screenshot 2024-07-29 at 11 08 58 AM](https://github.com/user-attachments/assets/1c3869a3-fe9b-4687-9471-53c33977f84a)

https://github.com/user-attachments/assets/42470d73-6ff0-4933-8bc9-0880e1813bf3

2024-07-30 14:33 UTC, TevinAdams commented on pkg/services/shipment_address_update/shipment_address_update_requester.go
> +		return nil, apperror.NewUnprocessableEntityError("destination address update requests can only be created for HHG and NTSr shipments")
Is the r in NTSr meant to be lower case or did you mean NTSR?

2024-07-30 14:48 UTC, TevinAdams commented
@danieljordan-caci I created an NTS shipment with zipcode 75126 TX, Approved as TOO, and then updated the destination address as the prime to 29229, SC. Went back to see the destination address status and noticed that destination address isn't showing up on the shipment like HHG shipments. Am I doing something incorrectly?
![image](https://github.com/user-attachments/assets/0252c3d2-5fea-4fa5-b2dd-098f368fdea0)

2024-07-30 14:50 UTC, danieljordan-caci commented
> @danieljordan-caci I created an NTS shipment with zipcode 75126 TX, Approved as TOO, and then updated the destination address as the prime to 29229, SC. Went back to see the destination address status and noticed that destination address isn't showing up on the shipment like HHG shipments. Am I doing something incorrectly? ![image](https://private-user-images.githubusercontent.com/136514590/353505860-0252c3d2-5fea-4fa5-b2dd-098f368fdea0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNTEzMjUsIm5iZiI6MTcyMjM1MTAyNSwicGF0aCI6Ii8xMzY1MTQ1OTAvMzUzNTA1ODYwLTAyNTJjM2QyLTVmZWEtNGZhNS1iMmRkLTA5OGYzNjhmZGVhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMFQxNDUwMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMGExZDk5YzdlMjdkMmRmMjUwZWYxMDZiMTE0MjJiMTI4YTQzZDYwOTc2Yzg0MmFiMDc2YzgxYzI0MDAzYjBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j_h7i2no2z5b1HG41XQpFuq9MO0oPM4cfmcZ40S4dZ8)

Delivery address == destination address

2024-07-30 14:52 UTC, TevinAdams commented
> > @danieljordan-caci I created an NTS shipment with zipcode 75126 TX, Approved as TOO, and then updated the destination address as the prime to 29229, SC. Went back to see the destination address status and noticed that destination address isn't showing up on the shipment like HHG shipments. Am I doing something incorrectly? ![image](https://private-user-images.githubusercontent.com/136514590/353505860-0252c3d2-5fea-4fa5-b2dd-098f368fdea0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNTEzMjUsIm5iZiI6MTcyMjM1MTAyNSwicGF0aCI6Ii8xMzY1MTQ1OTAvMzUzNTA1ODYwLTAyNTJjM2QyLTVmZWEtNGZhNS1iMmRkLTA5OGYzNjhmZGVhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMFQxNDUwMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMGExZDk5YzdlMjdkMmRmMjUwZWYxMDZiMTE0MjJiMTI4YTQzZDYwOTc2Yzg0MmFiMDc2YzgxYzI0MDAzYjBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j_h7i2no2z5b1HG41XQpFuq9MO0oPM4cfmcZ40S4dZ8)
> 
> Delivery address == destination address

Disregard i updated the wrong shipment.

2024-07-30 14:52 UTC, danieljordan-caci commented on pkg/services/shipment_address_update/shipment_address_update_requester.go
> +		return nil, apperror.NewUnprocessableEntityError("destination address update requests can only be created for HHG and NTSr shipments")
It's sometimes referred to like this in the code and sometimes NTSR. Don't mind changing it if you hate it haha

2024-07-30 14:58 UTC, TevinAdams commented on pkg/services/shipment_address_update/shipment_address_update_requester.go
> +		return nil, apperror.NewUnprocessableEntityError("destination address update requests can only be created for HHG and NTSr shipments")
Nope just making sure it was intended. Everything works and reviewed. Looks good.

2024-07-31 15:30 UTC, cameroncaci requested changes
Works like a charm, got a quick question on the API description though

2024-07-31 15:30 UTC, cameroncaci commented on swagger-def/prime.yaml
> +        For HHG shipments, if automatically approved or TOO approves, this will update the final destination address values for destination SIT service items to be the same as the changed destination
This mentions "should" but appears to be an explicit requirement - please correct if wrong

2024-07-31 15:35 UTC, cameroncaci commented on swagger-def/prime.yaml
> +        For HHG shipments, if automatically approved or TOO approves, this will update the final destination address values for destination SIT service items to be the same as the changed destination
Can we reword that to be "This endpoint and operation only supports the following shipment types:" 🫣

2024-07-31 15:41 UTC, danieljordan-caci commented on swagger-def/prime.yaml
> +        For HHG shipments, if automatically approved or TOO approves, this will update the final destination address values for destination SIT service items to be the same as the changed destination
You want it, you go it! Updated. Resolving comment.

2024-07-31 15:47 UTC, cameroncaci approved these changes
Works locally and meets AC 🚀

2024-07-31 16:05 UTC, merged