B 20673 int
transcom/mymove pull request #13350
Opened 2024-07-29 17:00 UTC by deandreJones

## [B-20673](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A982871)

## Summary

Will need new payment request status for TPPS RECEIVED
We send TPPS an invoice, EDI 858 with payment request information
TPPS will receive this information and send back an EDI 997
The receipt of an EDI 997 confirms that the TPPS has received the invoice
(TBD) An 824 will provide more detail in addition to the 997 for what errors, if any, came with the sending 
Based on data we receive about how TPPS pays HomeSafe (receiving the 997 (possibly receiving the 824), we will need to build backend logic for updating the status of the payment request to reflect those updates
UI portion: add the TPPS received status to PaymentRequestCard.jsx

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the office app
2. Login as a TIO
3. approve a payment request
4. SINCE files aren't sent to get locally or integration- the next step is to find that approved payment request and update the status to 'TPPS Received' 
5. verify the status updated on the UI

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots
![Screenshot 2024-07-29 at 11 45 59 AM](https://github.com/user-attachments/assets/5dcbf90e-a528-4397-82e6-1e10dda300e0)

2024-07-29 17:52 UTC, traskowskycaci requested changes
Looks good!

What do you think of modifying the "Accepted on" to be "Received on" with the received_by_gex_at date, assuming that column gets populated when we get the 997? Or if not, even just changing "Accepted on" to "Received"

If you pull in this [refactor commit](https://github.com/transcom/mymove/commit/a6b6f55ec8118870d7c123563381ea7cd9c3fdfe
) and add a case for if (paymentRequestStatus === PAYMENT_REQUEST_STATUS.TPPS_RECEIVED) you should be able to customize what that text says underneath

![image](https://github.com/user-attachments/assets/090204fe-8f2c-4b9d-83b8-214f00f2fce7)

2024-07-29 21:07 UTC, deandreJones commented
> Looks good!
> 
> What do you think of modifying the "Accepted on" to be "Received on" with the received_by_gex_at date, assuming that column gets populated when we get the 997? Or if not, even just changing "Accepted on" to "Received"
> 
> If you pull in this [refactor commit](https://github.com/transcom/mymove/commit/a6b6f55ec8118870d7c123563381ea7cd9c3fdfe) and add a case for if (paymentRequestStatus === PAYMENT_REQUEST_STATUS.TPPS_RECEIVED) you should be able to customize what that text says underneath
> 
> ![image](https://private-user-images.githubusercontent.com/147537467/353177932-090204fe-8f2c-4b9d-83b8-214f00f2fce7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyODc0NzAsIm5iZiI6MTcyMjI4NzE3MCwicGF0aCI6Ii8xNDc1Mzc0NjcvMzUzMTc3OTMyLTA5MDIwNGZlLThmMmMtNGI5ZC04M2I4LTIxNGYwMGYyZmNlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOVQyMTA2MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iM2I3NjJlMzBhOTZiNTQxMDkxMzBlYTE3NTM4OTE4NWUyY2U0NDZlNDMwNTQ3ZWRhMmEyN2JmZThhNDRhOWZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wpHML26guxUnMKW1pyxWx-ieyFkRXf0BlybKg-c3Q0E)

updated 
![image](https://github.com/user-attachments/assets/c1d6728c-09b7-4ae9-b2ff-311da1b850a0)

2024-07-29 21:59 UTC, traskowskycaci approved these changes
Looks great!

2024-07-30 15:11 UTC, TevinAdams commented on swagger-def/definitions/AdditionalDocuments.yaml
> +    type: stringmake s
Is this a typo?

2024-07-30 15:12 UTC, TevinAdams commented on swagger-def/definitions/AdditionalDocuments.yaml
> +    type: stringmake s
Is that supposed to be just string data type.

2024-07-30 15:50 UTC, deandreJones commented on swagger-def/definitions/AdditionalDocuments.yaml
> +    type: stringmake s
fixed

2024-07-30 16:01 UTC, TevinAdams approved these changes
Approved. Test case works and code reviewed. Went to DB and changed status of approved payment request to TPPS_RECEIVED and noticed the UI reflect that status for the payment request.

2024-07-30 16:18 UTC, merged