B 20639 nts loa fetching int
transcom/mymove pull request #13372
Opened 2024-07-31 19:40 UTC by cameroncaci

## [Agility ticket](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-20639)

## Summary
This ticket was rewritten after some NTS review. We're now introducing a new column to the move table to explicitly track when a move task order gets approved. Currently, the "MTO approved" timestamp is the `available_to_prime_at` database value, however in the future third party vendors may be available and NTS shipments will need a specific attribute just for MTO approval dates in order to look up the LOAs.

We are also retroactively applying this logic by setting the `approved_at` value on all existing MTOs to be equal to the `available_to_prime_at` value.

### How to test

1. Login as a new customer and create a new HHG move
2. Login as service counselor, review the order, and submit the move details
3. Login as task ordering officer and approve the requested move
4. Open your browser tools network tab -> refresh the page
5. Look for your move locator within the network tab, once found open it and verify a request URL of `ghc/v1/move/4C3XQM`
6. Read the response and verify that the attribute `approvedAt` is present and holds the same value as `availableToPrimeAt

### Database

#### Any new migrations/schema changes:

- [x] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [x] Excel sheet was updated

Zero-downtime not necessary as this does not affect existing columns

2024-08-02 14:49 UTC, traskowskycaci reviewed
Working properly and db matches what I see in the response!
![image](https://github.com/user-attachments/assets/b7299be1-4402-45f6-8389-c72ecd4fab79)
![image](https://github.com/user-attachments/assets/08faf3e4-d729-43d3-91b0-72531a78ee4e)

Not all of the approved_at values got updated when the available_to_prime_at values weren't null. Why would that be?
![image](https://github.com/user-attachments/assets/f7618b1c-64c4-4174-a00f-d727f4a637a7)

Last question is on the use of "effective." I know from your description that it's "the orders issue date or the Non-Temporary Storage (NTS) Move Task Order (MTO) approval date". But by "effective" do we mean effective for invoicing?

2024-08-02 14:53 UTC, cameroncaci commented
> Working properly and db matches what I see in the response! ![image](https://private-user-images.githubusercontent.com/147537467/354631319-b7299be1-4402-45f6-8389-c72ecd4fab79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MTA1OTUsIm5iZiI6MTcyMjYxMDI5NSwicGF0aCI6Ii8xNDc1Mzc0NjcvMzU0NjMxMzE5LWI3Mjk5YmUxLTQ0MDItNDVmNi04Mzg5LWM3MmVjZDRmYWI3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMlQxNDUxMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzc0NzM1OGM3ODU4MmFiMjVhNzg4NDFkNWEwM2JmOTBjZTJjZWQxMzU3ZjZlMDFkY2Q4NDkyMWMwZjcwMDE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.R_0WJ03xd2uGB5YTc3ahHJcltK_vh1Y_DuKfGXjB-gA) ![image](https://private-user-images.githubusercontent.com/147537467/354631861-08faf3e4-d729-43d3-91b0-72531a78ee4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MTA1OTUsIm5iZiI6MTcyMjYxMDI5NSwicGF0aCI6Ii8xNDc1Mzc0NjcvMzU0NjMxODYxLTA4ZmFmM2U0LWQ3MjktNDNkMy05MWIwLTcyNTMxYTc4ZWU0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMlQxNDUxMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMDQ0NmU3OWJlNTk0YzA0ZDNhODczY2E3OTE1ZTE2OTBkNTUwNjVhMzQyNDIwOGY2YmU0ZjM2NzE3NzFlY2M4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2k-DaHI-Vyt9az8U91BxN8JIJXeGMIctrNfln_rkxJU)
> 
> Not all of the approved_at values got updated when the available_to_prime_at values weren't null. Why would that be? ![image](https://private-user-images.githubusercontent.com/147537467/354632710-f7618b1c-64c4-4174-a00f-d727f4a637a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MTA1OTUsIm5iZiI6MTcyMjYxMDI5NSwicGF0aCI6Ii8xNDc1Mzc0NjcvMzU0NjMyNzEwLWY3NjE4YjFjLTY0YzQtNDE3NC1hMDBmLWQ3MjdmNGE2MzdhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMlQxNDUxMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NmE1NDVhYmY0NzYwY2RjOTlhNzI1N2UzODEwN2YzYzhlNDc3MzcxZmU5OTk1ODZhZDFjNzM0MDY2NzkyZWE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.om5MoVja7eHgoo_A31X2n9LYf6dWtzSLrCmDfdmO_Lw)
> 
> Last question is on the use of "effective." I know from your description that it's "the orders issue date or the Non-Temporary Storage (NTS) Move Task Order (MTO) approval date". But by "effective" do we mean effective for invoicing?

I've begun rewording "Orders Issue Date" to be the "Effective Date" as the parameter is really only used as the filter between TAC and LOA begin and ending dates. This is mainly because NTS is about to use this endpoint and they don't use orders issue date, they use either the current day of review or the day in which the MTO was approved. Wasn't sure of another term to use

2024-08-02 16:02 UTC, traskowskycaci approved these changes
Updated docs look great, appreciate the extra detail on the effective date!

Also discussed the issue of not all approved_at values getting updated with Cameron. Believe it's a non-issue and could be due to timing of seed data vs migration running. Not a big deal, won't impact NTS LOA fetching functionality.

Nice work!

2024-08-02 19:09 UTC, danieljordan-caci requested changes
One little migration change and I'll stamp ya

2024-08-02 19:09 UTC, danieljordan-caci commented on migrations/app/schema/20240729200347_add_mto_approved_at_timestamp.up.sql
> +ADD COLUMN approved_at timestamp with time zone;
Can you add `IF NOT EXISTS` to this migration file?

2024-08-06 12:40 UTC, cameroncaci commented on migrations/app/schema/20240729200347_add_mto_approved_at_timestamp.up.sql
> +ADD COLUMN approved_at timestamp with time zone;
Added

2024-08-06 18:08 UTC, danieljordan-caci approved these changes

2024-08-07 13:42 UTC, merged