Merged conflicts - resolved
transcom/mymove pull request #13376
Opened 2024-08-01 00:27 UTC by JonSpight

## [Agility ticket](tbd)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](https://dp3.atlassian.net/wiki/spaces/MT/pages/2566258689/MilMove+Final+Onboarding+Task) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [x] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

**Service Member**
1. Access milmovelocal
2. Create a new user
3. Fill out the required fields, "next" button should now be enabled
4. Input a preferred name that consists of letters and numbers, "next" button should now be disabled
5. Click outside of the preferred name, an error message should be displayed
6. Input a preferred name that consist of only letters, error message is gone and "Next" button is now enabled
7. Once service member information is complete verify preferred name is in the user section
8. Edit the user's preferred name and save changes.
9. Once service member information is saved verify changes are in the user section.

**Office Member**
1. Access officelocal
2. Sign in as a service counselor
3. Search customer
4. In the customer info section verify preferred name is visible

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-08-01 18:03 UTC, danieljordan-caci commented
Couple things on the PR level:
- make sure that you are assigning yourself the the PR
- make sure you're adding labels to the PR (this one would be INTEGRATION & your team name)

One thing that was missed on this was letting the office user update the customer. This is what I see when viewing Customer Info as the TOO:
![Screenshot 2024-08-01 at 1 02 00 PM](https://github.com/user-attachments/assets/75dc4b3b-1e79-4175-aedf-e9a94bbde489)


Unable to edit:
![Screenshot 2024-08-01 at 1 02 18 PM](https://github.com/user-attachments/assets/98390a45-ffdf-48fa-8a35-55c4d9795c53)


Could you add that edit functionality (as well as a test) and the labels? Thanks!

2024-08-01 18:03 UTC, danieljordan-caci requested changes
Re-request once the changes are complete please!

2024-08-02 15:50 UTC, deandreJones commented
> Couple things on the PR level:
> 
> * make sure that you are assigning yourself the the PR
> * make sure you're adding labels to the PR (this one would be INTEGRATION & your team name)
> 
> One thing that was missed on this was letting the office user update the customer. This is what I see when viewing Customer Info as the TOO: ![Screenshot 2024-08-01 at 1 02 00 PM](https://private-user-images.githubusercontent.com/136510600/354331130-75dc4b3b-1e79-4175-aedf-e9a94bbde489.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MTQwMjQsIm5iZiI6MTcyMjYxMzcyNCwicGF0aCI6Ii8xMzY1MTA2MDAvMzU0MzMxMTMwLTc1ZGM0YjNiLTFlNzktNDE3NS1hZWRmLWU5YTk0YmJkZTQ4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMlQxNTQ4NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDY0OTY0NTIwMDkxNThiNGQ0ZWI1NjJlMTk5MTcwZGJlMmJlYTZmYjRkMTY1Zjg1ZDllYmRmNmUxMzllNGFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6dZi7_UUYEkSzeJfuTPqkVbx7Vkuw0pDhE85eSSyEv4)
> 
> Unable to edit: ![Screenshot 2024-08-01 at 1 02 18 PM](https://private-user-images.githubusercontent.com/136510600/354331165-98390a45-ffdf-48fa-8a35-55c4d9795c53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MTQwMjQsIm5iZiI6MTcyMjYxMzcyNCwicGF0aCI6Ii8xMzY1MTA2MDAvMzU0MzMxMTY1LTk4MzkwYTQ1LWZmZGYtNDhmYS04YTM1LTU1YzRkOTc5NWM1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMlQxNTQ4NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yN2FlODdhNzZmMDI5ZjgxZmZiMzY0YzI0ODgyMWNiMDlkNTJkZDhjNTI5OGE0N2UyYjBkZDQ4ODQ3YmJiYWRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SSmTOdQcBgT6WZ6SKTGmXktykR1Jp2k0gZiSSor9fYY)
> 
> Could you add that edit functionality (as well as a test) and the labels? Thanks!

label for this PR would be ONBOARDING, but in a normal case - you would add your team and the branch its going to(main or integration)

2024-08-06 19:45 UTC, danieljordan-caci approved these changes
Overall, really good stuff! 

Solid code and I hope you learned a lot from the onboarding task! Happy to have you on the team and excited to see what all you accomplish here at MilMove!

I'll approve this, but please don't merge it. Dre will close the PR once he feels content.

2024-08-06 19:45 UTC, danieljordan-caci commented on migrations/app/schema/20240731205120_add_preferred_name_to_service_member.up.sql
> +COMMENT ON COLUMN service_members.preferred_name IS 'Service Members preffered Name.';
Make sure you watch out for misspellings - got one here. `preffered` should be `preferred`

2024-08-06 19:45 UTC, danieljordan-caci commented on pkg/models/service_member.go
> +	PreferredName          *string                   `json:"preferred_name" db:"preferred_name"`
Nice job making this a pointer!

2024-08-06 19:45 UTC, danieljordan-caci commented on pkg/services/office_user/customer/customer_updater.go
> +
Not a huge deal here, but could easily combine this with to make it a little more concise:
```
if customer.PreferredName != nil && len(*customer.PreferredName) == 0 {
    existingCustomer.PreferredName = nil
} else if customer.PreferredName != nil {
    existingCustomer.PreferredName = customer.PreferredName
}
```

2024-08-06 19:45 UTC, danieljordan-caci commented on src/components/Customer/NameForm/NameForm.jsx
> +    preferred_name: Yup.string().matches(/^[aA-zZ\s]+$/, 'Preferred Name must only contain letters.'),
Nice validation

2024-08-06 19:45 UTC, danieljordan-caci commented on src/components/form/CustomerAltContactInfoFields/index.jsx
> +            </div>
Nice job putting in the `optional` hint

2024-08-06 22:07 UTC, loganwc commented on src/components/Customer/NameForm/NameForm.jsx
> +    preferred_name: Yup.string().matches(/^[aA-zZ\s]+$/, 'Preferred Name must only contain letters.'),
We maybe want `\p{L}` for the regex because there are a lot of people with accent marks in their names 🤔 or even maybe a -

2024-08-07 12:42 UTC, joeydoyecaci approved these changes

2024-08-07 12:42 UTC, joeydoyecaci commented on src/components/Customer/NameForm/NameForm.jsx
> +    preferred_name: Yup.string().matches(/^[aA-zZ\s]+$/, 'Preferred Name must only contain letters.'),
agree with logan on the accent marks. not a show stopper by any stretch. but nice job on the regex regardless though.

2024-08-07 14:42 UTC, deandreJones commented
good work, looks good

2024-08-07 14:42 UTC, closed without merging