B-20767 EDI Error Display Int
transcom/mymove pull request #13382
Opened 2024-08-01 21:04 UTC by traskowskycaci

## [Agility ticket](tbd)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-08-02 16:25 UTC, danieljordan-caci requested changes
Some minor CSS changes and one suggestion - other than that it looks good!

2024-08-02 16:25 UTC, danieljordan-caci commented on src/components/Office/PaymentRequestCard/PaymentRequestCard.module.scss
> +  @include u-padding-bottom(2);
What you could do (and I've tested) is dynamically assign class names based off of the chevron arrow.

CSS:
```
.ediErrorDetailsCondensed {
  border-bottom: 1px solid #dcdee0;
  @include u-padding-bottom(2);
}

.ediErrorDetailsExpand {
  border-bottom: 1px solid #dcdee0;

  .ediHeaders {
    @include u-font-size('body', '3xs');
    color: $base;
    th {
      font-weight: bolder;
    }
  }

  .amountAccepted {
    @include u-display(flex);
    align-items: center;
    margin-right: 6em;

    svg {
      @include u-margin-right(2);
      height: 24px;
      width: 24px;
      path {
        fill: $success;
      }
    }
  }
}
```

Then your render:
```
      return (
        <div
          className={
            showErrorDetailsChevron === 'chevron-up' ? styles.ediErrorDetailsExpand : styles.ediErrorDetailsCondensed
          }
        >
...theRestOfYourCode
```

Now it'd purdy
https://github.com/user-attachments/assets/53b90ff7-51b3-4803-989a-45c169425c9b

2024-08-02 16:25 UTC, danieljordan-caci commented on src/components/Office/PaymentRequestCard/PaymentRequestCard.module.scss
> +  @include u-padding-bottom(2);
Also changed your EDI headers to be more distinct as headers (see the added `ediHeaders` class)

2024-08-02 18:04 UTC, traskowskycaci commented on src/components/Office/PaymentRequestCard/PaymentRequestCard.jsx
> +
I like that - modified it! No longer passing the payment request to renderEDIErrorDetails().

2024-08-02 18:05 UTC, traskowskycaci commented on src/components/Office/PaymentRequestCard/PaymentRequestCard.module.scss
> +  @include u-padding-bottom(2);
Modified this as well, appreciate the suggestion!

2024-08-02 18:59 UTC, danieljordan-caci approved these changes
LGTM!

2024-08-06 14:37 UTC, TevinAdams approved these changes
Tested and reviewed

2024-08-06 14:51 UTC, cameroncaci requested changes
Tested successfully. Code changes requested

2024-08-06 14:51 UTC, cameroncaci commented on swagger-def/ghc.yaml
> +        type: string
Can we set these to be `x-nullable: true` as it is possible to be empty strings?

2024-08-06 14:51 UTC, cameroncaci commented on pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
> +}
Could we move this to a service object? DB queries are service-level actions and this is within the handler package

2024-08-12 13:42 UTC, traskowskycaci commented on pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
> +}
100% agree that didn't belong in the handler! Started off on the path of making a new service object for fetching the edi, but switched plans and added it to the payment request fetcher since they're tied to the payment request. Good catch! Fix: https://github.com/transcom/mymove/pull/13382/commits/ac4288171408dfd24aac007e2c1e38bf7a129c1f

2024-08-12 14:00 UTC, cameroncaci approved these changes

2024-08-12 14:29 UTC, merged