INT B-20447 FIX: Customer Search Sorting Tweaks
transcom/mymove pull request #13403
Opened 2024-08-06 17:55 UTC by brooklyn-welsh

## [Agility ticket](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-20447)

## Original INT PR
#13381 

## Summary

In the original PR, sorting by Branch, phone, etc, would override the exact name matches in the name column, i.e.; results with Air Force branch would always come first regardless of match similarity with the given name search string. PO clarified that exact matches should still take precedent even when sorting via another column.

So, the search SQL query has been edited to always take match similarity into account first, i.e. if a result from the "Navy" branch is a closer match than a result from "Air Force", the "Navy" one should show up at the top anyway. The sort will instead affect the groups where match similarity is the same.

Also, matches were originally calculating match between first and last name separately, which led to some incorrect results. Now, it takes the similarity of the search string with both fields and gets the sum, ensuring that the closest match is always at the top.

Finally, since we are now calculating a "total_sim" field from values given in the SELECT, the Pop ORM expects a "total_sim" field to be defined in a model struct. But just adding this to the existing "ServiceMember" struct breaks any queries that EagerPreload any object that contains a ServiceMember, since it tries to find this field in the DB but it doesn't actually exist. This is why I added a "ServiceMemberSearchResult" struct to be used whenever we want to use the similarity score in a search query.

To test, search for a string (for example "submitted" is a good on for the test dataset), and ensure that closest matches are always first. Then sort via any column in the table and ensure that the sorting only affects results in groups, meaning that exact/closest matches should still be closer to the top of the results.

2024-08-06 19:21 UTC, KonstanceH approved these changes
LGTM

2024-08-06 19:59 UTC, taeJungCaci approved these changes
LGTM

2024-08-06 20:04 UTC, taeJungCaci requested changes
Looks like test file is failing tho

2024-08-07 19:42 UTC, taeJungCaci approved these changes

2024-08-07 23:28 UTC, merged