B-20671 Parse TPPS Paid Invoice Report INT
transcom/mymove pull request #13434
Opened 2024-08-09 17:01 UTC by traskowskycaci

## [Agility ticket](tbd)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-08-12 15:39 UTC, cameroncaci commented on pkg/services/invoice/tpps_paid_invoice_report_testfile.csv
Requesting that this file be placed inside a folder called `fixtures`. Such as `services/invoice/fixtures/`.

2024-08-12 15:52 UTC, cameroncaci commented on pkg/models/tpps_paid_invoice_report.go
This needs a test file

2024-08-12 16:14 UTC, TevinAdams commented on pkg/edi/tpps_paid_invoice_report/parser.go
> +		// If we have reached a NULL or empty row at the end of the file, do not continue parsing
Has it been verified that the end of file is a null or empty row? As in there are no circumstances or situations where a non empty row or non null row will come after a null or empty one.

2024-08-12 16:20 UTC, traskowskycaci commented on pkg/edi/tpps_paid_invoice_report/parser.go
> +		// If we have reached a NULL or empty row at the end of the file, do not continue parsing
The two files provided to be end with an empty row - check out the Agility attachments to double check me. Gotta go off of those two examples since that's what we were given.

2024-08-12 16:20 UTC, traskowskycaci commented
Working on peer review feedback now @cameroncaci

2024-08-13 22:43 UTC, traskowskycaci commented on pkg/models/tpps_paid_invoice_report.go
[Resolution](https://github.com/transcom/mymove/pull/13434/commits/13174d68974e96bc392e9b73ee8e59da15ee8622)

2024-08-13 22:44 UTC, traskowskycaci commented on pkg/services/invoice/process_tpps_paid_invoice_report.go
> +			}
[Resolution](https://github.com/transcom/mymove/pull/13434/commits/9fa33e8bdca009e5e39b0bf8206aecbaf2e9e820)

2024-08-13 22:44 UTC, traskowskycaci commented on pkg/services/invoice/tpps_paid_invoice_report_testfile.csv
[Moved](https://github.com/transcom/mymove/pull/13434/commits/ec06c72f17e473cd092b030e77d4cef7340b1e8b)

2024-08-13 22:45 UTC, traskowskycaci commented on pkg/models/tpps_paid_invoice_report.go
> +}
Cleaned this up [here](https://github.com/transcom/mymove/pull/13434/commits/7c3355ae705ec5ef892c62e163f88fa4b1462130)

Later commits also touched same area, please review overall file again in addition to this commit

2024-08-13 22:46 UTC, traskowskycaci commented on pkg/edi/tpps_paid_invoice_report/parser_test.go
> +9436-4123-3	2024-07-29	2024-07-30	125.25	DDP	DDP	7500	0.0167	125.25	9436-4123-93761f93	1                   	INT                                                                        	Notes to My Com
[Resolution](https://github.com/transcom/mymove/pull/13434/commits/0f667643d20b7015a44cfd97939c95d4913bf472)

2024-08-13 22:46 UTC, traskowskycaci commented on pkg/edi/tpps_paid_invoice_report/parser.go
> +func ParseTPPSReportEntryForOneRow(row []string) TPPSData {
[Resolution](https://github.com/transcom/mymove/pull/13434/commits/d0a097ff7cbe6ae96016ab18aa42c0acc656b347)

2024-08-13 22:46 UTC, traskowskycaci commented on pkg/edi/tpps_paid_invoice_report/parser.go
> +}
[Resolution](https://github.com/transcom/mymove/pull/13434/commits/6f680948b60c91a3893262e0ecc576dfae021a25)

2024-08-13 22:47 UTC, traskowskycaci commented on pkg/edi/tpps_paid_invoice_report/parser.go
> +		dataToParse = csvFile
[Resolution](https://github.com/transcom/mymove/pull/13434/commits/51951dffa99f2ae13447f3168b5bbfcde328691a)

2024-08-13 22:51 UTC, traskowskycaci commented
> Working on peer review feedback now 

Alright check it out when you get a chance @cameroncaci, organized feedback work with commits so it'll be easier to review again. Thanks again for the thorough review, I appreciate it!

2024-08-14 14:31 UTC, cameroncaci approved these changes

2024-08-14 14:51 UTC, danieljordan-caci requested changes
Some questions

2024-08-14 14:51 UTC, danieljordan-caci commented on migrations/app/schema/20240802161708_tpps_paid_invoice_table.up.sql
> +COMMENT on COLUMN tpps_paid_invoice_reports.product_description IS 'Reservice code for the service item';
These supposed to be the same thing?

2024-08-14 14:51 UTC, danieljordan-caci commented on pkg/cli/gex_sftp.go
> +	// flag.String(SFTPTPPSPaidInvoiceReportPickupDirectory, "", "TPPS Paid Invoice SFTP Pickup Directory") // pending completion of B-20560
I'll let these commented out lines slide but I SAW 'EM

2024-08-14 14:51 UTC, danieljordan-caci commented on pkg/models/tpps_paid_invoice_report.go
> +}
Looking at this struct and then the db - should we be addressing pointers?
```
CREATE TABLE IF NOT EXISTS tpps_paid_invoice_reports (
     id uuid NOT NULL,
     invoice_number varchar NOT NULL,
     tpps_created_doc_date timestamp,
     seller_paid_date timestamp NOT NULL,
     invoice_total_charges_in_millicents integer NOT NULL,
     line_description varchar NOT NULL,
     product_description varchar NOT NULL,
     line_billing_units integer NOT NULL,
     line_unit_price_in_millicents integer NOT NULL,
     line_net_charge_in_millicents integer NOT NULL,
     po_tcn varchar NOT NULL,
     line_number varchar NOT NULL,
     first_note_code varchar,
     first_note_description varchar,
     first_note_to varchar,
     first_note_message varchar,
     second_note_code varchar,
     second_note_description varchar,
     second_note_to varchar,
     second_note_message varchar,
     third_note_code varchar,
     third_note_code_description varchar,
     third_note_code_to varchar,
     third_note_code_message varchar,
     created_at timestamp not null,
     updated_at timestamp not null
);
```

The db has the following columns that can be `NULL`:
`tpps_created_doc_date`
`first_note_code`
`first_note_description`
`first_note_to`
`second_note_message`
`third_note_code`
`third_note_code_to`
`third_note_code_message`

Shouldn't these be pointers in this struct?

2024-08-14 14:54 UTC, traskowskycaci commented on pkg/cli/gex_sftp.go
> +	// flag.String(SFTPTPPSPaidInvoiceReportPickupDirectory, "", "TPPS Paid Invoice SFTP Pickup Directory") // pending completion of B-20560
Intentional on these actually - will uncomment when we get to 20560

2024-08-14 14:54 UTC, traskowskycaci commented on migrations/app/schema/20240802161708_tpps_paid_invoice_table.up.sql
> +COMMENT on COLUMN tpps_paid_invoice_reports.product_description IS 'Reservice code for the service item';
Yep! Both come through from the report the same.

2024-08-14 14:55 UTC, danieljordan-caci commented on pkg/cli/gex_sftp.go
> +	// flag.String(SFTPTPPSPaidInvoiceReportPickupDirectory, "", "TPPS Paid Invoice SFTP Pickup Directory") // pending completion of B-20560
Resolving convo!

2024-08-14 14:56 UTC, danieljordan-caci commented on migrations/app/schema/20240802161708_tpps_paid_invoice_table.up.sql
> +COMMENT on COLUMN tpps_paid_invoice_reports.product_description IS 'Reservice code for the service item';
Aight den. Resolving

2024-08-14 16:34 UTC, traskowskycaci commented on pkg/models/tpps_paid_invoice_report.go
> +}
[Resolution](https://github.com/transcom/mymove/pull/13434/commits/3a297669b75e7abc8e7d91f4731142039d6e168f)

2024-08-14 16:35 UTC, traskowskycaci commented on pkg/edi/tpps_paid_invoice_report/parser.go
> +		// If we have reached a NULL or empty row at the end of the file, do not continue parsing
@TevinAdams did you have any more questions? I added a comment to pkg/edi/tpps_paid_invoice_report/parser_test.go that outlines the delimiters and the end of the file.

2024-08-14 16:39 UTC, danieljordan-caci approved these changes
beaut

2024-08-14 17:48 UTC, merged