B 20621 mobile shipment ap is int 2
transcom/mymove pull request #13456
Opened 2024-08-13 16:19 UTC by KonstanceH

## [Agility ticket](tbd)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-08-13 20:11 UTC, taeJungCaci reviewed
Missing Feature flag in `config/env/loadtest.app.env`

2024-08-13 21:26 UTC, taeJungCaci requested changes

2024-08-13 21:26 UTC, taeJungCaci commented on pkg/handlers/ghcapi/mto_shipment.go
> +			featureFlagNameMH := "mobileHome"
This might have to be `mobile_home`

2024-08-13 21:26 UTC, taeJungCaci commented on pkg/handlers/internalapi/moves.go
> +				featureFlagNameMH := "mobileHome"
same with here.

2024-08-13 21:26 UTC, taeJungCaci commented on pkg/handlers/internalapi/mto_shipment.go
> +			featureFlagNameMH := "mobileHome"
same

2024-08-13 21:26 UTC, taeJungCaci commented on pkg/handlers/primeapi/move_task_order.go
> +			featureFlagNameMH := "mobileHome"
same

2024-08-13 21:26 UTC, taeJungCaci commented on pkg/handlers/primeapiv2/move_task_order.go
> +			featureFlagNameMH := "mobileHome"
same

2024-08-13 21:26 UTC, taeJungCaci commented on pkg/handlers/primeapiv3/move_task_order.go
> +			featureFlagNameMH := "mobileHome"
same

2024-08-13 21:26 UTC, taeJungCaci commented on pkg/services/mobile_home_shipment/rules.go
> +				verrs.Add("lengthInInches", "One of these criteria must be met for it to be a mobile home shipment: lengthInInches > 168, widthInInches > 82, or heightInInches > 77.")
I think the validations for mobile home is different. Might want to check if there is one.

2024-08-13 21:27 UTC, taeJungCaci commented on migrations/app/schema/20240813153431_change_mobile_home_shipment_deleted_at_type.up.sql
> +ALTER TABLE mobile_homes ALTER COLUMN deleted_at drop not NULL
and don't forget to make these changes from your Main branch plz

2024-08-13 21:33 UTC, taeJungCaci requested changes
I think you may also have to add mobile home to `pkg/models/mto_shipments.go` model

2024-08-16 15:58 UTC, taeJungCaci requested changes

2024-08-16 15:58 UTC, taeJungCaci commented on pkg/services/mto_service_item/mto_service_item_updater.go
I think we want to keep these changes - I don't see these changes in the revert PR.

2024-08-16 15:58 UTC, taeJungCaci commented on pkg/services/mto_service_item/mto_service_item_updater_test.go
Same with these

2024-08-16 15:58 UTC, taeJungCaci commented on pkg/services/mto_service_item/mto_service_item_validators.go
same with these

2024-08-16 15:58 UTC, taeJungCaci commented on pkg/services/mto_service_item/mto_service_item_validators_test.go
same with these

2024-08-16 15:58 UTC, taeJungCaci commented on playwright/tests/office/servicescounseling/servicesCounselingNTS.spec.js
same with these

2024-08-16 15:58 UTC, taeJungCaci commented on playwright/tests/office/txo/tooFlowsNTS.spec.js
same with these

2024-08-16 16:06 UTC, taeJungCaci requested changes

2024-08-16 16:06 UTC, taeJungCaci commented on migrations/app/migrations_manifest.txt
> -20240731125005_retroactively_update_approve_at_column_based_on_available_to_prime.up.sql
I think the plan might be to keep these in - they added a new migration file to remove these

2024-08-19 13:56 UTC, KonstanceH commented
> pkg/models/mto_shipments.go

I have it added in that file from the Backend/DB PR.

2024-08-19 17:32 UTC, taeJungCaci approved these changes
LGTM!

2024-08-19 17:35 UTC, taeJungCaci submitted a review, later dismissed
I forgot to add - could you add a `?` to `switch (shipmentType?.toUpperCase()) {` line 185 in ShipmentList.jsx please? It is something I've missed for mine and the app errors out if I create a shipment and try to view it in the UI. I know UI does not matter for this story, but I think for testing/POA purposes, they may want to see it populate and not crash.

2024-08-19 17:54 UTC, brooklyn-welsh approved these changes
Looks like all the changes were made and went through okay, LGTM!

2024-08-19 19:10 UTC, taeJungCaci approved these changes

2024-08-19 19:17 UTC, taeJungCaci reviewed
I didn't wanna stop the PR for this, but just FYI - Adding a `?` to `switch (shipmentType?.toUpperCase()) { ` line 185 in ShipmentList.jsx  will stop the customer app from crashing when getting shipments after doing creating a mobile shipment.

2024-08-19 19:23 UTC, KonstanceH commented
> I didn't wanna stop the PR for this, but just FYI - Adding a `?` to `switch (shipmentType?.toUpperCase()) { ` line 185 in ShipmentList.jsx will stop the customer app from crashing when getting shipments after doing creating a mobile shipment.

ah okay. That's no problem since I can't merge into integration now anyway haha. I'll make the change and push it up now

2024-08-20 19:54 UTC, merged