https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-20440
transcom/mymove pull request #13487
Opened 2024-08-16 17:41 UTC by WeatherfordAaron

## [B-20440](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-20440)
## [B-20438](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-20438)

## All ACs Summarized into 1 statement
- Office users that can currently see uploads related to documents should be able to rotate and zoom on image uploads.
- Office users that can currently see uploads related to documents should be able to save any rotational changes they make to image uploads. This means when other office users look at those same image uploads, the rotational changes will also show for them (also when users Refresh the page, the rotational changes should not revert as long as they have saved the rotation).

## Additional criteria based on dev findings during implementation
- When a customer or an office user adds uploads, they should be able to have a mixed bag of file types (i.e. png, jpg/jpeg, gif, or pdf) and be able to select between those files without errors. Also, during those selection changes rotational changes that are not saved, should revert.. rotational changes that are saved should not revert.
- When saving the rotation of an image, the selected file should stay on the file you just saved the rotation for
- When the rotation from the DB and the rotation of the shown image are the same, the "Save" button on the image controls (at the bottom of the doc viewer) should show as disabled.

## Project set up for this review
1. Checkout this branch and in the root folder of the project, run the following commands.
```yarn cache_clean```
```yarn clean```
2. Open the project's package.json file and verify that under the dependancies section, the line for @transcom/react-file-viewer looks like this:
`"@transcom/react-file-viewer": "git+https://github.com/transcom/react-file-viewer#B20440-amw-zoom-rotate-capability-for-images",`

2024-08-16 20:42 UTC, JamesHawks224 commented on migrations/app/schema/20240806230447_add_rotation_to_uploads.up.sql
> +ALTER TABLE uploads ADD COLUMN IF NOT EXISTS rotation INTEGER;
"INTEGER"... is it possible someday to use floats for the rotation e.g. 40.3?

2024-08-16 20:47 UTC, JamesHawks224 commented on swagger-def/ghc.yaml
> +          description: Successfully retrieved order
Should "order" be changed.  This api is in regards to "uploads" not just "orders"

2024-08-16 20:48 UTC, JamesHawks224 commented on swagger/ghc.yaml
> +          description: Successfully retrieved order
Should "order" be changed. This api is in regards to "uploads" not just "orders"

2024-08-16 20:49 UTC, JamesHawks224 commented on yarn.lock
> +"@transcom/react-file-viewer@git+https://github.com/transcom/react-file-viewer#B20440-amw-zoom-rotate-capability-for-images":
I'm not familiar w/yarn lock.  Why is it a branch name instead of a version #?

2024-08-16 20:53 UTC, JamesHawks224 commented on yarn.lock
> +  integrity sha512-Ajr4IcMXq/2QmMkEmSvxqfLN5zGmJ92gHXAeOXq1OekoH2rfDNsgdDoL2f7QaRCy7G/E6TpxBVdRuNraMztGHw==
"sha1" and "sha512".  I assume this means they used different encryptions. Has it been verified that changing the encryptions won't potentially impact something else? 

Here's what AI said:
Yes, there are both SHA-1 and SHA-512 hash functions, and there are significant differences between the two.

### SHA-1
- **Bit Length**: SHA-1 produces a 160-bit hash value, represented as a 40-digit hexadecimal number[2][3].
- **Security**: SHA-1 is considered to be less secure due to vulnerabilities that have been discovered over time, making it susceptible to collision attacks (where two different inputs produce the same hash)[3][4].
- **Usage**: It was widely used in the past for digital signatures and SSL certificates but has been deprecated in favor of more secure algorithms[4].

### SHA-512
- **Bit Length**: SHA-512 generates a 512-bit hash value, providing a much larger hash size compared to SHA-1[2][4].
- **Security**: It is significantly more secure than SHA-1 due to its larger bit size and resistance to collision attacks. It is part of the SHA-2 family, which includes several other hash functions with varying bit lengths[2][4][6].
- **Usage**: SHA-512 is used in scenarios where higher security is required, although it requires more processing power due to its complexity[4][6].

### Key Differences
- **Security**: SHA-512 is more secure than SHA-1, which is now considered obsolete due to its vulnerabilities[4].
- **Performance**: SHA-1 is faster but less secure, while SHA-512 offers higher security at the cost of being slower[4].
- **Hash Size**: The larger hash size of SHA-512 provides better security and is less prone to collisions compared to SHA-1[4].

Overall, SHA-512 is recommended for applications requiring strong security, whereas SHA-1 is generally not recommended due to its security weaknesses.

2024-08-16 20:53 UTC, WeatherfordAaron commented on migrations/app/schema/20240806230447_add_rotation_to_uploads.up.sql
> +ALTER TABLE uploads ADD COLUMN IF NOT EXISTS rotation INTEGER;
rotation is between 0 and 3 since i don't want them rotating like 45 degrees and stuff

2024-08-16 20:53 UTC, WeatherfordAaron commented on swagger-def/ghc.yaml
> +          description: Successfully retrieved order
order had to be changed because that's one of the ways it gets the uploads

2024-08-16 20:55 UTC, JamesHawks224 requested changes
testing: success
code: no show stoppers, but I did have questions.

2024-08-16 20:57 UTC, WeatherfordAaron commented on yarn.lock
> +"@transcom/react-file-viewer@git+https://github.com/transcom/react-file-viewer#B20440-amw-zoom-rotate-capability-for-images":
version number was pointing at a specific commit.. I willl do the same thing whenever we do that PR

2024-08-16 20:58 UTC, WeatherfordAaron commented on yarn.lock
> +  integrity sha512-Ajr4IcMXq/2QmMkEmSvxqfLN5zGmJ92gHXAeOXq1OekoH2rfDNsgdDoL2f7QaRCy7G/E6TpxBVdRuNraMztGHw==
yarn.lock is auto generated

2024-08-16 21:05 UTC, brooklyn-welsh approved these changes
LGTM ✅

2024-08-16 21:09 UTC, WeatherfordAaron commented
> testing: success code: no show stoppers, but I did have questions.

The main reply I have is that yarn.lock is auto-generated when you do a yarn install.. it takes what's in package.json and makes a file from that. Technically, it may not even be important for us to merge that in but ultimately a dev would have to delete their yarn.lock and run yarn install to make it generate again which would generate a file that looks identical to that one (I believe)

2024-08-16 21:14 UTC, JamesHawks224 commented on swagger-def/ghc.yaml
> +          description: Successfully retrieved order
What I mean is... the text description... so this isn't orders only, should the text description change?

2024-08-16 21:14 UTC, JamesHawks224 commented on yarn.lock
> +"@transcom/react-file-viewer@git+https://github.com/transcom/react-file-viewer#B20440-amw-zoom-rotate-capability-for-images":
k.

2024-08-16 21:15 UTC, JamesHawks224 commented on yarn.lock
> +  integrity sha512-Ajr4IcMXq/2QmMkEmSvxqfLN5zGmJ92gHXAeOXq1OekoH2rfDNsgdDoL2f7QaRCy7G/E6TpxBVdRuNraMztGHw==
k.  there you go.  :)

2024-08-16 21:16 UTC, JamesHawks224 commented on migrations/app/schema/20240806230447_add_rotation_to_uploads.up.sql
> +ALTER TABLE uploads ADD COLUMN IF NOT EXISTS rotation INTEGER;
Per my understanding, the software only accepts integers hence float is not a concern.

2024-08-19 09:55 UTC, WeatherfordAaron commented on swagger/ghc.yaml
> +          description: Successfully retrieved order
oh snap.. I think this is from when I copied the order one a hundred times, maybe. Yes I do need to change this. I have to fix something for a test anyways. Let me fix this along with it.

2024-08-19 11:47 UTC, WeatherfordAaron commented on swagger/ghc.yaml
> +          description: Successfully retrieved order
Just fixed and fixed the test that was messing up

2024-08-19 14:54 UTC, JamesHawks224 approved these changes
testing: success
code: lgtm

2024-08-19 15:08 UTC, merged