B-20530-INT Office user assign/unassign functionality
transcom/mymove pull request #13502
Opened 2024-08-19 16:00 UTC by paulstonebraker

## [Agility ticket](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-20530)

## Summary

This is the basic functionality of assigning or unassigned values to the assigned office users columns on the moves table, for queue management purposes.

### How to test

#### Test using postman
#### Test Assign
1. Pass a move id in the path to hit assignOfficeUser
`http://officelocal:3000/ghc/v1/moves/7c12fe36-811a-4af8-94e7-a55984546272/assignOfficeUser`
and an office user id and a role type in the body
```
{"roleType": "task_invoicing_officer",
"officeUserId": "a77f046f-52aa-4226-967a-6bd316f2a2f5"}
```
2. You should receive a 200 ok response looking like this
![image](https://github.com/user-attachments/assets/41dd4a47-10e6-431e-b22d-cfe66e9271e0)
3. Do this for SC, TOO, and TIO roles
4. Check your database moves table and make sure the corresponding office users columns of the moves table are properly populated
#### Test Unassign
1. Pass a move id in the path to hit unassignOfficeUser
`http://officelocal:3000/ghc/v1/moves/7c12fe36-811a-4af8-94e7-a55984546272/assignOfficeUser`
and a role type in the body
```
{"roleType": "task_invoicing_officer"}
```
2. You should receive a 200 ok response looking like this
![image](https://github.com/user-attachments/assets/a3662c36-44af-4e5f-86a5-b82be9174ec6)
3. Do this for SC, TOO, and TIO roles
4. Check your database moves table and make sure the corresponding office users columns of the moves table have been properly updated

2024-08-20 22:12 UTC, paulstonebraker commented on pkg/services/move/assigned_office_user_updater.go
> +	if err != nil {
handle this error and the one below

2024-08-20 22:12 UTC, paulstonebraker commented on swagger-def/ghc.yaml
> +        '400':
check if all responses are being used

2024-08-20 22:18 UTC, pambecker commented on pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
> +		ScAssignedUser:               AssignedOfficeUser(move.SCAssignedUser),
Could we keep the role portion of the payload field name all upper case, that seems to be what we do in other parts of the code.  So it would match the model name too then.
i.e. SCAssignedUser 
TOOAssignedUser
TIOAssignedUser

2024-08-20 22:19 UTC, paulstonebraker commented on swagger-def/ghc.yaml
> +    patch:
delete?

2024-08-21 15:52 UTC, pambecker approved these changes

2024-08-21 20:54 UTC, loganwc approved these changes

2024-08-22 15:26 UTC, danieljordan-caci requested changes
Some changes bruh

2024-08-22 15:26 UTC, danieljordan-caci commented on pkg/handlers/ghcapi/move.go
> +			role := getRole(params.Body.RoleType)
Can you do a `nil` check here? This will prevent null pointer errors later in this function.

We want to make sure these are provided in the payload.

2024-08-22 15:26 UTC, danieljordan-caci commented on pkg/handlers/ghcapi/move.go
> +			role := getRole(params.Body.RoleType)
Same thing here - throw in some `nil` checks to make sure `params.MoveID` and `params.Body.RoleType` are provided.

2024-08-22 15:26 UTC, danieljordan-caci commented on pkg/handlers/ghcapi/move.go
> +			officeUserID := uuid.FromStringOrNil(params.Body.OfficeUserID.String())
Also here

2024-08-22 15:26 UTC, danieljordan-caci commented on pkg/handlers/ghcapi/move.go
> +				appCtx.Logger().Error("Error updating move", zap.Error(err))
Can you make this error a little more specific?
Maybe `Error updating assigned office user on move` and provide the `officeUser.ID` or something

2024-08-22 15:26 UTC, danieljordan-caci commented on swagger-def/ghc.yaml
> +      description: updates a move with an assigned services counselor, task ordering officer, or task invoicing officer
I would dive more into this description - `updates a move by assigning either a services counselor, task ordering officer, or task invoicing officer`

at face value this description is a little confusing

2024-08-22 15:26 UTC, danieljordan-caci commented on swagger-def/ghc.yaml
> +          description: Successfully updated move
Change this to be more specific to the endpoint

2024-08-22 15:26 UTC, danieljordan-caci commented on swagger-def/ghc.yaml
> +          description: Successfully updated move
Change this to be more specific to the endpoint

2024-08-22 15:26 UTC, danieljordan-caci commented on swagger-def/ghc.yaml
> +      - officeUserId
Is `roleType` required in this payload? Is there a use case where it can not be provided?

2024-08-23 20:53 UTC, paulstonebraker commented on pkg/handlers/ghcapi/move.go
> +			role := getRole(params.Body.RoleType)
> Can you do a `nil` check here? This will prevent null pointer errors later in this function.
> 
> We want to make sure these are provided in the payload.

Don't see many place in the app where we do this, will implement if you insist

2024-08-23 20:54 UTC, paulstonebraker commented on pkg/handlers/ghcapi/move.go
> +				appCtx.Logger().Error("Error updating move", zap.Error(err))
Updated error message

2024-08-23 20:54 UTC, paulstonebraker commented on swagger-def/ghc.yaml
> +          description: Successfully updated move
Updated

2024-08-23 20:54 UTC, paulstonebraker commented on swagger-def/ghc.yaml
> +      description: updates a move with an assigned services counselor, task ordering officer, or task invoicing officer
Updated

2024-08-23 20:54 UTC, paulstonebraker commented on swagger-def/ghc.yaml
> +          description: Successfully updated move
Updated

2024-08-23 20:54 UTC, paulstonebraker commented on swagger-def/ghc.yaml
> +      - officeUserId
Good catch, updated

2024-08-26 13:44 UTC, danieljordan-caci requested changes
One more little thing - appreciate the changes

2024-08-26 13:44 UTC, danieljordan-caci commented on swagger-def/ghc.yaml
> +      description: updates a move by assigning either a services counselor, task ordering officer, or task invoicing officer
Can you add `to the move` at the end of this?

2024-08-26 13:44 UTC, danieljordan-caci commented on swagger-def/ghc.yaml
> +      description: updates a move by assigning either a services counselor, task ordering officer, or task invoicing officer
```
updates a move by assigning either a services counselor, task ordering officer, or task invoicing officer to the move
```

2024-08-26 13:44 UTC, danieljordan-caci commented on swagger-def/ghc.yaml
> +      description: updates a move by unassigning a services counselor, task ordering officer, or task invoicing officer
Same here
```
updates a move by unassigning a services counselor, task ordering officer, or task invoicing officer from the move
```

2024-08-26 14:03 UTC, loganwc commented on swagger-def/ghc.yaml
> +      description: updates a move by assigning either a services counselor, task ordering officer, or task invoicing officer
IMO that reads a little weird compared to what he has now

2024-08-26 14:05 UTC, danieljordan-caci commented on swagger-def/ghc.yaml
> +      description: updates a move by assigning either a services counselor, task ordering officer, or task invoicing officer
How?

2024-08-26 14:06 UTC, danieljordan-caci commented on swagger-def/ghc.yaml
> +      description: updates a move by assigning either a services counselor, task ordering officer, or task invoicing officer
Maybe this instead:
```
Assigns either a services counselor, task ordering officer, or task invoicing officer to the move
```

2024-08-26 14:11 UTC, loganwc commented on swagger-def/ghc.yaml
> +      description: updates a move by assigning either a services counselor, task ordering officer, or task invoicing officer
That's better

2024-08-26 14:23 UTC, danieljordan-caci requested changes
You need to not delete this file - likely the outcome of resolving a merge conflict when merging `integrationTesting` into this branch.
![Screenshot 2024-08-26 at 9 22 11 AM](https://github.com/user-attachments/assets/b4220311-dbf7-4fa7-8358-88308f7c9cda)

Happened with [this commit](https://github.com/transcom/mymove/pull/13502/commits/d0c3d9f02d6eab3d27b8e3d82192cc4155620c93)

2024-08-26 16:23 UTC, danieljordan-caci approved these changes

2024-08-26 17:06 UTC, merged