B 20724 int
transcom/mymove pull request #13519
Opened 2024-08-20 14:58 UTC by CoryKleinjanCACI

## [Agility ticket](tbd)

## Summary

This task removes the Primes ability to update the Prime Estimated Weight and Previously Recorded Weight ( NTSRecordedWeight). These fields are now read only for the prime on update.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the Office app
2. Login as a TOO
3. Add an NTS-Release shipment to any move, and then approve it
4. Grab the Move and Shipment ID, as well as the etag required to update.
5. Log in to the Prime swagger API (all versions were updated)
6. Move the UpdateMTOShipment endpoint
7. Apply the proper JSON to update your shipment (you will need to create/acquire this. I used the debugger to copy an update json from prime sim and then used the new etag that was returned. Example provided.)
8. Verify that you cannot update the Prime Estimated Weight or Previously Recorded Weight (NTSRecordedWeight)

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-08-20 18:46 UTC, MInthavongsay commented on pkg/handlers/primeapiv2/mto_shipment.go
> +			if mtoShipment.ShipmentType == models.MTOShipmentTypeHHGOutOfNTSDom {
Although not ideal to use the existing domain object retrieved from the DB find, I guess making sure values are never overridden with incoming data suffices here, I would at least put  comments w/ticket number to make sure other developers know why we are making it read-only here. Apply it for the other versioned  handlers affected.

2024-08-20 18:51 UTC, MInthavongsay approved these changes

2024-08-22 15:28 UTC, ajlusk commented
Functions correctly as far as I can tell but these changes seem like they would be more at home in the service rather than the handler. The handler already tells the service if it's a request from the prime so you can use that in your condition. Maybe somewhere around `pkg/services/mto_shipment/mto_shipment_updater.go:715-765` where it currently handles these two values.

2024-08-23 14:43 UTC, danieljordan-caci requested changes
Reading your line:
```
Verify that you cannot update the Prime Estimated Weight or Previously Recorded Weight (NTSRecordedWeight)
```

I am able to successfully update the `ntsRecordedWeight` value when using the `updateMTOShipment` endpoint.

Previous return after updating - you can see `ntsRecordedWeight` is `5000`:
![Screenshot 2024-08-23 at 9 41 05 AM](https://github.com/user-attachments/assets/54fa6c1e-7c0a-40e1-b52a-e5fae01eb586)

I'm using this payload to update:
```
{
  "actualProGearWeight": 4500,
  "actualSpouseProGearWeight": 4500,
  "scheduledPickupDate": "2024-08-23",
  "actualPickupDate": "2024-08-23",
  "firstAvailableDeliveryDate": "2024-08-23",
  "scheduledDeliveryDate": "2024-08-23",
  "actualDeliveryDate": "2024-08-23",
  "ntsRecordedWeight": 4000
}
```

Now you can see it has been updated to `4000`.
![Screenshot 2024-08-23 at 9 42 14 AM](https://github.com/user-attachments/assets/d7d8a330-b4ed-474f-829e-1b0a5cd7174d)

Is that working as intended or should it just be read only? If we don't want the Prime to update that value then you need to add a validation to `rules.go`.

2024-08-23 14:56 UTC, closed without merging