B 20674 tpps paid info int
transcom/mymove pull request #13510
Opened 2024-08-19 19:47 UTC by traskowskycaci

## [Agility ticket](tbd)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-08-20 15:08 UTC, danieljordan-caci requested changes
Just have one question about your fancy new value in the payment requests model, but the rest looks great!

Props for the thorough walk through and instructions.

![Screenshot 2024-08-20 at 10 07 50 AM](https://github.com/user-attachments/assets/6883096e-857a-4439-b418-fa4d17153765)

2024-08-20 15:08 UTC, danieljordan-caci commented on pkg/models/payment_request.go
> +	TPPSPaidInvoiceReports        TPPSPaidInvoiceReportEntrys `has_many:"tpps_paid_invoice_reports" fk_id:"payment_request_number"`
Should this be a pointer since it can be `null`?

I see you have `x-nullable: true` down in your swagger.

2024-08-20 15:24 UTC, traskowskycaci commented on pkg/models/payment_request.go
> +	TPPSPaidInvoiceReports        TPPSPaidInvoiceReportEntrys `has_many:"tpps_paid_invoice_reports" fk_id:"payment_request_number"`
Good question! I started off with it as a pointer, and had a bunch of server tests failing - basically all payment request server tests.

Removing the pointer solved all of my server test issues. I also looked to the EdiErrors part of this struct to see how that was set up - it's also not a pointer. This implementation seems to be working but I am open to suggestions.

As an alternative to that being a pointer, I am making sure things don't get funky by having some nil checks on it in pkg/handlers/ghcapi/internal/payloads/model_to_payload.go.

@danieljordan-caci and ccing @cameroncaci for his thoughts as well

2024-08-20 16:03 UTC, danieljordan-caci commented on pkg/models/payment_request.go
> +	TPPSPaidInvoiceReports        TPPSPaidInvoiceReportEntrys `has_many:"tpps_paid_invoice_reports" fk_id:"payment_request_number"`
I will await the wise input from @cameroncaci

2024-08-20 16:18 UTC, traskowskycaci commented on pkg/models/payment_request.go
> +	TPPSPaidInvoiceReports        TPPSPaidInvoiceReportEntrys `has_many:"tpps_paid_invoice_reports" fk_id:"payment_request_number"`
Sounds good! I will say that the x-nullable in swagger isn't referring to the TPPSPaidInvoiceReportEntrys you see here - the values that are x-nullable are actually pointers themselves, declared in model_to_payload.go

2024-08-21 12:08 UTC, cameroncaci commented on pkg/models/payment_request.go
> +	TPPSPaidInvoiceReports        TPPSPaidInvoiceReportEntrys `has_many:"tpps_paid_invoice_reports" fk_id:"payment_request_number"`
Mmmm - I'm not seeing which one of these values are linked to the `swagger-def` mods. Which value specifically here are we discussing?

2024-08-21 12:46 UTC, cameroncaci requested changes
Tested successfully, love the details of the PR & the TPPS presentation looks great so far. Leaving some code review

2024-08-21 12:46 UTC, cameroncaci commented on pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
> +			if TPPSPaidInvoiceReportsForPR[0].InvoiceTotalChargesInMillicents > -1 {
Why check for `> -1` rather than `>= 0`. Having `-1` makes it sound like there's a special logic like how SIT does its funky calculations

2024-08-21 12:46 UTC, cameroncaci commented on pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
> +		tppsDataForPaymentRequest := *tppsPaidReportData
While you can safely loop over a pointer without a nil check, this line is explicitly attempting to assign memory values without a nil check - making it unsafe

2024-08-21 14:02 UTC, traskowskycaci commented on pkg/models/payment_request.go
> +	TPPSPaidInvoiceReports        TPPSPaidInvoiceReportEntrys `has_many:"tpps_paid_invoice_reports" fk_id:"payment_request_number"`
These values are defined as nullable in the swagger-def file:
`tppsInvoiceAmountPaidTotalMillicents`
`tppsInvoiceSellerPaidDate`
`tppsInvoiceAmountPaidPerServiceItemMillicents`

Daniel's question was whether the `TPPSPaidInvoiceReports` of type `TPPSPaidInvoiceReportEntrys` needed to be a struct - I am hoping the answer is no on that one as it broke a ton of tests @cameroncaci

2024-08-21 14:04 UTC, traskowskycaci commented on src/components/Office/PaymentRequestCard/PaymentRequestCard.jsx
> +      return 'TPPS Paid';
This is a good question - I didn't see anywhere else this PAID status was already being used, but I will check with Dan to confirm that we don't need a brand new status to track TPPS_PAID separately from PAID.

2024-08-21 14:08 UTC, traskowskycaci commented on pkg/models/payment_request.go
> +	TPPSPaidInvoiceReports        TPPSPaidInvoiceReportEntrys `has_many:"tpps_paid_invoice_reports" fk_id:"payment_request_number"`
I mistyped above - typed struct instead of pointer, edited to fix

2024-08-21 15:13 UTC, traskowskycaci commented on migrations/app/schema/20240815195730_add_fk_to_tpps_paid_invoice_reports.up.sql
> +ON DELETE CASCADE;
Good call! Updated for both table creation and foreign key creation.

2024-08-21 15:35 UTC, cameroncaci commented on pkg/models/payment_request.go
> +	TPPSPaidInvoiceReports        TPPSPaidInvoiceReportEntrys `has_many:"tpps_paid_invoice_reports" fk_id:"payment_request_number"`
Okay, thank you for the clarification. This can remain as a non-pointer - since it's a slice (array), it'll just be an empty slice. Since it wouldn't be a value reference, whenever this slice is attempted to be read, it'll just be empty and handled accordingly. And then if found, it can be appended to rather than initialized as a new memory instance

2024-08-21 15:50 UTC, cameroncaci commented on src/components/Office/PaymentRequestCard/PaymentRequestCard.jsx
> +      return 'TPPS Paid';
Communicated via slack - this will be handled in the downstream

2024-08-21 16:10 UTC, traskowskycaci commented on pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
> +			if TPPSPaidInvoiceReportsForPR[0].InvoiceTotalChargesInMillicents > -1 {
[Resolution](https://github.com/transcom/mymove/commit/3829afb0c7df34151db0eabf038edb95975cc911)

2024-08-21 16:10 UTC, traskowskycaci commented on pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
> +		tppsDataForPaymentRequest := *tppsPaidReportData
[Resolution](https://github.com/transcom/mymove/commit/770931e717125c4aa060c71e21d37fe94551d063)

2024-08-21 16:10 UTC, traskowskycaci commented on pkg/services/payment_request/payment_request_list_fetcher.go
> +		paymentRequests[i].TPPSPaidInvoiceReports = tppsReportEntryList
[Resolution](https://github.com/transcom/mymove/commit/fd6db799bc77b67a62bc25a176acf9b932dc0ffe)

Let me know if you think this needs more detail - happy to add on if need be.

2024-08-21 16:10 UTC, traskowskycaci commented on pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
> +		}
[Resolution](https://github.com/transcom/mymove/commit/fd6db799bc77b67a62bc25a176acf9b932dc0ffe)

Let me know if you think this needs more detail - happy to add on if need be.

2024-08-21 22:17 UTC, traskowskycaci commented on src/components/Office/PaymentRequestCard/PaymentRequestCard.jsx
> +      return 'TPPS Paid';
Talked with Wendy on this and added to the story it will be handled in, B-20758 - we will be using PAID and will not have a new status of TPPS_PAID on the backend. For the frontend, we will still show TPPS PAID. The only time a payment request will be in that state is on receipt of the TPPS Paid Invoice report, referenced in this PR

2024-08-22 12:26 UTC, cameroncaci approved these changes

2024-08-22 13:53 UTC, danieljordan-caci approved these changes

2024-08-22 14:19 UTC, merged