B 20919 sit date retention int
transcom/mymove pull request #13522
Opened 2024-08-20 19:33 UTC by cameroncaci

## [B-20919](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A995185)

## Summary

Introduces the start of a SIT refactor that will support the grouping of SIT service items and providing a top-level summary. Due to our service item architecture, SIT service items are split across multiple different entries, each of which are able to hold separate information when they should be in sync. To support possible features where they should not be in sync, rather than combine their data this refactor introduces "summaries" of each SIT grouping. A SIT grouping holds all the service items for a given entry of SIT (Be it origin or destination), and extracts any discrepancies in data and provides it at a summary level. This will be particularly helpful for code and data readability as well as future overhauls such as showing multiple SITs on the UI.

Per ticket requirements, this also persists past SIT data on the SIT dashboard until a new SIT replaces it - making use of the "summaries".

## How to test

### Disclaimer
To make life easy for testing scenarios, feel free to modify SIT departure dates and other fields of data (Customer contact for example) directly in the database and then refresh your UI page.

### Setup a current Origin SIT

1. Login as prime
2. Select any move and create a new HHG shipment
3. Approve the requested shipment as a TOO
4. Go back into the Prime sim and create Origin sit on this new shipment, set Departure date to today, sent entry date to one week ago
5. Approve the SI’s as TOO
6. Verify SIT departure date is present, but customer contact and requested delivery date are empty
7. Switch back to prime and edit DOASIT, set requested delivery and customer contacted dates to today
8. Switch back to TOO and verify SIT Departure date, customer contact date, and requested delivery date are visible

### Setup a past Origin SIT

1. Login as prime
2. Select any move and create a new HHG shipment
3. Approve the requested shipment as a TOO
4. Go back into the Prime sim and create Origin sit on this new shipment, set Departure date to yesterday, sent entry date to one week ago, thus immediately making it “past”
5. Approve the SI’s as TOO
6. Previously, SIT Departure date will be missing, and in its place will ONLY be “Previously used SIT”
7. Verify SIT departure date is not missing and is present. Customer contact and requested delivery date will be empty for now. We will populate those next
8. Switch to prime, edit DOASIT again, leave departure date in the past but set a requested delivery and customer contacted date
9. Switch back to the move as a TOO and verify you can see customer contact date and requested delivery date

### Replace a past Origin SIT
Continue off of the scenario of `Setup a past Origin SIT`
Login as prime
Create a new destination SIT with either no departure date or a departure date of today
Open the move page and verify that the past SIT data (Departure date, customer contact, requested delivery date) are all `-` empty values, thus meaning you have replaced it
Replicate steps to populate these fields on the destination sit and verify you see them on the UI

## Screenshots

![image](https://github.com/user-attachments/assets/22719800-d323-41d6-bfb5-2736c5955cc6)

![Pasted Graphic 1](https://github.com/user-attachments/assets/fa8e91d7-619a-44c5-946b-50574485a219)

![Pasted Graphic](https://github.com/user-attachments/assets/169b0c22-031a-4e09-9f3b-aee671da6604)

2024-08-21 12:46 UTC, cameroncaci commented
Failing client error has a hotfix coming in the pipeline
https://github.com/transcom/mymove/pull/13508

2024-08-21 16:32 UTC, TevinAdams commented
@cameroncaci Testing this and had a question at this step. Do we set the entry dat one week from the departure date or from current date?

2024-08-21 16:40 UTC, cameroncaci commented
> @cameroncaci Testing this and had a question at this step. Do we set the entry dat one week from the departure date or from current date?

Depends on which scenario you want:

Past SIT: entry and departure date should both be in the past (Entry always before departure though)
Current SIT: Entry either today or in the past, with departure either not defined or in the future
Future SIT: entry in the future - departure whatever you're feeling

2024-08-21 16:55 UTC, TevinAdams commented
Went through the test case and everything worked as expected.

Current origin SIT did populate with expected Data.
<img width="794" alt="Screenshot 2024-08-21 at 11 23 18 AM" src="https://github.com/user-attachments/assets/bdf5e7ba-8116-4a9f-87f8-6f5da2c0fb03">

Past Origin SIT did populate with expected data.

Replacing a past Origin SIT did render the expected results.
<img width="885" alt="Screenshot 2024-08-21 at 11 52 00 AM" src="https://github.com/user-attachments/assets/00cf5787-fe76-4511-b501-3ec9edec3dc9">

2024-08-21 16:56 UTC, TevinAdams approved these changes
Reviewed code and test case worked as expected. ACs also met.

2024-08-21 17:00 UTC, TevinAdams requested changes
All looks good. Test case worked as expected and reviewed code. ACs seems to have been met. Just requesting a 508 compliance screenshot.

2024-08-21 17:43 UTC, traskowskycaci approved these changes
Looks awesome going through testing - kept changing the dates as the prime and continued to see them update on the UI as expected.

Really liking the refactor, code looks good. Had a few comments in there but none that should hold up the PR. Green checkmark is yours - very nice!

2024-08-21 17:51 UTC, traskowskycaci commented
> All looks good. Test case worked as expected and reviewed code. ACs seems to have been met. Just requesting a 508 compliance screenshot.

Agree with Tevin's request here - forgot to check that

2024-08-21 18:10 UTC, cameroncaci commented on pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
> +		ServiceItemID:        *handlers.FmtUUID(currentSIT.ServiceItemID), // TODO: Refactor out service item ID dependence in GHC API. This should be based on SIT groupings / summaries
We do not other than anticipated continued refactoring

2024-08-21 18:10 UTC, cameroncaci commented
@TevinAdams @traskowskycaci 508 finding and justification provided, requesting re-review

2024-08-21 19:03 UTC, traskowskycaci commented
> @TevinAdams @traskowskycaci 508 finding and justification provided, requesting re-review

Thanks for adding that! That issue looks good as written.

2024-08-21 19:10 UTC, traskowskycaci commented on src/components/Office/ShipmentSITDisplay/ShipmentSITDisplayTestParams.js
> +        daysInSIT: 21,
Discussed via Slack, since these values aren't important to the test they will stay as is. Resolving

2024-08-21 19:10 UTC, traskowskycaci commented on src/components/Office/ShipmentSITDisplay/ShipmentSITDisplayTestParams.js
> +        daysInSIT: 30,
Discussed via Slack, since these values aren't important to the test they will stay as is. Resolving

2024-08-21 19:10 UTC, traskowskycaci commented on src/components/Office/ShipmentSITDisplay/ShipmentSITDisplayTestParams.js
> +        daysInSIT: 30,
Discussed via Slack, since these values aren't important to the test they will stay as is. Resolving

2024-08-21 19:10 UTC, danieljordan-caci approved these changes
Tested locally and looks really good dude! What a great start to a refactor.

Don't have any other input other than what has been stated. Tried to break it, but couldn't seem to poke any holes. Good work!

2024-08-21 19:10 UTC, traskowskycaci commented on src/components/Office/ShipmentSITDisplay/ShipmentSITDisplayTestParams.js
> +        daysInSIT: 30,
Discussed via Slack, since these values aren't important to the test they will stay as is. Resolving

2024-08-21 19:10 UTC, danieljordan-caci commented
You do have some conflicts to resolve though

2024-08-21 19:11 UTC, traskowskycaci commented on pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
> +		ServiceItemID:        *handlers.FmtUUID(currentSIT.ServiceItemID), // TODO: Refactor out service item ID dependence in GHC API. This should be based on SIT groupings / summaries
Ok. In the absence of a feature to tie it to, good with leaving it in there

2024-08-21 19:19 UTC, danieljordan-caci commented on pkg/services/sit_status/shipment_sit_status.go
> +	} */
ope - can you remove these comments?

2024-08-21 19:27 UTC, TevinAdams approved these changes

2024-08-21 19:42 UTC, cameroncaci commented on pkg/services/sit_status/shipment_sit_status.go
> +	} */
Thank you, this was a leftover from me thinking about shoehorning the past SIT into current SIT - but didn't implement because that's a pretty bad approach

2024-08-22 13:48 UTC, cameroncaci commented
Flaky client test
![image](https://github.com/user-attachments/assets/ff74f221-7a49-4941-8fde-d60f0f14b6f5)

2024-08-22 13:48 UTC, merged