B 20671 parse tpps paid invoice int part 2
transcom/mymove pull request #13527
Opened 2024-08-21 14:06 UTC by traskowskycaci

## [Agility ticket](tbd)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-08-21 14:57 UTC, traskowskycaci commented
Flaky server tests failing

2024-08-22 15:49 UTC, danieljordan-caci requested changes
Itty bitty typo

2024-08-22 15:49 UTC, danieljordan-caci commented on pkg/services/invoice/process_tpps_paid_invoice_report_test.go
> +	suite.Run("successfully proccesses a TPPSPaidInvoiceReport from a file directly from the TPPS pickup directory and stores it in the database", func() {
typo in `processes`

2024-08-22 16:41 UTC, traskowskycaci commented on pkg/services/invoice/process_tpps_paid_invoice_report_test.go
> +	suite.Run("successfully proccesses a TPPSPaidInvoiceReport from a file directly from the TPPS pickup directory and stores it in the database", func() {
Fixed! [Resolution](https://github.com/transcom/mymove/pull/13527/commits/b8da51cfdcd61c1810f9798e80afff55aad694e5)

2024-08-22 16:42 UTC, danieljordan-caci approved these changes

2024-08-22 16:46 UTC, traskowskycaci commented
seeing some conflicts, will resolve

2024-08-22 17:07 UTC, traskowskycaci commented
Client test failed after merging in latest int, not marked as flaky in Circle but does pass for me locally

![image](https://github.com/user-attachments/assets/9ae974f1-3368-43b0-ade3-6a3f81d3c75e)

2024-08-22 19:33 UTC, traskowskycaci commented
> Client test failed after merging in latest int, not marked as flaky in Circle but does pass for me locally
> 
> ![image](https://private-user-images.githubusercontent.com/147537467/360563480-9ae974f1-3368-43b0-ade3-6a3f81d3c75e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNTU0OTMsIm5iZiI6MTcyNDM1NTE5MywicGF0aCI6Ii8xNDc1Mzc0NjcvMzYwNTYzNDgwLTlhZTk3NGYxLTMzNjgtNDNiMC1hZGUzLTZhM2Y4MWQzYzc1ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMlQxOTMzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YmIyNDc3YTU1OGYwMTc5M2I4MGM0OGI3MzgxZWQyOTliM2I1OWE0ZDMyM2E1MzcyNmRlNGMyYzA3NzJjNGU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9czPFgV-_zIxFIjNUOsCxo3UBAFuUW15VMVcxrLEdIs)

Just a flaky client test, still good to review

2024-08-23 14:36 UTC, deandreJones commented on pkg/edi/tpps_paid_invoice_report/parser.go
> +			processedEntry = strings.TrimLeft(processedEntry, "�")
is that supposed to be a weird ascii char?

2024-08-23 14:40 UTC, cameroncaci approved these changes
Good, just curious about what Dre found too https://github.com/transcom/mymove/pull/13527/files#r1729082481

2024-08-23 14:44 UTC, traskowskycaci commented on pkg/edi/tpps_paid_invoice_report/parser.go
> +			processedEntry = strings.TrimLeft(processedEntry, "�")
Yep! It starts off the version of the file that lives in the SFTP folder. 
![image](https://github.com/user-attachments/assets/108a4f14-85e3-4e78-ae9a-37aaf1b69ce2)

@deandreJones @cameroncaci

2024-08-23 14:48 UTC, deandreJones commented on pkg/edi/tpps_paid_invoice_report/parser.go
> +			processedEntry = strings.TrimLeft(processedEntry, "�")
every file starts that way?

2024-08-23 14:50 UTC, deandreJones commented on pkg/edi/tpps_paid_invoice_report/parser.go
> +			processedEntry = strings.TrimLeft(processedEntry, "�")
well I see that - that's how it originally shows,, but will it be that way after the app grabs it and parses it

2024-08-23 14:50 UTC, traskowskycaci commented on pkg/edi/tpps_paid_invoice_report/parser.go
> +			processedEntry = strings.TrimLeft(processedEntry, "�")
Yep, every file currently in that folder does

![image](https://github.com/user-attachments/assets/56128913-2e6d-417c-81fa-447f071a24a7)


![image](https://github.com/user-attachments/assets/78a37030-5f78-419c-9dbc-8912cb808f73)


![image](https://github.com/user-attachments/assets/a7514d2d-2c98-40e0-a791-0700c8d4b7cf)


![image](https://github.com/user-attachments/assets/9f88f4ad-b5f7-4b68-a412-21b7afe79335)

2024-08-23 14:58 UTC, traskowskycaci commented on pkg/edi/tpps_paid_invoice_report/parser.go
> +			processedEntry = strings.TrimLeft(processedEntry, "�")
Talked with Dre on slack about his question - the parsing logic should still work even if there isn't the weird character to lead off the file. However, we won't truly know this parsing logic works until we can hook up to the final agreed on pickup dir - just writing tests for as many versions of the file I can predict at this point

2024-08-23 15:39 UTC, merged