INT B-20793 Add GSR role and base (QAE) traits in office/admin app
transcom/mymove pull request #13529
Opened 2024-08-21 15:27 UTC by danieljordan-caci

## [Agility ticket](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-20793)

## Summary

As we continue implementation of creating GSR (Government Surveillance Representative) users, we need to set the base permissions the same as QAE. This has also been requested to be placed on a feature flag, so this PR also implements that logic. Nothing too crazy.

This PR does the following:
- adds all relevant information needed for GSR feature flag 
(you can find the merged PR for `milmove-feature-flags` repo [here](https://github.com/transcom/milmove-feature-flags/pull/196))
- implements creating a GSR role using the local sign-in method
- adds GSR checkbox to admin app for creating/updating/viewing office users
- added in functionality to NOT create an okta account when approving requested office users from devlocal
- set default log in route for GSR & base permissions to be the same as QAE
- checking GSR feature flag on sign in, if `gsr_role` is `false` then that GSR user will get the invalid permissions page
- fixing the requested office users form to not be skinny on load by setting static width
- updated all relevant tests

### How to test

1. In your `envrc` and `developmental-features` files, set the GSR role value to `true`
2. FIre up your `server` and `client`
3. Using local sign-in, create a new GSR user
4. Confirm you are directed to the QAE home page where you can search for whatever
5. Navigate the app, confirm you can do all things QAE
6. Log out
7. Set the flags to `false`
8. Refire your `server`
9. Log in as a GSR
10. You should see the invalid permissions screen

## Screenshots
![Screenshot 2024-08-21 at 10 25 38 AM](https://github.com/user-attachments/assets/417789c7-8fae-40b0-8a26-d71cdb69eca7)

![Screenshot 2024-08-21 at 10 25 13 AM](https://github.com/user-attachments/assets/e7a41f41-66e4-4e6a-80e5-c482670937b2)

2024-08-21 18:47 UTC, traskowskycaci commented on pkg/handlers/authentication/devlocal_test.go
> +				roles.RoleTypeServicesCounselor, roles.RoleTypePrimeSimulator, roles.RoleTypeGSR, roles.RoleTypeHQ, roles.RoleTypeQae, roles.RoleTypeCustomerServiceRepresentative},
Bothers me a little bit that GSR and HQ are capitalized but Qae is not - how tough would that be to make a standard either one way or the other? Feel free to tell me to shove it

2024-08-21 18:50 UTC, traskowskycaci requested changes
Would you mind updating the AC to reflect what I think you and Dan talked about this morning - moving this to B-20809? Probably good to leave it there but just strike through and note that it's been moved to a downstream

```
Given I am an requesting office user
When I fill out the request form for an office account
Then there will be an option for me to select the GSR role and submit the form successfully
```

Had one ask in there for GSR vs Gsr but up to you on that one, not critical

2024-08-21 18:51 UTC, danieljordan-caci commented on pkg/handlers/authentication/devlocal_test.go
> +				roles.RoleTypeServicesCounselor, roles.RoleTypePrimeSimulator, roles.RoleTypeGSR, roles.RoleTypeHQ, roles.RoleTypeQae, roles.RoleTypeCustomerServiceRepresentative},
I won't tell you to shove it, but I will tell you that I won't change it haha

2024-08-21 18:52 UTC, danieljordan-caci commented
> Would you mind updating the AC to reflect what I think you and Dan talked about this morning - moving this to B-20809? Probably good to leave it there but just strike through and note that it's been moved to a downstream
> 
> ```
> Given I am an requesting office user
> When I fill out the request form for an office account
> Then there will be an option for me to select the GSR role and submit the form successfully
> ```
> 
> Had one ask in there for GSR vs Gsr but up to you on that one, not critical

Done!

2024-08-21 19:04 UTC, traskowskycaci commented on pkg/handlers/authentication/devlocal_test.go
> +				roles.RoleTypeServicesCounselor, roles.RoleTypePrimeSimulator, roles.RoleTypeGSR, roles.RoleTypeHQ, roles.RoleTypeQae, roles.RoleTypeCustomerServiceRepresentative},
I suppose I can live with it

2024-08-21 19:05 UTC, traskowskycaci approved these changes
Looks good! Poked around and it seemed like I could do all QAE things.

2024-08-22 14:56 UTC, TevinAdams requested changes
Reviewed code and wrapping up working through the test case. Missing 508 compliance check screenshot.

2024-08-22 15:13 UTC, danieljordan-caci commented
> Reviewed code and wrapping up working through the test case. Missing 508 compliance check screenshot.

508 added

2024-08-22 15:14 UTC, TevinAdams approved these changes

2024-08-22 15:14 UTC, merged