MAIN - B 19813 - Customer time validation - HHG, NTS, NTSR
transcom/mymove pull request #13542
Opened 2024-08-22 16:20 UTC by MInthavongsay

## [B-19813](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A946350&RoomContext=TeamRoom%3A855664&concept=TeamRoom)

## [INT PR](https://github.com/transcom/mymove/pull/13426)

## Summary

**MAIN**

This PR adds date validation for HHG, NTS and NTSR for preferred pickup and/or delivery date selection for the shipment onboarding process. An inline alert message will appear upon date selection from date picker. An alert message will appear on page load and on date selection. Message will be customized to respective date label. Alert will notify user if date selected is on weekend and/or holiday(federal holidays). For now implementation will assume date context is in the United States. For example, July 4th is a holiday and Sat/Sunday are considered weekend days.   

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

Alerts will only display if date is on a weekend and/or holday.

1. Login as customer
2. Add shipment types: HHG, NTS, NTSR
3. For each shipment verify alert messages are displayed when holidays and weekend dates are selected for preferred pickup and delivery dates during onboarding.
4. Verify alerts are displayed on shipment edit.
5. Verify alert messages are for pickup or delivery.

![Screenshot 2024-08-06 at 1 19 00 PM](https://github.com/user-attachments/assets/f19243b1-6767-4248-aff5-da3dcb955684)
![Screenshot 2024-08-06 at 12 16 55 PM](https://github.com/user-attachments/assets/d3865d4c-9b2c-4387-8062-3799ef40fa74)
![Screenshot 2024-08-06 at 12 16 45 PM](https://github.com/user-attachments/assets/2833e911-d1ca-4a34-b3ac-ac44146664d5)

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

2024-08-23 14:08 UTC, danieljordan-caci requested changes
You have an extra commit in this branch than you do in `INT`
[moved calander.js to util dir](https://github.com/transcom/mymove/pull/13542/commits/6213b6fd69b59e86bc43ce53ea4941be86522f91)

Also you have an difference in a line here than you do in INT.

2024-08-26 15:12 UTC, MInthavongsay commented on src/utils/calendar.js
> +  if (!Number.isNaN(date.getTime())) {
If I recall moving the calendar.js to the util dir and the addition of the `if (!Number.isNaN(date.getTime())) {` was due to lint complaining about `if (!Number.isNaN(date.getTime())) {` in the original implementation for BP-19813 INT-PR.  For some reason it was complaining when it was moved to the util directory. It's NOT in INT for BP-19813 because I decided to piggy back off BP-19815 INT-PR. Both BP-19813 and BP-19815 share the same calendar.js file. Due to BP-19813 already passed PO acceptance I made a judgment call not to move BP-19813 back to development when it was too far along for a small refactor I can make off BP-19815. Make sense?

2024-08-26 19:37 UTC, r-mettler approved these changes

2024-08-27 19:48 UTC, CoryKleinjanCACI approved these changes

2024-08-27 20:16 UTC, danieljordan-caci requested changes
Letting @deandreJones chime in on this one.

I know the change is small, but this PR has been branched off of its downstream PR which makes these dependent on each other.

IMO this is not ideal coding practices and could cause issues down the way - no matter how small the changes may seem.

Once Dre has chimed in, I'll check back.

2024-08-27 20:23 UTC, deandreJones commented
> Letting @deandreJones chime in on this one.
> 
> I know the change is small, but this PR has been branched off of its downstream PR which makes these dependent on each other.
> 
> IMO this is not ideal coding practices and could cause issues down the way - no matter how small the changes may seem.
> 
> Once Dre has chimed in, I'll check back.

Agree- It is not good practice to have 2 branches dependent on each other- maybe should have been combined- 
circular dependencies make things messy
I agree it may not be convenient to go back and make changes to INT, but it keeps other from having conflicts, if those branches aren't merged together

2024-08-27 23:30 UTC, r-mettler commented
> > Letting @deandreJones chime in on this one.
> > I know the change is small, but this PR has been branched off of its downstream PR which makes these dependent on each other.
> > IMO this is not ideal coding practices and could cause issues down the way - no matter how small the changes may seem.
> > Once Dre has chimed in, I'll check back.
> 
> Agree- It is not good practice to have 2 branches dependent on each other- maybe should have been combined- circular dependencies make things messy I agree it may not be convenient to go back and make changes to INT, but it keeps other from having conflicts, if those branches aren't merged together

Agree it should have gone in with the INT branch with this backlog but now both INT and Main have the change in question I am going to go ahead and merge this into main.
![image](https://github.com/user-attachments/assets/f7a752ef-4e72-4349-ab13-a338e3b0138a)

2024-08-28 13:21 UTC, deandreJones approved these changes

2024-08-28 20:13 UTC, r-mettler commented
This was merged in with another PR so closing this as its no longer needed.

2024-08-28 20:13 UTC, closed without merging