INT-B-20466 add a frontend (filterable) column to the SC's queue
transcom/mymove pull request #13558
Opened 2024-08-23 22:34 UTC by JonSpight

## [Agility ticket](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A979856)

## Summary
Add a frontend column to the SC's queue that displays move.counselingOffice, and can be filtered and sorted.

### How to test

1.  Login as a Service Counselor
2. Search for a customer using a customer name
3. Create a new move for the customer
4. Verify Counseling Office column shows respective counseling office name
5. Enter the name of the Counseling Office and verify only respective moves are shown

2024-08-30 15:21 UTC, pambecker commented
Jon, sorting on the new column is not working for me.

2024-08-30 15:32 UTC, pambecker commented on pkg/handlers/ghcapi/orders.go
> +					moveOptions.CounselingOfficeID = &officeUser.TransportationOfficeID
Is this IF block needed?  seems redundant to the lines above 319-322

2024-08-30 15:41 UTC, pambecker commented on swagger-def/ghc.yaml
> -        x-nullable: true
Did you mean to delete this line?

2024-08-30 16:33 UTC, loganwc commented
Filtering only works if you type in the complete name. 
`PPPO Scott AFB - USAF` Counseling office is not filterable by Scott, or PPPO or any other combination

2024-08-30 16:35 UTC, loganwc approved these changes

2024-08-30 16:37 UTC, danieljordan-caci requested changes
Please include a 508 check screenshot

2024-08-30 16:46 UTC, loganwc commented
> Please include a 508 check screenshot

![Uploading Screenshot 2024-08-30 at 11.46.46 AM.png…]()

2024-08-30 17:27 UTC, danieljordan-caci requested changes

2024-08-30 17:27 UTC, danieljordan-caci commented on pkg/handlers/ghcapi/orders.go
> +					// return orderop.NewCreateOrderUnprocessableEntity(), err
left in comment - please remove

2024-08-30 18:21 UTC, danieljordan-caci commented on pkg/services/order/order_fetcher.go
> +}
Has there been conversation with the gov regarding this being a hard WHERE query? Could we throw an `ILIKE` in here to handle partial matches?
```
func counselingOfficeFilter(office *string) QueryOption {
	return func(query *pop.Query) {
		if office != nil {
			query.Where("transportation_offices.name ILIKE ?", "%"+*office+"%")
		}
	}
}
```

2024-08-30 18:47 UTC, pambecker commented on pkg/services/order/order_fetcher.go
> +}
So we actually discussed that and thought it might be good to keep the filter work like the other text column filters in the queues.  Customer name and Origin duty location, you have to type in the full name.  Not ideal, but didn't want to open a bigger can of worms.

2024-08-30 19:01 UTC, pambecker commented on pkg/services/order/order_fetcher.go
> +}
Actually, I'm mistaken, customer does have the ILIKE with last name

2024-08-30 19:35 UTC, danieljordan-caci commented on pkg/services/order/order_fetcher.go
> +}
Maybe worth asking Terri about? Feel like they would know for sure or not.

I say this because we've had previous implementations like this that have enhancements created down the line where they want partial matches to show up. Just a thought!

2024-09-04 12:52 UTC, danieljordan-caci commented on pkg/services/order/order_fetcher.go
> +}
@JonSpight hey just for future PRs, when addressing my comments - I prefer to resolve the conversations. Just like to make sure that the code changes has happened or the PR assignee (in this case, you) has either addressed the question via comment or made a code change.

Typically I like to see a response instead of a conversation marked resolved without any word from the assignee. Keep up the good work!

2024-09-04 14:01 UTC, danieljordan-caci commented
Conflicts

2024-09-05 13:38 UTC, danieljordan-caci commented
> Please include a 508 check screenshot

@JonSpight still missing your 508 screenshot

2024-09-05 14:23 UTC, pambecker commented on pkg/handlers/ghcapi/orders.go
> +					moveOptions.CounselingOfficeID = &officeUser.TransportationOfficeID
Still a question on this block of code you added here.  did you find that it was needed?  We have the 'fetchOfficeUserByID' on line 189 that already seems to get the info, and it populates the CounselingOfficeID on line 322.  Isn't this redundant code then?

2024-09-05 14:27 UTC, paulstonebraker commented
> > Please include a 508 check screenshot
> 
> @JonSpight still missing your 508 screenshot

I told him to attach to the story in agility - I thought that was how we handled 508?

2024-09-05 14:53 UTC, danieljordan-caci commented
> > > Please include a 508 check screenshot
> > 
> > 
> > @JonSpight still missing your 508 screenshot
> 
> I told him to attach to the story in agility - I thought that was how we handled 508?

In the description plz

2024-09-05 15:21 UTC, danieljordan-caci approved these changes
LGTM!

2024-09-05 15:41 UTC, pambecker approved these changes

2024-09-05 16:29 UTC, merged