B 20758 tpps paid pr status int
transcom/mymove pull request #13554
Opened 2024-08-23 15:55 UTC by traskowskycaci

## [Agility ticket](tbd)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-08-23 20:27 UTC, danieljordan-caci approved these changes
LGTM!

2024-08-26 12:47 UTC, cameroncaci requested changes

2024-08-26 12:47 UTC, cameroncaci commented on pkg/services/invoice/process_tpps_paid_invoice_report.go
> +					}
Could you update this log to include payment request ID?

2024-08-26 12:47 UTC, cameroncaci commented on pkg/services/invoice/process_tpps_paid_invoice_report.go
> +	)
Could we add the UUID too?

2024-08-28 14:25 UTC, traskowskycaci commented on pkg/services/invoice/process_tpps_paid_invoice_report.go
> +	)
Added

2024-08-28 14:25 UTC, traskowskycaci commented on pkg/services/invoice/process_tpps_paid_invoice_report.go
> +					}
Added

2024-08-28 14:27 UTC, cameroncaci requested changes

2024-08-28 14:27 UTC, cameroncaci commented on pkg/services/invoice/process_edi824.go
> +
Could you maintain the zap error too?

`txnAppCtx.Logger().Error(fmt.Sprintf("failure updating payment request status : %v", paymentRequest.ID), zap.Error(err))`

2024-08-28 14:35 UTC, traskowskycaci commented on pkg/services/invoice/process_edi824.go
> +
Fixed!

2024-08-28 15:27 UTC, merged