20621 add mobile shipment customer flows int
transcom/mymove pull request #13559
Opened 2024-08-26 10:36 UTC by KonstanceH

## [Agility ticket](tbd)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-08-26 20:47 UTC, taeJungCaci requested changes
I've also added a different buttons for the 2nd page of the boat shipment form. Check out `src/components/Customer/MtoShipmentForm/MtoShipmentForm.jsx` line 669.

This give the user a `Back` and `Save & Continue` Button.

Other than these, everything else looks good! I think you still need to fix some stuff for edit flow and the shipment list view page, but I think you should be able to do those in the shipment card story!

2024-08-26 20:47 UTC, taeJungCaci commented on src/components/Customer/modals/MobileHomeInfoModal/MobileHomeInfoModal.jsx
So I originally was planning on using the same modal for Boat shipment and Mobile home together for these kinda like how they have HHG & PPM together and NTS' together. But I just realized that I named my file `boatInfoModal` instead of `boatAndMobileHomeInfoModal`. Since both modal's title is saying Boat & Mobile homes info, would you be able to either - put the mobile home info in the `boatInfoModal` and changes the file name to `boatAndMobileHomeInfoModal` or - change the headers in both modals to reference their corresponding shipment?

2024-08-26 20:47 UTC, taeJungCaci commented on src/components/Customer/MobileHomeShipment/MobileHomeShipmentForm/MobileHomeShipmentForm.jsx
Brooklyn just made changes to the boat shipment fields to show required labels differently so I think you may have to add them here as well.
https://github.com/transcom/mymove/pull/13567/files

2024-08-26 20:47 UTC, taeJungCaci commented on src/pages/MyMove/MobileHome/MobileHomeShipmentCreate/MobileHomeShipmentCreate.jsx
> +  };
I don't think you are going to be needed these for mobile home. These were to redirect the user if dimensions didn't meet for the boat shipment.

2024-08-26 20:50 UTC, taeJungCaci commented
Also, don't forget to add ANDI screenshots and the tag to the backlog!

2024-08-27 12:31 UTC, WeatherfordAaron approved these changes
After entering the information the following shows in dev tools ✅ 

![Screenshot 2024-08-27 at 7 14 00 AM](https://github.com/user-attachments/assets/a923769c-0a34-4a8f-ae88-e4f6c0a44fd7)

___

The following shows up in the DB ✅ 
```
select m."locator" as "Move Locator", ms.shipment_locator as "Shipment Locator", mh.make as "Make", mh.model as "Model", mh."year" as "Year"
FROM mobile_homes mh
JOIN mto_shipments ms on ms.id = mh.shipment_id
JOIN moves m on m.id = ms.move_id
WHERE m."locator" = '3CG686'
```
<img width="1183" alt="Screenshot 2024-08-27 at 7 22 50 AM" src="https://github.com/user-attachments/assets/8a2cf04e-a8c2-4fcc-a9a1-7795ae647fe3">

___

The only potential issue I see is the underscore between Mobile and Home.. but if this makes it through POA, I take no issue. I'd only change this if you think it won't make it through POA.

![Screenshot 2024-08-27 at 7 23 39 AM](https://github.com/user-attachments/assets/0fb1ed0d-794e-469e-b7fd-e3518518b9dc)

<font style="color:green">All in all LGTM</font> 👽

2024-08-27 13:36 UTC, KonstanceH commented on src/components/Customer/modals/MobileHomeInfoModal/MobileHomeInfoModal.jsx
Ah okay I was wondering why the title was both lol. Yea I'll drop it in the boatInfoModal and rename the file.

2024-08-27 18:24 UTC, KonstanceH commented
> After entering the information the following shows in dev tools ✅
> 
> ![Screenshot 2024-08-27 at 7 14 00 AM](https://private-user-images.githubusercontent.com/147739091/361802766-a923769c-0a34-4a8f-ae88-e4f6c0a44fd7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NjcxNTcsIm5iZiI6MTcyNDc2Njg1NywicGF0aCI6Ii8xNDc3MzkwOTEvMzYxODAyNzY2LWE5MjM3NjljLTBhMzQtNGE4Zi1hZTg4LWU0ZjZjMGE0NGZkNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyN1QxMzU0MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNmZmZGEwNWFkMGJhNGQ3ZDE4NTVmMWRkYWYwMzZjZTNjYTYyZTBiMGMyZTVhN2M1NDAyMmUxNmJhNzMyZGE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6IzVW65OL_iUGuPKZH02BZ3NcfY0qWIWJoMrqiy9v0s)
> 
> The following shows up in the DB ✅
> 
> ```
> select m."locator" as "Move Locator", ms.shipment_locator as "Shipment Locator", mh.make as "Make", mh.model as "Model", mh."year" as "Year"
> FROM mobile_homes mh
> JOIN mto_shipments ms on ms.id = mh.shipment_id
> JOIN moves m on m.id = ms.move_id
> WHERE m."locator" = '3CG686'
> ```
> 
> <img alt="Screenshot 2024-08-27 at 7 22 50 AM" width="1183" src="https://private-user-images.githubusercontent.com/147739091/361803470-8a2cf04e-a8c2-4fcc-a9a1-7795ae647fe3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NjcxNTcsIm5iZiI6MTcyNDc2Njg1NywicGF0aCI6Ii8xNDc3MzkwOTEvMzYxODAzNDcwLThhMmNmMDRlLWE4YzItNGZjYy1hOWExLTc3OTVhZTY0N2ZlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyN1QxMzU0MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNGU3NjQ3NjU5ZGRiYjNmY2YyNWY2YjU2MDE4YjBmZGExMDgyZDQ2YmVjYjEwOGFjZjE2ZmM0ZGRmM2NiNTA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LKxpBI31v0e1J9Ddr9PaLRqLNES_xxRUV_neHqf1tTY">
> The only potential issue I see is the underscore between Mobile and Home.. but if this makes it through POA, I take no issue. I'd only change this if you think it won't make it through POA.
> 
> ![Screenshot 2024-08-27 at 7 23 39 AM](https://private-user-images.githubusercontent.com/147739091/361803658-0fb1ed0d-794e-469e-b7fd-e3518518b9dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NjcxNTcsIm5iZiI6MTcyNDc2Njg1NywicGF0aCI6Ii8xNDc3MzkwOTEvMzYxODAzNjU4LTBmYjFlZDBkLTc5NGUtNDY5ZS1iN2ZkLWUzNTE4NTE4YjlkYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyN1QxMzU0MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OGViY2Y0N2I4MzJjNDJkYzhiNzQ4YjU1YWY2ZGMzZjUyMjI1MGUwNDY5ZTgwYTc4Y2U1MTI0MGEyNjg4ZTdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.R_Uv7okj2f-8JuiKsVP_QrcW8Zc4QrenJn9myZYfvfw)
> 
> All in all LGTM 👽

yea that's a fair point I'll try and add a space in it. I think it'll look better

2024-08-28 19:38 UTC, taeJungCaci requested changes

2024-08-28 19:38 UTC, taeJungCaci commented on .envrc
> -export DTOD_USE_MOCK=false
Don't forget to switch this back to `false` unless you meant the change!

2024-08-28 19:42 UTC, taeJungCaci commented on src/components/Customer/modals/MobileHomeInfoModal/MobileHomeInfoModal.jsx
Thanks for updating those!

2024-08-28 19:44 UTC, taeJungCaci requested changes

2024-08-28 19:44 UTC, taeJungCaci commented on .envrc
> +export DTOD_USE_MOCK=true
Don't forget to switch this back to false unless you meant the change!

2024-08-28 20:17 UTC, KonstanceH commented on .envrc
> +export DTOD_USE_MOCK=true
yikes! let me take this out now

2024-08-28 20:18 UTC, taeJungCaci approved these changes
LGTM!

2024-08-29 02:50 UTC, merged