B 19463 int
transcom/mymove pull request #13581
Opened 2024-08-28 05:22 UTC by paulstonebraker

## [Agility ticket](tbd)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-08-28 18:22 UTC, danieljordan-caci requested changes
Some suggestions, some changes.

I'm not sure the use case of still having the dropdown when the user is not a supervisor. It doesn't add value to the queue for them and is a potential distractor - unless they can assign themselves to a move without the action of a supervisor.

If the dropdown has no functionality for the non-supervisor user, I would suggest hiding the column. If it will eventually have functionality that the non-supervisors can action then I'm fine with it being there.

Also you need a 508 check screenshot with less red than this one.
![Screenshot 2024-08-28 at 1 22 37 PM](https://github.com/user-attachments/assets/c5edaf0b-e531-4dae-bdcd-9ac60c24eff7)

2024-08-28 18:22 UTC, danieljordan-caci commented on src/utils/queues.jsx
> +};
You can destructure here to make it a little more concise & nice:
```
export const formatAvailableOfficeUsersForRow = (row) => {
  const { assignedTo, availableOfficeUsers = [] } = row;

  if (assignedTo && !availableOfficeUsers.some((user) => user.value === assignedTo.id)) {
    addAssignedOfficeUser(row);
  }

  const assignedToUser = availableOfficeUsers.find((user) => user.value === assignedTo?.id);

  const formattedAvailableOfficeUsers = availableOfficeUsers.map(({ value, label }) => (
    <option value={value} key={`filterOption_${value}`}>
      {label}
    </option>
  ));

  return { formattedAvailableOfficeUsers, assignedToUser };
};
```

2024-08-28 18:22 UTC, danieljordan-caci commented on src/utils/queues.jsx
> +  const fullName = `${user.lastName}, ${user.firstName}`;
Can you add a `null` check here just in case we need to handle null values?

`user?.lastName`, etc

Y'never know

2024-08-28 18:22 UTC, danieljordan-caci commented on src/utils/queues.jsx
> +};
Can destructure here:
```
const addAssignedOfficeUser = (row) => {
  const { lastName, firstName, id } = row.assignedTo;
  row.availableOfficeUsers.push({
    label: `${lastName}, ${firstName}`,
    value: id,
  });
};
```

2024-08-28 18:22 UTC, danieljordan-caci commented on src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
> +  ),
![Screenshot 2024-08-28 at 1 03 44 PM](https://github.com/user-attachments/assets/9bde8ebb-2048-4024-93fc-8815cbab3421)

2024-08-28 18:22 UTC, danieljordan-caci commented on src/utils/queues.jsx
> +    </option>
Do you have any thoughts on truncating the label at all? 

For example if someone has a really long name it looks like this without truncation:
![Screenshot 2024-08-28 at 1 14 18 PM](https://github.com/user-attachments/assets/a0ddaedb-4e2f-439f-8157-7845017bfa22)
You can see that the width of the dropdown will be as wide as the longest name inside of it. Even this example it's starting to bleed off page.

If truncated:
```
    <option value={value} key={`filterOption_${value}`}>
      {label.length > 30 ? `${label.slice(0, 30)}...` : label}
    </option>
```
It looks like this:
![Screenshot 2024-08-28 at 1 16 59 PM](https://github.com/user-attachments/assets/b871fd02-5ad2-4a50-aad2-505cfae91e48)
Gives us a little more control of the width of the select box and avoids some crazy wide thing that flows off page.

Just a thought. Lemme know.

2024-08-28 18:24 UTC, danieljordan-caci requested changes

2024-08-28 18:24 UTC, danieljordan-caci commented on src/utils/queues.jsx
> +  // if theres an assigned user, assign to a variable so we can set a default value below
either put `there's` or `there is` here in the comments - sorry for the grammar police wee woo wee woo

2024-08-29 18:05 UTC, paulstonebraker commented on src/utils/queues.jsx
> +  // if theres an assigned user, assign to a variable so we can set a default value below
Don't say sorry if you're not actually sorry

2024-08-30 13:45 UTC, paulstonebraker commented
Code has been updated to address most comments; also updated to address a bug I discovered in queues.jsx util functions. formatAvailableOfficeUsersForRow was refactored to avoid issues of passing objs/arrays by reference

2024-08-30 13:46 UTC, paulstonebraker commented on src/utils/queues.jsx
> +    </option>
I'm going to leave as is but will bring up with the PO, personally in these cases I'd prefer to see the full name

2024-08-30 21:20 UTC, pambecker commented
Code works as expected.  just waiting on 508 screenshots.

2024-09-03 14:43 UTC, pambecker approved these changes

2024-09-04 13:36 UTC, merged