B-19463 add assigned user col to SC queue; add dropdown select to row
transcom/mymove pull request #13580
Opened 2024-08-28 05:19 UTC by paulstonebraker

## [Agility ticket](tbd)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-09-23 19:40 UTC, joeydoyecaci requested changes
Changes were made on ghc.yaml in swagger & swagger-def, adding AssignedOfficeUser and assignedTo respectively in this PR, but not in the int PR. These changes must be removed.

2024-09-26 16:48 UTC, paulstonebraker commented
> Changes were made on ghc.yaml in swagger & swagger-def, adding AssignedOfficeUser and assignedTo respectively in this PR, but not in the int PR. These changes must be removed.

My bad! I mistakenly opened this review and then took a half day and didn't undo my mistake 🤦  all should be good now

2024-09-26 17:46 UTC, pambecker approved these changes
Seems to be good.  as noted, differences seem to be due to Counseling office in main and it wasn't yet in int when that merged occurred.  built the branch locally and the Assigned column seems to function as expected.

2024-09-26 17:46 UTC, pambecker commented on src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
> +    createHeader('Counseling office', 'counselingOffice', {
The line count diff here seems to deal with Counseling office column being in main already vs it was not when you merged this code to INT.  Still seems good to go here, just moved lines from 187-191 up.

2024-09-26 19:02 UTC, joeydoyecaci approved these changes

2024-10-07 18:43 UTC, merged