B 20671 b 20574 b 20758 simulate process tpps cmd int
transcom/mymove pull request #13603
Opened 2024-08-29 20:04 UTC by traskowskycaci

## [Agility ticket](tbd)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-08-29 20:39 UTC, deandreJones commented on migrations/app/migrations_manifest.txt
> -20240820151043_add_gsr_role.up.sql
why remove this?

2024-08-29 20:41 UTC, traskowskycaci commented on migrations/app/migrations_manifest.txt
> -20240820151043_add_gsr_role.up.sql
It's already on line 997, I had the same question at first

2024-08-30 12:46 UTC, cameroncaci requested changes
Didn't run successfully. Got these logs:
```
➜  mymove git:(B-20671-B-20574-B-20758-simulate-process-tpps-cmd-INT) ✗ go run ./cmd/simulate-process-tpps/
2024-08-30T12:40:22.077Z	INFO	cli/dbconn.go:317	Connecting to the database	{"url": "postgres://postgres:*****@localhost:5432/dev_db?sslmode=disable", "db-ssl-root-cert": ""}
2024-08-30T12:40:22.079Z	INFO	invoice/process_tpps_paid_invoice_report.go:64	Successfully parsed TPPS Paid Invoice Report
2024-08-30T12:40:22.079Z	INFO	invoice/process_tpps_paid_invoice_report.go:67	RECEIVED: TPPS Paid Invoice Report Processor received a TPPS Paid Invoice Report
2024-08-30T12:40:22.097Z	ERROR	invoice/process_tpps_paid_invoice_report.go:252	failure saving entry from TPPS paid invoice report	{"error": "pq: insert or update on table \"tpps_paid_invoice_reports\" violates foreign key constraint \"tpps_paid_invoice_reports_invoice_number_fkey\""}
github.com/transcom/mymove/pkg/services/invoice.(*tppsPaidInvoiceReportProcessor).StoreTPPSPaidInvoiceReportInDatabase.func1
2024-08-30T12:40:22.098Z	ERROR	invoice/process_tpps_paid_invoice_report.go:261	pq: insert or update on table "tpps_paid_invoice_reports" violates foreign key constraint "tpps_paid_invoice_reports_invoice_number_fkey"
github.com/transcom/mymove/pkg/services/invoice.(*tppsPaidInvoiceReportProcessor).StoreTPPSPaidInvoiceReportInDatabase
2024-08-30T12:40:22.098Z	INFO	invoice/process_tpps_paid_invoice_report.go:76	Successfully stored TPPS Paid Invoice Report information in the database
2024-08-30T12:40:22.108Z	INFO	invoice/process_tpps_paid_invoice_report.go:107	SUCCESS: TPPS Paid Invoice Report Processor updated Payment Request to PAID status
2024-08-30T12:40:22.108Z	INFO	invoice/process_tpps_paid_invoice_report.go:131	TPPS Paid Invoice Report log	{"TPPSPaidInvoiceReportEntry.InvoiceNumber": "1077-4079-3", "PaymentRequestNumber": "1077-4079-3", "PaymentRequest.Status": "PAID", "PaymentRequest.ID": "4288a7eb-1efc-4e78-9049-092ea2909c05"}
2024-08-30T12:40:22.111Z	INFO	invoice/process_tpps_paid_invoice_report.go:107	SUCCESS: TPPS Paid Invoice Report Processor updated Payment Request to PAID status
2024-08-30T12:40:22.111Z	INFO	invoice/process_tpps_paid_invoice_report.go:131	TPPS Paid Invoice Report log	{"TPPSPaidInvoiceReportEntry.InvoiceNumber": "1208-5962-1", "PaymentRequestNumber": "1208-5962-1", "PaymentRequest.Status": "PAID", "PaymentRequest.ID": "ed2fe501-6bf7-4896-9521-777fc8fe8105"}
2024-08-30T12:40:22.113Z	INFO	invoice/process_tpps_paid_invoice_report.go:107	SUCCESS: TPPS Paid Invoice Report Processor updated Payment Request to PAID status
2024-08-30T12:40:22.113Z	INFO	invoice/process_tpps_paid_invoice_report.go:131	TPPS Paid Invoice Report log	{"TPPSPaidInvoiceReportEntry.InvoiceNumber": "8801-2773-2", "PaymentRequestNumber": "8801-2773-2", "PaymentRequest.Status": "PAID", "PaymentRequest.ID": "cfd110d4-1f62-401c-a92c-39987a0b4228"}
2024-08-30T12:40:22.115Z	ERROR	invoice/process_tpps_paid_invoice_report.go:117	sql: no rows in result set
github.com/transcom/mymove/pkg/services/invoice.(*tppsPaidInvoiceReportProcessor).ProcessFile
2024-08-30T12:40:22.115Z	ERROR	simulate-process-tpps/main.go:89	Error while processing TPPS Paid Invoice Report file	{"path": "pkg/services/invoice/fixtures/tpps_paid_invoice_report_testfile_tpps_pickup_dir.csv", "error": "sql: no rows in result set"}
	/Users/cameron.jewell_cn/Projects/mymove/cmd/simulate-process-tpps/main.go:89
2024-08-30T12:40:22.115Z	INFO	simulate-process-tpps/main.go:105	The tpps_paid_invoice_reports table should now have the following data:
2024-08-30T12:40:22.115Z	INFO	simulate-process-tpps/main.go:106
1077-4079-3	2024-08-05	2024-08-05	421.87	DUPK	DUPK	10340	0.0311	321.57	1077-4079-cabd6371	2
1077-4079-3	2024-08-05	2024-08-05	421.87	DDP	DDP	10340	0.0097	100.3	1077-4079-a4e717fd	1
1208-5962-1	2024-08-05	2024-08-05	557	MS	MS	1	557	557	1208-5962-e0fb5863	1
8801-2773-2	2024-08-05	2024-08-05	2748.04	DOP	DOP	1	77.02	77.02	8801-2773-f2bb471e	1
8801-2773-2	2024-08-05	2024-08-05	2748.04	DPK	DPK	1	2671.02	2671.02	8801-2773-fdaee177	2
8801-2773-3	2024-08-05	2024-08-05	1397.74	DDP	DDP	1	91.31	91.31	8801-2773-2e54e07d	2
8801-2773-3	2024-08-05	2024-08-05	1397.74	DLH	DLH	1	1052.84	1052.84	8801-2773-27961d7f	1
8801-2773-3	2024-08-05	2024-08-05	1397.74	FSC	FSC	1	6.66	6.66	8801-2773-f9e0672c	3
8801-2773-3	2024-08-05	2024-08-05	1397.74	DUPK	DUPK	1	246.93	246.93	8801-2773-c6c78cf9	4
```

Steps to reproduce:
`make db_dev_fresh`
`make build`
`go run ./cmd/simulate-process-tpps/`

2024-08-30 12:47 UTC, cameroncaci commented on cmd/simulate-process-tpps/main.go
> +
This file does not appear to exist - it may have gotten lost in intTesting during a merge conflict

2024-08-30 12:52 UTC, traskowskycaci commented on cmd/simulate-process-tpps/main.go
> +
That's not good - we should be seeing some failing tests if it's gone

2024-08-30 12:53 UTC, traskowskycaci commented on cmd/simulate-process-tpps/main.go
> +
I do see it in integration in https://github.com/transcom/mymove/blob/integrationTesting/pkg/services/invoice/fixtures/tpps_paid_invoice_report_testfile_tpps_pickup_dir.csv

2024-08-30 12:55 UTC, traskowskycaci commented on cmd/simulate-process-tpps/main.go
> +
@cameroncaci those error messages about violating a foreign key constraint look like they come from not having a payment request with a payment_request_number that matches the invoice_number of the test file. Did you update some payment request numbers to be 1077-4079-3, 1208-5962-1, 8801-2773-2, and 8801-2773-3?

2024-08-30 14:03 UTC, traskowskycaci commented
Marking as draft to incorporate some requested test data file changes per government PO request.

2024-08-30 20:04 UTC, traskowskycaci commented
> Marking as draft to incorporate some requested test data file changes per government PO request.

After discussion with PO, will be testing in the dev environment so no changes to the test file are needed.

2024-08-30 20:09 UTC, traskowskycaci commented on cmd/simulate-process-tpps/main.go
> +
Please retest when you're able to, I believe the issue will be resolved if you make sure to update the payment request numbers

2024-08-30 21:10 UTC, traskowskycaci commented
Failing server tests are resolved in this SSW PR: https://github.com/transcom/mymove/pull/13574/files

2024-09-03 13:05 UTC, cameroncaci commented on cmd/simulate-process-tpps/main.go
> +
```
```
All running normally. Comparing logs between the two, it would appear that payment request `8801-2773-3` encountered the constraint issue.

2024-09-03 13:06 UTC, cameroncaci commented on cmd/simulate-process-tpps/main.go
> +
```
2024-09-03T13:00:21.759Z	INFO	cli/dbconn.go:317	Connecting to the database	{"url": "postgres://postgres:*****@localhost:5432/dev_db?sslmode=disable", "db-ssl-root-cert": ""}
2024-09-03T13:00:21.760Z	INFO	invoice/process_tpps_paid_invoice_report.go:64	Successfully parsed TPPS Paid Invoice Report
2024-09-03T13:00:21.760Z	INFO	invoice/process_tpps_paid_invoice_report.go:67	RECEIVED: TPPS Paid Invoice Report Processor received a TPPS Paid Invoice Report
2024-09-03T13:00:21.790Z	INFO	invoice/process_tpps_paid_invoice_report.go:76	Successfully stored TPPS Paid Invoice Report information in the database
2024-09-03T13:00:21.801Z	INFO	invoice/process_tpps_paid_invoice_report.go:107	SUCCESS: TPPS Paid Invoice Report Processor updated Payment Request to PAID status
2024-09-03T13:00:21.801Z	INFO	invoice/process_tpps_paid_invoice_report.go:131	TPPS Paid Invoice Report log	{"TPPSPaidInvoiceReportEntry.InvoiceNumber": "1077-4079-3", "PaymentRequestNumber": "1077-4079-3", "PaymentRequest.Status": "PAID", "PaymentRequest.ID": "cfd110d4-1f62-401c-a92c-39987a0b4228"}
2024-09-03T13:00:21.803Z	INFO	invoice/process_tpps_paid_invoice_report.go:107	SUCCESS: TPPS Paid Invoice Report Processor updated Payment Request to PAID status
2024-09-03T13:00:21.803Z	INFO	invoice/process_tpps_paid_invoice_report.go:131	TPPS Paid Invoice Report log	{"TPPSPaidInvoiceReportEntry.InvoiceNumber": "1208-5962-1", "PaymentRequestNumber": "1208-5962-1", "PaymentRequest.Status": "PAID", "PaymentRequest.ID": "cfd110d4-1f62-401c-a92c-39987a0b4229"}
2024-09-03T13:00:21.805Z	INFO	invoice/process_tpps_paid_invoice_report.go:107	SUCCESS: TPPS Paid Invoice Report Processor updated Payment Request to PAID status
2024-09-03T13:00:21.805Z	INFO	invoice/process_tpps_paid_invoice_report.go:131	TPPS Paid Invoice Report log	{"TPPSPaidInvoiceReportEntry.InvoiceNumber": "8801-2773-2", "PaymentRequestNumber": "8801-2773-2", "PaymentRequest.Status": "PAID", "PaymentRequest.ID": "20ddf2ef-a7be-45e6-9dd3-7d050ba93ea3"}
2024-09-03T13:00:21.806Z	INFO	invoice/process_tpps_paid_invoice_report.go:107	SUCCESS: TPPS Paid Invoice Report Processor updated Payment Request to PAID status
2024-09-03T13:00:21.806Z	INFO	invoice/process_tpps_paid_invoice_report.go:131	TPPS Paid Invoice Report log	{"TPPSPaidInvoiceReportEntry.InvoiceNumber": "8801-2773-3", "PaymentRequestNumber": "8801-2773-3", "PaymentRequest.Status": "PAID", "PaymentRequest.ID": "e00c4325-d6e2-4a80-bd36-8d21a6239186"}
2024-09-03T13:00:21.808Z	INFO	simulate-process-tpps/main.go:105	The tpps_paid_invoice_reports table should now have the following data:
2024-09-03T13:00:21.809Z	INFO	simulate-process-tpps/main.go:106
1077-4079-3	2024-08-05	2024-08-05	421.87	DUPK	DUPK	10340	0.0311	321.57	1077-4079-cabd6371	2
1077-4079-3	2024-08-05	2024-08-05	421.87	DDP	DDP	10340	0.0097	100.3	1077-4079-a4e717fd	1
1208-5962-1	2024-08-05	2024-08-05	557	MS	MS	1	557	557	1208-5962-e0fb5863	1
8801-2773-2	2024-08-05	2024-08-05	2748.04	DOP	DOP	1	77.02	77.02	8801-2773-f2bb471e	1
8801-2773-2	2024-08-05	2024-08-05	2748.04	DPK	DPK	1	2671.02	2671.02	8801-2773-fdaee177	2
8801-2773-3	2024-08-05	2024-08-05	1397.74	DDP	DDP	1	91.31	91.31	8801-2773-2e54e07d	2
8801-2773-3	2024-08-05	2024-08-05	1397.74	DLH	DLH	1	1052.84	1052.84	8801-2773-27961d7f	1
8801-2773-3	2024-08-05	2024-08-05	1397.74	FSC	FSC	1	6.66	6.66	8801-2773-f9e0672c	3
8801-2773-3	2024-08-05	2024-08-05	1397.74	DUPK	DUPK	1	246.93	246.93	8801-2773-c6c78cf9	4
```
All running normally. Comparing logs between the two, it would appear that payment request `8801-2773-3` encountered the constraint issue the first time around. Have no idea why because I shouldn't have been able to even set the payment request to a value that would violate the constraint, but it's working now as intended

2024-09-03 13:15 UTC, traskowskycaci commented on cmd/simulate-process-tpps/main.go
> +
That is odd - will see if anyone else runs into the same issue and investigate further if they do. Thanks for taking a look!

2024-09-03 13:16 UTC, cameroncaci requested changes

2024-09-03 13:16 UTC, cameroncaci commented on cmd/simulate-process-tpps/main.go
> +func checkConfig(v *viper.Viper, logger *zap.Logger) error {
Can we add an extra comment to describe that this binary will be explicitly for simulation and testing purposes for the scenario of payment request numbers `1077-4079-3`, `1208-5962-1`, `8801-2773-2`, `8801-2773-3`

Otherwise, the only indicator is the filename

2024-09-03 16:37 UTC, danieljordan-caci approved these changes
Tested locally - LGTM!

2024-09-03 17:17 UTC, traskowskycaci commented
Demoing this in the dev environment today, 9/3/24, with the gov PO's approval to do so after discussion last week on testing the remaining TPPS stories.

When done with the demo and 20671 and 20758 stories are PO accepted in Agility, will merge into integration and then create the corresponding main PR. 20674 already has PO acceptance.

2024-09-03 18:49 UTC, merged