B 21015 int
transcom/mymove pull request #13615
Opened 2024-09-03 15:57 UTC by deandreJones

## [B-21015](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A1005508)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the Swagger UI
2. run the v1 prime listmoves api - grab a move uuid
3. run the v3 prime getMoveTaskOrder api
4. verify that county returns for address objects

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

## Screenshots
Before
 
![image](https://github.com/user-attachments/assets/d90d19c7-4b4e-452b-b790-63f4080c460d)

After

 
![image](https://github.com/user-attachments/assets/4c7891de-eee8-461f-b169-3d6db1157053)

2024-09-03 16:05 UTC, danieljordan-caci commented on pkg/services/mto_service_item/mto_service_item_validators.go
> +
the heck - why was this taken out in `main`?

2024-09-03 16:06 UTC, danieljordan-caci requested changes

2024-09-03 16:06 UTC, danieljordan-caci commented on pkg/handlers/primeapiv3/payloads/model_to_payload.go
>  }
Can you update a test please? `TestGetMoveTaskOrder` will work!

2024-09-03 19:53 UTC, deandreJones commented on pkg/handlers/primeapiv3/payloads/model_to_payload.go
>  }
added

2024-09-04 17:03 UTC, traskowskycaci commented on pkg/services/mto_service_item/mto_service_item_validators.go
> +
I'm still seeing this in main, I remember it being a confusing thing to merge:
 https://github.com/transcom/mymove/blob/3a2885a628217ba1b6e1dcb32acf1341cb370693/pkg/services/mto_service_item/mto_service_item_validators.go#L134

2024-09-04 17:10 UTC, traskowskycaci approved these changes
Looks good!
![image](https://github.com/user-attachments/assets/20717081-22a0-4dbc-b8dc-aec42dc600e5)

2024-09-04 19:45 UTC, deandreJones commented on pkg/handlers/primeapiv3/payloads/model_to_payload.go
>  }
@danieljordan-caci ping

2024-09-04 19:47 UTC, danieljordan-caci approved these changes

2024-09-04 19:56 UTC, merged