INT-B-20492
transcom/mymove pull request #13636
Opened 2024-09-05 01:30 UTC by loganwc

## [Agility ticket](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A980560&RoomContext=TeamRoom%3A848240&concept=TeamRoom)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

### How to test

1. Access the office app
2. Login as a TIO
3. Open a move with Proof of Service docs (ORGSIT from seed data)
4. Review Payment Request and approve
5. Click View Documents
6. Click `Download All Files (PDF)` button at top of document viewer
7. Accept download and review pdf has all proof of service uploads

2024-09-05 22:03 UTC, pambecker approved these changes

2024-09-06 16:09 UTC, paulstonebraker commented
![image](https://github.com/user-attachments/assets/c41d8afd-2d9a-41ba-ac65-d8afaaf19213)
Can we find a different spot for the button? It adds a vertical scroll to the whole page

2024-09-06 16:14 UTC, paulstonebraker commented
> ![image](https://private-user-images.githubusercontent.com/147535220/365234439-c41d8afd-2d9a-41ba-ac65-d8afaaf19213.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MzkyOTAsIm5iZiI6MTcyNTYzODk5MCwicGF0aCI6Ii8xNDc1MzUyMjAvMzY1MjM0NDM5LWM0MWQ4YWZkLTJkOWEtNDFiYS1hYzY1LWQ4YWZhYWYxOTIxMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNlQxNjA5NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOWY4ZGQyNDU3OGIwODE5YzQ5OTk0ZjFkMjVhZmM4NzRjNjlhMGE2OTViNmRhMGYyYTQyMTA2ZjZjMDJmZmJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-8vrFEERb5KxlznNBu2K6QpzMMfmWjvgB4SQbYQWuGo) Can we find a different spot for the 'Download All Files' button? It adds a vertical scroll to the whole page

suggestion: supporting documents and order have a 'Download File' button here... since we don't have that for the TIO view documents, maybe put it here? otherwise maybe in the hamburger button?

![image](https://github.com/user-attachments/assets/cff15abc-e21d-4eca-a05d-ee927279060e)

2024-09-06 16:16 UTC, loganwc commented
> > ![image](https://private-user-images.githubusercontent.com/147535220/365234439-c41d8afd-2d9a-41ba-ac65-d8afaaf19213.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MzkyOTAsIm5iZiI6MTcyNTYzODk5MCwicGF0aCI6Ii8xNDc1MzUyMjAvMzY1MjM0NDM5LWM0MWQ4YWZkLTJkOWEtNDFiYS1hYzY1LWQ4YWZhYWYxOTIxMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNlQxNjA5NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOWY4ZGQyNDU3OGIwODE5YzQ5OTk0ZjFkMjVhZmM4NzRjNjlhMGE2OTViNmRhMGYyYTQyMTA2ZjZjMDJmZmJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-8vrFEERb5KxlznNBu2K6QpzMMfmWjvgB4SQbYQWuGo) Can we find a different spot for the 'Download All Files' button? It adds a vertical scroll to the whole page
> 
> suggestion: supporting documents and order have a 'Download File' button here... since we don't have that for the TIO view documents, maybe put it here? otherwise maybe in the hamburger button?
> 
> ![image](https://private-user-images.githubusercontent.com/147535220/365236073-cff15abc-e21d-4eca-a05d-ee927279060e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2Mzk2NTcsIm5iZiI6MTcyNTYzOTM1NywicGF0aCI6Ii8xNDc1MzUyMjAvMzY1MjM2MDczLWNmZjE1YWJjLWUyMWQtNGVjYS1hMDVkLWVlOTI3Mjc5MDYwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNlQxNjE1NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZGNlYTc0ZGRjMTQ5Y2U5MjI1ZDVlMWQyYTI5OGJhZDE5ZWM1NTYzOGZlNDQ1ZjM2NmMyOGM2MDJkNjZkYmRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Kdr3H5CqOWaRxiG7Q2ZdQROSotJdqcoHI4vARDvggfA)

That would require me to modify the document viewer and prop drill all that information and it would've been pretty messy

2024-09-06 16:25 UTC, paulstonebraker requested changes

2024-09-06 16:25 UTC, paulstonebraker commented on swagger-def/ghc.yaml
> +          $ref: '#/responses/PermissionDenied'
I don't believe 403 or 404 are used, if so remove them pleasies

2024-09-06 16:26 UTC, paulstonebraker commented
> > > ![image](https://private-user-images.githubusercontent.com/147535220/365234439-c41d8afd-2d9a-41ba-ac65-d8afaaf19213.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MzkyOTAsIm5iZiI6MTcyNTYzODk5MCwicGF0aCI6Ii8xNDc1MzUyMjAvMzY1MjM0NDM5LWM0MWQ4YWZkLTJkOWEtNDFiYS1hYzY1LWQ4YWZhYWYxOTIxMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNlQxNjA5NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOWY4ZGQyNDU3OGIwODE5YzQ5OTk0ZjFkMjVhZmM4NzRjNjlhMGE2OTViNmRhMGYyYTQyMTA2ZjZjMDJmZmJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-8vrFEERb5KxlznNBu2K6QpzMMfmWjvgB4SQbYQWuGo) Can we find a different spot for the 'Download All Files' button? It adds a vertical scroll to the whole page
> > 
> > 
> > suggestion: supporting documents and order have a 'Download File' button here... since we don't have that for the TIO view documents, maybe put it here? otherwise maybe in the hamburger button?
> > ![image](https://private-user-images.githubusercontent.com/147535220/365236073-cff15abc-e21d-4eca-a05d-ee927279060e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2Mzk2NTcsIm5iZiI6MTcyNTYzOTM1NywicGF0aCI6Ii8xNDc1MzUyMjAvMzY1MjM2MDczLWNmZjE1YWJjLWUyMWQtNGVjYS1hMDVkLWVlOTI3Mjc5MDYwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNlQxNjE1NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZGNlYTc0ZGRjMTQ5Y2U5MjI1ZDVlMWQyYTI5OGJhZDE5ZWM1NTYzOGZlNDQ1ZjM2NmMyOGM2MDJkNjZkYmRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Kdr3H5CqOWaRxiG7Q2ZdQROSotJdqcoHI4vARDvggfA)
> 
> That would require me to modify the document viewer and prop drill all that information and it would've been pretty messy

okay, where else can we move it so its not there 😄

2024-09-06 16:31 UTC, paulstonebraker commented
Very nicely done, code works. I think `Download all files` button should be moved but if team over rules me I will happily approve.

2024-09-06 16:47 UTC, pambecker commented
> Very nicely done, code works. I think `Download all files` button should be moved but if team over rules me I will happily approve.

Paul, if you move off of this branch and pull up the View Docs, that scroll bar is not there?  I wasn't seeing a scroll bar when I tested, but my doc was not full page I guess?

2024-09-06 17:23 UTC, paulstonebraker commented
> > > Very nicely done, code works. I think `Download all files` button should be moved but if team over rules me I will happily approve.
> > 
> > 
> > Paul, if you move off of this branch and pull up the View Docs, that scroll bar is not there? I wasn't seeing a scroll bar when I tested, but my doc was not full page I guess?
> 
> I'm not sure, I will check. Personally, I just don't like the `Download all files` link taking up that entire section of my screen. But if it doesn't bug anyone else besides me, I certainly won't let it block my approval 😺

Just checked and viewing the same move/document, scroll did not appear off this branch.

2024-09-06 18:11 UTC, pambecker commented
> > > > Very nicely done, code works. I think `Download all files` button should be moved but if team over rules me I will happily approve.
> > > 
> > > 
> > > Paul, if you move off of this branch and pull up the View Docs, that scroll bar is not there? I wasn't seeing a scroll bar when I tested, but my doc was not full page I guess?
> > 
> > 
> > I'm not sure, I will check. Personally, I just don't like the `Download all files` link taking up that entire section of my screen. But if it doesn't bug anyone else besides me, I certainly won't let it block my approval 😺
> 
> Just checked and viewing the same move/document, scroll did not appear off this branch.

yeah, I agree, we don't want to introduce a scroll if there's a way around it.  Logan can you see about a way to prevent the scroll?

2024-09-09 17:31 UTC, paulstonebraker commented on swagger-def/ghc.yaml
> +          $ref: '#/responses/PermissionDenied'
😬

2024-09-10 16:37 UTC, merged