INT-B-20618 Office users edit/create/delete mobile home shipments
transcom/mymove pull request #13650
Opened 2024-09-06 15:59 UTC by brooklyn-welsh

## [Agility ticket](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-20618)

## Summary

Most of this ticket was actually rendered OBE by Aaron's work on B-20617 (his PR is here: #13642).

However while looking into this story I found that feature flag checks were missing on the frontend for the "Add a new shipment" dropdown that is at the top of the "Move Details" page when an office user clicks on a move. There was also a flag check missing from the Prime UI "Create Shipment" form.

So, this branch adds checks for both of these, if you edit the .envrc to disallow mobile home shipments, you should no longer see an option to choose mobile home shipment types from either of these menus.

### How to test

1. Edit the .envrc and make the mobile home flag set to FALSE (running a find for "mobile" will take you to the flag).
2. Access a move as an SC.
3. Click the "Add a new shipment" dropdown and confirm that "Mobile Home" is **not** an option.
4. Repeat step 3 for TIO/TOO.
5. Access a move as a Prime sim user.
6. Click the "Create Shipment" button on the page, then on the next form confirm that "MOBILE_HOME" is **not** an option for the shipment type.

2024-09-06 21:14 UTC, WeatherfordAaron approved these changes
lgtm 👽 
Only thing is there are conflicts with the go ver stuff

2024-09-09 15:19 UTC, cameroncaci requested changes

2024-09-09 15:19 UTC, cameroncaci commented on pkg/services/move/move_router.go
> +			move.MTOShipments[i].Status = models.MTOShipmentStatusSubmitted
Please add test coverage for these lines

2024-09-09 20:11 UTC, taeJungCaci commented
Just to let you know, Aaron's story didn't include the approve, edit, and delete portion so it doesn't have any playwright tests for those - which I am adding those tests for boat in my current story. While most things may work out of the box for mobile homes - I had to fix some stuff on the boat shipment side and also add in those tests.

2024-09-13 20:43 UTC, brooklyn-welsh commented on pkg/services/move/move_router.go
> +			move.MTOShipments[i].Status = models.MTOShipmentStatusSubmitted
@cameroncaci Added tests for the if cases in this section in move_router_test.go for the boat and mobile home shipment types. Didn't get the tests to cover the error blocks though, couldn't find anywhere in the app where anyone had written tests to cover these DB validation functions, so I assumed you just meant the "happy path" for each.

If not I might need some guidance on how I would write a go test to reach this error statement, as I can't pass in an incorrectly formed struct without the Go compiler catching it, and my attempts to mock it were unsuccessful, I assume since this is in a private function.

2024-09-16 19:10 UTC, cameroncaci commented on pkg/services/move/move_router.go
> +			move.MTOShipments[i].Status = models.MTOShipmentStatusSubmitted
@brooklyn-welsh 
`ValidateAndUpdate` is just based on the model's "Validate" function, see `func (m *MTOShipment) Validate` in `pkg/models/mto_shipments.go`. You would trigger these errors by passing in a shipment that does not satisfy the validation. Examples can be found at `pkg/models/mto_shipments_test.go`

2024-09-20 21:14 UTC, brooklyn-welsh commented on pkg/services/move/move_router.go
> +			move.MTOShipments[i].Status = models.MTOShipmentStatusSubmitted
Okay, newest push should show that all of the errors around this are now covered. Also added another error block as I found the original was only testing the "MTOShipment" object, but wanted one to also cover the "BoatShipment" or "MobileHome" object as well.

2024-09-23 13:14 UTC, cameroncaci commented on pkg/services/move/move_router.go
> +			move.MTOShipments[i].Status = models.MTOShipmentStatusSubmitted
Mobile home shipment code coverage still missing, additionally how come the boat status update has the following condition? `move.MTOShipments[i].ShipmentType == models.MTOShipmentTypeMobileHome` - line 213. This condition is hit a second time on line 229
![image](https://github.com/user-attachments/assets/1ab81cf0-be24-4c45-ad4f-7b41b3631024)

2024-09-23 15:00 UTC, brooklyn-welsh commented on pkg/services/move/move_router.go
> +			move.MTOShipments[i].Status = models.MTOShipmentStatusSubmitted
I'm actually not sure, for context, I think due my branch being dependent on a branch that wasn't merged yet, when I drafted this PR it showed this file as changed by me, but I didn't actually touch this file for this branch at all. (Except now for the tests that have been added).

But my guess is that it looks like from the blame that there were two PR's pretty close to each other and one was responsible for just mobile homes and accidentally added an extra if block. Didn't catch that when writing tests either.

But I'm about to push a change that gets rid of it, and adds the validateandsave for mobile homes into the boat/mobile if block, where it is now covered by the test.

2024-09-23 16:45 UTC, brooklyn-welsh commented on pkg/services/move/move_router.go
> +			move.MTOShipments[i].Status = models.MTOShipmentStatusSubmitted
@cameroncaci Also just pushed a fix for a few tests as well, had accidentally moved the validateAndSave() function for the whole move object inside of the if-block for boat/mobile. But the entire section with mobile/boat code should now show as green.

2024-09-24 16:01 UTC, cameroncaci approved these changes

2024-09-24 16:02 UTC, cameroncaci commented on pkg/services/move/move_router.go
> +			move.MTOShipments[i].Status = models.MTOShipmentStatusSubmitted
Great, thank you! Resolving and approving 🚀

2024-09-26 20:05 UTC, merged