B-19810 INT
transcom/mymove pull request #13677
Opened 2024-09-10 19:03 UTC by traskowskycaci

## [Agility ticket](tbd)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-09-11 14:07 UTC, danieljordan-caci submitted a review, later dismissed

2024-09-11 14:07 UTC, danieljordan-caci commented on src/components/LeftNavTag/LeftNavTag.module.scss
> +  background-color: $error;
You don't want to blanket apply this styling inside this file - since this is a frequently reused component, we should handle changing the background color where the components are rendered.

You should instead conditionally apply the background color through the props, like so:
```
          <LeftNavTag
            background="#d63E04"
            associatedSectionName="requested-shipments"
            showTag={needsPpmAdvanceReviewCount !== 0}
            testID="advanceTag"
          >
```

2024-09-13 14:10 UTC, cameroncaci requested changes
cANDI didn't pass
![image](https://github.com/user-attachments/assets/799c8b76-7cd5-4838-920d-315ed67dbf74)

2024-09-13 14:12 UTC, traskowskycaci commented
> cANDI didn't pass ![image](https://private-user-images.githubusercontent.com/136814362/367327758-799c8b76-7cd5-4838-920d-315ed67dbf74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMzY5OTEsIm5iZiI6MTcyNjIzNjY5MSwicGF0aCI6Ii8xMzY4MTQzNjIvMzY3MzI3NzU4LTc5OWM4Yjc2LTdjZDUtNDgzOC05MjBkLTMxNWVkNjdkYmY3NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxM1QxNDExMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MzIxNDJlZDc5YjdkYWE1ODBhNTJmZDQyYTJhMDUzMWI0OTJjZjhiOTI3Y2NlYzMyOWE1ODVjMWRmOGNjMzBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.44vLJ0eV3y0H8Nm1N1xfhdqZTN8liXNRvDXz-uDctXw)

Good catch @cameroncaci, this will also impact the other stories on this feature

2024-09-13 14:46 UTC, traskowskycaci commented
> cANDI didn't pass ![image](https://private-user-images.githubusercontent.com/136814362/367327758-799c8b76-7cd5-4838-920d-315ed67dbf74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMzgwNTQsIm5iZiI6MTcyNjIzNzc1NCwicGF0aCI6Ii8xMzY4MTQzNjIvMzY3MzI3NzU4LTc5OWM4Yjc2LTdjZDUtNDgzOC05MjBkLTMxNWVkNjdkYmY3NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxM1QxNDI5MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NmQ2NzRjOTM5YzM3NTMzNTY2MzM5N2FlZTZkMzM0YjZiNGE3N2UxOWMzYWZlYmMxN2EyNzZmODNmMTE1Y2JjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.q4VLv3Dy9RFrN8UCEGYWFyKp63V7TAMdmQsn5LJH7xg)

Resolved using the suggested color for the background:
![image](https://github.com/user-attachments/assets/8a4af642-7c3b-4afd-b4cd-0d32d383a4b8)

2024-09-13 14:54 UTC, traskowskycaci commented
[B-21097](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A1010363) created to take care of the existing color contrast fail @cameroncaci

2024-09-13 15:16 UTC, cameroncaci approved these changes
Works as intended

2024-09-13 15:36 UTC, TevinAdams approved these changes

2024-09-13 15:37 UTC, merged