test prev cache key
transcom/mymove pull request #13707
Opened 2024-09-13 13:57 UTC by deandreJones

v6 and v7 keys not being restored, testing previous keys

2024-09-16 13:55 UTC, traskowskycaci reviewed
Do the restore_cache_for_go and save_cache_for_go also need to go from v7 to v8?

2024-09-20 17:36 UTC, deandreJones commented
> Do the restore_cache_for_go and save_cache_for_go also need to go from v7 to v8?

only when we upgrade a go version

2024-09-23 16:01 UTC, danieljordan-caci requested changes

2024-09-23 16:01 UTC, danieljordan-caci commented on README.md
> +This repository contains the application source code for the MilMove application,the next generation version of the Defense Personal Property System (DPS). DPS is an online system managed by the U.S.
I hate to do this, but can you add a space after the comma here?
```
the MilMove application, the
```

2024-09-23 16:02 UTC, deandreJones commented on README.md
> +This repository contains the application source code for the MilMove application,the next generation version of the Defense Personal Property System (DPS). DPS is an online system managed by the U.S.
why do you hate to do it.. I want it grammatically correct- I failed English, lol

2024-09-23 16:03 UTC, danieljordan-caci commented on README.md
> +This repository contains the application source code for the MilMove application,the next generation version of the Defense Personal Property System (DPS). DPS is an online system managed by the U.S.
lol because it's a butterfly fart size of a change and this has been open since last week haha

2024-09-23 16:15 UTC, deandreJones commented on README.md
> +This repository contains the application source code for the MilMove application,the next generation version of the Defense Personal Property System (DPS). DPS is an online system managed by the U.S.
every space matters

2024-09-23 16:44 UTC, danieljordan-caci approved these changes

2024-09-23 17:42 UTC, merged