B-21041-INT Prime can update second/third addresses
transcom/mymove pull request #13702
Opened 2024-09-12 15:52 UTC by paulstonebraker

## [Agility ticket](tbd)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-09-16 20:34 UTC, pambecker approved these changes

2024-09-17 19:34 UTC, loganwc requested changes

2024-09-17 19:34 UTC, loganwc commented on src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateAddress.test.jsx
> -        expect(screen.getAllByLabelText('State')[0]).toHaveValue(shipment.destinationAddress.state);
is your new code tested?

2024-09-17 19:41 UTC, paulstonebraker commented on src/pages/PrimeUI/Shipment/PrimeUIShipmentUpdateAddress.test.jsx
> -        expect(screen.getAllByLabelText('State')[0]).toHaveValue(shipment.destinationAddress.state);
Yes. I refactored this component to display/allow to edit the address you click "edit" on. The previous version had both pickup and destination addresses on it, with separate save buttons that would save that specific address, and return to move details screen.

2024-09-17 19:43 UTC, paulstonebraker commented on pkg/handlers/primeapi/mto_shipment_address.go
> +				(dbShipment.DestinationAddressID == nil || *dbShipment.DestinationAddressID == addressID) {
@ajlusk I updated this and the NTSR below to allow for clearer error messaging when a move does not yet have an existing destination (for NTS) or pickup (for NTSR) address... do you see this check causing any issues that I'm not thinking of?

2024-09-17 19:52 UTC, ajlusk commented on pkg/handlers/primeapi/mto_shipment_address.go
> +				(dbShipment.DestinationAddressID == nil || *dbShipment.DestinationAddressID == addressID) {
No concerns come to mind. Covers a scenario I missed. ✅

2024-09-18 14:07 UTC, pambecker commented on pkg/handlers/primeapi/mto_shipment_address.go
> +				(dbShipment.DestinationAddressID != nil || *dbShipment.DestinationAddressID == addressID) {
I believe we want these to be && if statements don't we?

2024-09-18 19:29 UTC, loganwc approved these changes

2024-09-18 19:42 UTC, pambecker commented
All code looks good and is working according to steps listed.  Just need the AC in the Agility story updated, believe this is waiting on word with Terri.

2024-09-18 21:38 UTC, pambecker approved these changes

2024-09-18 22:54 UTC, merged