INT b 20465 customer selecting counseling office
transcom/mymove pull request #13713
Opened 2024-09-13 20:00 UTC by JonSpight

## [Agility ticket](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-20465)

## Summary
When a customer selects an origin duty location assigned to government counseling, then they will also be asked to select a counseling office within the same GBLOC. This field will be called "Counseling Office".

### How to test as a Customer
1.  Login as a Customer
2. Select a counseling Office while creating a new move
3. Check the Moves data table for corresponding counseling_office_id

### How to test as a Service Counselor
1.  Login as a Service Counselor
2. Verify the counseling queue's counseling Office column matches what was created in previous move

## 508 Screenshots
[508Screenshots-20465.pdf](https://github.com/user-attachments/files/16971315/508Screenshots-20465.pdf)

2024-09-17 19:09 UTC, loganwc requested changes

2024-09-17 19:10 UTC, loganwc commented
You have a few files in there that I don't think are apart of your PR

2024-09-17 22:15 UTC, JonSpight commented on .project
> +<?xml version="1.0" encoding="UTF-8"?>
removed it.

2024-09-17 22:15 UTC, JonSpight commented on .project
> +<?xml version="1.0" encoding="UTF-8"?>
along with the other files .

2024-09-18 15:45 UTC, pambecker commented
I'm not seeing the new text required on the UI to meet the first AC in the story.

Given I am a Milmove customer
When I am on the create orders page
Then I see this instructional text below the Current duty Location field:
"Select an origin duty location that most closely represents your current physical location, not where your shipment will originate, if different. This will allow a nearby transportation office to assist you."

![image](https://github.com/user-attachments/assets/a9c1f93f-7116-4b49-b87e-80b527c95349)

2024-09-18 15:54 UTC, pambecker commented
We need to have the 'Required' label on this new field and not enable the Next button until it's filled out.  This is how the other fields work.  
And the Red Required text when the field is cleared out like the other fields do.

![image](https://github.com/user-attachments/assets/e52003d8-49e9-4829-a4c8-12560495593a)

![image](https://github.com/user-attachments/assets/4ecc184b-d37f-4d62-ba42-72df7cb6e475)

2024-09-18 16:06 UTC, pambecker commented
Found an issue.  When I first pick a govt counseled duty location and choose a counseling office, then go back and change the origin duty location to a GHC prime counseled (NS Mayport), complete the form and save.  My previously picked counseling office is still saved to the counseling_transportation_office_id in the DB and it should have been nulled out.

2024-09-18 16:07 UTC, pambecker requested changes
Added some feedback for cleanup.

2024-09-23 17:17 UTC, closed without merging