B 20631 upgrade go 1.23.0 nodejs 18.20.4 int
transcom/mymove pull request #13728
Opened 2024-09-16 21:50 UTC by cameroncaci

## [Agility ticket](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-20641)

## Summary

Bring main to int
Bump go to `1.23.0`
Bump nodejs to `18.20.4` (LTS)
Bump CI/CD container to https://github.com/transcom/circleci-docker/pull/470

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

2024-09-17 21:06 UTC, traskowskycaci commented on .circleci/config.yml
Wondering if the v7-server-tests-coverage on line 1556 should be v8? cc @deandreJones

2024-09-17 21:09 UTC, deandreJones commented on .circleci/config.yml
what cam has is fine

2024-09-17 21:12 UTC, traskowskycaci requested changes
Still seeing go-version: '1.22.2' in `.github/workflows/go-auto-approve.yml`

Had a question about v7-server-tests-coverage in .circleci/config.yml - resolved

Only requesting changes for visibility, feel free to dismiss review if no changes needed

2024-09-17 21:14 UTC, cameroncaci commented
> Still seeing go-version: '1.22.2' in `.github/workflows/go-auto-approve.yml`
> 
> Had a question about v7-server-tests-coverage in .circleci/config.yml - resolved
> 
> Only requesting changes for visibility, feel free to dismiss review if no changes needed

Great catch, thank you. Resolved now

2024-09-17 21:20 UTC, traskowskycaci approved these changes
Looks good!

2024-09-18 19:32 UTC, TevinAdams approved these changes

2024-09-19 15:41 UTC, merged