B19795 main doc viewer doc title change
transcom/mymove pull request #13740
Opened 2024-09-19 15:54 UTC by JamesHawks224

## Agility ticket
[B19795](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-19795)

## INT PR
[13623](https://github.com/transcom/mymove/pull/13623)

## Summary/Testing/ANDI/Screenshots
* See INT PR's

2024-09-19 18:20 UTC, taeJungCaci requested changes
Is there another INT PR related to these changes? I am seeing multiple differences with the INT PR you have referenced.

2024-09-19 18:20 UTC, taeJungCaci commented on src/components/DocumentViewerFileManager/DocumentViewerFileManager.jsx
> +import { appendTimestampToFilename } from 'utils/appendTimestampToFilename';
This part seems to be different from the INT PR

2024-09-19 18:20 UTC, taeJungCaci commented on src/pages/MyMove/AdditionalDocuments/AdditionalDocuments.jsx
> +    return createUploadForAdditionalDocuments(newFile, moveId);
These are also different from INT PR

2024-09-20 20:39 UTC, JamesHawks224 commented on src/pages/MyMove/AdditionalDocuments/AdditionalDocuments.jsx
> +    return createUploadForAdditionalDocuments(newFile, moveId);
I made changes to the main branch after I merged into the int branch.  I forgot to merge those into the int branch.  The changes were code refactoring to improve the code.  There were no functional changes or bug fixes.  Since the int branch was tested and accepted, I reverted the main branch back to the commit that was merged into int.  This should fix the discrepancies you were seeing.

2024-09-20 20:39 UTC, JamesHawks224 commented on src/components/DocumentViewerFileManager/DocumentViewerFileManager.jsx
> +import { appendTimestampToFilename } from 'utils/appendTimestampToFilename';
I made changes to the main branch after I merged into the int branch.  I forgot to merge those into the int branch.  The changes were code refactoring to improve the code.  There were no functional changes or bug fixes.  Since the int branch was tested and accepted, I reverted the main branch back to the commit that was merged into int.  This should fix the discrepancies you were seeing.

2024-09-25 20:03 UTC, taeJungCaci commented
As per Dre, the coverage test needs to pass for these to get merged in now.

2024-10-04 20:09 UTC, WeatherfordAaron approved these changes
lgtm

2024-10-16 21:37 UTC, deandreJones commented
> @deandreJones want you to see this and get your thoughts
> 
> To attempt to satisfy code coverage tests have been added in this PR that are not existing in INT. You cool with that?

its unfortunate that the coverage wasn't caught in INT- but any changes that are needed for this branch to pass builds, must be put back into integrationTesting- prior to this branch merging into main
avoiding going back to main, is what gets us in merge conflict issues- the only exceptions to bypassing main, is library updates and config changes that bright stars team may have

2024-10-22 22:07 UTC, taeJungCaci commented
Added a few tests and got enough coverage to pass. I will merge this once we get that INT PR created and merged in @JamesHawks224

2024-10-23 16:43 UTC, brooklyn-welsh approved these changes
LGTM!

2024-10-24 14:29 UTC, taeJungCaci approved these changes
LGTM

2024-10-24 14:30 UTC, brooklyn-welsh approved these changes
LGTM!

2024-10-24 14:51 UTC, merged