B-20465-INT - Add Counseling Office Selection to Customer Application
transcom/mymove pull request #13779
Opened 2024-09-27 20:53 UTC by JonSpight

## [Agility ticket](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-20465)

## Summary
When a customer selects an origin duty location assigned to government counseling, then they will also be asked to select a counseling office within the same GBLOC. This field will be called "Counseling Office".

### How to test as a Customer
1.  Login as a Customer
2. Select a counseling Office while creating a new move
3. Check the Moves data table for corresponding counseling_office_id

### How to test as a Service Counselor
1.  Login as a Service Counselor
2. Verify the counseling queue's counseling Office column matches what was created in previous move

## 508 Screenshots
[508Screenshots-20465.pdf](https://github.com/user-attachments/files/16971315/508Screenshots-20465.pdf)

2024-09-30 16:02 UTC, paulstonebraker requested changes

2024-09-30 17:00 UTC, JonSpight commented on src/components/Customer/OrdersInfoForm/OrdersInfoForm.jsx
> +                    assist
good catch - fixed

2024-09-30 17:00 UTC, JonSpight commented on src/pages/MyMove/AddOrders.jsx
> +      pendingValues.counseling_office_id = undefined;
you're right, just fixed this too.

2024-09-30 17:00 UTC, JonSpight commented on src/components/Table/SearchResultsTable.jsx
> +import { useFilters, usePagination, useSortBy, useTable } from 'react-table';
Nope nothing was changed aside from the ordering.

2024-09-30 18:03 UTC, paulstonebraker approved these changes

2024-09-30 18:03 UTC, paulstonebraker commented
Nice work!

2024-09-30 20:49 UTC, pambecker commented
conflicts

2024-10-01 14:25 UTC, pambecker commented on src/components/Table/SearchResultsTable.jsx
> +import { useFilters, usePagination, useSortBy, useTable } from 'react-table';
You didn't change anything in this file?  Then just curious how it shows up with these changes?  We don't want to introduce changes that aren't required or our backlog ususally.

2024-10-01 15:58 UTC, JonSpight commented on src/components/Table/SearchResultsTable.jsx
> +import { useFilters, usePagination, useSortBy, useTable } from 'react-table';
there weren't any changes, the differences came from the ordering. Which changed when I was doing merge conflicts. I put them back now.

2024-10-01 15:58 UTC, JonSpight commented on src/components/Customer/OrdersInfoForm/OrdersInfoForm.jsx
> +  const [officeOptions, setOfficeOptions] = useState(null);
Good Call, just fixed this!

2024-10-02 11:56 UTC, pambecker commented on src/components/Customer/OrdersInfoForm/OrdersInfoForm.jsx
> +  const [counselingOfficeOptions, setcounselingOfficeOptions] = useState(null);
This needs to be camelCase, setCounselingOfficeOptions

2024-10-02 23:08 UTC, JonSpight commented on src/components/Customer/OrdersInfoForm/OrdersInfoForm.jsx
> +  const [counselingOfficeOptions, setcounselingOfficeOptions] = useState(null);
good catch

2024-10-03 12:38 UTC, paulstonebraker approved these changes

2024-10-03 12:38 UTC, pambecker approved these changes

2024-10-03 14:25 UTC, merged