B 21428 add market code to shipments int
transcom/mymove pull request #13818
Opened 2024-10-02 12:43 UTC by cameroncaci

## [B-21428](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A1015231)

### Summary

Preps downstreams by adding an optional market code attribute to mto shipment model and table

2024-10-02 13:16 UTC, traskowskycaci reviewed
Any swagger updates we need to make for this?

2024-10-02 13:22 UTC, danieljordan-caci requested changes

2024-10-02 13:22 UTC, danieljordan-caci commented on migrations/app/schema/20241001193619_market-code-enum.up.sql
> +COMMENT ON COLUMN "mto_shipments"."market_code" IS 'Market code indicator for the shipment. i for international and d for destination.';
To keep up with how we've been doing previous migrations, could you remove the quotes from this comment line?
```
COMMENT ON COLUMN mto_shipments.market_code IS
```

2024-10-02 18:30 UTC, begrohmann approved these changes

2024-10-03 12:45 UTC, cameroncaci commented on migrations/app/schema/20241001193619_market-code-enum.up.sql
> +COMMENT ON COLUMN "mto_shipments"."market_code" IS 'Market code indicator for the shipment. i for international and d for destination.';
Resolved via https://github.com/transcom/mymove/pull/13818/commits/4455101e5a99f77b20d99f0c95aa69fa10f99d2d

2024-10-03 12:46 UTC, cameroncaci commented
> Any swagger updates we need to make for this?

@traskowskycaci 
I don't think it'd be good to have swagger return data that is only possible to be null - could send mixed messages to third parties. I'd wager that'd be better for the BLI which will enhance the Prime API

2024-10-03 13:19 UTC, traskowskycaci approved these changes
Looks good! Failing server tests are just flaky

2024-10-04 16:15 UTC, danieljordan-caci requested changes

2024-10-04 16:15 UTC, danieljordan-caci commented on migrations/app/schema/20241001193619_market-code-enum.up.sql
> +ALTER TABLE mto_shipments ADD COLUMN market_code market_code_enum;
`ADD COLUMN IF NOT EXISTS` here plz

2024-10-07 14:47 UTC, danieljordan-caci approved these changes
vv happy thank u

![Screenshot 2024-10-07 at 9 46 51 AM](https://github.com/user-attachments/assets/c8424eef-6702-4442-a0b1-ebbd55506f31)

2024-10-08 14:00 UTC, merged