B 21213 int
transcom/mymove pull request #13825
Opened 2024-10-02 18:38 UTC by CoryKleinjanCACI

## [Agility ticket](tbd)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-10-07 12:52 UTC, antgmann commented
<img width="226" alt="image" src="https://github.com/user-attachments/assets/877b50f5-8e04-4b0d-a788-4c11754a6614">

Should we remove the option to filter by "Waiting on Customer" if that status will no longer appear in this table?

2024-10-07 15:26 UTC, MInthavongsay requested changes
Looks good except for Anthony's comments about removing the waiting on customer status from the drop down. I think that should be removed per ticket description.

2024-10-08 15:25 UTC, CoryKleinjanCACI commented on playwright/tests/office/servicescounseling/servicesCounselingQueueFilters.spec.js
> -      await page.locator('th[data-testid="locator"] > div > input').blur();
Whoops. I thought I had removed that.

2024-10-08 18:53 UTC, antgmann approved these changes

2024-10-09 15:57 UTC, ajlusk approved these changes
Looks good! The only status displayed in the closeout queue is needs closeout including for moves that contain other shipments that aren't yet at that stage.

<img width="136" alt="Screenshot 2024-10-09 at 11 39 55 AM" src="https://github.com/user-attachments/assets/1a4fa191-7d69-4fcc-98cb-24e23d5a4276">

This also displays correctly when viewing as an HQ user.

2024-10-09 15:57 UTC, ajlusk commented on pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
> +				}
Clever way of approaching this. Took me a minute to understand what this was doing. Seems like something that could benefit from a comment and/or backlog number.

2024-10-09 16:41 UTC, merged