Int b 20975 too submits mto and receives incorrect validation
transcom/mymove pull request #13845
Opened 2024-10-06 23:51 UTC by samaysofo

## [Agility ticket](tbd)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-10-07 17:22 UTC, brianmanley-caci commented
One of the integration test is failing, but I'm not sure if it is related to your changes.

2024-10-07 17:36 UTC, samaysofo commented
> One of the integration test is failing, but I'm not sure if it is related to your changes.
I took a look but doesn't look like its related to the changes i made but i could be wrong, @danieljordan-caci  @r-mettler do you by chance know if this is one of those flaky failed tests?

2024-10-07 17:38 UTC, danieljordan-caci commented
> > One of the integration test is failing, but I'm not sure if it is related to your changes.
> > I took a look but doesn't look like its related to the changes i made but i could be wrong, @danieljordan-caci  @r-mettler do you by chance know if this is one of those flaky failed tests?

It is a flaky test so you can disregard

2024-10-07 19:47 UTC, brianmanley-caci approved these changes

2024-10-08 18:33 UTC, samaysofo commented
@danieljordan-caci / @r-mettler may you please take a look at this when you get the chance? thanks

2024-10-08 18:49 UTC, danieljordan-caci commented
> @danieljordan-caci / @r-mettler may you please take a look at this when you get the chance? thanks

Looking now

2024-10-08 18:56 UTC, ryan-mchugh approved these changes

2024-10-08 19:02 UTC, danieljordan-caci requested changes
So... I am seeing the `Task order created successfully` message, but when creating the customer I am being redirected. I know WHY this is (see [this PR](https://github.com/transcom/mymove/pull/13797)) and we likely need to allow the SC access to that add orders route when coming from the create customer process. Similar to how we allow the SC to access the add orders route when coming from the `Create New Move` button.

Task order flash message
![Screenshot 2024-10-08 at 1 55 22 PM](https://github.com/user-attachments/assets/ed560d49-63bc-4f4d-975d-37deb3188c67)

https://github.com/user-attachments/assets/c58621d8-ad0c-43c4-bd15-aa70c8409978

2024-10-08 19:17 UTC, samaysofo commented
> So... I am seeing the `Task order created successfully` message, but when creating the customer I am being redirected. I know WHY this is (see [this PR](https://github.com/transcom/mymove/pull/13797)) and we likely need to allow the SC access to that add orders route when coming from the create customer process. Similar to how we allow the SC to access the add orders route when coming from the `Create New Move` button.
> 
> Task order flash message ![Screenshot 2024-10-08 at 1 55 22 PM](https://private-user-images.githubusercontent.com/136510600/374689894-ed560d49-63bc-4f4d-975d-37deb3188c67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MTQ4NDUsIm5iZiI6MTcyODQxNDU0NSwicGF0aCI6Ii8xMzY1MTA2MDAvMzc0Njg5ODk0LWVkNTYwZDQ5LTYzYmMtNGY0ZC05NzVkLTM3ZGViMzE4OGM2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQxOTA5MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZTFiYWU2ODlhNTdjZDZkYzlmMzljNmI1MDRlYmUxMTUzMGI1N2NhMDVjODhlNDY3OTJkZTdjZDVhOTIwNTAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5U1Dx1zVriyZZEU2fH1o3WUPjQDHkBwU3lP8Ey_l5E4)
> 
>  Screen.Recording.2024-10-08.at.2.00.12.PM.mov

2024-10-08 19:22 UTC, samaysofo commented
> So... I am seeing the `Task order created successfully` message, but when creating the customer I am being redirected. I know WHY this is (see [this PR](https://github.com/transcom/mymove/pull/13797)) and we likely need to allow the SC access to that add orders route when coming from the create customer process. Similar to how we allow the SC to access the add orders route when coming from the `Create New Move` button.
> 
> Task order flash message ![Screenshot 2024-10-08 at 1 55 22 PM](https://private-user-images.githubusercontent.com/136510600/374689894-ed560d49-63bc-4f4d-975d-37deb3188c67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MTUzMzgsIm5iZiI6MTcyODQxNTAzOCwicGF0aCI6Ii8xMzY1MTA2MDAvMzc0Njg5ODk0LWVkNTYwZDQ5LTYzYmMtNGY0ZC05NzVkLTM3ZGViMzE4OGM2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQxOTE3MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NWVjZDA4YTE3OWI1NTMwYmUxM2FjZWMzYTRkNTM5NjRlM2FkOWZkZjAxZjQyMjE4Mzg3ZjEwZjk5MjFjYTEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TEkBlVnoFgUS1rxL0dTiXjGIAjB4zf3anx2ScQCscLA)
> 
>  Screen.Recording.2024-10-08.at.2.00.12.PM.mov

Ok, will take a look at it . it works fine when yes is clicked for "Okta Account" radio button. So i'm assuming that's a different call when "no" is clicked?

2024-10-08 19:24 UTC, danieljordan-caci commented
> > So... I am seeing the `Task order created successfully` message, but when creating the customer I am being redirected. I know WHY this is (see [this PR](https://github.com/transcom/mymove/pull/13797)) and we likely need to allow the SC access to that add orders route when coming from the create customer process. Similar to how we allow the SC to access the add orders route when coming from the `Create New Move` button.
> > Task order flash message ![Screenshot 2024-10-08 at 1 55 22 PM](https://private-user-images.githubusercontent.com/136510600/374689894-ed560d49-63bc-4f4d-975d-37deb3188c67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MTUzMzgsIm5iZiI6MTcyODQxNTAzOCwicGF0aCI6Ii8xMzY1MTA2MDAvMzc0Njg5ODk0LWVkNTYwZDQ5LTYzYmMtNGY0ZC05NzVkLTM3ZGViMzE4OGM2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQxOTE3MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NWVjZDA4YTE3OWI1NTMwYmUxM2FjZWMzYTRkNTM5NjRlM2FkOWZkZjAxZjQyMjE4Mzg3ZjEwZjk5MjFjYTEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TEkBlVnoFgUS1rxL0dTiXjGIAjB4zf3anx2ScQCscLA)
> > Screen.Recording.2024-10-08.at.2.00.12.PM.mov
> 
> Ok, will take a look at it . it works fine when yes is clicked for "Okta Account" radio button. So i'm assuming that's a different call when "no" is clicked?

It is not a different API call. Shouldn't matter anyway per the code:
```
    return createCustomerWithOktaOption({ body })
      .then((res) => {
        const customerId = Object.keys(res.createdCustomer)[0];
        setFlashMessage('CUSTOMER_CREATE_SUCCESS', 'success', `Customer created successfully.`);
        navigate(
          generatePath(servicesCounselingRoutes.BASE_CUSTOMERS_ORDERS_ADD_PATH, {
            customerId,
          }),
          { state: { isSafetyMoveSelected: isSafetyMove } },
        );
      })
      .catch((e) => {
        let errorMessage;
        if (e.status === 409) errorMessage = 'This EMPLID is already in use';
        else errorMessage = getResponseError(e?.response, 'failed to create service member due to server error');
        setServerError(errorMessage);
      });
```

2024-10-08 19:55 UTC, samaysofo commented
> > > So... I am seeing the `Task order created successfully` message, but when creating the customer I am being redirected. I know WHY this is (see [this PR](https://github.com/transcom/mymove/pull/13797)) and we likely need to allow the SC access to that add orders route when coming from the create customer process. Similar to how we allow the SC to access the add orders route when coming from the `Create New Move` button.
> > > Task order flash message ![Screenshot 2024-10-08 at 1 55 22 PM](https://private-user-images.githubusercontent.com/136510600/374689894-ed560d49-63bc-4f4d-975d-37deb3188c67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MTUzMzgsIm5iZiI6MTcyODQxNTAzOCwicGF0aCI6Ii8xMzY1MTA2MDAvMzc0Njg5ODk0LWVkNTYwZDQ5LTYzYmMtNGY0ZC05NzVkLTM3ZGViMzE4OGM2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQxOTE3MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NWVjZDA4YTE3OWI1NTMwYmUxM2FjZWMzYTRkNTM5NjRlM2FkOWZkZjAxZjQyMjE4Mzg3ZjEwZjk5MjFjYTEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TEkBlVnoFgUS1rxL0dTiXjGIAjB4zf3anx2ScQCscLA)
> > > Screen.Recording.2024-10-08.at.2.00.12.PM.mov
> > 
> > 
> > Ok, will take a look at it . it works fine when yes is clicked for "Okta Account" radio button. So i'm assuming that's a different call when "no" is clicked?
> 
> It is not a different API call. Shouldn't matter anyway per the code:
> 
> ```
>     return createCustomerWithOktaOption({ body })
>       .then((res) => {
>         const customerId = Object.keys(res.createdCustomer)[0];
>         setFlashMessage('CUSTOMER_CREATE_SUCCESS', 'success', `Customer created successfully.`);
>         navigate(
>           generatePath(servicesCounselingRoutes.BASE_CUSTOMERS_ORDERS_ADD_PATH, {
>             customerId,
>           }),
>           { state: { isSafetyMoveSelected: isSafetyMove } },
>         );
>       })
>       .catch((e) => {
>         let errorMessage;
>         if (e.status === 409) errorMessage = 'This EMPLID is already in use';
>         else errorMessage = getResponseError(e?.response, 'failed to create service member due to server error');
>         setServerError(errorMessage);
>       });
> ```

ok, so out of curiosity. I had to double check both the main/int branch and the main branch works fine but the int branch does the redirecting. 

https://github.com/user-attachments/assets/e3bcb8a3-f607-42ca-a2f0-dcc7ee1b32bf

https://github.com/user-attachments/assets/f33366cd-3451-4e41-b411-7165d78d2dde

2024-10-08 19:57 UTC, danieljordan-caci commented
> > > > So... I am seeing the `Task order created successfully` message, but when creating the customer I am being redirected. I know WHY this is (see [this PR](https://github.com/transcom/mymove/pull/13797)) and we likely need to allow the SC access to that add orders route when coming from the create customer process. Similar to how we allow the SC to access the add orders route when coming from the `Create New Move` button.
> > > > Task order flash message ![Screenshot 2024-10-08 at 1 55 22 PM](https://private-user-images.githubusercontent.com/136510600/374689894-ed560d49-63bc-4f4d-975d-37deb3188c67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MTUzMzgsIm5iZiI6MTcyODQxNTAzOCwicGF0aCI6Ii8xMzY1MTA2MDAvMzc0Njg5ODk0LWVkNTYwZDQ5LTYzYmMtNGY0ZC05NzVkLTM3ZGViMzE4OGM2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQxOTE3MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NWVjZDA4YTE3OWI1NTMwYmUxM2FjZWMzYTRkNTM5NjRlM2FkOWZkZjAxZjQyMjE4Mzg3ZjEwZjk5MjFjYTEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TEkBlVnoFgUS1rxL0dTiXjGIAjB4zf3anx2ScQCscLA)
> > > > Screen.Recording.2024-10-08.at.2.00.12.PM.mov
> > > 
> > > 
> > > Ok, will take a look at it . it works fine when yes is clicked for "Okta Account" radio button. So i'm assuming that's a different call when "no" is clicked?
> > 
> > 
> > It is not a different API call. Shouldn't matter anyway per the code:
> > ```
> >     return createCustomerWithOktaOption({ body })
> >       .then((res) => {
> >         const customerId = Object.keys(res.createdCustomer)[0];
> >         setFlashMessage('CUSTOMER_CREATE_SUCCESS', 'success', `Customer created successfully.`);
> >         navigate(
> >           generatePath(servicesCounselingRoutes.BASE_CUSTOMERS_ORDERS_ADD_PATH, {
> >             customerId,
> >           }),
> >           { state: { isSafetyMoveSelected: isSafetyMove } },
> >         );
> >       })
> >       .catch((e) => {
> >         let errorMessage;
> >         if (e.status === 409) errorMessage = 'This EMPLID is already in use';
> >         else errorMessage = getResponseError(e?.response, 'failed to create service member due to server error');
> >         setServerError(errorMessage);
> >       });
> > ```
> 
> ok, so out of curiosity. I had to double check both the main/int branch and the main branch works fine but the int branch does the redirecting.
> 
>  create_cust001_main.mov 
>  cust_creation_int.mov

If you pull the newest `main` you'll see that it should now do what `integrationTesting` does :)

[Just merged it](https://github.com/transcom/mymove/pull/13798)

2024-10-10 14:40 UTC, samaysofo commented
> > > > > So... I am seeing the `Task order created successfully` message, but when creating the customer I am being redirected. I know WHY this is (see [this PR](https://github.com/transcom/mymove/pull/13797)) and we likely need to allow the SC access to that add orders route when coming from the create customer process. Similar to how we allow the SC to access the add orders route when coming from the `Create New Move` button.
> > > > > Task order flash message ![Screenshot 2024-10-08 at 1 55 22 PM](https://private-user-images.githubusercontent.com/136510600/374689894-ed560d49-63bc-4f4d-975d-37deb3188c67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MTUzMzgsIm5iZiI6MTcyODQxNTAzOCwicGF0aCI6Ii8xMzY1MTA2MDAvMzc0Njg5ODk0LWVkNTYwZDQ5LTYzYmMtNGY0ZC05NzVkLTM3ZGViMzE4OGM2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQxOTE3MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NWVjZDA4YTE3OWI1NTMwYmUxM2FjZWMzYTRkNTM5NjRlM2FkOWZkZjAxZjQyMjE4Mzg3ZjEwZjk5MjFjYTEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TEkBlVnoFgUS1rxL0dTiXjGIAjB4zf3anx2ScQCscLA)
> > > > > Screen.Recording.2024-10-08.at.2.00.12.PM.mov
> > > > 
> > > > 
> > > > Ok, will take a look at it . it works fine when yes is clicked for "Okta Account" radio button. So i'm assuming that's a different call when "no" is clicked?
> > > 
> > > 
> > > It is not a different API call. Shouldn't matter anyway per the code:
> > > ```
> > >     return createCustomerWithOktaOption({ body })
> > >       .then((res) => {
> > >         const customerId = Object.keys(res.createdCustomer)[0];
> > >         setFlashMessage('CUSTOMER_CREATE_SUCCESS', 'success', `Customer created successfully.`);
> > >         navigate(
> > >           generatePath(servicesCounselingRoutes.BASE_CUSTOMERS_ORDERS_ADD_PATH, {
> > >             customerId,
> > >           }),
> > >           { state: { isSafetyMoveSelected: isSafetyMove } },
> > >         );
> > >       })
> > >       .catch((e) => {
> > >         let errorMessage;
> > >         if (e.status === 409) errorMessage = 'This EMPLID is already in use';
> > >         else errorMessage = getResponseError(e?.response, 'failed to create service member due to server error');
> > >         setServerError(errorMessage);
> > >       });
> > > ```
> > 
> > 
> > ok, so out of curiosity. I had to double check both the main/int branch and the main branch works fine but the int branch does the redirecting.
> > create_cust001_main.mov
> > cust_creation_int.mov
> 
> If you pull the newest `main` you'll see that it should now do what `integrationTesting` does :)
> 
> [Just merged it](https://github.com/transcom/mymove/pull/13798)

The pr has been updated with the fix. 

https://github.com/user-attachments/assets/425f70d3-d6ea-4e1e-971b-bb0bedfc6083

2024-10-10 14:51 UTC, msaki-caci commented
@samaysofo I think something may have went wrong with your latest push. I am showing 236 files changed right now. Is that right?

![image](https://github.com/user-attachments/assets/5a7011c1-2fa6-49a4-8fe6-c8395c7c166f)

2024-10-10 14:53 UTC, danieljordan-caci commented
> @samaysofo I think something may have went wrong with your latest push. I am showing 236 files changed right now. Is that right?
> 
> ![image](https://private-user-images.githubusercontent.com/180579307/375430038-5a7011c1-2fa6-49a4-8fe6-c8395c7c166f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NzIyNTEsIm5iZiI6MTcyODU3MTk1MSwicGF0aCI6Ii8xODA1NzkzMDcvMzc1NDMwMDM4LTVhNzAxMWMxLTJmYTYtNDlhNC04ZmU2LWM4Mzk1YzdjMTY2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQxNDUyMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNzY4YjkyNjNiZTI0Y2UxOTNiYjEyNWU0MzU3YTg5MjdiMThlZWEzYzU0MWM4YzNiMWE4MTg5YWU0ODRhNzUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.R9QsWOKL8isMppr6SHGwKk26er_cKSPKbetr0D9JZn8)

Needed to merge in the latest `integrationTesting` - we were seeing the Go upgrade file changes, which were not in this branch. Should be fixed now - just updated the branch.

2024-10-10 15:00 UTC, samaysofo commented
> @samaysofo I think something may have went wrong with your latest push. I am showing 236 files changed right now. Is that right?
> 
> ![image](https://private-user-images.githubusercontent.com/180579307/375430038-5a7011c1-2fa6-49a4-8fe6-c8395c7c166f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NzI1OTQsIm5iZiI6MTcyODU3MjI5NCwicGF0aCI6Ii8xODA1NzkzMDcvMzc1NDMwMDM4LTVhNzAxMWMxLTJmYTYtNDlhNC04ZmU2LWM4Mzk1YzdjMTY2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQxNDU4MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNGViMzBiNjMzMjYwZDk2M2Y5MmRmMzgxNmUwZTI5YmIzOGU2NDQ3MWI2ZWVjZGNlZTc2ODUxMzEzOWFiODdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.hNiKyECbWKUZxQ9mzWO3pxNWJzuODF9xUO30aMBCvSw)

i probably need to update my branch with the latest integration branch.

2024-10-10 15:03 UTC, msaki-caci commented
> > @samaysofo I think something may have went wrong with your latest push. I am showing 236 files changed right now. Is that right?
> > ![image](https://private-user-images.githubusercontent.com/180579307/375430038-5a7011c1-2fa6-49a4-8fe6-c8395c7c166f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NzI1OTQsIm5iZiI6MTcyODU3MjI5NCwicGF0aCI6Ii8xODA1NzkzMDcvMzc1NDMwMDM4LTVhNzAxMWMxLTJmYTYtNDlhNC04ZmU2LWM4Mzk1YzdjMTY2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQxNDU4MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNGViMzBiNjMzMjYwZDk2M2Y5MmRmMzgxNmUwZTI5YmIzOGU2NDQ3MWI2ZWVjZGNlZTc2ODUxMzEzOWFiODdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.hNiKyECbWKUZxQ9mzWO3pxNWJzuODF9xUO30aMBCvSw)
> 
> i probably need to update my branch with the latest integration branch.

Yeah its all good now 👍

2024-10-10 17:36 UTC, msaki-caci commented
LGTM but you have a failure in one of the circleci tests

2024-10-10 18:22 UTC, samaysofo commented
> LGTM but you have a failure in one of the circleci tests
I still see some changes in the pr that don't belong here in pkg/services/mocks/ which seems to be what's failing. Let me update my branch with INT again, not sure why they are still there after the update.

2024-10-10 18:31 UTC, danieljordan-caci commented
> > LGTM but you have a failure in one of the circleci tests
> > I still see some changes in the pr that don't belong here in pkg/services/mocks/ which seems to be what's failing. Let me update my branch with INT again, not sure why they are still there after the update.

On your branch run `make mocks_generate` and push the changes

2024-10-10 18:53 UTC, samaysofo commented
> > > LGTM but you have a failure in one of the circleci tests
> > > I still see some changes in the pr that don't belong here in pkg/services/mocks/ which seems to be what's failing. Let me update my branch with INT again, not sure why they are still there after the update.
> 
> On your branch run `make mocks_generate` and push the changes

@danieljordan-caci @msaki-caci its cleanup up now, thanks.

2024-10-10 19:03 UTC, msaki-caci approved these changes

2024-10-10 19:58 UTC, danieljordan-caci commented on src/pages/Office/CustomerOnboarding/CreateCustomerForm.jsx
>            generatePath(servicesCounselingRoutes.BASE_CUSTOMERS_ORDERS_ADD_PATH, {
Can you add/update a test to reflect these changes? Thanks.

2024-10-11 12:57 UTC, samaysofo commented on src/pages/Office/CustomerOnboarding/CreateCustomerForm.jsx
>            generatePath(servicesCounselingRoutes.BASE_CUSTOMERS_ORDERS_ADD_PATH, {
test updated.

2024-10-11 16:13 UTC, danieljordan-caci approved these changes
Most excellent!

2024-10-11 16:53 UTC, samaysofo commented
> Most excellent!

@danieljordan-caci i see some server test failing which seems to have nothing to do with my changes after i updated my branch again with INT before i merge, do you think i'm still good to merge?

2024-10-11 16:58 UTC, merged