B-21427: Update Addresses is_oconus column
transcom/mymove pull request #13849
Opened 2024-10-07 16:06 UTC by TevinAdams

## [Agility ticket](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-21427)

## Summary
This sql script updates the is_oconus values of addresses records

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Run the migrations
2. Verify that the record in the addresses table have a true or false value for is_oconus
3. If country is US or United States then is_oconus should be false. Anything else it should be true

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-10-07 16:08 UTC, danieljordan-caci approved these changes

2024-10-07 16:08 UTC, danieljordan-caci commented on migrations/app/schema/20241004203140_update_addresses_is_oconus.up.sql
> +                        WHEN country IN ('US', 'United States') THEN false
Also need `USA`

2024-10-07 16:18 UTC, traskowskycaci requested changes
Since we are treating Alaska and Hawaii as OCONUS, we also need to set is_oconus to true for the state values of AK or HI in addition to just checking the country

2024-10-07 16:31 UTC, danieljordan-caci requested changes
whoops picked the wrong one

2024-10-07 17:36 UTC, traskowskycaci commented on migrations/app/schema/20241004203140_update_addresses_is_oconus.up.sql
> +    UPDATE addresses
@danieljordan-caci is also going to be dropping the address.county column with the upstream to this work, so this check will need to be reworked to account for his changes

2024-10-08 12:54 UTC, begrohmann commented on migrations/app/schema/20241004203140_update_addresses_is_oconus.up.sql
> +                        WHEN country IN ('US', 'United States') THEN false
AK and HI are US but they are OCONUS.

2024-10-08 16:31 UTC, pambecker commented on migrations/app/schema/20241004203140_update_addresses_is_oconus.up.sql
> +                        WHEN country IN ('US', 'United States') THEN false
my story will add is_oconus true for the AK and HI addresses I'm adding.
https://github.com/transcom/mymove/pull/13852

2024-10-08 16:35 UTC, traskowskycaci commented on migrations/app/schema/20241004203140_update_addresses_is_oconus.up.sql
> +                        WHEN country IN ('US', 'United States') THEN false
Thanks for the link Pam! I think we should still be explicit and have a check for the states of AK and HI here, if any test values happen to exist in the various environments that are not on your list, then this would update them

2024-10-08 21:05 UTC, TevinAdams commented on migrations/app/schema/20241004203140_update_addresses_is_oconus.up.sql
> +                        WHEN country IN ('US', 'United States') THEN false
Addressed this by checking state for AK and HI

2024-10-08 21:05 UTC, TevinAdams commented on migrations/app/schema/20241004203140_update_addresses_is_oconus.up.sql
> +    UPDATE addresses
Adjusted to source the country value in the new table

2024-10-08 21:07 UTC, begrohmann approved these changes

2024-10-08 21:21 UTC, danieljordan-caci commented
conflicts

2024-10-08 22:10 UTC, traskowskycaci commented on migrations/app/schema/20241004203140_update_addresses_is_oconus.up.sql
> +                        WHEN (Select country from re_countries where id = country_id ) IN ('US', 'United States', 'USA') AND state NOT IN ('AK', 'HI') THEN false
Now that re_countries is used, we should just have to check for 'US' rather than all three values of 'US', 'United States', 'USA'

2024-10-08 22:11 UTC, traskowskycaci commented on migrations/app/schema/20241004203140_update_addresses_is_oconus.up.sql
> +                        WHEN (Select country from re_countries where id = country_id ) IN ('US', 'United States', 'USA') AND state NOT IN ('AK', 'HI') THEN false
Probably doesn't hurt anything to leave it in there but isn't 100% - leaving that up to you on whether to change or not

2024-10-09 13:44 UTC, danieljordan-caci requested changes

2024-10-09 13:44 UTC, danieljordan-caci commented on pkg/services/address/address_creator.go
> +		if country.Country != "US" && country.Country != "United States" && country.Country != "USA" && transformedAddress.State != "AK" && transformedAddress.State != "HI" {
You don't need anything other than `US` here

2024-10-09 13:46 UTC, TevinAdams commented on migrations/app/schema/20241004203140_update_addresses_is_oconus.up.sql
> +                        WHEN (Select country from re_countries where id = country_id ) IN ('US', 'United States', 'USA') AND state NOT IN ('AK', 'HI') THEN false
It doesnt hurt to leave it for now.

2024-10-09 13:48 UTC, danieljordan-caci commented on migrations/app/schema/20241004203140_update_addresses_is_oconus.up.sql
> +                        WHEN (Select country from re_countries where id = country_id ) IN ('US', 'United States', 'USA') AND state NOT IN ('AK', 'HI') THEN false
Data minimization - 21073 just handled this and there is no case where there will be any other value other than `US`.

2024-10-09 13:56 UTC, traskowskycaci commented on migrations/app/schema/20241004203140_update_addresses_is_oconus.up.sql
> +                        WHEN (Select country from re_countries where id = country_id ) = 'US' THEN false
Still need to check for HI and AK here

2024-10-09 13:56 UTC, traskowskycaci commented on pkg/services/address/address_creator.go
> +		if country.Country != "US" {
Still need to check for HI and AK here

2024-10-09 14:08 UTC, danieljordan-caci requested changes
You also need to handle the use case where an address is being created through a service item creation.

See `pkg/services/mto_service_item/mto_service_item_creator.go:599` - it does not use the expected `addressCreator` function, but instead `CreateOne`.

Also let's ensure we are covering down on when an address is also being updated, not just created to handle the `isConus` value.

2024-10-09 14:10 UTC, danieljordan-caci reviewed
Also ensure you add/update a test to reflect the changes you're making.

2024-10-09 16:19 UTC, danieljordan-caci submitted a review, later dismissed

2024-10-09 16:19 UTC, danieljordan-caci commented on pkg/services/address/address_creator.go
> +		if country.Country != "US" && transformedAddress.State != "AK" && transformedAddress.State != "HI" {
Shouldn't these be `||` operands instead of `&&`? This would only return true if all of these conditions were met.

2024-10-09 16:20 UTC, danieljordan-caci commented on pkg/services/address/address_creator.go
> +		if country.Country != "US" && transformedAddress.State != "AK" && transformedAddress.State != "HI" {
You'd need something like:
```
if country.Country != "US" && transformedAddress.State != "AK" || country.Country != "US" && transformedAddress.State != "HI" 
```

2024-10-14 15:51 UTC, danieljordan-caci commented on pkg/services/address/address_updater.go
> +	mergedAddress.IsOconus = &isOconus
Can you add a test for this in `address_updater_test.go`?

2024-10-14 15:52 UTC, danieljordan-caci commented on pkg/testdatagen/make_address.go
> +		IsOconus: models.BoolPointer(false),
Can you remove this white space?

2024-10-14 15:53 UTC, traskowskycaci requested changes
Running through customer flow with Alaska FF on - looks like current and backup addresses didn't get the is_oconus flag set to the right value for AK 
<img width="1049" alt="image" src="https://github.com/user-attachments/assets/ba3903d3-3946-4eff-b27f-f4a244bcf4d7">

2024-10-14 16:09 UTC, TevinAdams commented on pkg/testdatagen/make_address.go
> +		IsOconus: models.BoolPointer(false),
Not sure why that's there but its removed.

2024-10-14 16:09 UTC, TevinAdams commented on pkg/services/address/address_updater.go
> +	mergedAddress.IsOconus = &isOconus
Test added

2024-10-14 16:10 UTC, TevinAdams commented
> Running through customer flow with Alaska FF on - looks like current and backup addresses didn't get the is_oconus flag set to the right value for AK <img alt="image" width="1049" src="https://private-user-images.githubusercontent.com/147537467/376313714-ba3903d3-3946-4eff-b27f-f4a244bcf4d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MjE4MDAsIm5iZiI6MTcyODkyMTUwMCwicGF0aCI6Ii8xNDc1Mzc0NjcvMzc2MzEzNzE0LWJhMzkwM2QzLTM5NDYtNGVmZi1iMjdmLWY0YTI0NGJjZjRkNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQxNTU4MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzZmNGViMGNiMTBkMGYzNWZiMTA5NTU4NmZkMTMzYjQzOWExZTE1YTg4OWIxMWQ5Y2YyNGVmMGZiNmY0MjY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jMF_ByRPsrz3elF-sK1hDJZUQ3ECCYuA3Xeen-F4LPk">

Looking into this now

2024-10-14 16:12 UTC, TevinAdams commented
> > Running through customer flow with Alaska FF on - looks like current and backup addresses didn't get the is_oconus flag set to the right value for AK <img alt="image" width="1049" src="https://private-user-images.githubusercontent.com/147537467/376313714-ba3903d3-3946-4eff-b27f-f4a244bcf4d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MjE4MDAsIm5iZiI6MTcyODkyMTUwMCwicGF0aCI6Ii8xNDc1Mzc0NjcvMzc2MzEzNzE0LWJhMzkwM2QzLTM5NDYtNGVmZi1iMjdmLWY0YTI0NGJjZjRkNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQxNTU4MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzZmNGViMGNiMTBkMGYzNWZiMTA5NTU4NmZkMTMzYjQzOWExZTE1YTg4OWIxMWQ5Y2YyNGVmMGZiNmY0MjY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jMF_ByRPsrz3elF-sK1hDJZUQ3ECCYuA3Xeen-F4LPk">
> 
> Looking into this now

Hey in your test case is the country_id populated? If so what is the country.country value on it?

2024-10-14 16:21 UTC, traskowskycaci commented
> Hey in your test case is the country_id populated? If so what is the country.country value on it?

Discussing via slack with Tevin

2024-10-14 17:32 UTC, traskowskycaci commented on pkg/models/address.go
> +	} else {
I think you could simplify this logic and remove this else condition, and instead just have the cases in your EvaluateIsOconus function be `address.Country.Country != "US" || address.State == "AK" || address.State == "HI"` instead of the current `address.Country.Country != "US" || address.Country.Country == "US" && address.State == "AK" || address.Country.Country == "US" && address.State == "HI"` check

2024-10-14 17:33 UTC, traskowskycaci commented on pkg/models/address.go
> +	} else {
Up to you. With @danieljordan-caci's 21073 work, the country _should_ never be null

2024-10-14 17:34 UTC, traskowskycaci commented on pkg/models/address.go
> +	} else {
I do think address.Country.Country != "US" || address.State == "AK" || address.State == "HI" is cleaner

2024-10-14 17:36 UTC, danieljordan-caci commented on pkg/models/address.go
> +	} else {
One risk with that is when we do start allowing customer/office user input for country, we don't want to assume that the country is always `US`

I'm on the side of leaving it as is to handle that use case

2024-10-14 17:38 UTC, traskowskycaci commented on pkg/models/address.go
> +	} else {
If the check was simplified to address.Country.Country != "US" || address.State == "AK" || address.State == "HI" that would still handle the case of a country not being US  - is that what you mean?

2024-10-14 17:40 UTC, danieljordan-caci commented on pkg/models/address.go
> +	} else {
You're technically correct, yes. It should still cover it - not a hill I wanna die on though. Just prefer being explicit.

2024-10-14 17:41 UTC, traskowskycaci commented on pkg/models/address.go
> +	} else {
Up to you @TevinAdams, re-request a review when you're ready for another look!

2024-10-14 19:06 UTC, TevinAdams commented on pkg/models/address.go
> +	} else {
@traskowskycaci This is now ready for review

2024-10-14 19:54 UTC, traskowskycaci requested changes
Would you be able to add the is_oconus value to the various payload to model files to return that value along with the other values in the address object? Similar to how it was done for the market_code

2024-10-14 20:08 UTC, TevinAdams commented
> Would you be able to add the is_oconus value to the various payload to model files to return that value along with the other values in the address object? Similar to how it was done for the market_code

I intentionally did not add it in any payload because I wasn't aware of any work or requirements that needed it and didn't want to return more data than what's needed. There was a story or the market_code to be returned because current work needed it. There isn't a story to return the is_oconus value on addresses. In my opinion if that is not needed at this time it would be best to create a story to do that so i can move on to getting the marketCode displayed on the cards.

2024-10-14 20:18 UTC, traskowskycaci commented
> > Would you be able to add the is_oconus value to the various payload to model files to return that value along with the other values in the address object? Similar to how it was done for the market_code
> 
> I intentionally did not add it in any payload because I wasn't aware of any work or requirements that needed it and didn't want to return more data than what's needed. There was a story or the market_code to be returned because current work needed it. There isn't a story to return the is_oconus value on addresses. In my opinion if that is not needed at this time it would be best to create a story to do that so i can move on to getting the marketCode displayed on the cards.

Ok. I'll need it for my BL for the internal API and we would probably need it for the office API as there is office user UB work upcoming

2024-10-14 20:55 UTC, TevinAdams commented
> > > Would you be able to add the is_oconus value to the various payload to model files to return that value along with the other values in the address object? Similar to how it was done for the market_code
> > 
> > 
> > I intentionally did not add it in any payload because I wasn't aware of any work or requirements that needed it and didn't want to return more data than what's needed. There was a story or the market_code to be returned because current work needed it. There isn't a story to return the is_oconus value on addresses. In my opinion if that is not needed at this time it would be best to create a story to do that so i can move on to getting the marketCode displayed on the cards.
> 
> Ok. I'll need it for my BL for the internal API and we would probably need it for the office API as there is office user UB work upcoming

Just pushed up a change returning Is_Oconus value where requested.

2024-10-15 13:36 UTC, traskowskycaci commented on migrations/app/schema/20241004203140_update_addresses_is_oconus.up.sql
> +-- Update is_oconus value on the addresses table based on the addresses country
Can you update the comment here to include "based on the addresses country and the state"

2024-10-15 13:40 UTC, begrohmann commented on pkg/models/address.go
> +		if address.State == "HI" || address.State == "AK" {
There is a is_oconus column in re_states that can be checked here instead of hard coding HI and AK. Or can be done in a later BL if this is going before 21442?

2024-10-15 13:59 UTC, TevinAdams commented on pkg/models/address.go
> +		if address.State == "HI" || address.State == "AK" {
Looks like this work is being done simultaneously. I will bring it up with the team at stand up. But we can either wait for scrummy bears to get that in and adjust off that or we can change it later. I will comment back here after discussing with the team on what they want to do.

2024-10-15 14:37 UTC, TevinAdams commented on migrations/app/schema/20241004203140_update_addresses_is_oconus.up.sql
> +-- Update is_oconus value on the addresses table based on the addresses country
Comment updated.

2024-10-15 14:38 UTC, TevinAdams commented on pkg/models/address.go
> +		if address.State == "HI" || address.State == "AK" {
@begrohmann After discussing with the team. We are going to push this work through. There is a story down the line that we do some re_states work and will update the hard coded states with that work.

2024-10-15 14:40 UTC, traskowskycaci commented on pkg/models/address.go
> +		if address.State == "HI" || address.State == "AK" {
That work Tevin referenced is [B-21530](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-21530) with the AC of:

Given we store the state values in the re_states table
When we populate/update the is_oconus boolean value on the address table
Then the logic there checks the re_states value rather than hard-coded state values

2024-10-15 14:45 UTC, traskowskycaci approved these changes
Tested out and `is_oconus` values are looking good!

2024-10-15 15:22 UTC, merged