B 21435 int
transcom/mymove pull request #13841
Opened 2024-10-04 19:08 UTC by deandreJones

## [B-21435](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A1015238)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### How to test

1. run `make db_dev_fresh `or `make db_dev_migrate`
2. view db client or psql-dev to see that the following tables have been created: 
-re_states, re_us_post_region, re_oconus_rate_areas, re_intl_transit_times, 

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-10-07 13:38 UTC, danieljordan-caci requested changes
42k lines added... yeesh. Got some questions.

2024-10-07 13:38 UTC, danieljordan-caci commented on migrations/app/schema/20241002140154_addlocationObjects.up.sql
> +updated_at	timestamp	NOT NULL,
Should there be a default on these columns?
`NOT NULL DEFAULT NOW()`

2024-10-07 13:38 UTC, danieljordan-caci commented on migrations/app/schema/20241002140154_addlocationObjects.up.sql
> +updated_at	timestamp	 NULL,
Do you need this `NULL` if it can be null?

2024-10-07 13:38 UTC, danieljordan-caci commented on migrations/app/schema/20241002140154_addlocationObjects.up.sql
> +--COMMENT ON COLUMN re_oconus_rate_areas.country IS 'The associated country code.';
Do we need all of these lines that are commented out? Can they be removed?

2024-10-07 13:38 UTC, danieljordan-caci commented on migrations/app/schema/20241002140154_addlocationObjects.up.sql
> +COMMENT ON COLUMN re_intl_transit_times.ub_transit_time IS 'The UB transit time between the origin and destination rate area.';
Can you add a comment for `inactive_flag`?

2024-10-07 14:27 UTC, deandreJones commented on migrations/app/schema/20241002140154_addlocationObjects.up.sql
> +--COMMENT ON COLUMN re_oconus_rate_areas.country IS 'The associated country code.';
well, I was debating if I should pull in your country changes or add a new BL later to put that stuff back

2024-10-07 14:29 UTC, danieljordan-caci commented on migrations/app/schema/20241002140154_addlocationObjects.up.sql
> +--COMMENT ON COLUMN re_oconus_rate_areas.country IS 'The associated country code.';
Hm... Honestly I'd rather push in what we can now and add the constraints later. Especially since I have no idea when this dumb stupid idiotic blocker will be fixed for 21073.

2024-10-07 14:31 UTC, begrohmann commented on migrations/app/schema/20241002140154_addlocationObjects.up.sql
> +--COMMENT ON COLUMN re_oconus_rate_areas.country IS 'The associated country code.';
We need to add us_post_region_cities_id to this table for AK and HI with constraint to us_post_region_cities

2024-10-07 14:37 UTC, deandreJones commented on migrations/app/schema/20241002140154_addlocationObjects.up.sql
> +updated_at	timestamp	 NULL,
lol nope

2024-10-07 14:37 UTC, deandreJones commented on migrations/app/schema/20241002140154_addlocationObjects.up.sql
> +updated_at	timestamp	NOT NULL,
do we do that for other created_at columns?

2024-10-08 18:30 UTC, begrohmann commented on migrations/app/migrations_manifest.txt
> +20241002140154_addlocationObjects.up.sql
These are already in B-21442 so they can go away. B-21442 is more up to date.
20241002140154_addlocationObjects.up.sql
20241002140539_populateStates.up.sql
20241004124121_populateUsPostRegion.up.sql

2024-10-08 22:23 UTC, r-mettler commented on pkg/models/re_state.go
> +	State_Name string    `json:"state_name" db:"state_ame"`
typo `db:"state_ame"`

2024-10-09 15:16 UTC, deandreJones commented on migrations/app/migrations_manifest.txt
> +20241002140154_addlocationObjects.up.sql
@r-mettler - you have these files right? just checking before I remove them from my BL

2024-10-09 15:17 UTC, deandreJones commented on migrations/app/migrations_manifest.txt
> +20241002140154_addlocationObjects.up.sql
it would actually help if you do.. since I created them a while back- but now mine needs to go in after Daniels.. the timestamp is trying to run mine first

2024-10-09 15:20 UTC, begrohmann commented on migrations/app/migrations_manifest.txt
> +20241002140154_addlocationObjects.up.sql
Yes you can remove. We can handle in B-21442.

2024-10-09 15:49 UTC, closed without merging