INT-B-20472
transcom/mymove pull request #13879
Opened 2024-10-10 20:28 UTC by loganwc

## [Agility ticket](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A980088&RoomContext=TeamRoom%3A848240&concept=TeamRoom)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

### How to test

1. Login to milmovelocal
2. Create a new move
3. Before submitting move click the 'Cancel Move' button
4. Check database for the canceled move and it's shipments
5. Create a new move
6. Submit move to SC 
7. Cancel Move button should be gone

2024-10-10 22:20 UTC, paulstonebraker commented on src/pages/MyMove/Home/MoveHome.jsx
> +                    completedHeaderText="window.location.reloadOrders uploaded"
whats this

2024-10-14 14:37 UTC, loganwc commented on src/pages/MyMove/Home/MoveHome.jsx
> +                    completedHeaderText="window.location.reloadOrders uploaded"
I've never seen this before

2024-10-14 15:21 UTC, loganwc commented on src/pages/MyMove/Home/MoveHome.jsx
> +                    completedHeaderText="window.location.reloadOrders uploaded"
undid that change

2024-10-15 18:18 UTC, pambecker commented
'cancelled' should be spelled with 1 'l' to match the rest of the UI (canceled).
![image](https://github.com/user-attachments/assets/aef0fc0a-486b-4c73-bdf2-f5407aad6aae)

2024-10-15 18:26 UTC, pambecker commented
Maybe something to ask Terri, do we want to redirect the customer back to the landing page after cancel?  After I click yes in the modal, it just stays in the move but I have no way to tell if the move was canceled until I go back to the landing page.  Also, we will need a success message to display after the submit.

2024-10-15 21:26 UTC, loganwc commented
> Maybe something to ask Terri, do we want to redirect the customer back to the landing page after cancel? After I click yes in the modal, it just stays in the move but I have no way to tell if the move was canceled until I go back to the landing page. Also, we will need a success message to display after the submit.

There was a toast confirming that the move was canceled but it wouldn't display because I was reloading the page. I removed that and made the other changes you requested 👍

2024-10-29 16:24 UTC, paulstonebraker requested changes
Works as intended, only change requested is updating comments. I have a couple more thoughts that I will share as non blocking comments

2024-10-29 16:24 UTC, paulstonebraker commented on pkg/handlers/internalapi/office_test.go
> +		// Then: expect a 200 status code
Update comments for this section

2024-10-29 16:27 UTC, paulstonebraker commented
Two thoughts:

1. in the handler, do we want to check if the logged in user's ID is the same as the `Move.Order.ServiceMemberID` and return an error if not?
2. customer viewing a canceled move looks kinda weird
![image](https://github.com/user-attachments/assets/89a5cd4d-60af-4b11-9377-080eb5a3e7a9)

![image](https://github.com/user-attachments/assets/20e89d59-ac19-4263-aaee-3a181d039e88)

![image](https://github.com/user-attachments/assets/a22721a7-57d6-436e-896b-42ab8bd50401)

2024-10-29 16:52 UTC, JonSpight approved these changes
Other than the updated comment, pointed out by Paul. I am good too.

2024-10-29 16:53 UTC, joeydoyecaci approved these changes
No issue with cancelling other than the PPM glitch and the "d" screen issue.

2024-10-30 21:58 UTC, paulstonebraker approved these changes

2024-10-30 21:58 UTC, merged