B 21442 int
transcom/mymove pull request #13872
Opened 2024-10-10 15:48 UTC by begrohmann

[B-21442](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A1015413)

## Summary

The purpose of this BL is to add AK locations to us_post_region_cities table. In doing so, we also created several parent tables with city, state and zip data with associated ids to us_post_region_cities and addresses tables:

re_states
re_us_post_regions
re_cities

We created the following tables for OCONUS rate area associations and transit times:

re_oconus_rate_areas
re_intl_transit_times

We created a new view v_locations to query by city, state, zip, country and/or country and see all associated ids.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### How to test

### Database

Open the database.
Check that the following tables exist with data:

re_states
re_cities
re_us_post_regions
re_oconus_rate_areas
re_intl_transit_times

Check that us_post_region_cities table has the following new columns added and populated with data:

us_post_regions_id
cities_id

Check that addresses table has the us_post_region_cities_id column added. We have populated most of the associated data but there is some fallout where there is no county, the city does not match what is in re_cities or the combination of the data does not match up with us_post_region_cities. We will handle this in an upcoming BL when FK constraints are added. Data cleanup will be case by case.

Check that the v_locations view was created and you can query data.

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-10-10 16:05 UTC, danieljordan-caci requested changes
:)

2024-10-10 16:05 UTC, danieljordan-caci commented on migrations/app/schema/20241007184200_create_re_oconus_rate_areas_re_intl_transit_times.up.sql
> +inactive_flag	varchar(1)  DEFAULT 'N',
Is this only going to be `Y` or `N`? Would a boolean be better?

If you're set on `Y` and `N` values only, I'd recommend creating an enum so we can control the values that are inserted here.

2024-10-10 16:05 UTC, danieljordan-caci commented on migrations/app/schema/20241007184200_create_re_oconus_rate_areas_re_intl_transit_times.up.sql
> +	CONSTRAINT re_oconus_rate_areas_fkey02 REFERENCES us_post_region_cities (id),
Can we rename these constraints to be more descriptive?
`fkey_re_oconus_rate_areas_country_id`

`fkey_re_oconus_rate_areas_city_id`

2024-10-10 16:05 UTC, danieljordan-caci commented on migrations/app/schema/20241004150358_create_re_states_re_us_post_regions_re_cities.up.sql
> +updated_at	timestamp	NOT NULL,
Can you add a `DEFAULT NOW()` to these?

2024-10-10 16:05 UTC, danieljordan-caci commented on migrations/app/schema/20241007184200_create_re_oconus_rate_areas_re_intl_transit_times.up.sql
> +	CONSTRAINT re_intl_transit_times_fkey02 REFERENCES re_rate_areas (id),
Can you improve the naming of these foreign keys? Examples already mentioned.

2024-10-10 16:05 UTC, danieljordan-caci commented on migrations/app/schema/20241007184200_create_re_oconus_rate_areas_re_intl_transit_times.up.sql
> +inactive_flag	varchar(1),
Same question as the above table - enum vs. boolean?

2024-10-10 19:34 UTC, danieljordan-caci commented on migrations/app/schema/20241004150358_create_re_states_re_us_post_regions_re_cities.up.sql
> +is_oconus	bool,
Should this be `NOT NULL`?

2024-10-10 20:43 UTC, danieljordan-caci commented on pkg/models/re_cities.go
> +func (d ReCities) TableName() string {
Can you change this to `c ReCities`? `d` don't make no sense.

2024-10-10 20:43 UTC, danieljordan-caci commented on pkg/models/re_states.go
> +func (d ReStates) TableName() string {
Can you change this to `s ReStates`? `d` don't make no sense.

2024-10-10 20:44 UTC, danieljordan-caci commented on pkg/models/re_us_post_regions.go
> +func (d ReUsPostRegions) TableName() string {
Can you change this to `r ReStates`? `d` don't make no sense.

2024-10-10 20:44 UTC, danieljordan-caci commented on pkg/models/us_post_region.go
> +func (d UsPostRegion) TableName() string {
Can you change this to `r UsPostRegion ` ? `d` don't make no sense.

2024-10-10 22:10 UTC, r-mettler commented on pkg/models/us_post_region.go
> +func (d UsPostRegion) TableName() string {
actually we don't need this file, it was added by @deandreJones in his original 21435 branch and I believe we changed to table name since his 21435 to be `re_us_post_regions`. So I dropped this file in favor of the `models/re_us_post_regions`

2024-10-10 22:10 UTC, r-mettler commented on pkg/models/re_us_post_regions.go
> +func (d ReUsPostRegions) TableName() string {
copy pasta, fixed now

2024-10-10 22:10 UTC, r-mettler commented on pkg/models/re_states.go
> +func (d ReStates) TableName() string {
copy pasta, fixed now

2024-10-10 22:10 UTC, r-mettler commented on pkg/models/re_cities.go
> +func (d ReCities) TableName() string {
copy pasta, fixed now

2024-10-11 13:35 UTC, danieljordan-caci commented on migrations/app/schema/20241004150358_create_re_states_re_us_post_regions_re_cities.up.sql
> +state_id	uuid
This should be `NOT NULL`, yeah?

2024-10-11 13:36 UTC, danieljordan-caci commented on migrations/app/schema/20241007224427_update_addresses_us_post_region_cities_id.up.sql
> +ALTER TABLE addresses ADD IF NOT EXISTS us_post_region_cities_id uuid;
Are you missing `ADD COLUMN` here?

2024-10-11 14:08 UTC, danieljordan-caci commented on migrations/app/schema/20241007224427_update_addresses_us_post_region_cities_id.up.sql
> +ALTER TABLE addresses ADD IF NOT EXISTS us_post_region_cities_id uuid;
Actually looking at the previous migration, this is being handled there so this line can be removed.

2024-10-11 14:35 UTC, danieljordan-caci requested changes
Is the `active` column going to be `NOT NULL` or nullable?

Make sure you're setting up pointers in your models when columns can be null.

2024-10-11 14:35 UTC, danieljordan-caci commented on pkg/models/re_cities.go
> +	IsConus   bool      `json:"is_conus" db:"is_conus"`
This should be `IsOconus` & `json:"is_oconus" db:"is_oconus"` per the migration:
```
is_oconus	bool		NOT NULL,
```

2024-10-11 14:35 UTC, danieljordan-caci commented on pkg/models/re_cities.go
> +	StateID   uuid.UUID `json:"state_id" db:"state_id"`
If `state_id` is remaining `NULL` per the migration:
```
state_id	uuid
	CONSTRAINT fk_re_cities_re_states REFERENCES re_states (id),
```

Then this should be a pointer: `*uuid`

2024-10-11 14:35 UTC, danieljordan-caci commented on migrations/app/schema/20241004150358_create_re_states_re_us_post_regions_re_cities.up.sql
> +ALTER TABLE us_post_region_cities ADD COLUMN IF NOT EXISTS cities_id uuid;
We should be setting up foreign keys here, yeah? In DBeaver I'm not seeing that set up correctly.

Also shouldn't it be `city_id` instead of `cities_id`?

Also please add comments when adding columns.

2024-10-11 14:35 UTC, danieljordan-caci commented on pkg/models/re_states.go
> +	IsConus    bool      `json:"is_conus" db:"is_conus"`
This should be `IsOconus` & `json:"is_oconus" db:"is_oconus"` per the migration:
```
is_oconus	bool		NOT NULL,
```

2024-10-11 14:35 UTC, danieljordan-caci commented on pkg/models/re_states.go
> +	State_Name string    `json:"state_name" db:"state_ame"`
This should be `StateName`

Also typo in your db clause: `state_ame`

2024-10-11 14:35 UTC, danieljordan-caci commented on pkg/models/re_international_transit_time.go
> +	UpdatedAt             time.Time `json:"updated_at" db:"updated_at"`
Can we follow what you're doing in other models and put these at the bottom of the model?

2024-10-11 15:06 UTC, r-mettler commented on migrations/app/schema/20241004150358_create_re_states_re_us_post_regions_re_cities.up.sql
> +state_id	uuid
I believe that is should be `NOT NULL`, city has to have a state associated with it

2024-10-11 15:14 UTC, r-mettler commented on migrations/app/schema/20241004150358_create_re_states_re_us_post_regions_re_cities.up.sql
> +ALTER TABLE us_post_region_cities ADD COLUMN IF NOT EXISTS cities_id uuid;
Beth was going to add foreign key constraints in another BL. 
We listed it as `cities_id` because its the id that links back to the `id` in the `re_cities` table. We also have the plural for `us_post_regions_id`.

2024-10-11 15:17 UTC, danieljordan-caci commented on migrations/app/schema/20241004150358_create_re_states_re_us_post_regions_re_cities.up.sql
> +ALTER TABLE us_post_region_cities ADD COLUMN IF NOT EXISTS cities_id uuid;
I agree. I also think we should add foreign key relations here - I see no reason why we shouldn't.

2024-10-11 15:17 UTC, danieljordan-caci commented on migrations/app/schema/20241004150358_create_re_states_re_us_post_regions_re_cities.up.sql
> +state_id	uuid
I agree it should be `NOT NULL`

2024-10-11 17:51 UTC, r-mettler commented on pkg/models/re_oconus_rate_area.go
> +func (ReOconusRateArea) TableName() string {
done

2024-10-11 18:15 UTC, stevengleason-caci commented on Dockerfile.local
> +COPY config/tls/dod-sw-ca-66.pem /config/tls/dod-sw-ca-75.pem
Should this be "75" like the others?
```suggestion
COPY config/tls/dod-sw-ca-75.pem /config/tls/dod-sw-ca-75.pem
```

2024-10-11 18:30 UTC, r-mettler commented on pkg/models/re_cities.go
> +	StateID   uuid.UUID `json:"state_id" db:"state_id"`
I changed `state_id` to be `NOT NULL`

2024-10-11 18:31 UTC, r-mettler commented on migrations/app/schema/20241004150358_create_re_states_re_us_post_regions_re_cities.up.sql
> +state_id	uuid			NOT NULL,
This was originally `NULL` and made it `NOT NULL` because every city should have a state and a `state_id` associated to it.

2024-10-11 19:00 UTC, r-mettler commented on migrations/app/schema/20241004150358_create_re_states_re_us_post_regions_re_cities.up.sql
> +	CONSTRAINT rk_re_cities_re_countries REFERENCES re_countries (id),
fixed

2024-10-11 19:01 UTC, r-mettler commented on pkg/models/re_international_transit_time.go
> +	Active                bool      `json:"active" db:"active"`
made pointer

2024-10-11 19:01 UTC, r-mettler commented on pkg/models/re_states.go
> +	IsConus    bool      `json:"is_conus" db:"is_conus"`
changed to `IsOconus`

2024-10-11 19:01 UTC, r-mettler commented on pkg/models/re_states.go
> +	State_Name string    `json:"state_name" db:"state_ame"`
fixed

2024-10-11 19:01 UTC, r-mettler commented on pkg/models/re_international_transit_time.go
> +	UpdatedAt             time.Time `json:"updated_at" db:"updated_at"`
moved to bottom

2024-10-15 16:17 UTC, traskowskycaci commented on migrations/app/schema/20241004150358_create_re_states_re_us_post_regions_re_cities.up.sql
> +state_id	uuid
Thirding the not null

2024-10-15 16:33 UTC, traskowskycaci commented on migrations/app/schema/20241007184200_create_re_oconus_rate_areas_re_intl_transit_times.up.sql
Should hhg_transit_time, ub_transit_time, or active be changed to NOT NULL for the re_intl_transit_times table?

2024-10-15 16:38 UTC, begrohmann commented on migrations/app/schema/20241004150358_create_re_states_re_us_post_regions_re_cities.up.sql
> +is_oconus	bool,
Updated

2024-10-15 16:45 UTC, begrohmann commented on migrations/app/schema/20241007224427_update_addresses_us_post_region_cities_id.up.sql
> +ALTER TABLE addresses ADD IF NOT EXISTS us_post_region_cities_id uuid;
Looks like this was corrected. I do not see it in a previous migration so I think it needs to stay?

2024-10-15 16:47 UTC, begrohmann commented on migrations/app/schema/20241007184200_create_re_oconus_rate_areas_re_intl_transit_times.up.sql
hhg_transit_time will be null for local AK and HI moves. I do not see where ub_transit_time can be null based on their spreadsheet so I can make this not null.

2024-10-15 16:47 UTC, danieljordan-caci commented on migrations/app/schema/20241004150358_create_re_states_re_us_post_regions_re_cities.up.sql
> +state_id	uuid
@r-mettler please do not resolve these conversations until the fix is pushed. Thanks.

2024-10-15 16:50 UTC, danieljordan-caci commented on migrations/app/schema/20241007224427_update_addresses_us_post_region_cities_id.up.sql
> +ALTER TABLE addresses ADD IF NOT EXISTS us_post_region_cities_id uuid;
Looks to be correct - resolving. Thanks.

2024-10-15 18:09 UTC, r-mettler commented on migrations/app/schema/20241004150358_create_re_states_re_us_post_regions_re_cities.up.sql
> +state_id	uuid
I changed it to not null but realized I did it on one table and not the other. So I thought it was resolved

2024-10-15 19:00 UTC, begrohmann commented on migrations/app/schema/20241004150358_create_re_states_re_us_post_regions_re_cities.up.sql
> +state_id	uuid
Updated

2024-10-15 19:00 UTC, begrohmann commented on migrations/app/schema/20241004150358_create_re_states_re_us_post_regions_re_cities.up.sql
> +ALTER TABLE us_post_region_cities ADD COLUMN IF NOT EXISTS cities_id uuid;
Added FKs

2024-10-15 19:00 UTC, begrohmann commented on migrations/app/schema/20241007184200_create_re_oconus_rate_areas_re_intl_transit_times.up.sql
> +rate_area_id	uuid		NOT NULL,
Added FK

2024-10-15 19:04 UTC, begrohmann commented on migrations/app/schema/20241007184200_create_re_oconus_rate_areas_re_intl_transit_times.up.sql
I don't see where they will have a null ub transit time but I will just leave them both to allow nulls for now.

2024-10-15 19:06 UTC, traskowskycaci commented on migrations/app/schema/20241007184200_create_re_oconus_rate_areas_re_intl_transit_times.up.sql
Good with that! Resolving

2024-10-15 19:50 UTC, danieljordan-caci commented
You have an insane amount of server tests failing btw

2024-10-16 12:24 UTC, cameroncaci requested changes
Identified some areas for change with the models for the ORM, gobuffalo/pop. The types look good, but to ensure that other devs and also automated tests use these models with the db properly we'll want to add in some validators.

These validators prevent nil "(null)" values from being inserted into the database. This is because in go, when a value is initialized as "not nil", it is initialized as "empty". For example, if you create a `var string`, string is equal to an empty string `""`. The same is for UUID, `var uuid` will be initialized as an empty UUID, or `0000-0000-0000`. By having a validator we make sure that we don't end up saving a fake foreign key of an empty UUID value.

This is why in go, if there is a variable that can be null (called nil in go), it is created as a pointer. I provided an example validator for the `ReOconusRateArea` model, more can be found in their docs here https://github.com/gobuffalo/validate?tab=readme-ov-file#usage, or by comparing with existing models we have in the `pkg/models` folder.

2024-10-16 12:24 UTC, cameroncaci commented on pkg/models/re_oconus_rate_area.go
This model needs a validator and test, eg
```go
// Validate gets run every time you call a "pop.Validate*" (pop.ValidateAndSave, pop.ValidateAndCreate, pop.ValidateAndUpdate) method.
func (r *ReOconusRateArea) Validate(_ *pop.Connection) (*validate.Errors, error) {
	return validate.Validate(
		&validators.UUIDIsPresent{Field: r.RateAreaId, Name: "RateAreaId"},
		&validators.UUIDIsPresent{Field: r.CountryId, Name: "CountryId"},
		&validators.UUIDIsPresent{Field: r.UsPostRegionCityId, Name: "UsPostRegionCityId"},
	), nil
}
```

2024-10-16 12:24 UTC, cameroncaci commented on pkg/models/re_cities.go
This model needs a validator and test

2024-10-16 12:24 UTC, cameroncaci commented on pkg/models/re_international_transit_time.go
This model needs a validator and test

2024-10-16 12:24 UTC, cameroncaci commented on pkg/models/re_states.go
This model needs a validator and test

2024-10-16 12:24 UTC, cameroncaci commented on pkg/models/re_states.go
> +}
The name of this struct should be singular of `ReState`. To declare plurals it is recommended to add this line of code:
```go
type ReStates []ReState
```

This way when another package calls this model they can initialize a singular `models.ReState`, or if they have an array they can do `models.ReStates`

2024-10-16 12:24 UTC, cameroncaci commented on pkg/models/re_us_post_regions.go
> +}
The name of this struct should be singular of `ReUsPostRegion`. To declare plurals it is recommended to add this line of code:
```go
type ReUsPostRegions [] ReUsPostRegion
```

This way when another package calls this model they can initialize a singular `models. ReUsPostRegion`, or if they have an array they can do `models. ReUsPostRegions`

2024-10-16 12:24 UTC, cameroncaci commented on pkg/models/re_us_post_regions.go
This model needs a validator and test

2024-10-18 22:23 UTC, r-mettler commented on pkg/models/us_post_region_city_test.go
> -func (suite *ModelSuite) TestCanSaveValidUsPostRegionCity() {
Since we now have static data in the DB table for us_post_region_cities we don't need to test inserting of data because we should NOT be inserting anything into this table going forward. Removed these tests and updated the TestFindCountyByZipCode so we have test coverage for the factory file and we can verify data is present in the us_post_region_cities table.

2024-10-18 22:24 UTC, r-mettler commented on pkg/services/address/address_updater_test.go
> +	suite.Run("Successfully merges state for an address", func() {
added to increase test coverage

2024-10-18 22:24 UTC, r-mettler commented on pkg/services/address/address_creator_test.go
> +	suite.Run("Transforms Country to nil when no country name is specified", func() {
added to increase test coverage

2024-10-18 22:25 UTC, r-mettler commented on scripts/db-truncate
> +              AND tablename NOT IN ('us_post_region_cities', 're_countries', 're_states', 're_cities', 're_us_post_regions', 're_oconus_rate_areas', 're_rate_areas', 're_intl_transit_times')) LOOP
We don't want to delete the data in these tables as they all will contain static data.

2024-10-21 14:11 UTC, r-mettler commented on pkg/models/address_test.go
> +func (suite *ModelSuite) TestAddressFormat() {
Increasing test coverage

2024-10-21 14:23 UTC, r-mettler commented on pkg/models/re_cities.go
Nothing is using these new tables yet. We shouldn't be updating or inserting anything into the re_cities and re_state tables as they are static data so would we still want/need the validators?

2024-10-21 18:57 UTC, r-mettler commented on pkg/models/re_cities.go
> +	ID        uuid.UUID `json:"id" db:"id" rw:"r"`
modified the model to be read only because we don't want anybody updating anything in the tables via the app

2024-10-21 18:57 UTC, r-mettler commented on pkg/models/re_oconus_rate_area.go
> +	ID                 uuid.UUID `json:"id" db:"id" rw:"r"`
modified the model to be read only because we don't want anybody updating anything in the tables via the app

2024-10-22 14:54 UTC, r-mettler commented on pkg/models/re_cities.go
See comment for `pkg/models/re_international_transit_time.go`

2024-10-22 14:55 UTC, r-mettler commented on pkg/models/re_states.go
See comment for `pkg/models/re_international_transit_time.go`

2024-10-22 14:55 UTC, r-mettler commented on pkg/models/re_us_post_regions.go
See comment for `pkg/models/re_international_transit_time.go`

2024-10-22 14:57 UTC, r-mettler commented on pkg/models/re_oconus_rate_area.go
See comment for `pkg/models/re_international_transit_time.go`

2024-10-22 20:08 UTC, traskowskycaci approved these changes
Migrations run without issue locally, seeing all the tables and the view

2024-10-23 14:55 UTC, r-mettler approved these changes
I approve Beth's changes, and of course my own 😄

2024-10-23 15:04 UTC, danieljordan-caci commented on pkg/models/re_oconus_rate_area.go
> +type ReOconusRateArea struct {
Is there a reason why this file name and struct is singular `ReOconusRateArea` instead of `ReOconusRateAreas`?

2024-10-23 15:04 UTC, danieljordan-caci commented on pkg/models/re_oconus_rate_area.go
> +	Active             *bool     `json:"active" db:"active" rw:"r"`
We cool with this being nullable?

2024-10-23 15:08 UTC, danieljordan-caci requested changes

2024-10-23 15:08 UTC, r-mettler commented on pkg/models/re_oconus_rate_area.go
> +type ReOconusRateArea struct {
I believe this one we pulled in from Dre's 21435 and just didn't change it. I will go change it to use plural.

2024-10-23 15:10 UTC, danieljordan-caci commented on pkg/models/service_member.go
> +			}
Wondering why this is not in the code... It was def merged in [this PR](https://github.com/transcom/mymove/pull/13902/files)

2024-10-23 15:13 UTC, danieljordan-caci commented on pkg/services/address/address_creator.go
> +		transformedAddress.Country = &country
Remove this line - it's a duplicate

2024-10-23 15:14 UTC, danieljordan-caci commented on pkg/services/address/address_creator_test.go
> +	suite.Run("Transforms Country to nil when no country name is specified", func() {
The title of this test is incorrect - you're testing that if a nil country is provided and checking that an error is returned. Please change the title to be more descriptive to what's being tested.

2024-10-23 15:19 UTC, danieljordan-caci commented on pkg/models/re_oconus_rate_area.go
> +type ReOconusRateArea struct {
Thank ya

2024-10-23 15:30 UTC, r-mettler commented on pkg/models/service_member.go
> +			}
Looking at the history in INT, looks like this [commit](https://github.com/transcom/mymove/commit/8f9cb75cc394657ce2090d4744b6b39569d7ebb5) added it but in the next [commit]([merge integration](https://github.com/transcom/mymove/commit/050b38c200db76ce56692e5082cd73d92aa78eaa)) its not there.

2024-10-23 15:36 UTC, r-mettler commented on pkg/services/address/address_creator_test.go
> +	suite.Run("Transforms Country to nil when no country name is specified", func() {
These weren't changes that we made, assuming they came from your branch since it states Country. I'll go change it here.

2024-10-23 15:36 UTC, r-mettler commented on pkg/services/address/address_creator.go
> +		transformedAddress.Country = &country
thanks git lol

2024-10-23 15:41 UTC, r-mettler commented on pkg/services/address/address_updater.go
> +
This was pulled in from your [commit](https://github.com/transcom/mymove/commit/3387596631b49350a19f53f2ba9bea5fd954b569#diff-9220efd41eeec670da964c3ce45222dc721652e7171f14bde828be6b91793b74)
😄 
Glad your reviewing these. Updating it now.

2024-10-23 15:44 UTC, danieljordan-caci commented on pkg/models/re_oconus_rate_area.go
> +	Active             *bool     `json:"active" db:"active" rw:"r"`
Yeah

2024-10-23 15:48 UTC, deandreJones commented on pkg/models/re_oconus_rate_area.go
> +type ReOconusRateArea struct {
wait- should it be plural.. most of the model files are singular 
but reference the plural table and return the plural table name in func TableName()

2024-10-23 15:50 UTC, danieljordan-caci commented on pkg/services/address/address_creator_test.go
> +	suite.Run("Transforms Country to nil when no country name is specified", func() {
Yeah some funky stuff goin' on

2024-10-23 15:51 UTC, danieljordan-caci commented on pkg/models/re_oconus_rate_area.go
> +type ReOconusRateArea struct {
In that case, should it be `OconusRateArea`?

@r-mettler doing the same with `State` and `City` (which I like) - removing the `Re` seems appropriate.

2024-10-23 15:51 UTC, begrohmann commented on pkg/models/re_oconus_rate_area.go
> +	Active             *bool     `json:"active" db:"active" rw:"r"`
It's bool with default true so it should always either be true or false. Doesn't hurt to set it not null if we want.

2024-10-23 15:52 UTC, deandreJones commented on pkg/models/re_oconus_rate_area.go
> +type ReOconusRateArea struct {
looking at other models- it isn't very consistent - some have the Re some don't ...

2024-10-23 15:53 UTC, r-mettler commented on pkg/models/service_member.go
> +			}
@danieljordan-caci Can you verify this is in the correct spot in the code since git placed it here.

2024-10-23 15:56 UTC, r-mettler commented on pkg/services/address/address_creator.go
> +		transformedAddress.Country = &country
removed the duplicate, this was from a git merge so its only in the INT branch and not on the main.

2024-10-23 16:05 UTC, r-mettler commented on pkg/services/mto_shipment/mto_shipment_creator_test.go
> +	suite.Run("If the shipment has an international address it should be returned", func() {
Looks like this might be another one that was already in INT as part of 21703?

2024-10-23 16:57 UTC, r-mettler commented on pkg/models/re_oconus_rate_area.go
> +type ReOconusRateArea struct {
I like have the model file the same name as the table because it makes it easier to know which table it corresponds to in the DB, but I agree we should remove the Re from the struct names. I'll go do that.

2024-10-23 18:25 UTC, r-mettler commented on pkg/models/re_oconus_rate_area.go
> +	Active             *bool     `json:"active" db:"active" rw:"r"`
I made the Active columns not null in the table and in the model I updated to have `bool` and not `*bool`

2024-10-23 19:01 UTC, r-mettler commented on pkg/models/re_international_transit_time.go
> +	return "re_international_transit_times"
Changed filename to be plural and removed the Re from the struct name.

2024-10-23 19:02 UTC, r-mettler commented on pkg/models/service_member.go
> +			}
removed

2024-10-23 19:02 UTC, r-mettler commented on pkg/services/address/address_updater.go
> +
removed

2024-10-23 19:02 UTC, r-mettler commented on pkg/services/address/address_creator_test.go
> +	suite.Run("Transforms Country to nil when no country name is specified", func() {
Updated the description

2024-10-23 20:33 UTC, deandreJones approved these changes

2024-10-23 20:35 UTC, danieljordan-caci requested changes

2024-10-23 20:35 UTC, danieljordan-caci commented on pkg/models/re_international_transit_times.go
> +	return "re_international_transit_times"
This table name is still wrong. It's `re_intl_transit_times` in your migration

2024-10-23 22:34 UTC, r-mettler commented on pkg/models/re_international_transit_times.go
> +	return "re_international_transit_times"
It wasn't at one point 😄 . I fixed it, good catch

2024-10-24 12:56 UTC, danieljordan-caci approved these changes

2024-10-24 15:11 UTC, merged