B 21432 display market code int
transcom/mymove pull request #13940
Opened 2024-10-17 13:27 UTC by TevinAdams

## [B-21432](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-21432)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-10-18 19:46 UTC, traskowskycaci requested changes

2024-10-18 19:46 UTC, traskowskycaci commented on src/components/Customer/Review/ShipmentCard/HHGShipmentCard/HHGShipmentCard.test.jsx
> +  it('renders incomplete HHGShipmentCard with a heading that as a market code and shipment type', async () => {
small typo here - as should be has

2024-10-18 19:46 UTC, traskowskycaci commented on src/components/Customer/Review/ShipmentCard/HHGShipmentCard/HHGShipmentCard.test.jsx
> +  marketCode: 'd',
I see lots of good test cases for marketCode: 'd' - would you mind adding in a few for marketCode: 'i'?

2024-10-18 19:46 UTC, traskowskycaci commented on src/components/Customer/Review/ShipmentCard/HHGShipmentCard/HHGShipmentCard.test.jsx
> +  it('renders complete HHGShipmentCard with a heading that as a market code and shipment type', async () => {
small typo here - as should be has

2024-10-18 19:46 UTC, traskowskycaci commented on src/components/Customer/Review/Summary/Summary.jsx
>        }
Not seeing a market_code for a UB on the summary page - looks like we need a `marketCode={shipment.marketCode}` addition for line 338 inside this `shipment.shipmentType === SHIPMENT_TYPES.UNACCOMPANIED_BAGGAGE` if condition

![image](https://github.com/user-attachments/assets/4a0daf0a-45b0-4c76-b370-1bad326fd501)

2024-10-18 19:46 UTC, traskowskycaci commented on src/components/Office/ShipmentHeading/shipmentHeading.module.scss
> +    font-size: 14px;
What do you think of making this font-size slightly bigger? As is, as an office user viewing it on the MTO page, I personally think the market code looks slightly smaller than it should, proportionally.

As is - 14px:
![image](https://github.com/user-attachments/assets/83d3a95e-e140-44bb-9216-84ed5de29228)

Example of upping that to 20px:
![image](https://github.com/user-attachments/assets/f40b1c1e-2e68-4c32-97b9-4a2f2dc8f902)

2024-10-21 13:59 UTC, TevinAdams commented on src/components/Office/ShipmentHeading/shipmentHeading.module.scss
> +    font-size: 14px;
I agree that I do like them with a bigger font. I increased all of the font for these to at least 16. then some 20.

2024-10-21 14:00 UTC, TevinAdams commented on src/components/Customer/Review/Summary/Summary.jsx
>        }
Ahhh this is in int but not main so I missed this one. Its added now. Good catch.

2024-10-21 14:01 UTC, TevinAdams commented on src/components/Customer/Review/ShipmentCard/HHGShipmentCard/HHGShipmentCard.test.jsx
> +  it('renders complete HHGShipmentCard with a heading that as a market code and shipment type', async () => {
Went through and fixed the typo on this text and the other ones I found.

2024-10-21 14:01 UTC, TevinAdams commented on src/components/Customer/Review/ShipmentCard/HHGShipmentCard/HHGShipmentCard.test.jsx
> +  marketCode: 'd',
I went through and switched a few of them to use "i".

2024-10-21 14:01 UTC, TevinAdams commented on src/components/Customer/Review/ShipmentCard/HHGShipmentCard/HHGShipmentCard.test.jsx
> +  it('renders incomplete HHGShipmentCard with a heading that as a market code and shipment type', async () => {
Went through and fixed the typo on this text and the other ones I found.

2024-10-21 14:01 UTC, traskowskycaci commented on src/components/Customer/Review/Summary/Summary.jsx
>        }
Ah yes, totally understand on that one. Hopefully getting the first wave of UB work PO accepted this week

2024-10-21 14:24 UTC, danieljordan-caci requested changes
Could you also update the prime sim? Doesn't have to be anything fancy, but was thinking here:
![Screenshot 2024-10-21 at 9 23 57 AM](https://github.com/user-attachments/assets/1a1447d4-519b-4766-8b61-b970b5a42e81)

2024-10-21 15:00 UTC, TevinAdams commented
> Could you also update the prime sim? Doesn't have to be anything fancy, but was thinking here: ![Screenshot 2024-10-21 at 9 23 57 AM](https://private-user-images.githubusercontent.com/136510600/378467941-1a1447d4-519b-4766-8b61-b970b5a42e81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MjMwOTMsIm5iZiI6MTcyOTUyMjc5MywicGF0aCI6Ii8xMzY1MTA2MDAvMzc4NDY3OTQxLTFhMTQ0N2Q0LTUxOWItNDc2Ni04YjYxLWI5NzBiNWE0MmU4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQxNDU5NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OTJmMzI3ZGIwNjU3YjU4MmUxZTJjNjc0ZmZiNmQ4ZTQ1MDJiYjcxMzVkYmFlNjZjNDIxZjZjNjEzOTM0MDQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8bGLMle95D1cJN_BAxKQdNB5WtzXv8Ih2N5SU0wqeoQ)

@danieljordan-caci  added.
![image](https://github.com/user-attachments/assets/6f6878d9-1f60-4557-86fc-6aa47c9371cc)

2024-10-21 15:18 UTC, danieljordan-caci approved these changes
LGTM!

![Screenshot 2024-10-21 at 10 18 46 AM](https://github.com/user-attachments/assets/fc3bc757-c13a-45b5-80f6-a5625d1bc0d2)

2024-10-21 15:19 UTC, traskowskycaci approved these changes
Looks good!

2024-10-21 15:20 UTC, danieljordan-caci commented
You do have some client tests failing that aren't flaky - just saw

2024-10-22 14:03 UTC, merged