INT - B-21481 -  DB -  Add HI/AK duty locations
transcom/mymove pull request #13963
Opened 2024-10-21 14:32 UTC by MInthavongsay

## [B-21481](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A1016235&RoomContext=TeamRoom%3A855664&concept=TeamRoom)

## Summary

This PR introduces a new database migration file to insert 533 Hawaii and Alaska duty locations. A total of 533 duty location records were created out of possible 639 from the provided TRDM file. 106 duty locations were ignored/excluded per TRDM's instructions(flag).   

Feature flag -- enable_alaska -  has been been incorporated to include/exclude both HI and AK duty locations from duty location search results. This feature serves as a transitional feature to bridge the work between data migration and the issue related to empty counseling office dropdown. Another backlog ticket will be created to address the counseling office issue. This FF enables this ticket to be fulfilled per AC.

Note: This PR contains [DB - INT PR 21442](https://github.com/transcom/mymove/pull/13872)

**New Migration File: migrations/app/schema/20241017183144_add_AK_HI_duty_locations.up.sql**

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Edit .envrc and set FEATURE_FLAG_ENABLE_ALASKA to TRUE. Run direnv allow. Login as customer/office. Goto view containing Duty Location widget and search for Alaska and Hawaii locations....ie Honolulu, Anchorage ...etc... See attached file below for 599 expected locations. Confirm AK and HI locations are present in the results.
2. Edit .envrc and set FEATURE_FLAG_ENABLE_ALASKA to FALSE. Run direnv allow. Login as customer/office. Goto view containing Duty Location widget and search for Alaska and Hawaii locations....ie Honolulu, Anchorage ...etc... See attached file below for 599 expected locations. Confirm AK and HI locations are not present in the results.

**599 Duty Locations:**
[HI-AK-data-1729264016473.csv](https://github.com/user-attachments/files/17462373/HI-AK-data-1729264016473.csv)

Note: 
106 Excluded Duty Locations:
[null-us_post_region_cities_id.csv](https://github.com/user-attachments/files/17462406/null-us_post_region_cities_id.csv)

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-10-21 21:28 UTC, r-mettler commented on migrations/app/schema/20241017183144_add_AK_HI_duty_locations.up.sql
> +INSERT INTO public.addresses VALUES ('4d1f305a-fb7d-4191-ab3c-349e749d340a','n/a',null,'KAILUA KONA','HI','96745','2024-10-17 18:12:00.374399','2024-10-17 18:12:00.374399',null,'HAWAII',true,'791899e
We should change these to use the COPY command, its best for large data inserts. I can help you bulk edit this in VSCode if you need to.
See the `20241004151509_insert_re_cities.up.sql` file for an example on the format. Note those are tabs in between the data.

2024-10-22 18:09 UTC, MInthavongsay commented on migrations/app/schema/20241017183144_add_AK_HI_duty_locations.up.sql
> +INSERT INTO public.addresses VALUES ('4d1f305a-fb7d-4191-ab3c-349e749d340a','n/a',null,'KAILUA KONA','HI','96745','2024-10-17 18:12:00.374399','2024-10-17 18:12:00.374399',null,'HAWAII',true,'791899e
Done.

2024-10-23 18:02 UTC, MInthavongsay commented on .envrc
> +# Feature flag to allow AK to be entered as a state
This is probably coming from the merge of 21442.

2024-10-23 18:16 UTC, MInthavongsay commented on .envrc
> +# Feature flag to allow AK to be entered as a state
It looks like it came from original merge of B-21442-INT into my INT branch. Merging latest of B-21442-INT corrected the issue.

2024-10-29 15:34 UTC, ajlusk approved these changes
No AK & HI locations with the feature flag off:
<img width="554" alt="Screenshot 2024-10-29 at 11 12 27 AM" src="https://github.com/user-attachments/assets/f1040c31-6897-40e9-ab86-16cdda25c1d6">

AK & HI flags with the feature flag on:
<img width="554" alt="Screenshot 2024-10-29 at 11 07 00 AM" src="https://github.com/user-attachments/assets/18b26420-f5aa-42eb-a5cd-3d1bfa758e64">
<img width="554" alt="Screenshot 2024-10-29 at 11 06 25 AM" src="https://github.com/user-attachments/assets/eb273320-4f70-432e-b094-bebe797eb507">

No Counseling Offices available when an AK or HI duty location is selected as expected: 
<img width="559" alt="Screenshot 2024-10-29 at 11 27 41 AM" src="https://github.com/user-attachments/assets/16c3f516-05b3-4c73-8e69-3a6df98abf7f">

"City Names To Avoid" are not included
<img width="554" alt="Screenshot 2024-10-29 at 11 07 52 AM" src="https://github.com/user-attachments/assets/1a85d164-7814-4845-803f-36ce91d96ce4">

2024-10-29 15:39 UTC, ajlusk commented
Unrelated to these changes but I did notice even with enable_alaska FF set to true I am not able to use an AK zip code in my customer's current address in the initial account set up:
<img width="554" alt="Screenshot 2024-10-29 at 11 05 23 AM" src="https://github.com/user-attachments/assets/61ef368d-bcb8-4499-82fe-71d0c93f7f3a">

However, I am able to edit my existing current address to an AK zip code:
<img width="559" alt="Screenshot 2024-10-29 at 11 32 24 AM" src="https://github.com/user-attachments/assets/f65237c1-67f9-460e-9281-6157ea5a2eea">

First part may be something that the alaska FF needs to include. Second part seems like an oversight from at least 16 months ago.

2024-10-29 17:25 UTC, begrohmann approved these changes

2024-10-29 20:16 UTC, traskowskycaci requested changes
Test coverage for pkg/handlers/internalapi/duty_locations.go is showing lots of red, can you add a test in? Here's an example of how to mock the feature flag fetcher: https://github.com/transcom/mymove/pull/13976/files#diff-eed993d434b4dccb23f242b5fe4737faceabef22a440321423563a2ff454e548

<img width="1060" alt="image" src="https://github.com/user-attachments/assets/50377610-2cde-49d4-85f6-725dac182717">

2024-10-29 20:20 UTC, traskowskycaci commented
> Test coverage for pkg/handlers/internalapi/duty_locations.go is showing lots of red, can you add a test in? Here's an example of how to mock the feature flag fetcher: https://github.com/transcom/mymove/pull/13976/files#diff-eed993d434b4dccb23f242b5fe4737faceabef22a440321423563a2ff454e548
> 


You're using GetBooleanFlagForUser, so here is a file with a more closely related example on how to mock that - https://github.com/transcom/mymove/blob/integrationTesting/pkg/handlers/internalapi/mto_shipment_test.go

2024-10-30 13:59 UTC, traskowskycaci approved these changes
Thanks for adding those tests in!

2024-10-30 14:22 UTC, traskowskycaci commented
> This is unrelated to these changes but I did notice even with enable_alaska FF set to true I am not able to use an AK zip code in my customer's current address in the initial account set up: <img alt="Screenshot 2024-10-29 at 11 05 23 AM" width="554" src="https://private-user-images.githubusercontent.com/158500142/381199277-61ef368d-bcb8-4499-82fe-71d0c93f7f3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyOTg0MDMsIm5iZiI6MTczMDI5ODEwMywicGF0aCI6Ii8xNTg1MDAxNDIvMzgxMTk5Mjc3LTYxZWYzNjhkLWJjYjgtNDQ5OS04MmZlLTcxZDBjOTNmN2YzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMFQxNDIxNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YjFhMDRjN2Y1MWEwYTFmZWY3OTI3MzllN2NkN2FkYmYwN2EyNWQ5MjA0ZDhlYTMwZWMzMWZmZWJhYWQ4NTU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.X_VOqSVgMGrpcz73ZouLCDQzp_lhOiNnyjjjVsU9ag8">
> 
> However, I am able to edit my existing current address to an AK zip code: <img alt="Screenshot 2024-10-29 at 11 32 24 AM" width="559" src="https://private-user-images.githubusercontent.com/158500142/381199760-f65237c1-67f9-460e-9281-6157ea5a2eea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyOTg0MDMsIm5iZiI6MTczMDI5ODEwMywicGF0aCI6Ii8xNTg1MDAxNDIvMzgxMTk5NzYwLWY2NTIzN2MxLTY3ZjktNDYwZS05MjgxLTYxNTdlYTVhMmVlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMFQxNDIxNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNjFhMTdmZTc0YTk4ZDAzMzA5MjgzNTFiNDQzNDBiZTVkYzNkNGU0Y2ZiM2Y4NmQ3MDk3MmYwNmRkNjZhMGQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4K4002uiGZc-B-d9u-OXV9c_WOPwhchcziHGCgMQKYg">
> 
> First part may be something that the alaska FF needs to include. Second part seems like an oversight from at least 16 months ago.

That error message and AK zip codes will be handled with @r-mettler's [B-21168](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A1011663) work

2024-10-30 15:01 UTC, merged