B 21374 ub fields int
transcom/mymove pull request #13977
Opened 2024-10-22 17:17 UTC by cameroncaci

## [B-21374](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A1014669&RoomContext=TeamRoom%3A808731&concept=TeamRoom)

## Summary

Introduces the optional and OCONUS specific fields of accompanied tour and dependent under/over 12 years of age. Feature flags the frontend portion of the application - the backend is not FF'd as it is the internal API and optional, nullable fields with no intent to ever make not nullable. This means the backend works as intended with or without the FF. The Prime cannot control these fields at this time, this is purely for customer and office user.

These OCONUS specific fields are for UB allowance enabling.

## How to test

Please test with FF on and off

### Setup
1. Think of two different duty locations
2. Once you have two different duty locations, open one up within the database, navigate to its address, and set the address `is_oconus` to true
3. Now you have a CONUS and OCONUS duty location
4. Update `.envrc` and adjust `+export FEATURE_FLAG_UNACCOMPANIED_BAGGAGE=true`

### Customer
1. Navigate to milmovelocal and create a new account
2. Create a new order and fill out all forms until you reach "Tell us about your move orders"
![image](https://github.com/user-attachments/assets/1367f9a4-b66a-4479-b33e-0229a83b5c79)
3. Fill in current and new duty location, ensuring to set one of these locations to the OCONUS version you created in the "Setup" section above.
5. Test adding dependents
6. Remove your OCONUS duty location and check that the OCONUS fields dissappear
7. Try to break it
8. Fully submit your move and proceed to Office

### Office
1. Once you have submitted the move as a customer, login to Office and preview the submitted move as a SC and TOO
2. The SC should be able to see the information under entitlements
3. The TOO should be able to see the information under entitlements and update them
4. These OCONUS entitlement fields shouldn't be present on CONUS moves, verify that
5. Try to break it

## Recording
https://github.com/user-attachments/assets/1d8f5474-5b7c-4caa-a20c-77e73c3df358

## 508 Screenshot
Tooltips do not violate ANDI
![image](https://github.com/user-attachments/assets/2a6fa962-231d-4e45-8380-6af0bb79deef)

2024-10-24 17:48 UTC, begrohmann commented on migrations/app/schema/20241018091722_oconus-entitlements-enhancement.up.sql
> +    ADD COLUMN dependents_under_twelve INTEGER NULL,
Need ADD COLUMN IF NOT EXISTS on these

2024-10-24 19:22 UTC, cameroncaci commented on migrations/app/schema/20241018091722_oconus-entitlements-enhancement.up.sql
> +    ADD COLUMN dependents_under_twelve INTEGER NULL,
resolved in b18166514bfa46643e890b9c4f7e968dea6f6f20

2024-10-24 19:26 UTC, traskowskycaci requested changes
1. From the AC - "When I select yes,
I can enter values for the number of dependents "12 and Older" AND "Under 12" (clear out values entered when the user changes dependents included answer back to "No").
I wasn't seeing the number of dependents under the age of 12 and over 12 clearing out when toggling the "Are dependents included in your orders" radio buttons - values persisted

2. I see 0s for dependents < 12 and >= 12 when viewing the Edit Allowances page as an SC:
![image](https://github.com/user-attachments/assets/e5cd3a0b-5972-4f3a-9956-d1b3fc394d10)
Steps I took:
Viewed allowances on move summary page as SC
Viewed allowances on move summary page as TOO
Edited allowances as TOO (which worked great!)
Tried to edit allowances as SC and saw the 0 values

3. This is just a thought and not necessarily requesting you change this - I could see Dan not liking the placement of these tooltips and he might prefer them to be more inline with the text 


All AC except the last one and the one I mentioned above look like they've been met!
Seeing the entitlement DB values match the UI inputs, as well as get updated based on the TOO editing them.

2024-10-24 20:10 UTC, TevinAdams commented
I was able to change the Number of dependents under age of 12 as a SC. Not sure if that's correct or not because the testing instructions says SC should be able to see the information and TOO should be able to update it.

2024-10-25 12:33 UTC, cameroncaci commented
Converting back to draft to address changes and introduce new AC. New functionality will be as follows:

- Customer being able to edit accompanied tour, dependents under twelve, dependents twelve and over on their orders after it has been submitted
- Customer being able to preview these UB fields when selecting "Review request"
- SC being able to edit UB fields
- Checking with PO on tooltip preview

2024-10-25 12:37 UTC, cameroncaci commented
> 1. From the AC - "When I select yes,
>    I can enter values for the number of dependents "12 and Older" AND "Under 12" (clear out values entered when the user changes dependents included answer back to "No").
>    I wasn't seeing the number of dependents under the age of 12 and over 12 clearing out when toggling the "Are dependents included in your orders" radio buttons - values persisted

@traskowskycaci I did this intentionally so that if the user is just clicking around, they can keep their values without having to re-type information they've already entered - figured it'd be a smoother experience. I have conditionals on the submit that will default these to null if dependents are set to false/('no'). Let me know if this suffices and if it works as intended

2024-10-25 19:28 UTC, cameroncaci commented
> I was able to change the Number of dependents under age of 12 as a SC. Not sure if that's correct or not because the testing instructions says SC should be able to see the information and TOO should be able to update it.

The AC required us to fill in the gaps here in there which is how we got some dev proposed AC. SC should be able to edit allowances and is fully able to now - ready for review again (Once I verify the pipeline is passing)

2024-10-25 19:42 UTC, cameroncaci commented
Failing test is flaky

2024-10-25 19:52 UTC, cameroncaci commented
Failing tests are flaky

2024-10-25 20:14 UTC, danieljordan-caci reviewed
Is there a reason the customer can't edit their information after adding their orders but before submitting their shipments?

![Screenshot 2024-10-25 at 3 14 27 PM](https://github.com/user-attachments/assets/86362a76-e8b9-48d5-832d-708809ab0f1f)

2024-10-25 20:43 UTC, danieljordan-caci requested changes
![Screenshot 2024-10-25 at 3 36 06 PM](https://github.com/user-attachments/assets/5d5bc236-c9c3-4ecb-8265-92c59c7dc30c)

Some UI requested changes... Can you shorten these a bit? Suggestions:
- `Accompanied tour` with a `Yes` or `No` value instead of `Is this an accompanied tour?`
- `Dependents under age 12` instead of `Number of dependents under the age of 12`
- `Dependents over age 12` instead of `Number of dependents of the age 12 or over`

And you could keep the extended description in this part
![Screenshot 2024-10-25 at 3 38 28 PM](https://github.com/user-attachments/assets/b9f4e263-38b3-49e3-b85e-e7b910daa4ef)


Also could you please update/add the storybooks for the `EditOrdersForm`, `AddOrdersForm` and the `AllowancesList` form?

And... Don't want to open a can here, but remember the SC can add orders for a service member...
![Screenshot 2024-10-25 at 3 42 55 PM](https://github.com/user-attachments/assets/32c89948-f9a5-426d-889b-7e5fd15acc2b)

2024-10-28 13:00 UTC, begrohmann approved these changes

2024-10-28 13:09 UTC, traskowskycaci commented
> > 1. From the AC - "When I select yes,
> >    I can enter values for the number of dependents "12 and Older" AND "Under 12" (clear out values entered when the user changes dependents included answer back to "No").
> >    I wasn't seeing the number of dependents under the age of 12 and over 12 clearing out when toggling the "Are dependents included in your orders" radio buttons - values persisted
> 
> @traskowskycaci I did this intentionally so that if the user is just clicking around, they can keep their values without having to re-type information they've already entered - figured it'd be a smoother experience. I have conditionals on the submit that will default these to null if dependents are set to false/('no'). Let me know if this suffices and if it works as intended

Morning! Honestly, I like your implementation. However, it would probably be good to run it by Dan that AC mentioning clearing out the values did come from the him & his team

2024-10-28 17:35 UTC, cameroncaci commented
Moving back to draft until new AC gets added in

2024-10-28 17:35 UTC, cameroncaci commented
> I was able to change the Number of dependents under age of 12 as a SC. Not sure if that's correct or not because the testing instructions says SC should be able to see the information and TOO should be able to update it.

Customer confirms this is desired capabilities

2024-10-28 17:36 UTC, cameroncaci commented
> > > 1. From the AC - "When I select yes,
> > >    I can enter values for the number of dependents "12 and Older" AND "Under 12" (clear out values entered when the user changes dependents included answer back to "No").
> > >    I wasn't seeing the number of dependents under the age of 12 and over 12 clearing out when toggling the "Are dependents included in your orders" radio buttons - values persisted
> > 
> > 
> > @traskowskycaci I did this intentionally so that if the user is just clicking around, they can keep their values without having to re-type information they've already entered - figured it'd be a smoother experience. I have conditionals on the submit that will default these to null if dependents are set to false/('no'). Let me know if this suffices and if it works as intended
> 
> Morning! Honestly, I like your implementation. However, it would probably be good to run it by Dan that AC mentioning clearing out the values did come from the him & his team

Thank you for pointing that out, asked and concurred (See agility for POA)

2024-10-28 17:36 UTC, cameroncaci commented
> ![Screenshot 2024-10-25 at 3 36 06 PM](https://private-user-images.githubusercontent.com/136510600/380318764-5d5bc236-c9c3-4ecb-8265-92c59c7dc30c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMzU3NzksIm5iZiI6MTczMDEzNTQ3OSwicGF0aCI6Ii8xMzY1MTA2MDAvMzgwMzE4NzY0LTVkNWJjMjM2LWM5YzMtNGVjYi04MjY1LTkyYzU5YzdkYzMwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOFQxNzExMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDlmYWRiYWZlNTIzYzRiNWYzNzdhZThlMjcwMGY0Yzg4YWI3OWU5MjExN2U4YjNmMmRjMGUxMjc4Y2YwNWFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oOANgABNDJ-lBeLcRnBumsuOpYj3jLtSvGANm8UYGLk)
> 
> Some UI requested changes... Can you shorten these a bit? Suggestions:
> 
> * `Accompanied tour` with a `Yes` or `No` value instead of `Is this an accompanied tour?`
> * `Dependents under age 12` instead of `Number of dependents under the age of 12`
> * `Dependents over age 12` instead of `Number of dependents of the age 12 or over`
> 
> And you could keep the extended description in this part ![Screenshot 2024-10-25 at 3 38 28 PM](https://private-user-images.githubusercontent.com/136510600/380319514-b9f4e263-38b3-49e3-b85e-e7b910daa4ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMzU3NzksIm5iZiI6MTczMDEzNTQ3OSwicGF0aCI6Ii8xMzY1MTA2MDAvMzgwMzE5NTE0LWI5ZjRlMjYzLTM4YjMtNDllMy1iODVlLWU3YjkxMGRhYTRlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOFQxNzExMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYTFjNjE1MDNiNWExZjA4ZWMwMWQ4ZmI2NmZjOTZhNTI4MzM1ZjNiZDBkYjQ2ZjAwYmM4MjA1NjBlOWJkM2Y0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4hDU1XiYAw-9NldxnLtlZXWDauqhDDEGssaEO0-j2Po)
> 
> Also could you please update/add the storybooks for the `EditOrdersForm`, `AddOrdersForm` and the `AllowancesList` form?
> 
> And... Don't want to open a can here, but remember the SC can add orders for a service member... ![Screenshot 2024-10-25 at 3 42 55 PM](https://private-user-images.githubusercontent.com/136510600/380320795-32c89948-f9a5-426d-889b-7e5fd15acc2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMzU3NzksIm5iZiI6MTczMDEzNTQ3OSwicGF0aCI6Ii8xMzY1MTA2MDAvMzgwMzIwNzk1LTMyYzg5OTQ4LWY5YTUtNDI2ZC04ODliLTdlNWZkMTVhY2MyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOFQxNzExMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMTU3NTBjMTZmYzI2OTAxY2FjNWIxZTI0N2RlMmFlMmVmYzlhZTA0OGUwMmYxMGY0YmFkYTc3YmNlOTU4NGJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.69hHeyrJX-7hiWx6YgM-tWoqjhUK-OFPWLmYgKE6gag)

Proposed to customer and added as new AC, will action

2024-11-06 16:39 UTC, TevinAdams approved these changes
Tested this and it works as expected.

2024-11-06 18:55 UTC, traskowskycaci approved these changes
Looks good

2024-11-06 19:20 UTC, danieljordan-caci approved these changes

2024-11-06 19:53 UTC, merged