INT B-20808 GSR user can add appeals to violations
transcom/mymove pull request #13994
Opened 2024-10-23 22:26 UTC by danieljordan-caci

## [Agility ticket](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-20808)

## Summary

We want to let the GSR office users to be able to add an appeal to a violation. A violation can only have one appeal by a GSR user and it's a one time thing and there's no requirement for them to edit it or anything. Future work will allow COR office users to add additional appeals and that's why the architecture of the appeals process is an array of objects. This PR does the following:
- adds and edits swagger definitions to allow `gsrAppeals` to appear on report violations and evaluation reports
- adds service object to add a row to the `gsr_appeals` table
- updates UI to allow a GSR user to add an appeal
- adds/updates relevant tests
- added tests to increase server test coverage

### How to test

1. Turn the GSR flag on in your `envrc`
2. Fire up your `server` and `client`
3. You can either sign in as a multi role user or a GSR user
4. Search for a move (my fav is `EVLRPT` with devseed data)
5. Create a report and add a couple violations
6. Once you're back on the evaluation report screen, click to view the report
7. You should see a `Leave Appeal Decision` button
8. Fill that form out and submit
10. You should now see a dropdown that you can click that will expand and show the details of the appeal you just left underneath the violation
11. Verify you see the information in the `gsr_appeals` table with all relevant data

## Screenshots
![Screenshot 2024-10-23 at 3 45 11 PM](https://github.com/user-attachments/assets/8c478832-b332-48b9-9a27-e27ea671d381)
![Screenshot 2024-10-23 at 3 45 28 PM](https://github.com/user-attachments/assets/d4fecd65-00ea-4d76-ae20-fbc2da48e515)

2024-10-24 18:06 UTC, begrohmann approved these changes

2024-10-24 19:54 UTC, traskowskycaci requested changes
This is a silly one - slight change in color contrast needed for the green button to meet ANDI compliance:
![image](https://github.com/user-attachments/assets/3673abb7-44c4-478e-8d41-016a6bf40e01)

2024-10-24 19:57 UTC, traskowskycaci requested changes
Also noticed in the description of the story that as a GSR, I should be able to leave an appeal decision if a serious incident was found. I am logged in as a GSR here and created a report with a serious incident but don't see the option to leave an appeal decision:
![image](https://github.com/user-attachments/assets/cab9cf31-6e5a-4513-966c-c301d4b09cb2)
![image](https://github.com/user-attachments/assets/3eefdbfa-feaf-4a44-8701-6ecca6666930)

2024-10-24 19:58 UTC, danieljordan-caci commented
> Also noticed in the description of the story that as a GSR, I should be able to leave an appeal decision if a serious incident was found. I am logged in as a GSR here and created a report with a serious incident but don't see the option to leave an appeal decision: ![image](https://private-user-images.githubusercontent.com/147537467/379918312-cab9cf31-6e5a-4513-966c-c301d4b09cb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4MDAxODQsIm5iZiI6MTcyOTc5OTg4NCwicGF0aCI6Ii8xNDc1Mzc0NjcvMzc5OTE4MzEyLWNhYjljZjMxLTZlNWEtNDUxMy05NjZjLWMzMDFkNGIwOWNiMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQxOTU4MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOWQ5OTRmMjBlMjU3ZTMzMmQ4OTEyZGM2NDA0ZWExMmE3ZmIwMTRkODRjZTM0NjIxNWRkZjBmM2I3NGM3YWQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.V0w895vcJa_UgxLDretas4RTvxMX9U33wpj0Rg9v7DY) ![image](https://private-user-images.githubusercontent.com/147537467/379918337-3eefdbfa-feaf-4a44-8701-6ecca6666930.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4MDAxODQsIm5iZiI6MTcyOTc5OTg4NCwicGF0aCI6Ii8xNDc1Mzc0NjcvMzc5OTE4MzM3LTNlZWZkYmZhLWZlYWYtNGE0NC04NzAxLTZlY2NhNjY2NjkzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQxOTU4MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YmU0NjNmMDc0ZWMxZTlkNWU4MTU2OGEwMzc1ZjllYWM1MWE1ZTZhOGZlYTQ5YjNiNmNmNjA5MGJiNmIzYzQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.eujKvogcuueI6pevEXE3iTpumdORPJQR09mqk34bSlI)

That will be in a [future BL item](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A986405)

2024-10-24 19:59 UTC, traskowskycaci commented
> > Also noticed in the description of the story that as a GSR, I should be able to leave an appeal decision if a serious incident was found. I am logged in as a GSR here and created a report with a serious incident but don't see the option to leave an appeal decision: ![image](https://private-user-images.githubusercontent.com/147537467/379918312-cab9cf31-6e5a-4513-966c-c301d4b09cb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4MDAxODQsIm5iZiI6MTcyOTc5OTg4NCwicGF0aCI6Ii8xNDc1Mzc0NjcvMzc5OTE4MzEyLWNhYjljZjMxLTZlNWEtNDUxMy05NjZjLWMzMDFkNGIwOWNiMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQxOTU4MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOWQ5OTRmMjBlMjU3ZTMzMmQ4OTEyZGM2NDA0ZWExMmE3ZmIwMTRkODRjZTM0NjIxNWRkZjBmM2I3NGM3YWQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.V0w895vcJa_UgxLDretas4RTvxMX9U33wpj0Rg9v7DY) ![image](https://private-user-images.githubusercontent.com/147537467/379918337-3eefdbfa-feaf-4a44-8701-6ecca6666930.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4MDAxODQsIm5iZiI6MTcyOTc5OTg4NCwicGF0aCI6Ii8xNDc1Mzc0NjcvMzc5OTE4MzM3LTNlZWZkYmZhLWZlYWYtNGE0NC04NzAxLTZlY2NhNjY2NjkzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQxOTU4MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YmU0NjNmMDc0ZWMxZTlkNWU4MTU2OGEwMzc1ZjllYWM1MWE1ZTZhOGZlYTQ5YjNiNmNmNjA5MGJiNmIzYzQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.eujKvogcuueI6pevEXE3iTpumdORPJQR09mqk34bSlI)
> 
> That will be in a [future BL item](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A986405)

Ah ok, I also see the one for Move History too. Thanks!

2024-10-24 19:59 UTC, danieljordan-caci commented
> This is a silly one - slight change in color contrast needed for the green button to meet ANDI compliance: ![image](https://private-user-images.githubusercontent.com/147537467/379917665-3673abb7-44c4-478e-8d41-016a6bf40e01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4MDAyNTksIm5iZiI6MTcyOTc5OTk1OSwicGF0aCI6Ii8xNDc1Mzc0NjcvMzc5OTE3NjY1LTM2NzNhYmI3LTQ0YzQtNDc4ZS04ZDQxLTAxNmE2YmY0MGUwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQxOTU5MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MjEzYzM4NjBhNGEzZGY4YmE4MGQxZjFkM2JmNmQ3NjMwMmY2OWRhZTc1YjVkMmQ3MDc3ZTdjMDU0ZTRmMWE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.u0GpXK2YjuRX1BwfHvknPXyh53H5piRjai7r7l8OQ3c)

This is silly. I'm taking this from the `colors.scss` file... I might just change it on that file to meet compliance.

2024-10-24 20:09 UTC, danieljordan-caci commented
> This is a silly one - slight change in color contrast needed for the green button to meet ANDI compliance: ![image](https://private-user-images.githubusercontent.com/147537467/379917665-3673abb7-44c4-478e-8d41-016a6bf40e01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4MDA4NzIsIm5iZiI6MTcyOTgwMDU3MiwicGF0aCI6Ii8xNDc1Mzc0NjcvMzc5OTE3NjY1LTM2NzNhYmI3LTQ0YzQtNDc4ZS04ZDQxLTAxNmE2YmY0MGUwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQyMDA5MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOTU2MGNiNTY2YTg4MGMyOWE5NjMwNTVjN2VjMTNiN2UxN2EzOTc5NWI1OTIzZWU1NzRlMmUwZDc4OWUxNGYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UP1qWINjpX_22rIBF_3Q2VUVwRVHO2Kx3jl5SdLoGYU)

Got it fixed [in this commit](https://github.com/transcom/mymove/pull/13994/commits/25d95d3f925147d46dbebc18553926ee098874a8)

2024-10-24 21:30 UTC, traskowskycaci commented on migrations/app/schema/20241004203140_update_addresses_is_oconus.up.sql
> -    ALTER COLUMN is_oconus SET NOT NULL;
Kind of a weird changed file to pop up. Know where it came from?

2024-10-24 21:39 UTC, traskowskycaci approved these changes
ANDI is happy! Lots of good tests in here too, nice work
![image](https://github.com/user-attachments/assets/b4d072fe-3cc2-4482-b422-1240b5507d83)

2024-10-24 21:40 UTC, danieljordan-caci commented on migrations/app/schema/20241004203140_update_addresses_is_oconus.up.sql
> -    ALTER COLUMN is_oconus SET NOT NULL;
Merged from `main`

2024-10-25 13:43 UTC, cameroncaci requested changes
Gorgeous UI, functions and meets AC. Just got some backend comments

2024-10-25 13:43 UTC, cameroncaci commented on pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
> +		AppealStatus:      ghcmessages.GSRAppealStatusType(gsrAppeal.AppealStatus),
`*gsrAppeal.IsSeriousIncidentAppeal` needs a nil check, can default to false if nil as I see `IsSeriousIncident` is not nillable

2024-10-25 13:43 UTC, cameroncaci commented on pkg/handlers/ghcapi/evaluation_report.go
> +				appCtx.Logger().Error(err.Error())
"appealr" typo at the end here

2024-10-25 13:43 UTC, cameroncaci commented on pkg/handlers/ghcapi/evaluation_report.go
> +				}
These HTTP returns are using `NewSubmitEvaluationReport` endpoint response swagger gens rather than `NewAddAppealToViolation` endpoint responses. Switching to `NewAddAppealToViolation` makes sure that our swagger definition supports said protocols and it also documents it as possible responses.

2024-10-25 13:43 UTC, cameroncaci commented on pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
> +	reportID := *handlers.FmtUUID(gsrAppeal.EvaluationReportID)
`gsrAppeal.ReportViolationID` needs to be nil wrapped. `gsrAppeal` is properly nil wrapped, but `ReportViolatonID` is a nested nil, will panic without a default

2024-10-25 13:43 UTC, cameroncaci commented on pkg/models/gsr_appeals_test.go
> +	// })
leftover comments from deleted test

2024-10-25 14:28 UTC, danieljordan-caci commented on pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
> +		AppealStatus:      ghcmessages.GSRAppealStatusType(gsrAppeal.AppealStatus),
addressed in [this commit](https://github.com/transcom/mymove/pull/13994/commits/ee32d71d30a532b21f281a2a25dcc23cd09701e8)

2024-10-25 14:28 UTC, danieljordan-caci commented on pkg/handlers/ghcapi/evaluation_report.go
> +				}
addressed in [this commit](https://github.com/transcom/mymove/pull/13994/commits/ee32d71d30a532b21f281a2a25dcc23cd09701e8)

2024-10-25 14:28 UTC, danieljordan-caci commented on pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
> +	reportID := *handlers.FmtUUID(gsrAppeal.EvaluationReportID)
addressed in [this commit](https://github.com/transcom/mymove/pull/13994/commits/ee32d71d30a532b21f281a2a25dcc23cd09701e8)

2024-10-25 14:28 UTC, danieljordan-caci commented on pkg/models/gsr_appeals_test.go
> +	// })
addressed in [this commit](https://github.com/transcom/mymove/pull/13994/commits/ee32d71d30a532b21f281a2a25dcc23cd09701e8)

2024-10-25 15:14 UTC, cameroncaci approved these changes
🚀

2024-10-25 15:27 UTC, merged