MAIN-B-21509
transcom/mymove pull request #13990
Opened 2024-10-23 19:10 UTC by msaki-caci

## [B-21509](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A1018861)

[Int b 21509 PR #1](https://github.com/transcom/mymove/pull/14057#event-15353050251)

[Int b 21509 PR #2](https://github.com/transcom/mymove/pull/14255)

[Int b 21509 PR #3](https://github.com/transcom/mymove/pull/14323#event-15513197174)

## Summary

We are adding the `ports` and `port_location` tables to the database along with adding the Port of Debarkation (POD) and Port of Embarkation (POE) columns to `mto_service_items`. 

Also added tests for `ports` and `port_location` and updated `mto_service_items` tests.

## Verification Steps for the Author

These are to be checked by the author.

- [x] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [x] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Run the migrations:  
   - I ran mine using `make db_dev_reset db_dev_migrate`, though the reset might not be necessary.
   - You could also run `make server_test`
2. Verify that the tables and new columns have been added.
   - I verified mine using DBeaver.

### Database

#### Any new migrations/schema changes:

- [x] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [x] Have been communicated to #g-database.

2024-12-02 16:55 UTC, loganwc approved these changes
Matches changes in both INT PRs

2024-12-02 17:04 UTC, msaki-caci commented
> https://github.com/transcom/mymove/pull/14255/files Here's another PR that includes some of these changes that went into INT

Good catch! I updated the description

2024-12-03 15:47 UTC, ryan-mchugh commented on migrations/app/schema/20241120221040_change_port_location_fk_to_correct_table.up.sql
> +--POE Location columns should reference PORT_LOCATIONS table
Any reason we can't just modify the original migration? It's added in this PR.

2024-12-03 15:48 UTC, ryan-mchugh commented on .dccache
Can you restore this file to main's? Reading through, it's a cache that references your machine

2024-12-03 15:49 UTC, ryan-mchugh requested changes
A couple comments to go through before my approval.

2024-12-03 16:06 UTC, loganwc commented on migrations/app/schema/20241120221040_change_port_location_fk_to_correct_table.up.sql
> +--POE Location columns should reference PORT_LOCATIONS table
old migrations don't get run again

2024-12-03 16:07 UTC, loganwc commented on migrations/app/schema/20241120221040_change_port_location_fk_to_correct_table.up.sql
> +--POE Location columns should reference PORT_LOCATIONS table
So it would end up diverging from integration if he were to modify the existing migration

2024-12-03 16:53 UTC, msaki-caci commented on .dccache
Deleted this file and have the PR open to get it removed from integrationTesting too here: https://github.com/transcom/mymove/pull/14323

2024-12-03 16:59 UTC, ryan-mchugh approved these changes

2024-12-04 14:37 UTC, deandreJones approved these changes

2024-12-10 17:10 UTC, deandreJones commented
What's this PR waiting on??

2024-12-10 17:42 UTC, merged

2024-12-10 17:42 UTC, deandreJones commented
> > What's this PR waiting on??
> 
> It should be good to go. @brianmanley-caci was gonna merge it was clear to merge into main

merged