B 20533 INT -  Full stack queue assignment work: TIO
transcom/mymove pull request #14030
Opened 2024-10-28 18:38 UTC by JonSpight

## [Agility ticket](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-20533)

## Summary
**When assigning a payment request to a TIO, assign all payment requests from that move to that TIO**
HQ users queues should be READ ONLY in ALL CASES

>[!IMPORTANT]
>Contains 20777 Code
>## Referencing PR
>[B-20777 TIO Queue Management. ](https://github.com/transcom/mymove/pull/13907)

##Test Steps

## Screenshots

2024-10-29 16:56 UTC, paulstonebraker approved these changes

2024-10-29 16:56 UTC, paulstonebraker commented on pkg/handlers/ghcapi/queues.go
> +			isHQrole := appCtx.Session().Roles[0].RoleType == roles.RoleTypeHQ
Can we update these to this `isHQrole := appCtx.Session().Roles.HasRole(roles.RoleTypeHQ)`

I believe that is what we want

2024-10-29 16:57 UTC, paulstonebraker requested changes

2024-10-29 16:57 UTC, paulstonebraker commented on pkg/handlers/ghcapi/queues.go
> +			isHQrole := appCtx.Session().Roles[0].RoleType == roles.RoleTypeHQ
Can we update these to this isHQrole := appCtx.Session().Roles.HasRole(roles.RoleTypeHQ)

I believe that is what we want

2024-10-29 17:49 UTC, JonSpight commented on src/pages/Office/MoveQueue/MoveQueue.jsx
> +            </div>
This was my initial thought - when I tested it out I got a weird error about nested ternary operations. so I stuck with this. But I'm not seeing that error anymore when I try now. 

Going to switch back over, I agree it is much easier to read.

2024-10-29 17:49 UTC, JonSpight commented on pkg/handlers/ghcapi/queues.go
> +			isHQrole := appCtx.Session().Roles[0].RoleType == roles.RoleTypeHQ
updated

2024-10-29 19:39 UTC, pambecker commented on pkg/handlers/ghcapi/queues.go
> +			queueMoves := payloads.QueueMoves(moves, officeUsers, nil, roles.RoleTypeTOO, officeUser, isSupervisor, isHQrole)
Isn't the roletype in the officeUser variable here?  just wondering if we can grab the isHQrole once we are in the QueueMoves function instead of passing so many variables here.

2024-10-29 21:28 UTC, pambecker approved these changes

2024-10-29 21:28 UTC, pambecker commented on pkg/handlers/ghcapi/queues.go
> +			queueMoves := payloads.QueueMoves(moves, officeUsers, nil, roles.RoleTypeTOO, officeUser, isSupervisor, isHQrole)
Disregard my note, the officeUser role isn't populated.  I don't want to hold the PR up.  Just something I noticed that the params are getting lengthy. I'm okay with it though.

2024-10-29 21:29 UTC, pambecker commented on pkg/handlers/ghcapi/queues.go
> +			queueMoves := payloads.QueueMoves(moves, officeUsers, nil, roles.RoleTypeTOO, officeUser, isSupervisor, isHQrole)
Disregard my note, the officeUser role isn't populated. I don't want to hold the PR up. Just something I noticed that the params are getting lengthy. I'm okay with it though.

2024-10-30 13:12 UTC, paulstonebraker approved these changes

2024-10-30 15:08 UTC, merged