B 21353 price escalations int
transcom/mymove pull request #14077
Opened 2024-10-31 18:59 UTC by TevinAdams

## [B-21353](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A1014422)
## [INT PR]()

## Summary

This story introduces adjustments to how the escalated price is calculated based on the contract year. There can be up to 8 total contract years for a contract. Here are the contract years in order:

1. Base Period Year 1
2. Base Period Year 2
3. Base Period Year 3
4. Option Period 1
5. Option Period 2
6. Award Term 1
7. Award Term 2
8. Option Period 3

Calculations needed to be adjusted to compound the escalation factors of each contract year. For example:
```
(A) Given a price for base period year 1
1. p = Round[p]
2. p = p * BasePeriodYear1EscalationFactor
3. p = Round[p]
4. p = p * quantity

(B) Given a price for base period year 2
1. p = Round[p]
2. p = p * BasePeriodYear1EscalationFactor
3. p = p * BasePeriodYear2EscalationFactor
4. p = Round[p]
5. p = p * quantity

(C) Given a price for base period year 3
1. p = Round[p]
2. p = p * BasePeriodYear1EscalationFactor
3. p = p * BasePeriodYear2EscalationFactor
4. p = p * BasePeriodYear3EscalationFactor
5. p = Round[p]
6. p = p * quantity

(E) Given a price for Option Period 1
1. p = Round[p]
2. p = p * BasePeriodYear1EscalationFactor
3. p = p * BasePeriodYear2EscalationFactor
4. p = p * BasePeriodYear3EscalationFactor
5. p = p * OptionPeriodYear1EscalationFactor
6. p = Round[p]
7. p = p * quantity

(F) Given a price for Option Period 2
1. p = Round[p]
2. p = p * BasePeriodYear1EscalationFactor
3. p = p * BasePeriodYear2EscalationFactor
4. p = p * BasePeriodYear3EscalationFactor
5. p = p * OptionPeriodYear1EscalationFactor
6. p = p * OptionPeriodYear2EscalationFactor
7. p = Round[p]
8. p = p * quantity

(G) Given a price for Award Term 1
1. p = Round[p]
2. p = p * BasePeriodYear1EscalationFactor
3. p = p * BasePeriodYear2EscalationFactor
4. p = p * BasePeriodYear3EscalationFactor
5. p = p * OptionPeriodYear1EscalationFactor
6. p = p * OptionPeriodYear2EscalationFactor
7. p = p * AwardTerm1EscalationFactor
8. p = Round[p]
9. p = p * quantity

(H) Given a price for Award Term 2
1. p = Round[p]
2. p = p * BasePeriodYear1EscalationFactor
3. p = p * BasePeriodYear2EscalationFactor
4. p = p * BasePeriodYear3EscalationFactor
5. p = p * OptionPeriodYear1EscalationFactor
6. p = p * OptionPeriodYear2EscalationFactor
7. p = p * AwardTerm1EscalationFactor
8. p = p * AwardTerm2EscalationFactor
9. p = Round[p]
10. p = p * quantity

(H) Given a price for Option Period 3
1. p = Round[p]
2. p = p * BasePeriodYear1EscalationFactor
3. p = p * BasePeriodYear2EscalationFactor
4. p = p * BasePeriodYear3EscalationFactor
5. p = p * OptionPeriodYear1EscalationFactor
6. p = p * OptionPeriodYear2EscalationFactor
7. p = p * AwardTerm1EscalationFactor
8. p = p * AwardTerm2EscalationFactor
9. p = p * OptionPeriodYear3EscalationFactor
10. p = Round[p]
11. p = p * quantity
```
  

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

You can control what contract year is used by setting the shipments requested pickup date pn shipment creation and setting it in between a start and end date for a specific contract year.

Database table re_contract_years:
![image](https://github.com/user-attachments/assets/8863a972-f550-4d04-b8d8-a6995402268e)

You can change the shipments Requested Pickup Date in the mto_shipments table, through the UI as a TOO by clicking "Edit Shipment" or as a Prime by clicking "Update Shipment"

1. Access MilMove as a customer
2. Create a shipment and use an HHG Shipment and set the Requested Pickup Date between  the start and end date of the re_contract_years that you want to test
3. After creating the shipment approve the shipment as a SC
4. Approve the shipment as a TOO
5. As a Prime add a destination sit service item to the shipment
6. As the TOO approve the service items for the shipment
7. As the prime create a payment request for a some service items within the shipment
8. Go to the move as a TIO and you can view the service items and their prices on the payment request
![image](https://github.com/user-attachments/assets/cba8db42-96ac-4a53-aae0-51c558398f11)
 #13130 

My Scenario:
Requested Pickup Address =  08/08/2025, which puts the contract year at Award Term 2
![image](https://github.com/user-attachments/assets/51d8e264-48c4-4c9a-9b15-6a39ec99445d)

Base price  in Cents = p = 650
Contract Year = Award Term 2
Final Weight = quantity = 3000

This case should follow steps (H)

1. 650 = Round[650]
2. 650 = 650 * (BasePeriodYear1EscalationFactor = 1)
3. 662.61 = 650 * (BasePeriodYear2EscalationFactor = 1.0.194)
4. 675.7959390000001 = 662.61 * (BasePeriodYear3EscalationFactor = 1.0199)
5. 690.0552333129 = 675.7959390000001 * (OptionPeriodYear1EscalationFactor = 1.0211)
6. 704.8224153057961 = 690.0552333129 * (OptionPeriodYear2EscalationFactor = 1.0214)
7. 718.7074168873203 = 704.8224153057961 * (AwardTerm1EscalationFactor = 1.0197)
8. 733.5127896751991 = 718.7074168873203 * (AwardTerm2EscalationFactor = 1.0206)
9. 734 = Round[733.5127896751991]
10. 22020 = 734 * ((3000/100) = 3000.ToCWTFFloat64())
22020 cents = $220.20
![image](https://github.com/user-attachments/assets/b8b45e01-041e-40dd-8f03-c5b83bcd1334)

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-11-06 18:09 UTC, danieljordan-caci approved these changes
LGTM - ran through some test cases and looks like this should've fixed it!

2024-11-07 15:40 UTC, cameroncaci commented on pkg/models/re_contract_year.go
> +	}
Still a bit behind on business logic with the contract years, do we want to support a default here?

2024-11-07 17:26 UTC, TevinAdams commented on pkg/models/re_contract_year.go
> +	}
There isn't any cases to reach the default so I removed it

2024-11-07 19:00 UTC, cameroncaci requested changes

2024-11-07 19:00 UTC, cameroncaci commented on pkg/models/re_contract_year.go
>  }
Replacing the default with an empty object still returns default 0 values. Since the object has non-nil attributes, they default to 0

2024-11-07 19:07 UTC, TevinAdams commented on pkg/models/re_contract_year.go
>  }
What are you suggesting to return? The method has to return this object. How I currently have it implemented works. How i have this currently implemented accounts for this case.

2024-11-07 20:24 UTC, cameroncaci commented on pkg/models/re_contract_year.go
>  }
Responded via slack

2024-11-07 22:20 UTC, TevinAdams commented on pkg/models/re_contract_year.go
>  }
@cameroncaci  Returning error in the case that no switch case is hit

2024-11-08 21:11 UTC, cameroncaci approved these changes
Meets AC - thank you for the descriptive PR. The ticket is pretty hard to understand, but it makes more sense in code. Not required, but what do you think about adding your PR description to a comment in the code? Not sure the best place, maybe func `GetExpectedEscalationPriceContractsCount`?

2024-11-08 21:53 UTC, merged