B 21566 int
transcom/mymove pull request #14072
Opened 2024-10-31 16:04 UTC by brianmanley-caci

## [Agility ticket](tbd)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-11-01 15:06 UTC, begrohmann approved these changes

2024-11-05 22:49 UTC, msaki-caci approved these changes

2024-11-06 16:36 UTC, danieljordan-caci requested changes
Couple of small changes - rest looks good.

2024-11-06 16:36 UTC, danieljordan-caci commented on pkg/models/re_service_item.go
> +func (g ReServiceItem) TableName() string {
Can you change this shortcut to something relevant instead of `g`?

2024-11-06 16:36 UTC, danieljordan-caci commented on pkg/models/re_service.go
> +	ServiceLocation *ServiceLocationType `db:"service_location" rw:"r"`
Can you add `ServiceLocation` above the `CreatedAt` line? Just to keep in line what we're doing in other models.

2024-11-06 16:36 UTC, danieljordan-caci commented on pkg/models/re_service.go
> +	ServiceLocation *ServiceLocationType `db:"service_location" rw:"r"`
Silly, I know.

2024-11-06 19:53 UTC, brianmanley-caci commented on pkg/models/re_service.go
> +	ServiceLocation *ServiceLocationType `db:"service_location" rw:"r"`
Hey I'm all for consistency. This is fixed now.

2024-11-06 19:54 UTC, brianmanley-caci commented on pkg/models/re_service_item.go
> +func (g ReServiceItem) TableName() string {
I updated this to `r`. It looked like that was consistent with some of the other parameter names.

2024-11-06 20:05 UTC, danieljordan-caci approved these changes

2024-11-06 21:12 UTC, merged