MAIN B-20618 office edit mobile home redo
transcom/mymove pull request #14073
Opened 2024-10-31 16:41 UTC by brooklyn-welsh

## [Agility ticket](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-20618)

## Original INT PR
#13650 

## Rebase INT PR
#13930 

## Most recent hotfix INT PR
#13969 

## Summary

This branch fixes an issue where the header for the shipment card was not visible for Mobile Home shipmens both in the approval preview window when a TOO would click "Approve Selected", and also on the "Move Task Order" tab after the shipment was approved.

### How to test

1. Access a move as a TOO, either one with a Mobile Home shipment or one without, you can just add one with the "Add shipment" button.
2. Check the shipment and click "Approve selected". Confirm that the "Mobile Home" title is visible on the shipment card inside the pop-up modal.
3. Once approved, go to the "Move Task Order" tab and confirm that the shipment is visible, and the title is visible at the top of the card.

2024-11-04 18:03 UTC, taeJungCaci requested changes
A few diff showing.

2024-11-04 18:03 UTC, taeJungCaci commented on src/components/Office/DefinitionLists/ShipmentInfoListSelector.jsx
> +    SHIPMENT_OPTIONS.BOAT_TOW_AWAY,
These were not touched in the INT PRs

2024-11-04 18:03 UTC, taeJungCaci commented on src/components/Office/ShipmentDisplay/ShipmentDisplay.jsx
> +    SHIPMENT_OPTIONS.BOAT_TOW_AWAY,
These were not touched in the INT PR.

2024-11-04 18:03 UTC, taeJungCaci commented on src/constants/shipments.js
> +  [SHIPMENT_TYPES.BOAT_TOW_AWAY]: 'Boat',
Same for these

2024-11-04 20:33 UTC, brooklyn-welsh commented on pkg/handlers/internalapi/moves_test.go
> +		suite.NotNil(updatedMove.SubmittedAt)
Yeah I added this because I think this is a flaky test that keeps getting a nil pointer error when trying to access "SubmittedAt", but turns out that it doesn't even stop the test if NotNil triggers a fail, so I'll take it out just to keep the PR clean

2024-11-04 20:41 UTC, brooklyn-welsh commented on pkg/services/move/move_router.go
> +				msg := "failure saving mobile home shipment when routing move submission"
So I'm a bit confused on this one, I separated them because it was failing tests because when the if's are combined, it hits "ValidateAndUpdate" for both MTOShipment[i].MobileHome and MTOSHipments[i].BoatShipment, and the BoatShipment check fails because if it's a mobile home then the reference to BoatShipment is nil.

Is this possibly related to the missing changes you're merging in main? Not sure how it passed in INT with the combined statement.

2024-11-04 20:50 UTC, taeJungCaci commented on pkg/services/move/move_router.go
> +				msg := "failure saving mobile home shipment when routing move submission"
In integrationBranch, it's combined but with if checks are there for each validateAndUpdate. 
![image](https://github.com/user-attachments/assets/40403efb-0bb8-4a6a-93b4-bf5452a1bbbd)

2024-11-04 20:51 UTC, taeJungCaci commented on pkg/services/move/move_router.go
> +				msg := "failure saving mobile home shipment when routing move submission"
Does this error out in INT as well??

2024-11-04 21:02 UTC, brooklyn-welsh commented on pkg/services/move/move_router.go
> +				msg := "failure saving mobile home shipment when routing move submission"
Oh I see somehow it was missing those nil checks in MAIN I think, so I went with separating them out this way. In that case I can just use the way that's currently in INT

2024-11-04 21:05 UTC, taeJungCaci commented on pkg/services/move/move_router.go
> +				msg := "failure saving mobile home shipment when routing move submission"
Yeah, I think your MAIN PR's been out of date for a while so there's been some conflicts that is out of order I bet

2024-11-05 20:16 UTC, WeatherfordAaron commented on src/components/Office/ShipmentDisplay/ShipmentDisplay.jsx
> +    SHIPMENT_OPTIONS.BOAT_TOW_AWAY,
```
    SHIPMENT_TYPES.BOAT_HAUL_AWAY,
    SHIPMENT_TYPES.BOAT_TOW_AWAY,
```
These 2 are already in MAIN. The one that is just BOAT is not currently there

2024-11-05 20:18 UTC, WeatherfordAaron commented on src/constants/shipments.js
> +  [SHIPMENT_TYPES.BOAT_TOW_AWAY]: 'Boat',
Currently in INT and MAIN are these lines so that change hasn't been made yet in INT?:
```
[SHIPMENT_TYPES.BOAT_HAUL_AWAY]: 'Boat haul-away',
[SHIPMENT_TYPES.BOAT_TOW_AWAY]: 'Boat tow-away',
```

2024-11-05 20:20 UTC, taeJungCaci commented on src/constants/shipments.js
> +  [SHIPMENT_TYPES.BOAT_TOW_AWAY]: 'Boat',
These are outdated and I think Brooklyn already made the changes. Resolving theses now.

2024-11-05 20:22 UTC, WeatherfordAaron requested changes
I did find some diffs. I'd recommend either doing a follow-up INT PR to address the proposed changes or revert some of this where possible

2024-11-05 20:42 UTC, taeJungCaci requested changes

2024-11-05 20:42 UTC, taeJungCaci commented on src/components/Office/ShipmentDisplay/ShipmentDisplay.jsx
> +                  <Tag className="usa-tag--red">cancelled</Tag>
Not sure where these came from

2024-11-05 20:44 UTC, taeJungCaci reviewed
There seems to be a few missing files from this PR https://github.com/transcom/mymove/pull/13930/files:
These don't like they are in latest Main either.

- playwright/tests/office/txo/tooFlowsMobileHome.spec.js
- src/components/Office/DefinitionLists/MobileHomeShipmentInfoList.jsx
- src/components/Office/RequestedShipments/ApprovedRequestedShipments.jsx
- src/components/Office/RequestedShipments/SubmittedRequestedShipments.jsx

2024-11-06 22:21 UTC, taeJungCaci requested changes

2024-11-06 22:21 UTC, taeJungCaci commented on pkg/testdatagen/scenario/shared.go
> +
This looks like a duplicate

2024-11-06 22:24 UTC, taeJungCaci commented on pkg/testdatagen/scenario/shared.go
> +
nvm disregard

2024-11-06 22:25 UTC, taeJungCaci approved these changes
LGTM

2024-11-06 22:33 UTC, taeJungCaci requested changes

2024-11-06 22:33 UTC, taeJungCaci commented on src/components/Office/RequestedShipments/ApprovedRequestedShipments.jsx
> +      <div className={styles.dropdownButton}>
Actually, I see some conflicts here with latest INT where @KonstanceH had made a reverted the change [here](https://github.com/transcom/mymove/commit/155a43023104d2f27a828dfcaacdab9f093fb3b2#diff-cecc14e57e16fff37c4bf37873c6d314a58213f6002f9cb659d08f6a96e280b4)? Might want to double check because while this might match your INT PR, it might not match the latest INT.

2024-11-06 22:34 UTC, taeJungCaci commented on src/components/Office/RequestedShipments/ApprovedRequestedShipments.jsx
> +      <div className={styles.dropdownButton}>
This Main PR is really outdated so we have to watch out for reverting any new changes that may have happened.

2024-11-07 16:41 UTC, taeJungCaci commented on src/components/Office/RequestedShipments/ApprovedRequestedShipments.jsx
Diff in this file is due to conflicts with other stories and this Main branch being out-of-date.

2024-11-07 16:41 UTC, taeJungCaci commented on src/components/Office/RequestedShipments/SubmittedRequestedShipments.jsx
Diff in this file is due to conflicts with other stories and this Main branch being out-of-date.

2024-11-07 20:57 UTC, taeJungCaci approved these changes
LGTM

2024-11-08 15:03 UTC, taeJungCaci commented
I think the server_test might be failing for one of boat/mobile tests. I thought it was flaky, but maybe not

2024-11-08 20:45 UTC, WeatherfordAaron approved these changes
lgtm

2024-11-08 20:46 UTC, merged