B 21168 int Zip/City/State Finder
transcom/mymove pull request #14105
Opened 2024-11-04 19:35 UTC by r-mettler

## [Agility ticket](tbd)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-11-05 16:20 UTC, deandreJones commented on migrations/app/schema/20240805234231_update_us_post_region_cities_state.up.sql
> +ALTER TABLE public.us_post_region_cities ALTER COLUMN state SET NOT NULL;
im curious what the reasoning for this is

2024-11-05 20:43 UTC, r-mettler commented on migrations/app/schema/20240805234231_update_us_post_region_cities_state.up.sql
> +ALTER TABLE public.us_post_region_cities ALTER COLUMN state SET NOT NULL;
This was left over code from when we first attempted to do the city finder tool last PI and were using the us_post_region_cities table. I pulled all that work into this branch and I forgot that I had this script in there. This script actually isn't needed anymore because of the changes we made in B-21442 so I can remove this script now.

2024-11-05 21:49 UTC, r-mettler commented on migrations/app/schema/20240805234231_update_us_post_region_cities_state.up.sql
> +ALTER TABLE public.us_post_region_cities ALTER COLUMN state SET NOT NULL;
Removed the file and the entry from the manifest file

2024-11-05 22:37 UTC, r-mettler commented on src/components/Office/ShipmentForm/ShipmentForm.jsx
> +        const handlePickupLocationChange = (value) => {
I don't like having multiple methods that do the same thing but just have a different object (pickup, secondaryPickup...). If anybody knows of a way to use the name of the variable stored as a string and reference the object using a string we could reduce this to just one handler.

2024-11-06 20:14 UTC, MInthavongsay approved these changes
Looks good

2024-11-11 20:49 UTC, antgmann reviewed
I haven't ran through the testing steps yet, but I've got a couple comments on the code after a quick read through.

2024-11-11 20:49 UTC, antgmann commented on pkg/handlers/ghcapi/addresses_test.go
> +	suite.Run("successful zip city lookup", func() {
For most handlers I've worked with, I've seen test cases hit successes and as many failure conditions as possible. Might be nice to have a test for the failures, too. Though I don't see as many of these in the internal and ghc handlers.

2024-11-11 20:49 UTC, antgmann commented on pkg/handlers/internalapi/addresses_test.go
> +	suite.Run("successful zip city lookup", func() {
Same as other handler comment

2024-11-11 20:49 UTC, antgmann commented on pkg/handlers/internalapi/internal/payloads/payload_to_model.go
> +		County:             *address.County,
While I'm here, I should probably mention that B-21423 (the task I was working last week) won't be changing optional counties any time soon, as we've since introduced more dependencies that are going to change 21423's work. We can talk more about this if you want the details.

2024-11-11 20:49 UTC, antgmann commented on pkg/services/address/address_lookup.go
> +func FindLocationsByZipCity(appCtx appcontext.AppContext, search string) (models.VLocations, error) {
I think this service should have an associated test. Let me know if you need any help with making one, I'd be happy to support.

2024-11-12 19:17 UTC, antgmann requested changes
Testing instructions went well as a customer, but I've run into an issue as an office user.

<img width="772" alt="image" src="https://github.com/user-attachments/assets/d9f88a28-d78f-48c3-b148-9dc913314e7c">

As a customer, I set my address to Clearwater, FL in Pinellas county. Upon changing this address as an office user to Lexington, KY the county updated to Fayette on the frontend, but did not update to Fayette on the backend. Continuing to update it to other locations, but it still just reads Pinellas on page load. 

If I'm able to help with resolving this just let me know!

2024-11-13 19:20 UTC, closed without merging