B-21432: Display Market Code and I-13434: Market Code Population Correction
transcom/mymove pull request #14101
Opened 2024-11-04 15:32 UTC by TevinAdams

## [B-21432](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-21432)
## [INT PR](https://github.com/transcom/mymove/pull/13940)

## [I-13434](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=I-13434)
## [INT PR](https://github.com/transcom/mymove/pull/14000)

## Summary

This PR has My work or B-21432 and Daniels work for I-13434

In this PR we are displaying the market code on the shipment card headers in MyMove and Office.

AND

An issue was found where NTS & NTSR shipment market codes weren't being updated on update. I took this opportunity to move the market code logic to the shipments model as well as add an additional helper function for PPM shipments that use a different model type.

All shipments should now be included in the model function and I addressed creation/update of all shipment types.

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

## MyMove
1. Access mymove as a customer
2. Create a move or use an existing one
3. Create one or many shipments of various types
4. You should see the market code next to the shipment type on the she shipment cards
![Screenshot 2024-10-16 at 9 07 37 AM](https://github.com/user-attachments/assets/3d21138b-2874-4a4a-8813-76cc883a83d7)
![image](https://github.com/user-attachments/assets/c63a2aea-a564-4391-9d73-b6815f3142af)

## Office
1. Access office as any role but Prime
2. Create a move or use an existing one
3. Create one or many shipments of various types
4. You should see the market code next to the shipment type on the she shipment cards

![image](https://github.com/user-attachments/assets/330c9a69-d7c7-4f6f-915a-c589f230050a)
![image](https://github.com/user-attachments/assets/0bf0e03a-096e-4eda-89ca-02f79acb2b99)

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

## 508 Checks
![image](https://github.com/user-attachments/assets/667f7384-b06f-4279-bcbe-7ddcdb4cb959)
![image](https://github.com/user-attachments/assets/616dc852-0a6c-441d-9f61-4f678b83fac7)
![image](https://github.com/user-attachments/assets/c4575779-ac9a-44cb-803e-f708fddcfb41)

2024-11-04 16:30 UTC, danieljordan-caci requested changes

2024-11-04 16:30 UTC, danieljordan-caci commented on src/components/Customer/Review/Summary/Summary.jsx
>      });
You're missing a change on line `344` in this file from the INT PR

![Screenshot 2024-11-04 at 10 23 37 AM](https://github.com/user-attachments/assets/72718dee-00fd-4603-8741-c899f1d298d4)

2024-11-04 16:30 UTC, danieljordan-caci commented on src/pages/MyMove/Profile/BackupAddress.test.jsx
>    });
Some differences in this file

`MAIN`
![Screenshot 2024-11-04 at 10 26 05 AM](https://github.com/user-attachments/assets/e3795d1c-d706-44d1-bad5-ecdec4ce07ed)

`INT`
![Screenshot 2024-11-04 at 10 26 24 AM](https://github.com/user-attachments/assets/0d90b32c-e589-4a73-bf32-05a265fbfb37)

2024-11-04 16:30 UTC, danieljordan-caci commented on src/pages/PrimeUI/CreateSITExtensionRequest/CreateSITExtensionRequest.test.jsx
> +      marketCode: 'd',
Seems to just be a formatting issue here, in INT it's all inline:
```
pickupAddress: { streetAddress1: '100 1st Avenue', city: 'New York', state: 'NY', postalCode: '10001' },
```
and here you have it lined out:
```
      pickupAddress: {
        streetAddress1: '100 1st Avenue',
        city: 'New York',
        state: 'NY',
        postalCode: '10001',
      },
```

2024-11-04 17:15 UTC, TevinAdams commented on src/components/Customer/Review/Summary/Summary.jsx
>      });
I know where this came from. That change should be in here now.

2024-11-04 17:17 UTC, TevinAdams commented on src/pages/PrimeUI/CreateSITExtensionRequest/CreateSITExtensionRequest.test.jsx
> +      marketCode: 'd',
Removed the formatting change.

2024-11-04 17:17 UTC, TevinAdams commented on src/pages/MyMove/Profile/BackupAddress.test.jsx
>    });
This change is coming from you PR https://github.com/transcom/mymove/pull/14000/files#diff-07f83427ecace3e2c2d28e1f16c27f1bd3c38a4efd07162b749c35f4f08bdcff

2024-11-04 17:46 UTC, danieljordan-caci approved these changes
All looks good now. Some minor differences in INT that seem to already be in `main`

2024-11-05 12:49 UTC, cameroncaci approved these changes

2024-11-05 14:13 UTC, danieljordan-caci commented
Conflicts - I can do Happo check once you've resolved.

2024-11-05 14:16 UTC, traskowskycaci approved these changes

2024-11-05 15:33 UTC, closed without merging