B 21542 int - DoD ID Does Not Populate in Services Counselor Queue
transcom/mymove pull request #14120
Opened 2024-11-06 01:02 UTC by JonSpight

## [Agility ticket](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-21542)

## Summary
When office users login to MM, their queue is not showing the DOD ID of the customer.

### How to test
1. Login as a customer and create a move.
2. Login as a  Services Counselor verify the DoD ID value is displayed in the counseling Queue
3. submit the move
4. Login as TOO,  verify the DoD ID value is displayed In the task order queue
5. approve the move and create a payment request
6. Login as a or TIO verify the DoD ID value is displayed In the payment request queues

## Screenshots

2024-11-06 18:14 UTC, danieljordan-caci requested changes

2024-11-06 18:14 UTC, danieljordan-caci commented on src/pages/Office/HeadquartersQueues/HeadquartersQueues.test.jsx
> +const SEARCH_OPTIONS = ['Move Code', 'edpi', 'Customer Name', 'Payment Request Number'];
Typo in `edpi` - should be `edipi`

2024-11-07 14:51 UTC, danieljordan-caci approved these changes
As the joker that did the BL item that jacked this up - thanks for the fix! LGTM.

2024-11-07 14:59 UTC, pambecker commented
I am not seeing the DoDID being populated in the TIO (Payment request queue).
And all 4 queues are breaking on sort and filter not working on any queues.

2024-11-07 15:01 UTC, danieljordan-caci commented
> I am not seeing the DoDID being populated in the TIO (Payment request queue). And all 4 queues are breaking on sort and filter not working on any queues.

Oh nice - let me re-review. Didn't think about checking the TIO queue.

2024-11-07 15:12 UTC, JonSpight commented
> > I am not seeing the DoDID being populated in the TIO (Payment request queue). And all 4 queues are breaking on sort and filter not working on any queues.
> 
> Oh nice - let me re-review. Didn't think about checking the TIO queue.

Good catch, I'll look into the filtering/sorting issue. But I do see the DoDID being populated for the TIO.

2024-11-07 15:25 UTC, loganwc approved these changes

2024-11-07 17:08 UTC, danieljordan-caci requested changes
Sort isn't working - getting the oops page

![Screenshot 2024-11-07 at 11 08 01 AM](https://github.com/user-attachments/assets/66b86c87-11fd-422a-8487-c5e4473e5dcd)

```
Operation queues.getServicesCounselingQueue failed: Error: Unprocessable Entity (422)
```

2024-11-07 17:21 UTC, danieljordan-caci commented
Is this missing value part of your work? Should be showing up in this list. There's a chance it's a small fix and would be convenient to wrap into this BL item.

![Screenshot 2024-11-07 at 11 20 56 AM](https://github.com/user-attachments/assets/889e53f0-7ab9-4dff-a46d-deed62371a89)

2024-11-07 17:27 UTC, danieljordan-caci commented
> Sort isn't working - getting the oops page
> 
> ![Screenshot 2024-11-07 at 11 08 01 AM](https://private-user-images.githubusercontent.com/136510600/384066333-66b86c87-11fd-422a-8487-c5e4473e5dcd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5OTk2MTAsIm5iZiI6MTczMDk5OTMxMCwicGF0aCI6Ii8xMzY1MTA2MDAvMzg0MDY2MzMzLTY2Yjg2Yzg3LTExZmQtNDIyYS04NDg3LWM1ZTQ0NzNlNWRjZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwN1QxNzA4MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kM2RhN2I0YzZmMmNiOGU2ZTAxZWY3MjhiZDg2MmJhNTQ5ZDgyYjQ1NzdmZTE5MzY2ODA4ODU0MTk2Nzg3YzJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4a8Ofx0CX7vbDgj-nhuAsDLwQw6PlGtFZYlWPC2tTac)
> 
> ```
> Operation queues.getServicesCounselingQueue failed: Error: Unprocessable Entity (422)
> ```

I would say so because this AC:
```
As a Services Counselor, TOO, or TIO working a record in my queue,
I want to see the DoD ID of the customer,
So that I am able to identify my customer. 
```

2024-11-07 17:32 UTC, pambecker commented
> Is this missing value part of your work? Should be showing up in this list. There's a chance it's a small fix and would be convenient to wrap into this BL item.
> 
> ![Screenshot 2024-11-07 at 11 20 56 AM](https://private-user-images.githubusercontent.com/136510600/384070917-889e53f0-7ab9-4dff-a46d-deed62371a89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwMDEwMDcsIm5iZiI6MTczMTAwMDcwNywicGF0aCI6Ii8xMzY1MTA2MDAvMzg0MDcwOTE3LTg4OWU1M2YwLTdhYjktNGRmZi1hNDZkLWRlZWQ2MjM3MWE4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwN1QxNzMxNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNGFhZjEwYTIxYTNhMTNhMjU2ZDllZWI4OGVmZTA3ZmQ2ZGJmYzdjODBmODA2NTIxOWIwMTg4OTY5ZjRkNmQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dfUiKl-yLAHKeWEqfstKX_f4MkuPnbPjDd1WZ0i3SOg)

good catch, I agree, this should be updated as well.

2024-11-07 20:13 UTC, JonSpight commented
> > Is this missing value part of your work? Should be showing up in this list. There's a chance it's a small fix and would be convenient to wrap into this BL item.
> > ![Screenshot 2024-11-07 at 11 20 56 AM](https://private-user-images.githubusercontent.com/136510600/384070917-889e53f0-7ab9-4dff-a46d-deed62371a89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwMDEwMDcsIm5iZiI6MTczMTAwMDcwNywicGF0aCI6Ii8xMzY1MTA2MDAvMzg0MDcwOTE3LTg4OWU1M2YwLTdhYjktNGRmZi1hNDZkLWRlZWQ2MjM3MWE4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwN1QxNzMxNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNGFhZjEwYTIxYTNhMTNhMjU2ZDllZWI4OGVmZTA3ZmQ2ZGJmYzdjODBmODA2NTIxOWIwMTg4OTY5ZjRkNmQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dfUiKl-yLAHKeWEqfstKX_f4MkuPnbPjDd1WZ0i3SOg)
> 
> good catch, I agree, this should be updated as well.

Made some changes, Updated the customer info page, The columns should work and are sortable/filterable, you can also search for a move using the DodID as well.

2024-11-07 22:21 UTC, pambecker approved these changes

2024-11-08 17:52 UTC, danieljordan-caci approved these changes
Very nice! LGTM.

2024-11-08 21:01 UTC, merged