modified code to always get the correct GBLOC
transcom/mymove pull request #14127
Opened 2024-11-07 14:15 UTC by WeatherfordAaron

## [Agility ticket](tbd)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-11-07 21:06 UTC, brooklyn-welsh requested changes
Tried to test by first creating a KKFA move, creating a shipment, and then switching origin location to Bloomingdale, IL 60108 (BGNC).

While the GBLOC did change for the move, the move is *not* routed to the BGNC counselor queue. It *is* however removed from the KKFA queue (or rather, just doesn't show up there in the first place).

Please test and confirm, but from my testing this needs to be changed to fill the 2nd part of the AC. 

P.S. Tested routing by creating a move that was BGNC with same origin from the beginning, and that move was routed to the BGNC queue correctly, which points to some logic missing in the GBLOC change code somewhere.

2024-11-08 23:53 UTC, WeatherfordAaron commented
> Tried to test by first creating a KKFA move, creating a shipment, and then switching origin location to Bloomingdale, IL 60108 (BGNC).
> 
> While the GBLOC did change for the move, the move is _not_ routed to the BGNC counselor queue. It _is_ however removed from the KKFA queue (or rather, just doesn't show up there in the first place).
> 
> Please test and confirm, but from my testing this needs to be changed to fill the 2nd part of the AC.
> 
> P.S. Tested routing by creating a move that was BGNC with same origin from the beginning, and that move was routed to the BGNC queue correctly, which points to some logic missing in the GBLOC change code somewhere.

I believe I figured this part out and updated the code so that it should route correctly upon updating as the customer or as the counselor

2024-11-11 16:21 UTC, WeatherfordAaron commented on pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
> +			originGBLOC = ghcmessages.GBLOC(OriginPostalCodeToGBLOC.GBLOC)
let me find it but there's a separate method that handles that already (IIRC).. I think someone just copied that to this when it doesn't work right which is why this ticket got created in the first place

2024-11-11 18:50 UTC, taeJungCaci commented on pkg/handlers/internalapi/orders.go
> +
As discussed - reverting changes in model_to_payload and adding tests for this would do the trick I think.

2024-11-11 20:16 UTC, WeatherfordAaron commented on pkg/handlers/internalapi/orders.go
> +
I'm going to add a playwright test since the test coverage isn't tripping

2024-11-11 20:23 UTC, taeJungCaci commented on pkg/handlers/internalapi/orders.go
> +
Shouldn't it be the backend test to cover the code you've added - and to help avoid the coverage issue in the future?

2024-11-11 21:49 UTC, WeatherfordAaron commented on pkg/handlers/internalapi/orders.go
> +
Yea I may need to add that too.. that to protect the code change.. but the playwright test would be more to protect the actual ask from the PO

2024-11-21 19:48 UTC, JamesHawks224 approved these changes
testing: success
code: lgtm

2024-11-25 17:27 UTC, taeJungCaci requested changes
Also I think the server_test might be failing and possibly not flaky

2024-11-25 17:27 UTC, taeJungCaci commented on pkg/models/move.go
> +
Not sure where these are getting used at.

2024-11-25 17:27 UTC, taeJungCaci commented on pkg/handlers/internalapi/orders_test.go
> -		}
Not sure if you meant to delete this test.

2024-11-25 19:12 UTC, WeatherfordAaron commented on pkg/handlers/internalapi/orders_test.go
> -		}
I did not intend this. I fixed it

2024-11-25 19:13 UTC, WeatherfordAaron commented
> Tried to test by first creating a KKFA move, creating a shipment, and then switching origin location to Bloomingdale, IL 60108 (BGNC).
> 
> While the GBLOC did change for the move, the move is _not_ routed to the BGNC counselor queue. It _is_ however removed from the KKFA queue (or rather, just doesn't show up there in the first place).
> 
> Please test and confirm, but from my testing this needs to be changed to fill the 2nd part of the AC.
> 
> P.S. Tested routing by creating a move that was BGNC with same origin from the beginning, and that move was routed to the BGNC queue correctly, which points to some logic missing in the GBLOC change code somewhere.

This should be resolved now

2024-11-25 19:13 UTC, WeatherfordAaron commented on pkg/models/move.go
> +
you are correct. Removing this

2024-11-25 19:15 UTC, WeatherfordAaron commented on pkg/models/move.go
> +
removed them

2024-11-25 19:17 UTC, taeJungCaci requested changes

2024-11-26 01:35 UTC, WeatherfordAaron commented on pkg/factory/duty_location_factory.go
> +
you are correct.. removed

2024-11-26 18:56 UTC, taeJungCaci commented on pkg/handlers/internalapi/orders.go
> +			newDutyLocationGBLOC, err := models.FetchGBLOCForPostalCode(appCtx.DB(), destinationDutyLocation.Address.PostalCode)
There seems to be a lot of duplicate code here that are already in `if payload.OriginDutyLocationID != "" {` case after line 393 - which are code for `originDutyLocation`. You can reuse code in there to fetch `originDutyLocation`. 

So bottom line - you can achieve the same result by adding the following code under line 401:

```
originGBLOC, originGBLOCerr := models.FetchGBLOCForPostalCode(appCtx.DB(), originDutyLocation.Address.PostalCode)
if originGBLOCerr != nil {
    return handlers.ResponseForError(appCtx.Logger(), originGBLOCerr), originGBLOCerr
}
order.OriginDutyLocationGBLOC = &originGBLOC.GBLOC
```

2024-11-26 19:15 UTC, taeJungCaci requested changes

2024-11-26 19:15 UTC, taeJungCaci commented on pkg/handlers/internalapi/orders_test.go
> +	fetchedGBLOC, err = fetchedOrder.GetOriginGBLOC(suite.DB())
Also this should be `fetchedGBLOC = *fetchedOrder.OriginDutyLocationGBLOC` to check if order gbloc was changed. You are currently fetching new Gbloc.

2024-12-06 17:00 UTC, danieljordan-caci requested changes

2024-12-06 17:00 UTC, danieljordan-caci commented on pkg/models/order.go
> +
Add tests please

2024-12-10 14:06 UTC, danieljordan-caci commented on pkg/models/order.go
> +
Gotcha. No worries!

2024-12-10 16:50 UTC, paulstonebraker requested changes
Just a small typo and you're good to go!

2024-12-10 16:50 UTC, paulstonebraker commented on pkg/models/order.go
> +		return "", errors.WithMessage(ErrInvalidOrderID, "You must created the order in the DB before getting the origin GBLOC.")
Typo here? I think you meant 'create' vs 'created' here and below on 338.

2024-12-13 16:19 UTC, paulstonebraker approved these changes

2024-12-13 17:37 UTC, merged