B 21375 int
transcom/mymove pull request #14137
Opened 2024-11-07 22:39 UTC by traskowskycaci

## [Agility ticket](tbd)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-11-11 16:06 UTC, danieljordan-caci requested changes
Some potential issues with your migration/model, but functionality works great!

2024-11-11 16:06 UTC, danieljordan-caci commented on pkg/models/ub_allowances.go
> +}
Looking at your migration - only `id` is `NOT NULL`, so the rest of these should be pointers.

2024-11-11 16:06 UTC, danieljordan-caci commented on pkg/models/ub_allowances.go
> +}
Also... Will this data ever change? If not, we should make it read only.

2024-11-11 16:09 UTC, traskowskycaci commented on src/components/Customer/OrdersInfoForm/OrdersInfoForm.test.jsx
> -jest.setTimeout(60000);
Hmm good question - merge conflict error, will add back in

2024-11-11 16:09 UTC, traskowskycaci commented on pkg/models/ub_allowances.go
> +}
You're right on both of those, will make those changes

2024-11-11 16:11 UTC, deandreJones commented on src/components/Customer/OrdersInfoForm/OrdersInfoForm.test.jsx
> -jest.setTimeout(60000);
she must be looking for a new flaky test

2024-11-11 16:12 UTC, danieljordan-caci commented on src/components/Customer/OrdersInfoForm/OrdersInfoForm.test.jsx
> -jest.setTimeout(60000);
It's a losing battle, so what's one more haha

2024-11-11 16:13 UTC, deandreJones commented on migrations/app/schema/20241031163018_create_ub_allowances_table.up.sql
> +    orders_type text,
since this can only be PERMANENT_CHANGE_OF_STATION or TEMPORARY_DUTY
should this be a constraint on this or enum

or if its never changing data- set the column as read only

2024-11-11 16:21 UTC, deandreJones commented on pkg/models/ghc_entitlements.go
> +// maria this is where you should add some conditonal checks in, maybe pass in all necessary values to check for
update comment to be a TODO

2024-11-11 16:23 UTC, traskowskycaci commented on pkg/models/ghc_entitlements.go
> +// maria this is where you should add some conditonal checks in, maybe pass in all necessary values to check for
ope thank you, I talk to myself in the comments sometimes

2024-11-11 16:24 UTC, danieljordan-caci commented on pkg/models/ghc_entitlements.go
> +// maria this is where you should add some conditonal checks in, maybe pass in all necessary values to check for
that is so funny - nice find Dre haha

2024-11-11 16:26 UTC, traskowskycaci commented on pkg/models/ghc_entitlements.go
> +// maria this is where you should add some conditonal checks in, maybe pass in all necessary values to check for
used to do it in all caps so at least I'm not yelling at myself anymore

2024-11-11 16:45 UTC, traskowskycaci commented
> Not sure if this is correct. The ubAllowance says 0 but dependents of over and under age is set > 0 and accompanied is set to true and false in the other. I was editing the dependents as a SC and then when I toggled Accompanied that's when I noticed the ubAllowance set to 0 no matter what. the allowance was initially according to the excel sheet.


What's the combo of branch, grade, orders type, depedents authorized, and whether it's accompanied? I'm not 100% following, we can huddle if you want

2024-11-11 20:45 UTC, TevinAdams commented
> > Not sure if this is correct. The ubAllowance says 0 but dependents of over and under age is set > 0 and accompanied is set to true and false in the other. I was editing the dependents as a SC and then when I toggled Accompanied that's when I noticed the ubAllowance set to 0 no matter what. the allowance was initially according to the excel sheet.
> 
> What's the combo of branch, grade, orders type, depedents authorized, and whether it's accompanied? I'm not 100% following, we can huddle if you want

Disregard. I spent some time today testing this and didnt find any issues.

2024-11-11 21:42 UTC, traskowskycaci commented on src/components/Customer/OrdersInfoForm/OrdersInfoForm.test.jsx
> -jest.setTimeout(60000);
Added back in [here](https://github.com/transcom/mymove/pull/14137/commits/7f25a06bf73cb116bdfea2de79ea863c6bb3ab5b)

2024-11-11 21:45 UTC, traskowskycaci commented on pkg/models/ub_allowances.go
> +}
Added [here](https://github.com/transcom/mymove/pull/14137/commits/683609ea89a528aeb860a310ba490c24477227c3)

- added `ub_allowances` to `scripts/db-truncate`
- made fields pointers in `pkg/models/ub_allowances.go`
- added rw:"r" to the pkg/models/ub_allowances.go so the model is read-only

2024-11-11 21:48 UTC, traskowskycaci commented on migrations/app/schema/20241031163018_create_ub_allowances_table.up.sql
> +    orders_type text,
Added [here] and ended up doing both check constraints and marking as read-only, not 100% necessary but doesn't hurt at all (https://github.com/transcom/mymove/pull/14137/commits/683609ea89a528aeb860a310ba490c24477227c3)

- Added in check constraints on `branch`, `grade`, `orders_type`, and `ub_weight_allowance` columns in migration
- added `ub_allowances` to `scripts/db-truncate`
- made fields pointers in `pkg/models/ub_allowances.go`
- added `rw:"r" `to `pkg/models/ub_allowances.go` so the model is read-only

2024-11-11 21:48 UTC, traskowskycaci commented on pkg/models/ghc_entitlements.go
> +// maria this is where you should add some conditonal checks in, maybe pass in all necessary values to check for
Fixed [here](https://github.com/transcom/mymove/pull/14137/commits/683609ea89a528aeb860a310ba490c24477227c3)

2024-11-11 22:09 UTC, traskowskycaci commented
> > > Not sure if this is correct. The ubAllowance says 0 but dependents of over and under age is set > 0 and accompanied is set to true and false in the other. I was editing the dependents as a SC and then when I toggled Accompanied that's when I noticed the ubAllowance set to 0 no matter what. the allowance was initially according to the excel sheet.
> > 
> > 
> > What's the combo of branch, grade, orders type, depedents authorized, and whether it's accompanied? I'm not 100% following, we can huddle if you want
> 
> Disregard. I spent some time today testing this and didnt find any issues.

Sounds good, let me know if you run into anything weird

2024-11-12 14:33 UTC, danieljordan-caci approved these changes
Thanks for the fixes - LGTM

2024-11-12 15:03 UTC, merged