INT-B-21568 Display UB Preapproved Service Items
transcom/mymove pull request #14181
Opened 2024-11-13 21:25 UTC by brianmanley-caci

## [Agility ticket](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A1024473&RoomContext=TeamRoom%3A1007470&concept=TeamRoom)

## Summary
This story is to display the Preapproved Service Items for International UB shipments on the TOO Approval screen. Currently the domestic preapproved services are hard coded in the page. However for international we are pulling the data from re_service_items and using the shipment type, market code, auto approved data to determined which service items should display to the user.

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Turn on ENABLE_ALASKA and UNACCOMPANIED_BAGGAGE feature flags.
2. Login as a Customer.
3. Create a Move.
4. Choose Alaska for the new duty location.
5. Add the orders document.
6. Add a new UB shipment to the move
7. Enter all required info.
8. Submit the move (note the move code).
9. Login as a Services Counselor.
10. Search for the move you created in the previous steps.
11. Enter the required orders info.
12. Submit the move.
13. Login as a TOO.
14. Search for the move.
15. On the move details page check the box by the UB shipment and then click the Approve Select button.
16. You should see the 4 applicable service items. Note International UB, International UB pack, International UB unpack will always show. For Conus to Oconus shipments, International POE Fuel Surcharge will display. For Oconus to Conus shipments, International POD Fuel Surcharge will display.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots
Conus to Oconus
![image](https://github.com/user-attachments/assets/4e7d3f46-e2ba-447f-b936-ac99a1edffd5)

Oconus to Conus
![image](https://github.com/user-attachments/assets/ff612463-d33e-436d-ab68-0bb6278d00e7)

2024-11-14 15:47 UTC, danieljordan-caci requested changes

2024-11-14 15:47 UTC, danieljordan-caci commented on pkg/services/service_item/service_item_fetcher.go
> +// NewPaymentRequestFetcher returns a new payment request fetcher
Make sure you adjust your copy/paste here in this comment

2024-11-14 15:47 UTC, danieljordan-caci commented on pkg/services/re_service_item.go
> +//go:generate mockery --name serviceItemListFetcher
Any time we add a new service object, we need to run `make mocks_generate` which should fix your failing generated code test in the build

2024-11-14 15:47 UTC, danieljordan-caci commented on pkg/handlers/ghcapi/re_service_items.go
> +// ShowAddressHandler returns an address
Copy/paste here in the comment

2024-11-14 15:47 UTC, danieljordan-caci commented on pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
> +}
Add tests for these plz

2024-11-14 15:47 UTC, danieljordan-caci commented on pkg/services/service_item/service_item_fetcher.go
> +	err := appCtx.DB().Eager("ReService").All(&serviceItems)
You need to return an error here before the return:
```
if err != nil
```

2024-11-14 15:47 UTC, danieljordan-caci commented on src/components/Office/ShipmentServiceItemsTable/ShipmentServiceItemsTable.jsx
> +      return serviceItem.serviceCode !== 'POEFSC';
Instead of hard coding service item strings here, can you add them to the `SERVICE_ITEM_CODES` variable in `src/constants/serviceItems.js` and import that?

2024-11-14 15:47 UTC, danieljordan-caci commented on src/components/Office/ShipmentServiceItemsTable/ShipmentServiceItemsTable.jsx
> +      return serviceItem.serviceCode !== 'PODFSC';
Instead of hard coding service item strings here, can you add them to the `SERVICE_ITEM_CODES` variable in `src/constants/serviceItems.js` and import that?

2024-11-15 19:35 UTC, ryan-mchugh commented
Changes look good! Waiting on feedback from comments to be addressed and will review again.

2024-11-18 20:04 UTC, brianmanley-caci commented on pkg/services/service_item/service_item_fetcher.go
> +// NewPaymentRequestFetcher returns a new payment request fetcher
Corrected name.

2024-11-18 20:04 UTC, brianmanley-caci commented on pkg/services/re_service_item.go
> +//go:generate mockery --name serviceItemListFetcher
I ran mocks_generate, and that did fix it. Thanks 🎉

2024-11-18 20:04 UTC, brianmanley-caci commented on pkg/handlers/ghcapi/re_service_items.go
> +// ShowAddressHandler returns an address
Fixed copy/paste issue.

2024-11-18 20:05 UTC, brianmanley-caci commented on pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
> +}
I added tests for both functions.

2024-11-18 20:05 UTC, brianmanley-caci commented on pkg/services/service_item/service_item_fetcher.go
> +	err := appCtx.DB().Eager("ReService").All(&serviceItems)
I added an error check.

2024-11-18 20:06 UTC, brianmanley-caci commented on src/components/Office/ShipmentServiceItemsTable/ShipmentServiceItemsTable.jsx
> +      return serviceItem.serviceCode !== 'PODFSC';
Added these to serviceItems.js and used those values here.

2024-11-18 20:06 UTC, brianmanley-caci commented on src/components/Office/ShipmentServiceItemsTable/ShipmentServiceItemsTable.jsx
> +  React.useEffect(() => {
Updated as suggested.

2024-11-18 20:07 UTC, brianmanley-caci commented on src/components/Office/ShipmentServiceItemsTable/ShipmentServiceItemsTable.jsx
> +  }, [marketCode, shipmentType, shipment]);
I updated this logic like you suggested, and it is still working well for me. Thanks for the suggestion.

2024-11-18 20:08 UTC, brianmanley-caci commented on src/components/Office/ShipmentApprovalPreview/ShipmentApprovalPreview.jsx
>                        />
It seemed cleaner to consolidate it into the single prop since the values all come from a shipment anyways.

2024-11-18 21:24 UTC, brianmanley-caci commented on src/components/Office/ShipmentServiceItemsTable/ShipmentServiceItemsTable.jsx
> +  const [filteredServiceItems, setFilteredServiceItems] = React.useState([]);
Updated as well.

2024-11-18 21:25 UTC, brianmanley-caci commented
> Changes look good! Waiting on feedback from comments to be addressed and will review again.

Ryan, all the suggested changes have been applied.

2024-11-19 13:47 UTC, danieljordan-caci approved these changes
Appreciate all of the changes! Tested again and looks great - send it!

2024-11-19 13:47 UTC, danieljordan-caci approved these changes

2024-11-19 15:45 UTC, ryan-mchugh approved these changes

2024-11-19 15:48 UTC, merged