20991 int - Add Counseling Office Column and Filtering to TIO Queue
transcom/mymove pull request #14185
Opened 2024-11-13 23:00 UTC by JonSpight

## [Agility ticket](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-20991)

## Summary
When a customer selects an origin duty location assigned to government counseling, then they will also be asked to select a counseling office within the same GBLOC. This field will be called "Counseling Office".

How to test
1. Login as a customer and create a 2 both with different counseling offices.
2. Login as a Services Counselor and submit the new move.
3 Login as TOO, approve both moves.
4. Crete multiple payment requests for each move
5. Login as TIO and filter the Counseling Office Task Order Queue for a move to verify filtering works.
6. Login as TIO and sort the Counseling Office Task Order Queue for a move to verify sort works.

## Screenshots

2024-11-14 02:15 UTC, loganwc approved these changes

2024-11-19 13:57 UTC, danieljordan-caci requested changes

2024-11-19 13:57 UTC, danieljordan-caci commented on pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
> +	})
Can you expand more on this test? Just seems that it's testing that it's not nil, but the test description is telling me it should be checking for the counseling office and assigned user values not being nil.

2024-11-19 13:57 UTC, danieljordan-caci commented on pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
> +	})
Same thing here - your test description and the actual test contradict each other. Just adding a little specificity would be nice. Thanks! Nice start!

2024-11-20 17:44 UTC, danieljordan-caci requested changes
Tests look good - just a little cleanup and you're G2G.

2024-11-20 17:44 UTC, danieljordan-caci commented on pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
> +		// paymentRequests := QueuePaymentRequests(&paymentRequests, officeUsers, officeUser, false, false)
left some commented out code in here

2024-11-20 17:44 UTC, danieljordan-caci commented on pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
> +		// paymentRequests := QueuePaymentRequests(&paymentRequests, officeUsers, officeUser, false, false)
left some commented out code in here

2024-11-20 17:44 UTC, danieljordan-caci commented on pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
> +		// PaymentRequests := QueuePaymentRequests(&paymentRequests, officeUsers, officeUser, true, false)
left some commented out code in here

2024-11-20 18:33 UTC, danieljordan-caci approved these changes

2024-11-21 14:33 UTC, merged