B21575-main3-add_order_types
transcom/mymove pull request #14206
Opened 2024-11-15 16:55 UTC by JamesHawks224

## [Agility ticket](tbd)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-12-10 21:01 UTC, WeatherfordAaron approved these changes
found no diff between INT and MAIN PRs. lgtm 👽

2024-12-11 14:27 UTC, taeJungCaci requested changes
looks like there are some linter fixes needed in couple of these files. Other than that - LGTM

2024-12-12 19:50 UTC, WeatherfordAaron commented
> looks like there are some linter fixes needed in couple of these files. Other than that - LGTM

Agreed. I think the Happo is showing something broken for the File Viewer or something too.. at least 1 part of this one may get resolved by updating the branch.

2024-12-12 21:57 UTC, JamesHawks224 commented
> looks like there are some linter fixes needed in couple of these files. Other than that - LGTM

I believe I've resolved those.  Please re-evaluate.

2024-12-12 22:03 UTC, taeJungCaci approved these changes

2024-12-12 22:30 UTC, WeatherfordAaron commented
Note: There is a current Happo fail on this PR. The fix is in another PR
https://github.com/transcom/mymove/pull/14303

This is from Agility Ticket [B-21373](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-21373) which has been merged into INT but is sitting in the Testing lane.

2024-12-13 13:25 UTC, antgmann commented
Please link all integration PRs that this main PR is covering. The only int pr linked covers just... wait. the commits between the linked PR and this PR don't match up?
[a6077ee](https://github.com/transcom/mymove/pull/14206/commits/a6077ee652d3c5b7ac598fda4e3fd0b5a73ec123) matches.
[ce85e0f](https://github.com/transcom/mymove/pull/14206/commits/ce85e0fcec14121d8e9f96e825578fcbf98013b0) and [b3d6905](https://github.com/transcom/mymove/pull/14211/commits/b3d69055d828f1aa6c68bc8cae19f679af64d008) don't, and none of them seem to match exactly again until commit [57f970d](https://github.com/transcom/mymove/pull/14206/commits/57f970d9f89b716bc15a023dfa0fd748b7478110). Am I misunderstanding something?

2024-12-13 13:53 UTC, antgmann requested changes
~~Okay I'm definitely confused on what's going on with this PR, there's some substantial differences between this one and the INT ones. Commits don't line up, and changes aren't the exact same either. 

I hate to throw a wrench into this, but it's important things match between environments. See review comments for more info and let me know if there's anything I can do to help get things back on track.~~

After some discussion, the only remaining issue is the following commit: [934f477](https://github.com/transcom/mymove/pull/14206/commits/934f4772ed0b7f4fb3309f5b99913a4605ead644)

2024-12-13 13:53 UTC, antgmann commented on src/components/Customer/EditOrdersForm/EditOrdersForm.jsx
>          const isRetirementOrSeparation = ['RETIREMENT', 'SEPARATION'].includes(values.orders_type);
Discrepancy 
<img width="1100" alt="image" src="https://github.com/user-attachments/assets/3c14bdce-279d-4227-a3a0-c44066d190b6" />

2024-12-13 13:53 UTC, antgmann commented on src/components/Customer/EditOrdersForm/EditOrdersForm.jsx
> +            setFieldValue('has_dependents', fieldValueHasDependents ? 'yes' : 'no');
Discrepancy
<img width="1100" alt="image" src="https://github.com/user-attachments/assets/4448e63d-4585-4c25-82a5-61e8b3765f4d" />

2024-12-13 13:53 UTC, antgmann commented on src/components/Customer/OrdersInfoForm/OrdersInfoForm.jsx
> +
Small spacing discrepancy 
![Uploading image.png…]()

2024-12-13 13:53 UTC, antgmann commented on src/components/Office/AddOrdersForm/AddOrdersForm.jsx
>  import { dropdownInputOptions } from 'utils/formatters';
This file is not edited on int pr https://github.com/transcom/mymove/pull/14211/files or https://github.com/transcom/mymove/pull/14378/files, or even https://github.com/transcom/mymove/pull/14164/files

2024-12-13 13:53 UTC, antgmann commented on migrations/app/schema/20241111221400_add_new_order_types.up.sql
> +-- adding order types to orders_type enum used in the orders table.
<img width="1059" alt="image" src="https://github.com/user-attachments/assets/a1956e2d-c8ef-4ca8-a67f-7d26e5b76694" />

Nothing to do with this migration, but this change to scripts/db-truncate also isn't present. Probably just the linter giving you a hard time?

2024-12-13 14:35 UTC, taeJungCaci commented
> Okay I'm definitely confused on what's going on with this PR, there's some substantial differences between this one and the INT ones. Commits don't line up, and changes aren't the exact same either.
> 
> I hate to throw a wrench into this, but it's important things match between environments. See review comments for more info and let me know if there's anything I can do to help get things back on track.

Trying to see if I can help, but I've created a new branch off the IntergrationBranch just now and merged in this branch into it to see. [This is the PR](https://github.com/transcom/mymove/pull/14395/files). I only see 1 diff which is the `src/components/Office/AddOrdersForm/AddOrdersForm.jsx` that was actually added after I approved this PR. Not sure why on that though and glad you caught that.

2024-12-13 15:00 UTC, antgmann commented
> Trying to see if I can help, but I've created a new branch off the IntergrationBranch just now and merged in this branch into it to see. [This is the PR](https://github.com/transcom/mymove/pull/14395/files). I only see 1 diff which is the `src/components/Office/AddOrdersForm/AddOrdersForm.jsx` that was actually added after I approved this PR. Not sure why on that though and glad you caught that.

This is very helpful as it lets us see that all of the discrepancies I listed above (aside from # 4, that's the additional commit added that you mention) are actually in integrationTesting, even if it's confusing how exactly that happened. Seems like maybe we've lost an int pr somewhere along the way? 

Either way, it implies that this should be a much more solid PR once [934f477](https://github.com/transcom/mymove/pull/14206/commits/934f4772ed0b7f4fb3309f5b99913a4605ead644) is added to integration first.

2024-12-13 15:22 UTC, JamesHawks224 commented
> > Trying to see if I can help, but I've created a new branch off the IntergrationBranch just now and merged in this branch into it to see. [This is the PR](https://github.com/transcom/mymove/pull/14395/files). I only see 1 diff which is the `src/components/Office/AddOrdersForm/AddOrdersForm.jsx` that was actually added after I approved this PR. Not sure why on that though and glad you caught that.
> 
> This is very helpful as it lets us see that all of the discrepancies I listed above (aside from # 4, that's the additional commit added that you mention) are actually in integrationTesting, even if it's confusing how exactly that happened. Seems like maybe we've lost an int pr somewhere along the way?
> 
> Either way, it implies that this should be a much more solid PR once [934f477](https://github.com/transcom/mymove/pull/14206/commits/934f4772ed0b7f4fb3309f5b99913a4605ead644) is added to integration first.

I think this will help clarify why things seem so odd.  
* my main branch: completed dev
* created my INT branch and merged my main branch into it
* B21374 was in INT.  It introduced changes in the same code of my changes.  Because B21374 was not in main yet, I could not make changes in my main and then merge to my int.  
* I made changes in the INT branch to get it to work with the B21374 changes. 
* When B21374 made it to main, I then updated my main (which was essentially the same changes in my INT).  
* Because I made changes to my main, I created another INT pr to apply that commit to INT per Daniel's instructions.

2024-12-13 15:36 UTC, taeJungCaci commented
> > Trying to see if I can help, but I've created a new branch off the IntergrationBranch just now and merged in this branch into it to see. [This is the PR](https://github.com/transcom/mymove/pull/14395/files). I only see 1 diff which is the `src/components/Office/AddOrdersForm/AddOrdersForm.jsx` that was actually added after I approved this PR. Not sure why on that though and glad you caught that.
> 
> This is very helpful as it lets us see that all of the discrepancies I listed above (aside from # 4, that's the additional commit added that you mention) are actually in integrationTesting, even if it's confusing how exactly that happened. Seems like maybe we've lost an int pr somewhere along the way?
> 
> Either way, it implies that this should be a much more solid PR once [934f477](https://github.com/transcom/mymove/pull/14206/commits/934f4772ed0b7f4fb3309f5b99913a4605ead644) is added to integration first.

Yes, or deleted from this PR because it doesn't look like it belong in this BL.

2024-12-13 15:41 UTC, antgmann commented
> I think this will help clarify why things seem so odd.
> 
> * my main branch: completed dev
> * created my INT branch and merged my main branch into it
> * B21374 was in INT.  It introduced changes in the same area as my changes.  Because B21374 was not in main yet, I could not make changes in my main and then merge to my int.
> * I made changes in the INT branch to get it to work with the B21374 changes.
> * When B21374 made it to main, I then updated my main with essentially the same changes in my INT.
> * Because I made changes to my main, I created another INT pr to apply that commit to INT per Daniel's instructions.

That'll do it. I'm sorry that you've had to deal with so many conflicts, especially after dev was completed. That makes organizing by dependency much more difficult and harder to follow.

In that case, never mind any of the other differences. It'd be an exercise in futility to track them all down if they're the result of conflicts like that. All of the changes match except for [934f477](https://github.com/transcom/mymove/pull/14206/commits/934f4772ed0b7f4fb3309f5b99913a4605ead644), then this will be g2g without that commit like @taeJungCaci suggests, or once the commit is pushed to main.

2024-12-13 16:23 UTC, taeJungCaci requested changes
Requesting change as mentioned above

2024-12-13 19:24 UTC, JamesHawks224 commented
> Requesting change as mentioned above



> > I think this will help clarify why things seem so odd.
> > 
> > * my main branch: completed dev
> > * created my INT branch and merged my main branch into it
> > * B21374 was in INT.  It introduced changes in the same area as my changes.  Because B21374 was not in main yet, I could not make changes in my main and then merge to my int.
> > * I made changes in the INT branch to get it to work with the B21374 changes.
> > * When B21374 made it to main, I then updated my main with essentially the same changes in my INT.
> > * Because I made changes to my main, I created another INT pr to apply that commit to INT per Daniel's instructions.
> 
> That'll do it. I'm sorry that you've had to deal with so many conflicts, especially after dev was completed. That makes organizing by dependency much more difficult and harder to follow.
> 
> In that case, never mind any of the other differences. It'd be an exercise in futility to track them all down if they're the result of conflicts like that. All of the changes match except for [934f477](https://github.com/transcom/mymove/pull/14206/commits/934f4772ed0b7f4fb3309f5b99913a4605ead644), then this will be g2g without that commit like @taeJungCaci suggests, or once the commit is pushed to main.

Removed the "934f477" commit.

2024-12-13 19:27 UTC, taeJungCaci approved these changes

2024-12-16 13:11 UTC, antgmann approved these changes

2024-12-16 15:37 UTC, merged