Initial UB Excess weight implementation
transcom/mymove pull request #14237
Opened 2024-11-19 21:48 UTC by TevinAdams

## [Agility ticket](tbd)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-11-20 14:02 UTC, cameroncaci commented
@TevinAdams I think your PR description and such forgot to save when you opened it up, marking back to draft

2024-11-20 14:03 UTC, cameroncaci commented
Please reopen the PR as ready once the description and test steps are refreshed

2024-11-20 15:00 UTC, TevinAdams commented
> @TevinAdams I think your PR description and such forgot to save when you opened it up, marking back to draft

@cameroncaci I was still in the process of building out the PR. Its done now.

2024-11-21 18:39 UTC, cameroncaci requested changes
Identified frontend issue & a missed code coverage spot.

Verified using actual and estimated via postman as well as prime sim too

https://github.com/user-attachments/assets/32445203-326e-46b7-bd98-e5c604a67e96

2024-11-21 18:39 UTC, cameroncaci commented on pkg/services/move/move_weights.go
> +		}
Missing code coverage here
![Screenshot 2024-11-21 at 1 37 57 PM](https://github.com/user-attachments/assets/d8886121-b897-417a-8097-a51859138802)

2024-11-21 18:50 UTC, danieljordan-caci commented
Are we sure this doesn't need to be its own allowance check? Did we verify that they are cool with it being shown in the move history as the same action of the TOTAL weight allowance being acknowledged? Without different columns in the db then we won't know if the UB allowance or the total weight allowance was in excess.

2024-11-21 19:11 UTC, danieljordan-caci commented
For example, if I have a UB shipment & an HHG shipment.

I updated the est allowance to trigger the UB excess weight and get the banner, but there's no way to know if it's the total weight allowance or the UB allowance

![Screenshot 2024-11-21 at 1 10 44 PM](https://github.com/user-attachments/assets/7323bc6b-a6a9-4b84-b55d-a04687200878)

2024-11-21 21:14 UTC, traskowskycaci commented
> For example, if I have a UB shipment & an HHG shipment.
> 
> I updated the est allowance to trigger the UB excess weight and get the banner, but there's no way to know if it's the total weight allowance or the UB allowance
> 
> ![Screenshot 2024-11-21 at 1 10 44 PM](https://private-user-images.githubusercontent.com/136510600/388656956-7323bc6b-a6a9-4b84-b55d-a04687200878.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyMjM3NDUsIm5iZiI6MTczMjIyMzQ0NSwicGF0aCI6Ii8xMzY1MTA2MDAvMzg4NjU2OTU2LTczMjNiYzZiLWE2YTktNGI4NC1iNTVkLWEwNDY4NzIwMDg3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMVQyMTEwNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Mjc3YjU0ZTEwN2Q5ODE5NDAzZWM5OGFkOGU1MDkwNzJiZjM0OGVhMDI5NWE1OTUyOGRjMjA2ZWQxZmE3YTFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rMj4XsRT4Zvp4DK6_bAhISVx8AgsIQyirAGx3jdhDlQ)

Had the same question - and do we need to show the UB allowance itself on this MTO page as part the excess weight? The office users can see it on the Move details page but they probably don't want to toggle back and forth

2024-11-21 21:28 UTC, danieljordan-caci commented
> > For example, if I have a UB shipment & an HHG shipment.
> > I updated the est allowance to trigger the UB excess weight and get the banner, but there's no way to know if it's the total weight allowance or the UB allowance
> > ![Screenshot 2024-11-21 at 1 10 44 PM](https://private-user-images.githubusercontent.com/136510600/388656956-7323bc6b-a6a9-4b84-b55d-a04687200878.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyMjM3NDUsIm5iZiI6MTczMjIyMzQ0NSwicGF0aCI6Ii8xMzY1MTA2MDAvMzg4NjU2OTU2LTczMjNiYzZiLWE2YTktNGI4NC1iNTVkLWEwNDY4NzIwMDg3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMVQyMTEwNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Mjc3YjU0ZTEwN2Q5ODE5NDAzZWM5OGFkOGU1MDkwNzJiZjM0OGVhMDI5NWE1OTUyOGRjMjA2ZWQxZmE3YTFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rMj4XsRT4Zvp4DK6_bAhISVx8AgsIQyirAGx3jdhDlQ)
> 
> Had the same question - and do we need to show the UB allowance itself on this MTO page as part the excess weight? The office users can see it on the Move details page but they probably don't want to toggle back and forth

It's pretty confusing to the user. I think we need to let them know "hey they're UB shipment allowance is in excess" so we can 1. be able to audit that and 2. the office user isn't confused that the weight allowance is actually fine, it's just the UB allowance that's at risk

2024-11-21 21:35 UTC, traskowskycaci commented
> > > For example, if I have a UB shipment & an HHG shipment.
> > > I updated the est allowance to trigger the UB excess weight and get the banner, but there's no way to know if it's the total weight allowance or the UB allowance
> > > ![Screenshot 2024-11-21 at 1 10 44 PM](https://private-user-images.githubusercontent.com/136510600/388656956-7323bc6b-a6a9-4b84-b55d-a04687200878.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyMjM3NDUsIm5iZiI6MTczMjIyMzQ0NSwicGF0aCI6Ii8xMzY1MTA2MDAvMzg4NjU2OTU2LTczMjNiYzZiLWE2YTktNGI4NC1iNTVkLWEwNDY4NzIwMDg3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMVQyMTEwNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Mjc3YjU0ZTEwN2Q5ODE5NDAzZWM5OGFkOGU1MDkwNzJiZjM0OGVhMDI5NWE1OTUyOGRjMjA2ZWQxZmE3YTFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rMj4XsRT4Zvp4DK6_bAhISVx8AgsIQyirAGx3jdhDlQ)
> > 
> > 
> > Had the same question - and do we need to show the UB allowance itself on this MTO page as part the excess weight? The office users can see it on the Move details page but they probably don't want to toggle back and forth
> 
> It's pretty confusing to the user. I think we need to let them know "hey they're UB shipment allowance is in excess" so we can 1. be able to audit that and 2. the office user isn't confused that the weight allowance is actually fine, it's just the UB allowance that's at risk

I also brought this up to Wendy earlier - so far, our work has been to calculate UB allowance in isolation, but it is _part_ of the total move allowance. As far as I know, we aren't doing any math to subtract the UB allowance from the TOTAL move weight allowance - something we need to think about and may work in the future. Making sure we distinctly show UB excess weight vs move excess weight will help clarify some of that math we might need to do.

2024-11-22 13:53 UTC, cameroncaci commented
@traskowskycaci @danieljordan-caci 

I voiced these same exact concerns and Dan wrote it off as okay (Verbally in the past) by just sharing the same exact flow. It would be better UX to separate them though. Since Dan is out we may have to have Terri write it off as okay in Agility

2024-11-22 14:37 UTC, TevinAdams commented
> > @traskowskycaci @danieljordan-caci
> > I voiced these same exact concerns and Dan wrote it off as okay (Verbally in the past) by just sharing the same exact flow. It would be better UX to separate them though. Since Dan is out we may have to have Terri write it off as okay in Agility
> 
> I agree. I do think we should see if she's available to meet for a second after standup and demo what we are talking about and how the ambiguity can be confusing to the end user. I can pull branch and have it to demo if she's available.

@danieljordan-caci, @cameroncaci , @traskowskycaci   I am okay with a seperate message for UB I was just following the the approach of all the other shipments that doesn't have a specific message. Seemed like the AC wanted to use what was already there.

2024-11-26 14:11 UTC, cameroncaci commented
@TevinAdams per that meeting we had, marking this PR back to draft until changes implemented

2024-12-03 18:37 UTC, closed without merging