Int b 21668 stored procs for ordering service items
transcom/mymove pull request #14230
Opened 2024-11-19 18:03 UTC by deandreJones

## [Agility ticket](tbd)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-11-19 19:56 UTC, danieljordan-caci requested changes
Just a static review, but will review again when changes are made. Also got some questions.

2024-11-19 19:56 UTC, danieljordan-caci commented on migrations/app/schema/20241119151019_stored_procs_for_ordering_service_items.up.sql
> +);
`CREATE TYPE IF NOT EXISTS`, right?

2024-11-19 19:56 UTC, danieljordan-caci commented on migrations/app/schema/20241119151019_stored_procs_for_ordering_service_items.up.sql
> +);
Is there a reason we don't just add all columns in `mto_service_items` now?

2024-11-19 19:56 UTC, danieljordan-caci commented on migrations/app/schema/20241119151019_stored_procs_for_ordering_service_items.up.sql
> +    estimate_weight int4,
`estimated_weight` instead of `estimate_weight`

2024-11-19 19:56 UTC, danieljordan-caci commented on migrations/app/schema/20241119151019_stored_procs_for_ordering_service_items.up.sql
> +);
For example, some of these accessorials will need `sit_destination_original_address_id` and all that other crap. If we just create a type with all fields in the service items table now, less work later.

2024-11-19 19:56 UTC, danieljordan-caci commented on pkg/services/mto_service_item/mto_service_item_creator.go
> +}*/
I see this is commented out. Any thoughts on moving this to the model instead? I know we like to have db logic in service objects, but if we move this to the model then you won't have to comment it out and we can re-use it elsewhere when needed.

2024-11-19 20:09 UTC, deandreJones commented on migrations/app/schema/20241119151019_stored_procs_for_ordering_service_items.up.sql
> +);
was actually working on adding all of them

2024-11-19 20:09 UTC, deandreJones commented on pkg/services/mto_service_item/mto_service_item_creator.go
> +}*/
I don't hate that idea

2024-11-19 20:11 UTC, danieljordan-caci commented on pkg/services/mto_service_item/mto_service_item_creator.go
> +}*/
Yeah it just makes sense to me for a use case like this

2024-11-19 21:08 UTC, deandreJones commented on migrations/app/schema/20241119151019_stored_procs_for_ordering_service_items.up.sql
> +);
had to get creative with the I`F NOT EXISTS` doesn't work like tables and columns

2024-11-19 21:08 UTC, deandreJones commented on migrations/app/schema/20241119151019_stored_procs_for_ordering_service_items.up.sql
> +    estimate_weight int4,
gave it the D

2024-11-19 21:09 UTC, deandreJones commented on pkg/services/mto_service_item/mto_service_item_creator.go
> +}*/
moved and added a test

2024-11-19 21:25 UTC, danieljordan-caci commented on migrations/app/schema/20241119151019_stored_procs_for_ordering_service_items.up.sql
> +$$;
Missing some columns - here's what I wrote up:
```
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mto_service_item_type') THEN
        CREATE TYPE mto_service_item_type AS (
            id uuid,
            move_id uuid,
            mto_shipment_id uuid,
            re_service_id uuid,
            created_at timestamptz,
            updated_at timestamptz,
            reason text,
            pickup_postal_code text,
            description text,
            status public.service_item_status,
            rejection_reason text,
            approved_at timestamp,
            rejected_at timestamp,
            sit_postal_code text,
            sit_entry_date date,
            sit_departure_date date,
            sit_destination_final_address_id uuid,
            sit_origin_hhg_original_address_id uuid,
            sit_origin_hhg_actual_address_id uuid,
            estimated_weight int4,
            actual_weight int4,
            sit_destination_original_address_id uuid,
            sit_customer_contacted date,
            sit_requested_delivery date,
            requested_approvals_requested_status bool,
            customer_expense bool,
            customer_expense_reason text,
            sit_delivery_miles int4,
            pricing_estimate int4,
            standalone_crate bool,
            locked_price_cents int4,
            service_location public.service_location_enum
        );
    END IF;
END
$$;
```

I'm not sure if we need the `created_at` or `updated_at` values, but I included those as well.

2024-11-19 21:32 UTC, deandreJones commented on migrations/app/schema/20241119151019_stored_procs_for_ordering_service_items.up.sql
> +$$;
can a type reference other types?

2024-11-19 21:40 UTC, brianmanley-caci commented on pkg/models/mto_shipments_test.go
> +		err := models.CreateApprovedServiceItemsForShipment(suite.DB(), &shipment)
I think the shipment will have to be persisted first, otherwise it's erroring for an invalid shipment.

2024-11-19 21:41 UTC, danieljordan-caci commented on migrations/app/schema/20241119151019_stored_procs_for_ordering_service_items.up.sql
> +$$;
I'm pretty sure yeah!

2024-11-19 21:57 UTC, brianmanley-caci commented on migrations/app/schema/20241119151019_stored_procs_for_ordering_service_items.up.sql
> +CREATE OR REPLACE PROCEDURE CreateAccessorialServiceItems (
To better match the other proc name should this be called CreateAccessorialServiceItems**ForShipment**?

2024-11-19 22:01 UTC, deandreJones commented on pkg/models/mto_shipments_test.go
> +		err := models.CreateApprovedServiceItemsForShipment(suite.DB(), &shipment)
thinking about how this proc works.. im not sure the test will work like this.. will have to use that factory crap

2024-11-19 22:07 UTC, danieljordan-caci commented on migrations/app/schema/20241119151019_stored_procs_for_ordering_service_items.up.sql
> +CREATE OR REPLACE PROCEDURE CreateAccessorialServiceItems (
I agree with this

2024-11-20 02:46 UTC, deandreJones commented on migrations/app/schema/20241119151019_stored_procs_for_ordering_service_items.up.sql
> +CREATE OR REPLACE PROCEDURE CreateAccessorialServiceItems (
no objections here

2024-11-20 15:30 UTC, deandreJones commented on migrations/app/schema/20241119151019_stored_procs_for_ordering_service_items.up.sql
> +-- stored proc that creates auto-approved shipments based off of a shipment id
yea Im not much of a comment person.. so I blame you for that one

2024-11-20 15:30 UTC, danieljordan-caci commented on migrations/app/schema/20241119151019_stored_procs_for_ordering_service_items.up.sql
> +-- stored proc that creates auto-approved shipments based off of a shipment id
guilty as charged

2024-11-20 16:13 UTC, danieljordan-caci commented on migrations/app/schema/20241119151019_stored_procs_for_ordering_service_items.up.sql
> +                    updated_at
We need to also update `approved_at` to fulfll UI checks
![Screenshot 2024-11-20 at 10 13 12 AM](https://github.com/user-attachments/assets/b4eb0418-206a-44fb-b1a9-d106e5ada6bf)

2024-11-20 17:03 UTC, danieljordan-caci commented on migrations/app/schema/20241119151019_stored_procs_for_ordering_service_items.up.sql
> +                )
gotta add `approved_at` here too

2024-11-20 17:03 UTC, danieljordan-caci commented on migrations/app/schema/20241119151019_stored_procs_for_ordering_service_items.up.sql
> +                updated_at
and here

2024-11-20 17:03 UTC, danieljordan-caci commented on migrations/app/schema/20241119151019_stored_procs_for_ordering_service_items.up.sql
> +                    NOW()
Need to add a `NOW()` to slap `approved_at` data in

2024-11-20 17:20 UTC, deandreJones commented on migrations/app/schema/20241119151019_stored_procs_for_ordering_service_items.up.sql
> +                NOW()
yea yea... 
have I mentioned how I hate this is in string

2024-11-20 17:21 UTC, danieljordan-caci commented on migrations/app/schema/20241119151019_stored_procs_for_ordering_service_items.up.sql
> +                NOW()
I believe in you!

2024-11-20 17:39 UTC, danieljordan-caci commented on migrations/app/schema/20241119151019_stored_procs_for_ordering_service_items.up.sql
> +            );
Looks like once you update to include `approved_at` here and also add a `NOW()` below you should be good for the other SIs
![Screenshot 2024-11-20 at 11 38 21 AM](https://github.com/user-attachments/assets/e95485fc-1280-4d5d-9f45-fa63f59f7480)

2024-11-20 17:50 UTC, danieljordan-caci reviewed
Any thoughts on validating when a shipment already has basic service items? I'm currently able to call it as many times as I want and have duplicate service items.

![Screenshot 2024-11-20 at 11 50 10 AM](https://github.com/user-attachments/assets/7da06b81-2f49-4b3b-ad2a-c20996474bbf)

2024-11-20 18:03 UTC, deandreJones commented
> Any thoughts on validating when a shipment already has basic service items? I'm currently able to call it as many times as I want and have duplicate service items.
> 
> ![Screenshot 2024-11-20 at 11 50 10 AM](https://private-user-images.githubusercontent.com/136510600/388208484-7da06b81-2f49-4b3b-ad2a-c20996474bbf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMjUzNDYsIm5iZiI6MTczMjEyNTA0NiwicGF0aCI6Ii8xMzY1MTA2MDAvMzg4MjA4NDg0LTdkYTA2YjgxLTJmNDktNGIzYi1hZDJhLWMyMDk5NjQ3NGJiZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMFQxNzUwNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MmVjMzQzYjQ5NjYwZDJhNDdmZWJkMzgyOWY5YzllMjM2MmU1NGM0M2NlMTNkMzE2ZTc3N2Q0N2RhOGYxYmM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JtXKpSt93gXhtFgxExn6WKS2XuCOFiABvzU-BW9MCl8)

thinking we should just check the shipment status.. since it would only be for newly approved - long as we call this right as the too approves it, what you think?

2024-11-20 18:21 UTC, danieljordan-caci commented on migrations/app/schema/20241119151019_stored_procs_for_ordering_service_items.up.sql
> +                    (item->>''standalone_crate'')::boolean
With the switch to using composite type over JSONB, need to change these from `->>` to `item.whatever`

2024-11-20 18:22 UTC, danieljordan-caci commented on migrations/app/schema/20241119151019_stored_procs_for_ordering_service_items.up.sql
> +              AND rs.code = (item->>''code'')::text
Need to change to `AND rs.id = (item.re_service_id)::text` I think

2024-11-20 18:27 UTC, deandreJones commented on migrations/app/schema/20241119151019_stored_procs_for_ordering_service_items.up.sql
> +              AND rs.code = (item->>''code'')::text
your saying don't match on the code- but rather the service item id?

2024-11-20 18:31 UTC, danieljordan-caci commented on migrations/app/schema/20241119151019_stored_procs_for_ordering_service_items.up.sql
> +              AND rs.code = (item->>''code'')::text
Well the type you are using doesn't contain the code, it contains the `re_service_id` instead

2024-11-20 19:30 UTC, deandreJones commented
@begrohmann you gonna add your 2cents to this?

2024-11-21 02:57 UTC, cameroncaci commented
I am behind here, why did we go the route of uniquely creating stored db procedures for accessorial service items rather than the existing service object layer that could be triggered on shipment type?
@deandreJones @danieljordan-caci

2024-11-21 18:22 UTC, danieljordan-caci commented
For those reviewing - here is kind of what I've been using to test `CreateAccessorialServiceItemsForShipment` using DBeaver
```
DO $$
DECLARE
    service_items mto_service_item_type[];
BEGIN
    service_items := ARRAY[
        ROW(
            NULL, -- id
            NULL, -- move_id
            NULL, -- mto_shipment_id
            'f2739142-97d1-40f3-a8f4-6a9daf390806', -- re_service_id
            NOW(), -- created_at
            NOW(), -- updated_at
            'Storage reason', -- reason
            '12345', -- pickup_postal_code
            'Storage service description', -- description
            'SUBMITTED', -- status (valid value from public.service_item_status)
            NULL, -- rejection_reason
            NULL, -- approved_at
            NULL, -- rejected_at
            '54321', -- sit_postal_code
            '2024-01-15', -- sit_entry_date
            '2024-02-01', -- sit_departure_date
            'eb4275bf-7826-412d-a49a-84d923438e53', -- sit_destination_final_address_id
            'eb4275bf-7826-412d-a49a-84d923438e53', -- sit_origin_hhg_original_address_id
            'eb4275bf-7826-412d-a49a-84d923438e53', -- sit_origin_hhg_actual_address_id
            500, -- estimated_weight
            450, -- actual_weight
            'eb4275bf-7826-412d-a49a-84d923438e53', -- sit_destination_original_address_id
            '2024-01-20', -- sit_customer_contacted
            '2024-01-25', -- sit_requested_delivery
            FALSE, -- requested_approvals_requested_status
            TRUE, -- customer_expense
            'Storage fee covered by customer', -- customer_expense_reason
            120, -- sit_delivery_miles
            NULL, -- pricing_estimate
            TRUE, -- standalone_crate
            NULL, -- locked_price_cents
            'O', -- service_location
            null, -- poe_location
            null -- pod_location
        )::mto_service_item_type,
        ROW(
            NULL, -- id
            NULL, -- move_id
            NULL, -- mto_shipment_id
            'ae84d292-f885-4138-86e2-b451855ffbf2', -- re_service_id
            NOW(), -- created_at
            NOW(), -- updated_at
            'Delivery delay reason', -- reason
            '54321', -- pickup_postal_code
            'Delivery service description', -- description
            'APPROVED', -- status (valid value from public.service_item_status)
            NULL, -- rejection_reason
            NULL, -- approved_at
            NULL, -- rejected_at
            '12345', -- sit_postal_code
            '2024-03-01', -- sit_entry_date
            '2024-03-15', -- sit_departure_date
            'eb4275bf-7826-412d-a49a-84d923438e53', -- sit_destination_final_address_id
            'eb4275bf-7826-412d-a49a-84d923438e53', -- sit_origin_hhg_original_address_id
            'eb4275bf-7826-412d-a49a-84d923438e53', -- sit_origin_hhg_actual_address_id
            600, -- estimated_weight
            580, -- actual_weight
            'eb4275bf-7826-412d-a49a-84d923438e53', -- sit_destination_original_address_id
            '2024-03-05', -- sit_customer_contacted
            '2024-03-10', -- sit_requested_delivery
            TRUE, -- requested_approvals_requested_status
            FALSE, -- customer_expense
            NULL, -- customer_expense_reason
            150, -- sit_delivery_miles
            NULL, -- pricing_estimate
            FALSE, -- standalone_crate
            NULL, -- locked_price_cents
            'D', -- service_location
            null, -- poe_location
            null -- pod_location
        )::mto_service_item_type
    ];

    -- Execute the procedure
    CALL CreateAccessorialServiceItemsForShipment(
        ':shipmentId',
        service_items
    );
END $$;
```

2024-11-21 18:41 UTC, deandreJones commented
> For those reviewing - here is kind of what I've been using to test `CreateAccessorialServiceItemsForShipment` using DBeaver
> 
> ```
> DO $$
> DECLARE
>     service_items mto_service_item_type[];
> BEGIN
>     service_items := ARRAY[
>         ROW(
>             NULL, -- id
>             NULL, -- move_id
>             NULL, -- mto_shipment_id
>             'f2739142-97d1-40f3-a8f4-6a9daf390806', -- re_service_id
>             NOW(), -- created_at
>             NOW(), -- updated_at
>             'Storage reason', -- reason
>             '12345', -- pickup_postal_code
>             'Storage service description', -- description
>             'SUBMITTED', -- status (valid value from public.service_item_status)
>             NULL, -- rejection_reason
>             NULL, -- approved_at
>             NULL, -- rejected_at
>             '54321', -- sit_postal_code
>             '2024-01-15', -- sit_entry_date
>             '2024-02-01', -- sit_departure_date
>             'eb4275bf-7826-412d-a49a-84d923438e53', -- sit_destination_final_address_id
>             'eb4275bf-7826-412d-a49a-84d923438e53', -- sit_origin_hhg_original_address_id
>             'eb4275bf-7826-412d-a49a-84d923438e53', -- sit_origin_hhg_actual_address_id
>             500, -- estimated_weight
>             450, -- actual_weight
>             'eb4275bf-7826-412d-a49a-84d923438e53', -- sit_destination_original_address_id
>             '2024-01-20', -- sit_customer_contacted
>             '2024-01-25', -- sit_requested_delivery
>             FALSE, -- requested_approvals_requested_status
>             TRUE, -- customer_expense
>             'Storage fee covered by customer', -- customer_expense_reason
>             120, -- sit_delivery_miles
>             NULL, -- pricing_estimate
>             TRUE, -- standalone_crate
>             NULL, -- locked_price_cents
>             'O', -- service_location
>             null, -- poe_location
>             null -- pod_location
>         )::mto_service_item_type,
>         ROW(
>             NULL, -- id
>             NULL, -- move_id
>             NULL, -- mto_shipment_id
>             'ae84d292-f885-4138-86e2-b451855ffbf2', -- re_service_id
>             NOW(), -- created_at
>             NOW(), -- updated_at
>             'Delivery delay reason', -- reason
>             '54321', -- pickup_postal_code
>             'Delivery service description', -- description
>             'APPROVED', -- status (valid value from public.service_item_status)
>             NULL, -- rejection_reason
>             NULL, -- approved_at
>             NULL, -- rejected_at
>             '12345', -- sit_postal_code
>             '2024-03-01', -- sit_entry_date
>             '2024-03-15', -- sit_departure_date
>             'eb4275bf-7826-412d-a49a-84d923438e53', -- sit_destination_final_address_id
>             'eb4275bf-7826-412d-a49a-84d923438e53', -- sit_origin_hhg_original_address_id
>             'eb4275bf-7826-412d-a49a-84d923438e53', -- sit_origin_hhg_actual_address_id
>             600, -- estimated_weight
>             580, -- actual_weight
>             'eb4275bf-7826-412d-a49a-84d923438e53', -- sit_destination_original_address_id
>             '2024-03-05', -- sit_customer_contacted
>             '2024-03-10', -- sit_requested_delivery
>             TRUE, -- requested_approvals_requested_status
>             FALSE, -- customer_expense
>             NULL, -- customer_expense_reason
>             150, -- sit_delivery_miles
>             NULL, -- pricing_estimate
>             FALSE, -- standalone_crate
>             NULL, -- locked_price_cents
>             'D', -- service_location
>             null, -- poe_location
>             null -- pod_location
>         )::mto_service_item_type
>     ];
> 
>     -- Execute the procedure
>     CALL CreateAccessorialServiceItemsForShipment(
>         ':shipmentId',
>         service_items
>     );
> END $$;
> ```

adding this to the how to test steps above

2024-11-21 18:52 UTC, cameroncaci commented on migrations/app/schema/20241119151019_stored_procs_for_ordering_service_items.up.sql
> +    s_status mto_shipment_status;
duplicate here make the migration fail

2024-11-21 18:53 UTC, cameroncaci commented on migrations/app/schema/20241119151019_stored_procs_for_ordering_service_items.up.sql
> +    s_status mto_shipment_status;
```suggestion
    s_status mto_shipment_status;
```
Duplicate needs removal

2024-11-21 20:15 UTC, cameroncaci requested changes
All working on this end, no risk of sql injection seen. Looking into more about commenting the funcs and procedures

2024-11-21 20:15 UTC, cameroncaci commented on migrations/app/schema/20241119151019_stored_procs_for_ordering_service_items.up.sql
> +    service_id UUID,
not snake_case 🐍

2024-11-21 20:15 UTC, cameroncaci commented on migrations/app/schema/20241119151019_stored_procs_for_ordering_service_items.up.sql
> +    IN shipment_id UUID
not snake_case 🐍

2024-11-21 20:15 UTC, cameroncaci commented on migrations/app/schema/20241119151019_stored_procs_for_ordering_service_items.up.sql
> +    IN shipment_id UUID,
not snake_case 🐍

2024-11-21 20:15 UTC, cameroncaci commented on pkg/models/mto_shipments.go
> +}
Missing test

2024-11-21 20:15 UTC, cameroncaci commented on migrations/app/schema/20241119151019_stored_procs_for_ordering_service_items.up.sql
> +END;
This always returns `false` no matter what, the exception is if it throws an exception on already exists. Should we instead refactor to return `EXISTS`? The loops will still function the same this way
```suggestion
BEGIN
    RETURN EXISTS (
    SELECT 1
    FROM mto_service_items
    WHERE re_service_id = service_id
    AND mto_shipment_id = shipment_id
    );
shipment_id;
END;
```

2024-11-21 20:15 UTC, cameroncaci commented on migrations/app/schema/20241119151019_stored_procs_for_ordering_service_items.up.sql
> +    service_id UUID,
Should we rename to be a more descriptive func name like `does_service_item_exist`?
```suggestion

CREATE OR REPLACE FUNCTION does_service_item_exist(
    service_id UUID,
```

2024-11-21 20:23 UTC, deandreJones commented on migrations/app/schema/20241119151019_stored_procs_for_ordering_service_items.up.sql
> +    service_id UUID,
to those sound the same.. but if its clearer to you that way.. ill update

2024-11-21 20:47 UTC, deandreJones commented on migrations/app/schema/20241119151019_stored_procs_for_ordering_service_items.up.sql
> +END;
actually that return false isnt supposed to be there-.. git mixed up an old version with the newest version.. i do still want the exception thrown tho

2024-11-21 20:48 UTC, deandreJones commented on migrations/app/schema/20241119151019_stored_procs_for_ordering_service_items.up.sql
> +    service_id UUID,
to those sound the same.. but if its clearer to you that way.. ill update

2024-11-22 13:49 UTC, cameroncaci commented on migrations/app/schema/20241119151019_stored_procs_for_ordering_service_items.up.sql
> +    service_id UUID,
It sounds like it if you already know what it does, but for unfamiliar devs they may not know exactly what the "check" condition is

2024-11-22 13:49 UTC, cameroncaci commented on migrations/app/schema/20241119151019_stored_procs_for_ordering_service_items.up.sql
> +END;
That works too

2024-11-22 16:35 UTC, deandreJones commented on migrations/app/schema/20241119151019_stored_procs_for_ordering_service_items.up.sql
> +    s_status mto_shipment_status;
fixed

2024-11-22 16:35 UTC, deandreJones commented on pkg/models/mto_shipments.go
> +}
added

2024-11-22 16:39 UTC, danieljordan-caci requested changes
Forgot - one last thing. Everything is working pretty good now.

Can you add the `mto_service_item_type` to the `mto_service_item` model?

2024-11-25 13:56 UTC, danieljordan-caci commented on pkg/models/mto_service_items.go
> +	ID                                uuid.UUID           `db_type:"id"`
should this be `db:id`?

2024-11-25 14:09 UTC, danieljordan-caci commented on pkg/models/mto_service_items.go
> +type MTOServiceItemType struct {
Also should we make these fields pointers @cameroncaci? My backend brain isn't 100% if this applies to db types.

2024-11-25 14:17 UTC, cameroncaci commented on pkg/models/mto_service_items.go
> +type MTOServiceItemType struct {
If nullable yes any nullable field should be a pointer so we don't end up returning "empty" default values of `0`, `''`, `false` etc etc

2024-11-25 14:38 UTC, cameroncaci commented on pkg/models/mto_service_items.go
> +}
Suggesting removing the json attribute of `db` since this is a typed parameter rather than a backend struct -> db ORM

2024-11-25 15:31 UTC, deandreJones commented on pkg/models/mto_service_items.go
> +}
golangci-lint doesn't like not having the struct tag key there- any suggestions?

```
pkg/models/mto_service_items.go:181:2: structtag: struct field tag `"id"` not compatible with reflect.StructTag.Get: bad syntax for struct tag key (govet)
	ID                                *uuid.UUID           `"id"`
	^
```

2024-11-25 16:23 UTC, danieljordan-caci commented on pkg/models/mto_service_items.go
> +		RejectedReason:                    m.RejectionReason,
`RejectionReason` instead of `RejectedReason`

2024-11-25 18:31 UTC, danieljordan-caci approved these changes
well alright then.

2024-11-25 20:17 UTC, deandreJones commented
@begrohmann need your eyes

2024-11-26 14:10 UTC, cameroncaci commented on pkg/models/mto_service_items.go
> +}
We can replace `db:"id"` with `json:"id"` and that'll fix it

2024-11-26 16:43 UTC, cameroncaci approved these changes

2024-11-26 16:48 UTC, merged

2024-11-26 19:32 UTC, begrohmann approved these changes