INT B-21414 - TOO update for international crate approval requests
transcom/mymove pull request #14274
Opened 2024-11-22 15:56 UTC by taeJungCaci

## [Agility ticket](tbd)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-11-22 18:06 UTC, WeatherfordAaron approved these changes
lgtm 👽 
the playwright tests are a nice touch

2024-11-22 21:16 UTC, JamesHawks224 commented on pkg/handlers/ghcapi/mto_service_items.go
> +					}
I don't see anything added to the test file for this file.  Is this code tested in other tests?  Or, is it even worth testing?  This is just an "ask", not a "must".

2024-11-22 21:25 UTC, JamesHawks224 requested changes
testing: success
code: looks good, did have a comment.

2024-11-23 00:12 UTC, taeJungCaci commented on pkg/handlers/ghcapi/mto_service_items.go
> +					}
I think I left this one out because all it is doing is loading other related data into the service item from the DB and not sure if it is worth testing. And I didn't see other codes in the tests either. But I can try to add some tests for it if you think it is important.

2024-11-23 01:12 UTC, taeJungCaci commented on pkg/handlers/ghcapi/mto_service_items.go
> +					}
Added test to `mto_service_items.test` as requested!

2024-11-25 15:13 UTC, brooklyn-welsh approved these changes
LGTM!

2024-11-25 15:45 UTC, JamesHawks224 approved these changes

2024-11-25 16:14 UTC, merged