using func for proc and added test
transcom/mymove pull request #14295
Opened 2024-11-29 13:08 UTC by KonstanceH

## [Agility ticket](tbd)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-11-29 17:28 UTC, WeatherfordAaron commented on pkg/services/mto_shipment/mto_shipment_updater.go
> +
the way this compares the first 3 digits of the postal codes (origin to destination) seems wonky. If this was something you actually added, I would suggest making a separate method that compares these which returns true or false for if it's a shorthaul or longhaul.. but since you aren't actually adding this functionality, I'd suggest leaving it as-is.

2024-11-29 17:40 UTC, WeatherfordAaron requested changes
1 change in mto_shipment_updater.go
1 change in shipment_approver.go

2024-11-29 17:40 UTC, WeatherfordAaron commented on pkg/services/mto_shipment/mto_shipment_updater.go
> -		}
If it's a HHG shipment and we check if first 3 of origin postal code and destination postal code are the same, it builds it out as if it's a shorthaul.. if it's not a shorthaul, it should be a longhaul, correct?
If so, I believe this other return needs to be added back in

2024-11-29 17:40 UTC, WeatherfordAaron commented on pkg/services/mto_shipment/shipment_approver.go
> +			return shipment, err
I'd recommend change the err return to
```
errors.WithMessage(err, "<specific error message here>")
```
Preferably something specific to this action that is attempting to be performed.. like "There was a problem creating the international shipment items for shipment ID "+shipment.ID)

The reason I think this is important is because it will help future devs know exactly where the error is occuring in instances where a line,char is not provided

2024-11-29 17:49 UTC, WeatherfordAaron commented on pkg/services/mto_shipment/mto_shipment_updater.go
> +
follow-up to this:
Using the first 3 digits of postal code is as designed. No change necessary to this process at this time.

2024-11-29 17:52 UTC, KonstanceH commented on pkg/services/mto_shipment/shipment_approver.go
> +			return shipment, err
If there's an error here the message will be this currently from the `CreateApprovedServiceItemsForShipment ` call: 
"error creating approved service items: %w" the placeholdershould be an even more specific reason from the db error.

2024-11-29 17:58 UTC, KonstanceH commented on pkg/services/mto_shipment/mto_shipment_updater.go
> -		}
this applies for domestic HHG shipping but the criteria/services won't align for international HHG

2024-11-29 18:04 UTC, WeatherfordAaron commented on pkg/services/mto_shipment/mto_shipment_updater.go
> -		}
that's good enough for me.

2024-11-29 18:04 UTC, WeatherfordAaron commented on pkg/services/mto_shipment/shipment_approver.go
> +			return shipment, err
honestly, that's good enough for me. ty

2024-11-29 18:04 UTC, WeatherfordAaron approved these changes
lgtm 👽

2024-11-29 18:53 UTC, brooklyn-welsh approved these changes
Tested and worked for me, looks like comments were addressed. LGTM ✅

2024-12-03 16:26 UTC, deandreJones approved these changes

2024-12-03 17:32 UTC, merged