INT-B-21505 prime port update
transcom/mymove pull request #14309
Opened 2024-12-02 16:52 UTC by brianmanley-caci

## [Agility ticket](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A1018852&RoomContext=TeamRoom%3A1007470&concept=TeamRoom)

## Summary
This story is to allow the prime user to update the port location for a move with either a POEFSC or PODFSC service item.

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test
Note: the functionality for ordering POEFSC and PODFSC service items does not yet exist. Therefore in order to test you will need to manually create either a POEFSC or PODFSC service item for a shipment.

1. Create an INTL UB shipment as a customer (CONUS -> AK or AK -> CONUS)
2. Manually create the mto_service_items table for the shipment: `
INSERT INTO mto_service_items (
					id,
                    mto_shipment_id,
                    move_id,
                    re_service_id,
                    status,
                    created_at,
                    updated_at,
                    approved_at
                )
                VALUES (
                uuid_generate_v4(),
                    '8eeba537-bb40-4f58-a534-74ea9ff64590',
                    '813b7a43-2e3f-42f3-8c4e-eca95390d5ca',
                    '388115e8-abe9-441d-96cf-a39f24baa0a3',
                    'APPROVED'::service_item_status,
                    NOW(),
                    NOW(),
                    NOW()
                );
`
3. In the prime v3 api, call getMoveTaskOrder using the move_id for the service item you created in step 2. You will need the etag for the newly created service item for the next step.
4. In the prime v1 api, call updateMTOServiceItem using a payload like this (adjust for you specific service item ID): `
{
  "id": "40b7e71a-6b03-4413-8601-dea694253ee3",
  "modelType": "UpdateMTOServiceItemInternationalPortFSC",
  "portCode": "PDX",
  "reServiceCode": "PODFSC"
}
`
5. Verify that you receive a 200 response like this: `{
  "reServiceCode": "PODFSC",
  "eTag": "MjAyNC0xMi0wMlQxNjo0MjoxNi42NjUwNDla",
  "id": "40b7e71a-6b03-4413-8601-dea694253ee3",
  "modelType": "MTOServiceItemBasic",
  "moveTaskOrderID": "813b7a43-2e3f-42f3-8c4e-eca95390d5ca",
  "mtoShipmentID": "8eeba537-bb40-4f58-a534-74ea9ff64590",
  "reServiceName": "International POD Fuel Surcharge",
  "status": "APPROVED"
}`
6. In the prime v3 api, call getMoveTaskOrder using the same move_id as before.
7. Verify that the updated shipment now has the portOfDebarkation (or portOfEmbarkation) object as part of the response like this: 
`"portOfDebarkation": {
        "city": "PORTLAND",
        "country": "UNITED STATES",
        "county": "MULTNOMAH",
        "id": "b6e94f5b-33c0-43f3-b960-7c7b2a4ee5fc",
        "portCode": "PDX",
        "portName": "PORTLAND INTL",
        "portType": "A",
        "state": "OREGON",
        "zip": "97220"
      },`

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-12-02 20:02 UTC, danieljordan-caci requested changes
Static review for now

2024-12-02 20:02 UTC, danieljordan-caci commented on swagger-def/definitions/Port.yaml
> +description: A port
Can you add just a liiiiiittle bit more to this description?

2024-12-02 20:02 UTC, danieljordan-caci commented on swagger-def/definitions/Port.yaml
> +    example: 'Anchorage'
Please use another example to avoid having the same `Anchorage` example for different fields

2024-12-02 20:02 UTC, danieljordan-caci commented on swagger-def/definitions/Port.yaml
> +    example: 'Anchorage'
Please use another example to avoid having the same `Anchorage` example for different fields

2024-12-02 20:11 UTC, brianmanley-caci commented on pkg/handlers/primeapiv3/payloads/model_to_payload.go
> +}
I can rename the function. I separated it out to try to avoid duplicating the logic if that makes sense.

2024-12-02 20:12 UTC, brianmanley-caci commented on pkg/handlers/primeapiv3/payloads/model_to_payload.go
> +}
The function is returning a port based off the port location, so would it make more sense to name the function Port?

2024-12-02 20:15 UTC, danieljordan-caci commented on pkg/handlers/primeapiv3/payloads/model_to_payload.go
> +}
Oh gotcha! Missed. Then yes! I think that'd be good!

2024-12-02 20:27 UTC, brianmanley-caci commented on pkg/services/mto_service_item/mto_service_item_updater_test.go
> +	// Test failure Prime validation for Port of Embarkation
Good catch. Copy paste error.

2024-12-02 20:27 UTC, brianmanley-caci commented on pkg/services/mto_service_item/mto_service_item_updater_test.go
> +	// Test failure Prime validation for Port of Debarkation
Good catch. Copy paste error.

2024-12-02 20:31 UTC, brianmanley-caci commented on swagger-def/definitions/Port.yaml
> +description: A port
Reasonable ask.

2024-12-02 20:36 UTC, brianmanley-caci commented on pkg/services/mto_service_item/mto_service_item_updater_test.go
> +	// Test failure Prime validation for Port of Embarkation
Fixed.

2024-12-02 20:36 UTC, brianmanley-caci commented on pkg/services/mto_service_item/mto_service_item_updater_test.go
> +	// Test failure Prime validation for Port of Debarkation
Fixed.

2024-12-02 20:37 UTC, brianmanley-caci commented on swagger-def/definitions/Port.yaml
> +    example: 'Anchorage'
Updated to example with greater variance.

2024-12-02 20:37 UTC, brianmanley-caci commented on swagger-def/definitions/Port.yaml
> +    example: 'Anchorage'
Updated to example with greater variance.

2024-12-03 22:01 UTC, brianmanley-caci commented on pkg/handlers/primeapiv3/payloads/model_to_payload_test.go
> +	}
I created a port and port location factory. Let me know if it is any better?

2024-12-03 22:03 UTC, brianmanley-caci commented on pkg/handlers/primeapiv3/payloads/model_to_payload_test.go
> +	mtoShipmentId := uuid.Must(uuid.NewV4())
Removed uuid generator and used factories.

2024-12-03 22:05 UTC, brianmanley-caci commented on pkg/handlers/primeapiv3/payloads/model_to_payload_test.go
> +	}
refactored to use factories.

2024-12-03 22:09 UTC, brianmanley-caci commented
@danieljordan-caci ready for further scrutiny.

2024-12-04 14:26 UTC, danieljordan-caci requested changes
Closer! Just a few more changes pleaseeeee

2024-12-04 14:26 UTC, danieljordan-caci commented on pkg/factory/port_location_factory.go
> +	}
So for this part, since we want to return an ACTUAL row from `port_locations`, instead of returning default data you should instead fetch the default one since the user isn't specifying which one. Looking better! 

```
    var portLocation models.PortLocation
	if db != nil {
		err := db.EagerPreload("Port", "City", "Country", "UsPostRegionCity.UsPostRegion.State").Where("is_active = TRUE").InnerJoin("ports p", "port_id = p.id").Where("p.port_code = $1", port.PortCode).First(&portLocation)
		if err == nil {
			return portLocation
		}
	}

	// search for the default port if one is not provided
	defaultPortCode := "PDX"
	err := db.EagerPreload("Port", "City", "Country", "UsPostRegionCity.UsPostRegion.State").Where("is_active = TRUE").InnerJoin("ports p", "port_id = p.id").Where("p.port_code = $1", port.PortCode).First(&defaultPortCode)
	if err != nil && err != sql.ErrNoRows {
		log.Panic(err)
	} else {
		return portLocation
	}
```

2024-12-04 14:26 UTC, danieljordan-caci commented on pkg/factory/mto_service_item_factory.go
> +
Can you add/update a test in `mto_service_item_factory_test.go` to reflect these changes?

2024-12-04 14:26 UTC, danieljordan-caci commented on pkg/factory/port_factory.go
> +	}
So same thing here as the port locations factory - fetch a default port instead of returning dummy data.

2024-12-04 14:26 UTC, danieljordan-caci commented on pkg/handlers/primeapi/payloads/payload_to_model_test.go
> +		model, _ := MTOServiceItemModelFromUpdate(mtoServiceItemID, &updateMTOServiceInternationalPortFsc)
Check for no error:
```
suite.NoError(err)
```

2024-12-04 14:26 UTC, danieljordan-caci commented on pkg/handlers/primeapi/payloads/payload_to_model_test.go
> +		model, _ := MTOServiceItemModelFromUpdate(mtoServiceItemID, &updateMTOServiceInternationalPortFsc)
Check for no error:
```
suite.NoError(err)
```

2024-12-04 14:26 UTC, danieljordan-caci commented on swagger-def/definitions/Port.yaml
> +    description: 'Port type A (Air), B(Border Crossing), S (Sea)'
Add a space after `B` here to keep up with what you're doing for `A` and `S`
```
'Port type A (Air), B (Border Crossing), S (Sea)'
```

2024-12-04 20:53 UTC, brianmanley-caci commented on pkg/factory/port_location_factory.go
> +	}
Updated to pull default record from the DB.

2024-12-04 20:53 UTC, brianmanley-caci commented on pkg/factory/mto_service_item_factory.go
> +
Added a test to validate the ports in this function.

2024-12-04 20:54 UTC, brianmanley-caci commented on pkg/factory/port_factory.go
> +	}
Grabbing default from the db.

2024-12-04 20:54 UTC, brianmanley-caci commented on pkg/handlers/primeapi/payloads/payload_to_model_test.go
> +		model, _ := MTOServiceItemModelFromUpdate(mtoServiceItemID, &updateMTOServiceInternationalPortFsc)
validated errors is empty.

2024-12-04 20:54 UTC, brianmanley-caci commented on pkg/handlers/primeapi/payloads/payload_to_model_test.go
> +		model, _ := MTOServiceItemModelFromUpdate(mtoServiceItemID, &updateMTOServiceInternationalPortFsc)
validated errors is empty

2024-12-04 20:54 UTC, brianmanley-caci commented on swagger-def/definitions/Port.yaml
> +    description: 'Port type A (Air), B(Border Crossing), S (Sea)'
added space for consistency.

2024-12-05 16:19 UTC, WeatherfordAaron submitted a review, later dismissed

2024-12-05 16:19 UTC, WeatherfordAaron commented on pkg/services/move_task_order/move_task_order_fetcher.go
> +		if serviceItem.POELocation != nil {
I'd consider combining these 2 if blocks since they both look for the same condition.

2024-12-06 14:15 UTC, danieljordan-caci commented on pkg/factory/mto_service_item_factory.go
> +
Not seeing a change in `mto_service_item_factory_test.go`?

2024-12-06 14:16 UTC, danieljordan-caci commented on pkg/factory/port_factory.go
> +	}
Not seeing this change?

2024-12-06 14:16 UTC, danieljordan-caci commented on pkg/factory/port_location_factory.go
> +	}
Same here - not seeing these changes. You push your changes?

2024-12-06 14:18 UTC, danieljordan-caci commented on pkg/services/move_task_order/move_task_order_fetcher.go
> +		if serviceItem.POELocation != nil {
Doesn't look like the logic after the `if` is the same, so I would say this approach is fine. If `PODLocation` isn't `nil`, then he's querying for the `PODLocation` on the service item. Same for `POELocation`.

2024-12-06 14:24 UTC, begrohmann approved these changes

2024-12-06 16:05 UTC, WeatherfordAaron commented on pkg/services/move_task_order/move_task_order_fetcher.go
> +		if serviceItem.POELocation != nil {
You are correct. I missed the last letters of those.

2024-12-09 17:39 UTC, brianmanley-caci commented on pkg/factory/port_location_factory.go
> +	}
Last week was a blur. I can see the changes in there now. Let me know if you are still not seeing them.

2024-12-09 17:39 UTC, brianmanley-caci commented on pkg/factory/port_factory.go
> +	}
just merged and pushed back up. It should be up to date now.

2024-12-09 17:39 UTC, brianmanley-caci commented on pkg/factory/mto_service_item_factory.go
> +
just merged and pushed back up. It should be up to date now.

2024-12-10 17:08 UTC, danieljordan-caci commented on pkg/factory/port_location_factory.go
> +		}
You want to do an `if` check here. Could even do an `if/else` check.

```
if port.PortCode != nil {
...fetch the requested port location
}
else {
...fetch default port location
}

2024-12-10 17:08 UTC, danieljordan-caci commented on pkg/factory/mto_service_item_factory.go
> +
Thanks for the test!

2024-12-10 17:09 UTC, danieljordan-caci requested changes
Just one more little change with your factories. Rest look good.

2024-12-10 17:09 UTC, danieljordan-caci commented on pkg/factory/port_factory.go
> +	}
Same thing here - do a `if cPort.PortCode != nil` check, if not, fetch the default.

2024-12-10 19:20 UTC, brianmanley-caci commented on pkg/factory/port_location_factory.go
> +		}
Updated to check for empty since nil is not valid.

2024-12-10 19:20 UTC, brianmanley-caci commented on pkg/factory/port_factory.go
> +	}
Updated to check for empty since nil is not valid here too.

2024-12-10 21:37 UTC, msaki-caci commented
> Anybody else wanna review this lol

I have been trying to today but I can't UB to work haha

2024-12-11 19:35 UTC, msaki-caci commented on pkg/factory/shared.go
> +// portGroup is a grouping of all the port related fields
Should this be "portLocationGroup is a grouping...."?

2024-12-11 19:43 UTC, msaki-caci commented on pkg/services/move_task_order/move_task_order_fetcher_test.go
> +		suite.True(found, "Expected service item ReServiceCodePOEFSC")
Should this be "Expected service item **ReServiceCodePODFSC**"

2024-12-11 19:50 UTC, msaki-caci commented on pkg/services/mto_service_item/mto_service_item_updater_test.go
> +	// Test failure Prime validation for Port of Embarkation
Should this be "Port of Debarkation"?

2024-12-11 21:08 UTC, brianmanley-caci commented on pkg/factory/shared.go
> +// portGroup is a grouping of all the port related fields
Yep. Fixed.

2024-12-11 21:09 UTC, brianmanley-caci commented on pkg/services/move_task_order/move_task_order_fetcher_test.go
> +		suite.True(found, "Expected service item ReServiceCodePOEFSC")
Updated to correct code.

2024-12-11 21:09 UTC, brianmanley-caci commented on pkg/services/mto_service_item/mto_service_item_updater_test.go
> +	// Test failure Prime validation for Port of Embarkation
Updated to correct wording.

2024-12-11 21:15 UTC, msaki-caci commented on yarn.lock
On your latest commit this file was modified. Was this on purpose?

2024-12-11 21:19 UTC, brianmanley-caci commented on yarn.lock
That change came from main. @cameroncaci can you confirm that this is correct best off your recent main PR for B-21230?

2024-12-11 21:48 UTC, msaki-caci commented on yarn.lock
I will go ahead and resolve this conversation

2024-12-12 15:03 UTC, danieljordan-caci reviewed
Question - was able to update the service item, but here's my payload:
```
{   
   "id": "ad1dc99c-3c51-4c0b-94eb-ace44d6be2f1",   
   "modelType": "UpdateMTOServiceItemInternationalPortFSC",   
   "portCode": "PDX",   
   "reServiceCode": "POEFSC" 
}
```

And here's my response:
```
{
  "reServiceCode": "POEFSC",
  "eTag": "MjAyNC0xMi0xMlQxNDo1NDo0OS40MzQ4MDJa",
  "id": "ad1dc99c-3c51-4c0b-94eb-ace44d6be2f1",
  "modelType": "MTOServiceItemBasic",
  "moveTaskOrderID": "5a99af3f-e9ce-4973-a064-b1606e3d95e8",
  "mtoShipmentID": "113a4bc3-ad46-464c-a98f-396b65ea2872",
  "reServiceName": "International POE Fuel Surcharge",
  "status": "APPROVED"
}
```

I just am not sure how I feel about us not returning the values that we have updated to confirm that they have been updated correctly. Here I updated the port, but I have no way of knowing it was successful (other than the `200`) in the response. Any thoughts on that? We could entertain having a `MTOServiceItemFuelSurcharge` response that contains that data, or add it to `MTOServiceItemBasic`. 

But it's also not a hill I want to die on and if the gov is cool with the response lacking all the port info, then I don't mind approving.

2024-12-12 15:07 UTC, danieljordan-caci requested changes
Ah, but while I'm thinking of it - please update the docs for the update service item endpoint on what is required when updating `PODFSC` & `POEFSC`. Just a brief run through of our process, what we require, etc, so we can inform HomeSafe when they start implementing this.

2024-12-12 15:12 UTC, brianmanley-caci commented
> Question - was able to update the service item, but here's my payload:
> 
> ```
> {   
>    "id": "ad1dc99c-3c51-4c0b-94eb-ace44d6be2f1",   
>    "modelType": "UpdateMTOServiceItemInternationalPortFSC",   
>    "portCode": "PDX",   
>    "reServiceCode": "POEFSC" 
> }
> ```
> 
> And here's my response:
> 
> ```
> {
>   "reServiceCode": "POEFSC",
>   "eTag": "MjAyNC0xMi0xMlQxNDo1NDo0OS40MzQ4MDJa",
>   "id": "ad1dc99c-3c51-4c0b-94eb-ace44d6be2f1",
>   "modelType": "MTOServiceItemBasic",
>   "moveTaskOrderID": "5a99af3f-e9ce-4973-a064-b1606e3d95e8",
>   "mtoShipmentID": "113a4bc3-ad46-464c-a98f-396b65ea2872",
>   "reServiceName": "International POE Fuel Surcharge",
>   "status": "APPROVED"
> }
> ```
> 
> I just am not sure how I feel about us not returning the values that we have updated to confirm that they have been updated correctly. Here I updated the port, but I have no way of knowing it was successful (other than the `200`) in the response. Any thoughts on that? We could entertain having a `MTOServiceItemFuelSurcharge` response that contains that data, or add it to `MTOServiceItemBasic`.
> 
> But it's also not a hill I want to die on and if the gov is cool with the response lacking all the port info, then I don't mind approving.

Yeah I do see what you're saying. Do you know other service items return any kind of info in the response like when they do an update? The way this feature spelled it out, after sending this update they would subsequently query the MTO and see the port information in that payload.

2024-12-12 15:13 UTC, danieljordan-caci commented
> > Question - was able to update the service item, but here's my payload:
> > ```
> > {   
> >    "id": "ad1dc99c-3c51-4c0b-94eb-ace44d6be2f1",   
> >    "modelType": "UpdateMTOServiceItemInternationalPortFSC",   
> >    "portCode": "PDX",   
> >    "reServiceCode": "POEFSC" 
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And here's my response:
> > ```
> > {
> >   "reServiceCode": "POEFSC",
> >   "eTag": "MjAyNC0xMi0xMlQxNDo1NDo0OS40MzQ4MDJa",
> >   "id": "ad1dc99c-3c51-4c0b-94eb-ace44d6be2f1",
> >   "modelType": "MTOServiceItemBasic",
> >   "moveTaskOrderID": "5a99af3f-e9ce-4973-a064-b1606e3d95e8",
> >   "mtoShipmentID": "113a4bc3-ad46-464c-a98f-396b65ea2872",
> >   "reServiceName": "International POE Fuel Surcharge",
> >   "status": "APPROVED"
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I just am not sure how I feel about us not returning the values that we have updated to confirm that they have been updated correctly. Here I updated the port, but I have no way of knowing it was successful (other than the `200`) in the response. Any thoughts on that? We could entertain having a `MTOServiceItemFuelSurcharge` response that contains that data, or add it to `MTOServiceItemBasic`.
> > But it's also not a hill I want to die on and if the gov is cool with the response lacking all the port info, then I don't mind approving.
> 
> Yeah I do see what you're saying. Do you know other service items return any kind of info in the response like when they do an update? The way this feature spelled it out, after sending this update they would subsequently query the MTO and see the port information in that payload.

There a few more types that we use for SIT, etc. You can check these others out:
```
definitions:
  MTOServiceItemBasic: # spectral oas2-unused-definition is OK here due to polymorphism
    $ref: 'definitions/prime/MTOServiceItemBasic.yaml'
  MTOServiceItemDestSIT: # spectral oas2-unused-definition is OK here due to polymorphism
    $ref: 'definitions/prime/MTOServiceItemDestSIT.yaml'
  MTOServiceItemDomesticCrating: # spectral oas2-unused-definition is OK here due to polymorphism
    $ref: 'definitions/prime/MTOServiceItemDomesticCrating.yaml'
  MTOServiceItemInternationalCrating: # spectral oas2-unused-definition is OK here due to polymorphism
    $ref: 'definitions/prime/MTOServiceItemInternationalCrating.yaml'
  MTOServiceItemOriginSIT: # spectral oas2-unused-definition is OK here due to polymorphism
    $ref: 'definitions/prime/MTOServiceItemOriginSIT.yaml'
  MTOServiceItemShuttle: # spectral oas2-unused-definition is OK here due to polymorphism
    $ref: 'definitions/prime/MTOServiceItemShuttle.yaml'
```

2024-12-12 17:03 UTC, brianmanley-caci commented
> MTOServiceItemShuttle

Thanks for the suggestion. I'm looking at what it would take to add a custom response type for international fuel surcharge now.

2024-12-12 21:15 UTC, brianmanley-caci commented
> > > Question - was able to update the service item, but here's my payload:
> > > ```
> > > {   
> > >    "id": "ad1dc99c-3c51-4c0b-94eb-ace44d6be2f1",   
> > >    "modelType": "UpdateMTOServiceItemInternationalPortFSC",   
> > >    "portCode": "PDX",   
> > >    "reServiceCode": "POEFSC" 
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > And here's my response:
> > > ```
> > > {
> > >   "reServiceCode": "POEFSC",
> > >   "eTag": "MjAyNC0xMi0xMlQxNDo1NDo0OS40MzQ4MDJa",
> > >   "id": "ad1dc99c-3c51-4c0b-94eb-ace44d6be2f1",
> > >   "modelType": "MTOServiceItemBasic",
> > >   "moveTaskOrderID": "5a99af3f-e9ce-4973-a064-b1606e3d95e8",
> > >   "mtoShipmentID": "113a4bc3-ad46-464c-a98f-396b65ea2872",
> > >   "reServiceName": "International POE Fuel Surcharge",
> > >   "status": "APPROVED"
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I just am not sure how I feel about us not returning the values that we have updated to confirm that they have been updated correctly. Here I updated the port, but I have no way of knowing it was successful (other than the `200`) in the response. Any thoughts on that? We could entertain having a `MTOServiceItemFuelSurcharge` response that contains that data, or add it to `MTOServiceItemBasic`.
> > > But it's also not a hill I want to die on and if the gov is cool with the response lacking all the port info, then I don't mind approving.
> > 
> > 
> > Yeah I do see what you're saying. Do you know other service items return any kind of info in the response like when they do an update? The way this feature spelled it out, after sending this update they would subsequently query the MTO and see the port information in that payload.
> 
> There a few more types that we use for SIT, etc. You can check these others out:
> 
> ```
> definitions:
>   MTOServiceItemBasic: # spectral oas2-unused-definition is OK here due to polymorphism
>     $ref: 'definitions/prime/MTOServiceItemBasic.yaml'
>   MTOServiceItemDestSIT: # spectral oas2-unused-definition is OK here due to polymorphism
>     $ref: 'definitions/prime/MTOServiceItemDestSIT.yaml'
>   MTOServiceItemDomesticCrating: # spectral oas2-unused-definition is OK here due to polymorphism
>     $ref: 'definitions/prime/MTOServiceItemDomesticCrating.yaml'
>   MTOServiceItemInternationalCrating: # spectral oas2-unused-definition is OK here due to polymorphism
>     $ref: 'definitions/prime/MTOServiceItemInternationalCrating.yaml'
>   MTOServiceItemOriginSIT: # spectral oas2-unused-definition is OK here due to polymorphism
>     $ref: 'definitions/prime/MTOServiceItemOriginSIT.yaml'
>   MTOServiceItemShuttle: # spectral oas2-unused-definition is OK here due to polymorphism
>     $ref: 'definitions/prime/MTOServiceItemShuttle.yaml'
> ```



> > MTOServiceItemShuttle
> 
> Thanks for the suggestion. I'm looking at what it would take to add a custom response type for international fuel surcharge now.

Ok, so I have added a new type MTOServiceItemInternationalFuelSurcharge that will include the service code and the port in the response. This should help validate that the port they sent was saved. I think this is a helpful solution.

2024-12-12 21:16 UTC, brianmanley-caci commented
> Ah, but while I'm thinking of it - please update the docs for the update service item endpoint on what is required when updating `PODFSC` & `POEFSC`. Just a brief run through of our process, what we require, etc, so we can inform HomeSafe when they start implementing this.

Idded some verbiage to the API documentation to help spell out how the port can be updated.

2024-12-16 15:22 UTC, danieljordan-caci approved these changes
Update response:
![Screenshot 2024-12-16 at 9 21 23 AM](https://github.com/user-attachments/assets/c0cac46b-1d19-4fa1-ba13-4c07b990dd90)

Shipment body in MTO fetch:
![Screenshot 2024-12-16 at 9 22 03 AM](https://github.com/user-attachments/assets/16e79d1e-c5a3-47d4-9d52-647335c07ba9)

LGTM! Thanks for all the changes.

2024-12-16 16:24 UTC, danieljordan-caci commented on swagger-def/definitions/Port.yaml
> +      - P
oooo nice eagle eye!

2024-12-16 16:35 UTC, brianmanley-caci commented on swagger-def/definitions/Port.yaml
> +      - P
Nice catch. It should be update now.

2024-12-16 18:19 UTC, deandreJones approved these changes

2024-12-16 18:55 UTC, merged