B 21359 int - Backend: Assigned User Cleanup
transcom/mymove pull request #14346
Opened 2024-12-06 23:24 UTC by JonSpight

## [Agility ticket](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-21359)

## Summary
Once an assigned office user has completed their task on  a move, we need to clean up that assigned and remove them from the move.

## Screenshots

2024-12-16 16:31 UTC, danieljordan-caci commented on pkg/handlers/ghcapi/payment_request.go
> +			}
I know this is still in draft, but please add a test for this. Pretty big functionality that should be added.

2024-12-17 14:22 UTC, danieljordan-caci requested changes
Static review changes

2024-12-17 14:22 UTC, danieljordan-caci commented on pkg/factory/move_factory.go
> +	}
Update a test to reflect these changes plz

2024-12-17 14:22 UTC, danieljordan-caci commented on pkg/handlers/ghcapi/payment_request.go
> +			openPr := false
What is `openPr` mean? Could this be renamed to be something a little more clarifying on what its scope is?

2024-12-17 14:22 UTC, danieljordan-caci commented on pkg/handlers/ghcapi/payment_request.go
> +			}
Would it be appropriate to put in a `break` in here to reduce the number of loops?

2024-12-17 14:22 UTC, danieljordan-caci commented on pkg/handlers/ghcapi/payment_request.go
> +
Can you remove this white space?

2024-12-17 14:22 UTC, danieljordan-caci commented on pkg/handlers/primeapi/payloads/model_to_payload_test.go
> +	// suite.Equal(handlers.NotImplementedErrMessage, *noDetailError.Detail)
left in comment

2024-12-17 20:38 UTC, JonSpight commented on pkg/handlers/ghcapi/payment_request.go
> +			unreviewedPaymentRequset := false
fixed

2024-12-18 04:50 UTC, paulstonebraker commented
```
Approve a service item as TOO
Navigate back to the Task Oder Queue and verify the move is no longer assigned and is now assignable
Reject a service item as TOO
Navigate back to the Task Oder Queue and verify the move is no longer assigned and is now assignable
```
TOO approves/rejects service item, there are some remaining service items to be dealt with and it still appears in their queue - have we confirmed with PO that this is how they'd like it? I kind of assumed since it hasn't moved out of the TOO's queue, it would remain assigned to the same TOO until the point at which it leaves their queue (and when it returns, it would be unassigned)

2024-12-18 04:57 UTC, paulstonebraker commented on pkg/services/mto_service_item/mto_service_item_updater.go
> +		_, err = models.SaveMoveDependencies(appCtx.DB(), &move)
Should we just do like we do in `move_task_order_updater` and Validate and save rather than use SaveMoveDependencies?
```
		verrs, err := appCtx.DB().ValidateAndSave(&move)
		if verrs != nil && verrs.HasAny() {
			return apperror.NewInvalidInputError(move.MTOShipments[i].ID, nil, verrs, "")
		}
		if err != nil {
			return err
		}
```

2024-12-23 18:22 UTC, paulstonebraker commented on pkg/services/payment_request/payment_request_status_updater_test.go
> +	suite.Run("If we get a payment request pointer with a status it should update and return no ", func() {
Update this for better description of test

2024-12-23 18:22 UTC, paulstonebraker commented on pkg/services/payment_request/payment_request_list_fetcher.go
> +	services.MoveAssignedOfficeUserUpdater
Remove this I think

2024-12-23 18:24 UTC, paulstonebraker commented on pkg/services/move_task_order/move_task_order_updater.go
> +	move.TOOAssignedID = nil
Lets add tests for this and the SC, sorrryyyyyy, I can help

2024-12-23 18:26 UTC, paulstonebraker commented on pkg/handlers/ghcapi/payment_request.go
> +	services.PaymentRequestListFetcher
Do we need this? And MoveAssignedOfficeUserUpdater?

2024-12-23 18:27 UTC, paulstonebraker commented on pkg/factory/shared.go
> +// type officeUserGroup struct {
remove

2024-12-24 16:37 UTC, paulstonebraker commented on pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
> +	suite.Run("Success - Returns a ghcmessages Upload payload from Upload Struct Marine move with no shipments", func() {
Whats this change

2024-12-24 16:58 UTC, paulstonebraker commented on pkg/handlers/ghcapi/payment_request.go
> +	services.MoveAssignedOfficeUserUpdater
I think we can remove this since we moved the updating to the PaymentRequestStatusUpdater service. Also remove from associated test file and api.go

2024-12-24 16:59 UTC, paulstonebraker commented on pkg/models/move.go
> +		"MTOServiceItems.Status",
I ran the tests without `"MTOServiceItems.Status"` and it worked. And oddly enough - i tested without `"MTOServiceItems"` and it also worked. Maybe first level associations are loaded by default?

2024-12-26 22:33 UTC, paulstonebraker approved these changes
Thanks for dealing with me and my wishy washy change requests! Good work

2024-12-30 15:13 UTC, loganwc approved these changes

2024-12-30 17:43 UTC, danieljordan-caci approved these changes
Approving on the @paulstonebraker "trust me bro" factor

2024-12-30 20:07 UTC, merged