B 21536 int
transcom/mymove pull request #14357
Opened 2024-12-09 21:18 UTC by CoryKleinjanCACI

## [Agility ticket](tbd)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-12-10 15:53 UTC, MInthavongsay commented on migrations/app/schema/20221129184114_redifine_audit_tables.up.sql
> -		'destination_address_id',
For this particular change can this be done in a new migration file? Or updating the original migration the only way?

2024-12-10 16:12 UTC, deandreJones requested changes
new migration file needed

2024-12-10 16:16 UTC, MInthavongsay requested changes
Need to create a new migration file to apply the db changes instead of updating existing migration file.

2024-12-10 16:22 UTC, CoryKleinjanCACI commented on migrations/app/schema/20221129184114_redifine_audit_tables.up.sql
> -		'destination_address_id',
Nope. Just forgot. Fixing it now.

2024-12-10 20:24 UTC, MInthavongsay approved these changes
Talked to Cory about some "issues" uncovered that are related to audit logs that are outside the scope of this BL. For example,  DELETEs of addresses are not correctly captured in the audit logs. This will need to be addressed in another BL and/or EPIC.  Will approve this per AC.

2024-12-11 20:15 UTC, antgmann approved these changes
New migration file looks good, testing steps work as instructed.

2024-12-12 20:54 UTC, danieljordan-caci requested changes
Discrepancy i n variable names

2024-12-12 20:54 UTC, danieljordan-caci commented on src/constants/MoveHistory/Database/FieldMappings.js
> +  has_tertiary_destination_address: 'Third Delivery Address',
`delivery` or `destination`? If they're different then I hate it.

2024-12-12 20:55 UTC, danieljordan-caci commented on pkg/assets/sql_scripts/move_history_fetcher.sql
> +				FROM
Can you put this back to where it was?

2024-12-12 21:01 UTC, CoryKleinjanCACI commented on pkg/assets/sql_scripts/move_history_fetcher.sql
> +				FROM
Yea, I think pre-commit might have done that for some reason. Just tried pushing a change to remove the weird spacing and it took it now.

2024-12-12 21:08 UTC, CoryKleinjanCACI commented on src/constants/MoveHistory/Database/FieldMappings.js
> +  has_tertiary_destination_address: 'Third Delivery Address',
This is how it exists in existing logs, and other places in the application. The backend is secondary_destination, but the frontend displays delivery. It is like this on the Approved Shipments tab of a move as well. I also don't like it.

2024-12-12 21:09 UTC, danieljordan-caci commented on src/constants/MoveHistory/Database/FieldMappings.js
> +  has_tertiary_destination_address: 'Third Delivery Address',
Gross.

2024-12-12 21:09 UTC, danieljordan-caci approved these changes

2024-12-12 21:09 UTC, CoryKleinjanCACI commented on src/constants/MoveHistory/Database/FieldMappings.js
> +  has_tertiary_destination_address: 'Third Delivery Address',
<img width="638" alt="Screenshot 2024-12-12 at 3 09 35 PM" src="https://github.com/user-attachments/assets/eec38d35-0fdf-4b78-958f-145ca78fc579" />

2024-12-13 14:21 UTC, antgmann commented
Accepted happo diff

2024-12-16 13:12 UTC, antgmann approved these changes

2024-12-16 18:19 UTC, deandreJones approved these changes

2024-12-16 18:20 UTC, merged