Revert "B-21636 Update PPTAS LOA Fields"
transcom/mymove pull request #14353
Opened 2024-12-09 20:10 UTC by deandreJones

Reverts transcom/mymove#14234

reverting per team request

2024-12-09 20:12 UTC, TevinAdams approved these changes

2024-12-09 20:28 UTC, pambecker approved these changes

2024-12-09 20:30 UTC, cameroncaci requested changes
I'll be the annoying one - requesting merge to int first since it isn't a hotfix

2024-12-09 20:44 UTC, pambecker commented
> I'll be the annoying one - requesting merge to int first since it isn't a hotfix

@cameroncaci here are the INT reverts

https://github.com/transcom/mymove/pull/14354
https://github.com/transcom/mymove/pull/14355

2024-12-09 21:58 UTC, deandreJones commented
> > I'll be the annoying one - requesting merge to int first since it isn't a hotfix
> 
> @cameroncaci here are the INT reverts
> 
> #14354 #14355

INT reverted
@cameroncaci

2024-12-10 12:58 UTC, cameroncaci approved these changes

2024-12-10 13:27 UTC, merged