B-21094: Automatic Reweigh Based on Estimated Weight
transcom/mymove pull request #14364
Opened 2024-12-10 17:06 UTC by WeatherfordAaron

## Agility Ticket: [B-21094](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-21094)

## Agility Ticket's Acceptance Criteria

As the MilMove system (on behalf of the TOO),
I need to request a reweigh for all shipments on a customer's move based on the sum of the estimated weight(s),
So that I can ensure the customer has the greatest chance of reweighs being performed on all of their shipments (through the use of more advanced notice).

AC1: 
Given the sum of all estimated weights on a customer's move,
When that sum is within 10% (or greater) of the customer's weight entitlement,
Then a reweigh is requested for all shipments on a that move (excludes PPMs).

AC2: PRESERVE EXISTING CAPABILITY ALREADY IN MILMOVE
Given a customer's move where the sum of the estimated weights did not result in automatic reweigh(s) being requested,
When the sum of the actual shipment weights is within 10% (or greater) of the customer's weight entitlement,
Then a reweigh is requested for all shipments on that move (excludes PPMs).

## How to test

1. As a **_Service Member_**, create a new move + orders + at least 2 non-PPM shipments.
2. As **_Service Counsellor_**, update the move's orders and approve/send the move.
3. As **_TOO_**, approve the shipments (this should make the move available to the Prime user role).
4. As **_Prime_**, update each shipment so that the sum of the Estimated Weights of all the shipments on the move falls within the top 10% of the Authorized Weight.
___
Note 1: _Currently you must enter both Estimated and Actual Weights on each of the shipments if you are using the Prime Simulator because current form validation forces you to do so.. however, this is a ticket which should change this functionality so that the Prime Simulator can have Estimated Weight without the need for Actual Weight (and vice versa)._
___
Note 2: _The reason the sum needs to fall within the top 10% of the Authorized Weight is because other logic may be carried out once the sum of Estimated Weights or Actual Weights goes over the Authorized Weight._
___
```
Authorized Weight = A
Target Weight Floor = T
A * 0.9 = T
```
Example: If Authorized Weight is 7000 lbs, 7000 * 0.9 = 6300. This means that, from the entire move, if the sum of the Estimated Weights is at least 6300 lbs or the sum of the Actual Weights is at least 6300 lbs, it will trigger an automatic reweight request.

6. As soon as the sum of the Estimated Weights of the shipments on the move falls within the top 10% of the Authorized Weight, you should see the "Reweigh Weight" attribute (seen below) with the red "Missing" text for each shipment on the move. This indicates that an auto-reweigh has been initiated.
<img width="443" alt="Screenshot 2024-12-05 at 6 32 37 AM" src="https://github.com/user-attachments/assets/067dec9d-eba6-4aa0-95e6-a26bdba22ce8">

2024-12-12 17:09 UTC, danieljordan-caci requested changes

2024-12-12 17:09 UTC, danieljordan-caci commented on pkg/models/move.go
> +func (move Move) NeedsReweigh(appCtx appcontext.AppContext) (*bool, error) {
This needs to be in a service object, not in the models folder.

Any time we tinker with the database, we need it to be within the service objects. Simple queries are typically fine here, but this looks like it would be better suited in the `services` folder

2024-12-12 18:08 UTC, WeatherfordAaron commented on pkg/models/move.go
> +func (move Move) NeedsReweigh(appCtx appcontext.AppContext) (*bool, error) {
I had it here because I liked the modularity of it being able to be ran off of the move object that it is in regards to. I will move it to the services folder based on your requested change.. however, could you expand on the reasoning so I understand what I should do in the future when I have something like this?

2024-12-12 18:13 UTC, WeatherfordAaron commented on pkg/models/move.go
> +func (move Move) NeedsReweigh(appCtx appcontext.AppContext) (*bool, error) {
actually nevermind.. I think I understand the reasoning

2024-12-13 16:37 UTC, WeatherfordAaron commented on pkg/models/move.go
> +func (move Move) NeedsReweigh(appCtx appcontext.AppContext) (*bool, error) {
Upon further investigation and studying of this issue, I would like you to expand on the suggestion because even when I thought I knew the reason why, I think the reasoning I was assuming you had doesn't apply in this case. Let me try to explain the reasoning I had behind putting this method inside the model to get the conversation started.

My background is more simulation and video game development oriented. I would create models which are ultimately representing data structure. It was very common to include getter and setter methods inside the model which are directly related to either getting or setting data.
- Setters would take input of some kind as an arg and through validation would either change the object's attribute(s) or produce an error.
- Getters would produce data or information from the starting point of having an instance of that object in memory. When producing the return value(s) I could perform calculations, data aggregation, and/or 1 or more SQL queries in order to produce the result.

In both cases, there would be a singular data object that is the subject of the getting or setting. If I were to make a service, it would usually be because it's a job that has more than one data object as the subject.

2024-12-16 14:33 UTC, danieljordan-caci requested changes

2024-12-16 14:33 UTC, danieljordan-caci commented on pkg/models/move.go
> +func (move Move) NeedsReweigh(appCtx appcontext.AppContext) (*bool, error) {
It's just the depth of the database work needed for this makes it appropriate for a service object. You can even use the existing `ReweighFetcher` service object and put the function in there.

This is making several queries:
- move on 668
- move again (should probably only query the move once btw) on 678
- every shipment under the move

If this had one simple query then I'd be cool with it, but it doesn't. We also have setters and getters in the service object because we should keep all of our (or as many of our) database transactions within that folder. It's not just best practice, but it's keeping in line with what we are doing throughout the rest of the app. I don't think this use case is an exception.

2024-12-18 15:24 UTC, taeJungCaci commented on pkg/services/mto_shipment/mto_shipment_updater.go
> +				if needsReweigh == models.BoolPointer(true) {
I think I ran into this issue as well, but when doing the bool check - I believe it should be`if *needsReweigh {` instead of checking `models.BoolPointer(true)`.

2024-12-18 15:29 UTC, taeJungCaci commented on pkg/services/mto_shipment/mto_shipment_updater.go
> +				if needsReweigh == models.BoolPointer(true) {
I've ran into issue with comparing with models.BoolPointer(true). Might have to use `if *needsReweigh {` instead unless you know for sure this works 100%.

2024-12-18 17:50 UTC, danieljordan-caci commented on pkg/services/move/move_weights.go
> +	}
Any reason why you're loading the move twice here?

2024-12-18 17:53 UTC, danieljordan-caci commented on pkg/services/move/move_weights.go
> +		err = appCtx.DB().Load(&move.MTOShipments[i], "MTOServiceItems", "ShipmentType", "Status", "DeletedAt")
Instead of calling here, can you load it all in one query above? Maybe add `"MTOShipments.MTOServiceItems"` to `Eager`
```
err := appCtx.DB().Eager("MTOShipments", "Orders.Entitlement.DBAuthorizedWeight").Find(&move, moveID)
```

And do you not have access to the shipment type, status, and deleted already? As in, do you need to include those in the list?

2024-12-18 17:55 UTC, WeatherfordAaron commented on pkg/services/move/move_weights.go
> +	}
Does Load not work like I think it does? I thought Load would make sure MTOShipments is there (I know it should already be).. but also pulls in Orders.Entitlement.DBAuthorizedWeight (which I don't think it will have at first)

2024-12-18 17:57 UTC, WeatherfordAaron commented on pkg/services/move/move_weights.go
> +		err = appCtx.DB().Load(&move.MTOShipments[i], "MTOServiceItems", "ShipmentType", "Status", "DeletedAt")
That it iterative, right? Is there a way to make it do that before or instead of iterating?

2024-12-18 17:58 UTC, danieljordan-caci commented on pkg/services/move/move_weights.go
> +		err = appCtx.DB().Load(&move.MTOShipments[i], "MTOServiceItems", "ShipmentType", "Status", "DeletedAt")
Well you just need to load the array of shipments in your query above and any association you need and you shouldn't have to load here

2024-12-18 17:58 UTC, danieljordan-caci commented on pkg/services/move/move_weights.go
> +	}
lol nose in the code

2024-12-18 18:09 UTC, WeatherfordAaron commented on pkg/services/move/move_weights.go
> +		err = appCtx.DB().Load(&move.MTOShipments[i], "MTOServiceItems", "ShipmentType", "Status", "DeletedAt")
ok changes made.. checking tests now. Will ping you whenever it makes it back to this point

2024-12-18 18:09 UTC, WeatherfordAaron commented on pkg/services/move/move_weights.go
> +	}
ok changes made.. checking tests now. Will ping you whenever it makes it back to this point

2024-12-18 18:09 UTC, danieljordan-caci commented on pkg/services/move/move_weights.go
> +	err := appCtx.DB().Eager("MTOShipments", "Orders.Entitlement.DBAuthorizedWeight", "MTOShipments.ServiceItems").Find(&move, moveID)
This would be `"MTOShipments.MTOServiceItems"`, I believe.

When you look at the model for `mto_shipment`, you have this:
```
MTOServiceItems                  MTOServiceItems        `has_many:"mto_service_items" fk_id:"mto_shipment_id"`
```

So when doing the association call, you have to match that middle value.

2024-12-18 19:25 UTC, WeatherfordAaron commented on pkg/services/move/move_weights.go
> +	err := appCtx.DB().Eager("MTOShipments", "Orders.Entitlement.DBAuthorizedWeight", "MTOShipments.ServiceItems").Find(&move, moveID)
I tried that and it didn't work.. any reason why we can't do the iterative approach? (see current code)

2024-12-19 15:12 UTC, danieljordan-caci commented on pkg/services/move/move_weights.go
> +	weightLimit := *move.Orders.Entitlement.DBAuthorizedWeight
Can you add in a nil check here because this value CAN be null, so we need to make sure we have it.

2024-12-19 15:36 UTC, WeatherfordAaron commented on pkg/services/move/move_weights.go
> +	weightLimit := *move.Orders.Entitlement.DBAuthorizedWeight
change added and pushed

2024-12-19 16:59 UTC, danieljordan-caci commented on pkg/services/move/move_weights.go
> +		weightLimit = *move.Orders.Entitlement.DBAuthorizedWeight
Since this is crucial to your function/logic and if it's nil, should an error be returned here?

2024-12-19 17:28 UTC, WeatherfordAaron commented on pkg/services/move/move_weights.go
> +		weightLimit = *move.Orders.Entitlement.DBAuthorizedWeight
done and pushed

2024-12-19 17:32 UTC, danieljordan-caci submitted a review, later dismissed

2024-12-19 18:38 UTC, deandreJones submitted a review, later dismissed

2024-12-19 19:35 UTC, taeJungCaci requested changes
So my weight allowance is 5000 lb and I put 4999 lbs for the estimated weight and it doesn't seem to auto trigger the reweight. Anything I am missing?

![image](https://github.com/user-attachments/assets/c27f0382-e154-4bc6-9862-79e8aa6db332)
![image](https://github.com/user-attachments/assets/ad4cd67f-62ac-478d-a1a3-741c6a98bfe2)

2024-12-19 19:36 UTC, taeJungCaci commented
Also I get this error when putting actual weight after submitting estimated weight: 
![image](https://github.com/user-attachments/assets/e74ac1dc-c6ef-4a24-a208-c94a53a55c0e)

2024-12-20 16:48 UTC, brooklyn-welsh requested changes
I'm currently getting a nil reference error at line 273 of move_weights.go:

![Screenshot 2024-12-20 at 11 47 05 AM](https://github.com/user-attachments/assets/8fe7ea26-19c7-42bf-9bd5-68378c53b93c)

Here's my Prime API page:
![Screenshot 2024-12-20 at 11 47 12 AM](https://github.com/user-attachments/assets/9451c1a3-3f92-4a8c-b878-fdd3b4b7ac6b)

2024-12-20 16:49 UTC, brooklyn-welsh commented
> I'm currently getting a nil reference error at line 273 of move_weights.go:
> 
> ![Screenshot 2024-12-20 at 11 47 05 AM](https://private-user-images.githubusercontent.com/146959895/397808026-8fe7ea26-19c7-42bf-9bd5-68378c53b93c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3MTM1OTksIm5iZiI6MTczNDcxMzI5OSwicGF0aCI6Ii8xNDY5NTk4OTUvMzk3ODA4MDI2LThmZTdlYTI2LTE5YzctNDJiZi05YmQ1LTY4Mzc4YzUzYjkzYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMFQxNjQ4MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZTNkZjg1YTJiMDRiMzFmM2VjMTBiYzJjYmM5YzM1MzhiNWU4NDBjYTQ4NTI3ODQ4M2JiZDgyMzY0ZjJmNTdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KldaN5JGdTv8R0FijXol6ozQnBfrQVSw9GvOvCnT0XI)
> 
> Here's my Prime API page: ![Screenshot 2024-12-20 at 11 47 12 AM](https://private-user-images.githubusercontent.com/146959895/397808063-9451c1a3-3f92-4a8c-b878-fdd3b4b7ac6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3MTM1OTksIm5iZiI6MTczNDcxMzI5OSwicGF0aCI6Ii8xNDY5NTk4OTUvMzk3ODA4MDYzLTk0NTFjMWEzLTNmOTItNGE4Yy1iODc4LWZkZDNiNGI3YWM2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMFQxNjQ4MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZjM1ZWQ0ZWRjZGMyNmI0OWRlNmY2YTJlODU3NjY1YTZiYmI3OTc0ZTE1YTc1NTkyNTVmNDgwNTcyOTc4MGQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jWxqhG8XZXzBrWVvBGrLT_MQKGcSg-39IXjyxxpd07k)

Oops my screenshot cut off the weights field, but I had tried to set the actual and estimated weights to 2,500 lbs.

2025-01-30 18:35 UTC, danieljordan-caci requested changes
Looks like you still have failing tests - re-request when ya get all those stubborn things resolved.

2025-02-04 18:13 UTC, danieljordan-caci approved these changes
Had two shipments (OCONUS) and allowance of 11,000 pounds.

Updated weights of first to be 6,000

Second shipment, updated weights to 6,000

Automatically saw the "reweigh weight: missing" populate
![Screenshot 2025-02-04 at 12 12 48 PM](https://github.com/user-attachments/assets/18541d18-42b4-4a44-a6a3-443388864d3d)

Verified I was prompted to address it as TOO
![Screenshot 2025-02-04 at 12 11 37 PM](https://github.com/user-attachments/assets/b09d3835-a625-40fa-9ae3-ca70892be701)

LGTM!

2025-02-05 20:16 UTC, cameroncaci requested changes
Clean implementation, love the new GetAutoReweighShipments func. Works and meets AC, but noticed 2 spots for touch up

![Screenshot 2025-02-05 at 3 09 59 PM](https://github.com/user-attachments/assets/ea8cfb83-c1cb-47bd-b6ce-32cd2b46c971)
![Screenshot 2025-02-05 at 3 12 51 PM](https://github.com/user-attachments/assets/a6e4ebb2-af11-4831-9d57-66e19552cb6f)

2025-02-05 20:16 UTC, cameroncaci commented on pkg/services/move/move_weights.go
> +func (w moveWeights) GetAutoReweighShipments(appCtx appcontext.AppContext, move *models.Move, updatedShipment *models.MTOShipment) (models.MTOShipments, error) {
`move` and `updatedShipment` parameters are required by this function. Recommend putting in nil checks or removing the pointer, otherwise this func could cause a nil panic in the future

2025-02-06 18:03 UTC, brooklyn-welsh commented on pkg/services/move/move_weights.go
> +		return nil, err
Hey Cameron, taking this PR over for Aaron, I agree, added these back in

2025-02-06 18:04 UTC, brooklyn-welsh commented on pkg/services/move/move_weights.go
> +func (w moveWeights) GetAutoReweighShipments(appCtx appcontext.AppContext, move *models.Move, updatedShipment *models.MTOShipment) (models.MTOShipments, error) {
Added nil checks to this func and CheckAutoReweigh and added a couple tests for these nil checks

2025-02-07 16:53 UTC, taeJungCaci approved these changes

2025-02-07 20:07 UTC, brooklyn-welsh approved these changes

2025-02-10 17:42 UTC, cameroncaci approved these changes
Perfect!

2025-02-10 22:12 UTC, merged