B 21904 nts oconus int
transcom/mymove pull request #14384
Opened 2024-12-12 15:41 UTC by KonstanceH

## [Agility ticket](tbd)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-12-13 18:24 UTC, taeJungCaci reviewed
Just 1 minor thing to check - everything else looks good to me.

2024-12-13 18:24 UTC, taeJungCaci commented on migrations/app/schema/20241208080706_add_internatinoal_nts_re_service_items.up.sql
> +    ('e702818f-defd-452c-81a3-865b902e7dd0', '388115e8-abe9-441d-96cf-a39f24baa0a3' ,'HHG_INTO_NTS_DOMESTIC', 'i', true, now(), now(), 3),
I think they might be wanting `PODFSC` as 2  and packing stuff as 3 for sorting. Check out `20241126222026_add_sort_column_to_re_service_items.up.sql` and see what you think.

2024-12-13 18:50 UTC, KonstanceH commented on migrations/app/schema/20241208080706_add_internatinoal_nts_re_service_items.up.sql
> +    ('e702818f-defd-452c-81a3-865b902e7dd0', '388115e8-abe9-441d-96cf-a39f24baa0a3' ,'HHG_INTO_NTS_DOMESTIC', 'i', true, now(), now(), 3),
oh yikes! yea ordering really matters on this story so I'll make the change and push it up

2024-12-13 19:12 UTC, taeJungCaci approved these changes
LGTM!

2024-12-13 21:07 UTC, JamesHawks224 approved these changes
testing: success
code: lgtm

2024-12-16 16:13 UTC, begrohmann commented on migrations/app/schema/20241208080706_add_internatinoal_nts_re_service_items.up.sql
> +    ('2a560507-db09-4be1-b809-49c0f515b31b', '9f3d551a-0725-430e-897e-80ee9add3ae9' ,'HHG_INTO_NTS_DOMESTIC', 'i', true, now(), now(), 1),
The shipment type should be updated to HHG_INTO_NTS (remove DOMESTIC). I see we have B-21905 to update this so I think that BL should be an upstream to this one.

2024-12-16 17:19 UTC, danieljordan-caci commented on migrations/app/schema/20241208080706_add_internatinoal_nts_re_service_items.up.sql
> +VALUES
Have you had any guidance on the `sort` values here? Is there a reason only some of them have a `sort` value but the others don't?

2024-12-16 17:40 UTC, danieljordan-caci requested changes

2024-12-16 17:40 UTC, danieljordan-caci commented on pkg/services/mto_shipment/shipment_approver.go
> +	internationalSi := []models.MTOShipmentType{models.MTOShipmentTypeHHG, models.MTOShipmentTypeHHGIntoNTSDom}
Can you change this variable name? `internationalSi` doesn't seem to match - something like `internationalShipmentTypes` or something.

2024-12-16 17:40 UTC, danieljordan-caci commented on pkg/services/mto_shipment/shipment_approver.go
> +	internationalSi := []models.MTOShipmentType{models.MTOShipmentTypeHHG, models.MTOShipmentTypeHHGIntoNTSDom}
Can also put a comment here that these are the shipment types we allow at the moment and future devs can add to it

2024-12-16 17:40 UTC, danieljordan-caci commented on pkg/services/mto_shipment/shipment_approver.go
> +	internationalSi := []models.MTOShipmentType{models.MTOShipmentTypeHHG, models.MTOShipmentTypeHHGIntoNTSDom}
Also, we need to put this block into the transaction to ensure if there are errors we can rollback.

2024-12-16 17:40 UTC, danieljordan-caci commented on pkg/services/mto_shipment/shipment_approver_test.go
> +					MarketCode:   "i",
Instead of hard coding `"i"`, can you use the existing variable in the shipments model?
```
type MarketCode string

const (
	MarketCodeDomestic      MarketCode = "d" // domestic
	MarketCodeInternational MarketCode = "i" // international
)
```

2024-12-16 17:40 UTC, danieljordan-caci commented on pkg/services/mto_shipment/shipment_approver_test.go
> +		invalidShipment := models.MTOShipment{}
Instead of an empty shipment here, can you use an actual shipment type that we currently don't support? Maybe a PPM or something.

2024-12-16 17:40 UTC, KonstanceH commented on migrations/app/schema/20241208080706_add_internatinoal_nts_re_service_items.up.sql
> +    ('2a560507-db09-4be1-b809-49c0f515b31b', '9f3d551a-0725-430e-897e-80ee9add3ae9' ,'HHG_INTO_NTS_DOMESTIC', 'i', true, now(), now(), 1),
Yea I saw that after I was already knee deep in this story so I figured since its just adding these records, it'd be okay to do the name change after. Tae's working the other story that's handling that name change and we had already talked about it. BUT I don't mind putting this on hold until his story gets in and then I can make the name change on this pr either.

2024-12-16 17:42 UTC, KonstanceH commented on migrations/app/schema/20241208080706_add_internatinoal_nts_re_service_items.up.sql
> +VALUES
I haven't I was just following the other service items that aren't pre approved in the re_service_items table, their sort numbers are null in the db.

2024-12-16 18:11 UTC, taeJungCaci commented on migrations/app/schema/20241208080706_add_internatinoal_nts_re_service_items.up.sql
> +    ('2a560507-db09-4be1-b809-49c0f515b31b', '9f3d551a-0725-430e-897e-80ee9add3ae9' ,'HHG_INTO_NTS_DOMESTIC', 'i', true, now(), now(), 1),
I should be almost finished with name change story. Just need to test if anything is broken lol. I'd be okay with you holding this story until mine gets in. Then I don't have to do rename changes for your DB stuff.

2024-12-16 18:50 UTC, KonstanceH commented on migrations/app/schema/20241208080706_add_internatinoal_nts_re_service_items.up.sql
> +VALUES
Okay that sounds good. I just asked if there's a preference on it and I'll push up the changes once I get an answer back. I think I pushed up all of the changes for the rest of your comments

2024-12-16 18:51 UTC, danieljordan-caci commented on migrations/app/schema/20241208080706_add_internatinoal_nts_re_service_items.up.sql
> +VALUES
Thank ya, thank ya. I'll resolve when I re-review.

2024-12-16 18:59 UTC, KonstanceH commented on migrations/app/schema/20241208080706_add_internatinoal_nts_re_service_items.up.sql
> +    ('2a560507-db09-4be1-b809-49c0f515b31b', '9f3d551a-0725-430e-897e-80ee9add3ae9' ,'HHG_INTO_NTS_DOMESTIC', 'i', true, now(), now(), 1),
okay sounds like a plan to me

2024-12-18 20:20 UTC, taeJungCaci commented on migrations/app/schema/20241208080706_add_internatinoal_nts_re_service_items.up.sql
> +    ('2a560507-db09-4be1-b809-49c0f515b31b', '9f3d551a-0725-430e-897e-80ee9add3ae9' ,'HHG_INTO_NTS_DOMESTIC', 'i', true, now(), now(), 1),
The changes for renaming NTS is in IntegrationBranch now and you should be able to merge in `MAIN-B-21905-rename-nts-shipment-type` to your Story Main branch and then merge those changes here. [This is the Main PR for ref.](https://github.com/transcom/mymove/pull/14418)

2024-12-19 14:20 UTC, KonstanceH commented on migrations/app/schema/20241208080706_add_internatinoal_nts_re_service_items.up.sql
> +VALUES
Okay I got answer that the preview window should show the same ordering as an HHG, so I left those ordered UI facing ones and left the others NULL. I put some comments in the sql to help me out lol but this should be good to go for another review.

2024-12-19 14:21 UTC, KonstanceH commented on migrations/app/schema/20241208080706_add_internatinoal_nts_re_service_items.up.sql
> +    ('2a560507-db09-4be1-b809-49c0f515b31b', '9f3d551a-0725-430e-897e-80ee9add3ae9' ,'HHG_INTO_NTS_DOMESTIC', 'i', true, now(), now(), 1),
Added in the name change and the migration file from my main branch so this should be good to go for another review.

2024-12-19 18:56 UTC, danieljordan-caci approved these changes

2024-12-19 19:59 UTC, taeJungCaci approved these changes

2024-12-20 14:27 UTC, brianmanley-caci commented on pkg/services/mto_shipment/shipment_approver_test.go
> +	suite.Run("Given international mtoShipment is approved successfully pre-approved mtoServiceItems are created NTS", func() {
This test handles CONUS -> OCONUS which is good. What do you think about adding a similar test for OCONUS -> CONUS to validate that the 3rd service item (PODFSC) is added?

2024-12-20 14:35 UTC, KonstanceH commented on pkg/services/mto_shipment/shipment_approver_test.go
> +	suite.Run("Given international mtoShipment is approved successfully pre-approved mtoServiceItems are created NTS", func() {
Yea that makes sense I'll add it in and push it up now

2024-12-20 15:18 UTC, brianmanley-caci requested changes

2024-12-20 15:18 UTC, brianmanley-caci commented on pkg/services/mto_shipment/shipment_approver_test.go
> +	suite.Run("Given international mtoShipment is approved successfully pre-approved mtoServiceItems are created NTS OCONUS to CONUS", func() {
I think both test locations are backwards 😆 this says OCONUS to CONUS, but it's using IA - > AK and it's checking for 3 service items. The CONUS to OCONUS tests is going AK -> IA.

2024-12-20 15:22 UTC, KonstanceH commented on pkg/services/mto_shipment/shipment_approver_test.go
> +	suite.Run("Given international mtoShipment is approved successfully pre-approved mtoServiceItems are created NTS OCONUS to CONUS", func() {
WHEW not only that but the asserts lol I think it should be good now lol

2024-12-20 15:41 UTC, KonstanceH commented on pkg/services/mto_shipment/shipment_approver_test.go
> +	suite.Run("Given international mtoShipment is approved successfully pre-approved mtoServiceItems are created NTS OCONUS to CONUS", func() {
let me take a minute to make sure this is right because I think I keep mixing the logic lol

2025-01-07 19:32 UTC, danieljordan-caci requested changes
Got some questions

2025-01-07 19:32 UTC, danieljordan-caci commented on migrations/app/schema/20241218204620_add_international_nts_service_items.up.sql
> +    ('e702818f-defd-452c-81a3-865b902e7dd0', '388115e8-abe9-441d-96cf-a39f24baa0a3' ,'HHG_INTO_NTS', 'i', true, now(), now(), 2),
Will NTS shipments ever have a use case where they will be CONUS -> OCONUS? If so, we need to add `POEFSC` here.

2025-01-07 19:32 UTC, danieljordan-caci commented on pkg/services/mto_shipment/shipment_approver_test.go
> +			models.ReServiceCodeISLH,
Shouldn't this test check for a fuel surcharge as well?

2025-01-07 19:32 UTC, danieljordan-caci commented on pkg/services/mto_shipment/shipment_approver_test.go
> +			models.ReServiceCodeISLH,
If it is CONUS -> OCONUS then we should have a POEFSC service item

2025-01-07 19:34 UTC, begrohmann commented on migrations/app/schema/20241218204620_add_international_nts_service_items.up.sql
> +    ('e702818f-defd-452c-81a3-865b902e7dd0', '388115e8-abe9-441d-96cf-a39f24baa0a3' ,'HHG_INTO_NTS', 'i', true, now(), now(), 2),
No. This is an NTS Retrograde and still ships to a CONUS facility. That work is coming later.

2025-01-07 19:38 UTC, danieljordan-caci commented on migrations/app/schema/20241218204620_add_international_nts_service_items.up.sql
> +    ('e702818f-defd-452c-81a3-865b902e7dd0', '388115e8-abe9-441d-96cf-a39f24baa0a3' ,'HHG_INTO_NTS', 'i', true, now(), now(), 2),
coo coo - resolving

2025-01-07 19:39 UTC, danieljordan-caci commented on pkg/services/mto_shipment/shipment_approver_test.go
> +			models.ReServiceCodeISLH,
Per Beth's comment - won't need POEFSC. Resolving.

2025-01-07 19:41 UTC, begrohmann commented on pkg/services/mto_shipment/shipment_approver_test.go
> +			models.ReServiceCodeISLH,
HHG_INTO_NTS would always have a CONUS destination

2025-01-08 14:35 UTC, brianmanley-caci commented on pkg/services/mto_shipment/mto_shipment_updater_test.go
> +		for i := range expectedReServiceCodes {
Is this loop needed?

2025-01-08 15:46 UTC, KonstanceH commented on pkg/services/mto_shipment/mto_shipment_updater.go
> +		if shipment.MarketCode != models.MarketCodeInternational {
yea that makes sense I think I assumed it wouldn't work without the added handling of each case's international service items, but nothings breaking so I'm making this change and I'm gonna push it up now.

2025-01-08 15:47 UTC, KonstanceH commented on pkg/services/mto_shipment/mto_shipment_updater_test.go
> +		for i := range expectedReServiceCodes {
No I think I just copied this function from somewhere else and built on it and left it in lol It'll be removed on this next push

2025-01-08 17:33 UTC, danieljordan-caci requested changes
Getting a `nil pointer dereference` error when approving a NTS shipment as TOO with OCONUS -> CONUS.

Looks to be erroring here in `mto_shipment_updater`:
```
		if newShipment.MarketCode == models.MarketCodeInternational &&
			(newShipment.PrimeEstimatedWeight != nil ||
				newShipment.PickupAddress != nil && newShipment.PickupAddress.PostalCode != dbShipment.PickupAddress.PostalCode ||
				newShipment.DestinationAddress != nil && newShipment.DestinationAddress.PostalCode != dbShipment.DestinationAddress.PostalCode ||
				newShipment.RequestedPickupDate != nil && newShipment.RequestedPickupDate.Format("2006-01-02") != dbShipment.RequestedPickupDate.Format("2006-01-02")) {
```

I just coded these changes and looks like `dbShipment.DestinationAddress` is `nil` for this specific NTS scenario

2025-01-08 17:38 UTC, danieljordan-caci commented
@KonstanceH adding this nil check fixed it, but should we consider shipment type in that check?
```
		if newShipment.MarketCode == models.MarketCodeInternational &&
			newShipment.PrimeEstimatedWeight != nil ||
			newShipment.PickupAddress != nil && dbShipment.PickupAddress != nil && newShipment.PickupAddress.PostalCode != dbShipment.PickupAddress.PostalCode ||
			newShipment.DestinationAddress != nil && dbShipment.DestinationAddress != nil && newShipment.DestinationAddress.PostalCode != dbShipment.DestinationAddress.PostalCode ||
			newShipment.RequestedPickupDate != nil && newShipment.RequestedPickupDate.Format("2006-01-02") != dbShipment.RequestedPickupDate.Format("2006-01-02") {
```

2025-01-08 17:39 UTC, danieljordan-caci commented
I also have a question - when we have a domestic NTS shipment, but it has an OCONUS storage facility... Should that still have domestic service items or the international ones?

2025-01-08 17:45 UTC, KonstanceH commented
> @KonstanceH adding this nil check fixed it, but should we consider shipment type in that check?
> 
> ```
> 		if newShipment.MarketCode == models.MarketCodeInternational &&
> 			newShipment.PrimeEstimatedWeight != nil ||
> 			newShipment.PickupAddress != nil && dbShipment.PickupAddress != nil && newShipment.PickupAddress.PostalCode != dbShipment.PickupAddress.PostalCode ||
> 			newShipment.DestinationAddress != nil && dbShipment.DestinationAddress != nil && newShipment.DestinationAddress.PostalCode != dbShipment.DestinationAddress.PostalCode ||
> 			newShipment.RequestedPickupDate != nil && newShipment.RequestedPickupDate.Format("2006-01-02") != dbShipment.RequestedPickupDate.Format("2006-01-02") {
> ```

Yea I think there should be a shipment type check for NTS shipments because they're the only ones that there's a conversion from storage address to destination address that happens in the db. But that makes me think doesn't that happen right after the NTS is created?

2025-01-08 17:48 UTC, taeJungCaci commented
> > @KonstanceH adding this nil check fixed it, but should we consider shipment type in that check?
> > ```
> > 		if newShipment.MarketCode == models.MarketCodeInternational &&
> > 			newShipment.PrimeEstimatedWeight != nil ||
> > 			newShipment.PickupAddress != nil && dbShipment.PickupAddress != nil && newShipment.PickupAddress.PostalCode != dbShipment.PickupAddress.PostalCode ||
> > 			newShipment.DestinationAddress != nil && dbShipment.DestinationAddress != nil && newShipment.DestinationAddress.PostalCode != dbShipment.DestinationAddress.PostalCode ||
> > 			newShipment.RequestedPickupDate != nil && newShipment.RequestedPickupDate.Format("2006-01-02") != dbShipment.RequestedPickupDate.Format("2006-01-02") {
> > ```
> 
> Yea I think there should be a shipment type check for NTS shipments because they're the only ones that there's a conversion from storage address to destination address that happens in the db. But that makes me think doesn't that happen right after the NTS is created?

Doesn't the TOO input the storage address if the customer created the NTS?

2025-01-08 17:50 UTC, brianmanley-caci commented
> I also have a question - when we have a domestic NTS shipment, but it has an OCONUS storage facility... Should that still have domestic service items or the international ones?
> 

Trying to understand this. If it has an OCONUS storage facility, it wouldn't be a domestic NTS right?

2025-01-08 17:50 UTC, KonstanceH commented
> I also have a question - when we have a domestic NTS shipment, but it has an OCONUS storage facility... Should that still have domestic service items or the international ones?
> 
> ![Screenshot 2025-01-08 at 11 39 02 AM](https://private-user-images.githubusercontent.com/136510600/401248899-59097c38-6d6c-4a11-a3bb-dfaae147e923.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzNTgzMDYsIm5iZiI6MTczNjM1ODAwNiwicGF0aCI6Ii8xMzY1MTA2MDAvNDAxMjQ4ODk5LTU5MDk3YzM4LTZkNmMtNGExMS1hM2JiLWRmYWFlMTQ3ZTkyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwOFQxNzQwMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzdkMDcxMDE4OTE0YTUxOWRhYzhiOWFkZTY4YjAwMzRkNzQ2MThmYTA1NWRiM2MzMDNiNWY3MWQ5YTY4YzYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dlPzLwCTgq7nEmbKgieJZRIlNr1AIFMgp4w_8Q2ZLXs)

They should have international ones. I must've messed something up on the creation I'm looking into now

2025-01-08 17:51 UTC, danieljordan-caci commented
> > @KonstanceH adding this nil check fixed it, but should we consider shipment type in that check?
> > ```
> > 		if newShipment.MarketCode == models.MarketCodeInternational &&
> > 			newShipment.PrimeEstimatedWeight != nil ||
> > 			newShipment.PickupAddress != nil && dbShipment.PickupAddress != nil && newShipment.PickupAddress.PostalCode != dbShipment.PickupAddress.PostalCode ||
> > 			newShipment.DestinationAddress != nil && dbShipment.DestinationAddress != nil && newShipment.DestinationAddress.PostalCode != dbShipment.DestinationAddress.PostalCode ||
> > 			newShipment.RequestedPickupDate != nil && newShipment.RequestedPickupDate.Format("2006-01-02") != dbShipment.RequestedPickupDate.Format("2006-01-02") {
> > ```
> 
> Yea I think there should be a shipment type check for NTS shipments because they're the only ones that there's a conversion from storage address to destination address that happens in the db. But that makes me think doesn't that happen right after the NTS is created?

The flow I did was:
SC creates customer
SC creates move & orders
SC creates two NTS shipments, one with a CONUS addy and one with OCONUS addy
SC submits move details
TOO reviews & is required to add a destination address
Received error when TOO tried to edit destination address of NTS with OCONUS pickup and CONUS storage

2025-01-08 17:51 UTC, taeJungCaci commented
> > I also have a question - when we have a domestic NTS shipment, but it has an OCONUS storage facility... Should that still have domestic service items or the international ones?
> > ![Screenshot 2025-01-08 at 11 39 02 AM](https://private-user-images.githubusercontent.com/136510600/401248899-59097c38-6d6c-4a11-a3bb-dfaae147e923.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzNTgzMDYsIm5iZiI6MTczNjM1ODAwNiwicGF0aCI6Ii8xMzY1MTA2MDAvNDAxMjQ4ODk5LTU5MDk3YzM4LTZkNmMtNGExMS1hM2JiLWRmYWFlMTQ3ZTkyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwOFQxNzQwMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzdkMDcxMDE4OTE0YTUxOWRhYzhiOWFkZTY4YjAwMzRkNzQ2MThmYTA1NWRiM2MzMDNiNWY3MWQ5YTY4YzYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dlPzLwCTgq7nEmbKgieJZRIlNr1AIFMgp4w_8Q2ZLXs)
> 
> They should have international ones. I must've messed something up on the creation I'm looking into now

I believe this is the same issue I raised @KonstanceH where the NTS is registering as `dNTS` instead of `iNTS` when the customer creates NTS and the TOO inputs the storage facility address.

2025-01-08 17:52 UTC, KonstanceH commented
> > > @KonstanceH adding this nil check fixed it, but should we consider shipment type in that check?
> > > ```
> > > 		if newShipment.MarketCode == models.MarketCodeInternational &&
> > > 			newShipment.PrimeEstimatedWeight != nil ||
> > > 			newShipment.PickupAddress != nil && dbShipment.PickupAddress != nil && newShipment.PickupAddress.PostalCode != dbShipment.PickupAddress.PostalCode ||
> > > 			newShipment.DestinationAddress != nil && dbShipment.DestinationAddress != nil && newShipment.DestinationAddress.PostalCode != dbShipment.DestinationAddress.PostalCode ||
> > > 			newShipment.RequestedPickupDate != nil && newShipment.RequestedPickupDate.Format("2006-01-02") != dbShipment.RequestedPickupDate.Format("2006-01-02") {
> > > ```
> > 
> > 
> > Yea I think there should be a shipment type check for NTS shipments because they're the only ones that there's a conversion from storage address to destination address that happens in the db. But that makes me think doesn't that happen right after the NTS is created?
> 
> Doesn't the TOO input the storage address if the customer created the NTS?

I don't think so? or at least I thought the customer could add the storage address from their creation of the nts.

2025-01-08 17:52 UTC, danieljordan-caci commented
> > I also have a question - when we have a domestic NTS shipment, but it has an OCONUS storage facility... Should that still have domestic service items or the international ones?
> 
> Trying to understand this. If it has an OCONUS storage facility, it wouldn't be a domestic NTS right?

Yeah we might have an upstream problem here because, in my head, if either the pickup/destination (in this case, pickup/storage) is OCONUS, the shipment needs to be international

2025-01-08 17:53 UTC, brianmanley-caci commented
> Yeah we might have an upstream problem here because, in my head, if either the pickup/destination (in this case, pickup/storage) is OCONUS, the shipment needs to be international

Yes, I would agree with that.

2025-01-08 17:54 UTC, danieljordan-caci commented
> > > > @KonstanceH adding this nil check fixed it, but should we consider shipment type in that check?
> > > > ```
> > > > 		if newShipment.MarketCode == models.MarketCodeInternational &&
> > > > 			newShipment.PrimeEstimatedWeight != nil ||
> > > > 			newShipment.PickupAddress != nil && dbShipment.PickupAddress != nil && newShipment.PickupAddress.PostalCode != dbShipment.PickupAddress.PostalCode ||
> > > > 			newShipment.DestinationAddress != nil && dbShipment.DestinationAddress != nil && newShipment.DestinationAddress.PostalCode != dbShipment.DestinationAddress.PostalCode ||
> > > > 			newShipment.RequestedPickupDate != nil && newShipment.RequestedPickupDate.Format("2006-01-02") != dbShipment.RequestedPickupDate.Format("2006-01-02") {
> > > > ```
> > > 
> > > 
> > > Yea I think there should be a shipment type check for NTS shipments because they're the only ones that there's a conversion from storage address to destination address that happens in the db. But that makes me think doesn't that happen right after the NTS is created?
> > 
> > 
> > Doesn't the TOO input the storage address if the customer created the NTS?
> 
> I don't think so? or at least I thought the customer could add the storage address from their creation of the nts.

Customer only provides the pickup address for NTS

2025-01-08 17:55 UTC, KonstanceH commented
> > > I also have a question - when we have a domestic NTS shipment, but it has an OCONUS storage facility... Should that still have domestic service items or the international ones?
> > > ![Screenshot 2025-01-08 at 11 39 02 AM](https://private-user-images.githubusercontent.com/136510600/401248899-59097c38-6d6c-4a11-a3bb-dfaae147e923.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzNTgzMDYsIm5iZiI6MTczNjM1ODAwNiwicGF0aCI6Ii8xMzY1MTA2MDAvNDAxMjQ4ODk5LTU5MDk3YzM4LTZkNmMtNGExMS1hM2JiLWRmYWFlMTQ3ZTkyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwOFQxNzQwMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzdkMDcxMDE4OTE0YTUxOWRhYzhiOWFkZTY4YjAwMzRkNzQ2MThmYTA1NWRiM2MzMDNiNWY3MWQ5YTY4YzYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dlPzLwCTgq7nEmbKgieJZRIlNr1AIFMgp4w_8Q2ZLXs)
> > 
> > 
> > They should have international ones. I must've messed something up on the creation I'm looking into now
> 
> I believe this is the same issue I raised @KonstanceH where the NTS is registering as `dNTS` instead of `iNTS` when the customer creates NTS and the TOO inputs the AK storage facility address.

OOH okay. Well then yea in that case we were just talking about this earlier. Its a bug. And its a special case for ONLY this case on editing dNTS shipments for the first time the shipment market code doesn't flip to international when the addresses are changed to OCONUS. I was waiting on direction from our scrum master to see how to go about getting the process started on reporting the bug.

2025-01-08 17:56 UTC, danieljordan-caci commented
> > > > I also have a question - when we have a domestic NTS shipment, but it has an OCONUS storage facility... Should that still have domestic service items or the international ones?
> > > > ![Screenshot 2025-01-08 at 11 39 02 AM](https://private-user-images.githubusercontent.com/136510600/401248899-59097c38-6d6c-4a11-a3bb-dfaae147e923.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzNTgzMDYsIm5iZiI6MTczNjM1ODAwNiwicGF0aCI6Ii8xMzY1MTA2MDAvNDAxMjQ4ODk5LTU5MDk3YzM4LTZkNmMtNGExMS1hM2JiLWRmYWFlMTQ3ZTkyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwOFQxNzQwMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzdkMDcxMDE4OTE0YTUxOWRhYzhiOWFkZTY4YjAwMzRkNzQ2MThmYTA1NWRiM2MzMDNiNWY3MWQ5YTY4YzYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dlPzLwCTgq7nEmbKgieJZRIlNr1AIFMgp4w_8Q2ZLXs)
> > > 
> > > 
> > > They should have international ones. I must've messed something up on the creation I'm looking into now
> > 
> > 
> > I believe this is the same issue I raised @KonstanceH where the NTS is registering as `dNTS` instead of `iNTS` when the customer creates NTS and the TOO inputs the AK storage facility address.
> 
> OOH okay. Well then yea in that case we were just talking about this earlier. Its a bug. And its a special case for ONLY this case on editing dNTS shipments for the first time the shipment market code doesn't flip to international when the addresses are changed to OCONUS. I was waiting on direction from our scrum master to see how to go about getting the process started on reporting the bug.

Wouldn't that be a blocker for this work?

2025-01-08 18:01 UTC, KonstanceH commented
> > > > > I also have a question - when we have a domestic NTS shipment, but it has an OCONUS storage facility... Should that still have domestic service items or the international ones?
> > > > > ![Screenshot 2025-01-08 at 11 39 02 AM](https://private-user-images.githubusercontent.com/136510600/401248899-59097c38-6d6c-4a11-a3bb-dfaae147e923.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzNTgzMDYsIm5iZiI6MTczNjM1ODAwNiwicGF0aCI6Ii8xMzY1MTA2MDAvNDAxMjQ4ODk5LTU5MDk3YzM4LTZkNmMtNGExMS1hM2JiLWRmYWFlMTQ3ZTkyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwOFQxNzQwMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzdkMDcxMDE4OTE0YTUxOWRhYzhiOWFkZTY4YjAwMzRkNzQ2MThmYTA1NWRiM2MzMDNiNWY3MWQ5YTY4YzYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dlPzLwCTgq7nEmbKgieJZRIlNr1AIFMgp4w_8Q2ZLXs)
> > > > 
> > > > 
> > > > They should have international ones. I must've messed something up on the creation I'm looking into now
> > > 
> > > 
> > > I believe this is the same issue I raised @KonstanceH where the NTS is registering as `dNTS` instead of `iNTS` when the customer creates NTS and the TOO inputs the AK storage facility address.
> > 
> > 
> > OOH okay. Well then yea in that case we were just talking about this earlier. Its a bug. And its a special case for ONLY this case on editing dNTS shipments for the first time the shipment market code doesn't flip to international when the addresses are changed to OCONUS. I was waiting on direction from our scrum master to see how to go about getting the process started on reporting the bug.
> 
> Wouldn't that be a blocker for this work?

I don't think so because the bug exists now in milmove. The code I'm adding works for this features AC. I think that bug has more to do with updating the shipment in general and that would effect more than the service items. But that's just my lowly dev thoughts lol I think this is a question for the government?

2025-01-08 18:04 UTC, taeJungCaci commented
> > > > > I also have a question - when we have a domestic NTS shipment, but it has an OCONUS storage facility... Should that still have domestic service items or the international ones?
> > > > > ![Screenshot 2025-01-08 at 11 39 02 AM](https://private-user-images.githubusercontent.com/136510600/401248899-59097c38-6d6c-4a11-a3bb-dfaae147e923.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzNTgzMDYsIm5iZiI6MTczNjM1ODAwNiwicGF0aCI6Ii8xMzY1MTA2MDAvNDAxMjQ4ODk5LTU5MDk3YzM4LTZkNmMtNGExMS1hM2JiLWRmYWFlMTQ3ZTkyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwOFQxNzQwMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzdkMDcxMDE4OTE0YTUxOWRhYzhiOWFkZTY4YjAwMzRkNzQ2MThmYTA1NWRiM2MzMDNiNWY3MWQ5YTY4YzYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dlPzLwCTgq7nEmbKgieJZRIlNr1AIFMgp4w_8Q2ZLXs)
> > > > 
> > > > 
> > > > They should have international ones. I must've messed something up on the creation I'm looking into now
> > > 
> > > 
> > > I believe this is the same issue I raised @KonstanceH where the NTS is registering as `dNTS` instead of `iNTS` when the customer creates NTS and the TOO inputs the AK storage facility address.
> > 
> > 
> > OOH okay. Well then yea in that case we were just talking about this earlier. Its a bug. And its a special case for ONLY this case on editing dNTS shipments for the first time the shipment market code doesn't flip to international when the addresses are changed to OCONUS. I was waiting on direction from our scrum master to see how to go about getting the process started on reporting the bug.
> 
> Wouldn't that be a blocker for this work?

A workaround - If you "edit shipment" for the 2nd time and then save with AK address - it switches to `iNTS`

2025-01-08 18:05 UTC, danieljordan-caci commented
> > > > > > I also have a question - when we have a domestic NTS shipment, but it has an OCONUS storage facility... Should that still have domestic service items or the international ones?
> > > > > > ![Screenshot 2025-01-08 at 11 39 02 AM](https://private-user-images.githubusercontent.com/136510600/401248899-59097c38-6d6c-4a11-a3bb-dfaae147e923.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzNTgzMDYsIm5iZiI6MTczNjM1ODAwNiwicGF0aCI6Ii8xMzY1MTA2MDAvNDAxMjQ4ODk5LTU5MDk3YzM4LTZkNmMtNGExMS1hM2JiLWRmYWFlMTQ3ZTkyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwOFQxNzQwMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzdkMDcxMDE4OTE0YTUxOWRhYzhiOWFkZTY4YjAwMzRkNzQ2MThmYTA1NWRiM2MzMDNiNWY3MWQ5YTY4YzYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dlPzLwCTgq7nEmbKgieJZRIlNr1AIFMgp4w_8Q2ZLXs)
> > > > > 
> > > > > 
> > > > > They should have international ones. I must've messed something up on the creation I'm looking into now
> > > > 
> > > > 
> > > > I believe this is the same issue I raised @KonstanceH where the NTS is registering as `dNTS` instead of `iNTS` when the customer creates NTS and the TOO inputs the AK storage facility address.
> > > 
> > > 
> > > OOH okay. Well then yea in that case we were just talking about this earlier. Its a bug. And its a special case for ONLY this case on editing dNTS shipments for the first time the shipment market code doesn't flip to international when the addresses are changed to OCONUS. I was waiting on direction from our scrum master to see how to go about getting the process started on reporting the bug.
> > 
> > 
> > Wouldn't that be a blocker for this work?
> 
> A workaround - If you "edit shipment" for the 2nd time and then save with AK address - it switches to `iNTS`

Is there an issue created for this bug? @KonstanceH @taeJungCaci

2025-01-08 18:07 UTC, KonstanceH commented
> > > > > > I also have a question - when we have a domestic NTS shipment, but it has an OCONUS storage facility... Should that still have domestic service items or the international ones?
> > > > > > ![Screenshot 2025-01-08 at 11 39 02 AM](https://private-user-images.githubusercontent.com/136510600/401248899-59097c38-6d6c-4a11-a3bb-dfaae147e923.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzNTgzMDYsIm5iZiI6MTczNjM1ODAwNiwicGF0aCI6Ii8xMzY1MTA2MDAvNDAxMjQ4ODk5LTU5MDk3YzM4LTZkNmMtNGExMS1hM2JiLWRmYWFlMTQ3ZTkyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwOFQxNzQwMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzdkMDcxMDE4OTE0YTUxOWRhYzhiOWFkZTY4YjAwMzRkNzQ2MThmYTA1NWRiM2MzMDNiNWY3MWQ5YTY4YzYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dlPzLwCTgq7nEmbKgieJZRIlNr1AIFMgp4w_8Q2ZLXs)
> > > > > 
> > > > > 
> > > > > They should have international ones. I must've messed something up on the creation I'm looking into now
> > > > 
> > > > 
> > > > I believe this is the same issue I raised @KonstanceH where the NTS is registering as `dNTS` instead of `iNTS` when the customer creates NTS and the TOO inputs the AK storage facility address.
> > > 
> > > 
> > > OOH okay. Well then yea in that case we were just talking about this earlier. Its a bug. And its a special case for ONLY this case on editing dNTS shipments for the first time the shipment market code doesn't flip to international when the addresses are changed to OCONUS. I was waiting on direction from our scrum master to see how to go about getting the process started on reporting the bug.
> > 
> > 
> > Wouldn't that be a blocker for this work?
> 
> A workaround - If you "edit shipment" for the 2nd time and then save with AK address - it switches to `iNTS`

Yea this^^  also  they could create a new shipment for the marketCode change and delete the old one

2025-01-08 18:09 UTC, KonstanceH commented
> > > > > > > I also have a question - when we have a domestic NTS shipment, but it has an OCONUS storage facility... Should that still have domestic service items or the international ones?
> > > > > > > ![Screenshot 2025-01-08 at 11 39 02 AM](https://private-user-images.githubusercontent.com/136510600/401248899-59097c38-6d6c-4a11-a3bb-dfaae147e923.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzNTgzMDYsIm5iZiI6MTczNjM1ODAwNiwicGF0aCI6Ii8xMzY1MTA2MDAvNDAxMjQ4ODk5LTU5MDk3YzM4LTZkNmMtNGExMS1hM2JiLWRmYWFlMTQ3ZTkyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwOFQxNzQwMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzdkMDcxMDE4OTE0YTUxOWRhYzhiOWFkZTY4YjAwMzRkNzQ2MThmYTA1NWRiM2MzMDNiNWY3MWQ5YTY4YzYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dlPzLwCTgq7nEmbKgieJZRIlNr1AIFMgp4w_8Q2ZLXs)
> > > > > > 
> > > > > > 
> > > > > > They should have international ones. I must've messed something up on the creation I'm looking into now
> > > > > 
> > > > > 
> > > > > I believe this is the same issue I raised @KonstanceH where the NTS is registering as `dNTS` instead of `iNTS` when the customer creates NTS and the TOO inputs the AK storage facility address.
> > > > 
> > > > 
> > > > OOH okay. Well then yea in that case we were just talking about this earlier. Its a bug. And its a special case for ONLY this case on editing dNTS shipments for the first time the shipment market code doesn't flip to international when the addresses are changed to OCONUS. I was waiting on direction from our scrum master to see how to go about getting the process started on reporting the bug.
> > > 
> > > 
> > > Wouldn't that be a blocker for this work?
> > 
> > 
> > A workaround - If you "edit shipment" for the 2nd time and then save with AK address - it switches to `iNTS`
> 
> Is there an issue created for this bug? @KonstanceH @taeJungCaci

Yea that was the part about waiting on the hear back on how to report it lol
For bug issues can we just create them ourselves/follow the issue template and go on about our day? or is there more to it?
Because if I can just do it myself I'll make one now

2025-01-08 18:16 UTC, KonstanceH commented
> > > Is there an issue created for this bug? @KonstanceH @taeJungCaci
> > 
> > 
> > Yea @danieljordan-caci that was the part about waiting to hear back on how to report it lol For bug issues can we just create them ourselves/follow the issue template and go on about our day? or is there more to it? Because if I can just do it myself I'll make one now
> 
> Oh yeah I create issues all the time! Ideal process is to create the issue, provide analysis & fix, testers confirm, get PO to create a BL from the issue -> fix the issue

oh nice! I'll get on it now and tag the issue in this pr

2025-01-08 18:23 UTC, danieljordan-caci commented
> > > > Is there an issue created for this bug? @KonstanceH @taeJungCaci
> > > 
> > > 
> > > Yea @danieljordan-caci that was the part about waiting to hear back on how to report it lol For bug issues can we just create them ourselves/follow the issue template and go on about our day? or is there more to it? Because if I can just do it myself I'll make one now
> > 
> > 
> > Oh yeah I create issues all the time! Ideal process is to create the issue, provide analysis & fix, testers confirm, get PO to create a BL from the issue -> fix the issue
> 
> oh nice! I'll get on it now and tag the issue in this pr

Cool cool. For now if you can get a fix in for that nil check, rest looks good.

2025-01-08 18:44 UTC, KonstanceH commented
> > > > > Is there an issue created for this bug? @KonstanceH @taeJungCaci
> > > > 
> > > > 
> > > > Yea @danieljordan-caci that was the part about waiting to hear back on how to report it lol For bug issues can we just create them ourselves/follow the issue template and go on about our day? or is there more to it? Because if I can just do it myself I'll make one now
> > > 
> > > 
> > > Oh yeah I create issues all the time! Ideal process is to create the issue, provide analysis & fix, testers confirm, get PO to create a BL from the issue -> fix the issue
> > 
> > 
> > oh nice! I'll get on it now and tag the issue in this pr
> 
> Cool cool. For now if you can get a fix in for that nil check, rest looks good.

Okay the issue is created adding it here for reference:

2025-01-08 21:20 UTC, danieljordan-caci requested changes

2025-01-08 21:20 UTC, danieljordan-caci commented on pkg/services/mto_shipment/mto_shipment_updater.go
> +			newShipment.ShipmentType == models.MTOShipmentTypeHHGIntoNTS || newShipment.ShipmentType == models.MTOShipmentTypeHHGOutOfNTSDom {
This specific function is addressing updating estimated pricing for this shipment type. Has the upstream db functions/procs been updated to accommodate international NTS & NTSr shipments?

2025-01-08 21:20 UTC, danieljordan-caci commented on pkg/services/mto_shipment/mto_shipment_updater.go
> +			newShipment.ShipmentType == models.MTOShipmentTypeHHGIntoNTS || newShipment.ShipmentType == models.MTOShipmentTypeHHGOutOfNTSDom {
You also are eliminating this check for iHHG moves, which is what it was originally created for.

2025-01-08 22:41 UTC, KonstanceH commented on pkg/services/mto_shipment/mto_shipment_updater.go
> +			newShipment.ShipmentType == models.MTOShipmentTypeHHGIntoNTS || newShipment.ShipmentType == models.MTOShipmentTypeHHGOutOfNTSDom {
Okay this should be good now. I'll see about these failing circleCI tests tomorrow @_@

2025-01-10 14:58 UTC, KonstanceH commented on pkg/services/mto_shipment/mto_shipment_updater.go
> +			newShipment.ShipmentType == models.MTOShipmentTypeHHGIntoNTS || newShipment.ShipmentType == models.MTOShipmentTypeHHGOutOfNTSDom {
Okay was missing the parenthesis for precedence but finally got that nil check in and not breaking any tests :D

2025-01-13 15:15 UTC, taeJungCaci approved these changes

2025-01-13 18:29 UTC, danieljordan-caci commented
> > > > Is there an issue created for this bug? @KonstanceH @taeJungCaci
> > > 
> > > 
> > > Yea @danieljordan-caci that was the part about waiting to hear back on how to report it lol For bug issues can we just create them ourselves/follow the issue template and go on about our day? or is there more to it? Because if I can just do it myself I'll make one now
> > 
> > 
> > Oh yeah I create issues all the time! Ideal process is to create the issue, provide analysis & fix, testers confirm, get PO to create a BL from the issue -> fix the issue
> 
> oh nice! I'll get on it now and tag the issue in this pr

I see [an issue](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=I-13719) addressing this - thanks for adding that

2025-01-13 18:39 UTC, danieljordan-caci commented
Should this have a fuel surcharge service item for CONUS pickup -> OCONUS storage facility? Just making sure.

![Screenshot 2025-01-13 at 12 39 07 PM](https://github.com/user-attachments/assets/046a24cd-7d2d-49f9-9455-642a4d579836)

2025-01-13 19:17 UTC, KonstanceH commented
> Should this have a fuel surcharge service item for CONUS pickup -> OCONUS storage facility? Just making sure.
> 
> ![Screenshot 2025-01-13 at 12 39 07 PM](https://private-user-images.githubusercontent.com/136510600/402659010-046a24cd-7d2d-49f9-9455-642a4d579836.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY3OTU2NTMsIm5iZiI6MTczNjc5NTM1MywicGF0aCI6Ii8xMzY1MTA2MDAvNDAyNjU5MDEwLTA0NmEyNGNkLTdkMmQtNDlmOS05NDU1LTY0MmE0ZDU3OTgzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExM1QxOTA5MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MWZmODY4NmMzYzMwYjJjNTJlNWE4Zjc4YmQ0OTQ3ZTVhZjQ2NmU3MDJjOTQ5NDk3YTYxYjg3Zjk2ZDRlMTBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2abIJirrOcdmvv1QVU_hg60HKADiZjIwXRQOKcAJp7Y)

No I don't think so. In my AC it says there should only be a fuel surcharge for OCONUS pickup to CONUS destinations.
<img width="849" alt="Screenshot 2025-01-13 at 1 16 45 PM" src="https://github.com/user-attachments/assets/c933e637-bd95-4529-9860-b01c86fb573e" />

2025-01-13 19:20 UTC, JamesHawks224 approved these changes
testing: success
code: lgtm

2025-01-13 19:50 UTC, danieljordan-caci approved these changes
Meets AC - able to see the created service items after approving NTS shipments as TOO

2025-01-13 21:10 UTC, brianmanley-caci approved these changes
Thanks for working through all the questions/comments. It looks good and is working well for me 🎈

2025-01-13 21:13 UTC, merged