B-21488: Fixing UB Warning Message Display
transcom/mymove pull request #14398
Opened 2024-12-13 18:03 UTC by TevinAdams

## [Agility ticket](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-21488)
##[I-13640](https://www13.v1host.com/USTRANSCOM38/Issue.mvc/Summary?oidToken=Issue%3A1044154)

## Summary
This is a fix for the work pushed up for B-21488.  Forgot to add check for UB Shipments for the UB Excess weight logic.

The UB shipment excess weight warning was showing up on moves that had no UB shipments. This was because there was no condition added to stop the UB logic from running when there is no UB Shipments. Simple fix. Add a check for UB shipments where if there are UB shipments then run the logic if not skip it.

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-12-16 15:48 UTC, danieljordan-caci commented on pkg/services/move/move_weights.go
> +	if hasUbShipments && ((int(float32(ubWeightAllowance)*RiskOfExcessThreshold) <= sumOfWeights.SumEstimatedWeightOfUbShipments) || (int(float32(ubWeightAllowance)*RiskOfExcessThreshold) <= sumOfWeight
For readability, can you break this down like so?
```
threshold := int(float32(ubWeightAllowance) * RiskOfExcessThreshold)

isWeightExceedingThreshold := (threshold <= sumOfWeights.SumEstimatedWeightOfUbShipments) || (threshold <= sumOfWeights.SumActualWeightOfUbShipments)

if hasUbShipments && isWeightExceedingThreshold {
}
```

2024-12-16 15:48 UTC, danieljordan-caci commented on pkg/services/move/move_weights.go
> +	if hasUbShipments && ((int(float32(ubWeightAllowance)*RiskOfExcessThreshold) <= sumOfWeights.SumEstimatedWeightOfUbShipments) || (int(float32(ubWeightAllowance)*RiskOfExcessThreshold) <= sumOfWeight
It's just kind of an ugly mess to look at when it's one big ole line haha

2024-12-16 17:16 UTC, TevinAdams commented on pkg/services/move/move_weights.go
> +	if hasUbShipments && ((int(float32(ubWeightAllowance)*RiskOfExcessThreshold) <= sumOfWeights.SumEstimatedWeightOfUbShipments) || (int(float32(ubWeightAllowance)*RiskOfExcessThreshold) <= sumOfWeight
@danieljordan-caci  Done

2024-12-16 17:19 UTC, TevinAdams commented
> Didn't we agree to add a breakdown of UB stuff here? I remember that being a thing. @transcom/mountain-movers
> 
> ![Screenshot 2024-12-16 at 11 10 01 AM](https://private-user-images.githubusercontent.com/136510600/396196752-1d8dc861-f486-4777-a6b1-17e8152b25a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNjk0NDYsIm5iZiI6MTczNDM2OTE0NiwicGF0aCI6Ii8xMzY1MTA2MDAvMzk2MTk2NzUyLTFkOGRjODYxLWY0ODYtNDc3Ny1hNmIxLTE3ZTgxNTJiMjVhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNlQxNzEyMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDM4Y2VmNmU5NjU1NGFiZWYyODUyNGM5OWIwZDU0YjVjY2YyMTQ1ZTZiOGIzM2ZkYmY4MDFlZDQzYTg3N2IyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.SDATo4CaByp7i7VgEh0Q-orwhKSt80efZHMWY-cQ0SU)
> 
> Otherwise I'm able to see both alerts at the same time, does not show when there isn't a UB shipment. ![Screenshot 2024-12-16 at 11 12 17 AM](https://private-user-images.githubusercontent.com/136510600/396197598-601910dc-8284-4ad2-ba8c-e9fc3bf96291.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNjk0NDYsIm5iZiI6MTczNDM2OTE0NiwicGF0aCI6Ii8xMzY1MTA2MDAvMzk2MTk3NTk4LTYwMTkxMGRjLTgyODQtNGFkMi1iYThjLWU5ZmMzYmY5NjI5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNlQxNzEyMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jODk4ZTU2NjFmOTFkMjhmNzlhZTY5YjQ2MjNhNjk4NjM1NmI0NzhiYzFhODBlOWI5M2M0Y2Q1NzkzODlhYmQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2-MS3E_FrDyCaN_YCDHCZ13eAawMpnxEIqvEpZdBSlM)
> 
> Any thoughts on also adding a UI check to display the UB weight alert is the UB flag is on and the move contains UB shipments?

@traskowskycaci I believe someone else had a story for that. I remember at PI planning Maria showed me and Cameron a box with the UB allowance. But someone else did that.

2024-12-16 17:25 UTC, ajlusk commented
Not a review since I don't know the details about all the other stuff but the scenario in which I encountered this issue appears to be resolved.

2024-12-16 17:33 UTC, danieljordan-caci requested changes
In addition to my outstanding questions, it looks like the action count is off.
This should say `2` in the action flags, but only says `1`
![Screenshot 2024-12-16 at 11 31 19 AM](https://github.com/user-attachments/assets/6772aaae-6fd4-41d9-b7f3-4d86e9573bfd)

Also when I dismissed the non-UB alert, the move status changed to `APPROVED`, but I still had the UB one present.
move is approved
![Screenshot 2024-12-16 at 11 33 03 AM](https://github.com/user-attachments/assets/b2b94472-0cf7-4705-ae85-96fc65960689)
still have an action
![Screenshot 2024-12-16 at 11 33 11 AM](https://github.com/user-attachments/assets/b1c14208-2d9d-4cd4-becf-c4d1deef8c77)

2024-12-16 17:46 UTC, TevinAdams commented
> > > Didn't we agree to add a breakdown of UB stuff here? I remember that being a thing. @transcom/mountain-movers
> > > ![Screenshot 2024-12-16 at 11 10 01 AM](https://private-user-images.githubusercontent.com/136510600/396196752-1d8dc861-f486-4777-a6b1-17e8152b25a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNjk0NDYsIm5iZiI6MTczNDM2OTE0NiwicGF0aCI6Ii8xMzY1MTA2MDAvMzk2MTk2NzUyLTFkOGRjODYxLWY0ODYtNDc3Ny1hNmIxLTE3ZTgxNTJiMjVhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNlQxNzEyMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDM4Y2VmNmU5NjU1NGFiZWYyODUyNGM5OWIwZDU0YjVjY2YyMTQ1ZTZiOGIzM2ZkYmY4MDFlZDQzYTg3N2IyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.SDATo4CaByp7i7VgEh0Q-orwhKSt80efZHMWY-cQ0SU)
> > > Otherwise I'm able to see both alerts at the same time, does not show when there isn't a UB shipment. ![Screenshot 2024-12-16 at 11 12 17 AM](https://private-user-images.githubusercontent.com/136510600/396197598-601910dc-8284-4ad2-ba8c-e9fc3bf96291.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNjk0NDYsIm5iZiI6MTczNDM2OTE0NiwicGF0aCI6Ii8xMzY1MTA2MDAvMzk2MTk3NTk4LTYwMTkxMGRjLTgyODQtNGFkMi1iYThjLWU5ZmMzYmY5NjI5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNlQxNzEyMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jODk4ZTU2NjFmOTFkMjhmNzlhZTY5YjQ2MjNhNjk4NjM1NmI0NzhiYzFhODBlOWI5M2M0Y2Q1NzkzODlhYmQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2-MS3E_FrDyCaN_YCDHCZ13eAawMpnxEIqvEpZdBSlM)
> > > Any thoughts on also adding a UI check to display the UB weight alert is the UB flag is on and the move contains UB shipments?
> > 
> > 
> > @traskowskycaci I believe someone else had a story for that. I remember at PI planning Maria showed me and Cameron a box with the UB allowance. But someone else did that. There was a box specific to UB from what I saw.
> 
> There is not an additional BL that I'm seeing that is covering this work.
Its fine ill add something similar to what i saw. A box to the right with UB allowance information?

2024-12-16 17:47 UTC, danieljordan-caci commented
> > > > Didn't we agree to add a breakdown of UB stuff here? I remember that being a thing. @transcom/mountain-movers
> > > > ![Screenshot 2024-12-16 at 11 10 01 AM](https://private-user-images.githubusercontent.com/136510600/396196752-1d8dc861-f486-4777-a6b1-17e8152b25a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNjk0NDYsIm5iZiI6MTczNDM2OTE0NiwicGF0aCI6Ii8xMzY1MTA2MDAvMzk2MTk2NzUyLTFkOGRjODYxLWY0ODYtNDc3Ny1hNmIxLTE3ZTgxNTJiMjVhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNlQxNzEyMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDM4Y2VmNmU5NjU1NGFiZWYyODUyNGM5OWIwZDU0YjVjY2YyMTQ1ZTZiOGIzM2ZkYmY4MDFlZDQzYTg3N2IyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.SDATo4CaByp7i7VgEh0Q-orwhKSt80efZHMWY-cQ0SU)
> > > > Otherwise I'm able to see both alerts at the same time, does not show when there isn't a UB shipment. ![Screenshot 2024-12-16 at 11 12 17 AM](https://private-user-images.githubusercontent.com/136510600/396197598-601910dc-8284-4ad2-ba8c-e9fc3bf96291.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNjk0NDYsIm5iZiI6MTczNDM2OTE0NiwicGF0aCI6Ii8xMzY1MTA2MDAvMzk2MTk3NTk4LTYwMTkxMGRjLTgyODQtNGFkMi1iYThjLWU5ZmMzYmY5NjI5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNlQxNzEyMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jODk4ZTU2NjFmOTFkMjhmNzlhZTY5YjQ2MjNhNjk4NjM1NmI0NzhiYzFhODBlOWI5M2M0Y2Q1NzkzODlhYmQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2-MS3E_FrDyCaN_YCDHCZ13eAawMpnxEIqvEpZdBSlM)
> > > > Any thoughts on also adding a UI check to display the UB weight alert is the UB flag is on and the move contains UB shipments?
> > > 
> > > 
> > > @traskowskycaci I believe someone else had a story for that. I remember at PI planning Maria showed me and Cameron a box with the UB allowance. But someone else did that. There was a box specific to UB from what I saw.
> > 
> > 
> > There is not an additional BL that I'm seeing that is covering this work.
> > Its fine ill add something similar to what i saw. A box to the right with UB allowance information?

No, you need to append to what's already there - underneath the "Hide Breakdown" section.

2024-12-16 20:43 UTC, TevinAdams commented
> > > Didn't we agree to add a breakdown of UB stuff here? I remember that being a thing. @transcom/mountain-movers
> > > ![Screenshot 2024-12-16 at 11 10 01 AM](https://private-user-images.githubusercontent.com/136510600/396196752-1d8dc861-f486-4777-a6b1-17e8152b25a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNjk0NDYsIm5iZiI6MTczNDM2OTE0NiwicGF0aCI6Ii8xMzY1MTA2MDAvMzk2MTk2NzUyLTFkOGRjODYxLWY0ODYtNDc3Ny1hNmIxLTE3ZTgxNTJiMjVhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNlQxNzEyMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDM4Y2VmNmU5NjU1NGFiZWYyODUyNGM5OWIwZDU0YjVjY2YyMTQ1ZTZiOGIzM2ZkYmY4MDFlZDQzYTg3N2IyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.SDATo4CaByp7i7VgEh0Q-orwhKSt80efZHMWY-cQ0SU)
> > > Otherwise I'm able to see both alerts at the same time, does not show when there isn't a UB shipment. ![Screenshot 2024-12-16 at 11 12 17 AM](https://private-user-images.githubusercontent.com/136510600/396197598-601910dc-8284-4ad2-ba8c-e9fc3bf96291.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNjk0NDYsIm5iZiI6MTczNDM2OTE0NiwicGF0aCI6Ii8xMzY1MTA2MDAvMzk2MTk3NTk4LTYwMTkxMGRjLTgyODQtNGFkMi1iYThjLWU5ZmMzYmY5NjI5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNlQxNzEyMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jODk4ZTU2NjFmOTFkMjhmNzlhZTY5YjQ2MjNhNjk4NjM1NmI0NzhiYzFhODBlOWI5M2M0Y2Q1NzkzODlhYmQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2-MS3E_FrDyCaN_YCDHCZ13eAawMpnxEIqvEpZdBSlM)
> > > Any thoughts on also adding a UI check to display the UB weight alert is the UB flag is on and the move contains UB shipments?
> > 
> > 
> > @traskowskycaci I believe someone else had a story for that. I remember at PI planning Maria showed me and Cameron a box with the UB allowance. But someone else did that. There was a box specific to UB from what I saw.
> 
> There is not an additional BL that I'm seeing that is covering this work.

@danieljordan-caci Breakdown added
![image](https://github.com/user-attachments/assets/bcf5719c-576b-42b0-8097-ce0315f9f4a7)

2024-12-16 20:45 UTC, TevinAdams commented
> Member

@danieljordan-caci Excess Risk count has been fixed
![image](https://github.com/user-attachments/assets/886afb72-bc99-43cd-a0db-50d808232434)

2024-12-17 16:53 UTC, danieljordan-caci requested changes

2024-12-17 16:53 UTC, danieljordan-caci commented on src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
> +      </div>
Need a test

2024-12-17 19:30 UTC, TevinAdams commented on src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
> +      </div>
@danieljordan-caci  test added

2024-12-18 22:59 UTC, traskowskycaci reviewed
Huddled with Tevin for a demo of the UI here, had a few questions on whether we want to allow multiple excess weight acknowledgements to happen, and whether we want to keep the move in approvals requested until all excess weight risks are acknowledged, when there are multiple, one for the move and one for UBs

2024-12-19 16:12 UTC, traskowskycaci approved these changes
Would be good to get this tested and in front of the PO, and see if the questions I had arise and discuss how we'd like to handle that work

2024-12-19 21:45 UTC, danieljordan-caci approved these changes

2024-12-20 19:56 UTC, danieljordan-caci approved these changes

2024-12-23 18:45 UTC, paulstonebraker approved these changes

2024-12-26 15:37 UTC, merged