B 21557 INT find Estimated price when shipment is updated with an estimated weight where there isn't one previously
transcom/mymove pull request #14448
Opened 2024-12-19 21:23 UTC by joeydoyecaci

## [B-21557](https://www13.v1host.com/USTRANSCOM38/TeamRoom.mvc/Show/848240)
## [INT PR](https://github.com/transcom/mymove/pull/14427)
## Summary

Updates the price estimates on service items where an estimated weight wasn't initially provided.

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Create a move as an HHG shipment, or find an existing move that is already approved
2. As a SC add an HHG shipment to the move. but do not add an estimated weight
3. Verify on the move task order tab that the service items are added, leave the tab open
4. Open a separate tab and find the move as a prime user
5. update the new mto shipment within the move with an estimated weight
6. back on the SC tab, refresh the mto shipment tab, the prices should now show next to the service items

2024-12-20 16:17 UTC, traskowskycaci commented
> ## [B-21557](https://www13.v1host.com/USTRANSCOM38/TeamRoom.mvc/Show/848240)
> ## Summary
> Updates the price estimates on service items where an estimated weight wasn't initially provided.
> 
> ### How to test
> 1. Create a move as an HHG shipment, or find an existing move that is already approved
> 2. As a SC add an HHG shipment to the move. but do not add an estimated weight
> 3. Verify on the move task order tab that the service items are added, leave the tab open
> 4. Open a separate tab and find the move as a prime user
> 5. update the new mto shipment within the move with an estimated weight
> 6. back on the SC tab, refresh the mto shipment tab, the prices should now show next to the service items

Can you update the testing instructions to include running `make tasks_save_ghc_fuel_price_data`? If this isn't run, those tesitng won't see a price for the Fuel Surcharge (FSC) service item

2024-12-20 16:34 UTC, traskowskycaci requested changes

2024-12-26 14:24 UTC, joeydoyecaci commented
> > ## [B-21557](https://www13.v1host.com/USTRANSCOM38/TeamRoom.mvc/Show/848240)
> > ## Summary
> > Updates the price estimates on service items where an estimated weight wasn't initially provided.
> > ### How to test
> > 
> > 1. Create a move as an HHG shipment, or find an existing move that is already approved
> > 2. As a SC add an HHG shipment to the move. but do not add an estimated weight
> > 3. Verify on the move task order tab that the service items are added, leave the tab open
> > 4. Open a separate tab and find the move as a prime user
> > 5. update the new mto shipment within the move with an estimated weight
> > 6. back on the SC tab, refresh the mto shipment tab, the prices should now show next to the service items
> 
> Can you update the testing instructions to include running `make tasks_save_ghc_fuel_price_data`? If this isn't run, those testing won't see a price for the Fuel Surcharge (FSC) service item

Done!

2024-12-26 16:54 UTC, joeydoyecaci commented on pkg/services/mto_service_item/mto_service_item_creator.go
> +	if mtoShipment.PrimeEstimatedWeight != nil && mtoShipment.RequestedPickupDate != nil && mtoShipment.ShipmentType != models.MTOShipmentTypeHHGOutOfNTSDom {
Done!

2024-12-26 19:00 UTC, traskowskycaci submitted a review, later dismissed
Seeing estimated prices when prime provides estimated weight for HHGs:
<img width="926" alt="image" src="https://github.com/user-attachments/assets/26f8afad-4371-4cb9-b686-3916557a2a25" />

Also seeing prices on an NTS-R shipment:
<img width="851" alt="image" src="https://github.com/user-attachments/assets/373bd2b8-e3f0-4168-b647-dae9e71ef59c" />

2024-12-26 21:09 UTC, danieljordan-caci commented on pkg/services/orchestrators/shipment/shipment_updater.go
> +		}
What is with the switching between the `shipment` and `mtoShipment` variables in here? Which one should take priority with the logic checks? Seems strange to bounce between two different objects - which one is the most updated?

2024-12-26 21:10 UTC, danieljordan-caci commented on pkg/services/orchestrators/shipment/shipment_updater.go
> +					serviceItemEstimatedPrice, err := s.mtoServiceItemCreator.FindEstimatedPrice(appCtx, &serviceItem, *mtoShipment)
Is there an `else` check here that returns the `err` value here?

2024-12-27 16:59 UTC, joeydoyecaci commented on pkg/services/orchestrators/shipment/shipment_updater.go
> +		}
Technically mtoShipment would represent what should've been saved in the DB with shipment being the "delta". But I've come across updateMtoShipment doesn't always consistently return the estimated weight with the mtoShipment when updated. 

So to protect from this it'll check if either the delta (shipment) or updated (mtoShipment) has the estimated weight populated. If the delta does have it, then use that by default. If not, then use the mtoShipment to prevent attempting to price service items sans a weight (and summarily failing due to nil pointer errors)

2024-12-27 17:12 UTC, loganwc approved these changes

2024-12-27 17:12 UTC, joeydoyecaci commented on pkg/services/orchestrators/shipment/shipment_updater.go
> +					serviceItemEstimatedPrice, err := s.mtoServiceItemCreator.FindEstimatedPrice(appCtx, &serviceItem, *mtoShipment)
I was initially trying to condense when these occur for coverage related reasons. I've added in a separate if block instead.

2024-12-27 19:05 UTC, danieljordan-caci commented on pkg/services/orchestrators/shipment/shipment_updater.go
> +		}
Gotcha, makes sense. Thanks for the explanation.

2024-12-27 19:09 UTC, danieljordan-caci commented
Is there a reason this BL is estimated at 13 points? Is that an accurate LOE? That seems super inflated.

2024-12-27 21:42 UTC, joeydoyecaci commented
> Is there a reason this BL is estimated at 13 points? Is that an accurate LOE? That seems super inflated.

It was meant to be much lower, there were some complications with getting the unit tests to work specifically for UpdateShipment.

2025-01-03 13:59 UTC, pambecker approved these changes

2025-01-03 14:58 UTC, merged