B21576 int add order types for sc too
transcom/mymove pull request #14446
Opened 2024-12-19 20:39 UTC by JamesHawks224

## Agility ticket
[B21576](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-21576)

## Notes
This PR is a remake of prior PR.  Prior PR was: [14164](https://github.com/transcom/mymove/pull/14091)

## Summary
In B21575, 2 new order types were added for the customer:  Student Travel, Early Return of Dependents.  B21576 adds these new order types for SC and TOO.  When the SC edits orders, they will be able to select the new order types and "has dependents" will update to "yes" on the backend.  In addition, the new order types will display in the "Orders" section of the "Move Details Page" for the SC or TOO.  And, finally, when SC creates a move, the "Orders" page will behave exactly like the customer version of this page.

### How to test
In the .envrc.local file, add the following to turn on the feature flag:
export FEATURE_FLAG_ENABLE_ALASKA=true
restart server and client

* Create a move with a HHG shipment and submit it.
  - On the Orders page,
    * Set order type to: permanent change of station
    * Set has dependents to: no.
* Keep the customer page open.  The orders section will be viewed to confirm changes.

Scenario 1: Creating a move
* login as a customer
* create a move
* at the move orders page ("tell us about your move orders")
  - set initial values all fields:
    - order type: Permanent Change of Station
    - remaining fields: any value is fine
* verification
  - verify: order type,  changing existing type to another existing type
    - change order type to local move
    - verify no fields are changed
  - verify: order type, changing existing type to new type (student travel)
    - change order type to student travel
    - verify "are dependents included" defaults to "yes"
    - verify "are dependents included" is disabled
  - verify: order type, changing new type (student travel) to existing type
    - change order type to permanent change of station
    - verify "are dependents included" defaults to no selection
    - verify "are dependents included" is enabled
  - verify: order type, changing existing type to new type (early return of dependents)
    - change order type to student travel
    - verify "are dependents included" defaults to "yes"
    - verify "are dependents included" is disabled
  - verify: order type, changing new type (early return of dependents) to existing type
    - change order type to permanent change of station
    - verify "are dependents included" defaults to no selection
    - verify "are dependents included" is enabled
  - verify: order type, changing new type (early return of dependents) to to new type (student travel)
    - change order type to early return of dependents
    - verify "are dependents included" defaults to "yes"
    - verify "are dependents included" is disabled
    - change order type to student travel
    - verify "are dependents included" defaults to "yes"
    - verify "are dependents included" is disabled
* finish creating the move w/a ppm shipment.

Scenario 2: edit existing orders
* login as a customer
* use the move just created in scenario 1
* click on "review your request"
* edit orders
* on the "edit orders" page, set the initial values the same as in scenario 1
* perform verification the same verification as in scenario 1.
* save the page

Scenario 3: turn off feature flag
In the .envrc.local file, add the following to turn on the feature flag:
export FEATURE_FLAG_ENABLE_ALASKA=false
restart server and client
* Create a move: On the orders page, verify neither Student Travel or Early Return of Dependents shows up in the drop down list
* Edit a move: On the orders page, verify neither Student Travel or Early Return of Dependents shows up in the drop down list

## ANDI Screenshots
Creating a move:
![image](https://github.com/user-attachments/assets/7eaf2b15-612b-4558-95d7-ecaeb938f7b8)

Editing existing orders:
![image](https://github.com/user-attachments/assets/b71fc586-4274-4705-87b6-80e0eea0ffc0)

## Testing Screenshots
N/A

2024-12-31 16:59 UTC, taeJungCaci requested changes
I also see a client test failing that maybe be related to your changes

2024-12-31 16:59 UTC, taeJungCaci commented on src/components/Office/AddOrdersForm/AddOrdersForm.test.jsx
> +
I think you may be missing the checks to see if the radio buttons are checked and disabled.
I think this would be needed to test if the buttons were disabled and then re-enabled.

```
await userEvent.selectOptions(screen.getByLabelText('Orders type'), ORDERS_TYPE.STUDENT_TRAVEL);
const hasDependentsYes = screen.getByLabelText('Yes');
const hasDependentsNo = screen.getByLabelText('No');

await waitFor(() => {
  expect(hasDependentsYes).toBeChecked();
  expect(hasDependentsYes).toBeDisabled();
  expect(hasDependentsNo).toBeDisabled();
});
```

2024-12-31 16:59 UTC, taeJungCaci commented on src/components/Office/AddOrdersForm/AddOrdersForm.test.jsx
> +
Same missing checks here

2024-12-31 17:19 UTC, taeJungCaci commented
Also noting the concern here that edit orders page doesn't have an option to choose "has dependent" for office users. This means if SC chooses`Student Travel` and then saves -> then goes back and chooses a different orders type -> the `has_dependent` will remain `true`.

2025-01-03 18:16 UTC, JamesHawks224 commented on src/components/Office/AddOrdersForm/AddOrdersForm.test.jsx
> +
Code has been updated.  Please re-review.

2025-01-03 18:16 UTC, JamesHawks224 commented on src/components/Office/AddOrdersForm/AddOrdersForm.test.jsx
> +
Code has been updated. Please re-review.

2025-01-03 18:18 UTC, JamesHawks224 commented
> Also noting the concern here that edit orders page doesn't have an option to choose "has dependent" for office users. This means if SC chooses`Student Travel` and then saves -> then goes back and chooses a different orders type -> the `has_dependent` will remain `true`.

I'll need to bring this to Gary's attention and get his feedback.

2025-01-03 18:43 UTC, taeJungCaci approved these changes

2025-01-08 00:00 UTC, WeatherfordAaron reviewed
Happo is complaining about the lbs now showing up as 0 for allowance (at the top).
That's not anything that was messed with here was it?

2025-01-09 15:16 UTC, taeJungCaci requested changes

2025-01-09 15:16 UTC, taeJungCaci commented on .circleci/config.yml
> +  dp3-env: &dp3-env placeholder_env
Would this be an accidental change?

2025-01-09 16:08 UTC, deandreJones commented on .circleci/config.yml
> +  dp3-env: &dp3-env placeholder_env
yea this needs to remain as loadtest

2025-01-09 16:53 UTC, taeJungCaci approved these changes

2025-01-13 15:16 UTC, WeatherfordAaron approved these changes
lgtm 👽

2025-01-13 17:45 UTC, merged