B 22132 int fix link amend orders
transcom/mymove pull request #14440
Opened 2024-12-19 17:11 UTC by loganwc

## [Agility ticket](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A1046702)

## Summary

Fix dead link

### How to test

1. Login to a customer with a submitted/approved move
2. Click the 'Upload a copy of your new orders' link
3. Navigates to orders amend page

![Screenshot 2024-12-18 at 1 33 36 PM](https://github.com/user-attachments/assets/67e15162-4264-44ac-acce-227f13c51138)

2024-12-23 16:13 UTC, deandreJones commented
Take a look at the happo, one of them is broke as a result of your change

2024-12-23 16:15 UTC, deandreJones submitted a review, later dismissed
Happo needs attention

2024-12-23 16:17 UTC, antgmann requested changes
Please check that all locations that use HelperApprovedMove are provided an orderId!

2024-12-23 16:17 UTC, antgmann commented on src/pages/MyMove/Home/HomeHelpers.jsx
> +export const HelperApprovedMove = ({ orderId }) => {
Looks like this param needs to be added to storybook. Please check that all locations that use HelperApprovedMove provide this!

2024-12-27 17:02 UTC, loganwc commented on src/pages/MyMove/Home/HomeHelpers.jsx
> +export const HelperApprovedMove = ({ orderId }) => {
Resolved the Happo issue

2024-12-30 15:50 UTC, JonSpight approved these changes

2024-12-30 20:17 UTC, antgmann reviewed
Accepted Happo diffs, not sure why playwright for ppm packets is failing

Edit: Apparently it's just unmarked flakiness

2024-12-31 01:58 UTC, pambecker approved these changes

2025-01-02 13:46 UTC, antgmann approved these changes

2025-01-02 15:55 UTC, merged