B 21336 int
transcom/mymove pull request #14457
Opened 2024-12-21 01:09 UTC by JonSpight

## [Agility ticket](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-21336)

## Summary
Create new feature flag called "FEATURE_FLAG_BULK_ASSIGNMENT."
Add a feature flagged button to the SC/TOO/TIO queues, only visible to supervisors.
Clicking the button will open a Bulk Assignment modal with just the Title, Save and Cancel button.

### How to test
1.With the FEATURE_FLAG_BULK_ASSIGNMENT OFF Check the SC/TOO/TIO and verify the bulk assignment Button is not visible
2. Turn the FEATURE_FLAG_BULK_ASSIGNMENT ON and create a TOO/SC/TIO all without supervisor privileges 
3. check the SC/TOO/TIO queues and verify the bulk assignment button is not visible
4. create a TOO/SC/TIO all with supervisor privileges
5. check the SC/TOO/TIO queues and verify the bulk assignment button is visible
6. Click the bulk assignment button and verify the bulk assignment modal pops up with a title save and cancel button

## Screenshots

2024-12-23 15:32 UTC, ryan-mchugh commented on src/components/BulkAssignment/BulkAssignmentModal.test.jsx
> +    const keepButton = await screen.findByRole('button', { name: 'Cancel' });
(minor) var name `keepButton` -> `cancelButton`

2024-12-23 15:33 UTC, ryan-mchugh commented on src/components/BulkAssignment/BulkAssignmentModal.test.jsx
> +    const cancelButton = await screen.findByRole('button', { name: 'Save' });
(minor) var name `cancelButton` -> `saveButton`

2024-12-23 15:38 UTC, ryan-mchugh commented on src/components/Table/TableQueue.jsx
> +            // onSubmit={handleBulkAssignment}
isn't this required?

2024-12-23 15:51 UTC, ryan-mchugh commented on src/shared/constants.js
> +  ENABLE_BULK_ASSIGNMENT: 'enable_Bulk_assignment',
I believe this should just be 'bulk_assignment' if dropping the second `enable_Bulk_assignment` flag

2024-12-23 15:52 UTC, ryan-mchugh commented on src/pages/Office/index.jsx
> +        const isBulkAssignmentFlagValue = await isBooleanFlagEnabled('bulk_assignment');
use the constant for `BULK_ASSIGNMENT`

2024-12-23 15:52 UTC, ryan-mchugh commented on config/flipt/storage/development.features.yaml
> +  - key: enable_Bulk_assignment
Any reason there are two flags for this? I'd drop this one if not and use `bulk_assignment`

2024-12-23 16:10 UTC, loganwc commented on src/components/Table/TableQueue.jsx
> +            // onSubmit={handleBulkAssignment}
that functionality is coming in a later story

2024-12-23 16:40 UTC, paulstonebraker commented on src/components/Table/TableQueue.jsx
> +                <Button type="button" unstyled onClick={handleShowBulkAssignMoveModal}>
can we style this like other buttons?

2024-12-23 16:58 UTC, JonSpight commented on src/components/Table/TableQueue.jsx
> +            // onSubmit={handleBulkAssignment}
I left it as a comment since functionality will be done in a later story

2024-12-23 17:04 UTC, paulstonebraker commented on src/components/BulkAssignment/BulkAssignmentModal.stories.jsx
> +export const WithOverrides = Template.bind({});
this and basic don't work I think? Can probably just take them out

2024-12-23 17:13 UTC, paulstonebraker commented on src/components/Table/TableQueue.jsx
> +            // onSubmit={handleBulkAssignment}
lets take it out until then IMO (or at least leave a TODO comment if not)

2024-12-23 17:16 UTC, paulstonebraker commented on src/components/Table/TableQueue.jsx
> +                  isHeadquartersUser={isHeadquartersUser}
Is this your change or did this get pulled in from elsewhere?

2024-12-23 17:18 UTC, paulstonebraker commented on src/components/Table/TableQueue.jsx
> +  isHeadquartersUser,
i dont see this value being passed to the TableQueue anywhere

2024-12-30 17:03 UTC, paulstonebraker submitted a review, later dismissed

2024-12-30 18:02 UTC, ryan-mchugh requested changes
One comment still outstanding. The rest have been resolved!

2024-12-30 22:44 UTC, ryan-mchugh commented
2 Happo diffs showing that are not related to this story??

2024-12-31 01:30 UTC, pambecker commented
Have you created the file changes to checkin for the FF into the milmove-feature-flags repo?  if so, can you link it here.

2024-12-31 01:36 UTC, pambecker requested changes
HQ supervisor should not see this Bulk Assignment button at any time.  This is failing the AC.

2024-12-31 01:39 UTC, pambecker commented
> HQ supervisor should not see this Bulk Assignment button at any time. This is failing the AC.

well, disregard, for some reason when I created my HQ role, it also gave me an SC role.  This is working as expected for the HQ role.

2024-12-31 16:42 UTC, ryan-mchugh commented
Tested and all matches up to the testing steps.
(NOTE - "Destination Requests" queue does not show button)

2024-12-31 20:51 UTC, ryan-mchugh approved these changes

2024-12-31 21:16 UTC, paulstonebraker commented
> The "Destination Requests" queue for the TOO was added this PI. From a quick search on VersionOne, I do not see any AC in those stories for the bulk assignment addition.
> 
> Wanted to make sure you're aware and can coordinate with Mountain Movers on the original feature for the queue E-05336, or Go-Rillaz for the related "assigned column" OBE feature E-06095.
> 
> Destination Requests queue <img alt="image" width="1725" src="https://private-user-images.githubusercontent.com/180579545/399494070-5147dfd7-170e-4766-ba53-c79fefc89864.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2Nzk5MjcsIm5iZiI6MTczNTY3OTYyNywicGF0aCI6Ii8xODA1Nzk1NDUvMzk5NDk0MDcwLTUxNDdkZmQ3LTE3MGUtNDc2Ni1iYTUzLWM3OWZlZmM4OTg2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIzMVQyMTEzNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMzFlMWQxNmY0YmY2NmZkZDdmMzE4MDZkMDgyMmVhMWVlMjAxOWVkZTQ5ZmQ3ODM3ZmUxNTU5NzhkMzc0OWRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.b6bFZLgECm0rXZ4FDT59tG7FI-B00NVnGSyGai5NPao">

Good call - will make a note to chat with team about it during team sync tomorrow, or later this week if tomorrow's team sync is sparsely attended

2025-01-02 17:42 UTC, JonSpight commented
Bulk assignment queue will be handled later in the following story 
[B-22151 [FF] Destination Request Queue](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-22151)

2025-01-02 17:52 UTC, paulstonebraker approved these changes

2025-01-02 18:11 UTC, ryan-mchugh commented
Approved happo based on disc between Jon and Dre. Unrelated changes.

2025-01-02 20:26 UTC, paulstonebraker commented
> Have you created the file changes to checkin for the FF into the milmove-feature-flags repo? if so, can you link it here.

@JonSpight

2025-01-02 20:34 UTC, JonSpight commented
.

> > Have you created the file changes to checkin for the FF into the milmove-feature-flags repo? if so, can you link it here.
> 
> @JonSpight

yep I linked it to the main one, good catch ill link it here as well.

2025-01-02 21:13 UTC, deandreJones commented
all the config/env/<env>.app.env files - we typically set the default FF values to false

2025-01-03 20:15 UTC, ryan-mchugh approved these changes

2025-01-03 20:17 UTC, merged