fix capturing the order type in adding orders detail info
transcom/mymove pull request #14458
Opened 2024-12-21 02:27 UTC by deandreJones

## [I-13667]

## Summary

Orders Type wasn't being captured for the orders detail screen, need to capture and lock down when bluebark is selected and prevent the email from being sent
I
These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. run server with email backend configured to use aws >> `EMAIL_BACKEND=ses AWS_REGION=us-gov-west-1  aws-vault exec transcom-gov-dev -- make server_run`
2. Access the office app
3. Login as a services counlelor
4. create a new move with bluebark orders type
5. add your email as the personal email of the customer
6. on move details update orders - see that the orders type Is locked down to blueback
7. fill out rest of form, save
8. submit move/shiment
9. verify that no email was sent 

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-12-23 20:05 UTC, traskowskycaci submitted a review, later dismissed
Verified I could not select an orders type other than BLUEBARK and did not receive an email

2024-12-26 14:50 UTC, danieljordan-caci requested changes

2024-12-26 14:50 UTC, danieljordan-caci commented on src/components/Office/OrdersDetailForm/OrdersDetailForm.jsx
> +          formOrdersType === 'SAFETY' || formOrdersType === 'BLUEBARK'
Can you change this to use variables from `orders.js`?

2024-12-26 14:50 UTC, danieljordan-caci commented on src/components/Office/OrdersDetailForm/OrdersDetailForm.jsx
> +        isDisabled={formIsDisabled || formOrdersType === 'SAFETY' || formOrdersType === 'BLUEBARK'}
Same thing here - use variables from `orders.js` instead of hardcoding

2024-12-26 17:18 UTC, traskowskycaci approved these changes

2024-12-26 18:26 UTC, danieljordan-caci approved these changes

2024-12-26 18:32 UTC, merged