B 21904 nts oconus main
transcom/mymove pull request #14450
Opened 2024-12-20 15:38 UTC by KonstanceH

## [B-21904](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A1038106)

## Summary

**Integration PR:** https://github.com/transcom/mymove/pull/14384
This PR adds in the pre approved service items for international NTS shipments.

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### How to test

1. Login as a TOO
2. Add an international NTS shipment to a move. Test the variations of the move:
OCONUS -> OCONUS
OCONUS -> CONUS... etc
3. Click on `Approve and send`.
4. Confirm on the next page`International Shipping and Linehaul` and `International Packing with NTS Pricing Factor` are preapproved service items. `Fuel Surcharge - PODFSC` should only be pre approved if the shipment is OCONUS -> CONUS

Note: OCONUS -> CONUS etc are determined by the shipments pickupaddress and storage facility address.
Example: NTS Shipment
**Pickup Address**     **->  _Storage Facility Address_**         ==      **Ordering Type** 
              Alaska              ->                          Alaska               ==                   OCONUS -> OCONUS
              Iowa                 ->           Alaska    ==               CONUS -> OCONUS
### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots
_**OCONUS -> CONUS**_
<img width="1020" alt="Screenshot 2024-12-12 at 4 02 50 PM" src="https://github.com/user-attachments/assets/bbd5bb66-5f18-40e5-806d-88cf6ae9a471" />

_**OCONUS -> OCONUS**_
<img width="1039" alt="Screenshot 2024-12-12 at 4 01 45 PM" src="https://github.com/user-attachments/assets/48893c39-2bc1-47f4-88ef-f5c1c8c258d6" />

2025-01-16 17:39 UTC, taeJungCaci requested changes

2025-01-16 17:39 UTC, taeJungCaci commented on pkg/services/mto_shipment/mto_shipment_updater_test.go
> +		}
Looks like these were deleted. You might have some commits missing

2025-01-16 17:51 UTC, KonstanceH commented on pkg/services/mto_shipment/mto_shipment_updater_test.go
> +		}
oh yikes! yea I see I'm adding it in now

2025-01-16 17:58 UTC, taeJungCaci approved these changes
Same as INT

2025-01-16 18:34 UTC, JamesHawks224 approved these changes
LGTM

2025-01-17 15:15 UTC, WeatherfordAaron approved these changes
lgrm 👽

2025-01-17 15:15 UTC, merged