INT - B-21687 - Inconsistent Design Multiple Tags
transcom/mymove pull request #14461
Opened 2024-12-23 16:17 UTC by taeJungCaci

## [Agility ticket](tbd)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2024-12-26 13:36 UTC, danieljordan-caci requested changes

2024-12-26 13:36 UTC, danieljordan-caci commented on src/shared/styles/_overrides.scss
> +  border-radius: 2em;
Can you remove this `border-radius`?

2024-12-26 14:54 UTC, taeJungCaci commented on src/shared/styles/_overrides.scss
> +  border-radius: 2em;
We are changing the tags to have rounded edges app wide though

2024-12-26 15:03 UTC, danieljordan-caci commented on src/shared/styles/_overrides.scss
> +  border-radius: 2em;
I say this because the only place I see the "oval" shape being mentioned is the dev analysis. Throughout the app we don't use a ton of border radiuses and it doesn't seem to match what is being done throughout the app.

I like the "tag" component being like a real life tag with defined corners. Making it like a pill seems out of place for the application imo.

2024-12-26 15:09 UTC, taeJungCaci commented on src/shared/styles/_overrides.scss
> +  border-radius: 2em;
Oh I see what you mean....but we actually got this exact mockup already shown to the PO before starting the work on this - and they reviewed it themselves and they agreed and liked the rounded edges I guess.

2024-12-26 15:11 UTC, danieljordan-caci commented on src/shared/styles/_overrides.scss
> +  border-radius: 2em;
I agree with the consistency - who was the PO? I see in the BL it says "Gary through Slack".

I'm really not a super fan of it tbh. It seems that the only reason why they decided on the pill shape was because it was mentioned in the fix analysis. I might get with Dan about it and get his thoughts - not trying to strong arm, but it just doesn't seem to look like a "tag" anymore and from a design standpoint it is a little out of place.

2024-12-26 15:13 UTC, taeJungCaci commented on src/shared/styles/_overrides.scss
> +  border-radius: 2em;
Yeah no worries. I'm no designer so I will go with whichever. But yeah our PO is Gary, and then he took it to his team and came back with additional changes they wanted. But the rounded edges were what I put in the mockup so they might change it back to rectangular shape if you are strong about it.

2024-12-26 15:15 UTC, danieljordan-caci commented on src/shared/styles/_overrides.scss
> +  border-radius: 2em;
Not trying to poo poo on your PR, just don't like the pill haha

2024-12-26 15:16 UTC, taeJungCaci commented on src/shared/styles/_overrides.scss
> +  border-radius: 2em;
I was thinking of Tags like how the Labels are in Github.

2024-12-26 15:17 UTC, taeJungCaci commented on src/shared/styles/_overrides.scss
> +  border-radius: 2em;
Hey ppls got diff tastes. But I'm okay with anything I just code 😆

2025-01-02 16:38 UTC, danieljordan-caci commented on src/shared/styles/_overrides.scss
> +  border-radius: 2em;
Talked with Dan Schuster- said to go forward with the rounded edges

2025-01-02 16:38 UTC, danieljordan-caci approved these changes

2025-01-02 16:43 UTC, taeJungCaci commented on src/shared/styles/_overrides.scss
> +  border-radius: 2em;
Update: PO decided to go with rounded edges.

2025-01-03 16:08 UTC, JamesHawks224 approved these changes
testing: success
code: lgtm

2025-01-06 20:41 UTC, brooklyn-welsh approved these changes
Tested and working. LGTM

2025-01-06 20:59 UTC, danieljordan-caci approved these changes
Happo approved, LGTM.

2025-01-06 21:01 UTC, merged