INT B-21707
transcom/mymove pull request #14473
Opened 2024-12-26 21:18 UTC by danieljordan-caci

## [Agility ticket](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-21707)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2025-01-03 16:10 UTC, cameroncaci requested changes

2025-01-03 16:10 UTC, cameroncaci commented on pkg/payment_request/service_param_value_lookups/port_name_lookup.go
> +	}
Should return error
```suggestion
	} else {
		return "", fmt.Errorf("unable to find port location with id %s", p.ServiceItem.ID)
	}
```

2025-01-03 16:10 UTC, cameroncaci commented on pkg/services/ghcrateengine/intl_port_fuel_surcharge_pricer.go
> +	}
Portname isn't utilized but I understand wanting to have one provided. Thoughts on removal? Fine with leaving or removing it, just wanted to spark a convo

2025-01-03 16:15 UTC, danieljordan-caci commented on migrations/app/schema/20241226173330_add_intl_param_values_to_service_params_table.up.sql
> +     ('759bd482-b2f6-461b-a898-792415efa5f1'::uuid,'56e91c2d-015d-4243-9657-3ed34867abaa','95ee2e21-b232-4d74-9ec5-218564a8a8b9','2024-12-26 15:55:50.041957','2024-12-26 15:55:50.041957',false); -- I
I'd rather leaves these as hard coded - it's what we are doing for all of the other large migrations. Lets us know when they were added locally instead of it always being right now. If ya don't mind.

2025-01-03 16:19 UTC, danieljordan-caci commented on pkg/services/ghcrateengine/intl_port_fuel_surcharge_pricer.go
> +	}
I'll remove it. It's also being checked in the function before so this is likely redundant.

2025-01-03 16:37 UTC, cameroncaci commented on migrations/app/schema/20241226173330_add_intl_param_values_to_service_params_table.up.sql
> +     ('759bd482-b2f6-461b-a898-792415efa5f1'::uuid,'56e91c2d-015d-4243-9657-3ed34867abaa','95ee2e21-b232-4d74-9ec5-218564a8a8b9','2024-12-26 15:55:50.041957','2024-12-26 15:55:50.041957',false); -- I
If this is the current practice then I'm fine with leaving as is - resolved

2025-01-03 16:38 UTC, cameroncaci commented on pkg/payment_request/service_param_value_lookups/port_name_lookup.go
> +	}
Although maybe this error should read "find port location for service item id"

2025-01-03 16:38 UTC, cameroncaci commented on pkg/payment_request/service_param_value_lookups/port_name_lookup.go
> +	}
@danieljordan-caci pinging since this is a comment 30 minutes later

2025-01-03 16:39 UTC, danieljordan-caci commented on pkg/payment_request/service_param_value_lookups/port_name_lookup.go
> +	}
Unlike you I don't trash my github emails so I'm seeing it, but appreciate the ping haha

2025-01-03 17:48 UTC, brianmanley-caci commented on pkg/models/re_rate_area.go
> +		err := db.RawQuery("SELECT get_rate_area_id($1, $2, $3)", addressID, serviceID, contractID).First(&rateAreaID)
I know you didn't add this function in this PR, but I did notice we ended up with 2 get_rate_area_id functions. Do you know if that was intentional?

2025-01-03 17:48 UTC, brianmanley-caci commented on pkg/payment_request/service_param_value_lookups/port_name_lookup_test.go
> +		suite.Equal(portName, "SEATTLE TACOMA INTL")
You could use port.PortName as the 2nd parameter here instead of the hardcoded value to make it slightly less breakable.

2025-01-03 17:48 UTC, brianmanley-caci commented on src/components/PrimeUI/CreatePaymentRequestForm/CreatePaymentRequestForm.jsx
> +                            mtoServiceItem.reServiceCode === 'DDSHUT' ||
Could these use SERVICE_ITEM_CODES from serviceItems.js?

2025-01-03 18:18 UTC, danieljordan-caci commented on pkg/models/re_rate_area.go
> +		err := db.RawQuery("SELECT get_rate_area_id($1, $2, $3)", addressID, serviceID, contractID).First(&rateAreaID)
Ah, gotcha. I must've never dropped the old one when I created the new one with a change in parameter.

2025-01-03 19:21 UTC, danieljordan-caci commented on pkg/payment_request/service_param_value_lookups/port_name_lookup.go
> +	}
Addressed in [this commit](https://github.com/transcom/mymove/pull/14473/commits/ca15696098cd7188b73aa28b6f8271ead8384624)

2025-01-03 19:21 UTC, danieljordan-caci commented on pkg/services/ghcrateengine/intl_port_fuel_surcharge_pricer.go
> +	}
Addressed in [this commit](https://github.com/transcom/mymove/pull/14473/commits/ca15696098cd7188b73aa28b6f8271ead8384624)

2025-01-03 19:21 UTC, danieljordan-caci commented on pkg/models/re_rate_area.go
> +		err := db.RawQuery("SELECT get_rate_area_id($1, $2, $3)", addressID, serviceID, contractID).First(&rateAreaID)
Addressed in [this commit](https://github.com/transcom/mymove/pull/14473/commits/ca15696098cd7188b73aa28b6f8271ead8384624)

2025-01-03 19:21 UTC, danieljordan-caci commented on pkg/payment_request/service_param_value_lookups/port_name_lookup_test.go
> +		suite.Equal(portName, "SEATTLE TACOMA INTL")
Addressed in [this commit](https://github.com/transcom/mymove/pull/14473/commits/ca15696098cd7188b73aa28b6f8271ead8384624)

2025-01-03 19:21 UTC, danieljordan-caci commented on src/components/PrimeUI/CreatePaymentRequestForm/CreatePaymentRequestForm.jsx
> +                            mtoServiceItem.reServiceCode === 'DDSHUT' ||
Addressed in [this commit](https://github.com/transcom/mymove/pull/14473/commits/ca15696098cd7188b73aa28b6f8271ead8384624)

2025-01-03 20:52 UTC, brianmanley-caci commented on src/components/PrimeUI/CreatePaymentRequestForm/CreatePaymentRequestForm.jsx
> +                            mtoServiceItem.reServiceCode === 'DDSHUT' ||
Nice!

2025-01-03 20:59 UTC, brianmanley-caci approved these changes
Working well for me 🎉 

![image](https://github.com/user-attachments/assets/376bc2a1-c776-494e-8825-3caba12c42fb)

2025-01-03 21:50 UTC, danieljordan-caci commented
> Working well for me 🎉
> 
> ![image](https://private-user-images.githubusercontent.com/180578931/400069800-376bc2a1-c776-494e-8825-3caba12c42fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU5NDEzMzAsIm5iZiI6MTczNTk0MTAzMCwicGF0aCI6Ii8xODA1Nzg5MzEvNDAwMDY5ODAwLTM3NmJjMmExLWM3NzYtNDk0ZS04ODI1LTNjYWJhMTJjNDJmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwM1QyMTUwMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MTc0MmZkMjc5NmM2MDFmYWIyZjdlZDk0ZWFkNmVkNDg5YTE1YTE0MTQ1MWI2OTc1ODliMzdmZjcxOTZjMTJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.RwLEKxVThxynaM8BwBfwCV09hf5I49_6l6R5KkKnBxs)

Re-requesting review - forgot to update the API docs per the BL AC

2025-01-03 22:58 UTC, brianmanley-caci commented
> Re-requesting review - forgot to update the API docs per the BL AC

Still good, and I can see the api doc updates.

![Screenshot 2025-01-03 at 4 56 41 PM](https://github.com/user-attachments/assets/e3866a78-1c25-4aef-b1a3-8b4362223e67)
![Screenshot 2025-01-03 at 4 56 59 PM](https://github.com/user-attachments/assets/8a45798f-9336-4819-9df1-972a38471b38)

2025-01-03 22:58 UTC, brianmanley-caci approved these changes

2025-01-06 16:59 UTC, danieljordan-caci commented
Okay I should be done now. Didn't realize that I was using the pickup <-> destination ZIP distance when I should've been using pickup/destination <-> port ZIP distance.

Please re-review when you get a chance @brianmanley-caci & @cameroncaci

2025-01-06 17:30 UTC, traskowskycaci commented on pkg/services/ghcrateengine/intl_port_fuel_surcharge_pricer_test.go
> +	suite.Run("FSC is negative if fuel price from EIA is below $2.50", func() {
Do we expect the fuel price from EIA to be below $2.50 in real world-scenarios? Just curious if we want to handle these negative price values somehow

2025-01-06 17:32 UTC, danieljordan-caci commented on pkg/services/ghcrateengine/intl_port_fuel_surcharge_pricer_test.go
> +	suite.Run("FSC is negative if fuel price from EIA is below $2.50", func() {
Dan is aware of this, so... I say we just let it run its course and if we need to consider negative values for payment requests down the road, we can deal with it then.

2025-01-06 17:38 UTC, traskowskycaci approved these changes
Looking good for me! Tested with a domestic zip to two separate AK zips:
![image](https://github.com/user-attachments/assets/cdb9df1e-043f-40c0-b685-7bc445613c72)

2025-01-06 18:17 UTC, brianmanley-caci approved these changes

2025-01-06 18:31 UTC, merged