Int b 21507 pod poe too validation
transcom/mymove pull request #14475
Opened 2024-12-26 22:04 UTC by msaki-caci

## [B-21507](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A1018854)

## Summary

We are adding a view for the Port of Embark and Port of Debark for the TOO and any other office user with the ability to view the MTO page.

They should be able to view the Port of Embark or Port of Debark based on whichever one is populated the other port should be blank. Here is an example:

![image](https://github.com/user-attachments/assets/ff735551-f3f8-4497-9d12-f7ab7a799586)

## Verification Steps for the Author

These are to be checked by the author.

- [x] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [x] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- 
- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [x] There are no new console errors in the browser devtools.
- [x] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [x] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [x] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

## Screenshots

2024-12-27 21:09 UTC, brianmanley-caci commented on swagger/ghc.yaml
> +      port:
Is this needed? I see `podLocation` and `poeLocation` below, so I'm trying to think what this would be.

2024-12-27 21:11 UTC, msaki-caci commented on pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
> +		portID, _ := uuid.NewV4()
Yeah I am kinda playing around with that as we speak.

2024-12-27 21:12 UTC, msaki-caci commented on src/components/Office/ShipmentAddresses/ShipmentAddresses.jsx
> +        columnHeaders={['Port of Embark', 'Port of Debark']}
Following what Wendy shared with me from an example from DPS but I am cool with either to be honest. She suggested it since it would have some uniformity between the two apps

![image](https://github.com/user-attachments/assets/7e9cad10-c8f3-4906-b2b0-d11001f76439)

2024-12-27 21:13 UTC, msaki-caci commented on swagger/ghc.yaml
> +      port:
uhhh might not be let me go back and look

2024-12-27 21:27 UTC, brianmanley-caci commented on src/utils/shipmentDisplay.jsx
> +  return '';
Just a thought. If you returned `'-'` here instead of empty string,  in ShipmentAddresses.jsx you could change this<br />`dataRow={[poeLocation ? formatPortInfo(poeLocation) : '-', podLocation ? formatPortInfo(podLocation) : '-']}`<br />to<br />`dataRow={[formatPortInfo(poeLocation), formatPortInfo(podLocation)]}`

2024-12-27 21:32 UTC, brianmanley-caci commented on src/components/Office/ShipmentAddresses/ShipmentAddresses.jsx
> +        columnHeaders={['Port of Embark', 'Port of Debark']}
Yeah I haven't seen anywhere else call it the shortened version of the name other than DPS 😆

2024-12-27 21:37 UTC, brianmanley-caci commented on pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
> +		PoeLocation:                 getPortLocation(mtoShipment.MTOServiceItems, "POE"),
You could add a test for these new fields.

2024-12-27 21:44 UTC, msaki-caci commented on src/utils/shipmentDisplay.jsx
> +  return '';
I like it

2024-12-27 22:10 UTC, msaki-caci commented on src/components/Office/ShipmentAddresses/ShipmentAddresses.jsx
> +        columnHeaders={['Port of Embark', 'Port of Debark']}
Renamed them here: [7bc337a](https://github.com/transcom/mymove/pull/14475/commits/7bc337aacabceea462a7a04e3f2472b70ffdd4af)

2024-12-27 22:10 UTC, msaki-caci commented on src/utils/shipmentDisplay.jsx
> +  return '';
Refactored this here [68bec57](https://github.com/transcom/mymove/pull/14475/commits/68bec57c213333331a9406414e52dac154fdce40)

2024-12-27 22:23 UTC, josiahzimmerman-caci commented
@msaki-caci not sure why the .gitlab-ci.yml is showing as a conflict but whatever is in main is correct.

2024-12-27 22:25 UTC, msaki-caci commented
> @msaki-caci not sure why the .gitlab-ci.yml is showing as a conflict but whatever is in main is correct.

Yeah I just saw that, not really sure what happened there either. I will get it resolved

2024-12-27 22:31 UTC, msaki-caci commented on swagger/ghc.yaml
> +      port:
Removed it here [25c6790](https://github.com/transcom/mymove/pull/14475/commits/25c6790be4f7321fb1d09412db69ec25bc3267b2)

2025-01-03 16:05 UTC, msaki-caci commented on pkg/handlers/ghcapi/internal/payloads/model_to_payload_test.go
> +		portID, _ := uuid.NewV4()
Got it to where we are using the port_location factory now.

2025-01-03 16:05 UTC, msaki-caci commented on swagger/ghc.yaml
> +      port:
I think I got that fixed now

2025-01-03 16:05 UTC, msaki-caci commented on pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
> +		PoeLocation:                 getPortLocation(mtoShipment.MTOServiceItems, "POE"),
Added them here [65e8deb](https://github.com/transcom/mymove/pull/14475/commits/65e8deb3615a27fbdded87bd344b7d5822104757)

2025-01-03 18:27 UTC, brianmanley-caci commented on pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
> +func getPortLocation(mtoServiceItems models.MTOServiceItems, portType string) *ghcmessages.Port {
I'm wondering if this should be named differently since it's getting a Port instead of a Port Location. I guess technically the Port payload has the location, so it may not be a big deal.

2025-01-03 18:27 UTC, brianmanley-caci commented on swagger/ghc.yaml
> +      port:
Hey I think you may need to run server_generate because this extra port is still in the generated files.

2025-01-03 19:11 UTC, msaki-caci commented on pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
> +func getPortLocation(mtoServiceItems models.MTOServiceItems, portType string) *ghcmessages.Port {
getPortPayload?

2025-01-03 22:27 UTC, brianmanley-caci commented on pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
> +func getPortLocation(mtoServiceItems models.MTOServiceItems, portType string) *ghcmessages.Port {
It looks like a lot of the other functions just use the return type, so maybe just `Port` 🤷

2025-01-06 17:41 UTC, msaki-caci commented on pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
> +func getPortLocation(mtoServiceItems models.MTOServiceItems, portType string) *ghcmessages.Port {
Sorry it took a minute, had to refactor and consolidate the two functions and test to make sure everything was still working as intended. Should be good to go here though: [124d4e9](https://github.com/transcom/mymove/pull/14475/commits/124d4e918b9397cfede4e7b816adf2cc2125158f)

2025-01-06 20:21 UTC, brianmanley-caci commented on pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
> +		if portType == "POD" && mtoServiceItem.PODLocation != nil {
Could this be changed to `else if` so you can skip the boolean check if `portType` is POE?

2025-01-07 14:22 UTC, brianmanley-caci approved these changes
Looks good 🎉 

![Screenshot 2025-01-07 at 8 21 05 AM](https://github.com/user-attachments/assets/706654f4-0593-41af-a0a3-b948846b9aa3)

2025-01-07 17:12 UTC, danieljordan-caci requested changes
Some smaller changes, also please update the storybook - `ShipmentDetails.stories.jsx`

Right now it's showing blank locations - should have at least one
![Screenshot 2025-01-07 at 11 12 53 AM](https://github.com/user-attachments/assets/1e4665a7-5eff-4d7b-ab74-7255803f0124)

2025-01-07 17:12 UTC, danieljordan-caci commented on src/utils/shipmentDisplay.jsx
> +
Can you move this to `formatters.js` instead of here? I think potentially we will need this in a more broad form throughout the app and that file seems more relevant.

This isn't a hill I want to die on, but I'd prefer `Seattle, Washington` over `SEATTLE, WASHINGTON` y'know? Not enforcing it, just want to bring that up.

2025-01-07 17:12 UTC, danieljordan-caci commented on src/components/Office/ShipmentAddresses/ShipmentAddresses.jsx
> +      />
Can we only display this if there's a `poeLocation` or `podLocation`? Don't see the point in showing this for domestic shipments.

2025-01-07 17:12 UTC, danieljordan-caci commented on pkg/services/mto_shipment/mto_shipment_fetcher.go
> +		}
Can you update/add a test to reflect these changes?

2025-01-08 15:06 UTC, msaki-caci commented on pkg/services/mto_shipment/mto_shipment_fetcher.go
> +		}
Got this here [f960e09](https://github.com/transcom/mymove/pull/14475/commits/f960e09cb4291db062a22b3008a24b441ffd07ce)

2025-01-08 15:06 UTC, msaki-caci commented on src/components/Office/ShipmentAddresses/ShipmentAddresses.jsx
> +      />
got this here [4ed67d0](https://github.com/transcom/mymove/pull/14475/commits/4ed67d02f7a5025a66ff7e1b2f98e8ca112d1313)

2025-01-08 15:07 UTC, msaki-caci commented on src/utils/shipmentDisplay.jsx
> +
Got this here [17cb068](https://github.com/transcom/mymove/pull/14475/commits/17cb068b9723c6c21b68250971a438eb0ac55d0c)

2025-01-08 15:07 UTC, msaki-caci commented
> Some smaller changes, also please update the storybook - `ShipmentDetails.stories.jsx`
> 
> Right now it's showing blank locations - should have at least one ![Screenshot 2025-01-07 at 11 12 53 AM](https://private-user-images.githubusercontent.com/136510600/400858138-1e4665a7-5eff-4d7b-ab74-7255803f0124.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzNDkwNTEsIm5iZiI6MTczNjM0ODc1MSwicGF0aCI6Ii8xMzY1MTA2MDAvNDAwODU4MTM4LTFlNDY2NWE3LTVlZmYtNGQ3Yi1hYjc0LTcyNTU4MDNmMDEyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwOFQxNTA1NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZmYyM2IwZmM5OTQ1ZGE4MTBjYWMzZmU0OTE4YjE1ZTE2NjQyMjcxOGUyZWQ4ODczYjVkMmI2OGE3ZGVmYTk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.LRz4eU0Y399n20rUI_ygbWOMxRQaoDpRhQuKGGXbZ2I)

Got this here [f0d0742](https://github.com/transcom/mymove/pull/14475/commits/f0d0742558eba5654097d69bcd895854be9772f9)

2025-01-08 15:17 UTC, brianmanley-caci commented on src/components/Office/ShipmentAddresses/ShipmentAddresses.jsx
> +      />
Is there a test that verifies these show up/don't show up based on the poeLocation and podLocation values? I didn't see one, but I may have overlooked it.

2025-01-08 15:56 UTC, msaki-caci commented on src/components/Office/ShipmentAddresses/ShipmentAddresses.jsx
> +      />
Good catch. Forgot to update that test but should be good now. [d2e43bc](https://github.com/transcom/mymove/pull/14475/commits/d2e43bc33de1261b23af1b2c23b8b0a1c91865ab)

2025-01-08 18:23 UTC, danieljordan-caci approved these changes
LGTM! Tested CONUS -> OCONUS, OCONUS -> CONUS, intra-AK, and domestic. Port info only shows up when it should. Good work.
![Screenshot 2025-01-08 at 12 21 53 PM](https://github.com/user-attachments/assets/dc542299-c213-4d93-aa35-18464f4b64d8)
![Screenshot 2025-01-08 at 12 22 01 PM](https://github.com/user-attachments/assets/55679d8a-cc10-42ab-977c-3a86b95fb4d6)
![Screenshot 2025-01-08 at 12 22 08 PM](https://github.com/user-attachments/assets/3595045c-ed63-4486-9224-ef95171e1e32)
![Screenshot 2025-01-08 at 12 22 15 PM](https://github.com/user-attachments/assets/2550b134-9237-4e7f-a21c-f0ffff3b4536)

2025-01-08 18:45 UTC, brianmanley-caci approved these changes

2025-01-08 19:59 UTC, merged