B 21410 int
transcom/mymove pull request #14483
Opened 2024-12-30 15:11 UTC by CoryKleinjanCACI

## [Agility ticket](tbd)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Access the
2. Login as a
3.

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots

2025-01-07 21:21 UTC, MInthavongsay commented on pkg/payment_request/service_param_value_lookups/market_destination_lookup.go
> +func (r MarketDestinationLookup) lookup(_ appcontext.AppContext, _ *ServiceItemParamKeyData) (string, error) {
Based on the code there are no errors to be returned. If so no need to return an error in the interface. Just return a string.

2025-01-07 21:23 UTC, MInthavongsay commented on pkg/payment_request/service_param_value_lookups/market_origin_lookup.go
> +func (r MarketOriginLookup) lookup(_ appcontext.AppContext, _ *ServiceItemParamKeyData) (string, error) {
Same as above comments about the error in the interface.

2025-01-07 21:43 UTC, danieljordan-caci requested changes
Lot of good work here. Just want to make sure you are tracking updating the pricing proc for displaying estimated pricing for these accessorials. Not relevant for this BL I don't think but was looking at BLs under this feature and couldn't find something to support that.

Can you also add these to the Prime v1 docs under `createPaymentRequest`? I just updated that section and made it a little more modular to separate domestic/international. Thanks! Re-request when you're ready.

2025-01-07 21:56 UTC, MInthavongsay commented on pkg/services/ghcrateengine/pricer_helpers.go
> +	if market == "" {
Is there a chance you may need to account for  value containing whitespaces?  Possibly use `len(strings.TrimSpace(s)) == 0` to cover all bases. Is there a string util in GOlang that covers both like something in Java?

2025-01-08 12:59 UTC, CoryKleinjanCACI commented on pkg/services/ghcrateengine/pricer_helpers.go
> +	if market == "" {
market is set within the backend. It should never have whitespaces.

2025-01-08 17:46 UTC, CoryKleinjanCACI commented
> Lot of good work here. Just want to make sure you are tracking updating the pricing proc for displaying estimated pricing for these accessorials. Not relevant for this BL I don't think but was looking at BLs under this feature and couldn't find something to support that.
> 
> Can you also add these to the Prime v1 docs under `createPaymentRequest`? I just updated that section and made it a little more modular to separate domestic/international. Thanks! Re-request when you're ready.

As we discussed seperately, these changes will be added in downstream tasks.

2025-01-08 20:10 UTC, r-mettler commented on pkg/handlers/primeapi/mto_service_item_test.go
> +		factory.FetchReServiceByCode(suite.DB(), models.ReServiceCodeDOSHUT)
Copy paste? Is this supposed to fetch the `IOSHUT` service code and not `DOSHUT`?

2025-01-08 20:23 UTC, r-mettler commented on pkg/handlers/primeapi/mto_service_item_test.go
> +		creator := mtoserviceitem.NewMTOServiceItemCreator(planner, builder, moveRouter, ghcrateengine.NewDomesticUnpackPricer(), ghcrateengine.NewDomesticPackPricer(), ghcrateengine.NewDomesticLinehaulPri
Copy paste again? Should this be using your new  `ghcrateengine` pricing for `internationalOriginShuttlingPricer`?

2025-01-08 20:41 UTC, r-mettler commented on pkg/handlers/primeapi/payloads/model_to_payload.go
> +		if mtoServiceItem.ReService.Code == models.ReServiceCodeIOSHUT && mtoServiceItem.MTOShipment.DestinationAddress != nil {
Is this supposed to check if the PickupAddress != nil ?

2025-01-08 21:44 UTC, r-mettler commented on pkg/handlers/primeapi/mto_service_item_test.go
> +		factory.FetchReServiceByCode(suite.DB(), models.ReServiceCodeDOSHUT)
Also applies to the prime v2 and v3 equivalent tests.

2025-01-08 21:44 UTC, r-mettler commented on pkg/handlers/primeapi/mto_service_item_test.go
> +		creator := mtoserviceitem.NewMTOServiceItemCreator(planner, builder, moveRouter, ghcrateengine.NewDomesticUnpackPricer(), ghcrateengine.NewDomesticPackPricer(), ghcrateengine.NewDomesticLinehaulPri
Also applies to the prime v2 and v3 equivalent tests.

2025-01-08 21:45 UTC, r-mettler commented on pkg/handlers/primeapi/payloads/model_to_payload.go
> +		if mtoServiceItem.ReService.Code == models.ReServiceCodeIOSHUT && mtoServiceItem.MTOShipment.DestinationAddress != nil {
Also applies to the prime v2 and v3 `model_to_payload` files.

2025-01-08 21:47 UTC, r-mettler commented on pkg/payment_request/service_param_value_lookups/market_destination_lookup_test.go
> +		value, err := conusLookup.lookup(nil, nil)
As @MInthavongsay mentioned in the `market_destination_lookup` file above, if you remove the error then make sure to update the tests here as well.

2025-01-08 21:48 UTC, r-mettler commented on pkg/payment_request/service_param_value_lookups/market_origin_lookup_test.go
> +		value, err := conusLookup.lookup(nil, nil)
Same as above don't forget to update checks here if you remove the error as a return.

2025-01-08 22:04 UTC, r-mettler commented on pkg/services/ghcrateengine/international_destination_shuttling_pricer_test.go
> +func (suite *GHCRateEngineServiceSuite) setupInternationalDestinationShuttlingServiceItem() models.PaymentServiceItem {
Nit: Typically we put the setup methods at the top of the file before the tests

2025-01-08 22:32 UTC, danieljordan-caci requested changes
Can you create a playwright test or two to cover down these changes for e2e testing? Lot of code and changes here and want to make sure we have the functionality and don't break it later on.

I have a [main branch for 21708](https://github.com/transcom/mymove/pull/14546) that has international playwright files for TXO & SC

2025-01-08 22:47 UTC, r-mettler commented on swagger-def/definitions/prime/MTOServiceItemInternationalShuttle.yaml
> +          or destination (`DDSHUT`).
Should be `IDSHUT` and not `DDSHUT`

2025-01-08 22:47 UTC, r-mettler commented on swagger-def/definitions/prime/MTOServiceItemInternationalShuttle.yaml
> +          - IOSHUT # Domestic Origin Shuttle Service
Comments should say International and not Domestic

2025-01-08 22:50 UTC, r-mettler commented on swagger-def/prime.yaml
> +            description: Provided by the movers, based on weight tickets. Relevant for shuttling (DDSHUT & DOSHUT) service items.
Should use `IDSHUT` and `IOSHUT`

2025-01-08 22:50 UTC, r-mettler commented on swagger-def/prime.yaml
> +            description: An estimate of how much weight from a shipment will be included in a shuttling (DDSHUT & DOSHUT) service item.
Should use `IDSHUT` and `IOSHUT`

2025-01-08 22:50 UTC, r-mettler commented on swagger-def/prime_v2.yaml
> +            description: Provided by the movers, based on weight tickets. Relevant for shuttling (DDSHUT & DOSHUT) service items.
Should use `IDSHUT` and `IOSHUT`

2025-01-08 22:50 UTC, r-mettler commented on swagger-def/prime_v2.yaml
> +            description: An estimate of how much weight from a shipment will be included in a shuttling (DDSHUT & DOSHUT) service item.
Should use `IDSHUT` and `IOSHUT`

2025-01-08 22:51 UTC, r-mettler commented on swagger-def/prime_v3.yaml
> +            description: Provided by the movers, based on weight tickets. Relevant for shuttling (DDSHUT & DOSHUT) service items.
Should use `IDSHUT` and `IOSHUT`

2025-01-08 22:51 UTC, r-mettler commented on swagger-def/prime_v3.yaml
> +            description: An estimate of how much weight from a shipment will be included in a shuttling (DDSHUT & DOSHUT) service item.
Should use `IDSHUT` and `IOSHUT`

2025-01-08 22:51 UTC, r-mettler commented on swagger/prime.yaml
> +              destination (`DDSHUT`).
Should say `IDSHUT`

2025-01-08 22:52 UTC, r-mettler commented on swagger/prime.yaml
> +              shuttling (DDSHUT & DOSHUT) service items.
Should use `IDSHUT` and `IOSHUT`

2025-01-08 22:52 UTC, r-mettler commented on swagger/prime.yaml
> +              a shuttling (DDSHUT & DOSHUT) service item.
Should use `IDSHUT` and `IOSHUT`

2025-01-08 23:01 UTC, r-mettler commented
> Can you create a playwright test or two to cover down these changes for e2e testing? Lot of code and changes here and want to make sure we have the functionality and don't break it later on.
> 
> I have a [main branch for 21708](https://github.com/transcom/mymove/pull/14546) that has international playwright files for TXO & SC

We have playwright setup for admin, office, and customer, but I don't think we have any playwright tests for the prime simulator which is where he made the changes for the front end.

2025-01-08 23:06 UTC, r-mettler commented on src/components/PrimeUI/CreateShipmentServiceItemForm/CreateShipmentServiceItemForm.jsx
> +          <option value={MTOServiceItemInternationalShuttle}>International Shuttle</option>
Can you please add the shuttle service items to the test in `CreateShipmentServiceItemForm.test.jsx`? I see tests for the other service items but not the domestic and international shuttles.

2025-01-08 23:08 UTC, r-mettler requested changes
Can you please add the shuttle service items to the test in `CreateShipmentServiceItemForm.test.jsx`? I see tests for the other service items but not the domestic and international shuttles.

2025-01-09 20:45 UTC, r-mettler commented on src/components/PrimeUI/CreateShipmentServiceItemForm/CreateShipmentServiceItemForm.test.jsx
> +    ['InternationalShuttleSitServiceItemForm', createServiceItemModelTypes.MTOServiceItemInternationalShuttle],
👍

2025-01-09 21:50 UTC, r-mettler commented
Looks good
![image](https://github.com/user-attachments/assets/8d103f0f-90de-4dc4-96ae-e136c309dc5f)

2025-01-09 21:50 UTC, r-mettler approved these changes

2025-01-13 20:14 UTC, begrohmann commented on migrations/app/schema/20250113160816_updating_create_accessorial_service_item_proc.up.sql
😍😍

2025-01-13 20:18 UTC, begrohmann commented on pkg/services/ghcrateengine/pricer_query_helpers.go
> +	var domAccessorialPrice models.ReIntlAccessorialPrice
Should this be "domAccessorialPrice"?

2025-01-13 21:41 UTC, r-mettler submitted a review, later dismissed
Looks good

2025-01-13 21:56 UTC, danieljordan-caci commented
> > Can you create a playwright test or two to cover down these changes for e2e testing? Lot of code and changes here and want to make sure we have the functionality and don't break it later on.
> > I have a [main branch for 21708](https://github.com/transcom/mymove/pull/14546) that has international playwright files for TXO & SC
> 
> We have playwright setup for admin, office, and customer, but I don't think we have any playwright tests for the prime simulator which is where he made the changes for the front end.

No need to use the prime sim - playwright tests can be added with set up moves with requested accessorials service items. Test that a TOO can approve those without error.

Then set up a TIO playwright that handles reviewing payment requests from Prime. Don't need tests for the Prime stuff, but TXO action after Prime requests accessorials & payment for said accessorials. Can check out 21708 to see how I set it up.

2025-01-13 21:56 UTC, danieljordan-caci requested changes
Need playwrights for the following:
- TOO approving accessorials (can add a rejection if ya want)
- TIO reviewing payment request sent by Prime for accessorial, verify prices are there

2025-01-14 03:16 UTC, CoryKleinjanCACI commented
> ee the

There are follow on tasks that are specifically for TOO and TIO that will handle these.

2025-01-14 03:16 UTC, CoryKleinjanCACI commented
> Need playwrights for the following:
> 
> * TOO approving accessorials (can add a rejection if ya want)
> * TIO reviewing payment request sent by Prime for accessorial, verify prices are there
> 
> You can see the setup in 21708 for reference - would recommend merging that into your `main` branch and building off of the new files I added there

There are follow on tasks that are specifically for TOO and TIO that will handle these.

2025-01-14 13:41 UTC, danieljordan-caci commented
> > Need playwrights for the following:
> > 
> > * TOO approving accessorials (can add a rejection if ya want)
> > * TIO reviewing payment request sent by Prime for accessorial, verify prices are there
> > 
> > You can see the setup in 21708 for reference - would recommend merging that into your `main` branch and building off of the new files I added there
> 
> There are follow on tasks that are specifically for TOO and TIO that will handle these.

Do you have a BL number?

2025-01-14 14:18 UTC, begrohmann submitted a review, later dismissed

2025-01-14 14:54 UTC, CoryKleinjanCACI commented
> > > Need playwrights for the following:
> > > 
> > > * TOO approving accessorials (can add a rejection if ya want)
> > > * TIO reviewing payment request sent by Prime for accessorial, verify prices are there
> > > 
> > > You can see the setup in 21708 for reference - would recommend merging that into your `main` branch and building off of the new files I added there
> > 
> > 
> > There are follow on tasks that are specifically for TOO and TIO that will handle these.
> 
> Do you have a BL number?

21439 - 21440

2025-01-14 15:00 UTC, danieljordan-caci commented
> > > > Need playwrights for the following:
> > > > 
> > > > * TOO approving accessorials (can add a rejection if ya want)
> > > > * TIO reviewing payment request sent by Prime for accessorial, verify prices are there
> > > > 
> > > > You can see the setup in 21708 for reference - would recommend merging that into your `main` branch and building off of the new files I added there
> > > 
> > > 
> > > There are follow on tasks that are specifically for TOO and TIO that will handle these.
> > 
> > 
> > Do you have a BL number?
> 
> 21439 - 21440

Can you update the BL descriptions to ensure it mentions creation of e2e tests for each respective role?

2025-01-14 15:28 UTC, CoryKleinjanCACI commented
> > > > > Need playwrights for the following:
> > > > > 
> > > > > * TOO approving accessorials (can add a rejection if ya want)
> > > > > * TIO reviewing payment request sent by Prime for accessorial, verify prices are there
> > > > > 
> > > > > You can see the setup in 21708 for reference - would recommend merging that into your `main` branch and building off of the new files I added there
> > > > 
> > > > 
> > > > There are follow on tasks that are specifically for TOO and TIO that will handle these.
> > > 
> > > 
> > > Do you have a BL number?
> > 
> > 
> > 21439 - 21440
> 
> Can you update the BL descriptions to ensure it mentions creation of e2e tests for each respective role?

Easy enough to do, but is the standard to update task descriptions with testing updates? I don't see it for 21708 and I can't think of another task I've seen it on.

2025-01-14 15:44 UTC, CoryKleinjanCACI commented
> > > > > > There are follow on tasks that are specifically for TOO and TIO that will handle these.
> > > > > 
> > > > > 
> > > > > Do you have a BL number?
> > > > 
> > > > 
> > > > 21439 - 21440
> > > 
> > > 
> > > Can you update the BL descriptions to ensure it mentions creation of e2e tests for each respective role?
> > 
> > 
> > Easy enough to do, but is the standard to update task descriptions with testing updates? I don't see it for 21708 and I can't think of another task I've seen it on.
> 
> I'm just making sure it is being tracked and that reviewers can check the BL in the future and expect to see playwright stuff.
> 
> You're correct in that I didn't document it in 21708 - that's on me and I'm probably coming off a bit like a hypocrite haha

I updated the descriptions to include end to end playwright testing for the TOO/TIO interactions with international shuttle.

2025-01-15 14:21 UTC, begrohmann submitted a review, later dismissed

2025-01-15 16:07 UTC, taeJungCaci commented on pkg/services/ghcrateengine/pricer_helpers.go
I believe @danieljordan-caci already created a file for Intl pricer helpers in `pkg/services/ghcrateengine/pricer_helpers_intl.go`

2025-01-15 16:09 UTC, danieljordan-caci commented on pkg/services/ghcrateengine/pricer_helpers.go
Yes I did - thanks Tae. That work was done in 21707

2025-01-15 16:52 UTC, danieljordan-caci commented on pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
> +	if s.ReService.Code == models.ReServiceCodeIDSHUT && s.MTOShipment.PickupAddress != nil {
Should this be `s.MTOShipment.DestinationAddress != nil`

2025-01-15 17:57 UTC, danieljordan-caci requested changes
Some things. Also ran into some issues:
- the move status doesn't change when I create either service item as Prime. It should change to `APPROVALS REQUESTED`

- want to make sure that the Prime Sim work to resubmit these rejected service items is being tracked. I see there's a Prime Sim story so that's good.

- getting an error when the estimated pricing is being updated for the service items in the db proc, this is likely because we don't have a case for these service items in the proc yet. You'll need to add the case and handle the estimated pricing first as an upstream to this or some sort of default - I'd prefer the former because estimated pricing should come before actual.

2025-01-15 18:40 UTC, taeJungCaci commented
> Some things. Also ran into some issues:
> 
> * the move status doesn't change when I create either service item as Prime. It should change to `APPROVALS REQUESTED`
> * want to make sure that the Prime Sim work to resubmit these rejected service items is being tracked. I see there's a Prime Sim story so that's good.
> * getting an error when the estimated pricing is being updated for the service items in the db proc, this is likely because we don't have a case for these service items in the proc yet. You'll need to add the case and handle the estimated pricing first as an upstream to this or some sort of default - I'd prefer the former because estimated pricing should come before actual.

Question about Prime resubmitting a rejected service item. Do you know if we are supposed to use the `edit` in Prime sim for these Accessorials? I know SIT uses the `edit` but I don't think service items like dometic crating have this func. They can just recreate a service item since you can create multiple crate service items as a prime.

2025-01-15 18:42 UTC, danieljordan-caci commented
> > Some things. Also ran into some issues:
> > 
> > * the move status doesn't change when I create either service item as Prime. It should change to `APPROVALS REQUESTED`
> > * want to make sure that the Prime Sim work to resubmit these rejected service items is being tracked. I see there's a Prime Sim story so that's good.
> > * getting an error when the estimated pricing is being updated for the service items in the db proc, this is likely because we don't have a case for these service items in the proc yet. You'll need to add the case and handle the estimated pricing first as an upstream to this or some sort of default - I'd prefer the former because estimated pricing should come before actual.
> 
> Question about Prime resubmitting a rejected service item. Do you know if we are supposed to use the `edit` in Prime sim for these Accessorials? I know SIT uses the `edit` but I don't think service items like dometic crating have this func. They can just recreate a service item since you can create multiple crate service items as a prime.
> 
> Doesn't look like domestic shuttle have `edit` func in the prime UI either. Is it just missing in the UI and the prime is supposed to use it vs. crating a new service item?

I'm assuming they'll want us to use the same process which is "updating" the service item with a new reason (I think it's `updateReason`?) which resets the service item status to `SUBMITTED`

2025-01-15 18:53 UTC, taeJungCaci commented
> > > Some things. Also ran into some issues:
> > > 
> > > * the move status doesn't change when I create either service item as Prime. It should change to `APPROVALS REQUESTED`
> > > * want to make sure that the Prime Sim work to resubmit these rejected service items is being tracked. I see there's a Prime Sim story so that's good.
> > > * getting an error when the estimated pricing is being updated for the service items in the db proc, this is likely because we don't have a case for these service items in the proc yet. You'll need to add the case and handle the estimated pricing first as an upstream to this or some sort of default - I'd prefer the former because estimated pricing should come before actual.
> > 
> > 
> > Question about Prime resubmitting a rejected service item. Do you know if we are supposed to use the `edit` in Prime sim for these Accessorials? I know SIT uses the `edit` but I don't think service items like dometic crating have this func. They can just recreate a service item since you can create multiple crate service items as a prime.
> > Doesn't look like domestic shuttle have `edit` func in the prime UI either. Is it just missing in the UI and the prime is supposed to use it vs. crating a new service item?
> 
> I'm assuming they'll want us to use the same process which is "updating" the service item with a new reason (I think it's `updateReason`?) which resets the service item status to `SUBMITTED`

Make sense. I guess other acc service items just didn't get updated yet.

2025-01-15 18:56 UTC, taeJungCaci requested changes
Other than Daniel's requested changes, I'm getting a null pointer error when trying to approve or reject intl shuttle as a TOO for a iHHG shipment. Might be same error that Daniel is talking about with estimated weight as I think that func is getting called when trying to approve or reject for some reason.

I don't think these acc service items have an estimated pricing though right?

2025-01-15 20:36 UTC, CoryKleinjanCACI commented
> Some things. Also ran into some issues:
> 
> * the move status doesn't change when I create either service item as Prime. It should change to `APPROVALS REQUESTED`
> * want to make sure that the Prime Sim work to resubmit these rejected service items is being tracked. I see there's a Prime Sim story so that's good.
> * getting an error when the estimated pricing is being updated for the service items in the db proc, this is likely because we don't have a case for these service items in the proc yet. You'll need to add the case and handle the estimated pricing first as an upstream to this or some sort of default - I'd prefer the former because estimated pricing should come before actual.

If you are correct, it appears the same issue exists with domestic shuttles on the main branch. I would validate with you PO that this is the case and if it is create an issue.

2025-01-15 20:38 UTC, danieljordan-caci commented
> > Some things. Also ran into some issues:
> > 
> > * the move status doesn't change when I create either service item as Prime. It should change to `APPROVALS REQUESTED`
> > * want to make sure that the Prime Sim work to resubmit these rejected service items is being tracked. I see there's a Prime Sim story so that's good.
> > * getting an error when the estimated pricing is being updated for the service items in the db proc, this is likely because we don't have a case for these service items in the proc yet. You'll need to add the case and handle the estimated pricing first as an upstream to this or some sort of default - I'd prefer the former because estimated pricing should come before actual.
> 
> If you are correct, it appears the same issue exists with domestic shuttles on the main branch. I would validate with you PO that this is the case and if it is create an issue.

No, the issue is this part in the estimated pricing proc that is running:
```
-- loop through service items in the shipment
    FOR service_item IN
        SELECT si.id, si.re_service_id
        FROM mto_service_items si
        WHERE si.mto_shipment_id = shipment_id
    LOOP
        -- get the service code for the current service item to determine calculation
        SELECT code
        INTO service_code
        FROM re_services
        WHERE id = service_item.re_service_id;

        CASE
            WHEN service_code IN (''ISLH'', ''UBP'') THEN
```

When there are international shuttle service items on the shipment, there is not a `CASE` statement for those service items, so it is erroring out. You need to merge in the estimated pricing work before this.

2025-01-15 20:47 UTC, CoryKleinjanCACI commented
> he shipme

Ah, I should have been more clear. I was talking about specifically the 'APPROVAL_REQUESTED' statement. I ran the main branch and created a domestic shuttle. The shipment stayed in approved status.

I agree the proc should be updated. I have a follow on task for it to be done, I didn't realize the call to the proc was going to be implemented and set as a requirement for international accessorials. Seems like that could have been feature flagged until it was ready to support the international service items, or at least a check added so that it didn't brick existing work for service items like international crating and shuttle.

2025-01-15 20:49 UTC, danieljordan-caci commented
> @danieljordan-caci
> 
> Ah, I should have been more clear. I was talking about specifically the 'APPROVAL_REQUESTED' statement. I ran the main branch and created a domestic shuttle. The shipment stayed in approved status.
> 
> I agree the proc should be updated. I have a follow on task for it to be done, I didn't realize the call to the proc was going to be implemented and set as a requirement for international accessorials. Seems like that could have been feature flagged until it was ready to support the international service items, or at least a check added so that it didn't brick existing work for service items like international crating and shuttle.

This is why we set dependencies. Should've handled the estimated work first before tackling the actual. All good - but this can't move forward until that is done.

2025-01-15 20:51 UTC, CoryKleinjanCACI commented
> > @danieljordan-caci
> > Ah, I should have been more clear. I was talking about specifically the 'APPROVAL_REQUESTED' statement. I ran the main branch and created a domestic shuttle. The shipment stayed in approved status.
> > I agree the proc should be updated. I have a follow on task for it to be done, I didn't realize the call to the proc was going to be implemented and set as a requirement for international accessorials. Seems like that could have been feature flagged until it was ready to support the international service items, or at least a check added so that it didn't brick existing work for service items like international crating and shuttle.
> 
> This is why we set dependencies. Should've handled the estimated work first before tackling the actual. All good - but this can't move forward until that is done.

Also, I found whats going on with the move status and I can fix it here. Its not existing for domestic, just displays strangely.

2025-01-20 14:41 UTC, danieljordan-caci requested changes
Putting a blocker on this until [B-22206](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-22206) is merged into `main`

This PR adjusts the pricing proc to use 110% of the estimated weight and is an upstream to this BL. Once that is merged, you'll need to adjust your pricing proc to copy the logic in that and then append the accessorials CASE statements. Ensure they multiply by 110% of estimated weight.

2025-01-20 15:30 UTC, danieljordan-caci commented
Want to just throw this out there because it's on my mind.

One thing I think that this could do in order to be pushed forward would be to take this feature back and restructure the BLs to be broken up into steps in the process instead of roles in the process. Example:
1. Prime can request accessorials
2. TOO can approve/reject accessorials and estimated price is updated
3. Prime can resubmit rejected accessorials
4. Prime can create payment request for accessorials
5. TIO can review (approve/reject) accessorials

I know that would be a kick to the nads because you've already done a lot of the work, but something to think about.

2025-01-22 18:59 UTC, r-mettler submitted a review, later dismissed

2025-01-23 16:52 UTC, r-mettler commented on pkg/factory/admin_user_factory_test.go
> +func (suite *FactorySuite) TestSuperBuildAdminUser() {
Glad you added this because somebody forgot to 🫨 
![image](https://github.com/user-attachments/assets/19926031-8359-47b0-a916-c1e5b0ca91b7)

2025-01-23 17:11 UTC, r-mettler submitted a review, later dismissed

2025-01-23 17:51 UTC, antgmann commented
Might not be a huge concern, but when rejecting the service item as part of the test instructions, I'm getting two different move history entries with the same information, just one of them with slightly more info. Might be an existing issue with service items, just thought it worth documenting:
<img width="1616" alt="image" src="https://github.com/user-attachments/assets/b77c9894-45e7-47a0-a040-11de81ec3a88" />

2025-01-23 18:16 UTC, antgmann commented
The updatedReason text is apparently being displayed in a follow on task: <img width="1127" alt="image" src="https://github.com/user-attachments/assets/6cb9e4b6-5b76-45b9-8870-520fef003c7a" />

2025-01-23 18:20 UTC, antgmann commented
Service items price successfully. Going to check on the above double service item history log, and if it's an existing issue, I think this will be ✅ <img width="1127" alt="image" src="https://github.com/user-attachments/assets/30924651-35c9-4826-b438-f886d9f4b387" />

2025-01-23 18:44 UTC, antgmann commented
Main: 
<img width="1670" alt="Pasted Graphic" src="https://github.com/user-attachments/assets/04dee856-63ab-4f7a-8c67-c87631b917d5" />

After re-attempting on current branch:
<img width="1670" alt="Pasted Graphic 1" src="https://github.com/user-attachments/assets/8320e551-98ce-4c01-bcca-48ed78d37506" />

Not sure why I had the above weirdness and can't seem to recreate it. I don't think it's worth holding up such a central feature, but will welcome opinions to the contrary.

2025-01-23 18:44 UTC, antgmann submitted a review, later dismissed

2025-01-23 20:37 UTC, danieljordan-caci requested changes
Just some little stuff, functionality works pretty good!

2025-01-23 20:37 UTC, danieljordan-caci commented on pkg/services/ghcrateengine/pricer_helpers_intl.go
> +	if weight < minDomesticWeight {
I believe this should be `if weight < minInternationalWeight`

2025-01-23 20:37 UTC, danieljordan-caci commented on pkg/services/ghcrateengine/pricer_helpers_intl_test.go
> +	suite.Run("destination golden path", func() {
test says `destination golden path` but you're using `IOSHUT` service item - should this be `origin golden path`?

2025-01-23 20:37 UTC, danieljordan-caci commented on pkg/services/ghcrateengine/pricer_helpers_intl_test.go
> +		twoYearsLaterPickupDate := doshutTestRequestedPickupDate.AddDate(2, 0, 0)
using the domestic pickup date here `doshutTestRequestedPickupDate`

2025-01-23 20:37 UTC, danieljordan-caci commented on pkg/services/ghcrateengine/pricer_helpers_intl_test.go
> +		suite.setupInternationalAccessorialPrice(models.ReServiceCodeIDSHUT, ioshutTestMarket, idshutTestBasePriceCents, testdatagen.DefaultContractCode, idshutTestEscalationCompounded)
should this variable be `idshutTestMarket` instead of `ioshutTestMarket`?

2025-01-23 20:37 UTC, danieljordan-caci commented on src/components/PrimeUI/CreateShipmentServiceItemForm/CreateShipmentServiceItemForm.test.jsx
> +    ['InternationalShuttleSitServiceItemForm', createServiceItemModelTypes.MTOServiceItemInternationalShuttle],
Any reason why this is `InternationalShuttleSit`? Shouldn't it be `InternationalShuttle`? Not sure why SIT is in there.

2025-01-23 20:37 UTC, danieljordan-caci commented on src/components/PrimeUI/CreateShipmentServiceItemForm/CreateShipmentServiceItemForm.jsx
> +        <InternationalShuttleSITServiceItemForm shipment={shipment} submission={createServiceItemMutation} />
Same thing here - Should this be `<InternationalShuttleServiceItemForm`?

2025-01-23 20:37 UTC, danieljordan-caci commented on src/components/PrimeUI/CreateShipmentServiceItemForm/InternationalShuttleSITServiceItemForm.jsx
> +const InternationalShuttleSITServiceItemForm = ({ shipment, submission }) => {
`InternationalShuttleServiceItemForm`?

2025-01-24 14:31 UTC, danieljordan-caci commented
Happo approved, re-reviewing

2025-01-24 14:31 UTC, MInthavongsay commented on src/components/PrimeUI/CreateShipmentServiceItemForm/InternationalShuttleServiceItemForm.jsx
> +const InternationalShuttleServiceItemForm = ({ shipment, submission }) => {
Suggestion -- If international is identical to dometic in terms of payload/HTML, I would reuse the existing ShuttleServiceItemForm.jsx to handle both international and domestic. Just pass in some type of identifier to differentiate between the two. The flag will determine the modelType and anything else.

2025-01-24 15:01 UTC, danieljordan-caci requested changes
Functionality is good, downstream BLs can do a lot of refinement if needed. Upstream feature is officially all in `main`

Able to request and resubmit international shuttle as Prime
Able to approve/reject TOO
Able to review pricing as TIO

One small thing wrong with the migration file overriding previous work for basic iHHG service items.

2025-01-24 15:01 UTC, danieljordan-caci commented on migrations/app/schema/20250121153007_update_pricing_proc_to_handle_international_shuttle.up.sql
> +CREATE OR REPLACE FUNCTION calculate_escalated_price(
Check out this [commit](https://github.com/transcom/mymove/pull/14574/commits/5fe1c265c9e948021f68399c87837e476ae7d5c9) that went in with [MAIN B-22206](https://github.com/transcom/mymove/pull/14574)

You need to be sure you're not changing any part of the code for the basic iHHG service items in there. You can see I added the `is_peak_period` function. Can you update this please?

2025-01-24 17:07 UTC, r-mettler commented on migrations/app/schema/20250121153007_update_pricing_proc_to_handle_international_shuttle.up.sql
> +CREATE OR REPLACE FUNCTION calculate_escalated_price(
I hope we can come up with a good method in the future to prevent things like this from happening. Its going to be difficult to see what changes were made to a proc/function when the current setup has us creating new files. Things are going to be missed because git can't merge in changes for us or mark conflicts 😢

2025-01-24 17:09 UTC, danieljordan-caci commented on migrations/app/schema/20250121153007_update_pricing_proc_to_handle_international_shuttle.up.sql
> +CREATE OR REPLACE FUNCTION calculate_escalated_price(
Dude, I know. Big reason why I was waiting on my stuff to get through since it's upstream. Lot of manual work with the current process, which means lotttts of risks of things getting missed.

2025-01-24 17:26 UTC, r-mettler commented on src/components/PrimeUI/CreateShipmentServiceItemForm/InternationalShuttleServiceItemForm.jsx
> +const InternationalShuttleServiceItemForm = ({ shipment, submission }) => {
I kinda prefer having them separate just thinking about future international shuttle only changes then we start getting into if international do this everywhere in the current file and may end up separating them later on anyways.

2025-01-24 19:33 UTC, danieljordan-caci requested changes
Some pricing changes & a question

2025-01-24 19:33 UTC, danieljordan-caci commented on migrations/app/schema/20250121153007_update_pricing_proc_to_handle_international_shuttle.up.sql
> +                END IF;
Couple things:
1. I believe that these should be multiplying to 110% of the estimated weight - when getting POA for iHHG basic service items Dan said that all estimated pricing should do that since Prime can bill for 110% of the actual weight and wants that to translate to estimated. Might as well tackle it here so we don't have to mess with it later

2. An observation I see and I like reusability, but it seems that `IOSHUT` uses the same calculation as `IHPK` & `IUBPK` - any objections to just adding this `CASE` to that one? Same goes for `IDSHUT` and `IHUPK` & `IUBUPK`. Only difference would be that those pass in the `shipment.requested_pickup_date` to `calculate_escalated_price` but it wouldn't matter for the query that you hit, but we should probably provide that anyway.

Thoughts? Objections?

2025-01-24 22:38 UTC, danieljordan-caci approved these changes
Requested as Prime
Approved/rejected as TOO
Able to see pricing as TIO

estimated pricing shows up
![Screenshot 2025-01-24 at 4 35 22 PM](https://github.com/user-attachments/assets/1dba48dd-31d7-4236-951c-a584bb5c10a3)

TIO pricing seems pretty different from estimated, but that can be addressed in a downstream to ensure those match up.
![Screenshot 2025-01-24 at 4 36 23 PM](https://github.com/user-attachments/assets/ba78f97a-67aa-484e-b2f6-ab1623a29168)

Meets AC, LGTM! Thanks for all the changes and sorry if it was a downer to wait for the upstreams. Nice work!

2025-01-24 22:39 UTC, danieljordan-caci commented
Happo approved

2025-01-25 00:44 UTC, antgmann approved these changes
Re-approving

2025-01-27 14:57 UTC, antgmann commented
🦛 ✅

2025-01-27 15:52 UTC, merged