B 21569 int
transcom/mymove pull request #14491
Opened 2024-12-30 21:35 UTC by stevengleason-caci

# B-21569 INT
[B-21569](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A1024477)
## Summary
Add service items for Unaccompanied Baggage. They are visible after the shipment is Approved and Submitted. They cane be Rejected and re-Approved.

The feature mentions that the Fuel Surcharge is only for when either the Origin or Destination is CONUS.
The story mentions using the DB, but I saw that other similar stories were putting it directly in reServiceCodesForShipment. 

## Verification Steps for the Author

These are to be checked by the author.

- [ ] Have the Agility acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

- [ ] Has the branch been pulled in and checked out?
- [ ] Have the BL acceptance criteria been met for this change?
- [ ] Was the CircleCI build successful?
- [ ] Has the code been reviewed from a standards and best practices point of view?

### Setup to Run the Code

- [Instructions for starting storybook](https://transcom.github.io/mymove-docs/docs/frontend/setup/storybook)
- [Instructions for starting the MilMove application](https://transcom.github.io/mymove-docs/docs/getting-started/application-setup/)
- [Instructions for running tests](https://transcom.github.io/mymove-docs/docs/getting-started/development/testing)

### How to test

1. Run with feature flags on: FEATURE_FLAG_UNACCOMPANIED_BAGGAGE=true FEATURE_FLAG_ENABLE_ALASKA=true make server_run
2. Login as a Customer and create an OCONUS-to-CONUS UB shipment
3. And create an OCONUS-to-OCONUS UB shipment
4. Log in as a Counselor and complete and approve both shipments
5. Log in as a TOO and submit the OCONUS-to-CONUS shipment
6. See the 4 service items
7. Submit the OCONUS-to-OCONUS shipment
8. See only 3 service items (no Fuel Surcharge)

### Frontend

- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://transcom.github.io/mymove-docs/docs/adrs/Browser-Support/#minimum-browser-requirements) (Chrome, Firefox, Edge).
- [ ] There are no new console errors in the browser devtools.
- [ ] There are no new console errors in the test output.
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.
- [ ] This change meets the standards for [Section 508 compliance](https://www.ssa.gov/accessibility/andi/help/install.html).

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/getting-started/development/logging).
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/backend/guides/golang-guide#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#zero-downtime-migrations).
- [ ] Have been communicated to #g-database.
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations).

## Screenshots
### OCONUS-CONUS with FSC
![Screenshot 2024-12-30 at 2 19 33 PM](https://github.com/user-attachments/assets/5200c2db-02d9-4704-ab0e-cdddd13a1782)
### OCONUS-OCONUS (no FSC)
![Screenshot 2024-12-30 at 2 44 03 PM](https://github.com/user-attachments/assets/7ca5f814-39e7-4de5-a22a-dd2b45fbfd32)

2024-12-31 20:39 UTC, ryan-mchugh commented
I noticed that FSC still shows in the preview for OCONUS-OCONUS UB shipments

<img width="1187" alt="Screenshot 2024-12-31 at 3 37 20 PM" src="https://github.com/user-attachments/assets/6ee3dcfb-69d2-4e57-a528-9ce7af990512" />

2025-01-07 19:23 UTC, stevengleason-caci commented
I updated the preview page so AK to AK doesn't produce the Fuel Surcharge.
I also changed my code to use the DB instead of coding it in the switch-case.

2025-01-07 19:38 UTC, danieljordan-caci requested changes

2025-01-07 19:38 UTC, danieljordan-caci commented on pkg/services/mto_shipment/shipment_approver_test.go
> +					ShipmentType: "UNACCOMPANIED_BAGGAGE",
Can you use a variable here instead of hard coding `"UNACCOMPANIED_BAGGAGE"`?

Should be `models.MTOShipmentTypeUnaccompaniedBaggage`

2025-01-07 19:38 UTC, danieljordan-caci commented on pkg/services/mto_shipment/shipment_approver_test.go
> +					MarketCode:   "i",
Can you use the variable for this instead of hard coding?

`models.MarketCodeInternational`

2025-01-07 19:38 UTC, danieljordan-caci commented on pkg/services/mto_shipment/shipment_approver_test.go
> +					ShipmentType: "UNACCOMPANIED_BAGGAGE",
Same thing here with avoiding these hard coded strings when we have the variables available.

2025-01-07 19:38 UTC, danieljordan-caci commented on pkg/services/mto_shipment/shipment_approver_test.go
> +					ShipmentType: "UNACCOMPANIED_BAGGAGE",
Use variables plz

2025-01-07 19:38 UTC, danieljordan-caci commented on src/components/Office/ShipmentServiceItemsTable/ShipmentServiceItemsTable.test.jsx
> +    it.each([['International UB'], ['International UB pack'], ['International UB unpack']])(
Can you also add a test for CONUS -> OCONUS & OCONUS -> CONUS?

2025-01-07 21:11 UTC, stevengleason-caci commented on pkg/services/mto_shipment/shipment_approver_test.go
> +					ShipmentType: "UNACCOMPANIED_BAGGAGE",
Updated

2025-01-07 21:19 UTC, stevengleason-caci commented
129 diffs in Happo: all the boxes have rounded corners. I don't think it's me. It's also showing up in these:
#14525 #14522 and others, and accepted in #14404

2025-01-07 21:21 UTC, danieljordan-caci commented
> 129 diffs in Happo: all the boxes have rounded corners. I don't think it's me. It's also showing up in these: #14525 #14522 and others, and accepted in #14404



> 129 diffs in Happo: all the boxes have rounded corners. I don't think it's me. It's also showing up in these: #14525 #14522 and others, and accepted in #14404

approved

2025-01-07 21:23 UTC, danieljordan-caci approved these changes

2025-01-07 22:49 UTC, brianmanley-caci approved these changes
All 3 cases worked for me 👏

2025-01-08 15:20 UTC, merged