MB-3840 MB-3847 - Add button to add another shipment and e2e test
transcom/mymove pull request #4741
Opened 2020-09-04 04:47 UTC by amitch23

## Description

Adds "add new shipment" button to the Review page, and routes to the select type page. Able to create a new shipment from there.

## Reviewer Notes

Does this unnecessarily bloat the e2e test?
Where should the optional text sit when the page is not on mobile view?

## Setup

Run app and ensure that you can add a new shipment with an existing shipment, from the review page.
also see e2e test for expected behavior.

## Code Review Verification Steps

* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] The requirements listed in
 [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely)
 have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://github.com/transcom/mymove/wiki/migrate-the-database#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/secure/RapidBoard.jspa?rapidView=28&modal=detail&selectedIssue=MB-3840&sprint=193) for this change
and https://dp3.atlassian.net/secure/RapidBoard.jspa?rapidView=28&modal=detail&selectedIssue=MB-3847&sprint=193

## Screenshots

If this PR makes visible UI changes, an image of the finished UI can help reviewers and casual
observers understand the context of the changes. A before image is optional and
can be included at the submitter's discretion.

Consider using an animated image to show an entire workflow instead of using multiple images. You may want to use GIPHY CAPTURE for this! 📸

_Please frame screenshots to show enough useful context but also highlight the affected regions._

2020-09-04 05:37 UTC, sojeri requested changes
the component changes look good to me. requesting changes for the e2e test side, though:

the longer this e2e test gets the more flakey it's going to get. I'd much rather see a jest component test which confirms this button shows on the review page. if you require an e2e test for this, I'd rather have a much simplied one which adds the minimum data without running any additional checks. do we really not have a way to prefill all the state required to get to the review page without running through the entire new user flow?

2020-09-04 05:37 UTC, sojeri commented on src/scenes/Review/Summary.jsx
> +    // const hasPPMorHHG = (isReviewPage && Object.keys(currentPPM).length) || Object.keys(mtoShipment).length;
do we need this commented out line for something? looks like this is new code, so not sure why it's here. :)

2020-09-04 05:41 UTC, sojeri commented
here are some screenshots not included in PR description for anyone else wandering by this PR :)

## desktop view of review page with add new shipment button

<img width="1110" alt="Screen Shot 2020-09-03 at 10 38 00 PM" src="https://user-images.githubusercontent.com/10818509/92203533-38fd7200-ee36-11ea-9b1a-e59a52e0a489.png">

## mobile view (mock samsung galaxy s5) of review page with add new shipment button

<img width="685" alt="Screen Shot 2020-09-03 at 10 39 18 PM" src="https://user-images.githubusercontent.com/10818509/92203566-516d8c80-ee36-11ea-8dab-a2819f6eb788.png">

2020-09-04 17:51 UTC, amitch23 commented on src/scenes/Review/Summary.jsx
> +    // const hasPPMorHHG = (isReviewPage && Object.keys(currentPPM).length) || Object.keys(mtoShipment).length;
I paired with @kimallen on this for a bit and Kim was under the impression that this button was to add a shipment whether there was a ppm or hhg. So, it would be possible to add a shipment without an existing shipment, and only a ppm. The ticket said otherwise, so I commented this out but wanted to leave it to raise the question in case I read the ticket wrong (https://dp3.atlassian.net/secure/RapidBoard.jspa?rapidView=1&projectKey=MB&modal=detail&selectedIssue=MB-3840&quickFilter=60)

2020-09-04 18:58 UTC, sojeri commented on src/scenes/Review/Summary.jsx
> +    // const hasPPMorHHG = (isReviewPage && Object.keys(currentPPM).length) || Object.keys(mtoShipment).length;
are we not counting PPM as a shipment? it definitely shows as a shipment in the designs. based on what you've said and the included abstract, I think the commented out line is the correct logic to match spec.

I am confused about the screen where an HHG and a PPM are in the list and the button is disabled. did you sync with Mariaclara on why that is?

2020-09-04 20:11 UTC, mariaclaratgolfo reviewed
Can we make the the following is currently aligned with the [visual design spec](https://share.goabstract.com/54bf497e-72bf-44b9-a169-3946e56ff710?collectionLayerId=afa6c581-79e8-452b-8683-f09188d2bc9c&mode=build)

- We're using H3 for mobile for the Add another shipment header.
- The Add another shipment button is the full width of the container (on mobile, the margins at left and right of container should be 20px). There should be 20px on either side of the button and it should be  aligned with the text above it. (eg. Optional should be aligned right with it, subcopy below subheader should be left aligned to it).
- There's 5 units above the section subheader [4opx] and 6 units between the Add another shipment button and the CTAs below it (48px)
- The optional tag should be flush against the container (so 20px to the right of it.

I can't tell what the intended disabled/enabled behavior is without clicking through with you so I will hold on logic comments around that!

2020-09-04 20:56 UTC, amitch23 commented on src/scenes/Review/Summary.test.js
> +  // Not able to find this element with shallow rendering :(
Even with removing the conditional wrapper for this h3 element, it is still not found

2020-09-04 23:59 UTC, amitch23 commented on src/scenes/Review/Summary.jsx
> +    // const hasPPMorHHG = (isReviewPage && Object.keys(currentPPM).length) || Object.keys(mtoShipment).length;
Some context here: https://ustcdp3.slack.com/archives/CTNTFJSBA/p1599246178169900

Still awaiting confirmation of this question: "Ok, so if the user has a PPM that has been submitted, the button should be disabled. And if the user has one or more HHGs (submitted or not), the button will be enabled, but the select-type page should not allow them to choose “HHG” - is that right?"

Until then, I am using the logic that if there is a ppm or hhg, user can add another shipment.

2020-09-08 21:44 UTC, Ronolibert commented
@mariaclaratgolfo We can finalize the design on the add another shipment section in https://dp3.atlassian.net/browse/MB-4110

2020-09-09 14:21 UTC, mariaclaratgolfo commented on src/scenes/Review/Summary.jsx
> +    // const hasPPMorHHG = (isReviewPage && Object.keys(currentPPM).length) || Object.keys(mtoShipment).length;
Shared this[ logic doc](https://docs.google.com/presentation/d/1Wqx8f3KzEqbCkqIvAztakwBaVF8jZ1JUYBECRsMJVBU/edit?usp=sharing) yesterday in Pamplemousse channel. Please let me know if there are still questions.

2020-09-09 14:28 UTC, mariaclaratgolfo reviewed
@Ronolibert If we're confident this work will be encompassed within the story you linked (mobile and desktop), then great! This story can go through, though incomplete. I'll need to have a pairing walk through to test the functionality as well which I can not do without staging. So the FE/behavior isn't approved/done until we review the new story.

2020-09-09 20:12 UTC, sojeri approved these changes
looks good to me! 🚀

2020-09-10 03:07 UTC, Ronolibert approved these changes

2020-09-10 13:47 UTC, mariaclaratgolfo approved these changes

2020-09-10 14:10 UTC, merged