[MB-4216] Signing and submitting a PPM routes to homepage
transcom/mymove pull request #4854
Opened 2020-09-23 19:53 UTC by Ronolibert

## Description

Signing and submitting a PPM routes to the new homepage

## Setup
`make server_run`
`make client_run`
Sign and submit a PPM

## Code Review Verification Steps
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-4216) for this change

2020-09-23 19:55 UTC, sojeri reviewed
code looks good! will pull locally and double check the flow after my next meeting, maybe around 2pm pacific.

2020-09-23 20:05 UTC, kimallen commented on src/scenes/Moves/Ppm/PaymentReview/index.jsx
> +          this.props.history.push('/');
So I thought we said we were not going to change this for Payment Request for now?

2020-09-23 20:21 UTC, Ronolibert commented on src/scenes/Moves/Ppm/PaymentReview/index.jsx
> +          this.props.history.push('/');
I'm going to revert this change! I was confused, I thought this was the legalese page since I saw the certificate submission.

2020-09-24 16:39 UTC, kimallen commented on cypress/integration/mymove/ppm.js
> -  cy.contains('Payment: Not ready yet');
I don't think we should delete these parts of the test.  Can we navigate to `/ppm` and have those checks?  Those messages are highly state dependent, so also easy to get wrong/ change inadvertently.

2020-09-24 16:40 UTC, Ronolibert commented on cypress/integration/mymove/ppm.js
> -  cy.contains('Payment: Not ready yet');
Sure, I can do that

2020-09-24 16:45 UTC, kimallen commented on src/scenes/Legalese/index.jsx
>      const landingPath = () => {
This no longer needs to be a function.  Can you change it to a variable?  It may be more appropriate now to call it `homePath` instead.

2020-09-24 16:46 UTC, kimallen requested changes
See comments- a couple quick adjustments

2020-09-24 16:54 UTC, kimallen approved these changes
Looks good- thanks for the quick changes!

2020-09-24 20:00 UTC, merged