MB-3616 TOO should only be able to add Mgmt & Counseling service items once
transcom/mymove pull request #4859
Opened 2020-09-25 00:57 UTC by donaldthai

## Description

> If the TOO has approved a shipment + Mgmt/Counseling service items, they should not be able to add them again.

This PR refactors the UI and backend service so the user can reject basic service items. This takes place during the time the TOO is approving shipments and basic service items.

## Reviewer Notes

Is there anything you would like reviewers to give additional scrutiny?

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

```sh
echo "Code goes here"
```

## Code Review Verification Steps

* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] The requirements listed in
 [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely)
 have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://github.com/transcom/mymove/wiki/migrate-the-database#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](tbd) for this change
* [this article](tbd) explains more about the approach used.

## Screenshots

If this PR makes visible UI changes, an image of the finished UI can help reviewers and casual
observers understand the context of the changes. A before image is optional and
can be included at the submitter's discretion.

Consider using an animated image to show an entire workflow instead of using multiple images. You may want to use GIPHY CAPTURE for this! 📸

_Please frame screenshots to show enough useful context but also highlight the affected regions._

2020-09-28 19:47 UTC, duncan-truss commented on pkg/services/mto_service_item/mto_service_item_creator.go
>  		verrs, err = o.builder.CreateOne(serviceItem)
Is there a reason CreateMTOServiceItem returns an array of service items if we are only ever creating just one?

2020-09-28 19:53 UTC, duncan-truss commented on pkg/services/mto_service_item/mto_service_item_creator.go
> +		if serviceItem.Status == "" {
Do we still need this conditional if the api requires a status?  Is this getting called somewhere else for basic service items?

2020-09-28 19:59 UTC, donaldthai commented on pkg/services/mto_service_item/mto_service_item_creator.go
>  		verrs, err = o.builder.CreateOne(serviceItem)
@sandy-wright made some changes to the service object to return an array which will support future work to create additional service items I believe. Here's the PR that did the changes: https://github.com/transcom/mymove/pull/4654/files

2020-09-28 20:12 UTC, donaldthai commented on pkg/services/mto_service_item/mto_service_item_creator.go
> +		if serviceItem.Status == "" {
That's a good point. The creator is [being used in other places like the Prime api](https://github.com/transcom/mymove/blob/master/pkg/handlers/primeapi/mto_service_item.go#L73) but maybe it would be better to explicitly pass in the status and just make sure the status is being passed back. I think we already have model validation before we create the service item.

2020-09-28 20:23 UTC, duncan-truss commented on pkg/services/mto_service_item/mto_service_item_creator.go
>  		verrs, err = o.builder.CreateOne(serviceItem)
Sounds good thanks for digging that back up

2020-09-28 20:26 UTC, duncan-truss commented on src/constants/mtoServiceItemStatusTypes.js
> +};
I think these are already defined under SERVICE_ITEM_STATUS in the `shared/constants` folder

2020-09-28 20:50 UTC, donaldthai commented on src/constants/mtoServiceItemStatusTypes.js
> +};
ah, I just didn't know. I can just use the one in the shared/contants.

2020-09-30 00:02 UTC, donaldthai commented on pkg/services/move_task_order/move_task_order_updater.go
> +
Didn't want to just do a double for loop to search for existing service items. Sorts the service items by code ascending order and the searching algorithm uses a binary search (assuming the collection is sorted).

2020-10-01 19:05 UTC, donaldthai commented on pkg/handlers/ghcapi/move_task_order.go
> +			serviceItemCodes[models.ReServiceCodeMS] = true
I felt like this took away the ambiguity of what service item codes are passed in. LMK if this doesn't work.

2020-10-01 19:08 UTC, donaldthai commented on src/components/Office/RequestedShipments/RequestedShipments.module.scss
> +    @include u-padding-top(2);
@transcom/truss-design I halved the padding since it looked a bit off to me. Let me know if that doesn't work.

2020-10-01 19:09 UTC, donaldthai commented on src/components/Office/RequestedShipments/RequestedShipments.module.scss
> +    @include u-padding-top(2);
I think you should be able to see the difference in happo now.

2020-10-01 20:59 UTC, duncan-truss commented
@donaldthai @brooksr4 If I'm looking at this right we are not displaying or saving to the database any basic service item that was rejected anymore?

2020-10-01 21:02 UTC, donaldthai commented
> @donaldthai @brooksr4 If I'm looking at this right we are not displaying or saving to the database any basic service item that was rejected anymore?

Nope, we're creating and displaying the ones that are selected for the first pass. On a second pass, users can only approve a shipment.

2020-10-01 22:03 UTC, duncan-truss commented on pkg/services/move_task_order/move_task_order_updater.go
> +	sort.Slice(mto.MTOServiceItems, func(i int, j int) bool {
This is MTOServiceItems array is going to include all of the accessorial service items (mainly) that are attached to a previous shipment not just any basic service items.  I feel like sorting all of those just to find if any basic service items exists is a lot of work, where maybe we can make some assumptions to simplify instead?  Or is there something changing in the future I don't know about?

Assumptions I think we know about MakeAvailableToPrime:
- Only basic services items (not accessorial) will ever be created (identifiable by their code or because they are special and have no shipment id associated)
- Basic service items will only ever be created the first time a Move Task Order becomes available to the prime.  After that they cannot be added when subsequent shipments are approved.
- No service items exist the first time a Move Task Order is being made available to the prime.

2020-10-01 22:04 UTC, duncan-truss commented on pkg/services/move_task_order/move_task_order_updater.go
> +		index := sort.Search(len(mto.MTOServiceItems), func(i int) bool {
I forgot how terrible searching was in Go 🤣

2020-10-01 22:09 UTC, duncan-truss commented on pkg/services/move_task_order/move_task_order_updater.go
> +	mtoApprovalServiceItems *map[models.ReServiceCode]bool) (*models.Move, error) {
I only see us iterating through this map, do you think it make sense to keep it a map if we're not doing lookups or ever getting a false bool value?

2020-10-01 22:38 UTC, donaldthai commented on pkg/services/move_task_order/move_task_order_updater.go
> +	sort.Slice(mto.MTOServiceItems, func(i int, j int) bool {
> I feel like sorting all of those just to find if any basic service items exists is a lot of work, where maybe we can make some assumptions to simplify instead? Or is there something changing in the future I don't know about?

Hmm that's a good point. I definitely also think that we can just use `available_to_prime_at` column to determine creating the service items or not. Thanks, I'll refactor.

2020-10-01 22:43 UTC, donaldthai commented on pkg/services/move_task_order/move_task_order_updater.go
> +	mtoApprovalServiceItems *map[models.ReServiceCode]bool) (*models.Move, error) {
I think if the user "intentionally" passes in a false value then we could encounter that. Otherwise, maybe instead of iterating, I could just pass in the bool values in the params?

2020-10-02 00:30 UTC, donaldthai commented on pkg/services/move_task_order/move_task_order_updater.go
> +	mtoApprovalServiceItems *map[models.ReServiceCode]bool) (*models.Move, error) {
Cool, just refactored to pass in bool values in the param.

2020-10-02 00:31 UTC, donaldthai commented on pkg/services/move_task_order/move_task_order_updater.go
> +	sort.Slice(mto.MTOServiceItems, func(i int, j int) bool {
Alright, we're only creating service items only if the `available_to_prime_at` is nil. Much simpler for sure.

2020-10-02 14:00 UTC, duncan-truss commented on pkg/services/move_task_order/move_task_order_updater.go
> +	sort.Slice(mto.MTOServiceItems, func(i int, j int) bool {
Thanks Donald, the changes I think reduced the complexity a lot. I saw that we are still calling update on the move task order, does that do anything if `available_to_prime_at` already has a value?

2020-10-02 14:12 UTC, duncan-truss commented on src/components/Office/RequestedShipments/RequestedShipments.jsx
> +      }
I think this can be one line now if we're being nitpicky:
```
const mtoApprovalServiceItemCodes = {
    serviceCodeMS: values.shipmentManagementFee,
    serviceCodeCS: values.counselingFee,
}
```

2020-10-02 14:14 UTC, duncan-truss commented on pkg/services/move_task_order/move_task_order_updater.go
> +	sort.Slice(mto.MTOServiceItems, func(i int, j int) bool {
👍 I see the conditional check in the form onSubmit now that doesn't even call approveMTO if it's already been set.

2020-10-02 14:15 UTC, duncan-truss approved these changes
👍

2020-10-02 19:20 UTC, suzubara commented on src/components/Office/RequestedShipments/RequestedShipments.jsx
> +            results[1]?.response?.status === 200 ||
why change this to `||`? Is there a scenario where one request can fail and it still is considered successful?

2020-10-02 19:20 UTC, suzubara commented on src/components/Office/RequestedShipments/RequestedShipments.jsx
> +              {mtoServiceItems?.length <= 0 && (
To clarify this logic, we should show these checkboxes if there are _no_ `mtoServiceItems`? In that case this might be better as:
```
!mtoServiceItems?.length && (...
```
that will eval to `true` if `mtoServiceItems` is undefined or if the length is 0. as-is, it will eval to `false` if mtoServiceItems is undefined, which I don't think is what we want..

2020-10-02 19:28 UTC, brooksr4 requested changes
Everything looks good, except the border-line for the service items should go all the way to the right.

2020-10-02 20:47 UTC, donaldthai commented
> Everything looks good, except the border-line for the service items should go all the way to the right.

@brooksr4 ok, just made the change to do full width for that service item area. Should be viewable once Happo is done generating differences.

for reference:
![image](https://user-images.githubusercontent.com/1522549/94968434-c4aa0300-04b5-11eb-841d-6b8a4fdf15c6.png)

2020-10-02 20:50 UTC, donaldthai commented on src/components/Office/RequestedShipments/RequestedShipments.jsx
> +            results[1]?.response?.status === 200 ||
oh that was a quick fix to refresh the page since the request to update the MTO status may not be included. Let me clean up the logic to make it clearer though.

2020-10-02 20:53 UTC, donaldthai commented on src/components/Office/RequestedShipments/RequestedShipments.jsx
> +              {mtoServiceItems?.length <= 0 && (
Squirrelly logic here...I wanted to show the button based on two cases:
1. show button if don't have any mto service items
2. show button if we haven't sent to prime

Probably easier to just check if we already sent to the prime or not. LOL. I'll refactor.

2020-10-02 20:58 UTC, donaldthai commented on src/components/Office/RequestedShipments/RequestedShipments.jsx
> +      }
Nice catch, I'll use that.

2020-10-02 21:22 UTC, brooksr4 approved these changes
looks good now

2020-10-02 22:03 UTC, donaldthai commented on src/components/Office/RequestedShipments/RequestedShipments.jsx
> +            results[1]?.response?.status === 200 ||
Okay, I moved the `results[1]?.response?.status === 200` logic inside the `if` and now we only need to reload the page if we're setting the status for the MTO. :D

2020-10-02 22:05 UTC, donaldthai commented on src/components/Office/RequestedShipments/RequestedShipments.jsx
> +              {mtoServiceItems?.length <= 0 && (
ok, `availableToPrimeAt` is now being used to determine to show the checkboxes. Much better I'd say.

2020-10-02 22:11 UTC, merged