[MB-4108] HHG and PPM  ShipmentCard storybook components
transcom/mymove pull request #4872
Opened 2020-09-28 16:40 UTC by Ronolibert

## Description

Adds storybook components for HHG and PPM Shipment cards

## Setup
`make storybook`

## Code Review Verification Steps
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-4108) for this change

## Screenshots

![image](https://user-images.githubusercontent.com/13622298/94461079-7f609b00-016e-11eb-95e5-cfa4b061feb0.png)
![image](https://user-images.githubusercontent.com/13622298/94461093-84254f00-016e-11eb-8278-5e22e0a44479.png)

2020-09-28 17:13 UTC, kimallen commented on src/components/Customer/Review/ShipmentCard/HHGShipmentCard/index.jsx
> +                {releasingAgent.email}
I believe email also needs a conditional since it is also an optional field.

2020-09-28 17:13 UTC, kimallen commented on src/components/Customer/Review/ShipmentCard/HHGShipmentCard/index.jsx
> +                {receivingAgent.email}
Add conditional to check for email

2020-09-28 17:26 UTC, kimallen commented on src/components/Customer/Review/ShipmentCard/HHGShipmentCard/index.jsx
> +            <p>{shipmentId}</p>
Amanda asked that I truncate the UUID to 10 in the home page ([discussion](https://ustcdp3.slack.com/archives/CTNTFJSBA/p1601064214059500)).  I don't want to do that unless we also do it on the Review page.  Could you do that here with `shipmentId.substring(0, 10)`?

2020-09-28 17:32 UTC, kimallen commented on src/components/Customer/Review/ShipmentCard/PPMShipmentCard/index.jsx
> +            <p>{shipmentId}</p>
Some request as above about (temporarily) using a substring of 10 here

2020-09-28 17:34 UTC, Ronolibert commented on src/components/Customer/Review/ShipmentCard/HHGShipmentCard/index.jsx
> +                {releasingAgent.email}
It shouldn't need one because if its not provided then its just empty

2020-09-28 17:35 UTC, kimallen commented on src/components/Customer/Review/ShipmentCard/PPMShipmentCard/index.jsx
> +  startingZIP: string.isRequired,
In most other parts of the application, we refer to this as originZIP- can we use that language here too for consistency?

2020-09-28 17:37 UTC, Ronolibert commented on src/components/Customer/Review/ShipmentCard/PPMShipmentCard/index.jsx
> +  startingZIP: string.isRequired,
Renamed this to originZIP

2020-09-28 17:38 UTC, kimallen commented on src/components/Customer/Review/ShipmentCard/HHGShipmentCard/index.jsx
> +            <dd>{destinationZIP}</dd>
I know previously we were told to use the full address here if a destination address existed, but otherwise use the destination duty station ZIP only.  I'm wondering if that changed, or if this needs to accommodate that.

2020-09-28 17:40 UTC, kimallen commented on src/components/Customer/Review/ShipmentCard/PPMShipmentCard/index.jsx
> +            <dd>{destinationZIP}</dd>
Wondering same as above here about using full address if a destination address is given.

2020-09-28 17:42 UTC, Ronolibert commented on src/components/Customer/Review/ShipmentCard/PPMShipmentCard/index.jsx
> +            <dd>{destinationZIP}</dd>
We separated that task to be in the implementation to the page [card](https://dp3.atlassian.net/browse/MB-4300)

2020-09-28 17:43 UTC, Ronolibert commented on src/components/Customer/Review/ShipmentCard/HHGShipmentCard/index.jsx
> +            <dd>{destinationZIP}</dd>
This'll be taken care of in [this card](https://dp3.atlassian.net/browse/MB-4300) when we use it on the page

2020-09-28 17:43 UTC, kimallen commented on src/components/Customer/Review/ShipmentCard/HHGShipmentCard/index.jsx
> +                {releasingAgent.email}
Would that not be true then for name and telephone?  Is it because it is the last field in the section?

2020-09-28 17:44 UTC, Ronolibert commented on src/components/Customer/Review/ShipmentCard/HHGShipmentCard/index.jsx
> +                {releasingAgent.email}
The others have it because they need linebreaks but this one doesn't need one since its last

2020-09-28 17:57 UTC, kimallen commented on src/components/Customer/Review/ShipmentCard/HHGShipmentCard/index.jsx
> +                {receivingAgent.email}
Resolved above

2020-09-28 18:32 UTC, kimallen approved these changes
LGTM!  Thanks for the quick responses to questions and tiny changes!

2020-09-28 21:06 UTC, duncan-truss commented on src/components/Customer/Review/ShipmentCard/HHGShipmentCard/index.jsx
> +  pickupLocation: shape({
This shape should be defined already https://github.com/transcom/mymove/blob/31cc51c1225ddd20a4c3d5e460a2aabe674955f9/src/types/address.js#L4 .  One day we'll fix the snake case coming back in the payload.

2020-09-28 21:09 UTC, duncan-truss commented on src/components/Customer/Review/ShipmentCard/HHGShipmentCard/index.jsx
> +              {pickupLocation.street_address_1} {pickupLocation.street_address_2}
We are doing something similar on the office side but don't have the hard break tag anymore.  I think design told us to make it a one line display https://github.com/transcom/mymove/blob/e46176ca160a4255e9e982556b53e48489b6adc1/src/utils/shipmentDisplay.jsx#L4 It doesn't include street_address_2 either yet.

2020-09-28 21:24 UTC, SirenaBorracha commented on src/components/Customer/Review/ShipmentCard/HHGShipmentCard/index.jsx
> +              {pickupLocation.street_address_1} {pickupLocation.street_address_2}
From Ron: "We'll leave it like this for now so it matches design spec, plus we're doing mobile first so if we had it as one single line then we'd have to rely on the natural word break of the addresses."

2020-09-28 22:35 UTC, suzubara requested changes
I left some comments, but the only blocking one is about the markup for the Remarks content

2020-09-28 22:35 UTC, suzubara commented on src/components/Customer/Review/ShipmentCard/HHGShipmentCard/index.jsx
> +          <Button className={styles.editBtn} unstyled>
There will need to be an `onClick` handler prop for this button

2020-09-28 22:35 UTC, suzubara commented on src/components/Customer/Review/ShipmentCard/HHGShipmentCard/index.jsx
> +          {remarks && (
I don't think this is good markup to achieve the full-width remarks content. Can the `remarks` be rendered inside of the `<dd>` element and we can apply custom CSS to the `div.row, dt, dd` to change the layout?

2020-09-28 22:35 UTC, suzubara commented on src/components/Customer/Review/ShipmentCard/ShipmentCard.module.scss
> +    @include u-padding-x('105');
what do these design tokens (`205, 105`) refer to? I haven't seen them used before

2020-09-28 22:35 UTC, suzubara commented on src/shared/formatters.js
> +export function formatCustomerDate(date) {
Can we add new formatter code under `src/utils`?

2020-09-28 22:35 UTC, suzubara commented on src/components/Customer/Review/ShipmentCard/ShipmentCard.module.scss
> +  @include u-margin-top(3);
Why the universal top margin?

2020-09-28 22:57 UTC, Shkeating commented on src/components/Customer/Review/ShipmentCard/ShipmentCard.module.scss
> +    @include u-padding-x('105');
105 = `12px`
205 = `20px`
https://designsystem.digital.gov/utilities/margin-and-padding/

2020-09-29 15:07 UTC, brooksr4 submitted a review, later dismissed
Some of the design stuff is a little bit off. The card header should be an `<h3>` with the following style attributes:
```
color: rgb(23, 23, 23);
font-size: 22px;
font-family: PublicSans-Bold;
font-weight: bold;
line-height: 26px;
```
The border-line above Expected Departure is missing and the same for Requested pickup date.

Also the content of the cards (minus the border-lines above Expected departure, PPM shipment weight and Requested pickup date) should have a left and right margin of about 24px (or 3 units).

Remarks should be to the right.

Here are screenshots from abstract of the cards: 
![image](https://user-images.githubusercontent.com/13547334/94576847-71c51700-023b-11eb-9316-938bc6dba425.png)
![image](https://user-images.githubusercontent.com/13547334/94576894-7ee20600-023b-11eb-824b-ffd85df3a5b9.png)


Here is a link to it in abstract for reference: https://share.goabstract.com/54bf497e-72bf-44b9-a169-3946e56ff710?collectionLayerId=87847ae6-e24d-4070-ae5f-25ae341b6b41&mode=design

2020-09-29 17:59 UTC, Ronolibert commented on src/components/Customer/Review/ShipmentCard/HHGShipmentCard/index.jsx
> +          {remarks && (
I couldn't find a way to ensure that the `<dd>` could be the full width of the table since its not a true table cell so I can't use colspan

2020-09-29 17:59 UTC, Ronolibert commented on src/components/Customer/Review/ShipmentCard/HHGShipmentCard/index.jsx
> +          <Button className={styles.editBtn} unstyled>
I'll add stub functions, but the true handlers will be added in the implementation card

2020-10-01 16:26 UTC, Ronolibert commented
@brooksr4 Made those changes! Also, I think we're using this [artboard](https://app.abstract.com/projects/1f6c1fd0-88a2-11e9-aaf7-a7ce5896598b/branches/master/commits/latest/files/4fa2c8bc-9dd1-4d09-b713-0bdc28483118/layers/F63F71B9-E837-43AA-83F1-55737B0DF60C?collectionId=ac5fb495-6a26-4019-a7e2-8b7df985bfd6&collectionLayerId=d1adb42e-695a-4bce-a958-7ae854034cc2&mode=build&selected=400467779-B3B3AB40-9DD5-493A-B7A6-FD581122E5CE) instead

2020-10-01 18:26 UTC, suzubara commented on src/components/Customer/Review/ShipmentCard/ShipmentCard.module.scss
> +    @include u-padding-x('105');
🤦‍♀️  well okay, that's random

2020-10-01 18:37 UTC, suzubara approved these changes

2020-10-01 18:53 UTC, Ronolibert commented on src/components/Customer/Review/ShipmentCard/ShipmentCard.module.scss
> +    display: table;
Good catch! Removed it

2020-10-01 19:00 UTC, Shkeating commented
I would recommend that you organize this a little differently in Storybook. right now, you have the Shipment Cards listed as completely different components, while i would recommend that you nest them underneath a section called `ShipmentCard`, similarly to how we handle `Shipment Display` in the [TIO/TOO section](https://storybook.dp3.us/?path=/story/too-tio-components-shipment-display--nts-shipment).

2020-10-01 19:12 UTC, Shkeating commented on src/components/Customer/Review/ShipmentCard/HHGShipmentCard/index.jsx
> +            <h4>HHG {shipmentNumber}</h4>
we want this to be an h3, so that it is 17px on mobile and 22px on desktop! you're going to have to add in styling in your css module to un-bold it.

2020-10-01 19:55 UTC, Ronolibert commented
@Shkeating Made those changes and grouped the shipment cards under ShipmentCards

2020-10-01 20:06 UTC, Shkeating approved these changes

2020-10-01 20:14 UTC, merged