[MB-4229] Hide back btn and add 'finish later' btn to review page
transcom/mymove pull request #4878
Opened 2020-09-29 20:04 UTC by amitch23

## Description

Removes "back" button and adds "Finish Later" button to the review page. Since there are a handful of other tickets to deal with routing and buttons on the whole flow (see tickets tagged with the epic "routing updates" - https://dp3.atlassian.net/browse/MB-3849), I adapted the Wizard Page to take props to hide the back btn and to show the "finish later" button. I thought this best in order to roll out the changes iteratively.

## Setup

See the review page and ensure that there is no back button, and the "finish later" routes to the home page.

## Code Review Verification Steps

* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] The requirements listed in
 [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely)
 have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://github.com/transcom/mymove/wiki/migrate-the-database#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/secure/RapidBoard.jspa?rapidView=1&projectKey=MB&modal=detail&selectedIssue=MB-4229&quickFilter=60) for this change

## Screenshots

<img width="402" alt="Screen Shot 2020-09-29 at 12 24 44 PM" src="https://user-images.githubusercontent.com/8170735/94609564-d2604e00-0253-11eb-916a-96eac048ffae.png">

2020-09-30 16:31 UTC, kimallen commented on src/shared/WizardPage/index.jsx
> +                data-testid="wizardFinishLaterButton"
I see a lot of the `data-testid` values in kebab case in the cypress tests, and then here you are using camelCase.  Is camelCase the preferred standard?

2020-09-30 16:37 UTC, kimallen commented on cypress/integration/mymove/hhg.js
>    cy.get('[data-testid="review-move-header"]').contains('Review your details');
I'm wondering if we want a test to click the `Finish Later` button and take them to the home page and then have them click `Review and submit` to get to the Review page again.  I think we are trying to put more emphasis on client tests and focus mostly on the happy path in integration tests, so I'm not sure.

2020-09-30 16:46 UTC, kimallen requested changes
Code looks good and works as expected!

It looks like from [this Abstract](https://app.abstract.com/projects/1f6c1fd0-88a2-11e9-aaf7-a7ce5896598b/branches/master/commits/latest/files/4794a2f1-15d3-42e5-aa8f-be21f9ede9ce/layers/7A3BED69-D33D-4A02-BDEF-81B6B21B3BFE?collectionId=72626442-df23-421f-bd5c-3ae6ade7d534&collectionLayerId=afa6c581-79e8-452b-8683-f09188d2bc9c) that we want the `Next` and `Finish later` buttons to be stacked when in phone view. 
![image](https://user-images.githubusercontent.com/13249580/94715014-c4690680-0301-11eb-86f0-951181334021.png)
 That and making 'later' lowercase are the only blocking changes.

2020-09-30 16:47 UTC, kimallen commented on src/shared/WizardPage/index.jsx
> +                Finish Later
later should be lower case

2020-09-30 21:36 UTC, amitch23 commented on src/shared/WizardPage/index.jsx
> +                data-testid="wizardFinishLaterButton"
I followed the pattern in this component for the buttons' data-testid values to be camelCase. I also see both, and I don't know which is the preferred standard. I asked in slack and will update with the answer here.

2020-09-30 21:37 UTC, amitch23 commented on cypress/integration/mymove/hhg.js
>    cy.get('[data-testid="review-move-header"]').contains('Review your details');
That's a good idea. :) I'll give that a go

2020-09-30 21:42 UTC, amitch23 commented on src/shared/WizardPage/index.jsx
> +                data-testid="wizardFinishLaterButton"
@suzubara says "I don’t think we have discussed or documented. I would throw a vote out there for camelCase to be consistent with JS var naming :shrug:", How about we stick to camelCase?

2020-09-30 23:47 UTC, amitch23 commented
@Shkeating @suzubara I'm having trouble with the formatting and display of the buttons to match the spec and was hoping you could offer some insight and help. I'll list the issues here, referencing the screenshots in the PR description:
1. Because the wizard buttons are inside a `grid-row`, it seems like the spacing of the buttons on the right is off and doesn't align with the "add a shipment" button. Moving them out of a row and into a `grid-col-row` fixes it, but then the buttons are not horizontally aligned on desktop view, but rather, vertically aligned. Not a good look :/
2. The "finish later" button size does not match the "next" button, and it's much "smaller", as compared to the screenshot of the buttons Kim posted above.
3. I'm not sure how to handle the margin between the "next" and "finish later" buttons and the "add shipment button" section. I adapted the existing style applied to the div on the wizard page (changed from .5rem to 2rem) but am not sure if this is the best practice way to handle this. I also don't know what the units in abstract represent - is that 6 px? Or 6 units of a pixel measurement?

2020-10-01 18:19 UTC, suzubara approved these changes
looks good!

2020-10-01 18:19 UTC, suzubara commented on src/shared/WizardPage/index.jsx
> +          {/* <div className="grid-col-10 text-right margin-top-6 margin-left-neg-1 tablet:margin-top-3 display-flex"> */}
can we delete this line altogether?

2020-10-01 18:19 UTC, suzubara commented on src/shared/WizardPage/index.css
> +
I don't love this but acknowledge it's prob the easiest way to apply these styles until the wizard nav can be refactored 🧹

2020-10-01 20:20 UTC, kimallen approved these changes
Changes approved!

2020-10-01 20:30 UTC, Shkeating approved these changes
lookin good!

2020-10-02 01:14 UTC, merged