[MB-4427] MS and CS service items should not error out when generating EDI
transcom/mymove pull request #4879
Opened 2020-09-29 20:13 UTC by garrettqmartin8

## Description

Creating an EDI from a payment request for only MS and CS fails due to missing dates.  

## Setup

1. `make server_run`
2. Create a payment request. Create a file called `create_payment_request.json` in the project root and paste in the JSON payload provided below:

```json
{
  "body": {
    "isFinal": false,
    "moveTaskOrderID": "9c7b255c-2981-4bf8-839f-61c7458e2b4d",
    "serviceItems": [
      {
        "id": "722a6f4e-b438-4655-88c7-51609056550d"
      },
      {
        "id": "ca9aeb58-e5a9-44b0-abe8-81d233dbdebf"
      }
    ]
  }
}
```

2. Use the Prime API Client to create the payment request and return the payment request number by running the command below:

```sh
prime-api-client --insecure create-payment-request --filename  create_payment_request.json | jq '.paymentRequestNumber'
```
3. Use the CLI utility to generate the EDI858 and view it in your terminal. Remember to pass the payment request number of the payment request you just created.

```sh
go run ./cmd/generate-payment-request-edi/ --payment-request-number [$paymentRequestNumber]
```

You should see a valid EDI in standard out with MS and CS service items.

## References

[Jira story](https://dp3.atlassian.net/browse/MB-4427)

2020-09-29 23:26 UTC, gidjin requested changes
Changes work, but there are a couple of issues that I left in the comments.

2020-09-29 23:26 UTC, gidjin commented on pkg/services/invoice/ghc_payment_request_invoice_generator.go
> +		edi858.Header = append(edi858.Header, originDestinationSegments...)
Why is this here, I would expect that even MS and CS only payment requests still have service member orders object so we can still include origin and destination. Basically I expect that an MTO will have an Orders object even if there are not shipments.

2020-09-29 23:26 UTC, gidjin commented on pkg/services/invoice/ghc_payment_request_invoice_generator.go
> +func msAndCsOnly(paymentServiceItems models.PaymentServiceItems) bool {
This method is named confusingly to me. The name `msAndCsOnly` implies that it should return true if we only have MS and CS, but it does the opposite of that. I would change it to return true if we only MS or CS and rename it to `msOrCsOnly` since a PaymentRequest could be just one as far as I understand.

2020-09-30 14:37 UTC, reggieriser commented on pkg/services/invoice/ghc_payment_request_invoice_generator.go
> +			codesWithoutMsOrCs = append(codesWithoutMsOrCs, code)
A couple of things here:
- Let's do the comparison against the constants like `ReServiceCodeMS` and `ReServiceCodeCS` rather than converting to a string and testing against string literals.
- Nit: Since you only care if there's a code that's not either MS or CS, couldn't you just return false immediately in the loop as soon as you see one rather than building up another slice and testing its length.

2020-09-30 14:40 UTC, garrettqmartin8 commented on pkg/services/invoice/ghc_payment_request_invoice_generator.go
> +		edi858.Header = append(edi858.Header, originDestinationSegments...)
Yep, this is wrong. I'll move that out of the conditional. Good catch!

2020-09-30 14:41 UTC, garrettqmartin8 commented on pkg/services/invoice/ghc_payment_request_invoice_generator.go
> +			codesWithoutMsOrCs = append(codesWithoutMsOrCs, code)
Yep, both of those changes make sense. I'll address them now.

2020-09-30 15:18 UTC, gidjin commented
You'll also want to pull master to resolve the `pre_test` failure

2020-09-30 17:22 UTC, gidjin approved these changes
LGTM, thanks for making those changes.

2020-09-30 17:22 UTC, gidjin commented on pkg/services/invoice/ghc_payment_request_invoice_generator.go
> +		DateQualifier: 86,
When pairing with Reggie we noticed this was `86` which is for Actual Pickup date vs `10` for Requested Pickup date. But I'm fine if this is fixed as part of Reggie's PR which will add the additional dates.

2020-09-30 17:22 UTC, gidjin commented on pkg/services/invoice/ghc_payment_request_invoice_generator.go
> +	if !msOrCsOnly(paymentServiceItems) {
Small nitpick, I don't like `if !boolean` because the `!` is easy to miss, but not sure there is a clear better way to adjust this so I'm fine if it stays.

2020-09-30 17:36 UTC, reggieriser approved these changes
LGTM -- thanks for making the changes!

2020-09-30 18:04 UTC, garrettqmartin8 commented on pkg/services/invoice/ghc_payment_request_invoice_generator.go
> +	if !msOrCsOnly(paymentServiceItems) {
Yeah I toyed around with names for this and I think it's important that we make it clear that the situation in which this conditional is met has to do with their only being MS or CS. I unfortunately couldn't come up with something that I liked better.

2020-09-30 18:35 UTC, merged