Kim mb 4125 selectable card component
transcom/mymove pull request #4883
Opened 2020-09-29 23:24 UTC by kimallen

## Description

Creates a SelectableCard component for a radio and adds it to storybook.  Three states are displayed in storybook: unselected, selected, and disabled.

## Reviewer Notes

I did not create a checkbox option or separate component.  it sounded like it may not be necessary ([see thread](https://ustcdp3.slack.com/archives/CTNTFJSBA/p1601334712127300)) right now.

## Setup

`make storybook`

Look under Customer Components --> SelectableCard

## Code Review Verification Steps

* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-4125) for this change.

## Screenshots
phone view:
![image](https://user-images.githubusercontent.com/13249580/94626360-d13d1a00-026f-11eb-9e24-749bcb65c4bb.png)

browser view:
![image](https://user-images.githubusercontent.com/13249580/94626416-e87c0780-026f-11eb-8302-e869424ba908.png)

selected:
![image](https://user-images.githubusercontent.com/13249580/94626455-fcc00480-026f-11eb-9efd-e1e7008b0e40.png)

disabled:
![image](https://user-images.githubusercontent.com/13249580/94626503-11040180-0270-11eb-8033-08227f09a9ac.png)

2020-09-30 15:25 UTC, Shkeating requested changes
This is great! I am noticing is the drop shadow is missing when the card is selected. I've spent some time this morning to see if there was a css-only way to acheive this, but I think we need to add a class/id to the `.cardContainer` div in order to have a way to target the div when the radio is selected. when we have a way to target it, we should be able to add the shadow with `@include u-shadow(2);`

The only other thing I am noticing this that the icon in the top left corner is missing, but it seems that icon has not been added to the repo for use (if it were, you would find it here: https://storybook.dp3.us/?path=/story/global-icons--all) I will export it out of the Sketch file and get it added for you ASAP!

2020-09-30 15:38 UTC, suzubara commented
> The only other thing I am noticing this that the icon in the top left corner is missing, but it seems that icon has not been added to the repo for use (if it were, you would find it here: https://storybook.dp3.us/?path=/story/global-icons--all) I will export it out of the Sketch file and get it added for you ASAP!

Since we're not implementing the actual handler for this icon in this story, it seems like it would make more sense to add the icon itself when we do add the tooltip/modal?

2020-09-30 15:57 UTC, suzubara requested changes
This is in really good shape! I did leave some comments but overall great job :D

2020-09-30 15:57 UTC, suzubara commented on src/components/Customer/SelectableCard.jsx
> +  cardText: string,
We will probably want `cardText` to be `PropTypes.node` so that it can include rich text. Then the usage would be something like:
```
<SelectableCard cardText={<p>My card description...</p>} ... />
```

2020-09-30 15:57 UTC, suzubara commented on src/components/Customer/SelectableCard.module.scss
> +  border-radius: 0.26667rem;
I think using px or units for border radius will be easier to keep track of.. it looks like this translates to `border-radius: 2px`

2020-09-30 15:57 UTC, suzubara commented on src/components/Customer/SelectableCard.module.scss
> +  margin: 1.6rem;
We will probably not want to set global margins on this component, because it will depend a lot on the context within which it's rendered. I would recommend removing this. However it _can_ be useful to set margins in between repeated components, ie.:

```
.cardContainer + .cardContainer {
  @include u-margin-top(1);
}
```

That will set a 1 unit top margin to SelectableCards that follow other SelectableCards

2020-09-30 15:57 UTC, suzubara commented on src/components/Customer/SelectableCard.module.scss
> +  font-size: 13px;
Looking at the designs, I think this also needs `line-height: 1.25;` to achieve a 16px line height

2020-09-30 15:57 UTC, suzubara commented on src/components/Customer/SelectableCard.test.jsx
> +describe('SelectableCard component', () => {
This component should not need to be mounted with the Redux provider & store. It can just be a basic:
```
mount(<SelectableCard {...props} />)
```

2020-09-30 16:13 UTC, kimallen commented on src/components/Customer/SelectableCard.module.scss
> +  margin: 1.6rem;
TIL!

2020-09-30 16:16 UTC, kimallen commented
> This is great! I am noticing is the drop shadow is missing when the card is selected. I've spent some time this morning to see if there was a css-only way to achieve this, but I think we need to add a class/id to the `.cardContainer` div in order to have a way to target the div when the radio is selected. when we have a way to target it, we should be able to add the shadow with `@include u-shadow(2);`
> 
> The only other thing I am noticing this that the icon in the top left corner is missing, but it seems that icon has not been added to the repo for use (if it were, you would find it here: https://storybook.dp3.us/?path=/story/global-icons--all) I will export it out of the Sketch file and get it added for you ASAP!

oof- you're right- I totally forgot about the color change and didn't see the drop shadow when selected.  Will work on that.

Do you mean to informational icon in the top right?  The story specifically says not to worry about that- we will cover it when we build the modal in another story.

2020-09-30 18:05 UTC, kimallen commented on src/components/Customer/SelectableCard.module.scss
> +  background-color: #ecf1f7;
@Shkeating - I didn't find a close enough color in the colors.scss.  I should probably add this color into that file-- do you have any recommendations for where that should go or for a name?

2020-09-30 18:44 UTC, kimallen commented on src/components/Customer/SelectableCard.module.scss
> +  background-color: #ecf1f7;
`$link-light` is the closest existing color I could find, but it was a a little darker

2020-09-30 19:42 UTC, amanda5iu requested changes
Thanks for including screenshots Kim. This looks great! 

My only note is that on desktop, the grey text should be left-aligned with the radio button label. After that, looks like we're good to go!

2020-09-30 20:22 UTC, amanda5iu approved these changes

2020-09-30 21:29 UTC, Shkeating approved these changes
i'm going to approve so this can move forward. Once I find out what color variable actually should be here for the selected box's background color, I'll open up a branch and fix it! The drop shadow looks great!

2020-09-30 23:35 UTC, kimallen commented on src/components/Customer/SelectableCard.module.scss
> +  background-color: #ecf1f7;
@Shkeating -thx for asking in #prac-design.  I ended up added two colors from the palette that were missing. (info-light and info).

2020-10-01 18:08 UTC, suzubara approved these changes
Updates look good! 💯

2020-10-01 18:32 UTC, merged