[WIP] [MB-4266] Update messaging in submitted HHG/NTS(r) Helper
transcom/mymove pull request #4898
Opened 2020-10-01 16:02 UTC by suzubara

## Description

Explain a little about the changes at a high level.

## Reviewer Notes

Is there anything you would like reviewers to give additional scrutiny?

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

```sh
echo "Code goes here"
```

## Code Review Verification Steps

* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] The requirements listed in
 [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely)
 have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://github.com/transcom/mymove/wiki/migrate-the-database#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](tbd) for this change
* [this article](tbd) explains more about the approach used.

## Screenshots

If this PR makes visible UI changes, an image of the finished UI can help reviewers and casual
observers understand the context of the changes. A before image is optional and
can be included at the submitter's discretion.

Consider using an animated image to show an entire workflow instead of using multiple images. You may want to use GIPHY CAPTURE for this! 📸

_Please frame screenshots to show enough useful context but also highlight the affected regions._

2020-10-01 18:39 UTC, Ronolibert commented on src/components/Customer/Home/Helper/Helper.module.scss
> +.Helper {
Is there a convention we're following for this? Titlecase for parent containers and camelCase for any other subsequent?

2020-10-01 18:43 UTC, Ronolibert commented on src/scenes/Review/Summary.jsx
> +              id="addAnotherShipmentBtn"
[nit] I don't think we need this `id`. It's not being used anywhere

2020-10-01 18:48 UTC, Ronolibert approved these changes
Looks good! Had a question and a couple nits but nothing blocking

2020-10-01 18:48 UTC, Ronolibert commented on src/scenes/Review/Summary.jsx
> +              className="usa-button--secondary"
We could use the `secondary` prop on the button here instead of the `className`

2020-10-01 18:48 UTC, Ronolibert commented on src/pages/MyMove/Home/index.test.jsx
> +      ...defaultProps,
[nit] Instead of spreading over defaultProps for all these functions, we could restructure `mountHome` to be:
```
function mountHome(props = {}) {
  return mount(
    <Provider store={store}>
      <Home {...defaultProps} {...props} />
    </Provider>,
  );
}
```

2020-10-01 21:52 UTC, suzubara commented on src/components/Customer/Home/Helper/Helper.module.scss
> +.Helper {
We haven't established a convention, but I like using TItlecase for classes that apply to the root element of a component (and naming the class the same as the component). The main thing I think is to avoid dash & underscores. there is probably a lint rule we can add..

2020-10-02 14:38 UTC, amanda5iu requested changes
This mostly looks good to me. A couple style notes:

- Can we change the padding in the helper to 3 units on desktop? Let's apply this to all instances of the helper.
- Links should be bold per the mock. I know this deviates from the standard MMDS link, but maybe we can add a font-weight override for all links in the helper component?

2020-10-02 15:27 UTC, Shkeating commented
I'd like to see the external link icon use MMDS colors (it looks like it's using USWDS defaults rn), and when pseudo classes such as :visited are applied, ideally the icon would change colors the same way the rest of the link does.

2020-10-02 15:51 UTC, suzubara commented
New screenshots: 

Desktop
![image](https://user-images.githubusercontent.com/2723066/94943293-12664180-049d-11eb-85eb-8e2b51db093f.png)

Mobile
![image](https://user-images.githubusercontent.com/2723066/94943319-201bc700-049d-11eb-905e-1eb2d98b6fe4.png)

Mobile (visited)
![image](https://user-images.githubusercontent.com/2723066/94943368-36c21e00-049d-11eb-824c-d779adedf13d.png)

2020-10-02 18:30 UTC, amanda5iu reviewed
The links should technically be `base-darkest` and underlined according to the mocks, but I kinda like it this way because it's closer to the MMDS link style. Is it cool if we wait to get @mariaclaratgolfo's take on Monday? I'm sure she had a reason for styling the links this way.

2020-10-05 18:02 UTC, mariaclaratgolfo commented
I like the blue styling as well, especially if this is how we typically treat links that appear in sentences/paragraphs. A couple of things I can't quite discern from looking at the screenshots:
• Is the link / text in bullet 1 larger than that of bullet 2? Might just be my eyes!
• Is there 40px min tap area for these links on mobile with the applied padding?
• Is the icon denoting being taken to another website the same size as for the font?
• Is this how we treat 'visited' linked [purple] across the app? @Shkeating

2020-10-05 18:15 UTC, suzubara commented
> I like the blue styling as well, especially if this is how we typically treat links that appear in sentences/paragraphs. A couple of things I can't quite discern from looking at the screenshots:
> • Is the link / text in bullet 1 larger than that of bullet 2? Might just be my eyes!

Nope, the text size is consistent across all bullets.

> • Is there 40px min tap area for these links on mobile with the applied padding?

We had some discussion about this on slack and confirmed the 40px min tap area does _not_ apply to inline text links.

> • Is the icon denoting being taken to another website the same size as for the font?

The icon is applied via USWDS styles using a background svg, so we aren't planning to customize it for now. We can address it further in the future if there's an issue.

> • Is this how we treat 'visited' linked [purple] across the app? @Shkeating

Yup, should be! @Shkeating can confirm

2020-10-05 18:31 UTC, mariaclaratgolfo commented
Re: all other things — awesome!

For the tap area one, what if our fat fingered friends on mobile have instance like [this](https://share.goabstract.com/0f81571d-01df-4aa6-a856-2b9d5ec5a927?collectionLayerId=acb4d785-d6f2-47b0-b37d-034a97f07ff7&mode=design) where there are consecutive links in each bullet? Where can I visit the slack discussion on this?

2020-10-05 19:45 UTC, suzubara commented
> Re: all other things — awesome!
> 
> For the tap area one, what if our fat fingered friends on mobile have instance like [this](https://share.goabstract.com/0f81571d-01df-4aa6-a856-2b9d5ec5a927?collectionLayerId=acb4d785-d6f2-47b0-b37d-034a97f07ff7&mode=design) where there are consecutive links in each bullet? Where can I visit the slack discussion on this?

Slack discussion at https://ustcdp3.slack.com/archives/CNTDW9Q1Z/p1601566919108000

The alternative would be making the whole bullet text a link. I think if we want to discuss other solutions, we should do it at a system wide level because this will be an issue whenever we have an inline text link. The way it's implemented now is consistent with mobile web standards.

2020-10-05 19:49 UTC, amanda5iu approved these changes

2020-10-05 21:23 UTC, merged