MB 4436 Standardize Heading type/size across all move setup screens
transcom/mymove pull request #4900
Opened 2020-10-01 17:20 UTC by Shkeating

## Description

This branch makes it so all top-level headers in the customer app are h1s, with the same text size, weight, and type scaling across devices. This creates a more consistent page layout across the customer app experience.

The pages affected by this PR include:
   - ppmCloseout - Customer Agreement page
   - hhg - HHG details form, Review Your Details, “Now for the official part” pages
   - Homepage “Welcome to my.move.mil”
   - ppm homepage “New move”
   - ppm “How much do you think you’ll move” page

## Reviewer Notes

Is there any pages I missed? Let me know! I caught most of these by running through our e2e/integration tests, so if there are areas they don't cover I'll have to go back through and look.

## Setup

```sh
make db_dev_e2e_populate
make server_run
make client_run
```

## Code Review Verification Steps

* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-4436?atlOrigin=eyJpIjoiOTk4MjJhN2YyOWYzNGVhMzlkZDA0NTVmYTdmNmU5MzgiLCJwIjoiaiJ9) for this change

## Screenshots

2020-10-01 17:41 UTC, kimallen reviewed
Looks like parts of the Payment request flow needs those changes too  `scenes/Moves/Ppm/PpmPaymentRequestIntro`,  `WeightTicketExamples.jsx`
That may not be all-inclusive.  I recommend checking in `scenes/MyMove/index.jsx` Which leads you to all of the pages that would have toplevel H1s.  Also look through `getWorkFlowRoutes.jsx` which also names pages.

2020-10-01 18:41 UTC, suzubara commented on src/components/Customer/EditShipment.jsx
> +        <h1 className="margin-top-1" style={{ fontSize: 28 }}>
@Shkeating Should this still have a custom font size applied with the style attr?

2020-10-01 21:08 UTC, Shkeating commented on src/components/Customer/EditShipment.jsx
> +        <h1 className="margin-top-1" style={{ fontSize: 28 }}>
nope!! thanks for pointing that out. I am seeing several of these have font sizes getting applied to them that I need to adjust. I didn't realize that making a draft PR would still notify everyone 😅

2020-10-05 16:03 UTC, Shkeating commented
@amanda5iu some images:

before on the left, after on the right:

**HHG Details, mobile**
<img width="763" alt="image" src="https://user-images.githubusercontent.com/59394696/95103378-86555380-0702-11eb-8e6c-aa7b2ebafab3.png">


**HHG Details, desktop**
<img width="863" alt="image" src="https://user-images.githubusercontent.com/59394696/95103525-b3096b00-0702-11eb-9ddf-ace2a209fb16.png">

2020-10-05 17:09 UTC, suzubara requested changes
could you remove the `.loki` directory from your branch? Updating from master might also resolve it. otherwise the changes look good!

2020-10-05 19:38 UTC, amanda5iu approved these changes
So satisfying to see this. LGTM!

2020-10-05 20:06 UTC, suzubara approved these changes

2020-10-05 20:14 UTC, merged