[WIP] Update Review page design using storybook components
transcom/mymove pull request #4909
Opened 2020-10-02 19:49 UTC by Ronolibert

…data shape

## Description

Explain a little about the changes at a high level.

## Reviewer Notes

Is there anything you would like reviewers to give additional scrutiny?

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

```sh
echo "Code goes here"
```

## Code Review Verification Steps

* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] The requirements listed in
 [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely)
 have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://github.com/transcom/mymove/wiki/migrate-the-database#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](tbd) for this change
* [this article](tbd) explains more about the approach used.

## Screenshots

If this PR makes visible UI changes, an image of the finished UI can help reviewers and casual
observers understand the context of the changes. A before image is optional and
can be included at the submitter's discretion.

Consider using an animated image to show an entire workflow instead of using multiple images. You may want to use GIPHY CAPTURE for this! 📸

_Please frame screenshots to show enough useful context but also highlight the affected regions._

2020-10-05 17:02 UTC, suzubara reviewed
left some general comments since this is still a WIP!

2020-10-05 17:02 UTC, suzubara commented on src/shared/utils.js
> +// Format orders type (ex: PERMANENT_CHANGE_OF_STATION => Permanent change of station)
It would be great to stop adding new code under `shared`, can we start a file under `src/utils` for any new formatters?

2020-10-05 17:02 UTC, suzubara commented on src/components/Customer/Review/ShipmentCard/HHGShipmentCard/index.jsx
> +            <dd>
Maybe we can create a shared function for formatting names & addresses, since this probably occurs in a lot of places throughout the app?

2020-10-05 20:36 UTC, Ronolibert commented on src/scenes/Review/Review.css
> +.review-move-container {
Moved this to the module

2020-10-05 20:36 UTC, Ronolibert commented on src/shared/utils.js
> +// Format orders type (ex: PERMANENT_CHANGE_OF_STATION => Permanent change of station)
Made the formatters file in utils

2020-10-05 20:40 UTC, Ronolibert commented on src/components/Customer/Review/OrdersTable/index.jsx
> +      <Button unstyled className={reviewStyles['edit-btn']} onClick={() => onEditClick(editPath)}>
i'm not sure what you mean by this, do you mean handling the logic of what path it would navigate to in the handler itself? I just did it this way because the alternative was passing in the `moveId` to the component itself just to be used as an argument for the handler

2020-10-05 21:16 UTC, Ronolibert commented on src/components/Customer/Review/ShipmentCard/HHGShipmentCard/index.jsx
> +            <dd>
Added a function for the addresses!

2020-10-05 22:16 UTC, suzubara commented on src/components/Customer/Review/OrdersTable/index.jsx
> +      <Button unstyled className={reviewStyles['edit-btn']} onClick={() => onEditClick(editPath)}>
So looking at the Summary component, where `OrdersTable` is rendered, it would look like this:
```
<OrdersTable onEditClick={() => this.handleEditClick(editOrdersPath) } ...
```

this is assuming that the edit handler for `OrdersTable` will be constant, but that is my impression based on the code.

2020-10-06 14:06 UTC, mariaclaratgolfo commented
This is looking great!

- In Happo, it appears we now have two ## signs appearing ahead of the shipment code for the shipment cards. This is appearing on the Review page and the Home page shipment cells. Let's be sure that's not the case

- Let's make sure the padding below each subheader [Profile, Orders, Move setup] is the same. It should be 3 units below each. Right now it appears the space below Move setup is smaller than the others.

- The buttons at the bottom of the page should be side by side [Back to the left, Next to the right]

2020-10-06 14:07 UTC, mariaclaratgolfo requested changes
Left a comment with a couple of things to double check

2020-10-06 16:58 UTC, Ronolibert commented on src/components/Customer/Review/OrdersTable/index.jsx
> +      <Button unstyled className={reviewStyles['edit-btn']} onClick={() => onEditClick(editPath)}>
Ahh yeah, I guess this is a case of a little bit of premature optimization. I'll change this so that the handler passed in is responsible for where it is going

2020-10-06 22:19 UTC, kimallen commented
> This is looking great!
> 
> * In Happo, it appears we now have two ## signs appearing ahead of the shipment code for the shipment cards. This is appearing on the Review page and the Home page shipment cells. Let's be sure that's not the case
> * Let's make sure the padding below each subheader [Profile, Orders, Move setup] is the same. It should be 3 units below each. Right now it appears the space below Move setup is smaller than the others.
> * The buttons at the bottom of the page should be side by side [Back to the left, Next to the right]

We should clarify about the side-by-side v. stacked.  Last week there was various conversation about it (there's different ways they show up in designs), and it was determined to do them stacked in phone view and side by side in browser view. @amanda5iu @mariaclaratgolfo

2020-10-07 06:45 UTC, Ronolibert commented on src/components/Customer/Review/OrdersTable/index.jsx
> +      <Button unstyled className={reviewStyles['edit-btn']} onClick={() => onEditClick(editPath)}>
Simplified this logic

2020-10-07 17:08 UTC, mariaclaratgolfo approved these changes

2020-10-08 15:15 UTC, suzubara commented on src/components/Customer/Review/ShipmentCard/ShipmentCard.module.scss
> +.todo {
if this is a style that should be able to applied anywhere to indicate a WIP, it might actually be easier to add to a global CSS file instead of a CSS module 🤷‍♀️

2020-10-08 15:15 UTC, suzubara commented on src/components/Customer/Review/Summary/index.test.jsx
> +import { Summary } from '.';
can this be `'./index'` just so it's a little clearer?

2020-10-08 15:15 UTC, suzubara commented on src/pages/MyMove/Review/index.jsx
> +/* eslint-disable import/no-named-as-default */
I'd prefer if we didn't ignore this ESLint rule. to get around it, you have to name the default export something that is not already a named export. Usually this means the default export is the component with Redux and/or other HOCs, so a common convention is to do something like `import ConnectedWizardPage from 'shared/WizardPage';`. then it's clearer what is being imported.

2020-10-08 15:15 UTC, suzubara commented on src/components/Customer/Review/Summary/Summary.module.scss
> +  margin: 0 !important;
I don't see what effective styles these are implementing.. there's already a margin bottom and margin top on the h2 sibling elements, and removing these styles doesn't seem to change anything. It would be best to avoid using `!important` as much as possible. Can we remove this?

2020-10-08 16:22 UTC, Ronolibert commented on cypress/integration/mymove/hhg.js
> +    // customerSubmitsMove();
Oops! Uncommenting this, was just debugging tests. Good catch!

2020-10-08 20:12 UTC, suzubara approved these changes

2020-10-08 22:52 UTC, merged