W I P | MB-4126 | add another shipment logic
transcom/mymove pull request #4912
Opened 2020-10-02 21:26 UTC by sojeri

![IGNORE_ME](https://user-images.githubusercontent.com/10818509/94971176-2de04500-04bb-11eb-8cc4-65c300bc41d2.png)

## Description

Explain a little about the changes at a high level.

## Reviewer Notes

Is there anything you would like reviewers to give additional scrutiny?

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

```sh
echo "Code goes here"
```

## Code Review Verification Steps

* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] The requirements listed in
 [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely)
 have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://github.com/transcom/mymove/wiki/migrate-the-database#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](tbd) for this change
* [this article](tbd) explains more about the approach used.

## Screenshots

If this PR makes visible UI changes, an image of the finished UI can help reviewers and casual
observers understand the context of the changes. A before image is optional and
can be included at the submitter's discretion.

Consider using an animated image to show an entire workflow instead of using multiple images. You may want to use GIPHY CAPTURE for this! 📸

_Please frame screenshots to show enough useful context but also highlight the affected regions._

2020-10-05 21:05 UTC, sojeri commented on src/pages/MyMove/Home/index.jsx
> +    if (this.hasSubmittedMove && this.doesPpmAlreadyExist) {
this will cause this step 3 button to disappear if move is submitted and PPM already exists. see reviewer notes #2 for more text.

2020-10-05 21:06 UTC, sojeri commented on src/pages/MyMove/Home/index.jsx
> +      return 'Add another shipment';
note to self: this should be `this.hasShipment || this.doesPpmAlreadyExist` b/c any shipment should trigger Add vs Plan

2020-10-05 21:07 UTC, sojeri commented on src/pages/MyMove/SelectMoveType.jsx
> +              {!isPpmSelectable && (
@suzubara is there a more intuitive way to do this? I went for the easy route here, but in reading this file as whole it's weird to see thing && content, !thing && content

2020-10-05 21:08 UTC, sojeri commented on src/pages/MyMove/SelectMoveType.jsx
> +  // TODO: question PR reviewers on checked behavior
re: checked behavior: if you have added an HHG shipment and you go back to selection page to add a new one, the current behavior (regardless of my changes) is that the HHG item will be checked. is this expected/desired? it felt weird to me, but I understand it can get complex otherwise if we need to maintain this checked behavior if/when customer hits back button from the details form page.

2020-10-05 21:09 UTC, sojeri commented on src/pages/MyMove/SelectMoveType.test.jsx
> +    isPpmSelectable: true,
this is where my first reviewer's note starts to matter. would you rather see this, or is there a better way here I should hydrate more of the actual state so this gets calculated in mapStateToProps based on actual PPM / HHG shipments state.

2020-10-05 21:27 UTC, suzubara commented on src/pages/MyMove/SelectMoveType.jsx
> +              {!isPpmSelectable && (
you can do:
```
{isPpmSelectable ? ppmSelectableContent : ppmUnselectableContent}
```

(I also recommend moving content into variables like that just so it's a little easier to read with some separation of content / logic)

2020-10-05 21:30 UTC, suzubara commented on src/pages/MyMove/SelectMoveType.jsx
> +  // TODO: question PR reviewers on checked behavior
that is weird to me. Navigating back to the selection page should mean `SelectMoveType` gets re-mounted, and there shouldn't be any initial "checked" state (unless one is passed in explicitly via props)

2020-10-05 21:36 UTC, suzubara commented on src/pages/MyMove/SelectMoveType.jsx
> +  // TODO: question PR reviewers on checked behavior
oh just looked at it real quick, SelectMoveType is initializing `moveType` state based on `props.selectedMoveType` which is a [common React anti-pattern](https://stackoverflow.com/questions/28785106/reactjs-why-is-passing-the-component-initial-state-a-prop-an-anti-pattern). I realize this is not related to your PR, but wanted to point it out as something that should probably be removed. What is the use case for a move type to already be selected when. navigating to this page?

2020-10-05 21:39 UTC, suzubara commented on src/pages/MyMove/SelectMoveType.jsx
> +              {!isPpmSelectable && (
(also I imagine this will end up looking a little different once @kimallen 's PR is in)

2020-10-05 21:45 UTC, sojeri commented on src/pages/MyMove/SelectMoveType.jsx
> +  // TODO: question PR reviewers on checked behavior
that's exactly what I'm saying @suzubara 
> is this expected/desired? it felt weird to me, but I understand it can get complex otherwise if we need to maintain this checked behavior if/when customer hits back button from the details form page.

2020-10-05 21:58 UTC, kimallen commented on src/pages/MyMove/SelectMoveType.jsx
> +  // TODO: question PR reviewers on checked behavior
the `selectedMoveType` is saved on the move in the db, so if you are remounting, that value is still on the move.  Whatever the last one selected is will be the value.  An alternative is that when a shipment or PPM is fully created (but move is not yet submitted), then we set the value of `move.selectedMoveType` to ''.  The reason we store this in the db is that we need to know what their selection was if they were mid-creating one so that we can start them where they left off if they log out and log back in.

2020-10-05 22:00 UTC, suzubara reviewed
Left some comments to hopefully answer your questions! I also tested the scenarios you mentioned and they look good. One comment is that when I _do_ access the Select Move Type page when I'm not supposed to (i.e., already submitted a move), it seems like the back & next buttons should be disabled. Clicking on them produces an API call with a 403 response. But since the user shouldn't end up on this page in the first place, I don't know how much of an issue that is.

2020-10-05 22:01 UTC, kimallen commented on src/pages/MyMove/Home/index.jsx
> +  get doesPpmAlreadyExist() {
[nit] I wonder if we can simplify this name to `hasPpm`

2020-10-05 22:02 UTC, suzubara commented on src/pages/MyMove/SelectMoveType.jsx
> +  // TODO: question PR reviewers on checked behavior
I would argue that this value should not be saved in `SelectMoveType` state at all, and that `move.selectedMoveType` can be saved in the DB (and Redux) when the user clicks "Next". But how are we resolving this field on the move now that a move can have multiple shipments of varying types?

2020-10-05 22:04 UTC, sojeri commented on src/pages/MyMove/Home/index.jsx
> +      return 'Add another shipment';
for this PR. my logic change above means that this string will be displaying incorrectly on the button if not resolved. fixing it now. :)

2020-10-05 22:11 UTC, kimallen commented on src/pages/MyMove/Home/index.jsx
> +      return 'Add another shipment';
`this.hasShipment` already checks if there is a Ppm or not, so it does not need `this.PpmAlreadyExist` added.

2020-10-05 22:16 UTC, kimallen commented on src/pages/MyMove/SelectMoveType.jsx
> +  // TODO: question PR reviewers on checked behavior
A more accurate name for the field would be `lastSelectedMoveType`.  I think what you said is correct.  Currently, if a user started entering their ppm (since there are multiple pages), and log out in the middle, then when they log back in, it will take them back to the last unfinished page (`selectedMoveType` is used in `getWorkflowRoutes` in helping determine which pages in the flow are completed.

2020-10-05 23:15 UTC, kimallen commented on src/pages/MyMove/Home/index.jsx
>      return (this.hasOrders && !!mtoShipments.length) || Object.keys(currentPpm).length;
Now that you changed the title to include MTO, do you want to remove the check for Ppms and adjust anywhere else that would be impacted?

2020-10-05 23:32 UTC, kimallen commented on src/pages/MyMove/SelectMoveType.jsx
> +    const ppmSelectableContent = (
I actually covered all of the content changes on my PR.  It's confusing because the content spreadsheet was linked on both of our stories, but my understanding was that this story was to cover the disabled/enabled states of the selectType page, and my story included the copy changes. https://dp3.atlassian.net/browse/MB-4302

2020-10-05 23:59 UTC, kimallen requested changes
I believe I saw all the correctly enabled/disabled radios on the Shipment Selection page.  I also saw on the home page that the Add shipments button was not there when there was a ppm+hhg combo submitted move, it was enabled when they did not yet have a Ppm (whether submitted or not).  That seems correct based on what I can glean from the story and the links.

Requested change: According to the spreadsheet, the home page step 3 should show 'If you need to add shipments, let your movers know.' when the submitted move has a disappeared button. 

Requested change: changes are needed around get `hasMtoShipments` Either the get action or the name need to change-- see comment.

2020-10-06 00:02 UTC, kimallen commented on src/pages/MyMove/Home/index.jsx
>      return (this.hasOrders && !!mtoShipments.length) || Object.keys(currentPpm).length;
For example, as currently written, it correctly shows the `ShipmentList` if there is any kind of shipment or ppm.  Your name change implies that it does not include Ppm, so either the name needs to be inclusive of Ppms or the check for ppms removed and other uses of `hasMtoShipments` as conditional check need to be adjusted to check for a Ppm.

2020-10-06 01:03 UTC, sojeri commented on src/pages/MyMove/Home/index.jsx
>      return (this.hasOrders && !!mtoShipments.length) || Object.keys(currentPpm).length;
ahhh, nope. I did an automatic rename, and I think it was a mistake! I will revert this part of the change / updated it to be hasAnyShipment for clarity.

2020-10-06 01:07 UTC, sojeri commented on src/pages/MyMove/SelectMoveType.jsx
> +    const ppmSelectableContent = (
So I think there were some crossed wires here and some scope creep on your story, which was supposed to cover only incorporating the new shipment card onto the page and nothing else.

If you look at the description and AC in my story, you can see that the state and content updates were part of MB-4126 (story for this PR):

> Incorporate logic into the shipment selection page that enables, and disables, shipments based on what the user has already requested within the flow.
> - Educational content for customers to understand what they can do about it

I think part of how this happened is our story templates are encouraging adding too many references. If no content changes are indicated, the content spreadsheet shouldn't be in the story. :/

2020-10-06 01:12 UTC, sojeri commented on src/pages/MyMove/SelectMoveType.jsx
> +    const ppmSelectableContent = (
Though FWIW I am only changing the disabled copy here, which may be in line with both our stories if you're only updating the enabled copy. In that case, I think we're fine and whoever merges second can deal with the merge conflict.

2020-10-06 02:39 UTC, sojeri commented on src/pages/MyMove/SelectMoveType.jsx
> +    const ppmSelectableContent = (
Thinking about this more, and I made a reminder to bring up at either next retro or the one after. I think something went wrong when we split these stories out and we could have done a better job on both for lining out what wasn't covered and then pointing to the other story which should cover it. We might have still had a merge conflict, but at least we'd have been less confused about the overlap. :)

2020-10-06 14:27 UTC, mariaclaratgolfo requested changes
I believe we've incorporated the new selectable cards for the Shipment selection page. Is there a reason we're not leveraging them here? 

A few additional notes:

- For the "given: you have already submitted a move not containing a PPM" scenario, once a user submits their move, the edit icon on the Home HHG cell + the edit link in the Review page should be removed. They can no longer make edits to HHG shipments post submission.

- Can you share screenshots of what the Home page and Review page looks like after they've submitted and already requested a PPM? The Add a shipment buttons should be removed from both pages in this scenario. Happy to pair to walk through these if that's easier.

- Echoing Kim's note above, Post-submission — on the Home and Review pages, when they can no longer add another shipment, we have language letting them know "If you need to add shipments, let your movers know."

2020-10-06 16:02 UTC, kimallen commented on src/pages/MyMove/SelectMoveType.jsx
> +    const ppmSelectableContent = (
Yes, I agree.  I think neither story is very clear or delineated between expected tasks.  And maybe one was meant to be finished before the other (they were in different sprints).  We'll figure it all out in the merge conflicts.

2020-10-07 17:51 UTC, kimallen commented on src/pages/MyMove/Home/index.jsx
> +                        <p className={styles.descriptionExtra}>If you need to add shipments, let your movers know.</p>
I would have expected this text below the list of shipments where the other messages appear (in place of the text of <Description>, but if the placement is okayed by @mariaclaratgolfo, then fine by me.  The abstract I found didn't contain the text at all, so is unclear.

2020-10-07 17:52 UTC, kimallen approved these changes
Changes approved!  left a note about placement of some text, but I don't really know what is desired.

2020-10-07 17:53 UTC, sojeri commented on src/pages/MyMove/Home/index.jsx
> +                        <p className={styles.descriptionExtra}>If you need to add shipments, let your movers know.</p>
@kimallen yeah, Mariaclara had to link me directly to the mockup. here it is with the text above: https://share.goabstract.com/54bf497e-72bf-44b9-a169-3946e56ff710?collectionLayerId=c963c8d3-0dbb-4f6a-85b8-cb492c62ace1&mode=design

2020-10-07 17:58 UTC, suzubara commented on src/components/Customer/Home/ShipmentList/ShipmentList.test.jsx
> +      moveSubmitted: false,
non-blocking, minor suggestion: if you update the `mountShipmentList` fn to return the following, you don't have to worry about passing in default props for each test case:
```
mount(<ShipmentList {...defaultProps} {...props} />)
```

2020-10-07 17:58 UTC, suzubara commented on src/components/Customer/Home/ShipmentList/index.jsx
> +    if (!canEdit) return;
this is not related to this PR, but I want to voice a strong opinion that this element should be a `<button>` element, then we don't have to add a keyDown handler and can use the `disabled` attribute to prevent the action.

2020-10-07 17:58 UTC, suzubara commented on src/components/Customer/Home/ShipmentList/index.jsx
> +      onClick={() => onShipmentClick(shipment, shipmentNumber, shipment.shipmentType, canEdit)}
minor, non-blocking: I would recommend wrapping `onShipmentClick` handler to implement the `canEdit` early return in one place, rather than having to pass it into the handler itself and also handle it in the keyDown. ie:

```
const handleShipmentClick = () => {
  if (!canEdit) return
  onShipmentClick(shipment, shipmentNumber, shipment.shipmentType)
}

<div onClick={handleShipmentClick}...
```

(but again, this wouldn't be needed if we changed it to a `<button>`!)

2020-10-07 17:58 UTC, suzubara commented on src/components/Customer/Home/ShipmentList/index.jsx
> +            onShipmentClick={() => onShipmentClick(shipment.id, shipmentNumber, shipmentType, canEdit)}
Blocking: this is also not strictly related to this PR, but the way this this handler is passed around is actually a bug IMO. The parent component `<ShipmentList>` is passing a fn that accepts no parameters, and calls `onShipmentClick` into `ShipmentListItem`. That means that the parameters passed into `onShipmentClick` from `ShipmentListItem` are redundant, and are not actually being used at all. The parameters should be passed into the handler in only one place, so one of these implementations should be changed to `onShipmentClick={onShipmentClick}`

2020-10-07 17:58 UTC, suzubara commented on src/pages/MyMove/SelectMoveType.mapStateToProps.test.jsx
> +// NOTE: mock setup has to happen before import of file with dep that needs mocking
I'm curious why you ended up adding this test file instead of testing `ConnectedSelectMoveType`? this is not a pattern I've ever seen before. It also seems like the tests could be part of `SelectMoveType.test.jsx` since usually we've been using one test file to test all exports from a file.

2020-10-07 17:58 UTC, suzubara commented on src/pages/MyMove/SelectMoveType.test.jsx
> +    defaultProps.isPpmSelectable = false;
Instead of mutating `defaultProps` I think it would follow React paradigm more to do:
```
const wrapper = mount(<SelectMoveType {...defaultProps} isPpmSelectable={false} />);
```

2020-10-07 18:58 UTC, sojeri reviewed
@suzubara responded to several of your comments & have pushed changes for those I could handle right away :)

2020-10-07 18:58 UTC, sojeri commented on src/components/Customer/Home/ShipmentList/index.jsx
> +    if (!canEdit) return;
yessssss so much. I didn't want to refactor now, but as I started looking at these click and event handlers I was feeling the same thing.

2020-10-07 18:58 UTC, sojeri commented on src/components/Customer/Home/ShipmentList/index.jsx
> +      onClick={() => onShipmentClick(shipment, shipmentNumber, shipment.shipmentType, canEdit)}
yeah, I see what you mean. I was trying to do the least work here because I agree it should be a button. I've made a slight adjustment to move all the canEdit early returns to the ShipmentList file. let me know what you think!

2020-10-07 18:58 UTC, sojeri commented on src/pages/MyMove/SelectMoveType.mapStateToProps.test.jsx
> +// NOTE: mock setup has to happen before import of file with dep that needs mocking
I separated them to keep this import mocking from altering or complicating anything for the other tests.

as for not testing `ConnectedSelectMoveType`, I had no idea that was a thing. still learning redux! if you think it's worth blocking this PR and Kim's, I can look into refactoring this to test `ConnectedSelectMoveType` instead.

I will say, though, I like being able to test this logic directly rather than checking for side effects in the resulting rendered component.

2020-10-07 18:58 UTC, sojeri commented on src/components/Customer/Home/ShipmentList/index.jsx
> +            onShipmentClick={() => onShipmentClick(shipment.id, shipmentNumber, shipmentType, canEdit)}
I don't understand what you mean. you may need to walk me through this.

what I'm seeing is:
1. in `pages/MyMove/Home`, we have `handleShipmentClick` which has 4 params
2. still in `pages/MyMove/Home`, we pass into ShipmentList a reference to that function
3. in `components/Customer/Home/ShipmentList`, we map the shipments to `ShipmentListItem`s, in the process defining arrow functions which will call the reference `handleShipmentClick` and passing in the relevant 4 args
4. still in `components/Customer/Home/ShipmentList` we have the second entry point into the `handleShipmentClick` ref, this time via the event handler function.

what am I misunderstanding or missing here? :)

2020-10-07 19:30 UTC, mariaclaratgolfo approved these changes
Notes that we talked through adding during our pairing session:

- No padding appearing below "add another shipment message" 
- Mention during Standup that a Design review will be needed for your work on Shipmenet selection page once new cards are in
- Review page — post submission, button disappears and new language

Sounds like you got them all in — in which case, approved

2020-10-07 21:23 UTC, suzubara approved these changes

2020-10-07 21:56 UTC, merged