Kim mb 4302 integrate selectable card
transcom/mymove pull request #4914
Opened 2020-10-02 23:15 UTC by kimallen

## Description

Applies the SelectableCard component in the select move page.  This applies the different copy based on a few different states. (see [Shipment Selection (Third info screen (step 3/5))](https://docs.google.com/spreadsheets/d/14_qlyhSN6-VjXmBLRtBHj2OUwy76NONOEUbYiRYQ2-w/edit?ts=5ee3fe45#gid=1041135497) for copy.  It also adds styling within that page.

## Reviewer Notes

Let me know where there is spacing missing. (not sure what it should be around the header)
Note that the states of the cards will be implemented with https://dp3.atlassian.net/browse/MB-4126.
Note that the 'eyebrow' is not part of this story, as there were questions about the numbering/copy.

## Setup

Log in as a customer 
Navigate to the select-type page (Can get there from the hope page Step 3)
Check that the correct copy appears in the correct states:
   - `combo@hhg.ppm`: shows submitted move
   - `hhg@only.unsubmitted` shows hhg created, not submitted
   - Create a ppm and see the text page on that card
    

## Code Review Verification Steps

* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-4302) for this change

## Screenshots

No shipments:
![image](https://user-images.githubusercontent.com/13249580/94976313-6850de80-04c9-11eb-800f-50b6b8424f2a.png)

1 hhg created:
![image](https://user-images.githubusercontent.com/13249580/94976353-933b3280-04c9-11eb-9004-d0d2429d6e2b.png)

has PPM/has HHG:
![image](https://user-images.githubusercontent.com/13249580/94976408-cf6e9300-04c9-11eb-8e43-702e740dca50.png)

desktop:
![image](https://user-images.githubusercontent.com/13249580/94976446-e7461700-04c9-11eb-926c-fac078777199.png)

post submitted:
![image](https://user-images.githubusercontent.com/13249580/94976522-1bb9d300-04ca-11eb-9bc9-17834ea2f25a.png)

2020-10-05 15:54 UTC, Shkeating reviewed
this is looking great! I went into abstract and found the page that may answer your questions about the spacing for the header: 

On [smaller screens](https://share.goabstract.com/0f81571d-01df-4aa6-a856-2b9d5ec5a927?collectionLayerId=9eb807f8-0b67-4c92-8cb5-4a763d91c24d&mode=design), we want 32px (USWDS token: 4) above the header


<img width="377" alt="image" src="https://user-images.githubusercontent.com/59394696/95102139-024e9c00-0701-11eb-8add-16adcda4b6c4.png">


On [desktop](https://share.goabstract.com/0f81571d-01df-4aa6-a856-2b9d5ec5a927?collectionLayerId=bab2ac2a-d672-41f4-929f-a6a89fe888a3&mode=design), we will bump that value up to 40px, or 5 as a USWDS token. the space below should remain 32px.

<img width="824" alt="image" src="https://user-images.githubusercontent.com/59394696/95102354-4b065500-0701-11eb-8388-57f1dc4668ea.png">

2020-10-05 16:18 UTC, suzubara commented on package.json
> +    "happo": "^5.0.0",
This should not be added, the correct package (`happo.io`) is already listed in our dev dependencies.

2020-10-05 16:42 UTC, suzubara requested changes
It looks like this PR re-adds the `.loki` assets, can we remove the whole `.loki` directory from this PR please? Left some other comments but the implementation is looking 👍

2020-10-05 16:42 UTC, suzubara commented on src/pages/MyMove/SelectMoveType.jsx
> +          <div className="tablet:grid-col-2 desktop:grid-col-2" />
I'm wondering about these 2 column divs that were added. `grid-container` should already center the content within a container on desktop. What's the intended layout on tablet/desktop?

2020-10-05 16:42 UTC, suzubara commented on src/pages/MyMove/SelectMoveType.jsx
> +    const ppmCardTextAlreadyChosen = `You’ve already requested a PPM shipment. If you have more things to move yourself but that you can’t add to that shipment, contact the PPPO at your origin duty s
minor suggestion, but for readability it might be easier to define const for each of the SelectableCard configurations, such as:
```
const selectPPMHasPPM = (
  <SelectableCard
    label="Do it yourself (already chosen)"
    cardText="You’ve already requested a PPM shipment. If you have more things to move yourself but that you can’t add to that shipment, contact the PPPO at your origin duty station."
    ... />
)

const selectPPM = (
  <SelectableCard
    label="Do it yourself"
    cardText="You pack and move your things, or make other arrangements, The government pays you for the weight you move.  This is a a Personally Procured Move (PPM), sometimes called a DITY."
    ... />
)
```

2020-10-05 16:42 UTC, suzubara commented on src/pages/MyMove/SelectMoveType.jsx
> +  mtoShipments: shape({}).isRequired,
Can we add some shape definitions for these props? you can see existing examples in `src/types`

2020-10-05 16:42 UTC, suzubara commented on src/pages/MyMove/SelectMoveType.module.scss
> +.gridContainer.cardsContainer {
ideally this CSS is defined at a higher level, to implement the desktop container size for all onboarding steps. Do we have another story for doing that work, or maybe I can help out?

2020-10-05 16:42 UTC, suzubara commented on src/pages/MyMove/SelectMoveType.test.jsx
>    });
It would be good to add tests for the various scenarios (ie, has a PPM already or has an HHG already)

2020-10-05 16:42 UTC, suzubara commented on src/shared/WizardPage/index.jsx
> +          <div>{footerText ? footerText : ''}</div>
We should only output a `<div>` if `footerText` is defined, so:
```
{footerText && <div>{footerText}</div>}
```

2020-10-05 16:45 UTC, kimallen commented on src/pages/MyMove/SelectMoveType.jsx
> +          <div className="tablet:grid-col-2 desktop:grid-col-2" />
It should be centered.  Grid-container alone did not center it, so I ended up adding those column divs which ended up getting the desired result.

2020-10-05 23:11 UTC, kimallen commented on src/pages/MyMove/SelectMoveType.module.scss
> +.gridContainer.cardsContainer {
I moved this to a more central place: `pages/index.module.scss`.  I also included padding above and below the H1, which I would expect to also be consistent in the onboarding flow, but I'm not 100% on that (@mariaclaratgolfo  ?).  I'm only applying those styles to the selectType page right now, but they could be applied (should probably be another story).

2020-10-05 23:11 UTC, kimallen commented on src/pages/MyMove/SelectMoveType.module.scss
> +.gridContainer.cardsContainer {
also cc @Shkeating re: h1 padding since you have been working on them

2020-10-06 19:17 UTC, kimallen commented on src/pages/MyMove/SelectMoveType.jsx
> +          <div className="tablet:grid-col-2 desktop:grid-col-2" />
Let me know if you have another solution for it.

2020-10-06 19:18 UTC, kimallen commented on src/pages/MyMove/SelectMoveType.jsx
> +    const ppmCardTextAlreadyChosen = `You’ve already requested a PPM shipment. If you have more things to move yourself but that you can’t add to that shipment, contact the PPPO at your origin duty s
I did make the changes, but the same question came up for me.  It felt like a lot of repeated code.

2020-10-07 15:37 UTC, suzubara commented on src/pages/MyMove/SelectMoveType.jsx
> +          <div className="tablet:grid-col-2 desktop:grid-col-2" />
So I happened to notice that @Shkeating is working on this ticket MB-4432 implementing Desktop container/layout CSS across the board for Onboarding pages. I'm inclined to suggest that we don't do anything for it in this PR (or just leave it as is and let @Shkeating know she can change it) and deal with it there. What do you think @kimallen & @Shkeating ?

2020-10-07 18:49 UTC, kimallen commented on src/pages/MyMove/SelectMoveType.jsx
> +          <div className="tablet:grid-col-2 desktop:grid-col-2" />
Works for me

2020-10-07 21:19 UTC, suzubara approved these changes

2020-10-09 18:08 UTC, merged