MB-4432 Desktop Container Styling Applied to Customer Onboarding
transcom/mymove pull request #5006
Opened 2020-10-15 18:00 UTC by Shkeating

## Description
This branch establishes the **SectionWrapper** component, a wrapping div with css applied to establish white boxes and spacing changes to sections in the customer app on desktop layouts. This branch also sets the background color of the customer app to be the **$bg-gray** color established in the MilMove Design System (MMDS). We also tweak backgound colors and some spacing for some components in the system that became apparent after the change in background color. For the end user, this change will break up complex page layouts into easier to read sections, and will help them know which elements are interactive on the page.

## Reviewer Notes

I tried my best to ensure that I implemented <SectionWrapper> on all the pages where it is needed but if I missed something let me know!

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

```sh
yarn install
yarn storybook
```

OR 

```sh
make client_run
make server_run
```

## Code Review Verification Steps
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-4432?atlOrigin=eyJpIjoiOWFlYmUwZGVhYmUyNGYyN2I0NTQ1ODBhYmFkMmNiNWMiLCJwIjoiaiJ9) for this change
* [Abstract spec](https://share.goabstract.com/376a7912-b8dd-4633-bcd0-7dfb2fc07735?mode=build&sha=8a7a7045845cb1fdf125dbeaa17142fa27afcf87) 

## Screenshots

![HHG Details form](https://user-images.githubusercontent.com/59394696/96168369-a0571900-0eee-11eb-9e48-927ee96992dd.png)
![Home Page](https://user-images.githubusercontent.com/59394696/96168370-a0571900-0eee-11eb-8e01-f4685df97a06.png)
![Review Page](https://user-images.githubusercontent.com/59394696/96168372-a0efaf80-0eee-11eb-8c1e-cfdd45a36967.png)
![Shipment Detail Review](https://user-images.githubusercontent.com/59394696/96168374-a1884600-0eee-11eb-995c-2b2dd9c7d2d8.png)

2020-10-19 20:00 UTC, amanda5iu approved these changes
Beautiful work, Shauna!

2020-10-20 00:14 UTC, Shkeating commented
still need to determine what we want to do with the following pages:

- legalese/signature page
- How much do you think you'll move? page with the slider
- page listing move types in h3s (need to go back through and find the name)

still need to move `.wrapper-co` styling out of global style sheet

2020-10-22 00:02 UTC, kimallen reviewed
This is great!  And that's a lot of files!

I noticed the edit pages don't utilize the SectionWrapper, not sure if we intend to at this point since those pages may get an overhaul later. 

 This includes `EditProfile`, `EditBackupContact`, `EditContactInfo`, `EditOrders`, `EditWeight`.   (You can't navigate to EditBackupContact and EditContactInfo right now, but they are found at `/moves/review/edit-backup-contact` and `/moves/review/edit-contact-info`. Same with EditWeight? `/moves/:moveId/review/edit-weight`)

2020-10-22 23:03 UTC, suzubara commented
IMO let's handle the edit pages later on? This PR contains a lot of changes already and it would be good for them to be merged in.

2020-10-22 23:14 UTC, suzubara requested changes

2020-10-22 23:14 UTC, suzubara commented on src/components/Customer/Review/ShipmentCard/PPMShipmentCard/index.jsx
> +            <dd className={styles.noborder}>{estimatedIncentive || 'Rate info unavailable'}</dd>
What is this class for? Can we use a pseudo selector instead?

2020-10-22 23:14 UTC, suzubara commented on src/components/Customer/SelectableCard.jsx
> +import faQuestionCircle from '@fortawesome/fontawesome-free-regular';
This should not be changed

2020-10-22 23:14 UTC, suzubara commented on src/components/Table/Table.jsx
> +import { useTable } from 'react-table/index';
This should also not be changed

2020-10-23 21:36 UTC, Shkeating commented on src/components/Customer/Review/ShipmentCard/PPMShipmentCard/index.jsx
> +            <dd className={styles.noborder}>{estimatedIncentive || 'Rate info unavailable'}</dd>
not without affecting all the other shipment types, which we don't want

2020-10-26 14:16 UTC, suzubara commented on src/components/Customer/Review/ShipmentCard/PPMShipmentCard/index.jsx
> +            <dd className={styles.noborder}>{estimatedIncentive || 'Rate info unavailable'}</dd>
what is different about this shipment type?

2020-10-26 16:14 UTC, suzubara approved these changes

2020-10-26 17:13 UTC, merged