MB-4566 MB-4379 Add NTS and NTS-R to Home and Review pages
transcom/mymove pull request #5009
Opened 2020-10-15 20:57 UTC by amitch23

## Description

Adds NTS and NTS-R to the home and review pages. Adds to ShipmentList and ShipmentCard components, respectively.

The Title of the card on the review page should probably not include a number ? see image below

## Reviewer Notes

Is there anything you would like reviewers to give additional scrutiny?

## Setup

Generate new e2e data: `make db_dev_e2e_populate`
Log in locally as the only nts user - ensure home and review pages appear as below.

## Code Review Verification Steps

* [ ] If the change is risky, it has been tested in experimental before merging.
* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] The requirements listed in
 [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely)
 have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://github.com/transcom/mymove/wiki/migrate-the-database#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/secure/RapidBoard.jspa?rapidView=1&projectKey=MB&modal=detail&selectedIssue=MB-4379&quickFilter=60) for this change
and https://dp3.atlassian.net/secure/RapidBoard.jspa?rapidView=1&projectKey=MB&modal=detail&selectedIssue=MB-4566&quickFilter=60

## Screenshots
Home:
<img width="428" alt="Screen Shot 2020-10-15 at 1 41 12 PM" src="https://user-images.githubusercontent.com/8170735/96185141-50785200-0eee-11eb-9f1d-99825e23a0cd.png">
Review:
<img width="418" alt="Screen Shot 2020-10-15 at 1 44 13 PM" src="https://user-images.githubusercontent.com/8170735/96185144-52daac00-0eee-11eb-877d-641482e8c919.png">

2020-10-15 21:01 UTC, amitch23 commented on src/components/Customer/Review/ShipmentCard/HHGShipmentCard/index.jsx
> +          {isNTS && (
Add `isHHG` for this and everywhere else to handle HHGs also

2020-10-15 21:06 UTC, suzubara commented on src/components/Customer/Review/ShipmentCard/HHGShipmentCard/index.jsx
> +  shipmentType,
We already have separate components for `HHGShipmentCard, PPMShipmentCard`. Is there a reason to not add disparate components for `NTSShipmentCard, NTSRShipmentCard` instead of modifying this one? that would probably clean up a lot of the logic that's being added here.

2020-10-15 21:11 UTC, amitch23 commented on src/components/Customer/Review/ShipmentCard/HHGShipmentCard/index.jsx
> +  shipmentType,
Since NTS and NTS-R are just subtypes of the MTOShipment, I thought it would make the most sense to adapt the HHGShipmentCard to handle mtoshipments (and all subtypes of MTOShipments), especially when thinking about possible field additions or changes to the mtoshipments, reducing manual maintenance etc. But if folks think that it's clearer and easier to read to create another card, I can go in that direction...

2020-10-16 13:51 UTC, mariaclaratgolfo requested changes
NTS-R cards have a different color bar than NTS — on both review page and home. There should be a component available in storybook with shipment specific color styling [storybook won't load for me at present]. You can reference the differences in [this collection](https://zpl.io/2pE7Z6j) and a visual [here](https://zpl.io/bPeZN6p).

Does this story include the logic for [when editing is disabled](https://docs.google.com/presentation/d/1Wqx8f3KzEqbCkqIvAztakwBaVF8jZ1JUYBECRsMJVBU/edit?usp=sharing)?

- icon on home + link on review page removed bc (1) user already requested one of each (2) they already submitted their move

2020-10-16 18:01 UTC, amitch23 commented
@mariaclaratgolfo - I've updated the color bars (see screenshots in description). For the disabled editing: these tickets don't include edit functionality, and so I disabled the edit buttons for now until that ticket is started. (see jira ticket links in description for more info)

2020-10-16 18:13 UTC, mariaclaratgolfo approved these changes

2020-10-17 01:24 UTC, amitch23 commented on src/components/Customer/Review/ShipmentCard/HHGShipmentCard/index.jsx
> +  shipmentType,
After meeting with Suz and Jeri, decided to have distinct cards for NTS, NTSR and HHG

2020-10-19 17:01 UTC, suzubara approved these changes
looks good! 👍

2020-10-19 17:02 UTC, suzubara commented
it looks like there's some unintended Happo changes, but I wonder if they will be resolved when both this and https://github.com/transcom/mymove/pull/4950 are merged in?

2020-10-21 19:29 UTC, merged