edit NTS/NTS-R shipments
transcom/mymove pull request #5042
Opened 2020-10-21 05:52 UTC by sojeri

## Description

Known issues which need to be fixed before this is ready for review:
- [ ] failing MtoShipmentForm tests (by design)
- [ ] cannot edit delivery address for NTS-R shipments

Remaining work:
- [ ] dev pass over styles & content compared to full design (what you see is just from pulling in current edit shipment page)
  - [ ] then: full design review with Mariaclara 🙂 
- [ ] fix FE data handling
  - [ ] double check delivery/pickup date handling && reconsider nesting values.delivery.field
  - [ ] refactor `handleChangeHasDeliveryAddress` and `handleUseCurrentResidenceChange` out of existence
  - [ ] double check shipment number handling
- [ ] fix BE data handling
  - [ ] confirm with DB folks whether a migration should have been created in #4950 for selectedMoveType changes
  - [ ] (maybe) double check delivery/pickup date from other end
- [ ] remove redux connect from MtoShipmentForm
- [ ] refactor hhg integration test
  - [ ] use one of the seed accounts instead of creating from scratch
  - [ ] (maybe) add jest component tests for form validations
       - [ ] then remove most form validation checks from hhg test
- [ ] do a rake notes pass and confirm no stale TODOs on touched files :)

## Reviewer Notes

None for now. Unless you see something from the above you want to take on yourself? DM me and then I think you can either branch off my branch. I promise GH will auto credit you when I squash merge. :)

## Setup

I haven't tested the stories yet, but manual UX clicking is working.

2020-10-21 05:54 UTC, sojeri commented on src/pages/MyMove/Home/index.jsx
> +    } else {
this was hacky to unblock getting to the relevant edit form. will remove when Andrea's PR merges.

2020-10-21 05:57 UTC, sojeri commented on src/components/Customer/MtoShipmentForm/MtoShipmentFormFields.jsx
> +import React from 'react';
if you want, I can try to redo this diff so it shows as a rename of the EditShipment component or else the MtoShipmentForm. lmk if that will make reviewing easier!

2020-10-21 05:59 UTC, sojeri commented on src/components/Customer/MtoShipmentForm/MtoShipmentFormFields.jsx
> +      <h1 className="margin-top-1">When and where can the movers pick up and deliver this shipment?</h1>
note for content pass: this is for sure wrong for all but HHG.

2020-10-21 05:59 UTC, sojeri commented on src/components/Customer/MtoShipmentForm/MtoShipmentFormFields.jsx
> +              requested date. Tip: Avoid scheduling multiple shipments on the same day.{' '}
Double check what/why `{' '}`

2020-10-21 06:00 UTC, sojeri commented on src/components/Customer/MtoShipmentForm/MtoShipmentFormFields.jsx
> +                      We can use the zip of your new duty station.
double check during content pass. this was not in the edit shipment component.

2020-10-21 06:00 UTC, sojeri commented on src/components/Customer/MtoShipmentForm/MtoShipmentFormFields.jsx
> +          You can change details for your HHG shipment when you talk to your move counselor or the person who&apos;s
needs smart shipment type, not "HHG" here

2020-10-22 05:48 UTC, sojeri commented on src/components/Customer/MtoShipmentForm/MtoShipmentFormFields.jsx
> +                      We can use the zip of your new duty station.
it's not in the NTS/r collection, but the HHG one shows an updated version of this. let's keep as is for now.

2020-10-22 21:46 UTC, sojeri commented on src/components/Customer/MtoShipmentForm/MtoShipmentFormFields.jsx
> +          {isNTS && (
move this check up a couple to remove whole section!

2020-10-22 21:59 UTC, sojeri commented
notes from pairing with Kim:
- should finishing edit take you back to home screen or review page? user flow feels more like editing a thing should take to review page. home is existing behavior though.
- should edit icon alone be click target?
- fix regression: shipment type eyebrow should always display but only number for HHG

2020-10-23 00:40 UTC, kimallen commented on src/pages/MyMove/CreateOrEditMtoShipment.jsx
>    // TODO: (in trailing PR) refactor edit component out of existence :)
Does this PR do that refactor (aka is this comment still needed?)

2020-10-23 00:56 UTC, kimallen commented on src/pages/MyMove/CreateOrEditMtoShipment.jsx
> +    currentResidence: get(selectServiceMemberFromLoggedInUser(state), 'residential_address', {}),
(Not sure if this is new code, or just copied over.)  I think we're trying not to use `get` from lodash now.  I think something like this would work:
`serviceMember?.residential_address` // serviceMember's default value is already {} from the selector
or `serviceMember?.residential_address || {}` to make the default value obvious

2020-10-23 00:57 UTC, kimallen commented on src/pages/MyMove/CreateOrEditMtoShipment.jsx
> +    newDutyStationAddress: get(orders, 'new_duty_station.address', {}),
same here: `orders?.new_duty_station?.address || {}`

2020-10-23 01:04 UTC, kimallen commented on src/components/Customer/MtoShipmentForm/MtoShipmentFormFields.jsx
> +        Remember: You can move {serviceMember.weight_allotment.total_weight_self} lbs total. You&rsquo;ll be billed for
This should be either `total_weight_self` or `total_weight_self_plus_dependents` if they have dependents.

2020-10-23 01:16 UTC, kimallen commented on src/components/Customer/MtoShipmentForm/MtoShipmentFormFields.jsx
> +              disabled={isSubmitting || (!isValid && !dirty) || (isValid && !dirty)}
fuzzy EOD logic brain, but could this be simplified to `{isSubmitting || !isValid || (isValid && !dirty}`?

2020-10-23 01:18 UTC, kimallen commented on src/components/Customer/MtoShipmentForm/MtoShipmentFormFields.jsx
> +  displayOptions,
I like how you did this with passing in the displayOptions.  Makes it easier to read than a long string of conditionals for each FieldSet.

2020-10-23 02:01 UTC, sojeri commented on src/components/Customer/MtoShipmentForm/MtoShipmentFormFields.jsx
> +        Remember: You can move {serviceMember.weight_allotment.total_weight_self} lbs total. You&rsquo;ll be billed for
is this true of the home page as well? I copied this from there. seems like they should match either way.

2020-10-23 05:26 UTC, sojeri commented on src/pages/MyMove/CreateOrEditMtoShipment.jsx
>    // TODO: (in trailing PR) refactor edit component out of existence :)
good point!

2020-10-23 05:40 UTC, sojeri commented on src/components/Customer/MtoShipmentForm/MtoShipmentForm.jsx
> +                // TODO - what is the purpose of this check?
@amitch23 I found the PR where this check (on L104) was added. can you speak to why this was necessary?

https://github.com/transcom/mymove/pull/4614/files#diff-950a2606c9670a3cbdc6b321563d8b42395cd723f23f2230c37f8a9962c031e7L104

2020-10-23 06:31 UTC, sojeri commented on dangerfile.ts
> + * areNewLegacyFilesSharedStyles checks if new legacy files are in the only permitted src/shared/ file folder: src/shared/styles.
@suzubara the new common customer styles file was already in src/shared/styles, so I added this helper method to allow new files. it looks like before we were failing any build with any new files in src/shared/** regardless of the official rule that src/shared/styles is OK.

> /src/shared/styles Global or shared styles
> -- https://github.com/transcom/mymove/wiki/frontend#file-layout--naming

2020-10-23 07:27 UTC, sojeri commented on src/components/Customer/MtoShipmentForm/MtoShipmentFormFields.jsx
> +              disabled={isSubmitting || (!isValid && !dirty) || (isValid && !dirty)}
that's not equivalent, but I think we could do just `{isSubmitting || !dirty}` without checking isValid since both seem to be OK.

2020-10-23 15:46 UTC, suzubara commented on dangerfile.ts
> + * areNewLegacyFilesSharedStyles checks if new legacy files are in the only permitted src/shared/ file folder: src/shared/styles.
@sojeri We still want to be moving out of `shared` though, even for CSS. New global CSS should be in `src/styles`

2020-10-23 15:49 UTC, Ronolibert requested changes
This may out of scope to this ticket, but when I try to edit an NTS shipments' pickup location, it sends the correct data to the backend but the backend doesn't save the edited data so it returns the old data

2020-10-23 15:51 UTC, Ronolibert commented
> This may out of scope to this ticket, but when I try to edit an NTS shipments' pickup location, it sends the correct data to the backend but the backend doesn't save the edited data so it returns the old data

I also found some other unexpected behavior. When I try to edit an NTSr that already has a full destination address, when I click `No` to `Do you know your delivery address?` and `Save` it still keeps the same destination address instead of reverting back to the ZIP code of the duty station

2020-10-23 15:55 UTC, suzubara commented on dangerfile.ts
> + * areNewLegacyFilesSharedStyles checks if new legacy files are in the only permitted src/shared/ file folder: src/shared/styles.
additionally, we already have a Customer app CSS module file located in `src/pages/MyMove/index.module.scss` so maybe we can just add the new styles there?

2020-10-23 16:04 UTC, kimallen commented on src/components/Customer/MtoShipmentForm/MtoShipmentFormFields.jsx
> +        Remember: You can move {serviceMember.weight_allotment.total_weight_self} lbs total. You&rsquo;ll be billed for
Yes- the home page is wrong- @monfresh discovered it a few weeks ago and I think he wrote up a ticket.

2020-10-23 16:06 UTC, kimallen commented on src/components/Customer/MtoShipmentForm/MtoShipmentFormFields.jsx
> +              disabled={isSubmitting || (!isValid && !dirty) || (isValid && !dirty)}
But if they enter invalid info, is that indicated by `!isValid`?

2020-10-23 17:36 UTC, sojeri commented on dangerfile.ts
> + * areNewLegacyFilesSharedStyles checks if new legacy files are in the only permitted src/shared/ file folder: src/shared/styles.
ah, yeah, I can do that. can you update the wiki entry to say that folder is not allowed / point to the new one instead?

2020-10-23 18:00 UTC, Ronolibert approved these changes

2020-10-23 18:02 UTC, suzubara approved these changes

2020-10-23 18:22 UTC, merged