Kim mb 4407 only one nts
transcom/mymove pull request #5052
Opened 2020-10-21 21:29 UTC by kimallen

## Description

This limits the front-end user to being able to create more than one NTS or NTSr by disabling the selection radio when either has already been created.

If both have been created, alternative text is shown instead of the selection cards.

If the move has been submitted, whether they have created either of the long-term storage types, they will see the alternative text.

## Reviewer Notes

This includes 3 stories.

## Setup

`make db_dev_e2e_populate`

Use `sm_no_move_type@example.com`

Choose an NTS and create it.  
`Add another shipment`
See that the NTS option is disabled.
Choose an NTSr and create it.
`Add another shipment`
See that both cards are gone and are replaced with alternate text.

Log in as a different user: `hhg@only.unsubmitted`
Choose an NTSr and create one.
From review page, `Add a shipment` and see that it is now disabled.
Use browser back.  From review page, choose `Next` and submit the full move.
From Home screen, `Add a shipment`.
See that the cards are not there and the alternative text is there.

## Code Review Verification Steps

* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Only one NTS](https://dp3.atlassian.net/browse/MB-4407) for this change
* [Only one NTSr](https://dp3.atlassian.net/browse/MB-4513) for this change
* [Neither available](https://dp3.atlassian.net/browse/MB-4575) for this change

## Screenshots

has both NTS and NTSr
![image](https://user-images.githubusercontent.com/13249580/96786352-fe7b7480-13a4-11eb-840c-a4350fc971c7.png)

has NTS
![image](https://user-images.githubusercontent.com/13249580/96788683-bd855f00-13a8-11eb-8a4f-359028e71760.png)

2020-10-21 21:41 UTC, sojeri reviewed
looking good aside from one small comment. will pull locally to manually test FE before approving.

2020-10-21 21:41 UTC, sojeri commented on src/pages/MyMove/SelectMoveType.jsx
> +              {(!isNtsSelectable && !isNtsrSelectable) || move.status !== MOVE_STATUSES.DRAFT ? (
shouldn't need to separately check for draft. this should be part of is-selectable calculation

2020-10-22 19:13 UTC, lynzt requested changes
I think we need to remove this txt too when we hide the NTS(r) buttons...

<img width="505" alt="Screen_Shot_2020-10-22_at_2_02_32_PM" src="https://user-images.githubusercontent.com/3099491/96918982-b45fc500-1470-11eb-9da9-4e5fb058ed67.png">

https://app.zeplin.io/project/5f6e33d2169b8832e39d06b7/screen/5f6e34eeb1c71c8bb1a02549

2020-10-22 20:36 UTC, suzubara commented on src/pages/MyMove/SelectMoveType.jsx
> +      'You‘ve already requested a long-term storage shipment for this move. Talk to your movers to change or add to your request.';
nit: these apostrophes look backwards, I think they should be: `’`

2020-10-22 20:44 UTC, kimallen commented on src/pages/MyMove/SelectMoveType.jsx
> +      'You‘ve already requested a long-term storage shipment for this move. Talk to your movers to change or add to your request.';
Hmm, @suzubara I can't actually see the difference.  I"m trying to use the shortcuts you suggested.  Should it be option+shift+] OR option+]?

2020-10-22 22:02 UTC, kimallen commented on src/pages/MyMove/SelectMoveType.jsx
> +      'You‘ve already requested a long-term storage shipment for this move. Talk to your movers to change or add to your request.';
I think I picked the right one now. . .

2020-10-22 22:11 UTC, lynzt approved these changes
let's address the wording for the different shipments in another pr and merge this as is

🚢

2020-10-22 22:15 UTC, sojeri commented on src/pages/MyMove/SelectMoveType.jsx
> +      'You‘ve already requested a long-term storage shipment for this move. Talk to your movers to change or add to your request.';
can we just `&rsquo;` ?

2020-10-22 22:29 UTC, sojeri commented on src/pages/MyMove/SelectMoveType.jsx
> +    const hasNTS = mtoShipments.some((shipment) => shipment.shipmentType === SHIPMENT_OPTIONS.NTS);
instead of moving this all to render and dropping the tests, can we move it to a util function that gets called during render and which we can separately test?

2020-10-23 13:47 UTC, mariaclaratgolfo approved these changes

2020-10-23 16:26 UTC, kimallen commented on src/pages/MyMove/SelectMoveType.jsx
> +    const hasNTS = mtoShipments.some((shipment) => shipment.shipmentType === SHIPMENT_OPTIONS.NTS);
I did add and adjust tests in the client test to make sure we are getting the right values.  I do see where testing that logic directly will be better if something goes wrong.  I do think adding those utils and tests will bump this story into the next sprint for me.  I'm going to make a story combining your request along with adding the additional layer `SelectMoveTypeForm`.

2020-10-23 16:56 UTC, merged

2020-10-23 17:17 UTC, kimallen commented
> I think we need to remove this txt too when we hide the NTS(r) buttons...
> 
> <img alt="Screen_Shot_2020-10-22_at_2_02_32_PM" width="505" src="https://user-images.githubusercontent.com/3099491/96918982-b45fc500-1470-11eb-9da9-4e5fb058ed67.png">
> 
> https://app.zeplin.io/project/5f6e33d2169b8832e39d06b7/screen/5f6e34eeb1c71c8bb1a02549

Adding this task as a separate story, along with pulling out the logic values into a util fn with tests:
https://dp3.atlassian.net/browse/MB-4935