mb-4886 | migrate selected move type nts raw value
transcom/mymove pull request #5076
Opened 2020-10-23 20:49 UTC by sojeri

## Description

in PR #4950 I updated the raw value of move.selectedMoveType for NTS shipments, but I did not add a migration for this change to update any existing moves with NTS shipments. this PR fixes that.

add migration to reflect new NTS raw value for move.selectedMoveType
- including column comment update
- also fixed a broken link

## Reviewer Notes

Am I doing this right? :)

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-4886) for this change

2020-10-23 21:06 UTC, kimallen commented on migrations/app/schema/20201023202845_update_selectedMoveType_NTS.up.sql
> +COMMENT ON COLUMN moves.selected_move_type IS 'The type of Move the customer is choosing. Allowed values are HHG, PPM, UB, POV, HHG_INTO_NTS_DOMESTIC, HHG_OUTOF_NTS_DOMESTIC HHG_PPM (but only HHG and
I think the last part of the comment can be removed "(but only HHG and PPM appear to be used currently)".  Or you can add in HHG_INTO_NTS_DOMESTIC and HHG_OUTOF_NTS_DOMESTIC to that statement.

2020-10-23 21:08 UTC, kimallen commented on migrations/app/schema/20201023202845_update_selectedMoveType_NTS.up.sql
> +    selected_move_type = 'HHG_INTO_NTS_DOMESTIC'
Do we also need to set 'HHG_OUTOF_NTS_DOMESTIC', or was that already done previously?

2020-10-23 21:46 UTC, lynzt requested changes
LGTM, but let's first make at least 1 NTS on experimental... and then run this and make sure things don't break...

2020-10-23 21:47 UTC, lynzt commented on migrations/app/schema/20201023202845_update_selectedMoveType_NTS.up.sql
> +    selected_move_type = 'HHG_INTO_NTS_DOMESTIC'
also, good question ☝️

2020-10-26 18:07 UTC, sojeri commented on migrations/app/schema/20201023202845_update_selectedMoveType_NTS.up.sql
> +    selected_move_type = 'HHG_INTO_NTS_DOMESTIC'
we don't need to set it because NTSR is new. NTS was an existing type which got updated, so we need this migration to convert old values to new.

2020-10-26 23:21 UTC, sojeri commented
@lynzt & @kimallen, here's the results of my adding a couple moves on exp:

- none of them show up in TIO/TOO regardless of whether there's an NTS shipment included or not
- adding a PPM shipment does show in the PPM office app
- saw no other unexpected issues, though the experience of submitting a PPM after submitting the main move is not great

2020-10-27 18:24 UTC, lynzt approved these changes
with the test of the migration in experimental, LGTM 🚢

2020-10-27 19:24 UTC, merged