Nt mb 4546 add event trigger for updatemoveorder
transcom/mymove pull request #5107
Opened 2020-10-28 00:00 UTC by NamibiaLT

## Description

Add an event trigger for the UpdateMobeOrderHandler and test that a notification is sent to Prime.

## Reviewer Notes

Please take a look at whether the query errors are properly handled and logged. 

## Setup

Nothing to setup.

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-4546) for this change

2020-10-28 21:03 UTC, shimonacarvalho commented on pkg/handlers/ghcapi/move_orders.go
> +	fmt.Println("moveOrder.ID", updatedOrder.ID)
This was mine, pretty sure, but do remove it. We don't print anything in the normal functioning of the server.

2020-10-28 21:05 UTC, shimonacarvalho commented on pkg/handlers/ghcapi/move_orders.go
> +
Might be a good idea to log an error here, it's unusual to have an orders object where there is no move associated.

2020-10-28 21:06 UTC, shimonacarvalho commented on pkg/handlers/ghcapi/move_order_test.go
> +	moveOrderOK := response.(*moveorderop.UpdateMoveOrderOK) // Type assertion: Take the response, change the type to *moveorderop.UpdateMoveOrderOK, and set the variable moveOrderOK to the new type
Maybe delete my explanation comment :)

2020-10-28 21:06 UTC, shimonacarvalho commented on pkg/handlers/ghcapi/move_order_test.go
> +	// suite.HasWebhookNotification(updatedOrder.ID, traceID)
Please remove commented line

2020-10-28 21:07 UTC, shimonacarvalho commented on pkg/handlers/ghcapi/move_order_test.go
> +func (suite *HandlerSuite) TestUpdateMoveOrderEventTrigger() {
Thanks for adding a test!

2020-10-28 21:08 UTC, shimonacarvalho requested changes
Awesome job, some changes requested. Let me know if you want to talk about any of them. 

Couple of notes on review conventions in our team:
Can be useful to mention if there's a test that someone can run. 
Add the label `roci` to the labels section, that way it shows up when we look for pending prs.

2020-10-28 22:36 UTC, NamibiaLT commented
Thanks @shimonacarvalho I added the changes. Can you let me know if I wrote the error logger correctly? Really appreciate the feedback!

2020-10-30 19:24 UTC, shimonacarvalho commented on pkg/handlers/ghcapi/move_orders.go
> +	fmt.Println("moveOrder.ID", updatedOrder.ID)
Hey namibia, I'm still seeing the fmt.Println?

2020-10-30 19:33 UTC, shimonacarvalho requested changes
Hey Namibia, the log message itself looks good but there's an issue with what happens after you detect the error. I've commented at the line.

2020-10-30 19:33 UTC, shimonacarvalho commented on pkg/handlers/ghcapi/move_orders.go
> +
If you don't find the move, move will be an empty struct. Then you use `move.id` in the call below to `TriggerEvent`. Not sure what happens then - does it send an zero id? Or a nil? Or cause a nil dereference?

Ideally i think if you couldn't find the move, you want to send a `nil` in that value, and have the `TriggerEvent` handle it however it will.

2020-11-02 23:34 UTC, sandy-wright commented on pkg/handlers/ghcapi/move_orders.go
> +
I was wondering - is it an error if there's no move? Maybe the order was created without the move for some reason? In that case, I might do an if statement like:

```
if err == nil {
    // do the event trigger code here
} else {
    log.Warning("ghcapi.UpdateMoveOrderHandler could not find move - no event created")
}
```

I'm not sure if that's right, but maybe that could be a good solution!

2020-11-02 23:39 UTC, NamibiaLT commented on pkg/handlers/ghcapi/move_orders.go
> +	fmt.Println("moveOrder.ID", updatedOrder.ID)
Ok, it has been removed.

2020-11-03 00:04 UTC, shimonacarvalho commented on pkg/handlers/ghcapi/move_orders.go
> +
Hey Sandy - yeah it looks like in this case they could be updating the moveOrders prior to creating the first move and that's okay. However we are going to trigger the _event_ but add a ticket to make sure the notification package handles the situation correctly.

2020-11-03 00:04 UTC, shimonacarvalho approved these changes
Awesome work, looks good to me!

2020-11-03 00:53 UTC, sandy-wright approved these changes
LGTM!

2020-11-03 01:02 UTC, merged