MB-4934 TOO can filter status column - UI
transcom/mymove pull request #5118
Opened 2020-10-28 23:01 UTC by donaldthai

## Description

Explain a little about the changes at a high level.

## Reviewer Notes

Is there anything you would like reviewers to give additional scrutiny?

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

```sh
echo "Code goes here"
```

## Code Review Verification Steps

* [ ] If the change is risky, it has been tested in experimental before merging.
* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] The requirements listed in
 [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely)
 have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://github.com/transcom/mymove/wiki/migrate-the-database#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](tbd) for this change
* [this article](tbd) explains more about the approach used.

## Screenshots

If this PR makes visible UI changes, an image of the finished UI can help reviewers and casual
observers understand the context of the changes. A before image is optional and
can be included at the submitter's discretion.

Consider using an animated image to show an entire workflow instead of using multiple images. You may want to use GIPHY CAPTURE for this! 📸

_Please frame screenshots to show enough useful context but also highlight the affected regions._

2020-10-30 18:36 UTC, brooksr4 requested changes
The form inputs function well, although they look kind of funny because they should be on a separate row. See image below:
![image](https://user-images.githubusercontent.com/13547334/97744296-f7dfb200-1ab4-11eb-9dc4-46977a488847.png)

2020-10-30 18:38 UTC, brooksr4 submitted a review, later dismissed
One more thing, for the status filter if we can middle align the checkbox since there's a carriage return, that would make it look a little cleaner.

2020-10-30 22:01 UTC, suzubara approved these changes
I left a few minor comments but nothing is blocking. Playing with the filters locally, it feels like there's probably some UX finessing that could be done (like adding an empty state, and UI improvements) but those can probably be taken care of later. This is a really great start to a complex feature!

2020-10-30 23:40 UTC, donaldthai commented
@brooksr4 Should be all good now! 
![image](https://user-images.githubusercontent.com/1522549/97765224-890f5280-1ace-11eb-81e5-2921f1343ec0.png)

2020-11-02 17:14 UTC, monfresh commented on src/constants/queues.js
> +};
What do y'all think about making this an explicit hash with `value` and `label` keys, so that it's clear which is which? Right now, with some of them having the same text on both sides, it's not immediately clear which one you would need to update.

2020-11-02 17:31 UTC, donaldthai commented on src/constants/queues.js
> +};
So instead of the object key value you would want to define the `value` and `label`. So pre-made like this?
```javascript
var branchFilterOptions = [
{ label: 'Air Force', value: 'AIR_FORCE' },
...
];
```

2020-11-02 19:46 UTC, monfresh commented on src/constants/queues.js
> +};
Exactly.

2020-11-02 19:47 UTC, monfresh commented on src/constants/queues.js
> +};
It doesn't have to be in this PR. I can write a JIRA story for later.

2020-11-02 20:03 UTC, donaldthai commented on src/constants/queues.js
> +};
Since we aren't using the options for anything else, I don't mind that format.

2020-11-02 20:27 UTC, amanda5iu approved these changes
Approved pending removal of the `x` from the filter fields, [as discussed in Slack](https://ustcdp3.slack.com/archives/CP4979J0G/p1604347471088900).

2020-11-02 20:36 UTC, donaldthai commented
> Approved pending removal of the `x` from the filter fields, [as discussed in Slack](https://ustcdp3.slack.com/archives/CP4979J0G/p1604347471088900).

Removed the `x`:
![image](https://user-images.githubusercontent.com/1522549/97916596-0ffb3f80-1d08-11eb-8a8c-6b512665cb7e.png)

2020-11-02 21:06 UTC, merged