MB-5119 Storybook Pagination
transcom/mymove pull request #5150
Opened 2020-11-04 21:00 UTC by noelledusahel

## Description

Explain a little about the changes at a high level.

## Reviewer Notes

Is there anything you would like reviewers to give additional scrutiny?

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

```sh
echo "Code goes here"
```

## Code Review Verification Steps

* [ ] If the change is risky, it has been tested in experimental before merging.
* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] The requirements listed in
 [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely)
 have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://github.com/transcom/mymove/wiki/migrate-the-database#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](tbd) for this change
* [this article](tbd) explains more about the approach used.

## Screenshots

If this PR makes visible UI changes, an image of the finished UI can help reviewers and casual
observers understand the context of the changes. A before image is optional and
can be included at the submitter's discretion.

Consider using an animated image to show an entire workflow instead of using multiple images. You may want to use GIPHY CAPTURE for this! 📸

_Please frame screenshots to show enough useful context but also highlight the affected regions._

2020-11-04 22:40 UTC, donaldthai requested changes
Looking good so far. I do think there's some changes we could do though. Comments on code. Let me know if you wanna pair or have questions.

2020-11-04 22:40 UTC, donaldthai commented on src/components/Table/Table.jsx
> +import { ReactComponent as ChevronRight } from '../../shared/icon/chevron-right.svg';
Heard from @suzubara that we're moving away from icons we upload in place of fontawesome. Found the chevron icons for fontawesome: https://fontawesome.com/icons?d=gallery&q=chevron&m=free

Here's an example of how we import them: https://github.com/transcom/mymove/blob/master/src/components/Table/Filters/MultiSelectCheckBoxFilter.jsx#L6

2020-11-04 22:40 UTC, donaldthai commented on src/components/Table/Table.jsx
> +            </c>
What's `<c></c>` suppose to be? The console is throwing an error for this: 
![image](https://user-images.githubusercontent.com/1522549/98173981-ea596c00-1ea8-11eb-9add-9f6eca759e3c.png)

2020-11-04 22:40 UTC, donaldthai commented on src/components/Table/Table.jsx
> +            <c className={styles.usaButtonUnstyled}>
Same here, what's `<c></c>`?

2020-11-04 22:40 UTC, donaldthai commented on src/components/Table/Table.jsx
> +            </select>
Mind replacing the `<select>` with our TrussWorksUSWDS component? I think it'll be easier to maintain and don't have to worry about styling too much if we use that component. Here's an example: https://github.com/transcom/mymove/blob/master/src/components/Table/Filters/SelectFilter.jsx#L4

2020-11-04 22:40 UTC, donaldthai commented on src/components/Table/Table.jsx
> +            </select>
I also notice the icon is different than the USWDS version: 
regular `<select>` - single chevron down
![image](https://user-images.githubusercontent.com/1522549/98174422-ba5e9880-1ea9-11eb-94d6-3af30b52354a.png)

USWDS - double chevron up down
![image](https://user-images.githubusercontent.com/1522549/98174557-eb3ecd80-1ea9-11eb-9fbd-170958f808db.png)

2020-11-04 22:40 UTC, donaldthai commented on src/components/Table/Table.module.scss
> +      font-size: 12px;
I think we should be able to remove this `font-size` since the font-size is set globally at the body.

2020-11-04 22:40 UTC, donaldthai commented on src/components/Table/Table.module.scss
> +      font-size: 12px;
I think if we import the TrussWorksUSWDS component, we won't need to worry about font-size either when the page resizes.

2020-11-04 22:40 UTC, donaldthai commented on src/components/Table/Table.module.scss
> +    }
Should be able to remove `display:flex` from `.tableControlPagination` and `tableControlRowsPerPage` since `display:flex` is set in `.paginationSectionWrapper`

2020-11-04 23:18 UTC, noelledusahel commented on src/components/Table/Table.jsx
> +            </select>
tbh i got it from here https://storybook.dp3.us/?path=/story/components-tables--table-elements, but i'm seeing in our code `Button` from uswds is being used

2020-11-04 23:31 UTC, suzubara reviewed
I left some comments.. It looks like the pagination markup was copied from the table elements stories (https://storybook.dp3.us/?path=/story/components-tables--table-elements) but unfortunately this is a misleading example. The code in that story is just an example of how it should look, but doesn't implement it as a functional React component, so I would expect some changes are needed.

2020-11-04 23:31 UTC, suzubara commented on src/components/Table/Table.jsx
> +    <div className={styles.inlineBlock}>
What is the reason for wrapping a Table inside an inline-block div?

2020-11-04 23:31 UTC, suzubara commented on src/components/Table/Table.jsx
> +        <div className={styles.paginationSectionWrapper}>
Should the pagination markup be rendered for every table? What about tables without pagination?

2020-11-04 23:31 UTC, suzubara commented on src/components/Table/Table.jsx
> +            </c>
I'm getting the same error. Maybe this is suppose to be a `Button`?

2020-11-04 23:31 UTC, suzubara commented on src/components/Table/Table.module.scss
> +      height: 38px;
We shouldn't be setting explicit height/width on elements unless absolutely necessary.

2020-11-04 23:31 UTC, suzubara commented on src/components/Table/Table.jsx
> +            <div className={styles.tableControlRowsPerPage}>
I don't think both of these divs are necessary

2020-11-04 23:31 UTC, suzubara commented on src/components/Table/Table.stories.jsx
> +export const TXOTablePagination = () => <CreateTableWithPagination />;
I am seeing pagination controls for all of the table stories, when I would expect to only see it for this one. Should there be Table stories where no pagination is displayed?

also, it might be good to include enough test data in the pagination table story for the pagination to be used.

2020-11-05 13:18 UTC, noelledusahel commented on src/components/Table/Table.jsx
> +            </c>
tbh i got it from here https://storybook.dp3.us/?path=/story/components-tables--table-elements, but i'm seeing in our code Button from uswds is being used

2020-11-11 22:09 UTC, donaldthai approved these changes
Some non-blocking comments but LGTM!

2020-11-11 22:09 UTC, donaldthai commented on src/components/Table/Table.module.scss
> +// @import 'shared/styles/_overrides';
nit: Let's remove this if we don't need it anymore

2020-11-11 22:09 UTC, donaldthai commented on src/components/Table/Table.module.scss
> +}
nit: These can be removed since it's not being used.

2020-11-12 19:00 UTC, noelledusahel commented on src/components/Table/Table.jsx
> +  perPage: [10, 20, 50],
@brooksr4  this is where you'd add an option for 1 per page: [1, 20, 50]

2020-11-12 19:54 UTC, suzubara reviewed
💯  this is looking really solid! I left a few minor comments

2020-11-12 19:54 UTC, suzubara commented on src/components/Table/Table.jsx
> +            <Button className={styles.usaButtonUnstyled} onClick={previousPage} disabled={!canPreviousPage}>
all `<Button>`s should have the `type="button"` prop

2020-11-12 19:54 UTC, suzubara commented on src/components/Table/Table.module.scss
> +.inlineBlock {
Doesn't look like this is used anymore, can we delete it?

2020-11-12 19:54 UTC, suzubara commented on src/components/Table/Table.module.scss
> +      .usaButtonUnstyled {
Instead of re-implementing `usaButtonUnstyled` in CSS modules, it should be applied using the existing global CSS. Since this is the ReactUSWDS Button component, adding the `unstyled` prop will achieve this ([docs](https://trussworks.github.io/react-uswds/?path=/story/button--unstyled)):
```<Button unstyled ... />```

If you need to override or add more styling then those can be added with another CSS class and styles in this module file.

2020-11-12 19:54 UTC, suzubara commented on src/components/Table/Table.module.scss
> +      .usaSelect {
similar to my comment above. It's fine to override CSS with new classes, but giving them the same name as existing USWDS classes is confusing, so can this be called something else? Alternatively, it can be selected using the global class like:
```
:global(.usa-select) { width: unset; }
```

2020-11-12 22:11 UTC, noelledusahel commented on src/scenes/Office/office.scss
> +.icon-right {
@suzubara i included these because i'd expect pagination icons' margins to mirror each other, but i realize not all icons have this style. is this fine? or better, a specific class (like pagination-icon-right' )

2020-11-13 15:49 UTC, brooksr4 approved these changes
Thanks for showing me where to add it. Looks good to me!

2020-11-13 17:42 UTC, merged