[MB-4544] WIP: support api calls process reviewed payment request
transcom/mymove pull request #5163
Opened 2020-11-05 21:57 UTC by pearl-truss

## Description

This is a draft PR of work in progress (it's missing unit tests). The PR is to create a support api endpoint to trigger the processing of  reviewed payment request. 

- If the sendToSyncada flag is true, it calls the ProcessReviewedPaymentRequest service. 
- If the sendToSyncada flag is false and a paymentRequestId is provided, it will find and update the status of that particular payment request. By default the status is switched to Sent_To_Gex. (There is a status flag, if provided it will change the status to match the flag)
- If the sendToSyncada flag is false and no paymentRequestId is provided, it will find all payment request with a reviewed status and switch the status of each to match the status flag. If no status flag provided, they're switched to a Sent_To_Gex status

## Reviewer Notes

Is there anything you would like reviewers to give additional scrutiny?

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

```sh
echo "Code goes here"
```

## Code Review Verification Steps

* [ ] If the change is risky, it has been tested in experimental before merging.
* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] The requirements listed in
 [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely)
 have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://github.com/transcom/mymove/wiki/migrate-the-database#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](tbd) for this change
* [this article](tbd) explains more about the approach used.

## Screenshots

If this PR makes visible UI changes, an image of the finished UI can help reviewers and casual
observers understand the context of the changes. A before image is optional and
can be included at the submitter's discretion.

Consider using an animated image to show an entire workflow instead of using multiple images. You may want to use GIPHY CAPTURE for this! 📸

_Please frame screenshots to show enough useful context but also highlight the affected regions._

2020-11-10 16:34 UTC, reggieriser reviewed
Nice job on a complex endpoint!  I left some comments on some things to review.  I was able to run the first two cases, but not the third (think it's just an E2E data setup issue).

2020-11-10 16:34 UTC, reggieriser commented on pkg/testdatagen/scenario/e2ebasic.go
> +			ID:            uuid.FromStringOrNil("345c9ebb-972f-4711-acb2-5911f52acpp9"),
This is a bad UUID, so it's returning `nil` and creating a new UUID each time this is re-run.

2020-11-10 16:34 UTC, reggieriser commented on pkg/testdatagen/scenario/e2ebasic.go
> +	testdatagen.MakePaymentServiceItem(db, testdatagen.Assertions{
It looks like we're going to need to add some service item params here if we want the third case in your instructions to work.  Right now, I'm getting this instead:

```json
{
  "Payload": {
    "detail": "function ProcessReviewedPaymentRequest failed call to generator.Generate: id: 00000000-0000-0000-0000-000000000000 not found for ContractCode",
    "instance": "4987f1e9-7de1-4377-87e2-89fc59b2b560",
    "title": "Internal Server Error"
  }
}
```

2020-11-10 16:40 UTC, pearl-truss commented on pkg/handlers/supportapi/payment_request.go
> +			updatedPaymentRequest, err := h.PaymentRequestStatusUpdater.UpdatePaymentRequestStatus(&paymentRequestForUpdate, nilEtag)
UpdatePaymentRequestStatus requires an eTag, but we decided we need more information on if/how this enpoint should use etags so it doesn't have a valid eTag to pass in. So instead of tabling the whole story, it was decided to make this endpoint not require an eTag for now. https://ustcdp3.slack.com/archives/CP6F568DC/p1604697280339500?thread_ts=1604690916.327700&cid=CP6F568DC

2020-11-10 16:40 UTC, pearl-truss commented on swagger/support.yaml
> +      # eTag:
I can remove it but I'd intentionally left it in since we're going to be coming back to this endpoint and adding/requiring an eTag

2020-11-10 16:43 UTC, pearl-truss commented on pkg/handlers/supportapi/payment_request.go
> +			paymentRequestForUpdate := models.PaymentRequest{
I can look into it. For context, I followed the same convention as the `UpdatePaymentRequestStatusHandler` found at the top of the file https://github.com/transcom/mymove/pull/5163/files/30bd36ee0bf369a7291c197fd7ef9e28f4c3d91c#diff-f0420efb25f24d852a5557d1a735e23438f664baaccf1211d5e631f586301617L91

2020-11-10 16:44 UTC, pearl-truss commented on pkg/handlers/supportapi/payment_request.go
> +				ReviewedAt:           &reviewedDate,
same as above

2020-11-10 16:56 UTC, reggieriser commented on pkg/handlers/supportapi/payment_request.go
> +				ReviewedAt:           &reviewedDate,
Hmm, I think this is still a potential issue (and maybe in the other code too).  Consider this scenario.  A payment request has been reviewed by the TIO and has a `ReviewedAt` time set.  Then this code runs and sets the `sentGexData` local variable only in the case above.  That means th elocal `reviewedDate` is still the zero time.  We'd overwrite the legit reviewed at date with the zero date I believe.

2020-11-10 22:04 UTC, jacquelineIO commented on pkg/handlers/supportapi/payment_request_test.go
> +	for i := 0; i < 4; i++ {
Did you mean to use the `num int` passed in to control the loop count here?

2020-11-10 22:07 UTC, jacquelineIO commented on pkg/testdatagen/scenario/e2ebasic.go
> +	// })
don't forget to remove commented out code

2020-11-11 15:29 UTC, pearl-truss commented on pkg/handlers/supportapi/api.go
> +	var logger paymentrequest.Logger
@reggieriser this is still outstanding. I've run into type issues when trying to get a value for this logger.

2020-11-11 15:57 UTC, pearl-truss commented on pkg/services/payment_request/payment_request_reviewed_processor.go
> +	sftpSession = nil
I want to call out this change. I removed the call to initialize a Syncada session because from my understanding we don't have the environment variables setup in `invoice.InitNewSyncadaSFTPSession` to actually establish a connection to syncada. Which was causing a "can't assign requested address" issue. 

@transcom/truss-a-team

2020-11-12 01:45 UTC, gidjin commented on pkg/services/payment_request/payment_request_reviewed_processor.go
> +	sftpSession = nil
We should have variables for connecting to Syncada via sftp stored chamber. They likely won't exist in a test context though.

2020-11-12 18:39 UTC, reggieriser requested changes
We're almost there -- blocking until we sort out the issues I noted with the DB updates.

2020-11-12 18:39 UTC, reggieriser commented on pkg/handlers/supportapi/payment_request.go
> +			pr.ReceivedByGexAt = &recGexDate
I did a test where I set the `requested_at` and `reviewed_at` columns in the payment request to actual dates, then ran case 1 from the setup instructions.  I noticed in the DB that those two columns stayed with their original values (good), the `sent_to_gex_at` was set to the current timestamp (good), but `received_by_gex_at` and `paid_at` changed to be the zero value timestamp rather than `null` (bad).  I've got some ideas about how we may be able to simplify the code above and get past this issue if you'd like to pair on it.

2020-11-12 18:39 UTC, reggieriser commented on pkg/handlers/supportapi/payment_request.go
> +					return paymentrequestop.NewProcessReviewedPaymentRequestsBadRequest().WithPayload(payloads.ClientError(handlers.BadRequestErrMessage, "bad request, an invalid status type was used", h.GetTraceID
Nit: This is subjective, but it might be a little more readable to use two `case` statements here: a `case ""` for the first part of the `if` and a `default` for the else part.  The `if` then goes away.

2020-11-12 18:39 UTC, reggieriser commented on pkg/handlers/supportapi/payment_request.go
> +		err := reviewedPaymentRequestProcessor.ProcessReviewedPaymentRequest()
I noticed when running case 3 that the status changed to `SENT_TO_GEX`, but the `sent_to_gex_at` timestamp was still `null` in the DB.  Should that service be setting that?  If so, we may need a story to fix the service.

2020-11-12 19:19 UTC, pearl-truss commented on pkg/handlers/supportapi/payment_request.go
> +			pr.ReceivedByGexAt = &recGexDate
I think I found a fix for this (I verified the null timestamps after running case 1)

2020-11-12 19:19 UTC, pearl-truss commented on pkg/handlers/supportapi/payment_request.go
> +			pr.ReceivedByGexAt = &recGexDate
Also, thanks for catching this!

2020-11-12 19:24 UTC, pearl-truss commented on pkg/handlers/supportapi/payment_request.go
> +		err := reviewedPaymentRequestProcessor.ProcessReviewedPaymentRequest()
yeah that would be my understanding. I created https://dp3.atlassian.net/browse/MB-5474 to address

2020-11-12 19:27 UTC, pearl-truss commented on pkg/services/payment_request/payment_request_reviewed_processor.go
> +	sftpSession = nil
@gidjin I'm just catching your comment. Yes we have: 

```
func InitNewSyncadaSFTPSession() services.SyncadaSFTPSender {
	return NewSyncadaSFTPSession(os.Getenv("SYNCADA_SFTP_PORT"), os.Getenv("SYNCADA_SFTP_USER_ID"), os.Getenv("SYNCADA_SFTP_IP_ADDRESS"), os.Getenv("SYNCADA_SFTP_PASSWORD"), os.Getenv("SYNCADA_SFTP_INBOUND_DIRECTORY"))
}
```

Is the expectation that these variables should work for the support api?

2020-11-12 20:13 UTC, reggieriser approved these changes
Thanks for making the changes!  I tried case 1 again and this time see that `null` values stay that way in the DB.  👍

2020-11-12 20:30 UTC, gidjin commented on pkg/services/payment_request/payment_request_reviewed_processor.go
> +	sftpSession = nil
🤔  yes, I would expect that those variables need to be set when the server is started otherwise the support api will not be able to contact Syncada. However, looking at it some now I'm realizing that there will likely need to be some additional work to get those variables through. First, we need to make sure our local docker setup is ready to pass those in. Second, we'll need to ensure they are setup in chamber for stg and exp and ensure the deploy passes them in properly. All of that is worth a new story. We could make this check for the presence of those vars and if present create the new session and if not return nil or an error so it can be skipped gracefully. I'm fine if that is just left to be part of the new story

2020-11-12 20:40 UTC, pearl-truss commented on pkg/services/payment_request/payment_request_reviewed_processor.go
> +	sftpSession = nil
@gidjin thanks for the clarification. I'm not really sure how I would test for the presence of the variables. If it's okay to move that into a new story I can create a ticket for it

2020-11-12 20:47 UTC, gidjin approved these changes
Changes look good, :shipit: and create a new story for connecting syncada environment vars

2020-11-12 20:49 UTC, gidjin commented on pkg/services/payment_request/payment_request_reviewed_processor.go
> +	sftpSession = nil
Yeah I'm good to put that into the new story as well. Let me know if you need feedback on the story once it's created

2020-11-12 20:55 UTC, pearl-truss commented on pkg/services/payment_request/payment_request_reviewed_processor.go
> +	sftpSession = nil
Great, I created https://dp3.atlassian.net/browse/MB-5483

2020-11-12 22:37 UTC, merged