MB-5337 Add Camp LeJeune transportation office with USMC GBLOC
transcom/mymove pull request #5191
Opened 2020-11-10 18:06 UTC by Ryan-Koch

## Description

Migration that inserts a new transportation office to handle all USMC moves, which is given the USMC GBLOC value. 

## Setup

Run the migration step below locally, once done you should see the entry in your local dev db.

```sh
make db_dev_migrate
```

## Code Review Verification Steps

* [ ] If the change is risky, it has been tested in experimental before merging.
* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] The requirements listed in
 [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely)
 have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://github.com/transcom/mymove/wiki/migrate-the-database#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

2020-11-10 21:08 UTC, duncan-truss commented on migrations/app/schema/20201110162713_make_usmc_transportation_office.up.sql
> +-- Data for Name: office_emails; Type: TABLE DATA; Schema: public; Owner: postgres
I see an office_emails record for the `DMO Camp LeJune` transportation office too did you want to add that as well

2020-11-10 21:20 UTC, monfresh commented on migrations/app/schema/20201110162713_make_usmc_transportation_office.up.sql
> +-- Data for Name: office_emails; Type: TABLE DATA; Schema: public; Owner: postgres
Are we sure this USMC entry is supposed to have the same address as the regular DMO Camp LeJeune?

2020-11-10 21:21 UTC, monfresh commented on migrations/app/schema/20201110162713_make_usmc_transportation_office.up.sql
> +-- Data for Name: office_emails; Type: TABLE DATA; Schema: public; Owner: postgres
Same question for the hours and services. Are they the same? Does it matter?

2020-11-10 21:24 UTC, monfresh commented on migrations/app/schema/20201110162713_make_usmc_transportation_office.up.sql
> +
It's interesting that the `number` column in `office_phone_lines` is freeform and not enforcing any kind of standard. I would expect at least an area code for each number.

2020-11-10 21:24 UTC, Ryan-Koch commented on migrations/app/schema/20201110162713_make_usmc_transportation_office.up.sql
> +-- Data for Name: office_emails; Type: TABLE DATA; Schema: public; Owner: postgres
I believe we're using the same data for this as the DMO version (that's what my read of the story anyway). I'll ping Alexi in slack to verify. Also good catch on noticing I missed the email record.

2020-11-10 21:25 UTC, Ryan-Koch commented on migrations/app/schema/20201110162713_make_usmc_transportation_office.up.sql
> +
Yeah I thought that was a bit off too

2020-11-11 16:22 UTC, Ryan-Koch commented on migrations/app/schema/20201110162713_make_usmc_transportation_office.up.sql
> +-- Data for Name: office_emails; Type: TABLE DATA; Schema: public; Owner: postgres
Added in the email record and got confirmation from Alexi that the data should be the same as the DMO record.

2020-11-11 19:32 UTC, duncan-truss approved these changes

2020-11-12 16:00 UTC, reggieriser requested changes
I ran the migration and it added the records as expected.  Just asking for one small change though -- can we use `now()` instead of the hard-coded timestamps?

BTW, I assume the 7-digit phone number is because that's marked as a DSN line where area code doesn't apply.

2020-11-12 16:19 UTC, Ryan-Koch commented on migrations/app/schema/20201110162713_make_usmc_transportation_office.up.sql
> +INSERT INTO public.office_phone_lines VALUES ('c20bbee8-72a8-4510-9dcb-20757e05ad36', 'ccf50409-9d03-4cac-a931-580649f1647a', '(910) 451-2377', NULL, false, 'voice', '2020-11-10 17:47:34.148582', '20
Done 👍

2020-11-12 16:20 UTC, reggieriser approved these changes
Thanks for making the change.  LGTM!  🚀

2020-11-12 16:35 UTC, merged