[MB-5245] Print legal agreement
transcom/mymove pull request #5202
Opened 2020-11-11 22:38 UTC by Ronolibert

## Description

Print legal agreement from the homepage

## Setup
`make server_run`
`make client_run`
1. Completely set up a move
2. Print legal agreement on homepage
Expected result: Print preview should have legalese, signature and the date you signed it

## Code Review Verification Steps
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-5245) for this change

## Screenshots

![image](https://user-images.githubusercontent.com/13622298/98872450-6ca6da80-242b-11eb-92e4-3e8d8c694147.png)

2020-11-12 15:16 UTC, mariaclaratgolfo approved these changes

2020-11-12 17:21 UTC, kimallen commented on src/pages/MyMove/Home/index.jsx
> +                              Prink the legal agreement
"Prink" --> "Print"

2020-11-12 18:30 UTC, kimallen reviewed
I know the ticket says to treat this print button the same as we do on the signature page, which it does; however, I noticed that on Firefox, it does not show a preview, it just shows this below.  @mariaclaratgolfo I'm wondering if that's acceptable behavior?  It does show a preview in Edge, still trying to get IE running to check there.
![image](https://user-images.githubusercontent.com/13249580/98979839-b4337200-24d0-11eb-90b4-0b9309bdd521.png)

It could also be that FIrefox allows to you adjust settings to be able to see the preview or not, I don't know.

UPDATE: I tested IE and similar to Firefox I don't see a preview 
![image](https://user-images.githubusercontent.com/13249580/98983956-5efa5f00-24d6-11eb-98d3-94e84617d926.png)

2020-11-12 19:13 UTC, kimallen requested changes
If I submit a move and then go to print from the home page directly, the signature and date are not populated but are expected to be:
![image](https://user-images.githubusercontent.com/13249580/98985063-e2688000-24d7-11eb-9c8b-1cddefb7c999.png)

However, if I log out and log back in, the values are populated.

Change requested for this and a small typo, but the code otherwise looks good and works.

2020-11-13 17:19 UTC, Ronolibert commented on src/pages/MyMove/Home/index.jsx
> +                              Prink the legal agreement
Oops! Fixed this

2020-11-13 17:20 UTC, Ronolibert commented
> If I submit a move and then go to print from the home page directly, the signature and date are not populated but are expected to be:
> ![image](https://user-images.githubusercontent.com/13249580/98985063-e2688000-24d7-11eb-9c8b-1cddefb7c999.png)
> 
> However, if I log out and log back in, the values are populated.
> 
> Change requested for this and a small typo, but the code otherwise looks good and works.

Good catch! The lifecycle method wasn't catching this. Added logic to fetch the certification if the move being provided to the homepage is already submitted

2020-11-13 17:23 UTC, Ronolibert commented
> I know the ticket says to treat this print button the same as we do on the signature page, which it does; however, I noticed that on Firefox, it does not show a preview, it just shows this below. @mariaclaratgolfo I'm wondering if that's acceptable behavior? It does show a preview in Edge, still trying to get IE running to check there.
> ![image](https://user-images.githubusercontent.com/13249580/98979839-b4337200-24d0-11eb-90b4-0b9309bdd521.png)
> 
> It could also be that FIrefox allows to you adjust settings to be able to see the preview or not, I don't know.
> 
> UPDATE: I tested IE and similar to Firefox I don't see a preview
> ![image](https://user-images.githubusercontent.com/13249580/98983956-5efa5f00-24d6-11eb-98d3-94e84617d926.png)

I think this is just default behavior for certain browsers but the print should still print the correct information. There are some workarounds we can explore for browsers like firefox like opening the file in a separate tab so it exposes firefox's print toolbar that does give the print preview but it's a a little more involved

2020-11-13 22:12 UTC, kimallen approved these changes
It works!  I'm approving, though also wonder if we need a client test for the `PrintableLegalese.jsx` component (which might have caught the earlier bug)

2020-11-13 22:15 UTC, Ronolibert commented
> It works! I'm approving, though also wonder if we need a client test for the `PrintableLegalese.jsx` component (which might have caught the earlier bug)

It's tricky because the PrintableLegalese doesn't always have data. It only has it in 2 situations, having submitted a move and directly after submitting a move, and to test both you need some real API data flow. I was trying to do an integration test but they don't have an API to check the print preview since its technically invisible up until you try to print. So I couldn't find any valuable tests to make

2020-11-13 22:19 UTC, merged