MB-5054 - Port run_ENV_migrations make commands from com to gov
transcom/mymove pull request #5205
Opened 2020-11-11 23:41 UTC by dynamike

## Description

Right now the run_env_migrations makefile endpoints are still tied to the legacy commercial environment. This PR updates things to use GovCloud. In this process it also decouples the logic to call out to the vault go library as that does not support assuming IAM roles between AWS accounts.

## Reviewer Notes

I'll be updating the https://github.com/transcom/mymove/wiki/migrate-the-database wiki as part of this PR

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

```sh
DISABLE_AWS_VAULT_WRAPPER=1 AWS_REGION=us-gov-west-1 aws-vault exec transcom-gov-milmove-exp make run_exp_migrations 
DISABLE_AWS_VAULT_WRAPPER=1 AWS_REGION=us-gov-west-1 aws-vault exec transcom-gov-milmove-stg make run_stg_migrations 
DISABLE_AWS_VAULT_WRAPPER=1 AWS_REGION=us-gov-west-1 aws-vault exec transcom-gov-milmove-prd make run_prd_migrations
```

## Code Review Verification Steps

* [ ] If the change is risky, it has been tested in experimental before merging.
* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] The requirements listed in
 [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely)
 have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://github.com/transcom/mymove/wiki/migrate-the-database#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](tbd) for this change
* [this article](tbd) explains more about the approach used.

2020-11-12 14:08 UTC, travelar approved these changes

2020-11-12 15:56 UTC, kilbergr requested changes
Please update references to `run_ENV_migrations` in documentation to reflect this change.

2020-11-12 15:59 UTC, gidjin reviewed
I'm in the process of running the migrations. One thing is that this setup requires a long command line, which we are not used to on milmove. I'm wondering if we can put `DISABLE_AWS_VAULT_WRAPPER=1 AWS_REGION=us-gov-west-1 aws-vault exec transcom-gov-milmove-exp` inside of the make command `make run_exp_migrations` to make the transition simpler.

2020-11-12 16:04 UTC, kilbergr commented
I would like to see an app eng run it. I'm wondering whether we can keep the make command a little simpler by putting the DISABLE part in the command like on line 399-402.

2020-11-12 16:05 UTC, kilbergr commented
Oh I see @gidjin s response now--yeah I am on a similar page.

2020-11-12 16:53 UTC, dynamike commented
@gidjin @kilbergr I simplified things a bit. Can y'all test it out?

2020-11-12 16:53 UTC, gidjin requested changes
The stg and exp migrations ran successfully! 🎉  However, the prd migrations failed with the below error, to make sure it wasn't a fluke I ran it twice. Marking this as changes requested due to that. Would also like to see the commands simplified if possible.

```sh
[POP] 2020/11/12 16:39:38 info - > add_april_fuel_eia_diesel_prices
[POP] 2020/11/12 16:39:38 info - > update_superusers
[POP] 2020/11/12 16:39:38 info - > add_new_tdls
AWS Error Code: "AccessDenied", "Access Denied", %!q(<nil>)
[POP] 2020/11/12 16:39:38 info - 9.7493 minutes
panic: error running migrations: error reading migration file at "s3://transcom-gov-milmove-prd-app-us-gov-west-1/secure-migrations/20190410215335_add_05_2019_tspps.up.sql": AccessDenied: Access Denied
        status code: 403, request id: D619D35998EA906D, host id: 0LRQSu4IGLXHzsjuem2pIfXcAx4NbvNabVJgE7YgPJYvS7bjopvI9F2C3OPsiWGjW18ktoxiigk=

goroutine 1 [running]:
main.main()
        /Users/john/projects/dod/mymove/cmd/milmove/main.go:122 +0x159a
make: *** [run_prd_migrations] Error 2
```

2020-11-12 16:54 UTC, dynamike commented
The looks like a IAM perms issue on the AWS side of things

2020-11-12 17:22 UTC, gidjin commented
Update short commands are working great! Thanks for making that change. Let me know when to test the prd migrations again.

2020-11-14 00:46 UTC, gidjin approved these changes
Changes work for me! :shipit: Reminder to modify the docs https://github.com/transcom/mymove/wiki/migrate-the-database once it's merged or shortly before and to make an announcement in #prac-engineering and maybe even the next demo

2020-11-16 16:59 UTC, kilbergr requested changes
Please update references to run_ENV_migrations in documentation to reflect this change.

2020-11-16 21:02 UTC, dynamike commented
@kilberg I've update the docs.

2020-11-16 21:15 UTC, kilbergr requested changes
I'm referring to references within MyMove: https://github.com/transcom/mymove/blob/master/scripts/pricing-import#L126 and https://github.com/transcom/mymove/blob/master/scripts/generate-secure-migration#L77. Since you've changed the names of the make commands, you have to update these as well.

2020-11-17 12:44 UTC, kilbergr requested changes
Caught a typo and removed some no longer correct info. Once this is changed, will approve.

2020-11-17 12:44 UTC, kilbergr commented on scripts/pricing-import
> +    3. Run make run_prd_migrations to verify that the upload worked and that the migration can be applied successfully. This will check against the commercial environment at the moment.
```suggestion
    3. Run make run_prd_migrations to verify that the upload worked and that the migration can be applied successfully.
```

2020-11-17 12:44 UTC, kilbergr commented on scripts/generate-secure-migration
> +    4. Run make run_pr_migrations to verify that the upload worked and that the migration can be applied successfully. This will check against the commercial environment only at the moment.
```suggestion
    4. Run make run_prd_migrations to verify that the upload worked and that the migration can be applied successfully.
```

2020-11-17 17:10 UTC, kilbergr approved these changes

2020-11-17 17:46 UTC, merged