[MB-3605] Fixes UpdateMTOPostCounselingInfoHandler payload response
transcom/mymove pull request #5207
Opened 2020-11-12 02:16 UTC by chrisrcoles

## Description

This PR introduces a fix to ensure that the API response for `UpdateMTOPostCounselingInfoHandler` includes `moveOrder.customer` and `moveOrder.destinationDutyStation`. Prior to this work, there were not values being returned for these attributes. 

## Reviewer Notes

In-line comments

## Setup

```
# Ensure tests are passing successfully
mylaptop ~ %: cd /mymove
mylaptop ~ %: make server_run
mylaptop ~ %: go test ./pkg/handlers/ghcapi --testify.m "TestMoveTaskOrderUpdater_UpdatePostCounselingInfo" -v 

# Ensure payload includes `moveOrder.customer` and `moveOrder.destinationDutyStation`
# _Note: Substitute `moveTaskOrderID`and `etag`_
curl --location --request PATCH 'https://primelocal:9443/prime/v1/move-task-orders/{moveTaskOrderID}/post-counseling-info' \
--header 'If-Match: {eTag}' \
--header 'Content-Type: application/json' \
--data-raw '{
    "ppmEstimatedWeight": 1500,
    "ppmType": "FULL"
}'
```

## Code Review Verification Steps

* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-3605)

2020-11-12 02:30 UTC, chrisrcoles commented on pkg/services/move_task_order/move_task_order_updater.go
> +	err = o.db.Q().Eager(
Previously, we were [only using `builder.FetchOne` to return only the `moveTaskOrder`](https://github.com/transcom/mymove/blob/380b1e558432730bcccdc8e8de3a68e1b9336dc8/pkg/services/move_task_order/move_task_order_updater.go#L113). This implementation excludes returning any associated data. In this case, `Orders.NewDutyStation.Address` and `Orders.ServiceMember` were not being queried from the database and thus not populating the payload correctly. Given that 1) since the new Pop 5 update now we are able to selectively query only the related data we want and 2) neither [`FetchOne`](https://github.com/transcom/mymove/blob/380b1e558432730bcccdc8e8de3a68e1b9336dc8/pkg/services/move_task_order/move_task_order_updater.go#L113) nor [`UpdateOne`](https://github.com/transcom/mymove/blob/master/pkg/services/query/query_builder.go#L360) return associated data, the [Eager() implementation](https://godoc.org/github.com/gobuffalo/pop#Connection.Eager) made the most sense. Because this happens before the update, we can be assured that we are able to query all the necessary data before updating the record.

2020-11-12 02:33 UTC, chrisrcoles commented on pkg/services/move_task_order/move_task_order_updater_test.go
> +		suite.NotNil(expectedMTO.Orders.NewDutyStation.Address.State)
these checks ensure that the previously nil fields have been fixed

2020-11-13 16:47 UTC, shimonacarvalho requested changes

2020-11-13 16:47 UTC, shimonacarvalho commented on pkg/services/move_task_order/move_task_order_updater.go
> +	err = o.db.Q().Eager(
Hey Chris, tested and it works yay. I agree I think selective Eager is a good choice here. 

It looks to me that you are overwriting moveTaskOrder with this query, is there any reason why you are keeping the other call to the query builder FetchOne on line 113? Seems like we could rip out the entire Fetcher as we are not using it any more? Unless I'm missing some other point in the function where we are?

2020-11-13 20:12 UTC, chrisrcoles commented on pkg/services/move_task_order/move_task_order_updater.go
> +	err = o.db.Q().Eager(
Hey Shimona - good catch. I've removed it.

2020-11-13 20:49 UTC, abbyoung approved these changes
lgtm!

2020-11-13 20:51 UTC, merged