MB-5431 - Add annotation for detect private key pre-commit hook
transcom/mymove pull request #5239
Opened 2020-11-16 23:06 UTC by amitch23

## Description

Based on discovery by @kimallen , all the keys except one case, are fake keys used for local development. Therefore, including an annotation indicating as much is the desired outcome.

The exception is in pkg/cli/auth.go which does not include an actual key- just the formatting for interpolating one.

This PR adds the annotation comment in the pre-commit config for the hook detect-private-key.

## Reviewer Notes

It was not straightforward to include inline annotations for this pre-commit hook in the .ssh and .go files detected (see jira ticket for full list of files). As such, it seemed the most straightforward to use the exclude block in the pre-commit config, as it was intended to be used.

## Code Review Verification Steps

* [ ] If the change is risky, it has been tested in experimental before merging.
* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] The requirements listed in
 [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely)
 have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://github.com/transcom/mymove/wiki/migrate-the-database#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/secure/RapidBoard.jspa?rapidView=38&modal=detail&selectedIssue=MB-5431) for this change

2020-11-17 15:32 UTC, sojeri reviewed
don't we need to separately annotate every single instance? what's to stop me tomorrow (or in 3 months) from checking in a real private key?

2020-11-17 17:52 UTC, kimallen commented on .pre-commit-config.yaml
> +        #RA: detect-private-key detected a private key, but this key is a fake key intended to be used for a local environment only.
I might add that `cli/auth.go` instance is triggered because of string interpolation.
This is the line where it is triggered: `privateKeyFormat := "-----BEGIN PRIVATE KEY-----\n%s\n-----END PRIVATE KEY-----"`

2020-11-17 18:36 UTC, amitch23 commented
> don't we need to separately annotate every single instance? what's to stop me tomorrow (or in 3 months) from checking in a real private key?

@sojeri I originally tried to bypass the keys inline in the key (ssh) files and the auth.go file, but "#nosec" is a bypass code specific to the gosec linter, so that didn't work. I failed to find information about excluding or bypassing rules for the detect-private-key pre-commit hook inline, and everything led me to the pre-commit config file "exclude" param to handle these cases. I'm happy to pair on finding another way to do it inline, or spend some more time researching today (being conscious of the goals we have for this week).

To answer your question, the thing that would stop you would be that if you did add a key and didn't modify the pre-commit config, the pre-commit hook would fail. If you then modified the pre-commit config, the codeowners rule would automatically add a necessary review from the "cATO static analysis" group, once the dangerJS PR changes go in (https://github.com/transcom/mymove/pull/5240/files), which should hopefully be enough to catch the change.

2020-11-17 18:49 UTC, jneuner-mitre requested changes
We need to be more explicit.

2020-11-17 18:49 UTC, jneuner-mitre commented on .pre-commit-config.yaml
>              config/tls/devlocal-.+\.key$|
Each of these lines needs its own risk assessment.  If multiple findings are identified by one line (e.g. the first line), make sure the assessment is correct for all of the findings.

The assessment should usually be three sentences.
RA: <Why did the linter flag this line of code?>
RA: <Why is this line of code valuable?>
RA: <What mitigates the risk of negative impact?>

2020-11-17 18:52 UTC, jneuner-mitre commented on .pre-commit-config.yaml
>              config/tls/devlocal-.+\.key$|
I added a bit more detail to the template here:
https://docs.google.com/spreadsheets/d/1eH5ZYkKv7_c-p_D_y5G5ULdWgI_Zrwg_xL4WbLNZoqw/edit#gid=1701318393

2020-11-18 02:07 UTC, amitch23 commented on .pre-commit-config.yaml
>              config/tls/devlocal-.+\.key$|
thanks @jneuner-mitre for the info. I don't think it's possible to add comments to a yaml file in the mapping block, as I tried to add risk assessments for each file/line, and am getting `InvalidConfigError`. I will look into this more tomorrow to see how we can be more granular/specific for each line while still adhering to acceptable config syntax.

2020-11-18 03:42 UTC, sojeri commented on .pre-commit-config.yaml
>              config/tls/devlocal-.+\.key$|
would it work to have a much more granular / specific regex and to annotate the group but call out each file as explicitly spelled out in the regex?

2020-11-18 18:58 UTC, jneuner-mitre commented on .pre-commit-config.yaml
>              config/tls/devlocal-.+\.key$|
@sojeri I think security types will always prefer explicit. ;)
@amitch23 If the current template doesn't work, feel free to propose an alternative way to annotate.

2020-11-18 23:30 UTC, merged

2020-11-18 23:53 UTC, amitch23 commented
I accidentally merged this PR without intending to, but am not seeing the changes in master, oddly. It seems I cannot reopen this PR, so will make a new one