Add annotation for all instances of G101
transcom/mymove pull request #5254
Opened 2020-11-17 22:38 UTC by kimallen

## Description

All occurrences of G101: Password Management: Hardcoded Password I categorized as false positives, as the linter was flagging the use of the words "token" and "secret", and they were all references to names rather than the keys/secrets themselves.

## Reviewer Notes

Is there anything you would like reviewers to give additional scrutiny?

## Setup

`pre-commit run -v --all-files golangci-lint | grep G304` and you will still see 5 occurrences.  However, all have annotation.

## Code Review Verification Steps

* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-4970) for this change

2020-11-17 22:44 UTC, sojeri commented on pkg/auth/cookie.go
>  // GorillaCSRFToken is the name of the base CSRF token
I would put this into the annotation instead of or in addition to line 41. it explains in clearer detail what's going on here.

2020-11-17 22:44 UTC, sojeri commented on pkg/cli/auth.go
> +	// ClientAuthSecretKeyFlag is the Client Auth Secret Key Flag // #nosec G101
so for all of these-- IMO this part should be in the annotation instead of or as part of line 16 here

2020-11-17 22:48 UTC, amitch23 approved these changes
apart from Jeri's comments, lgtm! (I updated the description for checking to be g101 instead of a different one ;))

2020-11-17 22:49 UTC, kimallen commented on pkg/auth/cookie.go
>  // GorillaCSRFToken is the name of the base CSRF token
I can add it in addition.  If I remove this comment, I get a complaint because it expects a comment above it.

2020-11-17 22:52 UTC, kimallen commented on pkg/auth/cookie.go
>  // GorillaCSRFToken is the name of the base CSRF token
I also had to add the line break between the annotation and the explanatory comment because it thought the first line of the annotation was the comment.

2020-11-17 23:02 UTC, sojeri commented on pkg/auth/cookie.go
>  // GorillaCSRFToken is the name of the base CSRF token
that is rude, lol. thanks golint 😅

2020-11-17 23:07 UTC, sojeri approved these changes
🚀

2020-11-18 19:22 UTC, jneuner-mitre requested changes
Applying these recommended changes to all the G101 findings in this commit and I'll concur.

2020-11-18 19:22 UTC, jneuner-mitre commented on pkg/cli/dps.go
> +	//RA: The value of this variable does not identify the actual secret, so is not a risk.
We should not assert whether something is or is not a risk.  Just state why the risk is reduced.

2020-11-18 19:22 UTC, jneuner-mitre commented on pkg/cli/dps.go
> +	//RA: The value of this variable does not identify the actual secret, so is not a risk.
```suggestion
	//RA: This variable does not store an application secret.
```

2020-11-18 19:22 UTC, jneuner-mitre commented on pkg/cli/dps.go
> +	//RA Developer Status: False Positive
The linter appears to be working correctly, so a False Positive status is incorrect.  
The finding has been assessed, and risk appears to be Mitigated because a application secret was not found.

2020-11-18 19:22 UTC, jneuner-mitre commented on pkg/cli/dps.go
> +	//RA Developer Status: False Positive
```suggestion
	//RA Developer Status: Mitigated
```

2020-11-19 15:28 UTC, jneuner-mitre approved these changes
lgtm

2020-11-19 23:02 UTC, merged