[MB-4063] TIO frontend sorting of payment requests queue
transcom/mymove pull request #5266
Opened 2020-11-18 22:02 UTC by duncan-truss

## Description

Explain a little about the changes at a high level.

## Reviewer Notes

Is there anything you would like reviewers to give additional scrutiny?

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

```sh
echo "Code goes here"
```

## Code Review Verification Steps

* [ ] If the change is risky, it has been tested in experimental before merging.
* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] The requirements listed in
 [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely)
 have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://github.com/transcom/mymove/wiki/migrate-the-database#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](tbd) for this change
* [this article](tbd) explains more about the approach used.

## Screenshots

If this PR makes visible UI changes, an image of the finished UI can help reviewers and casual
observers understand the context of the changes. A before image is optional and
can be included at the submitter's discretion.

Consider using an animated image to show an entire workflow instead of using multiple images. You may want to use GIPHY CAPTURE for this! 📸

_Please frame screenshots to show enough useful context but also highlight the affected regions._

2020-11-23 21:22 UTC, noelledusahel approved these changes
Looks good! I wish we didn't have the clunky " third click to remove sorting" functionality though

2020-11-23 22:02 UTC, amanda5iu approved these changes

2020-11-23 22:51 UTC, donaldthai approved these changes
Code looks good to me. Sorting works great!

One thing I did noticed was that on the third click of a column, the sort gets unset. According to the story, we may not want this behavior? Don't know how important it is though.

> Then that column toggles between sorting
>    ascending and descending

2020-11-23 22:58 UTC, duncan-truss commented
@noelledusahel @donaldthai Yea that is the default react-table behavior with the toggle unsetting the column.  I explored it but did not feel we had the time to implement our own toggleSort handler properly and test it.  It's definitely possible but there's a good bit going on in that TableQueue component already.

2020-11-23 23:04 UTC, sojeri requested changes
👋 hello! I am here, summoned by dangerJS because you have added a new eslint disable line. I left 3 related comments. the one I am requesting changes for is the new eslint line you've added re: unused variables. the other two I would also super appreciate if you fix now, but those fixes aren't blocking this PR since they are already known issues in the static analysis backlog.

2020-11-23 23:04 UTC, sojeri commented on src/components/Table/Table.jsx
> +                      key={`cell${index}`}
if you don't mind, I'd love to see this one fixed as well. this linter error is firing because indexes do not make good keys in react. the point of a key is to have a static ID which doesn't change when a list is reordered or when some items are removed / added. when you use an index, you're giving a dynamic value instead which potentially changes every time the list is updated in some way. you should instead pass in an object which has an immutable ID, and use that ID for the key.

this is a cat III as well.

2020-11-23 23:04 UTC, sojeri commented on src/components/Table/Table.jsx
> +                      key={`header${headerIndex}`}
this is another cat III array index as key issue. instead of a dynamic index value, this should be an immutable object id.

2020-11-23 23:06 UTC, duncan-truss commented
> 👋 hello! I am here, summoned by dangerJS because you have added a new eslint disable line. I left 3 related comments. the one I am requesting changes for is the new eslint line you've added re: unused variables. the other two I would also super appreciate if you fix now, but those fixes aren't blocking this PR since they are already known issues in the static analysis backlog.

Cthulhu has been awoken 🙈

2020-11-23 23:07 UTC, duncan-truss commented on src/components/Table/TableQueue.jsx
> +  // eslint-disable-next-line no-unused-vars
I just fixed this in another branch!

2020-11-24 00:47 UTC, sojeri approved these changes
looks like you can remove one more eslint disable line, but that's not required for merge -- just nice to have.

thanks for making a couple tweaks for me!

🚀

2020-11-24 00:47 UTC, sojeri commented on src/components/Table/Table.jsx
> +                {headerGroup.headers.map((column) => {
it won't let me comment there, but I think you can remove the linter disable line at the top of this file now. thanks for making this change! :)

2020-11-24 00:52 UTC, duncan-truss commented on src/components/Table/Table.jsx
> +                {headerGroup.headers.map((column) => {
I think I tried that and it flagged the headerGroup on line 37 (which should only ever have one row) and some others related to the page numbers which are basically indexes 🙁

2020-11-24 00:56 UTC, merged