MB-5592 | remediate & annotate g402 tls minversion linter findings
transcom/mymove pull request #5269
Opened 2020-11-18 23:35 UTC by sojeri

## Description

There are 7 total G402 TLS minversion linter findings.
- 5 are remediated in this PR by adding a minversion to the tls.Config object
- 2 are annotated in this PR, because we are actually using them to intentionally pass bad TLS versions in order to validate that we __cannot__ deploy with TLS 1.0 or 1.1.

## Reviewer Notes

This does not cover the other 4 G402's which are throwing a different warning related to insecure TLS verification. Those remaining instances will be covered in a separate PR / [jira sub-task](https://dp3.atlassian.net/browse/MB-5593).

## References

- [Jira chore](https://dp3.atlassian.net/browse/MB-5592) for this change
- [ChrisG's PR to add tls-checker](https://github.com/transcom/mymove/pull/3340), (referred to in annotations)

2020-11-19 00:53 UTC, kimallen commented on cmd/tls-checker/main.go
> +	//RA: However, this by design. The purpose of the tls-checker is to attempt to deploy the app with some
Typo: However, this **is** by design.

2020-11-19 00:55 UTC, kimallen commented on cmd/tls-checker/main.go
> +	//RA Developer Status: {RA Request, RA Accepted, POA&M Request, POA&M Accepted, **Mitigated**, Need Developer Fix, False Positive, Bad Practice}
I think it will be more clear if you just put **Mitigated** and remove the rest of the list

2020-11-19 01:04 UTC, kimallen reviewed
LGTM- just a couple minor comments.  Thanks for the clear description.  I approve, though will let Jarod click the final approve.

2020-11-19 14:57 UTC, monfresh commented
I don't know much about TLS, but I see that we are specifying that same 1.2 version in other places, like in the Redis config, so I think this should be fine.

2020-11-19 16:40 UTC, jneuner-mitre requested changes
Suggesting changes, because the finding was mostly my fault in the first place ;)

2020-11-19 16:40 UTC, jneuner-mitre commented on cmd/tls-checker/main.go
> +	//RA: - https://github.com/transcom/mymove/pull/3340
```suggestion
	//RA: The linter flagged this line of code, because we are passing in a tlsVersion which could be bad.
	//RA: The code is part of a subroutine that checks that MilMove public endpoints use TLS v1.2 or higher.
	//RA: The subroutine is executed by the MilMove pipeline, post-deployment.  It is not included in the production system.
	//RA: Related pull request... https://github.com/transcom/mymove/pull/3340
```

2020-11-19 16:40 UTC, jneuner-mitre commented on cmd/tls-checker/main.go
> +	//RA: - https://github.com/transcom/mymove/pull/3340
```suggestion
	//RA: The linter flagged this line of code, because we are passing in a tlsVersion which could be bad.
	//RA: The code is part of a subroutine that checks that MilMove public endpoints use TLS v1.2 or higher.
	//RA: This subroutine is executed by the MilMove pipeline, post-deployment.  It is not included in the production system.
	//RA: Related pull request... https://github.com/transcom/mymove/pull/3340
```

2020-11-20 13:46 UTC, jneuner-mitre approved these changes
🚀

2020-11-20 22:10 UTC, merged