Ignore dangerjs if acceptable rule
transcom/mymove pull request #5334
Opened 2020-11-24 23:18 UTC by kimallen

## Description

This adds to the dangerjs trigger for linter bypass changes.  It does not trigger a warning if the code adds certain disable rules.

## Reviewer Notes

Disables eslint rules:
    'no-underscore-dangle',
    'prefer-object-spread',
    'object-shorthand',
    'camelcase',
    'jsx-props-no-spreading',
    'destructuring-assignment',
    'forbid-prop-types',
    'prefer-stateless-function',
    'sort-comp',
    'import/no-extraneous-dependencies',
    'order',
    'prefer-default-export',
    'no-named-as-default'

## Setup

Run `yarn danger pr https://github.com/transcom/mymove/pull/5240`

## Code Review Verification Steps

* [ ] If the change is risky, it has been tested in experimental before merging.
* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] The requirements listed in
 [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely)
 have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://github.com/transcom/mymove/wiki/migrate-the-database#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](tbd) for this change
* [this article](tbd) explains more about the approach used.

## Screenshots

If this PR makes visible UI changes, an image of the finished UI can help reviewers and casual
observers understand the context of the changes. A before image is optional and
can be included at the submitter's discretion.

Consider using an animated image to show an entire workflow instead of using multiple images. You may want to use GIPHY CAPTURE for this! 📸

_Please frame screenshots to show enough useful context but also highlight the affected regions._

2020-11-25 07:25 UTC, sojeri commented on dangerfile.ts
>    let addedByPassCode = false;
I know this is still a draft, but can you update all the different bypass variables to use consistent casing? you don't have to follow this exact naming, but something like:
- `addedByPassCode` => `isBypassFound`
- `diffsWithbypassCodes` => `bypassDiffs`

2020-11-25 07:27 UTC, sojeri commented on dangerfile.ts
> +  const bypassCodes = ['eslint-disable', 'eslint-disable-next-line', '#nosec'];
doesn't have to be changed in this PR, but I'm thinking we should add a story to fail if eslint-disable is found outside of eslint-disable-next-line, because disabling the whole file can hide new issues.

2020-11-25 22:00 UTC, kimallen commented on dangerfile.ts
> +  const bypassCodes = ['eslint-disable', 'eslint-disable-next-line', '#nosec'];
Sometimes `eslint-disable` is used to disable the same line.  So we'd need to check if it was at the top of the file, somehow

2020-11-25 22:07 UTC, sojeri commented on dangerfile.ts
> +  const bypassCodes = ['eslint-disable', 'eslint-disable-next-line', '#nosec'];
I think any plain eslint-disable is for the whole file regardless of where it's placed--- even when scoped to a single type, it's still the whole file.

2020-11-26 01:15 UTC, kimallen commented on dangerfile.ts
> +  const bypassCodes = ['eslint-disable', 'eslint-disable-next-line', '#nosec'];
Ok, I see. I just check.  disabling the same line uses `eslint-disable-line`, which we are missing from the list of bypassCodes.  I'll add that.

2020-11-30 16:13 UTC, sojeri requested changes
I like where this is going, but there's a few issues in the current iteration which will either cause bugs or allow folks to slip through these new checks. I've left more detailed comments about these issues on relevant lines of code. :)

2020-12-01 00:04 UTC, kimallen commented on dangerfile.ts
> +    const bypassCodesInDiff = bypassCodes.map((b) => {
From what I understand, `find` returns only the first encounter that meets the callback criteria, and we need to know all bypass codes that occur in the diff.  I also would expect that map would only return the bypass codes of the diff that exist (returns a new array of the returned values).  It's definitely possible I'm thinking about it wrong.  Might be helpful to walk through it together.

2020-12-01 00:14 UTC, kimallen commented
I'm honestly wondering if it makes more sense, rather than spending a bunch of time on this, to just list the acceptable rules in the dangerjs message while it's just a warning, and then people can determine if they are in violation or not.

2020-12-02 21:29 UTC, kimallen commented on dangerfile.ts
> +            if (diff.diff.includes(codeValue + ' ' + okBypassRules[`${rule}`])) {
Now splitting on commas and checking against rules.

2020-12-02 23:21 UTC, kimallen commented on dangerfile.ts
> +    const bypassCodesInDiff = bypassCodes.map((b) => {
Walked through- I now understand the issue.

2020-12-03 11:47 UTC, sojeri approved these changes
❇️   ,,  ❇️ 
\\______/

I am so happy about where this ended up. I know [you had said](https://github.com/transcom/mymove/pull/5334#issuecomment-736131924) it was a lot of work, but I think this will be really helpful to MilMove eng AND it will save security reviewers a lot of time. Thanks for completely rewriting this from scratch after posting your first iteration. 🖤

I left a few small comments, but they are not blocking changes. Two of them are copy suggestions, so if you agree with my proposed language you can click them to commit directly to the branch. :)

2020-12-03 11:47 UTC, sojeri commented on dangerfile.ts
> +      prohibitedOverrideMsg = `Contains a rule that is not in the permitted eslint list. Ok rules: (\n${okBypassRules.map(
```suggestion
      prohibitedOverrideMsg = `Contains a rule that is not in the permitted eslint list. You are free to disable only: (\n${okBypassRules.map(
```

2020-12-03 11:47 UTC, sojeri commented on dangerfile.ts
> +      'Found "eslint-disable": this disables the whole file. Please specify rules if disable is permitted.';
```suggestion
      'Found `eslint-disable`. This disables the whole file, which is bad practice because it can allow security issues to slip in unnoticed. Please specify exact rules on a line by line basis, eg `eslint-disable-next-line no-underscore-dangle`.';
```

2020-12-03 11:47 UTC, sojeri commented on dangerfile.ts
> +// fn for bypassingLinterChecks
nitpick: can you remove or clarify these `fn for bypassingLinterChecks` comments? if you want to keep this context, I'd recommend creating a new file `bypassingLinterChecks.ts` with all relevant code & then import just `bypassingLinterChecks`.

2020-12-03 11:47 UTC, sojeri commented on dangerfile.ts
> +      `It looks like you are attempting to bypass a linter rule, which is not within
# 📨 📬
I LOVE THESE MESSAGES. They are so helpful and so much more specific than before! I think these will be really helpful to eng who get the dangerjs warnings.

2020-12-03 11:47 UTC, sojeri commented on dangerfile.ts
> +function checkPRHasProhibitedLinterOverride(dangerJSDiffCollection) {
if & only if it's not a huge chunk of work (maybe <15min?), can you update the signature of this fn to return the file name as well? if that's something we can do, it will make reviewing relevant changes easier. I'm thinking of this because a couple days ago the old version of this code pulled me into a 90-file review. having the offending file name would have made that a lot easier -- both for reviewer & the dev who first reads the dangerjs warning.

if it's a large amount of work, I can create a chore for it and we can do it later.

2020-12-03 11:48 UTC, sojeri commented on dangerfile.ts
> +function checkPRHasProhibitedLinterOverride(dangerJSDiffCollection) {
also if you do this & want a new review of those changes--- please rerequest my review or at mention me. either should trigger a github notification for me. :)

2020-12-03 18:38 UTC, kimallen commented on dangerfile.ts
> +    if (bypassCodesInDiff.length > 0) {
resolving because no longer relevant due to giant refactor. . .

2020-12-03 18:38 UTC, kimallen commented on dangerfile.ts
> +              break;
no longer relevant-- refactored

2020-12-03 18:42 UTC, kimallen commented on dangerfile.ts
> +// fn for bypassingLinterChecks
aah, yes, that would be a better way.  I was feeling like all my functions were making the dangerjs file really cluttered and harder to read, hence the clarifying comments.

2020-12-03 18:44 UTC, kimallen commented on dangerfile.ts
> +// fn for bypassingLinterChecks
I like the idea of putting stuff into a new file, but also don't want to clutter the project root with it.  Anywhere else you see it being a fitting place for it?

2020-12-03 21:52 UTC, sojeri commented on dangerfile.ts
> +// fn for bypassingLinterChecks
ah, yeah. you could add a new danger/ subdir like we have cypress?

2020-12-03 22:42 UTC, kimallen commented on dangerfile.ts
> +function checkPRHasProhibitedLinterOverride(dangerJSDiffCollection) {
Ok, I spent more time than I should have, and ran into a blocker, though I mostly know what I'd do to implement it.  We should create a story for it.

2020-12-03 22:43 UTC, kimallen commented on dangerfile.ts
> +        if (hasBypass) {
outdated with refactor

2020-12-04 17:23 UTC, merged