[MB-4237] Homepage move code
transcom/mymove pull request #5350
Opened 2020-11-25 18:33 UTC by Ronolibert

## Description

Adds the move code to then homepage and does some slight styling to accommodate for mobile and desktop

## Reviewer Notes
- I wanted to refactor a bit, but there is also a CustomerHeader component that I think we could make use of in the near future

## Setup
`make server_run`
`make client_run`
1. Log in
2. Set up a move
3. Submit a move
Expected result: Homepage should have move locator and the views should be different in desktop and mobile

## Code Review Verification Steps
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-4237) for this change

## Screenshots

![image](https://user-images.githubusercontent.com/13622298/100268269-98d15980-2f09-11eb-857a-9b02f5e98f55.png)

![image](https://user-images.githubusercontent.com/13622298/100268286-9f5fd100-2f09-11eb-8458-a11ee4a393f4.png)

2020-11-25 20:07 UTC, mariaclaratgolfo commented
Desktop will need some changes to reflect the [proposed design](https://zpl.io/29r7YKz)
The layout on desktop is meant to mimic that in the TOO experience. It should utilize [this component](https://storybook.dp3.us/?path=/story/components-headers-customer-header--customer) 

- Current duty station, destination duty station and report by date should be displayed horizontally in a data format [vs. conversational format on mobile]

- Padding and font rules should match the component

2020-11-25 20:14 UTC, mariaclaratgolfo requested changes
Added notes in comment

2020-11-25 20:36 UTC, Ronolibert commented
@mariaclaratgolfo Migrating to the new customer header will be done in https://dp3.atlassian.net/browse/MB-5720

2020-11-25 20:50 UTC, lynzt approved these changes
I see the `move code` on the home screen after submitting a move
🚢

2020-11-25 20:51 UTC, sojeri requested changes
left a few small comments about using more semantic HTML and styles.

2020-11-25 20:51 UTC, sojeri commented on src/pages/MyMove/Home/Home.module.scss
> +    margin-top: 12px;
just double checking my understanding here: don't we have unit measures that we prefer to use in styles like this rather than using raw pixel amounts?

2020-11-25 20:51 UTC, sojeri commented on src/pages/MyMove/Home/Home.module.scss
> +        display: inline-block;
why do we need all these inline-block styles? would it make more sense to use display: flex here?

2020-11-25 20:51 UTC, sojeri commented on src/pages/MyMove/Home/index.jsx
> +            <div>Weight allowance</div>
it would be more semantic to have this be a p tag containing the strong element.

in addition, the top level p tag (line 198) seems like it'd be better off as a fragment with the first three lines wrapped still in a p

2020-11-25 20:51 UTC, sojeri commented on src/pages/MyMove/Home/index.jsx
> +              <div>Move code</div>
same comment here re: semantic HTML and p containing strong

2020-11-25 21:06 UTC, suzubara requested changes
+1 to @sojeri 's comments about the HTML structure. I know the plan is to refactor this and use the Customer header component eventually, but it would be good to resolve the DOM errors at least.

2020-11-25 21:06 UTC, suzubara commented on src/pages/MyMove/Home/Home.module.scss
> +        display: inline-block;
I agree, display flex seems better to use here. also, is there a reason to have distinct classes for `subheaderWeightAllowance` and `subheaderMoveCode`? it seems like they could use a more generic subheader class

2020-11-25 21:06 UTC, suzubara commented on src/pages/MyMove/Home/index.jsx
> +            <div>Weight allowance</div>
agreed, there are a lot of invalid DOM nesting errors in the console when I view this page (divs not allowed inside p, for example)

2020-11-25 21:11 UTC, Ronolibert commented on src/pages/MyMove/Home/Home.module.scss
> +    margin-top: 12px;
Yup, I'll use the em value instead. Forgot about this since design didn't have the purple boxes just the raw pixel value

2020-11-25 23:05 UTC, mariaclaratgolfo approved these changes

2020-11-26 10:23 UTC, Ronolibert commented
@sojeri @suzubara Thanks! Rushed a bit too much on this, simplified the HTML/CSS and used more semantic HTML

2020-11-30 16:13 UTC, sojeri reviewed
the HTML looks a lot better now! left one more comment about the last trailing DOM issue :)

2020-11-30 17:33 UTC, suzubara approved these changes
Adding to this PR since @Ronolibert is OOO. I updated the markup & used `dl` and also re-organized the CSS a little to not use any max-width media queries. need to add my own approval since I had requested changes earlier.

2020-11-30 19:08 UTC, sojeri approved these changes
🚀

2020-11-30 20:05 UTC, merged