annotate all remaining g402s
transcom/mymove pull request #5368
Opened 2020-11-30 19:58 UTC by sojeri

## Description

Add annotations for all remaining G402s. The reason we want to keep all these remaining insecure verify bools is we are only setting them to true during local development / for local testing.

### Useful historical references

- [PR in which the prime API side was added](https://github.com/transcom/mymove/pull/3395)
- [PR in which the webhook client was added](https://github.com/transcom/mymove/pull/4531)

## Reviewer Notes

How is the phrasing? Should we include those doc refs or refs to the above PRs in the annotation?

## Other references

- [Jira story](https://dp3.atlassian.net/browse/MB-5593)

2020-11-30 21:56 UTC, lynzt reviewed
I see where we're initing this, but not the actual value coming in... Where are we actually passing this in?

2020-11-30 21:56 UTC, lynzt commented on cmd/prime-api-client/utils/connection.go
>  			InsecureSkipVerify: insecure,
where are we setting this value?

2020-11-30 23:23 UTC, sojeri commented on cmd/prime-api-client/utils/connection.go
>  			InsecureSkipVerify: insecure,
if you refer to the docs linked in the annotation, you'll see it gets passed through as a CLI arg. you can also chase "insecure" and "InsecureFlag" through the codebase if you want to see the whole flow.

- [Doc link 1 from annotations (official prime API docs)](https://github.com/transcom/prime_api_deliverable/wiki/Getting-Started#run-prime-api-client)
- [Doc link 2 from annotations (transcom/mymove wiki)](https://github.com/transcom/mymove/wiki/How-to-Test-the-Prime-API-(Local,-Staging,-and-Experimental)#testing-locally)

2020-11-30 23:41 UTC, kimallen commented on cmd/prime-api-client/utils/connection.go
>  			InsecureSkipVerify: insecure,
I'm seeing that.  I can approve since Lindsay is out for the day.

2020-11-30 23:41 UTC, kimallen approved these changes
Approved- I see where the flag is passed

2020-12-01 15:32 UTC, jneuner-mitre requested changes
Please add the RA Developer Status before merging.  It tremendously helps us to understand the dev position when we drop into the PR.  Otherwise, lgtm!

2020-12-01 22:16 UTC, jneuner-mitre approved these changes
Thanks for fixing up the statuses!

2020-12-01 22:45 UTC, merged