MB-5052: Update chamber references
transcom/mymove pull request #5420
Opened 2020-12-07 21:09 UTC by mdawn

## [Update Chamber Refs](https://dp3.atlassian.net/browse/MB-5052)

- forces use of `transcom-gov-dev` to call for chamber vars in `.envrc`

## Reviewer Notes

No terraform changes

2020-12-07 23:12 UTC, kilbergr requested changes

2020-12-07 23:12 UTC, kilbergr commented on .envrc
> +require LOGIN_GOV_SECRET_KEY "See 'AWS_REGION=us-gov-west-1 aws-vault exec transcom-gov-dev -- chamber read app-devlocal login_gov_secret_key'"
```suggestion
require LOGIN_GOV_SECRET_KEY "See 'DISABLE_AWS_VAULT_WRAPPER=1 AWS_REGION=us-gov-west-1 aws-vault exec transcom-gov-dev -- chamber read app-devlocal login_gov_secret_key'"
```
You'll need to add `DISABLE_AWS_VAULT_WRAPPER=1` to all of these before the region.

2020-12-07 23:22 UTC, mdawn commented on .envrc
> +require LOGIN_GOV_SECRET_KEY "See 'AWS_REGION=us-gov-west-1 aws-vault exec transcom-gov-dev -- chamber read app-devlocal login_gov_secret_key'"
oof copy🍝  no good. fixing.

2020-12-08 13:13 UTC, kilbergr approved these changes
I would love you to verify with an app eng before you landed. Otherwise, LGTM. Thank you!

2020-12-08 16:42 UTC, kilbergr requested changes
Sorry going back on my approval 😭 Please update the README.

2020-12-08 16:44 UTC, mdawn commented
> Sorry going back on my approval 😭 Please update the README.

Since I'm the one that pointed out I should probably still update the README, I find this a very reasonable request... 😝

2020-12-09 16:06 UTC, mdawn commented
> I would love you to verify with an app eng before you landed. Otherwise, LGTM. Thank you!

✅  https://ustcdp3.slack.com/archives/CP6PTUPQF/p1607443805469500

2020-12-09 23:11 UTC, mdawn commented
Well I did a little of updating the readme but it seems [MB-5053 is the real ticket for updating the readme](https://dp3.atlassian.net/browse/MB-5053) so I'm going to stop here.

2020-12-09 23:16 UTC, carterjones approved these changes

2020-12-10 15:16 UTC, kilbergr approved these changes
Usually I believe that docs should be updated as changes are made and would expect the discrete chamber references in the README to be updated in this ticket.
The reason I made the other ticket was that we were going to have to ask app-eng to change what they were doing (not only help new people get on). 
BUT I think you're justified in this case since the other ticket exists, and that I'm getting in my own way. This has been dragged out long enough. 
Thank you for tackling!

2020-12-10 15:29 UTC, merged