[MB-5737] add cli to hide mtos
transcom/mymove pull request #5437
Opened 2020-12-08 22:23 UTC by pearl-truss

## Description

This PR introduces a new command support-hide-mto to hide moves not using fake data

## Reviewer Notes

Any reviewer that has a CAC can test this in experimental. Just let me know when you're ready to do so and I can deploy to experimental. Or alternatively, anyone else can also do this. 

I added steps below on how to test both locally and on experimental 

## Setup

```sh
make db_dev_e2e_populate && make server_run
```

Locally 
```sh
prime-api-client --insecure support-hide-non-fake-mtos
```

Experimental (once deployed https://github.com/transcom/mymove/wiki/deploy-to-experimental)
```sh
prime-api-client  --cac --hostname api.exp.move.mil --port 443  support-hide-mtos | jq 
```

2020-12-10 00:02 UTC, gidjin commented
> Experimental (once deployed https://github.com/transcom/mymove/wiki/deploy-to-experimental)
> 
> ```shell
> prime-api-client  --cac --hostname api.exp.move.mil --port 443  support-hide-mtos | jq 
> ```

Should this second command also be `support-hide-non-fake-mtos` vis `support-hide-mtos`?

2020-12-10 00:30 UTC, gidjin reviewed
Code looks good and confirmed it works locally, it hide all moves as expected. I created 2 moves one with valid fake data one with invalid and it hid just the invalid one as expected. I can test this on exp as well. I'll approve once that's done unless someone else can before me

2020-12-10 08:42 UTC, gidjin requested changes
Okay so I ran this in exp and had a failure I'll slack you the log trace. From what I can tell from the log trace `pkg/handlers/supportapi/internal/payloads/model_to_payload.go` line 39 is where the failure came from and seems to indicate that the ContractorID is nil for some of the records, which could be for some old data. Since this is likely true in staging as well I'm thinking we need to handle the error in the handler at least. What are your thoughts on this @pearl-truss ?

2020-12-10 15:49 UTC, pearl-truss commented
> Okay so I ran this in exp and had a failure I'll slack you the log trace. From what I can tell from the log trace `pkg/handlers/supportapi/internal/payloads/model_to_payload.go` line 39 is where the failure came from and seems to indicate that the ContractorID is nil for some of the records, which could be for some old data. Since this is likely true in staging as well I'm thinking we need to handle the error in the handler at least. What are your thoughts on this @pearl-truss ?

This is ready for review again. I updated the handler to nil check the ContractorID

2020-12-11 16:05 UTC, jacquelineIO commented on pkg/handlers/supportapi/move_task_order.go
> +			return movetaskorderops.NewHideNonFakeMoveTaskOrdersConflict().WithPayload(payloads.ClientError(handlers.ConflictErrMessage, "ContractorID must be present on the MTO", h.GetTraceID()))
@pearl-truss @gidjin Do we really want to error out here? I don't think this is really our concern. I would think we should put out a warning message, but doesn't seem like this is a reason for this code to error out. I would think to skip it and continue if possible, but if this isn't possible then I guess that is a reason why.

2020-12-11 16:25 UTC, gidjin commented on pkg/handlers/supportapi/move_task_order.go
> +			return movetaskorderops.NewHideNonFakeMoveTaskOrdersConflict().WithPayload(payloads.ClientError(handlers.ConflictErrMessage, "ContractorID must be present on the MTO", h.GetTraceID()))
I don't think we want to error out, I think we want to continue, since there wouldn't be much we could do in this case. Currently it threw an error even though moves were hidden. Is it possible to catch the error and still render a json response of the moves affected?

2020-12-11 16:32 UTC, pearl-truss commented on pkg/handlers/supportapi/move_task_order.go
> +			return movetaskorderops.NewHideNonFakeMoveTaskOrdersConflict().WithPayload(payloads.ClientError(handlers.ConflictErrMessage, "ContractorID must be present on the MTO", h.GetTraceID()))
Okay, kind of combining the 2 meesages, it sounds like we want to

-  Check if the ContractorID is nil, and log a warning message 
- Return all MTOs that had fake data, minus the ones missing a contractorID

2020-12-11 17:55 UTC, gidjin approved these changes
The changes look good, tested locally by changing a move with unapproved fake data to have a null contractor id and there were no errors running and the move with the null contractor id was marked `show == f`

2020-12-11 20:42 UTC, merged