Mb 4361 upgrade storybook
transcom/mymove pull request #5438
Opened 2020-12-09 00:13 UTC by kimallen

## Description

Upgrades storybook from v5.3.19 to v6.1.10.

Changes include the following:
- Moves configurations into main.js (removes addons.js)
- Replaces `@storybook/addons-info` with `@storybook/addons-docs`
- Removes use of decorator `withKnob` which is now automatically added as a preset
- Adds `@storybook/essentials`
- Adds `@storybook/preset-create-react-app`
- Upgrades hierarchy separators to use `/` instead of `|`
- Replaces use of storiesOf with component story format

## Reviewer Notes

I'm not seeing any errors when running storybook.  Anything I missed?  Many of the "best practice" items in https://storybook.js.org/blog/storybook-6-migration-guide/ were covered in the green check changes.

## Setup

```sh
yarn storybook
```

## Code Review Verification Steps

* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-4361) for this change
* [this article](https://storybook.js.org/blog/storybook-6-migration-guide/) explains more about the approach used.

2020-12-09 00:25 UTC, Shkeating approved these changes

2020-12-09 16:03 UTC, Shkeating commented
I just noticed, while I do see storybook is successfully updated, that it seems that Public Sans is not getting loaded into storybook, and it is substituting Times! See here:
<img width="592" alt="image" src="https://user-images.githubusercontent.com/59394696/101654086-1919b380-3a0e-11eb-96a9-5b6e1b59c6a5.png">
<img width="596" alt="image" src="https://user-images.githubusercontent.com/59394696/101654112-2171ee80-3a0e-11eb-83d4-93c29a16cfb6.png">

2020-12-09 17:33 UTC, suzubara requested changes
The stories files look fine, but I think there's some additional things that need to be changed or added in the config (and we should remove `babel-loader` from package.json)

2020-12-09 17:33 UTC, suzubara commented on package.json
> +    "babel-loader": "^8.2.2",
why was this added? It looks like it is conflicting with the CRA version and causing test failures

2020-12-09 17:33 UTC, suzubara commented on package.json
> +    "@storybook/addon-essentials": "^6.1.10",
it looks like since we're adding `addon-essentials`, we can remove the included addons from `package.json` and the Storybook config: Actions, Docs, Viewport

2020-12-09 17:33 UTC, suzubara commented on .storybook/addons.js
> -import 'storybook-addons-abstract/register';
it looks like the Abstract addon didn't make it into the new config

2020-12-09 17:33 UTC, suzubara commented on .storybook/config.js
> -
it looks like some of these imports didn't make it over. from reading the migration guide for `main.js`, I think we need to add a `.storybook/preview.js` file that includes the following:

```
import 'happo-plugin-storybook/register';	

import './storybook.scss';	
import '../src/index.scss';	
import '../src/ghc_index.scss';	

import '../src/icons';
```

2020-12-09 17:33 UTC, suzubara commented on src/components/CustomerRemarksAgentsDetails/customerRemarksAgentsDetails.stories.jsx
> +  title: 'TOO/TIO Components/CustomerRemarksAgentsDetails',
It looks like that due to the new hierarchy separator, naming this section `TOO/TIO` is resulting in this:
![image](https://user-images.githubusercontent.com/2723066/101664905-fe493e00-3a11-11eb-9191-4e74e98cc0dc.png)


I'd recommend renaming to "Office Components" anyways..

2020-12-09 17:34 UTC, kimallen commented on package.json
> +    "babel-loader": "^8.2.2",
I added it because it was failing on not being able to find it, and that made it work.  Sounds like it should be a different approach.

2020-12-09 17:36 UTC, kimallen commented on src/components/CustomerRemarksAgentsDetails/customerRemarksAgentsDetails.stories.jsx
> +  title: 'TOO/TIO Components/CustomerRemarksAgentsDetails',
aah, good find. Will do.

2020-12-09 17:51 UTC, kimallen commented on package.json
> +    "@storybook/addon-essentials": "^6.1.10",
The addon-docs in `main.js` is a little more specific- should I still remove that too?
```{
      name: '@storybook/addon-docs',
      options: {
        configureJSX: true,
      },
    },```

2020-12-09 19:42 UTC, kimallen commented on .storybook/config.js
> -
Done

2020-12-14 17:17 UTC, suzubara approved these changes

2020-12-14 17:56 UTC, merged

2020-12-14 18:16 UTC, kimallen commented
> I just noticed, while I do see storybook is successfully updated, that it seems that Public Sans is not getting loaded into storybook, and it is substituting Times! See here:
> <img alt="image" width="592" src="https://user-images.githubusercontent.com/59394696/101654086-1919b380-3a0e-11eb-96a9-5b6e1b59c6a5.png">
> <img alt="image" width="596" src="https://user-images.githubusercontent.com/59394696/101654112-2171ee80-3a0e-11eb-83d4-93c29a16cfb6.png">

FIXED!  I missed some imports-  This is fixed through the imports in `preview.js`