MB-5808: deploy the webhook-client container to ecs
transcom/mymove pull request #5481
Opened 2020-12-12 01:12 UTC by carterjones

## Description

This creates the framework by which new versions of the webhook-client container can be released to the webhook-client task on the ECS cluster.

## Setup

This is entirely run in CircleCI, so you test this code via pull requests.

## Code Review Verification Steps

* [ ] If the change is risky, it has been tested in experimental before merging.
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-5808) for this change

## Screenshots

If this PR makes visible UI changes, an image of the finished UI can help reviewers and casual
observers understand the context of the changes. A before image is optional and
can be included at the submitter's discretion.

Consider using an animated image to show an entire workflow instead of using multiple images. You may want to use GIPHY CAPTURE for this! 📸

_Please frame screenshots to show enough useful context but also highlight the affected regions._

2021-01-29 12:11 UTC, esacteksab reviewed
Nothing stood out, but definitely get more eyes on this. Nice work!

2021-01-29 16:01 UTC, travelar approved these changes
Concur with Barry. More eyes would be great.

2021-01-29 18:05 UTC, shimonacarvalho commented on cmd/webhook-client/utils/connection.go
> +
I wouldn't take out the option to use paths here. We will need it when we test locally with prime's cert/key.
Is there any problem with keeping the certpath/keypath option in?

2021-01-29 18:08 UTC, carterjones commented on cmd/webhook-client/utils/connection.go
> +
The problem I encountered was that with the default of a path, it would end up failing unless I explicitly set the path to be an empty string. This makes me wonder: would it be a problem if I changed the default path to be an empty string?

2021-01-29 18:11 UTC, shimonacarvalho commented on cmd/webhook-client/main.go
> +	var session *awssession.Session
I think this should be either paths or keys. Looks like there was a bug there, but I wouldn't remove it totally.
I would fix it so it essentially says, we either need to find CertPathFlag+CertKeyFlag OR we need to find the RecipientMTLSCert+RecipientMTLSKey.

2021-01-29 18:13 UTC, shimonacarvalho commented on cmd/webhook-client/utils/shared.go
>  const (
Again, would like to keep this option

2021-01-29 18:18 UTC, shimonacarvalho requested changes
I'd like to keep the path option available for us to use locally for debug, so please put that back in.

Also is this going on staging after you merge it in? Seems like that would be the case? It is not quite ready to go on staging, we need to test a few more things. And clear staging of all the pending notifications. The slice goal was to get it working in experimental. 

Also was this pr able to send a notification to a live mtls server?

2021-01-29 18:21 UTC, shimonacarvalho commented on cmd/webhook-client/utils/connection.go
> +
Ah i see. yeah try that. Since in a way we are trying to default to using the env variables.

2021-01-29 18:23 UTC, carterjones commented on cmd/webhook-client/utils/connection.go
> +
Will do. I'll get a fix in for that.

2021-01-29 18:23 UTC, carterjones commented on cmd/webhook-client/main.go
> +	var session *awssession.Session
Good call. I'll get a fix in for that.

2021-01-29 18:24 UTC, carterjones commented
Thanks for the review! I'll get those fixes in.

No, this is not going to be deployed to staging. This only will be deployed to experimental. No tasks/jobs are defined for staging or prod for the webhook client.

2021-01-30 00:00 UTC, carterjones commented on cmd/webhook-client/utils/connection.go
> +
I performed the revert in 53f4fd6818cd7728e98d979e2c299a4d8792ae6f. I set the default paths to empty strings in aa3609fbec530794fb404c389450132e6bcc216f.

2021-01-30 00:00 UTC, carterjones commented on cmd/webhook-client/main.go
> +	var session *awssession.Session
I improved the logic with d01607eccced8e7abb0dab366b5def57769c6c1d. I did some testing for it, which I added to the description for this PR.

2021-01-30 00:03 UTC, carterjones commented
I made some updates, successfully got the webhook client running in exp against the exp API server _and_ in another draft PR got it working where it is running in experimental, but interacting successfully with the API server in staging.

Here is a link to compare the content of the most recent commits (excluding the merge of master and the deployment commit for testing in this PR): https://github.com/transcom/mymove/compare/53f4fd6818cd7728e98d979e2c299a4d8792ae6f...0c2b4a2da8dc29e34e2b82769102f52f30d4805b

2021-02-01 21:07 UTC, shimonacarvalho commented on cmd/webhook-client/main.go
> +	var session *awssession.Session
Looks good to me.

2021-02-01 21:08 UTC, shimonacarvalho approved these changes
This is for the go code changes in webhook-client.

2021-02-01 21:38 UTC, travelar commented on config/tls/dod-root-ca-3.cer
> +-----BEGIN CERTIFICATE-----
This certificate already exists in Certificates_PKCS7_v5.6_DoD.der.p7b. Do we need redundancy?

2021-02-01 21:38 UTC, travelar commented on config/tls/dod-sw-ca-60.cer
> +-----BEGIN CERTIFICATE-----
This certificate already exists in Certificates_PKCS7_v5.6_DoD.der.p7b. Do we need redundancy?

2021-02-01 23:23 UTC, carterjones commented on config/tls/dod-root-ca-3.cer
> +-----BEGIN CERTIFICATE-----
It looks like we don't. I managed to get it working with 7cfa3078c869f77da911d64a3d0b11575caff7b5 and tested it in https://github.com/transcom/mymove/pull/5802 by deploying to experimental and causing the webhook client send an API request to the staging API server. It returned a 200 OK, indicating that this approach of using the pre-existing certificate bundle works.

2021-02-01 23:23 UTC, carterjones commented on config/tls/dod-sw-ca-60.cer
> +-----BEGIN CERTIFICATE-----
It looks like we don't. I managed to get it working with 7cfa3078c869f77da911d64a3d0b11575caff7b5 and tested it in https://github.com/transcom/mymove/pull/5802 by deploying to experimental and causing the webhook client send an API request to the staging API server. It returned a 200 OK, indicating that this approach of using the pre-existing certificate bundle works.

2021-02-02 19:08 UTC, travelar commented on config/tls/dod-root-ca-3.cer
> +-----BEGIN CERTIFICATE-----
Groovy.

2021-02-02 19:13 UTC, merged