MB-4393 | Removing AWS_PROFILE from .envrc
transcom/mymove pull request #5490
Opened 2020-12-14 19:37 UTC by esacteksab

## Description

Removes the last remaining reference to AWS commercial. No impact expected as previous efforts worked around this.

## Reviewer Notes

_All_ the things! 

* [MB-4393](https://dp3.atlassian.net/browse/MB-4393) for this change

2020-12-14 19:47 UTC, travelar approved these changes
🚨

2020-12-14 21:26 UTC, kilbergr reviewed
Ok I'm being a little horrible in this PR bc it's total insider knowledge, but with this happening, I think you should move line 184/182 (export AWS_DEFAULT_REGION="us-gov-west-1") OUT of the conditional since we will henceforth be using exclusively govcloud, right? And all the scripts do expect the default region, I'm finding. What do you think?

2020-12-15 15:57 UTC, kilbergr requested changes
In fact, I'm going to block on my comment as I think it is necessary. Happy to walk thru if it doesn't make sense to you/you have objections.

2020-12-17 13:54 UTC, esacteksab commented
> In fact, I'm going to block on my comment as I think it is necessary. Happy to walk thru if it doesn't make sense to you/you have objections.

Let me know if I captured what you were hoping to achieve.

2020-12-17 14:47 UTC, kilbergr commented on .envrc
> -  export AWS_S3_REGION="us-gov-west-1"
Sorry--I think we should leave the S3 region in the conditional, but move the default region out.

2020-12-17 15:01 UTC, esacteksab commented on .envrc
> -  export AWS_S3_REGION="us-gov-west-1"
I'm curious why.

2020-12-17 15:36 UTC, kilbergr commented on .envrc
> -  export AWS_S3_REGION="us-gov-west-1"
Oh sure--because I believe S3 region is only being used when we set the STORAGE_BACKEND to S3, whereas the AWS_DEFAULT_REGION is being used by a bunch of other scripts unrelated to the STORAGE_BACKEND. Make sense?

2020-12-17 15:41 UTC, esacteksab commented on .envrc
> -  export AWS_S3_REGION="us-gov-west-1"
It does. Thank you.

2020-12-17 16:02 UTC, kilbergr approved these changes
🥇

2021-02-09 13:52 UTC, merged