[MB-5920] Redux Refactor: Moves & MTOShipments (read)
transcom/mymove pull request #5497
Opened 2020-12-15 21:04 UTC by suzubara

## Description

Explain a little about the changes at a high level.

## Reviewer Notes

Is there anything you would like reviewers to give additional scrutiny?

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

```sh
echo "Code goes here"
```

## Code Review Verification Steps

* [ ] If the change is risky, it has been tested in experimental before merging.
* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] The requirements listed in
 [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely)
 have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://github.com/transcom/mymove/wiki/migrate-the-database#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](tbd) for this change
* [this article](tbd) explains more about the approach used.

## Screenshots

If this PR makes visible UI changes, an image of the finished UI can help reviewers and casual
observers understand the context of the changes. A before image is optional and
can be included at the submitter's discretion.

Consider using an animated image to show an entire workflow instead of using multiple images. You may want to use GIPHY CAPTURE for this! 📸

_Please frame screenshots to show enough useful context but also highlight the affected regions._

2020-12-17 18:47 UTC, suzubara commented
re: the dangerJS lint warning, I think is a false positive. the only eslint disables I added were `camelcase` & `import/prefer-default-export` which are on the allowed list

2020-12-18 19:00 UTC, Ronolibert commented on src/components/Customer/Review/Summary/index.jsx
> +  selectServiceMemberFromLoggedInUser,
Love the standardization of the naming convention!

2020-12-18 19:08 UTC, Ronolibert requested changes
Had a more philosophical question I guess. I notice everything has normalize set to false, what situations would we and would we not want to normalize the data?

2020-12-18 19:49 UTC, Ronolibert approved these changes
Makes sense! Everything works the same and changes look good! So much change of old cold, so cathartic. Really like how everything is organized

2020-12-18 22:23 UTC, lynzt approved these changes
LGTM.. based on the pr walk thru, i'm good. 
I didn't have time to run it but I see you got a 👍 from Ron, so 🚢

2020-12-18 22:30 UTC, merged