[MB-5550] Use map instead of slice for EDI segments
transcom/mymove pull request #5510
Opened 2020-12-18 02:15 UTC by mboren

## Description

I modified the `Invoice858C` struct to use maps instead of slices to hold segments.

Previously, we have used slices to hold segments in [ghc_payment_request_generator.go](https://github.com/transcom/mymove/blob/master/pkg/services/invoice/ghc_payment_request_invoice_generator.go).
  This created unit tests that had to reference slices at specific indices, which made writing and updating tests annoying.
 It also leaves us with errors from the validator that reference `edi.Header[9] Missing Name` which is hard to debug.   Using a map instead of a slice allows the validator to use a more descriptive key in error messages.

## Reviewer Notes
- I haven't touched `Invoice858C.ServiceItems` yet, waiting to make sure that we like the library
- I was able to get the validation to work with linkedhashmap, but I'm not sure I went about it in the best way, I was kind of flailing around until something worked.
- Is there anything additional I need to do to add the new dependency? 
## Setup

## Code Review Verification Steps

* [ ] If the change is risky, it has been tested in experimental before merging.
* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] The requirements listed in
 [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely)
 have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://github.com/transcom/mymove/wiki/migrate-the-database#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-5550)
* [new map library](https://github.com/emirpasic/gods#linkedhashmap)

_Please frame screenshots to show enough useful context but also highlight the affected regions._

2020-12-23 20:50 UTC, gidjin requested changes
Changes look good. I don't think it's worth adding more reflection at this point either, so you can leave the inefficiency of Size and NonEmptySegments. Thanks for improving the generator test too. I'm marking this as Request Changes because of the change in some ConflictError's to BadDataErrors.

2020-12-23 20:50 UTC, gidjin commented on pkg/edi/invoice/generator_test.go
> +N9*1W*Leo, Spacemen**
I can confirm that the extra `*`'s at the end are optional when the data in those fields is omitted. However, the way our code generates the EDI ti would be a pain to take them out.

2020-12-23 20:50 UTC, gidjin commented on pkg/services/invoice/ghc_payment_request_invoice_generator.go
> -func (g ghcPaymentRequestInvoiceGenerator) createG62Segments(paymentRequestID uuid.UUID) ([]edisegment.Segment, error) {
Since this method is modifying the header that is passed in, is there any reason to still return the slice of segments vs just an error?

2020-12-23 20:50 UTC, gidjin commented on pkg/services/invoice/ghc_payment_request_invoice_generator.go
> +		return services.NewBadDataError("Invalid Order, must have NewDutyStation")
Should remain ConflictError as above

2020-12-23 20:50 UTC, gidjin commented on pkg/services/invoice/ghc_payment_request_invoice_generator.go
> +		return services.NewBadDataError(fmt.Sprintf("no rank found for ServiceMember ID: %s Payment Request ID: %s", serviceMember.ID, paymentRequestID))
Should be ConflictError as above

2020-12-23 20:50 UTC, gidjin commented on pkg/services/invoice/ghc_payment_request_invoice_generator.go
> +		return services.NewBadDataError(fmt.Sprintf("no branch found for ServiceMember ID: %s Payment Request ID: %s", serviceMember.ID, paymentRequestID))
Should be ConflictError as above

2020-12-23 20:50 UTC, gidjin commented on pkg/services/invoice/ghc_payment_request_invoice_generator.go
> +		return services.NewBadDataError("Invalid Order, must have OriginDutyStation")
This should remain a ConflictError not a BadDataError. BadData implies the prime sent in data that was bad, but this is a case where data in the system won't allow us to continue. See this doc for details https://github.com/transcom/mymove/wiki/API-Errors#error-types-and-error-responses

2020-12-23 20:50 UTC, gidjin commented on pkg/services/invoice/ghc_payment_request_invoice_generator.go
> +		return services.NewBadDataError("Invalid Order, must have OriginDutyStation")
Should remain ConflictError as above

2020-12-23 23:14 UTC, mboren commented on pkg/services/invoice/ghc_payment_request_invoice_generator.go
> +		return services.NewBadDataError("Invalid Order, must have NewDutyStation")
Thanks for catching these, I was using macros for a lot of these repetitive changes and this slipped by me.

2020-12-23 23:41 UTC, mboren commented on pkg/services/invoice/ghc_payment_request_invoice_generator.go
> -func (g ghcPaymentRequestInvoiceGenerator) createG62Segments(paymentRequestID uuid.UUID) ([]edisegment.Segment, error) {
No reason at all, I'll fix that

2020-12-28 17:24 UTC, gidjin approved these changes
Thanks for making updates! LGTM

2020-12-28 17:53 UTC, merged