[MB-3912] Drop unused confirmation_number column, replace with move code in payloads
transcom/mymove pull request #5552
Opened 2020-12-29 17:50 UTC by duncan-truss

…yloads

## Description

Explain a little about the changes at a high level.

## Reviewer Notes

Is there anything you would like reviewers to give additional scrutiny?

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

```sh
echo "Code goes here"
```

## Code Review Verification Steps

* [ ] If the change is risky, it has been tested in experimental before merging.
* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] The requirements listed in
 [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely)
 have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://github.com/transcom/mymove/wiki/migrate-the-database#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](tbd) for this change
* [this article](tbd) explains more about the approach used.

## Screenshots

If this PR makes visible UI changes, an image of the finished UI can help reviewers and casual
observers understand the context of the changes. A before image is optional and
can be included at the submitter's discretion.

Consider using an animated image to show an entire workflow instead of using multiple images. You may want to use GIPHY CAPTURE for this! 📸

_Please frame screenshots to show enough useful context but also highlight the affected regions._

2020-12-29 21:27 UTC, shimonacarvalho requested changes
Hey Duncan, I think the support.yaml is using `locator` for this field. To make it all consistent once and for all, could you possibly change that to match the prime.yaml. 

Also if `moveCode` is to be generated by milmove not requested by the caller, could you set it to be `readOnly` in the supportapi.

2020-12-29 21:35 UTC, shimonacarvalho commented on pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
> +	}
Hmm this makes me think, can there be more than 1 move? If so, is there a better way to select the right one? For e.g. not a cancelled move.

2020-12-29 21:39 UTC, duncan-truss commented on pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
> +	}
Yea I mentioned that in the reviewer notes that it is in practice a 1:1 relation to my knowledge. The moves are sorted by created_at descending on the orders model so if it were possible to get more than one then we'd be getting the most recent 🤷‍♂️.

2020-12-29 21:41 UTC, Ryan-Koch approved these changes

2020-12-29 22:43 UTC, shimonacarvalho commented on pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
> +	}
Oh! Okay great.

2020-12-29 23:23 UTC, donaldthai approved these changes
Works and LGTM

2020-12-30 18:27 UTC, shimonacarvalho requested changes

2020-12-30 18:27 UTC, shimonacarvalho commented on swagger/prime.yaml
> +      locator:
Sorry if I was not clear! I meant we should change `locator` to `moveCode` in both `prime.yaml` and `support.yaml` to match the rest of the system.

2020-12-30 18:30 UTC, duncan-truss commented on swagger/prime.yaml
> +      locator:
Haha whoops I mistook it for the reverse

2020-12-30 19:12 UTC, shimonacarvalho commented on swagger/prime.yaml
> +      locator:
Yeah I realized! So sorry. Approving now!

2020-12-30 19:13 UTC, shimonacarvalho approved these changes
Thanks! This will help us keep Prime in sync with rest of system.

2020-12-30 19:17 UTC, merged