MB-6076 Bump uswds from 2.9.0 to 2.10.0
transcom/mymove pull request #5589
Opened 2021-01-05 17:10 UTC by Shkeating

## Description

This PR updates the uswds version on the project. Dependabot ried to make this update for us on Dec 21st, but there were some design changes in happo (which I am opening this PR to review) and some issues with the e2e tests (which I am hoping don't happen again, but if they do, I will seek help from an engineer).

slack thread: https://ustcdp3.slack.com/archives/CTNTFJSBA/p1608588824279900

## Reviewer Notes
this is not ready for review yet. I had to open a PR to see the design changes in happo.

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

```sh
yarn install
yarn storybook
```

## Code Review Verification Steps

* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-6076?atlOrigin=eyJpIjoiMjE2NmI5NTU0MDliNDJmNGIwNmU3ZmMxOGM0NzQ1MGQiLCJwIjoiaiJ9) for this change
* [Original Dependabot PR](https://github.com/transcom/mymove/pull/5514)
* [slack thread](https://ustcdp3.slack.com/archives/CTNTFJSBA/p1608588824279900) 

## Screenshots

2021-01-08 16:34 UTC, suzubara commented
This is blocked pending a fix for this issue: https://github.com/uswds/uswds/issues/3909

2021-01-13 18:48 UTC, Shkeating commented
Update 1/13: issue still "in progress" on USWDS sprint board

2021-01-28 18:23 UTC, amanda5iu approved these changes

2021-01-29 00:42 UTC, suzubara requested changes
I'm requesting changes on this because we need to wait for USWDS to release a patch version, and will end up updating to (most likely) 2.10.1 in this PR. I want to ensure this PR is not able to be merged until that happens.

2021-01-29 00:42 UTC, suzubara commented on package.json
> +    "react-numeric-input": "^2.2.3",
This package was removed and should not be added back

2021-01-29 16:59 UTC, Shkeating commented on package.json
> +    "react-numeric-input": "^2.2.3",
done! i also labelled do not merge to cover our bases

2021-02-22 15:24 UTC, suzubara commented
https://github.com/uswds/uswds/releases/tag/v2.10.1 has been released, so we should be able to try this again @Shkeating

2021-02-25 23:27 UTC, suzubara commented
This isn't just the integration tests - starting the application (ie, `make client_run`) results in a JS error right off the bat.

![image](https://user-images.githubusercontent.com/2723066/109232860-8e379200-778e-11eb-9bc9-21dc87f67b69.png)

I am not sure why, but one possibility is that we have 2 different versions of USWDS installed because ReactUSWDS is not caught up with 2.10 yet. The latest version of ReactUSWDS implements USWDS 2.8.0. @Shkeating IMO we should version lock our USWDS to whatever our version of ReactUSWDS requires, which would mean 2.8.0.

2021-03-04 14:53 UTC, reggieriser commented
Just a heads up ... a dependabot update PR came through for uswds 2.10.2 (#6045).  I closed it since we have this PR to work through the 2.10.x upgrade.

2021-03-11 15:20 UTC, Shkeating commented
> This isn't just the integration tests - starting the application (ie, `make client_run`) results in a JS error right off the bat.
> 
> ![image](https://user-images.githubusercontent.com/2723066/109232860-8e379200-778e-11eb-9bc9-21dc87f67b69.png)
> 
> I am not sure why, but one possibility is that we have 2 different versions of USWDS installed because ReactUSWDS is not caught up with 2.10 yet. The latest version of ReactUSWDS implements USWDS 2.8.0. @Shkeating IMO we should version lock our USWDS to whatever our version of ReactUSWDS requires, which would mean 2.8.0.

I think that's a good point. Should I just close this PR then? Or should I try to coordinate with the folks currently working on reactuswds to use 2.10 in the next realease (even if they dont have component parity to it yet)?

2021-04-23 20:06 UTC, YanZ777 approved these changes

2021-04-23 20:08 UTC, merged