use latest milmove-cypress image: MB-6024
transcom/mymove pull request #5656
Opened 2021-01-13 22:40 UTC by lynzt

## Description

We have a repo circleci-docker that contains a build of cypress for our integration tests. When we update any packages in circleci-docker, we should pull the latest image of into mymove.

## Reviewer Notes

Make sure I have the correct hash: https://hub.docker.com/r/milmove/circleci-docker/tags?page=1&ordering=last_updated

## Setup

the integration tests should run w/o an issue on circle

## Code Review Verification Steps

* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-6024) for this change

2021-01-13 23:11 UTC, duncan-truss requested changes
It looks like the merge to master failed for that commit https://app.circleci.com/pipelines/github/transcom/circleci-docker/201/workflows/717e8b71-3fb5-4c5e-ae03-ca70cf7a7f86/jobs/236 meaning it didn't publish a new image to DockerHub.

It looks to be that common chromium download failure though. A rerun should generate the tag matching the commit `38cc39df3ee891652c472a6c731feecc63a1253b`

2021-01-14 03:42 UTC, lynzt commented
@duncan-truss that will teach me to multi-task... 

A re-run worked and I have updated the hash. 
Should I expect the hash to be the same when updating? Is that how you knew `38cc39df3ee891652c472a6c731feecc63a1253b` would eventually be the hash?

2021-01-14 14:54 UTC, duncan-truss commented
> @duncan-truss that will teach me to multi-task...
> 
> A re-run worked and I have updated the hash.
> Should I expect the hash to be the same when updating? Is that how you knew `38cc39df3ee891652c472a6c731feecc63a1253b` would eventually be the hash?

Since you merged the code I just looked at the git commit hash to master.  That's the same hash they use to tag the docker images with.

2021-01-14 14:55 UTC, duncan-truss approved these changes

2021-01-15 02:20 UTC, YanZ777 approved these changes

2021-01-15 19:58 UTC, merged