added truncation for city field
transcom/mymove pull request #5690
Opened 2021-01-19 18:52 UTC by pearl-truss

## Description

In the EDI the city name of the origin and destination duty stations can be a max of 30 characters in length. This PR updates the EDI generator to truncate the duty station city name's to be a max of 27 chars and adds an ellipsis ... 

## Reviewer Notes

I create a function called `truncateStr` in the generator file. Should it live somewhere else?

## Setup

```sh
make db_dev_e2e_populate
make server_run
```

Save json to file payload.json
```json
{
  "body": {
    "isFinal": false,
    "moveTaskOrderID": "9c7b255c-2981-4bf8-839f-61c7458e2b4d",
    "serviceItems": [
      {
        "id": "ca9aeb58-e5a9-44b0-abe8-81d233dbdebf"
      },
      {
        "id": "6431e3e2-4ee4-41b5-b226-393f9133eb6c"
      },
      {
        "id": "fd6741a5-a92c-44d5-8303-1d7f5e60afbf"
      }
    ]
  }
}
```

Update the either the origin or the destination duty station to have a city name longer than 27 characters 

For this mto, to update the destination duty station you can use this command exactly. To update the origin duty station replace the id with `ddb915e6-ae75-47a5-a153-2ddb2116027e`

```sh
update addresses set city='A super duper duper long city name' where id='5ac95be8-0230-47ea-90b4-b0f6f60de364';
```

Create payment request
```sh
prime-api-client --insecure create-payment-request --filename payload.json | tee output | jq '.id,.paymentRequestNumber'
```

Approve the payment request in the TIO interface http://officelocal:3000 Move Code `RDY4PY`

Generate EDI
```sh
bin/generate-payment-request-edi --payment-request-number [payment request number]
```
Expected Output
Notice the truncation in the first N4 segment for city name

```js
ISA*00*0084182369*00*0000000000*ZZ*MILMOVE        *12*8004171844     *210119*1839*U*00401*827201557*0*T*|
GS*SI*MILMOVE*8004171844*20210119*1839*100001251*X*004010
ST*858*0001
BX*00*J*PP*4116-3394*TRUS**4
N9*CN*4116-3394-1**
N9*CT*TRUSS_TEST**
N9*1W*Leo, Spacemen**
N9*ML*E_1**
N9*3L*ARMY**
G62*10*20210119**
G62*76*20210118**
G62*86*20200316**
N1*BY*JPPSO Testy McTest*92*LKNQ
N1*SE*Prime*2*PRME
N1*ST*Fort Gordon*10*CNNQ
N3*Fort Gordon*
N4*A super duper duper long ci...*GA*30813*USA** //Notice the truncation
PER*CN**TE*706-791-4184
N1*SF*3C99zB51T5*10*LKNQ
N3*987 Other Avenue*P.O. Box 1234
N4*Des Moines*IA*50309*USA**
PER*CN**TE*(510) 555-5555
HL*1**I
N9*PO*4116-3394-ad10cea7**
L5*1*DLH*TBD*D**
L0*1*354.000*DM*1349.000*B******L
L1*1*1349*LB*115948500
FA1*DY
FA2*TA*F8E1
HL*2**I
N9*PO*4116-3394-640c47d4**
L5*2*FSC*TBD*D**
L0*2*354.000*DM*1349.000*B******L
L1*2*1349*LB*34400
FA1*DY
FA2*TA*F8E1
HL*3**I
N9*PO*4116-3394-3b82e699**
L5*3*CS*TBD*D**
L0*3**********
L1*3*0**2235300
FA1*DY
FA2*TA*F8E1
L3*****1182182
SE*43*0001
GE*1*100001251
IEA*1*827201557
```
### Acceptance

* Generate an EDI on staging and ensure that the origin and destination duty station cities are truncated if they are over 27 chars long. I believe you won't be able to update the duty station city name in the database so you'll need to create a payment request for a move that has a long city name duty station in its orders

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-6180) for this change

2021-01-19 19:12 UTC, reggieriser commented on pkg/services/invoice/ghc_payment_request_invoice_generator.go
> +const maxCityLength = 27
Does it make more sense for the max length to be the actual length (30 in this case), then change the `truncateStr` function to back off of that with the ellipsis (or whatever it might do) to make sure it doesn't exceed 30?  Right now, the caller has to know what the `truncateStr` is adding to the string to know to put 27 rather than 30 as the cutoff.

2021-01-19 19:14 UTC, reggieriser commented on pkg/services/invoice/ghc_payment_request_invoice_generator.go
> +}
Might be worth throwing in some simple tests for this function.

2021-01-19 21:17 UTC, reggieriser requested changes
Thanks for reworking the method, but I think right now we could still exceed the max length given how we're slicing the original string.

2021-01-19 21:17 UTC, reggieriser commented on pkg/services/invoice/ghc_payment_request_invoice_generator.go
> +		return str[:cutoff] + "..."
I think you want `str[:cutoff-3]` here so the total doesn't exceed `cutoff` (and rename `cutoff` to `maxLength` perhaps?).

2021-01-19 21:37 UTC, reggieriser commented on pkg/services/invoice/ghc_payment_request_invoice_generator.go
> +		return str[:cutoff] + "..."
FYI, just tried it using your instructions and got this: `EDI failed validation: Key: 'Invoice858C.Header.DestinationPostalDetails.CityName' Error:Field validation for 'CityName' failed on the 'max' tag`

2021-01-19 21:46 UTC, pearl-truss commented on pkg/services/invoice/ghc_payment_request_invoice_generator.go
> +		return str[:cutoff] + "..."
yup, you're right!

2021-01-19 21:48 UTC, pearl-truss commented on pkg/services/invoice/ghc_payment_request_invoice_generator.go
> +		return str[:cutoff] + "..."
@reggieriser for your second comment, myself and Jaquie ran into that as well. For me it was resolved after I ran `make clean`

2021-01-19 22:37 UTC, reggieriser commented on pkg/services/invoice/ghc_payment_request_invoice_generator.go
> +		return str[:cutoff] + "..."
I think there's one more gremlin here after your latest fix.  If the cutoff is small -- say 2, for instance -- you'll get a `test panicked: runtime error: slice bounds out of range [:-1]`.  I guess in that case we just trim the string at the cutoff and not put on the ellipsis?  It's not an issue in this PRs use case, but just thinking about reuse since this is a nice generic function.

2021-01-20 15:21 UTC, reggieriser approved these changes
LGTM!  Thanks for the changes.  The ellipsis seems like a reasonable way to handle it, but you might want to double-check with @gidjin before merging (if you haven't already) to make sure the ellipsis is fine in the EDI.

2021-01-20 17:55 UTC, merged