Kim mb 6374 add branch to header
transcom/mymove pull request #5693
Opened 2021-01-19 23:55 UTC by kimallen

## Description

The branch (aka affiliation aka agency) is not showing yet on the CustomerHeader.  This story adds the service member's branch name before the grade (aka rank).  Also reformats the displayed grade with a dash instead of underscore (E-6 instead of E_6).

## Reviewer Notes

The correct value to use is `agency` returned from the `moveOrder` payload which comes from the `ServiceMember` table's `Affiliation` field.  See [Slack discussion](https://ustcdp3.slack.com/archives/CP4979J0G/p1611097878028000)

## Setup

`make storybook` and look at the CustomerHeader

`make server_run`
`make client_run`
Go to the office user and click on a move.  View the header with the branch name.

## Code Review Verification Steps

* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](tbd) for this change
* [this article](tbd) explains more about the approach used.

## Screenshots

![image](https://user-images.githubusercontent.com/13249580/105108268-c0a6ee80-5a6e-11eb-8265-2162c7c7dbab.png)

2021-01-20 00:06 UTC, YanZ777 approved these changes

2021-01-20 17:02 UTC, suzubara requested changes

2021-01-20 17:02 UTC, suzubara commented on src/utils/formatters.js
> +export function formatGrade(grade) {
I think you could use the values defined here to get the display value for grade (rank): https://github.com/transcom/mymove/blob/master/src/constants/orders.js#L33

generally I would avoid using a function to convert the database value to a display value, because it may not be consistent. It looks like there may be ranks that don't fit this format. Also I think there is already a constant defined for the agencies in that same file. `src/utils/formatters` is used for functions, and constants/display values are in `src/constants`

2021-01-20 18:48 UTC, kimallen commented on src/utils/formatters.js
> +export function formatGrade(grade) {
ooh, thank you.  I didn't know those already existed.

2021-01-20 18:48 UTC, kimallen commented on src/components/CustomerHeader/index.jsx
> +        <div data-test="nameBlock" className={styles.nameBlock}>
I thought something sounded off about `data-test`

2021-01-21 15:23 UTC, suzubara approved these changes
looks good to me!

2021-01-21 16:20 UTC, amanda5iu approved these changes
Looks great, thanks Kim!

2021-01-21 17:02 UTC, merged