MB-3620 Add queries move details page
transcom/mymove pull request #5694
Opened 2021-01-20 00:31 UTC by donaldthai

## Description

> On the MoveDetails page, replace the existing data fetch code with React Query, to fetch and the move order, customer, MTOs, MTO agents, MTO shipments, and MTO service items.
> 
> Notes:
> 
> MoveDetails should be converted from a class component to a functional component
> 
> The queries triggered by componentWillMount should be replaced with useQuery hooks, and Redux connect code should be deleted
> 
> The logic in existing mapStateToProps that maps API data to the format expected by the component may need to be replicated in the useQuery hook.
> 
> Other existing code reliant on the component lifecycle will also need to be modified to use hooks (i.e., the scroll handler and active section state)
> 
> Might be able to use useEffect
> 

> AC:
> 
> - MoveDetails does not rely on Redux for any API data
> 
> - MoveDetails queries the API directly for any data needed based on the move order ID in the URL params

## Reviewer Notes

Is there anything you would like reviewers to give additional scrutiny?

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

```sh
echo "Code goes here"
```

## Code Review Verification Steps

* [ ] If the change is risky, it has been tested in experimental before merging.
* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] The requirements listed in
 [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely)
 have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://github.com/transcom/mymove/wiki/migrate-the-database#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](tbd) for this change
* [this article](tbd) explains more about the approach used.

## Screenshots

If this PR makes visible UI changes, an image of the finished UI can help reviewers and casual
observers understand the context of the changes. A before image is optional and
can be included at the submitter's discretion.

Consider using an animated image to show an entire workflow instead of using multiple images. You may want to use GIPHY CAPTURE for this! 📸

_Please frame screenshots to show enough useful context but also highlight the affected regions._

2021-01-21 22:28 UTC, donaldthai commented
Approved Happo since no changes to the design. Just data returning.

2021-01-21 23:02 UTC, suzubara requested changes
I left some comments, and I also have a question about how the TXO app is using `normalizr`.. I noticed that this PR adds `normalize: false` to some of the queries. are there any instances in the TXO app where the data _should_ be normalized? I think it would be good for us to be more consistent about normalization, and I'm also starting to think the `makeSwaggerRequest` function should not be normalizing at all.

2021-01-22 14:04 UTC, duncan-truss commented on src/hooks/queries.js
> +  const { data: { mtoShipments } = {}, ...mtoShipmentQuery } = useQuery([MTO_SHIPMENTS, mtoID, true], getMTOShipments, {
The third parameter lets you toggle normalization of the response.  Since the query is used in multiple places and we were using the unnormalized result in the MoveDetailsQueries but here in the MoveTaskOrderQueries we wanted to keep the behavior the same.  We added the default value of true but I think we ended up having to set it explicitly here.

After this PR (and in the followup PRs on adding the useMutation hooks for the MoveDetails page) it would be good to revisit the different queries to make sure they'll all be cached and maybe move to denormalizing where we can.

2021-01-22 14:05 UTC, duncan-truss commented on src/pages/Office/MoveDetails/MoveDetails.jsx
> +  }
Yea we were just focused on porting what was there but yea seems better to just compute that based on the shipments data and remove the state updates.

2021-01-22 16:24 UTC, suzubara approved these changes

2021-01-22 16:26 UTC, Ryan-Koch approved these changes

2021-01-22 18:28 UTC, duncan-truss commented
The design diffs look spurious once I fixed the ShipmentApprovalPreview story data for agents and backup contact.

2021-01-22 18:49 UTC, merged