[MB-6194] Extend user endpoint to update Active status
transcom/mymove pull request #5717
Opened 2021-01-22 20:11 UTC by abbyoung

## Description

This PR updates the existing endpoint `PATCH /users/{userId}` to support changing the `Active` status of a user in the `users` table.

* The previous iteration used the update endpoint only to revoke user sessions, which was reflected in the naming.
* I've renamed all related functions, etc. to `UpdateUser`, `UserUpdatePayload`, etc. None of the previous code by @monfresh was altered except for renaming.
* This makes the code more flexible in case we need to add additional user properties to update in the future.
* Added new service object to handle updating the user (aside from session revocation, which already has its own SO). For now, this only handles the Active status, but I left a comment to direct any future engineer to add their changes to `UpdateUser`.
* Updated tests for the handler and added tests for the service object

## Reviewer Notes

See: https://github.com/transcom/mymove/compare/update-user-in-admin-app-mb-6194?expand=1#diff-1c02fbb6907330dee84754ccc54da0c2f62468c90e66e838504434b740df4279R126

Would love to know if there's a better way to do this in golang!

## Setup

Tests:

`go test ./pkg/services/user --testify.m "TestUserUpdater" -v`
go test ./pkg/handlers/adminapi/ --testify.m 'TestUpdateUserHandler' -v

You can also test the endpoint using Postman if you would like to brave the CSRF token setup. YOU CAN DO IT. Ping me if you want to pair to set it up.

Here are some instructions I wrote down for myself:

* Make sure you have Postman Interceptor installed in your browser and you've added `adminlocal` as a domain
* Open Postman -> Make sure Interceptor is turned on in Postman and you've added `adminlocal` as a domain
* Run `make server_run` and `make admin_client_run`
* In admin app, log in as local admin user
* Open up dev tools -> Application -> Cookies -> Copy the token for `admin_session`
* In Postman, make GET request to `http://adminlocal:3000/admin/v1/users/{userId}` You'll probably get a 403 because we need to update the admin_session token.
* Click the `cookies` link in your postman app (underneath the request path) -- you should see all populated. Click the `admin_session` cookie, paste in your new value, and save.
* You can redo the GET request now and you should receive a response.
* To do a `PATCH` request, click the `cookies` link again and copy the `masked_gorilla` token value.
* Add a header for your request with the key `X-CSRF-TOKEN` and value `<token value you copied>`
* Add a body to toggle the `active` status.
```
{ "active": false}
```
* Hit it!

## Code Review Verification Steps
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-6194) for this change

2021-01-22 22:19 UTC, eamahanna approved these changes
These changes make sense to me and everything worked in postman :)

2021-01-25 17:48 UTC, shimonacarvalho commented on pkg/handlers/adminapi/users.go
> +// Handle updates a user's Active status and/or their sessions
Thanks for making these comments useful and correct.

2021-01-25 17:51 UTC, shimonacarvalho commented on pkg/handlers/adminapi/users.go
>  	payload := params.User
Is params.User required in the payload? If not, you later do *payload which will cause a possible nil dereference.

2021-01-25 17:53 UTC, shimonacarvalho commented on pkg/handlers/adminapi/users_test.go
> +		suite.IsType(&userop.UpdateUserOK{}, response)
Great job checking the details returned here.

2021-01-25 17:57 UTC, shimonacarvalho commented on pkg/handlers/adminapi/users_test.go
>  		response := handler.Handle(params)
Can you call the swagger check prior to each of these Handle commands? It unearths a lot of invisible bugs. 
`suite.NoError(params.Body.Validate(strfmt.Default))`

2021-01-25 18:50 UTC, shimonacarvalho commented on pkg/handlers/adminapi/users_test.go
> +	userUpdater.On("UpdateUser",
Awesome job using mocks! Can I suggest that you add to each test a description of what is being setup and what is expected? Makes it easier for reviewer to doublecheck everything and for future updater to understand how to edit the test. 

I do something like this at the top of each test:
```
		// Under test: sendOneNotification function
		// Mocked:     Client
		// Set up:     We provide a FAILING webhook notification, and make the client fail twice to send
		//             and then succeed
		// Expected outcome:
		//             Client.Post called 3 times in total
		//             Notification would be updated as SENT
```

2021-01-25 18:50 UTC, shimonacarvalho commented on pkg/handlers/adminapi/users_test.go
> +		suite.IsType(&userop.UpdateUserOK{}, response)
I'm not understanding why the response should be ok if the update failed?

2021-01-25 18:52 UTC, shimonacarvalho commented on pkg/services/user/user_updater.go
> +	if payload.Active != nil {
payload itself is a pointer so are we sure here that it cannot be nil? If it could then payload.Active could cause a nil dereference.

2021-01-25 18:58 UTC, shimonacarvalho requested changes
Great job and a lot of good work! 

I found some potential nil dereferences. In the handler, I'm not sure they will cause them because it's possible that swagger would ensure that certain things would never be nil. In the service object, I'd recommend we doublecheck, because someone else could reuse that SO.

Some updates to the tests requested.

2021-01-25 19:00 UTC, abbyoung commented on pkg/handlers/adminapi/users_test.go
> +		suite.IsType(&userop.UpdateUserOK{}, response)
good question -- this was a test i updated but you're right. i'll dig in and figure out what's actually supposed to happen here. thanks!

2021-01-25 19:06 UTC, abbyoung commented on pkg/handlers/adminapi/users.go
>  	payload := params.User
`params.User` represents the required `UpdateUserPayload` in `admin.yaml`. Should I still check that it's not nil?

2021-01-26 19:05 UTC, monfresh commented on pkg/handlers/adminapi/users_test.go
> +		suite.IsType(&userop.UpdateUserOK{}, response)
Oh my! I wrote that. It looks like I meant to copy and paste what comes after that test into the test. So, lines 318-342 should go inside the test that starts on line 291, and it should replace lines 292-315.

2021-01-28 02:26 UTC, shimonacarvalho approved these changes
LGTM! Good job persevering! This one was full of booby traps!

2021-01-28 19:30 UTC, merged