Kim MB-4729 Apply Milmove Header
transcom/mymove pull request #5740
Opened 2021-01-26 02:33 UTC by YanZ777

## Description

Put in the new MilMoveHeader for the TOO.

## Reviewer Notes

Given that this PR is out there: https://github.com/transcom/mymove/pull/5737/files
I'm not certain that all the css changes are needed. I might wait until the above PR gets merged in, and then adjust as necessary. Please let me know if that is a good idea or not. Regardless, I'd still like to get eyes on this PR early.

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

```sh
make office_client_run
make server_run
```

## Code Review Verification Steps
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-4729) for this change

## Screenshots

If this PR makes visible UI changes, an image of the finished UI can help reviewers and casual
observers understand the context of the changes. A before image is optional and
can be included at the submitter's discretion.

Consider using an animated image to show an entire workflow instead of using multiple images. You may want to use GIPHY CAPTURE for this! 📸

_Please frame screenshots to show enough useful context but also highlight the affected regions._

![image](https://user-images.githubusercontent.com/6477059/105791802-74125600-5f3b-11eb-8d44-4426478bf59b.png)

![image](https://user-images.githubusercontent.com/6477059/105791934-a15f0400-5f3b-11eb-908c-33ce46b35e21.png)

2021-01-26 18:55 UTC, kimallen commented on src/components/MilMoveHeader/index.module.scss
> +      color: #b7caf0;
We should use a color variable from `colors.scss` for this rather than putting the code directly into the styles.   I don't see this particular one in there, but we should check with design if there is one close enough or if it's okay to add this one as well.

2021-01-26 18:58 UTC, kimallen commented on src/shared/User/LoginButton.jsx
> +      <Button unstyled className="usa-nav__link" onClick={handleLogOut} type="button">
I know we removed the li's when we were trying to use this component inside the dark background of the MilmoveHeader.  And we were experimenting with using <Button> instead of the <a>.  I don't think these changes hurt anything to keep, and they also may not be necessary, especially since we are likely refactoring sign-in in a near-future story.

2021-01-26 19:04 UTC, amanda5iu commented on src/components/MilMoveHeader/index.module.scss
> +      color: #b7caf0;
I think it makes sense to add this color in! I imagine we'll eventually have other uses for `link--light`, so it makes sense to have all the relevant colors codified.

2021-01-26 19:11 UTC, YanZ777 commented on src/components/MilMoveHeader/index.module.scss
> +      color: #b7caf0;
I can add that in this PR, what should it be named?

2021-01-26 20:05 UTC, amanda5iu commented on src/components/MilMoveHeader/index.module.scss
> +      color: #b7caf0;
In the design libraries we call it `a--light:hover` - something similar to that would be great. But I defer to whatever color naming pattern we use for regular links. Maybe `$link-light-hover`?

2021-01-27 15:27 UTC, amanda5iu approved these changes
This looks great! Thanks Yan!

2021-01-27 16:56 UTC, suzubara requested changes
This looks great for the most part, I just added a couple of comments for issues in the PPM Office app and Customer app that I think should be resolved before merging

2021-01-27 16:56 UTC, suzubara commented on src/pages/Office/index.jsx
> +            {(!userIsLoggedIn || activeRole === roleTypes.TIO) && <QueueHeader />}
The `<QueueHeader />` needs to show up for office users with the PPM role also -- as-is if I log in as a PPM office user, there is no header at all and I'm not able to sign out

2021-01-27 16:56 UTC, suzubara commented on src/shared/User/LoginButton.jsx
> +      <Button unstyled className="usa-nav__link" onClick={handleLogOut} type="button">
I think we might want to revert these changes because they are affecting the customer app (it's hard to see the links now)..

![image](https://user-images.githubusercontent.com/2723066/106025100-0f1b4500-608e-11eb-9fca-8d91b520d29d.png)

2021-01-27 16:57 UTC, suzubara commented
@YanZ777 to answer this question:
> Given that this PR is out there: https://github.com/transcom/mymove/pull/5737/files
> I'm not certain that all the css changes are needed. I might wait until the above PR gets merged in, and then adjust as necessary. Please let me know if that is a good idea or not. Regardless, I'd still like to get eyes on this PR early.

I don't think you need to worry about it, it doesn't look like that PR will affect the work in this one

2021-01-28 20:23 UTC, Shkeating approved these changes
looks like issue in customer app has been resolved :)
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/59394696/106194259-92b35f80-617c-11eb-870b-9f6b2821e6d3.png">

I am seeing a `Something Went Wrong` on the office app when logged in as a TOO user, but I'm guessing that is unrelated to the header? 
<img width="1856" alt="image" src="https://user-images.githubusercontent.com/59394696/106194405-cabaa280-617c-11eb-8f79-b39ef0723f35.png">

2021-01-28 22:16 UTC, suzubara approved these changes

2021-01-28 22:25 UTC, merged