Mb mb 1576 distance zip sit origin lookup
transcom/mymove pull request #5749
Opened 2021-01-26 23:21 UTC by mboren

## Description

Explain a little about the changes at a high level.

## Reviewer Notes

Is there anything you would like reviewers to give additional scrutiny?

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

```sh
echo "Code goes here"
```

## Code Review Verification Steps

* [ ] If the change is risky, it has been tested in experimental before merging.
* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] The requirements listed in
 [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely)
 have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://github.com/transcom/mymove/wiki/migrate-the-database#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](tbd) for this change
* [this article](tbd) explains more about the approach used.

## Screenshots

If this PR makes visible UI changes, an image of the finished UI can help reviewers and casual
observers understand the context of the changes. A before image is optional and
can be included at the submitter's discretion.

Consider using an animated image to show an entire workflow instead of using multiple images. You may want to use GIPHY CAPTURE for this! 📸

_Please frame screenshots to show enough useful context but also highlight the affected regions._

2021-01-27 15:59 UTC, jacquelineIO requested changes
SIT origin service items will have both `SITOriginHHGActualAddress` and `SITOriginHHGOriginalAddress` set. Since linehaul hasn't started yet, we can't ensure that the shipment won't be updated again before the linehaul happens. So we are keeping the information needed on the SIT origin service item. This is different than SIT destination, because linehaul has been completed, and we shouldn't be changing/update the shipment and we are able to use the destination address for distance.

2021-01-27 15:59 UTC, jacquelineIO commented on pkg/payment_request/service_param_value_lookups/service_param_value_lookups.go
> +		OriginalAddress: pickupAddress,
@mboren  your `OriginalAddress` should be coming from `MTOServiceItem.SITOriginHHGOriginalAddress`.

2021-01-27 15:59 UTC, jacquelineIO commented on pkg/payment_request/service_param_value_lookups/distance_zip_sit_origin_lookup_test.go
> +				SITOriginHHGActualAddress:   &actualOriginDiffZip3Address,
You also need to set `MTOServiceItem.SITOriginHHGOriginalAddress`. You won't be using the address from the Shipment.

2021-01-27 17:44 UTC, mboren commented on pkg/payment_request/service_param_value_lookups/service_param_value_lookups.go
> +		OriginalAddress: pickupAddress,
Ok, I'll do that

2021-01-27 23:06 UTC, jacquelineIO reviewed
The code looks good, but I think there is confusion on when to use the case statement at the beginning of the file. I left a clarifying comment on the code, to be considered for updating the code.

2021-01-27 23:11 UTC, jacquelineIO commented on pkg/payment_request/service_param_value_lookups/service_param_value_lookups.go
> -	default:
So getting rid of this `fallthrough` is why were having to use this new variable `	savePickupAndDestinationFromShipment := true`.

2021-01-28 00:40 UTC, mboren commented on pkg/payment_request/service_param_value_lookups/service_param_value_lookups.go
> -	default:
Yeah. The boolean feels a bit awkward, but I wasn't sure how else to do this.

2021-01-28 01:06 UTC, mboren commented on pkg/payment_request/service_param_value_lookups/service_param_value_lookups.go
> +			sitOriginOriginalAddress = *mtoServiceItem.SITOriginHHGOriginalAddress
I took out the case that I added, removed the top level variables for SIT addresses, and moved the address loading into the `default` case. This feels a bit more sensible, but I'm still not sure i'm doing the right thing

2021-01-28 20:31 UTC, mboren commented
Just realized that I do have a DB connection available in the lookup, so I'll be changing this a bit to use that later today

2021-01-28 22:39 UTC, jacquelineIO approved these changes
lgtm

2021-01-29 00:14 UTC, merged