MB-6173 add move detail page to admin app
transcom/mymove pull request #5776
Opened 2021-01-28 23:28 UTC by eamahanna

## Description

This PR added the move detail page to the admin app and added a cypress test.
![Screen Shot 2021-01-28 at 2 24 32 PM](https://user-images.githubusercontent.com/56279459/106211109-93e08e80-6174-11eb-9adc-036caff2f680.png)

## Reviewer Notes

This has to be merged in after [PR #5768](https://github.com/transcom/mymove/pull/5768).

## Setup
To run the cypress tests, execute `make e2e_test`.

To view the page, log onto the admin app locally. Navigate to the moves tab. Click on a list item, and you will be redirected to the detail page.

## Code Review Verification Steps

* [ ] If the change is risky, it has been tested in experimental before merging.
* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] The requirements listed in
 [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely)
 have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://github.com/transcom/mymove/wiki/migrate-the-database#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](tbd) for this change
* [this article](tbd) explains more about the approach used.

## Screenshots

If this PR makes visible UI changes, an image of the finished UI can help reviewers and casual
observers understand the context of the changes. A before image is optional and
can be included at the submitter's discretion.

Consider using an animated image to show an entire workflow instead of using multiple images. You may want to use GIPHY CAPTURE for this! 📸

_Please frame screenshots to show enough useful context but also highlight the affected regions._

2021-01-28 23:43 UTC, eamahanna commented on src/pages/Admin/Moves/MoveShow.jsx
> +MoveShowTitle.propTypes = {
Had to add in the propTypes to make eslint happy. If you would like to learn more about them:

https://reactjs.org/docs/typechecking-with-proptypes.html

2021-01-29 17:54 UTC, eamahanna commented on src/pages/Admin/Moves/MoveList.jsx
> +      <TextField source="serviceMember.id" label="Service Member Id" sortable={false} />
@sandy-wright this fixes the bug mentioned in https://ustcdp3.slack.com/archives/CP497TGAU/p1611942330126500

2021-01-29 18:18 UTC, sandy-wright requested changes
Looks good to me! I do think we should change the name of `AccessCodeList` to `MoveList`, but all my other comments are miscellaneous suggestions that you can justifiably ignore ☺️

2021-01-29 18:18 UTC, sandy-wright commented on src/pages/Admin/Moves/MoveList.jsx
>  const AccessCodeList = (props) => (
Can we rename this to MoveList? There's already another AccessCodeList; I think this is an old copy & paste error

2021-01-29 18:18 UTC, sandy-wright commented on src/pages/Admin/Moves/MoveList.jsx
> +  /* eslint-disable-next-line react/jsx-props-no-spreading */
In other files, I see this line at the very top, above the imports. If we do that, would it make it so that you don't have to use it twice in this file? That could be handy

2021-01-29 18:18 UTC, sandy-wright commented on src/pages/Admin/Moves/MoveShow.jsx
> +        <DateField source="updatedAt" showTime />
This is an annoying request, so please feel free to ignore it: Could we add the Orders ID to this output? It's not in the ticket, so no big deal either way. It just feels a little goofy to me to display it in the row on the table, but not in the detail page.

2021-01-29 18:39 UTC, eamahanna commented on src/pages/Admin/Moves/MoveShow.jsx
> +        <DateField source="updatedAt" showTime />
Sure!

2021-01-29 18:40 UTC, eamahanna commented on src/pages/Admin/Moves/MoveList.jsx
> +  /* eslint-disable-next-line react/jsx-props-no-spreading */
Done!

2021-01-29 18:51 UTC, sandy-wright approved these changes
Yay, looks great! Thanks for making those changes

2021-01-29 19:19 UTC, merged