[MB-1564] MilMove can look up NumberDaysSIT
transcom/mymove pull request #5800
Opened 2021-02-01 19:23 UTC by harshamurthy

## Description

Explain a little about the changes at a high level.

## Reviewer Notes

Is there anything you would like reviewers to give additional scrutiny?

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

```sh
echo "Code goes here"
```

## Code Review Verification Steps

* [ ] If the change is risky, it has been tested in experimental before merging.
* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] The requirements listed in [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely) have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://github.com/transcom/mymove/wiki/migrate-the-database#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](tbd) for this change
* [this article](tbd) explains more about the approach used.

## Screenshots

If this PR makes visible UI changes, an image of the finished UI can help reviewers and casual
observers understand the context of the changes. A before image is optional and
can be included at the submitter's discretion.

Consider using an animated image to show an entire workflow instead of using multiple images. You may want to use GIPHY CAPTURE for this! 📸

_Please frame screenshots to show enough useful context but also highlight the affected regions._

2021-02-08 17:52 UTC, jacquelineIO requested changes
Really good progress on this PR. I think there some changes needed to have the correct days calculated. Made relevant comments in the PR. 

Also consider changing the db queries to use slices as mentioned here https://ustcdp3.slack.com/archives/CP6F568DC/p1612305617277100?thread_ts=1612305573.277000&cid=CP6F568DC

2021-02-08 17:52 UTC, jacquelineIO commented on pkg/payment_request/service_param_value_lookups/number_days_sit_lookup.go
> +		paymentServiceItemSITDays, err := fetchNumberDaysSITParamValue(moveTaskOrderSITPaymentServiceItem)
This is not checking for first day of SIT and adding 1 day. Will need to do a check service code for and add 1 day appropriately. Something like


		reServiceCode := moveTaskOrderSITPaymentServiceItem.MTOServiceItem.ReService.Code
		if reServiceCode == models.ReServiceCodeDOASIT || reServiceCode == models.ReServiceCodeDOASIT {
            // handle additional days (already doing this part)
		} else if reServiceCode == models.ReServiceCodeDOFSIT || reServiceCode == models.ReServiceCodeDOFSIT {
			// TODO add 1 day of SIT
		}

2021-02-08 17:52 UTC, jacquelineIO commented on pkg/payment_request/service_param_value_lookups/number_days_sit_lookup.go
> +			return 1, nil
The `currentMTOServiceItem` can only be an additional day sit service item. This lookup will not be called for first day sit pricing.

2021-02-08 17:52 UTC, jacquelineIO commented on pkg/payment_request/service_param_value_lookups/number_days_sit_lookup.go
> +		currentMTOShipmentSITDays = currentMTOShipmentSITDays + paymentServiceItemSITDays
Also missing adding the first day of SIT to the number of shipment days.

2021-02-08 17:52 UTC, jacquelineIO commented on pkg/payment_request/service_param_value_lookups/number_days_sit_lookup.go
> +			return 29, nil
Where do you check that 29 is not more than 
`Today's date - (MTOShipmentEntryDate + first days SIT + additional days SIT)` for a shipment.

So a shipment will have it own number of days available for a payment request. One way to check is by calculating a new start date: `MTOShipmentEntryDate + first days SIT + additional days SIT`
than adding 29 days and verifying that this new date is not more than the current date. Or by finding the number of shipment days available for a shipment's payment request like `Today's date - (MTOShipmentEntryDate + first days SIT + additional days SIT)`  to return the `number of days` available to request payment for. 

This is different than the total number of days available for the whole move.

2021-02-08 19:12 UTC, reggieriser reviewed
Just adding a couple of comments.  Will hold off on further review/pairing until you've addressed the concerns from @jacquelineIO .

2021-02-08 20:10 UTC, harshamurthy commented on pkg/payment_request/service_param_value_lookups/number_days_sit_lookup.go
> +		paymentServiceItemSITDays, err := fetchNumberDaysSITParamValue(moveTaskOrderSITPaymentServiceItem)
`moveTaskOrderSITPaymentServiceItems` is a slice of all the SIT `Payment Service Items` that belong to either the MTO or the MTO Shipment depending on the context. The slice includes Payment Service Items for both First Day and Additional Day Services. When doing the PayServiceItemParamValue lookup the returned value will be reflect the first day value or additional day value.

If I'm not mistaken, this will properly account for first day of SIT.

2021-02-09 16:43 UTC, pearl-truss reviewed
This may have already been done but I think reviews for this PR also have to look at the DDASIT and DOASIT pricer since @gidjin 's [PR](https://github.com/transcom/mymove/pull/5781) for that pricer stubbed out this lookup

2021-02-09 23:21 UTC, harshamurthy commented
@jacquelineIO, ready for another review!

2021-02-10 17:57 UTC, jacquelineIO requested changes
Some additional things to review for updates.

2021-02-10 17:57 UTC, jacquelineIO commented on pkg/payment_request/service_param_value_lookups/number_days_sit_lookup.go
> +	daysSITAvailableForPayment := int(todaysDate.Sub(mtoShipmentEntryDate).Hours() / 24)
after getting the number of days since SIT entry date, you would need to subtract the number of days already submitted for payment to get the the remaining days available for payment. I think my comment on the previous and hopefully the number of days SIT doc talks about the logic for this.

2021-02-10 17:57 UTC, jacquelineIO commented on pkg/payment_request/service_param_value_lookups/number_days_sit_lookup.go
> +	mtoServiceItemSITDays, err := calculateMTOServiceItemSITDays(mtoShipmentSITPaymentServiceItems, keyData.MTOServiceItem)
Consider adding a comment that this is calculating the available SIT days or change the name of the function to `calculateMTOServiceItemAvailableSITDays` or something to indicate what is happening here.

2021-02-10 17:57 UTC, jacquelineIO commented on pkg/payment_request/service_param_value_lookups/number_days_sit_lookup.go
> +	return false, 29
Curious why this is not `false, 0` ?

2021-02-10 17:57 UTC, jacquelineIO commented on pkg/payment_request/service_param_value_lookups/number_days_sit_lookup.go
> +	daysSITAvailableForPayment := int(todaysDate.Sub(mtoShipmentEntryDate).Hours() / 24)
See if there is already a `hours in day` const or make a new one for this file.

2021-02-10 17:57 UTC, jacquelineIO commented on pkg/payment_request/service_param_value_lookups/number_days_sit_lookup.go
> +	return false, 29
Should probably make `29` a const in this file.

2021-02-10 17:57 UTC, jacquelineIO commented on pkg/payment_request/service_param_value_lookups/number_days_sit_lookup.go
> +			} else if shipmentSITPaymentServiceItem.MTOServiceItem.SITEntryDate != nil {
There isn't a check for `isDomesticOrigin(mtoServiceItem)` on this line. 
Maybe pull this out into it's own check and do the date checks internally, something like:

```go
if isDomesticOrigin(shipmentSITPaymentServiceItem.MTOServiceItem) {
    if isDomesticOrigin(mtoServiceItem) {
        if shipmentSITPaymentServiceItem.MTOServiceItem.SITDepartureDate != nil {
            // do stuff 
        } else if shipmentSITPaymentServiceItem.MTOServiceItem.SITEntryDate != nil {
            // do stuff 
        }
    }
}
```

2021-02-10 17:57 UTC, jacquelineIO commented on pkg/payment_request/service_param_value_lookups/number_days_sit_lookup.go
> +					originSITEntryDate = *sitEntryDate
if this is true `originSITEntryDate == *sitEntryDate ` why would it get saved on the next line? 
Should this just be check for zero only?

2021-02-10 17:57 UTC, jacquelineIO commented on pkg/payment_request/service_param_value_lookups/number_days_sit_lookup.go
> +					originSITEntryDate = *sitEntryDate
Maybe drop the `originSITEntryDate == *sitEntryDate` and else should be 
`else if originSITEntryDate != *sitEntryDate`? I'm not really sure, but this seems like what this is doing.

2021-02-10 23:12 UTC, jacquelineIO reviewed
Looks really good. I haven't run the code locally and won't be able to today, but leaving my last comments here for now. (I can't remove request changes until I approve, so it will still show, I think.)

2021-02-11 17:30 UTC, harshamurthy commented on pkg/payment_request/service_param_value_lookups/number_days_sit_lookup.go
> +	return false, 0
The place where this function is getting called returns `29` if this function returns `false` so I think it's good for this function to return `0` instead of also returning `29`.

2021-02-11 17:37 UTC, harshamurthy commented on pkg/payment_request/service_param_value_lookups/number_days_sit_lookup.go
> +	if sitDaysAvailableForBilling < fullBillingPeriod {
I left it as `<` because if it's `=` then technically it's a full billing period of `29` days.

2021-02-16 23:00 UTC, jacquelineIO approved these changes
Thanks for all of the updates. 

I have done the code review. There is some DRY'ing left for this code, but that will be a new chore/story to do that in. Also we should make sure to add some UT to the prime api create payment request UT for SIT, now that all of SIT MVP pricing is done. There is also some clean-up of error handling needed at the pricing level being returned to the prime api. 

Here is the local testing that I did before approving:

1. can price 1 additional day sit with full 29 (second request was denied with only having 5 days available for billing)
2. can price additional day sit with departure date set. AND was able to do this twice with one for origin and one for destination for a total of 33 days each (66 days + 2 for first day sits summed together). Which worked when I pushed the entry date back and erased the departure date and I was only able to bill for the remaining 22 days.

2021-02-17 16:04 UTC, merged