[MB-5392] Fix CAT III eslint errors
transcom/mymove pull request #5821
Opened 2021-02-03 20:17 UTC by Ronolibert

## Description

Fixed most instances of CAT III errors

## Code Review Verification Steps
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-5392) for this change

2021-02-04 00:30 UTC, kimallen commented on src/components/DataPoint/index.jsx
> +        {/* eslint-disable react/no-array-index-key */}
In order to keep this disable, do we need annotation for it?

2021-02-04 00:35 UTC, kimallen commented on src/components/form/StackedTableRowForm.jsx
> +  validationSchema: ({ validationSchema }, propName, componentName) => {
I'm confused as to what is happening here.  I thought the proptype was supposed to be definied here. How is it returning a value?

2021-02-04 00:46 UTC, kimallen commented on src/registerServiceWorker.js
> +      const serviceWorkerRegistration = registration;
Should this be a `let` if it's being modified in the next line?
And should `registration` be deep copied here?

I'm a little confused about the explanation 'This is done to avoid an edge case when mutating the argument object.' but then it says this is not an edge case.  Why is it being done then?

2021-02-04 00:56 UTC, kimallen commented on src/components/Table/Table.jsx
> +            /* eslint-disable-next-line react/no-array-index-key */
Does this need annotation?

2021-02-04 00:57 UTC, kimallen commented on src/components/Table/Table.jsx
> +                /* eslint-disable-next-line react/no-array-index-key */
Does this need annotation?

2021-02-04 01:18 UTC, kimallen requested changes
I'm not sure which CAT IIIs are not meant to be addressed here.  I did an audit of remaining `eslint-disable`s.
Here's what I found:

- there's still 2 `no-unused-vars`: `shared/Alert/index.jsx` and `shared/Uploader/index.jsx`
- There's a `no-only-tests`, though it's not listed in the static analysis spreadsheet- we should probably check if it needs to be addressed
- there's 3 places where we do an `es-lint-disable-line` or `es-lint-disable-next-line` where we don't name a rule.  We should enable it and see what the rule is and address it if needed (`Entities/reducer.js`, `validation.test.js`, `JsonSchemaForm/index.test.js`)

I have a few questions inline to address or answer.  Otherwise it looks good!

2021-02-04 01:57 UTC, YanZ777 approved these changes

2021-02-04 16:20 UTC, Ronolibert commented on src/components/form/StackedTableRowForm.jsx
> +  validationSchema: ({ validationSchema }, propName, componentName) => {
This is a way to add custom validation to the proptype check. This is checking that validationSchema is an object that has at least one key/value in it. If it returns null then that means it doesn't error out. We did it this way since validationSchema is a dynamically sized object, and it also has a corresponding defaultProp to ensure that it is an object

2021-02-04 17:54 UTC, amanda5iu approved these changes

2021-02-04 18:04 UTC, kimallen approved these changes
Changes look good!  Thanks for the explanations and addressing requests.

2021-02-04 21:23 UTC, duncan-truss commented on src/testUtils.jsx
> +  history: shape({
This could probably use the HistoryShape you fixed in `src/types/router.js` if we add the goBack function to it.

2021-02-04 21:24 UTC, duncan-truss approved these changes
Nice work this looked tedious 😅

2021-02-05 00:44 UTC, YanZ777 approved these changes

2021-02-08 16:02 UTC, suzubara commented on src/components/form/StackedTableRowForm.jsx
> +  validationSchema: ({ validationSchema }, propName, componentName) => {
this seemed like code smell to me, so I looked into it.. it doesn't look like we are actually using `StackedTableRowForm` in the app anywhere (just Storybook). the component itself is conflating a few different kinds of functionality: rendering a table row, toggling a show/edit form, rendering the form. I do think we should try to avoid using this kind of fn to validate prop types, but in this case since it's not being used, maybe adding a comment to this component to discourage usage (or at least indicate it should be refactored before using) would suffice?

2021-02-08 16:29 UTC, jneuner-mitre requested changes
I'm hung up more on the english sentences in the RA than what we've done on the remaining items.  When we say "Mitigated" the RA: lines need to have
1) What impact/risk is identified by the linter?
2) What are the predisposing conditions?
3) How do the conditions mitigate the risk/impact?

2021-02-08 16:29 UTC, jneuner-mitre commented on src/components/DataPoint/index.jsx
> +        {/* eslint-disable react/no-array-index-key */}
What is preventing us from creating unique ids here?  Unstructured source data?  Limited coding time?

Based on this...
  https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-array-index-key.md
...the first line of the RA block should be...
  "Using the index as an element key in cases where the array is reordered will result in unnecessary renders."

2021-02-08 16:41 UTC, Ronolibert commented on src/components/DataPoint/index.jsx
> +        {/* eslint-disable react/no-array-index-key */}
Updated the annotation! 

I believe this is an unstructured source data situation. The data being iterated over is an array of date strings which commonly has duplicates

2021-02-08 16:44 UTC, Ronolibert commented on src/shared/Entities/reducer.js
> +    // eslint-disable-next-line security/detect-object-injection
I don't have too much extra context, but I think these type of lint errors are automatically mitigated so we don't need to annotate these? I just added the specific rule because I saw it was missing the distinction. The static analysis sheet says this finding type is mitigated for type 1 mobile code

2021-02-08 16:56 UTC, jneuner-mitre commented on src/shared/Entities/reducer.js
> +    // eslint-disable-next-line security/detect-object-injection
Yep, I've got the exception in the [policy](https://ustcdp3.slack.com/files/UPS881M0Q/F01EM4VNS9M/20201117_draft_management_of_source_code_weaknesses.docx) so it can be referenced and applied consistently.  But annotation still goes in the code.  The policy notes are there to make it easier to write the RA: bits.

2021-02-08 17:14 UTC, Ronolibert commented on src/shared/Entities/reducer.js
> +    // eslint-disable-next-line security/detect-object-injection
Ohhh I see! I'll add this

2021-02-08 17:38 UTC, Ronolibert commented on src/shared/Entities/reducer.js
> +    // eslint-disable-next-line security/detect-object-injection
@jneuner-mitre Added this annotation. I just annotated this one instance, but we'll have a card in the future to annotate the rest of the occurrences

2021-02-08 21:16 UTC, jneuner-mitre reviewed
This really isn't convincing me that the problem is mitigated.  The comments are for future assessors that need to be convinced that predisposing conditions have been mitigated by something in the application.  Playing the devil's advocate...

> The key prop is used by React to identify which items have changed, are added, or are removed and should be stable.

Sounds like more work needs to be done.

> There are no other unique identifiers that can be used

You could make one.  Write more code!

2021-02-08 21:16 UTC, jneuner-mitre commented on src/components/DataPoint/index.jsx
> +          // RA Modified Severity:
Is this true?

```suggestion
          // RA Summary: eslint:react/no-array-index-key
          // RA: Using the index as an element key in cases where the array is reordered will result in unnecessary renders.
          // RA: The source data is unstructured, with duplicate values.
          // RA: A reorder function is not implemented for this array.
          // RA Developer Status: Mitigated
          // RA Validator Status: {RA Accepted, Return to Developer, Known Issue, Mitigated, False Positive, Bad Practice}
          // RA Validator: jneuner@mitre.org
          // RA Modified Severity:
```

2021-02-08 21:16 UTC, jneuner-mitre commented on src/components/Table/Table.jsx
> +            // RA Modified Severity:
Is this true?

```suggestion
          // RA Summary: eslint:react/no-array-index-key
          // RA: Using the index as an element key in cases where the array is reordered will result in unnecessary renders.
          // RA: The source data is unstructured, with duplicate values.
          // RA: A reorder function is not implemented for this array.
          // RA Developer Status: Mitigated
          // RA Validator Status: {RA Accepted, Return to Developer, Known Issue, Mitigated, False Positive, Bad Practice}
          // RA Validator: jneuner@mitre.org
          // RA Modified Severity:
```

2021-02-08 21:16 UTC, jneuner-mitre commented on src/components/Table/Table.jsx
> +                // RA Modified Severity:
Is this true?

```suggestion
          // RA Summary: eslint:react/no-array-index-key
          // RA: Using the index as an element key in cases where the array is reordered will result in unnecessary renders.
          // RA: The source data is unstructured, with duplicate values.
          // RA: A reorder function is not implemented for this array.
          // RA Developer Status: Mitigated
          // RA Validator Status: {RA Accepted, Return to Developer, Known Issue, Mitigated, False Positive, Bad Practice}
          // RA Validator: jneuner@mitre.org
          // RA Modified Severity:
```

2021-02-08 21:16 UTC, jneuner-mitre commented on src/shared/Entities/reducer.js
> +    //RA: Uses object square bracket notation
Trying to keep with convention...

```suggestion
    //RA Summary: eslint - security/detect-object-injection
    //RA: Using square bracket notation with user input can lead to exploitation
    //RA: Uses object square bracket notation
```

2021-02-08 22:28 UTC, Ronolibert commented on src/components/DataPoint/index.jsx
> +          // RA Modified Severity:
I removed this annotation. I ended up finding some unique values that the library provided for us

2021-02-08 22:28 UTC, Ronolibert commented on src/components/Table/Table.jsx
> +            // RA Modified Severity:
I removed this annotation. I ended up finding some unique values that the library provided for us

2021-02-08 22:28 UTC, Ronolibert commented on src/components/Table/Table.jsx
> +                // RA Modified Severity:
I removed this annotation. I ended up finding some unique values that the library provided for us

2021-02-08 22:29 UTC, Ronolibert commented on src/shared/Entities/reducer.js
> +    //RA: Uses object square bracket notation
Ah sorry! Noted for the future

2021-02-08 22:32 UTC, Ronolibert commented on src/components/DataPoint/index.jsx
> +          // RA Modified Severity:
I updated the annotation language. Also, on further investigation of the usage, this particular component is being used in static situations where this data never changes

2021-02-09 18:11 UTC, jneuner-mitre approved these changes

2021-02-09 18:12 UTC, jneuner-mitre commented
No more concerns from me.

2021-02-09 20:05 UTC, merged