[WIP][MB-4393] Removing transcom-ppp from .envrc and vault.go
transcom/mymove pull request #5888
Opened 2021-02-11 14:44 UTC by esacteksab

## Description

Originally tried this in #5490 but needed reverted in #5882. 

`transcom-ppp` doesn't exist, and `transcom-com-legacy` is going away. `transcom-gov-*` is the future. Because of the architecture change in AWS, the hard-coded nature of `transcom-ppp` should no longer exist. We do need `AWS_PROFILE` to be set, but it could vary depending on what task is being ran. Hopefully this ensures it is set, but allows it to be anything -- whether or not it's a valid `AWS_PROFILE` is another thing all together, and not something this takes into consideration.

2021-02-11 16:18 UTC, kilbergr requested changes
I still think you want to put the line `export AWS_DEFAULT_REGION="us-gov-west-1"` (182) from .envrc outside the if block to cover the whole env as is done here: https://github.com/transcom/mymove/pull/5490/files.
Unless you're trying to avoid having the default region in the .envrc completely, which should probably be fine, it's just a change in approach. LMK if your intent was to remove as much global hardcoding as possible :)

2021-02-11 16:18 UTC, kilbergr commented on pkg/cli/vault.go
> +		if len(awsProfile) > 0 {
Should this be 
```suggestion
		if len(awsProfile) == 0 {
```
Because you want to make sure that awsProfile DOES exists (IS > 0), right? Please correct if I'm misunderstanding.

2021-02-11 16:18 UTC, kilbergr commented on pkg/cli/vault.go
> -	VaultAWSProfileTranscomComLegacy string = "transcom-com-legacy"
An alternate approach is to add all the other account names here and use those in the `awsProfiles` slice. That would still be hardcoding, though. I don't know if that's really better than what you have here.

2021-02-11 16:20 UTC, esacteksab commented on pkg/cli/vault.go
> -	VaultAWSProfileTranscomComLegacy string = "transcom-com-legacy"
Yeah, then if we add/remove an env, we have to know to update this script, and that feels icky. If we find that we want some mechanism to ensure that we use only specific environments/profiles, then I'm gonna advocate for some other mechanism rather than hard-coding those values here.

2021-02-11 16:20 UTC, esacteksab commented on pkg/cli/vault.go
> +		if len(awsProfile) > 0 {
Off to the playground I go!

2021-02-11 16:28 UTC, esacteksab commented on pkg/cli/vault.go
> +		if len(awsProfile) > 0 {
https://play.golang.org/p/EALIjnmAO9l I think you're right. Did I do my example right?

2021-02-11 17:31 UTC, kilbergr commented on pkg/cli/vault.go
> -	VaultAWSProfileTranscomComLegacy string = "transcom-com-legacy"
Fair fair. Thanks for addressing.

2021-02-11 17:31 UTC, kilbergr commented on pkg/cli/vault.go
> +		if len(awsProfile) > 0 {
Yes -- I think you're understanding what I'm saying.

2021-02-26 15:58 UTC, travelar commented on .envrc
> +export AWS_PROFILE=transcom-gov-base-id
I feel skeptical about this profile, but not a blocker. 🤷

2021-02-26 15:58 UTC, travelar approved these changes

2021-02-26 16:01 UTC, esacteksab commented on .envrc
> +export AWS_PROFILE=transcom-gov-base-id
Admittedly I don't know which one to use. I'm happy to change it if one sticks out in your mind as better. But troubleshooting `aws-vault` this week, `AWS_PROFILE` needs to be set, in my experience, only `transcom-ppp` worked, but I'm hoping we can work past that. :-/

2021-02-26 17:12 UTC, kilbergr commented on .envrc
> +export AWS_PROFILE=transcom-gov-base-id
I'm really not sure what's appropriate here! I think we could either try this out and see what happens OR remove this, then alert people they may have failures, and try to address the failures where they came up. We have been following the second suggestion so far, so I'm prone to favor that. But, as I was telling Barry yesterday, there's still some aspects of aws-vault with direnv that are a bit mysterious to me. I think in those cases where something doesn't work and appears to need `AWS_PROFILE` to work, we should be noting that down and then addressing in the code to make sure it doesn't need `AWS_PROFILE` to work, or that the profile is set explicitly. What do you two think?

2021-02-26 19:59 UTC, esacteksab commented on .envrc
> +export AWS_PROFILE=transcom-gov-base-id
I like the idea of leaving it out. I'll merge this on Monday after notifying as many people as possible before doing so and we'll see what happens, but if there is an opportunity to remove something, we should do it!

2021-03-04 14:14 UTC, kilbergr approved these changes
LGTM...now, we wait.

2021-03-10 21:09 UTC, kilbergr commented
noice. I still approve.

2021-03-10 21:10 UTC, kilbergr commented
omg accidentally closed plz forgive so sorry!!

2021-03-11 15:05 UTC, merged