MB-6578 updateWebhookSubscription
transcom/mymove pull request #5940
Opened 2021-02-19 00:21 UTC by NamibiaLT

## Description

This is part of the Push Deploy work to add a new handler to update webhook subscriptions.

## Reviewer Notes

Please play close attention to the tests for UpdateWebhookSubscription Handler and Service Object

**The endpoint show allow updating of the following fields:**
subscriber_id - not the id of the subscription, but links to which contractor this subscription is related to status (ACTIVE, FAILING, DISABLED), event_key, callback_url, severity

## Setup
To test the endpoint in Postman
1. Add a new collection, which will be this branch `nt-CORRECTED-mb-6578-UpdateWebhookSubscription`
2. Make sure that you are making a PATCH request with url: {{baseUrl}}/webhook_subscriptions
3. Follow [these instructions] (https://github.com/transcom/mymove/wiki/Test-Admin-and-Office-APIs-with-Postman) for copying the correct X-CSRF token into your Header in Postman
4. You should be able to send the request and receive a 200 response.

To run tests

```sh
go test ./pkg/services/webhook_subscription -testify.m TestWebhookSubscriptionUpdater -failfast  -v
go test ./pkg/handlers/adminapi -testify.m TestWebhookSubscriptionUpdater -failfast  -v

```

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-6578) for this change

2021-02-19 01:36 UTC, shimonacarvalho commented on pkg/handlers/adminapi/payloads/payload_to_model.go
> +// WebhookSubscriptionModel represents a webhook subscription
Minor nit - this function converts a webhook subscription payload to a model.

2021-02-19 01:37 UTC, shimonacarvalho commented on pkg/handlers/adminapi/payloads/payload_to_model.go
> +		CreatedAt:    time.Now(),
You can remove CreatedAt and UpdatedAt. Pop will automatically update them. We especially don't want createdAt to be updated everytime the subscription is updated.

2021-02-19 01:38 UTC, shimonacarvalho commented on pkg/handlers/adminapi/payloads/payload_to_model.go
> +		Severity:     int(*sub.Severity),
Don't have the Severity here because if it is nil, there will be a dereference. Your other code on line 46 takes care of this.

2021-02-19 01:41 UTC, shimonacarvalho commented on pkg/handlers/adminapi/webhook_subscriptions.go
> +	logger.Info("got here")
these were for debug, you can take them out :)

2021-02-19 01:43 UTC, shimonacarvalho commented on pkg/handlers/adminapi/webhook_subscriptions.go
> +	updatedWebhookSubscription, err := h.WebhookSubscriptionUpdater.UpdateWebhookSubscription(webhookSubscription, "eTag")
You're passing a string "eTag" here, that seems wrong? I am not sure why that would work actually. 
I'm actually not sure if you need to check the etag on admin api endpoints, we can discuss in slack.

2021-02-19 01:44 UTC, shimonacarvalho commented on pkg/handlers/adminapi/webhook_subscriptions.go
> +		logger.Error(fmt.Sprintf("Error updating webhookSubscription %s", params.WebhookSubscriptionID.String()), zap.Error(err))
If the update failed, probably you want to return some sort of error response? This way it eventually returns an ok, even if the update failed.

2021-02-19 01:47 UTC, shimonacarvalho requested changes
Hi Namibia, that was a lot of work! I've put some review comments that need to be fixed. I didn't look at the tests yet because i think they will need some rework after the changes are made.

2021-02-19 02:18 UTC, shimonacarvalho commented on swagger/admin.yaml
> +    post:
Little unsure why this is showing up here, you didn't add this one right? It should have been there already?

2021-02-19 02:19 UTC, shimonacarvalho commented on swagger/admin.yaml
> +    patch:
Looks good!

2021-02-19 19:18 UTC, eamahanna commented on swagger/admin.yaml
> +    post:
You just need to merge the master branch into this one. Then you will no longer see previous changes. (If that is what this is.)

2021-02-19 23:16 UTC, NamibiaLT commented on pkg/handlers/adminapi/webhook_subscriptions.go
> +		logger.Error(fmt.Sprintf("Error updating webhookSubscription %s", params.WebhookSubscriptionID.String()), zap.Error(err))
After this err check if there was something wrong, would there be another failure that hasn't been checked? Or does this error response need to be more specific?

2021-02-19 23:18 UTC, NamibiaLT commented on swagger/admin.yaml
> +    post:
Hmmm, I don't remember adding anything but the patch, should I remove it? It looks like I added it based on it being green.

2021-02-19 23:18 UTC, NamibiaLT commented on swagger/admin.yaml
> +    patch:
Yay!

2021-02-22 18:55 UTC, shimonacarvalho commented on pkg/handlers/adminapi/webhook_subscriptions.go
> +		logger.Error(fmt.Sprintf("Error updating webhookSubscription %s", params.WebhookSubscriptionID.String()), zap.Error(err))
No I meant this "logger.Error" is just printing something in the logs, you need to return an actual error to the client. See other admin api handlers to see how they return errors (since it's probably a bit different than primeAPI).
```
return webhooksubscriptionop.NewUpdateWebhookSubscriptionInternalServerError...
```

2021-02-22 18:57 UTC, shimonacarvalho commented on pkg/handlers/adminapi/webhook_subscriptions_test.go
> +			WebhookSubscriptionID: strfmt.UUID(webhookSubscription.ID.String()),
Better to update all fields and check that they were updated.

2021-02-22 19:03 UTC, shimonacarvalho commented on pkg/handlers/adminapi/webhook_subscriptions_test.go
> +		suite.Equal(expectedResponse, response)
I'm confused how this would work because the handler has only one return statement as follows:
```
return webhooksubscriptionop.NewUpdateWebhookSubscriptionOK().WithPayload(payload)
```
And that returns OK not an error.

2021-02-22 19:06 UTC, shimonacarvalho commented on pkg/services/webhook_subscription/webhook_subscription_updater.go
> +	if err != nil {
You need to check the precondition before you call updateOne. If the precondition fails, you should not update the subscription.

2021-02-22 19:09 UTC, shimonacarvalho requested changes
Hey there, good work, getting closer but still needs some fixes.

2021-02-22 19:23 UTC, NamibiaLT commented on pkg/handlers/adminapi/webhook_subscriptions_test.go
> +			WebhookSubscriptionID: strfmt.UUID(webhookSubscription.ID.String()),
All fields in the model?

2021-02-22 19:27 UTC, NamibiaLT commented on pkg/handlers/adminapi/webhook_subscriptions_test.go
> +		suite.Equal(expectedResponse, response)
Is this a sufficient error checker?
	// Check that the uuid provided is valid
	if err != nil {
		logger.Error(fmt.Sprintf("Error updating webhookSubscription %s", params.WebhookSubscriptionID.String()), zap.Error(err))
	}

 I thought we return OK() once the model is converted back to a payload.

2021-02-22 20:23 UTC, NamibiaLT commented on pkg/services/webhook_subscription/webhook_subscription_updater.go
> +	if err != nil {
Ok that makes sense. I'll mmove the precondition fail check before updating and update the test.

2021-02-24 18:53 UTC, shimonacarvalho commented on pkg/handlers/adminapi/webhook_subscriptions_test.go
> +			WebhookSubscriptionID: strfmt.UUID(webhookSubscription.ID.String()),
All fields that can be updated should be passed in, and then checked at the end of the test that they were updated correctly.

2021-02-24 18:54 UTC, shimonacarvalho commented on pkg/handlers/adminapi/webhook_subscriptions_test.go
> +		suite.Equal(expectedResponse, response)
Please take out the mocks here. The mock is making it seem like it would return "http.StatusNotFound" but the handler is not returning that, at least that's what we saw when we paired.

2021-02-25 00:36 UTC, shimonacarvalho commented on pkg/services/webhook_subscription/webhook_subscription_updater.go
> +	}
Hmm I'm not sure there should be an & before webhookSubscription.Status (or any of the fields) here. Because that will be the address of that and would never be nil.

2021-02-26 21:59 UTC, NamibiaLT commented on pkg/handlers/adminapi/webhook_subscriptions_test.go
> +		suite.Equal(expectedResponse, response)
See 8693770, it has been removed from the tests

2021-03-01 17:05 UTC, shimonacarvalho commented on pkg/handlers/adminapi/webhook_subscriptions_test.go
> +		suite.IsType(expectedResponse, response)
This test looks identical to the previous test, I might be missing something. Can you explain what is different and why this test returns StatusNotFound, but the previous returns InternalServerError?

2021-03-01 17:05 UTC, shimonacarvalho commented on pkg/services/webhook_subscription/webhook_subscription_updater.go
> +	}
Needs update.

2021-03-01 17:07 UTC, shimonacarvalho commented on pkg/handlers/adminapi/webhook_subscriptions_test.go
> +				CallbackURL:  "something.com",
I tested with postman and if you don't send all the values, you get a validation error. Since this is a patch, it should be okay to send some values but not all.

2021-03-04 18:23 UTC, abbyoung commented
@NamibiaLT This PR can be closed since the rebased branch and final changes were merged in via #6030

2021-03-04 21:05 UTC, closed without merging

2021-03-04 21:05 UTC, shimonacarvalho commented
This PR can be closed since the rebased branch and final changes were merged in via #6030