MB-6771 Create storybook component for "warnings" we'd like to surface on form fields
transcom/mymove pull request #5986
Opened 2021-02-24 18:40 UTC by Shkeating

## Description
Creates a new component to support displaying warnings on particular form fields. 

## Reviewer Notes

I set this up as a new component because its styling was different than the other similar form fields. If I placed the component in a less than ideal location in the repo or in storybook (its currently inside our form directory inside the components folder) let me know! Also I'm not 1000% set on the way I named things, if there is a better way or a best practice to follow, I'm happy to make adjustments.

## Setup

```sh
yarn storybook
```
[http://localhost:6006/?path=/story/components-form--form-group-with-warning](http://localhost:6006/?path=/story/components-form--form-group-with-warning 
)
## Code Review Verification Steps

* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-6771?atlOrigin=eyJpIjoiYjQ2MTU4MzlhNTFlNDEwMWE5YWFhMjI4ZTY5ZmExYWIiLCJwIjoiaiJ9) for this change
* [Zeplin spec](https://app.zeplin.io/project/6006fcf5e144a21206b1baf0/screen/602bf788bb6cf41a28cb49ff) 

## Screenshots
<img width="1205" alt="image" src="https://user-images.githubusercontent.com/59394696/109049026-c7480780-76a5-11eb-8dcb-97a98635bccd.png">

2021-02-24 22:31 UTC, suzubara requested changes
Instead of creating a new component for `FormGroupWarning` (which has a lot of cross-functional concerns), I would recommend just writing a CSS class that can be passed into a `FormGroup` component using the `className` prop (see https://trussworks.github.io/react-uswds/?path=/story/components-form-elements-formgroup--text-input-form-group), and scope all styles to inside of that class. let me know if you'd like to chat more

2021-02-24 22:32 UTC, mariaclaratgolfo approved these changes

2021-02-24 22:33 UTC, mariaclaratgolfo reviewed
Is it possible to add a screenshot in here for how it looks in the context of the document viewer?

2021-02-25 01:48 UTC, YanZ777 commented on src/components/form/FormGroupWarning.stories.jsx
> +    warningMessage="This TAC does not appear in TGET, so might not be valid. Make sure it matches what's on the orders before you continue."
Just me nitpicking, but I think you meant to say "so it might not be valid".

2021-02-25 15:49 UTC, Shkeating commented
> Instead of creating a new component for `FormGroupWarning` (which has a lot of cross-functional concerns), I would recommend just writing a CSS class that can be passed into a `FormGroup` component using the `className` prop (see [docs](https://trussworks.github.io/react-uswds/?path=/story/components-form-elements-formgroup--text-input-form-group)), and scope all styles to inside of that class. let me know if you'd like to chat more

OMG how did I not realize that **FormGroup** can take custom classes 😅 yeah thats a way better idea

2021-02-25 20:39 UTC, suzubara approved these changes
looks good!

2021-02-25 20:41 UTC, merged