Kim mb 6716 show tac validation warning
transcom/mymove pull request #6005
Opened 2021-02-27 00:59 UTC by kimallen

## Description

This connects the TAC field on the orders edit form in the TxO Office to the tac validation api.  If the entered TAC is invalid, it will show the warning message and styling.  This occurs on blur and when first opening the edit form.  

## Reviewer Notes

This does not include the "bad format" error message for when the value is less than 4 digits.

Do I need more tests?  Where?

## Setup

Log in as a TOO and view a move.
Go to "View and edit orders"
Enter an "invalid" Tac (right now hardcoded in the api: any of ["2LGT", "4EVR", "5ALV", "MOBTR"]).
You should see the warning appear.
Submit.
Return to the "View and edit orders" and see the warning persist.
Add a valid tac.  See the warning disappear.

## Code Review Verification Steps

* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-6520) for this change

## Screenshots

![image](https://user-images.githubusercontent.com/13249580/109369807-cbfdee80-7852-11eb-8e88-0cb97c777617.png)

I couldn't get Giphy Capture to open my recording.

2021-03-01 16:31 UTC, suzubara reviewed
I keep getting this JS error when loading the Edit Orders page:
![image](https://user-images.githubusercontent.com/2723066/109526789-92a6c800-7a78-11eb-9e2d-f5c49865cfee.png)

I think `moveOrder` was recently renamed to `order` everywhere, and renaming this operation to `order.tacValidation` seems to fix it.

2021-03-01 17:02 UTC, duncan-truss commented on src/components/Office/OrdersDetailForm/OrdersDetailForm.jsx
> +      <TextInput name="tac" label="TAC" id="tacInput" warning={tacWarning} onBlur={handleTacBlur} />
Instead of using onBlur like this I think we could use the [validate prop for Formik fields](https://formik.org/docs/guides/validation#validate-1) and then pass in your validateTac handle func to it.

Doing this we could move to onChange validation, which would make sure the office user sees the error prior to submitting the form and would show the warning on initial load of the data.

2021-03-01 17:14 UTC, suzubara requested changes

2021-03-01 17:14 UTC, suzubara commented on src/pages/Office/MoveOrders/MoveOrders.jsx
> +            validateTac(formik.values.tac);
this is resulting in the validation running every time this component re-renders. Since you are just trying to validate the initial value, this should only happen when `moveOrder` is first loaded. You can achieve this with the `useEffect` hook (above the return block):

```
useEffect(() => {
  if (moveOrder?.tac) validateTac(moveOrder.tac)
}, [moveOrder])
```

2021-03-01 17:14 UTC, suzubara commented on src/components/form/fields/TextInput.test.jsx
> +      const wrapperWarning = shallow(
This test is failing, I believe because the mock of Formik at the top of this file is setting an error on the field.

2021-03-01 17:37 UTC, kimallen commented
> I keep getting this JS error when loading the Edit Orders page:
> ![image](https://user-images.githubusercontent.com/2723066/109526789-92a6c800-7a78-11eb-9e2d-f5c49865cfee.png)
> 
> I think `moveOrder` was recently renamed to `order` everywhere, and renaming this operation to `order.tacValidation` seems to fix it.

Thank you- that seemed to work.  Fixed!

2021-03-02 00:13 UTC, kimallen commented on src/components/form/fields/TextInput.test.jsx
> +      const wrapperWarning = shallow(
I ended up testing the render of the warning in the `DetailOrderForm` test.  Mocking formik for the `TextInputMinimal` with a warning and no error proved overly complicated.

2021-03-02 00:49 UTC, kimallen commented on src/pages/Office/MoveOrders/MoveOrders.jsx
> +            validateTac(formik.values.tac);
Done.

2021-03-02 16:02 UTC, brooksr4 approved these changes

2021-03-03 22:08 UTC, suzubara approved these changes
looks good!

2021-03-03 23:07 UTC, merged