Nt mb 5501 cancel shipment
transcom/mymove pull request #6096
Opened 2021-03-11 00:28 UTC by NamibiaLT

## Description

Add CANCELLATION_REQUESTED to the enum definitions in support.yaml and prime.yaml for `UpdateMTOShipment`. 

Add a test to make sure that a mto_shipment status can be updated to cancellation_requested 

## Reviewer Notes

The eTag does not match the IfMatch header value and is returning a precondition failed. This is a blocker for me that I am trying to work through.

## Setup

To run the test:

```sh
go test ./pkg/handlers/supportapi --testify.m "TestUpdateMTOShipmentHandler"

```

## Code Review Verification Steps

* [ ] If the change is risky, it has been tested in experimental before merging.
* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] The requirements listed in [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely) have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://github.com/transcom/mymove/wiki/migrate-the-database#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-5501) for this change

## Screenshots

2021-03-11 23:07 UTC, NamibiaLT commented
Updated test. It is passing. This is the final PR. Ready for review.

2021-03-11 23:17 UTC, shimonacarvalho commented on pkg/handlers/supportapi/mto_shipment_test.go
> +		suite.NotEmpty(okResponse, supportmessages.UpdateMTOShipmentStatusStatusCANCELLATIONREQUESTED)
I don't understand this use of suite.NotEmpty. 
suite.NotEmpty should check that the first argument is not empty (aka not nil, "" etc...) and then use the second argument as a message string. So this use above doesn't quite make sense.

2021-03-11 23:17 UTC, shimonacarvalho commented on pkg/handlers/supportapi/mto_shipment_test.go
> +		mto := testdatagen.MakeMove(suite.DB(), testdatagen.Assertions{Move: models.Move{Status: models.MoveStatusAPPROVED}})
Could you add the comment describing what this test is testing, what's expected at the end etc?

2021-03-11 23:18 UTC, shimonacarvalho commented on pkg/handlers/supportapi/mto_shipment_test.go
> +		response := handler.Handle(params)
Good job adding the params.Body.Validate check here!

2021-03-11 23:19 UTC, shimonacarvalho commented on pkg/handlers/supportapi/mto_shipment_test.go
> +		suite.Equal(supportmessages.UpdateMTOShipmentStatusStatusCANCELLATIONREQUESTED, okResponse.Payload.Status)
This is a good check here.

2021-03-11 23:20 UTC, shimonacarvalho requested changes
Some changes requested.

2021-03-12 19:35 UTC, NamibiaLT reviewed
@shimonacarvalho thanks for the feedback! I made some comments to some of the review comments. Should I remove the suite.NotEmpty test you commented on, or keep it there and merge the changes?

2021-03-12 19:35 UTC, NamibiaLT commented on pkg/handlers/supportapi/mto_shipment_test.go
> +		mto := testdatagen.MakeMove(suite.DB(), testdatagen.Assertions{Move: models.Move{Status: models.MoveStatusAPPROVED}})
Yes, the file has been updated with comments.

2021-03-12 19:35 UTC, NamibiaLT commented on pkg/handlers/supportapi/mto_shipment_test.go
> +		response := handler.Handle(params)
Thank you!

2021-03-12 19:35 UTC, NamibiaLT commented on pkg/handlers/supportapi/mto_shipment_test.go
> +		suite.NotEmpty(okResponse, supportmessages.UpdateMTOShipmentStatusStatusCANCELLATIONREQUESTED)
I had seen it used in a similar test, so added it just in case, but I can remove it since there are two other tests that are testing the new update option:
suite.Equal(supportmessages.UpdateMTOShipmentStatusStatusCANCELLATIONREQUESTED, okResponse.Payload.Status)
		suite.NotZero(okResponse.Payload.ETag)

2021-03-12 21:00 UTC, shimonacarvalho commented on pkg/handlers/supportapi/mto_shipment_test.go
> +		suite.NotEmpty(okResponse, supportmessages.UpdateMTOShipmentStatusStatusCANCELLATIONREQUESTED)
Yes I would remove it.

2021-03-12 22:17 UTC, shimonacarvalho approved these changes

2021-03-15 16:38 UTC, NamibiaLT commented
Thanks for the review @shimonacarvalho !

2021-03-15 16:38 UTC, merged