[MB-4740] TOO cannot approve Move without updating Orders information
transcom/mymove pull request #6142
Opened 2021-03-16 21:44 UTC by jenniferlynparsons

## Description

When the state of the orders table isn’t valid the button the TOO would use to approve the move and shipments button is disabled.

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

```sh
make server_run
make office_client_run
```

## Code Review Verification Steps

* [ ] If the change is risky, it has been tested in experimental before merging.
* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] The requirements listed in [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely) have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://github.com/transcom/mymove/wiki/migrate-the-database#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-4740) for this change

2021-03-16 21:45 UTC, jenniferlynparsons commented on src/components/Office/RequestedShipments/RequestedShipments.test.jsx
> +import { SHIPMENT_OPTIONS, MTOAgentType, MOVE_STATUSES } from 'shared/constants';
More constants, less strings!

2021-03-16 21:45 UTC, jenniferlynparsons commented on src/pages/Office/MoveDetails/MoveDetails.jsx
> +  const hasMissingOrdersRequiredInfo = Object.values(requiredOrdersInfo).some((value) => !value || value === '');
Happiness is refactoring code you wrote last week into something much more streamlined.

2021-03-17 16:39 UTC, duncan-truss commented on src/components/Office/RequestedShipments/RequestedShipments.test.jsx
> +import MOVE_STATUSES from '../../../constants/moves';
Yay so many fewer magic strings 🎉

2021-03-18 13:41 UTC, jenniferlynparsons commented
I self-reviewed Happo because there weren't actually any changes.

2021-03-18 17:21 UTC, duncan-truss commented on src/components/Office/RequestedShipments/RequestedShipments.jsx
> +  missingRequiredOrdersInfo: false,
We keep adding optional props here (I had to on my branch as well) because this component serves as both the approve requested shipments form and the approved shipments display.  I think splitting them into separate components would be a good refactor when we get the chance what do you think?

2021-03-18 17:23 UTC, jenniferlynparsons commented on src/components/Office/RequestedShipments/RequestedShipments.jsx
> +  missingRequiredOrdersInfo: false,
Yes. That sounds like a great idea!

2021-03-18 19:00 UTC, duncan-truss approved these changes
Works as expected! I did have to create a new move from scratch because we're always filling in the orders data in our testdata seeds.  It would be good to create some new moves with only the the orders fields populated by the customer side.

2021-03-18 19:09 UTC, jenniferlynparsons commented
> Works as expected! I did have to create a new move from scratch because we're always filling in the orders data in our testdata seeds. It would be good to create some new moves with only the the orders fields populated by the customer side.

Brought this up in slack as a potential chore so this can be merged and keep this sprint moving along.

2021-03-18 19:14 UTC, brooksr4 reviewed
We need a test case with the TAC empty

2021-03-18 19:15 UTC, brooksr4 requested changes
We need a test case with the Tac missing for design to review

2021-03-19 16:09 UTC, duncan-truss commented on pkg/testdatagen/scenario/devseed.go
> +	models.SaveMoveDependencies(db, &move)
These will get flagged in static analysis if we don't check the return value for errors I think although I see it's not checked elsewhere in the file.  I've also seen this fail silently and then the test data is not what we think it is.

2021-03-19 16:43 UTC, monfresh commented on pkg/testdatagen/scenario/devseed.go
> +	models.SaveMoveDependencies(db, &move)
Did you want multiple shipments, as well as a PPM move on purpose? If not, if you just want a move whose Order doesn't have a TAC, I think this can be simplified to this:
```golang
move := testdatagen.MakeHHGMoveWithShipment(db, testdatagen.Assertions{
    Move: models.Move{
        Locator: "NILTAC",
   },
})
order := move.Orders
order.TAC = nil
verrs, err := models.SaveMoveDependencies(db, &move)
if verrs.HasAny() || err != nil {
    logger.Error("errors encountered saving move and its dependencies", zap.Error(err))
}
```

2021-03-19 17:24 UTC, monfresh commented on pkg/testdatagen/scenario/devseed.go
> +			TAC:              models.StringPointer("F8E1"),
It should not be necessary to specify the TAC and OrdersNumber each time since they get populated by default if they are not specified.

2021-03-19 17:25 UTC, jenniferlynparsons commented on pkg/testdatagen/scenario/devseed.go
> +			TAC:              models.StringPointer("F8E1"),
Yes! I had added them on an earlier iteration. I'll clean that up.

2021-03-19 19:30 UTC, brooksr4 approved these changes
Looks good!

2021-03-19 19:32 UTC, merged

2021-03-20 00:36 UTC, monfresh commented on pkg/testdatagen/scenario/devseed.go
> +	models.SaveMoveDependencies(db, &move)
This move is not appearing in the TOO queue. When I look at it in TablePlus, I can see that it still has a status of DRAFT. How did you test this locally? I don't see any other orders with missing information, so I'm confused as to how y'all tested this PR.

2021-03-20 00:50 UTC, monfresh commented on pkg/testdatagen/scenario/devseed.go
> +	models.SaveMoveDependencies(db, &move)
I fixed it in my PR, and I also made sure to remove all the other required fields to make it easier to test that you can't approve the Move with one missing field at a time.

2021-03-22 13:29 UTC, monfresh commented on pkg/testdatagen/scenario/devseed.go
> +	models.SaveMoveDependencies(db, &move)
My bad. The confusion was because I was testing this on my branch, where the Orders validation caused the `SaveMoveDependencies` to silently fail and didn't create this move. I apologize if my tone sounded accusatory.