MB-7019 create storybook component for contact info fieldset
transcom/mymove pull request #6145
Opened 2021-03-16 23:13 UTC by YanZ777

## Description

Add new storybook component that holds the phone number, alternate phone number, email, and option for selecting preferred contact method.

## Reviewer Notes

This is currently being merged to `sr-7020-residential-address-fieldset` since I wanted to grab some changes from there while working on this story.

CSS! 
Did I put the component in the correct location? It's currently under: `components/Fieldsets/ServiceMemberContactInfoFields`

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

```sh
make storybook
make client_test
```

## Code Review Verification Steps

* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-7019) for this change

## Screenshots

If this PR makes visible UI changes, an image of the finished UI can help reviewers and casual
observers understand the context of the changes. A before image is optional and
can be included at the submitter's discretion.

Consider using an animated image to show an entire workflow instead of using multiple images. You may want to use GIPHY CAPTURE for this! 📸

_Please frame screenshots to show enough useful context but also highlight the affected regions._

![image](https://user-images.githubusercontent.com/6477059/111391596-2fb95180-8672-11eb-8e15-34f737e7811d.png)
![image](https://user-images.githubusercontent.com/6477059/111391670-537c9780-8672-11eb-8e37-03aec9046815.png)

2021-03-17 19:59 UTC, suzubara requested changes
this is mostly there, I made some suggestions for improvements! the most important thing is to get the Formik integration because that will ensure the inputs are hooked up to whatever form they're rendered in correctly

2021-03-17 19:59 UTC, suzubara commented on src/components/form/ServiceMemberContactInfoFields/ServiceMemberContactInfoFields.module.scss
> +}
I was kind of hoping no CSS would be needed for this story! are you able to get the desired layout using the existing [generic form CSS](https://github.com/transcom/mymove/blob/master/src/styles/form.module.scss)? We might need to expand on the `.radioGroup` so it's usable for inline checkboxes also.

We also shouldn't need to set any `width` on elements, that can be controlled using the `Grid` components provided by ReactUSWDS. There's a bunch of Storybook examples [here](https://storybook.dp3.us/?path=/story/design-system_components-grid--default-container) and the AddressFields also uses this to put the state & zip fields side-by-side

2021-03-17 19:59 UTC, suzubara commented on src/components/form/ServiceMemberContactInfoFields/index.jsx
> +            onChange={onChangePreferEmail}
For the Checkboxes, they should be hooked up to Formik like the `TextField` component is, and don't need to be passed an explicit `onChange` handler.

Since there's no corresponding `CheckboxField` component, you could use Formik's `<Field />` ([docs](https://formik.org/docs/api/field)), with the `as={Checkbox}` prop so it renders ReactUSWDS's Checkbox, or you could also set up a CheckboxField component if you want (although I imagine it wouldn't include extra markup like the TextField does).

Formik also provides an example of using `<Field />` with checkbox inputs: https://formik.org/docs/examples/checkboxes

2021-03-17 19:59 UTC, suzubara commented on src/components/form/ServiceMemberContactInfoFields/index.jsx
> +  const ServiceMemberContactInfoFieldsUUID = uuidv4();
I just made this update to AddressFields, but this value should be stored in a `useRef`, otherwise the uuid will change on every render (ie, whenever you type into the input). you can see my example here: https://github.com/transcom/mymove/pull/6139/files#diff-b110391453e762afa87747ad47ef60e098df61390d930a6cc049d02170c04b11R64

2021-03-17 22:35 UTC, Shkeating commented on src/components/form/ServiceMemberContactInfoFields/ServiceMemberContactInfoFields.module.scss
> +      width: 61%;
this value needs to be equal to the one you set at line 8 in order for the optional tag be aligned with the end of the field

<img width="220" alt="image" src="https://user-images.githubusercontent.com/59394696/111547348-6749fb80-874f-11eb-9839-d7630d87c0b0.png">

2021-03-17 22:35 UTC, Shkeating commented on src/components/form/ServiceMemberContactInfoFields/ServiceMemberContactInfoFields.module.scss
> +      width: 61%;
but also listen to suz if u are ditching the css file altogether ~

2021-03-17 23:58 UTC, YanZ777 commented on src/components/form/ServiceMemberContactInfoFields/ServiceMemberContactInfoFields.module.scss
> +      width: 61%;
Does the optional tag need to be aligned with the end of the field? The [Zeplin](https://app.zeplin.io/project/5f80b1b3ec80a85f303afe20/screen/5fca9f5d2c500143eddd9a81) made it look like it shouldn't be, but it does make my life easier if it _does_ need to be aligned.

2021-03-18 01:44 UTC, YanZ777 commented on src/components/form/ServiceMemberContactInfoFields/index.jsx
> +            onChange={onChangePreferEmail}
I'm still working on this part. I think I'll create a CheckboxField component so that way it can be used in other forms as well.

2021-03-18 16:05 UTC, suzubara commented on src/components/form/ServiceMemberContactInfoFields/ServiceMemberContactInfoFields.module.scss
> +      width: 61%;
I'm guessing the Zeplin is mistaken.. this should probably use the same "Optional" treatment as demonstrated in the [kitchen sink form example](https://storybook.dp3.us/?path=/story/components-forms--kitchen-sink-form)

2021-03-18 22:33 UTC, suzubara approved these changes
looks great to me!

2021-03-18 22:33 UTC, suzubara commented on src/components/form/ServiceMemberContactInfoFields/ServiceMemberContactInfoFields.stories.jsx
> +          onChangePreferEmail={action('clicked')}
can these be removed since these props don't exist anymore in this component?

2021-03-18 22:41 UTC, YanZ777 commented on src/components/form/ServiceMemberContactInfoFields/ServiceMemberContactInfoFields.stories.jsx
> +          onChangePreferEmail={action('clicked')}
Yes!

2021-03-19 18:01 UTC, Shkeating approved these changes
lookin goood

2021-03-19 19:21 UTC, amanda5iu approved these changes
Looking good ✨

2021-03-19 19:57 UTC, merged