Replace div with button and adjust styling
transcom/mymove pull request #6266
Opened 2021-03-30 20:39 UTC by kimallen

## Description

This replaces the div with a button element.  It adapts the styles to match the original styles and removes the `onKeyPress` handling that the button handles automatically.

## Reviewer Notes

I made the button background color transparent-- should i make it match the color of the background instead?

## Setup

Go to a Customer that has multiple shipments (`nts@ntsr.unsubmitted `) or create multiple shipments.  See the list of shipments on the Home page.  The visual should not be different than before.  I added cursor pointer as well.

## Code Review Verification Steps

* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-4929) for this change

## Screenshots

2021-03-31 16:57 UTC, Shkeating requested changes

2021-03-31 16:57 UTC, Shkeating commented on src/components/Customer/Home/ShipmentList/ShipmentList.module.scss
>    strong {
<img width="327" alt="image" src="https://user-images.githubusercontent.com/59394696/113182042-72595d00-9220-11eb-816f-fdb2f426b20e.png">
I'm noticing the next in the `strong` tag is not left aligned like they were before. To remediate this, add `text-align: left;` to your scss for the `strong`text in this component.

2021-03-31 20:53 UTC, suzubara approved these changes
other than @Shkeating 's comment, looks good to me!

2021-03-31 23:43 UTC, kimallen commented on src/components/Customer/Home/ShipmentList/ShipmentList.module.scss
>    strong {
Nice- fixed!

2021-04-01 21:06 UTC, Shkeating approved these changes
![looks good to me!](https://media2.giphy.com/media/3fyODM0X8lrO0/giphy.gif?cid=ecf05e47ya06oemh0cf0f53hnl4d7o3fktqdolabemxg0n2j&rid=giphy.gif)

looks good!

2021-04-01 21:08 UTC, merged