MB-5883 Create page for Service Member to edit all contact info
transcom/mymove pull request #6407
Opened 2021-04-14 01:05 UTC by felipe-lee

## Description

Add a page (and underlying form component) that allows a service member to edit all of their contact information (phone, email, preferences, residential address, backup address, and backup contact).

## Reviewer Notes

Still working on this, just putting it out here for more eyes if anyone has time.

A few things:
1. The styling for the top form doesn't match the specs, but I'm using the existing styling which is used on the onboarding forms. Should this be updated to affect all? Or should this form in particular use different styling?
2. I had to modify `src/components/form/BackupContactInfoFields/index.jsx` because the phone field clashed with the main contact (SM) phone field. I did it this way to allow namespacing it optionally, and hopefully so it wouldn't affect existing usages (they seem fine to me, but I could be wrong of course). Does this seem ok, or should I do this another way?

## Setup

1. Run storybook:

    ```sh
    make storybook
    ```

2. Navigate to [Customer Components / Forms / EditContactInfoForm](http://localhost:6006/?path=/story/customer-components-forms-editcontactinfoform--default-state)

## Code Review Verification Steps

* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-5883) for this change

## Screenshots

### Storybook

#### Desktop
![Screen Shot 2021-04-13 at 19 56 25](https://user-images.githubusercontent.com/35938642/114638958-57600180-9c92-11eb-8994-bf674396dc1c.png)
![Screen Shot 2021-04-13 at 19 58 12](https://user-images.githubusercontent.com/35938642/114639056-94c48f00-9c92-11eb-8c1a-90496744f1e5.png)

#### Mobile
![Screen Shot 2021-04-13 at 19 58 59](https://user-images.githubusercontent.com/35938642/114639117-b160c700-9c92-11eb-8e4f-9ea427197073.png)
![Screen Shot 2021-04-13 at 19 59 11](https://user-images.githubusercontent.com/35938642/114639129-b887d500-9c92-11eb-91db-0b151cccb26f.png)
![Screen Shot 2021-04-13 at 19 59 23](https://user-images.githubusercontent.com/35938642/114639135-bf164c80-9c92-11eb-969c-d7ed77b74efd.png)
![Screen Shot 2021-04-13 at 19 59 31](https://user-images.githubusercontent.com/35938642/114639150-c3db0080-9c92-11eb-893f-d0e78b0f0ff7.png)

2021-04-14 01:09 UTC, YanZ777 commented on src/components/Customer/EditContactInfoForm/EditContactInfoForm.jsx
> +                If we can‘t reach you, who can we contact? Any person you assign as a backup contact must be 18 years of
Minor nit: Should &apos; be used here?

2021-04-14 01:11 UTC, YanZ777 commented on src/components/Customer/EditContactInfoForm/EditContactInfoForm.jsx
> +    [residentialAddressName]: ResidentialAddressShape.isRequired,
Maybe not super relevant to the PR here, but what is the difference between an AddressShape and a ResidentialAddressShape?

2021-04-14 01:13 UTC, YanZ777 commented on src/components/Customer/EditContactInfoForm/EditContactInfoForm.test.jsx
> +  it('renders the form inputs', async () => {
Test ALL the fields!
Nicely done though!

2021-04-14 01:14 UTC, felipe-lee commented on src/components/Customer/EditContactInfoForm/EditContactInfoForm.test.jsx
> +  it('renders the form inputs', async () => {
Yeah...I'd done it more automated, but one of the pre-commit things didn't like it, so now it's fully spelled out haha.

2021-04-14 01:16 UTC, felipe-lee commented on src/components/Customer/EditContactInfoForm/EditContactInfoForm.jsx
> +                If we can‘t reach you, who can we contact? Any person you assign as a backup contact must be 18 years of
I'll switch it to `&apos;` to match the others on the page. Had copy/pasted this from elsewhere initially.

2021-04-14 01:17 UTC, felipe-lee commented on src/components/Customer/EditContactInfoForm/EditContactInfoForm.jsx
> +    [residentialAddressName]: ResidentialAddressShape.isRequired,
`AddressShape` has a street address 3 field, and a country field.

2021-04-14 01:21 UTC, YanZ777 commented on src/components/Customer/EditContactInfoForm/EditContactInfoForm.jsx
> +    [residentialAddressName]: ResidentialAddressShape.isRequired,
I guess my follow up question then would be: When should one be used vs the other?

2021-04-14 20:18 UTC, felipe-lee commented on src/components/Customer/EditContactInfoForm/EditContactInfoForm.jsx
> +    [residentialAddressName]: ResidentialAddressShape.isRequired,
That's a good question. I created `ResidentialAddressShape` a few weeks ago because I was re-using the same prop types in a few places. I didn't use `AddressShape` because there were more fields than what I needed for my components.

2021-04-15 16:23 UTC, suzubara reviewed
this is looking great so far! to answer your questions, I think the input sizes should be consistent on this page & the onboarding Contact Info page, but maybe double check with @transcom/truss-design ? And adding the optional namespace is a great addition to the backup contact fields 🎉

2021-04-15 16:24 UTC, suzubara commented on src/components/Customer/EditContactInfoForm/EditContactInfoForm.jsx
> +              <h2>Your conatct info</h2>
typo: `contact`

2021-04-16 23:34 UTC, kimallen requested changes
I'm getting some weird behavior on saving.  If I save the backup contact, it doesn't seem to save.  But then if I try again, it display the previous value that I had saved.  It appears that there is an array of BackupContact records returned from the API, and it's showing the older record rather than the newer record.

2021-04-16 23:34 UTC, kimallen commented on src/components/form/BackupContactInfoFields/BackupContactInfoFields.test.jsx
> +    expect(screen.getByText('Backup contact')).toBeInstanceOf(HTMLLegendElement);
I'm curious what the difference is between using `screen` and not using screen?  Did they fail without `screen`?

2021-04-16 23:34 UTC, kimallen commented on src/constants/routes.js
> +  CONTACT_INFO_EDIT_PATH: '/moves/review/edit-contact-info',
Not needed to change here, and I know it's what's in the copy spreadsheet, but I still think it's strange that we use `/review` in these paths instead of just `/moves/edit-contact-info`

2021-04-17 00:42 UTC, YanZ777 commented on src/components/form/BackupContactInfoFields/BackupContactInfoFields.test.jsx
> +    expect(screen.getByText('Backup contact')).toBeInstanceOf(HTMLLegendElement);
@felipe-lee Has an explanation for using screen in [this PR](https://github.com/transcom/mymove/pull/6403#discussion_r613588463). 
Quoted here for convenience: 
> Also you can use screen to access all the queries instead of using const { <query> } = render(...) so that you don't have to change anything render returns and can easily switch what queries you use (or add new ones).

2021-04-17 04:37 UTC, YanZ777 commented on src/pages/MyMove/Profile/EditContactInfo.jsx
> +  serviceMember: PropTypes.shape({
There is a serviceMember shape that I think you can use if you just add the residential address shapes to it.

2021-04-19 15:30 UTC, amanda5iu commented
Looking good for the most part! Only comment is for the `Your contact info` and `Current mailing address` forms, there should only be 24px padding between the h2 and the first input. Right now it looks like 56px and 44px, respectively.
![Screen Shot 2021-04-19 at 10 26 16 AM](https://user-images.githubusercontent.com/38052749/115262578-4b44cb80-a0fa-11eb-98c4-7f5bd54c86f4.png)
![Screen Shot 2021-04-19 at 10 26 23 AM](https://user-images.githubusercontent.com/38052749/115262580-4c75f880-a0fa-11eb-8f03-010315c4559c.png)

2021-04-19 23:39 UTC, YanZ777 commented
> I'm getting some weird behavior on saving. If I save the backup contact, it doesn't seem to save. But then if I try again, it display the previous value that I had saved. It appears that there is an array of 2 of BackupContact records returned from the API, and it's showing the older record array[0] rather than the newer record array[1].

I'm having trouble reproducing this behavior, can you give more details @kimallen? 
(I can see how it would be a bug since we're only getting the first backup contact.)

2021-04-20 16:46 UTC, felipe-lee commented on src/constants/routes.js
> +  CONTACT_INFO_EDIT_PATH: '/moves/review/edit-contact-info',
Same

2021-04-20 16:47 UTC, felipe-lee commented on src/components/Customer/EditContactInfoForm/EditContactInfoForm.test.jsx
> +  it('implements the onBack handler when the Back button is clicked', async () => {
Yup, I'll change that.

2021-04-20 16:49 UTC, felipe-lee commented on src/pages/MyMove/Profile/EditContactInfo.jsx
> +  serviceMember: PropTypes.shape({
I wasn't sure if this would mess up places that already use that shape but don't have address info. I guess the only places that would really happen though is in the onboarding steps, and it looks like nothing complained

2021-04-20 20:10 UTC, felipe-lee commented on src/components/Customer/EditContactInfoForm/EditContactInfoForm.module.scss
> +    }
This feels kind of hacky because I'm essentially undoing what https://github.com/transcom/mymove/blob/a8951f5a7d44af109dc5c7dca382bb8c1906a314/src/styles/form.module.scss#L102-L105
is doing, but idk how else to do it without breaking the CSS for other pages that need it to actually do what it's doing right now.

2021-04-20 20:16 UTC, felipe-lee commented
> I'm getting some weird behavior on saving. If I save the backup contact, it doesn't seem to save. But then if I try again, it display the previous value that I had saved. It appears that there is an array of 2 of BackupContact records returned from the API, and it's showing the older record array[0] rather than the newer record array[1].

Commenting for those seeing the PR. We found that it's more an issue with our data, probably, in that we currently don't really account for the possibility of a service member having more than one backup contact. But, our local devseed data can get into a state where a sm can have multiple backup contacts. Slack thread asking for more input, but for now, no change is planned in the code introduced in this pr (other than to maybe fix the devseed issue if we get feedback on the thread).

2021-04-20 20:17 UTC, felipe-lee commented
> Looking good for the most part! Only comment is for the `Your contact info` and `Current mailing address` forms, there should only be 24px padding between the h2 and the first input. Right now it looks like 56px and 44px, respectively.
> ![Screen Shot 2021-04-19 at 10 26 16 AM](https://user-images.githubusercontent.com/38052749/115262578-4b44cb80-a0fa-11eb-98c4-7f5bd54c86f4.png)
> ![Screen Shot 2021-04-19 at 10 26 23 AM](https://user-images.githubusercontent.com/38052749/115262580-4c75f880-a0fa-11eb-8f03-010315c4559c.png)

@amanda5iu I think I've fixed these now.

2021-04-20 20:49 UTC, kimallen approved these changes
Glad we figured out the multiple backup contacts issue! LGTM!

2021-04-20 21:29 UTC, YanZ777 approved these changes

2021-04-21 16:54 UTC, amanda5iu approved these changes
Looking good!

2021-04-21 17:32 UTC, merged