[MB-7376] Add Price Difference in Cents and  Fuel Surcharge Multiplier Service Item Param Keys for FSC surcharge price
transcom/mymove pull request #6418
Opened 2021-04-14 16:55 UTC by harshamurthy

## Description

Explain a little about the changes at a high level.

## Reviewer Notes

Is there anything you would like reviewers to give additional scrutiny?

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

```sh
echo "Code goes here"
```

## Code Review Verification Steps

* [ ] If the change is risky, it has been tested in experimental before merging.
* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] The requirements listed in [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely) have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://github.com/transcom/mymove/wiki/migrate-the-database#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](tbd) for this change
* [this article](tbd) explains more about the approach used.

## Screenshots

If this PR makes visible UI changes, an image of the finished UI can help reviewers and casual
observers understand the context of the changes. A before image is optional and
can be included at the submitter's discretion.

Consider using an animated image to show an entire workflow instead of using multiple images. You may want to use GIPHY CAPTURE for this! 📸

_Please frame screenshots to show enough useful context but also highlight the affected regions._

2021-04-15 14:16 UTC, reggieriser requested changes
The database migration seems to apply fine and generally looks OK -- just had a naming/type question.

I was surprised to see the pricer params already being built in the pricer itself since there's [another unstarted story](https://dp3.atlassian.net/browse/MB-6832) for that in next week's sprint.  If we are combining them, we'll want to update tests here to validate the params are coming back as expected from the pricer.  See some of the other pricer param PRs for examples.

I also think we're missing some updates to swagger enums (see `ServiceItemParamName` in `ghc.yaml` and `prime.yaml`) where these keys are listed.

2021-04-15 14:16 UTC, reggieriser commented on pkg/services/ghcrateengine/fuel_surcharge_pricer.go
> +		{Key: models.ServiceItemParamNameFSCPriceDifferenceInCents, Value: FormatCents(unit.Cents(fscPriceDifferenceInCents))},
I think `fscPriceDifferenceInCents` is a floating point number here.  I believe converting it to a `unit.Cents` will just drop the fractional part instead of rounding (see [Go Playground](https://play.golang.org/p/Ew2RC_RtYxk)).  I would think we'd want rounding here.

2021-04-16 16:54 UTC, harshamurthy commented on migrations/app/schema/20210414170143_add_FSC_service_item_param_keys.up.sql
> +('6ba0aeca-19f8-4247-a317-fffa81c5d5c1', 'FSCPriceDifferenceInCents', 'Difference in price between the weekly national average EIA fuel price and the base GHC diesel fuel price of $2.50', 'DECIMAL',
The multiplier itself which is what we want to display is an integer since it's not really cents, but the actual number of cents. So we would want to display it like `23 cents` instead of `0.23 cents` I would think.

2021-04-16 16:55 UTC, harshamurthy commented on migrations/app/schema/20210414170143_add_FSC_service_item_param_keys.up.sql
> +('6ba0aeca-19f8-4247-a317-fffa81c5d5c1', 'FSCPriceDifferenceInCents', 'Difference in price between the weekly national average EIA fuel price and the base GHC diesel fuel price of $2.50', 'DECIMAL',
Also, what I just said may make no sense at all 😅 so happy to talk it through!

2021-04-16 20:30 UTC, reggieriser reviewed
We're close -- just a few more small things before final approval.

2021-04-16 20:30 UTC, reggieriser commented on migrations/app/schema/20210414170143_add_FSC_service_item_param_keys.up.sql
> +('6ba0aeca-19f8-4247-a317-fffa81c5d5c1', 'FSCPriceDifferenceInCents', 'Difference in price between the weekly national average EIA fuel price and the base GHC diesel fuel price of $2.50', 'DECIMAL',
@harshamurthy and I talked about this and I was misunderstanding how this is used in the calculation based on what I was seeing in the FSC UI on the front end.  Per Harsha, we multiply by a number of cents as part of the calculation, so it probably makes sense for this to actually be in cents after all.  That said, we may need some refining to the UI to make this and the math clearer.  Harsha will be following up with design on that.

One issue, though ... If we're keeping it `FSCPriceDifferenceInCents`, we should change the type to be `INTEGER` rather than `DECIMAL`.

2021-04-16 20:30 UTC, reggieriser commented on swagger/ghc.yaml
> +      - ZipSITOriginHHGActualAddress
I did a diff with the keys in the DB and found that the last ones that start with `Zip` should be this:

```
ZipDestAddress
ZipPickupAddress
ZipSITDestHHGFinalAddress
ZipSITOriginHHGActualAddress
ZipSITOriginHHGOriginalAddress
```

Looks like `ZipSITAddress` isn't a param.  Also, the last two you had were in the wrong alpha order.  

I see the same issue in `prime.yaml` below too, as well as the three lists in the model.  (I realize you didn't add `ZipSITAddress`, but if we're cleaning this up, we might as well get it completely back in sync if it's not too painful).

2021-04-16 21:22 UTC, reggieriser approved these changes
LGTM!  Thanks for all the changes and the param key cleanup.

2021-04-16 21:52 UTC, merged