[MB-7623] Switch the connection for the Job Runner to use HTTPS to GEX
transcom/mymove pull request #6427
Opened 2021-04-15 00:01 UTC by mboren

## Description

I took the GEX connection code from `post_file_to_gex.go`, updated it a bit, and used it to change places where we were using SFTP to send files to Syncada to use HTTP to send to GEX instead. 
I left in the ability to switch back to using SFTP to send to Syncada. If we determine that we will not need this in the future, we should add a story to remove it.

I also added an ICN to the filenames that we send, to avoid having a file name collision if we sent multiple files at the same second. The new format is: `<timestamp>_<ICN>_edi858.txt`.

## Reviewer Notes

## Setup
I think we might need to test this on experimental, and I haven't done that before.

```sh
go run ./cmd/milmove-tasks process-edis --send-to-syncada true

sendtosyncada.json
```json
{
  "body": {
    "sendToSyncada": true,
    "readFromSyncada": false,
    "deleteFromSyncada": false
  }
}
```

```sh
prime-api-client --insecure support-reviewed-payment-requests --filename sendtosyncada.json
```

## Code Review Verification Steps
* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-7623) for this change

2021-04-16 07:05 UTC, gidjin requested changes
Had a few suggestions, marking this as changes requested because the gex sender isn't respecting the `SEND_TO_SYNCADA` flag (aka `sendEDIFile` parameter)

2021-04-16 17:39 UTC, mboren commented on pkg/services/payment_request/payment_request_reviewed_processor_test.go
> +		suite.Nil(paymentRequest.SentToGexAt)
Ok, I added some checks to make sure it's set to EDI_ERROR on failures and SENT_TO_GEX on successes.

2021-04-19 17:01 UTC, jacquelineIO approved these changes
Changes look good to me. There are valid UT, just need to run it to see what happens.

2021-04-19 18:21 UTC, gidjin approved these changes
Approving was able to connect to GEX via HTTPS locally

2021-04-19 18:21 UTC, gidjin commented on pkg/services/invoice/gex_sender_http_test.go
> +	resp, err = NewGexSenderHTTP(mockServer.URL, "", false, nil, "", "").
Small nit, could use a test that verifies the channel and file name end up in the url. But only if it's easy.

2021-04-19 20:33 UTC, mboren commented on pkg/services/invoice/gex_sender_http_test.go
> +	resp, err = NewGexSenderHTTP(mockServer.URL, "", false, nil, "", "").
OK i added a test for this.

2021-04-19 20:50 UTC, merged