MB-3164 service counselor login
transcom/mymove pull request #6461
Opened 2021-04-20 18:08 UTC by eamahanna

## Description

Explain a little about the changes at a high level.

## Reviewer Notes

Is there anything you would like reviewers to give additional scrutiny?

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

```sh
echo "Code goes here"
```

## Code Review Verification Steps

* [ ] If the change is risky, it has been tested in experimental before merging.
* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] The requirements listed in [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely) have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://github.com/transcom/mymove/wiki/migrate-the-database#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](tbd) for this change
* [this article](tbd) explains more about the approach used.

## Screenshots

If this PR makes visible UI changes, an image of the finished UI can help reviewers and casual
observers understand the context of the changes. A before image is optional and
can be included at the submitter's discretion.

Consider using an animated image to show an entire workflow instead of using multiple images. You may want to use GIPHY CAPTURE for this! 📸

_Please frame screenshots to show enough useful context but also highlight the affected regions._

2021-04-20 20:01 UTC, duncan-truss commented on pkg/auth/authentication/devlocal.go
> +		office := models.TransportationOffice{
I'm actually working on a [PR this week to fix these devlocal transportation offices](https://dp3.atlassian.net/browse/MB-7667) to include a value for Gbloc because it is currently missing.  Do you mind adding `Gbloc: "LKNQ"` here?

2021-04-20 20:22 UTC, eamahanna commented on pkg/auth/authentication/devlocal.go
> +		office := models.TransportationOffice{
Sure!

2021-04-20 20:22 UTC, eamahanna commented on pkg/auth/authentication/devlocal.go
> +		office := models.TransportationOffice{
That fixes an issue I was having lol

2021-04-21 18:52 UTC, shimonacarvalho commented on pkg/testdatagen/make_office_user.go
> +// MakeServicesCounselorOfficeUserWithUSMCGBLOC makes an OfficeUser tied to the USMC GBLOC
Minor change, could you say makes a Services Counselor tied to the USMC GBLOC? There is another function that makes a USMC office user with the identical comment.

2021-04-21 18:53 UTC, shimonacarvalho commented on pkg/testdatagen/scenario/devseed.go
> +	/* A user with tio role */
This comment should likely say "services counselor" role.

2021-04-21 19:01 UTC, sandy-wright reviewed
Nice, LGTM! The redirect seems to be a lil wonky when I create a fresh Service Counselor, but I think that's just the nature of the beast. I did leave some minor suggestions, but you could argue against them, so I'll leave it up to you to apply them or not ☺️

2021-04-21 19:03 UTC, shimonacarvalho commented on pkg/testdatagen/scenario/devseed.go
> +		},
A little confused by this function. Can you break it up with comments explaining what is happening? 
I'm assuming it would create one office user with all three roles. 

However, this user here gets created with only two roles (too, tio) on line 2882.
And then later the same userID gets used to create a service member on line 2899? I don't think an office user needs to be a service member?

And then another user gets created on line 2915, this time with all three roles and usmc. 

Would be good to clarify what is happening and why, how many users get created, and possibly break down into smaller creation functions.

2021-04-21 19:11 UTC, shimonacarvalho commented on pkg/testdatagen/scenario/e2ebasic.go
> +	testdatagen.MakeServiceMember(db, testdatagen.Assertions{
Here again, unsure why a servicemember is being created for the office user.

2021-04-21 19:14 UTC, shimonacarvalho commented on pkg/testdatagen/scenario/devseed.go
> +		},
Maybe this link will be helpful:
https://github.com/transcom/mymove/wiki/Understanding-Testdatagen-Functions

2021-04-21 19:15 UTC, shimonacarvalho requested changes
Works perfectly! Tried with a devlocal and a login.gov user.
Some of the testdatagen functions are confusing and possibly need refactoring.

2021-04-21 19:32 UTC, eamahanna commented on pkg/testdatagen/scenario/devseed.go
> +		},
So it doesn't look like an office user has to be a service member, so I removed that part. This function creates two offices users with the 3 office user roles. However, one is associated with usmc. 

The reason we have to create a user instead of just having a default user created in `MakeOfficeUser` is because we need to have a hard coded userID. 	

I added comments, so hopefully is should make it clearer.

2021-04-21 20:06 UTC, shimonacarvalho commented on pkg/testdatagen/scenario/devseed.go
> +		},
Okay, looking better. I still think it would be good to split it up. The function name is `createTXOServicesCounselor` which sounds like one user is being created. Perhaps split it up into `createTXOServicesCounselor` and `createTXOServicesCounselorUSMC`.

2021-04-21 20:07 UTC, shimonacarvalho commented on pkg/testdatagen/scenario/devseed.go
> +	if err != nil {
Is there any reason the three roles are queried one at a time? Seems like all the role ids could be queried at once, which would simplify this function further, and speed up the devseed code.

2021-04-21 20:58 UTC, eamahanna commented on pkg/testdatagen/scenario/devseed.go
> +	if err != nil {
I think it makes it easier to panic and send a specific error message.

2021-04-21 21:11 UTC, eamahanna commented on pkg/testdatagen/scenario/devseed.go
> +		},
Okay I split it, but having them separate functions will create additional calls to the DB and likely slow it down a bit.

2021-04-21 21:22 UTC, eamahanna commented on pkg/testdatagen/scenario/devseed.go
> +	if err != nil {
Can you provide an example of what you think I should change it to?

2021-04-21 23:24 UTC, shimonacarvalho commented on pkg/testdatagen/scenario/devseed.go
> +	if err != nil {
Something like...
```
	addRoleTypes := []roles.RoleType{roles.RoleTypeTOO, roles.RoleTypeTIO, roles.RoleTypeServicesCounselor}
	var addRoles []roles.Role
	err := db.Where("role_type in (?)", addRoleTypes).All(&addRoles)
```
Basically here are the three roles i want to add to my user, get me their ids.

Sure the error will be more generic, but this is devseed. No customer will be reading the errors and the state of the system is pretty fixed, not dynamic, as it runs on an empty database. If you have no errors on checkin, almost guaranteed to work exactly the same each time. 

The thing with devseed is that it's gotten slower and slower and harder to understand. So any attempts to keep it clean and lean help a lot with tech debt.

2021-04-21 23:28 UTC, shimonacarvalho commented on pkg/testdatagen/scenario/devseed.go
> +		},
Are the additional calls the roles queries? That can be simplified down to one call per function, so overall we should have fewer I think. 

What happens is that people reuse these helper functions and if they think it creates one counselor but actually creates two, this doubling will happen each time. Over time, this gets impossible to clean up because it's hard to tell if they used the function because they wanted a regular Services Counselor or a USMC Services Counselor.

2021-04-22 04:55 UTC, eamahanna commented on pkg/testdatagen/scenario/devseed.go
> +	if err != nil {
ahhhh, that makes sense. Changes pushed! Thanks for the feed back :)

2021-04-22 17:11 UTC, shimonacarvalho approved these changes
Looks good, thanks!

2021-04-22 17:37 UTC, merged

2021-04-22 19:34 UTC, monfresh commented on pkg/testdatagen/scenario/devseed.go
> +		},
@eamahanna What is the reason for hardcoding a user ID? Why can't we use the helper functions that we added in `make_move.go`, such as `MakeServicesCounselorOfficeUserWithUSMCGBLOC`?

2021-04-22 19:37 UTC, monfresh commented on pkg/testdatagen/scenario/e2ebasic.go
> +
`e2ebasic` is only used for the Cypress tests. If we add data to it without using it, we are unnecessarily slowing down the Cypress tests. Maybe I missed it, but I don't see any Cypress tests in this PR.

2021-04-22 19:46 UTC, monfresh commented on pkg/testdatagen/scenario/devseed.go
> +		},
Also, now we have both `createTXO` and `createTXOServicesCounselor`. It seems like having just one TXO with all 3 roles would be enough, as opposed to one that has 2 roles, and another that has 3 roles. Thoughts?