MB-3341 add Customer App Page Footer to storybook and move to components directory
transcom/mymove pull request #6527
Opened 2021-04-28 19:10 UTC by Shkeating

## Description

this branch
- creates a `.stories.jsx` file to add the Customer App Footer to storybook
- adds a wrapping `<Route>` tag around the `<Link>` tags in the footer to resolve an error
- moves the Footer component to the `components` directory
- updates the imports in other files that use the component to account for the move

## Reviewer Notes

I'm no pro at React Router, so if you are, I'd appreciate if you check to make sure I placed the `<Route>` tags in the correct location.

## Setup

```sh
yarn storybook
```
http://localhost:6006/?path=/story/customer-components-page-footer--basic 

## Code Review Verification Steps

* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-3341?atlOrigin=eyJpIjoiMjQ5ZThkN2MxOGU4NGQwMmI5MTVkNDk3OGNmY2E2NjQiLCJwIjoiaiJ9) for this change

## Screenshots
<img width="1564" alt="image" src="https://user-images.githubusercontent.com/59394696/116459479-dda04a00-a833-11eb-8b0d-1bcf9aaa86f9.png">
<img width="1563" alt="image" src="https://user-images.githubusercontent.com/59394696/116459513-e7c24880-a833-11eb-96a6-5e735230c474.png">

2021-04-28 21:52 UTC, cosburn approved these changes

2021-04-29 01:28 UTC, YanZ777 commented on src/components/Customer/Footer/index.jsx
> +                <Router>
I think you'll actually want to use mock providers inside of `*.stories.jsx`. 
An example you can look at is: `src/components/Customer/Profile/ContactInfoDisplay/ContactInfoDisplay.stories.jsx`

2021-04-29 01:28 UTC, YanZ777 commented on src/components/Customer/Footer/index.jsx
> +                    <Link className="usa-footer__primary-link" to="/privacy-and-security-policy">
This link appears to be dead for me, I'm not sure if this is outside the scope of this task though.

2021-04-29 01:28 UTC, YanZ777 commented on src/components/Customer/Footer/index.jsx
> +                <Router>
I think if you leave the <Router> wrapped around these links, they won't automatically redirect. That should be fixed once the <Router> gets moved.

2021-04-29 01:35 UTC, YanZ777 requested changes
I would take out the router inside of the `index.jsx` and use the mock providers inside of `index.stories.jsx` if that is where you were getting errors.

2021-04-29 19:02 UTC, Shkeating commented
> I would take out the router inside of the `index.jsx` and use the mock providers inside of `index.stories.jsx` if that is where you were getting errors.

All done! Thanks for your help 🌟

2021-04-29 19:52 UTC, YanZ777 requested changes
I'm seeing a few lint errors when I make storybook, which causes the component to not show up in storybook.

2021-04-29 19:56 UTC, Shkeating commented
> I'm seeing a few lint errors when I make storybook, which causes the component to not show up in storybook.

ahhhh i forgot to commit something 😅

2021-04-29 20:00 UTC, YanZ777 approved these changes
Thanks for making all those changes!

2021-04-29 20:21 UTC, merged