Em mb 7687 tio can see shipment details
transcom/mymove pull request #6569
Opened 2021-05-04 16:43 UTC by eamahanna

## Description

Explain a little about the changes at a high level.

## Reviewer Notes

Is there anything you would like reviewers to give additional scrutiny?

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

```sh
echo "Code goes here"
```

## Code Review Verification Steps

* [ ] If the change is risky, it has been tested in experimental before merging.
* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] The requirements listed in [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely) have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://github.com/transcom/mymove/wiki/migrate-the-database#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](tbd) for this change
* [this article](tbd) explains more about the approach used.

## Screenshots

If this PR makes visible UI changes, an image of the finished UI can help reviewers and casual
observers understand the context of the changes. A before image is optional and
can be included at the submitter's discretion.

Consider using an animated image to show an entire workflow instead of using multiple images. You may want to use GIPHY CAPTURE for this! 📸

_Please frame screenshots to show enough useful context but also highlight the affected regions._

2021-05-10 18:22 UTC, sandy-wright commented on src/components/Office/PaymentRequestDetails/PaymentRequestDetails.module.scss
> +      margin-bottom: 12px;
Do we have any standard spacing variables we could use here instead of hardcoding values?

2021-05-10 18:28 UTC, sandy-wright commented on src/components/Office/PaymentRequestDetails/PaymentRequestDetails.jsx
> +                  <b data-testid="departure-date">Departed {formatDateFromIso(shipmentDepartureDate, 'DD MMM YYYY')}</b>
Maybe like how it's done later on:
```css
.addressBlock {
    span {
      @include u-text('bold');
    }
  }
 ```

2021-05-10 20:34 UTC, donaldthai requested changes
I left a couple questions and comments but this is looking good so far!

2021-05-10 20:34 UTC, donaldthai commented on src/components/Office/ReviewServiceItems/ServiceItemCard.jsx
> +            <small className={styles.addressBlock}>
To add on, would a description list `dl` be better suited here instead of `div` `span`?

2021-05-10 20:34 UTC, donaldthai commented on src/components/Office/ReviewServiceItems/ServiceItemCard.module.scss
> +    font-size: 22px;
This actually looks like an `h3` element which is about 22px. So we can just use an `h3` instead.

2021-05-10 23:52 UTC, eamahanna commented on src/components/Office/PaymentRequestDetails/PaymentRequestDetails.jsx
> +  shipmentAddress: PropTypes.node,
It can be a node or a string. I update the type to reflect that :)

2021-05-11 00:20 UTC, eamahanna commented
@donaldthai  with respect to "To add on, would a description list dl be better suited here instead of div span?" 

I don't think a dl applies. I just looked at the definition to double check: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl

2021-05-11 17:31 UTC, donaldthai approved these changes
🚀

2021-05-11 21:05 UTC, amanda5iu approved these changes

2021-05-11 21:07 UTC, merged