MB-7342 TIO can see shipment modification tag
transcom/mymove pull request #6620
Opened 2021-05-12 21:28 UTC by eamahanna

## Description

This PR adds a `DIVERSION` or `CANCELLED` tag to the payment request details and service item card. If the status of the shipment associated with payment request or service item is cancelled, a cancelled tag will show. If a shipment has been marked as diverted, then the diversion tag will be displayed. 

## Reviewer Notes

Is the css rendering correctly? 

## Setup

To get these tags to show, you will need to update a shipment that is associated with a payment request to have `diversion = true `  or status = `CANCELLED`. The easiest way to do this is to manipulate existing data in a db viewer or via sql in your terminal. If you need help to set this up, please feel free to ping me. 

* Run the office app locally
* Navigate to the payment request that is associated with the shipment that you updated
* View the tags on the payment request details page and then when reviewing the service item

## Code Review Verification Steps

* [ ] If the change is risky, it has been tested in experimental before merging.
* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] The requirements listed in [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely) have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://github.com/transcom/mymove/wiki/migrate-the-database#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

This PR takes care of two JIRA tickets: 
* https://dp3.atlassian.net/browse/MB-7342
* https://dp3.atlassian.net/browse/MB-7339

## Screenshots
<img width="356" alt="Screen Shot 2021-05-12 at 1 17 42 PM" src="https://user-images.githubusercontent.com/56279459/118046556-f32e6d00-b325-11eb-8485-1d3f6473c5e0.png">
<img width="870" alt="Screen Shot 2021-05-12 at 1 17 36 PM" src="https://user-images.githubusercontent.com/56279459/118046565-f6295d80-b325-11eb-9c84-99c7e9effe34.png">

2021-05-13 14:33 UTC, jenniferlynparsons requested changes
Looks good overall! I suggested a small refactor. Params bloat can be a thing that happens in React components. 😄

2021-05-13 14:33 UTC, jenniferlynparsons commented on src/components/Office/PaymentRequestCard/PaymentRequestCard.jsx
> +                shipmentModificationType={shipmentModificationType}
I think this is a good opportunity to do a small refactor. Instead of passing through these three values separately, we can pass the `selectedShipment` to `PaymentRequestDetails` and destructure it there. The logic starting on line 171 could also be move there. It will be a little cleaner passing less params explicitly.

2021-05-13 18:41 UTC, eamahanna commented on src/components/Office/PaymentRequestCard/PaymentRequestCard.jsx
> +                shipmentModificationType={shipmentModificationType}
Done! Thank you :)

2021-05-14 16:58 UTC, amanda5iu approved these changes
LGTM!

2021-05-14 20:47 UTC, jenniferlynparsons requested changes
Looking good! Just one small change in the comments.

2021-05-14 20:47 UTC, jenniferlynparsons commented on src/components/Office/PaymentRequestDetails/PaymentRequestDetails.jsx
> +              {shipment.modificationType && (
This is more of best practice thing rather than incorrect, but you can destructure the shipment on this component to keep the code a little cleaner.

You can place this with the other `const`s at the top: 
`const {modificationType, departureDate, address} = shipment`

And then anything that's like `shipment.modificationType` no longer need `shipment.` to work. This would become `{modificationType && ...`

2021-05-17 14:59 UTC, eamahanna commented on src/components/Office/PaymentRequestDetails/PaymentRequestDetails.jsx
> +              {shipment.modificationType && (
Done!

2021-05-17 15:02 UTC, jenniferlynparsons approved these changes
Great job!

2021-05-17 15:23 UTC, merged