change updateMTOShipment description to match implementation
transcom/mymove pull request #6648
Opened 2021-05-18 00:09 UTC by NamibiaTorres

## Draft PR

## Description

This ticket fixes a bug on the description of the updateMTOShipment endpoint, that mistakenly tells the user that an agent can not be added but can instead be updated. The opposite behavior is true. An agent can be added using the `updateMTOShipment` endpoint, but an agent can not be added using this endpoint. Instead, the user should be pointed to the `updateMTOAgent` endpoint to update any of the subfields of an existing agent. 

## Reviewer Notes

Please make sure all the validations for this fix are covered. 

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

```sh
echo "Code goes here"
```

## Code Review Verification Steps

* [ ] If the change is risky, it has been tested in experimental before merging.
* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] The requirements listed in [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely) have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://github.com/transcom/mymove/wiki/migrate-the-database#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-8028) for this change

## Screenshots

If this PR makes visible UI changes, an image of the finished UI can help reviewers and casual
observers understand the context of the changes. A before image is optional and
can be included at the submitter's discretion.

Consider using an animated image to show an entire workflow instead of using multiple images. You may want to use GIPHY CAPTURE for this! 📸

_Please frame screenshots to show enough useful context but also highlight the affected regions._

2021-05-20 22:35 UTC, shimonacarvalho requested changes

2021-05-20 22:35 UTC, shimonacarvalho commented on swagger/prime.yaml
> +        * `agents` - Agents can not be added or updated using this endpoint. For adding use `createMTOAgent` and for updating use `updateMTOAgent`.
Hey @NamibiaTorres, I thought we came up with an entirely new description in the documentation meeting. 
Wasn't the goal of that to update this? Maybe I'm mistaken? 

Here's the link @sandy-wright shared after the meeting
https://ustcdp3.slack.com/archives/CP497TGAU/p1621366838012700

2021-05-21 16:34 UTC, shimonacarvalho commented on swagger/prime.yaml
> +        These restrictions are due to our [optimistic locking/concurrency control](https://github.com/transcom/mymove/wiki/use-optimistic-locking) mechanism.
None of the local links like `operation/updateMTOShipmentAddress` work due to spelling errors and the quotes. Please try this in redoc and check all the links. 
[https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/transcom/mymove/a5044be0c68d5741e06e3a7a5690b2460dca9226/swagger/prime.yaml#operation/updateMTOShipment](redoc for this commit)

2021-05-23 05:55 UTC, NamibiaTorres commented on swagger/prime.yaml
> +        These restrictions are due to our [optimistic locking/concurrency control](https://github.com/transcom/mymove/wiki/use-optimistic-locking) mechanism.
> None of the local links like `operation/updateMTOShipmentAddress` work due to spelling errors and the quotes. Please try this in redoc and check all the links. Below is this version in redoc.
> 
> https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/transcom/mymove/a5044be0c68d5741e06e3a7a5690b2460dca9226/swagger/prime.yaml

Thanks @shimonacarvalho! I made the correction and it works now:
https://raw.githubusercontent.com/transcom/mymove/f9e3afe287161783fe7848ae5ad198fc699f2ce0/swagger/prime.yaml

2021-05-24 17:03 UTC, shimonacarvalho commented on swagger/prime.yaml
> +        These restrictions are due to our [optimistic locking/concurrency control](https://github.com/transcom/mymove/wiki/use-optimistic-locking) mechanism.
Great works now!

2021-05-24 17:52 UTC, shimonacarvalho approved these changes

2021-05-24 17:56 UTC, merged