MB-7956 Update create item and crate with DCRT service item
transcom/mymove pull request #6686
Opened 2021-05-25 00:03 UTC by eamahanna

## Description

This PR creates a new tesdatagen func `MakeMTOServiceItemDomesticCrating`.  This function creates a DCRT service item and its associated item and crate. I updated devseed, e2e populate and another file to use this function when generating DCRT service items. 

## Reviewer Notes

I saw a DCRT service item was created in `bandwidth.go`. I'm not sure what the file is used for, but it also creates a DCRT service item, so I updated it to use the new function as well. Is that okay?

## Setup

To verify complete the following steps:

- Execute `make db_dev_reset`
- Execute `make db_dev_e2e_populate`
- Execute `make server_run`
- Check with `fetchMTOUpdates` using postman and verify that all crating service items (DCRT) have an ITEM and CRATE. You can search for `DCRT` in the response to quickly find the crating service items.

## Code Review Verification Steps

* [ ] If the change is risky, it has been tested in experimental before merging.
* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] The requirements listed in [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely) have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://github.com/transcom/mymove/wiki/migrate-the-database#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-7956) for this change

2021-05-25 21:33 UTC, sandy-wright requested changes
Thanks for adding this `testdatagen` function - it's gonna be super helpful as folks work on the crating feature! I have some notes of things that we should probably change so that it's a little more useful and follows our standards for these functions.

2021-05-25 21:33 UTC, sandy-wright commented on pkg/testdatagen/make_mto_service_item.go
> +		ID: uuid.FromStringOrNil("68417bd7-4a9d-4472-941e-2ba6aeaf15f4"), // DCRT - Domestic Crating
Is it safe to do this? Do we know this service will exist in the database before this function is used? It might in `devseed.go`, but I suspect this could cause an issue if this was used in tests

2021-05-25 21:33 UTC, sandy-wright commented on pkg/testdatagen/make_mto_service_item.go
> +	assertions.MTOServiceItem.Description = &description
What if the caller tries to pass in a different description as an assertion?

2021-05-25 21:33 UTC, sandy-wright commented on pkg/testdatagen/make_mto_service_item.go
> +	})
I could see someone wanting to use this to test different dimensions, so we should be able to pass in this info as an assertion, I think.

2021-05-25 21:33 UTC, sandy-wright commented on pkg/testdatagen/make_mto_service_item.go
> +		ID: uuid.FromStringOrNil("68417bd7-4a9d-4472-941e-2ba6aeaf15f4"), // DCRT - Domestic Crating
I think the solution here would be to check if an assertion for the ID was passed in, and if not, create this service code. So this line would go back up into devseed, probably.

2021-05-25 22:51 UTC, eamahanna commented on pkg/testdatagen/make_mto_service_item.go
> +		ID: uuid.FromStringOrNil("68417bd7-4a9d-4472-941e-2ba6aeaf15f4"), // DCRT - Domestic Crating
So my only hesitation for adding this back into devseed is it was in every single creation for domestic crating service items in devseed, e2e and the other data gen file. There is also a migration that creates the service table with values `20191101201107_create-re-services-table-with-values.up.sql
  14,3: ('68417bd7-4a9d-4472-941e-2ba6aeaf15f4', 'DCRT', 'Dom. Crating', now(), now()),`

2021-05-25 22:52 UTC, eamahanna commented on pkg/testdatagen/make_mto_service_item.go
> +	assertions.MTOServiceItem.Description = &description
That's fine, I can take this out.

2021-05-25 22:53 UTC, eamahanna commented on pkg/testdatagen/make_mto_service_item.go
> +	})
Sounds good

2021-05-26 15:28 UTC, sandy-wright commented on pkg/testdatagen/make_mto_service_item.go
> +		ID: uuid.FromStringOrNil("68417bd7-4a9d-4472-941e-2ba6aeaf15f4"), // DCRT - Domestic Crating
oh okay, I think that should be fine then!

2021-05-26 15:43 UTC, sandy-wright commented on pkg/testdatagen/make_mto_service_item.go
> +	})
Unfortunately, this still won't pass on any assertions the user might have passed in for the dimensions. I could see someone trying to use this like:
```go
cratingItem := testdatagen.MakeMTOServiceItemDomesticCrating(suite.DB(), testdatagen.Assertions{
    MTOServiceItem: models.MTOServiceItem{
        Dimensions: models.MTOServiceItemDimensions{
            models.MTOServiceItemDimension{
               Type: models.DimensionTypeItem,
               Length: 10000,
			   Height: 5000,
			   Width:  2500,
            },
            models.MTOServiceItemDimension{
               Type: models.DimensionTypeCrate,
               Length: 1000,  // maybe we're testing that the crate can't be smaller?
			   Height: 500,
			   Width:  200,
            },
        },
    },
})
```

Being able to handle that full example will be kind of complicated, but I do think we should be passing on assertions in some way, like:
```go
dimAssertions := assertions.MTOServiceItemDimension
MakeMTOServiceItemDimension(db, Assertions{
		MTOServiceItem: mtoServiceItem,
		MTOServiceItemDimension: models.MTOServiceItemDimension{
			Type: models.DimensionTypeCrate,
			Length: dimAssertions.Length,
			...etc
		},
	})
```

2021-05-26 15:46 UTC, sandy-wright commented on pkg/testdatagen/make_mto_service_item.go
> +	return mtoServiceItem
It might also be nice to add those two crating records to the output of the service item here. Something like:
```go
shipment := MakeMTOShipment(db, assertions)
	if move != nil {
		// This will allow someone to easily create multiple test shipments for one move
		move.MTOShipments = append(move.MTOShipments, shipment)
	}
	return shipment
``` 
(from `testdatagen/make_mto_shipment.go`)

They are being linked on the database, so any retrieval will get them back. However, if someone uses this function and then expects to see the crating records on the output service item, I don't think they'll see them unless we explicitly add them to that model.

This is optional though! I don't think this one is a big deal either way.

2021-05-26 21:06 UTC, eamahanna commented on pkg/testdatagen/make_mto_service_item.go
> +	})
Makes sense. I didn't really think it through all the way yesterday 😓  I just pushed an update that should work now.

2021-05-26 21:12 UTC, eamahanna commented on pkg/testdatagen/make_mto_service_item.go
> +	return mtoServiceItem
Done!

2021-05-26 21:32 UTC, sandy-wright approved these changes
Thanks for making those changes! Looks good - I had one last comment about renaming the new assertion, but it's just a suggestion. And approved so you can merge right away if you do change it 😄

2021-05-26 21:32 UTC, sandy-wright commented on pkg/testdatagen/make_mto_service_item.go
> +	assertions.MTOServiceItemCrate.Type = models.DimensionTypeCrate
Oh, nice! Would you be willing to rename this to `MTOServiceItemCrateDimension` or `MTOServiceItemDimensionCrate`? Just because I confused myself when I was first reading through this. Also there is a wee typo in the comment above this!

2021-05-27 16:15 UTC, eamahanna commented on pkg/testdatagen/make_mto_service_item.go
> +	assertions.MTOServiceItemCrate.Type = models.DimensionTypeCrate
Good call! Sure, thanks for all of your review on this PR. It wasn't my finest work lol.

2021-05-27 19:06 UTC, merged