MB-7694-make-pickup-address-viewable
transcom/mymove pull request #6724
Opened 2021-06-03 16:19 UTC by NamibiaTorres

## Description

Provide the user (Services Counselor) a view containing the additional pick-up address with the rest of the shipment information when it is present.

## Reviewer Notes

This is my first time writing a jest test for a conditional. Does the logic work out ok? 

Also, please provide extra scrutiny on the conditional: If a secondary address is present, then it is displayed. Did I write the conditional following convention?

## Setup

To run the unit test:
```sh
yarn test src/components/Office/ShipmentDisplay/ShipmentDisplay.test.jsx
```

To see whether secondary address is viewable by the Service Counselor (SC):
1. `make server_run` `make client_run`
2. Local  sign-in into **officelocal**
3. Select **Service Counselor** sign-in option
4. Select an account with a secondary address and see if that secondary address appears in the view card with the address data.
5. Repeat step for for an account with _no secondary address_ and make sure that the the secondary address view is not present.

## Code Review Verification Steps

* [ ] If the change is risky, it has been tested in experimental before merging.
* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-7694) for this change

## Screenshots

![Screen Shot 2021-06-03 at 9 15 47 AM](https://user-images.githubusercontent.com/17951554/120678187-b2b99f00-c44c-11eb-8619-ca239c7d7cf0.png)
![Screen Shot 2021-06-03 at 9 19 06 AM](https://user-images.githubusercontent.com/17951554/120678303-d0870400-c44c-11eb-81ca-6431df808418.png)

2021-06-03 16:38 UTC, eamahanna commented on src/components/Office/ShipmentDisplay/ShipmentDisplay.jsx
> +              <dd>{displayInfo.secondaryPickupAddress && formatAddress(displayInfo.secondaryPickupAddress)}</dd>
We already checked for the existence of secondaryPickupAddress, so we don't need to check again. You can have just the formatAddress .

2021-06-03 16:43 UTC, eamahanna commented on src/components/Office/ShipmentDisplay/ShipmentDisplay.test.jsx
> +    expect(wrapper.find('div[data-testid="shipment-display"]').exists()).toBe(true);
Check that it renders when present and that it doesn't exist when not present.

2021-06-03 16:45 UTC, eamahanna commented on src/components/Office/ShipmentDisplay/ShipmentDisplay.test.jsx
> +  destinationAddress: {
I think you can use the info object in the definition (I could be wrong though)
```
const secondaryAddressInfo = {
   info,
  secondaryAddress: ...
}
```

2021-06-04 18:17 UTC, sandy-wright requested changes
This doesn't work currently - there are a couple of changes you'll need to do to make the second pickup address show up:

* You need to make sure the `secondaryPickupAddress` field is getting passed into the `<ShipmentDisplay>` component. You'll do that in this chunk of code: https://github.com/transcom/mymove/blob/master/src/pages/Office/ServicesCounselingMoveDetails/ServicesCounselingMoveDetails.jsx#L56-L64
* You need to make sure that info is coming back from the database. I did this in my PR as well: https://github.com/transcom/mymove/blob/9a776b0389e41cbbba17bcc7b35a5dc2de96538e/pkg/handlers/ghcapi/mto_shipment.go#L73

Then it should work! And you'll have to update the tests for the Services Counselor component ☺️

2021-06-04 18:17 UTC, sandy-wright commented on pkg/handlers/internalapi/internal/payloads/model_to_payload.go
>  	}
The Service Counselors view uses the GHC API, not the Internal API, so I don't think this change does anything for us here. I would remove it.

2021-06-04 19:46 UTC, NamibiaTorres commented on pkg/handlers/internalapi/internal/payloads/model_to_payload.go
>  	}
Ok, thanks! We weren't sure where exactly it would go.

2021-06-04 19:49 UTC, NamibiaTorres commented on pkg/handlers/internalapi/internal/payloads/model_to_payload.go
>  	}
Looks like the ghc api payload already has secondaryPickupAddress, so I guess no changes need to made there?

2021-06-04 20:50 UTC, sandy-wright commented on pkg/handlers/internalapi/internal/payloads/model_to_payload.go
>  	}
Yup, looks like that part was already good to go!

2021-06-04 21:48 UTC, sandy-wright commented on src/components/Office/ShipmentDisplay/ShipmentDisplay.jsx
> +            </div>
This is a picky request, but would you be willing to call this prop `secondPickupAddress` instead? It seems like the prop names are matching the labels - not the shipment field names - in this component

2021-06-07 16:08 UTC, NamibiaTorres commented on src/components/Office/ShipmentDisplay/ShipmentDisplay.jsx
> +            </div>
Done! Made the update. Great suggestion, definitely don't want to confuse things.

2021-06-07 16:30 UTC, sandy-wright reviewed
LGTM! Only thing left to handle is an error in the `ShipmentDisplay.test.jsx` file. The rest looks good! Once that's passing, I'm good to approve 😄

2021-06-07 16:30 UTC, sandy-wright commented on src/components/Office/ShipmentDisplay/ShipmentDisplay.test.jsx
> +  secondaryAddress: {
This needs to have the name you'd use in the component - so `secondPickupAddress`. It would be good to name the `const` to something like `secondPickupAddressInfo` too, so that it's more explicit.

2021-06-07 16:30 UTC, sandy-wright commented on src/components/Office/ShipmentDisplay/ShipmentDisplay.test.jsx
> +    expect(screen.getByText('Second pickup address')).not.toBeInTheDocument();
When I run the tests locally, there seems to be an error with this line. It might be related to the incorrect naming above though, so once you fix that it might fix all the other errors in the test.

2021-06-07 17:37 UTC, sandy-wright approved these changes
🚀 ✨

2021-06-07 17:59 UTC, merged