MB-8247 add orders link for orders amendment flow (front end)
transcom/mymove pull request #6768
Opened 2021-06-08 21:11 UTC by pearl-truss

## Description

This PR adds a new screen that includes an "upload documents" link (that currently doesn't go anywhere). This is shown under the Orders step after a customer submits their move

## Setup

There are 2 ways to view these changes:

### Storybook
```sh
make storybook
```
And go to Customer Components -> Step -> Orders Amended

### Customer App
```sh
make server_run && make client_run
```
Create a customer move and after submitting the move verify the UI changes

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-8247) for this change

## Screenshots

<img width="988" alt="Screen Shot 2021-06-08 at 5 09 33 PM" src="https://user-images.githubusercontent.com/67110378/121258011-5c999100-c87c-11eb-84a1-b88dc15a1cc4.png">
<img width="323" alt="Screen Shot 2021-06-08 at 5 09 41 PM" src="https://user-images.githubusercontent.com/67110378/121258014-5d322780-c87c-11eb-8078-496637239baf.png">

2021-06-09 14:49 UTC, amanda5iu approved these changes
Looks good to me!

2021-06-09 15:35 UTC, reggieriser approved these changes
LGTM 🚀 -- both storybook and running through a move went as expected.  Code looks good too, but I may not be up on all the latest front-end patterns.  Probably want to get a look from someone more recently in the front-end.

Also looks like Danger is complaining like yesterday -- hopefully a merge with master gets past that for now.

2021-06-09 15:41 UTC, pearl-truss commented on src/components/Customer/Home/Step/Step.module.scss
>  .accept {
@jenniferlynparsons out of curiosity with styes like .accept and .edit-btn that aren't prefixed with step or within .step-container, are these being applied everywhere they appear (beyond this component) or is there something happening to scope them to the Step component?

2021-06-09 19:08 UTC, mboren commented on src/pages/MyMove/Home/index.jsx
> +                      editBtnLabel={this.hasOrders && !this.hasSubmittedMove ? 'Edit' : ''}
I think including `!this.hasSubmittedMove` in this condition might be redundant, and could be removed. On the other hand, it's not wrong and might make the code clearer, so I don't feel strongly about it.

2021-06-09 19:52 UTC, jenniferlynparsons commented on src/components/Customer/Home/Step/index.jsx
> +  const containerCN = classnames(styles['step-container'], styles[containerClassName]);
No need to change this. We don't follow this pattern anywhere else in the code except when we have to do some kind of logic on the classnames.

2021-06-09 19:52 UTC, jenniferlynparsons commented on src/components/Customer/Home/Step/Step.module.scss
>  .accept {
Yup! It's still getting scoped. If you look in the inspector you'll see things like `Step_accept__bjZEP` as a class name.

2021-06-09 19:53 UTC, jenniferlynparsons requested changes
It's looking good! I just made one small request to keep things consistent.

2021-06-09 19:57 UTC, pearl-truss commented on src/components/Customer/Home/Step/index.jsx
> +  const containerCN = classnames(styles['step-container'], styles[containerClassName]);
I tried adding a className to this div and wasn't getting picked up until I made this change. I can try again

2021-06-09 19:58 UTC, pearl-truss commented on src/pages/MyMove/Home/index.jsx
> +                      editBtnLabel={this.hasOrders && !this.hasSubmittedMove ? 'Edit' : ''}
Good catch, I think I should just remove it

2021-06-09 23:58 UTC, YanZ777 approved these changes
Looks good to me.

2021-06-10 14:05 UTC, pearl-truss commented on src/components/Customer/Home/Step/index.jsx
> +  const containerCN = classnames(styles['step-container'], styles[containerClassName]);
@jenniferlynparsons whenever you have time can you check the current diff? I reverted the classname changes here but now the .step-amended-orders styles aren't getting picked up and I'm not sure if there's something happening in the background I'm not familiar with

2021-06-10 19:44 UTC, jenniferlynparsons commented on src/components/Customer/Home/Step/index.jsx
> +  const containerCN = classnames(styles['step-container'], styles[containerClassName]);
Okay! I think I know where the issue is, but fiddled with it and couldn't solve it. Might be worth reaching out to Shauna and even Suz (because it's a CSS Modules thing). There's something I'm not grokking about how this works.

If you look at the rendered class names, you'll see `Step_step-container__IlFLr step-amended-orders` which I am pretty sure means that `step-amended-orders` is outside of the CSS module control. I don't have a full grasp on this and couldn't find the right similar scenario anywhere else. 

I've got some other things on my plate, but I'll try to come back to this asap.

2021-06-10 20:25 UTC, pearl-truss commented on src/components/Customer/Home/Step/index.jsx
> +  const containerCN = classnames(styles['step-container'], styles[containerClassName]);
Thanks for checking! @Shkeating @suzubara if you have time to look into this and/or know what's happening with the scss modules please let us know! Essentially I'm passing in 'step-amended-orders' into the `containerName` prop on the Step component and it's not getting picked up. I was able to get it to work by including it in the classnames function: ` classnames(styles['step-container'], styles[containerClassName])` however this doesn't match other patterns in the frontend like JP pointed out earlier

2021-06-14 12:41 UTC, jenniferlynparsons approved these changes

2021-06-14 13:12 UTC, merged