MB-7693 TOO can view additional addresses
transcom/mymove pull request #6771
Opened 2021-06-08 21:36 UTC by sandy-wright

## Description

This PR does a lot more than it set out to do.

## Reviewer Notes

Is there anything you would like reviewers to give additional scrutiny?

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

```sh
echo "Code goes here"
```

## Code Review Verification Steps

* [ ] If the change is risky, it has been tested in experimental before merging.
* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] The requirements listed in [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely) have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://github.com/transcom/mymove/wiki/migrate-the-database#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](tbd) for this change
* [this article](tbd) explains more about the approach used.

## Screenshots

If this PR makes visible UI changes, an image of the finished UI can help reviewers and casual
observers understand the context of the changes. A before image is optional and
can be included at the submitter's discretion.

Consider using an animated image to show an entire workflow instead of using multiple images. You may want to use GIPHY CAPTURE for this! 📸

_Please frame screenshots to show enough useful context but also highlight the affected regions._

2021-06-09 22:37 UTC, YanZ777 commented on src/types/agent.js
> +export const AgentShape = shape({
Yay! 🎉

2021-06-09 23:19 UTC, eamahanna commented on src/components/Office/DefinitionLists/ShipmentInfoList.stories.jsx
> +    originAddress={object('originAddress', info.originAddress)}
What are the object and text functions for?

2021-06-09 23:24 UTC, eamahanna approved these changes

2021-06-10 01:11 UTC, YanZ777 commented on src/components/Office/ShipmentDetails/ShipmentDetails.jsx
> +          secondaryDestinationAddress: shipment.secondaryDeliveryAddress,
I think the props should be changed to match what is returned from the backend. Understandably, that would be a lot of files to change, so I'm ok if you want to write up a ticket for this a well.

2021-06-10 01:48 UTC, YanZ777 approved these changes

2021-06-10 15:12 UTC, sandy-wright commented on src/components/Office/DefinitionLists/ShipmentInfoList.stories.jsx
> +    originAddress={object('originAddress', info.originAddress)}
These are Storybook commands that allow you to edit the values in these fields from within Storybook so you can see what it looks like with different content! They go under the "Knobs" tab:

<img width="506" alt="Screen Shot 2021-06-10 at 10 11 21 AM" src="https://user-images.githubusercontent.com/62574202/121550320-41da3000-c9d4-11eb-8235-2214dea19ea5.png">

2021-06-10 15:13 UTC, sandy-wright commented on src/components/Office/ShipmentDetails/ShipmentDetails.jsx
> +          secondaryDestinationAddress: shipment.secondaryDeliveryAddress,
I think you're right - I'll change the ones in the files I touched at least

2021-06-10 17:01 UTC, jenniferlynparsons requested changes
I left comments and would be happy to chat about them!

2021-06-10 17:01 UTC, jenniferlynparsons commented on src/containers/SimpleSection/SimpleSection.jsx
> +const SimpleSection = ({ children, header, border }) => {
This is an interesting idea. I wonder since it has some prescriptive styling on it, is it generic enough to be reusable? Also wondering if it's really needed. I'd like to know more about the thought behind it!

2021-06-10 17:19 UTC, sandy-wright commented on src/components/Office/ShipmentApprovalPreview.jsx
> +                        requestedMoveDate={shipment.requestedPickupDate}
Ooh, great, thanks for this input! I was seeing both approaches in the codebase and wasn't sure which to go with, so this is very clear 😄.

One question - would you prefer to see:
```jsx
<ShipmentInfoList
  className={styles.shipmentInfo} 
  shipment={{
    requestedPickupDate: shipment.requestedPickupDate,
    pickupAddress: shipment.pickupAddress,
    ...  // specifically naming which parts of the shipment I'm passing in here, which I've seen around town
  }}
/>
```
or just a wholesale:
```jsx
<ShipmentInfoList
  className={styles.shipmentInfo} 
  shipment={shipment}
/>
```
?

2021-06-10 17:20 UTC, sandy-wright commented on src/components/Office/ShipmentApprovalPreview.jsx
> +                        requestedMoveDate={shipment.requestedPickupDate}
It sounds like the latter, but figured I'd ask just to be sure

2021-06-10 17:21 UTC, sandy-wright commented on src/components/Office/ShipmentApprovalPreview.jsx
> +                        requestedMoveDate={shipment.requestedPickupDate}
OH, never mind! You answer this question exactly in a later comment 😄

2021-06-10 17:29 UTC, sandy-wright commented on src/components/Office/ShipmentDetails/ShipmentDetailsSidebar.jsx
> +            <SimpleSection header="Pickup" border={false}>
I didn't handle it so that it would work this way - but I think I should based on this! So I will change that

2021-06-10 17:30 UTC, sandy-wright commented on src/containers/SimpleSection/SimpleSection.jsx
> +const SimpleSection = ({ children, header, border }) => {
I saw this kind of section styling just enough throughout the designs that I thought it might be useful. I was also thinking about potentially adding a `compact` prop in addition to `border` so that the header could be larger sometimes as well - although there wasn't a specific use for that yet, so I didn't implement it. I think it _could_ be generic enough to be reusable, and it could help keep formatting more consistent. 

In particular, the header styling was really specific but also _really_ common throughout the designs. I didn't find consistent styling for that small header anywhere else, despite how common it is, and I thought it would be helpful to have that CSS explicitly defined in a generic part of the app instead of buried in the Office components. 

That said, I could easily remove it and combine it with the ShipmentDetailsSidebar component! Whichever feels best. Maybe @brooksr4 will have an opinion on this too?

2021-06-10 19:38 UTC, sandy-wright commented on src/components/Office/ShipmentDetails/ShipmentDetailsMain.jsx
> +        pickupAddress={shipment.pickupAddress}
I wasn't able to reduce it to `pickupAddress` because the tests and the linter yelled at me, unfortunately

2021-06-10 20:57 UTC, jenniferlynparsons approved these changes
Approving with the outstanding question about the SimpleSection. There's a ticket out for refactoring RequestedShipments that may help clean some of that up.

2021-06-10 20:57 UTC, jenniferlynparsons commented on src/components/Office/RequestedShipments/RequestedShipments.jsx
> +                    displayInfo={shipmentDisplayInfo(shipment, dutyStationPostal)}
Agreed!

2021-06-10 20:57 UTC, jenniferlynparsons commented on src/components/Office/ShipmentApprovalPreview.jsx
> +                          ...shipment,
Niceeeeee!

2021-06-10 20:57 UTC, jenniferlynparsons commented on src/containers/SimpleSection/SimpleSection.jsx
> +const SimpleSection = ({ children, header, border }) => {
My take is that this is fine as it is and will likely be useful in the future. I'm totally not opposed to styling-specific components if it helps us have more consistency.

Communicating this out to #prac-frontend would be helpful too. This is a change that's worth creating a ticket for to refactor a couple more similar places it could be used in order to establish the pattern.

2021-06-11 15:32 UTC, amanda5iu approved these changes
LGTM!

2021-06-11 17:06 UTC, merged