[MB-8331] Create page for uploading amended orders
transcom/mymove pull request #6788
Opened 2021-06-11 02:14 UTC by mboren

## Description

I added a page to upload amended orders and linked it to the "upload documents" button on the home screen.
The handlers for the buttons on the page are currently stubbed out.
Styling is covered in another story.

## Reviewer Notes

This is the only React code I've written outside of a tutorial I worked through years ago, so any React tips are appreciated.

I wanted to hook this up to the existing orders for mock up purposes instead of stubbing things, but I haven't been able to get it to work yet. Most of the code should be nearly copy-pasteable from `src/pages/MyMove/UploadOrders.jsx`, but it's gotta be translated to work in a functional component and I don't quite get it.

The page responsiveness is not that great. 

## Setup

Create a move through the customer interface and submit it, then click the "Upload documents" button on the homepage.
If you click the cancel link at the bottom, it should take you back to the home page.

## Code Review Verification Steps
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-8331) for this change

## Screenshots

Here's a screenshot of the new page:
![image](https://user-images.githubusercontent.com/2627844/121618356-7c1af000-ca1b-11eb-9daf-4e3b6f8b508f.png)

2021-06-11 13:34 UTC, pearl-truss commented
I haven't looked at your code yet but from reading your note about the links/buttons I think you can reuse the WizardNavigation component. It looks like theres an "edit mode" that'll give you a save button and a cancel link

<img width="581" alt="Screen Shot 2021-06-11 at 9 32 48 AM" src="https://user-images.githubusercontent.com/67110378/121694332-05700800-ca98-11eb-97a9-5c62cdaca311.png">

2021-06-11 15:13 UTC, mboren commented
> I think you can reuse the WizardNavigation component. 

nice, I'll give that a shot

2021-06-11 22:48 UTC, YanZ777 commented on src/pages/MyMove/AmendOrders/AmendOrders.test.jsx
> +import { React } from 'react';
I the AmendOrders.module.scss file is empty, it should be deleted.

2021-06-12 00:56 UTC, YanZ777 commented
You might want to note in the description that mobile view is going to be off. From what I understood, there's another ticket to work on the styling for the uploads table, correct?

2021-06-12 01:05 UTC, YanZ777 commented on src/pages/MyMove/AmendOrders/AmendOrders.jsx
> +  useEffect(() => {
I believe this is causing an infinite loop. I think you only want to do this once on mount, so you'll pass an empty array as the second argument to useEffect.

2021-06-12 01:13 UTC, YanZ777 requested changes
Please fix the infinite requests. 
Also, does this need to be branched off of `pm-mb-8247-add-orders-link-added-front-end`?

2021-06-14 22:30 UTC, mboren commented on src/pages/MyMove/AmendOrders/AmendOrders.jsx
> +  useEffect(() => {
eslint won't let me pass in an empty array because I'm using `serviceMemberId` and `updateOrders` in `useEffect`. I could just pass those as dependencies, but from what I'm reading, it seems like using a function in the dependencies array will not work the way I want it to. Still looking into this.

2021-06-15 16:49 UTC, mboren commented on src/pages/MyMove/AmendOrders/AmendOrders.jsx
> +  useEffect(() => {
I tried to just adding `serviceMemberId` and `updateOrders` to the deps array and it seems to have fixed the infinite loop. From reading up about this, I was under the impression that using `updateOrders` as a dep would not work due to function comparison stuff, but it seems fine? I don't really understand this.

2021-06-15 23:15 UTC, YanZ777 commented on src/pages/MyMove/AmendOrders/AmendOrders.jsx
> +  useEffect(() => {
At quick glance, I would have thought that adding `updateOrders` would have caused an infinite rendering loop as well, but when I look at the code again, it wouldn't because `updateOrders` is passed in a prop and not defined within this component itself. 
If it were defined in this component, then adding it as a dependency would cause the component to re-render, which would cause the component to re-define the function, which would trigger this useEffect, and cause another re-render, etc.

Could you be more specific about which aspect of function comparison would not work?

2021-06-15 23:18 UTC, YanZ777 commented on src/pages/MyMove/AmendOrders/AmendOrders.jsx
> +  // push: PropTypes.func.isRequired,
I think you might get push for free if you call `useHistory()` from within the component. 
```
import { useHistory } from 'react-router-dom';
...
const { history } = useHistory();
history.push(somePath);
...
```

2021-06-16 16:45 UTC, mboren commented on src/pages/MyMove/AmendOrders/AmendOrders.jsx
> +  useEffect(() => {
I think your explanation makes sense. It makes sense to me that a function defined inside the component would cause a loop.

2021-06-16 16:54 UTC, mboren commented on src/pages/MyMove/AmendOrders/AmendOrders.jsx
> +  // push: PropTypes.func.isRequired,
Oh cool. I saw push passed in as a prop to some of our other components, and assumed that was necessary for testing or something.

2021-06-17 01:13 UTC, YanZ777 approved these changes
It looks good to me, but I'd like someone else to take a look, if possible.

2021-06-17 19:51 UTC, kylehilltruss reviewed
I don't see any blocking problems with the code, leaving aside the uploaded file table overflow. I've left comments in the tests just because the exact same comments were useful for me this time last month :).

You have a mixture of `.then`-based promises in the main component logic, and `await`s in the test file; is there a reason for this, or just is a function of the code that you were adapting from?

This is definitely the kind of component that would be well-served by adding in a storybook entry, both for reference and for speeding up the development feedback cycle.

2021-06-17 19:51 UTC, kylehilltruss commented on src/pages/MyMove/AmendOrders/AmendOrders.test.jsx
> +    expect(queryByText('Loading, please wait...')).toBeInTheDocument();
We don't have this pattern in too many places yet, but the best practice with React Testing Library is to use `getByWhatever` or `findByWhatever`, rather than `queryByWhatever`, when you expect something to be in the document. 

`queryBy` is just intended to be used for checking that something _isn't_ in the document, since the other two accessors throw errors when they don't find something while query returns `null`.

See: https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#using-query-variants-for-anything-except-checking-for-non-existence

2021-06-17 19:51 UTC, kylehilltruss commented on src/pages/MyMove/AmendOrders/AmendOrders.test.jsx
> +      expect(queryByText('Loading, please wait...')).not.toBeInTheDocument();
Generally, we don't want to use `waitFor` anymore either (again, this isn't a common pattern in our code base yet). You can replace this as:

```js
// findByWhatever throws an error if something isn't found
// so we want to move the awaited positive assertion to the top
expect(await findByRole('heading', { name: 'Upload orders', level: 5 }))).toBeInTheDocument()

// Per above, use queryBy when something _shouldn't_ be there
expect(queryByText('Loading, please wait...')).not.toBeInTheDocument()

// Other assertions in the waitFor go here
```

See, in the same blog post as above: https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#using-waitfor-to-wait-for-elements-that-can-be-queried-with-find

2021-06-17 19:51 UTC, kylehilltruss commented on src/pages/MyMove/AmendOrders/AmendOrders.test.jsx
> +      expect(queryByText('Save')).toBeInTheDocument();
This (and the cancel button test) can just be simplified down to

```js
expect(await findByText('Save')).toBeInTheDocument()
```

2021-06-17 22:10 UTC, mboren commented on src/pages/MyMove/AmendOrders/AmendOrders.test.jsx
> +    expect(queryByText('Loading, please wait...')).toBeInTheDocument();
Thanks, this is helpful! I was very much cargo culting here.

2021-06-18 00:09 UTC, mboren commented on src/pages/MyMove/AmendOrders/AmendOrders.test.jsx
> +    expect(queryByText('Loading, please wait...')).toBeInTheDocument();
I haven't been able to successfully replace queryBy with findBy or getBy. I'll see if I can get some help with this on Monday.

2021-06-18 00:09 UTC, mboren commented on src/pages/MyMove/AmendOrders/AmendOrders.test.jsx
> +      expect(queryByText('Loading, please wait...')).not.toBeInTheDocument();
Gotcha. I've gotten rid of all the `waitFor`s.

2021-06-18 00:09 UTC, mboren commented on src/pages/MyMove/AmendOrders/AmendOrders.test.jsx
> +      expect(queryByText('Save')).toBeInTheDocument();
Thanks!

2021-06-21 16:53 UTC, mboren commented on src/pages/MyMove/AmendOrders/AmendOrders.test.jsx
> +    expect(queryByText('Loading, please wait...')).toBeInTheDocument();
I got it! I think I was just misunderstanding the difference between findBy and getBy.

2021-06-21 17:54 UTC, kylehilltruss approved these changes

2021-06-21 17:58 UTC, merged