MB-8211: Copy and design changes to review shipments page
transcom/mymove pull request #6820
Opened 2021-06-16 16:09 UTC by kylehilltruss

## Description

Design requested changes be made to part of the Review Summary component - changing the presentation and copy of the link to add additional shipments, and adding in a modal to display contextual information around why a user might want or need to add additional shipments this stage.

This pull request makes those design and element changes, adds that modal, and also adds a storybook entry for the Summary component (where previously one didn't exist).

## Reviewer Notes

Ensure that the reworked Review summary looks good and displays the correct information with every combination of shipments (HHG, PPM, both HHG and PPM, NTS, etc) and move submission states.

## Setup

This pull request adds stories for the new modal (`Customer Components`/`Modals`/`AddShipmentModalStory`) and for the Review component in its entirety (`Customer Components`/`Review Shipment`). Ensure that both look good there. (`yarn storybook` as usual.) Otherwise,

```sh
make server_run
make client_run
```

## Code Review Verification Steps

* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* Closes [MB-8211](https://dp3.atlassian.net/browse/MB-8211).

## Screenshots

Before:
* https://user-images.githubusercontent.com/83614364/122254782-769a2b80-ce9b-11eb-8104-eeb560d95918.png

After:
* https://user-images.githubusercontent.com/83614364/122254467-24590a80-ce9b-11eb-93f0-724647b07085.png
* https://user-images.githubusercontent.com/83614364/122254519-2fac3600-ce9b-11eb-970c-baba98a9e205.png

2021-06-16 16:37 UTC, Ronolibert commented on src/components/Customer/Review/Summary/index.jsx
> +              <Link href={shipmentSelectionPath}>Add another shipment</Link>
Do we want it to have the same style throughout all states? Currently, it has different styles when the link has been visited or hovered

2021-06-16 16:39 UTC, Ronolibert commented on src/components/Customer/Review/Summary/index.jsx
> +            *To change these fields, contact your local PPPO office at {get(currentStation, 'name')}{' '}
[nit] Could we use the `currentStation` already in scope on line 215

2021-06-16 16:59 UTC, Ronolibert commented on src/components/Customer/Review/Summary/index.jsx
> +    const thirdSectionHasContent = showMoveSetup || showPPMShipmentSummary || (isReviewPage && mtoShipments.length > 0);
👍

2021-06-16 17:00 UTC, kylehilltruss commented on src/components/Customer/Review/Summary/index.jsx
> +              <Link href={shipmentSelectionPath}>Add another shipment</Link>
Probably a question for @cosburn

2021-06-16 17:00 UTC, Ronolibert requested changes
Just unsure on the styling for the pseudo-class but other than that looks good!

2021-06-16 17:03 UTC, kylehilltruss commented on src/components/Customer/Review/Summary/index.jsx
> +            *To change these fields, contact your local PPPO office at {get(currentStation, 'name')}{' '}
Eh, I just copy/pasted the logic around for this part since I didn't really touch this part; since I only minimally understand what the component's development intent was, I didn't even really look at what I was copy pasting.

2021-06-16 17:19 UTC, kylehilltruss commented
> Just unsure on the styling for the pseudo-class and a nit but other than that looks good!

What's up with the pseudo-class styling?

2021-06-16 21:50 UTC, cosburn commented
Looking good! Two thoughts/questions:

1 - when I click to open the modal, the page behind it jumps to the top. This is disorienting, as I'd expect the page to stay put while the modal opens and closes. Is this the default behavior of all modals? Can we make the page stay in the same position?

2 - Looking at the implemented designs, I'm wondering if we could move that `?` icon even closer to the `add another shipment` link on desktop view. As it is, it looks a bit too far away. I've included a screenshot where I scooted it closer by reducing the min-width to 24px, but just an example of what I'd like it to look like (if possible).

Neither of these are deal-breakers, please let me know!

<img width="530" alt="Screen Shot 2021-06-16 at 4 46 42 PM" src="https://user-images.githubusercontent.com/9616034/122298853-dfe16500-cec2-11eb-82b2-e34ada64a9ed.png">

2021-06-17 00:49 UTC, YanZ777 commented
@cosburn 
> 
> 1 - when I click to open the modal, the page behind it jumps to the top. This is disorienting, as I'd expect the page to stay put while the modal opens and closes. Is this the default behavior of all modals? Can we make the page stay in the same position?

It looks like it's the default behavior of all modals. I think if we're planning on changing the default behavior so that users of modals can specify which behavior they want, a new ticket should be written up and addressed in there rather than this PR.

2021-06-17 01:06 UTC, YanZ777 commented on src/components/Customer/Review/Summary/index.jsx
> +  toggleModal = () => {
Bah! I should have converted this to a functional component when I have the chance. I think I shall write up a ticket to do so.

2021-06-17 16:00 UTC, kylehilltruss commented on src/components/Customer/Review/Summary/index.jsx
> +  toggleModal = () => {
I honestly considered doing just that, but I didn't really have the background knowledge about development intent or the business logic that it's implementing, plus... eh, it's a short week.

2021-06-17 16:36 UTC, YanZ777 commented on src/components/Customer/Review/Summary/index.jsx
> +  toggleModal = () => {
Yea that makes sense. I'll write up a ticket for converting this.

2021-06-17 18:30 UTC, YanZ777 approved these changes

2021-06-17 18:37 UTC, cosburn commented on src/components/Customer/Review/Summary/index.jsx
> +              <Link href={shipmentSelectionPath}>Add another shipment</Link>
It should behave like other inline links, so I think the state styles are good.

2021-06-17 18:47 UTC, cosburn approved these changes
Looks good to me!

2021-06-17 19:56 UTC, merged