[MB-8101] implement new uploads table design
transcom/mymove pull request #6875
Opened 2021-06-24 16:39 UTC by mboren

## Description

I took a stab at rewriting the UploadsTable component to match new designs.

### Designs
these designs are for the whole page, not just the component that I'm working on
- [mobile, some uploads](https://app.zeplin.io/project/5f9c266162cd02a552a0b661/screen/609c212513e4c7ab31622465)
- [mobile, no uploads](https://app.zeplin.io/project/5f9c266162cd02a552a0b661/screen/609c2125c29a3abce3128d23)
- [desktop, some uploads](https://app.zeplin.io/project/5f9c266162cd02a552a0b661/screen/609c2126a7cf19ac459cf219)

## Reviewer Notes

Generally I'm not sure what our conventions are for a lot of things.
I was definitely flailing around when writing the CSS, so if you're wondering "did he have a reason for doing it this weird way?" the answer is no.

The delete button jumps away from the right edge of the screen when the screen gets small enough. It seems like it's related to `justify-content: center` being set on `usa-button` in [_overrides.scss](https://github.com/transcom/mymove/blob/master/src/shared/styles/_overrides.scss#L12) and a media query at `mobile-lg` that changes the `width` from `100%` to `auto`.
I don't really know what to do with this. Is there something I did that's interacting badly with these styles? I don't notice this behavior in other places.

![image](https://user-images.githubusercontent.com/2627844/123298729-a665b680-d4cd-11eb-980d-56a311b39f50.png)

In the design, when there are no uploads, we don't show the uploads table. I tried rendering nothing in this case, but had trouble figuring out how to test that with RTL/jest.

## Setup
http://localhost:6006/?path=/docs/customer-components-uploadstable--uploads-table

```sh
echo "Code goes here"
```

## Code Review Verification Steps

* [ ] If the change is risky, it has been tested in experimental before merging.
* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] The requirements listed in [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely) have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://github.com/transcom/mymove/wiki/migrate-the-database#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](tbd) for this change
* [this article](tbd) explains more about the approach used.

## Screenshots

If this PR makes visible UI changes, an image of the finished UI can help reviewers and casual
observers understand the context of the changes. A before image is optional and
can be included at the submitter's discretion.

Consider using an animated image to show an entire workflow instead of using multiple images. You may want to use GIPHY CAPTURE for this! 📸

_Please frame screenshots to show enough useful context but also highlight the affected regions._

2021-06-25 15:51 UTC, Shkeating commented on src/components/UploadsTable/UploadsTable.module.scss
> +h6 {
it appears that this is affecting the typography page in storybook?? I'm not sure why. But is you scope the selector to the wrapping class of the component that should fix it.

2021-06-25 15:51 UTC, Shkeating commented on src/components/UploadsTable/UploadsTable.module.scss
> +  @include u-padding-left(0);
same here, I am seeing the universal ul styles getting impacted in storybook. Same solution as the previous comment, if you wrap these in your component's wrapping class, that should fix it.

2021-06-25 16:12 UTC, mboren commented on src/components/UploadsTable/UploadsTable.module.scss
> +h6 {
Ahh that's probably what's causing the happo diffs. I thought the whole module thing would prevent this, but I guess not.

2021-06-25 19:57 UTC, jacquelineIO reviewed
Ran locally fine for me. Looking for a f/e reviewer to approve.

2021-06-25 20:05 UTC, kylehilltruss requested changes
Looks pretty good, other than needing a tweak and adding new icons to the icon story.

2021-06-25 20:05 UTC, kylehilltruss commented on src/icons.js
> +  faFileImage,
Can you add these to the icons story? `src/stories/icons.stories.jsx`

2021-06-25 20:58 UTC, mboren commented on src/components/UploadsTable/UploadsTable.jsx
> +      <SectionWrapper className={classNames(styles.wrapper)}>
Done!

2021-06-25 20:58 UTC, mboren commented on src/icons.js
> +  faFileImage,
Done!

2021-06-28 13:35 UTC, jenniferlynparsons requested changes
Just one small change for clarity in the naming and otherwise looks good!

2021-06-28 13:35 UTC, jenniferlynparsons commented on src/components/UploadsTable/UploadsTable.module.scss
> +.wrapper {
This should probably be renamed to something like `uploadsTableContainer`.

2021-06-28 14:55 UTC, Shkeating commented on src/components/UploadsTable/UploadsTable.module.scss
> +h6 {
yeah i thought so too? weird!!

2021-06-28 14:57 UTC, Shkeating approved these changes
looks good!!

2021-06-28 16:20 UTC, mboren commented on src/components/UploadsTable/UploadsTable.module.scss
> +.wrapper {
Done

2021-06-28 16:21 UTC, jenniferlynparsons approved these changes
Looks good!

2021-06-28 19:30 UTC, merged