MB-8476 Wire up the Customer save button for uploading amended orders
transcom/mymove pull request #6897
Opened 2021-06-29 18:04 UTC by felipe-lee

## Description

GIVEN a customer has received updated orders
WHEN uploading updated documentation for their new orders
THEN the customer has a save button to click after uploading 
AND THEN receives a success message or an error message.

## Reviewer Notes

Is there anything you would like reviewers to give additional scrutiny?

## Setup

1. Run server and customer client

    ```sh
    make server_run
    ```

    ```sh
    make client_run
    ```

2. Log in as a customer that has already submitted their move.
3. Click to upload new orders.
4. Upload new orders.
5. Click Save.
6. Log in as a TOO. You should see the move as one that needs approval again.

## Code Review Verification Steps

* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] The requirements listed in [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely) have been satisfied.
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-8476) for this change
* [this article](tbd) explains more about the approach used.

## Screenshots

If this PR makes visible UI changes, an image of the finished UI can help reviewers and casual
observers understand the context of the changes. A before image is optional and
can be included at the submitter's discretion.

Consider using an animated image to show an entire workflow instead of using multiple images. You may want to use GIPHY CAPTURE for this! 📸

_Please frame screenshots to show enough useful context but also highlight the affected regions._

2021-06-30 21:06 UTC, mboren commented on src/pages/MyMove/AmendOrders/AmendOrders.jsx
> +    return createAmendedOrdersUploadForDocument(file, documentId);
you might already be aware of this, but just in case: we expect orders to have `null` for `uploaded_amended_orders` if a service member has not uploaded any orders before, so we're working on a separate endpoint for uploading amended order files right now. That endpoint will take `order_id` instead of `document_id` and will create the document if it doesn't exist.
Nothing you need to change for this, just wanted to make sure we're in sync

2021-07-02 15:24 UTC, Ronolibert requested changes
When I to upload an amended order, the list does not update and when I click `Save` I am getting `orders.uploadAmendedOrders failed: Error: Required parameter ordersId is not provided`

2021-07-02 17:59 UTC, felipe-lee commented
> When I tried to upload an amended order with the `hhg@multiple.pickup.amendedOrders.submitted` account, the list does not update and when I click `Save` I am getting `orders.uploadAmendedOrders failed: Error: Required parameter ordersId is not provided`

Thanks for testing it out. I actually just updated the description for the PR because uploading amended orders isn't functional yet. Our pr is more for once you do have them, you can click submit and it gets routed correctly. 

As for the error on save, it's working for me, I wonder if it gets into a weird state when you try uploading orders and then saving.

2021-07-02 18:14 UTC, mboren commented
I suspect that there might be an issue with the way the devseed data is set up because the table should be showing just the file name and not the full path. I don't know if that has to do with this PR or is a pre-existing issue with test fixtures. I'm pretty sure this only affects the test data and not the actual functionality though, so not super worried about it.

![image](https://user-images.githubusercontent.com/2627844/124313401-adbc3e00-db25-11eb-8a1a-c59373817931.png)

looks like the `uploads` table is getting filled inconsistently:
![image](https://user-images.githubusercontent.com/2627844/124313950-7d28d400-db26-11eb-8c9d-5f968870c8fb.png)


also the table breaking for long filenames is 100% my fault. I'll file a bug for it.

2021-07-02 19:33 UTC, Ronolibert commented on src/pages/MyMove/AmendOrders/AmendOrders.test.jsx
> +        // Disable this rule because makeSwaggerRequest does not throw an error if the API call fails
👍

2021-07-02 19:36 UTC, Ronolibert approved these changes
Ahh ok, I misunderstood what the scope of this card is. I tested it and now behaves as expected

2021-07-02 20:57 UTC, mboren commented on src/pages/MyMove/AmendOrders/AmendOrders.jsx
> +    return createAmendedOrdersUploadForDocument(file, documentId);
to clarify: you might want coordinate with @jacquelineIO when you merge your PR because her changes in https://github.com/transcom/mymove/pull/6908 will conflict with this and should take precedence.

2021-07-02 21:01 UTC, mboren approved these changes
I think this looks good. The Happo diffs for the file uploader are weird, I was seeing exactly the same thing last night (https://ustcdp3.slack.com/archives/CP6F568DC/p1625185771091500), I think they can be ignored.

2021-07-02 21:15 UTC, felipe-lee commented on src/pages/MyMove/AmendOrders/AmendOrders.jsx
> +    return createAmendedOrdersUploadForDocument(file, documentId);
Since our pr isn't actually meant to deal with handling uploads, maybe we should just undo this bit and leave it for the other pr to set up

2021-07-02 21:44 UTC, merged