[MB-9257] Create EditBillableWeight storybook component"
transcom/mymove pull request #7259
Opened 2021-08-27 18:08 UTC by Ronolibert

## Description

Creates `EditBillableWeight` storybook component

## Setup
`make storybook`
Search for `EditBillableWeight` component
Click `Edit` button
Should show alternate edit view
Click `Cancel` button
Should go back to Edit button view

## Code Review Verification Steps
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-9257) for this change

## Screenshots

<img width="449" alt="Screen Shot 2021-08-27 at 11 06 17 AM" src="https://user-images.githubusercontent.com/13622298/131170407-e40a063e-cced-4e99-9b8f-ee2e35ea5172.png">
<img width="449" alt="Screen Shot 2021-08-27 at 11 06 34 AM" src="https://user-images.githubusercontent.com/13622298/131170452-b240b76c-d4a3-44d3-9280-1af58bf670a6.png">
<img width="420" alt="Screen Shot 2021-09-01 at 12 02 57 PM" src="https://user-images.githubusercontent.com/13622298/131728874-fca7ab22-9719-414e-af4f-840f1b2872ac.png">

2021-08-28 01:11 UTC, YanZ777 requested changes

2021-08-30 14:56 UTC, Ronolibert commented on src/components/Office/BillableWeight/EditBillableWeight/EditBillableWeight.jsx
> +        <Button onClick={toggleEdit}>Save changes</Button>
I was thinking that that would be changed added when the actual submit is put in place

2021-08-30 14:57 UTC, Ronolibert commented on src/components/Office/BillableWeight/EditBillableWeight/EditBillableWeight.jsx
> +        <strong>{formatWeight(estimatedWeight)}</strong> <span>| 110% of total estimated weight</span>
I'm not sure, I just left it a static prop incase these values are already calculated on the backend

2021-08-30 15:59 UTC, cosburn approved these changes
Looks good to me!

2021-08-31 16:12 UTC, Ronolibert commented on src/components/Office/BillableWeight/EditBillableWeight/EditBillableWeight.jsx
> +        <strong>{formatWeight(estimatedWeight)}</strong> <span>| 110% of total estimated weight</span>
Changed this to do the calculation!

2021-08-31 16:12 UTC, Ronolibert commented on src/components/Office/BillableWeight/EditBillableWeight/EditBillableWeight.jsx
> +export default function EditBillableWeight({ weightAllowance, estimatedWeight }) {
Added support for this case! Can now render max billable weight case and billable weight

2021-08-31 16:17 UTC, cosburn approved these changes
still good! :D

2021-08-31 21:13 UTC, donaldthai commented on src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.jsx
> +        <EditBillableWeight />
Small thing here, the billable weight text value should disappear after the edit button is clicked.

Currently shows the text value
![image](https://user-images.githubusercontent.com/1522549/131576504-1b9333ba-777c-432c-a01a-29a7c2c98363.png)

Spec sheet shows that it should not show the text value after clicking edit
![image](https://user-images.githubusercontent.com/1522549/131576634-f620b7f6-6031-4100-93d5-97833e5511a7.png)

2021-09-01 01:48 UTC, YanZ777 commented on src/components/Office/BillableWeight/EditBillableWeight/EditBillableWeight.jsx
> +    <Button className={styles.editBtn} onClick={toggleEdit}>
When in edit mode, the component should show the title, the billable or max billable weight, and whatever the user entered as remarks.

2021-09-01 19:04 UTC, Ronolibert commented on src/components/Office/BillableWeight/EditBillableWeight/EditBillableWeight.jsx
> +    <Button className={styles.editBtn} onClick={toggleEdit}>
Added this in! Not doing any state management since that'll come from the API but added it to the initial view

2021-09-01 19:04 UTC, Ronolibert commented on src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.jsx
> +        <EditBillableWeight />
Oh! MIssed this! Didn't think it was included. Added in the weight and remarks and the conditional logic

2021-09-01 19:38 UTC, donaldthai commented on src/components/Office/BillableWeight/EditBillableWeight/EditBillableWeight.jsx
> +    <Button className={styles.editBtn} onClick={toggleEdit}>
Seems like the header size is suppose to change for the `Max billable weight`, which is an interesting design choice: 
![image](https://user-images.githubusercontent.com/1522549/131733159-f767e009-9cc2-4328-aa65-9807a0f4f97d.png)

Currently
![image](https://user-images.githubusercontent.com/1522549/131733273-6843622a-312d-4a64-bc09-37856f6e51f8.png)

2021-09-01 19:39 UTC, donaldthai commented on src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.jsx
> +        <EditBillableWeight />
I'm still seeing the text value on the `BillableWeightShipmentCard`: 
![image](https://user-images.githubusercontent.com/1522549/131733513-533fe69e-a313-46a1-901e-7a050586e183.png)

2021-09-02 01:19 UTC, YanZ777 approved these changes
Looks great! You'll want to fix the linter warning though in EditBillableWeight.stories.jsx.

2021-09-02 14:37 UTC, Ronolibert commented on src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.jsx
> +        <EditBillableWeight />
Good catch, updated this to solely use the `EditBillableWeight` component

2021-09-02 15:31 UTC, donaldthai approved these changes
🚀  Thanks for working on this!

2021-09-02 16:07 UTC, merged