MB-9306 create prime update reweigh endpoint
transcom/mymove pull request #7274
Opened 2021-08-31 00:10 UTC by eamahanna

## Description

This PR adds a new prime api endpoint, `UpdateReweigh`. There are only two fields that the prime will be able to edit: `Weight` and `VerificationReason`. Both of these fields were made optional because the prime can update the weight for the reweigh OR provide the verification reason to why they cannot complete the reweigh.

## Setup
To run the unit tests, execute `make server_test`

To verify this endpoint, complete the following steps:
* Navigate to the mymove repo
* Execute `make db_dev_reset db_dev_e2e_populate`
* Execute `make server_run`
* Using your terminal or your db viewer, navigate to the reweighs table and copy the `id` and `shipment_id` for a record that does not have a weight already associated with it.
* Using postman hit the UpdateReweigh endpoint and use the copied `id` and `shipment_id` values to fill in the request params.
* Use the following body for the request:
```
{
    "weight": 2000,
    "verificationReason": "The reweigh was not performed because the shipment was already delivered"
}
``` 

## Code Review Verification Steps

* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [MB-7233](https://dp3.atlassian.net/browse/MB-7233) for this change
* [MB-7233](https://dp3.atlassian.net/browse/MB-9306) for this change

2021-08-31 18:06 UTC, rogeruiz commented
thanks @eamahanna I'll run through this review shortly.

2021-08-31 18:43 UTC, eamahanna commented
@rogeruiz This PR isn't ready for review. I should have left it in draft. I will ping the roci channel when it is ready.

2021-09-03 17:15 UTC, sandy-wright commented on swagger/prime.yaml
> +        and response to be updated. This endpoint **cannot create** a reweigh.
We discussed this description during the Prime API Doc Review meeting this week (meeting notes). Here's what I would suggest as the description:

> This endpoint can be used to update a reweigh with a new weight or to provide the reason why a reweigh did not occur. Only one of weight or verificationReason should be sent in the request body.
>
> A **reweigh** is the second recorded weight for a shipment, as validated by certified weight tickets. Applies to one shipment. A reweigh can be triggered automatically, or requested by the customer or transportation office. Not all shipments are reweighed, so not all shipments will have a reweigh weight.

2021-09-03 17:31 UTC, eamahanna commented on swagger/prime.yaml
> +        and response to be updated. This endpoint **cannot create** a reweigh.
Done!

2021-09-03 18:03 UTC, sandy-wright reviewed
LGTM! I had a couple of really small comments I'll let you look at and decide on - just ping me again when you're good and I'll approve. Thanks for adding all those tests, those are super great

I was also wondering, should we ever allow the Prime to update the reweigh weight AND the verification reason? Can they do both? To be clear, I'm totally fine with not adding that validation right now (less is more at this point in the process, plus Namibia is working on that bit), but I'm wondering from a process standpoint if that makes sense

2021-09-03 18:05 UTC, rogeruiz requested changes
This looks great @eamahanna good work. I have some minor updates for readability and fixing some typos. otherwise LGTM 🌈 

All the tests passed locally after running `make server_test` and I was able to run through the manual steps as well.

2021-09-03 18:09 UTC, sandy-wright commented on pkg/handlers/primeapi/reweigh_test.go
> +		// Testcase:   reweigh us updated with the verrification reason
🦅

2021-09-03 18:15 UTC, rogeruiz commented on pkg/services/move_task_order/move_task_order_fetcher.go
> +			return &models.Move{}, err
We'd have to change the function signature here in order to return just the error though.
```go
func (f moveTaskOrderFetcher) FetchMoveTaskOrder(appCtx appcontext.AppContext, searchParams *services.MoveTaskOrderFetcherParams) (*models.Move, error) {
```

2021-09-03 18:21 UTC, rogeruiz commented on pkg/services/move_task_order/move_task_order_fetcher.go
> +			return &models.Move{}, err
Out of curiosity, I went all the way back to the original commit that introduced this signature for these functions and couldn't find much, but it seems like the original includes the return of the tuple. Looks like if it's an error, it's an empty model for the sake of keeping that function signature.

https://github.com/transcom/mymove/pull/3196

2021-09-03 18:22 UTC, rogeruiz commented on pkg/services/reweigh/reweigh_updater.go
> +	updatedReweigh.Shipment = shipment
ooh good catch here @sandy-wright I missed this in my review.

2021-09-03 18:28 UTC, rogeruiz commented on pkg/services/move_task_order/move_task_order_fetcher.go
> +	}
If I'm reading this correctly, this means that we go through all the shipments for a particular move to find possible reweighs? I don't see this being too bad unless there's a lot of shipments in a given move. but yeah this will be refactored later.

2021-09-03 18:35 UTC, eamahanna commented on pkg/services/move_task_order/move_task_order_fetcher.go
> +	}
Sounds good. I will leave it as is now. I am going to make a ticket to refactor the shipments to have a has_many relationship, so this isn't forever.

2021-09-03 18:36 UTC, eamahanna commented on pkg/services/move_task_order/move_task_order_fetcher.go
> +			return &models.Reweigh{}, err
I think this would be a good topic to do a quick chat about in the milmove backend checkin

2021-09-03 18:36 UTC, eamahanna commented on pkg/services/reweigh/reweigh_updater.go
> +	updatedReweigh.Shipment = shipment
Ah! I think this is an old bit of code. 🤦‍♀️ removing now

2021-09-03 18:37 UTC, eamahanna commented on pkg/handlers/primeapi/reweigh.go
> +			return mtoshipmentops.NewUpdateReweighNotFound().WithPayload(payloads.ClientError(handlers.NotFoundMessage, err.Error(), h.GetTraceID()))
sure!

2021-09-03 20:44 UTC, rogeruiz approved these changes
🌈 LGTM

2021-09-03 21:01 UTC, sandy-wright commented on pkg/services/move_task_order/move_task_order_fetcher.go
> +			return &models.Move{}, err
Oh, I wasn't advocating for changing the signature or _only_ returning the error. It's just that we could be doing:
```go
return nil, err
```
here instead of making an empty model. I think this is cleaner than needlessly creating empty objects. We use this pattern a lot in other areas of the codebase too.

2021-09-03 21:03 UTC, sandy-wright commented on pkg/services/move_task_order/move_task_order_fetcher.go
> +			return &models.Move{}, err
Even in that PR, they never use the empty move if they get an error. Seems pointless to return anything when nil is available.

2021-09-03 21:05 UTC, sandy-wright approved these changes
🚀

2021-09-03 21:06 UTC, merged