use span vs p to supress warnings about inline vs block tags
transcom/mymove pull request #7277
Opened 2021-08-31 17:50 UTC by lynzt

## Description

Explain a little about the changes at a high level.

## Reviewer Notes

Is there anything you would like reviewers to give additional scrutiny?

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

```sh
echo "Code goes here"
```

## Code Review Verification Steps

* [ ] If the change is risky, it has been tested in experimental before merging.
* [ ] Code follows the guidelines for [Logging](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#logging)
* [ ] The requirements listed in [Querying the Database Safely](https://github.com/transcom/mymove/wiki/Backend-Programming-Guide#querying-the-database-safely) have been satisfied.
* Any new migrations/schema changes:
  * [ ] Follow our guidelines for zero-downtime deploys (see [Zero-Downtime Deploys](https://github.com/transcom/mymove/wiki/migrate-the-database#zero-downtime-migrations))
  * [ ] Have been communicated to #g-database
  * [ ] Secure migrations have been tested following the instructions in our [docs](https://github.com/transcom/mymove/wiki/migrate-the-database#secure-migrations)
* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](tbd) for this change
* [this article](tbd) explains more about the approach used.

## Screenshots

If this PR makes visible UI changes, an image of the finished UI can help reviewers and casual
observers understand the context of the changes. A before image is optional and
can be included at the submitter's discretion.

Consider using an animated image to show an entire workflow instead of using multiple images. You may want to use GIPHY CAPTURE for this! 📸

_Please frame screenshots to show enough useful context but also highlight the affected regions._

2021-09-01 14:59 UTC, Shkeating requested changes

2021-09-01 14:59 UTC, Shkeating commented on src/pages/MyMove/Home/index.jsx
> +          <br />
i think you can remove these `<br />`s since the line height styling is adding space between the paragraphs. I'm noticing there is extra space between the paragraphs in the new output.

<img width="646" alt="image" src="https://user-images.githubusercontent.com/59394696/131694765-ccda559e-cbcc-453b-8626-6d4e38af38ab.png">

2021-09-01 15:17 UTC, Shkeating commented on src/pages/MyMove/Home/Home.module.scss
> +  line-height: 1.4;
add
`display: inline-block`
here

2021-09-01 15:17 UTC, Shkeating requested changes

2021-09-01 15:17 UTC, Shkeating commented on src/pages/MyMove/Home/index.jsx
> +          <br />
take just one of these `br`s out

2021-09-01 15:21 UTC, Shkeating commented on src/pages/MyMove/Home/index.jsx
> +          <span className={styles.alertSecondMsg}>You don&apos;t need to do anything else in MilMove.</span>
add `margin-top-1` class to this span. should look like this:
```<span className={`margin-top-1 ${styles.alertSecondMsg}`}>```

2021-09-07 17:50 UTC, kylehilltruss commented
Took over this PR for Lindsay since she's out this week.

@Shkeating Can you (or someone else) take another look?

2021-09-07 18:24 UTC, Shkeating approved these changes
looks good!

2021-09-07 18:43 UTC, merged