Mb 7290 sit so nt
transcom/mymove pull request #7355
Opened 2021-09-13 17:28 UTC by NamibiaTorres

## Draft PR

## Description

Explain a little about the changes at a high level.

## Reviewer Notes

Is there anything you would like reviewers to give additional scrutiny?

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

```sh
echo "Code goes here"
```

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-7290) for this change

2021-09-14 21:50 UTC, eamahanna commented on pkg/services/sit_extension/rules.go
> +		if sitExtension.MTOShipmentID == uuid.Nil {
Should we also check that the shipment ID exists in the DB?

2021-09-14 21:50 UTC, eamahanna commented on pkg/services/sit_extension/rules.go
> +// checkShipmentID checks that the user can't change the shipment ID
This comment doesn't quite make sense. The shipment ID is required to make a sit extension request.

2021-09-14 21:53 UTC, eamahanna commented on pkg/services/sit_extension/rules.go
> +		// Check that we have something in the Status field:
Update comment

2021-09-14 22:03 UTC, eamahanna commented on pkg/services/sit_extension/rules_test.go
> +			Move: models.Move{
You can always use the func `testdatagen.MakeAvailableMove` to make the move and pass it all in or you will need to add `Status: models.MoveStatusAPPROVED`

2021-09-15 17:00 UTC, sandy-wright requested changes
Looks really good! Super solid overall, and I really liked the way you reorganized the `validation.go` file. Subtle, but putting the interface at the bottom helps differentiate it, I think.

I did request a few changes though. Some of them might be confusing (sorry, I was struggling to word some things 😓), so just let me know if you want to go over anything!

2021-09-15 17:13 UTC, NamibiaTorres commented on pkg/services/sit_extension/sit_extension_creator.go
> +func NewSitExtensionCreator(db *pop.Connection) services.SITExtensionCreator {
> Should remove this `db` from the function arguments, we don't use it anymore.

Oh yes! I had to do this reweighs too.

2021-09-15 19:26 UTC, sandy-wright commented on pkg/services/sit_extension/sit_extension_creator.go
> +//}
You can delete this commented out bit entirely now :)

2021-09-15 19:27 UTC, sandy-wright approved these changes
Looks like you need to resolve some conflicts before merging, but it looks good to go! I left one more small comment about deleting some commented-out code, but that was it ☺️. Good work!

2021-09-15 20:29 UTC, merged