[MB-9026] add components to  the review shipment weights sidebar
transcom/mymove pull request #7366
Opened 2021-09-14 19:47 UTC by pearl-truss

## Description

Incorporates the review billable weight content into the document viewer sidebar in the review billable weights flow. This PR also added in some logic for:
- displaying the correct flags in the ship container component for missing estimated or reweighs
- hiding the reweigh related fields on the shipment card when a reweigh hasn't been requested on a shipment and it 
- the max billable weight exceeded flag to the edit max billable weight sidebar \
- the warning flags on the shipment sidebar for the missing info flag (appears when a reweigh was requested and the shipment doesnt have a reweigh weight or when the shipment is missing an estimated weight) 
- the over weight shipment flag appears when the shipment's original weight is more than 100% of the estimated weight

## Reviewer Notes

- This should be merged after https://github.com/transcom/mymove/pull/7359 
- Double check that the logic is correct

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

```sh
make server_run
make office_client_run
```
Log into TIO account
Click on any shipment any of these locators:

BILWEI
MULTRW
MISHRW
MAXCED

View payment requests
Click on Review weights
Expected result: Max billable weights page should have relevant information inside of components. You should be able to click the Review Shipments button in the sidebar and see the shipment specific weight info. If there's multiple shimpents, clicking Next Shipment will display the next shipment 

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-9026) for this change
* [specs for the page](https://app.zeplin.io/project/6112d5999a811689179723b4/screen/611ac58296d7a833928b98b9) 

## Screenshots

<img width="439" alt="Screen Shot 2021-09-14 at 3 45 42 PM" src="https://user-images.githubusercontent.com/67110378/133323740-7ecc28a1-b077-45c8-92ae-c4dc6104a2c3.png">
<img width="436" alt="Screen Shot 2021-09-14 at 3 45 48 PM" src="https://user-images.githubusercontent.com/67110378/133323744-c5eab428-85d5-4ac2-8326-061d00af45a4.png">
<img width="415" alt="Screen Shot 2021-09-14 at 3 46 09 PM" src="https://user-images.githubusercontent.com/67110378/133323745-0d79220c-12ca-4986-8bf7-3f8eacd2bb56.png">

2021-09-14 22:03 UTC, YanZ777 requested changes

2021-09-14 22:03 UTC, YanZ777 commented on src/utils/shipmentWeights.js
> +export function calcWeightRequested(mtoShipments) {
There are custom hooks that you can use inside of `custom.js`!

2021-09-14 22:23 UTC, donaldthai commented on src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.jsx
> +                )}
I think we also need to include the case of missing estimated weight. https://app.zeplin.io/project/6112d5999a811689179723b4/screen/611ac58296d7a833928b98b9

2021-09-15 14:13 UTC, pearl-truss commented on src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.jsx
> +                )}
The conditional statement here includes `!selectedShipment.primeEstimatedWeight`. Or are you referring to something else?

2021-09-15 14:48 UTC, pearl-truss commented on src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.jsx
> +              <WeightSummary
this is addressed

2021-09-15 14:48 UTC, pearl-truss commented on src/utils/shipmentWeights.js
> +export function calcWeightRequested(mtoShipments) {
thanks! this is addressed

2021-09-15 14:53 UTC, donaldthai commented on src/pages/Office/ReviewBillableWeight/ReviewBillableWeight.jsx
> +                )}
Oops, didn't see that part! Looks goooddd!

2021-09-15 17:53 UTC, donaldthai approved these changes
🚀

2021-09-15 19:08 UTC, cosburn approved these changes
Reviewed screenshot of requested style changes, looks good!

(slack thread for historical reference: https://ustcdp3.slack.com/archives/C0292K7MY31/p1631725632135000?thread_ts=1631719857.130700&cid=C0292K7MY31)

2021-09-15 21:01 UTC, YanZ777 approved these changes
Looks good to me! Thanks for making those changes.

2021-09-15 21:24 UTC, merged