[MB-8758] TOO can approve and deny SIT extensions (frontend)
transcom/mymove pull request #7410
Opened 2021-09-20 23:45 UTC by hannaliebl

## Description

Add the ability for a TOO to approve and deny SIT extensions on the front end.

## Reviewer Notes

Note: I am putting this in draft as I need to finish tests still, just if folks want to look at it early, feel free.

## Setup

```sh
make db_dev_e2e_populate
make server_run
make client_run
```

Install SEPEND move code.

## Code Review Verification Steps

- Go to the MTO page and look at the SIT Extensions section
- Note the tag saying SIT EXTENSION
- Click on the View request link
- Approve the SIT extension and add some comments
- The tag disappears and the SIT extension shows up in the list below in the APPROVED state
- Reset the DB or just set the SIT Extension you just approved back to a PENDING state
- Now try denying the SIT extension, note it also removes the SIT extension tag and moves the SIT extension into the DENIED state.
- Test out the form validation on the modal, etc.

## Reference

* [Jira story](https://dp3.atlassian.net/browse/MB-8758) for this change

## Screenshots
<img width="714" alt="Screen Shot 2021-09-20 at 7 43 20 PM" src="https://user-images.githubusercontent.com/3903208/134091122-2765e8b3-1a1e-410d-9111-b70d6597c436.png">

<img width="715" alt="Screen Shot 2021-09-20 at 7 38 26 PM" src="https://user-images.githubusercontent.com/3903208/134090458-1460d0e2-7499-47a3-85d5-48455d443b55.png">

<img width="715" alt="Screen Shot 2021-09-20 at 7 38 35 PM" src="https://user-images.githubusercontent.com/3903208/134090465-f7eb778f-079f-4178-99e1-79cd7320cbc1.png">

2021-09-21 18:33 UTC, monfresh commented on pkg/testdatagen/scenario/shared.go
> +func createMoveWithPendingSITExtension(appCtx appcontext.AppContext, userUploader *uploader.UserUploader) {
This is duplicating a lot of the setup in `createMoveWithSITExtensionHistory`. Ideally, these functions should be short and should make use of other functions for each of the setup steps. Here is how I would refactor this:

```golang
func createMoveWithApprovedSITExtensions(appCtx appcontext.AppContext, userUploader *uploader.UserUploader) {
	db := appCtx.DB()
	filterFile := &[]string{"150Kb.png"}
	serviceMember := makeServiceMember(db)
	orders := makeOrdersForServiceMember(serviceMember, db, userUploader, filterFile)
	move := makeMoveForOrders(orders, db, "SITEXT", models.MoveStatusAPPROVALSREQUESTED)
	shipment := makeApprovedShipmentForMove(appCtx, move)
	makeSITExtensionsForShipment(appCtx, mtoShipmentSIT)
	makePaymentRequestForSITExtension(appCtx, move)
}

func createMoveWithPendingSITExtensions(appCtx appcontext.AppContext, userUploader *uploader.UserUploader) {
	db := appCtx.DB()
	filterFile := &[]string{"150Kb.png"}
	serviceMember := makeServiceMember(db)
	orders := makeOrdersForServiceMember(serviceMember, db, userUploader, filterFile)
	move := makeMoveForOrders(orders, db, "SEPEND", models.MoveStatusAPPROVALSREQUESTED)
	shipment := makeApprovedShipmentForMove(appCtx, move)
	makePendingSITExtensionsForShipment(appCtx, shipment)
	makePaymentRequestForSITExtension(appCtx, move)
}

func makeApprovedShipmentForMove(appCtx appcontext.AppContext, move models.Move) models.MTOShipment {
    db := appCtx.DB()
	shipment := testdatagen.MakeMTOShipment(db, testdatagen.Assertions{
		Move: move,
		MTOShipment: models.MTOShipment{
			Status: models.MTOShipmentStatusApproved,
		},
	})
    
    return shipment
}

func makePaymentRequestForSITExtension(appCtx appcontext.AppContext, move models.Move) {
    db := appCtx.DB()
	paymentRequestSIT := testdatagen.MakePaymentRequest(db, testdatagen.Assertions{
		PaymentRequest: models.PaymentRequest{
			ID:            uuid.Must(uuid.NewV4()),
			Status:        models.PaymentRequestStatusReviewed,
			ReviewedAt:    swag.Time(time.Now()),
			MoveTaskOrder: move,
		},
		Move: move,
	})

	serviceItemASIT := testdatagen.MakeMTOServiceItemBasic(db, testdatagen.Assertions{
		MTOServiceItem: models.MTOServiceItem{Status: models.MTOServiceItemStatusApproved},
		PaymentRequest: paymentRequestSIT,
		ReService: models.ReService{
			ID: uuid.FromStringOrNil("9dc919da-9b66-407b-9f17-05c0f03fcb50"), // CS - Counseling Services
		},
	})

	serviceItemBSIT := testdatagen.MakeMTOServiceItemBasic(db, testdatagen.Assertions{
		MTOServiceItem: models.MTOServiceItem{Status: models.MTOServiceItemStatusApproved},
		PaymentRequest: paymentRequestSIT,
		ReService: models.ReService{
			ID: uuid.FromStringOrNil("1130e612-94eb-49a7-973d-72f33685e551"), // MS - Move Management
		},
	})

	testdatagen.MakePaymentServiceItem(db, testdatagen.Assertions{
		PaymentServiceItem: models.PaymentServiceItem{
			Status: models.PaymentServiceItemStatusApproved,
		},
		MTOServiceItem: serviceItemASIT,
		PaymentRequest: paymentRequestSIT,
	})

	testdatagen.MakePaymentServiceItem(db, testdatagen.Assertions{
		PaymentServiceItem: models.PaymentServiceItem{
			Status: models.PaymentServiceItemStatusDenied,
		},
		MTOServiceItem: serviceItemBSIT,
		PaymentRequest: paymentRequestSIT,
	})
}

func makePendingSITExtensionsForShipment(appCtx appcontext.AppContext, shipment models.MTOShipment) {
	db := appCtx.DB()

	for i := 0; i < 2; i++ {
		testdatagen.MakePendingSITExtension(db, testdatagen.Assertions{
			MTOShipment: shipment,
		})
	}
}
```

2021-09-21 18:35 UTC, monfresh commented on pkg/testdatagen/scenario/shared.go
> +func createMoveWithPendingSITExtension(appCtx appcontext.AppContext, userUploader *uploader.UserUploader) {
Also, in my PR, I created a move that has pending SIT extensions. I don't think we need both, so once we merge everything, I think we can remove this one here since the one I created has other useful things to test with.

2021-09-21 20:21 UTC, Ryan-Koch approved these changes
I think Moncef's comment is worth addressing, but looking at the rest of it things seem reasonable to me. I was able to do the things testing locally.

2021-09-22 14:13 UTC, hannaliebl commented
@monfresh @Ryan-Koch I went ahead and removed my changes to devseed after merging in master/Moncef's PR. Now it can be verified with the `PNDING` move code that Moncef added.

2021-09-22 14:25 UTC, monfresh commented
Thanks Hanna! To clarify, the move I created is `PENDNG`, although `PNDING` might have been a better name 😄

2021-09-22 14:27 UTC, hannaliebl commented
@monfresh ha, sorry. I corrected my comments/PR description.

2021-09-22 19:07 UTC, Shkeating requested changes
I'm noticing space getting added that should not be, but other than that its lookin good!

<img width="714" alt="134091122-2765e8b3-1a1e-410d-9111-b70d6597c436" src="https://user-images.githubusercontent.com/59394696/134406200-653b8cd7-047d-48fc-83da-86e506560f7c.png">

2021-09-23 13:50 UTC, hannaliebl commented
@Shkeating thanks! I fixed it in the latest commit.

2021-09-23 16:15 UTC, Shkeating approved these changes
looks great!!

2021-09-23 16:16 UTC, merged