[MB-4727] TOO can submit and approve SIT extensions (frontend)
transcom/mymove pull request #7451
Opened 2021-09-27 17:05 UTC by hannaliebl

## Description

Allow TOO to create and auto-approve a SIT extension

## Reviewer Notes

- Once JP's current PR is merged, this edit button will be moved to the summary info at the top of the SIT extension panel.
- I asked in the feature channel about how/when to hide the success alert.

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

```sh
make server_run
make client_run
```

Use `PENDNG` move. Go to MTO details page - note edit button isn't there. Go ahead and approve or deny the two pending SIT extensions. Then the edit button should show up and the modal and ability to auto-approve SIT should show up.

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-4727) for this change

## Screenshots
![Screen Shot 2021-09-27 at 12 59 22 PM](https://user-images.githubusercontent.com/3903208/134953327-4853f1c8-f4d6-4300-a152-a01643a0c555.png)
![Screen Shot 2021-09-27 at 12 59 13 PM](https://user-images.githubusercontent.com/3903208/134953336-cb530c0e-64df-461c-a20d-0dfd7d2d5e90.png)

2021-09-27 21:04 UTC, Shkeating requested changes
<img width="299" alt="image" src="https://user-images.githubusercontent.com/59394696/134985074-a895aa82-4dae-48fa-a279-bca20b014e27.png">

This edit button needs ~16px of space to the right of it

2021-09-28 13:20 UTC, hannaliebl commented
@Shkeating I've updated the margin in my latest commit.

2021-09-28 21:09 UTC, Ryan-Koch approved these changes

2021-09-29 00:32 UTC, monfresh approved these changes
I tested this locally and it works as described. Great work!

2021-09-29 00:33 UTC, monfresh commented
When you're ready to merge, can you please add the "ready-to-merge" label so we can test Mergify?

2021-09-29 14:01 UTC, duncan-truss commented on src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.jsx
> +  const reviewSITExtensionSchema = Yup.object().shape({
Just pointing out I like to move static things like this to the module level (declare before the SubmitSITExtensionaModal component) since it isn't dynamically changing based on anything when the component gets created/rendered.  This is a small form so it probably isn't a big gain but some of the form schema validations can get long and complex.

2021-09-29 14:03 UTC, jenniferlynparsons approved these changes
LGTM

2021-09-29 14:04 UTC, duncan-truss commented on src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.jsx
> +                    <MaskedTextField
This component is probably overkill for a numeric field where we only need to restrict input to positive numbers and aren't doing any extra masking or formatting.

2021-09-29 14:07 UTC, duncan-truss commented on src/components/Office/SubmitSITExtensionModal/SubmitSITExtensionModal.test.jsx
> +      expect(submitBtn).toBeDisabled();
Thanks for adding this test!

2021-09-29 14:16 UTC, duncan-truss commented on src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
> +                  handleSubmitSITExtension={(formValues) => {
I think React will think this is a unique function prop since we're creating it anew everytime even if mtoShipment hasn't changed.  I think that's why usually why other functions are defined `handle*` in the above scope and sometimes use the `useCallback` hook so that it won't cause an unnecessary rerender.  The ShipmentDetails component already has the mtoShipment data or we could just pass the shipment id back to the callback and lookup the shipment etag for that id.

2021-09-29 15:20 UTC, hannaliebl commented on src/pages/Office/MoveTaskOrder/MoveTaskOrder.jsx
> +                  handleSubmitSITExtension={(formValues) => {
Hmm yeah looking at this again, it might make sense to pass the shipment down to the SIT extension component, and I think, in fact, JP's PR already does this, so I can just add the shipment id into the functions there directly.

2021-09-29 15:53 UTC, Shkeating approved these changes
✅✅✅✅✅

2021-09-29 17:05 UTC, brooksr4 approved these changes

2021-09-29 21:01 UTC, merged