MB-9604 Bug yellow highlights for original and reweigh weights
transcom/mymove pull request #7488
Opened 2021-10-01 22:53 UTC by donaldthai

## Description

This PR fixes a bug around handling of the yellow label indicators.

## Reviewer Notes

Is there anything you would like reviewers to give additional scrutiny?
- If a shipment has a billable weight set by the TIO, the yellow highlights won't show for the original weight or reweigh weight. Does this behavior make sense?

## Setup

Add any steps or code to run in this section to help others prepare to run your code:

```sh
make db_dev_e2e_populate
make server_run
make office_client_run
```

### Testing
1. Log in as TIO in office app
2. Search for move code: `MULTRW`
3. Click on payment request to see details
4. Click on `Review weights` button
5. Click on `Review shipments`, there are 4 shipments that have varying weights to show the yellow indicators

## Code Review Verification Steps

* [ ] There are no aXe warnings for UI.
* [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
* [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
* [ ] User facing changes have been reviewed by design.
* [ ] Request review from a member of a different team.
* [ ] Have the Jira acceptance criteria been met for this change?

## References

* [Jira story](https://dp3.atlassian.net/browse/MB-9604) for this change

## Screenshots

![image](https://user-images.githubusercontent.com/1522549/135693947-99371859-f0bf-492a-bc88-b01390a783fa.png)

2021-10-02 00:56 UTC, YanZ777 requested changes
Nice test coverage! 
Just a few comments about test structure, but the logic looks good to me.

2021-10-02 00:56 UTC, YanZ777 commented on pkg/testdatagen/scenario/shared.go
> +	shipmentWithMisingReweigh := testdatagen.MakeMTOShipment(db, testdatagen.Assertions{
Nit: missing is missing an s.

2021-10-02 00:56 UTC, YanZ777 commented on src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.jsx
> +            [styles.missing]: showOriginalWeightHighlight,
Could we rename the style from missing to something else since it's technically being use for stuff that isn't missing, but still needs that style?

2021-10-02 00:56 UTC, YanZ777 commented on src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.test.jsx
> +      expect(screen.getByTestId('originalWeightContainer')).not.toHaveClass('missing');
Please use `queryBy...` instead of `getBy...` for all the things that check for non existence.

2021-10-02 00:56 UTC, YanZ777 commented on src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.test.jsx
> +  it('renders no yellow highlight for original and reweigh weights if weights do not exceeds 110% estimated weight', async () => {
Could you wrap this all in a describe since these tests are related?

2021-10-02 00:56 UTC, YanZ777 commented on src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.test.jsx
> +      expect(screen.getByTestId('reweighWeightContainer')).not.toHaveClass('missing');
Don't put multiple expects inside of an await waitFor. Typically only the first one needs to go in,  the rest can be out,

2021-10-02 00:56 UTC, YanZ777 commented on src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.test.jsx
> +    await waitFor(() => {
You probably don't need an `await waitFor()` for most of these. You can use `await screen.findBy...` instead.
Similarly to my below comment about `await waitFor()`, you don't need to put `await screen.findBy...` on everything, just the first one after a user interaction / blur. (And sometimes you don't need to even then.)

2021-10-04 21:53 UTC, donaldthai commented on src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.test.jsx
> +    await waitFor(() => {
yea, I ended up removing them. Guess there was something wrong with my machine because the tests were failing without the async waitFor() call. Now they're not failing after removing them 🤣

2021-10-04 21:53 UTC, donaldthai commented on src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.test.jsx
> +      expect(screen.getByTestId('reweighWeightContainer')).not.toHaveClass('missing');
Ended up removing them!

2021-10-04 21:53 UTC, donaldthai commented on src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.test.jsx
> +  it('renders no yellow highlight for original and reweigh weights if weights do not exceeds 110% estimated weight', async () => {
Wrapped them in a describe with a title "warning indicator".

2021-10-04 21:53 UTC, donaldthai commented on src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.test.jsx
> +      expect(screen.getByTestId('originalWeightContainer')).not.toHaveClass('missing');
I went ahead and changed all assertions relating to checks for non-existence.

2021-10-04 21:53 UTC, donaldthai commented on src/components/Office/BillableWeight/ShipmentCard/ShipmentCard.jsx
> +            [styles.missing]: showOriginalWeightHighlight,
I renamed that classname to "warning". Let me know if that's clearer or not.

2021-10-04 22:22 UTC, YanZ777 approved these changes
Thanks for making all those changes! Looks good to me.

2021-10-05 18:47 UTC, cosburn approved these changes

2021-10-05 21:01 UTC, merged