MB-10110 display NTSR specific information shipment display cards
transcom/mymove pull request #7840
Opened 2021-12-03 16:42 UTC by mlm55

## [Jira ticket](https://dp3.atlassian.net/browse/MB-10110) for this change
## [Jira ticket](https://dp3.atlassian.net/browse/MB-10114) for this change
## [Jira ticket](https://dp3.atlassian.net/browse/MB-10104) for this change

## Summary
This PR adds an nts release specific shipment list. It also adds error/warning flags for missing information, puts the correct label on shipment cards, and disables the submit when specific fields are missing (wip).

Is there anything you would like reviewers to give additional scrutiny?
I created a new shipment list to handle ntsr shipments rather than adding a bunch of conditionals into the already existing shipment display list. Was that the right way to go?

## Setup to Run Your Code

<details>
<summary>💻 You will need to use three separate terminals to test this locally.</summary>

##### Terminal 1

Start the Storybook locally.

```sh
make storybook
```

##### Terminal 2

Start the UI locally.

```sh
make client_run
```

##### Terminal 3

Start the Go server locally.

```sh
make server_run
```

</details>

### Additional steps

1. On storybook look at http://localhost:6006/?path=/story/office-components-shipment-display--nts-release-shipment to see a shipment that has all required fields 
2.  On storybook look at http://localhost:6006/?path=/story/office-components-shipment-display--nts-release-shipment-missing-info to see a shipment that has missing fields
2. Access the office app
2. Login as a service counselor
3. Find a move that already exists in your DB
4. Use postman/or manually edit the database to create an NTS release shipment that's missing the storage facility information and shipment weight
```{
    "moveTaskOrderID": "use-a-move-id-in-your-db",
    "requestedPickupDate": "2022-12-12",
    "destinationAddress": {
    "streetAddress1": "123 Main Ave",
    "city": "Anytown",
    "state": "DE",
    "postalCode": "90210",
    "country": "USA"
  },
    "shipmentType": "HHG_OUTOF_NTS_DOMESTIC",
    "tacType": "HHG",
    "sacType": "NTS",
    "usesExternalVendor": true,
    "diversion": true,
}
```
5. Go to the move details page and check that the storage facility has an error flag and that the submit button is disabled

## Verification Steps for Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Request review from a member of a different team.
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Frontend

- [ ] User facing changes have been reviewed by design.
- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
- [ ] There are no new console errors in the browser devtools
- [ ] There are no new console errors in the test output

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide#logging)
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide/#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#zero-downtime-migrations)
- [ ] Have been communicated to #g-database
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#secure-migrations)

## Screenshots

2021-12-04 01:21 UTC, YanZ777 requested changes
My comments are mainly for polishing up the tests, but everything else looks fine to me.

2021-12-04 01:21 UTC, YanZ777 commented on src/components/Office/DefinitionLists/NTSRShipmentInfoList.test.jsx
> +  it('renders a dash and adds a warning class for non-required missing items', () => {
Can we convert this to be table driven as well?

2021-12-04 01:21 UTC, YanZ777 commented on src/components/Office/DefinitionLists/ShipmentDefinitionLists.module.scss
> +.ShipmentDefinitionLists {
Are there styles that can be reused from `/src/styles/descriptionList.module.scss` instead? Or maybe combining the two?

2021-12-07 20:22 UTC, amanda5iu reviewed
Facility info is required in addition to facility address - specifically the facility name. So facility info should be displayed in [this view](http://localhost:6006/?path=/story/office-components-shipment-display--nts-release-shipment).

There should also be 2 units (16px) of space to the left and above the `Edit` button.

![image](https://user-images.githubusercontent.com/38052749/145100240-91bfb8a6-841e-437a-bfaa-3c3cf80ccd2a.png)

**Edit:** my first comment is incorrect! Do not show facility info in the collapsed view of the card. Also, the padding should be 24px between the list and `Edit` button, not 16px.

2021-12-07 20:40 UTC, YanZ777 approved these changes
Changes look good to me!

2021-12-07 20:40 UTC, YanZ777 commented on src/components/Office/DefinitionLists/NTSRShipmentInfoList.jsx
> +// import styles from 'styles/descriptionList.module.scss';
You might have forgotten to take this out?

2021-12-08 18:22 UTC, donaldthai approved these changes
Code looks good 😃 . I left some non-blocking comments.

2021-12-08 18:22 UTC, donaldthai commented on src/components/Office/DefinitionLists/NTSRShipmentInfoList.test.jsx
> +  });
I see we're not using any `await` call for some tests. Can we just remove the `async` keyword?

2021-12-08 18:22 UTC, donaldthai commented on src/components/Office/ShipmentDisplay/ShipmentDisplay.jsx
> +          <FontAwesomeIcon className={styles.icon} icon={expandableIconClasses} onClick={handleExpandClick} />
I feel like clicking on the icon to expand the fields is a bit small. What if we set the onClick to the entire heading? Maybe @amanda5iu has more of an opinion on this?

2021-12-08 19:05 UTC, amanda5iu commented on src/components/Office/ShipmentDisplay/ShipmentDisplay.jsx
> +          <FontAwesomeIcon className={styles.icon} icon={expandableIconClasses} onClick={handleExpandClick} />
@donaldthai agreed! There were specs for this somewhere when we first developed this pattern for HHG, but I can't find them at the moment. The whole header section should be clickable. I know this isn't in scope for this PR though!

2021-12-08 19:08 UTC, amanda5iu approved these changes

2021-12-09 21:39 UTC, donaldthai commented
I approved the Happo changes since it seem like a timing issue.

2021-12-09 21:39 UTC, merged