MB-10490 duty location migration
transcom/mymove pull request #7911
Opened 2021-12-14 04:41 UTC by leia-sefkin

## [Jira ticket](https://dp3.atlassian.net/browse/MB-10490) for this change

## Summary

This migration renames the duty station table to duty location and creates a view in order to maintain backwards compatibility. See [initial slack discussion](https://ustcdp3.slack.com/archives/CSGDM3NUW/p1635794050000500) for thoughts on this as an experiment. Once we are done migrating all things duty station we should be able to safely drop the view. 

## Setup to Run Your Code

I followed the steps referenced in the [documentation around migrating the DB](https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations/#understanding-migrations).  There are commands in that article for clearing the db and running tests, as well as running the migrations.

You can also run `make server_test` and that will also run migrations and tests. 

Note that there are some migrations which also reference duty station, so those will need to be updated as part of a later PR.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#zero-downtime-migrations)
- [ ] Have been communicated to #g-database

2021-12-14 15:27 UTC, reggieriser requested changes
I left a couple of notes about a few minor issues.  However, there's a failing test that I think is legit and not transient.  If I look at the error being returned by the `FetchPaymentRequestList` call in the test, I see `column "duty_stations.name" must appear in the GROUP BY clause or be used in an aggregate function`.  Something about the view must be affecting it.

BTW, the failing test masks the error above because it first [hits a nil pointer exception before it asserts no error](https://github.com/transcom/mymove/blob/e05bf35c4b8b1bdb2d456400925a79e632a98959/pkg/services/payment_request/payment_request_list_fetcher_test.go#L609-L612) was returned.  It should probably be checking the error value first.

2021-12-14 18:23 UTC, leia-sefkin commented on migrations/app/schema/20211213235039_update-duty-station-location.up.sql
> +ALTER TABLE duty_stations RENAME TO duty_locations;
ah! i totally forgot to look at those, thanks for pointing this out, will update shortly

2021-12-14 20:13 UTC, leia-sefkin commented
@reggieriser - made the changes you suggested/pointed out. Let me know what you think and thanks for the close eye on this 🙏

2021-12-14 22:45 UTC, reggieriser reviewed
@leia-sefkin Thanks for the changes -- they look good (just added a couple nits that aren't blockers).  But I'm curious -- why did the `duty_stations` references have to change to `duty_locations` in the payment request list fetcher but not anywhere else (I see quite a few raw queries and Pop joins elsewhere that still reference `duty_stations`).  This is passing tests, but want to make sure I understand why this change was necessary but the others weren't.

Another thought I had was that we may now be violating our zero-down migrations goal in the payment request list fetcher since it could reference `duty_locations` before the view has been created by the migration.  Am I thinking about this right?  It may not be as big a deal given we don't have production users yet, but just wanted to mention.

2021-12-14 22:45 UTC, reggieriser commented on migrations/app/schema/20211213235039_update-duty-station-location.up.sql
> +ALTER TABLE duty_stations RENAME TO duty_locations;
Sorry, noticing a few more "duty station" references.  These aren't mandatory to fix here since they shouldn't break anything, but just thought I'd mention them while I noticed:
- several tables have columns named `duty_station_id` (or something close to that): `service_members`, `duty_station_names`, `orders` (this could be a lot of changes if you carry it through to the model)
- comments on `duty_locations` and a few other places still mention `duty station`

2021-12-14 22:45 UTC, reggieriser commented on pkg/services/payment_request/payment_request_list_fetcher_test.go
> +		paymentRequests := *expectedPaymentRequests
Thanks for moving this around!

2021-12-14 22:50 UTC, leia-sefkin commented on migrations/app/migrations_manifest.txt
> +20211213235039_update-duty-station-location.up.sql
good call i will update that!

2021-12-14 22:53 UTC, leia-sefkin commented on migrations/app/schema/20211213235039_update-duty-station-location.up.sql
> +ALTER TABLE duty_stations RENAME TO duty_locations;
@reggieriser thanks! i'm aware of those other tables and columns yet to be migrated, i was just trying to parse out the PRs so they were a bit more manageable. i'm attempting also to make app reference changes in parallel but separate, but you see there was some weirdness with the payment request fetcher test...

2021-12-14 22:55 UTC, leia-sefkin commented
> @leia-sefkin Thanks for the changes -- they look good (just added a couple nits that aren't blockers). But I'm curious -- why did the `duty_stations` references have to change to `duty_locations` in the payment request list fetcher but not anywhere else (I see quite a few raw queries and Pop joins elsewhere that still reference `duty_stations`). This is passing tests, but want to make sure I understand why this change was necessary but the others weren't.
> 
> Another thought I had was that we may now be violating our zero-down migrations goal in the payment request list fetcher since it could reference `duty_locations` before the view has been created by the migration. Am I thinking about this right? It may not be as big a deal given we don't have production users yet, but just wanted to mention.

@reggieriser good question - i was wondering the same Q about the payment request list fetcher but didn't dig into it too much. maybe it's something to do with the way the test is structured? i'll see if i can figure it out. my goal was to try and keep the code and DB migrations separate per your comment, so it would be ideal if feasible to ensure that.

2021-12-15 02:21 UTC, leia-sefkin commented on pkg/services/payment_request/payment_request_list_fetcher_test.go
> +		paymentRequests := *expectedPaymentRequests
looks like there's plenty of other places this could be fixed/refactored...but trying to stay somewhat focused 😅

2021-12-15 02:59 UTC, leia-sefkin commented
@reggieriser this should be ready for a final re-review 🎉 more exciting changes to duty_location to come. thanks for the assist 💪

2021-12-15 16:26 UTC, reggieriser approved these changes
LGTM! 🎉  Thanks for making all the changes.  I added a couple of nits (sorry, I keep noticing something nit-picky each time I re-review!), but certainly not something you have to fix before merging.  No need for me to re-review if you do happen to adjust.

2021-12-15 16:26 UTC, reggieriser commented on pkg/services/payment_request/payment_request_list_fetcher.go
> +	err := query.GroupBy("payment_requests.id, service_members.id, moves.id, duty_stations.id, duty_stations.name").Paginate(int(*params.Page), int(*params.PerPage)).All(&paymentRequests)
Glad this is working!  I'm not exactly sure why we have to do it, but I think it should end up with the same results because we're already grouping by `duty_stations.id`.  Adding `duty_stations.name` shouldn't change anything since it's already unique via `duty_stations.id`.

2021-12-15 19:43 UTC, leia-sefkin commented on pkg/services/payment_request/payment_request_list_fetcher.go
> +	err := query.GroupBy("payment_requests.id, service_members.id, moves.id, duty_stations.id, duty_stations.name").Paginate(int(*params.Page), int(*params.PerPage)).All(&paymentRequests)
> LGTM! 🎉 Thanks for making all the changes. I added a couple of nits (sorry, I keep noticing something nit-picky each time I re-review!), but certainly not something you have to fix before merging. No need for me to re-review if you do happen to adjust.

Thank YOU for being so detail oriented!! I'm still learning my way around here so it's very helpful. Agree with your nits, but I'll leave these last ones in for now since I'll be migrating duty_stations_name shortly :)

2021-12-15 19:43 UTC, merged