[MB-10434] Add EditFacilityInfoModal to Storybook
transcom/mymove pull request #8012
Opened 2022-01-10 20:02 UTC by hannaliebl

## [Jira ticket](https://dp3.atlassian.net/browse/MB-10434) for this change

## Summary

Adds EditFacilityInfoModal to Storybook.

My main question is if the shape of the props seems correct. I suppose it could also be modified in implementation, too. I tried to use existing types where I could, but there is maybe space for optimization there. I also added some facility-specific types to the shipments file, but I could see an argument for adding a separate file for them.

## Setup to Run Your Code

<details>

##### Terminal 1

Start the Storybook locally.

```sh
make storybook
```
</details>

### Additional steps

1. View the EditFacilityInfoModal in Storybook

## Verification Steps for Author

These are to be checked by the author.

- [X] Request review from a member of a different team.
- [X] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Frontend

- [ ] User facing changes have been reviewed by design.
- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
- [ ] There are no new console errors in the browser devtools
- [ ] There are no new console errors in the test output
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

## Screenshots
![Screen Shot 2022-01-10 at 3 00 00 PM](https://user-images.githubusercontent.com/3903208/148831135-db748236-fff2-45c6-8c40-fe5e0980a8ba.png)

2022-01-11 01:44 UTC, YanZ777 requested changes
Just a few comments from my scan through of the code.
Also, yay, thanks for adding more shapes.

2022-01-11 01:44 UTC, YanZ777 commented on src/components/Office/EditFacilityInfoModal/EditFacilityInfoModal.jsx
> +import { StorageFacilityAddressShape, StorageFacilityShape, ShipmentOptionsOneOf } from '../../../types/shipment';
Can we change this from a relative path to absolute? 
I think you should just be able to take off the `../../../`.

2022-01-11 01:44 UTC, YanZ777 commented on src/components/Office/EditFacilityInfoModal/EditFacilityInfoModal.jsx
> +  const editFacilityInfoSchema = Yup.object().shape({
It looks like there is an existing schema you can use at `src/components/Customer/MtoShipmentForm/validationSchemas.js`

2022-01-11 01:44 UTC, YanZ777 commented on src/components/Office/EditFacilityInfoModal/EditFacilityInfoModal.module.scss
> +  min-width: 40rem !important;
What issue were you having that needed the `!important`? 
It could be perfectly valid, but I would prefer to avoid !important if we can help it. If it is needed, I think leaving a comment in would be helpful as well.

2022-01-11 20:45 UTC, hannaliebl commented on src/components/Office/EditFacilityInfoModal/EditFacilityInfoModal.jsx
> +  const editFacilityInfoSchema = Yup.object().shape({
That one doesn't include the service order number.

2022-01-11 20:51 UTC, hannaliebl commented on src/components/Office/EditFacilityInfoModal/EditFacilityInfoModal.module.scss
> +  min-width: 40rem !important;
It's overriding the modal's min-width, which is set in the Modal CSS module with extra specificity because it uses a div selector. Hmmm, I could also use a div selector to beat that rule, though.

2022-01-12 01:12 UTC, YanZ777 requested changes

2022-01-12 15:28 UTC, hannaliebl commented on src/components/Office/EditFacilityInfoModal/EditFacilityInfoModal.jsx
> +  const editFacilityInfoSchema = Yup.object().shape({
I'm doing it based on the form fields themselves (the service order number is part of the facility info fields in the modal UI), but from a data perspective, maybe? I can just use the existing schema if that's easier.

2022-01-12 15:51 UTC, hannaliebl commented on src/components/Office/EditFacilityInfoModal/EditFacilityInfoModal.module.scss
> +  min-width: 40rem;
The zepelin mocks are wider than the default modal, but maybe that's ok. In the other modal I did a few weeks ago, I did update the min width. Maybe this is a question for @amanda5iu

2022-01-12 15:54 UTC, hannaliebl commented on src/components/Office/EditFacilityInfoModal/EditFacilityInfoModal.module.scss
> +  min-width: 40rem;
Actually maybe based on this https://github.com/transcom/mymove/pull/7822 it's better to remove it, and when it's implemented it can be added if needed.

2022-01-12 16:38 UTC, amanda5iu reviewed
Looking good so far! Can we add 16px space between the NTS tag and h1? And there should be 32px above each h2, right now it looks like 48px.

![Screen Shot 2022-01-12 at 10 34 26 AM](https://user-images.githubusercontent.com/38052749/149182703-2531d1a0-8d33-43fc-b369-85134ca28c3c.png)

![Screen Shot 2022-01-12 at 10 34 17 AM](https://user-images.githubusercontent.com/38052749/149182706-b3798caa-f048-43cd-a8b8-7abaadff8c81.png)

2022-01-12 17:58 UTC, YanZ777 commented on src/components/Office/EditFacilityInfoModal/EditFacilityInfoModal.jsx
> +      <ModalContainer>
I think that should be fine. I think that section needs to be cleaned up. @kylehilltruss might know more about it.

2022-01-12 18:05 UTC, hannaliebl commented
@amanda5iu thanks, I adjusted the margins.

2022-01-12 21:42 UTC, YanZ777 commented on src/components/Office/EditFacilityInfoModal/EditFacilityInfoModal.jsx
> +  const editFacilityInfoSchema = Yup.object().shape({
I would make it align with how the data is, but I'd want someone else to weigh on this.

2022-01-12 21:45 UTC, YanZ777 approved these changes
Thanks for making all the changes. They look fine to me. 
It'd be good to get someone else's input on how the schema should look, but I'm not going to block on that.

2022-01-13 13:58 UTC, amanda5iu approved these changes
Thanks for making the changes!

2022-01-13 17:36 UTC, merged