[MB-10435] Storage facility edit modal implementation
transcom/mymove pull request #8038
Opened 2022-01-18 16:53 UTC by hannaliebl

## [Jira ticket](https://dp3.atlassian.net/browse/MB-10435) for this change

## Summary

I'm opening this early/as a draft for now because my availability is a bit up in the air this week, so if I get feedback earlier and have some free time later, hopefully this can get done sooner.

My main question is about the updating of the info on save - is there something wrong with the way I'm invalidating the react query cache? I don't always see my changes on modal close (if I change the facility name, for example.) They exist in the DB/on page reload, though.

I will add tests soon here, and correct the CSS a bit (to remove the right padding on the button.)

## Setup to Run Your Code

<details>
<summary>💻 You will need to use two separate terminals to test this locally.</summary>

##### Terminal 1

Start the UI locally.

```sh
make client_run
```

##### Terminal 2

Start the Go server locally.

```sh
make server_run
```

</details>

### Additional steps

1. Login into the office app as a TOO
2. Use the `NTSSUB` move code and approve the shipments, but first edit the NTS-R/NTS shipments to include storage facility info and addresses
3. On the MTO page, now you should see the facility info/address with the edit link on the shipment summaries. Clicking edit should open the edit modal.
4. Edit the storage facility info and hit save, confirm that the info has been successfully updated.

## Verification Steps for Author

These are to be checked by the author.

- [ ] Request review from a member of a different team.
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Frontend

- [ ] User facing changes have been reviewed by design.
- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
- [ ] There are no new console errors in the browser devtools
- [ ] There are no new console errors in the test output
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

2022-01-18 21:55 UTC, jacquelineIO reviewed
Looks good to me. I'd prefer to get an approval from someone with more React experience as you were asking if everything looks right. But the code review looked good and I was able to run it locally.

2022-01-18 21:58 UTC, rogeruiz approved these changes
lgtm 🌈

paired with @hannaliebl and ran this code locally. Tested it with Move Code, `HGNTSR` to see the Edit links.

2022-01-19 01:14 UTC, YanZ777 requested changes
The modal appears chopped off at the top for me. I think importing the ConnectedModal and using the isOpen should fix it though.

![image](https://user-images.githubusercontent.com/6477059/150045013-9598a066-9e30-41f2-a281-3b4b4f6029b2.png)

2022-01-19 01:14 UTC, YanZ777 commented on src/components/Office/EditFacilityInfoModal/EditFacilityInfoModal.jsx
> +      <ModalContainer>
You shouldn't need this wrapping.

2022-01-19 01:14 UTC, YanZ777 commented on src/components/Office/EditFacilityInfoModal/EditFacilityInfoModal.jsx
> +          <ModalClose handleClick={() => onClose()} />
I think you might just be able to use `handleClick={onClose}`

2022-01-19 01:14 UTC, YanZ777 commented on src/components/Office/ShipmentDetails/ShipmentDetailsSidebar.jsx
> +import { EditFacilityInfoModal } from 'components/Office/EditFacilityInfoModal/EditFacilityInfoModal';
Use this import instead: import `ConnectedEditFacilityInfoModal` from ....etc.

2022-01-19 01:14 UTC, YanZ777 commented on src/components/Office/ShipmentDetails/ShipmentDetailsSidebar.jsx
> +      {isEditFacilityInfoModalVisible && (
Rather than using this to toggle if the modal is visible or not, use the prop `isOpen` and pass `isEditFacilityInfoModalVisible` to that prop.

2022-01-19 13:03 UTC, hannaliebl commented on src/components/Office/ShipmentDetails/ShipmentDetailsSidebar.jsx
> +      {isEditFacilityInfoModalVisible && (
Ahh, thanks, that is what I was missing from all of this.

2022-01-19 13:07 UTC, hannaliebl commented
@YanZ777 thanks for pointing it out, I hadn't realized the onClose prop was needed, but I added that all back in and it did fix the overlay stuff.

2022-01-19 18:50 UTC, amanda5iu reviewed
The Edit link is styled differently from the rest of the sidebar. It should look the same as the link for service order number and accounting codes.

![Screen Shot 2022-01-19 at 12 44 04 PM](https://user-images.githubusercontent.com/38052749/150194566-5442794a-0003-440b-87ac-8427744b8b9c.png)

The modal is showing up really narrow for some reason. It isn't this narrow in [Storybook](https://storybook.dp3.us/?path=/story/office-components-editfacilityinfomodal--basic).

![Screen Shot 2022-01-19 at 12 43 05 PM](https://user-images.githubusercontent.com/38052749/150194698-fae8e8f4-cd7a-4135-8364-9c4401a35a67.png)

When I edit something in the modal then hit Save, the sidebar doesn't update until I refresh the page. Is this supposed to happen?

2022-01-19 19:44 UTC, hannaliebl commented
@amanda5iu hmm, I fixed the link size/padding a few commits ago, were you looking locally or on staging? I did just fix the modal width. I think sometimes there are overrides in the app that don't exist in Storybook, maybe.

2022-01-19 20:54 UTC, YanZ777 approved these changes
Coding wise, these changes look good to me. Thanks for making those edits.

2022-01-25 16:55 UTC, amanda5iu commented
@hannaliebl the link spacing and styling appears to be fixed now! The modal now saves changes to facility info and address on Save instead of reload as well. I've been reviewing on local.

One new weird thing: the sidebar shows for NTS-release, but not for NTS. The facility address doesn't show up in the addresses field either. I made sure to add facility info to the NTS before posting the MTO. 

<img width="982" alt="Screen Shot 2022-01-25 at 10 54 17 AM" src="https://user-images.githubusercontent.com/38052749/151022511-8fe0f78f-2a90-4d6e-a93b-cff5ed20fb00.png">

2022-01-25 21:03 UTC, hannaliebl commented
@amanda5iu hmmm, I just merged master in and don't see that. I don't recall that happening before, but it's been a bit at this point. I did end up changing one more thing in the code to mimic what I'm doing in this PR (https://github.com/transcom/mymove/pull/8082) to remove the eTag from the storage facility address, which I guess I wasn't doing in all cases here.

2022-01-26 20:56 UTC, amanda5iu approved these changes
Got the missing info to show up. Everything looks good!

2022-01-27 22:15 UTC, rogeruiz commented
argh. looks like there's a new DangerJS error happening here. @transcom/truss-a-team I think is on dependencies right now.

> Yarn Audit Issues Found: high - Cross site scripting in three.js Package three Patched in >=0.137.0 Dependency of @trussworks/react-file-viewer Path @trussworks/react-file-viewer > three More info https://github.com/advisories/GHSA-7vvq-7r29-5vg3
1 high vulnerabilities and 0 critical vulnerabilities found

2022-01-27 22:45 UTC, duncan-truss commented
> argh. looks like there's a new DangerJS error happening here. @transcom/truss-a-team I think is on dependencies right now.
> 
> > Yarn Audit Issues Found: high - Cross site scripting in three.js Package three Patched in >=0.137.0 Dependency of @trussworks/react-file-viewer Path @trussworks/react-file-viewer > three More info [GHSA-7vvq-7r29-5vg3](https://github.com/advisories/GHSA-7vvq-7r29-5vg3)
> > 1 high vulnerabilities and 0 critical vulnerabilities found
> 
> Interesting enough, this vulnerability seems like a nothing burger according to this comment. [mrdoob/three.js#23245 (comment)](https://github.com/mrdoob/three.js/pull/23245#issuecomment-1023561044)

Master should now have the fix.

2022-01-28 15:11 UTC, merged