MB-10675 Add EstimatedWeightsProGear page
transcom/mymove pull request #8216
Opened 2022-02-26 00:10 UTC by felipe-lee

## [Jira ticket](https://dp3.atlassian.net/browse/MB-10675) for this change

## Summary

This PR adds the Estimated Weights and Pro Gear page, implementing the previously created `EstimatedWeightsProGearForm` component.

This is still a WIP. Things left to do:
- [ ] Add tests for the page.
- [ ] Wire up the page in the routing. 
- [ ] Fix any missing bits with the submission. Wrote it without testing it (either automated or manually), so it may not work as is at all 🤷🏼 
- [ ] Add/edit CSS as needed.

Possible things that I may or may not do, depending on time and requirements:
- [ ] Set up more comprehensive routing for PPMs. E.g. if a customer starts a PPM shipment, but then leaves before going through the full workflow, we probably want to put them back where they were if they try to go back into the PPM. This is lower priority though because without specific handling for this, they should still be able to get back to where they were, just going through each page again.

## Setup to Run Your Code

<details>
<summary>💻 Setup </summary>

### Populate DB

You can skip this if you've already generated data with a customer that can add shipments, or if you want to do it from scratch.

```sh
make db_dev_fresh
```

### Server

Start the server

```sh
make server_run
```

### Client

Start the UI locally.

```sh
make client_run
```

</details>

### Additional steps

1. Go to the [local client page](http://milmovelocal:3000/)

2 A. Login as a client that has gotten through at least submitting orders, but has yet to submit the move.
2 B. Create a customer and get through the orders submission step.

3. Click to add a shipment.
4. Select PPM.
5. Enter date, postal codes, and SIT info. 
6. Click "Save & Continue"
7. Now you should see the new estimated weight and pro gear page. Test it out as you see fit.
8. Clicking "Save & Continue" won't fully work at the moment because the next page is coming in a separate PR and the BE work to get the updates for PPMs in is in #8185. 

## Verification Steps for Author

These are to be checked by the author.

- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Frontend

- [ ] User facing changes have been reviewed by design.
- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
- [ ] There are no new console errors in the browser devtools
- [ ] There are no new console errors in the test output

## Screenshots

Coming soon to a theater near you...but really, I'll add them once I get farther along.

2022-03-02 19:51 UTC, pearl-truss commented on src/components/Customer/PPMBooking/EstimatedWeightsProGearForm/EstimatedWeightsProGearForm.jsx
> +    estimatedWeight: mtoShipment.ppmShipment.estimatedWeight?.toString() || '',
For consistency can the `DateAndLocationForm` be updated to have the same changes for dropping the non required optional chaining?

2022-03-02 19:51 UTC, pearl-truss commented on src/pages/MyMove/PPMBooking/EstimatedWeightsProGear/EstimatedWeightsProGear.jsx
> +    patchMTOShipment(mtoShipment.id, payload, mtoShipment.eTag)
When I press submit I get a 412 error in the console, is that expected at this point?

2022-03-02 19:53 UTC, pearl-truss commented
@felipe-lee A heads up, I think ephemeral deploy link in the description is out of date https://my-milmove-pr-8214.mymove.sandbox.truss.coffee/. I wasn't able to progress to the estimated pro gear page from the dates and location page and the `estimated_weights@ppm.unsubmitted` user was missing. (None of this was an issue when I pulled up the PR locally)

2022-03-02 19:53 UTC, felipe-lee commented on src/components/Customer/PPMBooking/EstimatedWeightsProGearForm/EstimatedWeightsProGearForm.jsx
> +    estimatedWeight: mtoShipment.ppmShipment.estimatedWeight?.toString() || '',
I think the `DateAndLocationForm` needs to keep the optional chaining because in that one, we may not have a shipment yet if it's the first time through, whereas in this one, a shipment should already exist by the time people get here.

2022-03-02 19:54 UTC, felipe-lee commented on src/pages/MyMove/PPMBooking/EstimatedWeightsProGear/EstimatedWeightsProGear.jsx
> +    patchMTOShipment(mtoShipment.id, payload, mtoShipment.eTag)
Yeah, the backend work in #8185 will get this working. Though I do need to look at the PR to make sure I'm passing the expected eTag because we'd talked about a few different options.

2022-03-02 19:55 UTC, felipe-lee commented
> @felipe-lee A heads up, I think ephemeral deploy link in the description is out of date https://my-milmove-pr-8214.mymove.sandbox.truss.coffee/. I wasn't able to progress to the estimated pro gear page from the dates and location page and the `estimated_weights@ppm.unsubmitted` user was missing. (None of this was an issue when I pulled up the PR locally)

Weird, thanks for the heads up, I'll try redeploying it.

2022-03-02 19:57 UTC, felipe-lee commented
> > @felipe-lee A heads up, I think ephemeral deploy link in the description is out of date https://my-milmove-pr-8214.mymove.sandbox.truss.coffee/. I wasn't able to progress to the estimated pro gear page from the dates and location page and the `estimated_weights@ppm.unsubmitted` user was missing. (None of this was an issue when I pulled up the PR locally)
> 
> Weird, thanks for the heads up, I'll try redeploying it.

🤦🏼 I deployed the wrong PR, that's why haha. I'll update the link, though it will be 20-30min before it works

2022-03-02 20:04 UTC, ronaktruss commented on pkg/testdatagen/shared.go
> +}
As a general question is there a reason that we don't have some sort of shared "utils" file for many of these conversions / or does this already exist? For example this BoolPointer helper exists in models

2022-03-02 20:11 UTC, felipe-lee commented on pkg/testdatagen/shared.go
> +}
In general, it's probably a combo of not wanting cyclical imports and people not realizing or forgetting the other one existed. In this case I forgot about the model ones...so I can update this haha.

2022-03-02 20:14 UTC, pearl-truss commented on src/components/Customer/PPMBooking/EstimatedWeightsProGearForm/EstimatedWeightsProGearForm.jsx
> +    estimatedWeight: mtoShipment.ppmShipment.estimatedWeight?.toString() || '',
Got it, that makes sense

2022-03-02 20:15 UTC, pearl-truss approved these changes
LGTM

2022-03-03 14:38 UTC, duncan-truss commented on src/pages/MyMove/PPMBooking/EstimatedWeightsProGear/EstimatedWeightsProGear.jsx
> +  const mtoShipment = useSelector((state) => selectMTOShipmentById(state, mtoShipmentId));
Nice, you were able to get ride of mapStateToProps I noticed.  I meant to ask if there was some limitation with ownProps that I thought I read about that didn't translate perfectly to useSelector.

2022-03-03 14:41 UTC, duncan-truss commented on src/pages/MyMove/PPMBooking/EstimatedWeightsProGear/EstimatedWeightsProGear.test.jsx
> +      render(<EstimatedWeightsProGear />, { wrapper: MockProviders });
I forgot about this wrapper option

2022-03-03 15:54 UTC, duncan-truss requested changes

2022-03-03 15:54 UTC, duncan-truss commented on src/pages/MyMove/PPMBooking/EstimatedWeightsProGear/EstimatedWeightsProGear.jsx
> +    history.goBack();
Oh I thought of something, we shouldn't take the user back to the date and location page because the shipment has now been created.  We want to take them back to the edit version of the date and location page where we load the existing shipment instead of the new url.

2022-03-03 18:14 UTC, felipe-lee commented on src/pages/MyMove/PPMBooking/EstimatedWeightsProGear/EstimatedWeightsProGear.jsx
> +  const mtoShipment = useSelector((state) => selectMTOShipmentById(state, mtoShipmentId));
The ownProps was actually failing but then I saw you used this selector in your PR and switched to it haha.

2022-03-03 18:15 UTC, felipe-lee commented on src/pages/MyMove/PPMBooking/EstimatedWeightsProGear/EstimatedWeightsProGear.jsx
> +    history.goBack();
Ah, good point, I can update this.

2022-03-03 19:55 UTC, duncan-truss commented on src/pages/MyMove/PPMBooking/EstimatedWeightsProGear/EstimatedWeightsProGear.jsx
> +    history.goBack();
This probably requires more work to add in redux loading of the shipment and adding the standalone edit route because it was previously always being rendered by the CreateOrEditMtoShipment component.

2022-03-03 20:52 UTC, felipe-lee commented on pkg/testdatagen/shared.go
> +}
Done!

2022-03-03 20:54 UTC, felipe-lee commented on src/pages/MyMove/PPMBooking/EstimatedWeightsProGear/EstimatedWeightsProGear.jsx
> +    history.goBack();
I think that component already handles loading customer data on mount and the path would lead to the same component as before no? Unless I'm misunderstanding

2022-03-03 21:08 UTC, duncan-truss commented on src/pages/MyMove/PPMBooking/EstimatedWeightsProGear/EstimatedWeightsProGear.jsx
> +    history.goBack();
I think you're right that should be working properly my mistake.

2022-03-04 00:13 UTC, scarequotes requested changes
FYI: When I clicked the PPM shipment on the home screen, I landed on the PPM Date and Location page, but scrolled halfway down. That's not right — I should be at the top of the page — but I don't know if that's just my browser or something else. (Or unrelated to this ticket.)

Actually, that also happens when I go from Dates & Locations to the Estimated weight page. Should align to the top of the window. 

Background blue color on the infobox doesn't match Zeplin — Zeplin says it should be #ecf1f7 but site is #E7F6F8 — may be wrong variable? 

Found an odd validation error: 
- entered 4,288 lbs
- clicked outside field
- clicked back inside field and put my cursor in front of the 4
- added a 1 to make 14,288 lbs
- got this validation error: 
estimatedWeight must be a `number` type, but the final value was: `NaN` (cast from the value `"14,288"`).
![Screen Shot 2022-03-03 at 4 02 33 PM](https://user-images.githubusercontent.com/30428256/156673814-49ae882f-70bf-4d65-9099-e90a7ecd85c2.png)

When the estimated weight caution message appears, the yellow line on the left extends up beyond the field label — the top of that line should be even with the label.
![Screen Shot 2022-03-03 at 4 04 56 PM](https://user-images.githubusercontent.com/30428256/156673927-cfeb3662-d201-42dc-8029-25f1985ad70e.png)

In the pro-gear weight fields, when the user enters more than the maximum weight, the validation error appears along with the red highlight line, but the field and field label also move down the page. The field label should stay at the same height, with the message appearing below and pushing down the field itself.

![Screen Shot 2022-03-03 at 4 07 52 PM](https://user-images.githubusercontent.com/30428256/156674177-fddeb6e2-3eda-4a59-809b-19d482303b3d.png)
![Screen Shot 2022-03-03 at 4 07 36 PM](https://user-images.githubusercontent.com/30428256/156674178-e1c11d80-ef78-4bfa-8348-d7dd2c96c18b.png)

In the mobile view, the text in the PPM flag looks like it's not centered top to bottom — top space looks too small.
![Screen Shot 2022-03-03 at 4 12 02 PM](https://user-images.githubusercontent.com/30428256/156674565-bbdb2be3-b8d5-4ea5-b8c7-b838e2c2dd10.png)

2022-03-04 14:58 UTC, duncan-truss commented on src/components/Customer/PPMBooking/EstimatedWeightsProGearForm/EstimatedWeightsProGearForm.jsx
> +    estimatedWeight: mtoShipment.ppmShipment.estimatedWeight?.toString() || '',
If you hard refresh the page though, it will throw undefined errors if we don't keep the optional chaining until the shipment eventually resolves to not null from Redux.

2022-03-04 22:40 UTC, felipe-lee commented on src/components/Customer/PPMBooking/EstimatedWeightsProGearForm/EstimatedWeightsProGearForm.jsx
> +    estimatedWeight: mtoShipment.ppmShipment.estimatedWeight?.toString() || '',
Ah, I was wondering what that was from. Thanks for the info, I'll add the optional chaining back then.

2022-03-08 00:22 UTC, felipe-lee commented
@scarequotes Here's an update on a few things (I've asked deploybot to re-deploy, but that won't be ready for another 20-30min probably):

> FYI: When I clicked the PPM shipment on the home screen, I landed on the PPM Date and Location page, but scrolled halfway down. That's not right — I should be at the top of the page — but I don't know if that's just my browser or something else. (Or unrelated to this ticket.)
> 
> Actually, that also happens when I go from Dates & Locations to the Estimated weight page. Should align to the top of the window.

This has been a thing for a while. I can't find a bug ticket for it, but [I'm asking if others know of one](https://ustcdp3.slack.com/archives/CTQQJD3G8/p1646683779341489). If not, I can create one, but I'd rather that be separate work since it's a preexisting thing.
 
> Background blue color on the infobox doesn't match Zeplin — Zeplin says it should be #ecf1f7 but site is #E7F6F8 — may be wrong variable?

#e7f6f8 seems to be the color we have for the info alert component from before (I just re-used the component): https://storybook.dp3.us/?path=/story/components-alerts--info

Should that be changed to match zeplin then?

> Found an odd validation error:
> 
>     * entered 4,288 lbs
> 
>     * clicked outside field
> 
>     * clicked back inside field and put my cursor in front of the 4
> 
>     * added a 1 to make 14,288 lbs
> 
>     * got this validation error:
>       estimatedWeight must be a `number` type, but the final value was: `NaN` (cast from the value `"14,288"`).
>       ![Screen Shot 2022-03-03 at 4 02 33 PM](https://user-images.githubusercontent.com/30428256/156673814-49ae882f-70bf-4d65-9099-e90a7ecd85c2.png)

This has been fixed! Hopefully 😅 

> When the estimated weight caution message appears, the yellow line on the left extends up beyond the field label — the top of that line should be even with the label. ![Screen Shot 2022-03-03 at 4 04 56 PM](https://user-images.githubusercontent.com/30428256/156673927-cfeb3662-d201-42dc-8029-25f1985ad70e.png)
> 
> In the pro-gear weight fields, when the user enters more than the maximum weight, the validation error appears along with the red highlight line, but the field and field label also move down the page. The field label should stay at the same height, with the message appearing below and pushing down the field itself.
> 
> ![Screen Shot 2022-03-03 at 4 07 52 PM](https://user-images.githubusercontent.com/30428256/156674177-fddeb6e2-3eda-4a59-809b-19d482303b3d.png) ![Screen Shot 2022-03-03 at 4 07 36 PM](https://user-images.githubusercontent.com/30428256/156674178-e1c11d80-ef78-4bfa-8348-d7dd2c96c18b.png)

This should hopefully look better now.

> In the mobile view, the text in the PPM flag looks like it's not centered top to bottom — top space looks too small. ![Screen Shot 2022-03-03 at 4 12 02 PM](https://user-images.githubusercontent.com/30428256/156674565-bbdb2be3-b8d5-4ea5-b8c7-b838e2c2dd10.png)

So it looks like in FireFox this is centered, but when I switch to Chrome, I see what you're seeing. This is more an issue with our shipment tag component in general probably: https://storybook.dp3.us/?path=/docs/components-shipment-tag--ppm
Are you ok if I create a separate ticket for that fix? Also, which browser were you using (so I can add that info).

2022-03-08 14:48 UTC, duncan-truss commented on src/pages/MyMove/PPMBooking/DateAndLocation/DateAndLocation.jsx
> +  const dispatch = useDispatch();
Thanks for connecting these, I triggered the dispatch in the devtools to test things but should have included them eventhough the api wasn't implemented yet.

2022-03-08 15:59 UTC, pearl-truss commented on pkg/testdatagen/scenario/subscenarios.go
> +		createUnsubmittedMoveWithPPMShipmentThroughEstimatedWeights(appCtx, userUploader)
@felipe-lee The cypress populates with `e2e_basic` so I'm seeing the 401 unauthorized error when I tried using the user generated from the function above. I have a workaround that uses a user generated in `e2e_basic` but wanted to call it out in case there was a strong feeling that the cypress test should use the users generated here

2022-03-08 19:36 UTC, felipe-lee commented on pkg/testdatagen/scenario/subscenarios.go
> +		createUnsubmittedMoveWithPPMShipmentThroughEstimatedWeights(appCtx, userUploader)
I'm thinking this PR should have the data generation for devseed, but this function can be re-used across both I think. So maybe once this merges, you can start calling this function in the e2ebasic file so that you have access to the generated user from cypress too.

2022-03-08 19:43 UTC, felipe-lee commented on src/pages/MyMove/PPMBooking/DateAndLocation/DateAndLocation.jsx
> +  const dispatch = useDispatch();
No problem, it helped teach me things haha. I was confused why the info in the store seemed to have an old eTag every time, then I realized that the old way of using `mapDispatchToProps` handled taking the actions and wrapping them in dispatch (or something like that, I didn't go to deep into that), and learned about this hook to replace that.

2022-03-11 16:11 UTC, scarequotes approved these changes
LGTM (nice work with a lot of weird issues)

2022-03-11 17:31 UTC, merged

2022-03-11 20:12 UTC, felipe-lee commented
Created a ticket for the scrolling issue: https://dp3.atlassian.net/browse/MB-11956