[MB-10957] read from new duty location columns
transcom/mymove pull request #8242
Opened 2022-03-04 23:23 UTC by mboren

## [Jira ticket](tbd) for this change

## Summary
Posting this because I'm having trouble figuring out why tests are broken.
I've tried following the tests in a debugger and connecting to the test database, and I'm missing where things are going wrong.
It seems like the test data is set up correctly, but when the Orders get saved to the database, the `origin_duty_location_id` field is not present.

I got similar errors from tests when I tried to switch over `ServiceMember` to the new fields.

Everything was going swimmingly up until this commit: [34a8e8c95cd82017ddfe34e2cf48ecc9a5f5ab4b](https://github.com/transcom/mymove/commit/34a8e8c95cd82017ddfe34e2cf48ecc9a5f5ab4b)

## Setup to Run Your Code

<details>
<summary>💻 You will need to use three separate terminals to test this locally.</summary>

##### Terminal 1

Start the Storybook locally.

```sh
make storybook
```

##### Terminal 2

Start the UI locally.

```sh
make client_run
```

##### Terminal 3

Start the Go server locally.

```sh
make server_run
```

</details>

### Additional steps

1. Access the
2. Login as a
3.

## Verification Steps for Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Request review from a member of a different team.
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Frontend

- [ ] User facing changes have been reviewed by design.
- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
- [ ] There are no new console errors in the browser devtools
- [ ] There are no new console errors in the test output
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide#logging)
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide/#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#zero-downtime-migrations)
- [ ] Have been communicated to #g-database
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#secure-migrations)

## Screenshots

2022-03-08 20:52 UTC, mboren commented on pkg/services/duty_stations/load_duty_stations.go
>  	{{end}}`
This entire file is not really used anymore, and i would be shocked if it worked. I updated it because i wanted to remove all references to `duty_stations`, but i'm not committing to making sure that it runs.

2022-03-10 19:18 UTC, mboren commented on pkg/models/service_member.go
> +	DutyLocation           DutyLocation              `belongs_to:"duty_locations" fk_id:"duty_station_id"`
updating `fk_id` and all the other tags for these fields will come in the next PR.

2022-03-10 19:32 UTC, mboren commented on migrations/app/schema/20220308211442_update_origin_duty_location_to_gbloc_view.up.sql
> +         JOIN postal_code_to_gblocs pctg ON a.postal_code::text = pctg.postal_code::text;
here's the original definition for this view, to compare with:
```
marty@martys-MacBook-Pro-2 mymove % psql-dev
psql (12.7)
Type "help" for help.

dev_db=# \sv origin_duty_location_to_gbloc
CREATE OR REPLACE VIEW public.origin_duty_location_to_gbloc AS
 SELECT pctg.id,
    m.id AS move_id,
    pctg.gbloc
   FROM moves m
     JOIN orders ord ON ord.id = m.orders_id
     JOIN duty_stations ds ON ds.id = ord.origin_duty_station_id
     JOIN addresses a ON a.id = ds.address_id
     JOIN postal_code_to_gblocs pctg ON a.postal_code::text = pctg.postal_code::text
```

2022-03-10 22:50 UTC, leia-sefkin requested changes
Overall the changes look good, and I was able to make a move and see it in the TOO queue, and fuss around with Duty Location in various spots with no issues. 

One problem I did see is an error in console that the Customer form is expecting a dutyStationName prop and getting "undefined", where it is required. This is after the initial contact info is submitted, before uploading orders when visiting the review page. I've attached the error I saw. The page is loading ok without this, and can understand we want to minimize the scope of these changes, but seems worth looking at before shipping the code. 

![Screen Shot 2022-03-10 at 2 42 47 PM](https://user-images.githubusercontent.com/4184019/157768097-81e30b63-513c-4c42-b51e-0b242ce632e9.png)

2022-03-10 23:59 UTC, mboren commented
Thanks for catching that, I'll look into it.

2022-03-11 00:54 UTC, mboren commented
I was able to reproduce this with non-installation locations.
I don't think I introduced this issue, but I'm not 100% sure yet, still looking into it.
I'm seeing the same console error locally on master. I don't see the console error on staging, but when I look in the devtools, I see the same problematic props are undefined on staging, so maybe we're just suppressing the error somehow? IDK if that's a thing.
![image](https://user-images.githubusercontent.com/2627844/157779617-a818344c-72a4-4510-ba18-2c5cb847022f.png)

2022-03-11 19:56 UTC, leia-sefkin approved these changes

2022-03-11 19:58 UTC, leia-sefkin commented
after discussing with team we determined the console issue is due to something introduced prior to this work and fixing it will fall into another task. therefore - hitting approval as everything else looks good to 🚢

2022-03-11 20:27 UTC, Ryan-Koch approved these changes

2022-03-11 23:36 UTC, merged