MB-11037: Advance Form for PPM booking on storybook
transcom/mymove pull request #8275
Opened 2022-03-14 18:44 UTC by pearl-truss

## [Jira ticket](https://dp3.atlassian.net/browse/MB-11037) for this change

## Summary

This PR creates the Advance form for PPM Booking and adds it to storybook under: `Customer Components /PPM Booking`

## Setup to Run Your Code

<details>
<summary>💻 You will need to use three separate terminals to test this locally.</summary>

##### Terminal 1

Start the Storybook locally.

```sh
make storybook
```

## Verification Steps for Reviewers

### Frontend

- [ ] User facing changes have been reviewed by design.
- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
- [ ] There are no new console errors in the browser devtools
- [ ] There are no new console errors in the test output
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

## Screenshots
<img width="783" alt="Screen Shot 2022-03-14 at 2 42 49 PM" src="https://user-images.githubusercontent.com/67110378/158239720-7e58778d-a30a-48f9-9458-ac93b5015254.png">
<img width="747" alt="Screen Shot 2022-03-14 at 2 42 57 PM" src="https://user-images.githubusercontent.com/67110378/158239722-71911c86-d704-4709-a902-b56a46838025.png">
<img width="799" alt="Screen Shot 2022-03-14 at 2 43 04 PM" src="https://user-images.githubusercontent.com/67110378/158239723-7a5235a9-ca11-4d5d-8d98-2f2a7c1ea4f4.png">

2022-03-15 00:44 UTC, gidjin commented on src/components/Customer/PPMBooking/Advance/AdvanceForm.jsx
> +          `Enter a weight into at least one pro-gear field. If you won't have pro-gear, select No above.`,
Does this message need to be updated? Wondering if it should be updated to `Enter an advance amount. If you do not want an advance select No above.` or something.

2022-03-15 15:19 UTC, duncan-truss commented on src/components/Customer/PPMBooking/Advance/AdvanceForm.jsx
> +                        values.amountRequested > mtoShipment.ppmShipment.estimatedIncentive / 100
I think you should be able to move this into your validationSchema, you'll just need to make it dynamic instead of static.

I think it could become something like:
```javascript
const validationSchema = (estimatedIncentive) => {
    return Yup.object().shape({
    amountRequested: Yup.number().max(estimatedIncentive, `Your advance is limited to ${maxAdvanceToRequest}`)
    ...
    })
}
```

If you're concerned about this getting called a bunch you could put it inside of a useMemo or useEffect hook so it only changes when the mtoShpment.ppmShipment.estimatedIncentive prop value changes.

2022-03-15 16:33 UTC, duncan-truss commented on src/components/Customer/PPMBooking/Advance/AdvanceForm.jsx
> +                        values.amountRequested > mtoShipment.ppmShipment.estimatedIncentive / 100
That's right, I forgot to add that in my function definition example. The validation schema doesn't have to be outside of the component but that's why I converted it to a function where you can pass any data you need in.

2022-03-15 20:51 UTC, felipe-lee reviewed
Overall looks good! Just a few comments, but the only one that I think needs to be addressed for sure is the test error messages.

Also, I think it might be good to pull in master because there's some CSS that might be useful for the error state. Currently it moves the field label around a lot and I had to fix that in another PR, so _maybe_ those changes will help here too.

2022-03-15 20:51 UTC, felipe-lee commented on src/components/form/fields/MaskedTextField/MaskedTextField.jsx
> +        <div className={suffix ? styles.hasSuffix : styles.hasPrefix}>
Should this maybe use `classnames` to combine things? Like what if a field has both a prefix and a suffix?

2022-03-15 20:51 UTC, felipe-lee commented on src/components/Customer/PPMBooking/Advance/AdvanceForm.test.jsx
> +      const requestAdvance = await screen.getByLabelText('Yes');
iirc the `get*` queries aren't async. If you want to `await` it, you'd need to use the `find*` query, I _think_.

2022-03-15 20:51 UTC, felipe-lee commented on src/components/Customer/PPMBooking/Advance/AdvanceForm.test.jsx
> +describe('AdvanceForm component', () => {
I'm not sure which test it is, but I'm getting formik updates not wrapped in act errors:

![image](https://user-images.githubusercontent.com/35938642/158464901-33cd14c5-76f2-4426-b384-2934dfda8039.png)

2022-03-15 21:27 UTC, duncan-truss commented on src/components/Customer/PPMBooking/Advance/AdvanceForm.jsx
> +  const ppmShipmentAdvance = mtoShipment?.ppmShipment?.advance;
If you want to cut down on all the optional chaining, I've found destructuring like this to work well:
```javascript
const { advance, estimatedIncentive } = mtoShipment?.ppmShipment || {}
```

2022-03-15 21:30 UTC, duncan-truss commented on src/components/Customer/PPMBooking/Advance/AdvanceForm.jsx
> +  const formatedIncentive = formatCentsTruncateWhole(mtoShipment?.ppmShipment?.estimatedIncentive);
Should we add some null case checking or use some defaults in case the shipment data hasn't resolved yet so we aren't doing division on undefined values?

2022-03-15 22:45 UTC, dinabeigelman requested changes
It looks like the error state for advance amount is pushing the whole field down. I believe this is what @duncan-truss and @felipe-lee also encountered. Might there be a more systemic way to address this issue from popping up again?

![error state issue](https://user-images.githubusercontent.com/7771969/158484508-5df7e1a9-761a-48f4-8a32-4a2543dad009.png)

2022-03-15 23:26 UTC, scarequotes requested changes
The Jira ticket says the customer should get a warning if they enter over 60% of their incentive, and a hard block if they enter over 100%. 

Instead, they don't get any message for entering 60-99%, and a hard block for over 100%.

![Screen Shot 2022-03-15 at 4 10 55 PM](https://user-images.githubusercontent.com/30428256/158487643-4e19053f-c855-4116-a8cd-f96d6e51730e.png)
![Screen Shot 2022-03-15 at 4 10 46 PM](https://user-images.githubusercontent.com/30428256/158487647-ac765e8b-00a2-4a98-b289-97b13c3cd7d8.png)
![Screen Shot 2022-03-15 at 4 10 35 PM](https://user-images.githubusercontent.com/30428256/158487648-2d57568f-6281-4ba2-bb29-ea438dee8367.png)

Expected behavior: 

- Should get a warning message if I enter between $6,001 and $10,000, but Save & continue button should be active
- Should get a different warning message if I enter $10,001 or more, and Save & continue should not be active

I don't think we gave specific language for those scenarios, so I recommend:

- for soft validation: "Reminder: your advance can not be more than $X,XXX" (number is 60% of incentive)
- for hard validation: "Enter an amount less than $X,XXX " (where the number is 60% of incentive) 

Also discovered a related error while tracking that down. 

![Screen Shot 2022-03-15 at 4 03 56 PM](https://user-images.githubusercontent.com/30428256/158486691-8574430f-a64f-40ae-9fa3-457794d3c3b0.png)

I got that by entering $555,555, then moving my cursor to the beginning of the line and deleting the second 5. When the amount switched to $55,555, I got that odd error message.

(This but is less critical than the one about hard and soft errors.)

2022-03-15 23:35 UTC, felipe-lee commented
> Also discovered a related error while tracking that down.
> 
> ![Screen Shot 2022-03-15 at 4 03 56 PM](https://user-images.githubusercontent.com/30428256/158486691-8574430f-a64f-40ae-9fa3-457794d3c3b0.png)
> 
> I got that by entering $555,555, then moving my cursor to the beginning of the line and deleting the second 5. When the amount switched to $55,555, I got that odd error message.
> 
> (This but is less critical than the one about hard and soft errors.)

I think this one should be fixed after master gets merged in.

2022-03-16 11:10 UTC, pearl-truss commented
> > Also discovered a related error while tracking that down.
> > ![Screen Shot 2022-03-15 at 4 03 56 PM](https://user-images.githubusercontent.com/30428256/158486691-8574430f-a64f-40ae-9fa3-457794d3c3b0.png)
> > I got that by entering $555,555, then moving my cursor to the beginning of the line and deleting the second 5. When the amount switched to $55,555, I got that odd error message.
> > (This but is less critical than the one about hard and soft errors.)
> 
> I think this one should be fixed after master gets merged in.

Thanks for working on the fix for this Felipe! I saw that it was resolved once I pulled in master 🎉

2022-03-16 11:35 UTC, pearl-truss commented
> * Reminder: your advance can not be more than

This was resolved when I pulled in master which had Felipe's changes

2022-03-16 11:36 UTC, pearl-truss commented
> The Jira ticket says the customer should get a warning if they enter over 60% of their incentive, and a hard block if they enter over 100%.
> 
> Instead, they don't get any message for entering 60-99%, and a hard block for over 100%.
> 
> ![Screen Shot 2022-03-15 at 4 10 55 PM](https://user-images.githubusercontent.com/30428256/158487643-4e19053f-c855-4116-a8cd-f96d6e51730e.png) ![Screen Shot 2022-03-15 at 4 10 46 PM](https://user-images.githubusercontent.com/30428256/158487647-ac765e8b-00a2-4a98-b289-97b13c3cd7d8.png) ![Screen Shot 2022-03-15 at 4 10 35 PM](https://user-images.githubusercontent.com/30428256/158487648-2d57568f-6281-4ba2-bb29-ea438dee8367.png)
> 
> Expected behavior:
> 
> * Should get a warning message if I enter between $6,001 and $10,000, but Save & continue button should be active
> * Should get a different warning message if I enter $10,001 or more, and Save & continue should not be active
> 
> I don't think we gave specific language for those scenarios, so I recommend:
> 
> * for soft validation: "Reminder: your advance can not be more than $X,XXX" (number is 60% of incentive)
> * for hard validation: "Enter an amount less than $X,XXX " (where the number is 60% of incentive)
> 
> Also discovered a related error while tracking that down.
> 
> ![Screen Shot 2022-03-15 at 4 03 56 PM](https://user-images.githubusercontent.com/30428256/158486691-8574430f-a64f-40ae-9fa3-457794d3c3b0.png)
> 
> I got that by entering $555,555, then moving my cursor to the beginning of the line and deleting the second 5. When the amount switched to $55,555, I got that odd error message.
> 
> (This but is less critical than the one about hard and soft errors.)

Thanks, this was super helpful and has been addressed

2022-03-16 12:06 UTC, pearl-truss commented on src/components/Customer/PPMBooking/Advance/AdvanceForm.jsx
> +  const ppmShipmentAdvance = mtoShipment?.ppmShipment?.advance;
Nice, thanks!

2022-03-16 15:08 UTC, duncan-truss approved these changes
Code looks good to me, I think you can clean up the warning vars to use your new destructed ones.  We probably want to format the max advance number in the warning too with the $ sign and thousands comma separator.

2022-03-16 15:24 UTC, scarequotes approved these changes
The warning message should have a `$` before the amount — so $6,000 in the screenshot below. 

Looks like we're still getting the warning pushing text down the page a little, as well

LGTM otherwise. I'll `Approve` so it's not a blocker but definitely want the dollar sign fixed.

![Screen Shot 2022-03-16 at 8 21 48 AM](https://user-images.githubusercontent.com/30428256/158625519-fa4e399e-96bb-4d68-a98d-928ac1df7667.png)

2022-03-16 15:27 UTC, pearl-truss commented
> The warning message should have a `$` before the amount — so $6,000 in the screenshot below.
> 
> Looks like we're still getting the warning pushing text down the page a little, as well
> 
> LGTM otherwise. I'll `Approve` so it's not a blocker but definitely want the dollar sign fixed.
> 
> ![Screen Shot 2022-03-16 at 8 21 48 AM](https://user-images.githubusercontent.com/30428256/158625519-fa4e399e-96bb-4d68-a98d-928ac1df7667.png)

This was updated in the latest commit

<img width="651" alt="Screen Shot 2022-03-16 at 11 27 01 AM" src="https://user-images.githubusercontent.com/67110378/158626551-135b2914-517d-47e7-bb9d-b8fc7dde5c2b.png">

2022-03-16 15:28 UTC, pearl-truss commented
> Code looks good to me, I think you can clean up the warning vars to use your new destructed ones. We probably want to format the max advance number in the warning too with the $ sign and thousands comma separator.

Good catch, I just pushed a commit that addresses the formatting and cleans up the vars

2022-03-16 18:42 UTC, dinabeigelman reviewed
Looks like the field still seems to jump a bit (tho less than before) when it goes into the error state. Also jumps in the warning states as well.

![error state issue 2](https://user-images.githubusercontent.com/7771969/158663622-0d072ef0-624f-4633-b9d8-e5f1e7efc118.png)

2022-03-16 18:46 UTC, dinabeigelman approved these changes

2022-03-16 19:42 UTC, merged