Draft: Kc po9 switching to keyvalue
transcom/mymove pull request #8368
Opened 2022-03-31 20:44 UTC by kennethchow-truss

## [Jira ticket](tbd) for this change

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Setup to Run Your Code

<details>
<summary>💻 You will need to use three separate terminals to test this locally.</summary>

##### Terminal 1

Start the Storybook locally.

```sh
make storybook
```

##### Terminal 2

Start the UI locally.

```sh
make client_run
```

##### Terminal 3

Start the Go server locally.

```sh
make server_run
```

</details>

### Additional steps

1. Access the
2. Login as a
3.

## Verification Steps for Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Request review from a member of a different team.
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Frontend

- [ ] User facing changes have been reviewed by design.
- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
- [ ] There are no new console errors in the browser devtools
- [ ] There are no new console errors in the test output
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide#logging)
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide/#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#zero-downtime-migrations)
- [ ] Have been communicated to #g-database
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#secure-migrations)

## Screenshots

2022-04-01 16:47 UTC, kennethchow-truss commented
@mergify-bot rebase

2022-04-01 16:54 UTC, kennethchow-truss commented
@mergifyio rebase

2022-04-01 22:23 UTC, michaelvaldes-truss requested changes

2022-04-01 22:23 UTC, michaelvaldes-truss commented on pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
> +	stringData := *data
I think it's possible that there are scenarios (e.g. for insert events) where the old_data might be nil, which will cause a panic here. We might want to do a nil check or reconsider how we're unmarshalling data from the database

2022-04-04 15:54 UTC, merged

2022-04-04 16:59 UTC, kennethchow-truss commented on src/constants/historyLogUIDisplayName.js
> +export const HistoryLogValuesShape = PropTypes.object;
That would require a lot of manual work across all the tables we are trying to add. Also, part of the goal of our DB design is to maintain flexibility in case fields are added or changed, I feel that adding explicit shapes to these Front End components might go against that flexibility