Rp mb 11601 delete shipment
transcom/mymove pull request #8375
Opened 2022-04-04 17:28 UTC by ronaktruss

## [Jira ticket](tbd) for this change

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Setup to Run Your Code

<details>
<summary>💻 You will need to use three separate terminals to test this locally.</summary>

##### Terminal 1

Start the Storybook locally.

```sh
make storybook
```

##### Terminal 2

Start the UI locally.

```sh
make client_run
```

##### Terminal 3

Start the Go server locally.

```sh
make server_run
```

</details>

### Additional steps

1. Access the
2. Login as a
3.

## Verification Steps for Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Request review from a member of a different team.
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Frontend

- [ ] User facing changes have been reviewed by design.
- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
- [ ] There are no new console errors in the browser devtools
- [ ] There are no new console errors in the test output
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide#logging)
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide/#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#zero-downtime-migrations)
- [ ] Have been communicated to #g-database
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#secure-migrations)

## Screenshots

2022-04-06 00:26 UTC, felipe-lee commented on src/components/ShipmentList/index.jsx
> -      {canEdit ? <FontAwesomeIcon icon="pen" className={styles.edit} /> : <div className={styles.noEdit} />}
I'm glad we're getting rid of the icon-only button in favor of text 🎉

2022-04-06 00:26 UTC, felipe-lee commented on src/components/ShipmentList/index.jsx
> +          </Button>
I'm not 100% sure if we should keep using buttons or not for things that are in effect, just links. It's come up in the past but I don't remember the decision in the end. I've started a [thread in #prac-frontend](https://ustcdp3.slack.com/archives/CTQQJD3G8/p1649202414214919) asking if others remember what was decided.

2022-04-06 15:48 UTC, ronaktruss commented on src/components/Customer/Home/Step/Step.module.scss
> +
Remove additional whitespace at the bottom of the home page
![image](https://user-images.githubusercontent.com/84742904/162012690-7fe1c949-892d-4700-b8cf-555ca43c7430.png)

2022-04-07 20:48 UTC, duncan-truss commented on src/pages/MyMove/Review/Review.jsx
> +    canMoveNext: !!Object.keys(mtoShipments).length, // TODO: prevent incomplete PPM submission?
Heads up I removed this property in my PR that's now in master.  I did add a selector to return the shipments similar to what you're doing above.  Probably just move this logic to inside the component in conjunction with the check for an incomplete PPM.

2022-04-08 17:56 UTC, ronaktruss commented on src/components/ShipmentList/ShipmentList.test.jsx
>      await waitFor(() => {
@felipe-lee Is there a reason that we are using await here as opposed just triggering the click and using expects similar to what is done for the deletes below?

2022-04-08 17:56 UTC, ronaktruss commented on src/containers/FlashMessage/FlashMessage.jsx
> +  );
This was changed because the previous implementation made it so that if you modified the message multiple times on the same page it would be cleared on alternating notifications. (eg. If you delete two records on the first you would see a message, but on the second the message would disappear. You would then alternate seeing and not seeing it on subsequent triggers.)

Does anyone have context on the reason for this original implementation? If the comment is correct I think this servers to better mimic that description.

2022-04-08 18:12 UTC, ronaktruss commented
@scarequotes There are some existing issues with the modal that causes some potentially jarring scrolling to the top and back to your original position after the modal closes.

2022-04-08 19:03 UTC, jenniferlynparsons commented on src/components/ConfirmationModals/DestructiveShipmentConfirmationModal.jsx
> +  title = 'Are you sure?',
issue: The default value strings go against our typical pattern on this project.
suggestion: Use `defaultProps` (part of `propTypes`) to hold default values. You can see an example of how `defaultProps` are used with string placeholders on [FileUpload.jsx])https://github.com/transcom/mymove/blob/84f4f1004a9f7031d3e1cce0682e741eab5a9230/src/components/FileUpload/FileUpload.jsx#L92)

2022-04-08 21:25 UTC, ronaktruss commented on src/components/ConfirmationModals/DestructiveShipmentConfirmationModal.jsx
> +  title = 'Are you sure?',
Happy to make that change. Is there a particular reason that is the pattern? 

I saw some indication that defaultProps for functional components may be deprecated in the "future"(https://github.com/reactjs/rfcs/pull/107 and https://github.com/facebook/react/pull/16210/files)

2022-04-08 23:04 UTC, YanZ777 requested changes

2022-04-08 23:35 UTC, YanZ777 commented on src/components/Customer/Review/ShipmentCard/PPMShipmentCard/PPMShipmentCard.test.jsx
> +    fireEvent.click(editBtn);
**suggestion (non blocking):** Use `userEvent` rather than `fireEvent`.

2022-04-08 23:53 UTC, YanZ777 reviewed
A few more comments I have after going through this PR. I don't think I did a very deep review, so I'd prefer others to weigh in as well.

2022-04-08 23:53 UTC, YanZ777 commented on src/components/ShipmentList/ShipmentList.test.jsx
> +    for (let i = 0; i < defaultProps.shipments.length; i += 1) {
**suggestion (non blocking):** It looks like you might want to use a table driven test here instead.

2022-04-08 23:53 UTC, YanZ777 commented on src/components/ShipmentList/ShipmentList.jsx
> +  canEditOrDelete: bool.isRequired,
**thought:** I'm not sure how I feel about having both edit and delete being controlled by the same prop.
**question:** Will edit and delete always go hand in hand or will there ever be a case where a person can edit, but not delete, or vice versa?

2022-04-08 23:53 UTC, YanZ777 commented on src/components/ShipmentList/ShipmentList.module.scss
> +:global(.usa-button).edit-btn {
**suggestion:** I think you should be able to pass `secondary` to the button that you are trying to give this styling, since this looks like you're trying to get secondary styling. 
e.g. `<Button secondary type="button" onClick={closeModal}>`

2022-04-09 00:25 UTC, YanZ777 commented on src/components/ShipmentList/ShipmentList.module.scss
> +:global(.usa-button).edit-btn {
**thought:** Scratch this comment. I see what the visual looks like. Secondary won't help here.

2022-04-11 16:17 UTC, ronaktruss commented on src/components/ShipmentList/ShipmentList.jsx
> +  canEditOrDelete: bool.isRequired,
Our current expectations are that both edit and delete should be accessible as long as the move is not submitted. I didn't want to preemptively optimize for alternative scenarios that might not happen, as this is a fairly small change we can make when it is needed.

Are there any existing scenarios where we would want to separate out the availability of this functionality.

2022-04-11 16:42 UTC, ronaktruss commented on src/components/ConfirmationModals/DestructiveShipmentConfirmationModal.jsx
> +    <ModalContainer>
Thanks for pointing out the connectedModal. 

Given the current implementation it looks like the usage of a connected Modal will make it so that the modal is top aligned but supports scenarios where the modal text is large/requires scrolling. If we manually use `Overlay` and `ModalContainer` this will make the modal vertically centered but not appropriately handle a large amount of modal text. I have started a [thread](https://ustcdp3.slack.com/archives/CNTDW9Q1Z/p1649691824364099) to see if there is an expected behavior for modals. 

ConnectedModal behavior:
<img width="894" alt="Screen Shot 2022-04-11 at 9 54 12 AM" src="https://user-images.githubusercontent.com/84742904/162788563-5a75379f-4b86-47d8-8635-794dcc7a9c9b.png">

https://user-images.githubusercontent.com/84742904/162788742-a29ffe3f-35ae-4dbc-90d3-acc7e00637f4.mov

Manual usage of Overlay and ModalContainer:
<img width="897" alt="Screen Shot 2022-04-11 at 10 03 59 AM" src="https://user-images.githubusercontent.com/84742904/162788728-9d65df0b-e01a-4cd3-8d49-9e78ed25fc2f.png">

https://user-images.githubusercontent.com/84742904/162788599-e6aabae7-2253-4828-8409-9db4ce2584c2.mov

2022-04-12 00:03 UTC, YanZ777 commented on src/containers/FlashMessage/FlashMessage.jsx
> +  );
**thought:** I don't have any context on this.

2022-04-12 00:04 UTC, YanZ777 commented on src/components/ShipmentList/ShipmentList.jsx
> +  canEditOrDelete: bool.isRequired,
**thought:** I think if the current expectation is that both edit and delete and jointly accessible, then it's fine to leave as it is.

2022-04-12 15:14 UTC, pearl-truss commented on cypress/integration/office/servicescounseling/servicesCounselingNTSR.js
> +    cy.get('[data-testid="modal"] button').contains('Delete shipment').click({ force: true });
Thanks for adding this!

2022-04-12 19:52 UTC, duncan-truss commented on src/components/ConfirmationModals/DestructiveShipmentConfirmationModal.stories.jsx
> +    onSubmit={() => {}}
Try to define these stories using the newer [args pattern](https://storybook.js.org/docs/react/writing-stories/args) so that these props become editable in the Storybook controls panel and you can also use actions so those events show up in the [actions tab](https://github.com/storybookjs/storybook/blob/master/addons/actions/ADVANCED.md#manually-specified-actions) too.

2022-04-12 19:58 UTC, duncan-truss commented on src/components/Customer/Review/ShipmentCard/ShipmentCard.module.scss
> +        padding: 12px;
I think it's good to avoid using pixels and use USWDS tokens whenever possible.  You should be able to rewrite this as `@include u-padding(1.5)` https://designsystem.digital.gov/design-tokens/spacing-units/

2022-04-12 23:02 UTC, ronaktruss commented
> I've been testing and things look very good! One minor issue I see is when you delete all of the shipments on the Review page, the next button is still enabled for you to submit the move. I think if you just combine a check for mtoShipments length with the complete PPM conditional in Review.jsx you can fix that disabling.

@duncan-truss Yeah I caught this as well when I was working on the cypress tests. I forgot to add this back in when I merged in your code that added the logic for the incomplete PPMs. See [commit](https://github.com/transcom/mymove/pull/8375/commits/dddeeeba110b2c180d31d669d87f20162af9f5ce)

2022-04-13 00:50 UTC, felipe-lee commented on src/components/Customer/Review/ShipmentCard/PPMShipmentCard/PPMShipmentCard.test.jsx
> +    const editBtn = screen.queryByRole('button', { name: 'Edit' });
The `queryBy*` queries should be used for when you expect something to not exist. Otherwise, it should probably be `getBy*` or `findBy*`

https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#using-query-variants-for-anything-except-checking-for-non-existence

2022-04-13 00:50 UTC, felipe-lee commented on src/components/ShipmentList/ShipmentList.test.jsx
> +    expect(screen.getAllByTestId('shipment-list-item-container')[3]).toHaveTextContent(/^nts-release #id-4/i);
These shouldn't use the testID. I can see needing if for the count since there's not a great way to grab that otherwise, but for each shipment, we can use the `getByText` query. It's better to avoid testIDs with RTL if possible:
* https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#not-querying-by-text
* https://testing-library.com/docs/queries/about/#priority

2022-04-13 00:50 UTC, felipe-lee commented on src/components/ShipmentList/ShipmentList.test.jsx
> +    let editBtn = queryByRole(screen.getAllByTestId('shipment-list-item-container')[0], 'button', { name: 'Edit' });
Hmm, I also feel like these shouldn't use the test ID (like my comment above), but this one is harder. I wonder if grabbing the text of the shipment ID and then looking at sibling elements or something. Maybe it's just better like you have it.

2022-04-13 00:50 UTC, felipe-lee commented on src/components/ShipmentList/ShipmentList.test.jsx
> +      const deleteBtn = queryByRole(screen.getAllByTestId('shipment-list-item-container')[i], 'button', {
Same comment here about using `queryBy*` vs `getBy*`

2022-04-13 00:50 UTC, felipe-lee commented on src/shared/Entities/reducer.js
> +  }
Let me preface this by saying, I don't know much (i.e. next to nothing) about redux or how all these things tie together. But, looking at the existing code, is there a reason we need the new path for updating MTO shipments? It _seems_ like the `ADD_ENTITIES` path is doing the same thing, at least in the end. It's doing a merge of the original and new, but if the new overwrites the whole of `mtoShipments` I feel like that should be fine? Again, I could be totally off and if you tried that and it didn't work, then nvm.

2022-04-13 00:50 UTC, felipe-lee commented on src/sagas/entities.js
> +
Related to my comment on the reducer, it feels like this could follow the pattern of the other things on here, but going for `mtoShipments` as a whole, unlike the existing singular func above your new one.

2022-04-13 13:45 UTC, duncan-truss commented on src/shared/Entities/reducer.js
> +  }
I think would could clarify the purpose some and maybe make it a bit generalized if we called it REPLACE_ENTITY to reflect what it's doing now.

2022-04-13 13:55 UTC, ronaktruss commented on src/sagas/entities.js
> +
I think my answer above answer this. If not, can you rephrase the question/concern here.

2022-04-13 14:35 UTC, duncan-truss commented on src/pages/MyMove/Review/Review.jsx
> +                disableNext={!hasCompletedPPMShipments || !Object.keys(mtoShipments).length}
mtoShipments should be an array of objects coming back from the selectMTOShipmentsForCurrentMove selector or assigned to an empty array by default. I don't think calling Object.keys is necessary here.

2022-04-13 17:30 UTC, felipe-lee commented on src/components/ShipmentList/ShipmentList.test.jsx
> +    expect(screen.getAllByTestId('shipment-list-item-container')[3]).toHaveTextContent(/^nts-release #id-4/i);
Ah I didn't notice that. Ok, sounds good.

2022-04-13 18:34 UTC, scarequotes approved these changes
This PR works as expected for design. 

One call-out: Deleted shipments work as expected on this page, but then at least sometimes appear on the review screen. I think there's an existing ticket to fix that as a separate story, but just a heads-up that that will need to be fixed at some point.

2022-04-13 18:40 UTC, felipe-lee commented on src/containers/FlashMessage/FlashMessage.jsx
> +  );
I don't know anything about the initial implementation, but I think having a dependency array in `useEffect` is a good practice, and like you said, seems to match what the comment indicates we want, so I think this change is probably for the best.

2022-04-13 18:40 UTC, felipe-lee commented on src/pages/MyMove/Home/index.jsx
> +            )}
Sorry, you might have addressed this somewhere and I missed it, but do we need the separate alerts? Like does `<ConnectedFlashMessage />` not work if you're staying on the same page?

2022-04-13 18:52 UTC, felipe-lee commented on src/pages/MyMove/Home/index.test.jsx
> +      wrapper.find('ShipmentListItem').at(0).find('button').at(1).simulate('click');
I'm getting a missing prop error from one of the tests in this file, but I think it wasn't one you updated so I don't think it's a blocker for this PR. Just putting the info here in case you want to address it:
![image](https://user-images.githubusercontent.com/35938642/163249953-c1c67fa5-9848-4526-b453-6b8d6a336eaf.png)

2022-04-13 20:08 UTC, felipe-lee reviewed
Found a few prop errors in stories

2022-04-13 20:08 UTC, felipe-lee commented on src/components/ShipmentList/ShipmentList.stories.jsx
> +      onDeleteClick={() => {}}
This has a prop error from the missing `moveSubmitted` prop:

![image](https://user-images.githubusercontent.com/35938642/163261570-7cd0c974-5ba5-4ab4-acde-ec00d629232c.png)

2022-04-13 20:08 UTC, felipe-lee commented on src/components/ShipmentList/ShipmentList.stories.jsx
> +      onDeleteClick={() => {}}
This one also needs the `moveSubmitted` prop

2022-04-13 20:28 UTC, ronaktruss commented on src/pages/MyMove/Home/index.jsx
> +            )}
It's not actually clear to me when we use `Alert` vs `ConnectedFlashMessage`. I'd assume and it does generally seem to be the case that `ConnectedFlashMessage` was used when the parent had the ConnectedFlashMessage and the child element would just dispatch the action to update the message. Alerts seem to be used when the update is happening within the same component. With the update above we should be able to use `ConnectedFlashMessage` if we want.

2022-04-13 20:30 UTC, ronaktruss commented on src/components/ConfirmationModals/DestructiveShipmentConfirmationModal.stories.jsx
> +  onClose: { action: 'close button clicked' },
Ooops, this wasn't supposed to be checked in 😅. As a general note thanks for being thorough and providing references/sources.

2022-04-13 20:35 UTC, felipe-lee commented on src/pages/MyMove/Home/index.jsx
> +            )}
I think you're right about the general times we use each. I guess I'd opt for, if the page already has `<ConnectedFlashMessage/>` to use it, but maybe this is a discussion for FE check in. I'm fine with keeping this as is for now and if we decide to change it, it can be a follow-up later on.

2022-04-13 21:19 UTC, felipe-lee commented on src/pages/MyMove/Home/index.jsx
> +            )}
I started [a thread in #prac-frontend about this](https://ustcdp3.slack.com/archives/CTQQJD3G8/p1649882920594469) and plan on bringing it up at tomorrow's check in.

2022-04-13 21:19 UTC, felipe-lee commented on src/shared/Entities/reducer.js
> +  }
I started [a semi-related thread in #prac-frontend about this](https://ustcdp3.slack.com/archives/CTQQJD3G8/p1649882920594469) and plan on bringing it up at tomorrow's check in.

2022-04-13 21:20 UTC, felipe-lee approved these changes
I think given that some things need to discussed at a FE group level, I'm fine with this as is for now. Well pending those prop error fixes, but I don't want to be a blocker on this once you push those fixes up.

2022-04-14 18:07 UTC, merged