MB-12136 Shipment Approved Event
transcom/mymove pull request #8384
Opened 2022-04-05 18:20 UTC by kennethchow-truss

## [Jira ticket](tbd) for this change

## Summary

Adding an event display for shipment approved event.

## Setup to Run Your Code

1. Go to http://officelocal:3000/sign-in
2. Log in as an office user
3. Go to link: http://officelocal:3000/moves/DVRS0N/details
4. Approve a shipment 
5. Go to the history page
6. Observe there is a row with "Approved shipment" as the event

## Screenshots

![image](https://user-images.githubusercontent.com/84801109/161823458-4484323c-62f0-4807-bad2-fe9fa09d0e53.png)

2022-04-06 20:54 UTC, donaldthai commented on src/constants/historyLogUIDisplayName.js
> +export const shipmentTypeDetails = {
Can you also add the operation id `approveShipment`? That's the other approve endpoint for shipments.

2022-04-06 21:10 UTC, kennethchow-truss commented on src/constants/historyLogUIDisplayName.js
> +export const shipmentTypeDetails = {
Added

2022-04-06 21:11 UTC, donaldthai commented on src/constants/historyLogUIDisplayName.js
> +    }
I think we need to add `approveShipment` here too right?

2022-04-06 21:13 UTC, donaldthai commented on src/constants/historyLogUIDisplayName.test.js
> +  describe('display Approved shipment', () => {
Could also add a test case for operation id `approveShipment` here too?

2022-04-06 22:16 UTC, YanZ777 requested changes

2022-04-06 22:16 UTC, YanZ777 commented on src/pages/Office/MoveHistory/MoveHistoryDetailsSelector.jsx
> +  if (shipmentTypeDetails[eventName]) {
This looks like it would fall under PlainTextDetails, where you can just add the mapping to `eventNamePlainTextToDisplay` inside of `historyLogUIDisplayName`.
The latest changes from main show how to use the oldValues to get the shipment type.

2022-04-07 18:40 UTC, YanZ777 commented on src/pages/Office/MoveHistory/MoveHistoryDetailsSelector.test.jsx
> +    ['requestShipmentDiversion', 'Requested diversion'],
I'd take out this case since it is being covered by the below tests already.

2022-04-07 18:40 UTC, YanZ777 commented on src/constants/historyLogUIDisplayName.js
> +    }
I actually don't think this case is needed here since the other two events specifically need status to check what to return. 
`approveShipmentDiversion` can just fall into the default case and return `Approved shipment`.

2022-04-07 18:44 UTC, kennethchow-truss commented on src/pages/Office/MoveHistory/MoveHistoryDetailsSelector.jsx
> +  if (shipmentTypeDetails[eventName]) {
Changed to be under plain text

2022-04-07 18:45 UTC, kennethchow-truss commented on src/pages/Office/MoveHistory/MoveHistoryDetailsSelector.test.jsx
> +    ['requestShipmentDiversion', 'Requested diversion'],
Removed

2022-04-07 20:21 UTC, YanZ777 approved these changes

2022-04-07 20:25 UTC, merged