MB-11600 Block incomplete PPMs on frontend
transcom/mymove pull request #8438
Opened 2022-04-14 20:42 UTC by pearl-truss

## [Jira ticket](tbd) for this change

## Summary

- This PR blocks submission on the move/home page if any ppm shipment is incomplete.
- I removed legacy `current_ppm` logic on this page and in the unit tests

## ENGINEERING NOTES
- I noticed that `mto_shipment.ppmShipment.advancedRequested` isn't being automatically set to `null` on the front and instead that field is missing completely. Our existing `isPPMComplete` utility function was checking for a null value and since the field wasn't present (and not set to null) that check was failing. I've added an additional check in `isPPMComplete` to check for `undefined` as a temp fix and will look into why `advanceRequested` isn't being set to null

## DESIGN NOTES
- I realize when the PPM is incomplete the step number should show instead of a check mark. I will add this in when I'm back
reference: 
<img width="513" alt="Screen Shot 2022-04-14 at 4 38 53 PM" src="https://user-images.githubusercontent.com/67110378/163471650-a5f33af6-ad17-47dc-aea3-ed6249bf2357.png">

## Other Todos
- fix unit test for the home page
- add test for incomplete ppms for the home page
- update the step (3) to display instead of checkmark when there's ppm shipment that's incomplete
- look into why the frontend isn't setting `advanceRequested` to `null` initially

## Setup to Run Your Code

<details>
<summary>💻 You will need to use three separate terminals to test this locally.</summary>

##### Terminal 1

Start the Storybook locally.

```sh
make storybook
```

##### Terminal 2

Start the UI locally.

```sh
make client_run
```

##### Terminal 3

Start the Go server locally.

```sh
make server_run
```

</details>

### Additional steps

1. Access the 
2. Login as a
3.

### Frontend

- [ ] User facing changes have been reviewed by design.
- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
- [ ] There are no new console errors in the browser devtools
- [ ] There are no new console errors in the test output
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

## Screenshots
<img width="1043" alt="Screen Shot 2022-04-14 at 4 30 34 PM" src="https://user-images.githubusercontent.com/67110378/163470775-f2eb7787-2392-4d37-b2ec-dc7d2f6922e0.png">
<img width="1007" alt="Screen Shot 2022-04-14 at 4 31 14 PM" src="https://user-images.githubusercontent.com/67110378/163470778-580cc864-f90d-48f4-9c5e-474f304ff67a.png">

2022-04-14 21:47 UTC, duncan-truss commented on src/utils/shipments.js
> +  if (mtoShipment?.ppmShipment?.advanceRequested === null || mtoShipment?.ppmShipment?.advanceRequested === undefined) {
The reason I used `advanceRequested != null` is because it gives the same result for undefined as well as null because it doesn't look at type equality the way `!==` or `===` do.

![Screen Shot 2022-04-14 at 5 47 03 PM](https://user-images.githubusercontent.com/52669884/163482023-08e3b5cd-8e31-403e-9849-f4ee38b58277.png)

2022-04-19 00:06 UTC, felipe-lee commented on src/utils/shipments.js
> +  if (mtoShipment?.ppmShipment?.advanceRequested === null || mtoShipment?.ppmShipment?.advanceRequested === undefined) {
**thought**: I think being explicit how this was changed to might be better though so that future folks don't think it was an accident. Either that or adding a comment about it.

2022-04-19 00:10 UTC, felipe-lee commented
>     * I noticed that `mto_shipment.ppmShipment.advancedRequested` isn't being automatically set to `null` on the front and instead that field is missing completely. Our existing `isPPMComplete` utility function was checking for a null value and since the field wasn't present (and not set to null) that check was failing. I've added an additional check in `isPPMComplete` to check for `undefined` as a temp fix and will look into why `advanceRequested` isn't being set to null

**thought**: I think it's because we didn't set `x-omitempty` to `false` for `advance` and `advanceRequested`: https://github.com/transcom/mymove/blob/e24b332827774fbe82e51d28b5b5d12999d5b796/swagger-def/internal.yaml#L2540-L2550

**suggestion (non-blocking)**: Since we do set it for other fields on the `PPMShipment` and it's affecting this PR, can you update it as part of this PR?

2022-04-19 00:57 UTC, felipe-lee commented on src/components/ShipmentList/ShipmentList.jsx
> +        }
**nitpick**: Could you combine these and make it a `const`? 

**note**: Making it a `const` would require a change above to remove the `let isIncomplete` declaration so this suggestion can't be used standalone, sorry 😞 

```suggestion
        const isIncomplete = shipmentType === SHIPMENT_OPTIONS.PPM && !isPPMShipmentComplete(shipment)
```

2022-04-19 00:57 UTC, felipe-lee commented on src/utils/shipments.js
> +  if (mtoShipment?.ppmShipment?.advanceRequested === null || mtoShipment?.ppmShipment?.advanceRequested === undefined) {
**suggestion**: Given the change I suggested in another comment to the `internal.yaml` spec, I think we no longer have to check for undefined in this function. So I think we can change this to be 

```js
return mtoShipment?.ppmShipment?.advanceRequested !== null
```

2022-04-19 00:57 UTC, felipe-lee commented on src/components/ShipmentList/ShipmentList.stories.jsx
> +);
**issue**: There's two console errors with each of these new stories (only going to comment on this one to save space and comments). One is that the `moveSubmitted` prop is missing from the `ShipmentList` props. The other is that it says it can't find the story with the given ID, though it is loading the page so I'm not sure what the error means tbh.

![image](https://user-images.githubusercontent.com/35938642/163898528-64af0399-f8d7-40e0-b0f2-52b3f724ecd5.png)

2022-04-19 00:57 UTC, felipe-lee commented on src/components/ShipmentList/ShipmentList.stories.jsx
> +);
Huh...I'm getting that second error with every storybook component we have (or at least the ones I tested out that aren't part of this PR). So I guess it's mainly the missing prop that needs to be addressed in this PR. The other error I'm not sure about.

2022-04-19 00:57 UTC, felipe-lee commented on src/pages/MyMove/Home/index.jsx
> +  get hasCompletedPPMShipments() {
**nitpick**: Could the name be something like `hasCompletedAllPPMShipments`? Mainly because from the name, I could see it meaning all, or as long as there's one PPM Shipment completed it could be true. But the code is functionally doing the first.

2022-04-19 00:57 UTC, felipe-lee commented on src/pages/MyMove/Home/index.jsx
> -  }).isRequired,
**praise**: thank you for cleaning up the old PPM code in this page!

2022-04-19 14:46 UTC, ronaktruss commented on src/components/ShipmentList/ShipmentList.stories.jsx
> +);
This file has been modified quite a bit on master as part of https://github.com/transcom/mymove/pull/8375. That PR resolved the first issue and modified the existing story names.

2022-04-21 14:31 UTC, duncan-truss commented on src/utils/shipments.js
> +  if (mtoShipment?.ppmShipment?.advanceRequested === null || mtoShipment?.ppmShipment?.advanceRequested === undefined) {
I'm fine with being more explicit about it 👍 We should be comfortable dealing with undefined on the frontend though, in React props don't always resolve with values immediately and destructuring objects results in undefined values not only null.  By using the optional chaining you are also indicating that the value can be undefined not just null so it's a bit of a mixed message.

2022-04-21 14:31 UTC, duncan-truss commented on src/utils/shipments.js
> +  if (mtoShipment?.ppmShipment?.advanceRequested === null || mtoShipment?.ppmShipment?.advanceRequested === undefined) {
I'm fine with being more explicit about it 👍 We should be comfortable dealing with undefined on the frontend though, in React props don't always resolve with values immediately and destructuring objects results in undefined values not only null.  By using the optional chaining you are also indicating that the value can be undefined not just null so it's a bit of a mixed message.

2022-04-21 17:54 UTC, duncan-truss commented on src/components/ShipmentList/ShipmentList.stories.jsx
> +export const ShipmentListWithPPMs = () => (
Storybook mangled this name
<img width="341" alt="Screen Shot 2022-04-21 at 9 08 59 AM" src="https://user-images.githubusercontent.com/52669884/164521220-5dfd1dae-6037-44b5-b2b3-0b5f248521e8.png">

2022-04-22 16:02 UTC, duncan-truss commented on src/components/ShipmentList/ShipmentList.stories.jsx
> +export const ShipmentListWithPPMs = () => (
It looks like you can override the individual story name this way https://storybook.js.org/docs/react/writing-stories/introduction#rename-stories

2022-04-22 16:47 UTC, ronaktruss approved these changes
LGTM, outside of Duncan's comment regarding the storybook name.

2022-04-22 16:47 UTC, ronaktruss commented on src/utils/shipments.js
> +  if (mtoShipment?.ppmShipment?.advanceRequested === null || mtoShipment?.ppmShipment?.advanceRequested === undefined) {
Nit (suggestion/non-blocking): Personally prefer the original implementation over the current one.

2022-04-22 20:34 UTC, scarequotes approved these changes
Looks good to me!

2022-04-22 20:39 UTC, scarequotes requested changes
![Screen Shot 2022-04-22 at 1 37 52 PM](https://user-images.githubusercontent.com/30428256/164790310-096a9532-cec5-46e9-878a-4e235734fb8b.png)

This needs tweaking on the mobile view — the incomplete label should not move the delete and edit links off the screen. Label can move left, closer to PPM.

2022-04-22 22:29 UTC, felipe-lee commented on src/pages/MyMove/Home/index.test.jsx
> +
**thought**: We shouldn't be adding new tests using enzyme

**suggestion (non-blocking)**: Can you update these new tests to use RTL instead? I don't think you should have to update all the tests in the file to use RTL, but I'd rather make any new tests use RTL. Less work in the future if we do switch the rest of the tests.

2022-04-22 22:29 UTC, felipe-lee commented on src/utils/shipments.js
> +  if (mtoShipment?.ppmShipment?.advanceRequested === null || mtoShipment?.ppmShipment?.advanceRequested === undefined) {
**thought**: I agree with Ronak, if we're sticking with the check we were doing originally, then I prefer the simpler logic. I mainly meant being explicit about the null vs undefined, but if everyone prefers the `!=`, then I like the shorter version more.

2022-04-22 22:30 UTC, felipe-lee approved these changes
LGTM. I added a comment on the new Home page tests, but it's a non-blocking suggestion.

2022-04-25 14:19 UTC, pearl-truss commented
> ![Screen Shot 2022-04-22 at 1 37 52 PM](https://user-images.githubusercontent.com/30428256/164790310-096a9532-cec5-46e9-878a-4e235734fb8b.png)
> 
> This needs tweaking on the mobile view — the incomplete label should not move the delete and edit links off the screen. Label can move left, closer to PPM.

@ronaktruss is this fixed in your PR? otherwise I can address it here

2022-04-25 17:32 UTC, felipe-lee commented on src/pages/MyMove/Home/index.test.jsx
> +
🎉 thanks for making this testing change!

2022-04-25 17:34 UTC, felipe-lee commented on swagger/internal.yaml
> +          description: Requested weight estimate is above allotted entitlement
**question**: I'm not sure if this started showing up because of merging master or something, but it's not meant to be part of your changes right?

2022-04-25 18:17 UTC, pearl-truss commented on swagger/internal.yaml
> +          description: Requested weight estimate is above allotted entitlement
yeah it came after the latest merge from master. I'll look into why

2022-04-25 18:22 UTC, pearl-truss commented on swagger/internal.yaml
> +          description: Requested weight estimate is above allotted entitlement
okay this is resolved, I had to run `make swagger_generate` after the merge

2022-04-25 19:39 UTC, felipe-lee commented on swagger/internal.yaml
> +          description: Requested weight estimate is above allotted entitlement
Nice!

2022-04-26 19:41 UTC, scarequotes approved these changes
Thanks for fixing the alignment!

2022-04-26 20:08 UTC, merged