Add ADR-0070 for new recommendation on cypress test structure
transcom/mymove pull request #8614
Opened 2022-05-13 23:48 UTC by gidjin

## Summary

As part of PO7 A-Team decided on a new way to organize tests for large features. This PR adds an ADR to describe that choice and facilitate discussion about it and hopefully settle on a new pattern to ensure our tests are well organized.

[this slack thread](https://ustcdp3.slack.com/archives/C0250Q8469K/p1651701429155939) has some details.

## Setup to Run Your Code

No steps, just an ADR to read

## Verification Steps for Author

These are to be checked by the author.

- [X] Request review from a member of a different team.

2022-05-16 21:56 UTC, jenniferlynparsons requested changes
Thank you for writing this up! One change needed.

2022-05-16 21:56 UTC, jenniferlynparsons commented on docs/adr/0070-cypress-tests-file-layout.md
> +Recommend short test files over long ones. Long ones have been harder to debug in the past and have sometimes setup dependent tests. This has made it more
Issue: This last sentence isn't complete.

2022-05-16 22:58 UTC, rogeruiz commented on docs/adr/0070-cypress-tests-file-layout.md
> +Recommend short test files over long ones. Long ones have been harder to debug in the past and have sometimes setup dependent tests. This has made it more
This might be how to finish this sentence? I didn't want to be too redundant here.

```suggestion
Recommend short test files over long ones. Long ones have been harder to debug in the past and have sometimes setup dependent tests. This has made it more difficult to troubleshoot longer tests.
```

2022-05-16 22:59 UTC, rogeruiz commented on docs/adr/0070-cypress-tests-file-layout.md
> +- Create a new folder with new test files
```suggestion
## Considered Alternatives (bold denotes chosen)

- Keep every test for the new PPM flow in a `ppm.js` file
- Create new files in the same location
- Create a single new test file
- **Create a new folder with new test files**
```

2022-05-16 23:34 UTC, rogeruiz commented on docs/adr/0070-cypress-tests-file-layout.md
> +- Create a new folder with new test files
A recent bug fix I did for my Cypress test falls into this ADR and is slightly different. Does the Cypress test I added go a step too far as it's testing a very specific flow? I like this super detailed test because the feedback loop is much shorter as I'm only testing a single thing for the FE interacting with the BE. It could fall under other flows, but I personally feel like we missed this bug as it was never tested in the original `txo/` flows.

[=> The PR with the new Cypress test structure I used](https://github.com/transcom/mymove/pull/8564/files)

2022-05-18 10:55 UTC, pearl-truss commented on docs/adr/0070-cypress-tests-file-layout.md
> +
Addition: Smaller test make it easier to write cypress test as the larger feature is being developed

2022-05-23 13:04 UTC, rogeruiz commented on docs/adr/0070-cypress-tests-file-layout.md
> +- Create a new folder with new test files
Thinking about this further. I think it makes sense to call out the smaller tests cause repetition in the setup of tests. We could solve for this repetition with a function call that does it. Or we could accept the repetition as part of this ADR. 

I will add a suggestion on the PR where I think it makes sense to make the call out.

2022-05-26 18:08 UTC, gidjin commented on docs/adr/0070-cypress-tests-file-layout.md
> +Recommend short test files over long ones. Long ones have been harder to debug in the past and have sometimes setup dependent tests. This has made it more
Thanks both of you, I thought I'd finished this sentence but I missed it. I think it maybe because it felt redundant so I'll review it.

2022-05-26 22:34 UTC, gidjin commented on docs/adr/0070-cypress-tests-file-layout.md
> +- Create a new folder with new test files
I think your test follows the pattern and I don't think testing one specific flow is too far. Actually it fits my intention perfectly. You do make a great point about repetition. I'll update the text to reflect that; however, I feel prescribing an approach might go too far. I'd rather suggest a path to mitigate the repetition then leave it up to the individual at the time, at least for now. Open to alternatives though.

2022-05-26 22:39 UTC, gidjin commented on docs/adr/0070-cypress-tests-file-layout.md
> +
Good point, I'll add it

2022-06-06 12:49 UTC, jenniferlynparsons approved these changes
LGTM

2022-06-06 12:58 UTC, rogeruiz approved these changes
lgtm 🌈 

Agree with @jenniferlynparsons. Good work on this @gidjin. 

Is there anyway to prioritize refactoring the old tests? Maybe revisiting old tests to see if they still make sense? Or are we mostly focused on future tests following this pattern. Maybe it's a good topic for our weekly engineering checkin.

2022-06-07 00:17 UTC, gidjin commented
A-Team plans to update the PPM tests to meet this standard, but I'm not sure about the others. It does sound like a good topic for the engineering check-in meeting.

2022-06-07 00:17 UTC, merged