MB-11662 convert all handlers in admin api
transcom/mymove pull request #8622
Opened 2022-05-16 17:36 UTC by YanZ777

## [Jira ticket](https://dp3.atlassian.net/browse/MB-11662) for this change

## Summary

Refactored all the handlers inside of adminapi to the new appcontext pattern.

There are a few handlers that I'm uncertain about, I've left comments in this pull request if you look in the files tab.

## Setup to Run Your Code

<details>
<summary>💻 You will need to use three separate terminals to test this locally.</summary>

##### Terminal 1

Run the Go tests.

```sh
make server_test
```

</details>

### Additional steps

1. Run the Go tests, they should all pass. 

You may want to additionally just run the app and see if everything works.

## Verification Steps for Author

These are to be checked by the author.

- [ ] Request review from a member of a different team.
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide#logging)

2022-05-16 17:41 UTC, YanZ777 commented on pkg/handlers/adminapi/admin_users.go
> +				return adminuserop.NewUpdateAdminUserForbidden(), nil
I'm not sure what error I should be returning here, if I should be returning one.

2022-05-16 18:10 UTC, YanZ777 commented on pkg/handlers/adminapi/moves.go
> +				return moveop.NewUpdateMoveInternalServerError(), nil
Should I be using the logged text to create a new error to return?

2022-05-16 18:18 UTC, YanZ777 commented on pkg/handlers/adminapi/users.go
> +				return userop.NewUpdateUserInternalServerError(), revokeErr
If I returned `validationErrors` here, the tests would fail. However, returning `revokeErrors` makes the tests pass, but I'm not sure if that is the correct thing to return in this case.

2022-05-16 18:42 UTC, michaelvaldes-truss requested changes
**praise:** looks good so far, I added some suggestions!

2022-05-16 18:52 UTC, michaelvaldes-truss commented on pkg/handlers/adminapi/office_users.go
> +				return officeuserop.NewCreateOfficeUserUnprocessableEntity().WithPayload(validationError), verrs
**thought**: I think verrs makes sense, but you could [wrap them together](https://go.dev/doc/go1.13#error_wrapping) if you'd prefer that

2022-05-16 18:52 UTC, michaelvaldes-truss commented on pkg/handlers/adminapi/office_users.go
> +					return userop.NewUpdateUserInternalServerError(), err
**suggestion:** I'd split this into two if conditions

2022-05-16 19:14 UTC, YanZ777 commented on pkg/handlers/adminapi/office_users.go
> +					return userop.NewUpdateUserInternalServerError(), err
If I split into two if conditions, would I still be returning the same `InternalServerError` message or should I have different text in it?

2022-05-16 20:10 UTC, YanZ777 commented on pkg/handlers/adminapi/office_users.go
> +					return userop.NewUpdateUserInternalServerError(), err
Should I be splitting and returning the `revokeError` or the `validationErrors`, or the new `err` that I created?

2022-05-16 20:34 UTC, michaelvaldes-truss commented on pkg/handlers/adminapi/office_users.go
> +					return userop.NewUpdateUserInternalServerError(), err
I think it's fine if you return your new error, or split if-condition like so:

```suggestion
if revokeErr != nil {
   appCtx.Logger().Error(err.Error(), zap.Error(revokeErr))
   return userop.NewUpdateUserInternalServerError(), revokeErr
} else if validationErrors != nil {
   appCtx.Logger().Error(err.Error(), zap.Error(validationErrors))
   return userop.NewUpdateUserInternalServerError(), validationErrors
} 
```

2022-05-17 00:46 UTC, YanZ777 commented on pkg/handlers/adminapi/office_users.go
> +				return officeuserop.NewCreateOfficeUserUnprocessableEntity().WithPayload(validationError), verrs
Looking at this more carefully, I see that there is a case that already handles `errs` so my question here isn't applicable.

2022-05-17 21:10 UTC, YanZ777 commented on pkg/handlers/adminapi/users.go
> +				return userop.NewUpdateUserInternalServerError(), revokeErr
I'm leaving this as is without the suggestion. I've opened up [MB-12521](https://dp3.atlassian.net/browse/MB-12521) for further investigation since I think we still want to figure out how to handle the strangeness around this case and failing test if this suggestion is accepted.

2022-05-17 21:18 UTC, michaelvaldes-truss approved these changes
**praise**: looks great, this was a lot of work!

2022-05-17 22:46 UTC, donaldthai approved these changes
Changes look good! I did some testing around the session revoking on the admin app. Seems to be working. 👍

2022-05-18 20:09 UTC, merged