update backend with nullible strings and set no value to a string poi…
transcom/mymove pull request #8638
Opened 2022-05-18 23:15 UTC by NamibiaTorres

## [Jira ticket](https://dp3.atlassian.net/browse/MB-12249) for this change

## Summary

- Use new nullible strings method
- remove string type form secondary zip definitions
- Add new condition to payload_to_model to allow the use of the `Present` method and check whether secondary zip fields are selected then return nil and empty string if not.
- Our validation.go file in services/ppmshipment already converts empty strings to nil using the `SetOptionalStringField` function.

## Setup to Run Your Code

<details>
<summary>💻 You will need to use three separate terminals to test this locally.</summary>

##### Terminal 1

Start the UI locally.

```sh
make client_run
```

##### Terminal 2

Start the Go server locally.

```sh
make server_run
```

</details>

### Additional steps

1. Log into the local mymove app and set up a ppm shipment (or select a user that has a partial ppm shipment).
2. On the dates and locations page set secondary origin and destination zips to a value, then hit save and continue
3. Go back to the dates and location page and reset values to "no" for both questions about a secondary zip or location
4. Finish the flow and see if secondary zips are saved in the ppm shipment review page. If they aren't then, the bug is fixed.

## Verification Steps for Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Request review from a member of a different team.
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Frontend

- [ ] User facing changes have been reviewed by design.
- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
- [ ] There are no new console errors in the browser devtools
- [ ] There are no new console errors in the test output
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide#logging)
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide/#querying-the-database-safely) have been satisfied.

2022-05-19 21:55 UTC, duncan-truss commented on pkg/handlers/internalapi/internal/payloads/payload_to_model.go
> +		ppmModel.SecondaryDestinationPostalCode = models.StringPointer("")
I don't think we need these else clauses because it is clearing previously set values when we are updating the PPM shipment from other pages and not sending the secondary ZIP keys in those requests.

2022-05-19 23:31 UTC, felipe-lee commented on pkg/handlers/internalapi/internal/payloads/payload_to_model.go
> +		ppmModel.SecondaryDestinationPostalCode = models.StringPointer("")
Ah good point about it clearing out values on other form submissions. I tested a bit and I _think_ it should be updated to something like this instead:

```go
	if ppmShipment.SecondaryDestinationPostalCode.Present {
		if ppmShipment.SecondaryDestinationPostalCode.Value == nil {
			ppmModel.SecondaryDestinationPostalCode = models.StringPointer("")
		} else {
			ppmModel.SecondaryDestinationPostalCode = ppmShipment.SecondaryDestinationPostalCode.Value
		}
	}
```

2022-05-19 23:41 UTC, felipe-lee commented on pkg/handlers/internalapi/internal/payloads/payload_to_model.go
> +		ppmModel.SecondaryDestinationPostalCode = models.StringPointer("")
I would recommend turning this into a re-usable converter in our converters file: https://github.com/transcom/mymove/blob/32ad6b68a10bb888bcdcbadcf764babbed555abe/pkg/handlers/converters_strfmt.go

Something like 

```go
// ConvertNullableStringToStringPtr converts a nullable string swagger type to a string pointer we can use.
func ConvertNullableStringToStringPtr(n nullable.String) *string {
	if n.Present {
		if n.Value == nil {
			return models.StringPointer("")
		}

		return n.Value
	}

	return nil
}
```

Which can then be used like this (note lines 3 and 4 where we're setting the secondary postal codes):

```go
	ppmModel := &models.PPMShipment{
		ActualMoveDate:                 (*time.Time)(ppmShipment.ActualMoveDate),
		SecondaryPickupPostalCode:      handlers.ConvertNullableStringToStringPtr(ppmShipment.SecondaryPickupPostalCode),
		SecondaryDestinationPostalCode: handlers.ConvertNullableStringToStringPtr(ppmShipment.SecondaryDestinationPostalCode),
		SitExpected:                    ppmShipment.SitExpected,
		EstimatedWeight:                handlers.PoundPtrFromInt64Ptr(ppmShipment.EstimatedWeight),
		NetWeight:                      handlers.PoundPtrFromInt64Ptr(ppmShipment.NetWeight),
		HasProGear:                     ppmShipment.HasProGear,
		ProGearWeight:                  handlers.PoundPtrFromInt64Ptr(ppmShipment.ProGearWeight),
		SpouseProGearWeight:            handlers.PoundPtrFromInt64Ptr(ppmShipment.SpouseProGearWeight),
		Advance:                        handlers.FmtInt64PtrToPopPtr(ppmShipment.Advance),
		AdvanceRequested:               ppmShipment.AdvanceRequested,
	}
```

2022-05-19 23:45 UTC, felipe-lee commented on pkg/handlers/internalapi/internal/payloads/payload_to_model.go
> +		ppmModel.SecondaryDestinationPostalCode = models.StringPointer("")
Here's a patch with the changes I made locally to get this working if you want an example. I can also send you the patch file directly so you can apply it more easily. Idk why gh doesn't support patch file uploads.

```patch
Index: pkg/handlers/internalapi/internal/payloads/payload_to_model.go
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/pkg/handlers/internalapi/internal/payloads/payload_to_model.go b/pkg/handlers/internalapi/internal/payloads/payload_to_model.go
--- a/pkg/handlers/internalapi/internal/payloads/payload_to_model.go	(revision 09d423d39fca783f20e0c0cd7c9fa852608de5f4)
+++ b/pkg/handlers/internalapi/internal/payloads/payload_to_model.go	(date 1653003413119)
@@ -1,7 +1,6 @@
 package payloads
 
 import (
-	"fmt"
 	"time"
 
 	"github.com/gofrs/uuid"
@@ -135,15 +134,17 @@
 	}
 
 	ppmModel := &models.PPMShipment{
-		ActualMoveDate:      (*time.Time)(ppmShipment.ActualMoveDate),
-		SitExpected:         ppmShipment.SitExpected,
-		EstimatedWeight:     handlers.PoundPtrFromInt64Ptr(ppmShipment.EstimatedWeight),
-		NetWeight:           handlers.PoundPtrFromInt64Ptr(ppmShipment.NetWeight),
-		HasProGear:          ppmShipment.HasProGear,
-		ProGearWeight:       handlers.PoundPtrFromInt64Ptr(ppmShipment.ProGearWeight),
-		SpouseProGearWeight: handlers.PoundPtrFromInt64Ptr(ppmShipment.SpouseProGearWeight),
-		Advance:             handlers.FmtInt64PtrToPopPtr(ppmShipment.Advance),
-		AdvanceRequested:    ppmShipment.AdvanceRequested,
+		ActualMoveDate:                 (*time.Time)(ppmShipment.ActualMoveDate),
+		SecondaryPickupPostalCode:      handlers.ConvertNullableStringToStringPtr(ppmShipment.SecondaryPickupPostalCode),
+		SecondaryDestinationPostalCode: handlers.ConvertNullableStringToStringPtr(ppmShipment.SecondaryDestinationPostalCode),
+		SitExpected:                    ppmShipment.SitExpected,
+		EstimatedWeight:                handlers.PoundPtrFromInt64Ptr(ppmShipment.EstimatedWeight),
+		NetWeight:                      handlers.PoundPtrFromInt64Ptr(ppmShipment.NetWeight),
+		HasProGear:                     ppmShipment.HasProGear,
+		ProGearWeight:                  handlers.PoundPtrFromInt64Ptr(ppmShipment.ProGearWeight),
+		SpouseProGearWeight:            handlers.PoundPtrFromInt64Ptr(ppmShipment.SpouseProGearWeight),
+		Advance:                        handlers.FmtInt64PtrToPopPtr(ppmShipment.Advance),
+		AdvanceRequested:               ppmShipment.AdvanceRequested,
 	}
 
 	if ppmShipment.ExpectedDepartureDate != nil {
@@ -154,22 +155,10 @@
 		ppmModel.DestinationPostalCode = *ppmShipment.DestinationPostalCode
 	}
 
-	if ppmShipment.SecondaryDestinationPostalCode.Present {
-		ppmModel.SecondaryDestinationPostalCode = ppmShipment.SecondaryDestinationPostalCode.Value
-	} else {
-		ppmModel.SecondaryDestinationPostalCode = models.StringPointer("")
-	}
-	fmt.Println(ppmModel.SecondaryDestinationPostalCode)
 	if ppmShipment.PickupPostalCode != nil {
 		ppmModel.PickupPostalCode = *ppmShipment.PickupPostalCode
 	}
 
-	if ppmShipment.SecondaryPickupPostalCode.Present {
-		ppmModel.SecondaryPickupPostalCode = ppmShipment.SecondaryPickupPostalCode.Value
-	} else {
-		ppmModel.SecondaryPickupPostalCode = models.StringPointer("")
-	}
-
 	return ppmModel
 }
 
Index: pkg/handlers/converters_strfmt.go
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/pkg/handlers/converters_strfmt.go b/pkg/handlers/converters_strfmt.go
--- a/pkg/handlers/converters_strfmt.go	(revision 09d423d39fca783f20e0c0cd7c9fa852608de5f4)
+++ b/pkg/handlers/converters_strfmt.go	(date 1653003733125)
@@ -3,10 +3,11 @@
 import (
 	"time"
 
-	"github.com/gofrs/uuid"
-
 	"github.com/go-openapi/strfmt"
+	"github.com/gofrs/uuid"
 
+	"github.com/transcom/mymove/pkg/models"
+	"github.com/transcom/mymove/pkg/swagger/nullable"
 	"github.com/transcom/mymove/pkg/unit"
 )
 
@@ -76,3 +77,16 @@
 	pound := unit.Pound(value)
 	return &pound
 }
+
+// ConvertNullableStringToStringPtr converts a nullable string swagger type to a string pointer we can use.
+func ConvertNullableStringToStringPtr(n nullable.String) *string {
+	if n.Present {
+		if n.Value == nil {
+			return models.StringPointer("")
+		}
+
+		return n.Value
+	}
+
+	return nil
+}
```

2022-05-23 19:54 UTC, felipe-lee commented on pkg/handlers/internalapi/mto_shipment_test.go
> +					SecondaryDestinationPostalCode: nullable.NewString(""), // TODO: Update to pass null since that's what the FE will actually send.
**todo**: These two should be changed to be `nil` since that's what the FE will send. You can also remove the `TODO` comments to the right.

2022-05-24 20:51 UTC, duncan-truss approved these changes
Tested it locally and looks like the problem is fixed!

2022-05-24 22:52 UTC, felipe-lee commented on pkg/handlers/internalapi/internal/payloads/payload_to_model.go
> +		SecondaryDestinationPostalCode: handlers.FmtNullableStringToStringPtr(ppmShipment.SecondaryDestinationPostalCode),
**issue**: Can you add back the `ActualPickupPostalCode` and `ActualDestinationPostalCode`

2022-05-24 22:56 UTC, felipe-lee commented on pkg/handlers/internalapi/mto_shipment_test.go
> +					})
**thought**: I think this would be good to leave as it was since for this test case we're ensuring we can add secondary zips when there weren't any before.

2022-05-24 23:05 UTC, felipe-lee commented on pkg/handlers/internalapi/mto_shipment_test.go
> +							ActualDestinationPostalCode: models.StringPointer("90210"),
**todo**: Similar comment here as above, this test is trying to make sure we can add the actual postal codes so they shouldn't already be in the original shipment.

2022-05-24 23:06 UTC, felipe-lee commented on pkg/handlers/internalapi/mto_shipment_test.go
> +							ActualDestinationPostalCode: models.StringPointer("90210"),
**todo**: This one too, shouldn't have actual zips in the original shipment.

2022-05-24 23:08 UTC, felipe-lee requested changes
I left comments on a few things I think need to be updated before merging. The main one that I consider a blocker is the removal of those two fields in the payload_to_model, but I also think the others should be updated.

2022-05-25 04:59 UTC, NamibiaTorres commented on pkg/handlers/internalapi/internal/payloads/payload_to_model.go
> +		SecondaryDestinationPostalCode: handlers.FmtNullableStringToStringPtr(ppmShipment.SecondaryDestinationPostalCode),
Yes! I must have accidentally deleted while resolving the merge with master.

2022-05-25 19:28 UTC, merged