MB-9097: Remove DPS
transcom/mymove pull request #8651
Opened 2022-05-20 12:41 UTC by ahobson

## [Remove dead code paths: my.sddc.army.mil - mymove repo](https://dp3.atlassian.net/browse/MB-9097)

## Summary

Remove dead code related to DPS.

Really this was grepping for DPS and SDDC and chasing the string. Lots of files changed, but not terribly complicated

## Setup to Run Your Code

```
make server_test
```
## Verification Steps for Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Request review from a member of a different team.
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

2022-05-20 15:32 UTC, sheenamt commented
@ahobson The things I can review (docker and env files) look good.

2022-05-27 16:10 UTC, reggieriser approved these changes
I started to review on behalf of DB reviewers, but went ahead and reviewed the whole PR (well, as much as makes sense for a big code pruning like this).  Things LGTM!  I did do a search for "dps" on the branch and found a few nitpicks that I added.  There's also a couple of references to `DPS users` in the top-level `README.md` which wasn't touched, so you may want to get rid of them while pruning.  But those aren't big deals, so going ahead and approving.  Thanks for taking care of this! 🚀

2022-05-27 16:10 UTC, reggieriser commented on config/tls/devlocal-not-dps.key
> ------BEGIN PRIVATE KEY-----
**nitpick:** There's a reference to this file still in `.pre-commit-config.yaml`.

2022-06-27 18:40 UTC, gidjin requested changes
This looks good to me, I left one question for a line that looks like it shouldn't have been deleted so flagging this as requested changes since I'd like to make sure that line is correctly removed.

Second is a general question on this. Is there a plan/story to remove the environment vars from chamber after this PR is merged?

2022-06-27 18:40 UTC, gidjin commented on pkg/handlers/apitests.go
> -// AuthenticateAdminRequest authenticates DPS users
Praise: Nice catch on the copy pasta comment

2022-06-27 18:40 UTC, gidjin commented on pkg/models/client_cert_test.go
> -		AllowOrdersAPI:  true,
Question: Did you intend to delete the `AllowOrdersAPI` attribute here?

2022-06-28 15:51 UTC, ahobson commented on pkg/models/client_cert_test.go
> -		AllowOrdersAPI:  true,
The test doesn't depend on the setting of any particular capability, so I thought I'd only add the minimum necessary to the model. Concerns with that approach?

2022-06-28 20:27 UTC, ahobson commented
> This looks good to me, I left one question for a line that looks like it shouldn't have been deleted so flagging this as requested changes since I'd like to make sure that line is correctly removed.

I responded to the question as I think the line removed in the test was not necessary for the test and was arguably confusing.

> Second is a general question on this. Is there a plan/story to remove the environment vars from chamber after this PR is merged?

We have a ticket with infrasec related changes, but thank you for flagging that! I'll ask

2022-06-29 16:07 UTC, gidjin commented on pkg/models/client_cert_test.go
> -		AllowOrdersAPI:  true,
I missed that this was a test! Thank for answering

2022-06-29 16:08 UTC, gidjin approved these changes

2022-06-30 16:09 UTC, merged