Adding prime actual weight
transcom/mymove pull request #8657
Opened 2022-05-20 21:50 UTC by kennethchow-truss

[Jira Ticket](https://dp3.atlassian.net/browse/MB-11344)

## Summary

Added one line to accommodate the prime actual weight. Writing this PR and probably the writing the ticket probably took longer than making the change haha

## Setup to Run Your Code

1. Log in as a prime user
2. Navigate to move PENDNG
3. Click update shipment
4. Edit the actual pickup date and actual weight
5. Click save
6. Sign out 
7. Sign in as TIO user
8. Navigate to move PENDNG
9. Navigate to the move history tab
10. Observe that both actual pickup date and actual weight are created

2022-05-23 21:27 UTC, rogeruiz approved these changes
lgtm 🌈

2022-05-23 22:45 UTC, donaldthai requested changes

2022-05-23 22:45 UTC, donaldthai commented on src/constants/MoveHistory/Database/FieldMappings.js
> +  prime_actual_weight: 'Prime actual weight',
suggestion (blocking): I think the field name display text is suppose to be `Shipment weight` according to the [spreadsheet](https://docs.google.com/spreadsheets/d/1r-c01NLG1j2KgdZAnmiECs5e5goySIoEGw2Ue36DGK4/edit#gid=569262977&range=E28).

I would also append that field to the `LabeledDetails.test.jsx` file for [this test](https://github.com/transcom/mymove/blob/b1969b3d5cb3393eda91ce7114d4aaef791cdd6e/src/pages/Office/MoveHistory/LabeledDetails.test.jsx#L9). Would help to confirm what name and display text we're using.

2022-05-23 22:49 UTC, donaldthai commented on src/constants/MoveHistory/Database/FieldMappings.js
> +  prime_actual_weight: 'Prime actual weight',
another suggestion (blocking): Seems like the jira story is asking to add the `actual_pickup_date` field as display text `Departure date`

2022-05-24 17:21 UTC, kennethchow-truss commented on src/constants/MoveHistory/Database/FieldMappings.js
> +  prime_actual_weight: 'Prime actual weight',
Made the changes. Lemme know if there are other issues

2022-05-24 21:25 UTC, donaldthai approved these changes
⭐

2022-05-25 17:01 UTC, merged