add info alert to advances page if service member has retirement or s…
transcom/mymove pull request #8710
Opened 2022-06-01 16:03 UTC by duncan-truss

…eperation orders types

## [Jira ticket](https://dp3.atlassian.net/browse/MB-12169) for this change

## Summary

This PR displays an info alert if the service member's orders are of type retirement or separation on the advances page.  It does not functionally block or prevent the user from taking any action.

## Setup to Run Your Code

<summary>💻 You will need to use three separate terminals to test this locally.</summary>

##### Terminal 1

Start the UI locally.

```sh
make client_run
```

##### Terminal 2

Start the Go server locally.

```sh
make db_dev_e2e_populate && server_run
```

</details>

### Additional steps

1. Login as a test user with a PPM shipment such as `estimated_weights@ppm.unsubmitted`
2. Edit the existing PPM shipment until you reach the Advances page. 
3. Verify that no info alert is shown on the advances page.
4. Navigate back to the home page and edit the orders of the move.
5. Change the orders type to Retirement or Separation and save.
6. Resume editing the PPM shipment and continue to the Advances page.
7. Now an info alert will be shown advising that retirees and separatees typically don't request advances.

## Verification Steps for Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Request review from a member of a different team.
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Frontend

- [ ] User facing changes have been reviewed by design.
- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
- [ ] There are no new console errors in the browser devtools
- [ ] There are no new console errors in the test output
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide#logging)
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide/#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#zero-downtime-migrations)
- [ ] Have been communicated to #g-database
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#secure-migrations)

## Screenshots

<img width="717" alt="Screen Shot 2022-06-01 at 11 55 16 AM" src="https://user-images.githubusercontent.com/52669884/171449092-ed78424d-8aca-4fb8-9bfd-6ae7d4cac806.png">
![Screen Shot 2022-06-01 at 11 55 52](https://user-images.githubusercontent.com/52669884/171449121-896223d5-896c-4408-86f6-28d6138d2954.png)

2022-06-01 18:38 UTC, ronaktruss commented on src/pages/MyMove/PPMBooking/Advance/Advance.test.jsx
> +  selectCurrentOrders: jest.fn().mockImplementation(() => mockOrders),
FYSA: There is syntactic sugar for this ([ref](https://jestjs.io/docs/mock-function-api#mockfnmockimplementationfn))
```
selectCurrentOrders: jest.fn(() => mockOrders),
```

2022-06-01 18:39 UTC, ronaktruss commented on src/pages/MyMove/PPMBooking/Advance/Advance.test.jsx
>    eTag: btoa(new Date()),
Nit: This isn't anything you changed, but it looks like btoa is deprecated. You could replace it with the following
```suggestion
  eTag: Buffer.from(new Date()).toString('base64'),
```

2022-06-01 18:59 UTC, ronaktruss commented on src/pages/MyMove/PPMBooking/Advance/Advance.jsx
> +  const isRetireeOrSeparatee = matchesOrdersType(orders, ORDERS_TYPE.RETIREMENT, ORDERS_TYPE.SEPARATION);
Suggestion (non-blocking): It might be worth considering moving this upwards so that the two returns are closer together (from a readability perspective). 

Praise: `matchesOrdersType` works even when orders is undefined/null 🎉

2022-06-01 21:09 UTC, duncan-truss commented on src/pages/MyMove/PPMBooking/Advance/Advance.test.jsx
> +  selectCurrentOrders: jest.fn().mockImplementation(() => mockOrders),
Oh nice, I know there is mockReturnValue too that can be used to similar effect most of the time since we're not doing anything dynamic based on the call values.  I was mostly matching the existing style.

2022-06-01 21:29 UTC, duncan-truss commented on src/pages/MyMove/PPMBooking/Advance/Advance.test.jsx
> +    async (orders) => {
I guess my reasoning is if most component tests that are not async already will need to be with v14 if they are calling any `userEvent` or calling `waitFor` for appearance.  I know I've copied existing tests before and wondered why they didn't work until I made them async.  So that's made me generally default to async, because tests get expanded upon and then need switched over.

2022-06-01 21:43 UTC, ronaktruss commented on src/pages/MyMove/PPMBooking/Advance/Advance.jsx
> +  const isRetireeOrSeparatee = matchesOrdersType(orders, ORDERS_TYPE.RETIREMENT, ORDERS_TYPE.SEPARATION);
I was initially suggesting, that the loading placeholder be moved lower so that it is right next to the return call at the end of the function. (I'm not opposed to moving this return near the top, but from my initial glance it looked like the common pattern was to have it closer to the return function.)

2022-06-01 21:49 UTC, duncan-truss commented on src/pages/MyMove/PPMBooking/Advance/Advance.jsx
> +  const isRetireeOrSeparatee = matchesOrdersType(orders, ORDERS_TYPE.RETIREMENT, ORDERS_TYPE.SEPARATION);
Thanks for clarifying, well we can't have conditional hooks so it always needs to be below any hook calls but we're also doing wasted work of regenerating the handlers and deriving the orders type when we know the shipment/orders is not yet resolved.  I don't think redefining the handlers is a huge performance concern most of the time, so I do see the value of return statements being as close as possible.

2022-06-01 22:21 UTC, duncan-truss commented on src/pages/MyMove/PPMBooking/Advance/Advance.test.jsx
> +    async (orders) => {
That's definitely possible waitFor may be less necessary in the future.  I don't have a prediction for how it will or won't change really.

2022-06-01 22:45 UTC, felipe-lee commented on src/pages/MyMove/PPMBooking/Advance/Advance.test.jsx
> +    async (orders) => {
**thought**: I agree with Ronak that idk that it's necessary to add `async` before we know we need it for a given test. I'm a little more on the fence on whether we should preemptively add `await` for `userEvent` usages. One the one hand, I think Ronak's point about it being possible to miss errors but have files doing things incorrectly is a valid one, but on the other, I know dependency management and the time it takes has been a concern for a while so leaving fewer things for that team to clean up might be better, even if it is the case that these wouldn't be major changes. Maybe it'd be good to check in with the team doing dep management this sprint.

2022-06-02 00:44 UTC, felipe-lee approved these changes
Works as expected! I left a few comments and one suggestion, but it's all small stuff so I'll approve

2022-06-02 00:44 UTC, felipe-lee commented on src/utils/orders.test.js
> +describe('matchesOrdersType', () => {
**praise**: thanks for setting up thorough tests of the new util!

2022-06-02 00:44 UTC, felipe-lee commented on src/pages/MyMove/PPMBooking/Advance/Advance.jsx
> +  if (!mtoShipment && !orders) {
**thought**: I _think_ we probably want to use the loading placeholder if either the shipment or orders haven't loaded yet.

**suggestion**:  If my thought is correct, this should change to `||` instead of `&&`.

2022-06-02 00:44 UTC, felipe-lee commented on src/pages/MyMove/PPMBooking/Advance/Advance.test.jsx
> +
**question**: should there be tests for the `LoadingPlaceholder`?

2022-06-02 13:22 UTC, duncan-truss commented on src/pages/MyMove/PPMBooking/Advance/Advance.jsx
> +  if (!mtoShipment && !orders) {
🤦‍♂️ Oh duh

2022-06-02 13:23 UTC, duncan-truss commented on src/pages/MyMove/PPMBooking/Advance/Advance.test.jsx
> +
Good point, we have that in some office components I can add it here as well

2022-06-02 18:44 UTC, scarequotes requested changes
Looks good, works as expected. 

Please update copy in the infobox to:
`People leaving the military may not be eligible to receive an advance, based on individual service policies. Your counselor can give you more information after you make your request.`

2022-06-02 22:28 UTC, scarequotes approved these changes
LGTM. Thanks for the text change!

2022-06-03 13:16 UTC, merged