MB-13153: Refactor routing/server setup to allow for testing
transcom/mymove pull request #8871
Opened 2022-07-08 14:52 UTC by ahobson

## [Jira ticket](https://dp3.atlassian.net/browse/MB-13153) for this change

## Summary

This refactors code from `cmd/milmove/serve.go` into `pkg/handlers/routing/routing_init.go` so we can more easily test server setup and server routing.

There are many lines of changes, but it's mostly moving from one file to another. However, to facilitate independent testing, a new configuration struct for routing was created.

## Setup to Run Your Code

All existing functionality should remain the same, so the usual steps of running the application locally, running the tests, would apply.

## Verification Steps for Author

These are to be checked by the author.

- [X] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Request review from a member of a different team.
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide#logging)

2022-07-11 20:22 UTC, shimonacarvalho requested changes
One possible bug with orders api being moved to officelocal

Also a request to comment serveFunction and routerConfig. 

Other than that - looks good to me. I ran the tests, ran the server, milmove, office, admin clients. Also compared the server up logs from master to this branch (only in devlocal). All checked out, although there are some ordering differences in the logs which hopefully don't matter.

2022-07-11 20:22 UTC, shimonacarvalho commented on cmd/milmove/serve.go
> +func serveFunction(cmd *cobra.Command, args []string) error {
It's awesome to see this giant function broken into functional blocks. 

Since it's such an important function and does so many big/impactful things - I'd really love to see it be properly commented enough for an eng to read along and comprehend how the server gets set up.

2022-07-11 20:22 UTC, shimonacarvalho commented on cmd/milmove/serve.go
> +	if useDevlocalAuthCA {
Could this DevlocalAuth bit not be moved to a function to match the pattern of the rest of the serve function? Seems there are rather low level commands in here.

2022-07-11 20:22 UTC, shimonacarvalho commented on pkg/handlers/routing/routing_init.go
> +	// routing config
Since this config is so important - documentation via comments of what each parameter means would be amazing.

2022-07-12 15:35 UTC, ahobson commented on pkg/handlers/routing/routing_init.go
> +		ordersDetectionMiddleware := auth.HostnameDetectorMiddleware(appCtx.Logger(), officeServerName)
Thank you! Fixed!

2022-07-12 15:54 UTC, ahobson commented on cmd/milmove/serve.go
> +func serveFunction(cmd *cobra.Command, args []string) error {
Ok, I've added more comments, let me know what you think

2022-07-12 15:54 UTC, ahobson commented on cmd/milmove/serve.go
> +	if useDevlocalAuthCA {
Good idea, I've made changes, let me know what you think

2022-07-12 16:11 UTC, ahobson commented on pkg/handlers/routing/routing_init.go
> +	// routing config
Excellent idea. Done!

2022-07-14 17:49 UTC, shimonacarvalho commented
Think we should put more testing in soon, but in light of this being invasive and the possibility of it going stale, agree on merging it.

https://ustcdp3.slack.com/archives/C03BDHDMZSS/p1657223100408819

2022-07-14 18:01 UTC, shimonacarvalho approved these changes

2022-08-08 12:32 UTC, merged