[MB-12493] backend for evaluation reports page
transcom/mymove pull request #8882
Opened 2022-07-11 22:21 UTC by mboren

## [Jira ticket](tbd) for this change

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Setup to Run Your Code

<details>
<summary>💻 You will need to use three separate terminals to test this locally.</summary>

##### Terminal 1

Start the Storybook locally.

```sh
make storybook
```

##### Terminal 2

Start the UI locally.

```sh
make client_run
```

##### Terminal 3

Start the Go server locally.

```sh
make server_run
```

</details>

### Additional steps

1. Access the
2. Login as a
3.

## Verification Steps for Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Request review from a member of a different team.
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Frontend

- [ ] User facing changes have been reviewed by design.
- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
- [ ] There are no new console errors in the browser devtools
- [ ] There are no new console errors in the test output
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide#logging)
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide/#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#zero-downtime-migrations)
- [ ] Have been communicated to #g-database
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#secure-migrations)

## Screenshots

2022-07-13 20:17 UTC, mboren commented on pkg/testdatagen/scenario/subscenarios.go
> +func subScenarioEvaluationReport(appCtx appcontext.AppContext) func() {
todo: update this with ppm, nts, and ntsr shipments.

2022-07-13 21:22 UTC, leia-sefkin reviewed
Left some comments and suggestions inline, interested to hear what you think. Not fully decided but two separate routes feels more restful, we can also convo with Patrick when he's back in action since he'll bring a good FE view. 

Otherwise the code is looking good so far

2022-07-13 21:22 UTC, leia-sefkin commented on swagger-def/ghc.yaml
> +  '/moves/{moveID}/evaluation-reports':
i like your reasoning behind choosing moveID rather than locator, and the choice of moves seems good too.

r.e. the question of response structure, i would recommend a few tweaks:
* split the route into two, one for get a list of counseling reports, one for get a list of shipment reports
* from a FE standpoint for this story we don't need to load the entire report data, we only need enough to populate the table. this means you could simplify your code a little just to retrieve that subset of info, and update the route name to something like `report-list` or `report-info`.

2022-07-18 19:48 UTC, leia-sefkin requested changes
Did another review after splitting out the endpoints and like the changes overall. I saw a few places where there's some cleanup needed with temp variables and documentation. 

I am also curious to hear from @Ryan-Koch or @PDickeyTruss what they think about the response structure for these endpoints [The design](https://www.figma.com/file/5AhuEkaH3bJVrtffU3wp22/Milmove-Office-App?node-id=1938%3A36651) shows only a small subset of report info is needed (report ID, date submitted, location, violations (bool), serious incident (bool)). Should we return the full report data to the FE or just query for what we need and only load the full set when we go to resume or view?

2022-07-18 19:48 UTC, leia-sefkin commented on pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
> +		location = &foo // :(
looks like these foos 🤪 need updating

2022-07-18 19:48 UTC, leia-sefkin commented on pkg/services/evaluation_report/evaluation_report_list_fetcher.go
> +		Where("(submitted_at IS NOT NULL OR office_user_id = ?)", officeUserID).
question: does submitted_at get set on initial creation or only when a report is saved? 

concern: according to our figma designs a report can't be edited once it's submitted. would this query exclude reports in draft state? e.g. if they are set to `submitted_at IS NULL`

2022-07-18 19:48 UTC, leia-sefkin commented on swagger-def/ghc.yaml
> +        - application/json
TODO: add a response body ref here describing the response structure

2022-07-19 16:38 UTC, Ryan-Koch commented on pkg/services/evaluation_report/evaluation_report_list_fetcher.go
> +		Where("(submitted_at IS NOT NULL OR office_user_id = ?)", officeUserID).
Eventually we'll want this to exclude draft reports that the user didn't create. We can address that extra layer of logic later though (likely in: https://dp3.atlassian.net/browse/MB-12887), for now I'd be okay with spitting out all of the reports including those in draft that anyone has created.

2022-07-19 16:38 UTC, mboren commented on pkg/services/evaluation_report/evaluation_report_list_fetcher.go
> +		Where("(submitted_at IS NOT NULL OR office_user_id = ?)", officeUserID).
submitted_at should only get set when a report is submitted.
The query is supposed to exclude all queries in draft state unless you are logged in as the same office user that created them.

2022-07-19 16:44 UTC, Ryan-Koch commented on pkg/services/evaluation_report/evaluation_report_list_fetcher_test.go
> +		// would that be worth it?
I think this is okay. Returning the empty list seems like a reasonable approach here. If this were an external API it might be worth the extra feedback around what caused the empty list, but since it's only our client using this I don't think it's necessary.

2022-07-19 17:52 UTC, mboren commented on swagger-def/ghc.yaml
> +        - application/json
I'm not totally sure what you're referring to here

2022-07-19 17:54 UTC, mboren commented on pkg/handlers/ghcapi/internal/payloads/model_to_payload.go
> +		location = &foo // :(
I couldn't see a way to avoid using the temporary variables, so i renamed these to something more reasonable and got rid of my frowny face comments.

2022-07-19 17:54 UTC, mboren commented on pkg/services/evaluation_report/evaluation_report_list_fetcher_test.go
> +		// would that be worth it?
Thanks. I agree. I reworded this comment to be more of an explanation than a question.

2022-07-19 18:01 UTC, mboren commented
re: how much info we should include in the response:
I'm happy to go in either direction with this.
- I have a strong personal preference for including just the minimum that we need for the frontend
- I think on milmove we generally include whole objects so that we can share swagger definitions between endpoints, so this is what I went with. But I'm not sure if that's an explicit convention, or more of a vibe that I've inferred.

2022-07-19 18:03 UTC, mboren commented on swagger-def/ghc.yaml
> +  '/moves/{moveID}/evaluation-reports':
I implemented the suggestion to split into two routes, I think it is nicer. Still not totally sure how much to include in the response, I left another comment about that down below.

2022-07-20 17:10 UTC, leia-sefkin approved these changes

2022-07-20 17:11 UTC, leia-sefkin commented
thanks for all the hard work and conversation around how to approach this sensibly. changes look great, let's 🚢 IT

2022-07-20 18:04 UTC, merged