[MB-13136] PPM closeout add new item page
transcom/mymove pull request #8902
Opened 2022-07-14 18:38 UTC by duncan-truss

## [Jira ticket](https://dp3.atlassian.net/browse/MB-13136) for this change

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Setup to Run Your Code

<details>
<summary>💻 You will need to use three separate terminals to test this locally.</summary>

##### Terminal 1

Start the Storybook locally.

```sh
make storybook
```

##### Terminal 2

Start the UI locally.

```sh
make client_run
```

##### Terminal 3

Start the Go server locally.

```sh
make server_run
```

</details>

### Additional steps

1. Access the
2. Login as a
3.

## Verification Steps for Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Request review from a member of a different team.
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Frontend

- [ ] User facing changes have been reviewed by design.
- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
- [ ] There are no new console errors in the browser devtools
- [ ] There are no new console errors in the test output
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide#logging)
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide/#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#zero-downtime-migrations)
- [ ] Have been communicated to #g-database
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#secure-migrations)

## Screenshots

2022-07-18 17:24 UTC, duncan-truss commented on src/components/Customer/PPM/Closeout/ReviewItems/ReviewItems.jsx
> +                    <dt className={classnames({ [styles.hiddenTerm]: hideLabel })} aria-hidden={hideLabel}>
For the rows with no label, I needed a way to make sure there was still a valid `&lt;dt&gt;` element in the definition list.

2022-07-18 17:29 UTC, duncan-truss commented on src/pages/MyMove/PPM/Closeout/Review/Review.test.jsx
> +      expect(memoryHistory.location.pathname).toEqual(editAboutYourPPM);
I think this is the first test that lets you test react-router-dom Links call the right path.  At first I tried passing in a custom history prop with mocked push and goBack but that seemed incomplete.  Normally we've only been able to mock our component's own use of history.push when called directly.

2022-07-18 17:31 UTC, duncan-truss commented on src/utils/closeout.jsx
> +export const formatAboutYourPPMItem = (ppmShipment, edit) => {
I might move this back into the component folder since it does have to be a JSX file because of the react elements being created.  The component is pretty general though so I could see other format functions being created.

2022-07-19 14:33 UTC, pearl-truss commented on src/pages/MyMove/PPM/Closeout/Review/Review.test.jsx
> +      expect(memoryHistory.location.pathname).toEqual(editAboutYourPPM);
praise: nice!

2022-07-19 14:36 UTC, duncan-truss commented
> Question: should the mobile layout hold true in storybook?
> 
> <img alt="Screen Shot 2022-07-19 at 10 27 41 AM" width="471" src="https://user-images.githubusercontent.com/67110378/179775475-d5befb8c-5601-4c21-9efd-ebeb9179c7b4.png">

That's a good point.  I guess it depends, the more general you make a component it means that often it's hard to apply styles when custom components are passed in as links and buttons to allow more control.  Here it is probably easier to style certain things at the page level because you know what's being passed in.

I can probably fix storybook styling regardless so it doesn't look wrong but may not actually put those styles in the ReviewItems component module.

2022-07-19 15:23 UTC, ronaktruss reviewed
Based on my understanding of the story's AC, this is missing the routing logic, cypress tests, and potential testdatagen data. (The routing logic is also mentioned in the integration story) This also partially completes the work of https://dp3.atlassian.net/browse/MB-13137 (summary of pro gear and expenses).

We may need to update the stories to capture this.

2022-07-19 15:29 UTC, duncan-truss commented on pkg/services/ghcdieselfuelprice/ghc_diesel_fuel_price_fetcher.go
> +	fmt.Println(string(responseBody))
It was removed a few commits back you may be looking at a stale diff.

2022-07-19 15:49 UTC, duncan-truss commented
> Based on my understanding of the story's AC, this is missing the routing logic, cypress tests, and potential testdatagen data. (The routing logic is also mentioned in the integration story.) This also partially completes the work of https://dp3.atlassian.net/browse/MB-13137 (summary of pro gear and expenses).
> 
> We may need to update the stories to capture this.

Agree we'll need to clean up some of the ACs to reflect that we moved this work up ahead of where it was initially intended to be.  I am adding a testdatagen move now, I don't think I'll include the homepage routing though.  I think it's enough that you can get to the page from the weight tickets page at the moment.

2022-07-20 02:42 UTC, felipe-lee reviewed
> > Based on my understanding of the story's AC, this is missing the routing logic, cypress tests, and potential testdatagen data. (The routing logic is also mentioned in the integration story.) This also partially completes the work of https://dp3.atlassian.net/browse/MB-13137 (summary of pro gear and expenses).
> > We may need to update the stories to capture this.
> 
> Agree we'll need to clean up some of the ACs to reflect that we moved this work up ahead of where it was initially intended to be. I am adding a testdatagen move now, I don't think I'll include the homepage routing though. I think it's enough that you can get to the page from the weight tickets page at the moment.

Did we get confirmation that it's fine to put off the home page routing?

2022-07-20 02:42 UTC, felipe-lee commented on src/utils/closeout.jsx
> +      renderEditLink: () => edit,
**nit**: The other functions build the `Link` within the function while this one takes it in as a param. I think for matching, it'd be nice if this one was like the rest.

2022-07-20 02:42 UTC, felipe-lee commented on src/components/Customer/PPM/Closeout/ReviewItems/ReviewItems.stories.jsx
> +        { id: 'description', label: 'Description:', value: 'Training manuals' },
**todo**: I think this is missing the `hideLabel: true`

2022-07-20 02:42 UTC, felipe-lee commented on src/components/Customer/PPM/Closeout/ReviewItems/ReviewItems.jsx
> +const ReviewItems = ({ className, heading, renderAddButton, contents, emptyMessage }) => {
**thought**: idk that this should be changed, but I think this component would be easier to grok (at least it was a bit hard for me at first) if it was the generic component for the weights, pro-gear, and expenses, but not the top "About your PPM" section. I think to aid in that, the `<dl>` bit below could be extracted into a component that would be re-used across both the "About your PPM" component and this component because at least in my eyes, that's the main common bit (and the edit button, but that's already using a component).

Again, not something that has to change, just voicing my thoughts. Like in general, I think each of the things this component is being used for would be easier to understand if they had dedicated components, since they wouldn't have to go through the util function before getting passed in necessarily, but I can definitely appreciate that there are a lot of similarities in the way the weights, pro-gear, and expenses work so I see the value in generalizing it like this.

2022-07-20 02:42 UTC, felipe-lee commented on src/components/Customer/PPM/Closeout/ReviewItems/ReviewItems.test.jsx
> +    expect(screen.queryByRole('term', { name: 'Actual Move Date:' })).not.toBeInTheDocument();
**praise**: I didn't realize this finally got fixed, thanks for noticing and using these! (previously dt/dd couldn't be found with rtl)

2022-07-20 02:42 UTC, felipe-lee commented on src/pages/MyMove/PPM/Closeout/Review/Review.jsx
> +  });
**suggestion (non-blocking)**: this might be good to extract to a util of some kind since the home page will also need to know this in order to know if it needs to route to the review page or go through the full flow.

2022-07-20 12:28 UTC, duncan-truss commented on src/components/Customer/PPM/Closeout/ReviewItems/ReviewItems.test.jsx
> +    expect(screen.queryByRole('term', { name: 'Actual Move Date:' })).not.toBeInTheDocument();
Yes that was awkward having to work around that, I think there still isn't an accessible role for link/anchor from what I saw but I didn't go investigating.

2022-07-20 12:53 UTC, duncan-truss commented on src/components/Customer/PPM/Closeout/ReviewItems/ReviewItems.jsx
> +const ReviewItems = ({ className, heading, renderAddButton, contents, emptyMessage }) => {
Thanks for sharing, I always want to hear your opinions.  I am trying to look at it with fresh eyes and I think I felt like you did at first that maybe it wasn't worth generalizing for both types.  Looking at it now though I think the component is pretty concise at 50 lines and most of the work is accomplished in the prop types and styling.

I guess I'm a bit tired of one of components that aren't able to be reused at all like all these [definition list components](https://github.com/transcom/mymove/tree/master/src/components/Office/DefinitionLists).

I don't think this is over-engineered because it's not a complicated component and didn't take extra time to build so I don't mind too much.  I could have done things like assumed button and link components instead of using render props, that definitely occurred to me.

2022-07-20 12:54 UTC, duncan-truss commented on src/components/Customer/PPM/Closeout/ReviewItems/ReviewItems.stories.jsx
> +        { id: 'description', label: 'Description:', value: 'Training manuals' },
Thank you, I built this before the format functions and didn't go back to fix them.

2022-07-20 12:55 UTC, duncan-truss commented on src/pages/MyMove/PPM/Closeout/Review/Review.jsx
> +  });
Good point I think we must have something similar for PPMs somewhere

2022-07-20 18:05 UTC, felipe-lee commented on src/components/Customer/PPM/Closeout/ReviewItems/ReviewItems.jsx
> +const ReviewItems = ({ className, heading, renderAddButton, contents, emptyMessage }) => {
Oof, I did not realize we had so many `dl` components...I think having a generic one like the one you wrote would be great and potentially help to minimize that in the future, but doing that is beyond the scope of the current ticket.

2022-07-20 19:56 UTC, felipe-lee approved these changes
Given the AC changes we discussed in sprint planning, I'm good with this now (was mainly waiting on the home page routing and cypress test changes)

2022-07-20 22:56 UTC, scarequotes requested changes
Looks good, but I noticed a couple of things: 

In the info about each trip, the field label for `Trip weight` should have a lowercase `w` — `Trip weight`, not `Trip Weight`
![Screen Shot 2022-07-20 at 3 50 46 PM](https://user-images.githubusercontent.com/30428256/180096012-c4e71e32-952c-4802-9913-5c62248171f0.png)

In the mobile view, the button to add more weight should wrap to a new line. 

Here's what I'm seeing:
![Screen Shot 2022-07-20 at 3 53 03 PM](https://user-images.githubusercontent.com/30428256/180096133-bdadb4b9-f5a8-4bb4-97b1-a40d054aa622.png)

Here's the [look in Zeplin](https://zpl.io/W4vYroK)
![Screen Shot 2022-07-20 at 3 53 51 PM](https://user-images.githubusercontent.com/30428256/180096182-d803c1fe-4e54-4218-a2cb-32ff64ae02a8.png)

2022-07-20 23:18 UTC, duncan-truss commented
> Looks good, but I noticed a couple of things:
> 
> In the info about each trip, the field label for `Trip weight` should have a lowercase `w` — `Trip weight`, not `Trip Weight` ![Screen Shot 2022-07-20 at 3 50 46 PM](https://user-images.githubusercontent.com/30428256/180096012-c4e71e32-952c-4802-9913-5c62248171f0.png)
> 
> In the mobile view, the button to add more weight should wrap to a new line.
> 
> Here's what I'm seeing: ![Screen Shot 2022-07-20 at 3 53 03 PM](https://user-images.githubusercontent.com/30428256/180096133-bdadb4b9-f5a8-4bb4-97b1-a40d054aa622.png)
> 
> Here's the [look in Zeplin](https://zpl.io/W4vYroK) ![Screen Shot 2022-07-20 at 3 53 51 PM](https://user-images.githubusercontent.com/30428256/180096182-d803c1fe-4e54-4218-a2cb-32ff64ae02a8.png)

@scarequotes Thanks I'll fix the capitalization.

Our mobile breakpoint is set at less than 375px so you will need to resize to below that to see the specific layout changes.  Maybe we should make it to include 375px because that's what the iPhone SE setting is but that's not what it's currently set to.

2022-07-21 16:32 UTC, scarequotes commented on src/pages/MyMove/PPM/Closeout/Review/Review.jsx
> +          <h3>Delete this?</h3>
Good q, but we decided to embrace vagueness for simplicity at launch.

2022-07-21 16:36 UTC, scarequotes approved these changes
Thanks! Whether you changed something or my browser did, the breakpoints now look right in the same view I had yesterday, so I don't know what's up with that but 👍

2022-07-21 16:42 UTC, merged