MB-13424 QAE can view shipments when editing/creating a counseling evaluation report
transcom/mymove pull request #9103
Opened 2022-08-23 15:18 UTC by Ryan-Koch

… visible for counseling evaluation report form.

## [Jira ticket](tbd) for this change

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Setup to Run Your Code

<details>
<summary>💻 You will need to use three separate terminals to test this locally.</summary>

##### Terminal 1

Start the Storybook locally.

```sh
make storybook
```

##### Terminal 2

Start the UI locally.

```sh
make client_run
```

##### Terminal 3

Start the Go server locally.

```sh
make server_run
```

</details>

### Additional steps

1. Access the
2. Login as a
3.

## Verification Steps for Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Request review from a member of a different team.
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Frontend

- [ ] User facing changes have been reviewed by design.
- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
- [ ] There are no new console errors in the browser devtools
- [ ] There are no new console errors in the test output
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide#logging)
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide/#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#zero-downtime-migrations)
- [ ] Have been communicated to #g-database
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#secure-migrations)

## Screenshots

2022-08-25 15:24 UTC, AnnaGingle requested changes
Comments in [slack ](https://ustcdp3.slack.com/archives/CP4979J0G/p1661441061285789?thread_ts=1661437392.424369&cid=CP4979J0G)

2022-08-29 21:43 UTC, PDickeyTruss commented on src/components/Office/EvaluationReportShipmentDisplay/EvaluationReportShipmentDisplay.module.scss
> +    @include u-padding-top(12px);
Suggestion: This could probably just be `u-padding-top(1);`

2022-08-29 21:46 UTC, PDickeyTruss approved these changes
LGTM, display of shipments looks good and only one very minor suggestion code-wise.

2022-08-30 15:22 UTC, cosburn approved these changes
Approving with the note that we filed a bug to fix some alignment on the shipment card in the future.

2022-08-30 15:53 UTC, merged