MB-13351 Update ppm shipments and signed certification tables
transcom/mymove pull request #9118
Opened 2022-08-26 15:57 UTC by pearl-truss

## [Jira ticket](https://dp3.atlassian.net/browse/MB-13351) for this change

## Summary
Migrations in this PR:

- The database can record the customer’s W-2 address
- The address has a relationship with the PPM shipment
- The database can record the calculated final incentive
- Signed certifications table has relationship with the PPM Shipment

## Setup to Run Your Code

This is a task ticket with nothing visual to review except the code itself

2022-08-26 15:59 UTC, pearl-truss commented on pkg/models/signed_certification.go
> +	PpmID                    *uuid.UUID               `json:"ppm_id" db:"ppm_id"`
Is the casing here correct?

2022-08-26 16:00 UTC, pearl-truss commented on pkg/models/signed_certification.go
>  func FetchSignedCertificationsPPMPayment(db *pop.Connection, session *auth.Session, id uuid.UUID) (*SignedCertification, error) {
I added this comment as a placeholder. I believe to be able to reuse this model for PPMs this function will need to be updated to pass in a ppm shipment id

2022-08-26 16:25 UTC, rogeruiz commented on pkg/models/signed_certification.go
> +	PpmID                    *uuid.UUID               `json:"ppm_id" db:"ppm_id"`
from the looks of the other files, I believe it could be either `PPMID` but that certainly doesn't read as easily as `PpmID`.

Looking at `payloads/model_to_payload.go` there's references to `PPMType` and `PpmType`. So I'd say for readability, this is the way to go 👍🏽

2022-08-26 16:27 UTC, rogeruiz commented on pkg/models/signed_certification.go
>  func FetchSignedCertificationsPPMPayment(db *pop.Connection, session *auth.Session, id uuid.UUID) (*SignedCertification, error) {
Do you think we should have a Jira ticket around this to remove it? I like the idea of having the comment, but I'm wondering it there's a better way to bubble up the visibility on this. The comment's good enough though 💯

2022-08-26 16:32 UTC, rogeruiz commented
I'm going to set this up so I can see the Swagger documentation here to test something. but this looks good so far @pearl-truss. I may be slow on my review but if others get to it first that's fine too 😃

2022-08-26 17:41 UTC, rogeruiz requested changes
❌ This PR needs changes around descriptions for `finalIncentives` and `ppm_id` defined in a couple of places. Great work on this @pearl-truss. I don't see any technical issues here. From the documentation perspective, I do see some things that would really be great to add here even though our Swagger documentation does not currently meet the expectations I'm trying to shift our API docs to. 

> 📣 **Please feel free to dismiss this review**. I'm adding it as request changes so aid discussion on the topic, but I'm not trying to dictate here.

Can we get a description section here that describes this a bit better? I'm not familiar with this outcome at all, so I'm not sure what **Final Incentive** is here and _I personally think_ it'd be good for the project to have better descriptive text for new definitions in our API. I pulled what **Final Incentive** is from our Slack history in DP3 and from our Migration files that added the column.

Also, I'd like to suggest adding a new `final_incentive.yaml` file in our `swagger-def/definitions/` directory to centralize where this definition is being defined since I'm suggestion adding a `description: >` stanza to the Yaml and my current flow has me suggesting it in three different places across `ghc.yaml` and `internal.yaml`.

I've also added some suggestions to `ppm_id` definitions and since there's two in the `internal.yaml` file, I think it's a good idea to centralize this inside of `swagger-def/definitions/` as well.

2022-08-26 17:41 UTC, rogeruiz commented on swagger-def/internal.yaml
> +        x-omitempty: false
```suggestion
      finalIncentive:
        description: >
          The final calculated incentive for the PPM shipment. This does not include **SIT** as it is a reimbursement.
        type: integer
        format: cents
        x-nullable: true
        x-omitempty: false
```

2022-08-26 17:41 UTC, rogeruiz commented on swagger-def/ghc.yaml
> +        x-omitempty: false
```suggestion
      finalIncentive:
        description: >
          The final calculated incentive for the PPM shipment. This does not include **SIT** as it is a reimbursement.
        type: integer
        format: cents
        x-nullable: true
        x-omitempty: false
```

2022-08-26 17:41 UTC, rogeruiz commented on swagger-def/definitions/PPMShipment.yaml
> +    x-omitempty: false
```suggestion
      finalIncentive:
        description: >
          The final calculated incentive for the PPM shipment. This does not include **SIT** as it is a reimbursement.
        type: integer
        format: cents
        x-nullable: true
        x-omitempty: false
```

2022-08-26 17:41 UTC, rogeruiz commented on swagger-def/internal.yaml
> +        x-nullable: true
Similar to Final Incentive, I've borrowed this from our database comments on the table.

```suggestion
      ppm_id:
        description: >
          The PPM Shipment ID to associate with the assigned certificate.
        type: string
        format: uuid
        example: c56a4180-65aa-42ec-a945-5fd21dec0538
        x-nullable: true
```

2022-08-26 17:41 UTC, rogeruiz commented on swagger-def/internal.yaml
> +        x-nullable: true
```suggestion
      ppm_id:
        description: >
          The PPM Shipment ID to associate with the assigned certificate.
        type: string
        format: uuid
        example: c56a4180-65aa-42ec-a945-5fd21dec0538
        x-nullable: true
```

2022-08-26 17:42 UTC, rogeruiz commented
Also, you'll notice in my suggestions in my review that I'm using Markdown in the `description: >` stanza and I tested this locally with our Docusaurus repository to ensure that Markdown does get processed correctly in our documentation.

![Captura de Pantalla 2022-08-26 a la(s) 1 41 46 p m](https://user-images.githubusercontent.com/706004/186961990-336b73fe-6c19-4c21-9b15-f72a2b4bdc8e.png)

2022-08-26 19:20 UTC, pearl-truss commented
@rogeruiz thanks for the review! I believe all requested changes have been made

2022-08-26 19:32 UTC, rogeruiz approved these changes
lgtm 🌈 

Great work on this @pearl-truss!

2022-08-26 20:03 UTC, rogeruiz commented
Looks like the `pkg/gen` code I mentioned above wasn't committed to the branch. 👀

2022-08-26 20:20 UTC, pearl-truss commented
> Looks like the `pkg/gen` code I mentioned above wasn't committed to the branch.
> 
> 👀 https://app.circleci.com/pipelines/github/transcom/mymove/44762/workflows/b490be6a-f23f-4e4f-a2f8-38fd5cd47a17/jobs/708646/parallel-runs/0/steps/0-106
> 
> I believe the fix is to run
> 
> ```
> make swagger_generate server_generate
> ```



> Looks like the `pkg/gen` code I mentioned above wasn't committed to the branch.
> 
> 👀 https://app.circleci.com/pipelines/github/transcom/mymove/44762/workflows/b490be6a-f23f-4e4f-a2f8-38fd5cd47a17/jobs/708646/parallel-runs/0/steps/0-106
> 
> I believe the fix is to run
> 
> ```
> make swagger_generate server_generate
> ```

👍 I will push a fix for that as soon as I resolve swagger conversion issues in the payload_to_model and model_to_payload files

2022-08-29 21:42 UTC, duncan-truss commented on migrations/app/schema/20220824133409_add_w2_address_final_incentive_to_ppm_shipment.up.sql
> +COMMENT ON COLUMN ppm_shipments.w2_address_id IS 'Customer address to receive their W2 tax form';
When I read this it made it seem like we were managing where they would get their W2 sent.  In the Zeplin mock they ask "What is the address on your W2?" https://app.zeplin.io/project/625896e702018f8ff82451c0/screen/625897c6c3a6839268f33d89

2022-08-29 21:56 UTC, duncan-truss commented on pkg/models/ppm_shipment.go
>  	HasReceivedAdvance             *bool                `json:"has_received_advance" db:"has_received_advance"`
You could also add a placeholder association here for the signed certifications to make sure it's wired up:

```go
SignedCertifications SignedCertifications`has_many:"signed_certifications" fk_id:"ppm_id" order_by:"created_at desc"`
```

2022-08-29 22:00 UTC, duncan-truss commented on swagger-def/definitions/FinalIncentive.yaml
> +x-omitempty: false
I think this will also be a read-only property set by the system not modified by any API.

2022-08-29 22:03 UTC, duncan-truss commented on swagger-def/ghc.yaml
> +      finalIncentive:
I am pretty sure this won't get set by the office user but will just be the value of running the PPM incentive pricer on the actual values during closeout instead of the estimated/expected values during the initial incentive.

2022-08-30 17:54 UTC, pearl-truss commented on migrations/app/schema/20220824133409_add_w2_address_final_incentive_to_ppm_shipment.up.sql
> +COMMENT ON COLUMN ppm_shipments.w2_address_id IS 'Customer address to receive their W2 tax form';
I switched to say, "Address for where a customer received their W2 tax form"

2022-08-30 20:50 UTC, duncan-truss approved these changes

2022-08-30 20:59 UTC, felipe-lee commented on migrations/app/schema/20220826142534_associate_signed_certifications_with_ppms.up.sql
> +    ADD COLUMN ppm_id uuid CONSTRAINT ppm_id_fkey REFERENCES ppm_shipments (id);
**question**: I looked at the DDL for this table and noticed that signature is required but we aren't asking for signature on the page. Are we going to re-use their signature from when they submitted the move? Or modify this table to allow signature to be nullable?

```abbreviated signed_certifications DDL
-- auto-generated definition
create table signed_certifications
(
    id                          uuid      not null
        primary key,
    submitting_user_id          uuid      not null
        references users,
    move_id                     uuid      not null
        constraint signed_certifications_moves_id_fk
            references moves,
    certification_text          text      not null,
    signature                   text      not null,
    date                        timestamp not null,
    created_at                  timestamp not null,
    updated_at                  timestamp not null,
    personally_procured_move_id uuid
        references personally_procured_moves,
    certification_type          text,
    ppm_id                      uuid
        constraint ppm_id_fkey
            references ppm_shipments
);
```

2022-08-31 14:35 UTC, pearl-truss commented on migrations/app/schema/20220826142534_associate_signed_certifications_with_ppms.up.sql
> +    ADD COLUMN ppm_id uuid CONSTRAINT ppm_id_fkey REFERENCES ppm_shipments (id);
I think using the signature from the move makes the most sense since we probably don't want to allow nullable signatures for this table across the board. I made a note of this in https://dp3.atlassian.net/browse/MB-13354

2022-08-31 14:37 UTC, pearl-truss commented on migrations/app/schema/20220826142534_associate_signed_certifications_with_ppms.up.sql
> +    ADD COLUMN ppm_id uuid CONSTRAINT ppm_id_fkey REFERENCES ppm_shipments (id);
@felipe-lee @duncan-truss do you have any thoughts on this?

2022-08-31 14:59 UTC, duncan-truss commented on migrations/app/schema/20220826142534_associate_signed_certifications_with_ppms.up.sql
> +    ADD COLUMN ppm_id uuid CONSTRAINT ppm_id_fkey REFERENCES ppm_shipments (id);
That's a good question Felipe, I think we could weigh our options in the follow up PRs.  We could also insert something like "N/A" honestly.

I'm thinking more about the certification_text and how we may need to re-prompt if it has changed.  I think for move submission they have the frontend send the whole block of certification text to the API kind of naively.

2022-08-31 16:58 UTC, felipe-lee commented on migrations/app/schema/20220826142534_associate_signed_certifications_with_ppms.up.sql
> +    ADD COLUMN ppm_id uuid CONSTRAINT ppm_id_fkey REFERENCES ppm_shipments (id);
Yeah I'd be fine with those options. I think we'll want to verify with Danny, but agree we can do that in future tickets. Thanks for noting it in that ticket Pearl!

2022-09-01 17:11 UTC, merged