Scottmries/mb 12189 setup fe fake data gen factories and duty location
transcom/mymove pull request #9233
Opened 2022-09-22 18:31 UTC by scottmries

## [Jira ticket](tbd) for this change

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Setup to Run Your Code

<details>
<summary>💻 You will need to use three separate terminals to test this locally.</summary>

##### Terminal 1

Start the Storybook locally.

```sh
make storybook
```

##### Terminal 2

Start the UI locally.

```sh
make client_run
```

##### Terminal 3

Start the Go server locally.

```sh
make server_run
```

</details>

### Additional steps

1. Access the
2. Login as a
3.

## Verification Steps for Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Request review from a member of a different team.
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Frontend

- [ ] User facing changes have been reviewed by design.
- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
- [ ] There are no new console errors in the browser devtools
- [ ] There are no new console errors in the test output
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide#logging)
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide/#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#zero-downtime-migrations)
- [ ] Have been communicated to #g-database
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#secure-migrations)

## Screenshots

2022-09-23 14:02 UTC, ronaktruss commented on src/utils/test/factories/README.md
> +
While this can be inferred from reading the description of all three options, It might be helpful to have an explicit sentence indicating that the precedence is overrides < traits < lazy overrides.

2022-09-23 14:02 UTC, ronaktruss commented on src/utils/test/factories/README.md
> +```
We can probably get rid of these lines and update the title since we are not using swagger codegen and instead using js-yaml.

2022-09-23 18:29 UTC, kylehilltruss requested changes

2022-09-23 18:29 UTC, kylehilltruss commented on src/utils/test/factories/base.js
> +    traits,
The `BASE_FIELDS` properties aren't used anywhere else in this file. Do we want to worry about consistency w/r/t using the exported property names here? (`{ fields: ` instead of `{ [BASE_FIELDS.FIELDS]: ` for instance) Or is this just an optional, use-if-you-want setup?

2022-09-23 18:29 UTC, kylehilltruss commented on src/utils/test/factories/helpers.js
> +export default {};
Why are we exporting a default empty object? (It might make sense to export default an object containing all of the individually exported helper functions.)

2022-09-23 18:29 UTC, kylehilltruss commented on src/utils/test/factories/transportationOffice.js
> +    const numberOfLines = Math.random(4);
`Math.random` doesn't accept any parameters. What's the 4 doing?

2022-09-23 18:29 UTC, kylehilltruss commented on src/utils/test/factories/helpers.js
> +export const placeNameHelper = (f) => f.lorem.words(Math.random(4) + 1);
See below for comment on Math.random accepting params

2022-09-23 18:29 UTC, kylehilltruss commented on src/utils/test/factories/discovery/factory.js
> +  TEST_TRAIT: 'testTrait',
I hate to ask "what is this" in a code review, but, well... the contents of this file feels like testing/discovery code, and not something that we should commit to the project's code base (at the very least, not without explanatory comments).

2022-09-23 20:09 UTC, scottmries commented on src/components/Customer/FactoryTest/FactoryTest.test.jsx
> +import { BASE_FIELDS } from 'utils/test/factories/base';
Updated with the new filename and path.

2022-09-23 20:09 UTC, scottmries commented on src/utils/test/factories/base.js
> +    traits,
Updated to use constants here too.

2022-09-23 20:10 UTC, scottmries commented on src/utils/test/factories/helpers.js
> +export default {};
Fixed.

2022-09-23 20:12 UTC, scottmries commented on src/utils/test/factories/transportationOffice.js
> +    const numberOfLines = Math.random(4);
Good eye, I don't know why I think this method works this way. This and the other instances are fixed.

2022-09-23 20:14 UTC, scottmries commented on src/utils/test/factories/discovery/factory.js
> +  TEST_TRAIT: 'testTrait',
This is set up to work exactly the way the fields do, so user of the factory can just look up the name of the trait in the IDE. Noted that the trait test was not using this constant, which I fixed.

2022-09-23 22:57 UTC, YanZ777 reviewed
Aside from my questions and suggestions, the code is looking good!

2022-09-23 22:57 UTC, YanZ777 commented on src/utils/test/factories/address.js
> +    [ADDRESS_FIELDS.COUNTRY]: 'US', // Likely change once we support more than just OCONUS moves.
**suggestion:** Could you make a Jira ticket and put the ticket number in a comment here too?

2022-09-23 22:57 UTC, YanZ777 commented on src/utils/test/factories/README.md
> +# Factories
**question:** Is this intended to live here? Should it live inside the [MilMove developer documentation](https://transcom.github.io/mymove-docs/) instead?

2022-09-23 22:57 UTC, YanZ777 commented on src/utils/test/factories/base.js
> +let internalSpec = null;
**question:** Do `internalSpec` (and similarly, `ghcSpec` below) need to be declared outside their respective functions? I'm not seeing where else they're being used besides those places.

2022-09-23 23:53 UTC, felipe-lee reviewed
Thank you for continuing the work on this!

I'm still looking through this, but I've got a few questions, comments, etc. I'll continue looking on Monday!

2022-09-23 23:53 UTC, felipe-lee commented on src/utils/test/factories/README.md
> +# Factories
**issue**: Yeah, I think it should live in the mm dev docs like Yan said. Having this doc here is nice in that it lives next to where people will use the code, but it deviates from how the rest of our docs work (other than the top level readme, which tbh should also probably be migrated at some point).

2022-09-23 23:53 UTC, felipe-lee commented on src/utils/test/factories/README.md
> +Create and export a const called `{OBJECT_}FIELDS`. This constant should be an object whose keys are CAPITAL_SNAKE_CASE and whose values are the actual, camelCase names of the fields, e.g. `MY_FIELD:
**thought**: While it's true that it isn't strictly necessary, we should probably decide if we do want to do this, and if so, then we should say to do it. I feel like our docs saying something is optional will mean we won't be consistent. Maybe it won't be a big issue if we aren't consistent, but I think the docs should probably not leave that open.

2022-09-23 23:53 UTC, felipe-lee commented on src/utils/test/factories/README.md
> +Create and export a const called `{OBJECT_}FIELDS`. This constant should be an object whose keys are CAPITAL_SNAKE_CASE and whose values are the actual, camelCase names of the fields, e.g. `MY_FIELD:
**suggestion**: I think it might be good to show an example that is more ironed out than the inline one we have currently. Especially once this doc gets move to be in our dedicated docs repo.

2022-09-23 23:53 UTC, felipe-lee commented on src/utils/test/factories/README.md
> +  - the spread params: `...params`.
**suggestion**: I think an example of this, even as a simple case, would be great to have in the docs.

2022-09-23 23:53 UTC, felipe-lee commented on src/utils/test/factories/README.md
> +will always set the value of `field` to `'my value'` by default (i.e., unless)
**suggestion**: the `i.e.` bit at the end is a bit confusing to me so I'd suggest removing it, but maybe I'm missing something.

```suggestion
will always set the value of `field` to `'my value'` by default.
```

2022-09-23 23:53 UTC, felipe-lee commented on src/utils/test/factories/README.md
> +# Factories
**praise**: Thanks for getting the docs started for this!

2022-09-23 23:53 UTC, felipe-lee commented on src/utils/test/factories/README.md
> +# Factories
**question**: are these docs meant to cover the work for https://dp3.atlassian.net/browse/MB-12838? Or are they more of a baseline and when we get to that ticket, we'll iron things out more and add more details/examples? I ask to know how much to request in terms of details and such vs only focusing on making sure things make sense with the knowledge that we'll add more later.

2022-09-23 23:56 UTC, felipe-lee commented on src/utils/test/factories/base.js
> +let internalSpec = null;
**thought**: good question, I think the way I'd written this locally at first did require them to be defined at a top level, but then I switched to the `get<api>Spec` functions and so they do seem to remove the need for the declaration at this level. Thanks for calling that out.

2022-09-26 14:13 UTC, scottmries commented on src/utils/test/factories/address.js
> +    [ADDRESS_FIELDS.COUNTRY]: 'US', // Likely change once we support more than just OCONUS moves.
I created the ticket and added the number to the comment. It's [here](https://dp3.atlassian.net/browse/MB-13996), for the record.

2022-09-26 14:35 UTC, scottmries commented on src/utils/test/factories/README.md
> +# Factories
I removed this file from this repo and moved it to a PR in the [docs](https://github.com/transcom/mymove-docs/pull/214). I'll make any remaining changes in this PR to the code in that repo, and then maybe we move docs discussion there?

2022-09-26 14:46 UTC, scottmries commented on src/utils/test/factories/README.md
> +# Factories
@felipe-lee I had only really intended these as baseline for anyone coming into this fresh, but I'm assuming we'll also want to back-fill each of [these](https://github.com/transcom/mymove-docs/blob/main/docs/frontend/testing/writing-frontend-tests-for-milmove.md#address). I'll include a request to change addresses in my PR in the docs.

2022-09-26 15:19 UTC, scottmries commented on src/utils/test/factories/base.js
> +let internalSpec = null;
thought: I refactored these to be just aliases of their respective calls. I don't believe the falsy check is necessary anymore.

2022-09-26 18:41 UTC, felipe-lee commented on src/utils/test/factories/README.md
> +# Factories
Ah good catch, I'm not sure I'd seen those, or if I had, I'd forgotten, but they would be good to swap out.

2022-09-26 19:05 UTC, scottmries commented on src/utils/test/factories/README.md
> +Create and export a const called `{OBJECT_}FIELDS`. This constant should be an object whose keys are CAPITAL_SNAKE_CASE and whose values are the actual, camelCase names of the fields, e.g. `MY_FIELD:
I removed the "strictly necessary" language and added an example over in the [docs PR](https://github.com/transcom/mymove-docs/pull/214).

2022-09-26 19:07 UTC, scottmries commented on src/utils/test/factories/README.md
> +will always set the value of `field` to `'my value'` by default (i.e., unless)
I removed this over in the [docs PR](https://github.com/transcom/mymove-docs/pull/214).

2022-09-26 19:08 UTC, scottmries commented on src/utils/test/factories/README.md
> +  - the spread params: `...params`.
I added an example in the [docs PR](https://github.com/transcom/mymove-docs/pull/214).

2022-09-26 19:20 UTC, felipe-lee commented on src/utils/test/factories/base.js
> +          delete overrides[field];
**question**: Should we be deleting the field from the override in every section? If we do, is there a reason to continue passing the overrides to the builder down on line 110?

2022-09-26 19:23 UTC, felipe-lee commented on src/utils/test/factories/base.js
> +const applyOverrides = (object, overrides) => {
**suggestion**: can you add docstrings to these functions? Especially to make it easier to understand the different things `object` can be.

2022-09-26 19:25 UTC, felipe-lee commented on src/utils/test/factories/discovery/factory.js
> +import { perBuild } from '@jackfranklin/test-data-bot';
**question**: are the files in the `discovery` dir meant to be examples of how to make factories? Or were they meant to be removed now that this pr is trying to be merged? If we do want to keep them around, it might be good to add a comment or something stating they're mainly examples so people don't delete them or think they're something else.

2022-09-26 19:34 UTC, felipe-lee commented on src/utils/test/factories/address.js
> +};
**suggestion**: Can you add the `ONLY_BASIC_ADDRESS` trait from the other pr? https://github.com/transcom/mymove/pull/9142/files#diff-b25a459b02fa21a858ddd1db0f12409d125b99c6b1c983d2e107845cf82f7162R39-R47

Mainly since in that one it did come up as one that can be useful in tests. The `ONLY_REQUIRED_FIELDS` didn't get used so that one can get left out, though we may eventually add it.

2022-09-26 19:38 UTC, scottmries commented on src/utils/test/factories/base.js
> +const loadSpec = (fileName) => {
This function uses the file system and is called in two locations, within `getInternalSpec` and `getGHCSpec` just below. In both cases, it's called with a hardcoded path, and it's not exported, so it cannot be called with an arbitrary path.

2022-09-26 19:45 UTC, scottmries commented on src/utils/test/factories/base.js
> +    const formattedField = _.camelCase(field);
Oh makes sense, I didn't realize we were phasing out lodash. I'll push up a fix.

2022-09-27 19:33 UTC, scottmries commented on src/utils/test/factories/base.js
> +          delete overrides[field];
This was a really good catch. I pushed up a refactor to this function that doesn't need to delete these overrides (which seemed odd), and doesn't pass them into the builder. I think the function is much easier to understand now.
The issue was that `preBuild`s actually become objects with a `call` function, and we weren't properly handling that case.

2022-09-27 20:33 UTC, scottmries commented on src/utils/test/factories/base.js
> +const applyOverrides = (object, overrides) => {
That's a good suggestion. It's definitely hard to get a handle on how this works by just glancing over it. 
I pushed up a commit with docstrings.

2022-09-27 20:39 UTC, scottmries commented on src/utils/test/factories/discovery/factory.js
> +import { perBuild } from '@jackfranklin/test-data-bot';
I think we should keep them here to make sure the tests run and they work as we expect. I added a comment to the top of each file.

2022-09-27 20:46 UTC, scottmries commented on src/utils/test/factories/address.js
> +};
Done!

2022-09-28 15:56 UTC, kylehilltruss approved these changes

2022-09-29 16:02 UTC, merged