MB-12436 - Display deleted values in move history details
transcom/mymove pull request #9308
Opened 2022-10-04 23:03 UTC by michaelvaldes-truss

## [Jira ticket](https://dp3.atlassian.net/browse/MB-12436) for this change

## Summary

In the move history details, historyrecord.changedValue values that are null/empty/missing are filtered out from display so that superfluous information isn't shown to the user. This PR should begin to display some exceptions to this rule, in which a changedValue that is empty _is_ displayed if it also exists as an oldValue -- in other words, when the value has ostensibly been deleted (as in the case of deleted Services Counselor remarks).

## Setup to Run Your Code

<details>
<summary>💻 You will need to use two separate terminals to test this locally.</summary>

##### Terminal 1

Start the UI locally.

```sh
make client_run
```

##### Terminal 2

Start the Go server locally.

```sh
make server_run
```

</details>

### Additional steps

1. Access the office app as a services counselor
2. Access the moved details page for any move
3. Edit any shipment, add remarks, and hit `save`
4. Edit the shipment again, delete the remarks, and hit `save`
5. Navigate to the move history table
6. Ensure that the move history record corresponding to the deletion of the remarks shows the necessary information

## Verification Steps for Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Request review from a member of a different team.
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Frontend

- [ ] User facing changes have been reviewed by design.
- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
- [ ] There are no new console errors in the browser devtools
- [ ] There are no new console errors in the test output
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

## Screenshots
<img width="1306" alt="image" src="https://user-images.githubusercontent.com/97245917/193946305-bf15090f-f717-4f59-9cd2-6104965c8a07.png">

2022-10-05 17:36 UTC, juliemoon requested changes
@michaelvaldes-truss This looks great! The functionality works as expected. One quick thing I noticed is the **dash -** isn't showing up to visually indicate the deleted field. There is a deleted field usecase zeplin file here: https://app.zeplin.io/project/6216b3c50e72098ae7b8e72e/screen/6221000685c7845a760577d8

2022-10-05 19:35 UTC, YanZ777 commented on src/pages/Office/MoveHistory/LabeledDetails.jsx
> +      (dbField in changedValuesToUse && historyRecord.oldValues && dbField in historyRecord.oldValues)
**suggestion:** Can we just use `[]` operator for these checks instead of `in`?

```suggestion
      (changedValuesToUse[dbField] && historyRecord.oldValues && historyRecord.oldValues[dbField])
```

2022-10-06 16:57 UTC, michaelvaldes-truss commented on src/pages/Office/MoveHistory/LabeledDetails.jsx
> +      (dbField in changedValuesToUse && historyRecord.oldValues && dbField in historyRecord.oldValues)
This is an interesting question! The `in` operator will check if the key exists, while the `[]` operator will check if the key exists _and_ the value is not nullish. This ticket is about keys that exist and whose values are nullish in the changedValues, while the same keys exist with not-nullish values in the oldValues. I think that means we actually have to use `in` for the changedValues and `[]` for the oldValues.

2022-10-06 19:56 UTC, juliemoon approved these changes
Thanks for making this update! It looks great
<img width="1713" alt="Screen Shot 2022-10-06 at 3 55 59 PM" src="https://user-images.githubusercontent.com/16272040/194406504-a7816f41-938c-4ee7-bf8b-b925dee19d1d.png">

2022-10-06 22:42 UTC, YanZ777 commented on src/pages/Office/MoveHistory/LabeledDetails.jsx
> +      (dbField in changedValuesToUse && historyRecord.oldValues && dbField in historyRecord.oldValues)
**praise:** Leave it as is! Thanks for the explanation!

*suggestion (non-blocking):** If you could add why in is being used to the comment above this code, that would be awesome.

2022-10-07 16:07 UTC, michaelvaldes-truss commented
@Mergifyio rebase

2022-10-07 20:01 UTC, merged