Ruizaj mb 11217 office users can see order info submitted by customers
transcom/mymove pull request #9331
Opened 2022-10-11 23:53 UTC by ruizajtruss

## [Jira ticket](tbd) for this change

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Setup to Run Your Code

<details>
<summary>💻 You will need to use three separate terminals to test this locally.</summary>

##### Terminal 1

Start the Storybook locally.

```sh
make storybook
```

##### Terminal 2

Start the UI locally.

```sh
make client_run
```

##### Terminal 3

Start the Go server locally.

```sh
make server_run
```

</details>

### Additional steps

1. Access the
2. Login as a
3.

## Verification Steps for Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Request review from a member of a different team.
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Frontend

- [ ] User facing changes have been reviewed by design.
- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
- [ ] There are no new console errors in the browser devtools
- [ ] There are no new console errors in the test output
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide#logging)
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide/#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#zero-downtime-migrations)
- [ ] Have been communicated to #g-database
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#secure-migrations)

## Screenshots

2022-10-13 22:10 UTC, michaelvaldes-truss requested changes

2022-10-13 22:10 UTC, michaelvaldes-truss commented on src/constants/MoveHistory/EventTemplates/CreateOrders/createEntitlements.test.jsx
> +    it.each([
**praise:** nice table-driven testing!

2022-10-13 22:10 UTC, michaelvaldes-truss commented on src/pages/Office/MoveHistory/LabeledDetails.jsx
> +    (displayName === fieldMappings.dependents_authorized || displayName === fieldMappings.has_dependents) &&
**suggestion:** I think it might make more sense to move this to the specific templates so we can keep from adding more business logic to the LabeledDetails component

2022-10-13 22:12 UTC, michaelvaldes-truss commented
@ruizajtruss I'm going to wait to merge #9353 until this PR is merged due to anticipated merge conflicts

2022-10-13 22:13 UTC, michaelvaldes-truss commented on src/pages/Office/MoveHistory/LabeledDetails.jsx
> +    (displayName === fieldMappings.dependents_authorized || displayName === fieldMappings.has_dependents) &&
You can check out the changes done to `updateOrder.jsx` in #9353 for an example of that

2022-10-13 22:37 UTC, ruizajtruss commented on src/pages/Office/MoveHistory/LabeledDetails.jsx
> +    (displayName === fieldMappings.dependents_authorized || displayName === fieldMappings.has_dependents) &&
Agreed, I thought it felt a little bulky when I was typing it into this file

2022-10-14 15:54 UTC, michaelvaldes-truss commented on src/constants/MoveHistory/EventTemplates/CreateOrders/createOrders.jsx
> +        has_dependents: changedValues.has_dependents === true ? 'Yes' : 'No',
**suggestion:** what would this do to the changed values if they don't include a change to the `has_dependents` field? Imo we can probably omit this, since I think showing "true/false" is probably okay anyway.

2022-10-14 21:02 UTC, ruizajtruss commented on src/constants/MoveHistory/EventTemplates/CreateOrders/createEntitlements.test.jsx
> +    it.each([
tyty 🥳

2022-10-14 21:03 UTC, ruizajtruss commented on src/constants/MoveHistory/EventTemplates/CreateOrders/createEntitlements.jsx
> +    return <LabeledDetails historyRecord={historyRecord} getDetailsLabeledDetails={getDetailsLabeledDetails} />;
Done 🎉

2022-10-14 21:10 UTC, ruizajtruss commented on src/constants/MoveHistory/EventTemplates/CreateOrders/createOrders.jsx
> +        has_dependents: changedValues.has_dependents === true ? 'Yes' : 'No',
The acceptance criteria requires `Yes` or `No` be displayed rather than their boolean values which is why I've included that bit of logic. The dependents field in the form that affects this is a required field from what I can see (form doesn't let you continue without selecting yes or no) so it not popping up in changedValues shouldn't be an issue I would imagine. However one can't be too safe so I now included an optional chain operator which should handle it incase it didn't exist for some reason.

2022-10-17 16:02 UTC, michaelvaldes-truss approved these changes
lgtm, works as expected. Nice job refactoring it per ADR 74!

2022-10-17 17:23 UTC, merged