MB-11805 display order updates
transcom/mymove pull request #9353
Opened 2022-10-13 16:50 UTC by michaelvaldes-truss

## [Jira ticket](https://dp3.atlassian.net/browse/MB-11805) for this change

## Summary

Most of the AC for this story were already covered, but now the `has_dependents` field of the orders table is captured in the move history table. Please note that the display text 'Dependents included' matches the text found on the orders page when the option is selected by the user.
Also please note that this move history template was refactored as per [ADR 74](https://transcom.github.io/mymove-docs/docs/adrs/move-history-details-refactor).

## Setup to Run Your Code

<details>
<summary>💻 You will need to use three separate terminals to test this locally.</summary>

##### Terminal 1

Start the Storybook locally.

```sh
make storybook
```

##### Terminal 2

Start the UI locally.

```sh
make client_run
```

##### Terminal 3

Start the Go server locally.

```sh
make server_run
```

</details>

### Additional steps

1. Log in to the customer app as a user that has already submitted a move; note the move code for later
2. Navigate to the landing page and click 'Review your request'
3. Click 'Edit' on the orders card
4. Update your orders; change the currently selected option for "Dependents included"
5. Log into the office app as a TXO
6. Navigate to the move history tab of the move which has the move code noted in step 1
7. Verify that the move history has a properly-formatted entry for the orders update

## Verification Steps for Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Request review from a member of a different team.
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Frontend

- [ ] User facing changes have been reviewed by design.
- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
- [ ] There are no new console errors in the browser devtools
- [ ] There are no new console errors in the test output
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

## Screenshots
<img width="1321" alt="image" src="https://user-images.githubusercontent.com/97245917/195657268-a8e3f72e-e49c-490a-8709-b7815738205b.png">

2022-10-13 20:29 UTC, juliemoon approved these changes
This looks great, thanks for getting this done!
<img width="848" alt="Screen Shot 2022-10-13 at 4 29 27 PM" src="https://user-images.githubusercontent.com/16272040/195704201-c7daf540-a9ff-4f2d-b8a8-a333731db822.png">

2022-10-13 20:43 UTC, ruizajtruss submitted a review, later dismissed
Everything is working as intended, nice! 🥳

2022-10-18 16:23 UTC, ruizajtruss commented on src/constants/MoveHistory/EventTemplates/CreateOrders/createOrders.jsx
> +  if ('has_dependents' in newChangedValues) {
Love how readable this is, nice change!

2022-10-18 17:04 UTC, ruizajtruss requested changes

2022-10-18 19:57 UTC, afoon commented on src/constants/MoveHistory/EventTemplates/updateOrders/updateOrder.jsx
> +  eventName: '*',
I think wildcard is used here because multiple event names can match to the same template instead having make a separate one for each.

2022-10-18 20:10 UTC, ruizajtruss commented on src/constants/MoveHistory/EventTemplates/updateOrders/updateOrder.jsx
> +    newChangedValues.has_dependents = newChangedValues.has_dependents ? 'Yes' : 'No';
https://github.com/transcom/mymove/pull/9353#discussion_r998662598

2022-10-18 20:12 UTC, afoon commented on src/constants/MoveHistory/EventTemplates/updateOrders/updateOrder.test.jsx
> +    expect(screen.getByText('Dependents included')).toBeInTheDocument();
**suggestion**: Add a test case to test the value of `has_dependents`

2022-10-19 15:36 UTC, michaelvaldes-truss commented on src/constants/MoveHistory/EventTemplates/updateOrders/updateOrder.test.jsx
> +    expect(screen.getByText('Dependents included')).toBeInTheDocument();
Thanks! I just removed the conversion for the value field, so I think this is no longer necessary; we just expect to display whatever is in the value field.

2022-10-19 15:37 UTC, michaelvaldes-truss commented on src/constants/MoveHistory/EventTemplates/updateOrders/updateOrder.jsx
> +    newChangedValues.has_dependents = newChangedValues.has_dependents ? 'Yes' : 'No';
Fixed! There was an issue with the conversion logic. I just removed it per our requirements discussion.

2022-10-19 15:38 UTC, afoon commented on src/constants/MoveHistory/EventTemplates/updateOrders/updateOrder.test.jsx
> +    expect(screen.getByText('Dependents included')).toBeInTheDocument();
Would it be possible to still have that tested in case the value gets lost in an unrelated change?

2022-10-19 18:00 UTC, ruizajtruss commented on src/constants/MoveHistory/EventTemplates/updateOrders/updateOrder.test.jsx
> +      ['Dependents included', ': false'],
This change is great

2022-10-19 18:01 UTC, ruizajtruss approved these changes

2022-10-19 18:31 UTC, afoon approved these changes
lgtm!

2022-10-19 18:34 UTC, merged