[MB-11224] (User Story) Office users can see creation and updates to the customer profile
transcom/mymove pull request #9360
Opened 2022-10-14 18:07 UTC by afoon

## [Jira ticket](https://dp3.atlassian.net/browse/MB-11224) for this change

## Summary

- [ ] Add createServiceMember template and test
- [ ] Add patchServiceMember template and test
- [ ] Update move fetcher sql to show address and backup contact changes and retrieve duty location context.
- [ ] Consolidate address related move events into two templates

## Setup to Run Your Code

<details>
<summary>💻 You will need to use three separate terminals to test this locally.</summary>

##### Terminal 1

Run client

```sh
make client_run
```

##### Terminal 2

Run server

```sh
make server_run
```

</details>

## Verification Steps for Reviewers

1. Open the Milmove user app and create a new account. 
2. Complete the profile, orders, and shipment sections and submit the form.
3. In the office app, login is as service counselor.
4. Locate the move of the new service member.
5. Go to the move history
     - [ ] `Created profile` move event  is present
     - [ ] `Updated profile` move events representing the following events exist:
          - [ ] Rank and branch
          - [ ] Name
          - [ ] Email and phone number
          - [ ] Duty Location
          - [ ] Current Address
          - [ ]  Backup Address
          - [ ] Backup contact

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#zero-downtime-migrations)
- [ ] Have been communicated to #g-database
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#secure-migrations)

## Screenshots

2022-10-19 16:30 UTC, mmayo-truss commented on pkg/services/query/sql_scripts/move_history_fetcher.sql
> +						NULLIF(
Question: Does it matter if we return an empty context as opposed to null?

2022-10-19 16:39 UTC, kctruss commented on pkg/services/query/sql_scripts/move_history_fetcher.sql
> +						NULLIF(
It looks like we're primarily returning null for context, and since our client application is JS, that shouldn't be a problem. If we were supporting more strongly-typed front end languages, then we'd need to revisit.

2022-10-19 19:36 UTC, kctruss requested changes
Really great work on this, Amina! Aside from some lint errors and merge conflicts, and possibly a couple more files that could be deleted, I think this looks good

2022-10-19 19:36 UTC, kctruss commented on src/constants/MoveHistory/EventTemplates/UpdateAddress/updateAddress.jsx
> +export default {
**question:** Does this mean that `updateMTOShipmentAddresses.js` and `updateMTOShipmentAddresses.test.js` can also be deleted?

2022-10-19 19:36 UTC, kctruss commented on pkg/services/query/sql_scripts/move_history_fetcher.sql
> +					jsonb_build_object('current_duty_location_name', current_duty.name)
**praise:** really solid work on this!

2022-10-19 19:36 UTC, kctruss commented on src/constants/MoveHistory/EventTemplates/patchServiceMember/patchServiceMember.jsx
> +};
**todo:** I'm getting linting errors on this and a few other files because the folder names need to be PascalCase while the file names camelCase.

2022-10-20 14:09 UTC, juliemoon approved these changes
@afoon this looks great! I see the updates being made. I am making a note that the backup contact information is not currently showing up, but that's something that will be added in a separate PR. I am seeing blank rows come up but I also
<img width="1360" alt="Screen Shot 2022-10-20 at 10 05 25 AM" src="https://user-images.githubusercontent.com/16272040/196971892-a2d1bce2-7743-46f4-9fe8-6862e240116b.png">
 believe we have something to address that later down the road.

2022-10-20 14:53 UTC, merged