MB-13330-progear-form-nt
transcom/mymove pull request #9395
Opened 2022-10-18 22:02 UTC by NamibiaTorres

## [Jira ticket](https://dp3.atlassian.net/browse/MB-13330) for this change

##[Figma](https://www.figma.com/file/tRkjtoWjT8727XH5m9k7mK/Milmove-Customer-App?node-id=287%3A604)

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Setup to Run Your Code

<details>
<summary>💻 You will need to use three separate terminals to test this locally.</summary>

##### Terminal 1

Start the Storybook locally.

```sh
make storybook
```

##### Terminal 2

Start the UI locally.

```sh
make client_run
```

##### Terminal 3

Start the Go server locally.

```sh
make server_run
```

</details>

### Additional steps

1. Access the
2. Login as a
3.

## Verification Steps for Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Request review from a member of a different team.
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Frontend

- [ ] User facing changes have been reviewed by design.
- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/master/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
- [ ] There are no new console errors in the browser devtools
- [ ] There are no new console errors in the test output
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

## Screenshots

2022-10-20 14:55 UTC, rileyorr requested changes
Hi @NamibiaTorres! This looks great so far, I just noticed a few things that I outlined below. The feedback is broken up by page section. Please let me know if any of my feedback isn't related to the work for this ticket or if you have any questions. 

Also, here's [a link to the Figma design](https://www.figma.com/file/tRkjtoWjT8727XH5m9k7mK/Milmove-Customer-App?node-id=324%3A1956) in case it's helpful when reviewing feedback

### Interaction feedback
* When I type in one input field it automatically populates the same content in the other input field
    * Referring to ‘Brief description of the pro-gear’ and ‘Shipment’s pro-gear weight’ 

### Pro-gear belongs to
* Label should ask, ‘Who does this pro-gear belong to?’
* Hint text ‘You have to separate yours and your spouse’s pro-gear.’ is missing 

### Brief description of pro-gear
* Can we place the hint text below the input field’s label to match the design? 
    * Components for reference:
        * [MM design system](https://www.figma.com/file/rrga8ccVtYdAx9ZKXz4Gbi/Milmove-Design-System?node-id=1912%3A19348)
        * [USWDS](https://www.figma.com/file/OLdGlFy1XaZBAa7HkHRq71/USWDS-3.0.2-(Figma)?node-id=879%3A8174)
* Space needed between ‘equipment.’ And ‘Check’ 
    * Content: Examples of pro-gear includes specialized apparel and government issued equipment. Check the Joint Travel Regulations (JTR) for examples of pro-gear.
* Input field should be longer length
    * I previously had it at a fixed weight of 356 px - apologies for that. The description input field can be full width (ex. same as the address component inputs).

### Weight
* Hint text ‘Your maximum allowance is X,XXX lbs.’ should be below the input field’s label ‘Shipment’s pro-gear weight’ if possible (refer to Brief description of pro-gear section for more info) 
* Input field is missing the ‘lbs’ suffix 

#### Unchecked checkbox
* There’s an extra ‘Upload your pro-gear’s weight tickets’ above the weight ticket upload label

#### Checked checkbox
* Does this ticket include linking to the weight estimator spreadsheet? 
    * If yes, the ‘Go to Download Page’ button should link here: https://www.ustranscom.mil/dp3/weightestimator.cfm 

I'm happy to pair on any of these changes if that's helpful!

2022-10-20 16:44 UTC, NamibiaTorres commented
Thanks @rileyorr! The outline makes your feedback super easy to read. 

> Hi @NamibiaTorres! This looks great so far, I just noticed a few things that I outlined below. The feedback is broken up by page section. Please let me know if any of my feedback isn't related to the work for this ticket or if you have any questions.
> 
> Also, here's [a link to the Figma design](https://www.figma.com/file/tRkjtoWjT8727XH5m9k7mK/Milmove-Customer-App?node-id=324%3A1956) in case it's helpful when reviewing feedback
> 
> ### Interaction feedback
> * When I type in one input field it automatically populates the same content in the other input field

That's definitely a bug. I'll work on it.

>   
>   * Referring to ‘Brief description of the pro-gear’ and ‘Shipment’s pro-gear weight’
> 
> ### Pro-gear belongs to
> * Label should ask, ‘Who does this pro-gear belong to?’
> * Hint text ‘You have to separate yours and your spouse’s pro-gear.’ is missing
Will add this in. I worked on the second half (after the radio buttons, but it's not a heavy lift to fix this part too).
> 
> ### Brief description of pro-gear
> * Can we place the hint text below the input field’s label to match the design?
Yes, I think I was looking at an older design before.
>   * Components for reference:
>     
>     * [MM design system](https://www.figma.com/file/rrga8ccVtYdAx9ZKXz4Gbi/Milmove-Design-System?node-id=1912%3A19348)
>     * [USWDS](https://www.figma.com/file/OLdGlFy1XaZBAa7HkHRq71/USWDS-3.0.2-(Figma)?node-id=879%3A8174)
> * Space needed between ‘equipment.’ And ‘Check’
>   
>   * Content: Examples of pro-gear includes specialized apparel and government issued equipment. Check the Joint Travel Regulations (JTR) for examples of pro-gear.
> * Input field should be longer length
>   
>   * I previously had it at a fixed weight of 356 px - apologies for that. The description input field can be full width (ex. same as the address component inputs).
I'll look at the address component. Any chance you can specify how long it's supposed to be in Figma?
> ### Weight
> * Hint text ‘Your maximum allowance is X,XXX lbs.’ should be below the input field’s label ‘Shipment’s pro-gear weight’ if possible (refer to Brief description of pro-gear section for more info)
> * Input field is missing the ‘lbs’ suffix
I'll add that in.
> #### Unchecked checkbox
> * There’s an extra ‘Upload your pro-gear’s weight tickets’ above the weight ticket upload label
Yup, I see that now. I added a minor change yesterday that added that in. 
> #### Checked checkbox
> * Does this ticket include linking to the weight estimator spreadsheet?
>   
>   * If yes, the ‘Go to Download Page’ button should link here: https://www.ustranscom.mil/dp3/weightestimator.cfm
Sure, I can add the link in. I just hadn't if it wasn't already in the Figma.
> I'm happy to pair on any of these changes if that's helpful!

2022-10-20 21:34 UTC, NamibiaTorres commented
> Hi @NamibiaTorres! This looks great so far, I just noticed a few things that I outlined below. The feedback is broken up by page section. Please let me know if any of my feedback isn't related to the work for this ticket or if you have any questions.

Hi @rileyorr, I was looking through some other form examples and saw that the Hint text has previously been displayed underneath the text box. Attaching some examples. Is there a new way of displaying hint texts (what's in the Figma file)? Just wondering because the Figma for Expenses doesn't match what we currently have and I will make a new ticket if it needs to be different. 
![Screen Shot 2022-10-20 at 2 00 09 PM](https://user-images.githubusercontent.com/17951554/197063256-092216c9-d0aa-4171-9839-4f1938a59d2b.png)
![Screen Shot 2022-10-20 at 2 10 31 PM](https://user-images.githubusercontent.com/17951554/197063307-a96d14a8-acad-4002-ae56-1aee84428fdd.png)

2022-10-21 16:23 UTC, rileyorr commented
> Hi @rileyorr, I was looking through some other form examples and saw that the Hint text has previously been displayed underneath the text box. Attaching some examples. Is there a new way of displaying hint texts (what's in the Figma file)? Just wondering because the Figma for Expenses doesn't match what we currently have and I will make a new ticket if it needs to be different.

@NamibiaTorres thank you for pointing this out and providing examples! I noticed this as well, but the MM Design system and USWDS components both use hint text above the input field/below the input label. I previously chatted with the design team about the hint text styling as I was updating these designs and folks reacted positively to moving the hint text. I believe moving the hint text improves the content's hierarchical flow and is more accessible as the implementation in your example screenshots would result in screen readers only reading the hint text below the input field after the user has focused on the input field. 

How big of a lift is readjusting the already implemented hint text styling? I'm going to review the PPM designs to readjust the hint text styling so we won't have future rework.

2022-10-24 19:54 UTC, rileyorr commented
@NamibiaTorres thanks for incorporating those changes! I took another look and just found a couple things: 

### General UI styling
* Can the padding between the input field’s label and hint text be updated to 4px to match the mockup? It's currently set to 16px.
* There’s an extra 7.95px margin below ‘Your maximum allowance is X,XXX lbs.’ 

### Brief description of the pro-gear 

* Input field should be longer length
    * It should be full length with consideration of the container’s inherent padding. This will help prevent text from being cut off.
        * Similar to the input fields in the address components used in the app. 

I added a screenshot of the input field with one of the hint text's pro-gear examples for reference: 

<img width="515" alt="Screen Shot 2022-10-24 at 3 48 09 PM" src="https://user-images.githubusercontent.com/46329147/197613489-ef93321b-db77-4b20-b70a-8f18eeb970b5.png">


### Weight

* When I select ‘Go to Download Page’ for the constructed weight spreadsheet it redirects me back to the PPM Homepage 
* Duncan notified me that the content for the constructed weight spreadsheet upload should be updated since the spreadsheet is XLS or XLSX only. The design is now updated with the following content:
    * XLS or XLSX only. Maximum file size 25 MB.

Screenshot of updated content for reference: 
![Screen Shot 2022-10-24 at 3 51 35 PM](https://user-images.githubusercontent.com/46329147/197614662-ee599403-6fcd-4a36-9036-4f12fc96e9e6.png)

Please let me know if you have any questions!

2022-10-24 20:51 UTC, duncan-truss commented on src/components/Customer/PPM/Closeout/ProGearForm/ProGearForm.jsx
> +                  {values.selfProGear === 'true' && (
I think we want to render the same fields regardless of who the pro-gear belongs to so one option is to make this `values.selfProGear === 'true' || values.selfProGear === 'false'` so once either value is selected it gets shown.

2022-10-24 20:53 UTC, duncan-truss commented on src/components/Customer/PPM/Closeout/ProGearForm/ProGearForm.jsx
> +                            Examples of pro-gear includes specialized apparel and government issued equiptment. Check
Small typo in `equiptment`, in Figma and Zeplin they have a copy content button that you can use.  I know I'm always worried I'm gonna misspell something.

2022-10-24 21:06 UTC, duncan-truss commented on src/components/Customer/PPM/Closeout/ProGearForm/ProGearForm.jsx
>    },
I would remove setting defaults for the proGear object here and if you still want defaults set them in the Formik initialValues as the single source of truth.  I think the idea is that neither radio button is selected if it's a new pro-gear weight ticket item.  You can set the value to the empty string if the value is undefined, else use the existing value.

2022-10-24 21:42 UTC, NamibiaTorres commented on src/components/Customer/PPM/Closeout/ProGearForm/ProGearForm.jsx
> +                            Examples of pro-gear includes specialized apparel and government issued equiptment. Check
Thanks! I didn't realize there was that option.

2022-10-24 23:24 UTC, NamibiaTorres commented on src/components/Customer/PPM/Closeout/ProGearForm/ProGearForm.jsx
> +                          <Button className={ppmStyles.backButton} type="button" onClick={onBack} secondary outline>
Thanks, I noticed that I actually have this in a constant in the new WeightTicketUpload.jsx. How do I important that constant so that I can call it in my form?

2022-10-25 14:26 UTC, rileyorr commented
> I know it's styled to look like a button which is a bit confusing but it semantically behaves like a plain link.

I 100% agree that it should be a plain link rather than a link styled as a button. This is the pattern in the weight tickets section of the flow so I followed the same pattern for consistency. I'll write myself a ticket to revisit that part of the design and we can update it in the future - seems like a quick win for accessibility compliance!

2022-10-26 17:31 UTC, rileyorr approved these changes
LGTM! Thanks for all your work incorporating my feedback and the collaboration efforts! 

Also, I reviewed the Happo changes.

2022-10-28 21:39 UTC, NamibiaTorres commented on src/components/Customer/PPM/Closeout/ProGearForm/ProGearForm.jsx
>    },
I ended up changing this back to the original default value because some of @scottmries 's tests were failing. That brought up a question for me: @scottmries was the defaultProps set here because this form wasn't integrated to the BE yet?

2022-10-31 14:14 UTC, duncan-truss commented on src/components/Customer/PPM/Closeout/ProGearForm/ProGearForm.jsx
> +  const initialValues = {
Description needs to be added here as well so that when we're editing an existing pro-gear record instead of creating a new one we'll see the value pre-filled.

2022-10-31 14:40 UTC, duncan-truss commented on src/components/Customer/PPM/Closeout/ProGearForm/ProGearForm.jsx
> +                    <legend className="usa-label margin-bottom-0">Who does this pro-gear belongs to?</legend>
We try to avoid adding styles manually into the component html like this `margin-bottom-0` when we could define it in the ProGearForm.module.scss.

You could rewrite this in the scss file to something like:

.ProGearForm {
...

legend:global(.usa-label) {
    @include u-margin-bottom(0);
}

...
}

The `:global()` tag means it shouldn't rewrite the class name to be unique because we are using the global `usa-label` and not `styles.usa-label` that would generate something unique like ProGear_usa-label_a1B2c

2022-10-31 14:46 UTC, duncan-truss commented on src/components/Customer/PPM/Closeout/ProGearForm/ProGearForm.module.scss
> +    display: inline-block;
Can we remove this rule?  It is causing the form to be less than the width of the container because inline elements don't expand to take up the full width of their containers.  It only expands after the first question is answered.

<img width="658" alt="Screen Shot 2022-10-31 at 10 42 21 AM" src="https://user-images.githubusercontent.com/52669884/199035997-4e4a702a-fd67-41e4-849e-f6ab12f9f3f8.png">

2022-10-31 15:08 UTC, duncan-truss commented on src/components/Customer/PPM/Closeout/ProGearForm/ProGearForm.jsx
>    },
I think you have changed this back to null in the PR that I am seeing so it's outdated.  Generally we don't need to set anything explicitly to null because in Javascript we often treat null and undefined similarly.  I would just set proGear to `undefined` in the defaultProps object seeing as you have logic elsewhere in the component to assign the initialValue.

We could even make proGear required eventually because we usually have the page component wait until either the record gets created in the api or we load the existing record from the id in the URL.  You can see this in the WeightTickets page component where we display a loading placeholder until that data is ready https://github.com/transcom/mymove/blob/101df4f3ef1c288bd6bbca308833377c7138508a/src/pages/MyMove/PPM/Closeout/WeightTickets/WeightTickets.jsx#L138-L140

2022-10-31 19:32 UTC, NamibiaTorres commented on src/components/Customer/PPM/Closeout/ProGearForm/ProGearForm.module.scss
> +    display: inline-block;
Hi Duncan, unfortunately if I remove it gets overridden by a rule set in `PPM.module.scss`. Perhaps we can pair to find a better solution?

2022-11-02 18:02 UTC, merged