[DRAFT][MB-13792] Evaluation Report subcomponents rename
transcom/mymove pull request #9559
Opened 2022-11-09 15:19 UTC by SirenaBorracha

## [Jira ticket](https://dp3.atlassian.net/browse/MB-13792) for this change

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Setup to Run Your Code

<details>
<summary>💻 You will need to use three separate terminals to test this locally.</summary>

##### Terminal 1

Start the Storybook locally.

```sh
make storybook
```

##### Terminal 2

Start the UI locally.

```sh
make client_run
```

##### Terminal 3

Start the Go server locally.

```sh
make server_run
```

</details>

### Additional steps

1. Access the
2. Login as a
3.

## Verification Steps for Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Request review from a member of a different team.
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Frontend

- [ ] User facing changes have been reviewed by design.
- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/main/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
- [ ] There are no new console errors in the browser devtools
- [ ] There are no new console errors in the test output
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide#logging)
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide/#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#zero-downtime-migrations)
- [ ] Have been communicated to #g-database
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#secure-migrations)

## Screenshots

2022-11-22 18:03 UTC, mandaem reviewed
<img width="1367" alt="Screenshot 2022-11-22 at 1 00 55 PM" src="https://user-images.githubusercontent.com/108361430/203387959-bf943dc9-250f-4cb7-ae7e-00184ee33411.png">
There are some styling issues on the reports page.

2022-11-22 18:55 UTC, PDickeyTruss commented on src/components/Office/QAEReportTable/QAEReportTable.module.scss
> -.evaluationReportTable {
Looks like this is the line that is causing the styling issues. In the QAEReportTable component this is still 'evaluationReportTable' so this style is not getting used.

2022-11-22 18:55 UTC, PDickeyTruss commented on src/components/Office/QAEReportTable/QAEReportTable.module.scss
> -.evaluationReportTable {
See line 167 of QAEReportTable for the mismatch: `<table className={styles.evaluationReportTable}>`

2022-11-22 19:00 UTC, PDickeyTruss requested changes
Looking good, very nice naming cleanup. Makes it a bit easier to navigate the QAE fiels than before this PR.

Marking as 'Request changes' for the small 1-line styling fix. On standby to approve when fixed 🎉

2022-11-22 22:06 UTC, PDickeyTruss approved these changes
LGTM! Styling fixed and renaming still solid 🎉

2022-11-28 17:59 UTC, dinabeigelman approved these changes
Assuming there are no visual/UI changes - this looks good!

2022-11-28 18:12 UTC, merged