create tabs and routing for SC queue
transcom/mymove pull request #9597
Opened 2022-11-15 18:18 UTC by mandaem

## [Jira ticket](tbd) for this change

## Summary

Is there anything you would like reviewers to give additional scrutiny?

[this article](tbd) explains more about the approach used.

## Setup to Run Your Code

<details>
<summary>💻 You will need to use three separate terminals to test this locally.</summary>

##### Terminal 1

Start the Storybook locally.

```sh
make storybook
```

##### Terminal 2

Start the UI locally.

```sh
make client_run
```

##### Terminal 3

Start the Go server locally.

```sh
make server_run
```

</details>

### Additional steps

1. Access the
2. Login as a
3.

## Verification Steps for Author

These are to be checked by the author.

- [ ] Tested in the Experimental environment (for changes to containers, app startup, or connection to data stores)
- [ ] Request review from a member of a different team.
- [ ] Have the Jira acceptance criteria been met for this change?

## Verification Steps for Reviewers

These are to be checked by a reviewer.

### Frontend

- [ ] User facing changes have been reviewed by design.
- [ ] There are no aXe warnings for UI.
- [ ] This works in [Supported Browsers and their phone views](https://github.com/transcom/mymove/tree/main/docs/adr/0016-Browser-Support.md) (Chrome, Firefox, IE, Edge).
- [ ] There are no new console errors in the browser devtools
- [ ] There are no new console errors in the test output
- [ ] If this PR adds a new component to Storybook, it ensures the component is fully responsive, OR if it is intentionally not, a wrapping div using the `officeApp` class or custom `min-width` styling is used to hide any states the would not be visible to the user.

### Backend

- [ ] Code follows the guidelines for [Logging](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide#logging)
- [ ] The requirements listed in [Querying the Database Safely](https://transcom.github.io/mymove-docs/docs/dev/contributing/backend/Backend-Programming-Guide/#querying-the-database-safely) have been satisfied.

### Database

#### Any new migrations/schema changes:

- [ ] Follows our guidelines for [Zero-Downtime Deploys](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#zero-downtime-migrations)
- [ ] Have been communicated to #g-database
- [ ] Secure migrations have been tested following the instructions in our [docs](https://transcom.github.io/mymove-docs/docs/dev/contributing/database/Database-Migrations#secure-migrations)

## Screenshots

2022-11-21 16:04 UTC, PDickeyTruss commented on src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
> +        <Route path={servicesCounselingRoutes.QUEUE_COUNSELING_PATH}>
Should  the second two `Route` component have the `exact` prop like the first one here does?

2022-11-21 16:14 UTC, PDickeyTruss commented on src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
> +            useQueries={useServicesCounselingQueuePPMQueries}
Would be great to [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) this out a bit, I see most of these props are redundant for all 3 TableQueue flavors here. Should help to both reduce duplication and make it easer to tell at a glance what is different between there three TableQueues.  I am not exactly sure what props are common/differ but from a quick look it seems like almost all of them:

```
const commonProps =  {
    showTabs
     showFilters
     showPagination
     manualSortBy
     defaultCanSort
     defaultSortedColumns={[{ id: 'submittedAt', desc: false }]}
     disableMultiSort
     disableSortBy={false}
     columns={columns()}
      title="Moves"
     handleClick={handleClick}
}

<Switch>
    <Route path={servicesCounselingRoutes.QUEUE_CLOSEOUT_PATH} exact>
        <TableQueue {...commonProps} useQueries={useServicesCounselingQueuePPMQueries} />
    </Route>
    <Route path={servicesCounselingRoutes.QUEUE_COUNSELING_PATH}>
        <TableQueue {...commonProps} useQueries={useServicesCounselingQueueQueries} />
    </Route>
    <Route path={servicesCounselingRoutes.QUEUE_COUNSELING_PATH}>
        <TableQueue {...commonProps} useQueries={useServicesCounselingQueueQueries} />
    </Route>
</Switch>
```

2022-11-21 16:16 UTC, PDickeyTruss commented on src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
> +        </Route>
I do not see any difference between this TableQueue and the one directly before it. If they are the same, we could simplify this by just doing two paths in one route:
```
<Route path={[servicesCounselingRoutes.QUEUE_COUNSELING_PATH, servicesCounselingRoutes.DEFAULT_QUEUE_PATH}]}>
```

2022-11-21 16:35 UTC, mandaem commented on src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
> +        </Route>
modified, thanks for this!

2022-11-21 16:38 UTC, mandaem commented on src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
> +            useQueries={useServicesCounselingQueuePPMQueries}
Thanks, there are some upcoming changes where I believe there _might_ be more differences b/t ppm one and the others. I do agree it's not DRY but I think it might leave for now until those next tasks are done.

2022-11-21 17:40 UTC, mandaem commented on src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.jsx
> +        <Route path={servicesCounselingRoutes.QUEUE_COUNSELING_PATH}>
modified, thanks for this!

2022-11-22 18:42 UTC, dinabeigelman approved these changes

2022-11-22 18:55 UTC, dinabeigelman requested changes
i dont know how to remove the approval (would like to review once logic/math is up and running) so i added request changes until it's final/no longer in wip

2022-11-29 00:38 UTC, dinabeigelman reviewed
Took a look and noticed a few things:
* The PPM Closeout tab should capitalized "Closeout"
* When switching between the two tabs, it appears that some of the columns are different widths. It's hard for me to pinpoint which. Not sure how much of an issue this is given that the columns will change in the near future. It's prob be ok to revisit this once we have the final columns in place. 
* I noticed that when you apply a filter/search to a column, that filter/search is maintained when you switch tabs. Calling this out as I don't know if this is the behavior we want but it was never defined anywhere. I'll investigate on this and report back. Ok to leave as is for now.

2022-11-29 15:10 UTC, mandaem commented
@dinabeigelman 

> * The PPM Closeout tab should capitalize "Closeout"
This has been changed and I saw the latest conversation with Bo about the others. Please review the capital change.

2022-11-29 19:22 UTC, dinabeigelman approved these changes
@mandaem looks good! 🎉

2022-11-30 16:49 UTC, Ryan-Koch approved these changes

2022-11-30 17:23 UTC, PDickeyTruss commented on src/components/Table/TableQueue.module.scss
> +  border-bottom: (2px solid rgb(236, 234, 234));
No blocking suggestion: I suspect this color is already in our common colors file [here](https://github.com/transcom/mymove/blob/4ecd1b9c6f5e92e19d02b64578038e7493d27f54/src/shared/styles/colors.scss). Perhaps we could use do something like the below to prevent having a one-off color here. 
```
border-bottom: 2px solid $border-color;
```

2022-11-30 17:26 UTC, PDickeyTruss commented on src/pages/Office/ServicesCounselingQueue/ServicesCounselingQueue.module.scss
> +  border: (1px, solid, green);
Not blocking suggestion: Same as my above comment, I wonder if there is a common color here in our colors file we could use. If this is truly a new color to the app we may want to add it to the colors file so we don't have one-off colors in scss modules.

2022-11-30 19:05 UTC, mandaem commented on src/components/Table/TableQueue.module.scss
> +  border-bottom: (2px solid rgb(236, 234, 234));
thanks for this info :)

2022-12-01 18:08 UTC, merged